### ISSUE TITLE
Sylius request hangs on "admin/ajax/get-version"

### ISSUE THREAD

**Issue by mezoni** [Sylius/Sylius#10006]
Version 1.3.5.
All site did not respond and waits response from "admin/ajax/get-version".
![0](https://user-images.githubusercontent.com/2311549/49568661-75472a00-f953-11e8-92eb-abc13a063f5a.jpg)

**Comment by antimail** [comment]
A similar situation, my provider (I am from Russia) blocks by IP http://gus.sylius.com/version . At this address is the request version of Sylius.
I added gus.sylius.com to hosts 127.0.0.1. Although there should be a more elegant solution.

**Comment by stefandoorn** [comment]
https://docs.sylius.com/en/1.3/cookbook/configuration/disabling-admin-notifications.html

**Comment by Zales0123** [comment]
@mezoni have you tried the solution provided by @stefandoorn? Can this issue be closed? :)
