### ISSUE TITLE
[Feature] Forcing the user to enter a new password when they are changed from the administration

### ISSUE THREAD

**Issue by Chrysweel** [Sylius/Sylius#10000]
Sometimes a customer calls the ecommerce administrator, and for multiple reasons you have to set the password from the administration panel. (the client has forgotten the password, you have had to change an email for another ...)

I do it from:
```
administration/customers/140108/edit
route: sylius_admin_customer_update
```

Many web pages, force you to enter a new password the next time you enter, to make it a secure password.

I propose the following solution:
When you edit a client, when changing the password, there is an option that is "force new password". And if that option is checked, the customer when he returns to enter the ecommerce will see a warning that tells him to enter a more secure password.

**Comment by mamazu** [comment]
Why should the customer not use the reset password link on the store? This basically does the same thing.

**Comment by Chrysweel** [comment]
Very easy!

A user calls ecommerce. The client says he can not access, 80% of the time the reason is that he does not remember a password.

1) As an administrator, you enter the administration and put a password 1234
2) The user logs in correctly and you help him buy by phone.

Purchase made! $$

If the client has to reset the password ...
1) You tell him to go to the login page. Click on the "remember password" button
2) On the remember password page..you must write your email
3) You must open your email
4) Click on the email, go to your ecommerce and enter a new password
5) Log in with the new password ...
6) The user logs in correctly and you help him buy by phone.

If the user has not fallen in the process and has managed to do all the steps ... purchase made !! $$

In an ecommerce the important thing is that the user buys ... and customer service is very important.

**Comment by Zales0123** [comment]
The idea is nice, but I don't think we would like to have such a specific case in the Sylius Core. At least for now :) Maybe it would be nice to create a simple plugin with such a feature?

Offtopic: congratulations for catching #10000 😄

**Comment by Chrysweel** [comment]
It seems a minor problem. But it is an important case of usability and management of an ecommerce. If we want Sylius to be a real alternative to prestashop or magento, details like these make the community have more reasons to use sylius before another alternative ...

I think it's something that should be included in the core of Sylius. What is your opinion?
