### ISSUE TITLE
[QUESTION] Hotel Booking System

### ISSUE THREAD

**Issue by nckenn** [Sylius/Sylius#10010]
Hi guys, just want to ask question, is it possible to make a online hotel booking system using this framework? if yes, can i see your work. thanks in advance.

**Comment by Zales0123** [comment]
Hello, Yoh! :) Sylius tries to be as customizable and extendable as it's possible. You can do plenty of things with our codebase, including adjusting it to very specific cases (like a hotel booking system, for example).
However, **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. I strongly encourage you to use our [Slack](https://sylius.com/slack) - we have a very active, developed community, I'm sure someone will be able to help you with your transferring your idea into a great application :) Good luck!

**Comment by nckenn** [comment]
> Hello, Yoh! :) Sylius tries to be as customizable and extendable as it's possible. You can do plenty of things with our codebase, including adjusting it to very specific cases (like a hotel booking system, for example).
> However, **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. I strongly encourage you to use our [Slack](https://sylius.com/slack) - we have a very active, developed community, I'm sure someone will be able to help you with your transferring your idea into a great application :) Good luck!

sorry buddy, thank you anyway 👍 appreciated.
