### ISSUE TITLE
Taxons are not loading in admin

### ISSUE THREAD

**Issue by KirbyFox** [Sylius/Sylius#10019]
Sylius version affected: 1.3.5

Description:

Edit a product and go to the 'Taxonomy' tab. 

The animated GIF spins and in the browser console, it says API: No URL specified for api event. 

This issue seems to have been introduced with version 1.3.5 of Sylius, as it worked perfectly before.

**Comment by Zales0123** [comment]
Hello @KirbyFox, I've just checked that on the fresh `1.3` and it works for me :( Could you share some more details, maybe screenshots or sth? Thanks!

**Comment by KirbyFox** [comment]
At least one other user is experiencing the same problem - https://stackoverflow.com/questions/53214368/sylius-not-loading-taxons-on-product-edit

**Comment by KirbyFox** [comment]
Thanks everyone. It was an out of date app.js file.

**Comment by Vimal6617** [comment]
We are also facing the same issue and we are using 1.3.6 , can someone provide the details of the app.js file which needs to be updated as per the comment from @KirbyFox
