### ISSUE TITLE
Symfony 4.2 support

### ISSUE THREAD

**Issue by Zales0123** [Sylius/Sylius#10015]
During fixing our build (https://github.com/Sylius/Sylius/pull/10014), I've realized that we should think about updating supported Symfony version to 4.2. Looking at these versions official roadmap (https://symfony.com/roadmap/4.1 and https://symfony.com/roadmap/4.2), the maintenance of **Symfony 4.1** end in January '19. On the other hand, **Symfony 4.2** has just been released this month, and will be maintained until July '19.

I really believe we should discuss such changes with our community, to avoid frustration and disappointment as with [PHP version update](https://github.com/Sylius/Sylius/issues/9838) (not being malicious, just empathic :)).

**Comment by Roshyo** [comment]
The disappointment with PHP Version was not because of PHP 7.2 support, but because of PHP 7.1 drop without any obvious reason. As long as Symfony 4.1 is still supported, I believe noone will be disappointed with Symfony 4.2 support.
I also think Symfony 4.1 should be supported actively at least untill end January, and left in supported versions as long as there is no obvious incompatibility.

**Comment by stefandoorn** [comment]
Agree with @Roshyo :-) Obviously project needs to move forward and can't support things forever (also takes time), but e.g. not restricting it would already be a great help. Community can also help on keeping things compatible in case we (for whatever reason) cannot update yet to the latest version. Therefore I also hope S3.4 & PHP7.1 will be allowed for a while, even though if the mainline product moves forward.

**Comment by liverbool** [comment]
@pamil did you see this https://github.com/symfony/symfony/issues/29637

**Comment by pamil** [comment]
Solved by #10067.

**Comment by liverbool** [comment]
@pamil i think this is not solve https://github.com/symfony/symfony/issues/29637 because the Sylius kernel was not used in my app.

**Comment by pamil** [comment]
@liverbool could you open a separate issue for that (as it also happens with symfony/dependency-injection 4.1.8) and it's not connected with Symfony 4.2 support directly?
