### ISSUE TITLE
Type error: Return value of Sylius\Component\Core\Model\Channel::getLocales() must implement interface Doctrine\Common\Collections\Collection, null returned

### ISSUE THREAD

**Issue by atamaniuc** [Sylius/Sylius#10027]
**Sylius version affected**: 1.1.0

**Description**  
`Type error: Return value of Sylius\Component\Core\Model\Channel::getLocales() must implement interface Doctrine\Common\Collections\Collection, null returned`. 

**Steps to reproduce**  
Set environment variable `VAGRANT=VAGRANT` for using `/dev/shm` for **cache** and **logs**.
Same stale issue: [https://github.com/Sylius/Sylius/issues/8963](https://github.com/Sylius/Sylius/issues/8963)

**Possible Solution**  
```
//docker-compose.yml
build:
  context: .
  shm_size: '2gb'
```

**Comment by Zales0123** [comment]
Hello @atamaniuc, sadly we don't support Sylius 1.1 anymore (except security issues). Can you update your Sylius version and see if the problem still occurs? Btw, if it's connected somehow with Sylius Vagrant or Docker setup, you should open this issue for a proper repository (https://github.com/Sylius/Sylius-Standard/tree/master/docker, https://github.com/Sylius/Vagrant/).
