### ISSUE TITLE
Product Save action in admin panel doesn't show bubbled errors

### ISSUE THREAD

**Issue by aario** [Sylius/Sylius#10031]
**Sylius version affected**: 1.3.5

**Description**  
Trying to disable the product is not possible as the admin panel silently dies without saving the changes.
Debugging the code it is apparent from:
	vendor/symfony/form/Form.php:getErrors
That the form has various errors but they are not visible as bubble messages.

**Steps to reproduce**  
Go to one of sample products, click enabled to mark it as disabled. Click save changes.

**Possible Solution**  
Debugging the code to see which attribute is causing the error, then looking the value of that attribute in each channels and setting something for it to not be empty. Then saving the product.

**Comment by Prometee** [comment]
I don't know if it could help you but I made this changes to `@SyliusUi/Form/theme.html.twig` :

```
{% extends '@!SyliusUi/Form/theme.html.twig' %}

{%- block form_errors -%}
    {%- if errors|length > 0 -%}
        {%- for error in errors -%}
            <div class="ui red{% if form.parent is not empty %} pointing label{% else %} error message{% endif %} sylius-validation-error"{% if form.parent is empty %} style="margin-bottom: 10px;"{% endif %}>
                {% if form.parent is empty %}
                <i class="large circular exclamation triangle icon"></i>
                {% endif %}
                {{ error.message }}
            </div>
        {%- endfor -%}
    {%- endif -%}
{%- endblock form_errors -%}

{%- block form_start -%}
    {% if not form.vars.valid %}
        {% set attr = attr|merge({'class': (attr.class|default('') ~ ' error')|trim}) %}
    {% endif %}
    {{ parent() }}
{%- endblock form_start -%}
```

If you use `'error_bubbling' => true` in a `FormType` it will display those silently dismissed errors.

**Comment by aario** [comment]
> I don't know if it could help you but I made this changes to `@SyliusUi/Form/theme.html.twig` :
> 
> ```
> {% extends '@!SyliusUi/Form/theme.html.twig' %}
> 
> {%- block form_errors -%}
>     {%- if errors|length > 0 -%}
>         {%- for error in errors -%}
>             <div class="ui red{% if form.parent is not empty %} pointing label{% else %} error message{% endif %} sylius-validation-error"{% if form.parent is empty %} style="margin-bottom: 10px;"{% endif %}>
>                 {% if form.parent is empty %}
>                 <i class="large circular exclamation triangle icon"></i>
>                 {% endif %}
>                 {{ error.message }}
>             </div>
>         {%- endfor -%}
>     {%- endif -%}
> {%- endblock form_errors -%}
> 
> {%- block form_start -%}
>     {% if not form.vars.valid %}
>         {% set attr = attr|merge({'class': (attr.class|default('') ~ ' error')|trim}) %}
>     {% endif %}
>     {{ parent() }}
> {%- endblock form_start -%}
> ```
> 
> If you use `'error_bubbling' => true` in a `FormType` it will display those silently dismissed errors.

Now we need a brave hero to sacrifice a weekend and make a pull request out of that.

**Comment by Prometee** [comment]
I will, but it's easy to make it also by your own ;)
