### ISSUE TITLE
Default path for sorting product is wrong

### ISSUE THREAD

**Issue by filipcro** [Sylius/Sylius#10051]
**Sylius version affected**: 1.3

**Description**  
On products page, you can't change back to default sorting (sort by position) after choosing another sorting method.

**Steps to reproduce**  
1. Go to: `{localhost}/taxons/{slug}/`
2. Click on Sort by from A to Z
3. Try to sort it again by position.

It won't work, it will still be sorted from A to Z.

**Possible Solution**  
I'll send a pull request.

**Comment by filipcro** [comment]
Submitted #10053

**Comment by pamil** [comment]
Fixed by #10053.
