### ISSUE TITLE
Travis Marking Builds as Passed Despite Behat Failures

### ISSUE THREAD

**Issue by astorm** [Sylius/Sylius#10057]
**Sylius version affected**: 1.3.x (I think?  Too new to the project to say for sure)

**Description**  
I've been trying to get tests up on running on my local machine (this is context, not the issue I'm wrirint about), and I noticed something strange.  Travis marked the following test run as passed

> https://travis-ci.org/Sylius/Sylius/jobs/472684295

Despite that run having a behat error

![screen shot 2018-12-29 at 3 49 44 pm](https://user-images.githubusercontent.com/184372/50543085-7699fa00-0b81-11e9-9bc1-8c1be36cfda3.png)

I'm not familiar enough with the project or your test harness to know if this is a real problem or not, but it seemed worth mentioning somewhere.  I hope this is an OK place for it :)
**Steps to reproduce**  
1. Open https://travis-ci.org/Sylius/Sylius/jobs/472684295
2. Noticed the build has passed
3. Scroll to line 1828
4. Notice test failure
5. A naive understanding of the role of travis is to fail if behat tests fail

**Possible Solution**  
I don't really know -- see "too new to this platform" messaging all over this report :)  

However, in your slack support room someone seems to think there's a bug in your test harness where you'll only fail if the last test fails

https://sylius-devs.slack.com/archives/C3EGDG9LY/p1546104682079100?thread_ts=1546054164.077000&cid=C3EGDG9LY

I have no idea how true that is or not.

**Comment by stefandoorn** [comment]
@astorm The Behat setup is done in such way that failed scenario's are being retried once. It seems (also when developing my plugins) that sometimes they fail for unclear reasons (timeout, memory thingie, whatever.. - actually for me totally unclear whats the reason) so they get retried. 

First command: `vendor/bin/behat --strict --no-interaction -vvv -f progress -p cached --tags="@javascript && ~@todo && ~@cli"`

Second command: `vendor/bin/behat --strict --no-interaction -vvv -f progress -p cached --tags="@javascript && ~@todo && ~@cli" --rerun` (line 1883)

The second one passed and that makes all green in this case. 

Regarding 'However, in your slack support room someone seems to think there's a bug in your test harness where you'll only fail if the last test fails', not sure whether that's the case. Can't really find a proper example of one failing on PHPUnit tests for instance.. Probably @pamil knows this best.

**Comment by astorm** [comment]
@stefandoorn ah ha!  Thank you, I didn't know that 1. Behat had a rerun feature or that 2. The Sylius suites were using it.  Closing as _Not A Bug_ -- thank you for taking the time to explain that for me!

**Comment by mamazu** [comment]
The someone from slack here. :D Well, I am not that good in bash but wouldn't it make more sense to use an and operator for this line.
https://github.com/Sylius/Sylius/blob/9264c823b4e8635e417d24b317583a14f5a4eeda/etc/travis/suites/application/script.sh#L24
Because currently it is just setting the code of the script whatever it was before.
