### ISSUE TITLE
Spam protection on contact form

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#10060]
Currently there is not really an anti-spam solution on the out of the box contact form solution provided by Sylius. Although the content is only sent via email to the shop owner, in one of my projects the email hosting provider flagged the account as sending spam and therefore suspended the whole account. This breaks the checkout flow as the confirmation email is sent before reaching the payment provider, so the client never reach the payment page. This is an issue by itself (email should be handled on the background e.g.), but not related to the contact form.

Something like Recaptcha would probably be good. It's probably not hard to implement myself, but it's likely others are running into the same issues sooner or later.

**Comment by Prometee** [comment]
I agree with you, maybe a Google ReCaptcha Sylius Plugin can be built to add security points on Contact form, Register form and Login form*s*.

**Comment by stefandoorn** [comment]
WIP: https://github.com/stefandoorn/SyliusRecaptchaPlugin. It works in a production project on the contact form for now. Needs tests etc., but I needed something quick :-)

**Comment by mohamedyasser** [comment]
what about this bundle 
[https://github.com/core23/AntiSpamBundle](url)
with Recaptcha @stefandoorn
