### ISSUE TITLE
Form type Extension getExtendedType() id @deprecated since Symfony4.2 

### ISSUE THREAD

**Issue by featuriz** [Sylius/Sylius#10071]
**Sylius docs version**: 1.3

**Description**
<!-- Describe what is missing or where exactly is the bug/typo/issue located. Links highly appreciated. --!>

2.1.2 Customizing Forms
2. Create a Form Extension.

```
public function getExtendedType(): string
{
     return CustomerProfileType::class;
}
```

this is
`@deprecated since Symfony 4.2, use getExtendedTypes() instead.`
For updates,
**Update is**
```
public function getExtendedTypes(): iterable
    {
        return array(CustomerProfileType::class);
    }
```
Please update this in doc.

**Comment by Zales0123** [comment]
Associated with https://github.com/Sylius/Sylius/pull/10068
