### ISSUE TITLE
Fix Taxon after composer update

### ISSUE THREAD

**Issue by smanezItec** [Sylius/Sylius#10085]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.3.0

I'm trying to customize the Taxon model and I always get the same error. I tried to reverse the changes and I still get the same.

`Class "TaxonTranslation" not found. Is the "data_class" form option set correctly?`

**Comment by pamil** [comment]
Could you provide more information? What are the exact changes you have done?
