### ISSUE TITLE
How to prevent erasing database schema

### ISSUE THREAD

**Issue by qlerebours** [Sylius/Sylius#10099]
Hello !

When i run the `sylius:fixtures:load init` command my tables that are not generated by Sylius are dropped. For example, I installed a Sylius plugin for adding products to wishlist, that generates 2 tables. After running the load command, those tables disappeared from the database.

Is there a way to prevent this ?

Thanks

**Comment by Zales0123** [comment]
Hello and welcome to the community! **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our Slack (preferred) or [forum](https://forum.sylius.com/) ;) We have a very active, developed community, I'm sure someone will be able to help you with your problem. Good luck :)
