### ISSUE TITLE
Not able to Generate a AUTH token

### ISSUE THREAD

**Issue by Vimal6617** [Sylius/Sylius#10110]
On the Same server we have install two instances of sylius Dev and Stage.
php bin/console sylius:oauth-server:create-client --grant-type="password" --grant-type="refresh_token" --grant-type="token"

Using this command I am able to generate Access token for dev but when i move to the stage directory and try to execute the same command for auth it gives me a Auth token but that is valid for dev not for stage.

Let me know how can i create Access token for stage in this case.

**Comment by pamil** [comment]
Please add `--env=[your_environment]` to the command to make it work.
