### ISSUE TITLE
Product not editable after its main taxon or associated taxon has been deleted

### ISSUE THREAD

**Issue by KirbyFox** [Sylius/Sylius#10122]
After a Taxon has been deleted, any products for which that is their main taxon or one of its associated taxons, can no longer be edited.

It results in a server error instead.

The only way to resolve the situation is to edit the record directly within the database.

Sylius should first check that no products have the taxon set as their main taxon or an associated taxon before it is deleted.

**Comment by CoderMaggie** [comment]
I am not sure how come you could've achieved that. I suspect you deleted this taxon via database not via UI.

In the UI you would get prevented to do that:
![image](https://user-images.githubusercontent.com/13198869/53231703-e0b6b300-3689-11e9-85c7-3ad9d1d77fed.png)
