### ISSUE TITLE
Update to version babel 7

### ISSUE THREAD

**Issue by Chrysweel** [Sylius/Sylius#10129]
**Update version babel**
I see that babel has version 7.3.0 
https://babeljs.io/blog/2019/01/21/7.3.0

But in package.json of sylius last version has...
>"babel-core": "^6.26.3",

And also
>"babel-preset-env": "^1.7.0",

Is Sylius compatible with last version? Is there a plan to update the babel version?

https://babeljs.io/docs/en/v7-migration

And other question... Sylius has thought about the possibility of using webpack?

Thanks in advance ! :)

**Comment by kulczy** [comment]
Hi @Chrysweel We didn't test Sylius with the latest version of Babel. As for Webpack, we check the possibility of integration with our template system and it looks promising 🌟

**Comment by Chrysweel** [comment]
Good news about webpack.   :muscle: 

About updating Babel, have you propose it for the near future?

**Comment by kulczy** [comment]
I don't think so, we haven't thought about it

**Comment by CoderMaggie** [comment]
Hello guys!

Seems like this discussion is over, please reopen if needed or continue on our Slack! 👋
