### ISSUE TITLE
[RFC] coupon usage should not account for cancelled orders

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#10125]
**Describe the proposed solution**
I have configured the following vouchers: 
![image](https://user-images.githubusercontent.com/5156054/51844255-79714180-231d-11e9-8e61-cf4153bee4ea.png)

Any customers that are completing an order with such a voucher and get their order cancelled by any reasons (wrong stock, changed their mind etc.) will no longer be able to use the same coupon again without any intervention by customer support.

**Describe alternatives you've considered**
What we did so far was to allow our customer care reps. to issue more vouchers that can be used only once for such situations, but it's cumbersome and it requires over the phone / over the email communication. 

**Additional context**
The solution we applied on our case was pretty simple:

```
public function countByCustomerAndCoupon(CustomerInterface $customer, CouponInterface $coupon)
    {
        $qb = $this->createQueryBuilder('o');
        $expr = $qb->expr();
        return (int) $qb
            ->select('count(o.id)')
            ->innerJoin('o.promotionCoupon', 'coupon')
            ->andWhere('o.customer = :customer and o.completedAt IS NOT NULL and coupon = :coupon')
            ->andWhere($expr->notIn('o.state', [OrderInterface::STATE_ABANDONED, OrderInterface::STATE_CANCELLED]))
            ->setParameter('customer', $customer)
            ->setParameter('coupon', $coupon)
            ->getQuery()
            ->getSingleScalarResult();
    }
```
bear in mind that we are using Sylius 0.19 and things might have changed since that ancient version.

**Comment by GSadee** [comment]
If I understand correctly the issue, this feature already exists in Sylius at least since the 1.0: [applying_promotion_coupon_with_per_customer_usage_limit.feature#L51-L62](https://github.com/Sylius/Sylius/blob/1.0/features/promotion/applying_promotion_coupon/applying_promotion_coupon_with_per_customer_usage_limit.feature#L51-L62)
