### ISSUE TITLE
[Roadmap] Gift cards

### ISSUE THREAD

**Issue by loevgaard** [Sylius/Sylius#10127]
**Describe the proposed solution**
A generic way to create/use/buy gift cards.

Use cases
* Gift cards are a good way for customers to buy presents for other people.
* Also in a scenario where a customer have returned products that are damaged or what not, the store could give the customer a gift card instead of a refund. To give a gift card instead of a refund could be very useful in a lot of other customer service scenarios also.

Right now we have created our own plugin: https://github.com/Setono/SyliusGiftCardPlugin

**Comment by CoderMaggie** [comment]
Hi! One question: would you like Sylius to propose our own solution or to support your plugin as official? :)

**Comment by loevgaard** [comment]
Well basically I would love Sylius to provide a solution, but if you think it's better to make our plugin better that would also be a way to go.

**Comment by loevgaard** [comment]
I just thought it would be very useful to a lot of people that's why I thought it probably should be part of Sylius

**Comment by CoderMaggie** [comment]
it is useful for sure, but... is there anything wrong with your plugin? ;> If not, I assume it would be pointless to duplicate work that's already done :)

**Comment by loevgaard** [comment]
Okay, it would be good to make it very stable. Thanks @Zales0123

**Comment by gabiudrescu** [comment]
I like the idea of having Sylius vouch for something built by community and recommend it as an "Official Sylius Plugin". 

maybe you should extend this to other plugins too.

**Comment by loevgaard** [comment]
I will close this issue since our plugin (https://github.com/Setono/SyliusGiftCardPlugin) works very well and is the way to go I guess :)

**Comment by starmate** [comment]
Hello,

Seems to be a great plugin. @loevgaard : can our customers buy gift card? If yes, how could that be done?

Regards,

Jon

**Comment by loevgaard** [comment]
Hi @starmate 

I think it's a great plugin ;) It has certainly gone through a lot of development.

And to answer your question: Yes, your customers can buy gift cards :) You create a product that you mark as a gift card.

**Comment by starmate** [comment]
@loevgaard thanks a lot for your reply 👍

**Comment by starmate** [comment]
Hello again @loevgaard ,

I've installed the module but I don't see the option on product creation form.

I am using the following version of Sylius : 1.7.0@rc

Is there any known compatibility issues? Do I need to do something in particular in order to show this form element?

Please also note that I don't see the form on cart page.

Thanks

**Comment by starmate** [comment]
> Hello again @loevgaard ,
> 
> I've installed the module but I don't see the option on product creation form.
> 
> I am using the following version of Sylius : 1.7.0@rc
> 
> Is there any known compatibility issues? Do I need to do something in particular in order to show this form element?
> 
> Please also note that I don't see the form on cart page.
> 
> Thanks

nevermind, I just didn't override the templates. ;) Thanks again for this great module!

**Comment by loevgaard** [comment]
I am glad you like it :) If you have anymore issues it's probably better to post them on the gift card plugin page instead of this issue :)
