### ISSUE TITLE
Product Variant no longer editable after associated Shipping Category has been deleted

### ISSUE THREAD

**Issue by KirbyFox** [Sylius/Sylius#10139]
If a Product Variant's Shipping Category is deleted, that Product Variant is no longer editable via the Admin area.

It results in a server error and the only way to resolve the issue is to edit the Product Variant record directly in the database.

**Comment by Zales0123** [comment]
Hello @KirbyFox, which version of Sylius do you use? I've just checked it on our demo (Sylius 1.3.7) and it works as expected

**Comment by KirbyFox** [comment]
@Zales0123 The very latest version.

**Comment by CoderMaggie** [comment]
I have just tried to reproduce that on master version of Sylius and it does not occur.

Please come to [Slack](https://sylius.com/slack) channel if still having issues.
