### ISSUE TITLE
Expired cart remover efficiency

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#10148]
Hi,

Last week I ran into an issue where the removing of expired carts was causing issues. Basically due to my error an SQL error occurred on some orders (wrong cascading of null values). Anyway, as the flush in such commands is done at the end, none of the expired carts get removed. Basically it starts to build up and up, never removing any carts anymore. After a while, the amount of carts to be processed is so high that the command can also run out of memory.

I'm not sure what is the best solution here. Calling `flush()` after every removal in `src/Sylius/Bundle/OrderBundle/Command/RemoveExpiredCartsCommand.php` is probably also not a good solution. Obviously I'm working on fixing my error, but memory issues can occur anyway if people only setup such commands later in their projects and loading an huge amount of orders.

**Comment by wadjeroudi** [comment]
@stefandoorn I think the removal should be handled by pure SQL. And maybe notify only the ids removed not the loaded cart entities.

**Comment by stefandoorn** [comment]
I'm not sure this fully solves the issue @pamil. The index makes it more efficient, but it still can run out of memory if too many carts are loaded. Let's say somebody didn't schedule this command for 2 years and then wants to use it. That becomes rather hard. It probably has to move the expiry date month by month to get to a workable solution I'm afraid.

**Comment by nicogommen** [comment]
Hi,

We have the same issue.
We don't have any error, but just a lot of traffic.
We have the cronjob set up every night, to remove carts that have been idle for 2 days.
But in 2 days, we have too many carts and the command can't handle it... and always run out of memory.
We now have more than 9 000 000 carts in the database...
We're going to manually remove the items with an SQL query, but the issue will happen again very soon, so it would be nice to optimize the command like @stefandoorn suggested (https://github.com/Sylius/Sylius/issues/10148#issuecomment-460176496).

Thanks.

**Comment by Zales0123** [comment]
I'll reopen it then, to trigger a discussion :) If you @stefandoorn or @nicogommen have any possible, better solution for the problem, PR would be very welcomed 😄 🖖

**Comment by wadjeroudi** [comment]
@nicogommen did you make the SQL queries ?

**Comment by nicogommen** [comment]
Hi @wadjeroudi, 

Yes, we did the query manually => delete the items from the carts' table for the carts older than 2 days (I can't remember the exact query).
Then we ended up increasing the frequency of execution of the sylius:remove-expired-carts command.
We put it every hours, so there's way less items to delete each time it's executed.

**Comment by stefandoorn** [comment]
I actually did the same. My suggestion would be to just use a query to fetch the ID's to be removed, then remove these without loading the entities at all. Guess that should be possible with Doctrine.

**Comment by stefandoorn** [comment]
As @wadjeroudi suggests, so events can still be emitted.

**Comment by robjensen82** [comment]
One option to consider would be changing `\Sylius\Bundle\OrderBundle\Doctrine\ORM\OrderRepository::findCartsNotModifiedSince` to return `->iterate()` instead of `->getResult()`. The command could then do a clear after every 100 iterations. I think this would help keep memory usage under control

**Comment by stefandoorn** [comment]
Agree, something like that or doing a more efficient removal (no Doctrine entity loading) should do. For now I don't have issues, but on bigger shops like above mentioned this could still be an issue. I think it should stay open, @Zales0123.
