### ISSUE TITLE
Not able to create Persistent Connection: PDO

### ISSUE THREAD

**Issue by abhimanyu56** [Sylius/Sylius#10150]
I am trying creating Persistent connection but when checking through "netstat -aonp | grep 3306" I can still see number of connections. (Screenshot Attached)
![image](https://user-images.githubusercontent.com/1777553/52205322-b51b8680-289c-11e9-9435-fa0de31011d2.png)

I added ATTR_PERSISTENT in config file as well.
doctrine:
    dbal:
        driver: '%database_driver%'
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        server_version: '5.5'
        charset: UTF8
        **options:
            PDO::ATTR_PERSISTENT: true**

And also verified in constructor of vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php that this Persistent variable is coming in options value.

Can someone help on this creating persistent connection?

@KirbyFox @pminnieur @xElysioN @SyliusBot @isometriks @Zales0123

**Comment by xElysioN** [comment]
Hello, 
Why you wanna use persistent connection with Sylius ? 
Have a look on this link for persistent connection disadvantages.
https://stackoverflow.com/questions/3332074/what-are-the-disadvantages-of-using-persistent-connection-in-pdo

**Comment by CoderMaggie** [comment]
I am closing this due to low response rate, plaase come to our [Slack](https://sylius.com/slack), there we can have a more of a discussion :)
