### ISSUE TITLE
Failure during prod installation

### ISSUE THREAD

**Issue by loic425** [Sylius/Sylius#10158]
**Sylius version affected**: 1.4.0

**Description**  

Failure on cache:clear on prod due to DotEnv requirement.
```
Script symfony-cmd handling the auto-scripts event returned with error code 127
Script @auto-scripts was called via post-update-cmd
```

**Steps to reproduce**  

composer install --no-dev

**Possible Solution**  

Due to config/bootstrap.php, DotEnv is required on prod. Symfony/Skeleton has DotEnv on prod requirements.
https://github.com/symfony/skeleton/blob/master/composer.json

Maybe this is a bug on symfony...

**Comment by mohamedyasser** [comment]
You can try `composer update symfony/flex --no-plugins --no-scripts`.
Then try `composer install`.

Can you show us the `scripts` part of your `composer.json`?

or you can skip scripts by `--no-scripts`

**Comment by loic425** [comment]
@mohamedyasser just running this command "composer install --no-dev" on Sylius/Sylius repository.
bin/console script needs DotEnv cause it includes config/bootstrap.php
```
// Load cached env vars if the .env.local.php file exists
// Run "composer dump-env prod" to create it (requires symfony/flex >=1.2)
if (is_array($env = @include dirname(__DIR__) . '/.env.local.php')) {
    $_SERVER += $env;
    $_ENV += $env;
} elseif (!class_exists(Dotenv::class)) {
    throw new RuntimeException('Please run "composer require symfony/dotenv" to load the ".env" files configuring the application.');
} else {
    // load all the .env files
    (new Dotenv())->loadEnv(dirname(__DIR__) . '/.env');
}


```

**Comment by loic425** [comment]
@pamil This issue is critical.
Just run "composer install --no-dev" on master branch or 1.4 branch.

**Comment by markahesketh** [comment]
I am seeing the same issue.

It looks like the bootstrap was added here:
https://github.com/Sylius/Sylius/pull/10089/files#diff-2bad73d472db80e76e124fbfe9908964

When trying to run Sylius on any non-development environment, this exception is thrown as `DotEnv` has not been installed, as it expects a `require-dev` dependency to be present

This leads to a 500 error when trying to view the storefront, as well as when using the console such as to run the install command:

```
2019-03-03T18:53:35.649836177Z app[web.1]: [03-Mar-2019 18:53:34 UTC] PHP Fatal error:  Uncaught RuntimeException: Please run "composer require symfony/dotenv" to load the ".env" files configuring the application. in /app/config/bootstrap.php:13
2019-03-03T18:53:35.651247364Z app[web.1]: Stack trace:
2019-03-03T18:53:35.652122720Z app[web.1]: #0 /app/public/index.php(7): require()
2019-03-03T18:53:35.652220133Z app[web.1]: #1 {main}
2019-03-03T18:53:35.652386056Z app[web.1]:   thrown in /app/config/bootstrap.php on line 13
```

For now, I will edit the `config/bootstrap.php` as needed, but what is the expectation here?

**Comment by loic425** [comment]
> For now, I will edit the `config/bootstrap.php` as needed, but what is the expectation here? Personally, I think `DotEnv` should remain a dev dependency, but the bootstrap should only require it in a developer environment.

I don't think so, have you look at symfony skeleton composer:
https://github.com/symfony/skeleton/blob/4.2/composer.json

https://symfony.com/doc/current/configuration/dot-env-changes.html
New recipe needs dotenv on prod environment.

**Comment by loic425** [comment]
I close this issue, cause it has been fixed on Sylius Standard https://github.com/Sylius/Sylius-Standard/pull/333
