### ISSUE TITLE
Taxons Not working in 1.3.6

### ISSUE THREAD

**Issue by Vimal6617** [Sylius/Sylius#10154]
Sylius version affected: 1.3.6

Description:

Edit a product and go to the 'Taxonomy' tab.

The animated GIF spins and in the browser console, it says API: No URL specified for api event.

This Issue was also reported in https://github.com/Sylius/Sylius/issues/10111 and as per @KirbyFox it was resolved by updating the app.js

Please provide more details about how to resolve this.
@laurent35240 @KirbyFox @pamil

**Comment by pamil** [comment]
Could you try installing the assets once again?
```
bin/console assets:install
yarn install
yarn run gulp
```

**Comment by CoderMaggie** [comment]
Hello @Vimal6617 👋 

As I cannot reproduce that and you seem not to respond here to the proposed solution I'd recommend joining our [Slack](https://sylius.com/slack) . See you there!
