### ISSUE TITLE
Regex within security.yml prevents is_granted('ROLE_USER') from working on homepage.

### ISSUE THREAD

**Issue by KirbyFox** [Sylius/Sylius#10168]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no/yes
| RFC?             | no/yes
| Sylius version   | 1.4.0

**Comment by KirbyFox** [comment]
Please see https://stackoverflow.com/questions/44423491/sylius-authentication-failing-on-homepage-alone/49530952#49530952

**Comment by CoderMaggie** [comment]
If I am checking this correctly, to me it does not occur on standard Sylius app. Were you customizing something in the urls? :>

https://docs.sylius.com/en/1.4/cookbook/shop/disabling-localised-urls.html

If it is still an issue, please reopen.
