### ISSUE TITLE
Multi-channel improvements

### ISSUE THREAD

**Issue by stanislavdavid** [Sylius/Sylius#10160]
Hi, thanks for great work, 
I am looking for multi-channel ecommerce solution and in current version 1.4 I am missing this features
- assign category (taxon) to some channel as It is on product page
- enable/disable variant per channel. Now I must insert two products instead of one, ie.
- some fee for selected payment method (i.e. Fee for cash on deliver +10 PLN)

**Comment by Zales0123** [comment]
Hello @stanislavdavid and than you for your kind words! I'm happy you find Sylius well. 
Regarding features you've proposed - for sure they can be useful, but we must always remember Sylius wants to be an eCommerce framework. That means, we want to provide ~80% of the most common eCommerce features and make it **easy as hell** to implement more on your own :) And of course, for many people "most common features" are very different. 
I'll leave this open, perhaps we would like to implement some of these features in the next Sylius versions, but you can also consider implementing them on your own in your application or, if you want to share your work with the community, create a Sylius plugin (see https://docs.sylius.com/en/1.3/plugins/creating-plugin.html). Good luck! :) 🐎
