### ISSUE TITLE
The regular expression for locale in the URL is not correct

### ISSUE THREAD

**Issue by superbull** [Sylius/Sylius#10173]
Current regular expression: 
https://github.com/Sylius/Sylius-Standard/blob/4de56cf9231ddb2d571cec31fb38e81d7d0f7ea0/config/routes/sylius_shop.yaml#L5
is not suitable for all locales.

For example `zh_Hans_CN` is not fit to this regular expression, which will cause an exception.

Below expression is copied from this post https://stackoverflow.com/a/48300605/2168459
```
^[A-Za-z]{2,4}([_-]([A-Za-z]{4}|[0-9]{3}))?([_-]([A-Za-z]{2}|[0-9]{3}))?$
```
I have tested it, everything works fine.

**Comment by Zales0123** [comment]
Thank you, @superbull for noticing this bug, I think the reason it was not caught before, is most of us are using locale codes with only 2 parts (like `en_US` or `pl_PL`). Do you think you can open a PR with proposed fix? Thanks!

PS. I've transferred your issue to Sylius/Sylius repository, as it's also relevant for our main repository. We will, of course, incorporate proposed and merged changes into **Sylius-Standard** as well :)

**Comment by superbull** [comment]
@Zales0123 My pleasure!
Yes, I will open a PR later.
