### ISSUE TITLE
1.4 version upgrade problem Return value of Sylius\Component\Core\Model\Channel::getShopBillingData() must implement interface Sylius\Component\Core\Model\ShopBillingDataInterface, null returned

### ISSUE THREAD

**Issue by mitalcoi** [Sylius/Sylius#10198]
**Sylius version affected**: 1.4.0
**Description**  
After upgrading app from 1.3 to 1.4 I have following exception:
<img width="1068" alt="2019-02-25 17 55 38" src="https://user-images.githubusercontent.com/3224226/53345783-bfbebe00-3926-11e9-91bb-df498a6e23d2.png">

**Comment by F-Locos** [comment]
You need to add manually the record in the sylius_shop_billing table of the database.
Don't forget to set the billing_id on the channel
I think they forgot to handle it

**Comment by Zales0123** [comment]
It was fixed in https://github.com/Sylius/Sylius/pull/10116 and will be included in the next patch release

**Comment by mitalcoi** [comment]
thx!

**Comment by alekseyp** [comment]
i think it got lost, since 1.4.1 came out without it :)

**Comment by lchrusciel** [comment]
That's true @alekseyp, thanks for keeping an eye on it :)

**Comment by lchrusciel** [comment]
Or to be honest, not sure if the issue should be opened. Now for sure, it will be a part of next patch release, as it is already merged :)
