### ISSUE TITLE
CartContext does not throw exception

### ISSUE THREAD

**Issue by mamazu** [Sylius/Sylius#10192]
**Sylius version affected**: ^1.3.6

**Description**  
The cart context (aka. `Sylius\Component\Order\Context\CompositeCartContext`) goes through all the cart contexts and tries to get a cart. If none of those are getting a cart a `CartNotFoundException` is thrown.
The problem is now that this exception is never thrown because the last service (`sylius.context.cart.new`) with priority -999 is a context that always returns a cart (because it's a wrapper for the `OrderFactory`). So this exception will never be thrown.
https://github.com/Sylius/Sylius/blob/f3a635c18a5683e1f043b6ac35aa533b15b8d23e/src/Sylius/Component/Order/Context/CompositeCartContext.php#L47

**Steps to reproduce**  
* Create a script and get the `"sylius.context.cart.composite` service and call `getCart()` on it. Without any information about anything it will return a cart.
* One of the examples I am working on is the ShopApiPlugin, where together with the `UserCartRecalculationListener` this context creates a cart on any authenticated request. (see https://github.com/Sylius/ShopApiPlugin/pull/401 )

**Possible Solution**  
Remove the `sylius.context.cart.new` service from the `CompositeCartContext`.

**Comment by Zales0123** [comment]
I believe it's just a default implementation and the idea is to give availability to override this behavior. By default, we want always to provide a cart (even if it's a new, empty cart eventually). But on the other hand, we want to be prevented that if somebody overrides these context and after processing all of the no cart would be resolved, an exception will be thrown. I don't this functionality as a bug, but I would be glad to see other @Sylius/core-team's members opinions 🚀

**Comment by mamazu** [comment]
Well one thing that you can do would be to register another context that does the same thing with with exception.

**Comment by vvasiloi** [comment]
I wonder what will happen in the templates if the context will suddenly throw exceptions.

**Comment by mamazu** [comment]
Well for the shop context this makes sense that the context will always return a cart. But in other contexts this might not so we should start to differentiate between the two.

**Comment by diimpp** [comment]
@vvasiloi, it will crash regular shop in templates with `An exception has been thrown during the rendering of a template ("Sylius was not able to figure out the current cart.").` error.

Commenting `sylius.context.cart.new` service in the api services, makes it work right again. So it's a situation, where using shop api plugin brakes regular shop unconditionally.

**Comment by mamazu** [comment]
The simplest solution would be to introduce a service that does the same thing but without the factory.

**Comment by pamil** [comment]
@mamazu I'd introduce that service in ShopApiPlugin if it's possible. We can't change the existing behaviour of the default cart context as this would break backwards compatibility.

**Comment by mamazu** [comment]
Well the problem is that we can only add services to the `CompositeCartContext` so we would have to do is build a new composite cart context with a compiler pass that has every service that the original one also has but not the factory. I don't think that there is an easy way to implement it or am I missing something?

**Comment by lchrusciel** [comment]
The decoration of the service and throwing an exception, if we are behind ShopApi firewall?

**Comment by mamazu** [comment]
The `CompositeCartContext` will always return a cart. What we could do is take the result of the context and check if it is a completely new cart (I wouldn't know how) and if it is throw an exception.

My suggestion would be the following: Split the `CompositeCartContext` one that I would call `cart_context.inner` where we have all the cart context's except for the factory and then the current cart context is another `CompositeCartContext` with the factory like this:

sylius.context.cart.composite
|-->sylius.factory.cart
|--> sylius.context.cart.inner
    |--> get cart from request
    |--> get cart from authentifcated customer
    |--> ....

**Comment by diimpp** [comment]
Unstale?

**Comment by mamazu** [comment]
It's closed
