### ISSUE TITLE
How to use the Admin-CRUD-Bundle properly with own entities?

### ISSUE THREAD

**Issue by MrsBookik** [Sylius/Sylius#10190]
**Sylius docs version**: 1.x / latest

**Description**

Is there any documentation available for how to use the CRUD package in AdminBundle together with own Entities and an own Repository?

I stumbled upon the documentation of the SyliusResourceBundle which gives some ideas but did not go further into the details.

I have a new entity and a new repository and want to make it editable via Crud / Grid in the admin panel. I could write lots of code to get a table with the data, adding some pagination tools, edit/delete/add methods and so on. But I think, Sylius has plenty of such tools already inside without reinventing the wheel. I'm curious if I could re-use stuff from Sylius, and the Crud page comes into my mind for this while reading the source code.

Any ideas? Any docs? Any tutorials available? Would be really cool! :)

**Comment by xElysioN** [comment]
Hi, 
You have theses links in the documentation to create a new entity (Translatable model and simple model) : 
https://docs.sylius.com/en/1.4/cookbook/entities/custom-model.html
https://docs.sylius.com/en/1.4/cookbook/entities/custom-translatable-model.html?highlight=supplier

And this one to add them in the admin : 
https://docs.sylius.com/en/1.4/cookbook/entities/custom-model.html#add-entity-administration-to-the-admin-menu

**Comment by CoderMaggie** [comment]
@xElysioN thanks for helping out :)

@MrsBookik **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our [Slack channel](http://sylius.org/slack) ;) See you there 👋
