### ISSUE TITLE
Whay Behat is used in Taxonomy Slug Generator?

### ISSUE THREAD

**Issue by padalec** [Sylius/Sylius#10206]
**Sylius version affected**: dev-master dda1309

**Description**  
This code will not be work after run `composer install --no-dev -o` command https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Taxonomy/Generator/TaxonSlugGenerator.php#L46

**Comment by pamil** [comment]
@padalec thanks for spotting the issue! Could you open a PR adding `behat/transliterator` `^1.1` as a dependency, targeting the `1.3` branch with it? It's defined in component's `composer.json` but missing in `composer.json` of `sylius/sylius` though.

**Comment by padalec** [comment]
PR created https://github.com/Sylius/Sylius/pull/10214
