### ISSUE TITLE
Email issues break checkout

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#10200]
In case there are issue with the configured email provider, the checkout by default breaks. The confirmation email is being sent when the user gets redirected to the payment provider. If the email fails for whatever reason, the page results in an error and the customer is stuck. I know this is an hard one to tackle out of the box, but I think it would be great to have a solution that can be enabled (eg handling in an queue / db handler) in case users can use this. Similar to cleaning up expired carts etc. I don't think the default behavior should change, but it would be a best practice to configure this. I think it's more important to let the customer finish the order & pay, than sending the email. Emails can always be resend e.g.

**Comment by Roshyo** [comment]
Speaking generally, it's strongly advised to send emails on a separate process than in the main thread. If the SMTP is taking time to answer, or is simply down.
We might imagine a mail queue in DB that is sent by a cronjob. So if the mail fails to be sent, it does not block the process.

**Comment by 4c0n** [comment]
It seems that the problem can be overcome by enabling a spool:
https://symfony.com/doc/current/email/spool.html

Question, I guess is whether or not it should be enabled by default and/or maybe be part of the documentation, as to warn people about the default settings of swiftmailer and its consequences.

**Comment by Roshyo** [comment]
IMO it should be enabled by default and users can be able to change it.
One potential drawback to this spool is that you must have access to crontab to effectively send your emails. Or is it possible to send them via a controller ?

**Comment by 4c0n** [comment]
@Roshyo That is probably the reason that it is not enabled by default. Surely you can make a controller that does that, however you still need some other process to call it.

**Comment by stefandoorn** [comment]
Simply spooling to the end of the request might not be enough, some queue processing might be better (via db e.g.). It must be optional imo, but strongly recommended.

**Comment by 4c0n** [comment]
@stefandoorn Kind of like this? https://symfony.com/doc/current/email/spool.html#spool-using-files
Spooling from the request life cycle only has advantages if multiple emails need to be sent within 1 request. Typically however processing of the spool is done from another process, thus preventing the original problem described in the issue from happening.

Do you think more is needed? If so, please elaborate :)

**Comment by stefandoorn** [comment]
Files might be useful, I'm thinking on a set-up to also allow for 'worker' instances to handle the sending instead of the webserver itself. Shared fileserver is then needed, but any other spool implementation (DB) e.g. is compatible also then. Might be good enough indeed, then a docs addition is enough in case of Sylius?

**Comment by vvasiloi** [comment]
There is this database spool implementation: https://github.com/whiteoctober/WhiteOctoberSwiftMailerDBBundle
Also, one could implemenet a spool that integrates Symfony Messenger.

**Comment by 4c0n** [comment]
If you're on a container based platform, you could just schedule a php container to run as a worker for sending the mail in the spool. Just need some form of storage that can be shared between containers. On "classic" hosting a cron daemon would do the trick. Indeed there are already bundles out there to provide those kind of storage facilities.
