### ISSUE TITLE
Performance issue in AttributeChoiceRemoveListener

### ISSUE THREAD

**Issue by einorler** [Sylius/Sylius#10227]
**Sylius version affected**: 1.x

**Description**  
Hi. I noticed there is a major performance issue in `Sylius\Bundle\ProductBundle\EventListener\ SelectProductAttributeChoiceRemoveListener`. What it aims to do is to remove product attribute values that contain the freshly removed attribute choice and I understand the reasoning why it's a good idea to do that, however, this line here - https://github.com/Sylius/Sylius/blob/f7c5226c517c1fb249cc41f0266053280ec37f92/src/Sylius/Bundle/ProductBundle/EventListener/SelectProductAttributeChoiceRemoveListener.php#L66 calls a method that performs a fulltext search on a non indexed longtext field and in our case, we already have ~800K rows in that table and it is only getting bigger. The result when this little listener takes effect is that it locks the entire table and eventually dies due to lock wait timeoutes.

**Steps to reproduce**  
Just add ~30K products, each with ~50 attributes, most of which are selects and try to remove a choice from select attribtue :)

**Possible Solution**  
In our case, we simply disabled the entire functionality altogether to save some time (were a bit in a hurry recently). But even something as simple as adding an ID of an attribute in question when searching for an attribute value would definetly make a huge difference. That said though, it wouldn't solve the issue altogether, performing fulltext searches on unindexed fields like this is really a bad idea when your'e working with any slightly bigger amount of data.

The repository method in question for reference: 
https://github.com/Sylius/Sylius/blob/f7c5226c517c1fb249cc41f0266053280ec37f92/src/Sylius/Bundle/ProductBundle/Doctrine/ORM/ProductAttributeValueRepository.php#L24

**Comment by chyzas** [comment]
@einorler Have you solve this issue personally?
