### ISSUE TITLE
[Bug] Error on running easy-coding-standard

### ISSUE THREAD

**Issue by regnisolbap** [Sylius/Sylius#10236]
**Sylius version affected**: 1.3

**Description**  
Running `vendor/bin/ecs check src --fix` throw the error: 

> PHP Fatal error:  Uncaught Error: Call to private method PHPStan\PhpDocParser\Parser\PhpDocParser::parseTagValue() from context 'SlevomatCodingStandard\Helpers\AnnotationHelper'

**Possible Solution**  
Updating all phpstan packages to version ^0.11 could resolve the problem, as PhpDocParser::parseTagValue() has been made public in [this](https://github.com/phpstan/phpdoc-parser/commit/2cc49f47c69b023eaf05b48e6529389893b13d74) phpstan/phpdoc-parser commit, which is published in version ^0.11 of phpstan/phpstan-shim.

**Comment by pamil** [comment]
Could you report this issue on the ECS repository? It's here: https://github.com/Symplify/Symplify

**Comment by regnisolbap** [comment]
Sure, it's [done](https://github.com/Symplify/Symplify/issues/1501) !

**Comment by Zales0123** [comment]
Probably can be closed :) 🚀
