### ISSUE TITLE
[User] Cannot install sylius/user 1.4

### ISSUE THREAD

**Issue by cyrosy** [Sylius/Sylius#10238]
**Sylius version affected**: 1.4

**Description**  
sylius/user-bundle cannot be use as standalone package in 1.4 version :

It seems versions 1.4.0 and 1.4.1 of sylius/user are not taggued in packagist.
Requiring sylius/user-bundle install sylius/user v1.3.2, which misses the new `$encoreName` property and causes errors with Doctrine schema validation.

Manually requiring sylius/user with 1.4 constraint doesn't work unless I chage my minimum-stability to dev - which I don't want.

**Steps to reproduce**  
```bash
# Create temp project
mkdir tmp && cd tmp
# Init composer and require sylius/user-bundle
composer init && composer req sylius/user-bundle
# Require sylius/user with 1.4 constraint
composer req sylius/user ^1.4
```

**Possible Solution**  
Tag the v1.4.0 and v1.4.1 versions of sylius/user in Packagist

**Comment by Zales0123** [comment]
Hello @cyrosy, I've just checked it out and it seems to work for me:

![Zrzut ekranu 2019-03-19 o 12 21 44](https://user-images.githubusercontent.com/6212718/54602349-c03c0780-4a41-11e9-813c-a037e119e4c9.png)

As far as I see, there is also a tagged version on the packagist https://packagist.org/packages/sylius/user.

Is anyone else facing this problem?

**Comment by cyrosy** [comment]
Versions 1.4.0 and 1.4.1 where not tagged on packagist at time of writing the issue - seems to be resolved now.
Closing.
