### ISSUE TITLE
[Docs] Checkout graph is outdated

### ISSUE THREAD

**Issue by Zales0123** [Sylius/Sylius#10235]
**Sylius version affected**: 1.3.*

Both checkout graph and state machine configuration (https://docs.sylius.com/en/1.3/book/orders/checkout.html) are not up-to-date with the current implementation... and it's a euphemism 😄 

<img width="827" alt="Zrzut ekranu 2019-03-15 o 14 22 15" src="https://user-images.githubusercontent.com/6212718/54434388-67f9c280-472e-11e9-9f9e-d9178e0b4aa9.png">

**Comment by CoderMaggie** [comment]
As the graphs are created using LucidChart software it definitely wasn't a "Good First Issue" 😈
