### ISSUE TITLE
Support for CryptoCurrencies 

### ISSUE THREAD

**Issue by itinance** [Sylius/Sylius#10244]
We'd like to support CryptoCurrencies like Bitcoin and Ether in our Shop. However, it seems that only Currencies are working correctly that are fully supported by Symfonies Intl-Class:

[In the Docs:](https://docs.sylius.com/en/1.4/components_and_bundles/components/Currency/basic_usage.html)

> "The getName method uses Symfony’s Intl class to convert currency’s code into a human friendly form."

We tried to setup these currencies via SQL:

```
INSERT INTO `sylius_currency`(`id`,`code`,`created_at`,`updated_at`) VALUES ( '1', 'EUR', '2018-06-26 09:48:38', '2018-06-26 09:48:38' );
INSERT INTO `sylius_currency`(`id`,`code`,`created_at`,`updated_at`) VALUES ( '2', 'BTC', '2018-06-26 09:48:38', '2018-06-26 09:48:38' )

```

But getName() is delivering a blank string then and it looks strange (almost unusable) in the Admin-Panel:

<img width="252" alt="Screenshot 2019-03-19 16 47 18" src="https://user-images.githubusercontent.com/1758597/54620582-aeb92680-4a66-11e9-8bd9-cf806de75642.png">

In order to bring the huge world of CryptoCurrencies into Sylius, what would be the best approach? I could think of adding a concrete column "name" to the `sylius_currency`-table to make those currencies available. 

What do you guys think? I'd like to submit a PR, but want to discuss with you the best approach. Maybe something else that i am not aware of :)

**Comment by vvasiloi** [comment]
Extend `Symfony\Component\Form\Extension\Core\Type\CurrencyType` and add the cryptocurrencies to the result.
Decorate `Sylius\Bundle\CurrencyBundle\Templating\Helper\CurrencyHelper` to handle cryptocurrencies.
See this issue: #10204 
See this code: https://gist.github.com/vvasiloi/5d8d5d8c88645b5f425553a3be9929a9

**Comment by itinance** [comment]
Thx, @vvasiloi.
For now i've ended up with overriding currency class to an own one which overrides getName() and adds some more columns to the `sylius_currency`-table.

config.yml:

```
sylius_currency:
    resources:
        currency:
            classes:
                model: AppBundle\Entity\Currency
```



Why do you suggest to overwrite CurrencyType as well?

**Comment by vvasiloi** [comment]
@itinance It's used do add currencies from admin panel, but you can skip it probably.

**Comment by itinance** [comment]
But with my approach i run into another issue:

`Return value of Sylius\Bundle\CurrencyBundle\Templating\Helper\CurrencyHelper::convertCurrencyCodeToSymbol() must be of the type string, null returned
`

It happens when i want to edit a product. Will look at it ...

**Comment by vvasiloi** [comment]
@itinance I wrote about that in my first comment.

**Comment by vvasiloi** [comment]
No. It's a Symfony DI service. I suggest you to decorate it.
https://symfony.com/doc/current/service_container/service_decoration.html

**Comment by itinance** [comment]
Many thanks!
