### ISSUE TITLE
Channel code length 

### ISSUE THREAD

**Issue by TELLO0815** [Sylius/Sylius#10241]
If the channel code is to long (more than 6 digits / or / mb its the _ in my code) there is a error to get items in the basket. As example: my channel code was CH_B2C_WEB and the result was: 'value' => 'a:1:{s:6:"CH_B2C_WEB";a:1:{s:6:"amount";i:500;}} .

So I guess the channel code field must get a limitation of 6 digits ?

Mike

**Comment by Zales0123** [comment]
I've just tried to reproduce it on the newest `1.3` and it worked fine, with `CH_B2C_WEB` code 🎢 I also see no such length constraint in Channel mapping... are you sure these are not some of your changes making this issue?

**Comment by TELLO0815** [comment]
I used CH_B2C_WEB name CH B2C and CH_B2B_WEB name CH B2B Channel. And I got the error 500. In my sql all the channel was correct. Just after changing them to CH-B2C and CH-B2B everything works fine.
And I use three machines for this project. On this time the version was different. The newest Sylius 1.4.1 and 1.4.0 / Symfony 4.2.4 and 4.2.3 and the error was on booth.
After update Channel code all works fine.

**Comment by pamil** [comment]
I have created a channel "CH_B2C_WEB" but it works correctly. How did you create the channel or modify its code?

**Comment by TELLO0815** [comment]
Im not sure if I explain this correct. The problem is not the channel code if you create a channel. The problem is the long channel code or the underline, if you create them and than you have serialized products. If you want to give them to basket, you get the error:


And I just renamed the Channels to test it. Means I export my sql and dump db. rename the channel code and the code in the product serialization by search and change. And I get again the error.

> {
>     "code": 500,
>     "message": "Could not convert database value to 'array' as an error was triggered by the unserialization: 'unserialize(): Error at offset 16 of 90 bytes'"
> }

And the problem is the unserialization.
