### ISSUE TITLE
Symfony debug bar not working on archlinux on fresh Sylius install

### ISSUE THREAD

**Issue by lorenzo-milesi** [Sylius/Sylius#10245]
**Sylius version affected**: 1.4.*

**Description**  
Symfony debug bar doesn't seem to work just after installed Sylius and started local server on dev environment :

**Steps to reproduce**  
1. Install sylius with composer (create-project) from scratch
2. _Optionnal_ - Connect local database inside .env file
3. Start php server (in my case valet linux)
4. Connect to home page
5. Debug bottom bar message : "An error occurred while loading the web debug toolbar. "

**Environment**  
- PHP version : 7.3
- running with Valet Linux on Nginx on localhost
- database : MariaDB (but this has nothing to do with the bug, I think)

Cheers :D

**Comment by eyeskiller** [comment]
Hi, it's problem of PHP 7.3, you need to downgrade version of PHP to 7.2. 

(https://bugs.php.net/bug.php?id=77302)

**Comment by Zales0123** [comment]
I believe it's related to https://github.com/Sylius/Sylius/issues/10223, but it is said to happen also on PHP 7.2 😕 @Gounlaf, can you confirm?

**Comment by lorenzo-milesi** [comment]
Thanks @eyeskiller, @Zales0123 :+1: I will try and change my php version to 7.2 on my machine today or tomorrow, will tell you if that worked :)

**Comment by eyeskiller** [comment]
I am running Sylius on this version, and everything works well.
PHP 7.2.15 (cli) (built: Feb  7 2019 20:10:03) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans
    with Zend OPcache v7.2.15, Copyright (c) 1999-2018, by Zend Technologies

**Comment by lchrusciel** [comment]
Duplicated #10223
