### ISSUE TITLE
Impossible to add taxonomy to a product

### ISSUE THREAD

**Issue by MEDYN4** [Sylius/Sylius#10257]
**Sylius version affected**: 1.4.1

**Description**  
When creating or updating a product from the admin, nothing render in the Taxonomy tab, so it impossible to link a product to a taxon.

![image](https://user-images.githubusercontent.com/48885239/54881077-f3b4d280-4e43-11e9-8717-5ae3a1c88f1c.png)

![image](https://user-images.githubusercontent.com/48885239/54881109-5e660e00-4e44-11e9-810f-6622fc5bc070.png)

I havnt trouble with taxons and taxons tree somewhere else.
Everything works well when creating or updating a taxon

![image](https://user-images.githubusercontent.com/48885239/54881209-7ab67a80-4e45-11e9-9644-2cf53e7e4014.png)

**Steps to reproduce**  
I thought linked to my locales first, but i reloaded default fixtures but still not working

**Possible Solution**  
I don't know but I dont find any taxon table in database, I can just see the main taxon field in product table

I need help to make it work properly. Thanks

**Comment by vvasiloi** [comment]
Check the AJAX request and logs.
There is either an error or the request is handled too slow.

**Comment by MEDYN4** [comment]
@vvasiloi can you tell me please where exactly I should check? I'm new to this

**Comment by vvasiloi** [comment]
For requests:
![image](https://user-images.githubusercontent.com/7114562/54916545-6c7a6400-4f02-11e9-875f-5be89488ffdf.png)
And for logs look into `var/log/dev.log`.

**Comment by KirbyFox** [comment]
My guess would be that you're missing the admin.js file, or have an outdated version.

**Comment by MEDYN4** [comment]
@vvasiloi this is what I get

![image](https://user-images.githubusercontent.com/48885239/54935616-8b83f080-4f18-11e9-8d2e-9aa41d9387d0.png)

I think the trouble comes from the request as you said, but I don't even know how it should be

**Comment by MEDYN4** [comment]
@KirbyFox I have the app.js in admin/js directory 
but maybe it's outaded, I will try to replace it by the latest version to see

**Comment by Zales0123** [comment]
Hello @MEDYN4 and welcome to the community! **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our Slack (preferred) or [forum](https://forum.sylius.com/) ;) We have a very active, developed community, I'm sure someone will be able to help you with your problem. Good luck :)
