### ISSUE TITLE
Search filter is case sensitive with Postgre SQL

### ISSUE THREAD

**Issue by qlerebours** [Sylius/Sylius#10251]
**Sylius version affected**: 1.3.6

**Description**

When I write something in a search filter, the query is case sensitive. My prod environment uses PostgreSQL and my dev environment MySQL. I have the problem on prod and not on dev. So the issue seems to be related to my database.

**Steps to reproduce**

Install demo with PostgreSQL database and search for "mug" (without capital letter). It should return an empty list.

It can also be reproduced on a database playground like [www.db-fiddle.com/f/wPxkfcNch1oxJk2mAkpPZW/0](https://www.db-fiddle.com/f/wPxkfcNch1oxJk2mAkpPZW/0)
If you look at the example, you'll see that the two queries work with MySQL.
If you change MySQL 5.7 to PostgreSQL 10.0 you'll see the issue.

**Possible Solution**

I searched where could I change this and I found the StringFilter.php file (in src > Sylius > Component > Grid > Filter). But I didn't find where SQL request is sent to apply LOWER() SQL function.
If I found the SQL request, I could apply LOWER() SQL function like this :
`SELECT column FROM my_table WHERE LOWER(column) LIKE LOWER('%...%');`

**Comment by pamil** [comment]
You can hotfix it by overriding `sylius.grid_driver.doctrine.orm` service to return customised `DataSourceInterface` which uses customised `ExpressionBuilderInterface` in which the logic inside `like` comparison can be customised.

**Comment by qlerebours** [comment]
Thank you for the possible solution. I will try and write the code here if it works !

**Comment by FabienEssid** [comment]
Hello @pamil ! Thank you for your hotfix! I'm working with @qlerebours and this is the solution :
- Override `Sylius\Bundle\GridBundle\Doctrine\ORM\Driver` and change its namespace. Change `DataSource` to `DataSourceCustom` too.
- Change services configuration for `Driver.php` overrided (it has to call the new overrided class)
- Create two new classes in the same directory as new Driver file called `DataSourceCustom.php` and `ExpressionBuilderCustom.php`
- Copy `Sylius\Bundle\GridBundle\Doctrine\ORM\DataSource.php` source code and paste it in `DataSourceCustom.php` and replace `ExpressionBuilder` by `ExpressionBuilderCustom` class
- Copy `Sylius\Bundle\GridBundle\Doctrine\ORM\ExpressionBuilder.php` source code and paste it in `ExpressionBuilderCustom.php`
- In `ExpressionBuilderCustom.php`, in like method, replace : `return $this->queryBuilder->expr()->like($this->getFieldName($field), $this->queryBuilder->expr()->literal($pattern));` by : `return $this->queryBuilder->expr()->like('LOWER('.$this->getFieldName($field).')', 'LOWER('.$this->queryBuilder->expr()->literal($pattern).')');`

And now, it works!
