### ISSUE TITLE
Sorting products by cheapest or most expensive price is broken

### ISSUE THREAD

**Issue by qlerebours** [Sylius/Sylius#10266]
**Sylius version affected**: 1.4.0

**Description**

When sorting products in the shop by cheapest or most expensive price, Sylius catches an SQL error.

![image](https://user-images.githubusercontent.com/17043042/55001675-6c976400-4fd5-11e9-8e68-1916b863ea29.png)

**Steps to reproduce**

To reproduce it, you can simply go to the Sylius demo with this link : [https://master.demo.sylius.com/en_US/taxons/t-shirts/men](https://master.demo.sylius.com/en_US/taxons/t-shirts/men) and sort items by cheapest price or most expansive price. You got a 500 error.

**Possible Solution**

SQLSTATE[HY000]: General error: 3065 Expression #1 of ORDER BY clause is not in SELECT list, references column 'sylius_dev.s5_.price' which is not in SELECT list; this is incompatible with DISTINCT
The error says that it should add ORDER BY parameters in the SELECT clause.

**Comment by vvasiloi** [comment]
It is working on 1.4.0, but not on master.
I don't see in the diff any potential causes of this issue, so I think it's related to database configuration.
Maybe somethig related to sql_mode.

**Comment by vvasiloi** [comment]
I was on the right path.
Tested 1.4.0 again after adding ONLY_FULL_GROUP_BY to sql_mode and it thrown the same exception.
I'm running MYSQL 5.7.23 which didn't have that mode added by default.
