### ISSUE TITLE
Improve the discounts' display in Order Summary (and cart)

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#10261]
**Sylius version affected**: 1.2.x

**Description**  
I'm testing around with coupons. Currently we are not using them, but it might be used in the future. When testing with the coupon actions that apply at order level (either % or a fixed amount), I see that the prices of the order items are being manipulated. I would expect though that they stay the same, and only the full order price gets deducted by the amount of the coupon. Now we get lower product prices and a discount value, which sounds counterintuitive to me. 

Example - product price = 100. Coupon gives 25 euro discount.
Product price becomes 75, discount is -25, total price is 75. 
I would expect: product price = 100, discount = -25, total price is 75.

For 'per line' discounts it makes sense, although it might still be unclear to the customer if the prices first get lowered and then in the summary the discount is shown again (which feels like double).

**Comment by gabiudrescu** [comment]
it was confusing for us too. I guess better naming and some tooltips with details would do magic.

**Comment by CoderMaggie** [comment]
Fixed in #10400, #10417, #10419, #10420, #10443 and #10438! 👌 Phew, a lot of work it was 😅

**Comment by stefandoorn** [comment]
Thanks a lot! I think it's slightly different and therefore still potentially confusing - because the discount gets applied on each order row and that's not always what customers expect. But the positive thing is, is that's something easily changed by overriding some templates, so good to go I think 🎉 :-)
