### ISSUE TITLE
Fixtures: There are no ability to specify Product's slug 

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#10272]
**Sylius version affected**: Any

**Description**  
There are no ability to specify slug for Product so we should generate unique names. Otherwise it can raise slug duplication exception (if faker made non-unique name).

**Possible Solution**  
Add new option to `ProductFixture` and `ProductExampleFactory` and generate `slug` only if if it was not provided.

I will make PR if you guys OK with this.
Thanks

**Comment by Zales0123** [comment]
As far as I see, right now it's generated with a `SlugGenerator` but it totally should be doable to set it manually 👍 Feel free to open a PR :)
