### ISSUE TITLE
Can't remove product association when it's not in the ajax list

### ISSUE THREAD

**Issue by adeve-quotatis** [Sylius/Sylius#10275]
**Sylius version affected**: 1.4.1

**Description**  
When your are on the product detail page and you want to change associations, the ajax call returns only 20 products. If you get this list then try to remove an existing association which is not in the returned list, a javascript error occurs.

concerned file : ***sylius-product-auto-complete.js:57***
```
app.js:1 Uncaught TypeError: Cannot read property 'parents' of undefined
    at HTMLDivElement.onRemove (app.js:1)
    at Object.value (app.js:1)
    at HTMLAnchorElement.<anonymous> (app.js:1)
    at Function.each (app.js:1)
    at T.fn.init.each (app.js:1)
    at Object.labels (app.js:1)
    at Object.activeLabels (app.js:1)
    at HTMLElement.click (app.js:1)
    at HTMLDivElement.dispatch (app.js:1)
    at HTMLDivElement.m.handle (app.js:1)
```

**Steps to reproduce**  
- Go on the product detail page : https://demo.sylius.com/admin/products/73941/edit
- Add the association `Sticker "incidunt"` then save the product
- Click on the list to execute the ajax call and get 20 products
- When the list has been created, close it and try to remove the association `Sticker "incidunt"`
- The association is not remove and if you check your javascript console, you have an error

**Comment by UlrichHP** [comment]
This bug still occurs in Sylius 1.8
