### ISSUE TITLE
[RFC] Select product attributes causes tedious double locale management

### ISSUE THREAD

**Issue by techbech** [Sylius/Sylius#10285]
At the moment we add a translation for every locale for every value to a select product attribute. Then we have to choose this value for the product attribute to a product, but also for every locale. This causes some really tedious work when you start to have many locales. The problem is that the locale management is needed when applying attribute values for text attributes, or other single value attributes.

I have a simple solution in mind. Make a button for every select attribute `Apply for all locales` when choosing select attribute value(s) for a product. But still, this is just an easy  fix. Better solutions would probably require major restructuring.

Also the tabs solution to switch between locales in the attribute tab when editing a product, will overflow when there is enough locales present. Using a ui segment for every locale, like translations have their own foldable segment, would probably be a good solution for this.

![image](https://user-images.githubusercontent.com/1520592/55481792-6b90b300-5623-11e9-9d9b-9d28b7d1e2dd.png)

What solution do you think will be the best for these problems?

**Comment by igormukhingmailcom** [comment]
Do not stale this, please

**Comment by NoResponseMate** [comment]
Hi @techbech 

Thanks for raising this issue.
From what I can see it has been resolved in 1.9 via #12098 so I'm closing this.

Cheers 🍻
