### ISSUE TITLE
Include comment in coupon

### ISSUE THREAD

**Issue by Chrysweel** [Sylius/Sylius#10297]
**Include a comment when create coupon**

I think it may be useful to include a comment when creating a coupon.

You can use a promotion called "newspaper_times" and include coupon to each week, the promotion may vary, a week may be a promotion for the entire order, the following week may be only for the product ... etc. But the promotion is always the same, the appearances in the Times newspaper.

But if you modify the promotion, then you can not remember so you used the first coupon.

If you can create a coupon and leave a comment "discount 20% in full order"

And next week create another coupon and put a comment "valid for product B"

You can see globally, how the promotion has worked in the Times, and individually see each coupon that has worked.

Do you understand the utility it offers?

**Comment by gabiudrescu** [comment]
why shouldn't this be included in a plugin? why should it be implemented in core?

**Comment by Chrysweel** [comment]
@gabiudrescu the feature of coupons is into core of ecommerce... So I think that it feature complete the feature I dont think that is a complement...

**Comment by Chrysweel** [comment]
This issue is in voting to roadmap.
