### ISSUE TITLE
Shipping method rules

### ISSUE THREAD

**Issue by loevgaard** [Sylius/Sylius#10302]
**Describe the proposed solution**
I would love to be able to add a shipping method checker or whatever the name might be just as you can add promotion rules using tags. Could be something like:

```xml
<service id="App\Shipping\Checker\MyChecker">
    <tag name="sylius.shipping_method_eligibility_checker" />
</service>
```

I am just creating this issue so that it isn't forgotten. I will hopefully get around to creating a PR. Would be great with some feedback on naming from the Sylius team.

**Comment by gabiudrescu** [comment]
I'm glad this will land in core.
