### ISSUE TITLE
Validation groups on sylius.form.type.checkout_*

### ISSUE THREAD

**Issue by Prometee** [Sylius/Sylius#10300]
**Sylius version affected**: 1.4

**Description**  
Two `FormType` of the checkout process are declared with a `validation_group` but this validation group is not take into account because there is no parameter in the constructor of targeted classes.

Service declarations :
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/services/checkout.xml

`FormType` concerned by this issue :

 - https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/ShipmentType.php
 - https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/PaymentType.php

**Steps to reproduce**  
Trying to override the validation group corresponding to this parameters :
`sylius.form.type.checkout_payment.validation_groups` or `sylius.form.type.checkout_shipment.validation_groups`

**Possible Solution**  
Extends those `FormType` with `AbstractResourceType`.

**Comment by igormukhingmailcom** [comment]
This important bug to fix I believe. It shouldn't be stale
