### ISSUE TITLE
which version would be support all plugins

### ISSUE THREAD

**Issue by parthajudiya** [Sylius/Sylius#10305]
hello
i would like to almost plugin inbuild installed i can downmload  full package including plugins or
which version would be support all plugins and library i would like to test and learning purpose want to for social plugin and other for my internal learning for symfony so can u guide me how to do inbuild all plugin package i can or which version will support  plougins case plugisn are different different symfony version installation step so  
Thank you!

**Comment by Zales0123** [comment]
Hello @parthajudiya and welcome to the community!

Right now all our **official** plugins support Sylius `1.4` (and it will probably not change) - therefore Symfony version that can be used for them is Symfony `^3.4` or `^4.1`.

Btw, **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our [Slack](http://sylius.com/slack) (preferred) or [forum](https://forum.sylius.com/) :) We have a very active, developed community, I'm sure someone will be able to help you with your problem. Good luck 🖖
