### ISSUE TITLE
OrderBundle depends on Core component

### ISSUE THREAD

**Issue by embaya** [Sylius/Sylius#10319]
**Sylius version affected**: 1.4.1

**Description**  

`
Type error: Return value of Sylius\Bundle\OrderBundle\Controller\OrderController::getOrderRepository() must be an instance of Sylius\Component\Core\Repository\OrderRepositoryInterface, instance of Sylius\Bundle\OrderBundle\Doctrine\ORM\OrderRepository returned
`

**Steps to reproduce**  

use OrderBundle in standalone and overriding OrderRepository

**Comment by pamil** [comment]
Fixed by #10319.
