### ISSUE TITLE
full installation

### ISSUE THREAD

**Issue by parthajudiya** [Sylius/Sylius#10317]
Hello

i did try  7.3  version but some plugins not able to install due to version error
so all plugins i can download with all plugins from git repo or

what other options better for me ? 

inbuild install all pluigns possible or guide me which php version can support and install all plugins ? 
and library ?

**Comment by Zales0123** [comment]
Hello @parthajudiya! Both Sylius and our official plugins support PHP 7.2 and above. If you have any problems with installing any of these plugins, please, start a discussion on a specific repo :)

Btw - **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our [Slack](https://sylius.com/slack) (preferred) or [forum](https://forum.sylius.com). Good luck! 🖖 :)
