### ISSUE TITLE
Making a ProductVariant tracked after it has been purchased as untracked 

### ISSUE THREAD

**Issue by CoderMaggie** [Sylius/Sylius#10313]
**Sylius version affected**: all >1.0
Based on #9435 report

Right now if we make a variant, that is used in unfulfilled orders (unpaid), tracked and then we try to either fulfil or cancel these orders we would get a 500 error. This is because when we are setting current stock to 5, it makes the variants `onHand = 5` and `onHold = 0`; then we are trying to change the order state we are trying to change the value of `onHold` (while cancelling subtract from onHold and add to onHand; and while fulfilling subtract from both onHold and onHand. Read more on inventory operations [here](https://docs.sylius.com/en/1.4/book/products/inventory.html)).

**What should happen in my opinion:**

```
As an Admin

Background:

Given there is an untracked product variant „Shoe”
And 1 item of this variant was bought in the Order #0001
And the order #0001 is in state „New"

Scenario:
When I set the "Shoe" variant as tracked with the current stock set to 5
And I save it
Then I should be informed that the on hand and on hold inventory will be modified by 1 because the Variant was bought 1 time and remains unfulfilled
And this variant’s on hand value should be 6
And this variant’s on hold value should be 1
```

**Comment by gabiudrescu** [comment]
I would think the behavior below is better:

```
As an Admin

Background:

Given there is an untracked product variant „Shoe”
And 1 item of this variant was bought in the Order #0001
And the order #0001 is in state „New"

Scenario:
When I set the "Shoe" variant as tracked with the current stock set to 5
And I save it
Then I should be informed that the on hand and on hold inventory will be modified by 1 because the Variant was bought 1 time and remains unfulfilled
And this variant’s on hand value should be 4
And this variant’s on hold value should be 1
```

let's imagine the following real world situation: as a Merchant, I agree with a new supplier to start a new cooperation. I publish their products on my website and I start selling them as untracked - informing the customers that the orders will be fulfilled from our suppliers stock and shipping will take up to 3 weeks.

2 weeks after I published the products I have gathered 30 orders for 100 order items. I call my supplier and ask him to send to my warehouse 300 items - 100 to fulfill existing orders and 200 because that's what I forecast for the next week, when I'm planning a big marketing campaign on this. 

when I go to admin and I want to change the configuration of a a product from `untracked` to `tracked` and I set the inventory amount to a specific amount, I expect the system to keep that value, not increase it artificially. 

if we go with the scenario you proposed, people will be fooled into thinking they can buy 6 pieces from a product when they actually can only buy 4 - because 1 is going to be used for previous emails.

**Comment by alcaeus** [comment]
@gabiudrescu if I remember correctly, `onHand` is only decreased once something is marked as shipped. With that in mind, I'd suggest:

```
As an Admin

Background:

Given there is an untracked product variant „Shoe”
And 1 item of this variant was bought in the Order #0001
And the order #0001 is in state „New"

Scenario:
When I set the "Shoe" variant as tracked with the current stock set to 5
And I save it
Then I should be informed that the on hand and on hold inventory will be modified by 1 because the Variant was bought 1 time and remains unfulfilled
And this variant’s on hand value should be 5
And this variant’s on hold value should be 1
```

**Comment by gabiudrescu** [comment]
also, to ensure flexibility, I guess this behavior should be customizable and developers should be able to decide if they want this behavior or nothing at all. 

another solution would be:

```
As an Admin

Background:

Given there is an untracked product variant „Shoe”
And 1 item of this variant was bought in the Order #0001
And the order #0001 is in state „New"

Scenario:
When I set the "Shoe" variant as tracked with the current stock set to 5
And I save it
Then I should be informed that the on hand and on hold inventory will be modified by 1 because the Variant was bought 1 time and remains unfulfilled
And this variant’s on hand value should be 5
And this variant’s on hold value should be 0
```

and when the order gets fulfilled, to subtract from on_hand instead of on_hold.

**Comment by gabiudrescu** [comment]
@alcaeus your idea doesn't sound bad either, but how do I keep track of on_hold items and how do I fulfill them? from the initial available 5 items I got from my supplier.

**Comment by CoderMaggie** [comment]
@alcaeus you remember almost correctly. The `onHold` is decreased (but always together with `onHand`) when the order gets **paid**.
That should also solve the doubts of @gabiudrescu. As if you got 5 items from your supplier then you'd result in having 5 `onHand` and 1 `onHold` so if you this order (that put this one item onHold) gets paid, then you'd have 4 `onHand` and 0 `onHold`.
```
As an Admin

Background:

Given there is an untracked product variant „Shoe”
And 1 item of this variant was bought in the Order #0001
And the order #0001 is in state „New"

Scenario:
When I set the "Shoe" variant as tracked with the current stock set to 5
And I save it
Then I should be informed that the on hold inventory will be modified by 1 because the Variant was bought 1 time and remains unpaid
And this variant’s on hand value should be 5
And this variant’s on hold value should be 1
```

Edge case with this approach is: what if I set the current stock to 0 when making a variant tracked?
Have a look:
```
As an Admin

Background:

Given there is an untracked product variant „Shoe”
And 1 item of this variant was bought in the Order #0001
And the order #0001 is in state „New"

Scenario:
When I set the "Shoe" variant as tracked with the current stock set to 0
-----------
And I save it
Then I should be informed that the on hand and on hold inventory will be modified by 1 because the Variant was bought 1 time and remains unfulfilled
And this variant’s on hand value should be 1
And this variant’s on hold value should be 1
---OR---
And I try to save it
Then I should be informed that Variant was bought 1 time and remains unfulfilled and the current stock cannot be below that value
```

wdyt?

**Comment by gabiudrescu** [comment]
> @gabiudrescu if I remember correctly, `onHand` is only decreased once something is marked as shipped. With that in mind, I'd suggest:
> 
> ```
> As an Admin
> 
> Background:
> 
> Given there is an untracked product variant „Shoe”
> And 1 item of this variant was bought in the Order #0001
> And the order #0001 is in state „New"
> 
> Scenario:
> When I set the "Shoe" variant as tracked with the current stock set to 5
> And I save it
> Then I should be informed that the on hand and on hold inventory will be modified by 1 because the Variant was bought 1 time and remains unfulfilled
> And this variant’s on hand value should be 5
> And this variant’s on hold value should be 1
> ```

just to clear things out in my head, @alcaeus @CoderMaggie please confirm me the scenario below:

```
Background:

Given there is a tracked product variant „Shoe”
And the variant on hand value is 5

Scenario:
When I buy 1 item of this variant
And the order #0001 is in state „New"
Then this variant’s on hand value should be diminished with 1 from 5 to 4
And this variant’s on hold value should be increased with 1 from 0 to 1
But when I change the state to "Fulfilled"
And this variant’s on hold value should be diminished with 1 from 1 to 0
But this variant’s on hand value should remain 4
```

is this the current behavior? if yes, then I would implement the business case as it follows:

```
As an Admin

Background:

Given there is an untracked product variant „Shoe”
And 1 item of this variant was bought in the Order #0001
And the order #0001 is in state „New"

Scenario:
When I set the "Shoe" variant as tracked with the current stock set to 5
And I save it
Then I should be informed that the on hand and on hold inventory will be modified by 1 because the Variant was bought 1 time and remains unfulfilled
And this variant’s on hand value should be 4
And this variant’s on hold value should be 1
```

or

```
As an Admin

Background:

Given there is an untracked product variant „Shoe”
And 1 item of this variant was bought in the Order #0001
And the order #0001 is in state „New"

Scenario:
When I set the "Shoe" variant as tracked with the current stock set to 5
And I save it
Then I should be informed that the on hand and on hold inventory will be modified by 1 because the Variant was bought 1 time and remains unfulfilled
And this variant’s on hand value should remain 5
And this variant’s on hold value should remain 0
But when I change the state of the order to "Fulfilled"
Then this variant’s on hand value should be 4
And this variant’s on hold value should be 1
```

**Comment by CoderMaggie** [comment]
@gabiudrescu Neither of the scenarios you've given are true :D

Please make up a lil bit about the inventory operations in the docs: https://docs.sylius.com/en/1.4/book/products/inventory.html#inventory-on-hold

**Comment by gabiudrescu** [comment]
> Edge case with this approach is: what if I set the current stock to 0 when making a variant tracked?
> Have a look:
> 
> ```
> As an Admin
> 
> Background:
> 
> Given there is an untracked product variant „Shoe”
> And 1 item of this variant was bought in the Order #0001
> And the order #0001 is in state „New"
> 
> Scenario:
> When I set the "Shoe" variant as tracked with the current stock set to 0
> -----------
> And I save it
> Then I should be informed that the on hand and on hold inventory will be modified by 1 because the Variant was bought 1 time and remains unfulfilled
> And this variant’s on hand value should be 1
> And this variant’s on hold value should be 1
> ---OR---
> And I try to save it
> Then I should be informed that Variant was bought 1 time and remains unfulfilled and the current stock cannot be below that value
> ```
> wdyt?

for this edge case I would do this:

```
As an Admin

Background:

Given there is an untracked product variant „Shoe”
And 1 item of this variant was bought in the Order #0001
And the order #0001 is in state „New"

Scenario:
When I set the "Shoe" variant as tracked with the current stock set to 0
-----------
And I save it
Then I should be informed that the on hand and on hold inventory not be able to fulfill pending orders with the current available stock.
And this variant’s on hand value should be 0
And this variant’s on hold value should be 0
But when I try to fulfill the order I should be informed there is no available stock
And I should be informed that I either need to increase stock of product variant or disable tracking
```

it makes no sense for me to explicitly insert 0 in a form and then the system decides on my behalf that it will persist 1 or 200 in database because of some obscure reason.

**Comment by CoderMaggie** [comment]
Another edge case:
```
As an Admin

Background:

Given there is an untracked product variant „Shoe”
And 1 item of this variant was bought in the Order #0001
And the order #0001 is in state „New"

Scenario:
Given I set the "Shoe" variant as tracked with the current stock set to 1
And this variant's onHand = 1 and the onHold = 1 (due to the previous unpaid orders)

When 1 item of the 'Shoe" variant is bought in the Order #0002
And the order #0001 gets paid (the one placed before making the variant tracked)
Then the variants onHand and onHold should be both decreased to 0
But when I try to fulfil the #0002 order (the one placed after making the variant tracked)
Then I should be informed there is no available stock
And I should be informed that I either need to increase the stock of product variant or disable tracking
```

Does that sound okay?

**Comment by vvasiloi** [comment]
What about letting the admin to decide what he wants to do with the on-hold amount:
- include it in the entered on-hand
- add it to the entered on-hand
- or maybe just partially include

Also, this has to be possible to do with automation scripts.

**Comment by CoderMaggie** [comment]
@vvasiloi when should this decision happen? While saving the modified variant?

**Comment by vvasiloi** [comment]
@CoderMaggie I thought about several scenarios:
1. Always cover the on-hold amount by the entered on-hand, but inform the admin about that and show the on-hold value as a read-only input. Probably it should only be displayed when tracking is enabled and on-hand is changed, but hidden othewise.
![image](https://user-images.githubusercontent.com/7114562/56206540-51a89480-6055-11e9-94bd-49ddff272866.png)
2. When tracking is enabled and the on-hand is changed, make an AJAX request and if on-hold amount is more than 0 then display a modal (or just an extra input in the form) where the admin input how much of it is included in the entered on-hand: all, none, or a number between 0 and on-hold value.
The whole process can probably be done with JavaScript.
3. A more complex solution will be to use a strategy pattern with 3 implementation (mentioned above) included by default. It's basically an abstraction of point 2, which I believe will be more flexible to customize and use in automated processes.

**Comment by vvasiloi** [comment]
Another scenario:
If products were purchased as untracked and are still part of unfulfilled order when are marked as tracked the user should be informed about that quantity and potentially asked to take action, like adjust the onHold value the same way as the onHand (described above).

**Comment by gabiudrescu** [comment]
there is something wrong with Stalebot. he closed a ticket that is part of the roadmap.

@CoderMaggie this shouldn't be closed, right?

**Comment by lchrusciel** [comment]
Hey Gabi, it's not part of the roadmap anymore (I suppose). However, if you think it is still relevant, let's reopen this issue.

**Comment by gabiudrescu** [comment]
@lchrusciel it all boils down to make a decision about the behavior and implement it, as it is not a matter of life or death for the platform - minor issue, I would say, but quite trouble some if left undecided or undocumented.

I would go with the solution from @vvasiloi as it could be the easiest to implement. maybe we can convince him to contribute :smile:

**Comment by ehibes** [comment]
Hi, @lchrusciel can you reopen this issue ? No decision was taken about this bug.

**Comment by Rafikooo** [comment]
Hello @alcaeus,

since this problem still exists, we discussed it again and decided to put it in the backlog, fixing this 500 should be a decent starting point 💃 

Greetings,
Rafał 🚀
