### ISSUE TITLE
[Admin] Ability to override breadcrumbs

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#10321]
Hi, guys.

At admin templates, we have `@SyliusAdmin/Macro/breadcrumb.html.twig` macro which is pretty cool and save much time. 

But how about make ability to override `_breadcrumbs.html.twig` in a way when breadcrumb items from parent template will be available in all children templates?

So for breadcrumbs `1 > 2 > 3 > 4` and `1 > 2 > 3 > 4 > 5` - I can make some base `_breadcrumb.html.twig` with `1 > 2 > 3 > 4` defined, and for second one - another which override first one with just one additional item `> 5`.

**Describe the proposed solution**
For now I have no practical/working example how to implement that...

**Comment by igormukhingmailcom** [comment]
Any ideas?

**Comment by Zales0123** [comment]
@kulczy maybe you have some thought about that? The idea itself sounds nice 🖖

**Comment by vvasiloi** [comment]
Was looking into the macros for breadcrumbs and noticed an issue in :
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/UiBundle/Resources/views/Macro/breadcrumb.html.twig
Parameter `root_path` is defined, but `root_url` is used.

Now back to the actual issue.
The easiest way to achieve what you described @igormukhingmailcom is to allow passing breadcrumbs to the templates where it is built:
```twig
{% include '@SyliusAdmin/Order/History/_breadcrumb.html.twig' with {'breadcrumbs': [{ label: 'app.ui.thing'|trans }]} %}
```
```twig
{% import '@SyliusAdmin/Macro/breadcrumb.html.twig' as breadcrumb %}

{% set breadcrumbs = [
        { label: 'sylius.ui.administration'|trans, url: path('sylius_admin_dashboard') },
        { label: 'sylius.ui.orders'|trans, url: path('sylius_admin_order_index') },
        { label: '#'~order.number, url: path('sylius_admin_order_show', {'id': order.id}) },
        { label: 'sylius.ui.history'|trans }
    ]|merge(breadcrumbs|default([]))
%}

{{ breadcrumb.crumble(breadcrumbs) }}
```

**Comment by igormukhingmailcom** [comment]
@Zales0123, how about great idea proposed by @vvasiloi?

I will make PR based on `master` branch where `|merge(breadcrumbs|default([]))` will be added at every Core `_breadcrumb.html.twig`.

**Comment by vvasiloi** [comment]
Do not stale.

**Comment by vvasiloi** [comment]
@igormukhingmailcom did you my proposed solution with the new template events architecture?
