### ISSUE TITLE
Carts & Orders Documentation

### ISSUE THREAD

**Issue by rowanvanekeren** [Sylius/Sylius#10336]
Version 1.4

Below is documented

```
/** @var ChannelInterface $channel */
$channel = $this->container->get('sylius.context.channel')->getChannel();

$order->setChannel($channel);
```

But when trying to create a order programmatically those setters don't exist.

**Comment by vvasiloi** [comment]
What exception do you get?

**Comment by rowanvanekeren** [comment]
![image](https://user-images.githubusercontent.com/14889876/56734033-10556a80-6762-11e9-9cf6-924ad42760da.png)

**Comment by rowanvanekeren** [comment]
For setChannel the same 

![image](https://user-images.githubusercontent.com/14889876/56734061-25ca9480-6762-11e9-9d73-1ff2dfd27d6e.png)

**Comment by rowanvanekeren** [comment]
Im on sylius 1.4.3 btw

**Comment by vvasiloi** [comment]
Did you try to actually exectute the code?

**Comment by rowanvanekeren** [comment]
Okay you're right it's working, issue can be closed
