### ISSUE TITLE
Compiler passes takes only one tag into account

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#10334]
**Sylius version affected**: 1.3 (but way before as well)

**Description**  

During code review of #10331, we encounter the problem that the second definition of string filer was needed (https://github.com/Sylius/Sylius/pull/10331/files#diff-1cdf239bf9c8e8f33923911350380597R43) because adding the second tag to StringFilter service didn't work. It appears, that `RegisterFiltersPass` takes only the first tag into account https://github.com/Sylius/Sylius/blob/11768f43bdf14961fa78e8ddae4a02a4f2647909/src/Sylius/Bundle/GridBundle/DependencyInjection/Compiler/RegisterFiltersPass.php#L35-L40

while the second is important as well
![image](https://user-images.githubusercontent.com/6213903/56663757-1e928080-66a7-11e9-8a0f-122f117723fb.png)

Why is it need? For now, as an example same business logic, but different two different templates or form types are required.

**Steps to reproduce**  

Add the second tag to string filter service

**Affected classes**  

12 CompilerPasses:
 - [x] RegisterTaxCalculationStrategiesPass
 - [x] RegisterDriversPass (https://github.com/Sylius/SyliusGridBundle/pull/25)
 - [x] RegisterFieldTypesPass (https://github.com/Sylius/SyliusGridBundle/pull/25)
 - [x] RegisterFiltersPass (https://github.com/Sylius/SyliusGridBundle/pull/25)
 - [x] RegisterPaymentMethodsResolversPass
 - [x] RegisterGatewayConfigTypePass
 - [x] RegisterPromotionActionsPass
 - [x] RegisterRuleCheckersPass
 - [x] RegisterCalculatorsPass
 - [x] RegisterFormBuilderPass (https://github.com/Sylius/SyliusResourceBundle/issues/166)
 - [x] RegisterShippingMethodsResolversPass
 - [x] RegisterCalculatorsPass

**Possible Solution**  

We just need to iterate over attributes array and try to apply all of the tags.

**Comment by vvasiloi** [comment]
RegisterDriversPass, RegisterFieldTypesPass and RegisterFiltersPass covered in https://github.com/Sylius/SyliusGridBundle/pull/23

**Comment by pamil** [comment]
Changed the list of compiler passes to a TODO list.
