### ISSUE TITLE
Documentation on creation of custom fixture suite is severely lacking

### ISSUE THREAD

**Issue by LeanderFS** [Sylius/Sylius#10347]
**Sylius docs version**: latest

**Description**
The custom fixture documentation is referring to custom fixture suites a lot, for example showing yaml file structures with `my_suite_name` as key. The documentation is lacking the explanation on how to actually create a custom suite (where to place the file, what should the file name be etc.). Repeated attempts to place the file under different names and locations didn't reveal the custom suite when running the `sylius:fixtures:list` command.

**Comment by oallain** [comment]
Hello @LeanderFS 

Indeed the documentation may not have this level of detail.
Personally, I advise you to create a file like config/packages/fixtures.yaml (the file name does not matter, it just lets you find it). 

In this file you can do as the example of the documentation :
https://docs.sylius.com/en/1.4/components_and_bundles/bundles/SyliusFixturesBundle/architecture.html#fixtures

Keep in mind keywords words sylius_fixtures, suites and fixtures are required.

I hope my answer helped you :)

**Comment by elboletaire** [comment]
This documentation really needs to be improved... I've been reading everything in the docs about fixtures (at least everything I could find), and none of the documented approaches worked, until I found the way here.

**Comment by Rafikooo** [comment]
Hi folks, for now, as a complementary source, we encourage you to check these docs as well:
https://github.com/Sylius/SyliusFixturesBundle/blob/1.8/docs/index.md
