### ISSUE TITLE
SortByExtension.php sorts by text, not integer 

### ISSUE THREAD

**Issue by TELLO0815** [Sylius/Sylius#10369]
SortByExtension.php used for the attribute position (integer). But the outcome of the attribute sort must be 1 2 11 not 1 11 2. Means it sorts by text.

**Comment by bartoszpietrzak1994** [comment]
Hi Mike, 

Is this issue related to https://github.com/Sylius/Sylius/issues/10370? If so, please close this one :) If not, I'd be great if you provided a more detailed explanation of your problem.

**Comment by TELLO0815** [comment]
The problem is the integer. CoderMaggie, if you have only 2 you will not see it. Try to give position manually in admin like 1, 2, 20, 100 - so you will see its not integer.

And the position is everywhere wrong. Also if you list the attributes in the admin or product site. Because of the text instead integer.
