### ISSUE TITLE
Redirection to last page not working after login

### ISSUE THREAD

**Issue by FabienEssid** [Sylius/Sylius#10377]
**Sylius version affected**: 1.4.2 and more

**Description**

When I log in, I'm not redirected to the previous page. I'm directly redirected using the default route path.

**Steps to reproduce**

You can try it on Sylius demo :
- Choose a product and go to its details
- Click on log in button
- Log in with credentials (sylius@example.com, sylius)
=> You are redirected to the index of the shop

Two weeks ago, I tried and it worked on Sylius demo so I don't really understand why it doesn't work anymore.

**Possible Solution**

I did some researches :
- I have theses lines in my `security.yaml` file :
```php
security:
	firewalls:
		shop:
			form_login:
				default_target_path: sylius_shop_homepage
				always_use_default_target_path: false
				target_path_parameter: _target_path
```
[Link to the Symfony documentation about this : https://symfony.com/doc/current/reference/configuration/security.html#form-login-configuration](https://symfony.com/doc/current/reference/configuration/security.html#form-login-configuration)

- When you log in, the `onAuthenticationSuccess()` method of `AuthenticationSuccessHandler.php` file is called. Then, `parent::onAuthenticationSuccess()` is called. Inside it, `ParameterBagUtils::getRequestParameterValue()` of `ParameterBagUtils.php file` is called. Then, the first `if` statement is targeted and value returned is `$request->get($path)`. Its returns null because `_target_path` is not stored.

- I found that I could try to add these lines in `AuthenticationSuccessHandler.php` file :
```php
use TargetPathTrait;
```
And in `onAuthenticationSuccess()` method after the first `if` statement :
```php
if ($targetPath = $this->getTargetPath($request->getSession(), $token->getProviderKey())) {
	return new RedirectResponse($targetPath);
}
```

But it doesn't work because `_target_path` is not stored too.

Have you an idea?

**Comment by bartoszpietrzak1994** [comment]
Hello Fabien,

Currently, redirecting to the sylius_shop_homepage is the default and desired behavior in Sylius once you manually access the login page. If you want to access a route restricted by the firewall, you will be redirected to the login page automatically and after a successful login, you will be redirected to the route that you wanted to access.

**Comment by FabienEssid** [comment]
Hello @bartoszpietrzak1994 , thanks for your answer
The problem is that in my case, when I'm going to a route restricted by the firewall, I'm redirected to the login page, I'm logging in, and I'm been redirected to the home, not to the previous route.
