### ISSUE TITLE
Attributes order on product show page in shop

### ISSUE THREAD

**Issue by TELLO0815** [Sylius/Sylius#10370]
@ the moment the attributes are sort only on the product tab. And its not working well, because it sorts not integer. But must not be the attribute sort via position from entity? because it would be nice to get correct position sorted attributes in the admin selection and edit page of the product too?

**Comment by CoderMaggie** [comment]
If I understand correctly you would like the product attributes to be presented on the product page in the same order they are added to the product in admin, yes?

So if in admin panel to a book I add two attributes
1. Book pages
2. Book ISBN

Then on the product show page in the shop, I should see the attributes in this same order 1. Book pages and 2. Book ISBN.
