### ISSUE TITLE
Product show page improvements

### ISSUE THREAD

**Issue by Zales0123** [Sylius/Sylius#10385]
**Sylius version affected**: master

Product show page [has just been restored](https://github.com/Sylius/Sylius/pull/10296) (🎉), but it also suffers from some early-age problems. I believe we can fix it quickly and then think about some other improvements 🖖 

Simple product:
<img width="1440" alt="Zrzut ekranu 2019-05-15 o 09 29 03" src="https://user-images.githubusercontent.com/6212718/57756808-53b55000-76f4-11e9-9665-3c3a7c5043e2.png">

Variants on the configurable product:
<img width="1440" alt="Zrzut ekranu 2019-05-15 o 09 30 03" src="https://user-images.githubusercontent.com/6212718/57756824-5ca62180-76f4-11e9-9051-8fd6e2f86c28.png">

**Comment by GSadee** [comment]
I guess that it could be closed after merging https://github.com/Sylius/Sylius/pull/10388
Please reopen this issue if it is still valid.
