### ISSUE TITLE
Problem getting the default behaviour for the sylius.customer.post_register event ...

### ISSUE THREAD

**Issue by teratux** [Sylius/Sylius#10381]
**Sylius version affected**: 1.3.x

**Description**  
The **sylius.customer.post_register** event is not firing at all for the default listeners.  This is the output for the ./bin/console debug:event-dispatcher command:

```
"sylius.customer.post_register" event
-------------------------------------

 ------- ------------------------------------------------------------------------------------------- ---------- 
  Order   Callable                                                                                    Priority  
 ------- ------------------------------------------------------------------------------------------- ---------- 
  #1      Sylius\Bundle\ShopBundle\EventListener\UserMailerListener::sendUserRegistrationEmail()      0         
  #2      Sylius\Bundle\ShopBundle\EventListener\UserRegistrationListener::handleUserVerification()   0         
  #3      Redbridge\EventSubscriber\UserRegistrationSubscriber::onSyliusCustomerPostRegister()        0         
 ------- ------------------------------------------------------------------------------------------- ----------
```
Notice that listener #3 is mine.  In all three locations I issued a simple dump( "THROUGH HERE" ), and the only one I can see is mine.  The other default listeners are not firing at all.

**Steps to reproduce**  
Try to register a user ...

**Possible Solution**  
No idea ...

**Comment by Zales0123** [comment]
Hello @teratux! I've tried to reproduce the behavior but it worked for me (on the newest `master`, but as far as I see it's the same for `1.3`). You can see the listener catching the mentioned event:

```xml
<service id="sylius.listener.user_mailer_listener" class="Sylius\Bundle\ShopBundle\EventListener\UserMailerListener">
    <argument type="service" id="sylius.email_sender" />
    <argument type="service" id="sylius.context.channel" />
    <tag name="kernel.event_listener" event="sylius.user.password_reset.request.pin" method="sendResetPasswordPinEmail" />
    <tag name="kernel.event_listener" event="sylius.user.password_reset.request.token" method="sendResetPasswordTokenEmail" />
    <tag name="kernel.event_listener" event="sylius.user.email_verification.token" method="sendVerificationTokenEmail" />
    <tag name="kernel.event_listener" event="sylius.customer.post_register" method="sendUserRegistrationEmail" />
</service>
```

I've also debugged it with xdebug and the event is properly handled by the listener:

<img width="1021" alt="Zrzut ekranu 2019-05-15 o 10 00 47" src="https://user-images.githubusercontent.com/6212718/57758774-c294a800-76f8-11e9-855f-29632aa4ba44.png">

Can you confirm that it indeed does not work for you?

**Comment by teratux** [comment]
No, it still doesn't .. I've tinkered a lot with the sylius build to customize the store and probably the issue is something that got broken along the way.  Still the information from the event debug command from Symfony is giving me false information for some reason, and the fact that it does work correctly in my bundle is troublesome.  To further debug the issue I'll have to clone the same version again and compare the entire Sylius Bundle against the one I have here and see if I find anything.  For the time being I won't be able to give you more information.  I'll have to duplicate the entire message notification subsystem to use it in my bundle, it'll be the fastest solution.

**Comment by teratux** [comment]
Umm a quick followup, I downloaded the 1.3.12 tagged version and compared the EventListener directory to mine.  The main difference I noted is in the annotations.  My version has all parameters annotated, for example:

Sylius/Bundle/ShopBundle/EventListener/UserMailListener.php:

```
final class UserMailerListener extends MailerListener
{
    /**
     * @var ChannelContextInterface
     */
    private $channelContext;

    /**
     * @param SenderInterface $emailSender
     * @param ChannelContextInterface $channelContext
     */
    public function __construct(SenderInterface $emailSender, ChannelContextInterface $channelContext)
    {
        parent::__construct($emailSender);

        $this->channelContext = $channelContext;
    }

    /**
     * @param GenericEvent $event
     *
     * @throws UnexpectedTypeException
     */
    public function sendUserRegistrationEmail(GenericEvent $event): void
    {
        $customer = $event->getSubject();

        Assert::isInstanceOf($customer, CustomerInterface::class);

        $user = $customer->getUser();
        if (null === $user) {
            return;
        }

        $email = $customer->getEmail();
        if (empty($email)) {
            return;
        }

        Assert::isInstanceOf($user, ShopUserInterface::class);

        $this->sendEmail($user, Emails::USER_REGISTRATION);
    }

    /**
     * {@inheritdoc}
     */
    protected function sendEmail(UserInterface $user, string $emailCode): void
    {
        $this->emailSender->send($emailCode, [$user->getEmail()], [
            'user' => $user,
            'channel' => $this->channelContext->getChannel(),
        ]);
    }
}

```

this is the cloned version:
```
final class UserMailerListener extends MailerListener
{
    /** @var ChannelContextInterface */
    private $channelContext;

    public function __construct(SenderInterface $emailSender, ChannelContextInterface $channelContext)
    {
        parent::__construct($emailSender);

        $this->channelContext = $channelContext;
    }

    /**
     * @throws UnexpectedTypeException
     */
    public function sendUserRegistrationEmail(GenericEvent $event): void
    {
        dump ( "HERE I STAND");
        $customer = $event->getSubject();

        Assert::isInstanceOf($customer, CustomerInterface::class);

        $user = $customer->getUser();
        if (null === $user) {
            return;
        }

        $email = $customer->getEmail();
        if (empty($email)) {
            return;
        }

        Assert::isInstanceOf($user, ShopUserInterface::class);

        $this->sendEmail($user, Emails::USER_REGISTRATION);
    }

    /**
     * {@inheritdoc}
     */
    protected function sendEmail(UserInterface $user, string $emailCode): void
    {
        $this->emailSender->send($emailCode, [$user->getEmail()], [
            'user' => $user,
            'channel' => $this->channelContext->getChannel(),
        ]);
    }
}
```

It seems to me that the annotations prevented the autowiring mechanism in Symfony from working.  How can I see exactly what is the version of the Sylius install I'm using to see how far behind I am from the lastest 1.3.x version?

**Comment by teratux** [comment]
Ok found it ...

public const VERSION = '1.3.0-DEV';

I am now receiving two empty emails with no subject and something like this for a body

Example.com <teratux@gmail.com>

I noticed that there are two templates that I imagine should be used:
Sylius/Bundle/ShopBundle/Resources/views/Email/userRegistration.html.twig
Sylius/Bundle/ShopBundle/Resources/views/Email/verification.html.twig

but my version is not calling them, can you suggest where I should look for to see where this happens?

**Comment by teratux** [comment]
Problem solved ... wasn't paying attention to the redefined theme template overriding the default one.  Already sending the emails with no further issue.  The 1.3.0-DEV version it seems caused some issues with autowiring in Symfony, that was the main problem.
