### ISSUE TITLE
Can't see products in admin when different default locale than en_US is set

### ISSUE THREAD

**Issue by Holicz** [Sylius/Sylius#10398]
**Sylius version affected**: 1.5.0

**Description**  
I can't see created products in the administration, I can see them in store frontend. I checked several things:

1) I have only one locale - `cs` (configured during the installation)
2) My channel has this locale set
3) My user account has this locale set
4) My product has translation in this locale

However, when I check the DQL queries in profiler I can see there is parameter for locale with value `en_US` even though I selected `cs` as default locale during the installation and never configured anything about en_US.

**Steps to reproduce**  
1. Install clean Sylius 1.5.0
2. Run `bin/console sylius:install`
3. Provide default currency `CZK` and default locale `cs`
4. Finish other installation steps
5. Go to the administration
6. Create taxon
7. Create product, set it's main taxon
8. Go to `/admin/products/` or `/admin/products/taxon/1`
9. No products can be seen on this page

**Comment by vvasiloi** [comment]
Check the value of the `locale` parameter: `php bin/console debug:container --parameter locale`
You have to set it manually.

**Comment by Holicz** [comment]
Forgot about than one, changing it in `config/services.yaml` worked. But maybe it's not a great UX behavior and it could be set during installation?

**Comment by vvasiloi** [comment]
No, it can't be set during the installation, but it should not break the product listing in the admin panel anyway.

**Comment by vvasiloi** [comment]
https://github.com/Sylius/Sylius/blob/d76b120075abf1eacfb3076175159db50b8be281/src/Sylius/Bundle/CoreBundle/Resources/config/services.xml#L163
This line caused your issue, but I don't see other sources of default locale.
Also, this is documented (see the first warning message): https://docs.sylius.com/en/1.5/book/installation/installation.html
So it's not a bug.

**Comment by Holicz** [comment]
I actually read the warning message before I posted the issue, but I get it like "`sylius:install` will set the locale and currency. If you want to change the default values later, do it in `Configuration > Channels` and in `config\services.yaml`".

Maybe a message during the command `sylius:install` would improve the DX. Something like "You may also need to change the Symfony locale in `config\services.yaml`."

**Comment by Zales0123** [comment]
The difference between a default locale set in `services.yaml` and the locale set in administration panel (as an entity) can be indeed confusing. Would you be able to open a PR with a proposed message during installation? Then we could iterate over this solution in comments :) Thanks! 🚀
