### ISSUE TITLE
Select non-default language during installation create some troubles

### ISSUE THREAD

**Issue by Mauricette** [Sylius/Sylius#10411]
**Sylius version affected**: 1.5

**Description**  
Hello, when i install sylius from scratch `sylius:install` and choose other language than default (en_US), i can't add values to "select" type attributes (when i save, the attribute is saved but not the values)

**Steps to reproduce**  
1. sylius:install 
2. enter EUR to currency
3. enter fr_FR as language
4. go to admin/product-attributes/select/new
5. fill fields and try to add one or more values
6. save

the attribute is ok but values doesn't appear.

**Comment by vvasiloi** [comment]
See https://github.com/Sylius/Sylius/issues/10398 and https://github.com/Sylius/Sylius/pull/10399
