### ISSUE TITLE
Styling issue for SearchBar

### ISSUE THREAD

**Issue by StephanePate** [Sylius/Sylius#10425]
**Sylius version affected**: 1.6.0-DEV

**Description**  
Styling Issue for SearchBar

<img width="1351" alt="Capture d’écran 2019-06-04 à 13 33 31" src="https://user-images.githubusercontent.com/6461942/58876161-8e941d80-86cd-11e9-937c-5b05eef8bf9a.png">

**Comment by Zales0123** [comment]
Thank you for reporting 🖖 Could you provide a resolution on which this issue happens?

**Comment by StephanePate** [comment]
MacOSX Mojave 10.14.5 Firefox 67.0.1 : the issue exists ...
MacOSX Mojave 10.14.5 Safari 12.1.1 : no problem, styling ok !

**Comment by CoderMaggie** [comment]
As far as I can see it is fixed by #10498 :) Please reopen if still an issue.
