### ISSUE TITLE
Exception on cache:clear --env=prod

### ISSUE THREAD

**Issue by StephanePate** [Sylius/Sylius#10428]
**Sylius version affected**: 1.6.0-DEV

**Description**  
Property "currencyCode" does not exist in class "Sylius\Component\Order\Model\OrderInterface"

<img width="716" alt="Capture d’écran 2019-06-05 à 11 47 07" src="https://user-images.githubusercontent.com/6461942/58947665-a7153e00-8788-11e9-8247-91289308e709.png">

**Comment by vvasiloi** [comment]
https://github.com/Sylius/Sylius/issues/10424
