### ISSUE TITLE
[RFC] Using the declared addresses when ordering

### ISSUE THREAD

**Issue by Wasper** [Sylius/Sylius#1042]
I want to add address selection in ordering process (addressing step).
I can enter addresses in the user account now, but I can not use them later.

In "Shipping address" box I want to add a dropdown list of defined addresses.
In addition, I want to use "default shipping address" and fill out a form on startup.
If the address is different than we have in the list, then we can select the checkbox "Save Address" and add it to the list.

More interesting is the billing address :)
Currently, there are two ways in my head.... 
1. We could remove "default billing address" option in user accout. Then we could use the current version of the choice of billing address ("Use different" checkbox)
2. We could add the same dropdown in "Billing address" box. But then box should always be visible, because it will be always filled (If we define default address).
   It is more problematic option.

I would like to know your opinions. Which solution will be better??

**Comment by michalmarcinkowski** [comment]
Already implemented in https://github.com/Sylius/Sylius/pull/6526
