### ISSUE TITLE
Sale Shipments error 500

### ISSUE THREAD

**Issue by keeper7** [Sylius/Sylius#10431]
**Sylius version affected**: 1.5 and master

**Description**  
Sales shipments show error 500 when you show order details at shipmentwith state cart.

**Steps to reproduce**  
Add some product to cart.
Go to admin Sales -> Shipments
Find shipment with state cart and click on Show order details button

**Possible Solution**  
Solution 1: Do not list shipment with state cart
Solution 2: Update templates to show not copleted orders .

**Comment by lchrusciel** [comment]
The first solution should be applied 👍

**Comment by francesco-laricchia** [comment]
Solution 1 should be preferred, since there's little interest in checking the shipping state of orders that aren't completed (if they will be). Also, in my opinion default ordering should be from most recent order on.

**Comment by pamil** [comment]
Fixed by #10605.
