### ISSUE TITLE
Allow default currency to be defined in the parameters or in an argument

### ISSUE THREAD

**Issue by remyvanlerberghe** [Sylius/Sylius#10454]
Hello :wave:

At the moment, the default currency is `USD` and is defined in [this file](https://github.com/Sylius/Sylius/blob/1.5/src/Sylius/Bundle/CoreBundle/Installer/Setup/CurrencySetup.php) which means it is mandatory to answer the currency question in the setup to have another currency set as default.

I think there should be another way to set it, either via a `currency` key in the parameters, the same way as the default locale is handled, or via an argument in the setup comment.

Thanks

**Comment by Zales0123** [comment]
Hello @remyvanlerberghe, It seems like a good idea, can speed up setting a simple store with no interaction mode in simple cases. I leave it open for the discussion though, as I would like to see other opinions (cc @Sylius/core-team)

**Comment by remyvanlerberghe** [comment]
I can take care of the PR when it is decided on your side

**Comment by remyvanlerberghe** [comment]
@Zales0123 Any updates on this subject ? Should I propose a PR ?

**Comment by Zales0123** [comment]
Sorry for the long response time, feel free to open a PR with your proposition :)

**Comment by remyvanlerberghe** [comment]
I close the issue as this has been implemented in #10707
