### ISSUE TITLE
The "en_US" locale is unavailable in this channel.

### ISSUE THREAD

**Issue by Den-Uchiwa** [Sylius/Sylius#10469]
Hello, i have one problem when i want to pay its wirting : 
The "en_US" locale is unavailable in this channel.
i have error like on this pictures what i can doing?

![Capture d’écran de 2019-06-25 22-32-56](https://user-images.githubusercontent.com/48279209/60131254-38307100-9799-11e9-9e48-1cee2ecd428d.png)

**Comment by vvasiloi** [comment]
Use GitHub issues only to discuss about Sylius bugs, new features and documentation. 
For this kind of questions about Sylius usage, please use
any of the support alternatives described here: http://docs.sylius.com/en/latest/support/index.html

**Comment by Den-Uchiwa** [comment]
ok but in forum when i register dont receive mail :/ and slack no answer :/

**Comment by vvasiloi** [comment]
You can close the issue now.
