### ISSUE TITLE
New Frontend

### ISSUE THREAD

**Issue by gety9** [Sylius/Sylius#10476]
In last year's "Sylius Intro Webinar" Paweł Jędrzejewski mentioned that you are working on New Frontend. 
Is there update on that ?

**Comment by pierre-H** [comment]
This question is very relevant with the very slow development of Semantic UI.

**Comment by pierre-H** [comment]
Related to #10463

**Comment by pierre-H** [comment]
I find this : https://www.master.demo.sylius.com/admin/
So it's I think for the 1.6.0 release.
And I've got to say that's a very nice frontend !

**Comment by gety9** [comment]
@pierre-H do you mean Paweł Jędrzejewski meant admin front end and now shop front end ?

**Comment by pierre-H** [comment]
@gety9 yes : the shop front-end is generally always customized so I don't think that there is a need to release a new shop front-end.
Maybe he spoke about https://github.com/Sylius/BootstrapTheme .
