### ISSUE TITLE
LAMP deployment issue

### ISSUE THREAD

**Issue by mkic** [Sylius/Sylius#10480]
**Sylius version affected**: 1.5

**Description**  
I have been working on a Sylius project for a couple of months and I am now trying to deploy it to a server. Giving the fact that I did a theme I thought I would install a standard sylius app then use my theme rather than uploading all of my project on the server.

**Steps to reproduce**  
I've followed this exact steps :
https://docs.sylius.com/en/1.5/book/installation/installation.html
I'm using a lamp stack on a ubuntu 18 server deployed on Vultr.
Once I'm done with the installation, I edit my etc/apache2/sites-avalailbe/http.conf file to change the Document root folder, which gives that :
```
<VirtualHost *:80>
    #ServerAdmin webmaster@example.com
    #ServerName host.example.com

    DocumentRoot /var/www/html/project/public

    SetEnvIf Request_URI "^/favicon\.ico$" dontlog
    SetEnvIf Request_URI "^/robots\.txt$" dontlog

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    DirectoryIndex index.php index.html
</VirtualHost>
```

When I then go on my server (xx.xx.xx.xx since I don't have a domain name), I have an apache 404 error, but with the Sylius favicon.

Interesting note, when I forget to edit the .env file to add my database password, I get a symfony error saying there is an error accessing the database, which means the Sylius application is getting requested.

I've tried multiple work around but I am stuck at the moment, any help would be much appreciated

**Comment by Zales0123** [comment]
Hello @mkic and welcome to the community! 🚀 **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our [Slack](http://sylius.com/slack) (preferred) or [forum](https://forum.sylius.com/) ;) We have a very active, developed community, I'm sure someone will be able to help you with your problem. Good luck :)
