### ISSUE TITLE
Shipping Calculator Form not correctly handling Form Types using CollectionType

### ISSUE THREAD

**Issue by markbeazley** [Sylius/Sylius#10487]
**Sylius version affected**: 1.4.6

**Description**  
If a ShippingCalculator form type uses CollectionType in the form builder the form isn't being handled correctly, the add button shows but has no Javascript click handlers bound so it just acts like a link to #. If you edit a shipping method set to use the calculator it works, but not when you create a new shipment method, and it breaks if you pick a different calculator from the drop down then switch back. 

**Steps to reproduce**  
1. Add a custom ShipmentCalculator that has a form type using the CollectionType (Simple example):

services.yaml:
```
    App\ShippingCalculator\BandedCalculator:
        tags:
            -
                {
                    name: sylius.shipping_calculator,
                    calculator: "banded",
                    label: "Banded",
                    form_type: App\Form\Type\BandedShippingCalculatorType
                }
```

BandedCalculator.php:
```
<?php declare(strict_types=1);

namespace App\ShippingCalculator;

use Sylius\Component\Shipping\Calculator\CalculatorInterface;
use Sylius\Component\Shipping\Model\ShipmentInterface;

/**
 * Class BandedCalculator
 */
class BandedCalculator implements CalculatorInterface
{

	public function calculate(ShipmentInterface $subject, array $configuration): int
	{
		return 1000;
	}

	public function getType(): string
	{
		return 'banded';
	}
}
```

BandedShippingCalculatorType.php:
```
<?php declare(strict_types=1);

namespace App\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * Class BandedShippingCalculatorType
 */
class BandedShippingCalculatorType extends AbstractType
{
	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		$builder
			->add('bandedShippingCalculatorBands', CollectionType::class,[
				'entry_type' => BandedShippingCalculatorBandType::class,
				'entry_options' => ['label' => false],
				'allow_add' => true,
				'allow_delete' => true,
			]);
	}
}
```

BandedShippingCalculatorBandType.php

```
<?php declare(strict_types=1);

namespace App\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Webmozart\Assert\Assert;

/**
 * Class BandedShippingCalculatorBandType
 */
class BandedShippingCalculatorBandType extends AbstractType
{
	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		Assert::keyExists($options, 'currency');

		$builder
			->add('weight', NumberType::class)
			->add('price', MoneyType::class, [
				'label'    => 'sylius.ui.price',
				'required' => true,
				'currency' => $options['currency'],
			]);
	}

	public function configureOptions(OptionsResolver $resolver): void
	{
		$resolver->setRequired(['currency']);
		$resolver->setDefaults([
			'currency'   => 'USD',
		]);
	}
}
```

2. Click create on the shipping methods page, while setting up the method you will be unable to click the add button, save the method with no configuration in the calculator.

3. Edit the method you have just created, the calculators form will now function correctly.

4. While editing the method if you change the calculator drop down to another calculator and back the form will be broken again, only showing a non functioning add button and all child rows wont be shown, if you save changes now the configuration for the calculator will be emptied,

**Comment by vvasiloi** [comment]
Can you reproduce this on a fresh Sylius-Standard instance?
I used the CollectionType (and FixedCollectionType) a lot of times and never had issues like that.

**Comment by markbeazley** [comment]
Just used the same code on a clean download and install of 1.5.2 and the exact same thing happens.

**Comment by markbeazley** [comment]
As we have updated our site to Sylius 1.6.1 I decided to give this another try, but I am seeing the same issue, the CollectionType form works fine if you edit a shipping method that has already been saved with that calculator, but not when creating a new shipping method or editing one using another calculator, in those cases the Add button just adds a # to the url and takes you to the top of the page.

I've just created a new clean 1.6.1 project following the [instructions on the download page](https://sylius.com/download/), adding a `composer require symfony/web-server-bundle` to add the Symfony web server, copied the 3 files across and added the same block to services.yaml, and am seeing the same issue.

**Comment by Norel** [comment]
Here is a quick fix
BandedShippingCalculatorType.php:
`<?php declare(strict_types=1);

namespace App\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * Class BandedShippingCalculatorType
 */
class BandedShippingCalculatorType extends AbstractType
{
	public function buildForm(FormBuilderInterface $builder, array $options)
	{
		$builder
			->add('bandedShippingCalculatorBands', CollectionType::class,[
				'entry_type' => BandedShippingCalculatorBandType::class,
				'entry_options' => ['label' => false],
				'allow_add' => true,
				'allow_delete' => true,
                                **'label' => false**
			]);
	}
}`
For some reason the collection type label seems to prevent the add button to trigger correctly the event.

**Comment by Norel** [comment]
It's due to the javascript prototype handler not triggering the form collection handler. A quick fix would be to manually call the CollectionForm() function after the prototype container is filled with the data.

sylius-prototype-handler.js
```
/*
 * This file is part of the Sylius package.
 *
 * (c) Paweł Jędrzejewski
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

import $ from 'jquery';

const methods = {
  init(options) {
    const settings = $.extend({
      prototypePrefix: false,
      containerSelector: false,
    }, options);

    const show = function show(element, replace) {
      const selectedValue = element.val();
      let prototypePrefix = element.attr('id');
      if (settings.prototypePrefix != false) {
        ({ prototypePrefix } = settings);
      }

      const prototypeElement = $(`#${prototypePrefix}_${selectedValue}`);
      let container;

      if (settings.containerSelector) {
        container = $(settings.containerSelector);
      } else {
        container = $(prototypeElement.data('container'));
      }

      if (!container.length) {
        return;
      }

      if (!prototypeElement.length) {
        container.empty();
        return;
      }

      if (replace || !container.html().trim()) {
        container.html(prototypeElement.data('prototype'));
        container.find('[data-form-type="collection"]').CollectionForm(); // Force the new data to be handled by the collection form script
      }
    };

    return this.each((index, element) => {
      show($(element), false);
      $(element).change((event) => {
        show($(event.currentTarget), true);
      });
    });
  },
};

$.fn.handlePrototypes = function handlePrototypes(method, ...args) {
  if (methods[method]) {
    return methods[method].apply(this, args);
  } else if (typeof method === 'object' || !method) {
    return methods.init.apply(this, [method, ...args]);
  }

  $.error(`Method ${method} does not exist on jQuery.handlePrototypes`);

  return undefined;
};
```
There's probably a better and cleaner way to do it but I hope this can help resolve the issue.

**Comment by ehibes** [comment]
Same issue here.  Let's say we have 3 calculator methods, and the second one contains a form with a collectionForm field.
Making a new shipping method, you choose the second calculator method, the add button is not bound, and no event is fired (normally collection form event are bound).
