### ISSUE TITLE
Make it possible to have no shipping methods in fixtures

### ISSUE THREAD

**Issue by TiMESPLiNTER** [Sylius/Sylius#10490]
**Sylius version affected**: 1.4

**Description**  
You can't use Order fixtures if you don't have any shipping method fixtures.

**Steps to reproduce**  

Create a fixture suite with orders but without shipping methods.

**Possible Solution**  

#10489

**Comment by igormukhingmailcom** [comment]
I guess you should specify channel with `skipping_shipping_step_allowed` and `skipping_payment_step_allowed` options set to `true`. (Never tried, but probably should work)

**Comment by TiMESPLiNTER** [comment]
Setting the channel to `skipping_shipping_step_allowed: true` works still this line here is a problem:

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php#L220

Once I remove it everything works fine.

**Comment by igormukhingmailcom** [comment]
> https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php#L220

I believe that a bug and fixture should apply `TRANSITION_SKIP_SHIPPING` transition when `isShippingMethodSelectionRequired` is false and select random shipping only before `TRANSITION_SELECT_SHIPPING` transition applied.

**Comment by pamil** [comment]
Fixed by #10618.
