### ISSUE TITLE
LazyOption::randomOne* functions uses findAll which loads all data

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#10493]
**Sylius version affected**: any

**Description**  
`LazyOption`'s `randomOne`, `randomOneOrNull` and `randomOnes` functions uses `findAll` which trying to load all data from repository. This become a problem when you have thousands of records in that repository.

**Steps to reproduce**  
Try to build multi-channel (5-10 channels) store fixtures with close-to-realworld set of taxons (100-200), with products (even few per taxon) with size options (few sizes per product). After that getting random product variant will take infinity time/resources.

**Possible Solution**  
Not sure, maybe one of:
- Select random chunks per one db request and only then pass to php's `array_rand`
- Check table records count - if there not much records - use `findAll` as before, if more than X000 - then use `rand()` in db query.

**Comment by igormukhingmailcom** [comment]
Not stale...

**Comment by TheMilek** [comment]
Closing as it should be fixed by https://github.com/Sylius/Sylius/pull/15086 😅 

cheers! 🍻
