### ISSUE TITLE
Option's values undeletable

### ISSUE THREAD

**Issue by systemasis** [Sylius/Sylius#1049]
I was just managing some options for my products, on the sylius dashboard. But when I wanted to delete some values of an option, I didn't find how. Nothing would help me to erase some particular values. I tried to just leave the box blanck, hoping that Sylius would understand I didn't want them anymore. But it just answered to me that it couldn't be null.

Also, I tried to deleted an entire option. But the following error occured :

```
An exception occurred while executing 'DELETE FROM sylius_option WHERE id = ?' with params [7]:

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`sylius_dev`.`sylius_prototype_option`, CONSTRAINT `FK_B458391BA7C41D6F` FOREIGN KEY (`option_id`) REFERENCES `sylius_option` (`id`))
```

It is caused by the relation of the options with the prototypes. In my opinion, the delete button shouldn't appear, or be clickable, if the option is used in a prototype. Or maybe just to show a warning to explain why it wouldn't work.

**Comment by pjedrzejewski** [comment]
We now display a message when you try to delete an option that is used by a product.
