### ISSUE TITLE
Incorrectly mapped validation for product attribute value in product with multiple locale.

### ISSUE THREAD

**Issue by aakashtushar** [Sylius/Sylius#10523]
**Sylius version affected**: all

**Description**  
Validation errors are incorrectly mapped in ProductAttributeValue during product save.

![Attribute](https://i.ibb.co/dkBs35w/screenshot-localhost-2019-07-12-16-03-28.png)
![Attribute Value Validation](https://i.ibb.co/pPg4bwn/screenshot-localhost-2019-07-12-16-04-00.png)

**Steps to reproduce**  
1. Create two or more locales in one channel.
2. Add multiple attributes in a product.
3. Click create / save.

**Comment by Roshyo** [comment]
Hi.

Any update on this ? And hack to solve it ?

**Comment by matjazbo** [comment]
I can confirm this bug is still present in version 1.8.5
