### ISSUE TITLE
Why the product list is filter on locales (in admin panel) ?

### ISSUE THREAD

**Issue by gaugau3000** [Sylius/Sylius#10545]
**Sylius version affected**: v1.5.2

**Description**  
if application locales (based on config/services.yaml) and product locales (based i think on sylus_product_translation) are different then the products related don't appear in product administration panel.

_controller :	"sylius.controller.product:indexAction"
_route	: "sylius_admin_product_index"

Two sql requests filters on locales :
** SELECT s0_.code AS code_0, s0_.created_at AS created_at_1, s0_.updated_at AS updated_at_2, s0_.enabled AS enabled_3, s0_.id AS id_4, s0_.variant_selection_method AS variant_selection_method_5, s0_.average_rating AS average_rating_6, s1_.name AS name_7, s1_.slug AS slug_8, s1_.description AS description_9, s1_.meta_keywords AS meta_keywords_10, s1_.meta_description AS meta_description_11, s1_.id AS id_12, s1_.short_description AS short_description_13, s1_.locale AS locale_14, s0_.main_taxon_id AS main_taxon_id_15, s1_.translatable_id AS translatable_id_16 FROM sylius_product s0_ INNER JOIN sylius_product_translation s1_ ON s0_.id = s1_.translatable_id AND (s1_.locale = ?) ORDER BY s0_.code ASC LIMIT 10 **

** SELECT count(DISTINCT s0_.id) AS sclr_0 FROM sylius_product s0_ INNER JOIN sylius_product_translation s1_ ON s0_.id = s1_.translatable_id AND (s1_.locale = ?) **

Have a nice day.

**Comment by rendler-denis** [comment]
Similar issue with this one:  #10584
