### ISSUE TITLE
Cannot override ShopBillingData as it's not a mapped-superclass

### ISSUE THREAD

**Issue by mlazze** [Sylius/Sylius#10563]
**Describe the proposed solution**
Map ShopBillingData to be a MappedSuperclass as any other entity, this way we can override its properties.

**Describe alternatives you've considered**
I tried to override both Channel and ShopBIllingData xml mapping, but I couldn't get the bundle ShopBillingData not to create its own table, so that I had two shop_billing_data tables in the db.

**Comment by igormukhingmailcom** [comment]
It was fixed?

**Comment by Gounlaf** [comment]
> It was fixed?

Nope. Still an entity, declared as final via comments (but not in code because Doctrine extends it).

**Comment by Zales0123** [comment]
Indeed, it should be changed 👍 Are you willing to open a PR with such a fix? Thanks in advance!

**Comment by Gounlaf** [comment]
> Indeed, it should be changed +1 Are you willing to open a PR with such a fix? Thanks in advance!
I can try
