### ISSUE TITLE
Make Billing Address the main address during checkout and shipping address optional

### ISSUE THREAD

**Issue by AndreasA** [Sylius/Sylius#10575]
Hi,

I really think that the billing address should be the main address during a checkout and the shipping address optional (and taken from the billing address if not available).

These are the reasons why:
- Products might not be shipped (e.g. downloadable products). They still require a billing address though.
- Customer might retrieve the product from a store and only pay and reserve it using the online shop.
- The billing address is less likely to change for a customer. However, shipping addresses can be different during each order. This is the case for B2C and B2B but especially in B2B it is possible to have a lot of shipping destinations but the billing address will always be the same.
- B2B accounts might not even let one change the billing address as those are verified by the shop and only shipping addresses can be defined.

It shouldn't be that difficult to change it. However, it might be a breaking change.

**Comment by vvasiloi** [comment]
I had to change that for the project I am currently working on, so the customer fills in the billing address first, then uses it as shipping address or fills in a new one.
I can't remember a project where it was the other way.

**Comment by vvasiloi** [comment]
Do no stale.

**Comment by loevgaard** [comment]
I totally agree with this. In Denmark I have never seen a store with the shipping address being the main address.

**Comment by stefandoorn** [comment]
Same for The Netherlands I think.
