### ISSUE TITLE
TaxiationBundle can't be used as a standalone Bundle

### ISSUE THREAD

**Issue by hmonglee** [Sylius/Sylius#10582]
**Sylius version affected**: 1.5.3

**Description**  
TaxationBundle must not depends of Core component.

**Steps to reproduce**  
See https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/TaxationBundle/Resources/config/services.xml, in line 20 `<parameter key="sylius.tax_calculation_strategy.interface">Sylius\Component\Core\Taxation\Strategy\TaxCalculationStrategyInterface</parameter>
`

**Possible Solution**  
Add interface in Taxiation component/bundle

**Comment by hmonglee** [comment]
Hey @Zales0123 , this should be in CoreBundle ?
`<service id="sylius.registry.tax_calculation_strategy" class="Sylius\Component\Registry\PrioritizedServiceRegistry">
            <argument>%sylius.tax_calculation_strategy.interface%</argument>
            <argument>Tax calculation strategy</argument>
        </service>`

**Comment by lchrusciel** [comment]
Yes, it should be fixed.

Can you open a PR?

**Comment by pamil** [comment]
Fixed in #10995.
