### ISSUE TITLE
AdminApi: Serialized Order lacks _links property

### ISSUE THREAD

**Issue by leflings** [Sylius/Sylius#10585]
**Sylius version affected**: 1.5.2 (this is version the version I've tested on, though I suspect it will affect older versions aswell)

_disclaimer: I'm new to Sylius, and work, so far, exclusively against the API, so I apologize in advance for any wrong terminology, or lack of understanding of Sylius at a deeper level_

**Description**  
The `Order` entity never includes a `_links` property in their serialized format, neither in list- or detailed-format.

**Steps to reproduce**  
Make a GET request to the `/api/v1/orders/` or `/api/v1/orders/XX` and inspect that the JSON object representing an order has no `_links` property.

**Possible Solution**  
From my digging around, I think the issue is due to the lack of a `relations` property for the
serialization format defined in `AdminApiBundle/Resources/config/serializer/Model.Order.yml`.

**Comment by vvasiloi** [comment]
Do not stale.

**Comment by lchrusciel** [comment]
@leflings are you willing to open a PR with fix? Adding `relations` should do the trick ;)
