### ISSUE TITLE
Excessive object-graph expansion in API / too much data included

### ISSUE THREAD

**Issue by leflings** [Sylius/Sylius#10586]
**Sylius version affected**: 1.5.2 (this is version the version I've tested on, though I suspect it will affect older versions aswell)

_disclaimer: I'm new to Sylius, and work, so far, exclusively against the API, so I apologize in advance for any wrong terminology, or lack of understanding of Sylius at a deeper level_

In general I've opened this issue to raise my concern with the amount of data included in the response for certain requests. Specifically, to what level of depth and detail, the object graph for a given entity/resource is expanded.

I'll highlight the problem using screenshots from a response to the `/api/v1/products/XXX` endpoint, running on a `sylius/sylius-standard` installation as described in [installation guide](https://docs.sylius.com/en/latest/getting-started-with-sylius/installation.html). Portions of the response is folded. Notice the line numbers on the left.

![product_details_associated_products_explosion](https://user-images.githubusercontent.com/658790/62765468-7905f000-ba90-11e9-8111-80be345fb04a.PNG)

The response consists of  _5353_ lines, totaling _306 kB_ data!

The main issue in this example is the associated products, which are serialized _in full detail_ (because, I imagine, _any_ "product" for this requests are _all_ "requested" to be serialized in full detail), covering ~4500 lines.

From the same response, I'll also highlight taxon serialization.

![product_details_excessive_taxon_hierachy_details](https://user-images.githubusercontent.com/658790/62765974-9dae9780-ba91-11e9-88ff-cba15d99f50a.PNG)

Although, not as expansive, line wise, as the associated products, still about ~500 lines for `productTaxons` and ~190 lines for `mainTaxon`. Is it important/necessary to know the, hold on, _children of the root, of the children of the taxons, to which this product is related_?

I know that there is tradeoff between how much data, besides just 'foreign key' data, you want to sent along with related entities to avoid excessive n+1 request behaviour, but to me, this goes _way_ in the opposite direction - I don't think I would ever care about the structure of the hierachy of associated taxons _when I'm asking for product details_. If you end up relying on that data, I would say you have a data acquisition problem in your application.

**Possible Solution**  
From what little I've gathered digging around various `XxxBundle/Resources/config/serializer/Model.Yyy.yml`, I suspect the problem connects to how exposed properties are defined by `groups` and how these are then adhered to when serializing. I imagine the active group (`Detailed`, `Default` etc) is active throughout the entire "chain of serialization". So if I want a `Detailed` `Product` I get `Detailed` versions of every kind of associated object.

I imagine there needs to be a way to configure, for example, the `Model.Product.yml`, such that: when viewing a product detailed, include the associated products in the _default_ "group"/view (or another, suitable group). Same for `productTaxons` and `mainTaxon` etc.

**Comment by vvasiloi** [comment]
@leflings what do you thing about a feature to include/exlclude graph nodes, like in GraphQL?

**Comment by leflings** [comment]
> 
> 
> @leflings what do you thing about a feature to include/exlclude graph nodes, like in GraphQL?

@vvasiloi From my limited understanding, with zero practical usage of GQL, this is the kind of problem GQL was a solution to. So anything resembling that functionality would be a "solution" / win. This lends to power to the consumer, to decide which data to include.

But I expect it would be "the Sylius way" to be able to provide a reasonable standard configuration, without the consumer needing to make that decision.

**Comment by vvasiloi** [comment]
@leflings Would you like craft a reasonable configuration?

**Comment by leflings** [comment]
> 
> 
> @leflings Would you like craft a reasonable configuration?

@vvasiloi Are you asking if I'd like to craft the reasonable configurations? As a default, I would think that nothing but the "main entity" should be serialized in detail, and associated entities should be serialized by a group that's even less inclusive than the 'default' group (including only things like id, code, name, slug and translations). But to me, what exactly the configuration should be, is secondary to _if the configuration can actually be stated_.

So one solution could be to allow a way, where one could specify by what level of detail associated objects are exported. For example, something like the following, would determine to level of detail for all associated entities on Product:

```
Sylius\Component\Core\Model\Product:
    ...
    associated_objects_detail:
        - from: [Default, Detailed]
          to: Minimal
    properties:
        ...
        ...
```

This would limit the configuration to specifiy one setting, that would govern all properties with related entities.

Alternatively, I imagine allowing such specification on a per-property basis. Something like the following example.

```
Sylius\Component\Core\Model\Product:
    ...
    properties:
        shortDescription: ...
        averageRating: ...
        images: ...
        channels:
            expose: true
            type: array
            groups:
                -   from: [Detailed]
                    to: Default
                -   from: [Default]
                    to: Minimal
        ...
```

That is, when serializing a `Product` in:
- `Detailed` format => include the channels in `Default` format
- `Default` format => include the channels in `Minimal` format
- other formats => `channels` property not included

**Comment by mamazu** [comment]
Yes, you are completely right the product endpoint needs to be minified. For example taxons can be excluded because they can have their own endpoint.

One thing that can also be considered is, if we are calling the api with a given channel, we should only get information based on the channel and the locale that we provide. So the translations would be merged into the main object.

**Comment by leflings** [comment]
So `jms/serializer` has (of course) had to deal with this sort of issue.

[Overriding Groups of Deeper Branches of the Graph](http://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies#overriding-groups-of-deeper-branches-of-the-graph)

From what I understand, this is not configurable via the usual Annotations/YAML configurations, but is specified in the `SerializationContext` for any given serialization "action".

Can any guide me further in how/if this is plugable in the current architecture?

**Comment by vvasiloi** [comment]
It's the same groups list, but nested.
Unfortunately you can only pass a flat list of groups through `Accept` header, but I thing it can't be hard to make it accept nested lists.

**Comment by vvasiloi** [comment]
It's the same groups list, but nested.
Unfortunately you can only pass a flat list of groups through the `Accept` header, but I think it can be made to accept nested lists.

**Comment by leflings** [comment]
It took me a little while to grok what you meant by the accept header :)

For those not familiar, the `RequestConfigurationFactory` from `sylius/ResourceBundle` looks for `Accept`-headers where it's possible to specify
- by which API version the request should be serialized (aside; is this not potential "security" vulnerability if at some point v1 of an api was completely deprecated, i.e. no routing, but v1 could still be specified?)
- by which groups the request should be serialized

For example, adding `Accept: g=Autocomplete` to `POST /api/v1/products/` would save you the overhead of a *huge* response when creating products (particularly if product has many taxons, has associations (associated products), or your taxon tree is "big"). I often just care about the `id` when creating a resource.

I've tested the [group overriding strategy](http://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies#overriding-groups-of-deeper-branches-of-the-graph), and can confirm it works as I've hoped. To go back to the example from the initial issue, the following code can make sure associated products are serialized in a sane manner.

```
$product = $this->productRepository->findOneByCode($slug);

$context = SerializationContext::create();
$context->setGroups(array(
    'Detailed',
    'associations' => array(
        'Default',
        'associatedProducts' => array('Autocomplete')
    ),
));

$json = $this->serializer->serialize($product, "json", $context);
```

Response:

```
{
    ...
    "associations": [
        {
            "id": 4,
            "type": {
                "id": 1,
                "code": "similar_products",
                "translations": {
                    "en_US": {
                        "locale": "en_US",
                        "id": 1,
                        "name": "Similar products"
                    }
                },
                "_links": {
                    "self": {
                        "href": "/api/v1/product-association-types/similar_products"
                    }
                }
            },
            "associatedProducts": [
                {
                    "name": "Mug \"non\"",
                    "id": 2,
                    "code": "4a658137-ddb6-35ab-80c0-f67e67033813"
                },
                {
                    "name": "Mug \"quos\"",
                    "id": 3,
                    "code": "0c5c4215-b10d-3f0d-ac53-9c900f099280"
                },
                {
                    "name": "Mug \"itaque\"",
                    "id": 13,
                    "code": "821daa6f-dd4e-3e10-b1b9-3ebe8af8da35"
                }
            ]
        }
    ],
    ...
}
```

The issue remains, that this cannot by specified via the serializer annotations/yaml configuration - perhaps we should raise the issue on that repository.

However, if, as @vvasiloi suggests, the functionality in `RequestConfigurationFactory` was extended to accept a new kind of `Accept`-header containing a detailed specification of groups (ala what I've specified in my serializtion example), we would land on some sort of lightweight-GraphQL functionality, where API consumers could specify how serialization should happen on a per-request basis. It would be limited to work with the groups already defined in serialization config, so knowledge of these configs would be required to make use of the new header.
