### ISSUE TITLE
No shipping confirmation email when pressing `Ship` on shipments grid

### ISSUE THREAD

**Issue by disperate** [Sylius/Sylius#10581]
**Sylius version affected**: 1.5.3

**Description**  
When pressing `Ship` on the order page, a confirmation email is being sent.
When pressing `Ship` on the shipments grid, no shipment confirmation emails is being sent.
In both cases, the order is displayed as `Shipped`.

**Steps to reproduce**  
1. Create an order
2. Go to /admin/shipments/ and press Ship. => Order is displayed as `Shipped` but no email is sent.
3. Create a second order
4. Go to /admin/orders/{orderId} and press Ship  => Order is displayed as `Shipped` and a email is sent.

**Possible Solution**

**Comment by lchrusciel** [comment]
We are missing the proper event (or new tag on the listener).

In this configuration: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminBundle/Resources/config/routing/shipment.yml#L16-L27

We are missing this declaration:
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminBundle/Resources/config/routing/order.yml#L104

So this service will be called:
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminBundle/Resources/config/services/listener.xml#L18-L21

Would you like to fix it? Preferably with behat scenario :)

PS. If one will be there, please also add `section` section ;)
