### ISSUE TITLE
Additional options for grid actions: background(or color), enabled, visible

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#10592]
**Describe the proposed solution**
I believe its a good idea to add next options to all grid actions configuration/templates (to default, show, create, delete, etc):
- `background` (or `color`)
- `enabled|default(true)`
- `visible|default(true)`

**Additional context**
Once plugin developer wants to add some custom action to grid (which have background different than default or which have conditional visibility or enable) - he should implement new template/action for grid. Much easier to add that to core. 

It just a MUST for `default` action, but for another actions (`show`, `create`, `delete`) it also very nice to have.

This new feature not break BC.

I will prepare PR if you guys ok with an idea. 
Thanks

UPD: Actually `class` can be used now to specify button background (color)... So only two options are the subject.

**Comment by costinel-draculet** [comment]
I agree that would be nice to have some extra features on grid actions, like:

```
enabled|default(true)
visible|default(true)
```
