### ISSUE TITLE
Official province codes of austria are not working

### ISSUE THREAD

**Issue by alexander-schranz** [Sylius/Sylius#10604]
**Sylius version affected**: 1.5.3

**Description**  

Austria official province codes not accepted when creating a new province.

**Steps to reproduce**  

The official province codes of austria are following this pattern:

AT-1, AT-2, AT-3, ...

See https://en.wikipedia.org/wiki/ISO_3166-2:AT

There are also countries having a mix of numbers and letters see: https://en.wikipedia.org/wiki/ISO_3166-2:VN

Which will not work when you try to create one with a number behind. It errors with you need to use the following pattern e.g. (DE-BY)

I once created a list of the codes but its not up2date as provinces are changing rapidly around the world: https://github.com/alexander-schranz/iso-3166-2/tree/master/subdivisions

**Possible Solution**  

It should accept numbers and letters as second part of the code.

**Comment by pamil** [comment]
Fixed by #10739.
