### ISSUE TITLE
Replace gulp with Webpack (encore)

### ISSUE THREAD

**Issue by jelen07** [Sylius/Sylius#10656]
:wave: Hi guys! At the moment Sylius using gulp for building assets - admin and shop.
Our feature request is replacing the gulp process with webpack encore.

The installation will be the same as now
```
$ yarn install
$ yarn build
```

## Todo
- rewrite the build using webpack for admin and
- shop
- remove gulp from project
- **[optional]** rewrite Sylius JavaScripts for webpack (frontend JS is in a deplorable state)

## Profit
- One modern build tool (when using [Sylius/BootstrapTheme](https://github.com/Sylius/BootstrapTheme) you have two build tools in your project)
- Consistency
- Get rid of deprecated errors
- Sylius will switch to Bootstrap anyway

**Comment by kulczy** [comment]
@jelen07 there is still some work to be done, but we have already started testing the encore with the sylius-standard https://github.com/Sylius/Sylius-Standard/pull/354

**Comment by gabiudrescu** [comment]
this should be reopen, as the replacement of Gulp with Webpack is not complete yet. 

issues I bumped into:
 - the package.json file still uses Gulp by default for running various commands (especially from docker)
 - docker files should be updated to avoid copying Gulp files and copy webpack instead

**Comment by ProcesJohnson** [comment]
How do we do to be able to use that?

**Comment by jakubtobiasz** [comment]
Some time has passed since this issue has been opened, but after 3 years I can close this issue as Sylius 1.12 fully supports Webpack 🎉. In case of any problems with new Webpack, I encourage you to open new issues and ping me there :).
