### ISSUE TITLE
Whole ShippingBundle in autoload-dev

### ISSUE THREAD

**Issue by mmenozzi** [Sylius/Sylius#10657]
Is it ok that the whole ShippingBundle is in the `autoload-dev` of the `composer.json` file?

https://github.com/Sylius/Sylius/blob/master/composer.json#L239

I know that it's not a big problem because it is also in the `autoload` with the `"Sylius\\Bundle\\": "src/Sylius/Bundle/"` mapping but it sounds weird that the whole bundle it's also in the `autoload-dev`. Especially because other bundles have only the `spec` classes in their `autoload-dev` mapping.

**Comment by Zales0123** [comment]
It's a typo, for sure it should be `src/Sylius/Bundle/ShippingBundle/spec/` 👍

**Comment by mmenozzi** [comment]
Ok but there's no `spec` folder inside `src/Sylius/Bundle/ShippingBundle` (only `test`). So maybe that line should be removed?

**Comment by lchrusciel** [comment]
I would vote for line removal
