### ISSUE TITLE
Save position button on product variants doesn't work

### ISSUE THREAD

**Issue by Latrellx** [Sylius/Sylius#10678]
**Sylius version affected**: 1.5. 

**Description**  

I tried to reposition product variants using the save position button and changing the order of the variants inputing different numbers in widgets. After I proceeded with submit button page just reloaded and result was the same like before submit.

I went to demo.sylius and tried there to check also and the same issue happened.

**Steps to reproduce**  

**Possible Solution**

**Comment by GSadee** [comment]
Hi @Latrellx, are you sure that this feature does not work? I've just checked that on [demo](demo.sylius.com) and everything seems to work correctly.

Before changes:
![image](https://user-images.githubusercontent.com/6140884/65240812-6d233a00-dae2-11e9-96c0-7b619d0b61f9.png)
![image](https://user-images.githubusercontent.com/6140884/65240839-7ad8bf80-dae2-11e9-9af9-6d3aab52789b.png)

After change (set `0` for `Basic_regular-variant-2`):
![image](https://user-images.githubusercontent.com/6140884/65240853-8330fa80-dae2-11e9-80d3-57712c5ab611.png)
![image](https://user-images.githubusercontent.com/6140884/65240866-8af09f00-dae2-11e9-878d-5e80704ee327.png)
As you see, `Basic_regular-variant-2` moved to the first place and it is also displayed as the default one in shop.

Could you check that again, and if sth is wrong, provide a scenario?

**Comment by Latrellx** [comment]
Hi @GSadee , maybe they fixed it meanwhile but on demo it didnt work same issue like when i pulled repo to local.

**Comment by Latrellx** [comment]
I tested it once more and now everything is ok, thank you for your brief explanation and sorry for any inconvenience.
