### ISSUE TITLE
Error database update 1.5 to 1.6

### ISSUE THREAD

**Issue by imajim** [Sylius/Sylius#10673]
Hello,

i'm updated sylius 1.5 to 1.6 
` sylius/sylius": "~1.5.0@rc" changed to "sylius/sylius": "~1.6.0"`
A little composer update

But when i loggin to admin i'v got a error with database

```
Erreur
An exception occurred while executing 'SELECT t0.type AS type_1, t0.path AS path_2, t0.id AS id_3, t0.owner_id AS owner_id_4 FROM sylius_avatar_image t0 WHERE t0.owner_id = ?' with params [1]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'delannoy_voyage_dev.sylius_avatar_image' doesn't exist
```
No migrations on the update.

`bin/console doctrine:migrations:migrate`

> No migrations to execute.

**Comment by imajim** [comment]
Resolved.
i'm forgotten :
`bin/console make:migration`
and
`bin/console doctrine:migrations:migrate`

**Comment by Zales0123** [comment]
You can also copy a migration file, as explained in [UPGRADE file](https://github.com/Sylius/Sylius/blob/master/UPGRADE-1.6.md) ;)
