### ISSUE TITLE
Grid Field Ordering by position

### ISSUE THREAD

**Issue by arnaudroulee** [Sylius/Sylius#10676]
**Sylius version affected**: 1.4

**Description**
The ordering of field is wrong, field with position 11 will be display before field with position 2 cause of function strcasecmp in Sylius\Bundle\UiBundle\Twig\SortByExtension

**Steps to reproduce**  
Create a Grid with field position 2 ans field position 11

echo strcasecmp(12, 2);
echo "\n";
echo strcasecmp(1, 2);
echo "\n";
echo strcasecmp(2, 1);
echo "\n";
echo strcasecmp(2, 2);

**Possible Solution**  
Replace 
$result = strcasecmp($firstProperty, $secondProperty);
By 
$result = ($firstProperty-$secondProperty) ? ($firstProperty-$secondProperty)/abs($firstProperty-$secondProperty) : 0;

**Comment by Zales0123** [comment]
I've just checked it and it's indeed a bug 🖖 Are you willing to open a PR @arnaudroulee with a fix? Thanks in advance!

**Comment by pamil** [comment]
It should be changed from `strcasecmp` to `strnatcasecamp` (https://www.php.net/manual/en/function.strnatcasecmp.php).

**Comment by GSadee** [comment]
Fixed by #11511
