### ISSUE TITLE
Sylius Plugin Store

### ISSUE THREAD

**Issue by slince** [Sylius/Sylius#10677]
Hello

I think manual rebuid caching after installing plugins is a bit inconvenient; maybe these actions can be done automatically; including downloading plugin source code, rebuild cache;

Users just need to click "install it" in admin panel.

Regards

**Comment by Zales0123** [comment]
Hello @slince! Thank you for your opinion.

The plugins marketplace is for sure the thing we would like to have in our ecosystem. We understand how significant improvement in DX it would be.

However, such a project is not a trivial work, as you can imagine, and requires a lot of time and resources to be appropriately created. Believe me, we've been talking about it a lot :) The only thing I can promise **right know** is, that we, as @Sylius/core-team keep in mind that community desires such a platform. I hope we could do something like this sooner than later 🖖

**Comment by slince** [comment]
Thanks! I am also a symfony developer, and I understand that doing this dynamic plugging on symfony is very difficult, which may require sylius to redesign the plug-in mechanism instead of using symfony bundle.

But for an e-commerce platform, sylius has a steep learning curve, which makes it difficult for ordinary users to learn. So we need to make it so simple that the user can extend it with just a few clicks on the web.
Anyway, thank you for your efforts.

@Zales0123

**Comment by CoderMaggie** [comment]
Hi @slince I have changed the title of your issue to be using the codename under which the plugins marketplace will exist in the ecosystem :)

This is a tiny hint, that something is happening on that 😉

**Comment by slince** [comment]
Great! Is this feature already under development? Which branch has the relevant code? I would like to try it.  😄

**Comment by CoderMaggie** [comment]
Hi, just to be clear,
I've meant something near [this comment](https://github.com/Sylius/Sylius/issues/10677#issuecomment-532588931), rather than the initial "click to install a plugin" feature of yours.

Slowly, but surely. :)

For now we are thinking of _just_ a marketplace of plugins, so that everyone interested in selling their plugins will be able do so via an official platform.

**Comment by CoderMaggie** [comment]
As we have opened the [Sylius Store](https://sylius.com/plugins/) recently, I am closing this issue. 

We are not planning to implement the "click to install a plugin" functionalities, as Sylius is a platform of a different type than for example Woocommerce. We have always been a platform for responsible development, where you have at least some consciousness while installing extensions. While Sylius is highly tested and testable we highly recommend this workflow, where you know what is exactly changing in the platform while installing plugins if you at least see their code. 🖖 🚀 

✌️ What is Sylius Store? [Read this blog post.](https://sylius.com/blog/sylius-store-now-open-the-marketplace-of-extensions/)
