### ISSUE TITLE
PercentAttribute is being Rounded on Edit Product Form

### ISSUE THREAD

**Issue by panigrc** [Sylius/Sylius#10683]
**Sylius version affected**: 1.5.0

**Description**  
When using a percent attribute and typing a decimal value i.e. 12.5 the value is persisted as float value correctly in the database (0.125) but in the reloaded Product Edit Form the form value is being rounded.

**Steps to reproduce**  
Edit a product with a percentage attribute, and give a decimal value.

**Comment by panigrc** [comment]
So I found out that it's not a bug but a feature :grinning: !

Actually is the _View Format_ which is responsible for this result. Take a look into the screenshot.

![grafik](https://user-images.githubusercontent.com/645895/65408426-83344180-dde5-11e9-9ae1-4e7349e6d07a.png)

It would be usefull to change the view by using a `addViewTransformer` so the real data is shown.

**Comment by jelen07** [comment]
Hi, is there any intention to add decimal AttributeType?
