### ISSUE TITLE
Changing the data processed by Shipments grid

### ISSUE THREAD

**Issue by Floflinou** [Sylius/Sylius#10685]
Hi,

I have a grid that shows every order no matter what the payment status is. I'd like it to show only the orders where payment_status = paid.

Thanks in advance !

**Comment by lchrusciel** [comment]
Hello Florian 👋,

you will have to configure query builder for such a case. 

However, please join our [slack](https://sylius-slackin.herokuapp.com/) and look for some help on our #support channel or on StackOverflow. We are using issues only for bug reports and feature requests.

I hope you will solve your problem pretty quickly ;)
