### ISSUE TITLE
Empty variants list on product media association dropdown

### ISSUE THREAD

**Issue by LucaGallinari** [Sylius/Sylius#10684]
**Sylius version affected**: 1.6.0

**Description** 
An admin user with a locale code (sylius_admin_user[localeCode]) different from the "store locale", cannot associate a product media to any of its variants because the dropdown shows "no results found".
Example: the website has a single locale "it_IT" and the admin user have "it" as locale code.

**Steps to reproduce**  
* Create admin user with locale different from the locale of the store (i assume a single locale is configured in the store, i haven't tested other cases)
* Create a configurable product with some variants and some media
* Try to associate a media of the configurable product to one of the variants, but you can't because it shows "no results found"

**Comment by dimaip** [comment]
I can reproduce this. Website locale is `ru_RU`, when admin's locale is `ru` the dropdown is empty.

"sylius/sylius" version: "v1.5.3",
