### ISSUE TITLE
Infinite loop on order fixture after update to 1.4.8

### ISSUE THREAD

**Issue by ostrolucky** [Sylius/Sylius#10682]
**Sylius version affected**: 1.4.8

**Description**  
sylius:fixtures:load is stuck on this loop after updating from 1.3.18
https://github.com/Sylius/Sylius/blob/70ed4dffcc90b77d9754c2db9f757af6d7bf0fe3/src/Sylius/Bundle/CoreBundle/Fixture/OrderFixture.php#L171-L177

When this happens, this is the state of relevant database tables at this point
```
select * from sylius_product_channels c RIGHT JOIN sylius_channel c2 ON c.channel_id=c2.id WHERE c.channel_id IS NULL \G
*************************** 1. row ***************************
                    product_id: NULL
                    channel_id: NULL
                            id: 1
          shop_billing_data_id: NULL
             default_locale_id: 1
              base_currency_id: 1
           default_tax_zone_id: 1
                          code: default
                          name: Default
                         color: LightGreen
                   description: NULL
                       enabled: 0
                      hostname: localhost
                    created_at: 2019-09-19 14:57:09
                    updated_at: 2019-09-19 14:57:09
                    theme_name: NULL
      tax_calculation_strategy: order_items_based
                 contact_email: NULL
skipping_shipping_step_allowed: 1
 skipping_payment_step_allowed: 0
 account_verification_required: 1
*************************** 2. row ***************************
                    product_id: NULL
                    channel_id: NULL
                            id: 5
          shop_billing_data_id: NULL
             default_locale_id: 1
              base_currency_id: 4
           default_tax_zone_id: 2
                          code: ISK
                          name: ISK
                         color: Teal
                   description: NULL
                       enabled: 0
                      hostname: localhost
                    created_at: 2019-09-19 14:57:09
                    updated_at: 2019-09-19 14:57:09
                    theme_name: NULL
      tax_calculation_strategy: order_items_based
                 contact_email: NULL
skipping_shipping_step_allowed: 1
 skipping_payment_step_allowed: 0
 account_verification_required: 1
2 rows in set (0.00 sec)
```

So there are some channels which are not assigned to any products which is the reason this loop happens. What did you guys change and what do we need to change?

**Steps to reproduce**  
Our fixture file:
[fixtures.yml.zip](https://github.com/Sylius/Sylius/files/3631270/fixtures.yml.zip)

**Comment by ostrolucky** [comment]
I've bisected this to a1df268ea80493e343f9cff25ab1e098a7b92737 @Zales0123

**Comment by Zales0123** [comment]
The idea of this change was, that we should not create orders in fixtures that contains items with products that are not available in their channels. And it totally makes sense, as you don't want to have orders placed in a channel containing products that you're not able to buy in it 🚀 

There are probably some problems with other fixtures configuration. `sylius_product_channels` table is used to relate products with channels (each product should be available in at least one channel to be buyable). I also wonder how you achieved null values on `channel_id` and `product_id`, as [the mapping file](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Product.orm.xml#L40) clearly says they are not nullable 🤔 

Let me know if it makes anything at least a little bit clearer :)

**Comment by ostrolucky** [comment]
> we should not create orders in fixtures that contains items with products that are not available in their channels.

That makes sense, but doesn't work with channels not used by any products. Also I assume inifnite loop was not by design, there should be exception instead

> I also wonder how you achieved null values on channel_id and product_id

It's not null in database. It's null in query result because no sylius_product_channels record for given sylius_channel was found. I should have probably used `select c2.*` to be less confusing.

What action do I need to take?
