### ISSUE TITLE
Wrong calculated subtotal in admin order show page

### ISSUE THREAD

**Issue by Tomanhez** [Sylius/Sylius#10697]
**Sylius version affected**: 1.6.0

As administrator, in Order show page table, amount subtotal is wrong calculated 

![Screenshot 2019-09-24 at 16 06 38](https://user-images.githubusercontent.com/39232096/65520296-a7784700-dee7-11e9-9921-93deac21ccb4.png)

**Comment by pamil** [comment]
Related: https://github.com/Sylius/Sylius/pull/10725

**Comment by CoderMaggie** [comment]
Closing in favour of #11112
