### ISSUE TITLE
Change price of order item

### ISSUE THREAD

**Issue by imajim** [Sylius/Sylius#10703]
Sylius 1.6 and Symfony 4.3.4

Hello,
I would like to change the price and the name of order item but it's not working.
In Database , the quantity is changed, the label product too, but not the price.
see me code below : 
 
```
/** @var OrderInterface $order */
        $order = $this->orderFactory->createNew();

        /** @var ChannelInterface $channel */
        $channel = $this->channelContext->getChannel();
        $order->setChannel($channel);


        $order->setLocaleCode($localeCode);

        $currencyCode = $this->currencyContext->getCurrencyCode();
        $order->setCurrencyCode($currencyCode);

        /** @var CustomerInterface $customer */
        $customer = $this->customerRepository->findOneBy(['email' => $reservationVoyage['coordonneesFacturation']['email']['first']]);

        $order->setCustomer($customer);

        /** @var ProductVariantInterface $product */
        $product = $em->getRepository(ProductVariant::class)->findOneBy(['id' => 1]);

        /* @var \App\Entity\Order\OrderItem $orderItem */
        $orderItem = $this->cartItemFactory->createNew();
        $orderItem->setVariant($product);
        $orderItem->setVariantName('test Label');
        $orderItem->setProductName('test Label');
        $orderItem->setUnitPrice(99999);

        $this->orderItemQuantityModifier->modify($orderItem, 4);
        
        $order->addItem($orderItem);
        $this->orderProcessor->process($order);
        $this->orderRepository->add($order);
        
```
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/13310096/65611873-bc221100-dfb3-11e9-9147-914d5849e6da.png">
<img width="2072" alt="image" src="https://user-images.githubusercontent.com/13310096/65611908-c80dd300-dfb3-11e9-94ec-b4f423f018dd.png">

thanks ^^

**Comment by vvasiloi** [comment]
It's overriden in `Sylius\Component\Core\OrderProcessing\OrderPricesRecalculator`. Try to set it immutable.

**Comment by imajim** [comment]
@vvasiloi thanks ^^
> Try to set it immutable.
any example ? i don't understand --!

**Comment by imajim** [comment]
Oki thanks ^^

**Comment by vvasiloi** [comment]
Example: `$orderItem->setImmutable(true);`

> We use GitHub issues only to discuss about Sylius bugs, new features and documentation. 
> For this kind of questions about Sylius usage, please use
any of the support alternatives described here: http://docs.sylius.com/en/latest/support/index.html

So please close the issue.
