### ISSUE TITLE
[Bug] TaxonInterface should extend TimestampableInterface

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#10728]
**Sylius version affected**: master (1.7, 1.6, etc)

**Description**  
[TaxonInterface](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/Model/TaxonInterface.php) should extend `TimestampableInterface` as [Taxon](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/Model/Taxon.php) uses `TimestampableTrait` and have proper fields.

**Steps to reproduce**  
- When you define argument as `TaxonInterface $taxon`, your PHPStorm will not show `getUpdatedAt`/`setUpdatedAt` and `getCreatedAt`/`setCreatedAt` at autocomplete.

**Comment by pamil** [comment]
Fixed in #10734.
