### ISSUE TITLE
[Critial Bug] Strict use_authorize option value check lead to Payum fail

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#10720]
**Sylius version affected**: 1.6

**Description**  
You have next recommendation at `docs/cookbook/payments/authorize.rst`:
```php
class MyGatewayGatewayConfigurationType extends AbstractType
// ...
                ->add('use_authorize', HiddenType::class, [
                    'data' => 1,
                ])
```

This form will store field at `sylius_gateway_config.config` database field as `"use_authorize": 1`. 

But at [this line](https://github.com/Sylius/Sylius/commit/6c748c9aec878687c610bd440aac9635143df0c3#diff-063b340e70ed54a7454a9c76bd3ef84eR158) **check become strict** and we expecting for `true` (strictly `boolean`) rather than `1`. 

Since that point, **Payum no longer works** and Sylius redirects user to `capture` action rather than `authorize`.

**Steps to reproduce**  
- Add a payment method at admin that have `use_authorize` field at its form type
- Check at database that field stored as integer rather than boolean (`select * from sylius_gateway_config;`)

**More context**
This issue was faced at https://github.com/Setono/SyliusQuickpayPlugin. After upgrading from Sylius 1.5 to 1.6 payment stopped work and throw exception because it become redirecting to capture payment before authorize (e.g. before even user can type his payment card information). 

Currently, we can make payment works by changing `use_authorize` value to `true` at fixtures. But if we put something like `'data' => true,` at `...GatewayGatewayConfigurationType` - we still have an issue because it store value at database like this: `"use_authorize":"1"` (e.g. `true` stored as string).

**Possible Solution**  
1. **Less strict comparison** at https://github.com/Sylius/Sylius/commit/6c748c9aec878687c610bd440aac9635143df0c3#diff-063b340e70ed54a7454a9c76bd3ef84eR158
2. As far as proposed `HiddenType` example doesn't support booleans and `'data' => true,` will not help, probably we should **expect `integer` (`0`/`1`) from `use_authorize`**?
3. Or **provide valid MyGatewayGatewayConfigurationType example** how to define `use_authorize` form field that stored as `boolean` in database

**Comment by lchrusciel** [comment]
As a hotfix, we can just make a comparison less strict. Patch version should be published soon. I'm wondering if there is no better way to solve it (for example with some configuration options), I would have to dig into it.
