### ISSUE TITLE
Sylius should not ask for database erase confirmation on sylius:install

### ISSUE THREAD

**Issue by ostrolucky** [Sylius/Sylius#10722]
**Sylius version affected**: 1.4.7

**Description**  
When running sylius:install, execution unnecessary stops on

```
Creating Sylius database for environment dev.
It appears that your database already exists.
Warning! This action will erase your database.
Would you like to reset it? (y/N) y
 4/4 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 100%

Loading sample data for environment dev.
Warning! This action will erase your database.
Continue? (y/N) y
```

There is no need for this confirmation, since blank database was created in previous step. This is annoying because we often run this command to re-provision our dev environment.

**Steps to reproduce**  
`sylius:install`

**Comment by CoderMaggie** [comment]
Well, I do not agree it is an unnecessary check. You can run `sylius:install` on an already existing project, where you've already had a database and you might not want the command to reset it.

It's what is actually happening in the output you've pasted. Have a look:
```
...
It appears that your database already exists.
...
```

**Comment by ostrolucky** [comment]
I think there is a misunderstanding. First question is allright. But in case user selects Y, as an yes, erase the database, following command (sample data import one) shouldn't ask same thing again.
