### ISSUE TITLE
Adding the free products

### ISSUE THREAD

**Issue by denis019** [Sylius/Sylius#10730]
Currently we can not set the price of the product to be 0.

Is there some way to achieve this in Sylius?
I found some old feature request https://github.com/Sylius/Sylius/issues/361 but without guidelines how to achieve this.

**Comment by F-Locos** [comment]
@denis019 Did you tried the last comment from the request #361 ? Override the validation?

**Comment by TiMESPLiNTER** [comment]
@F-Locos the last comment in that issue (if we're talking about the same one) -> https://github.com/Sylius/Sylius/issues/361#issuecomment-453871553 is a question, not a solution.

**Comment by denis019** [comment]
I have followed the steps mentioned in the sylius documentation:
 https://docs.sylius.com/en/1.6/customization/validation.html
but without success, the solution is similar to https://github.com/Sylius/Sylius/issues/361#issuecomment-453871553

**Comment by denis019** [comment]
working solution will be the same as https://github.com/Sylius/Sylius/issues/361#issuecomment-453871553
with different parameter.
`parameters:
    sylius.form.type.product_variant.validation_groups: ['app']`
