### ISSUE TITLE
No more error badges on Product form

### ISSUE THREAD

**Issue by Roshyo** [Sylius/Sylius#10745]
**Sylius version affected**: 1.6.0

**Description**  
Since the new look of admin, the DOM has changed and the `addTabErrors()` method can no longer work on product page. That's why there are no more error badges on product admin form.

**Steps to reproduce**  
GO to https://demo.sylius.com/admin/products/new/simple and submit the empty form.

**Possible Solution**  
Either rely on specific classes to trigger JS (such as `js-my-class`) or rework `sylius-compound-form-errors` to take in note the new DOM structure.

**Comment by loic425** [comment]
@Roshyo @pamil I am on it!
