### ISSUE TITLE
Sylius 1.6 - Symfony MakerBundle Errors

### ISSUE THREAD

**Issue by DOCS-kdu3** [Sylius/Sylius#10751]
**Sylius version affected**: 1.6.0

**Description**  
The Symfony MakerBundle is incompatible with Sylius, thus leaving no way for a developer to create entities via CLI. It errors out after input of the entity name.

**Steps to reproduce**  
```
composer create-project sylius/sylius-standard acme
cd acme
php bin/console sylius:install
composer require symfony/maker-bundle
php bin/console make:entity
```

```
Class name of the entity to create or update (e.g. GentleJellybean):
 > AppBundle\Test

 created: src/Entity/AppBundle/Test.php
 created: src/Repository/AppBundle/TestRepository.php

In ORMTranslatableListener.php line 71:
                                                  
  Call to a member function isAbstract() on null  
                                                  
```

**Additional Details**  
https://github.com/Sylius/SyliusResourceBundle/issues/103
There is an open issue here with a non solution that creates a massive application breaking migration file. There is also an additional bug that requires --no-debug to run the make:entity command.

**Comment by Zales0123** [comment]
As the bug is strictly connected with a SyliusResourceBundle, I think we should keep the discussion/potential fixes propositions in the linked issue. Thanks! 🖖
