### ISSUE TITLE
Bring back the Order Discount line into order summary page

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#10753]
**Sylius version affected**: 1.6.0 (demo)

Testing the order discount implementation after #10261, I figured out the following thing that is rather non-standard:

![image](https://user-images.githubusercontent.com/4903082/66484144-bd206b80-eaa6-11e9-8078-616152e97e8f.png)

I have tested an order with a discount that applies to the whole order. On the demo, this shows clearly to the customer as order level discount (in the summary), and the unit prices stay unchanged.

In the admin though, a 'distributed order discount' seems there, and no discount summary at order level (which I expected close to 'Shipping total' line or 'Items total' line). I have never seen a similar implementation.

I don't think the order lines should be adjusted or any discounts should be distributed over order lines - only discounts at order item / unit level should be applied there. The order level discounts should be applied at the order level. 

This is also how many shops use it as far as I know - they want to give a discount on the whole cart and not on single order lines. Prices stay the same, as for the follow-up order the prices are not changed - maybe only no discount anymore.

**Comment by loevgaard** [comment]
I have had a talk with Stefan on Slack, and I believe that **at least** there should be a summary of the discount. UX wise everybody would expect that

**Comment by stefandoorn** [comment]
As @loevgaard also mentioned in our chat - the distribution makes sense to use for returns, refunds, etc. In that case reason could be to distribute that also properly. But indeed, I probably miss a summary so both things can live next to each other. Basically what a customer sees, should also be seen for administrators (which are often not more technical than customers).

**Comment by CoderMaggie** [comment]
The core idea behind this rework was to make the order line consistent (so it is now possible to calculate the item total adding and multiplying from left to right :) ).

Though after some time I am also missing the order discount summarized value.

Putting it on the roadmap then :)
