### ISSUE TITLE
MySql error if Entity class (extending ResourceInterface) has a property whose name is "reserved"

### ISSUE THREAD

**Issue by marcis101** [Sylius/Sylius#10765]
**Sylius version affected**: 1.6.0.

**Description**  
If you create a new Resource Entity and add, for example, a property named "key" application fails (MySql sintax error) when creating a new object from admin form, because field name is not escaped at query.

**Steps to reproduce**  
See above

**Possible Solution**  
Escape field names

**Comment by vvasiloi** [comment]
https://doctrine-project.org/projects/doctrine-orm/en/2.6/reference/basic-mapping.html#quoting-reserved-words
