### ISSUE TITLE
Creating cart item

### ISSUE THREAD

**Issue by bochkarev-artem** [Sylius/Sylius#10767]
**Sylius version affected**: 1.6.x

**Description**  
Its more like a strange behaviour and lack of documentation:
https://docs.sylius.com/en/1.6/api/carts.html#creating-a-cart-item
Here its states how to create a cart item and what response you would get as a return. What is not stated: what will happen if you send this request twice. In fact what is happening: after successfull creation of a cart item and calling endpoint for the 2nd time you will create the second item, but with the same variant id! (i would expect either 1. an error response, since cart item with such id is already created and you can delete or change quantity of it OR 2. adding up quantity for already existing item in the cart). I cant even imagine how the cart should like with 2 line of same product and of different quantity.

**Steps to reproduce**  
```
POST /api/v1/carts/{cart-id}/items/
{
    "variant": "code",
    "quantity": 2
}
```

```
POST /api/v1/carts/{cart-id}/items/
{
    "variant": "code",
    "quantity": 3
}
```

`GET /api/v1/checkouts/{cart-id}`
you will get to products with different cart item ids, but the same variant id. One item will be in quantity of 2, another - 3.

**Possible Solution**  
I would expect either of those:
- an error response, since cart item with such id is already created and you can delete or change quantity of it 
- (preferred) adding up quantity for already existing item in the cart

**Comment by lchrusciel** [comment]
Hey Artem,

even if it seems counter-intuitive, it was designed to behave this way. This is the POST action, which should create a new object always. We could be of course more clear about it in the docs. You should use PUT action to update item quantity. 

One thing that we could consider is this validation exception when you are about to create another item with the same variant id. 

On the side note, we are still not supporting a PUT action for object creation (it could be `createOrUpdate`) which could be also a possible solution in this case. However `id` handling that comes from the client may be tricky.
