### ISSUE TITLE
Resolving locales in Shop after a locale being disabled by Admin

### ISSUE THREAD

**Issue by ikakarov** [Sylius/Sylius#10763]
**Sylius version affected**: 1.5+

**Description**  
If you use some language in frontend, after disable this language project throw exception:
language code is not define.

**Steps to reproduce**  
1. Create some language in admin area.
2. Go to frontend/public part of store.
3. Change language with last created language
4. Disable this language form channel .
5. Refresh publish/frontend page.

**Possible Solution**  
In my case, just i catch this exception and redirect to main channel language.

Sorry for my bad english.

**Comment by pamil** [comment]
Fixed by #11068.
