### ISSUE TITLE
Custom business logic : don't find directories

### ISSUE THREAD

**Issue by kmleroi** [Sylius/Sylius#10778]
**Sylius docs version**: 1.6 

hello, I start with Sylius 1.6, I discover the documentation, and I would like to implement a new delivery system but I can not find the directories follow 'src / ShippingCalculator directory' and App \ Form \ Type, to which files it corresponds in the version 1.6? thank you

**Comment by markbeazley** [comment]
You can just create the folders in the src/ directory if they don't exist already so from the root of your project just create:

    src/ShippingCalculator
    src/Form
    src/Form/Type

**Comment by kmleroi** [comment]
a big thank-you

**Comment by lchrusciel** [comment]
Hello @kmleroi,

would you mind if I will close this issue?
