### ISSUE TITLE
Problem loading assets with Assetic in dev environment

### ISSUE THREAD

**Issue by alexsegura** [Sylius/Sylius#1077]
Hello, 

First of all, I'm new to Sylius and Symfony :-)

When installing Sylius in dev mode, the assets (css/js) in backend area were throwing 404 errors: this is because the URLs look like `/app_dev.php/assets/...`

Of course I had run `app/console assetic:install` and `app/console assetic:dump`

After a little bit of research I got it working by changing `app/config/config_dev.yml`

```
assetic:
    use_controller: true
```

becomes

```
assetic:
    use_controller: false
```

After removing the `app/cache/dev` folder it was working. 

Should `use_controller` be set to `false` ? Or maybe I'm missing something related to assets.

**Comment by pjedrzejewski** [comment]
We will drop Assetic. See #3646.
