### ISSUE TITLE
Possibility to generate admin path at setup to avoid brutforce on /admin

### ISSUE THREAD

**Issue by FlorentinGarnier** [Sylius/Sylius#10774]
**Describe the proposed solution**
Generate a `/admin . uniqueId()` and parse/edit admin route prefix

**Describe alternatives you've considered**

create an .env variable to define admin prefix 

**Additional context**
This feature is to avoid brute force on /admin

**Comment by vvasiloi** [comment]
You can use a subdomain.
https://symfony.com/doc/current/routing.html#sub-domain-routing

**Comment by FlorentinGarnier** [comment]
okay it was shust a dummy issue because it simply to modify `config/routes/sylius_admin.yaml` and so on. Sorry
