### ISSUE TITLE
[Channel][Taxation] Channel's default tax zone can have "shipping" scope

### ISSUE THREAD

**Issue by vvasiloi** [Sylius/Sylius#10782]
**Sylius version affected**: all
**Description**  
The channel default tax zone has no restriction and can be one with scope "shipping".
The OrderTaxesProcessor matches only zones with "tax" scope (or "all", which means incl. "tax"), but if no zone is matched then the default tax zone is used, which can be one with scope "shipping".
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/OrderProcessing/OrderTaxesProcessor.php#L87
Side effects or bugs not detected yet.

**Possible Solution**  
Allow only zones with scope "tax" or "all" to be used as default tax zone.

**Comment by pamil** [comment]
https://github.com/Sylius/Sylius/pull/10780#issuecomment-543778321

**Comment by vvasiloi** [comment]
Added a bit of description for context.
