### ISSUE TITLE
Connect Sylius to JTL-Wawi

### ISSUE THREAD

**Issue by csaeum** [Sylius/Sylius#10788]
Unfortunately I am not a developer but I could test and give help. JTL software itself offers a connector that allows you to connect any shop to its Wawi.
https://github.com/jtl-software/connector-core

Maybe one of you would like to implement this. For tests and tips on Wawi I would be ready.

**Comment by Zales0123** [comment]
Hello Christian! Thank you for such a tip, however, right now I'm 150% sure we, as the @Sylius/core-team, will not have time to implement such an integration. I would recommend you to ask on our [Slack](https://sylius.com/slack) for some help with it. Good luck! 🖖
