### ISSUE TITLE
Sylius Admin => bootstrap

### ISSUE THREAD

**Issue by hlorridi-mbp** [Sylius/Sylius#10798]
Hi, is there any way to use bootstrap instead of semantic ui for the admin part ?
I've found one package for the shop, but none for the admin.

**Comment by Zales0123** [comment]
Hello @hlorridi-mbp and welcome to the community! 🚀

Right now we do not plan to introduce a bootstrap theme for Sylius admin panel. However, you can easily replace Admin twig templates with your own implementation - check out the [Customizing templates](https://docs.sylius.com/en/1.6/customization/template.html) section in documentation ;)

**Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our [Slack](http://sylius.com/slack) (preferred) or [forum](https://forum.sylius.com/) ;) We have a very active, developed community, I'm sure someone will be able to help you with your problem. Good luck 🖖
