### ISSUE TITLE
Support case when CountryNameExtension::translateCountryIsoCode() doesn't have translation

### ISSUE THREAD

**Issue by diimpp** [Sylius/Sylius#10799]
**Sylius version affected**: 1.6.1

**Description**  
`Sylius\Bundle\AddressingBundle\Twig\CountryNameExtension::translateCountryIsoCode()` return type hint expects non-null result, while `Intl::getRegionBundle()->getCountryName()` might return null if no translation provided. 
Some of the edge case ISO countries, like reserved names, might not have translation. (UN, TA, XK, EZ, DG, EA, IC, AC)

**Steps to reproduce**  
Add one of countries (UN, TA, XK, EZ, 
DG, EA, IC, AC) to country list and there will be 500 error on country listing at admin UI.

**Possible Solution**  
If no translation found, return raw country code.

![image](https://user-images.githubusercontent.com/870747/67633173-2abdfb80-f8df-11e9-9a59-52a964288bab.png)

While I should just drop those countries (It worked at Sylius1.2 and SF3.4, btw), it will be nice to handle this case generally.

**Comment by Zales0123** [comment]
I see no danger in doing a fallback to the country code if a name is not found 👌
