### ISSUE TITLE
Use case for an Order Item Promotion Adjustment

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#10801]
**Sylius docs version**: latest

**Description**

What are real world use cases for an `Order Item Promotion Adjustment`? 

 I ask this because not a single out-of-a-box promotion uses this kind of adjustment. Every bundled promotion in Sylius applies adjustments on an order item unit level. The `AdjustmentInterface::ORDER_ITEM_PROMOTION_ADJUSTMENT` isn't used anywhere.

The [documentation](https://docs.sylius.com/en/1.6/book/orders/adjustments.html) doesn't clarify this. It would be nice to have small table or something which would describe the differences or when one should be used instead of another. Or maybe this doesn't really matter in the end.

**Comment by Zales0123** [comment]
Hello Mike! There is no such use-case currently. I can imagine that for simpler shops it can be some kind of simplification (maybe ⚖️). But on the other hand, we cannot remove it, as it would be a BC break for somebody who uses it 💃 

If anyone has any idea about how we can document it better, be our guest in the documentation 😄 

Also, if you need any more elaboration on this topic, feel free to reopen the issue 🖖

**Comment by loevgaard** [comment]
I would like to mark this adjustment as @deprecated, @Zales0123. Can we do that? I was in the same situation, where I needed to figure out where it was used, but figured out it wasn't.
