### ISSUE TITLE
Discount does not include order level adjustments

### ISSUE THREAD

**Issue by elvetemedve** [Sylius/Sylius#10800]
**Sylius version affected**: 1.6.1

**Description**  

The total order discount does not include order level adjustments (only item level).

**Steps to reproduce**  

1. Register a custom promotion action implementation which will add order level promotion adjustment to the order. 
For instance see [FreeOrderPromotionActionCommand.zip](https://github.com/Sylius/Sylius/files/3778814/FreeOrderPromotionActionCommand.zip)
1. Create a new promotion and make sure the action type is set to the action created in previous step.
1. Add a product to the shopping cart where the promotion is applicable.
1. Inspect the summary block on the checkout page. You will see the **Order Total** updated, but the **Discount** value has not changed.
For instance:
![screenshot-localhost-8000-2019 10 23-17-58-34](https://user-images.githubusercontent.com/596431/67682205-1afdf000-f98f-11e9-8143-28f6c473699f.png)

**Comment by Zales0123** [comment]
Thank you for the report and welcome to the Community! Indeed, there is a problem with that calculation, even bigger, as this method is used not only to display discounts but also in [convert action for Paypal](https://github.com/Sylius/Sylius/blob/583f53aa5a19d5203db8e9ac0f8af9370b2fcb57/src/Sylius/Bundle/PayumBundle/Action/Paypal/ExpressCheckout/ConvertPaymentAction.php#L71) 💃 We should definitely take a close look at this bug.

**Comment by pamil** [comment]
Fixed by #10806.
