### ISSUE TITLE
Translations on Crowdin

### ISSUE THREAD

**Issue by jjanvier** [Sylius/Sylius#1080]
**Last export : 02/21/14**

Hi guys ! 

All Github translations are now on Crowdin with the yaml format. I'm sure we are lost a few Crowdin translations during the migration, but nothing real important IMO. 

Documentation will be updated soon to explain how to translate Sylius. Short story here : 
 * **translators** : please contribute on Crowdin here https://crowdin.net/project/sylius. 
 * **developers** : only add or edit English translations keys in your PR. 

**From now on, no PR about translations (except English files of course) will be merged.**

The **synchronization** between Github and Crowdin is done manually at the moment : 
 * if you need lastest Crowdin translations, please ping us here, we'll update them on Github as soon as possible
 * if you have added new English keys (or updated existing keys) in your translations, please remind it to us in your PR. We'll upload your modifications on Crowdin as soon as possible.

**Comment by paceto256** [comment]
I translated it on Bulgarian 6 months ago. Seeing just now that have to post here before the git repo gets Updated.

I translated:
WebBundle 
VariationBundle
ResourceBundle
PaymentBundle
MoneyBundle
LocaleBundle
ContentBundle
ContactBundle
CardBundle
AddressingBundle


thanks

**Comment by pjedrzejewski** [comment]
@paceto256 I believe I got your e-mail. I will for now send you translations files in a package, until we fix the synchronization process. You first need to approve Bulgarian translations, I added you as proofreader.

**Comment by Headd2k** [comment]
is there any chance to get an updated translation pack for german? would be great! thanks in advance!

**Comment by pjedrzejewski** [comment]
Ping @jjanvier. Could you give us just quick hint what is status of this sync tool? I can take it over, but wanted to know where are we at the moment. :)

**Comment by pamil** [comment]
We got the translation synchronization back, can be closed :tada:
