### ISSUE TITLE
Changing shipping method doesn't change price

### ISSUE THREAD

**Issue by loevgaard** [Sylius/Sylius#10828]
**Sylius version affected**: All I suppose

**Description**  
![image](https://user-images.githubusercontent.com/2412177/68459680-4e017880-0206-11ea-9ba3-3baab3845d6b.png)

When I choose another shipping method, the shipping costs are not updated and neither the total obviously.

**Possible Solution**  
A javascript solution should suffice

**Comment by TheMilek** [comment]
Hi @loevgaard! 🍻 
We are not planning to implement it in nearest future, nevertheless you can provide a PR 💃🏽
