### ISSUE TITLE
Get the data from the OpenGeoDB

### ISSUE THREAD

**Issue by csaeum** [Sylius/Sylius#10850]
I would appreciate if you have a chance to use the Opengeodb.

If a shop owner uses a country for shipping, etc., then one would then have the opportunity to retrieve the country's data from the Opengeodb.
http://opengeodb.giswiki.org

One could then import the federal states, the ZIP codes, etc.

This would make it easier for customers to enter their customer data and also for shop operators to validate customer addresses.

Maybe there is a better database, I know this from JTL shop, there it is already used.

**Comment by Zales0123** [comment]
Hello Christian!

It sounds like a nice feature, but I would definitely encourage someone (maybe you 😄) to write a plugin for integration with this library. We try to make Sylius strictly eCommerce-focused but at the same time, easy to integrate with other solutions providing more specific functionalities. Nevertheless, thank you for this idea 🖖 If you want to discuss it with other community members, you should use our [Slack](https://sylius.com/slack) (as I see, you're already there ;)). Good luck!
