### ISSUE TITLE
CoreBundle/Resources/config/services/form.xml references a non existent class

### ISSUE THREAD

**Issue by pfazzi** [Sylius/Sylius#10866]
**Sylius version affected**: 1.6.2

**Description**  
`CoreBundle/Resources/config/services/form.xml` contains a definition of a service with a non existent class:
https://github.com/Sylius/Sylius/blob/a12ce58e9ebce9b465fe8869110bafdd2934e30f/src/Sylius/Bundle/CoreBundle/Resources/config/services/form.xml#L180

**Possible Solution**  
Remove service config.

**Edit:**
I found 3 bad service definitions:
1. sylius.form.event_subscriber.build_promotion_rule 
2. sylius.form.event_subscriber.build_promotion_action
3. sylius.form.type.data_transformer.product_variants_to_codes

**Comment by lchrusciel** [comment]
Thanks for reporting. Are you willing to open a PR?

**Comment by pfazzi** [comment]
Yes, i can ;)

**Comment by lchrusciel** [comment]
Solved by #10926
