### ISSUE TITLE
where the "web" folder in version 1.4+, for xampp setting

### ISSUE THREAD

**Issue by 0andy** [Sylius/Sylius#10864]
**Sylius docs version**: 1.4+/ latest

**Description**
Hi,
I notice 1.3 and earlier version, it has web folder. But 1.4 and latest version do not have that.
Where could I find it or where could I use for the xampp setting?
Thanks.

**Comment by Zales0123** [comment]
Hello @0andy! It was the time when we switched to the [new Symfony directory structure](http://fabien.potencier.org/symfony4-directory-structure.html). You should use a `public/` folder now :) Good luck 🖖
