### ISSUE TITLE
Shipment confirmation email

### ISSUE THREAD

**Issue by vvasiloi** [Sylius/Sylius#10872]
**Sylius version affected**: all

**Description**  
Shipment confirmation email sending is done by [sylius.listener.shipment_ship](https://github.com/Sylius/Sylius/blob/f5b137e926be95c40b3def2e6abf64e42619d9ab/src/Sylius/Bundle/AdminBundle/Resources/config/services/listener.xml#L18-L21)  listening on `sylius.shipment.post_ship`, which is a resource event triggered by default only in admin panel ([here](https://github.com/Sylius/Sylius/blob/f5b137e926be95c40b3def2e6abf64e42619d9ab/src/Sylius/Bundle/AdminBundle/Resources/config/routing/order.yml#L104) and [here](https://github.com/Sylius/Sylius/blob/f5b137e926be95c40b3def2e6abf64e42619d9ab/src/Sylius/Bundle/AdminBundle/Resources/config/routing/partial/shipment.yml#L7)) and [admin api](https://github.com/Sylius/Sylius/blob/f5b137e926be95c40b3def2e6abf64e42619d9ab/src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/order.yml#L33)).
Adding a state machine callback to send it will send it twice when the transition is done through the resource layer.

**Possible Solution**  
Trigger the email sending through a state machine callback.
Maybe move the whole thing from Admin to Core bundle.

**Comment by vvasiloi** [comment]
Related issue: https://github.com/Sylius/Sylius/issues/10581
That was the perfect moment to ask if it's a good solution.

**Comment by Zales0123** [comment]
Sorry for the long response time @vvasiloi. The problem with sending emails on state machine callbacks is, they're triggered **before** a flush to the database. So if anything goes bad during the save, there is still an email sent (and it should not) :/

**Comment by vvasiloi** [comment]
@Zales0123 I guess a more sophisticated notification system, specifically an asynchronous one, is out of the table, since it's a lot of work. What if the callback will not send the email, but will use another service to register the email for sending and then a listener (can be the same service) will send them on kernel.response? It's similar to how Cookie Storage works.

**Comment by mmenozzi** [comment]
@stale don't stale
This issue should be open.
