### ISSUE TITLE
[BUG] UserProvider should throw UnsupportedUserException and not UnexpectedValueException

### ISSUE THREAD

**Issue by AndreasA** [Sylius/Sylius#10879]
**Sylius version affected**: 1.6.2

**Description**  
When using different user providers with multiple firewall contexts and some are outside the Sylius-User Provider scope then a `refreshUser` can throw (depending on which UserProviders are registered first and if they provide a user or not) an UnexpectedValueException as Symfony checks all UserProviders when calling `refreshUser`.

If the user is not supported, Symfony expects a `UnsupportedUserException` where they would try the next provider and they throw their own exception if no provider supports the user.
See also: https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Http/Firewall/ContextListener.php#L174

**Steps to reproduce**  
see above.

**Possible Solution**  
Instead of `Assert::instanceOf` at https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/UserBundle/Provider/AbstractUserProvider.php#L71
(refreshUser of the AbstractUserProvider).
Do an instanceof check and throw an `\Symfony\Component\Security\Core\Exception\UnsupportedUserException` instead.

**Comment by lchrusciel** [comment]
Hello Andreas 👋 

Thanks for the bug report. Are you willing to open a PR with fix? We should target version 1.5

**Comment by AndreasA** [comment]
Hi, yes I can create a PR. Not sure when exactly though but I am hoping sometime this week. It shouldn't be a terrible difficult PR.

Btw. is there already a test regarding this check that I can adapt or should I add a new one?

**Comment by Zales0123** [comment]
We should definitely have such checks for all providers that extend the `AbstractUserProvider` in their specs files, so in `EmailProviderSpec`, `UserProviderSpec`, `UsernameOrEmailProviderSpec` and `UsernameProviderSpec` (I think that's all 😄)
