### ISSUE TITLE
Customer impersonation bug when no referrer url sent

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#10886]
**Sylius version affected**: 1.6

**Description**  
Impersonation controller in the admin throws unhandled 500 error when no referrer url is available.

**Steps to reproduce**  
1. Go to https://demo.sylius.com/admin/customers/
2. `Show` any customer
3. Copy `Impersonate` button's URL
4. Paste in the browser
5. Kaboom

**Possible Solution**  
Check referrer was sent. If not redirect to the client's "show" page

**Comment by pamil** [comment]
Fixed by #11129.
