### ISSUE TITLE
symfony 4.4 - Warning: password_hash(): Unknown password hashing algorithm: 2

### ISSUE THREAD

**Issue by TELLO0815** [Sylius/Sylius#10887]
I tried with Symfony  4.3.8 customer registration works. Than i made update to 4.4 and i get on customer registration:
Warning: password_hash(): Unknown password hashing algorithm: 2

have this issue on two projects.

the update:
`

Package operations: 1 install, 56 updates, 0 removals
  - Updating symfony/routing (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/polyfill-mbstring (v1.12.0 => v1.13.0): Loading from cache
  - Updating symfony/polyfill-php73 (v1.12.0 => v1.13.0): Loading from cache
  - Updating symfony/polyfill-ctype (v1.12.0 => v1.13.0): Loading from cache
  - Updating symfony/polyfill-php72 (v1.12.0 => v1.13.0): Loading from cache
  - Updating symfony/polyfill-intl-idn (v1.12.0 => v1.13.0): Loading from cache
  - Updating symfony/mime (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/http-foundation (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/event-dispatcher (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/debug (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/var-dumper (v4.3.8 => v4.4.0): Loading from cache
  - Installing symfony/error-handler (v4.4.0): Loading from cache
  - Updating symfony/http-kernel (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/finder (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/filesystem (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/dependency-injection (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/config (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/var-exporter (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/cache (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/framework-bundle (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/polyfill-php70 (v1.12.0 => v1.13.0): Loading from cache
  - Updating symfony/doctrine-bridge (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/console (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/inflector (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/property-access (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/security (v4.3.8 => v4.4.0): Loading from cache
  - Updating doctrine/doctrine-bundle (1.11.2 => 1.12.1): Loading from cache
  - Updating doctrine/orm (v2.6.4 => v2.7.0): Loading from cache
  - Updating symfony/twig-bridge (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/twig-bundle (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/templating (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/options-resolver (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/intl (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/polyfill-intl-icu (v1.12.0 => v1.13.0): Loading from cache
  - Updating symfony/form (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/asset (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/validator (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/translation (v4.3.8 => v4.4.0): Loading from cache
  - Updating sonata-project/block-bundle (3.18.1 => 3.18.2): Loading from cache
  - Updating symfony/dotenv (v4.3.8 => v4.4.0): Loading from cache
  - Updating webmozart/assert (1.5.0 => 1.6.0): Loading from cache
  - Updating symfony/web-profiler-bundle (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/security-bundle (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/yaml (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/polyfill-iconv (v1.12.0 => v1.13.0): Loading from cache
  - Updating symfony/monolog-bridge (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/proxy-manager-bridge (v4.3.8 => v4.4.0): Loading from cache
  - Updating white-october/pagerfanta-bundle (v1.2.4 => v1.3.1): Loading from cache
  - Updating symfony/dom-crawler (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/browser-kit (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/debug-bundle (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/expression-language (v4.3.8 => v4.4.0): Loading from cache
  - Updating coduo/php-matcher (3.2.2 => 3.2.3): Loading from cache
  - Updating symfony/stopwatch (v4.3.8 => v4.4.0): Loading from cache
  - Updating symfony/process (v4.3.8 => v4.4.0): Loading from cache
  - Updating friendsofphp/php-cs-fixer (v2.16.0 => v2.16.1): Loading from cache
  - Updating nette/utils (v2.5.3 => v2.5.4): Loading from cache

`

**Comment by michaelmo5** [comment]
This 2 is a **string**, but should be **int**, because
in **vendor/symfony/security-core/Encoder/NativePasswordEncoder.php:__constructor()**

`$this->algo = (string) ....`
should be
`$this->algo = (int)`

**Comment by michaelmo5** [comment]
In my case this worked:
from:
```
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
```
to:
```
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
```

**Comment by michaelmo5** [comment]
Try changing **security.yaml**
```
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
```
to:
```
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: auto
```
or any other algorithm

**Comment by TELLO0815** [comment]
I tried this too. Registration works, but not the login or reregistration this way. Don’t remember how it was. I downgrade symfony from 4.4 zu 4.3.

**Comment by pamil** [comment]
It looks like it's caused by FOSUserBundle: https://github.com/Sylius/Sylius/issues/10887.
