### ISSUE TITLE
cache:clear performance on the cli

### ISSUE THREAD

**Issue by Guave-Mattias** [Sylius/Sylius#10882]
**Sylius version affected**: 1.6.2

**Description**  
When running cache:clear in my instance tries to get a channel in order to warm the template cache here:

vendor/sylius/theme-bundle/src/Templating/Locator/TemplateFileLocator.php:62

But since it does not have the correct context for a channel, it can't find one. The command should result in 0 queries to the database but with my 20 channels it results in 2'277 queries (probably one for each template). This makes developing for sylius very difficult because it takes ages (multiple minutes) to build the cache, once it needs to be refreshed.

**Steps to reproduce**  
run `app/console cache:clear`

**Possible Solution**  
On my instance I solved this issue by creating a custom channel context (sylius.context.channel). This is what it looks like:

```php
if (php_sapi_name() !== "cli") {
	throw new ChannelNotFoundException();
}

if ($this->channel) {
	return $this->channel;
}

/**
 * Just return any channel. We need to do this so the other listeners don't search for a channel.
 *
 * @var $channel Channel
 */
$channel = $this->channelRepository->findOneBy([]);
if (null === $channel) {
	throw new ChannelNotFoundException();
}
return $this->channel = $channel;
```

This brings the number of queries down from 2'277 to 3 and thus the command is a lot faster.

**Comment by pamil** [comment]
Related to #9296.

**Comment by vjandrea** [comment]
Looks like this is still relevant on Windows, I just tried to create a new project using composer create-project , and I get a timeout while the script runs **cache:clear**:

```
$ composer create-project sylius/sylius-standard sylius-tutorial
... 
Executing script cache:clear
The following exception is caused by a process timeout
Check https://getcomposer.org/doc/06-config.md#process-timeout for details


  [Symfony\Component\Process\Exception\ProcessTimedOutException]
  The process "C:\php\php.exe --php-ini=C:\php\php.ini ./bin/console --ansi cache:clear" exceeded the timeout of 300 seconds.
```

```
$ php --version
PHP 8.0.15 (cli) (built: Jan 18 2022 13:43:14) ( NTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.15, Copyright (c) Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans
    with Zend OPcache v8.0.15, Copyright (c), by Zend Technologies
```
