### ISSUE TITLE
Cart context should respect current user's currency context not channel default

### ISSUE THREAD

**Issue by alexrowesoap** [Sylius/Sylius#10898]
**Sylius version affected**: 1.2+

**Description**  
At present, all orders are placed and processed in the base currency set in the channel. Ideally, in terms of payments, these should be handed in the currency context selected by the customer as some banks refuse transactions when placed outside of the card-holder's currency. 
The issue is a bit of a thorny one, as how having different currencies in orders and payments may affect reporting and promotions. Further, if an order is placed in the past the exchange rate may differ to current rates such that any display that converts the currency to/from the base currency will not accurately reflect the amount paid at the time.

While this was also discussed in https://github.com/Sylius/Sylius/issues/9093 , the fact that customers not being able to pay in their selected currency is having a demonstrable fiscal impact in that we can see customer's orders being rejected by banks due to the destination currency, thus I feel this issue is distinct to 9093 as this is more focused on the issue impacting the checkout rather than the rendering.

In a nutshell, to enable a multi-currency platform to effectively handle payments in multiple currencies, we need to at least handle the payment in the user's selected currency.

IMHO we should still store orders and payments in the base currency, but have some form of transformer that will render orders and payments in the selected currency as this will keep the platform's fiscal calculations and reporting accurate and easy to query, but allow for customer's to complete the entire checkout in the currency of their choice. I'd like to encourage discussion on an elegant solution for this.

Shout out to @vvasiloi for helping debug this.

**Steps to reproduce**  

1. Access a standard Sylius install 1.2 or greater
2. Ensure more than one currency is available on the presently accessible channel
3. Go to the front-end and switch your context to the currency that is not the base currency of the channel
4. Add an item to your basket and proceed to checkout
5. Observe in the checkout flow that the amounts are shown in the selected currency with a converted figure of the channel's default currency at certain points
6. Observe that the payment taken is using the channel's base currency rather than the one in the current customer's context

**Possible Solutions**  

- https://github.com/Sylius/Sylius/blob/f9bac2f77ed2621897fd7df4f1c5b38ecdb4c022/src/Sylius/Component/Core/Cart/Context/ShopBasedCartContext.php#L64 Modified to accept the current context (This may not be the only location)

- Store two more columns on sylius_order and sylius_payment: One storing the channel's base currency at the time of ordering and another tracking the current exchange rate between the two (this will resolve the accuracy issues raised in https://github.com/Sylius/Sylius/issues/9093)

- Create a transformer class that accepts orders and payments and returns the same object with the monitory values adjusted. How we ensure this transformed object does not adversely impact the parent in terms of values being changed needs to be discussed.

Thanks!

Alex

**Comment by vvasiloi** [comment]
Here are my thoughs on that issue.
1. The shop already displays the amounts in the selected currency, but store them in the channel's base locale, so that's where the change should be made.
2. Channel's base locale is theoretically immutable, so there is no need to save the one used when the order is placed as it must not change in time.
3. The whole order (invoice) should be immutable once it's placed because it's a contract between the store and the customer, so the amounts should be converted using the rate at that moment and set in stone.

**Comment by alexrowesoap** [comment]
So good news on your three points:
1) Agreed. 
I've made progress on this and I have this working end-to-end for customers including the currency sent to the gateway ( I've not done any testing with third party gateways such as the Adyen one) and it renders correctly on orders and payments within the admin. Thus far I've only had to override the ShopBasedCartContext and a couple of twigs ( the ones that show the "Base Currency" value no longer need this output if the orders are in / are paid in the selected currency)

2) Agreed. This saves a job

3) Agreed. We have a local override that updates the exchange rates every night, so the amount at payment is correct, and as the order and payment are created in that currency they become immutable. 
The one issue we are facing, as expected, is reporting. 
Part one of this issue is an idea to make plugin developer's lives easier and offer a helper function on orders/payments/adjustments that returns the amount and currency of the entity as the customer paid for it and replace the existing "getPrice" type functions to convert the fiscal value to the channel's base currency if said object is not using the base currency, thus providing transparent backwards compatibility of this functionality. 
The second issue is that of storing the exchange rate. For orders, once they are paid for, the amount is fixed at the point in time it was created / paid for, thus saving the exchange rate on the entity or on a related entity makes sense. However for reporting and for other objects that do not possess a time context such as shipping prices or promotions, so I guess these would convert the value on the fly?
Either way, the last steps for us is figuring out the two issues with point three. We are implementing the transparent conversion for our system regardless as we require this functionality, but if we can do this that might be back-portable we will do so.

**Comment by alexrowesoap** [comment]
```
public function getCart(): BaseOrderInterface
    {
        if (null !== $this->cart) {
            return $this->cart;
        }

        /** @var OrderInterface $cart */
        $cart = $this->cartContext->getCart();
        Assert::isInstanceOf($cart, OrderInterface::class);

        try {
            /** @var ChannelInterface $channel */
            $channel = $this->shopperContext->getChannel();

            $cart->setChannel($channel);
            if($cart->getCurrencyCode() != null) {
                $cart->setCurrencyCode($cart->getCurrencyCode());
            }else{
                if($this->shopperContext->getCurrencyCode() != null){
                    $cart->setCurrencyCode($this->shopperContext->getCurrencyCode());
                }else {
                    $cart->setCurrencyCode($channel->getBaseCurrency()->getCode());
                }
            }
            $cart->setLocaleCode($this->shopperContext->getLocaleCode());
        } catch (ChannelNotFoundException | CurrencyNotFoundException | LocaleNotFoundException $exception) {
            throw new CartNotFoundException('Sylius was not able to prepare the cart.', $exception);
        }

        /** @var CustomerInterface $customer */
        $customer = $this->shopperContext->getCustomer();
        if (null !== $customer) {
            $this->setCustomerAndAddressOnCart($cart, $customer);
        }

        $this->cart = $cart;

        return $cart;
    }
```

**Comment by vvasiloi** [comment]
This is kind of weird:
```
if ($cart->getCurrencyCode() != null) {
    $cart->setCurrencyCode($cart->getCurrencyCode());
```
I think the the whole if/else statement can be resumed to:
```
$cart->setCurrencyCode($this->shopperContext->getCurrencyCode() ?? $channel->getBaseCurrency()->getCode());
```

**Comment by alexrowesoap** [comment]
Good spot. Not sure why I did that :joy:

**Comment by caboose89** [comment]
Hey, can someone re-open this and not stale?
