### ISSUE TITLE
Same Product Variant for different channels needs different tax and shipping option too 

### ISSUE THREAD

**Issue by TELLO0815** [Sylius/Sylius#10892]
I think some people will go to this issue too.

If you have two channels. Lets say one B2C and one B2B. Means B2C must have VAT inclusive, B2B exclusive.
If I sell same product in two channels, I can set different price. But I must have the possibility to set also different VAT models and shipping models per channel.

**Comment by vvasiloi** [comment]
You can just remove the taxes when selling B2B.
Implement a new `Sylius\Component\Core\Taxation\Applicator\OrderTaxesApplicatorInterface` with 
```
public function apply(OrderInterface $order, ZoneInterface $zone): void
{
    if (!$this->aServiceOrMethodToCheckIfTaxShouldBeRemove($order, $zone)) {
        return;
    }

    foreach ($order->getItems() as $item) {
        if ($item->getUnits()->isEmpty()) {
            return;
        }

        /** @var OrderItemUnit $unit */
        $unit = $item->getUnits()->first();
        $item->removeAdjustmentsRecursively(AdjustmentInterface::TAX_ADJUSTMENT);
        $item->setUnitPrice($item->getUnitPrice() - $unit->getIncludedTaxTotal());
    }
}
```

**Comment by TELLO0815** [comment]
I understand. On the end I need the VAT on the order. And there are different VAT´s. But this means I must insert price with VAT - because B2C is inclusive. This means lot of calculation before, because everything in B2B is net. Or I write something to calculate from the form field when I insert, but there will be small differences in rounding I guess. So its not "clean" .

**Comment by vvasiloi** [comment]
This code will work regardless if the prices are including or excluding tax.
If you need the tax on the order, you can calculate the total while removing item adjustments and set it as a neutral tax adjustment on the order.
You can also implement a new variant price calculator that will return it with or without tax depending  on the channel.

**Comment by TELLO0815** [comment]
i will try.

**Comment by lchrusciel** [comment]
Also, you may customize the whole TaxStrategy if you need more flexibility in calculation
