### ISSUE TITLE
Adding exchange rate value bigger that 99,999 is not possible

### ISSUE THREAD

**Issue by hsharghi** [Sylius/Sylius#10905]
**Sylius version affected**: 1.6.1

**Description**  
Adding exchange rate with value bigger than 99,999 will throw `Numeric value out of range` exception

**Steps to reproduce**  
Try to add exchange rate from any currency to another currency with rate value of 100,000 or bigger.

**Possible Solution**  
Change rate column format from DECIMAL(10,5) to DECIMAL(11,5) or bigger value

**Comment by pamil** [comment]
We can change it to `DECIMAL(11,5)` and it will not change the number of bytes used: https://dev.mysql.com/doc/refman/5.7/en/precision-math-decimal-characteristics.html

What is the biggest exchange rate that we would like to support? What is the lowest exchange rate also?

**Comment by hsharghi** [comment]
@pamil The biggest exchange rate we were trying to add was IRR.
114,000 IRR/USD
