### ISSUE TITLE
Resend order confirmation email from backend

### ISSUE THREAD

**Issue by loevgaard** [Sylius/Sylius#10907]
**Describe the proposed solution**
Have a button on the order show page in `admin` where you can resend the order confirmation email.

**Describe alternatives you've considered**
None

**Additional context**
When a customer writes their email wrong and the admin edits it manually on the customer, then this feature is mandatory :D

**Comment by CoderMaggie** [comment]
It's a "feature" planned to appear within one month max :D

**Comment by loevgaard** [comment]
Great!
