### ISSUE TITLE
[Promotion] Unable to generate coupons

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#10912]
**Sylius version affected**: 1.6

**Description**  
```
Invalid coupons code length or coupons amount. It is not possible to generate 50 unique coupons with code length equals 16. Possible generate amount is -9223372036854775808.
```

**Steps to reproduce**  
See screenshot: https://www.dropbox.com/s/x4fbw8wohwnweom/Screenshot%202019-12-09%2019.28.31.png?dl=0

Another one: https://www.dropbox.com/s/na4xbazvadlpz7d/Screenshot%202019-12-09%2019.33.07.png?dl=0

**Comment by pamil** [comment]
Fixed in #11095.
