### ISSUE TITLE
[Taxation] How do I apply a state based tax

### ISSUE THREAD

**Issue by benborla** [Sylius/Sylius#10920]
Hi all,

I am new to Sylius, currently taxation only supports country based or zone based tax, however, I want to know if it's possible to apply tax on a state. For example, in Florida there is a 7% tax on every product you add to the cart. How would I able to apply it via admin panel or programmatically.

Thank you!

**Comment by vvasiloi** [comment]
That's exactly what zones are for. You can add the states as provinces and then create an "US" zone consisting of provinces (the states).

**Comment by benborla** [comment]
Oh, okay. I'll try that one.

**Comment by lchrusciel** [comment]
Hey Ian, 

Would you mind if I will close this issue then?

**Comment by benborla** [comment]
Yes sure, thank you
