### ISSUE TITLE
hello i have been trying to extend my admin menu and for some reason it give me this error

### ISSUE THREAD

**Issue by Giaro117** [Sylius/Sylius#10927]
Attempted to load class "AdminMenuListener" from namespace "App\Admin\Add".
Did you forget a "use" statement for another namespace?

below is my code.

<?php

namespace App\Menu;

use Sylius\Bundle\UiBundle\Menu\Event\MenuBuilderEvent;

final class AdminMenuListener
{
    public function addAdminMenuItems(MenuBuilderEvent $event): void
    {
        $menu = $event->getMenu();

        $newSubmenu = $menu
            ->addChild('new')
            ->setLabel('NAV')
        ;

        $newSubmenu
            ->addChild('new-subitem')
            ->setLabel('Products')
        ;
    }
}

  App.listener.admin.menu_builder:
        class: App\Menu\AdminMenuListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addAdminMenuItems }

i am using sylius 1.6 and i created an app file because my wsdl controllers are in the src folder.

the listener folder is in App/Menu

**Comment by Zales0123** [comment]
Hello @Giaro117 and welcome to the community! 🚀 **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our [Slack](http://sylius.com/slack) (preferred) or [forum](https://forum.sylius.com/) ;) We have a very active, developed community, I'm sure someone will be able to help you with your problem. Good luck :)
