### ISSUE TITLE
The road to Symfony 5

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#10928]
Symfony 5 has been released a few weeks ago, now's the time to make the effort to support it.

## Dependencies

I've compiled a list of dependencies that either need to be updated on Sylius side (to next major releases) or need to support Symfony 5 first:

<table>
<tr><th>Status</th><th>Package</th><th>Installed version</th><th>Details</th></tr>
<tr><td>:white_check_mark:</td><td>behat/behat</td><td>v3.5.0</td><td><a href="https://github.com/Behat/Behat/pull/1256">Pull request</a></td></tr>
<tr><td>:white_check_mark:</td><td>behat/mink</td><td>1.7.x-dev</td><td><a href="https://github.com/minkphp/Mink/issues/787">Issue</a></td></tr>
<tr><td>:white_check_mark:</td><td>behat/mink-browserkit-driver</td><td>1.3.3</td><td><a href="https://github.com/minkphp/MinkBrowserKitDriver/issues/139">Issue</a></td></tr>
<tr><td>:white_check_mark:</td><td>behat/mink-extension</td><td>2.3.1</td><td><a href="https://github.com/Behat/MinkExtension/pull/355">Pull request</a></td></tr>
<tr><td>:x:</td><td>doctrine/doctrine-bundle</td><td>1.12.2</td><td>Supported in <a href="https://github.com/doctrine/DoctrineBundle/blob/2.0.0/composer.json">^2.0</a></td></tr>
<tr><td>:x:</td><td>doctrine/doctrine-cache-bundle</td><td>1.4.0</td><td>Deprecated, will be solved by updating doctrine/doctrine-bundle</td></tr>
<tr><td>:white_check_mark:</td><td>doctrine/doctrine-fixtures-bundle</td><td>v2.4.1</td><td>Supported in <a href="https://github.com/doctrine/DoctrineFixturesBundle/releases/tag/3.3.0">^3.3</a></td></tr>
<tr><td>:white_check_mark:</td><td>friends-of-behat/symfony-extension</td><td>v2.0.10</td><td><a href="https://github.com/FriendsOfBehat/SymfonyExtension/pull/100">Pull request</a></td></tr>
<tr><td>:white_check_mark:</td><td>friends-of-behat/variadic-extension</td><td>v1.2.0</td><td><a href="https://github.com/FriendsOfBehat/VariadicExtension/pull/27">Pull request</a></td></tr>
<tr><td>:x:</td><td>friendsofsymfony/oauth-server-bundle</td><td>1.6.2</td><td><a href="https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/issues/625">Issue</a></td></tr>
<tr><td>:x:</td><td>friendsofsymfony/rest-bundle</td><td>2.6.0</td><td>Supported in <a href="https://github.com/FriendsOfSymfony/oauth2-php/blob/master/composer.json">master</a></td></tr>
<tr><td>:white_check_mark:</td><td>hwi/oauth-bundle</td><td>0.6.3</td><td><a href="https://github.com/hwi/HWIOAuthBundle/pull/1575">Pull request</a></td></tr>
<tr><td>:x:</td><td>jms/serializer-bundle</td><td>2.4.4</td><td>Supported in <a href="https://github.com/schmittjoh/JMSSerializerBundle/releases/tag/3.5.0">^3.5</a></td></tr>
<tr><td>:white_check_mark:</td><td>knplabs/knp-gaufrette-bundle</td><td>v0.5.3</td><td>Supported in <a href="https://github.com/KnpLabs/KnpGaufretteBundle/releases/tag/v0.7.0">^0.7</a></td></tr>
<tr><td>:white_check_mark:</td><td>knplabs/knp-menu-bundle</td><td>v2.3.0</td><td>Supported in <a href="https://github.com/KnpLabs/KnpMenuBundle/blob/v3.0.0/composer.json">^3.0</a></td></tr>
<tr><td>:white_check_mark:</td><td>lchrusciel/api-test-case</td><td>v3.1.4</td><td><a href="https://github.com/lchrusciel/ApiTestCase/pull/163">Pull request</a></td></tr>
<tr><td>:white_check_mark:</td><td>liip/imagine-bundle</td><td>2.2.0</td><td><a href="https://github.com/liip/LiipImagineBundle/pull/1246">Pull request</a></td></tr>
<tr><td>:white_check_mark:</td><td>matthiasnoback/symfony-dependency-injection-test</td><td>v3.1.0</td><td>Supported in <a href="https://github.com/SymfonyTest/SymfonyDependencyInjectionTest/blob/master/CHANGELOG.md#v410">^4.1</a></td></tr>
<tr><td>:white_check_mark:</td><td>payum/payum-bundle</td><td>2.3.4</td><td><a href="https://github.com/Payum/PayumBundle/pull/501">Pull request</a></td></tr>
<tr><td>:white_check_mark:</td><td>phpspec/phpspec</td><td>5.1.2</td><td>Supported in <a href="https://github.com/phpspec/phpspec/releases/tag/6.1.0">^6.1</a></td></tr>
<tr><td>:white_check_mark:</td><td>phpstan/phpstan</td><td>0.11.19</td><td>Supported in <a href="https://github.com/phpstan/phpstan/releases/tag/0.12.0">^0.12</a></td></tr>
<tr><td>:white_check_mark:</td><td>polishsymfonycommunity/symfony-mocker-container</td><td>v1.0.2</td><td><a href="https://github.com/PolishSymfonyCommunity/SymfonyMockerContainer/releases/tag/v1.0.3">v1.0.3</a> (will install automatically for Symfony 5)</td></tr>
<tr><td>:white_check_mark:</td><td>sensiolabs/security-checker</td><td>v5.0.3</td><td>Supported in <a href="https://github.com/sensiolabs/security-checker/commit/8613e86690ac8506ff99225bac75e53c4c9edfe3">^6.0.3</a></td></tr>
<tr><td>:white_check_mark:</td><td>sonata-project/block-bundle</td><td>3.18.2</td><td>Supported in <a href="https://github.com/sonata-project/SonataBlockBundle/releases/tag/4.0.0">^4.0</a></td></tr>
<tr><td>:white_check_mark:</td><td>sonata-project/intl-bundle</td><td>2.7.0</td><td><a href="https://github.com/sonata-project/SonataIntlBundle/pull/278">Pull request</a></td></tr>
<tr><td>:white_check_mark:</td><td>stof/doctrine-extensions-bundle</td><td>v1.3.0</td><td><a href="https://github.com/stof/StofDoctrineExtensionsBundle/pull/403">Pull request</a> | <a href="https://github.com/antishov/StofDoctrineExtensionsBundle">Maintained port</a></td></tr>
<tr><td>:white_check_mark:</td><td>sylius-labs/association-hydrator</td><td>v1.1.1</td><td><a href="https://github.com/SyliusLabs/AssociationHydrator/issues/6">Issue</a></td></tr>
<tr><td>:white_check_mark:</td><td>sylius/fixtures-bundle</td><td>v1.4.1</td><td><a href="https://github.com/Sylius/SyliusFixturesBundle/issues/22">Issue</a></td></tr>
<tr><td>:white_check_mark:</td><td>sylius/grid-bundle</td><td>dev-master</td><td><a href="https://github.com/Sylius/SyliusGridBundle/issues/29">Issue</a></td></tr>
<tr><td>:white_check_mark:</td><td>sylius/mailer-bundle</td><td>v1.4.4</td><td><a href="https://github.com/Sylius/SyliusMailerBundle/issues/12">Issue</a></td></tr>
<tr><td>:x:</td><td>sylius/resource-bundle</td><td>v1.6.1</td><td><a href="https://github.com/Sylius/SyliusResourceBundle/issues/121">Issue</a></td></tr>
<tr><td>:x:</td><td>sylius/sylius</td><td>1.7.x-dev</td><td>Look below</td></tr>
<tr><td>:white_check_mark:</td><td>sylius/theme-bundle</td><td>v1.5.0</td><td><a href="https://github.com/Sylius/SyliusThemeBundle/issues/33">Issue</a></td></tr>
<tr><td>:x:</td><td>white-october/pagerfanta-bundle</td><td>v1.3.2</td><td><a href="https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/pull/217">Pull request</a></td></tr>
<tr><td>:x:</td><td>willdurand/hateoas</td><td>2.12.0</td><td>Supported in <a href="https://github.com/willdurand/Hateoas/releases/tag/3.3.0">^3.3</a></td></tr>
<tr><td>:x:</td><td>willdurand/hateoas-bundle</td><td>1.4.0</td><td>Supported in <a href="https://github.com/willdurand/BazingaHateoasBundle/releases/tag/2.1.0">^2.1</a></td></tr>
<tr><td>:x:</td><td>winzou/state-machine-bundle</td><td>v0.3.1</td><td>Supported in <a href="https://github.com/winzou/StateMachineBundle/releases/tag/0.4.2">^0.4.2</a></td></tr>
</table>

Please let me know in this issue if the information above become outdated. That'd be a great help.

## Sylius

When it comes to Sylius (meaning `sylius/sylius` package), the master branch supports only Symfony ^4.3 and should support only Symfony ^4.4 soon. 

There are some deprecated classes, methods and interfaces listed in Psalm configuration file (`psalm.xml`). Sections `DeprecatedClass`, `DeprecatedInterface`, `DeprecatedMethod`, `TooManyArguments` and `InvalidArgument` should be cleared from Symfony references, while keeping Psalm passing.

Packages split from Sylius (those in `src/Sylius/Bundles` and `src/Sylius/Component`) should also be updated once we're done with Sylius as a whole.

**Comment by alcaeus** [comment]
@pamil: DoctrineBundle 1.12 and 2.0 are the same feature-wise, so once you fix all deprecations you can also allow 2.0 for that sweet Symfony 5 support 😊

**Comment by elchris** [comment]
I'm actively working with @iisisrael on friendsofsymfony/oauth-server-bundle , see this thread, would also appreciate more eyeballs to vet our work against [my fork](https://github.com/elchris/oauth2-php/tree/symfony-5)

Read about it [here](https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/issues/625#issuecomment-584354536)

**Comment by pamil** [comment]
I've updated the list ❤️

**Comment by loic425** [comment]
I've fixed my PR here for Intl component deprecations.
https://github.com/Sylius/Sylius/pull/10565

**Comment by rimas-kudelis** [comment]
Regarding the Pagerfanta bundle: its continuation is https://github.com/BabDev/BabDevPagerfantaBundle, which seems to support SF5. The README of the original bundle now links to this fork and it looks like WhiteOctober plan to archive their repository when SF4.3 falls out of support: whiteoctober/WhiteOctoberPagerfantaBundle#223.

**Comment by pamil** [comment]
Thanks, @rimas-kudelis! We'll have to think about using it without causing BC breaks though, there's a namespace change 😢 Probably we'll need a polyfill, something like https://github.com/SyliusLabs/PolyfillSymfonyEventDispatcher.

**Comment by rimas-kudelis** [comment]
Oh, and here's another good reason to switch to BabDevPagerfantaBundle:  BabDev/BabDevPagerfantaBundle#2.
Regarding a polyfill: I suppose it wouldn't have to remain forever available in Sylius, but just for a couple releases or so?

**Comment by loic425** [comment]
@pamil fos/rest-bundle now supports Symfony 5 on 3.0 release
Here is my work on sylius/resource-bundle https://github.com/Sylius/SyliusResourceBundle/pull/167

**Comment by Tetragramat** [comment]
The payum/payum together with payum/payum-bundle is practically abandoned.
https://github.com/Payum/Payum/issues/854#issuecomment-632094499

**Comment by loic425** [comment]
@pamil for pager fanta upgrade
https://github.com/Sylius/SyliusResourceBundle/pull/169/files

**Comment by loic425** [comment]
@pamil [A pull request on StateMachineBundle](https://github.com/winzou/StateMachineBundle/pull/59) to support Symfony 5 cause it's not enough with 0.4.2 release.

**Comment by macintoshplus** [comment]
@pamil Symfony 5.0 is supported by "friendsofsymfony/rest-bundle" version 3.0.

To migrate to this version, must change all usage of View object with call `setTemplate`. Because this method has been removed in targeted version.

**Comment by loic425** [comment]
> @pamil Symfony 5.0 is supported by "friendsofsymfony/rest-bundle" version 3.0.
> 
> To migrate to this version, must change all usage of View object with call `setTemplate`. Because this method has been removed in targeted version.

Yes but it's already done on master for sylius Resource bundle.

**Comment by macintoshplus** [comment]
> > @pamil Symfony 5.0 is supported by "friendsofsymfony/rest-bundle" version 3.0.
> > To migrate to this version, must change all usage of View object with call `setTemplate`. Because this method has been removed in targeted version.
> 
> Yes but it's already done on master for sylius Resource bundle.

But not in Sylius. Resource Bundle can be an example to apply in Sylius.

**Comment by stloyd** [comment]
@macintoshplus It's not in repo, but ready as PR: https://github.com/Sylius/Sylius/pull/11804

**Comment by macintoshplus** [comment]
> @macintoshplus It's not in repo, but ready as PR: #11804

Thanks for information.

**Comment by alexsoftdev** [comment]
When? :)

**Comment by pamil** [comment]
@alexsoftdev #12084 allowing us to install Symfony 5 is green, then #12148 will add that ability and add it to the build. We plan to include Symfony 5 support within Sylius 1.9, which will be released around 01.03 - and soon, there'll be a first 1.9-ALPHA release tagged for early adopters.

**Comment by pamil** [comment]
All done, thanks everyone! v1.9.0-ALPHA.2 has been released 🎉

**Comment by Kocal** [comment]
Good job everyone! :)
