### ISSUE TITLE
Sylius Intallation Error

### ISSUE THREAD

**Issue by babysure** [Sylius/Sylius#10931]
**Sylius version affected**: 1.2.17
OS :  Ubuntu  

When I'm the doc for the installation, 
 the command "compose create-project sylius/sylius-standard acme" returns the following error: 

Installing sylius/sylius-standard (v1.2.17)
  - Installing sylius/sylius-standard (v1.2.17): Downloading (100%)         
Created project in acme
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for league/uri 5.3.0 -> satisfiable by league/uri[5.3.0].
    - league/uri 5.3.0 requires ext-intl * -> the requested PHP extension intl is missing from your system.
  Problem 2
    - Installation request for league/uri-components 1.8.2 -> satisfiable by league/uri-components[1.8.2].
    - league/uri-components 1.8.2 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 3
    - Installation request for league/uri-hostname-parser 1.1.1 -> satisfiable by league/uri-hostname-parser[1.1.1].
    - league/uri-hostname-parser 1.1.1 requires ext-intl * -> the requested PHP extension intl is missing from your system.
  Problem 4
    - Installation request for league/uri-manipulations 1.5.0 -> satisfiable by league/uri-manipulations[1.5.0].
    - league/uri-manipulations 1.5.0 requires ext-intl * -> the requested PHP extension intl is missing from your system.
  Problem 5
    - Installation request for sylius/sylius v1.2.17 -> satisfiable by sylius/sylius[v1.2.17].
    - sylius/sylius v1.2.17 requires ext-gd * -> the requested PHP extension gd is missing from your system.
  Problem 6
    - Installation request for symfony/symfony v4.2.8 -> satisfiable by symfony/symfony[v4.2.8].
    - symfony/symfony v4.2.8 requires ext-xml * -> the requested PHP extension xml is missing from your system.
  Problem 7
    - Installation request for instaclick/php-webdriver 1.4.5 -> satisfiable by instaclick/php-webdriver[1.4.5].
    - instaclick/php-webdriver 1.4.5 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 8
    - Installation request for phar-io/manifest 1.0.1 -> satisfiable by phar-io/manifest[1.0.1].
    - phar-io/manifest 1.0.1 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 9
    - Installation request for phpunit/php-code-coverage 5.3.2 -> satisfiable by phpunit/php-code-coverage[5.3.2].
    - phpunit/php-code-coverage 5.3.2 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 10
    - Installation request for phpunit/phpunit 6.5.14 -> satisfiable by phpunit/phpunit[6.5.14].
    - phpunit/phpunit 6.5.14 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 11
    - Installation request for squizlabs/php_codesniffer 3.4.2 -> satisfiable by squizlabs/php_codesniffer[3.4.2].
    - squizlabs/php_codesniffer 3.4.2 requires ext-simplexml * -> the requested PHP extension simplexml is missing from your system.
  Problem 12
    - Installation request for stripe/stripe-php v6.34.5 -> satisfiable by stripe/stripe-php[v6.34.5].
    - stripe/stripe-php v6.34.5 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 13
    - Installation request for theseer/tokenizer 1.1.2 -> satisfiable by theseer/tokenizer[1.1.2].
    - theseer/tokenizer 1.1.2 requires ext-dom * -> the requested PHP extension dom is missing from your system.
  Problem 14
    - symfony/symfony v4.2.8 requires ext-xml * -> the requested PHP extension xml is missing from your system.
    - symplify/package-builder v4.8.0 requires symfony/config ^3.4|^4.0 -> satisfiable by symfony/symfony[v4.2.8].
    - Installation request for symplify/package-builder v4.8.0 -> satisfiable by symplify/package-builder[v4.8.0].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.1/cli/php.ini
    - /etc/php/7.1/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.1/cli/conf.d/10-opcache.ini
    - /etc/php/7.1/cli/conf.d/10-pdo.ini
    - /etc/php/7.1/cli/conf.d/20-calendar.ini
    - /etc/php/7.1/cli/conf.d/20-ctype.ini
    - /etc/php/7.1/cli/conf.d/20-exif.ini
    - /etc/php/7.1/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.1/cli/conf.d/20-ftp.ini
    - /etc/php/7.1/cli/conf.d/20-gettext.ini
    - /etc/php/7.1/cli/conf.d/20-iconv.ini
    - /etc/php/7.1/cli/conf.d/20-json.ini
    - /etc/php/7.1/cli/conf.d/20-mbstring.ini
    - /etc/php/7.1/cli/conf.d/20-mcrypt.ini
    - /etc/php/7.1/cli/conf.d/20-mysqli.ini
    - /etc/php/7.1/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.1/cli/conf.d/20-phar.ini
    - /etc/php/7.1/cli/conf.d/20-posix.ini
    - /etc/php/7.1/cli/conf.d/20-readline.ini
    - /etc/php/7.1/cli/conf.d/20-shmop.ini
    - /etc/php/7.1/cli/conf.d/20-sockets.ini
    - /etc/php/7.1/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.1/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.1/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.1/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.1/cli/conf.d/20-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

And then when I run the command "php bin/console sylius:install" here is the error that appeared 

 PHP Warning:  require(/home/boris/Projet/Symfony/acme/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /home/boris/Projet/Symfony/acme/bin/console on line 17
PHP Fatal error:  require(): Failed opening required '/home/boris/Projet/Symfony/acme/bin/../vendor/autoload.php' (include_path='.:/usr/share/php') in /home/boris/Projet/Symfony/acme/bin/console on line 17

**Comment by vvasiloi** [comment]
First, the documentation says:
> To create your Sylius-based application, first make sure you use PHP 7.2 or higher 

Second, you have all issues listed in the console output, you're missing 14 PHP extensions.

**Comment by Zales0123** [comment]
Hello @babysure and welcome to the community! 🚀 Please, take a look at the answer provided by @vvasiloi, it's a good start.

By the way, **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our [Slack](http://sylius.com/slack) (preferred) or [forum](https://forum.sylius.com/) ;) We have a very active, developed community, I'm sure someone will be able to help you with your problem. Good luck :)

**Comment by babysure** [comment]
okay thanks  ,   @Zales0123  @vvasiloi   really dsl but yes, I'm novice  with sylius
