### ISSUE TITLE
[AdminBundle] UserCartRecalculationListener recalculates a cart when admin logs in

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#10934]
**Sylius version affected**: 1.6.2

**Description**  
Even though I'm an admin, even though I login to the admin's dashboard, Sylius triggers cart recalculation via the `UserCartRecalculationListener` (I may be impersonated as a customer though, don't know if this matters).

Is this an expected behavior? Does it make any sense to do so?

**Comment by SSMellow** [comment]
I'm also faced this bug :)

**Comment by Zales0123** [comment]
Indeed it seems like a bug 🖖 The most straightforward solution would be to check the firewall inside the `UserCartRecalculationListener` and do not process cart if it's not shop. *Maybe* there is some other possibility (to not listen to the event for specific firewalls) but I'm not sure 🐎 

@mikemix do you think you would be able to open a fix for that issue?

**Comment by mikemix** [comment]
I would rather check for the user type instead? Eg. only recalculate if the user is instance of the `ShopUserInterface`. People may be using other firewall names.

**Comment by Zales0123** [comment]
Good catch. Maybe a listener could use a `*Checker` service? By default it would use interfaces for checking _is it shop user or not_ and it would be easy to customize if someone would like to base on other conditions (like the firewall name) 🚀
