### ISSUE TITLE
"Customer can login to the store" checkbox bug in the customer admin

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#10951]
**Sylius version affected**: 1.6.2

**Description**  
Even though customer has an account, the "user can login" checkbox is not checked.

**Steps to reproduce**  

1. Go to the [customer admin](https://demo.sylius.com/admin/customers/new)
2. Type: `first name`, `last name` and the `email`, DON'T check the "user can login" checkbox
3. Press save and wait for the page to reload
4. Check `user can login` checkbox, type a password and press save
5. Notice the checkbox is NOT checked

When you check it, the form disappears LOL ! This bug makes my clients go crazy.

![Peek 2019-12-16 19-38](https://user-images.githubusercontent.com/2399452/70933212-d3fdb400-203b-11ea-9941-3d24e4ec98f4.gif)

**Comment by mikemix** [comment]
Well, this is a bug on your side anyway. In the `@SyliusAdmin/Customer/_form.html.twig` you have:

`{% if customer.user is empty or customer.user.id is null %}`

BUT! The `empty` test will always return true when the account exists! From the [documentation](https://twig.symfony.com/doc/2.x/tests/empty.html):

> For objects that implement the __toString() magic method (and not Countable), it will check if an empty string is returned.

:

**Comment by Zales0123** [comment]
Indeed there is a bug. Are you willing to open a PR with the fix? Regarding a test, we should probably add some scenario in [this file](https://github.com/Sylius/Sylius/blob/master/features/user/managing_customers/adding_customer_account.feature#L11), with some new step like `And customer should be able to log in to the store` with the checkbox check
