### ISSUE TITLE
Impossible to overwrite SemanticUI theme (@#$#@$@!DsdasD) 

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#10978]
**Sylius version affected**: 1.6

**Description**  
I'm struggling to get rid of the SemanticUI in favor of my custom theme build with Bootstrap Scss. It's still not possible to do so - easily (it's a pain in the a** to be honest). Essentialy lots of views has to be copied and overwritten because `SyliusShop`'s templates uses the `SyliusUi` views directly, which of course is used by the `SyliusAdmin` as well, eg:

```
$ grep -Ril "@SyliusUi/" vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views

vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views/Order/show.html.twig
vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/Complete/_header.html.twig
vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views/Common/_address.html.twig
vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views/Login/_form.html.twig
vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views/layout.html.twig
vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views/ProductReview/_list.html.twig
vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views/Grid/Action/show.html.twig
vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views/Grid/Filter/string.html.twig
vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views/Cart/Summary/_header.html.twig
vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views/Cart/summary.html.twig
vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views/Product/Index/_main.html.twig
vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/Grid/Action/pay.html.twig
vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views/Account/Order/Show/_header.html.twig
vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/_defaultAddress.html.twig
vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/index.html.twig
vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views/Account/AddressBook/_item.html.twig
```

**Possible Solution**  
Create `@SyliusUi`'s counterparts in the `@SyliusShop` as you did with many views already. Especially the macros, the buttons etc…

 It's hard already, please don't make it even worse.

**Comment by vvasiloi** [comment]
> Essentialy lots of views has to be copied and overwritten

Don't you have to do that anyway to in a custom theme?

**Comment by mikemix** [comment]
No. In some views I have to copy entire template, just because the view is tied to the `@SyliusUi` which cannot be modified.

**Comment by vvasiloi** [comment]
> There're many "technical" templates where there's no html, just Twig calls.

In that case it makes sense to not overrride it.
Can you give a few examples of such templates?
In the list you shared are only 3 templates like that, but for a custom theme not using Semantic UI it's safer to override them anyway.
