### ISSUE TITLE
PWA based on react & next js

### ISSUE THREAD

**Issue by gomcodoctor** [Sylius/Sylius#10987]
I am trying to develop PWA based on

next.js
React
Redux
Material UI

I am planning to make it open source. 

Someone else working on similar concept so that I can contribute to existing project instead of starting new project?

Also kindly give your suggestions to make development faster.

**Comment by Zales0123** [comment]
Hello @gomcodoctor! I suggest you ask this question on our [Slack](http://sylius.com/slack), probably there is the highest chance to catch somebody working on such a project :) Good luck 🖖

**Comment by gomcodoctor** [comment]
Thanks for reply..issue with slack is.. chat got lost in few days..

I posted here knowingly so that people can reach via Google even.. I hope it's not a issue for sylius team,!!!

**Comment by gabiudrescu** [comment]
@gomcodoctor the people from BitBag built something like this and open sourced it here: https://github.com/BitBagCommerce/SyliusVueStorefrontPlugin

maybe you can liaise with them and work together.

**Comment by gomcodoctor** [comment]
@gabiudrescu  ya, I saw.. they released it today.. But I already did lot of work in react.. going through there code now
thanks

**Comment by davidroberto** [comment]
Hey @gomcodoctor,

I'm also starting to work on a next.js / Sylius integration and i read in your first comment that you planned to go open source with your project. Is it still the case ? Thanks :)

**Comment by Saltibarsciai** [comment]
It would be cool to have sylius integration with SSG js framework like next.js. Currently looking for better cms than woocommerce for next.js front and remembered sylius :)

**Comment by davidroberto** [comment]
@Saltibarsciai i'm finishing a Sylius / next.js integration boilerplate / theme, i'll go open source with in 1 or 2 weeks :)

**Comment by chatart** [comment]
@davidroberto hey, any update on this? Are you still working on it? :)

**Comment by Saltibarsciai** [comment]
@davidroberto We're exited to see it :)

**Comment by davidroberto** [comment]
@chatart, @Saltibarsciai here you go: https://github.com/davidroberto/sylius-next-boilerplate-theme :)

**Comment by chatart** [comment]
@davidroberto great news! i'll check this out soon :)
