### ISSUE TITLE
Extending ProductAttributeChoiceType is not working

### ISSUE THREAD

**Issue by antonioperic** [Sylius/Sylius#10993]
Extending `Sylius\Bundle\ProductBundle\Form\Type\ProductAttributeChoiceType` with form extension is not working, if you try it - this error will popup '
`You cannot add children to a simple form. Maybe you should set the option "compound" to true?
`

if you add compound true, than this happens
`An exception has been thrown during the rendering of a template ("The form is configured to inherit its parent's data, but does not have a parent.").`

As far as I can see from the controller, where this form is used, I need to override form entirely and then override the controller also - which is a little bit overkil for doing this simple extending of the form

**Comment by lchrusciel** [comment]
Won't form extension do the job? 

Some form of the parameter with the form type name could be a useful extension point thus.
