### ISSUE TITLE
Taxon View, query broken on Postgres

### ISSUE THREAD

**Issue by acornforth** [Sylius/Sylius#11025]
Not sure if this is an issue with the plugin skeleton, or with the sylius codebase itself..

Our sylius set-up was done by a Sylius partner, and uses the bitbag elastic search plugin. As a result, i have not seen this bug in our main sylius installation, but this issue report may rightfully belong in the main repo.

I am reporting it here, since it is with the plugin skeleton that I have seen the issue.

## Steps to reproduce

I started again with a fresh create-project.

set the doctrine config to use a pgsql dsn

follow steps exactly as per readme.

click the 'dresses' menu item in the demo store.

if you have successfully replicated my scenario, you should now see the following error:

![skeleton issue](https://user-images.githubusercontent.com/4586381/72257954-c882b600-3604-11ea-960d-846ea9b8635e.png)

**Comment by LeoHugues** [comment]
I have same issue since yesterday, maybe after I do "composer update sylius/sylius --with-all-dependencies"

**Comment by acornforth** [comment]
@LeoHugues 
that is a reasonable workaround for people running mysql, postgres users will not have much luck with that though unfortunately...

**Comment by antiseptikk** [comment]
I have same issue for me, after `composer update sylius/sylius --with-all-dependencies`

**Comment by acornforth** [comment]
I have run a composer update on my plugin development project last week and this issue has gone away... It appears to have been fixed in a recent update! If anyone can confirm that, this issue can probably be closed !

**Comment by Zales0123** [comment]
@LeoHugues @antiseptikk can you check it out as well? It would be great if it's fixed :D 💃

**Comment by antiseptikk** [comment]
Hi @Zales0123, 
I tried with Sylius 1.7.0@alpha and mysql percona:5.7 docker image (from sylius-standard repo) and the bug is still there.

I fix this by adding `command: mysqld --sql_mode=""` into the `docker-compose.yml` file but i don't think is the best solution.

I think the problem is here : 
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Doctrine/ORM/ProductRepository.php#L74

But I haven't found a solution to propose yet. Any idea ? :)

**Comment by Zales0123** [comment]
Hello guys, sorry for such a long response time 🖖 

We're currently working on better support for Postgres. Stay tuned, I hope we'll be able to do something with this issue in the nearest future.
