### ISSUE TITLE
"Select" product attribute completely broken – doesn't work with translated value

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#11038]
**Sylius version affected**: any

**Description**  
When adding product attributes, only current locale options are visible, translations are not available for select.

![Peek 2020-01-17 11-10](https://user-images.githubusercontent.com/2399452/72604115-9631cb00-391a-11ea-91e2-832c3928254d.gif)

**Steps to reproduce**  

1. Have at least 2 shop locale
2. Create product attribute of type "select", create a value and type its name for every locale
3. Add this product attribute to the product
4. Check each tab for each locale, only "english" options are visible
5. We end up with wrong JSON values in the database (each translation has a different uuid):

![Zaznaczenie_003](https://user-images.githubusercontent.com/2399452/72604135-9fbb3300-391a-11ea-95e3-bff7ecbcb14b.png)

**Comment by Zales0123** [comment]
"Select" attribute type is indeed a pain in the back, probably we should fix it together with the introduction of new (better) attributes UI - https://github.com/Sylius/Sylius/pull/10543

**Comment by mikemix** [comment]
Ineed.
