### ISSUE TITLE
 OrderPaymentProcessor parameter

### ISSUE THREAD

**Issue by pfazzi** [Sylius/Sylius#11030]
**Describe the proposed solution**
<!-- A clear and concise description of what you want to happen. --!>

**Describe alternatives you've considered**
<!-- A clear and concise description of any alternative solutions or features you've considered. --!>

**Additional context**
<!-- Add any other context or screenshots about the feature request here. --!>

**Comment by Zales0123** [comment]
Hello @pfazzi, can you give some more details about this issue? :D Thanks!

**Comment by Zales0123** [comment]
Ok, I see, it probably should be closed due to #11031 💃

**Comment by pfazzi** [comment]
Sorry, i don't know why my issue has been partially posted :scream:
