### ISSUE TITLE
Using API how to get complete image path?

### ISSUE THREAD

**Issue by PeanutSquareLLP** [Sylius/Sylius#11041]
**Sylius docs version**: 1.x / latest

**Description**
I am importing product from one sylius store to another sylius store using api. but in product api response i get below response for image
` "images": [
        {
            "id": 62,
            "type": "main",
            "path": "e5/bc/487f65d31800594f9c7ccd120a23.jpeg"
        }
    ],`

actual path is like this
`http://localhost:8002/media/cache/sylius_shop_product_large_thumbnail/e5/bc/487f65d31800594f9c7ccd120a23.jpeg`

I know LiipImagine bundle  is configured with sylius to manage images.
But as i am third party user who is accessing product from sylius API. so how can i get the full path for image from ` "path": "e5/bc/487f65d31800594f9c7ccd120a23.jpeg"`

**Comment by lchrusciel** [comment]
Hey @PeanutSquareLLP

as you are using API only and don't have access to the codebase, you will need to concatenate your paths. If your codebase follows default configuration images should be placed in `media/cache/`, then some filter which can be found here: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/app/config.yml#L56-L65 or https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ShopBundle/Resources/config/app/config.yml#L41-L53 and the path that you have in API.

I don't know any other option without influencing a codebase.

Have you asked your question already on our slack? This is our official support channel.

**Comment by PeanutSquareLLP** [comment]
Ok thanks
