### ISSUE TITLE
How to create about us, blog pages in Sylius

### ISSUE THREAD

**Issue by fazliddin** [Sylius/Sylius#11076]
How pages which require CMS feature managed in Sylius?

**Comment by Zales0123** [comment]
Hello @fazliddin! Sylius is meant to be a pure e-commerce product, so in its core, it focuses on e-commerce features. If you need some simple CMS functionality, you can extend it with plugins (like https://sylius.com/plugin/cmsplugin/ or https://sylius.com/plugin/sylius-blog-plugin/). Good luck! 🎉
