### ISSUE TITLE
[sylius_addressing] no default value defined for the parameter scopes in the bundle configuration

### ISSUE THREAD

**Issue by pvasdoria** [Sylius/Sylius#11074]
**Sylius version affected**: [sylius_addressing] 1.6.5

**Description**  
no default value defined for the parameter scopes in the bundle configuration.

**Steps to reproduce**  
no reproduce into the fullstack sylius, juste if you use the AddressingBundle alone

**Possible Solution**  
add default value into 

Sylius\Bundle\AddressingBundle\DependencyInjection\Configuration.php

**Comment by lchrusciel** [comment]
All scopes are defined in core: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius/sylius_addressing.yml#L6-L8
While scope `all` should be defined in AddressingBundle.

By the way, I'm not convinced about adding a translation. Maybe we should support some convention here?
