### ISSUE TITLE
Wrong serializer's xml_root_name at Model.ChannelPricing.yml

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#11084]
**Sylius version affected**: 1.7 (master) and any

**Description**  
I've noticed that you have `channel` here rather than `channel-pricing`: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminApiBundle/Resources/config/serializer/Model.ChannelPricing.yml#L3

Not sure how is that critical as I've never used Sylius admin API in XML format.

**Comment by Zales0123** [comment]
I'm not sure either, but it's definitely a bug 😄 I just wonder, will it be a BC break if we change it? Probably

**Comment by vvasiloi** [comment]
@Zales0123 maybe keep the old one, add the new one and write a deprecation note?
Would be easier with a defined and versioned schema though... but that's a long way.

**Comment by Zales0123** [comment]
Indeed, longer, but it seems like a proper solution 👌

**Comment by igormukhingmailcom** [comment]
One more thing I've noticed - most names with dashes (like `promotion-coupon`), but next ones - with underscores: `sylius_admin_user`, `exchange_rate`, `sylius_customer`.
