### ISSUE TITLE
Behat on non-EN fallback channel

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#11092]
**Sylius version affected**: 1.6 (any?)

**Description**  
When we have non-EN locale:

```
config/services.yaml
parameters:
    locale: da_DK
```

Behat tests no longer works as interface in Dahish in that case.

**Steps to reproduce**  
- Change default locale
- Run behat tests

**Possible Solution** 
Use a translator in all contexts.

As an example how to make tests compatible with any locale, we should replace function
```
        public function create(): void
        {
            $this->getDocument()->pressButton('Create');
        }
```
to something like this:
```
    public function create(): void
    {
        $this->getDocument()->pressButton(
            $this->translator->trans('sylius.ui.create')
        );
    }
```

**Comment by igormukhingmailcom** [comment]
As quick fix it could be magic conversion right at some top-level functions like this:
* `Create` > `sylius.ui.` + `strtolower('Create')`. 

This will not work for all things for sure...

**Comment by lchrusciel** [comment]
I would instead go with the changes we recently introduced to Sylius, like this one: #11093. These changes should go further, and all website interactions for both Admin and Shop panel should be based on test data attributes.

For now, our MVP is to decouple from Semantic UI classes for shop part, so projects like https://github.com/Sylius/BootstrapTheme will be able to test UI on our Behats.

Nevertheless, feel free to help us with it.
