### ISSUE TITLE
liip_imagine, not resolve images in cache with fedora.

### ISSUE THREAD

**Issue by judikaelB** [Sylius/Sylius#11123]
**Sylius version affected**: 

##Latest

**Description**  

Hello i'm trying to set up my firt e-commerce App with sylius, and that not easy with documentation.
So, i will create a new product with admin panel, product will be create with success, but if i return to the shop the first images will be cached by liip ( that really cool, Thank you Sylius ! ), i click on my product for enter on it but if i'm inside the new creted product or test product images will be not cached 
**Steps to reproduce**  

- >Full install Sylius and try.
**Possible Solution**  

I don't know this bug it's the 2nd time liip_imagine does this to me.
Thank you for any one want to help you are my sun :sun_with_face:

**Comment by lchrusciel** [comment]
Hey @judikaelB!

Thanks for asking your question. I hope someone will be able to help you with it. However, please consider that our official support channels are: 
 * [Slack](sylius.com/slack)
 * [StackOverflow](https://stackoverflow.com/search?tab=newest&q=sylius)
 * [Forum](https://forum.sylius.com/)

You can read more about them here: https://docs.sylius.com/en/latest/support/index.html

**Comment by judikaelB** [comment]
okay thanks you for what i will send a message for that. GoodBye.

**Comment by chrissnyder2337** [comment]
For anyone else who finds this issue. It may be a nginx configuration issue. See this thread: https://github.com/liip/LiipImagineBundle/issues/784#issuecomment-619786798
