### ISSUE TITLE
Twig global variables display default Sonata Block Templates at admin area

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#11120]
**Sylius version affected**: 1.7 / master

**Description**
During migrating to 1.7 where new template architecture was introduced (which is awesome, btw), I've found that at admin things become messed up a bit - content of `vendor/sonata-project/block-bundle/src/Resources/views/Block/block_template.html.twig` now appears at the end of admin page (as many times as much you have admin javascript templates injected with `BlockEventListener`). I guess it displays OK for out-of-the-box sylius app as by default there is no `BlockEventListener`s defined, but in real app it is as most of plugins injecting their javascripts via `BlockEventListener`.

This is how it looks like:
<img width="696" alt="Screenshot 2020-02-13 11 26 42" src="https://user-images.githubusercontent.com/6544038/74420224-c0ac7080-4e53-11ea-8e23-dfc76dae4306.png">

HTML:
```html
...
<script src="/assets/admin/js/app.js"></script>

<!-- BEGIN EVENT | event name: "sylius.admin.layout.javascripts" -->
<!-- BEGIN BLOCK | event name: "sylius.admin.layout.javascripts", block name: "legacy", template: "@SyliusUi/Block/_legacySonataEvent.html.twig", priority: 0 -->
    <div id="cms-block-5e45160e1a57d4.55639750" class="cms-block cms-block-element">
    <h3>Sonata Block Template</h3>
If you want to use the <code>sonata.block.template</code> block type, you need to create a template :

<pre>{# file: '@My/Block/my_block_feature_1.html.twig' #}
  {% extends sonata_block.templates.block_base %}

  {% block block %}
  &lt;h3&gt;The block title&lt;/h3&gt;
    &lt;p&gt;
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam vel turpis at lacus
    vehicula fringilla at eu lectus. Duis vitae arcu congue, porttitor nisi sit amet,
    mattis metus. Nunc mollis elit ut lectus cursus luctus. Aliquam eu magna sit amet
    massa volutpat auctor.
    &lt;/p&gt;
  {% endblock %}</pre>

And then call it from a template with the <code>sonata_block_render</code> helper:

<pre>{{ sonata_block_render({ 'type': 'sonata.block.service.template' }, {
    'template': '@My/Block/my_block_feature_1.html.twig',
}) }}</pre>
    </div>
    <div id="cms-block-5e45160e1a5b09.32903937" class="cms-block cms-block-element">
    <h3>Sonata Block Template</h3>
...
```

Also, we have next errors at log:
```
[cms::blockContext] block.id=5e45120f3da086.36571351 - error while resolving options - The options "app", "our_custom_twig_global_variable", "event", "sonata_block", "sylius", "sylius_base_locale", "sylius_meta" do not exist. Defined options are: "address", "addresses", "attr", "cart", "channel", "customer", "extra_cache_keys", "form", "order", "order_item", "orders", "product", "product_review", "product_reviews", "products", "resource", "resources", "statistics", "taxon", "template", "ttl", "use_cache".
```

**Steps to reproduce**  
- Install Sylius 1.7 / master
- Inject template to `sylius.admin.layout.javascripts` via `BlockEventListener`
- Open `/admin` and scroll down to see weird output

**Possible Solution**
Put all twig global variables you have (defined at twig config or at twig extension via `getGlobals`, or just get them from your error log from `[cms::blockContext]`) to `sonata_block` config like this:
```
# config/packages/sonata_block.yaml
sonata_block:
    blocks:
        sonata.block.service.template:
            settings:
                app: ~
                our_custom_twig_global_variable: ~
                event: ~
                sonata_block: ~
                sylius: ~
                sylius_base_locale: ~
                sylius_meta: ~
```

So I believe todo is next:
- Add all global vars that defined by Sylius to `sonata_block` config out of the box
- Add note at docs about this (I've spent many hours to find why that happens)

Related: https://github.com/Sylius/Sylius/pull/10924

**Comment by igormukhingmailcom** [comment]
I will provide PR with config if my `Possible solution` is the key (I still not sure its ok, maybe some deeper things should be fixed, not sure what exactly).

**Comment by pamil** [comment]
I'm on it! :)

**Comment by pamil** [comment]
I'll filter the variables passed to legacy events so that they only include what is whitelisted in the config.
