### ISSUE TITLE
Bug liip_imagine Bundle not displayed images.

### ISSUE THREAD

**Issue by judikaelB** [Sylius/Sylius#11122]
**Sylius version affected**: 1.7

**Description**  

Images not displayed.
**Steps to reproduce**  
install all recommended bundle in this following step ->
composer create-project sylius/sylius-standard acme
- >cd acme
- >php bin/console sylius:install
- >yarn install
- >yarn run gulp
- >symfony server:start
- >open http://127.0.0.1:8000

**Possible Solution**  

Just you need to add the folder in your directory require by you'r server.
Example: 127.0.0.1:51676 [404]: /media/cache/resolve/sylius_shop_product_thumbnail/1f/a8/4de2d5634b90a7d6bbaf1a723c6b.jpeg - No such file or directory.
- >You just need to add the missed directory and file.

I'm so sorry for bad is my english, i will learn it fast i promise...

**Comment by pamil** [comment]
Please make sure `/public/media` is writable by your webserver.

**Comment by ayyilmaz** [comment]
How can we sure? I make permissions of that folder 777 and I use nginx. Could you share configuration for this? I cant see images. I see asset folder's images but I do not see media folder's images.
