### ISSUE TITLE
Shipping Category Does Not Work

### ISSUE THREAD

**Issue by therealheman** [Sylius/Sylius#11127]
**Sylius version affected**: 1.2  onward 

**Description**  
Product that's been assigned to a shipping category still get the default shipping method.  

**Steps to reproduce**  

create a shipping category
create a shipping method
create a product
assign the shipping method to the shipping category
assign shipping category to the product
checkout the product and observe the estimated cost

**Expected**
The estimated cost is that of shipping category 
**Actual**
The estimated cost is that of default shipping method
**Possible Solution**  

**PS**
How did 9374 get closed. It's so obviously not resolved?

**Comment by Zales0123** [comment]
Hello @therealheman! It seems to work on the latest Sylius stable version. Obviously, if you have one shipping method with the category requirement and the rest of them has no requirement at all, you still get the first shipping method by default 💃 Also Sylius 1.2 is no longer supported, I strongly encourage to upgrade to 1.6 or 1.7 🖖 

Feel free to reopen if there are still some problems.
