### ISSUE TITLE
Carts & Orders

### ISSUE THREAD

**Issue by bybilvanis** [Sylius/Sylius#11132]
**Sylius docs version**: 1.x / latest

**Description**
<!-- Describe what is missing or where exactly is the bug/typo/issue located. Links highly appreciated. --!>
[Carts & Orders](https://docs.sylius.com/en/latest/book/orders/index.html#carts-orders)
The list items below this title has wrong links.
When I click by example on [Payments](https://docs.sylius.com/en/latest/book/orders/orders/payments.html) it redirecting me to page "Sorry this page does not exists" the correct link is [Payments](https://docs.sylius.com/en/latest/book/orders/payments.html) there is one /orders/ to much in the link

**Comment by Zales0123** [comment]
Thank you for reporting this problem 👍 Are you willing to open a PR fixing this error?

**Comment by bybilvanis** [comment]
> Thank you for reporting this problem 👍 Are you willing to open a PR fixing this error?

I don't know how to fix it 😂

**Comment by CoderMaggie** [comment]
I guess it's working now :)
