### ISSUE TITLE
Why symfony/dotenv is in required_dev?

### ISSUE THREAD

**Issue by mkalkowski83** [Sylius/Sylius#11133]
**Sylius version affected**: 1.6.5

**Description**  
after running composer install -o --no-dev I got the error below 

`Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Uncaught RuntimeException: Please run "composer require symfony/dotenv" to load the ".env" files configuring the application. in /var/www/test/config/bootstrap.php:13
!!  Stack trace:
!!  #0 /var/www/test/bin/console(26): require()
!!  #1 {main}
!!    thrown in /var/www/test/config/bootstrap.php on line 13
!!  
Script @auto-scripts was called via post-install-cmd
`
**Possible Solution**  
`composer req symfony/dotenv`

Regards

**Comment by vvasiloi** [comment]
https://symfony.com/doc/current/deployment.html#b-configure-your-environment-variables
It's optional, in case you're using .env files in production instead of real env vars.

**Comment by mkalkowski83** [comment]
Ok thx.
