### ISSUE TITLE
Unable to use a select attribute with a value without a label

### ISSUE THREAD

**Issue by macintoshplus** [Sylius/Sylius#11149]
**Sylius version affected**: 1.6.5

**Description**  
This error `Notice: Undefined index: fr_FR` occurs when you want to add a select attribute with an empty value onto the product.

**Steps to reproduce**  
1. Add a new attribute with type select.
1. On value list, keep one without value and save.
1. Now, edit a product and attempt to add the attribute added in the previous step.

**Possible Solution**  

1. Return empty value if the translation key does not exist.
1. Use a fallback language to return a value.

**Comment by lchrusciel** [comment]
Closed in #11150
