### ISSUE TITLE
Free item unbuyable

### ISSUE THREAD

**Issue by Philiphil** [Sylius/Sylius#11153]
**Sylius version affected**: 1.7.0

**Description**  
Trying to order a cart with only free items results in the following error "This collection should contain exactly 1 element." When I try to add any item with a price to the cart, the order works fine.
![image](https://user-images.githubusercontent.com/7517734/75360710-7f39ad80-58b6-11ea-8be4-f21e82e68aa0.png)
![image](https://user-images.githubusercontent.com/7517734/75360409-09354680-58b6-11ea-9ffb-e5fc61391eee.png)
![image](https://user-images.githubusercontent.com/7517734/75360543-47326a80-58b6-11ea-9d4a-5a96cf0f73a7.png)

**Comment by pamil** [comment]
I've just tried to reproduce it on Sylius v1.7.0 and it passes. Could you specify what exact setup you have?

Behat scenario would be amazing <3

**Comment by Philiphil** [comment]
Sorry I don't use behat.

So I'm using Sylius Standard 1.7 alpha2 with out of the box fixtures. After multiple tests, the bug I mention also requires no taxes and  shipping not required in order to appear.

**Comment by Zales0123** [comment]
Hello @Philiphil! Can you try to upgrade to Sylius 1.7.3? I've investigated this on the latest stable demo and it seems to work 🖖 Feel free to reopen the issue if there are still some problems for you 🚀
