### ISSUE TITLE
Should not embed Google Font with Semantic UI, to comply with GDPR

### ISSUE THREAD

**Issue by reyostallenberg** [Sylius/Sylius#11161]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Sylius version   | *

See https://github.com/Semantic-Org/Semantic-UI/issues/6422

The Semantic-UI library loads a Google Font as main font, that's fine, but it would be nice to have an easy way to disable this behavior in Sylius to be (more) GDPR compliant.
As mentioned in https://github.com/Semantic-Org/Semantic-UI/issues/6422 it is possible to disable it in Semantic-UI, but I couldn't find a way / figure out how to do it in the way Semantic-UI is loaded in Sylius.

**Comment by reyostallenberg** [comment]
Isn't there anyone (not a bot) who can react on this issue somehow? I'd like to make a PR for this, but need some (small) help to get in the right direction

**Comment by vvasiloi** [comment]
I think that's currently not possible.
Sylius uses the [semantic-ui-css](https://github.com/Semantic-Org/Semantic-UI-CSS) package, which doesn't support theming and the compiled and minified [semantic.min.css](https://github.com/Semantic-Org/Semantic-UI-CSS/blob/master/semantic.min.css) file.

**Comment by reyostallenberg** [comment]
That's to bad

**Comment by lchrusciel** [comment]
Hey Reyo, sorry for the lack of response, however, no one found time to take a closer look into this. I will try to bring it internally, but I cannot promise any date of fixing it. In the meantime, I can reopen this issue.

**Comment by reyostallenberg** [comment]
I'd like to help fix this, but have no clue (yet) where to start. Let me know if and how I can help
