### ISSUE TITLE
[AdminBundle] Remove dependency to Sylius/CoreBundle

### ISSUE THREAD

**Issue by jacquesbh** [Sylius/Sylius#11172]
Hi!

Is there a possibility to add the removal of the sylius/core-bundle dependency in sylius/admin-bundle in the current roadmap?

Because loading the admin bundle gives then all the e-commerce bundles.

And we would like to avoid this dependency.

So, how can we do? Can we help?

Thank you!

**Comment by pamil** [comment]
Why would you like to use AdminBundle without CoreBundle? What's the use case?

**Comment by jacquesbh** [comment]
I would like to find a simple way to get an application using :
- the resource bundle
- the admin bundle
- the theme bundle

and Done.

And my preference is to do it this way:

1. Create new symfony app
2. Require the 3 bundles
3. Require other plugins with a dependency on admin bundle (like our CMS plugin, and so on)

But I don't want to get the full core, because I don't want the products, etc.

And by doing this, if later I need the e-commerce part: `require sylius/core` and BOOM 💥 !

**Comment by pamil** [comment]
I'd hate to disappoint, but it looks like we don't want to support this use-case. It'd require at least a bit of work and further effort to avoid coupling. AdminBundle was created to act as an admin UI for CoreBundle (same as ShopBundle as a shop UI for CoreBundle).

However, there's the Monofony project by @loic425 which you might find useful. Anyway, @CoderMaggie is responsible for our roadmap, let's see what is her opinion.

**Comment by jacquesbh** [comment]
Having CoreBundle depending on the AdminBundle: YES!
But I'm pretty sure it's possible (ok, leads to some effort here) to remove the other way with the AdminBundle depending on the CoreBundle.

**Comment by jacquesbh** [comment]
And I prefectly understand the actual thing: CoreBundle has no dependency on AdminBundle, in case somebody wants to use the Core features without the admin panel.
In that scenario I would use an admin-bridge like the [doctrine-bridge](https://github.com/symfony/doctrine-bridge) or the [twig-bridge](https://github.com/symfony/twig-bridge).
