### ISSUE TITLE
Use new template event system for cart summary / order checkout lines

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#11186]
If you add a new adjustment type that is not neutral, you might want to customise cart summary and order checkout lines.

Every table line on the right should be a registered block with its own priority. This way you can reorder them, remove some, override some or add some.

<img width="1172" alt="Screenshot 2020-03-06 at 10 01 36" src="https://user-images.githubusercontent.com/1897953/76068512-8f761a80-5f91-11ea-8051-3a4fd4aa57bb.png">

<img width="1163" alt="Screenshot 2020-03-06 at 10 01 21" src="https://user-images.githubusercontent.com/1897953/76068501-8d13c080-5f91-11ea-86b4-463fd793d310.png">

**Comment by lchrusciel** [comment]
Ref. #10997
