### ISSUE TITLE
Sylius database credentials with special characters @ either $

### ISSUE THREAD

**Issue by joenilson** [Sylius/Sylius#11247]
**Sylius version affected**: 1.7.0

**Description**  
When installing Syliys Standard 1.7.0 in a Azure environment with a Azure Database it fails to connect if the username have an @ in the username string.

**Steps to reproduce**  
Creation of a SQL Database for MariaDB in Azure Cloud Services
username for database is 'databaseuser@dbname_azure'
password for database is 'money$money$'

- executing the php bin/console sylius:install suppress the dbname_azure from the username string showing this message:
In AbstractMySQLDriver.php line 93:
                                                                                                                                        
  An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'databaseuser'@'dbname_azure.mariadb.database.azure.com' (using password: YES) 

- encoding the @ as URL %40 value show this error:
In srcApp_KernelDevDebugContainer.php line 6047:
                                               
  The parameter "40dbname_azure:" must be defined.  

**Possible Solution**  

The problem is the resolve database_url function in config/packages/doctrine.yaml

from:
    env(resolve:DATABASE_URL): ''

to:
    env(DATABASE_URL): ''

But the problem is that this action will not understand the %kernel.environment% variable from the .env config file.

To keep running the Sylius app i made this workaround in the azure environment.

**Comment by pamil** [comment]
Special characters should be urlencoded, see more here: https://github.com/symfony/symfony/issues/26721
