### ISSUE TITLE
Product API: Attribute values are not validated

### ISSUE THREAD

**Issue by michalsemelka** [Sylius/Sylius#11263]
**Sylius version affected**: 1.6.5

**Description**  
When creating product via API, attributes collection aren't validated which leads to error 500, see steps to reproduce.

**Steps to reproduce**  
Say I have created product attribute of type "text" with code "foo". When I want create product with attributes and I forgot some mandatory field:
```
POST http://127.0.0.1:8000/api/v1/products/ HTTP/1.1

{
    "code": "bar",
    "channels": [
        "default"
    ],
    "translations": {
        "cs_CZ": {
            "name": "bar",
            "slug": "bar"
        }
    },
    "attributes": [
         {
            "localeCode": "cs_CZ",
            "value": "baz"
         }
     ]
}
```
Response is:
```
{
    "code": 500,
    "message": "Call to a member function getConfiguration() on null"
}
```

When I add attribute "foo" but this time I forgot "locaceCode", response is:
```
{
    "code": 500,
    "message": "An exception occurred while executing 'INSERT INTO sylius_product_attribute_value (locale_code, text_value, boolean_value, integer_value, float_value, datetime_value, date_value, json_value, product_id, attribute_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, \"baz\", null, null, null, null, null, null, 6, 1]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'locale_code' cannot be null"
}
```

**Comment by lchrusciel** [comment]
Hey Michal.

It's for a sure bug. Thanks for opening an issue. I cannot guarantee you that we will fix it in the nearest future, but I will be more than happy to merge or review a PR to fix it ;) 

If you need some assist with it, the best place to start will be to visit our slack and ask at #support channel.

PS. Have you seen #11250?

**Comment by kaushi5054** [comment]
Hi All,

Still, I'm getting the same error can you guide me to solve this error

thanks you
