### ISSUE TITLE
Taxon without product isn't removable

### ISSUE THREAD

**Issue by jacquesbh** [Sylius/Sylius#11277]
**Sylius version affected**: v1.4.4

**Description**  

Sylius says the category is used and cannot be removed, when we try to remove an empty category.

We figured out that we had some products with the taxon as "Main Taxon".

**Steps to reproduce**  

1. Add a taxon, keep it empty of products.
2. Update a product to use the newly created taxon as Main taxon.
3. Try to remove the taxon.

**Possible Solution**  

I suggest to set to `NULL` the `main_taxon_id` column for those products, but this may not be the best solution.

Adding a warning could be a good idea, like "This taxon is used as main taxon for some products.".
But here the issue is "Which products???".

So, maybe a solution could be a warning and a link or a button to "Remove the taxon anyway".

I don't know. The usability of this is quite tricky :/.

**Comment by lchrusciel** [comment]
I can confirm, that the problem still exists. I can see a few possible solutions to this: 
1. As the main taxon is used to generate breadcrumbs only, I would say, that it could be fine to just remove it. 
2. If we will force main taxon to be part of product taxons, then the problem will also disappear, as we can just list related products just by clicking on taxon tree.
3. Just list all of the related products in a custom error message, with a list of all or some products(I would limit it to let's say ~20 or 100, as the catalog may be pretty big). This can be achieved pretty easily, we have similar logic in `TaxonDeletionListener` with the removal of menu taxon (where we also do not specify, which channel is related to particular taxon).

The last option is quite an easy pick, if anyone would like to contribute to Sylius and improve our UX a little bit ;)

**Comment by jacquesbh** [comment]
I would add to the 3rd point: adding a link to unlink all the products from a taxon in the error message :p. But it's a must have ^^

**Comment by jacquesbh** [comment]
Do not stale

**Comment by TheMilek** [comment]
Hi!
 closing as It seems it has been solved by https://github.com/Sylius/Sylius/pull/14994 🎉
