### ISSUE TITLE
[API] problem with serialisation empty relation field

### ISSUE THREAD

**Issue by AdamKasp** [Sylius/Sylius#11285]
when i am trying to cover this scenario: https://github.com/Sylius/Sylius/blob/master/features/shipping/managing_shipping_methods/shipping_method_validation.feature#L49-L55
I get the problem, the empty zone should be validated by 'NotBlank', but instead, I get an error related with wrong IRI format (null is not IRI :) ) which occur before validation
so, for now, this scenario is without coverage.
If we want to cover this scenario probably we will need some custom serializer, for now, admin can't delete zone from shipping method but it generates error but should generate validation message.

**Comment by lchrusciel** [comment]
The issue still exists, however it is rare edge case and there is no clear path how to fix it at the moment. Closing for now.
