### ISSUE TITLE
PdoSessionHandler (in)compatibility

### ISSUE THREAD

**Issue by TheDevilOnLine** [Sylius/Sylius#11296]
**Sylius version affected**: 1.7.0

**Description**  
When you enable Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler as session handler, a login to the admin gives the error "There is already an active transaction"

**Steps to reproduce**  
Follow the steps from https://symfony.com/doc/current/doctrine/pdo_session_storage.html to configure and enable the PdoSessionHandler, then try to login to the admin on a clean install (having just run bin/console sylius:install)

**Comment by Zales0123** [comment]
Hello @TheDevilOnLine, sorry for the long response time. Did you try what is mentioned in the first snippet of code:

```yml
# If you get transaction issues (e.g. after login) uncomment the line below
# - { lock_mode: 1 }
```

It worked for me with the issue (that indeed happens without this line added) 🖖

**Comment by lchrusciel** [comment]
Please comment, if still relevant.
