### ISSUE TITLE
Add help texts to admin interface

### ISSUE THREAD

**Issue by loevgaard** [Sylius/Sylius#11292]
When I add fields to the admin interface, sometimes I want to explain to the user what this field does. Symfony has a help text option for this purpose. However, it is not utilized in Sylius.

A solution (that I discussed with @kulczy) could be to add a question mark icon next to the field. This wouldn't be the perfect solution on mobile, but I doubt that many use the backend on mobile phones.

**Comment by pamil** [comment]
Related to #11536.

**Comment by loevgaard** [comment]
Yes, I think we can close this. I basically just wanted it output. Then I guess @kulczy can make it look nicer :D
