### ISSUE TITLE
Support for JMS serializer 3.0

### ISSUE THREAD

**Issue by reyostallenberg** [Sylius/Sylius#11301]
**Description**
To be able to install other libraries on my installation I want to have support for JMS Serializer 3.0, see https://github.com/schmittjoh/serializer/blob/master/UPGRADING.md#from-2x-to-300

Is it possible? Or are there issues mentioned as "deeper branch group exclusion strategy" has a different behaviour, the latest group is used instead of falling back to "Default" ?

I'm aware of https://github.com/Sylius/Sylius/issues/9288 but I think it'll take longer to implement and has a totally different path.

**Comment by lchrusciel** [comment]
Hey Reyo,

I don't remember usage of `deeper branch group exclusion strategy` from the top of my head. Can you open a PR with support for the new version? While we will see a build, we will know how much work is needed to finish it. 

Also, I would recommend dropping support for JMS serializer 2.0

**Comment by reyostallenberg** [comment]
Dropping support makes upgrade paths harder and is not needed for Sylius if `deeper branch group exclusion strategy` is not used. In that case it will be able to support both

**Comment by lchrusciel** [comment]
The problem with the support for 2.0 is that we should have it tested and it would mean, that we need another build for that. I would vote for the removal of 2.0. @Sylius/core-team does anyone have some opinion here?

**Comment by leflings** [comment]
As for `deeper branch group exclusion strategy` I'm assuming [this](http://jmsyst.com/libs/serializer/master/cookbook/exclusion_strategies#overriding-groups-of-deeper-branches-of-the-graph) is what's referred to.

Also mentioned in #10586
