### ISSUE TITLE
Sylius won't handle large quantities

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#11312]
**Sylius version affected**: any

**Description**  
Try adding 9999 items to the cart. Witness Sylius die spectacularly with 500. Now imagine having larger number of promotions, things just gets worse.

**Steps to reproduce**  
1. Visit the shop https://demo.sylius.com/en_US/products/330m-slim-fit-jeans
2. Add 9999 items to the cart
3. Nothing happens, 500 in the background

**Comment by vvasiloi** [comment]
https://github.com/Sylius/Sylius/issues/10741
https://github.com/Sylius/Sylius/issues/10661
https://github.com/Sylius/Sylius/issues/10155

**Comment by mikemix** [comment]
I guess I'll have to stick to Magento. It handles large quantities in an instant.
