### ISSUE TITLE
Custom bulk action cannot use selected item ids

### ISSUE THREAD

**Issue by radekbernatek** [Sylius/Sylius#11324]
**Sylius version affected**: 1.7

**Description**  
In https://github.com/Sylius/Sylius/commit/4013e51dfdd3ff7d5bd00f2751308eac2bb3149a#diff-58eafbd631b5c6126f098f7e6808604eR27 bulk checkboxes have been bound to `#bulk-delete` form so it is not possible to use them for custom actions as [current documentation](https://docs.sylius.com/en/1.7/components_and_bundles/bundles/SyliusGridBundle/custom_bulk_action.html) mentioned

ref [slack discussion](https://sylius-devs.slack.com/archives/C3EGDG9LY/p1585819984141300)

**Comment by lchrusciel** [comment]
Hello Radek, 

That's true, we by mistake coupled bulk actions with delete. Is it something that is blocking you? Would you like to revert the PR that you have mentioned to the original form (or propose something js free with the same behavior)?

**Comment by radekbernatek** [comment]
Since mentioned commit has no added feature, revert would be probably the best solution for now. We've overrided problematic template so it is not blocking for us but it could be annoying for somebody other who has to debug it again.

**Comment by lchrusciel** [comment]
Could you open a PR with a fix, please? It should be added to the 1.7 branch. Then it will be added to the nearest patch release (probably released in less than 2 weeks)

Also, let me apologize for the long response time.

**Comment by GalloisLuca** [comment]
I made a PR to revert the commit mentionned by @radekbernatek

**Comment by wadjeroudi** [comment]
@lchrusciel @pamil @Zales0123  could you plz merge the revert, it's blocking the bulk actions from working on >1.7.
Thx !

**Comment by lchrusciel** [comment]
We are blocked by the red build on https://github.com/Sylius/Sylius/pull/11708. Once it will be green I will merge it and we should tag fixed version pretty soon

**Comment by pierre-H** [comment]
Any news ?

**Comment by lchrusciel** [comment]
Should be fixed at https://github.com/Sylius/Sylius/releases/tag/v1.7.7 and further versions. Can you confirm?
