### ISSUE TITLE
Improve product taxon position

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#11326]
**Describe the proposed solution**
The entity ProductTaxon has a property called `position` where the system automatically increments the value on newly added products.

First product has position 0, 2nd position 1 and so on.

I suggest a new algorithm for positioning: 
Fist product should have position 0, 2nd product should have position 10, 3rd product should have position 20.

That way, whenever you want to insert a product between two products, you don't have to update the entire database of products from that taxon.

**Describe alternatives you've considered**
Alternatively, this logic should be in a service that is called whenever a productTaxon is persisted and allow customization (people might want a different logic than the one I have suggested).

**Additional context**
Imagine Jane, a Sylius Store ower. She has a taxon called „Laptops” with 300 products assigned to it. 

The first 10 products on the product list are some good selling laptops. 

She wants to put some flops on the first positions to increase their exposure and get rid of some stocks she wants to liquidate. With the current positioning strategy, it's a bit cumbersome to do that from admin.

If the positioning would count with a 10 increment, this job would be much easier.

**Comment by vvasiloi** [comment]
Aren't the products automatically reordered when you change a position?

**Comment by vvasiloi** [comment]
They are, I tested at https://demo.sylius.com/admin/.
This is the initial order:
![Screenshot_1](https://user-images.githubusercontent.com/7114562/78292919-77fa6500-7530-11ea-8eeb-7b16553d423f.png)
Then I set position of product `007M_black_elegance_jeans`  to 1, so it will be second in the list.
This is the result:
![Screenshot_2](https://user-images.githubusercontent.com/7114562/78293084-b2640200-7530-11ea-9b19-b9a97555c459.png)
As you can see, all other products are reordered and the desired result achieved.

**Comment by gabiudrescu** [comment]
@vvasiloi well, I might have rushed to write this without properly testing before the implemented behaviour. The 0.x versions of Sylius I am used to had put their mark on me :older_man: 

The issue I'm having with this reordering algo is that it updates the entire database and this can have side effects.

For example, if the system uses ElasticSearch for product listing/search in front end, then such a big update could trigger lots of subsequent changes in events thrown for each product.

Or even a full reindexing might be required.

And, if the product has Loggable behaviour on this field, the amount of logs can be quite big.

On the other hand, if the update is done MySQL level, not with the ORM, then the Elastic Search remains out of sync, rendering unwanted behaviour.

While my proposal it allows one to update only one product to achieve the same result with, imho, less side effects

**Comment by vvasiloi** [comment]
@gabiudrescu unfortunately the sortable extension doesn't allow the scenario you're describing. It will always convert the position into a zero-indexed sequence of consecutive integers.

**Comment by gabiudrescu** [comment]
I guess there is nothing left to say here
