### ISSUE TITLE
Composer Memory Limit Reached

### ISSUE THREAD

**Issue by fmarcoux96** [Sylius/Sylius#11327]
**Sylius version affected**: 1.7.x

**Description**  
Composer is running out of memory on my Web server. It has 8GB of RAM and it still doesn't work correctly. It runs out after about 1GB to 1.5GB.

**Steps to reproduce**  
1. Install Plesk Obsidian.
2. Deploy app via Plesk GIT
3. Run PHP Composer

Even in CLI, we can't execute it.

**Possible Solution**  
Composer takes up to 2.7GB of my RAM when local. How is that normal?
![image](https://user-images.githubusercontent.com/1487078/78315051-dcfe8c80-7529-11ea-8b05-e09b8ab6fdfc.png)

**Comment by fmarcoux96** [comment]
@mamazu The problem is that the Web server crashes when I give PHP more than 2GB of RAMs. The server has other customers on it.

**Comment by Gounlaf** [comment]
@fmarcoux96 are you trying to install without a composer.lock?
If so, try installing all the dependencies on your computer, commit your lock file, make sure to have it on your server, then install dependencies.

Resolving the dependency tree consume a lot of resources (it's a know composer issue; as example https://github.com/composer/composer/issues/8694#issuecomment-598818468)
But when you have a lock file, composer will just fetch/clone/unzip dependencies.

You may have an issue too with symfony cache generation (it take lot of resources too).

**Comment by fmarcoux96** [comment]
@Gounlaf Yes, I do commit my composer.lock and use the Install feature in PHP Composer.

Here's the interface: 
![image](https://user-images.githubusercontent.com/1487078/78461948-5a95da00-769b-11ea-9bcc-2c03cec4b04e.png)

As for the cache, yeah it's a pain everytime.

**Comment by Gounlaf** [comment]
Well, try to disable cache-generation (disable the auto-script cache:clear) and run it manually.
Pure creation of "vendor" should don't take so much ram =/
You can commit your vendor, even if it's "ugly" and not recommended... 

But unfortunately it's not really a Sylius issue... It's more likely a `composer` issue (and the team behind composer is working on it)

**Comment by pamil** [comment]
Can't do much with it in Sylius. You can restrict used Symfony versions in Symfony Flex though: https://symfonycasts.com/screencast/symfony5-upgrade/flex-symfony-require
