### ISSUE TITLE
Large memory usage with zones

### ISSUE THREAD

**Issue by YellowFish085** [Sylius/Sylius#11338]
**Sylius version affected**: 1.7.0

**Description**  

When editing zones in the admin, memory usage goes up really fast the more countries are associated to the zone.

To give you some numbers (taken from the Symfony debug bar), the highest memory usage peak we have on admin "list" pages such as `/zones` is around 10~20MB. I don't know if it's a normal number, but it's just here to give you a base number.

When editing a zone with 7 countries, the app goes up to around 400MB, for 15 countries around 800MB, and for 21 countries around 1050MB.

A [previous issue #8048](https://github.com/Sylius/Sylius/issues/8048) already mentioned a similar issue in the edit zone pages, but it was never resolved.

**Steps to reproduce**  

Create a countries zone in the admin and associate a few countries to it.

**Comment by vvasiloi** [comment]
I wasn't able to reproduce it on 1.6.4. Can you share your PHP config?

**Comment by YellowFish085** [comment]
I've attached a (big) screenshot of our `phpinfo()` for the project.

<details>
<summary>See screenshot</summary>

![screen](https://user-images.githubusercontent.com/11556009/78906394-92c46080-7a7f-11ea-933f-3149b83173c0.png)
</details>

Thanks for your help.

**Comment by YellowFish085** [comment]
We still have the issue on our project.

I've done a bit more testing using the [Sylius Standard Edition repository](https://github.com/Sylius/Sylius-Standard) and I can confirm that the issue is not tied to our project but to Sylius.

**Sylius version affected:** 1.7.4

**Steps to reproduce**

> Note: I'm using the included Docker development environment to make it easier for everyone to reproduce the issue, but [the original issue](https://github.com/Sylius/Sylius/issues/11338#issue-596564779) is on a server which does not uses Docker, so we probably can exclude Docker as a culprit here.

1. Create a new Sylius project with `php composer.phar create-project sylius/sylius-standard project`.
2. Add the line `memory_limit = -1` at the end of the file `project/docker/php/php.ini` to not restrict PHP memory usage.
3. In the project directory, start the docker development environment with `docker-compose up`.
4. Once the containers are done initializing, in a terminal connect to the php container with `docker exec -it <php_container_name> sh` and install the project using `php bin/console sylius:install`.
5. Add _all_ available countries in the http://localhost/admin/countries/ page.
6. Finally, try to open the two predefined zones that come with the example shop, **US** (which should only contains 1 country USA) and **WORLD** (which should contains 11 countries) and observe the memory usage.

From my tests, I can see that the memory usage when displaying the **US** zone can go up to around 135 MiB, and for the **WORLD** zone it can go up to around 750 MiB, which correlate with the observations we've done on our project.

---

In case you don't want to manually add all countries in the DB, I've created a command you can run to automatically create all countries.

<details>
<summary>Click to see the file</summary>

```PHP
<?php

namespace App\Command;

use App\Entity\Addressing\Country;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\Intl\Countries;

class CreateCountries extends Command implements ContainerAwareInterface
{
    protected static $defaultName = 'app:create-countries';

    /** @var ContainerInterface */
    private $container;
    /** @var SymfonyStyle */
    private $io;
    /** @var ObjectManager */
    private $em;

    public function __construct(ObjectManager $em)
    {
        $this->em = $em;

        parent::__construct();
    }

    public function setContainer(ContainerInterface $container = null)
    {
        $this->container = $container;
    }

    protected function configure()
    {
        $this->setDescription('Init countries data.');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->io = new SymfonyStyle($input, $output);
        $this->io->title('Starting...');

        $this->initCountries();

        $this->io->newLine();
        $this->io->success('Delivery initialized.');
    }

    /**
     * Create all countries not yet existing in our db yet.
     *
     * @return void
     */
    private function initCountries()
    {
        $this->io->section('Init countries...');

        $country_repository = $this->em->getRepository(Country::class);

        \Locale::setDefault('fr');

        $countries = Countries::getNames();

        $this->io->progressStart(count($countries));

        foreach ($countries as $code => $name) {
            $exists = $country_repository->findOneBy([
                'code' => $code,
            ]);

            if (is_null($exists)) {
                $country = new Country();
                $country->setCode($code);

                $this->em->persist($country);
            }

            $this->io->progressAdvance();
        }

        $this->io->progressFinish();

        $this->em->flush();
    }
}
```
</details>

**Comment by YellowFish085** [comment]
We just updated our project to 1.8.5, the memory issues we faced are for now gone.
