### ISSUE TITLE
Romanian translation finished 100% please deploy to default install

### ISSUE THREAD

**Issue by unbaiat** [Sylius/Sylius#11340]
Romanian translation finished 100% please deploy to default install

**Comment by unbaiat** [comment]
hello. can some one please at least answer?

**Comment by lchrusciel** [comment]
Hello @unbaiat,

thanks a lot for raising your issue and I'm very sorry for the late response. Apparently we have some issues with crowdin bot if the translations are not synchronized. I will ping my colleague who is responsible for it.

**Comment by unbaiat** [comment]
Hello @lchrusciel. Thanks a lot. Is there anyway I can download them manually? I was going to write a python script if no one answered the request.

**Comment by lchrusciel** [comment]
Most probably, yes, as this is how our bot is probably working. However, I don't have any details. /cc @AdamKasp

**Comment by unbaiat** [comment]
Hello @AdamKasp. Can you please help me out?

**Comment by unbaiat** [comment]
@lchrusciel any updates. thanks?

**Comment by lchrusciel** [comment]
We have some issues with our bot (see #11485 & #11484). We are working on that.

**Comment by unbaiat** [comment]
any news?

**Comment by lchrusciel** [comment]
Can you see, if the problem was resolved in #11576 & #11577?

**Comment by Catalin-Ionut** [comment]
> Can you see, if the problem was resolved in #11576 & #11577?

Both issues are merged.

**Comment by NoResponseMate** [comment]
It seems that syncing from crowding has been fixed, so I'm closing this.

Cheers :beers:
