### ISSUE TITLE
SalesDataProvider::getLastYearSalesSummary uses a hardcoded table name for the order table

### ISSUE THREAD

**Issue by DanieleGBX** [Sylius/Sylius#11343]
**Sylius version affected**: 1.7.2

**Description**  
SalesDataProvider::getLastYearSalesSummary uses a hardcoded table name for the order table.

If the order table is renamed in the entity, accessing the admin dashboard throws an exception.

**Steps to reproduce**  
Specify a name for the order table other than "sylius_order", and visit the admin dashboard.

**Possible Solution**  
Get the table name from the order entity metadata.

**Comment by DanieleGBX** [comment]
Specifically, this commit should be looked over more
https://github.com/Sylius/Sylius/commit/fb3e2c2aa950acf74723a969c60d4489d6b51f9e

Not to mention DATE_FORMAT is not available under Postgres.

**Comment by lchrusciel** [comment]
Fixed in #11465
