### ISSUE TITLE
Going back to Addresses step is not fully functionnal

### ISSUE THREAD

**Issue by jacquesbh** [Sylius/Sylius#11348]
**Sylius version affected**: 1.7.0

**Description**  
If you fill the billing AND shipping addresses in the checkout, then you go to Shipping method, then you go back to the addresses: the checkbox "Use different address for shipping?" isn't checked anymore.

![address_bug](https://user-images.githubusercontent.com/858611/79000693-5fe89e00-7b4d-11ea-8307-5582b54f384b.gif)

**Steps to reproduce**  

See above.

**Possible Solution**  

I don't have any, I think it's because of the switch of the billing and shipping addresses.

**Comment by lchrusciel** [comment]
Hello Jacques, thanks for reporting.

For me, it is not clear if it is bug fix or enhancement. What is more, we need to add deprecation notice to fix it properly, therefore it will be fixed in 1.8.

**Comment by jacquesbh** [comment]
For me it's a bug since it was working well before if I recall correctly.
