### ISSUE TITLE
Having data in disabled locale should not cause exceptions

### ISSUE THREAD

**Issue by rimas-kudelis** [Sylius/Sylius#11350]
**Sylius version affected**: 1.6.5

**Description**  
I have an import script which imports products and other entities from a service. It so happens that it can import data in more languages than are enabled at the moment. If it does so, I can no longer edit the product in question because of an exception:

![paveikslas](https://user-images.githubusercontent.com/2812673/79043994-5e7dab00-7c0b-11ea-9f07-bd50d4f2cae1.png)

Is it supposed to work like this? I would prefer if Sylius just ignored data in the locales that it doesn't know.

**Comment by rimas-kudelis** [comment]
Now that I'm looking at the exception closer, it doesn't even involve Sylius files. Feel free to close this if this is a platform limitation which cannot be overcome without too much hassle.

**Comment by mamazu** [comment]
This looks like a missing validation. "et" does not look like a valid locale code as locale codes should be of the form `<locale>_<sublocale>`

**Comment by rimas-kudelis** [comment]
> This looks like a missing validation. "et" does not look like a valid locale code as locale codes should be of the form `<locale>_<sublocale>`.
> But as you are doing it with a script and not with a GUI, this looks like you are missing a validator call. And the invalid data has been inserted into the database and now the GUI can't display it.

I'm pretty sure what you said is false. `et` is a valid locale code for Estonian. Here, I just enabled this locale in demo.sylius.com:
![paveikslas](https://user-images.githubusercontent.com/2812673/94119668-e53fe080-fe57-11ea-9db4-6a6b69703800.png)

The data in question, like I said, was inserted using an import script, which did not check whether the locale was enabled. My point was that the presence of data like that shouldn't cause exceptions.
