### ISSUE TITLE
Yarn install/build fails with Node 12

### ISSUE THREAD

**Issue by vvasiloi** [Sylius/Sylius#11358]
**Sylius version affected**: 1.*

**Description**  
Yarn `install` and `build` commands fail when using Node 12 due to failing node-sass command, because the locked version of `node-sass` is 4.10 and it's not compatible with Node 12, the minimum compatible version is 4.12 ([compatibility table](https://github.com/sass/node-sass#supported-nodejs-versions-vary-by-release-please-consult-the-releases-page-below-is-a-quick-guide-for-minimum-support))

**Steps to reproduce**  
Clone the repository. Run `yarn install` or `yarn build` with Node 12.

**Possible Solution**  
Remove `yarn.lock` from the repository and add it to `.gitignore`, like it was done with `composer.lock`.
After removing it and running `yarn install`, there are no issue and the locked `node-sass` version is `4.13.1` which is compatible with Node 12

**Comment by pamil** [comment]
Sounds like a plan, would you like to provide a PR?

**Comment by vvasiloi** [comment]
Sure, accidentally closed...

**Comment by vvasiloi** [comment]
Fixed by upgrading `node-sass` in https://github.com/Sylius/Sylius/commit/98709683a7b7424eaba238840f60fe1efe7f7f08

**Comment by bigthinkery** [comment]
This saved me.
