### ISSUE TITLE
Impossible to install elfinder assets using the sylius:theme:assets:install command

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#11353]
**Sylius version affected**: 1.6

**Description**  
Can't install ElFinderBundle assets using the `sylius:theme:assets:install` command.

**Steps to reproduce**  
1. Run `bin/console elfinder:install` to install bundle assets. The directory `elfinder` now exists in the `public/bundles` directory
2. Run `bin/console sylius:theme:assets:install` to install theme assets
3. The `elfinder` assets are gone and missing in the `_themes` asset directory

**Comment by lchrusciel** [comment]
Hey Mike,

thanks for the bug report. Hopefully, someone from our community will find time to take a look at this problem. In the meantime, feel welcome to our slack, where you can ask for help if needed.
