### ISSUE TITLE
Flex installation issue

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#11355]
**Sylius version affected**: master

**Description**  

Running composer install on the newest master may end up with the following error: 
```
  The file "../../src/Controller/" does not exist (in: "_sylius/s1/config/routes", "_
  sylius/s1/src", "_sylius/s1/src/Resources") in ../../src/Controller/ (which is being imported from "_sylius/s1/config/routes/annotations.yaml"). Make sure annotations are installed and enabled.
```

**Steps to reproduce**  

run:
```bash
composer install
```
on the newest master
**Possible Solution**  

Right now, one may remove new files added by flex or run composer with `--no-scripts` flag. 

This problem may be propagated into clear master Sylius-Standard installation and we should investigate, what has changed in the new recipes as well.

**Comment by pamil** [comment]
Wouldn't `composer update` + code adjustments solve this one? As soon as Flex marks changes as done, we can revert them and it won't do it again.
