### ISSUE TITLE
Different crumbs at product show / update

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#11374]
**Sylius version affected**: master

**Description**  
See screenshots, one crumb use product's name, other - code.

Show
![image](https://user-images.githubusercontent.com/6544038/79698893-a9936000-8294-11ea-9551-1bf95e1d149d.png)
Edit
![image](https://user-images.githubusercontent.com/6544038/79698901-b912a900-8294-11ea-878a-068e11dca1cf.png)

**Possible Solution**  
Use default template (`resource.name|default(resource.code|default(resource.id))`) rather than `product.code` at `src/Sylius/Bundle/AdminBundle/Resources/views/Product/Show/_breadcrumb.html.twig`

**Comment by lchrusciel** [comment]
Your proposed solution is, of course, a good one. Maybe someone from our community would like to pick it up.
