### ISSUE TITLE
Multiple Cart Item Variants.

### ISSUE THREAD

**Issue by OwaisArain** [Sylius/Sylius#11385]
I found there is no option to select multiple product variants at a time to add them into the cart. For example If I want a T-shirt with multiple sizes S,M,L. I have to select the single size first then I have to come again to select the other size of the product to add them to the cart. There should be multi-select feature to add variants so it will be easy for the user to select all the variants at a time.

**Comment by lchrusciel** [comment]
Nice idea and it totally makes sense. However, it may have more sense to develop it as a separate plugin or part of B2B solution. 

Nonetheless, let's summon our Product Owner /cc @CoderMaggie

**Comment by CoderMaggie** [comment]
@OwaisArain do you maybe have an example of a store where it is possible? :)
