### ISSUE TITLE
As anonymous user when I go to account area I got 500

### ISSUE THREAD

**Issue by knyk** [Sylius/Sylius#11382]
**Sylius version affected**: 1.7.2

**Description**  
When anonymous user enters account area, for ex `/account/orders`, he is not being redirected to login page but gets 500 `Unable to get a property on a non-object.`

**Steps to reproduce**  
As not logged in user open url of page in account area. User can get url in email or saved in browser.
Another way to reproduce is to place an order with email address belongs to one of registered users. If user ignores login mechanism at address step, then on thank you page he gets and "View order" button which is linked to order view in account area.

**Possible Solution**  
Detect if user is not logged in and redirect to login page if so

**Comment by Zales0123** [comment]
Hello Kamil!

Have you checked `/en_US/account/orders` or `/account/orders`? The language prefix is present in all shop-related URLs in Sylius default implementation. With the first option, the redirection works well (I've just checked it on the demo) 🖖

**Comment by knyk** [comment]
My bad. You are right @Zales0123. I had changed routes paths but left ACL regexs unchanged. Now everything is working as it should.

Issue can be closed.
