### ISSUE TITLE
Cannot use dropdown in admin area (tested for categories)

### ISSUE THREAD

**Issue by fdyckhoff** [Sylius/Sylius#11384]
**Sylius version affected**: 1.7.2

- PHP version: 7.3
- Yarn version: 1.19.2
- Node version: 12.13.1

**Description**  
When clicking on the dropdown next to a category, the dropdown only opens for a split second and will be closed before you can click any link. (Route /admin/taxons/new)

**Steps to reproduce**  

- Install Sylius v1.7.0 as described in the docs: https://docs.sylius.com/en/latest/getting-started-with-sylius/installation.html (using PHP 7.3)
- After the installation the dropdown works fine
- Then upgrade to v1.7.2 via `composer update` and build assets again via `yarn build`
- After the upgrade the dropdown does not work anymore
- When you downgrade back to v1.7.1, the dropdown works again

**Comment by aztecnologic** [comment]
I'm having the same issue after upgrade to 1.7.4

**Comment by lchrusciel** [comment]
Can you explain better and perhaps reproduce it on our demo: https://demo.sylius.com/admin/taxons/new or master demo: https://master.demo.sylius.com/admin/taxons/new?
