### ISSUE TITLE
Can't set custom priority value for promotions

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#11429]
**Sylius version affected**: any

**Description**  
Can't control the order of promotions programmatically. I manage promotions with custom fixtures executed during deploy time. The order is fixed though – each promotion gets its own priority number, yet when persisted the priority is totally different.

What's controlling promotion priority? I can't set custom value because Sylius is forcing me to use its own. Very frustrating.

**Comment by mikemix** [comment]
Is it possible to drop the gedmo sortable for this entity?

**Comment by lchrusciel** [comment]
If you provide a backward-compatible, maintained implementation(preferably not in Sylius core) that is for sure an option. 

I can imagine, that Sylius is not working as you would wish, but we sometimes have to do go for compromise or balance needs with potential improvements. I bet, you will be able to dynamically remove gedmo extension for this entity from your code. Feel free to publish a blog post or some tutorial once you do it, so others can benefit from it.

**Comment by vvasiloi** [comment]
Here's an example of how it works, in case anyone needs it: https://github.com/Sylius/Sylius/issues/11326

**Comment by mikemix** [comment]
I found that sortable behavior really annoying, so I disabled it completely.
