### ISSUE TITLE
1.7.3 fails to install with composer (payum token_storage issue)

### ISSUE THREAD

**Issue by mjhca** [Sylius/Sylius#11438]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Sylius version   | 1.7.3

Following the [install instructions ](https://docs.sylius.com/en/latest/book/installation/installation.html).  Environment is Ubuntu 20.04, composer 1.10.1, php 7.4

Run:

`composer create-project sylius/sylius`

... usual "Configuring" options appear, and then the error:

> Executing script cache:clear [KO]
>  [KO]
> Script cache:clear returned with error code 1
> !!  
> !!  In BaseNode.php line 441:
> !!                                                                                 
> !!    Invalid configuration for path "**payum.security.token_storage**": Only one tok  
> !!    en storage could be configured.                                              
> !!                                                                                 
> !!  
> !!  In MainConfiguration.php line 154:
> !!                                                 
> !!    Only one token storage could be configured.  
> !!                                                 
> !!  
> !!  
> Script @auto-scripts was called via post-update-cmd

Is this a bug?  Seems unusual to run into this with just the basic create-project step.

**Comment by lchrusciel** [comment]
Hey!

Thanks for asking your question. I hope someone will be able to help you with it. However, please consider that our official support channels are: 
 * [Slack](sylius.com/slack)
 * [StackOverflow](https://stackoverflow.com/search?tab=newest&q=sylius)
 * [Forum](https://forum.sylius.com/)

You can read more about them here: https://docs.sylius.com/en/latest/support/index.html

**Comment by Prometee** [comment]
@mjhca this is not a Sylius bug, this is happening because you try to install `sylius/sylius` and not `sylius/sylius-standard` like the doc explains it : https://docs.sylius.com/en/latest/book/installation/installation.html

Anyway, to those who wants to know why this error is happening : it's because the file `symfony.lock` is not aware of the installation of `payum/payum-bundle` so when the recipes are checked then the payum recipe is run, causing the bug described.

@lchrusciel some other packages are missing in `symfony.lock` maybe it needs to be updated or deleted and ignored ?

**Comment by Catalin-Ionut** [comment]
This is still hapening, i want to install the developer edition and i get this error aswell `Invalid configuration for path "payum.security.token_storage": Only one token storage could be configured.`

**Comment by Prometee** [comment]
@Catalin-Ionut same answer https://github.com/Sylius/Sylius/issues/11438#issuecomment-628072507, read the documentation carefully it's `sylius/sylius-standard` not `sylius/sylius`.

**Comment by Catalin-Ionut** [comment]
@Prometee based on the docs [here](https://docs.sylius.com/en/latest/book/contributing/code/patches.html) if i want to contribute i need to fork the developer edition which is `sylius/sylius` . After cloning and after `composer install` at the clear cache step the said error occures.

**Comment by Prometee** [comment]
@Catalin-Ionut ah ok, so this is not related to the installation of Sylius. As I comment before the `symfony.lock` file has to be updated.

**Comment by foxou33** [comment]
Like @Catalin-Ionut said, following instructions here: https://docs.sylius.com/en/latest/book/contributing/code/patches.html leads you to clone Sylius/Sylius. In order to make changes and test them, we need to install and ultimately run into this error.

**Comment by Zales0123** [comment]
I believe it can be closed 🖖

**Comment by webprobox** [comment]
Can someone please explain how this issue was fixed?
