### ISSUE TITLE
Taxons stopped working after upgrading to 1.7

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#11440]
**Sylius version affected**: 1.7.3

**Description**  
Not sure what's wrong, I cannot open the product admin list (because of the taxon tree) and the taxon admin list as well.

This is happening, because inside the `ResourceController` in this step:

```
->setData([
    'configuration' => $configuration,
    'metadata' => $this->metadata,
    'resources' => $resources,
    $this->metadata->getPluralName() => $resources,
])
```

The `getPluralName()` method returns word `taxa` instead of `taxons` for the resource name `taxon`. This is where it happens (Doctrine's inflector class):

![obraz](https://user-images.githubusercontent.com/2399452/81498659-7c9c0100-92c6-11ea-9cbe-87807c4c1518.png)

Why's this happening? I've just upgraded from 1.6 to 1.7 using the [upgrade notes](https://github.com/Sylius/Sylius/blob/master/UPGRADE-1.7.md). However I didn't just update `sylius/sylius`, but I also ran: `composer update`

**Comment by mikemix** [comment]
It looks like an issue with the `doctrine/inflector` dependency. Versions 1-1.3 produced plural name `taxons`, but in 1.4 they refactored the class to use "rulesets" and so now it's `taxa` not `taxons`.

Anyway, the word `taxa` is a valid plural form of the word `taxon` so it's entirely wrong on your part I guess lol.

**Comment by mikemix** [comment]
Maybe it would be better to decorate the inflector? One day Doctrine will require version 2 and this will happen again.

**Comment by Zales0123** [comment]
The conversation has already been started on the [doctrine/inflector](https://github.com/doctrine/inflector/issues/147) repository. #11441 is definitely a hot-fix just to make Sylius working again. We will iterate over this change to resolve it properly
