### ISSUE TITLE
Shop product list sorting and pagination is broken

### ISSUE THREAD

**Issue by jbator** [Sylius/Sylius#11477]
**Sylius version affected**: 1.6.* and 1.7.*

**Description**  
Product pagination on the shop taxon page is generating wierd results. When sorted or max per page parameter changed, number of results displayed is messed up.
This issue is visble also on Demo page.

**Steps to reproduce**  
On the demo page just change sorting by price. number of displayed results will change on the first page. 

Also changing max per page param does not work well - on the T-Shirt category default number of items is 6 (max per page is set to 9) but when I change this to max = 18 then I got 7 results on the first page. Something is wrong.

https://demo.sylius.com/en_US/taxons/category/jeans
https://demo.sylius.com/en_US/taxons/category/jeans?limit=27&sorting%5Bname%5D=asc

**Comment by vvasiloi** [comment]
It's a long-time issue.
https://github.com/Sylius/Sylius/issues/10343

**Comment by lchrusciel** [comment]
Thanks a lot for the reporting! I will close this issue to trace all changes to this bug at #10343
