### ISSUE TITLE
Hardcoded `new-api` route in Swagger Documentation normalizers

### ISSUE THREAD

**Issue by esserj** [Sylius/Sylius#11483]
**Sylius version affected**: 1.8-dev

**Description**  
in 1.8 the api route can be configured, but the swagger documentation normalizers
`\Sylius\Bundle\ApiBundle\Swagger\ShopAuthenticationTokenDocumentationNormalizer` and `\Sylius\Bundle\ApiBundle\Swagger\AdminAuthenticationTokenDocumentationNormalizer` hardcode `/new-api` as path, resulting in swagger sending requests to an invalid path when you change the api route in your own configuration

**Steps to reproduce**  
update `security.yaml` paramter `sylius.security.new_api_route` to `/some-api`
navigate to `/some-api/docs` and you will see the token routes still displayed as `/new-api` so swagger will call those resulting in a 404

**Possible Solution**  
Inject the parameter as argument into the services (but maybe better to have a bundle config that then defines the parameter for you that is then used)

**Comment by lchrusciel** [comment]
Hello Jan!

Thanks for reporting. It should be fixed, of course. Could you open a PR with either of the solutions?

**Comment by esserj** [comment]
Sure, I'll put in on my TODO, expect a PR somewhere the coming week
