### ISSUE TITLE
Unknown "locale_name" filter Twig syntax error

### ISSUE THREAD

**Issue by mattsches** [Sylius/Sylius#11498]
**Sylius version affected**: 1.7.4

**Description**  
I'm getting a `Unknown "locale_name" filter. Did you mean "sylius_locale_name"?` `Twig\Error\SyntaxError` on the Checkout Complete page (`sylius_shop_checkout_complete`) after upgrading from 1.6 to 1.7.4. 

**Steps to reproduce**  
Step through the checkout steps until you reach the checkout overview page.

**Possible Solution**  
The name of the Twig filter was changed in https://github.com/Sylius/Sylius/commit/59eee7b6eaf4721c57820682d8183dc4aa15e2ed but this did not make it in the 1.7.4 release?!

Did I miss anything during the upgrade process? Should it fall back to `locale_name`?

**Comment by pamil** [comment]
Please make sure that you've followed the upgrade instructions (https://github.com/Sylius/Sylius/blob/master/UPGRADE-1.7.md), especially point no. 5.

**Comment by mattsches** [comment]
Thank you, that was exactly the problem. I had somehow missed this step, sorry!
