### ISSUE TITLE
Promotion data collector

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#11495]
I would add to this debug panel for cart the promotions that were evaluated for eligibility and why they were rejected or not. 

With the current implementation of promotions, it takes a lot of concentration to understand why a promotion was applied to cart or why it didn't.

and if you have a couple of hundred of them... things can get really really messy.

_Originally posted by @gabiudrescu in https://github.com/Sylius/Sylius/pull/10688#issuecomment-571964193_

**Comment by gabiudrescu** [comment]
:disappointed:

**Comment by GSadee** [comment]
Hi @gabiudrescu!

As nothing has happened with this issue for 3 years, and we have no plans to add to it in the near future, I'm closing this issue. Of course, if you find it relevant, feel free to reopen it or open a new one 🖖🏻
