### ISSUE TITLE
Add description to the UI what the Inventory Tracked flag is about

### ISSUE THREAD

**Issue by alexander-schranz** [Sylius/Sylius#11518]
**Describe the proposed solution**

For better UX for the user there should be a description what the `Tracked` flag in the Product Variant Inventory is for and what effect it has. Me personally it always confuse it if it need to be activated or disabled for which case 🙈 .

**Comment by mamazu** [comment]
Would you suggest an explanatory text underneath it or just a popup on hover?

**Comment by alexander-schranz** [comment]
A [help text](https://symfony.com/blog/new-in-symfony-4-1-form-field-help) under the field would be great.

**Comment by mamazu** [comment]
That sounds like a great idea. It's the first time I see this feature.

**Comment by mamazu** [comment]
Hm, I have just checked out this feature and this would require to change the build in checkbox type to support the help feature. I don't think that this is a good idea.
On the other hand it might also make sense to move the inventory form templates into one location (currently both product and product variant have different templates for rendering the inventory status)

**Comment by vvasiloi** [comment]
> this would require to change the build in checkbox type

I don't think that's necessary.
It requires to add `form_help(form)` to [@SyliusUi/Form/theme.html.twig](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig#L22-L30) and the `help` option to [Sylius\Bundle\CoreBundle\Form\Extension\ProductVariantTypeExtension](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Form/Extension/ProductVariantTypeExtension.php#L41)

**Comment by mamazu** [comment]
Ah okay. I will look into that this evening.

**Comment by mamazu** [comment]
The implementation is working. The question now is how should it look. I am not aware of any other descriptive text in Sylius (which should probably changed in the future) so I'd propose two possible solutions:

## Version :one: : A simple message panel
![version1](https://user-images.githubusercontent.com/14860264/84689297-13508300-af41-11ea-85b5-aa5e89021f47.png)


## Version :two: : Text inside a small tag.
![version2](https://user-images.githubusercontent.com/14860264/84689341-206d7200-af41-11ea-9ffb-494a21c170d6.png)

## Version :three: : Normal sized text with 60% opacity.
![version3](https://user-images.githubusercontent.com/14860264/84690176-59f2ad00-af42-11ea-82f4-6a053aece1ec.png)

**Comment by alexander-schranz** [comment]
I personally would go with :three: or a combination between :two: and :three:.

**Comment by mamazu** [comment]
The thing is that setting the current stock doesn't make any sense if this switch is off. So I am also thinking about reordering those.
