### ISSUE TITLE
Products are not displayed when I change the locale

### ISSUE THREAD

**Issue by dimacros** [Sylius/Sylius#11521]
**Sylius version affected**: 1.x.y

**Description**  

I just installed sylius, I'm not sure if this is the default behavior, but when changing the locale parameter located in `services/config`, they stopped loading products.

**Steps to reproduce**  

![image](https://user-images.githubusercontent.com/31266588/83072300-1fc57800-a034-11ea-9421-7def2965662f.png)

Expected

![image](https://user-images.githubusercontent.com/31266588/83072497-7c289780-a034-11ea-92d4-2fd2469f5ae4.png)

**Comment by dimacros** [comment]
Well, I discovered that when listing products, it is filtered by "locale". However in "manage taxons". It displays a list that it shouldn't.

**Comment by jubaron** [comment]
I have similar issue but with the frontOffice. When I choose the french language, products are not displays. There is no product bar and no items. Maybe it's link ?
