### ISSUE TITLE
With a 100% promotion on shipping/products, the checkout process is failing with a constraint error

### ISSUE THREAD

**Issue by deStrO** [Sylius/Sylius#11530]
**Sylius version affected**: 1.7.4 / 1.7.3

**Description**  

When a promotion is applied who set the price to 0, there are an error in the checkout process when validating the address :

This collection should contain exactly 1 element and it seems related to the order.payments that's empty because no payment is required.

![image](https://user-images.githubusercontent.com/519112/83188940-bb3c1300-a130-11ea-9f99-3e9110f2ebe2.png)

I searched everywhere where that Count constraints is set, but I don't find it.

**Steps to reproduce**  

I simply created a promotion that give 100% promotion on the product and on the shipping and just put in the cart and process the checkout.

Another user on slack reported me that he got the exact same issue.

**Comment by lchrusciel** [comment]
Hello Julien,

can you write a failing behat scenario for your case and open a PR with it? It will make it easier to solve your problem

**Comment by deStrO** [comment]
Hello,

Never writed that kind of scenario, but I'll try ! :)

**Comment by deStrO** [comment]
@lchrusciel done tested and it's failling
I tried to change the scenario and set the promotion to 50% and the order total to $30.00 and in that case it works.

**Comment by lchrusciel** [comment]
that's great that it worked out. With the failing scenario, it is much easier to pick up work and it will protect us in the future from the regression

**Comment by deStrO** [comment]
Okay, after investigation, I found that the issue is coming from the admin-order-creation-plugin, and it's added constraints on the payments field.

`<?xml version="1.0" encoding="UTF-8"?>

<constraint-mapping xmlns="http://symfony.com/schema/dic/constraint-mapping"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://symfony.com/schema/dic/constraint-mapping
                    http://symfony.com/schema/dic/services/constraint-mapping-1.0.xsd">
    <class name="Sylius\Component\Core\Model\Order">
        <property name="payments">
            <constraint name="Count">
                <option name="min">1</option>
                <option name="max">1</option>
                <option name="groups">sylius</option>
            </constraint>
        </property>
    </class>
</constraint-mapping>
`

When I remove that part, it's going further :)

**Comment by Prometee** [comment]
@deStrO Thanks a lot, I was stucked on this error while testing a free order !
