### ISSUE TITLE
Cart is clear when we log in with an account created after an order

### ISSUE THREAD

**Issue by bGaetan** [Sylius/Sylius#11557]
**Sylius version affected**: 1.7.x / latest

**Description**  
When I log in with an account created after an order, my cart is empty

**Steps to reproduce**  
- As an anonymous user, I had at least one product in my cart
- I Go to the checkout, choose an address, a shipment method, a payment method
- In the last step, I click to "place order"
- On the "Thank you" page, I click "Create an account"
- I complete the fields, create an account and validate my email address

Now, I'm not logged.
- As an anonymous guy, I had at least one product in my cart
- I click on the login link and I log me in
- I'm now logged but my cart is empty

**Comment by keeper7** [comment]
This is a correct behaviour.
When you "Place order" then you finish it from point of customer. 
On the Thank you page you see that you place your order.
After you create account you can find order in your account Order history.

**Comment by lchrusciel** [comment]
Hello Gaetan, as @keeper7 explained, this is expected behavior. Do you have any issues with it?

**Comment by bGaetan** [comment]
I think I have poorly explain the problem. Imagine, you go on the shop, you place an order and create your account.

You comme back one week later and you want to place a new order. You are not logged, you add a product and now, you decide to log in to your account. At this time, your new cart is clear. So my product should be in my cart anymore.

I really think it'a a bug

**Comment by lchrusciel** [comment]
I think it is just a side effect of this feature: https://github.com/Sylius/Sylius/blob/master/features/cart/shopping_cart/maintaining_previous_cart_after_authorization.feature

**Comment by bGaetan** [comment]
Okay, thank s! So, for you, it's a normal behavior ?

**Comment by lchrusciel** [comment]
It is a little bit controversial but expected. Cart merging is something that is probably often customized at end application, but I don't remember if we have documentation for that

**Comment by bGaetan** [comment]
At a business side, it's a real problem. A customer who add products in his cart and lost all his cart when he log in can quit the website and go buy on a rival website.

We will investigate by our own side but I think @CoderMaggie can be concern by this behavior choice. I stay available on slack if you want to discuss more about that :)

**Comment by rakkot-vm** [comment]
How I can set a new value for the cart's context priority?

**Comment by vvasiloi** [comment]
@rakkot-vm just redefine the service and set a different priority.
```
services:
    sylius.context.cart.session_and_channel_based:
        class: Sylius\Bundle\CoreBundle\Context\SessionAndChannelBasedCartContext
        arguments:
            - "@sylius.storage.cart_session"
            - "@sylius.context.channel"
        tags:
            - { name: sylius.context.cart, priority: -333 }
