### ISSUE TITLE
Username not being assigned for existing customer

### ISSUE THREAD

**Issue by prengerjarno** [Sylius/Sylius#11556]
**Sylius version affected**: 1.6.8

**Description**  
When managing customers in the admin interface, the shop user does not get a username when it is being enabled for an existing customer which in itself is not being updated. This is caused by the DefaultUsernameORMListener which assigns the username when a customer is updated. If the customer is not updated, the username is not applied.

**Steps to reproduce**  
1. Make customer in admin interface
2. Enable login for the shop user and save without editing customer details

**Possible Solution**  
Also listen on Shop User insertion

**Comment by hatem20** [comment]
I think this PR https://github.com/Sylius/Sylius/pull/11048 should fix it @prengerjarno
