### ISSUE TITLE
Taxon variable missing

### ISSUE THREAD

**Issue by gabzsmallz** [Sylius/Sylius#11569]
**Sylius version affected**: 1.6.5

**Description**  

Taxon variable not been passed to the view
Resourcecontroller 
**Steps to reproduce**  

Open products index
Open shop
**Possible Solution**

**Comment by mamazu** [comment]
Can confirm that. I have encountered this problems in the plugins that fail their pipeline. The hot-fix solution is to override the template and remove the taxon or default it with the `resource` variable.

**Comment by gabzsmallz** [comment]
> 
> 
> Can confirm that. I have encountered this problems in the plugins that fail their pipeline. The hot-fix solution is to override the template and remove the taxon or default it with the `resource` variable.

Ah awesome been trying to figure out how to do it kindly guide on adding to the resource variable

**Comment by lchrusciel** [comment]
May be related to #11441

**Comment by stefandoorn** [comment]
If related to #11441, then I can confirm it also happens on Sylius v1.5.

**Comment by mamazu** [comment]
Well this has been fix right?

**Comment by Zales0123** [comment]
I think so 🖖 :)
