### ISSUE TITLE
Product index not showing, Option index not showing

### ISSUE THREAD

**Issue by gabzsmallz** [Sylius/Sylius#11568]
**Sylius version affected**: 1.7.5

**Description**  

Product index is not listing even through there are product entries on the database
Options index is not listing even with options entries in the database
**Steps to reproduce**  

Save some attributes of a product head to shop click Attributes
Save a product and go to Product 
Save a option and go to Option
**Possible Solution**  

Query maybe

**Comment by lchrusciel** [comment]
Hello @gabzsmallz,

have you asked about your issue on our slack channel? Someone there may help you with your issue, as there is our official support channel. If you think, that there is a bug, we need more precise steps to reproduce it I suppose.

**Comment by gabzsmallz** [comment]
> 
> 
> Hello @gabzsmallz,
> 
> have you asked about your issue on our slack channel? Someone there may help you with your issue, as there is our official support channel. If you think, that there is a bug, we need more precise steps to reproduce it I suppose.

Hello @lchrusciel no will do. I have seen the issue in all new instances i create with composer create-project sylius/sylius-standard

**Comment by gabzsmallz** [comment]
Just figured it out my locale during installation was set to en_KE and on config/services.yaml locale was set to en_US after changing that all products appear
