### ISSUE TITLE
[Doc] How to deploy Sylius Plus to Platform.sh ?

### ISSUE THREAD

**Issue by oallain** [Sylius/Sylius#11574]
**Sylius version affected**: Sylius Plus

**Description**  
For the installation of wkhtmltopdf we have in the documentation:

```
dependencies:
    ...
    ruby:
        "wkhtmltopdf-binary": "> 0.12.5.1" # adding wkhtmltopdf as a one of dependencies
``` 
But wkhtmltopdf did an new release on June 10 and created version 1.12.6.
When deploying to Platform.sh we now have the error:

        W: /app/.global/gems/wkhtmltopdf-binary-0.12.6/bin/wkhtmltopdf:28:in `<top (required)>': undefined method `match?' for /deepin/:Regexp (NoMethodError)
        W: Did you mean?  match
        W: 	from /app/.global/bin/wkhtmltopdf:22:in `load'
        W: 	from /app/.global/bin/wkhtmltopdf:22:in `<main>'

**Steps to reproduce**  
Deploy Sylius Plus to Platform.sh
Error occurred when execute
```
hooks:
    build: |
        ...
        wkhtmltopdf -V
```

**Possible Solution**  
Maybe we should fix the version of wkhtmltopdf?

**Comment by oallain** [comment]
I fix it on my projet by using :

```diff
dependencies:
    nodejs:
        yarn: "*"
        gulp-cli: "*"
    ruby:
-        "wkhtmltopdf-binary": "> 0.12.5.1" # adding wkhtmltopdf as a one of dependencies
+        "wkhtmltopdf-binary": "0.12.5.1" # adding wkhtmltopdf as a one of dependencies
```

But I don't know if it's the best way to do it.

**Comment by AdamKasp** [comment]
Hello @oallain, your solution looks fine, but we should also consider how to handle a new version of `wkhtmltopdf` in future
