### ISSUE TITLE
javascript file is working time to time

### ISSUE THREAD

**Issue by kaushi5054** [Sylius/Sylius#11579]
Hi guys, I need a small help, this is not a bug, few days back I started Sylius and when I trying to add new JS file, at first sign it works fine, after that even I do the changers it didn't works . I started clearing the cash also. but it woks in time to time.

Can you please guide me?

Thank you

**Comment by mamazu** [comment]
Did you check the docs for best practices for including javascript? 
https://docs.sylius.com/en/1.4/cookbook/frontend/admin-js-and-css.html

**Comment by kaushi5054** [comment]
hi, thanks, I corrected the title . Sorry

yes I did refer it , thing is im trying to add js file in **templates/bundles/SyliusAdminBundle/AdminUser/_form.html.twig** and once I config the  service.yml,

 **_I'm getting error like bellow_**
`An exception has been thrown during the rendering of a template ("There are no registered paths for namespace "App".").`

**_This is how my services.yaml_** 
`app.block_event_listener.admin.layout.javascripts:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@App/templates/bundles/SyliusAdminBundle/AdminUser/_form.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.admin.layout.javascripts, method: onBlockEvent }`

Thank you!!
