### ISSUE TITLE
 Invalid configuration for path "payum.security.token_storage": Only one token storage could be configured.

### ISSUE THREAD

**Issue by akrick** [Sylius/Sylius#11583]
Invalid configuration for path "payum.security.token_storage": Only one token storage could be configured.

**Comment by lchrusciel** [comment]
Hey!

Thanks for rising your issue, you haven't described what happened or how to reproduce your bug. I hope someone will be able to help you with it. However, please consider that our official support channels are: 
 * [Slack](sylius.com/slack)
 * [StackOverflow](https://stackoverflow.com/search?tab=newest&q=sylius)
 * [Forum](https://forum.sylius.com/)

You can read more about them here: https://docs.sylius.com/en/latest/support/index.html
