### ISSUE TITLE
How to order  Admin select options alphabetically?

### ISSUE THREAD

**Issue by jmarcone** [Sylius/Sylius#11596]
I'm using Sylius 1.5 and I need to to order the Admin's product filter's options alphabetically.

This particular filter it's an EntityFilter, but I also need to order other fields.

What's the best way of doing this? Should I create custom a filter type for this? or implement an event listener?

**Comment by lchrusciel** [comment]
Hey!

Thanks for asking your question. I hope someone will be able to help you with it. However, please consider that our official support channels are: 
 * [Slack](sylius.com/slack)
 * [StackOverflow](https://stackoverflow.com/search?tab=newest&q=sylius)
 * [Forum](https://forum.sylius.com/)

You can read more about them here: https://docs.sylius.com/en/latest/support/index.html
