### ISSUE TITLE
[Admin] How to edit the indexAction grid query 

### ISSUE THREAD

**Issue by kaushi5054** [Sylius/Sylius#11598]
Hi ,

I'm just trying to edit the **indexAction** in product controller doing some data filtering. what I did was I added new column as **channel_code** in product table and the user table , when each user login to the system they show the product list according to the  their **channel_code**.

I'm just trying to change query in **resources** (Please refer the attachment). and I count catch it,

Can you please guide me solve this issue 

<img width="1415" alt="Screen Shot 2020-06-23 at 8 52 50 PM" src="https://user-images.githubusercontent.com/20614311/85424143-2d1f4500-b595-11ea-87c3-9d650089300f.png">

**Comment by vvasiloi** [comment]
The products are already filtered by channel.
What you need to do it add a new channel context that will return the channel of a logged in user.
https://docs.sylius.com/en/latest/bdd/how-to-add-new-context.html

**Comment by kaushi5054** [comment]
Hi,

thanks @vvasiloi  vvasiloi, By the way if we want to add more fields and with the user role they should be filler by each way. for that do we have to export the ProductRepository?

**Comment by lchrusciel** [comment]
Hey!

Thanks for asking your question. I hope someone will be able to help you with it. However, please consider that our official support channels are: 
 * [Slack](sylius.com/slack)
 * [StackOverflow](https://stackoverflow.com/search?tab=newest&q=sylius)
 * [Forum](https://forum.sylius.com/)

You can read more about them here: https://docs.sylius.com/en/latest/support/index.html

**Comment by kaushi5054** [comment]
Hi,

Thanks and [here](https://stackoverflow.com/questions/62553146/sylius-admin-how-to-edit-the-indexaction-grid-query) is the question please help me to resolve this
