### ISSUE TITLE
Extending form with EntityType field leads to internal server error

### ISSUE THREAD

**Issue by samchery** [Sylius/Sylius#11595]
**Sylius version affected**: 1.7.5
PHP : 7.3.3
Symfony : 4.4.10

**Description**  
Trying to extend my Product form in SyliusAdminShop with an EntityType field. 
The purpose of this development is to bind a custom Entity (Brand) to my product. 
The process always leads to an internal error, no detail on my dev.log, neither on my PHP server...

**Steps to reproduce**  
- create a Brand Entity in my themes.
```
...
    /** @ORM\Column(type="string", nullable=false) */
    private $name;

    /** 
     * @ORM\OneToMany(targetEntity="App\Entity\Product\Product", mappedBy="brand") 
     */
    private $products;
public function __construct() {
        $this->products = new ArrayCollection();
    }

... + getter and setter
```

- extend product Entity in src : 
```
...
 /** @ORM\Column(type="integer", name="brand_id", nullable=true) */
    private $brandId;

    /** 
     * @ORM\ManyToOne(targetEntity="Admin\Entity\Brand", inversedBy="products") 
     */
    private $brand;
... + getter and setter
```

Trying to extend Product form by adding in my theme Form > ProductTypeExtension : 
```
<?php

declare(strict_types=1);

namespace Admin\Form;

use Sylius\Bundle\ProductBundle\Form\Type\ProductType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

use Admin\Entity\Brand;

final class ProductTypeExtension extends AbstractTypeExtension
{

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('brand', EntityType::class, [
                'required' => true,
                'label' => 'Marque du produit',
                'class' => Brand::class,
                'choice_label' => function ($brand) {
                    return $brand->getName();
                }
            ])
        ;
    }

    public static function getExtendedTypes(): iterable
    {
        return [EntityType::class, ProductType::class];
    }
}
```

**Possible Solution**  
I have no idea of what i m doing wrong...

thanks for any help !

**Comment by vvasiloi** [comment]
Your mapping doesn't look right, you have both `$brand` and `$brandId` properties mapped.
Check the [Doctrine docs](https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/association-mapping.html#one-to-many-bidirectional) for details.
In addition to that, your form type extension should not extend `EntityType`.
Also, check if you have the following ini settings properly configured, assuming it's a development environment:
```
display_errors = On
error_reporting = E_ALL
```
Then test again and share the error message.

**Comment by samchery** [comment]
Hi, thanks for the reply ! 
My bad for the mapping, i fixed it, remove EntityType from : `public static function getExtendedTypes()` and it work ! 
Thanks a lot again !! 
We (I ?) can close this issue ! :)

**Comment by lchrusciel** [comment]
Hello Samantha, I'm glad that you've resolved your issue :) However, please consider that our official support channels are: 
 * [Slack](sylius.com/slack)
 * [StackOverflow](https://stackoverflow.com/search?tab=newest&q=sylius)
 * [Forum](https://forum.sylius.com/)

You can read more about them here: https://docs.sylius.com/en/latest/support/index.html

Also, Victor, thanks for your support 🎉
