### ISSUE TITLE
An existing migration is blocking future migrations

### ISSUE THREAD

**Issue by jacquesbh** [Sylius/Sylius#11592]
**Sylius version affected**: **since 1.1.0**

**Description**  
If you add a field using annotations to the ProductAttribute entity then you end up with an error during migrations.
Here I've added a `filterable` field and I get this:

![image](https://user-images.githubusercontent.com/858611/84944105-94487f80-b0e5-11ea-8214-889a5cd56ccd.png)

This is caused because we ask doctrine to load the attributes during a migration:
https://github.com/Sylius/Sylius/blob/f08c3bf8f70e8f13da1ca3efa8440846297f0c76/app/migrations/Version20171003103916.php

**Steps to reproduce**  

Add a field to your entity, generate the migration and migrate the database from the beginning.

**Possible Solution**  

Using a specific method of the Repository, limiting the fields to select.

```php
    public function findByTypeForMigration(string $type)
    {
        return $this
            ->createQueryBuilder('o')
            ->select([
                'o.id',
                'o.code',
                'o.type',
                'o.storageType',
                'o.configuration',
                'o.createdAt',
                'o.updatedAt',
                'o.position'
            ])
            ->where('o.type = :type')
            ->setParameter('type', $type)
            ->getQuery()
            ->getResult()
        ;
    }
```

**Comment by lchrusciel** [comment]
Hey Jacques,

indeed this migration is written poorly and it should be fixed. Are you willing to open a PR with your proposed solution?

**Comment by jacquesbh** [comment]
@lchrusciel Ok, I'll do that :).

**Comment by lchrusciel** [comment]
Thank you!
