### ISSUE TITLE
Show available variants in grid if such exists

### ISSUE THREAD

**Issue by dbalabka** [Sylius/Sylius#11605]
Currently, the grid contains any variants sorted by position. IMO customer is interested to see available variants if such exists. To make it possible, available variants sorted by position should show first otherwise not available variant should be shown.

**Additional context**
It is important if you would like to customize the grid and add product availability information based on variant information. If a variant that has position "0" is not available, such product will be marked as not available.

**Alternative solution**
Summary of variants `on hand` and `on hold` information should be stored on product level as well.

**Comment by TheMilek** [comment]
Hi @dbalabka!
I'm closing this issue in ref to https://github.com/Sylius/Sylius/pull/11606#issuecomment-1420848222
