### ISSUE TITLE
Documentation using removed function TaxonInterface::getProducts().

### ISSUE THREAD

**Issue by mdevlamynck** [Sylius/Sylius#11603]
**Sylius docs version**: 1.7 / latest

**Description**
In the [3rd code snippet of this section of the documentation](https://docs.sylius.com/en/1.7/book/products/product_associations.html?highlight=getProducts#how-to-add-a-new-association-to-a-product), the code snippet is using the `getProducts()` function that does not exist anymore :
```php
/** @var TaxonInterface $taxon */
$taxon = $this->container->get('sylius.repository.taxon')->findOneBy(['code' => 'sd-cards']);

$associatedProducts = $taxon->getProducts();
```

**Question**
Is there another way to get the products associated to a given taxon? Maybe there exist a repository method? Or do I need to write a query myself?

**Comment by lchrusciel** [comment]
Hey Matthias,

the method you mentioned does not exist anymore, that's true. Would you like to open a PR to our documentation? 

If you need to fetch products by taxon, you should use `\Sylius\Bundle\CoreBundle\Doctrine\ORM\ProductRepository` (so `sylius.product.repository` as a service) and then you have two query builders, that may help you with your problem.

**Comment by mdevlamynck** [comment]
I've been able to implement the fetch of products by taxon in the `ProductRepository` with a custom query.

I'd be glad to provide a PR, how do you think I should replace the code example that was using the removed function? Implement the repository query and use it in two code blocks?
