### ISSUE TITLE
Admin notifications disabled but still having JS requests with each request

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#11604]
**Sylius version affected**: 1.7

**Description**  
I have disabled the notifications:

```
sylius_admin:
    notifications:
        enabled: false
```

but still I get two unnecessary JS calls with each admin page visit. Why's that happening?

Two XHR calls with each request:

![obraz](https://user-images.githubusercontent.com/2399452/85859014-d8f6a980-b7bc-11ea-8a30-901c8c718cf4.png)

The call stack of each:

![obraz](https://user-images.githubusercontent.com/2399452/85859072-f166c400-b7bc-11ea-89fe-392bda7449d3.png)

How to get rid of that? My guess is this is a bug.

**Comment by mikemix** [comment]
Well this happens because you never show the notification bar, while the scripts expects some data from it lol:

```
	jquery.fn.extend({
	  notification: function notification() {
	    var notificationMenu = jquery('#sylius-version-notification'); <-------------- HERE
	    var askFrequency = notificationMenu.attr('data-frequency') * MILISECONDS_MULTIPLIER;
```

As a temporary fix I had to put this code inside the footer:

```
    <script>localStorage.setItem('hub_request_time', '9999999999999')</script>
    <div style="display: none" id="sylius-version-notification" data-frequency="0" data-url="#" data-current-version="0"></div>
```

**Comment by lchrusciel** [comment]
Hey Mike,

Thanks for reporting. Could you propose some fix for this issue? Preferably with PR :)

**Comment by mikemix** [comment]
Against which branch?

**Comment by lchrusciel** [comment]
As this is a bugfix, let's open it to 1.7

**Comment by mikemix** [comment]
Funny nobody did notice this.
