### ISSUE TITLE
Database field too small for OAuth access token when using Keycloak as identity provider

### ISSUE THREAD

**Issue by der-peer** [Sylius/Sylius#11608]
**Sylius version affected**: 1.7.6

**Description**  
Trying to add users via OAuth (using hwi/HWIOAuthBundle) fails:
`SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'access_token' at row 1 at /var/www/sylius/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:129, PDOException(code: 22001): SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'access_token' at row 1 at /var/www/sylius/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:127)`
Affected identity provider: Keycloak

**Steps to reproduce**  
- install Sylius following the cookbook
- `composer require hwi/HWIOAuthBundle`
- setup identity provider following the documentation

**Possible Solution**  
Access tokens can be of very different sizes, depending on contained data.
Suggestion: 
`ALTER TABLE sylius_user_oauth MODIFY access_token VARCHAR(8192);`  
`ALTER TABLE sylius_user_oauth MODIFY refresh_token VARCHAR(8192);`

**Comment by lchrusciel** [comment]
Hello @der-peer,

thanks for rising and issue. However, have you checked our official support channels? 
 * [Slack](sylius.com/slack)
 * [StackOverflow](https://stackoverflow.com/search?tab=newest&q=sylius)
 * [Forum](https://forum.sylius.com/)

Perhaps, someone there will be able to help you with your issue

**Comment by der-peer** [comment]
Hello @lchrusciel,

yes, I did a research on the issue, at least in the Github issue list there was no reference to that. But it's no problem. As you can see, I already included a solution that works - maybe something for the impatient ones. I'd suggest to put it into schema for one of the following releases.

It might be worth a short discussion on how useful it is to restrict field size to 255, as it is originally. My suggestion of 8192 might not be sufficient either. Because, when using OAuth2 (Keycloak/openid-connect in my case), sizes my vary depending on strength and type of encryption - though I'd consider using an 8kB token a bad idea.

**Comment by lchrusciel** [comment]
That makes absolute sense. Therefore it is good to have it here, maybe someone will solve their problem based on this issue.

I'm wondering if it is something we should change with migration or rather create a cookbook for that in the documentation.

**Comment by der-peer** [comment]
In my opinion this would be good to be changed with migration. I can't imagine any case where removing/raising the limit would break functionality for anyone. So why keeping that obstacle?
