### ISSUE TITLE
Invalid taxon data

### ISSUE THREAD

**Issue by nenadalm** [Sylius/Sylius#11602]
**Sylius version affected**: 1.6.8

**Description**  
Table `sylius_taxon` sometimes contains invalid values. When this issue was last noticed, there were 2 rows with same `tree_root`, `tree_left`, `tree_right` values.

**Steps to reproduce**  
Most likely updating taxons in parallel.

**Possible Solution**  
Since tree extension is used to manage these values: https://github.com/Sylius/Sylius/blob/c4cd1efb0b5dc9216214e8ba69a4539f0555e524/src/Sylius/Bundle/TaxonomyBundle/Resources/config/doctrine/model/Taxon.orm.xml#L58 and documentation mentions using locks to prevent these kinds of issues (I didn't notice any in Sylius code): https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/transaction-safety.md#making-safe-transactions-in-concurrent-environment I think adding the `LockMode::PESSIMISTIC_WRITE` lock on `Taxon` entity for given root should prevent this problem.

**Comment by lchrusciel** [comment]
Hey Miloslav,

thanks for reporting the issue. Can you be more precise about reproduction steps?

**Comment by nenadalm** [comment]
The issue can happen if the code updating `sylius_taxon` table is running multiple times at the same time (there is more requests trying to do that). I think it's best described in the official documentation of the tree extension: https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/transaction-safety.md#making-safe-transactions-in-concurrent-environment used to update mentioned columns?
