### ISSUE TITLE
ApiPlatform GET taxons collection endpoint as anonymous

### ISSUE THREAD

**Issue by TheGrimmChester** [Sylius/Sylius#11614]
**Sylius version affected**: 1.8-dev-master

**Description**  
When **authenticated**: api calls $taxonRepository->findAll() method to retrieve the taxons so we have everything. => **OK**

When **anonymous**: api calls $taxonRepository->findChildrenByChannelMenuTaxon($channelMenuTaxon) where $channelMenuTaxon is the root taxon we selected in the edit channel page.
**Result:** We only receive the first children of our selected root. I think we should receive the root taxon + every children and children of children...

**Steps to reproduce**  
1. Create 3 levels of taxons
2. Set the top parent taxon as menu taxon for a channel
3. Call the api GET /new-api/taxons as anonymous

**Comment by nithiz** [comment]
+1, i have the same issue. Out of the box in 1.8 there is no way to get the full taxon tree.

**Comment by nithiz** [comment]
I have tried overriding the Taxon configuration but i can't seem to find a way to do this. I have tried the following `resources:
    App\Entity\Taxonomy\Taxon:
        shortName: 'Taxon'
        itemOperations:
            shop_get:
                method: 'GET'
                path: '/shop/taxons/{id}'
                openapi_context:
                    summary: 'Use $slug to retrieve a taxon resource.'
                requirements:
                    id: '.+'
` in `config/api_platform/resources.yaml`.

I also set the packages/api_platform.yaml to `api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/config/api_platform'
` but without any luck.. 

I have searched the API Platform docs and issues on this topic but couldn't find anything related to overriding bundle configurations for API Platform resources.

Any ideas?

**Comment by dembandiaye** [comment]
I am having the same issue, any solutions?

**Comment by lchrusciel** [comment]
There is a possibility, that for now, you have to duplicate the whole config file for AP to work. So my advice would be to duplicate Taxon.xml and try to customize it there.

**Comment by NoResponseMate** [comment]
There have been a lot of changes to the API, and as such, this issue is no longer valid.
From what I tested, right now it works the same way whether you are logged in or not.
For the time being, receiving only the immediate children is the expected behavior, since getting the whole subtree could get really messy.

Cheers :beers:
