### ISSUE TITLE
A lot of cache file generated

### ISSUE THREAD

**Issue by Nek-** [Sylius/Sylius#11634]
**Sylius version affected**: 1.7.x

**Description**  
I figure out that sylius generate on each call a lot of files in the cache. They almost all refer to OrderItem and have same content. I have no idea where it comes from. I'm not sure it's really an issue _(except id like to have an idempotent cache, which is something else... I take any advice here or slack if you have some)_

Here are some examples of files:

```php
<?php //%255BSylius%255CComponent%255CCore%255CModel%255COrderItem%2523equals%255D%255B1%255D

return [PHP_INT_MAX, []];
```
```php
<?php //%255BSylius%255CComponent%255CCore%255CModel%255COrderItem%255D%255B1%255D

return [PHP_INT_MAX, []];
```
```php
<?php //isWritable.a%253A3%253A%257Bi%253A0%253Bs%253A26%253A%2522App%255CEntity%255COrder%255COrderItem%2522%253Bi%253A1%253Bs%253A9%253A%2522unitPrice%2522%253Bi%253A2%253Ba%253A0%253A%257B%257D%257D

return [PHP_INT_MAX, true];
```
**Steps to reproduce**  
Navigate the website

**Possible Solution**  
I have no idea, sorry.

**Comment by vvasiloi** [comment]
These files are generated by Symfony to cache annotations.
The cache is generated for OrderItem and other entities because these have annotations, like:
```
// App\Entity\Order\OrderItem
/**
 * @ORM\Entity()
 * @ORM\Table(name="sylius_order_item")
 */
class OrderItem extends BaseOrderItem
```
It's nothing to be concerned about.

**Comment by Nek-** [comment]
On each request it generates hundreads of files containing same contents. Are you saying this is an issue of DoctrineBundle?

**Comment by vvasiloi** [comment]
I'm saying it's not an issue. If you don't want cache, you can disable it, but the application might get be considerably slower.
Or you can use a different cache storage, like Redis or Memcached, instead of files: https://symfony.com/doc/current/cache.html#configuring-cache-with-frameworkbundle
