### ISSUE TITLE
Removing SymfonyInsight from the checks

### ISSUE THREAD

**Issue by jacquesbh** [Sylius/Sylius#11635]
Hi!

SymfonyInsight is almost blocking all the PRs. I mean… not blocking but keeping them running.

Is that possible to disable it? Or if you want to run it on master only?

It's kind of annoying :p 

Thank you.

**Comment by lchrusciel** [comment]
Thanks for your opinion. SymfonyInsight could be a valuable addition to our CI pipeline, but sometimes it is not working perfectly. As we are still experimenting with it, I'm ok with yellow builds, as Travis is the main source of truth. Therefore, don't worry, SymfonyInsight is not blocking PRs, however, I can see your point.

**Comment by jacquesbh** [comment]
I know it's not blocking. It's just Yellow all the time :).

Having insight on the master branch only could be a solution, don't you think?

**Comment by vvasiloi** [comment]
Probably unrelated, but it's still [configured with PHP 7.2](https://github.com/Sylius/Sylius/blob/master/.symfony.insight.yaml#L1) , while the [composer.json has 7.3 or higher](https://github.com/Sylius/Sylius/blob/master/composer.json#L22).

**Comment by lchrusciel** [comment]
That probably is not helping us ;)

**Comment by vvasiloi** [comment]
What's the reason Symfony Insight builds are pending for so long?

**Comment by jacquesbh** [comment]
It's stuck somewhere in the multiverse.

**Comment by vvasiloi** [comment]
I asked about it in Symfony's Slack workspace and the product manager at Symfony Insight suggested that it might be a problem at their end and to contact https://symfony.com/support.
Perhaps @pamil should do that.

**Comment by jacquesbh** [comment]
![image](https://user-images.githubusercontent.com/858611/87445695-a4765080-c5f8-11ea-8188-4a506c26c602.png)

```
[err] Cloning into '.'...
[err] warning: Could not find remote branch refs/pull/11378/head to clone.
fatal: Remote branch refs/pull/11378/head not found in upstream origin
```

Apparently there is a small issue during the clone.

**Comment by vvasiloi** [comment]
How did you find that?

**Comment by jacquesbh** [comment]
Link above the images ;)

**Comment by vvasiloi** [comment]
Yeah, I mean the link...

**Comment by jacquesbh** [comment]
<img src="https://octodex.github.com/images/nyantocat.gif" width="120"/>
<details><summary>If I tell you I'll have to kill you…</summary>

![insight](https://user-images.githubusercontent.com/858611/87478543-3c406280-c62a-11ea-80d8-d6f91b8f3d10.gif)
</comment>

**Comment by jacquesbh** [comment]
Symfony Team just fixed the issue we had.

![image](https://user-images.githubusercontent.com/858611/87564212-6e9c9f00-c6c0-11ea-8cb2-28f1e42310d2.png)

Have a good day!
