### ISSUE TITLE
Same HTML id attribute in Admin view

### ISSUE THREAD

**Issue by Hraph** [Sylius/Sylius#11649]
The id "shipping-state" is set 2 times in the document (in div and h3 tag)

https://github.com/Sylius/Sylius/blob/6ec16374070e8f142947d713a34fbc52db45a155/src/Sylius/Bundle/AdminBundle/Resources/views/Order/Show/_shipments.html.twig#L4

**Comment by lchrusciel** [comment]
Hey Raphael, thanks for raising an issue. Are you willing to fix it on our repo?
