### ISSUE TITLE
Wrong tax calculation

### ISSUE THREAD

**Issue by rakkot-vm** [Sylius/Sylius#11652]
Have a problem with tax:
- add product with price 100 to cart
- product has tax rate 10%
- /+ shipping 10
- Order total is 110 

and taxes is 9.09  instead of 11

"sylius/sylius": "~1.4.1",

**Comment by lchrusciel** [comment]
Hey!

What you have described seems like the difference between tax included and excluded in the price. You may want to read through these files, to get how does it work: https://github.com/Sylius/Sylius/tree/master/features/taxation/applying_taxes

Some additional resources may be found here: https://docs.sylius.com/en/latest/search.html?q=tax&check_keywords=yes&area=default

Nonetheless, thanks for asking your question. However, please consider that our official support channels are: 
 * [Slack](sylius.com/slack)
 * [StackOverflow](https://stackoverflow.com/search?tab=newest&q=sylius)
 * [Forum](https://forum.sylius.com/)

Closing for now, as it is not a repository issue.
