### ISSUE TITLE
Sylius-standart demo issue

### ISSUE THREAD

**Issue by Paintras** [Sylius/Sylius#11667]
Good day,
I followed guide of installing demo page of Sylius when it finished there was things missing out of it. Like product navbar, carousel of products etc. For example I can access administration, create product, but cannot access its details. What could have gone wrong? There was no modification on my part.
Thank you kindly

**Comment by Paintras** [comment]
Well I figured out this issues is only when localization changes. The one that I was working on (Czech) was missing product navbar when I tried Polish for example, navbar was there. Is this localization issues or am I missing something here?)

**Comment by lchrusciel** [comment]
Hey @Paintras,

the reason for this may be related to the fact, that our fixtures do not include Czech translation. Products and navbar will appear if you will add Czech translations to your products and taxons.
