### ISSUE TITLE
500 error if tried to change PM for already placed order to the disabled/not available PM

### ISSUE THREAD

**Issue by Jara-script** [Sylius/Sylius#11679]
**Sylius version affected**: 1.7.0

**Description**  
500 error if tried to change PM for already placed order to the disabled/not available PM

**Steps to reproduce**  

**Preconditions**:
- Created at least one regular PM 

**TC**:
1. Add something to the cart
2. Go through the all checkout and place the order
3. As admin disable selected PM
4. Click on the “Change payment method” (e.g. from confirmation email)
5. As an user click on the Pay button in Change payment method window

**Actual results**:

Displayed white page with 500 error

**Comment by AdamKasp** [comment]
Hey @Jara-script 
I was able to reproduce this bug also on the master, and it's true, we will get 500 error if admin will disable all payment methods, probably in this case we should disable pay button,
fell free to contribute with this or your solution, and thanks for pointing it. :)

**Comment by Rafikooo** [comment]
We want to let you know that we finally put this problem on the board, it should be fixed in the near future 🚀
