### ISSUE TITLE
[HELP][Admin] How extend the roles

### ISSUE THREAD

**Issue by kaushi5054** [Sylius/Sylius#11685]
Hi, 

We are trying to add new two roles to the admin section and , We need to hide some side menu times by user role, Is there any way to extend the role (using **Sylius** **1.7**)

Thank you..

**Comment by vvasiloi** [comment]
https://github.com/odiseoteam/RbacPlugin
https://sylius.com/plugin/access-control-layer-plugin/

**Comment by kaushi5054** [comment]
Thank you @vvasiloi
