### ISSUE TITLE
how to user jquery as global

### ISSUE THREAD

**Issue by inggil2407** [Sylius/Sylius#11684]
We use GitHub issues only to discuss about Sylius bugs, new features and documentation. 
For this kind of questions about Sylius usage, please use
any of the support alternatives described here: https://docs.sylius.com/en/latest/book/support/

Thank you!

**Comment by Zales0123** [comment]
Hello Inggil 🖖 Indeed, such a question is good to be posted on Slack :) Hope you'll find the help there 🎉
