### ISSUE TITLE
select-payment too many redirects

### ISSUE THREAD

**Issue by maikelreyes** [Sylius/Sylius#11692]
hi there, 

I'm using Sylius 1.7.6, with php 7.3.10.
In the checkout step, at the select-payment uri, te browser is giving the error:

The page isn’t redirecting properly

Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

    This problem can sometimes be caused by disabling or refusing to accept cookies.

Can bring some support about it?

**Comment by Zales0123** [comment]
Hello Maikel! 🚀 **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our [Slack](http://sylius.com/slack) (preferred) or [forum](https://forum.sylius.com/) ;) We have a very active, developed community, I'm sure someone will be able to help you with your problem. Good luck :)
