### ISSUE TITLE
[Shop] product preview section image is missing

### ISSUE THREAD

**Issue by kaushi5054** [Sylius/Sylius#11699]
Hi,

Today we did the production and add sample data and  the images and clear the cash, unfortunately product preview section image is missing, image URL is showing as `DOMAIN_NAME/media/cache/resolve/sylius_shop_product_large_thumbnail/f7/90/84cd0618712974b8da37ac0c3468.jpeg`

please refer the attachment 
<img width="890" alt="Screen Shot 2020-07-30 at 6 25 34 PM" src="https://user-images.githubusercontent.com/20614311/88926103-1aceb000-d293-11ea-9b51-4960184c5926.png">

Please help me to resolve it.

Thank you !!

**Comment by Zales0123** [comment]
Hello @kaushi5054! 🚀 **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our [Slack](http://sylius.com/slack) (preferred) or [forum](https://forum.sylius.com/) ;) We have a very active, developed community, I'm sure someone will be able to help you with your problem. Good luck :)

**Comment by chrissnyder2337** [comment]
For anyone else who finds this issue. It may be a nginx configuration issue. See this thread: https://github.com/liip/LiipImagineBundle/issues/784#issuecomment-619786798
