### ISSUE TITLE
Enter press in the Attribute tab delete the first in the list

### ISSUE THREAD

**Issue by zangra-dev** [Sylius/Sylius#11712]
**Sylius version affected**:  1.7.6 on local / 1.7.0 on online demo

**Description**  
When I'm on the Product's edit page, go to the Attributes tab, focus any input field with text/number and press the Enter key => the first attribute of the list is delete. 
Also try to block any keypress with the following code
```
{% block javascripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="text/javascript">
        $('input').on('keypress', (e) => { if (e.keyCode == 13) { return false; }});
    </script>
{% endblock %}
```
The form is not send if the focus is in any field, but the attribute still deleted

Test with Firefox Quantum 68.11.0esr / Brave 1.11.104 / Firefox Browser 78.0.2 / Google Chrome 84.0.4147.105

**Steps to reproduce**  
You can check this is the demo in any product (for example this one : https://demo.sylius.com/admin/products/77048/edit )

**Possible Solution**  
May be it's a form conflict ? The delete button is called instead of the form validation ?

**Comment by lchrusciel** [comment]
Hey @zangra-dev,

thanks for the reporting. Would you like to contribute your proposed fix?

**Comment by zangra-dev** [comment]
Hello,
Back from holidays and investigate the issue and I think it come from this function (called when you click on the Delete Button and press Enter)

```
var modifySelectorOnAttributesListElementDelete = function modifySelectorOnAttributesListElementDelete() {
  jquery(".attribute button")
    .off("click")
    .on("click", function (event) {
     var attributeId = jquery(event.currentTarget)
        .parents(".attribute")
        .attr("data-id");

      jquery("div#attributeChoice > .ui.dropdown.search").dropdown(
        "remove selected",
        attributeId
      );
      modifyAttributesListOnSelectorElementDelete(attributeId);
    });
};
```

I log the event, and in both case I've got the same type : "click"
But, when I go deeper and analyze the originalEvent (both as click too), I have some differences : 

- ClientX/ClientY  PageX/PageY  ScreenX/ScreenY are at 0 for the Enter pressed but with number when Button clicked
- the explicitOriginalTarget.id are differents : sylius_product_attributes_0_value Enter pressed, empty when Button clicked

Still not find the solution, but I'm on it

**Comment by zangra-dev** [comment]
May be I have a solution : add a empty id checker.
If the id is empty, it means the button delete is press so we can delete correctly the line. 
If the id is not empty, it means the user press the Enter button so the form is send

This is the modified function (still in the sylius-product-attributes.js , line 33)
```
const modifySelectorOnAttributesListElementDelete = function modifySelectorOnAttributesListElementDelete() {
  $('.attribute button').off('click').on('click', (event) => {
    if ($(event.originalEvent.explicitOriginalTarget.id).is(':empty')) {
      const attributeId = $(event.currentTarget).parents('.attribute').attr('data-id');

      $('div#attributeChoice > .ui.dropdown.search').dropdown('remove selected', attributeId);
      modifyAttributesListOnSelectorElementDelete(attributeId);
    }
  });
};
```

But I didn't find why the Enter key call the function or the attribute button on click event

**Comment by zangra-dev** [comment]
Hum ... We just saw something very strange

If you are in the product's main edit page, you want to change any fields and validate by pressing Enter ... The attribute still being deleted (even with the correction below)

So it's more deep that I thank and I'm not sure to find where the problem is

**Comment by zangra-dev** [comment]
Nothing more found or any correction about this other than mine ?

We are the only using the attributes and validate the product editing by pressing Enter ?

**Comment by lyk-antrop** [comment]
We run into the same issue on 1.8

**Comment by kbyjoel** [comment]
Hi @zangra-dev, Hi @lchrusciel 

For me, that's not a JS bug. The attribute's delete button simply hasn't the `type="button"` attribute.
Override the @SyliusAdmin/Product/Attribute/attributesCollection.html.twig, add `type="button"` attribute on line 35 and 39, and that's it.

Tell me if I'm missing something. If not, i can propose a PR.

**Comment by zangra-dev** [comment]
Well @kbyjoel ... It's work with the type added to the button

Enter save the product (anywhere on the product edit page), press the button delete the attribute

I never thought that this problem could come from a twig file ^^'

**Comment by kbyjoel** [comment]
The button has the default submit type. So I suppose the button is triggered when the form is submitted by the enter key. 
I still don't understand why, because, as far as I know, it isn't a common behaviour.

Anyway, if you give the button type to the delete button, it's not triggered anymore, and the bug "disappear".
I'm not sure it's a very clean bugfix, because it would be interesting to understand why form submission by enter key triggers the click event, and prevent this.

But, at least, it gives a solution for those who had problems with that bug.
