### ISSUE TITLE
Sylius Error on checkout complete, works on dev env but not on prod

### ISSUE THREAD

**Issue by patrickkenekayoro** [Sylius/Sylius#11724]
**Sylius version affected**: 1.7.6
PHP7.4.8

**Description**  
I have simply created a new project using
composer create-project sylius/sylius-standard MyFirstShop

Starting the server: symfony serve and trying to place an order results in an error.
On checkout/complete URL it says Sylius Encountered an Error.

The check out completes on dev environment

**Comment by vvasiloi** [comment]
And what's the error?

**Comment by patrickkenekayoro** [comment]
I've been unable to find out the error exactly because it works on the dev environment.

On terminal it simply says ERROR| SERVER POST (500) /en_US/checkout/complete host="127.0.0.1:8004" scheme="https"
and Sylius Encountered an Error on the the web page.

Apologies if this is not helpful.

**Comment by vvasiloi** [comment]
What about the logs in `var/log/prod.log`?

**Comment by patrickkenekayoro** [comment]
Thank you. It was my fault.  The error was from SwiftMail, I had configured MAILER_URL incorrectly.
