### ISSUE TITLE
locale problem

### ISSUE THREAD

**Issue by XANIZA** [Sylius/Sylius#11727]
**Sylius version affected**: 1.7.4

**Description**  
I have a problem with the front end. threw me this error and I don't know how to fix it

Parameter "_locale" for route "sylius_shop_homepage" must match "[A-Za-z]{2,4}(?:_(?:[A-Za-z]{4}|[0-9]{3}))?(?:_(?:[A-Za-z]{2}|[0-9]{3}))?" ("en_USD" given) to generate a corresponding URL.

![screencapture-185-28-100-127-shopplus-public-2020-08-11-09_33_37](https://user-images.githubusercontent.com/49248719/89874281-ec6aa200-dbbb-11ea-8dda-8aab5663eca2.png)

**Comment by vvasiloi** [comment]
@XANIZA "en_USD" is not a valid locale.

**Comment by Zales0123** [comment]
Hello Michal!

As far as I see, you specify the wrong locale indeed. The valid value is `en_US` not `en_USD` :)

Btw, **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our [Slack](http://sylius.com/slack) (preferred) or [forum](https://forum.sylius.com/) ;) We have a very active, developed community, that is always eager to help. Good luck :)
