### ISSUE TITLE
Promotions fails to open if used product is deleted AND new created product with same code as was deleted product appears in all places where was used deleted

### ISSUE THREAD

**Issue by Jara-script** [Sylius/Sylius#11764]
**Sylius version affected**: 1.7.6

**Description**  
There can be a situation when there is promotion with rule, which includes resource model in its options (like Contains product, or other rule with Taxon), and the resource is deleted (product is deleted), then admin cannot open promotion edit form, as there are transformation or resource identifier to resource model, and there is no check if resource exist. so you will get the error page.
In other hand, related bug, when product which was used in some places is deleted and after some time is created product with same code as was old. In this situation new created product appears in all places where was used previously deleted. What actually can leads to the mess.

**TC1:**

1. Any product should exist in shop
2. Create new promotion with rule “Contains product“
3. Select product
4. Save promotion
5. Then go to products list and delete product, which is used in promotion rule
6. go back to promotions list
7. try to open saved promotion.

**Actual results:**

- Error page is shown

**Expected results:**

- Edit page should not be broken
- In all other places if user want to delete something what currently is in use is shown additional message. It will be good to have same logic here.

 

Other related issue:

**Preconditions:**

- Product with code X is created
- Created product is used e.g. in promotions or in any other place

**TC2:**

1. Go to the product list
2. Delete the product X
> Product X disappears visually from all places where it was used (e.g. actions → item fixed discount → Product filter)
3. Create new product with same code X

**Actual results:**

- New created product appears in all places where was used previously deleted product with same code. It can lead to the mess, cause user is able to forgot where previously was used old product. Business requirements can be different for the newly created.

**Expected results:**

- New created product is not used instead of previously deleted.

**Comment by AdamKasp** [comment]
Hello @Jara-script,
the first part of your issue is a bug, I have just confirmed it.
I am not sure if the second part is a bug or behavior of Sylius.
thanks for reported it 💯 
if you have a solution for this bug feel free to create PR :)

**Comment by Rafikooo** [comment]
We want to let you know that we finally put this problem on the board, it should be fixed in the near future, thanks for reporting the issue 🚀
