### ISSUE TITLE
sylius:cancel-unpaid-orders halts if exception thrown on single order

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#11768]
**Sylius version affected**: 1.3.x and up

The command `sylius:cancel-unpaid-orders` is being used in our shop regularly (cron scheduled) to cancel old orders. In one of the event listeners to this event, we send the customer an email. All fine, but I just noticed someone entered `gmail..com` in their email address. This results in an exception on the sending of that email, which occurs as soon as the state machine kicks in to cancel the order.

Now one could reason that the email sending logic should handle this (the event listener in this case), which makes full sense. But next to this, any exception that happens inside a single order will make this command stop instantly and not process the other orders. This can keep blocking forever, making the list of unpaid orders big and they never get cancelled. 

From that perspective it might be good to catch exceptions separately and let the cancel updater continue to the next order.

**Comment by lchrusciel** [comment]
Hey Stefan, 

your proposal makes sense. Would you like to open a PR?
