### ISSUE TITLE
404 Error trying sorting categories in admin panel

### ISSUE THREAD

**Issue by jorgeagundez** [Sylius/Sylius#11766]
**Sylius version affected**: 1.6.8
This is a bug report similar to [](https://github.com/Sylius/Sylius/issues/11145)

**Problem:**
Sorting of categories in admin panel is not working properly. When a category has many associated products and an attempt is made to change its position, many queries are executed and after a long wait it causes a 404 error.

**Comment by lchrusciel** [comment]
Hey Jorge,

thanks for your bug report. This is probably still an issue. However, keep in mind that version 1.6 is not maintained anymore.

**Comment by NoResponseMate** [comment]
Seems it has been fixed somewhere along the line since changing taxons' positions works fine even with a lot of products.

Cheers 🍻
