### ISSUE TITLE
Implement product list filter without Elasticsearch

### ISSUE THREAD

**Issue by kolarian** [Sylius/Sylius#11809]
Hi!
I'd like to implement product filter by attributes and options (on product_index page), but I do not want to use elasticsearch for this, because there is no possibility to use it in my case. How can I do this?

**Comment by AdamKasp** [comment]
Hello and welcome to the community! 🚀 
**Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our [Slack](http://sylius.com/slack) (preferred) or [forum](https://forum.sylius.com/) ;) We have a very active, developed community, I'm sure someone will be able to help you with your problem. Good luck :)

**Comment by kolarian** [comment]
> @kolarian did you find a way to implement product filters without Elasticsearch? I have the same issue 👎 Elasticsearch is too heavy for my project!

Unfortunately, I have not found a ready solution. In the end, I had to stay with my own CMS. Because 90% of my clients don't need Elasticsearch.
