### ISSUE TITLE
Form validation on Product review as a guest

### ISSUE THREAD

**Issue by easycom-xmedias** [Sylius/Sylius#11816]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.7.6

Form : 
`Sylius\Bundle\CoreBundle\Form\Type\Product\ProductReviewType`

Description :
On product review form, as a guest, if the rating value is set, the form error about mail is not correctly mapped and the message is not displayed.

Error messages without selected rating
![withoutRating](https://user-images.githubusercontent.com/11668060/92400991-1b2d5700-f12d-11ea-8c13-c7a93622de71.png)

Error messages with selected rating
![withRating](https://user-images.githubusercontent.com/11668060/92401085-40ba6080-f12d-11ea-9934-c53539a13dff.png)

**Comment by AdamKasp** [comment]
Hello, @easycom-xmedias,
Thanks to reported it 🎉 
It's a known error related to Symfony/form
if you want to know more, You can read this issue  Symfony/symfony#38039
and we fixed it in this PR https://github.com/Sylius/Sylius/pull/11798
You can confirm it on our master demo :)
