### ISSUE TITLE
Admin::Dashboard - Variable "statistics" does not exist. - after upgrade to 1.8

### ISSUE THREAD

**Issue by malvor** [Sylius/Sylius#11836]
**Sylius version affected**: 1.8.x-dev

**Description**  
After upgrade from 1.4 to 1.8 i have "Variable "statistics" does not exist." error in admin dashboard (/admin) [in templates/bundles/SyliusAdminBundle/Dashboard/_statistics.html.twig (line 9) ]

**Steps to reproduce**  
Login to admin dashboard.

**Possible Solution**

**Comment by vvasiloi** [comment]
@malvor it was moved to [@SyliusAdmin/Dashboard/Statistics/_template.html.twig](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/Statistics/_template.html.twig)

**Comment by malvor** [comment]
Oh great. Thanks! I didn't spot that change.
