### ISSUE TITLE
[DX] Make promotions easy: adding inheritance & interface removal

### ISSUE THREAD

**Issue by Nek-** [Sylius/Sylius#11849]
I think some things are over-engineered here and lead to pain for the final developer. Since I didn't see any issue related to it I open one so we can at least debate about it.

## Problem

As today if you want to extend the promotion system (with custom action and so on), it's a pain unless you re-write a lot of code (by copy/pasting a lot).

Let me show you how obvious the problem is in 2 steps.

### Promotion subjects interface

https://github.com/Sylius/Sylius/blob/86add520857de74f9ea0bf53408d4e064dd70796/src/Sylius/Component/Core/Promotion/Action/PercentageDiscountPromotionActionCommand.php#L42-L45

Here the execute method receives a `PromotionSubjectInterface`, and you instantly check it's actually an OrderInterface. And that's in fact the case for **every** PromotionActionCommand. It should be typed OrderInterface, or maybe the PromotionSubjectInterface should inherit from OrderInterface.

### PromotionActionCommandInterface is final

This means that if you want to extend the behavior of the PromotionActionCommand, it's required you copy/paste the whole class. This is so absurd that there are protected methods inside this command:

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/Promotion/Action/PercentageDiscountPromotionActionCommand.php#L73-L78

### Bonus

It's, even more, a problem if you consider how easy it is to customize action form type with Symfony Form Extensions!

## Solution

I suggest refactoring a little bit the PromotionActionCommands to make more use of protected methods and remove final clause.

And PromotionSubjectInterface should just be removed since it does not really make sense.

What do you think guys?

**Comment by vvasiloi** [comment]
The promotion component and bundle are decoupled from Sylius, so both can be used independently, therefore the abstraction.
It's over-engineered on purpose, so you can make promotions for things other than order.
Sylius comes with an implementation of it for it's order in the core bundle.

**Comment by Nek-** [comment]
Do you have any example of usage outside of the scope of Sylius? Because as I showed in my previous post, there's no possibility of using this component without the order component, because it does not use the order interface as type hint but directly after the method prototype as assertion. This is to me the exact same thing, except direct type hinting is better.

Please tell me how decoupling things may be an argument here while it's highly coupled (and I do not see any reason to decouple more here, so I will not blame the "lack" of decoupling).

**Comment by vvasiloi** [comment]
@Nek- pay attention to the namespace of the classes where these assertions are made, all should be in Sylius Core Component/Bundle which make the integration between other components, bundles and 3rd party libraries.
Here's the documentation for standalone usage of [Sylius Promotion Component](https://docs.sylius.com/en/latest/components_and_bundles/components/Promotion/index.html) and [Sylius Promotion Bundle](https://docs.sylius.com/en/latest/components_and_bundles/bundles/SyliusPromotionBundle/index.html)

**Comment by Nek-** [comment]
Oh indeed I missed the fact that the Promotion bundle only provides interfaces. Making me think that it may be possible to make something even more global? I mean it's just some patterns with interfaces, maybe something for the general case is possible?

Anyway, that only answers a part of my notices. :)

**Comment by vvasiloi** [comment]
In my opinion these classes should remain final, since each one is very specific, but also contain a fair amount of glue code, which can be reused (DiscountPromotionActionCommand, ProportionalIntegerDistributorInterface, UnitsPromotionAdjustmentsApplicatorInterface). Also, these classes have only one public method, so extending doesn't really do anything, you will implement the public method and will either write completely new code, or copy and modify the original, or call the parent method and add more code on top of it. All these scenarios can and should be done through DI, by replacing the current service, decorating it or adding a new one.

**Comment by Nek-** [comment]
My point is adding protected method to make their behavior extendable. This is useful because those classes does many things. Let me show more precisely inside the code:

```php
    public function execute(PromotionSubjectInterface $subject, array $configuration, PromotionInterface $promotion): bool
    {
        // (let's pretend it's not highly couple to order, channel and product x))
        if (!$subject instanceof OrderInterface) {
            throw new UnexpectedTypeException($subject, OrderInterface::class);
        }

        $channelCode = $subject->getChannel()->getCode();
        if (!isset($configuration[$channelCode]) || !isset($configuration[$channelCode]['percentage'])) {
            return false;
        }

        // Filtering time. Many filter. No extension point.
        $filteredItems = $this->priceRangeFilter->filter(
            $subject->getItems()->toArray(),
            array_merge(['channel' => $subject->getChannel()], $configuration[$channelCode])
        );
        $filteredItems = $this->taxonFilter->filter($filteredItems, $configuration[$channelCode]);
        $filteredItems = $this->productFilter->filter($filteredItems, $configuration[$channelCode]);

        if (empty($filteredItems)) {
            return false;
        }

        // Promotion calculation is the only thing that really should be here
        foreach ($filteredItems as $item) {
            $promotionAmount = (int) round($item->getUnitPrice() * $configuration[$channelCode]['percentage']);
            $this->setUnitsAdjustments($item, $promotionAmount, $promotion);
        }

        return true;
    }

    private function setUnitsAdjustments(
        OrderItemInterface $item,
        int $promotionAmount,
        PromotionInterface $promotion
    ): void {
        foreach ($item->getUnits() as $unit) {
            // Is this just me or is this parent method call but the class should not be extended?!?!?
            $this->addAdjustmentToUnit($unit, $promotionAmount, $promotion);
        }
    }
```

**Comment by vvasiloi** [comment]
> (let's pretend it's not highly couple to order, channel and product x))

No one pretends anything there, it's quite the opposite, this line ensures the coupling, because it's in the core bundle which  role is to couple all the pieces.

I will not individually comment on the rest because it all can be reduced to:
Although this command could benefit from extracting some of it's logic, so it's easier to customize, this is better done through composition and delegation rather than inheritance.

**Comment by Nek-** [comment]
> > (let's pretend it's not highly couple to order, channel and product x))
> 
> No one pretends anything there, it's quite the opposite, this line ensures the coupling, because it's in the core bundle which role is to couple all the pieces.
> 

Yes, but there is **no** implementation of the `PromotionActionCommandInterface` inside the Promotion component. That's why I'm saying that.

> I will not individually comment on the rest because it all can be reduced to:
> Although this command could benefit from extracting some of it's logic, so it's easier to customize, this is better done through composition and delegation rather than inheritance.
> 
> [en.wikipedia.org/wiki/Composition_over_inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance)

So this issue is about doing it.
