### ISSUE TITLE
Lint container gives error after upgrade to 1.8

### ISSUE THREAD

**Issue by loevgaard** [Sylius/Sylius#11840]
**Sylius version affected**: 1.8

**Description**
```
In CheckTypeDeclarationsPass.php line 289:

Invalid definition for service "doctrine.migrations.dependency_factory": argument 2 of "Doctrine\Migrations\DependencyFactory::setDefinition" accepts "callable", "SyliusLabs\DoctrineMigrationsExtraBundle\Factory\ContainerAwareVersionFactory" passed.
```

**Steps to reproduce**  
Run `bin/console lint:container`

**Comment by stloyd** [comment]
This is not Sylius issue, it's either Doctrine migrations and/or Symfony:
https://github.com/symfony/symfony/issues/38056

**Comment by loevgaard** [comment]
I will subscribe to that issue. Thank you @stloyd 👍
