### ISSUE TITLE
Upgrade from 1.7 to 1.8 is not straight forward

### ISSUE THREAD

**Issue by jacquesbh** [Sylius/Sylius#11854]
**Sylius docs version**: 1.8

**Description**

After applying the changes from the UPGRADE-1.8.md I've got this issue:

![image](https://user-images.githubusercontent.com/858611/93397803-9f44b480-f87a-11ea-86a5-2780d7303994.png)

This is related to the JWT Authentication for the New API.

For now I've commented out the bundles and configuration related to the API.

**Comment by AdamKasp** [comment]
Hey Jacques,
yup, it was a missing part of our upgrade file.
but we already fixed it.
for now [Upgrade file](https://github.com/Sylius/Sylius/blob/master/UPGRADE-1.8.md) should by complete.

If you still will have some problem with that feel free to reopen this issue 🚀
