### ISSUE TITLE
Deleted at in customer entity

### ISSUE THREAD

**Issue by ping86** [Sylius/Sylius#11869]
**Describe the proposed solution**
We need know when user is deleted. When user Is deleted, sylius_user record is deleted, but sylius_customer don't have information about this deleteion.

**Describe alternatives you've considered**

Create a field deletedAt in sylius_customer to know when user is deleted.

**Comment by AdamKasp** [comment]
Hello @ping86  🚀
what you write looks like simple customization of the `customer` entity.
Check our [guide](https://docs.sylius.com/en/latest/customization/model.html) about it.
if you will have some problem with it please use our [Slack](http://sylius.com/slack) (preferred) or [forum](https://forum.sylius.com/) ;)

Deletions of the customer is a more complex feature that simply extending a `customer` entity, and we are not planning to add this think to the core.

if you won't discuss it fell free to reopen this issue :)
