### ISSUE TITLE
[Products][Admin] Main taxon dropdown has no taxons to select

### ISSUE THREAD

**Issue by nithiz** [Sylius/Sylius#11870]
**Sylius version affected**: 1.7.7

**Description**  
Hey everyone, it seems that the issue reported in https://github.com/Sylius/Sylius/issues/8068 is back again. I can't select any mainTaxon for a product. The only time a value is present in the dropdown is when it already is the mainTaxon (for example if you run fixtures where mainTaxons are applied).

It also seems that there is no way this could work with the current code. In Tab/_taxonomy.html.twig i see {{ form_row(form.mainTaxon) }} but form.mainTaxon is null when no mainTaxon has been chosen yet..

**Steps to reproduce**  
Just run a clean install, don't run any fixtures and configure a taxon and a product manually in Sylius. You will be able to select a taxon from the checkboxes but you won't be able to select a taxon from the main taxon dropdown because there won't be any options to select from.

**Comment by AdamKasp** [comment]
hey, @nithiz,
I'm not sure if I understand correctly, but on `1.7` when i create new simple product i see:
<img width="806" alt="Screenshot 2020-09-22 at 09 57 01" src="https://user-images.githubusercontent.com/29897151/93856878-fbb03580-fcb9-11ea-8c2d-8e0d002ac24f.png">

on our master same:
<img width="843" alt="Screenshot 2020-09-22 at 09 57 49" src="https://user-images.githubusercontent.com/29897151/93856949-1c788b00-fcba-11ea-81c3-f14f6b0bd05b.png">

are you sure that you have done all steps from the installation guide properly?

**Comment by nithiz** [comment]
Yeah thanks for checking. Something else is wrong, clean install does work.. i'm investigating.

**Comment by nithiz** [comment]
When i do a clean install the ajax request fires to check for taxons. In my local (modified) setup it doesn't fire an ajax request while i haven't changed anything the templates. I made sure i have the latest js build. Weird..

**Comment by nithiz** [comment]
@AdamKasp I found the issue. It's the combination with BitBagCommerce/SyliusMolliePlugin. See this issue: https://github.com/BitBagCommerce/SyliusMolliePlugin/issues/29. I'll try updating to a newer version of the plugin :)
