### ISSUE TITLE
Sylius cache management

### ISSUE THREAD

**Issue by Bakudan** [Sylius/Sylius#1188]
Hi @Sylius community,
I am a beginner with Symfony2 and a few weeks ago I started to use Sylius. I did not realize that Sylius is not stable yet and I fully customized the <code>dev</code> version instead of starting a new project. Now, I think that I can't put it in <code>prod</code> because of cache management :
- Images do not always load but sometimes : <pre>Resource interpreted as Image but transferred with MIME type text/html</pre>
- Same for CSS and JS : <pre>net::ERR_CONNECTION_RESET</pre>

And I can't clear the cache with <code>php app/console cache:clear -e prod</code> :

<pre>Clearing the cache for the prod environment with debug true
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 98304 bytes) in C:\wamp\www\sylius\app\cache\pro_\twig\9a\2e\9cb2d88c764cb674efaa179d7259f64ff3b6396785924a758ca5728914b5.php on line 98

PHP Stack trace:
PHP   1. {main}() C:\wamp\www\sylius\app\console:0
PHP   2. Symfony\Component\Console\Application->run() C:\wamp\www\sylius\app\console:28
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() C:\wamp\www\sylius\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:121
PHP   4. Symfony\Component\Console\Application->doRun() C:\wamp\www\sylius\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:96
PHP   5. Symfony\Component\Console\Application->doRunCommand() C:\wamp\www\sylius\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:191
PHP   6. Symfony\Component\Console\Command\Command->run() C:\wamp\www\sylius\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:905
PHP   7. Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() C:\wamp\www\sylius\vendor\symfony\symfony\src\Symfony\Component\Console\Command\Command.php:244
PHP   8. Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() C:\wamp\www\sylius\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand.php:83
PHP   9. Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() C:\wamp\www\sylius\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand.php:120
PHP  10. Symfony\Bundle\TwigBundle\CacheWarmer\TemplateCacheCacheWarmer->warmUp() C:\wamp\www\sylius\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate.php:47
PHP  11. Twig_Environment->loadTemplate() C:\wamp\www\sylius\vendor\symfony\symfony\src\Symfony\Bundle\TwigBundle\CacheWarmer\TemplateCacheCacheWarmer.php:62

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 98304 bytes) in C:\wamp\www\sylius\app\cache\pro_\twig\9a\2e\9cb2d88c764cb674efaa179d7259f64ff3b6396785924a758ca5728914b5.php on line 98

Call Stack:
    0.0005     331032   1. {main}() C:\wamp\www\sylius\app\console:0
    0.0698    3608112   2. Symfony\Component\Console\Application->run() C:\wamp\www\sylius\app\console:28
    0.0764    3860448   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() C:\wamp\www\sylius\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:121
    0.6014   15730344   4. Symfony\Component\Console\Application->doRun() C:\wamp\www\sylius\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:96
    0.6027   15730344   5. Symfony\Component\Console\Application->doRunCommand() C:\wamp\www\sylius\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:191
    0.6034   15755448   6. Symfony\Component\Console\Command\Command->run() C:\wamp\www\sylius\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:905
    0.6037   15755792   7. Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() C:\wamp\www\sylius\vendor\symfony\symfony\src\Symfony\Component\Console\Command\Command.php:244
    0.7519   16165176   8. Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() C:\wamp\www\sylius\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand.php:83
    7.0263   57502064   9. Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() C:\wamp\www\sylius\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand.php:120
   14.6093   95010368  10. Symfony\Bundle\TwigBundle\CacheWarmer\TemplateCacheCacheWarmer->warmUp() C:\wamp\www\sylius\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate.php:47
   21.6284  133900880  11. Twig_Environment->loadTemplate() C:\wamp\www\sylius\vendor\symfony\symfony\src\Symfony\Bundle\TwigBundle\CacheWarmer\TemplateCacheCacheWarmer.php:62</pre>

EDIT : I already cleared the cache manually but it didn't change anything.

Anyone got a solution ?
Thanks in advance ! *And i'm sorry.. I don't mean to pollute the issues section =/*

**Comment by stloyd** [comment]
@pjedrzejewski @aRn0D ping...

**Comment by hantsy** [comment]
Hi, I got the same error when I created the project...

	E:\temp\sylius-standard>php app/console sylius:install
	Installing Sylius...

	Step 1 of 4. Checking system requirements.
	+------------------------------------+------------------------------------+
	| Issue                              | Recommendation                     |
	+------------------------------------+------------------------------------+
	| sylius.settings.short_open_tag     |                                    |
	| sylius.settings.session.auto_start |                                    |
	| sylius.extensions.accelerator      | sylius.extensions.accelerator.help |
	+------------------------------------+------------------------------------+
	Success! Your system can run Sylius properly.

	Step 2 of 4. Setting up the database.
	Creating Sylius database for environment dev.

	Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate
	 130968 bytes) in E:\temp\sylius-standard\vendor\twig\twig\lib\Twig\Parser.php o
	n line 120

**Comment by kayue** [comment]
@hantsy Try to increase the memory for PHP.

Keep in minds that you might have two PHP.ini, one for web server one for command line.

http://stackoverflow.com/questions/3903363/allowed-memory-size-of-268435456-bytes-exhausted

**Comment by hantsy** [comment]
@kayue  Thanks.

I have overcame this barrier, but encountered another problem, I have commented in #2604
