### ISSUE TITLE
Add phone number on channel

### ISSUE THREAD

**Issue by loevgaard** [Sylius/Sylius#11886]
**Describe the proposed solution**
Just as we have a 'Contact email' we should have a 'Contact phone number' on the channel in my opinion. Lots of stores have phone numbers to reach them just as they have emails.

![image](https://user-images.githubusercontent.com/2412177/94540272-8c50bd80-0246-11eb-824c-2a3fc1f30d3b.png)

**Comment by igormukhingmailcom** [comment]
I can provide PR :)

**Comment by NoResponseMate** [comment]
No idea why this issue has been left open for so long, the field in question was added in #11950

Cheers :beers:

**Comment by loevgaard** [comment]
Cool :D
