### ISSUE TITLE
[HELP] ADMIN - How to export a new admin API  for postmen

### ISSUE THREAD

**Issue by kaushi5054** [Sylius/Sylius#11890]
**Sylius version affected**: 1.7.6

Hi All,

I was trying to create a new API endpoint and trying call from the postmen what I did was I export admin bandle a controller and wrote router in`config/routes/sylius_admin_api.yaml `now it's telling **Access Denied.** How can I give the access

**Comment by Ferror** [comment]
hi @kaushi5054 Access Denied seems like the lack of Bearer auth token. Please see the APi Platform docs :) https://api-platform.com/docs/core/jwt/
