### ISSUE TITLE
Changing the number of items in the shopping cart does not work in IE11

### ISSUE THREAD

**Issue by mvriel** [Sylius/Sylius#11892]
**Sylius version affected**: 1.7.6

**Description**  

Changing the number of items in the shopping cart does not work in IE11. The inputs and submit button use the `form` attribute, but this is not supported by IE11. I have verified the issue on demo.sylius.com as well; when you go there using IE11 you are unable to change the amounts of a product in your cart

**Steps to reproduce**  

1. Go to demo.sylius.com using IE11
2. Put a product in your cart
3. Go to the cart summary
4. Change the amount of ordered product
5. Press 'update cart' and observe nothing happens

**Possible Solution**  

Do not use the form attribute with the input fields and submit button but structure the HTML in such a way that the inputs and submit button are within the form element.

**Comment by Ferror** [comment]
Hi @mvriel Thanks for the issue. We do not support IE11.
