### ISSUE TITLE
[ADMIN API] -  always giving 403 (Access Denied)

### ISSUE THREAD

**Issue by kaushi5054** [Sylius/Sylius#11902]
**Sylius version affected**: 1.7.6

Hi All,

I was trying to call admin API through the postmen, and please refer to the below steps that I have followed.

**1. Create client** 
`php bin/console sylius:oauth-server:create-client --grant-type="password" --grant-type="refresh_token" --grant-type="token"`

**2. Generate the token**
<img width="1083" alt="Screen Shot 2020-10-02 at 9 18 53 AM" src="https://user-images.githubusercontent.com/20614311/94886311-63236d80-0490-11eb-8278-eb9c307f29e9.png">

**3. Call order API using refresh token**
<img width="1070" alt="Screen Shot 2020-10-02 at 9 20 06 AM" src="https://user-images.githubusercontent.com/20614311/94886361-8cdc9480-0490-11eb-8d86-f70bb07dc0e0.png">

Now I'm getting 403 `Access Denied`. Please help me to resolve this issue

**_Note:_** 
I'm using my own user with `ROLE_ADMINISTRATION_ACCESS` role access and we check all the steps in this [ticket](https://github.com/Sylius/Sylius-Standard/issues/119) also
once I log in to the application with the same user credentials we can see order details clearly 

Thank you

**Comment by hatem20** [comment]
I think the issue is you are trying to access API with an already created user with `ROLE_ADMINISTRATION_ACCESS` only but to access APIs you have to gain `ROLE_API_ACCESS` and this can be done if you call `oauth/v2/token` with new username and password, it will create new user with both `ROLE_ADMINISTRATION_ACCESS` and `ROLE_API_ACCESS`

**Comment by kaushi5054** [comment]
Hi @hatem20 ,

Thnk you

**Comment by lecajer** [comment]
This solved the issue in my setup. Grant the defaut user `ROLE_API_ACCESS` so we it can call endpoints `/api/v2/admin/*`
```sh
bin/console sylius:user:promote sylius@example.com ROLE_API_ACCESS --user-type=admin
```

**Comment by codercms** [comment]
Hey guys, I faced the same problem, and it took a time to find this issue.
Shouldn't it be documented here https://docs.sylius.com/en/1.13/book/api/authorization.html to prevent users from getting stuck with admin API usage ?

**Comment by jenbhu** [comment]
I faced the same issue recently...
