### ISSUE TITLE
[ADMIN API] while creating new product error "show Call to a member function getConfiguration() on null"

### ISSUE THREAD

**Issue by kaushi5054** [Sylius/Sylius#11910]
**Sylius version affected**: 1.7

Hi all,

I'm trying to call admin product API (create a new product) please refer the following details

```
curl --location --request POST 'http://127.0.0.1:8000/api/v1/products/' \
--header 'Authorization: Bearer MDc5ZTA4OWQ0MmMyMjJiNTRiYjVkYjY1MWU2ZGEyNmExYWYyZDA0ZDZhYWQwMDI1N2QwMGI1MGUwNzkwNTYyMg' \
--header 'Content-Type: application/json' \
--header 'Content-Type: text/plain' \
--data-raw '
        {
            "code": "MUG_TH",
            "mainTaxon": "mugs",
            "productTaxons": "mugs",
            "channels": [
                "US_WEB"
            ],
            "attributes": [
                 {
                     "attribute": "mug_color",
                     "localeCode": "en_US",
                     "value": "yellow"
                 }
             ],
            "options": [
                "mug_type"
            ],
             "associations": {
                 "similar_products": "SMM,BMM"
             },
            "translations": {
                "en_US": {
                    "name": "Theme Mug",
                    "slug": "theme-mug"
                },
                "pl": {
                    "name": "Kubek z motywem",
                    "slug": "kubek-z-motywem"
                }
            },
            "images": [
                {
                    "type": "ford"
                }
            ]
        }
    '
```

I'm using the same sample which includes in the doc and I'm getting 500 error with

`Uncaught PHP Exception Error: "Call to a member function getConfiguration() on null" at /Applications/MAMP/htdocs/my-shop/sylius/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Validator/Constraints/LocalesAwareValidAttributeValueValidator.php line 46 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getConfiguration() on null at /Applications/MAMP/htdocs/my-shop/sylius/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Validator/Constraints/LocalesAwareValidAttributeValueValidator.php:46)"} []
`

please help me to resolve this issue.

Think you

**Comment by Ferror** [comment]
Hi! We are not maintaining Syliu 1.7 anymore, but if it fails in current Sylius version 1.11 do not hesitate to reopen this issue
