### ISSUE TITLE
Gaufrette and GaufretteBundle updates

### ISSUE THREAD

**Issue by Nyholm** [Sylius/Sylius#11913]
I just released Gaufrette 0.10.0. It includes support for AsyncAws and removed some deprecated adapters. I will release GaufretteBundle 0.8.0 within the next few days. It will also just remove some deprecated code. 

I've taken over maintenance of the project. I will fix/review bugs (if you ping me) but I don't plan to continue the work from previous maintainers. Ie, the API will not change. 

Btw, using AsyncAws instead of the official S3 client was one of the things that let me deploy Sylius on AWS Lambda.

**Comment by Ferror** [comment]
Hi @Nyholm we gonna look into it (really XD)

We were waiting for GaufretteBundle 0.8.0 😄
