### ISSUE TITLE
Unsupported shipping method

### ISSUE THREAD

**Issue by loevgaard** [Sylius/Sylius#11921]
**Sylius version affected**: All, I guess, but probably more prevalent with users using the shipping method rules (i.e. >= 1.8)

**Description**  
1. Add some products to the cart
2. Go through checkout and select a shipping method (do not complete order)
3. Open a new tab and add some products that will violate a shipping method rule
4. Complete order in the first tab

Now you have an order that is de facto invalid from the point of the view of the store owner because he/she probably can't ship it.

**Possible Solution**  
I think the best solution would be to create a `OrderIntegrityCheckerInterface` and related tags (just as the order processors) and then a `CompositeOrderIntegrityChecker` that will run before you complete an order. Right now the current `OrderIntegrityChecker` just checks promotions. With this implementation users could have their own rules for a 'valid' order.

Other scenarios could be to check stock count from an external service just before completing an order.

**Comment by MyUtd4Life** [comment]
Hi @loevgaard ,

Please consider https://github.com/Sylius/Sylius/pull/10434#discussion_r497440099 as relevant for this issue.

**Comment by loevgaard** [comment]
Could also be handled with validators as Sylius does it with `\Sylius\Bundle\CoreBundle\Validator\Constraints\OrderShippingMethodEligibilityValidator` for example.

Will close this issue for now.
