### ISSUE TITLE
Cancel unpaid orders command should process next orders upon error

### ISSUE THREAD

**Issue by LucaGallinari** [Sylius/Sylius#11945]
**Describe the proposed solution**
The command "sylius:cancel-unpaid-orders" should be atomic on each order cancellation, so that if an order fails to be canceled, andit throws an error, next orders can still be processed for cancellation. This could be done easily with a try/catch and a writeln to output or a message in the log.

**Comment by loevgaard** [comment]
Would be great with a PR for this. Sounds like an easy fix :)

**Comment by twojtylak** [comment]
A few weeks ago, I made a pr for this issue https://github.com/Sylius/Sylius/pull/11894 @LucaGallinari @loevgaard Is that a solution that you had in mind

**Comment by LucaGallinari** [comment]
@twojtylak Yes, that's exactly what I had in mind. Thanks!

**Comment by loevgaard** [comment]
@twojtylak: I just reviewed your PR :)
