### ISSUE TITLE
Potential broken sf debugger caused by Sylius Channel settings

### ISSUE THREAD

**Issue by kayue** [Sylius/Sylius#11941]
**Sylius version affected**: 1.8

**Description**  
A "Cart" menu/collector is added in Sylius 1.8, but this feature requires Channel to exist in the debugger/profiler's route, otherwise user will get the following error:

> An exception has been thrown during the rendering of a template ("Channel could not be found! Tip: You can use the Web Debug Toolbar to switch between channels in development.").

The error is triggered by `convertAndFormat()`.

https://github.com/Sylius/Sylius/blob/7b9d0989223a75ffda30038c439337b6c84119e9/src/Sylius/Bundle/CoreBundle/Resources/views/Collector/cart.html.twig#L18-L21

I think the Symfony debugger should always work regardless how channel or Sylius is configured. 

Sylius's channel settings is default to match by host name, however in my project I have a "route based" channel settings, and therefore it breaks the debugger bar.

**Steps to reproduce**  
- If the project don't match Channel by hostname then it might run into this problem

**Possible Solution**  
- Do not use any feature that might require Channel context in debugger bar

**Comment by lchrusciel** [comment]
Hey @kayue, do you think you could open a PR with the fix?

**Comment by kayue** [comment]
Cannot reproduce this anymore somehow.
