### ISSUE TITLE
Add field to ShopBillingData

### ISSUE THREAD

**Issue by malvor** [Sylius/Sylius#11942]
Hi,
I'm trying add new field to ShopBillingData - bank_account_number. Create App\Entity\ShopBillingData with field, add new orm config, and Form Extension. But still Channel in Admin has ShopBillingData as Sylius\Component\Core\Model\ShopBillingData. How i can change it? Should i create Channel entity with new relationship?

**Comment by Zales0123** [comment]
Hello Jakub! 🚀 **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our [Slack](http://sylius.com/slack) (preferred) or [forum](https://forum.sylius.com/) ;) We have a very active, developed community, I'm sure someone will be able to help you with your problem. Good luck :)
