### ISSUE TITLE
"Add to cart" via http request

### ISSUE THREAD

**Issue by FlashPanther** [Sylius/Sylius#11969]
It seems to me that this code could be improved.

We are forced to go through "ajax" requests to be able to recover errors when adding an item to the cart.

Can't we add a condition that would check the type of request and redirect users when there is an error?

https://github.com/Sylius/Sylius/blob/80723fbae156c4d3f67e79f37ec74c94cdd44fe4/src/Sylius/Bundle/OrderBundle/Controller/OrderItemController.php#L58-L63

@patrickallaert @fabianSolarz

**Comment by lchrusciel** [comment]
Hey @FlashPanther,

makes sense and also would allow us to reduce the amount of js scenarios. I would add it to the core 👍

**Comment by Ferror** [comment]
it is already done
