### ISSUE TITLE
[Doctrine Migrations] Provide an helper trait to add DoctrineMigration path from plugin

### ISSUE THREAD

**Issue by Jibbarth** [Sylius/Sylius#11960]
By using DoctrineMigration v3, lots of sylius plugin can now add their migrations in `doctrine_migration` config and this avoid users to copy / paste migrations from vendor into their project :+1: 
But, I saw it often misused. When we just prepend doctrine configuration, it put the newly added migration_path in first position. And when we launch the command to generate a migration, doctrine take the first path it get to generate file, so it's often in vendor dir. 

```php
        $container->prependExtensionConfig('doctrine_migrations', [
            'migrations_paths' => [
                'Acme\SyliusAwesomePlugin\Migrations' => __DIR__ . '/../Migrations', // ⬅️ Last extension executed will provide this path by default.
            ],
        ]);
```

I fixed it in CoreBundle and AdminApiBundle in PR #11901 

**Describe the proposed solution**
I think it would be great to provide a Trait that could be used in VendorExtension.php with a `addDoctrineMigrationPaths(array $paths, ContainerBuilder $container)` method in it.  (in the same way Symfony provide a trait for sort tagged service)

Not sure anyway if it should be in CoreBundle or maybe in SyliusLabsDoctrineMigrationExtra. WDYT ?

If you are ok with this feature request, I can provide a pull request :wink: 

**Additional context**

* Problem appear in SyliusRefundPlugin (https://github.com/Sylius/RefundPlugin/pull/205/files#diff-31f138b564b46086525364190dbb09eb88f665b6972ccb611035f936dba5b89b) 
* I heard that problem is also in SyliusPlus.

**Comment by lchrusciel** [comment]
Hey Jibbarth, 

thanks for your proposal and it makes totally sense. I would probably add it to `SyliusLabsDoctrineMigrationExtra`, but we should also adjust the plugin development guide with it. But this part can be on us.

**Comment by lchrusciel** [comment]
I've also confirmed choice with @Zales0123, that `SyliusLabsDoctrineMigrationExtra` would be the best place

**Comment by Jibbarth** [comment]
Resolved by https://github.com/Sylius/Sylius/pull/12060/files#diff-1892e258c11c8a359aa8ac9fea82154f7a37b4b2bd5cb3c77cecef0d0b15dc8f in CoreBundle
