### ISSUE TITLE
[New install] error with symfony/doctrine-bridge

### ISSUE THREAD

**Issue by oallain** [Sylius/Sylius#11979]
**Sylius version affected**: test on 1.7.3 & 1.8.0 & 1.8.3

**Description**  
After installation i got error 

    Cannot find a field on 'App\Entity\Channel\ChannelPricing' that is mapped to column 'channelCode'. Either the field does not exist or an association exists but it has multiple join columns in . (which is being imported from "/Users/xxx/work/xxx/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Resources/config/routing.yml"). Make sure there is a loader supporting the "api_platform" type.

**Steps to reproduce**  
Install Sylius and set a price to a product in BO.

**Possible Solution**  
Just put `"symfony/doctrine-bridge": "4.4.16"` in `conflict` in composer.json

**Comment by Holicz** [comment]
It is not just new install. All existing projects which updates `symfony/doctrine-bridge` to the version `4.4.16` are stuck with this issue.

**Comment by Zales0123** [comment]
Hi Olivier!

We've already conflicted this library on Sylius: https://github.com/Sylius/Sylius/pull/11972
Maybe we should do the same on Sylius-Standard? 🤔

**Comment by afasciaux** [comment]
Same here after fresh install of 1.8

**Comment by oallain** [comment]
Hi @Zales0123 

If we've already fix it on Sylius/Sylius, so IMHO just create en fix tag here solve this issue.
Shouldn't we need to change the composer.json from Sylius/Sylius-Standard, what do you think ?

Regards

**Comment by kconde2** [comment]
I'm getting the same error
![image](https://user-images.githubusercontent.com/43377621/97950465-3c11d180-1d97-11eb-99bb-af78988a5cfd.png)

**Comment by lchrusciel** [comment]
Hey folks, 

it is already fixed in master #11972, we need to tag a new release.
