### ISSUE TITLE
Updating from symfony/doctrine-bridge 4.4.15 to 4.4.16 results in doctrine mapping exception

### ISSUE THREAD

**Issue by tannyl** [Sylius/Sylius#11970]
**Sylius version affected**: 1.8.2 (most likely others as well)

**Description**  
When updating from symfony/doctrine-bridge 4.4.15 to 4.4.16 this breaks Sylius.
When running `bin/console cache:clear` after updating to 4.4.16 this results in the followering error:
```
In MappingException.php line 621:
  Cannot find a field on 'Sylius\Component\Core\Model\ChannelPricing' that is mapped to column 'channelCode'. Either the field does not exi  
  st or an association exists but it has multiple join columns.
```
I suspect that this is due to the changes to symfony/doctrine-bridge/PropertyInfo/DoctrineExtractor.php as seen her: https://github.com/symfony/doctrine-bridge/compare/v4.4.15...v4.4.16

**Steps to reproduce**  
Update symfony/doctrine-bridge from 4.4.15 to 4.4.16 and run `bin/console cache:clear`

**Comment by tannyl** [comment]
To try and temporally fix the problem I added this to our extended `ProductVariant`
```
    /**
     * @ORM\OneToMany(targetEntity="Sylius\Component\Core\Model\ChannelPricingInterface", mappedBy="productVariant", orphanRemoval=true, indexBy="channel_code", cascade={"ALL"})
     *
     * @var Collection
     */
    protected $channelPricings;
```

The `indexBy` is not changed from "**channelCode**" to "**channel_code**", which fixes the above error.

By a new problem arises. The `collection` that is returned does not use the "**channel_code**" as key, as it should.

In 4.4.15 it would return this as expected (without the above change to IndexBy ofcourse:
![image](https://user-images.githubusercontent.com/11209600/97427371-b44e4200-1914-11eb-99ec-cbf96a6f2197.png)

But now in 4.4.16 it ignores the `indexBy` and uses numbers as keys. Which in turn breaks Sylius again, as it never finds any price for any of the variants.
![image](https://user-images.githubusercontent.com/11209600/97427552-042d0900-1915-11eb-9545-fcdd5415eb92.png)

Strangely enough if I use "**id**" in `indexBy` it works as expected, and they entries in the `collection` is using the ids as keys.

So I guess symfony/doctrine-bridge 4.4.16 is broken.

**Comment by lchrusciel** [comment]
The problem still has to be fixed on Symfony/DoctrineBridge

**Comment by lucasballyn** [comment]
Yes, but it is reported, see https://github.com/symfony/symfony/issues/38861
