### ISSUE TITLE
When I create an administrator user 

### ISSUE THREAD

**Issue by maximehuran** [Sylius/Sylius#11975]
**Sylius version affected**: 1.8.2 and probably lower

**Description**  
When I create a new administrator user with an image, but required field not set, I have a TypeError.
If I don't add an image, form validation is correct.

```
Argument 1 passed to Symfony\Component\Security\Csrf\CsrfToken::__construct() must be of the type string, null given, called in /Users/mhuran/Sites/sylius/vendor/symfony/security-csrf/CsrfTokenManager.php on line 80
```

**Steps to reproduce**  
- Create a new administrator
- Add an image
- Keep other required fields empty
- Save

**Comment by Zales0123** [comment]
Thank you for reporting the problem Maxime, indeed there is a bug 👍

**Comment by TheMilek** [comment]
Hi @maximehuran! 🍻 
It seems that it works on Sylius 1.12 version, so I'm closing this issue
Feel free to open another issue if in your opinion the issue still exists 💃🏽
