### ISSUE TITLE
Channel automatically selected

### ISSUE THREAD

**Issue by FlashPanther** [Sylius/Sylius#11990]
**Describe the proposed solution**
When we only have one channel, it's annoying to check "Default" channel for every products, blocks (cms plugin ...).
It could be interessting to automatically select default channel, and maybe hide the selection.

**Comment by AdamKasp** [comment]
for now, if you create a new product, you have by default disabled channel(s) and enable product, after your proposal we should disable product by default so adding a new product will take same work, now administrator must choose if he wants to enable the product in each channel, thanks to this we prevent against accidentally add product.
So IMO your proposed behaviour should be done as customization.
let me know if I'm wrong :)
