### ISSUE TITLE
Programatically add new product attribute

### ISSUE THREAD

**Issue by huberts90** [Sylius/Sylius#11996]
Hi,

where should I put the code to the symfony repository to add product attribute permanently ?(https://docs.sylius.com/en/latest/book/products/attributes.html). This code will update database too ?
Or should I add attribute via database and parallelly programatically ?

**Comment by Zales0123** [comment]
Hello and welcome to the community! 🚀 **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our [Slack](http://sylius.com/slack) (preferred) or [forum](https://forum.sylius.com/) ;) We have a very active, developed community, I'm sure someone will be able to help you.

If you're new to Sylius, follow the [Getting Started with Sylius](https://docs.sylius.com/en/latest/getting-started-with-sylius/) guide. You can be also interested in our [video course](https://sylius.com/online-course/) :) Besides these contents, as mentioned already, Slack is the best place where you can find some help. Good luck! 🖖
