### ISSUE TITLE
[RFC]  Dispatch some events in AddressController

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius#1201]
In https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Controller/Frontend/Account/AddressController.php#L53 and https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Controller/Frontend/Account/AddressController.php#L76 there are no events dispatched.

We have a use case where we have regional prices for products, so we need to recalculate item prices each time shipping address is changed, which is also when shipping address is set.

I am opened for event names suggestions.

**Comment by michalmarcinkowski** [comment]
You can do it on state machine callbacks now.
