### ISSUE TITLE
[RFC] Multiple payment, offline payment, and recording refund

### ISSUE THREAD

**Issue by kayue** [Sylius/Sylius#1202]
#### Background

In our project we want to track refund in Sylius, though Sylius's multiple payment ability. I am planning to treat each refund as a new payment, with state `refunded` and / or negative amount. 

Also since refund could happen in different form, it could be a PayPal refund transaction, or could be a "Gift Card" / "Store Credit", we have to allow admin to create these Payment manually. 

![screen shot 2014-03-14 at 10 11 30 am](https://f.cloud.github.com/assets/193112/2417373/00e38d80-ab1e-11e3-8824-0d6a62edfeed.png)
#### Related Issues

We are willing to contribute, and I think we can close the following issues:
- Multiple payments per order support https://github.com/Sylius/Sylius/issues/834
- Offline payments https://github.com/Sylius/Sylius/issues/485
#### Questions
- Should I treat refund as a new Payment? Or on a separated table?
- Do we create a new payment method for offline payment / refund? Or should we allow `null`?
- Should we allow negative amount in Payment, or just rely on Payment State?

Any feedback are welcome. Thank you for your time.

/cc @umpirsky @pjedrzejewski @makasim

**Comment by michalmarcinkowski** [comment]
Part of this covered in https://github.com/Sylius/Sylius/issues/3710.
