### ISSUE TITLE
Doctrine syntax in one place produces sql incompatible with postgres/standard sql

### ISSUE THREAD

**Issue by tdestro** [Sylius/Sylius#12049]
**Sylius version affected**: 1.8

**Description**  
https://github.com/Sylius/Sylius/blob/4b1ea10f1369cc49daa2ae074a4a3c5ca1dc0cad/src/Sylius/Component/Core/Dashboard/SalesDataProvider.php#L71

This entire switch statement is affected in multiple places.  

Produces SQL code incompatible with postgres and is probably non standard sql. I have been running Sylius on Postgres for almost two years in production. 

You cannot rely on aliases in a having clause as it produces 
<img width="1920" alt="Screen Shot 2020-11-17 at 12 30 20 AM" src="https://user-images.githubusercontent.com/10113013/99350376-2c50bd80-286c-11eb-9968-a2d9bbcf7ba2.png">

See https://www.postgresql.org/message-id/18195.1038530280@sss.pgh.pa.us

The following code executes correctly but is obviously ugly.
```
  $queryBuilder
                    ->addSelect('YEAR(o.checkoutCompletedAt) as year')
                    ->addSelect('MONTH(o.checkoutCompletedAt) as month')
                    ->groupBy('year')
                    ->addGroupBy('month')
                    ->andHaving($queryBuilder->expr()->orX(
                        'YEAR(o.checkoutCompletedAt) = :startYear AND YEAR(o.checkoutCompletedAt) = :endYear AND MONTH(o.checkoutCompletedAt) >= :startMonth AND MONTH(o.checkoutCompletedAt) <= :endMonth',
                        'YEAR(o.checkoutCompletedAt) = :startYear AND YEAR(o.checkoutCompletedAt) != :endYear AND MONTH(o.checkoutCompletedAt) >= :startMonth',
                        'YEAR(o.checkoutCompletedAt) = :endYear AND YEAR(o.checkoutCompletedAt) != :startYear AND MONTH(o.checkoutCompletedAt) <= :endMonth',
                        'YEAR(o.checkoutCompletedAt) > :startYear AND YEAR(o.checkoutCompletedAt) < :endYear'
                    ))

```

**Comment by remoteclient** [comment]
Can you please fix this? The issue also appears in the current version 1.10.
