### ISSUE TITLE
Many bundles have an  implicit (no composer require) dependency on SyluisAdminApiBundle

### ISSUE THREAD

**Issue by esserj** [Sylius/Sylius#12042]
**Sylius version affected**: 1.0 - 1.8

**Description**  
Trying to install some sylius bundles without the SyliusAdminApiBundle leaves us with routes that are used for relations, but don't exist.
Affected bundles and files are:
![image](https://user-images.githubusercontent.com/1032205/99068626-24afc100-25ad-11eb-86fc-164614106d06.png)

**Steps to reproduce**  
install any of these bundles and try serialize (with jms) any of their models

**Possible Solution**  
I think all these relation definitions should exists within the Admin Api bundle alone? like they do for many of the Core bundle models

**Comment by Ferror** [comment]
Good news! We fixed it in 1.10.2 Sylius <3

Related PR: https://github.com/Sylius/SyliusAdminApiBundle/pull/9

**Comment by esserj** [comment]
<3
