### ISSUE TITLE
Can't edit slug during product creation, after uniqConstraintError

### ISSUE THREAD

**Issue by ragdnatak** [Sylius/Sylius#12061]
**Sylius version affected**: 1.8.1

**Description**  
Hello, when you create a product translation with a same slug than another, we have and error because of integrity constraint (here, is ok). But, you can't change slug because field is on **readonly**

**Steps to reproduce**  
1 - create product with EN translation slug named "test"
2 - save
3 - create new product with EN translation slug named "test"
4 - save => ERROR
5 - Impossible to edit the slug
![Trad produit error](https://user-images.githubusercontent.com/74724104/99688487-26cebf80-2a86-11eb-8f91-40641da618b7.png)

**Possible Solution**  
CF PR https://github.com/Sylius/Sylius/pull/12062

**Comment by Ferror** [comment]
Hi @ragdnatak you can toggle the keylock on the right side of the input and then the input will be editable.

<img width="850" alt="Screenshot 2022-05-25 at 12 36 53" src="https://user-images.githubusercontent.com/17534504/170243350-c5070ce3-0a7e-4ca9-89c6-bcafaeca4396.png">

<img width="841" alt="Screenshot 2022-05-25 at 12 37 07" src="https://user-images.githubusercontent.com/17534504/170243400-615ede8b-fa74-4143-8f3f-9328afe19691.png">
