### ISSUE TITLE
Bad translation in flash message after removing the cart 

### ISSUE THREAD

**Issue by moafred** [Sylius/Sylius#12068]
**Sylius version affected**: 1.8.4

**Description**  
The translation in the flash message after removing the cart is not well translated, it use [this translation ](https://github.com/Sylius/SyliusResourceBundle/blob/115b6288ec7a49dbcf77b9ed73f7220327dd2db4/src/Bundle/Resources/translations/flashes.fr.yml#L8).

I understand that the Order is the entity used to manage the Cart, but it's not translated to Cart (in my case in French: "Panier").
What i'm expected will be "the cart has been emptied" (fr: "Le panier a été vidé").

**Steps to reproduce**  
1. Add one item in the cart.

2. Click on "Clear cart" 
![image](https://user-images.githubusercontent.com/1343723/99794101-f8a2bb80-2b29-11eb-99c8-43599aff025e.png)

3. Then it show 
![image](https://user-images.githubusercontent.com/1343723/99793974-c3966900-2b29-11eb-9397-945dd7362866.png)

**Possible Solution**  
Add and use a new translation in https://github.com/Sylius/Sylius/blob/60134b783c51c4b9da0b58c5a54482824a8baf8a/src/Sylius/Bundle/OrderBundle/Resources/translations/flashes.fr.yml#L4-L9

**Comment by Ferror** [comment]
Hi! it seems like translations are already fixed. We are really looking forward to more translation propositions <3
