### ISSUE TITLE
[ADMIN API] customer save API returns " Undefined index: children"

### ISSUE THREAD

**Issue by kaushi5054** [Sylius/Sylius#12063]
**Sylius version affected**: 1.7

Hi All,

I'm using the **Admin AP**I to create a **customer** and it's getting **500** error` Notice: Undefined index: children` as response

This is the curl I'm using

```
curl --location --request POST 'http://127.0.0.1:8000/api/v1/customers/' \
--header 'Authorization: Bearer MDNkMTYxYjM5ZTExMWNiOThhN2FjY2QxZGQ4YWQxMmE0ZjVhYjI1YTI1ZGRmZWRhODE0NmM3' \
--header 'Content-Type: application/json' \
--data-raw '
{
    "firstName": "XXXXXX",
    "lastName": "Diggle",
    "email": "xxxx@gmail.com",
    "gender": "m",
    "user": {
        "plainPassword" : "xxxx"
    }
}
    '
```

Thank you!

**Comment by Ferror** [comment]
Hi @kaushi5054 I tried to reproduce this issue in the latest Sylius but failed. Would you like to test it again against 1.11 version?
