### ISSUE TITLE
package abandoned

### ISSUE THREAD

**Issue by akrick** [Sylius/Sylius#12080]
my php  version is 7.3
`Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.
Package zendframework/zend-hydrator is abandoned, you should avoid using it. Use laminas/laminas-hydrator instead.
Package white-october/pagerfanta-bundle is abandoned, you should avoid using it. Use babdev/pagerfanta-bundle instead.
Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.
Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.
Package fzaninotto/faker is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.`

**Comment by Ferror** [comment]
Hi! These are dependencies we are not using directly, but other bundles/packages do. When updated these should disappear :)
