### ISSUE TITLE
jquery type error : xxx is not a function 

### ISSUE THREAD

**Issue by akrick** [Sylius/Sylius#12094]
when open the homepage , i found such a javascript error:
`jquery.js:4046 jQuery.Deferred exception: jquery(...).sidebar is not a function TypeError: jquery(...).sidebar is not a function
    at HTMLDocument.<anonymous> (http://local.sylius.com/assets/shop/js/app.js:55982:23)
    at mightThrow (http://local.sylius.com/assets/shop/js/app.js:9014:30)
    at process (http://local.sylius.com/assets/shop/js/app.js:9082:13) undefined
jQuery.Deferred.exceptionHook @ jquery.js:4046
process @ jquery.js:3834
setTimeout (async)
(anonymous) @ jquery.js:3868
fire @ jquery.js:3496
fireWith @ jquery.js:3626
fire @ jquery.js:3634
fire @ jquery.js:3496
fireWith @ jquery.js:3626
ready @ jquery.js:4106
completed @ jquery.js:4116
jquery.js:4046 jQuery.Deferred exception: jquery(...).popup is not a function TypeError: jquery(...).popup is not a function
    at HTMLDocument.<anonymous> (http://local.sylius.com/assets/shop/js/app.js:56496:24)
    at mightThrow (http://local.sylius.com/assets/shop/js/app.js:9014:30)
    at process (http://local.sylius.com/assets/shop/js/app.js:9082:13) undefined
jQuery.Deferred.exceptionHook @ jquery.js:4046
process @ jquery.js:3834
setTimeout (async)
(anonymous) @ jquery.js:3868
fire @ jquery.js:3496
fireWith @ jquery.js:3626
fire @ jquery.js:3634
fire @ jquery.js:3496
fireWith @ jquery.js:3626
ready @ jquery.js:4106
completed @ jquery.js:4116
app.js:30 Uncaught TypeError: jquery(...).sidebar is not a function
    at HTMLDocument.<anonymous> (app.js:30)
    at mightThrow (jquery.js:3762)
    at process (jquery.js:3830)
(anonymous) @ app.js:30
mightThrow @ jquery.js:3762
process @ jquery.js:3830
setTimeout (async)
jQuery.readyException @ jquery.js:4054
(anonymous) @ jquery.js:4074
mightThrow @ jquery.js:3762
process @ jquery.js:3830
setTimeout (async)
(anonymous) @ jquery.js:3868
fire @ jquery.js:3496
fireWith @ jquery.js:3626
fire @ jquery.js:3634
fire @ jquery.js:3496
fireWith @ jquery.js:3626
process @ jquery.js:3850
setTimeout (async)
(anonymous) @ jquery.js:3868
fire @ jquery.js:3496
fireWith @ jquery.js:3626
fire @ jquery.js:3634
fire @ jquery.js:3496
fireWith @ jquery.js:3626
ready @ jquery.js:4106
completed @ jquery.js:4116
app.js:30 Uncaught TypeError: jquery(...).popup is not a function
    at HTMLDocument.<anonymous> (app.js:30)
    at mightThrow (jquery.js:3762)
    at process (jquery.js:3830)`

**Comment by diimpp** [comment]
I've got similar `jQuery.Deferred` issue, but strangely only in prod JS build. (Sylius 1.2)
As result semantic-ui checkboxes or tabs weren't press-able without  any explicit errors

Solution for me was to replace `.load` with `.on('load', function()` for sylius-ui `sylius-form-collection.js`, as `load` alias appears to be deprecated https://stackoverflow.com/a/45974735

https://github.com/Sylius/Sylius/blob/af428c41f8b300b2c6618ed61e1b502f46b47126/src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-form-collection.js#L70

**Comment by coldic3** [comment]
Hey @akrick,
I can't reproduce this bug. I guess the issue can be closed. Feel free to reopen it if you still have this issue :woman_dancing:
