### ISSUE TITLE
Master variant price should not show

### ISSUE THREAD

**Issue by PaddyLock** [Sylius/Sylius#121]
Hi, when I have created a product with a master variant I have to give it a price (which could be anything), even if I need to create variants which all have different prices to the master. By creating the variants the master price becomes redundant. However, this price still shows on the frontend homepage view, which in my case it shouldn't. Is this an oversight or a feature?

thanks

**Comment by coudenysj** [comment]
I think this is only partially fixed. There are still prices shown in the overview
<img width="282" alt="sylius_-_modern_ecommerce_for_symfony2" src="https://cloud.githubusercontent.com/assets/96260/11059596/e7ec0b44-879a-11e5-9115-a8d8ff267e27.png">

but on the detail page this price is not available 
<img width="427" alt="sylius_-_modern_ecommerce_for_symfony2" src="https://cloud.githubusercontent.com/assets/96260/11059606/f9af771c-879a-11e5-842f-d8a91030407a.png">
