### ISSUE TITLE
Error when creating simple product

### ISSUE THREAD

**Issue by SylvanoTombo** [Sylius/Sylius#12106]
**Sylius version affected**: 1.7.6

**Description**  
Error when creating simple product

Call to a member function getChannels() on null in HasAllPricesDefinedValidator.

**Comment by Zales0123** [comment]
Hello @SylvanoTombo! Can you share some screenshot or stack trace? On our demo, everything works fine. I also strongly encourage you to upgrade to 1.8 as it's the most recent and the only supported version right now :) 🖖

**Comment by SylvanoTombo** [comment]
Thanks for your response, Here a screenshot..
![Screenshot from 2020-12-02 09-58-32](https://user-images.githubusercontent.com/40351002/100834076-b3b14a00-3484-11eb-88f5-08e119231432.png)

**Comment by SylvanoTombo** [comment]
@Zales0123 , if i dump the form in resource controller, i get the product variant with parent(product), but in validators, the `getProduct` return null

**Comment by SylvanoTombo** [comment]
@Zales0123, in the validators if i do `dd($this->context->getRoot()->getData()->getChannels());` this return the channels
