### ISSUE TITLE
Display the product's code instead of the product's name in the association tab

### ISSUE THREAD

**Issue by zangra-dev** [Sylius/Sylius#12129]
**Sylius version affected**: 1.8

**Description**  
When I try to add a new product association the dropdown list show only the product name.
There is a way to display the product code (or the name + the code it will be good too).
I search a file where there is a potential 'return product->getName()' to change it but I find nothing

**Steps to reproduce**  
Just go to to Product => Edit => Associations and click on the dropdown

Thanks in advance for your help

**Comment by nils-m** [comment]
we copied sylius-product-auto-complete.js with the method productAutoComplete()
were you can make the change `name: item.**name** to name: item.**code**`

` onResponse(response) {
          return {
            success: true,
            results: response._embedded.items.map(item => ({
              name: item.name,
              value: item.code,
            })),
          };
        },`

Along with a custom call:

`import $ from 'jquery';
import './zangra-product-auto-complete';

$(document).ready(() => {

  $('.product-assoc-select.ui.fluid.multiple.search.selection.dropdown').productAutoComplete();

});`

Do the appropriate css class name changes in  _associations.html.twig
