### ISSUE TITLE
[HELP] - Unable to create new shipping methods - Unable to find an endpoint to create a new shipping method. 

### ISSUE THREAD

**Issue by hasithaarimac** [Sylius/Sylius#12134]
[HELP} - Unable to create new shipping methods - Unable to find an endpoint to create a new shipping method. 

Hi all,

In my scenario, I need to create new shipping methods using admin endpoints. But there is no clue mentioned in the documentation. How can I create a new shipping method using admin APIs?

**Comment by Zales0123** [comment]
Hi! As far as I see, such an endpoint is available in both old (`POST /api/v{version}/shipping-categories/`) and new (`POST /new-api/admin/shipping-methods`) API. I hope you'll find it helpful.

Btw, **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our [Slack](http://sylius.com/slack) ;) We have a very active, developed community, I'm sure someone will be able to help you with your problem. Good luck :)
