### ISSUE TITLE
Composer update - PHPCR Bundle needs PHPCR Implementation

### ISSUE THREAD

**Issue by JRomeoSalazar** [Sylius/Sylius#1213]
I have executed a composer update and then it has thrown:

```
- doctrine/phpcr-bundle 1.0.0 requires phpcr/phpcr-implementation 2.1.* -> no matching package found.
```

And then other errors related to this problem.

**Comment by tesfayesolomon33** [comment]
@antonioperic 
I add just this lines

"provide": {
"phpcr/phpcr-implementation": "2.1.0"
},
And It works for me as well 10Q

**Comment by michaelqxd** [comment]
same to me
