### ISSUE TITLE
Frontend assets as NPM packages

### ISSUE THREAD

**Issue by floriangosse** [Sylius/Sylius#12132]
I was setting up a new shop with [Sylius-Standard](https://github.com/Sylius/Sylius-Standard) and stumbled across the problem that I had to install the composer dependencies to be able to build the admin UI (with gulp or webpack). This made the whole build process quite complicated because I had to take care that PHP + composer is available as well in the build context for the frontend resources.

**Describe the proposed solution**
We could provide npm packages for the needed assets. This way we can build the frontend resources independently of PHP and composer which allows us to speed up and simplify build pipelines.

I think it should be relatively easy to setup a pipeline that cares about the release of the PHP package and the NPM packages and maintain the same version number in all packages. This should allow developers to easily upgrade their dependencies for both "environments".

**Comment by jakubtobiasz** [comment]
Hi @floriangosse!
Thanks for your suggestion; we are testing this solution :). I will let you know when we finish.

**Comment by jakubtobiasz** [comment]
After some testing, I can announce we released `sylius-ui/frontend` package 👉🏼 https://www.npmjs.com/package/@sylius-ui/frontend.

We are using it internally for our test applications in our plugins, but it works and will be added to Sylius-Standard and Sylius/Sylius soon. Recommended `package.json`:

```json
{
  "license": "MIT <or whatever you want>",
  "scripts": {
    "build": "encore dev",
    "build:prod": "encore production",
    "postinstall": "semantic-ui-css-patch",
    "lint": "yarn lint:js",
    "watch": "encore dev --watch"
  },
  "devDependencies": {
    "@sylius-ui/frontend": "^1.0"
  }
}
```

I am closing this issue, in case of any problems with this package just open a new one and ping me :).

**Comment by vvasiloi** [comment]
@Ferror can we use this to remove one of the circular dependencies between js and php when building the docker images?

**Comment by Ferror** [comment]
> @Ferror can we use this to remove one of the circular dependencies between js and php when building the docker images?

Yea. As soon as I get my PRs merged and it's ported to Sylius-Standard I will start working on it :)
