### ISSUE TITLE
I want to overrite sylius admin user product list

### ISSUE THREAD

**Issue by zhasan0** [Sylius/Sylius#12131]
I added sylius admin user in channel. Now I need When admin create a channel and access the specific admin user. Then when login this specific admin user then he only see his access channel product. Others channel product he do not get the access to see.

![channel](https://user-images.githubusercontent.com/42202246/101213277-54ca1b80-36a4-11eb-89c9-00ff064e3108.PNG)
![productlist](https://user-images.githubusercontent.com/42202246/101213285-5693df00-36a4-11eb-9544-a51cff0c50ae.PNG)

How can I do this. Anyone help me or give a code example.

**Comment by Zales0123** [comment]
Hello Zahid!

Such functionality is not available in Sylius by default and would require some coding indeed. I would start with the custom repository method for products grid and see how it goes. You can get some inspiration from [this](https://docs.sylius.com/en/latest/customization/grid.html) or [this](https://github.com/Sylius/SyliusGridBundle/blob/master/docs/index.md) documentation. 

Btw, **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our [Slack](http://sylius.com/slack), We have a very active, developed community, I'm sure someone will be able to help you with your problem. Good luck :)
