### ISSUE TITLE
[HELP] - Unable to add new provinces to an existing country - Unable to find an endpoint to do this operation.

### ISSUE THREAD

**Issue by hasithaarimac** [Sylius/Sylius#12135]
HI all,

I need to update an existing country with new provinces using admin APIs. But as per the available ADMIN API document, there is no endpoint available to update the country with new provinces. Can anyone help me with this?

**Comment by Zales0123** [comment]
Hi :) As far as I see there is no endpoint to update country in our legacy Admin API exposed. As we're right now focusing on developing the new Api Platform integration, you would probably need to implement it by yourself. I hope you will manage to do that 🖖 

As mentioned in the other issue, please, use our Slack for such questions. There are plenty of people willing to help others 🚀
