### ISSUE TITLE
Error when using annotation in translation

### ISSUE THREAD

**Issue by SylvanoTombo** [Sylius/Sylius#12141]
**Sylius version affected**: 1.7.6

Custom translation error:` Class "App\Entity\StockHistory\StockHistoryTranslation" sub class of "Sylius\Component\Resource\Model\AbstractTranslation" is not a valid entity or mapped super class.`

When i generate migration diff, it give me the error above.

Here my StockHistoryTranslation:

```
<?php

namespace App\Entity\StockHistory;

use Doctrine\ORM\Mapping as ORM;
use Sylius\Component\Resource\Model\AbstractTranslation;
use Sylius\Component\Resource\Model\ResourceInterface;

class StockHistoryTranslation extends AbstractTranslation implements ResourceInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    protected $id;
    /**
     * @ORM\Column(type="string")
     */
    protected $type;
    /**
     * @return mixed
     */
    public function getType()
    {
        return $this->type;
    }
    /**
     * @param mixed $type
     */
    public function setType($type): void
    {
        $this->type = $type;
    }
    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * @param mixed $id
     */
    public function setId($id): void
    {
        $this->id = $id;
    }
}
```

**Comment by Zales0123** [comment]
Hello @SylvanoTombo. My first shot would be that you need to add the `/** @Entity */` annotation for this class, as AbstractTranslation is not an entity indeed.

Btw, I see you've also asked this question on our Slack - which is great! Please, try to solve such issues on the Slack indeed, as it's the first and default support channel for our community. When you find a bug indeed, then it's a good time to open an issue :) Thanks! 🖖

**Comment by SylvanoTombo** [comment]
@Zales0123, My bad! Thanks
