### ISSUE TITLE
Unwanted payment methods API route

### ISSUE THREAD

**Issue by kayue** [Sylius/Sylius#12181]
**Sylius version affected**: 1.8

**Description**  

All API routes should be prefixed with `/shop` or `/admin`. There is an unwanted API `/new-api/payments/{id}/methods` being generated by API Platform due to definition of subresource. 

https://github.com/Sylius/Sylius/blob/ea5d196c9e949ffc1cfab83c9a55f0278c4450e8/src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/Payment.xml#L73-L75

This could potentially be a security problem.

**Steps to reproduce**  
<img width="696" alt="API_Platform" src="https://user-images.githubusercontent.com/193112/102696788-e7a1b300-426b-11eb-9241-1161b3dc04fd.png">

**Possible Solution**  

I guess you can change the path, but this API do seems redundant. 
I do wonder how can we turn off route generation in Api Platform.

**Comment by antonioperic** [comment]
you can use somethin like this https://locastic.com/blog/switch-off-the-apiplatform-specification-in-sylius/
or you need to turn off apis and reconfigure the one you want to use

**Comment by AdamKasp** [comment]
Hey @kayue
we fixed it in meantime, sorry for the no response from us,  but now I can respond with information that now it works properly :)
