### ISSUE TITLE
Add the ability to delete orders

### ISSUE THREAD

**Issue by DieterHolvoet** [Sylius/Sylius#12200]
**Describe the proposed solution**
I think it would be useful to be able to delete orders through the admin interface. 

**Describe alternatives you've considered**
Cancelling an order is often sufficient, but there are legitimate use cases where you want to completely delete orders, e.g. in the case of test data.

**Additional context**
When suggesting this on Slack, someone said this is not normal ecommerce system behavior, so I did some research:
- On **WooCommerce** you can trash orders and permanently delete them by emptying the trash ([source](https://www.fastcomet.com/tutorials/woocommerce/managing-orders#:~:text=In%20order%20to%20delete%20an,of%20orders%20on%20your%20website.))
- On **Shopify** you can archive or permanently delete orders, the last one only in the following cases ([source](https://help.shopify.com/en/manual/orders/cancel-delete-order)):
    - orders that were paid with a manual payment method
    - orders that started as a draft and were then marked as paid
    - orders that were imported through the Shopify API
    - test orders
- On **Wix** you can archive orders (apart from cancelling them) [[source](https://support.wix.com/en/article/wix-stores-archiving-your-orders)]

**Comment by jakubtobiasz** [comment]
Hello @DieterHolvoet.
We had a discussion on orders deleting here #5052. We don't think it is necessary to include such feature in the core, if you need, you can use `Archivable ` trait to adjust Sylius to your needs, as it is its stronger side 💪🏻.
