### ISSUE TITLE
Broken LiipImagineBundle image filtering

### ISSUE THREAD

**Issue by vytasgavelis** [Sylius/Sylius#12207]
**Sylius version affected**: 1.8.6

**Description**  

With 1.8.6 Sylius allows to use svg images without filtration. The problem is new FilterExtension introduced in https://github.com/Sylius/Sylius/pull/12010 also affects non Sylius environment. And in some cases projects may use classes for their images and put additional image path generation logic in method `__toString()`. In that case any resolution of images using LiipImagineBundle will throw TypeError `substr() expects parameter 1 to be string, object given` here https://github.com/Sylius/Sylius/blob/v1.8.7/src/Sylius/Bundle/CoreBundle/Twig/FilterExtension.php#L48

**Steps to reproduce**  

Pass an object as `$path` parameter in `Sylius\Bundle\CoreBundle\Twig\FilterExtension:filter`

**Possible Solution**  

This could be fixed by adding a `string` parameter type in https://github.com/Sylius/Sylius/blob/v1.8.7/src/Sylius/Bundle/CoreBundle/Twig/FilterExtension.php#L33

**Comment by coldic3** [comment]
Hey @vytasgavelis,
I see FilterExtension itself from LiipImageBundle is deprecated now so I'm closing the issue.
