### ISSUE TITLE
Dashboard Statistics date ranges wrong in Month and Week intervals

### ISSUE THREAD

**Issue by joenilson** [Sylius/Sylius#12217]
**Sylius version affected**: 1.x

**Description**  
In the Admin Dashboard Summary the SalesStatistics Summary don't get the correct intervals for the month and 2Week buttons.

**Steps to reproduce**  
- Login as admin into https://demo.sylius.com/admin or in a local fresh Sylius installation with features loaded.
- Click on the SummaryStatistics Buttons and choose Month or Weeks.
- Click on the prev arrow and se the dates that are populated in the graph, the endDate is not the same or endDate -1 in the data reload.
- After that try to click in next arrow and the graph cann't refresh the information.

**Possible Solution**  
The problem comes from the javascripts:

/Users/joenilson/NetBeansProjects/Sylius/src/Sylius/Bundle/AdminBundle/Resources/private/js/dateObjects/month-date-object.js
/Users/joenilson/NetBeansProjects/Sylius/src/Sylius/Bundle/AdminBundle/Resources/private/js/dateObjects/week-date-object.js

Changing the calculation variables for prevDate and nextDate the data will be send correctly to the controller.

**Comment by Ferror** [comment]
Hi @joenilson ! I checked it and it works properly in Sylius 1.11 <3
