### ISSUE TITLE
Admin routing for orders misses /orders prefix for two routes

### ISSUE THREAD

**Issue by diimpp** [Sylius/Sylius#12225]
https://github.com/Sylius/Sylius/blob/e6c9cb6318bc806474427e0fca84c25515a4802d/src/Sylius/Bundle/AdminBundle/Resources/config/routing/order.yml#L123

```diff
    --- path: /{id}/resend-confirmation-email
    +++ path: /orders/{id}/resend-confirmation-email
```

https://github.com/Sylius/Sylius/blob/e6c9cb6318bc806474427e0fca84c25515a4802d/src/Sylius/Bundle/AdminBundle/Resources/config/routing/order.yml#L98

```diff
    --- path: /{id}/ship
    +++ path: /orders/{id}/ship
```

Otherwise you will get routes like this
![image](https://user-images.githubusercontent.com/870747/103670559-4e350980-4fac-11eb-9165-bcf0f9348eb8.png)

**Comment by coldic3** [comment]
Hey @diimpp,

thanks for raising an issue. I've reviewed [mentioned PR](https://github.com/Sylius/Sylius/pull/13237). For sure it's a bug and it'll be nice to fix it but we have to keep current route paths to avoid BC breaks.
