### ISSUE TITLE
isXmlHttpRequest is not correct if I disable localized URL

### ISSUE THREAD

**Issue by maximehuran** [Sylius/Sylius#12227]
**Sylius version affected**: 1.8.7

**Description**  

If I use `locale_switcher: storage` like in documentation to disable locale URLs, I have a 404 on my route with the `isXmlHttpRequest` condition.

```
sylius_shop:
    locale_switcher: storage
```

See https://github.com/monsieurbiz/SyliusRichEditorPlugin/issues/94 for more info

**Steps to reproduce**  

- Disable localized URL (Or just change `locale_switcher: storage` in `sylius_shop`)
- Create a route with the condition `condition: "request.isXmlHttpRequest()"`
- Make an ajax call to this route
- You will have a 404

**Possible Solution**  

I am on it...

**Comment by DieterHolvoet** [comment]
I also have `locale_switcher: storage` in my site, so it's indeed possible this is the issue.

**Comment by maximehuran** [comment]
Also check here : 
https://github.com/monsieurbiz/SyliusRichEditorPlugin/issues/94#issuecomment-755333704
https://github.com/monsieurbiz/SyliusRichEditorPlugin/issues/94#issuecomment-755337656

@lchrusciel do you think we can remove this part from the documentation to remove locale from URLs ?
```yaml
sylius_shop:
    locale_switcher: storage
```

**Comment by maximehuran** [comment]
ping @coldic3 @NoResponseMate

**Comment by NoResponseMate** [comment]
Can confirm it is indeed a bug.
Unfortunately not adding the storage locale switcher is not really an option if you have more than one locale configured, as in that case switching the current locale will do nothing.
I'll dig deeper and try to fix it.

**Comment by maximehuran** [comment]
So it's ok if you have only one locale, but not many
