### ISSUE TITLE
Different adjustement for units in same items 

### ISSUE THREAD

**Issue by SylvanoTombo** [Sylius/Sylius#12261]
**Sylius version affected**: 1.7

**Description**  

I am in the process of refunding the order but I see that for the product "XXX", I ordered 12 so there are 12 units. but I see that for the last 2 units, the adjustement is different.

![Screenshot from 2021-01-18 17-13-59](https://user-images.githubusercontent.com/40351002/104926908-d0143200-59b1-11eb-812c-15a32d5e721a.png)

**Comment by Zales0123** [comment]
Hello @SylvanoTombo! This is the desired behaviour. When calculating taxes (or promotions) for each order item unit, it's possible that the tax/promotion amount cannot be split equally. Then, the `ProportionalIntegerDistributor` service is used, to split the amount without fractions of the total. I suppose it's the reason for the situation you have :)

**Comment by SylvanoTombo** [comment]
Thanks!
