### ISSUE TITLE
Tag 2.6.0 on API Platform Core

### ISSUE THREAD

**Issue by oallain** [Sylius/Sylius#12273]
**Sylius version affected**: 1.8.*

**Description**  
Since [tag 2.6.0 on API Platform Core](https://github.com/api-platform/core/releases/tag/v2.6.0) install or update Sylius project is brocken.

**Steps to reproduce**  
### _On install new Sylius project_
```
composer create-project sylius/sylius-standard sylius
```

### _On update an existing project_
```
composer update
```

**Possible Solution**  
A quick fix can be :

### _On install new Sylius project_
  ```
  composer create-project --no-install --no-scripts sylius/sylius-standard sylius
  composer require --no-update api-platform/core:2.5.9
  composer install
  ```

### _On update an existing project_
  Add to composer.json
  ```json
  "conflict": {
         ...
         "api-platform/core": "^2.6",
      },
  ```
  Then run `composer update`
  
EDIT : Change after @loic425 comment.

**Comment by kayue** [comment]
This pull request would fix it https://github.com/Sylius/Sylius/pull/12274

**Comment by loic425** [comment]
@oallain I think you mean
```
"conflict": {
   ...
   "api-platform/core": "^2.6",
},
```

**Comment by kayue** [comment]
Already tagged as conflict in v1.8.9. This can be closed.
