### ISSUE TITLE
Webpack documentation seems very outdated

### ISSUE THREAD

**Issue by leonboot** [Sylius/Sylius#12307]
**Sylius docs version**: 1.8 / latest

**Description**
I have tried to replace Gulp asset management with Webpack by following the [Using Webpack Encore in Sylius](docs/cookbook/frontend/webpack.rst) cookbook page. However, I ran into many issues. I seem to have resolved them all, but I'd like to share what I've run in to.

## Missing NPM packages
The `yarn encore dev` command resulted in an error that sass-loader was not installed. After running the suggested `yarn add` command, Webpack continued but failed during asset compilation, yielding 61 errors. All errors seemed to be related to missing NPM packages. I had to `yarn add --dev` all the missing packages (from the top of my head: semantic-ui-css, jquery.dirtyforms, lightbox2, chart.js and slick-carousel).

## 404 errors on images
Both in the shop and in the admin, images such as the Sylius logos, the default homepage banner and the Sylius Plus logo in the footer were missing, despite having created the overruled `_[logo|header|etc.].html.twig` files. I consulted the manifest.json files for both the shop and admin entries, and noted that the paths to the respective images were quite different. For instance, the path to admin-logo.svg in SyliusAdminBundle/_logo.html.twig was `build/admin/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Resources/private/img/admin-logo.svg`, instead of `build/admin/images/admin-logo.svg`, as stated in the documentation.

## More 404's
After fixing the paths, more images were still missing. I had to add overrides for the following templates as well:
* SyliusAdminBundle/Security/_content.html.twig (the logo on the admin login page)
* SyliusShopBundle/Homepage/_banner.html.twig
* SyliusShopBundle/Layout/Footer/Grid/_plus.html.twig (the Sylius Plus promo)
The ShopBundle assets might not be that relevant, since the template is likely to be replaced entirely. But the logo on the login page seems desirable.

## Deprecated templates
I decided to have a look at the original templates I was supposed to override, and noticed that the _scripts.html.twig, _styles.html.twig and _logo.html.twig templates of the AdminBundle were deprecated and moved to the Layout folder. I think this should be reflected in the documenation, so users aren't overriding a template that might soon be deprecated.

I haven't filed a PR with an updated documentation page. First of all, I'm not sure if all these hoops I had to jump through have a more elegant solution (especially the long path names to image assets). I also found quite a few issues with (merged) PR's regarding incorrect image paths in the documentation, but I couldn't find these changes in the master branch.

**Comment by loevgaard** [comment]
For people finding this issue, here is a PR showing the migration from Gulp to Webpack in a plugin. I guess the procedure is much the same in an application: https://github.com/Setono/SyliusPluginSkeleton/pull/20

**Comment by jbator** [comment]
Anyone have a problem with Admin js issue with dirtyForms jquery plugin when using Webpack:

`"ss(...).dirtyForms is not a function" error on every admin page`

Issue is caused by this line of code from app.js in AdminBundle 

`$(`${formsList}, .check-unsaved`).dirtyForms();`

**Comment by wadjeroudi** [comment]
@jbator https://github.com/Setono/SyliusPluginSkeleton/issues/21

**Comment by jbator** [comment]
@wadjeroudi Thanks man, it does the trick :+1:

**Comment by coldic3** [comment]
Hi, in Sylius 1.12 we've updated webpack so I guess it can be closed :dancer: Link to the documentation: https://docs.sylius.com/en/1.12/cookbook/frontend/migrating-to-webpack-1-12-or-later.html

**Comment by leonboot** [comment]
Indeed! Well done on switching to Webpack! 💪
