### ISSUE TITLE
Cannot view order from thank you page as guest when I have an active account

### ISSUE THREAD

**Issue by benlinkevicius** [Sylius/Sylius#12305]
**Sylius version affected**: 1.8.8

**Description**  
Given I have an enabled customer account, john@example.com and I checkout with the same email without being logged in then I can't view my order by clicking "view order" from "thank you" page.

**Steps to reproduce**  
1. Enable a customer account in the backend;
2. Go to checkout and input the same email as the customer you just enabled;
3. Finish all the checkout steps and place the order;
4. Try to view order from "thank you" page.

You will now receive an argument type error.

**Comment by Ferror** [comment]
Hi @benlinkevicius we fixed it in the Sylius 1.11. Thanks for your issue <3
