### ISSUE TITLE
Integrity constraint violation: 1048 Column 'base_currency_id' cannot be null

### ISSUE THREAD

**Issue by DieterHolvoet** [Sylius/Sylius#12330]
**Sylius version affected**: 1.8.5

**Description**  
Creating a new channel triggers the following error:
```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'base_currency_id' cannot be null
```

**Steps to reproduce** 
1. Go to /admin/channels
2. Make sure there's an existing channel with as host name the current host name
3. Add a new channel. The base currency field is disabled because of [this code](https://github.com/Sylius/Sylius/blob/f27be445c11eccd0556d5edbafd60067960ca46c/src/Sylius/Bundle/CoreBundle/Form/EventSubscriber/AddBaseCurrencySubscriber.php#L48).
4. Save the new channel. Because the base currency field was disabled, its value is null and the error appears.

**Possible Solution**  
I suspect that the `getDisabledOption` is there to prevent the base currency from being changed on an existing channel. Somehow, the active channel is leaking into that method causing it to disable the field.

**Comment by Ferror** [comment]
@DieterHolvoet I tried to reproduce the issue with your steps on Sylius 1.11, yet I failed. It seems to be working as it should and the base currency field is not locked.

Please let me know if you are able still to reproduce the issue and maybe create a Loom video?
