### ISSUE TITLE
Impossible to edit product when a product association type has a numeric code

### ISSUE THREAD

**Issue by hdasdoria** [Sylius/Sylius#12339]
**Sylius version affected**: All

**Description**  
Unable to edit a product if any product association type has a numeric code.
The method `getProductAssociationByTypeCode()` in `Sylius\Bundle\ProductBundle\Form\DataTransformer\ProductsToProductAssociationsTransformer` receives an int instead of a string if the product association type code is composed by numbers only.

**Steps to reproduce**  
On every Sylius (works on https://demo.sylius.com too):
- Create a product association with a numeric code (use only numbers, like "123")
- Edit a product and hit the save button

**Possible Solution**  
Convert the code into a string before calling `getProductAssociationByTypeCode()`

**Comment by hdasdoria** [comment]
Any update ?
This gives a 500 when trying to add an associated product on the created association

**Comment by diimpp** [comment]
I've reproduced this bug with sylius 1.12 by following initial instructions.

1. Created new association type with numeric code `111111`
![image](https://user-images.githubusercontent.com/870747/203392496-17136a0d-8e91-49ab-bb7d-737817382cc4.png)
2. Opened random product edit page, selected one of the products under `Test association`. 
![image](https://user-images.githubusercontent.com/870747/203392821-74483eb3-9e7b-4e5d-80e4-4c72c3850980.png)
3. Saved the product and got the described error.
![image](https://user-images.githubusercontent.com/870747/203393108-86f75fa6-38c2-446a-b30e-1443994ab14f.png)


@jakubtobiasz Hi, can you please triage.

**Comment by jakubtobiasz** [comment]
Hi @diimpp!
Thank you for bumping this issue, I added this issue to the agenda for our nearest meeting 🙂.

**Comment by NoResponseMate** [comment]
Hi @hdasdoria and @diimpp 

A fix has just been merged and will be available in the next patch of 1.12.
Cheers 🍻
