### ISSUE TITLE
Unified API ProductVariant requires a non-existing ID parameter

### ISSUE THREAD

**Issue by Kyngo** [Sylius/Sylius#12343]
**Sylius version affected**: As of 1.8 and above

**Description**  

ProductVariant object requires an ID when making a POST /api/v2/admin/product-variants

**Steps to reproduce**  

It can be reproduced in https://master.demo.sylius.com/api/v2/docs if you go to the POST ProductVariant. When trying to make such query in a local environment I get the following error whatever I put in the request body (even if it's empty):

`{"code":404,"message":"Invalid identifier value or configuration."}`

**Possible Solution**  

Remove the need for this parameter on API Platform

**Comment by coldic3** [comment]
Hey, @Kyngo 
I see it was fixed in the meantime. Feel free to reopen if you still have this issue :dancer:
