### ISSUE TITLE
Translation override not working

### ISSUE THREAD

**Issue by adwil13** [Sylius/Sylius#12345]
**Sylius version affected**: 1.8.5-1.8.9

**Description**  
I am trying to override translation for Payum payment description, but it's not working.

**Steps to reproduce**
Original translation is located in:
`vendor/sylius/sylius/src/Sylius/Bundle/PayumBundle/Resources/translations/messages+intl-icu.en.yml`

I've added in `translations/messages+intl-icu.en.yml`:
```yml
sylius:
    payum_action:
        payment:
            description: 'new translation'
```

However after clearing cache (either by using `bin/console cache:clear` or removing cache folder manually)
I'm still getting the old translation.

**Possible Solution**  
TBH I don't have a possible solution. Every other translation I've overridden so far worked without any issues.

**My thoughts**
TBH default payment description makes no sense. It's not really useful for anyone to *not* include order number in payment description. Order total and number of purchased items are just not enough to identify this transaction for accounting purposes.

**Comment by SVillette** [comment]
I had the same issue with all my translations after a `composer update.`

Symfony update their `symfony/finder` component and the issue came from that part. (related issue: https://github.com/symfony/symfony/issues/40014)

You can resolve this issue by adding this in your composer.json (at least it worked for me).

`    "conflict": {
        "symfony/finder": "=4.4.19"
    },`

**Comment by rdinna** [comment]
> I had the same issue with all my translations after a `composer update.`
> 
> Symfony update their `symfony/finder` component and the issue came from that part. (related issue: [symfony/symfony#40014](https://github.com/symfony/symfony/issues/40014))
> 
> You can resolve this issue by adding this in your composer.json (at least it worked for me).
> 
> ` "conflict": { "symfony/finder": "=4.4.19" },`

Thank you!

**Comment by Zales0123** [comment]
I guess it can be closed :) Thank you, @SVillette, for this useful tip 👌
