### ISSUE TITLE
Wrong accordion initialisation on new collection item

### ISSUE THREAD

**Issue by DjLeChuck** [Sylius/Sylius#12380]
**Sylius version affected**: 1.8.9 (and other I think)

**Description**  
When a new collection item is added, the accordions inside are initialized with `.accordion` selector: 
```js
  $('body').on('DOMNodeInserted', '[data-form-collection="item"]', (event) => {
    if ($(event.target).find('.accordion').length > 0) {
      $(event.target).find('.accordion').accordion();
    }
  });
```

This is a problem when the new item has nested accordion because only the first level of accordion should be initialized, not the other ones.

**Steps to reproduce**  
I have found this example on codepen, the behaviour is the same: https://codepen.io/anon/pen/gzWyGR

When clicking on a nested accordion, it "open/close" instantly because of the double initialization.
In this example, the solution is to remove the `.ui` class in nested accordion, but not for Sylius as explain in `Possible Solution`.

**Possible Solution**  
Change the initialisation code and use the selector `.ui.accordion`

```js
  $('body').on('DOMNodeInserted', '[data-form-collection="item"]', (event) => {
    if ($(event.target).find('.ui.accordion').length > 0) {
      $(event.target).find('.ui.accordion').accordion();
    }
  });
```

**Comment by kulczy** [comment]
Hi @DjLeChuck it looks like you're right. There is no such case in Sylius, but PR is always welcome 😄

**Comment by DjLeChuck** [comment]
Done @kulczy 👍🏻

**Comment by kulczy** [comment]
@DjLeChuck thanks!
