### ISSUE TITLE
Unexpected duplicated custom OrderProcessor

### ISSUE THREAD

**Issue by benjaminmal** [Sylius/Sylius#12389]
**Sylius version affected**: 1.8.9

**Description**  
When creating a custom `OrderProcessor`, I find out that it was called 2 times for only one call in the [OrderItemController](https://github.com/Sylius/Sylius/blob/909500efa30b1377ff627b111b6b869cba6c1106/src/Sylius/Bundle/OrderBundle/Controller/OrderItemController.php#L76). I dumped `$orderProcessors` in [CompositeOrderProcessor](https://github.com/Sylius/Sylius/blob/909500efa30b1377ff627b111b6b869cba6c1106/src/Sylius/Component/Order/Processor/CompositeOrderProcessor.php#L40) and found out that my `OrderProcessor` exists twice in PriorityQueue but the second time only with priority `0`. Also, only my custom processor is duplicated.

```php
class OrderProcessor implements OrderProcessorInterface
{
    public function process(OrderInterface $order): void
    {
        dump('passed');
    }
}
```
```yaml
services:
    # ...
    App\Processor\OrderProcessor:
        tags:
            - { name: sylius.order_processor, priority: 70 }
```

Dumped data:
```
In CompositeOrderProcessor.php line 40:

Zend\Stdlib\PriorityQueue {#7767 ▼
  #queueClass: "Zend\Stdlib\SplPriorityQueue"
  #items: array:9 [▼
    0 => array:2 [▼
      "data" => App\Processor\OrderProcessor {#7775}
      "priority" => 70
    ]
    1 => array:2 [▼
      "data" => App\Processor\OrderProcessor {#7775} <--------------- Unexpected
      "priority" => 0
    ]
    2 => array:2 [▼
      "data" => Sylius\Component\Core\OrderProcessing\OrderAdjustmentsClearer {#7777 ▶}
      "priority" => 60
    ]
   ...
  ]
  #queue: Zend\Stdlib\SplPriorityQueue {#7776 ▶}
}

In OrderProcessor.php line 12:

"passed"

In OrderProcessor.php line 12:

"passed" <--------------- Unexpected
```
**Steps to reproduce**  
I basically followed the [installation book](https://docs.sylius.com/en/latest/book/installation/installation.html):
- `composer create-project sylius/sylius-standard`
- Set database in `.env` file
- `bin/console sylius:install`. 
- `yarn install && yarn build`
- Create `Processor\OrderProcessor` (see above)
- Register it in `services.yaml` (see above)
- `symfony serve`
- Choose a product in Shop and add it to cart.
- In profiler, check the  dump section for `POST` request: `en/ajax/cart/add?productId=6` 

**Possible Solution**  
Not sure, but it seems that the container "thinks" that the processor has 2 tags, one with the correct priority and the other without one.

Here the container file that call `CompositeOrderProcessor::addProcessor()`. 
`var/cache/dev/Container****/getSylius_OrderProcessing_OrderProcessorService.php`
```php
// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sylius.order_processing.order_processor' shared service.

include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Order/Processor/OrderProcessorInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Component/Order/Processor/CompositeOrderProcessor.php';
include_once \dirname(__DIR__, 4).'/src/Processor/OrderProcessor.php';

$this->services['sylius.order_processing.order_processor'] = $instance = new \Sylius\Component\Order\Processor\CompositeOrderProcessor();

$a = new \App\Processor\OrderProcessor();

$instance->addProcessor($a, 70);
$instance->addProcessor($a, 0); // <--------------- Unexpected
$instance->addProcessor(($this->services['sylius.order_processing.order_adjustments_clearer'] ?? $this->load('getSylius_OrderProcessing_OrderAdjustmentsClearerService.php')), 60);
// ...

return $instance;
```

Or maybe am I doing something wrong ? :)

**Thanks**

**Comment by vvasiloi** [comment]
Try this:
```
services:
    # ...
    App\Processor\OrderProcessor:
        autoconfigure: false
        tags:
            - { name: sylius.order_processor, priority: 70 }
```

**Comment by benjaminmal** [comment]
Thanks @vvasiloi, you're the best. This fix the issue. Is this the expected behavior ?

**Comment by vvasiloi** [comment]
Yes, this is expected.
Sylius enables autoconfiguration for instances of `OrderProcessorInterface` [here](https://github.com/Sylius/Sylius/blob/bff75358c0f1aa42828baf6dddf97ed112f2237a/src/Sylius/Bundle/OrderBundle/DependencyInjection/SyliusOrderExtension.php#L45-L48) and adds the corresponding tag, then you add it the second time in the service definition, so it now has 2 tags.

**Comment by benjaminmal** [comment]
Thanks for answering. I'm closing the issue since this is the expected behavior.
