### ISSUE TITLE
Wrong totals passed to PayPal while converting payment

### ISSUE THREAD

**Issue by mmenozzi** [Sylius/Sylius#12381]
Give the following pre-conditions:
* Having a shipping method subject to a given tax category with a flat rate cost greater than zero
* Having a not included in price tax rate for the above tax category and a given zone
* Checking out with a billing address in the zone above

You'll have that:
* The `\Sylius\Component\Core\Model\Order::getShippingTotal()` method will give you the shipping cost **including tax**. 
* The `\Sylius\Component\Core\Model\Order::getTaxTotal()` method will give you the tax total **including the shipping tax amount**.

So this means that here, when converting payment for PayPal:

https://github.com/Sylius/Sylius/blob/9b9831844a380adb008cf047e090de97a6e8b530/src/Sylius/Bundle/PayumBundle/Action/Paypal/ExpressCheckout/ConvertPaymentAction.php#L47-L83

The shipping tax amount is passed twice: first time inside the "Tax Total" item and second time in the "Shipping Total" item.

This leads to a PayPal API error (**The totals of the cart item amounts do not match order amounts.**) which makes fail every PayPal payment with the above preconditions.

**Comment by vvasiloi** [comment]
Looks like a duplicate of https://github.com/Sylius/Sylius/issues/8950

**Comment by mmenozzi** [comment]
You’re right @vvasiloi. Closing.
