### ISSUE TITLE
Can't start new project

### ISSUE THREAD

**Issue by RomkaLTU** [Sylius/Sylius#12400]
**Sylius version affected**: 1.9.0

**Description**  
Followed installation instructions from https://docs.sylius.com/en/latest/getting-started-with-sylius/installation.html
And it simply doesn't work. Getting error 

`Fatal error: Uncaught Error: Class 'Symfony\Component\Debug\Debug' not found ...`

**Comment by CodableFR** [comment]
Hello,
Go in public/index.php and replace : 
`use Symfony\Component\Debug\Debug;`

by 

`use Symfony\Component\ErrorHandler\Debug;`

**Comment by Zales0123** [comment]
@RomkaLTU thank you for the report, thank you for the answer @CodableFR :) The fix is opened on `Sylius-Standard` repository https://github.com/Sylius/Sylius-Standard/pull/524 🚀

**Comment by pamil** [comment]
I've just released v1.9.1 fixing this issue for new projects - for existing projects, @CodableFR's change will fix the issue.
