### ISSUE TITLE
The `vendors` translations are not overloaded by default `translations/messages.en.yml`

### ISSUE THREAD

**Issue by syjust** [Sylius/Sylius#12409]
**Sylius version affected**: 1.8.9 / 1.9.0

**Description**  
The `vendors` translations are not overloaded by default `translations/messages.en.yml`
Flashes & Validators are also impacted.

**Steps to reproduce**  
1. install a default sylius project [installation guide](https://docs.sylius.com/en/latest/book/installation/installation.html)
2. change the homepage purposed translation like `sylius.homepage.about_us_content` or `sylius.homepage.newsletter_description` into your `%kernel.project_dir%/translations/messages.en.yaml` file
3. `php bin/console clear:cache`
4. message is not overloaded

Note :
1. if you put a new translation by overriding `vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views/Homepage/index.html.twig` for example (copy file to `templates/bundles/ShopBundle/Homepage/index.html.twig` and add something like `{{ 'app.ui.my_homepage_cool_message|trans }}` into the overridden template )
1. then if you add this translation in your `%kernel.project_dir%/translations/messages.en.yaml` => `app.ui.my_homepage_cool_message: "My Sylius e-shop is very cool"`
1. the message is well translated

Note 2 : this bug is not reproducible on Sylius v 1.8.0

**Workaround**
One workaround is to move problematic translations to a new file : `translations/messages+intl-icu.en.yaml`
the `+intl-icu` translations are prioritized (but this not work for already pluralized messages like `sylius.ui.item.choice`)

thank you to @Prometee for this workaround

**Possible Solution**  
I think SyliusThemeBundle can be responsible of this issue but I can't prove it. (I tried to replace all sylius translator services by default symfony translator service, but translations still not work)

**Comment by syjust** [comment]
I found this issue in Symfony https://github.com/symfony/symfony/issues/40014 .

It seem's not be a Sylius problem :)

**Comment by syjust** [comment]
upgrading symfony to 4.4.20 should fix the issue but does not work
downgrading symfony to 4.4.17 resolve the issue

**Comment by robjensen82** [comment]
I had the same problem. I did `composer require symfony/translation:4.4.17` and that fixed the issue for me. I have an override of `FOSUserBundle.en.yml` that was no longer being used.

**Comment by syjust** [comment]
In my case, downgrading only `symfony/translation` does not fix the issue.

I just tested an upgrade to symfony `5.3.3.` => issue is always here 😢
