### ISSUE TITLE
BackOffice > Dashboard statistics DateTime::__construct error

### ISSUE THREAD

**Issue by morgan-blondellet** [Sylius/Sylius#12428]
**Sylius version affected**: upgraded from 1.7.x to 1.8.9

In the back office on the dashboard page, statistics are not showing. When visiting the `/statistics` url generated in the twig template i get this error

![image](https://user-images.githubusercontent.com/5166399/110356667-c6668c80-803a-11eb-94e2-a7ed7178ec46.png)

**Steps to reproduce**  
Symfony 4.4.18, Sylius upgraded from 1.7.x to 1.8.9. I just logged in the back office and notices the statistics were not showing.

**Possible Solution**  
Habing a default value to give to the DateTime constructor if no `startDate` and/or no `endDate` is present in the symfony Request in https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminBundle/Controller/DashboardController.php#L88

**Comment by coldic3** [comment]
Hey @morgan-blondellet,

I see the problem does not exist anymore. Feel free to reopen if you still have this issue.
