### ISSUE TITLE
Corrupted taxons tree when trying to delete used taxon

### ISSUE THREAD

**Issue by LucaGallinari** [Sylius/Sylius#12422]
**Sylius version affected**: 100% sure for versions >= 1.8.3

**Description**  
Trying to delete a taxon that is associated to some products will results in a change of the "tree_left" and "tree_right" properties of some taxons. If you keep trying to delete the same taxon it will corrupt more and more taxons.
You can easily reproduced this on your demo by trying to delete the "Men" taxon under "T-shirts".

**Steps to reproduce**  
1. Create a taxon tree with 3/4 taxons under the root category and 2/3 taxons for each of them
2. Add some products
3. Associate each product to just one of the leaf taxons
4. Try to remove the first leaf taxon of the taxon tree, it will fails cause it's associated to some products
5. The tree gets corrupted (precisely the "tree_left" and "tree_right" properties of some taxons) and on frontend, in each taxon, you will see products of other taxons

**Possible Solution**
...

**Comment by lchrusciel** [comment]
The problem occurs because the Gedmo\Tree extension updates leaf nodes before the deletion transaction begin. 

Reference: https://github.com/doctrine-extensions/DoctrineExtensions/issues/1062 and https://github.com/doctrine-extensions/DoctrineExtensions/blob/main/doc/transaction-safety.md  

We will solve this issue on our end eventually, but for anyone who would like to unblock themself, you need to wrap the taxon deletion operation with a transaction. 

The following snippet does exactly that. You have to add the following class:

```php
<?php

declare(strict_types=1);

namespace App\Controller;

use Doctrine\ORM\EntityManagerInterface;
use Sylius\Bundle\ResourceBundle\Controller\ResourceDeleteHandlerInterface;
use Sylius\Component\Resource\Model\ResourceInterface;
use Sylius\Component\Resource\Repository\RepositoryInterface;

final class ResourceDeleteHandler implements ResourceDeleteHandlerInterface
{
    private ResourceDeleteHandlerInterface $decoratedResourceDeleteHandler;
    private EntityManagerInterface $entityManager;

    public function __construct(ResourceDeleteHandlerInterface $decoratedResourceDeleteHandler, EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
        $this->decoratedResourceDeleteHandler = $decoratedResourceDeleteHandler;
    }

    public function handle(ResourceInterface $resource, RepositoryInterface $repository): void
    {
        $this->entityManager->beginTransaction();

        try {
            $this->decoratedResourceDeleteHandler->handle($resource, $repository);

            $this->entityManager->commit();
        } catch (\Exception $exception) {
            $this->entityManager->rollback();

            throw $exception;
        }
    }
}
```

to ```App/Controller``` folder and register it in a container:

```xml
<service id="\App\Controller\ResourceDeleteHandler" decorates="sylius.resource_controller.resource_delete_handler" public="false">
    <argument type="service" id="Sylius\Bundle\CoreBundle\ResourceDeleteHandler.inner" />
    <argument type="service" id="doctrine.orm.entity_manager" />
</service>
```

Please, let me know it worked for you.

Best regards,

Łukasz Chruściel.

**Comment by LucaGallinari** [comment]
Great! I'll try soon. Thanks

**Comment by LucaGallinari** [comment]
Thanks!
