### ISSUE TITLE
Missing productVariantCode param throws 500

### ISSUE THREAD

**Issue by flashlabs** [Sylius/Sylius#12433]
**Sylius version affected**: 1.8.0

**Description**  
Not providing `productVariantCode` parameter to `/shop/orders/{id}/items` endpoint results in `MissingConstructorArgumentsException ` exception:
```
Uncaught PHP Exception Symfony\Component\Serializer\Exception\MissingConstructorArgumentsException: "Cannot create an instance of "Sylius\Bundle\ApiBundle\Command\Cart\AddItemToCart" from serialized data because its constructor requires parameter "productVariantCode" to be present."
```

**Steps to reproduce**  
```
static::createClient()->request(
            'PATCH',
            "/shop/orders/{id}/items",
            [
                'headers' => ['Content-Type' => 'application/merge-patch+json'],
                'json' => [
                    'productCode' => {productCode},
                    // missing key -> 'productVariantCode' => {productVariantCode},
                    'quantity' => {quantity},
                ],
            ]
        );
```

**Possible Solution**  
Add validation of required parameters to `AddItemToCart` command or higher to `CartContext`.

**Comment by coldic3** [comment]
Hey @flashlabs,

Request body has changed and you need just a product variant IRI and quantity. I guess this issue can be closed. Feel free to reopen if you still have this issue.
