### ISSUE TITLE
Too generic API errors

### ISSUE THREAD

**Issue by robopuff** [Sylius/Sylius#12432]
**Sylius version affected**: 1.8.5

**Description**  
When using still experimental API bundle a lot of errors are just thrown with code 500 and some of them are removed from JSON and thrown into logs

**Steps to reproduce**  
* Create a new cart without any products in the new API
* Call `complete` endpoint

**Possible Solution**  
Widely used Assert is throwing too generic errors, replace with a better solution

**Comment by coldic3** [comment]
Hey @robopuff,
I see it's already fixed and you should receive 422 code with a detailed message. We are aware of problems with 500 errors in the checkout. Feel free to open a new issue if you find a similar problem in a different place in the API :woman_dancing:
