### ISSUE TITLE
Paymernt Method, Shipping Method: Column 'name' cannot be null

### ISSUE THREAD

**Issue by franzwilding** [Sylius/Sylius#12449]
**Sylius version affected**: 1.9.1

**Description**  
You can save payment methods and shipping methods without a name, however this produces an SQL error during checkout:
```
An exception occurred while executing 'INSERT INTO sylius_payment_method_translation (name, description, instructions, locale, translatable_id) VALUES (?, ?, ?, ?, ?)' with params [null, null, null, "de_AT", 1]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null
```

**Steps to reproduce**  
Create a payment or shipping method without a name.

**Possible Solution**  
Mark the field as required or catch the error during checkout

**Comment by coldic3** [comment]
Hey @franzwilding,
thanks a lot for raising an issue :dancer: Sylius 1.9 is not supported. I've tried to reproduce this bug on [demo.sylius.com](https://demo.sylius.com) but don't see this SQL error message. Could you write the scenario for your issue if you still have this error in version 1.10 or higher?
