### ISSUE TITLE
[ADMIN] Disable list of languages supported in the store

### ISSUE THREAD

**Issue by st-pham** [Sylius/Sylius#12464]
**Describe the proposed solution**
#### Feature explanation
In admin panel (/admin/locales/), we can add a language to the list of languages supported in the site, but we cannot disable them in order to hide the language we don't want to use.

#### Proposed solution
Add attribute `active(bool)` to entity `Locale` to allow us to show language settings for only the languages which are active.

**Comment by vvasiloi** [comment]
You can enable/disable locales per channel:
![image](https://user-images.githubusercontent.com/7114562/111873106-63a8b580-8997-11eb-9ab2-5f7563c7c450.png)
![image](https://user-images.githubusercontent.com/7114562/111873117-6c998700-8997-11eb-9c16-0625976e4f3e.png)

**Comment by st-pham** [comment]
Thanks for the info. So, my feature is useless :) I will close the issue

**Comment by Rafikooo** [comment]
Hello @st-pham,

we discussed your feature proposal and decided that it is not for our current goals. It is rather edge case, and to help clean up unused locations, we have introduced [this](https://github.com/Sylius/Sylius/pull/15026) PR. I hope this will partially solve your problem 💃 

Best, Rafał
