### ISSUE TITLE
Upgrading from v1.6 to v1.7 on old directory structure keeps loading removed bundles

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#12463]
**Sylius version affected**: 1.7.x and higher when on old directory structure

**Description**  
I followed the [upgrade guide to v1.7](https://github.com/Sylius/Sylius/blob/master/UPGRADE-1.7.md) to upgrade from Sylius v1.6 to Sylius v1.7. As this project originated from the time Sylius was at version `v1.0.0-beta-1`, we still have the Symfony 3.4 directory structure. Our kernel therefore extends from `Sylius\Bundle\CoreBundle\Application\Kernel`.

In the new directory structure / new kernel setup (looking at Sylius Standard) this behavior is not used anymore. Your own kernel extends directly from the Symfony kernel. But as the old structure still extends it, we get an error:

```
$ bin/console
Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "SonataCoreBundle" from namespace "Sonata\CoreBundle".
```

The upgrade guide describes to remove several bundles, but these bundles are being loaded from the Sylius Kernel. This makes that the old directory structure incompatible with Sylius v1.7.

I'm not sure why the file at all is still in the repository, but in case we keep it there I think we should change it to make it work again. Another problem is here that Sylius v1.7 is not getting new releases anymore. WDYT @pamil ? It would be a pain for many to go from Sylius v1.6 to Sylius v1.8 straight if we want to make it work there. I like to upgrade in small increments as possible, to have better control over it.

An alternative is of course that I add local dependencies to these removed packages in order to keep it working. Or, I fork Sylius temporary to fix it myself. But I guess many others eventually are going to run into it, I'm probably not the only out there that still uses this directory structure. And yes, I will upgrade it at some moment ;-)

**Steps to reproduce**  
* Upgrade project to Sylius v1.7 and notice errors on `bin/console`
* Or: checkout branch 1.7 from GH, install dependencies and check `vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Application/Kernel.php`

**Comment by stefandoorn** [comment]
I'm aware of https://github.com/Sylius/Sylius/blob/1.3/UPGRADE-1.3.md#directory-structure-change, but it's nowhere mentioned that this will become 'problematic' before Sylius v2.0.

**Comment by vvasiloi** [comment]
@stefandoorn I recently upgraded a project from 1.6 straight to 1.9 easily, but it has the new directory structure, so I made a diff with Sylius-Standard to incorporate the changes easier.
It's worth upgrading the directory structure asap, because it makes upgrading to new versions easier.
Newer versions have upgrade processes and instructions  made according to the new directory structure.
Since 1.7 is no longer maintained, you have to fix the issue in the project. The easiest solution I can think of is to not call the `registerBundles()`  from the Core Bundle Kernel and register all bundles in your application kernel.
The better way would be to upgrade the directory structure.
Maybe a note mentioning the issue can be added to UPGRADE-1.7.md.

**Comment by stefandoorn** [comment]
Finished it. It's a bit of work, but with some guidance of @vvasiloi on Slack I got through it, thanks again! I guess it's enough indeed to mention in the UPGRADE guide somewhere, and it seems not many are running into it.

**Comment by lchrusciel** [comment]
@stefandoorn can you propose some note to docs for others?

**Comment by Rafikooo** [comment]
Hello @stefandoorn,

since these versions of Sylius are no longer supported, we have decided to close this issue, thank you for contributing 💃 

Best, Rafał
