### ISSUE TITLE
Cart item quantity update relies on fragile SQL result sorting

### ISSUE THREAD

**Issue by robgwin** [Sylius/Sylius#12515]
**Sylius version affected**: I'm using 1.7.11 but I've verified the basic problem exists on 1.9.2 as well.

**Description**
When I change the quantity of items in my cart and hit "Update Cart", the new quantities sometimes get applied to the wrong items. The submitted form simply contains a list of quantities, and so only works properly when the item sort order is consistent between the cart display and update handler. Which it usually is, but it can be easily thrown off because there is no explicit sorting in either case.

When displaying the cart, the items are retrieved with a query like this:

`SELECT ... FROM sylius_order s0 LEFT JOIN sylius_order_item s1 ON s0.id = s1.order_id WHERE s0.id=28`
 
When updating the cart (OrderController::saveAction()) the items are retrieved with a query like this:

`SELECT ... FROM sylius_order_item t0 WHERE t0.order_id = 28;`

These queries happen to return items in the same order, but without any explicit sorting, small things can throw it off. In my case I have a plugin that adds a RentalReservation property to the OrderItem, which ends up changing that second query to something like:

`SELECT ... FROM sylius_order_item t0 LEFT JOIN rental_reservation t12 ON t12.order_item_id = t0.id WHERE t0.order_id = 28;`

This changes the sort order of the results. Items with a non-null reservation always come first for some reason -- and the reason is irrelevant, since one should never rely on a non-explicit result sort order. The new quantities are blindly applied to the items in whatever order they are found, which means they map to the wrong items.

Even though my plugin is the surface cause of the problem, this seems like a weak point in Sylius that could be improved. 

**Possible Solution**  
Either of these would do it:
* Explicitly sort order items by id in both cases
* Include the item ids in the cart form to make sure the quantities are mapped to the proper items

**Comment by vvasiloi** [comment]
@robgwin ordering by id will work for sequences, but not for uuid or other identifier generation strategies.

**Comment by robgwin** [comment]
@vvasiloi good point, so the other solution is probably best.

/{locale}/cart currently POSTs the quantity values only:

sylius_cart[items][0][quantity]: 2
sylius_cart[items][1][quantity]: 3
sylius_cart[items][2][quantity]: 1

But it should include item identifiers as well, maybe like this:

sylius_cart[items][0][id]: 57
sylius_cart[items][0][quantity]: 2
sylius_cart[items][1][id]: 123
sylius_cart[items][1][quantity]: 3
sylius_cart[items][2][id]: 98
sylius_cart[items][2][quantity]: 1

And the form handler should take that into account when loading the resource.

**Comment by NoResponseMate** [comment]
The order of items in collections should be consistent since #14685.
Let me know if that's not the case.

Cheers 🍻
