### ISSUE TITLE
[UserBundle][Checkout] Incorrect credentials message is not translated in the checkout process

### ISSUE THREAD

**Issue by Florian-Merle** [Sylius/Sylius#12527]
**Sylius version affected**: All

**Description**  
Incorrect credentials message is not translated in the checkout process (it's always in english).

**Steps to reproduce**  

In the checkout process, if I'm a not connected and I try to login with my email and a wrong password, the error message I get is not translated and always in english.

```yaml
Given the store operates on a channel named "France"
And the user "client@email.com" with the password "correct_password" exists
And the visitor has product "Some product" in the cart
When the visitor specify the email as "client@email.com"
And the visitor specify the password as "wrong_password"
Then the visitor should see the error message "Identifiants incorrects" # Currently the error message is always "Incorrect credentials" the current locale is not taken into accout

```
**Possible Solution**  
The message should be translated here https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/UserBundle/Authentication/AuthenticationFailureHandler.php#L27

**Comment by lchrusciel** [comment]
Hey Florian,

thanks for opening this issue. If this problem is related to what I think it is, it should be already covered at https://github.com/Sylius/Sylius/pull/12458/

Best regards,
Łukasz

**Comment by lchrusciel** [comment]
Hopefully should be closed :)
