### ISSUE TITLE
Standardize message buses naming

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#12548]
References to https://github.com/Sylius/Sylius/pull/12546#discussion_r616522691.

**Comment by lchrusciel** [comment]
We have 7 busses defined across 4 products. Each of them with a different name. We should unify this configuration.

  At Sylius (https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ApiBundle/Resources/config/app/config.yaml#L33-L43 ) we should change:
* sylius_default.bus to sylius.command_bus
* sylius_event.bus to sylius.event_bus
* make an alias sylius_default.bus that will point out to sylius.command_bus
* make an alias sylius_event.bus that will point out to sylius.event_bus
* Remove from event config all middleware and add allow_no_handlers

at Invoicing Plugin:
* Remove command bus and reuse sylius_default.bus. In the next version we can migrate these busses again (https://github.com/Sylius/InvoicingPlugin/blob/master/src/Resources/config/config.yml#L14-L19 )
* Explicitly declare busses on each handler (E.g. https://github.com/Sylius/InvoicingPlugin/blob/master/src/Resources/config/services/events.xml#L15  - we should look for all <tag name="messenger.message_handler" />)

at Refund Plugin: 
* Remove custom handlers and reuse sylius_default.bus. In the next version we can migrate these busses again (https://github.com/Sylius/RefundPlugin/blob/master/src/Resources/config/app/config.yml#L9-L34)
* Explicitly declare busses on each handler (E.g. https://github.com/Sylius/RefundPlugin/blob/master/src/Resources/config/services/command_bus.xml#L13  - we should look for all <tag name="messenger.message_handler" />

**Comment by pamil** [comment]
To add up on top of @lchrusciel's comment, these `sylius_default.bus` and `sylius_event.bus` should be marked as deprecated - https://symfony.com/blog/new-in-symfony-4-3-deprecating-service-aliases.

**Comment by GSadee** [comment]
I assume, this issue has been resolved by #12602
