### ISSUE TITLE
Priority of order processors conflicts with shipping method resolving

### ISSUE THREAD

**Issue by aleho** [Sylius/Sylius#12554]
**Sylius version affected**: 1.9

**Description**  
Looking at `order_processing.xml` the current priority of processors is

```
  50. sylius.order_processing.order_shipment_processor:   OrderShipmentProcessor
  40. sylius.order_processing.order_prices_recalculator:  OrderPricesRecalculator
  30. sylius.order_processing.shipping_charges_processor: ShippingChargesProcessor
  ...
```

If shipping method rules are based on totals (e.g. shipment unit totals, order sum, etc.) shipping method resolving will not work in `50: OrderShipmentProcessor` as expected.

The reason for this is that updated sums will not yet be available as all items' values are calculated in `OrderPricesRecalculator` one step afterwards.

**Steps to reproduce**  
1. Configure two shipping methods. One with rule "order total sum <= 29.99", one with "order total sum >= 30.00"
2. Empty cart.
3. Add one item to cart that makes rule checker condition true (e.g. "order total sum >= 30.00").
4. Check shipping method being set. It's not the one that matches the condition.

Depending on the template this might not be observed immediately, as cart summary / overview might not include shipping costs (in our templates they do).

**Possible Solution**  
Switch priorities of `OrderPricesRecalculator` and `OrderShipmentProcessor` so that all fields are calculated before shipping method is determined.

**Comment by mdevlamynck** [comment]
There is a similar issue with taxes where the incorrect shipping method is selected:
#### Steps to reproduce
1. Create a shipping method A with "order total sum <= 29.99" and another B with "order total sum >= 30.00".
2. Create a cart where the total without taxes is bellow 29.99 and the total with taxes is above 30.00.
3. On the shipping method form the shipping method B is proposed and not A (since the total is above 30.00).
4. On submission when OrderShipmentProcessor runs the total is without taxes so method B is unavailable.

**Comment by JinbeiStudio** [comment]
A solution less drastic than changing your services order, is to call manually the service OrderPricesRecalculator on your order entity in the checker so it will have the correct amount for the total.

$order = $shippingSubject->getOrder();
$this->orderPricesRecalculator->process($order);
$total = $order->getItemsTotal();

**Comment by Leobaillard** [comment]
Hi! Is there any current plans to address this?

This seems to me like something that would be used commonly in e-commerce applications. Maybe the people actually doing this are using third-party plugins?

**Comment by CoderMaggie** [comment]
@Leobaillard @aleho @mdevlamynck we're on it, see #13769 🚀
