### ISSUE TITLE
Improve register form email type validation

### ISSUE THREAD

**Issue by Loocos** [Sylius/Sylius#12551]
**Sylius version affected**: 1.8 (i think all are affected)

**Description**  
We can create account user with an invalid email. Some forget to add the domain extension

**Steps to reproduce**  
On https://demo.sylius.com/en_US/register
Try to register a new account with an email like : xxxx@yyyy
Submit the form
You'll have a success message. 

**Possible Solution**  
Add a form constraint to the email type or add a pattern regex on the input using the HTML5 property

**Comment by Ferror** [comment]
Hi @Loocos it seems like it is already fixed with the Sylius 1.11 <3
