### ISSUE TITLE
Error when updating to Chart.js v3

### ISSUE THREAD

**Issue by UlrichHP** [Sylius/Sylius#12560]
**Sylius version affected**: 1.8.12

**Description**

When compiling using npm or yarn, there is an error :
```
"./vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-chart.js" contains a reference to the file "chart.js/dist/Chart.min".
This file can not be found, please check it for typos or update it if the file got moved.
```

**Steps to reproduce**

- Update Chart.js to v3
- use npm or yarn

**Possible Solution** 

In AdminBundle/Resources/private/js/sylius-chart.js, Chart.min.js is imported but now in v3, chart.min.js is in lowercase according to their [documentation](https://www.chartjs.org/docs/latest/getting-started/v3-migration.html) : `Distributed files are now in lower case. For example: dist/chart.js.`

**Comment by Ferror** [comment]
I'm closing the issue as we made it work https://github.com/Sylius/Sylius/pull/13419 <3
