### ISSUE TITLE
It's impossible to change shipping calculator from one with configuration to one without

### ISSUE THREAD

**Issue by rimas-kudelis** [Sylius/Sylius#12577]
It seems like there a logical flaw in the code referenced below: if a shipping method is already configured to use a calculator with a defined configuration form, `addConfigurationField()` triggered by `PRE_SET_DATA` will add a child form for that configuration. However, if you change the method to one without options, the same method will be triggered by `PRE_SUBMIT`, but it will not remove the pre-existing child form, thus causing validation to fail and making it impossible to save the shipping method with this change.

https://github.com/Sylius/Sylius/blob/4fd80b913d58857c3661fde02750cdcbd5fe650d/src/Sylius/Bundle/ShippingBundle/Form/Type/ShippingMethodType.php#L95-L112

https://github.com/Sylius/Sylius/blob/4fd80b913d58857c3661fde02750cdcbd5fe650d/src/Sylius/Bundle/ShippingBundle/Form/Type/ShippingMethodType.php#L152-L163

**Comment by Zales0123** [comment]
Hello Rimas! First of all, sorry for such a long response time... We're making progress with being up-to-date with issues, but still fails from time to time 🖖 

If I understood you correctly, this functionality seems to be working. I've created a new dummy calculator with an empty form type as a configuration type:

<img width="617" alt="Zrzut ekranu 2022-07-13 o 16 10 37" src="https://user-images.githubusercontent.com/6212718/178754726-bfbf6764-ca5d-41e8-84a8-afb4b5083012.png">

And changing from flat rate to dummy resulted in no error 🤔 

https://user-images.githubusercontent.com/6212718/178754829-d779e89e-c6a1-4c3e-b62c-16eeb0f17559.mov

Can you, please, check is it still an issue? Or maybe I've misunderstood you with something?

Thank you, for being part of the Community 🚀

**Comment by rimas-kudelis** [comment]
⁽ᴵ'ᵐ ⁿᵒᵗ ʷᵒʳᵏᶦⁿᵍ ʷᶦᵗʰ ˢʸˡᶦᵘˢ ᴬᵀᴹ⁾· If it works fine for you, feel free to close this ticket. Maybe you changed something after I reported it?

**Comment by NoResponseMate** [comment]
Hi @rimas-kudelis 

I've just rechecked to make sure, but indeed this issue does not seem to occur.

Cheers 🍻
