### ISSUE TITLE
[Bug] [API] Duplicated cart creation in new API

### ISSUE THREAD

**Issue by pptasinski-bitbag** [Sylius/Sylius#12606]
**Sylius version affected**: 1.9.2

**Description**  
As an logged in shop api user when i am picking up a new cart, more than one cart is created in database

**Steps to reproduce**  
1. Retrieve shop user token (authenticate)
2. Authorize to API (API platform) using shop user bearer token
3. Pick up new cart through API
4. Check database "sylius_order" table

**Possible Solution**  
Modify composite cart context to not use ShopBasedCartContext for api.

**Comment by athlonUA** [comment]
Hello guys! Any news how to fix this?

**Comment by TheMilek** [comment]
Hi!
I'm closing this issue at it seems to be no longer valid on Sylius 1.12 version 🚀 
cheers 🍻
