### ISSUE TITLE
Filters not working on shop/orders (with custom data provider)  Endpoint in the API V2

### ISSUE THREAD

**Issue by titi60** [Sylius/Sylius#12608]
**Sylius version affected**: 1.9.2

**Description**  

**Steps to reproduce**  
Use http://demo.sylius.com/api/v2/shop/authentication-token for the token with 

{
  "email": "shop@example.com",
  "password": "sylius"
}

and GET http://demo.sylius.com/api/v2/shop/orders to retrieve orders from the API.
The response give 2 orders.

GET  http://demo.sylius.com/api/v2/shop/orders?page=1&limit=1 
It return us 2 orders.

Filters like order are not working either.

need help 👯

**Comment by CoderMaggie** [comment]
Hi, @titi60 sorry for the late response. It has been fixed in the most recent releases:
![image](https://user-images.githubusercontent.com/13198869/178484712-96a4b34d-24d9-4509-9ac5-de76cae5771a.png)
