### ISSUE TITLE
Custom template is not loaded

### ISSUE THREAD

**Issue by Bartex77** [Sylius/Sylius#12636]
**Sylius version affected**: 1.9.3

**Description**  
I installed a fresh Sylius, created and switched on my custom theme, it's visible in the debug bar, but no changes take effect and the CSS is loaded from the default "shop" theme.

**Steps to reproduce**  
Simply follow the steps described in the docs:
1) https://docs.sylius.com/en/1.9/getting-started-with-sylius/installation.html
2) https://docs.sylius.com/en/1.9/book/themes/themes.html
3) Set the new theme for the default channel
4) Try to change anything in any twig the templates folder
5) Clear cache

Nothing happens. In the page source there is still link rel="stylesheet" href="/assets/shop/css/style.css", while in the bottom bar there is a title of the custom theme as set. Changing twigs in the vendors makes the effect. Tested in a few different environments. 

**Possible Solution**  
No idea at the moment. Maybe it's about the docs? In Sylius 1.8 it worked.

![2021-05-14_10-49](https://user-images.githubusercontent.com/3829375/118246327-1c740800-b4a2-11eb-9c37-20206dbca5e5.png)
![2021-05-14_10-48](https://user-images.githubusercontent.com/3829375/118246330-1d0c9e80-b4a2-11eb-959c-298f7080978b.png)

**Comment by frezelth** [comment]
I had the same problem, I had to change the theme structure following: [https://github.com/Sylius/SyliusThemeBundle/blob/master/UPGRADE.md](https://github.com/Sylius/SyliusThemeBundle/blob/master/UPGRADE.md)
Then it worked!

**Comment by NoResponseMate** [comment]
Hi @Bartex77 

Sorry for the late response, the docs have been updated somewhere on the way and now include also the new directory structure.
You can find them [here](https://docs.sylius.com/en/1.12/book/themes/themes.html).

Cheers :beers:
