### ISSUE TITLE
Can't remove product from cart when out of stock

### ISSUE THREAD

**Issue by mateusz-kolecki-vsf** [Sylius/Sylius#12635]
**Sylius version affected**: 1.8.8

**Description**  
Cant remove the product from the cart when there is not sufficient stock for that product.

**Steps to reproduce**  
* Customer A: put a product with low stock into a cart
* Customer B: buy that product in a separate session -> stock goes to zero
* Customer A: try to remove the product from the cart

Result: Customer A sees an error message and the product is still in the cart. The product can be removed from the cart only when stock is sufficient.

![image](https://user-images.githubusercontent.com/84175424/118242043-29dac380-b49d-11eb-8b22-205aa186734a.png)

**Possible Solution**  
_none_

**Comment by victor-v-bv** [comment]
Couldn't reproduce on 1.9.0 (https://demo.sylius.com/ ) or 1.10.0-DEV (https://master.demo.sylius.com/).
Can you reproduce it with a clean installation of 1.8.8?
It's just to make sure it's not some custom code that's causing this.

**Comment by mateusz-kolecki-vsf** [comment]
Ok, our mistake. After trying with a fresh setup it looks like it was related to one of the plugins we installed. The issue can be closed. Sorry for the hassle.

**Comment by vvasiloi** [comment]
Is it a community plugin?
