### ISSUE TITLE
Algorithm "argon2i" is not available. Either use "auto" or upgrade to PHP 7.2+ instead.

### ISSUE THREAD

**Issue by 0mars** [Sylius/Sylius#12662]
**Sylius version affected**: 1.x.y

**Description**  
Getting an error missing algorithm, and the problem is that it's asking for PHP 7.2+ while I do have PHP 7.3.24

**Steps to reproduce**  
```
COMPOSER_MEMORY_LIMIT=-1 composer create-project sylius/sylius-standard xxxxxxxx
```

actual result:
```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In SecurityExtension.php line 705:
!!
!!    Algorithm "argon2i" is not available. Either use "auto" or upgrade to PHP 7
!!    .2+ instead.
!!
!!
!!
Script @auto-scripts was called via post-install-cmd
```

**Comment by chalasr** [comment]
Looks like argon2i is not available on your platform, which is pretty rare in a PHP 7.3 setup though.
Using `native`, `auto` or `bcrypt`  as hashing algorithm instead of `argon2i` is fine to fix that.
Also, as of Symfony 5.3, the default algorithm has been changed back to bcrypt (check https://github.com/symfony/symfony/pull/40176 for the rationale).

**Comment by djeraseit** [comment]
Same issue on Centos 8

PHP 7.4.21 (cli) (built: Jun 29 2021 15:17:15) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

What is the solution to proceed with the install?

**Comment by djeraseit** [comment]
[](https://serverfault.com/questions/1011310/how-to-enable-argon2-for-php-from-centos-software-collections)

Seems like libargon2 is not available in RHEL / CentOS

**Comment by chalasr** [comment]
https://stackoverflow.com/a/58181153/4363634 might help.

**Comment by djeraseit** [comment]
@chalasr That worked perfectly. Thank you!

**Comment by coldic3** [comment]
Hi all, I guess it can be closed :dancer:
