### ISSUE TITLE
Doctrine Error on Installation

### ISSUE THREAD

**Issue by damienmoulin** [Sylius/Sylius#12685]
**Sylius version affected**: 1.9.1
**PHP Version: 7.4
**Description**  
When runing `composer create-project sylius/sylius-standard acme`
I encounter an error on **cache:clear** after dependencies installation :
`Either explicitly define entity managers in all doctrine-bundle configuration files, or in none of them`

**Comment by jzawadzki** [comment]
encountered same issue today
Reasons:
1) composer.lock in .gitignore... (sic!) https://github.com/Sylius/Sylius-Standard/pull/505
2) https://github.com/doctrine/DoctrineBundle/commit/759018e82e73f4c03d7108b6b609ccd47a3b3ad9

**Comment by GSadee** [comment]
I guess that this PR: https://github.com/Sylius/Sylius-Standard/pull/567 should fix the problem with Doctrine during installation. 
@damienmoulin you can apply changes from the above PR to your project to fix the problem.

**Comment by damienmoulin** [comment]
Perfect it's working, Thanks.

**Comment by pakidaxed** [comment]
same problem today
