### ISSUE TITLE
Unused ShipmentUnitTransitions

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#12705]
**Sylius version affected**: 1.7

**Description**  
Looks like `ShipmentUnitTransitions` and `sylius_shipment_unit` graph never used.

**Possible Solution**  
Remove that from Shipping component

**Comment by SirDomin** [comment]
Hey, we cant really remove it atm as it would be a BC. We could deprecate it, feel free to create pull request :)

**Comment by lchrusciel** [comment]
Will be fixed by #13500
