### ISSUE TITLE
placehold.it certificate expired

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#12754]
**Sylius version affected**: all?

```
curl --head https://placehold.it/50x50
curl: (60) SSL certificate problem: certificate has expired
```

At several templates in Sylius as a backup a placeholder image from `placehold.it` is loaded. But, visiting the website I'm redirected to https://placeholder.com/. The images itself don't work anymore and return a certificate error.

**Comment by SirDomin** [comment]
@stefandoorn i created a product with placeholder image and all seems to be fine. This may be a problem of your server settings? If you still have that problem with loading placeholders, you can download them and use links directly to your server.
![image](https://user-images.githubusercontent.com/22825722/149929608-57b6ad3d-9696-4982-9293-e0f202b475dc.png)

**Comment by stefandoorn** [comment]
I guess it was a temporary problem (they announced switching over) but I guess too many complaints and then a switchback :-)

**Comment by GSadee** [comment]
It seems that the problem has been resolved by this PR: https://github.com/Sylius/Sylius/pull/13750 as we've removed the usage of placeholders from the external page in favour of our own placeholders.
