### ISSUE TITLE
Sylius Theme System Does Not Work

### ISSUE THREAD

**Issue by tugrulgencoglu** [Sylius/Sylius#12783]
**Sylius version affected**: 1.10 (latest)

**Description**  
I am following the documentation ( https://docs.sylius.com/en/latest/book/themes/themes.html ) and i am doing exactly same things. The theme appears in dashboard and debug bar. But nothing override.

**Note**
I am not sure if this issue could be in this repo or SyliusThemeBundle repo. Because of i am not sure if it's related with integration or themeBundle itself and i am not sure how to check it  i decided to post this issue here.

I've seen this issue https://github.com/Sylius/Sylius/issues/12636 but it won't help me a lot. 

**Steps to reproduce**  
* Fresh install with following https://docs.sylius.com/en/latest/book/index.html#installation
* Create theme with using structure  ```themes/CrimsonTheme/templates/bundle/SyliusShopBundle/login.html.twig``` and following https://docs.sylius.com/en/latest/book/themes/themes.html
* Change something on login.html.twig
* Select and save the theme on dashboard
* Clear cache
* Check the login page, nothing changes except for the debug bar

**Possible Solution**  
I also tried old directory structure and this repo: https://github.com/Sylius/ThemeSkeleton
Maybe there is something can be missing on documentation. I believe the given directory structure is incorrect. As a suggestion the ThemeSkeleton repo can be updated for new theme directory structure.

Quick Fix (Not a good solution): Use ThemeSkeleton repo and old directory structure and add following lines to this file ```config/packages/sylius_theme.yaml```

```
sylius_theme:
    legacy_mode: true
 ```

Look for more: https://github.com/Sylius/SyliusThemeBundle/blob/master/UPGRADE.md

**Comment by vvasiloi** [comment]
It's `bundles` not `bundle`.

**Comment by tugrulgencoglu** [comment]
Thanks a lot that's work. I am going to PR asap to documentation.
