### ISSUE TITLE
Changing the quantity of a product that doesn't have enough stock causes the totals to be still recalculated

### ISSUE THREAD

**Issue by MacBim** [Sylius/Sylius#12787]
**Sylius version affected**: 1.9

**Description**  
When in the cart summary, updating the quantity of a product (that is tracked and has only 2 in stock) to 3 causes the total to be recalculated as if 3 products were available, and the quantity updated in the Order entity itself, despite having the error message saying "X product is out of stock".
The quantity inputs also keep the non-valid submitted quantity.

This bug appears to be visual only.

**Steps to reproduce**  
1. Set a product to be tracked, and set it's quantity to any number, other than 0 
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/11718596/124601733-796bb900-de68-11eb-9f5b-444e12451f16.png">
2. Add this product to your cart 
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/11718596/124601820-90121000-de68-11eb-8966-5d030470ae29.png">
3. In the cart summary, update the quantity of this product to a number greater than the available quantity
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/11718596/124601888-a0c28600-de68-11eb-80c5-388c655d7707.png">

**Possible Solution**  
- The availability check should be done before calling the OrderItemModifier->modify(...) in the OrderItemQuantityDataMapper->mapFormsToData(...)
- The Order entity should be reset with it's "pre update" quantities when there's not enough stock available during the quantity update

A current workaround we've found is to clear the changes on the Order entity off the doctrine memory, then fetching a un-modified Order entity

in App/../OrderController, just before the return of the saveAction function :
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/11718596/124603830-a15c1c00-de6a-11eb-89d8-96b697da485b.png">

**Comment by MacBim** [comment]
Any update on this issue ?

Thanks

**Comment by Rafikooo** [comment]
Hello @MacBim,

thank you for reporting the issue. We inform you that this has already been fixed [here](https://github.com/Sylius/Sylius/pull/14865) 💃 

Best regards,
Rafał
