### ISSUE TITLE
ApiBundle requires API Platform to have Swagger enabled

### ISSUE THREAD

**Issue by mbabker** [Sylius/Sylius#12832]
**Sylius version affected**: 1.10.0

**Description**  
If you disable API Platform's Swagger integration (or, as in my case, the documentation as a whole; we just aren't using the API and there's no reason to expose the docs for it in any way), it does not load a handful of services.  The ApiBundle unconditionally registers a number of services that depend on ApiPlatformBundle parameters or decorate services that do not exist when Swagger is disabled, leading to an error along the lines of these:

```sh
The service "sylius.api.swagger_admin_authentication_documentation_normalizer" has a dependency on a non-existent service "api_platform.swagger.normalizer.documentation".
```

```sh
You have requested a non-existent parameter "api_platform.enable_swagger_ui". Did you mean one of these: "api_platform.enable_entrypoint", "api_platform.enable_docs"?  
 ```

**Steps to reproduce**  
- Install Sylius 1.10 with ApiBundle enabled
- Add the following to `config/packages/api_platform.yaml`

```yaml
api_platform:
    enable_swagger: false
    enable_swagger_ui: false
    enable_re_doc: false
    enable_entrypoint: false
    enable_docs: false
```

- Try to build the container

**Possible Solution**  
Can't say I have one offhand, there isn't anything from the ApiPlatformBundle which exposes the `enable_swagger` key in a way that other container extensions could use without re-parsing the configuration, and that is the config node that will cause the most problems here (there is the `api_platform.enable_swagger_ui` and `api_platform.enable_re_doc` parameters, but those are only set when `enable_swagger: true`).

For now, my workaround is a compiler pass removing these services defined in the ApiBundle:

- api_platform.swagger.action.ui (overrides the service defined by ApiPlatformBundle)
- sylius.api.swagger_admin_authentication_documentation_normalizer
- sylius.api.swagger_shop_authentication_documentation_normalizer
- sylius.api.swagger_product_documentation_normalizer
- sylius.api.swagger_product_variant_documentation_normalizer

**Comment by devfive** [comment]
@mbabker thanks, this worked for us!

**Comment by coldic3** [comment]
Hi @mbabker, thanks for rising this issue – it should be fixed now :dancer:
