### ISSUE TITLE
OrderShipmentProcessor: ShippingMethod eligibility is checked before new/missing ShipmentUnits are added to the Shipment

### ISSUE THREAD

**Issue by leflings** [Sylius/Sylius#12835]
**Sylius version affected**: 1.9 (but probably all the way back to 1.2? [faulty commit](https://github.com/Sylius/Sylius/commit/c1d8763b48948e7c49e381ce6ba57c2a06feaf0e))

**Description**  
When adding a new OrderItem to an order that already has a shipment, the eligibility of the selected shipping method is checked before before the new OrderItem is added as a ShipmentUnit to the shipment. Therefore the eligibility check will happen on the Shipment, where the ShipmentUnits won't contain the new OrderItem and thus won't correctly "invalidate" a shipping method whose conditions no longer apply.

See [these lines](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/OrderProcessing/OrderShipmentProcessor.php#L65-L75):
```php
        if ($order->hasShipments()) {
            $shipment = $this->getExistingShipmentWithProperMethod($order);

            if (null === $shipment) {
                return;
            }

            $this->processShipmentUnits($order, $shipment);

            return;
        }
```

**Possible Solution**  
A solution would be to fetch the shipment directly via `$order->getShipments->first()` (as is done in `getExistingShipmentWithProperMethod`), call `processShipmentUnits` and then call `getExistingShipmentWithProperMethod` (I guess the name should be changed, since its purpose is no longer to get a shipment, but rather to _just_ ensure that the shipment has a valid shipping method)

**Comment by lchrusciel** [comment]
Hey @leflings,

pointed lines for sure may lead to unexpected behaviors. We almost for sure, should process new shipment again. Yet, it will not resolve the problem entirely, as there is no logic to break the app/create a second shipment if something cannot be delivered in one shot. Still, I'm open to the contribution to fix it. I would either remove the shipment from the fault order entirely or introduce the concept of the creation of a second shipment. The second solution would be much harder to implement, cuz we need to allow developers to configure a split strategy. Nonetheless, we should ask @CoderMaggie what would be the best approach here.

**Comment by jakubtobiasz** [comment]
Hello @leflings 👋🏼!
If I understand correctly your issue, it seems to no longer exist. I achieved to create an order with shipment not meeting the requirements (I increased the total of the cart in the separate cart), and I got the following error once I tried to place the order
![CleanShot 2023-07-17 at 10 40 18](https://github.com/Sylius/Sylius/assets/80641364/5b81f6eb-d229-4c97-9a66-47c34c6d108f)

I'm closing this issue, but if you find your issue still appear, just let me know, I'll reopen it :).
