### ISSUE TITLE
API V2 get_item calls leads to 404 not found error since 1.10.* upgrade

### ISSUE THREAD

**Issue by titi60** [Sylius/Sylius#12857]
**Sylius version affected**: 1.10.* / dev-master

**Description**  
get_item on /api/v2/**/{code} leads to 404 not found error

**Steps to reproduce**  
Upgrade from 1.9 to 1.10

**Possible Solution**  

Comment ChannelAwareItemDataProvider service definition in 
Sylius/Bundle/ApiBundle/Resources/config/services.xml
``

**Comment by stloyd** [comment]
Be sure to re-enable API after update as there is BC break disabling it by default:
```
# config/packages/_sylius.yaml
sylius_api:
    enabled: true
```
https://github.com/Sylius/Sylius/blob/master/UPGRADE-1.9.md#upgrade-from-v195-to-v196

**Comment by titi60** [comment]
@stloyd yes, I followed the every upgrade instructions, and the other endpoints like get_collection(list) are working as expected. We only get this error when the API use ItemDataProvider class (get_item)

**Comment by titi60** [comment]
I've found the solution. At Bundles declaration /config/bundles.php
`ApiPlatform\Core\Bridge\Symfony\Bundle\ApiPlatformBundle::class => ['all' => true]`
should be added before 
`ApiPlatform\Core\Bridge\Symfony\Bundle\ApiPlatformBundle::class => ['all' => true]`

This little trick should fix the issue
