### ISSUE TITLE
Themes don't work in Sylius on Docker

### ISSUE THREAD

**Issue by GrzegorzKaczor** [Sylius/Sylius#12864]
Hello community,

I have a problem. I have created new theme act on in instruction in documentation how do it. And I can't select this theme in my Sylius instance running on docker.
I tried install asserts and theme on docker. I cleaned php cache too. 
Does anyone have the same problem?

**Comment by Ferror** [comment]
Hi @GrzegorzKaczor it's been some time and the current Docker in Sylius-Standard looks a little bit different. Let me know if it is still an issue
