### ISSUE TITLE
Payment zone restrictions

### ISSUE THREAD

**Issue by marcoooo** [Sylius/Sylius#1288]
Hi, I will soon need a feature on payment, i.e restrict a payment method to a shipping zone / country. In my case should result in "You cans pay by cheque only if your bank account is in my country".
I am about to develop it, but first want to know if it's not already made somewhere ?

Thanxs

**Comment by kielabokkie** [comment]
Hi @pjedrzejewski, sorry to dig up an old ticket but I'm looking to setup something like this and I'm just wondering if this is possible now? I'm on v0.18 at the moment.

**Comment by pjedrzejewski** [comment]
@kielabokkie I'd suggest using a channel for that. Or modifying the payment methods resolver, should be pretty straightforward. Have a look how shipping methods are handled. :)

**Comment by hornofj** [comment]
@marcoooo I think this is exactly what you need https://github.com/mangoweb-sylius/SyliusPaymentRestrictionsPlugin
