### ISSUE TITLE
`yarn install` fails with error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?

### ISSUE THREAD

**Issue by honigkuchenbaer** [Sylius/Sylius#12893]
**Sylius version affected**: 1.10

**Description**  

When I follow the installation instructions for installing Sylius 1.10 on a brand new Mac, a compilation error happens while `yarn install`.

**Steps to reproduce**  

```
composer create-project sylius/sylius-standard acme
cd acme
# prepare database connection URL into .env properly
php bin/console sylius:install
yarn install
```

gives:

```
In file included from ../src/binding.cpp:1:
In file included from ../../nan/nan.h:58:
In file included from ~/.node-gyp/16.6.1/include/node/node.h:63:
In file included from ~/.node-gyp/16.6.1/include/node/v8.h:30:
~/.node-gyp/16.6.1/include/node/v8-internal.h:488:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:776:50: note: 'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
1 error generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/private/tmp/acme/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 20.5.0
gyp ERR! command "/opt/homebrew/Cellar/node/16.6.1/bin/node" "/private/tmp/acme/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /private/tmp/acme/node_modules/node-sass
gyp ERR! node -v v16.6.1
gyp ERR! node-gyp -v v3.8.0
```

Versions:

Mac: MacBook Pro 2021 M1
MacOS:  BigSur 11.4
Node: v16.6.1
PHP:  8.0.9
Composer: 2.1.5
XCode: 12.5.1

**Possible Solution**  

could not find any. But I found out, that the node-sass dependencies are outdated for years.

`sass-loader` is versioned with 7, but the current version is 12.
`gulp-sass` is tagged with 4.0.1, but the current version is 5.0.0

However, updating the gulp-sass did not solve the issue in my tests. On Stackoverflow I found many hints, that gulp-sass is outdated and should be replaced with `gulp-dart-sass`. Maybe this could be a solution?

**Comment by itinance** [comment]
I stumbled upon the same issue. Sass implementation in Sylius seems to be little outdated as you already pointed out.

Indeed, to install `gulp-dart-sass` fixes the issue, but still need some manual patches:

First:
  
```
yarn add gulp-sass@5.0.0
yarn add gulp-dart-sass@^1.0.2
```

`yarn install` will work with these deps properly.

However, `yarn run gulp` (or `gulp build`)  will run into a new issue stating that 

> gulp-sass 5 does not have a default Sass compiler; please set one yourself.
> Both the `sass` and `node-sass` packages are permitted.

We need to fix the following line from 

`import sass from 'gulp-sass';`

to

`var sass = require('gulp-sass')(require('sass'));`

in the following files:

- vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/gulpfile.babel.js
- vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/gulpfile.babel.js

Please note that after deleting the vendor directory and reinstalling, all the above steps must be performed again.

**Comment by Nek-** [comment]
I'm not sure `gulp-dart-sass` is required. `sass` package is enough (it stands as the replacement for `node-sass`).

The changes required for the upgrade to gulp-sass 5.x are described here : https://github.com/dlmanning/gulp-sass/tree/master#migrating-to-version-5

And this seems to be fine:

```diff
- import sass from 'gulp-sass';
+ import gulpSass from 'gulp-sass';
+ import realSass from 'sass';
+ const sass = gulpSass(realSass);
```

**Comment by coldic3** [comment]
Hi @honigkuchenbaer, thanks for the issue. We recommend using webpack since Sylius 1.11 and it is used by default since 1.12. Therefore I'm closing it :woman_dancing:
