### ISSUE TITLE
[Feature Request] Shop Product Import 

### ISSUE THREAD

**Issue by doertedev** [Sylius/Sylius#1290]
OHAI.

One of our clients whants a webshop which can programmagically import products, images, prices, descriptions etc from his existing Ebay and Amazon store.

See: https://twitter.com/pjedrzejewski/status/448861242917408768

**Comment by michalmarcinkowski** [comment]
Duplicate of https://github.com/Sylius/Sylius/issues/2242

**Comment by lsmith77** [comment]
still a work in progress but hopefully soon this will be full featured: https://github.com/FriendsOfSylius/SyliusImportExportPlugin
