### ISSUE TITLE
Validation not taken into account in promotion configuration forms

### ISSUE THREAD

**Issue by bburnichon** [Sylius/Sylius#1295]
As validation_groups is set to ```sylius``` by default, Symfony's Form Component does not validate any of the Constraints set in Forms.

This is a big issue for configuration of promotions which have no underlying object to validate. Only an array.

On a fresh install of Sylius, I just added GreaterThan in ItemCountConfigurationType.

```php
->add('count', 'integer', array(
    'label' => 'sylius.form.rule.item_count_configuration.count',
    'constraints' => array(
        new NotBlank(),
        new Type(array('type' => 'numeric')),
        new GreaterThan(array('value' => 0)),
   )
))
```

I could saved a -1 value in the item_count_configuration of New Year Promotion

**Comment by umpirsky** [comment]
@pjedrzejewski I am interested into fixing this issue. Any directions?

**Comment by michalmarcinkowski** [comment]
@umpirsky According to docs (http://symfony.com/doc/current/book/forms.html#adding-validation), you can just add validation groups to constraint like this:
```php
new NotBlank(array('groups' => array('sylius'))
```

Tell me if it works :)

**Comment by umpirsky** [comment]
@michalmarcinkowski This did the trick, thanks!

But, why it does not work with:

```php
class MyConfigurationType extends AbstractType
{
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver
            ->setDefaults(array(
                'validation_groups' => ['sylius'],
            ))
        ;
    }
}
```

**Comment by michalmarcinkowski** [comment]
@umpirsky Not sure what are you asking.
 
If the form is embedded I suppose it may be connected with cascade validation (http://symfony.com/doc/current/reference/forms/types/form.html#cascade-validation)

Is that your case?

**Comment by umpirsky** [comment]
@michalmarcinkowski Yes, but that is the case with all rule checker config types. They are embedded by default.
