### ISSUE TITLE
Guest checkout for registered users

### ISSUE THREAD

**Issue by nickvanderzwet** [Sylius/Sylius#12965]
**Sylius version affected**: v1.10.0

**Description**  

For the new api (v2) it's not possible to get an order by its tokenValue if the customer of that particular order is attached to a shopUser and the user is not logged in. So guest checkouts are not possible for already registered email addresses.

**Steps to reproduce**  

- Create a new shopping cart (as a guest) with some example items and in the addressing step add an already registered user. 
- Try to get the order by it's generated token

```
curl -X 'GET' \
  'https://localhost:8000/api/v2/shop/orders/-FxtSVSSaW' \
  -H 'accept: application/ld+json'
```

- The Api will respond with a 404 error
- Find the shopUser for this order and remove the link to the customer
- Repeat the step of retrieving the order by it's token and you will get the correct order

**Possible Solution**  
It seems like there is an extra JWT check if the order belongs to a shopuser? Is this really necessary for these kind of shop endpoints? Should a tokenValue not be enough?

Update:
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/OrderGetMethodItemExtension.php#L66 & https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/OrderMethodsItemExtension.php#L81

Why is there a visitor check?

**Comment by lchrusciel** [comment]
Hey Nick,

thanks for raising the question. We made this decision on purpose, to increase the safety of users. Once you have an account, we didn't want to expose the details of your order data(even tho it is behind a random token). For now, we are not planning to change this behavior. In case you need it, overriding both mentioned classes by you should resolve your issue.
