### ISSUE TITLE
Wrong usage of repository in Version20161209095131 migration in CoreBundle

### ISSUE THREAD

**Issue by pptasinski-bitbag** [Sylius/Sylius#12985]
**Sylius version affected**: 

1.8.*
1.9.*
1.10.*

**Description**  

Migration Sylius\Bundle\CoreBundle\Migrations\Version20161209095131 uses repository instead of raw sql queries.

This causes that above migration will fail after adding new field to Zone entity.

**Steps to reproduce**  

For example, install project, modify Zone entity (add new field), run migrations.

**Possible Solution**  

Use raw SQL queries in migrations.

**Comment by GSadee** [comment]
I'm closing the issue as it has been fixed by #13187
