### ISSUE TITLE
Associations in admin product form seams not working

### ISSUE THREAD

**Issue by gaetanbuellet** [Sylius/Sylius#13000]
**Sylius version affected**: 1.10

**Description**  
On the product admin panel, on the Associations tab, the select box don't show products
The ajax route called is 
`admin/ajax/products/?limit=20&criteria%5Bsearch%5D%5Btype%5D=contains&criteria%5Bsearch%5D%5Bvalue%5D=&_=1629802288056`

and the error behind is 
```
{
    code: 500,
    message: "Unable to generate a URL for the named route "sylius_admin_api_product_option_show" as such route does not exist."
}
```
**Steps to reproduce**  
- Go to Catalog > Products > Edit a product > Associations 
- Try to select a product

**Comment by gaetanbuellet** [comment]
Just test it again : doesn't works on sylius 1.10 but seems working on the next release (1.11.0)

**Comment by ernestWarwas** [comment]
Hi @gaetanbuellet, thanks for the issue but it seems to work fine so I close the issue 💃
