### ISSUE TITLE
Distinct Validation Groups in Create / Update...

### ISSUE THREAD

**Issue by pdias** [Sylius/Sylius#1301]
Hello,

I'm using **SyliusResourceBundle** and want to know if there is some configuration that allows to use distinct validation groups
For example:
- using validation group **"new"** in form created in the create route
- validation group **"edit"** in the form for the update route)

If I override the **getForm** method i can do it... but if it exists way to do so by configuring it might be better.

```
class CountryController extends ResourceController
{
    /**
     * @param object|null $resource
     *
     * @return FormInterface
     */
    public function getForm($resource = null)
    {
        if(null === $resource->getId()) {
            return $this->createForm(
                $this->config->getFormType(), 
                $resource, 
                array('validation_groups'=>array('new')));
        } else {
            return $this->createForm(
                $this->config->getFormType(), 
                $resource, 
                array('validation_groups'=>array('edit')));
        }
    }
}
```

Thanks,

Paulo

**Comment by pjedrzejewski** [comment]
You can now configure it as a form option via ``_sylius`` routing.

http://docs.sylius.org/en/latest/bundles/SyliusResourceBundle/create_resource.html#passing-custom-options-to-form
