### ISSUE TITLE
Argument 1 passed to PriceHelper_2012e62::getPrice() must implement interface Sylius\Component\Core\Model\ProductVariantInterface, null given

### ISSUE THREAD

**Issue by Bharath8499** [Sylius/Sylius#13024]
**Argument 1 passed to PriceHelper_2012e62::getPrice() must implement interface Sylius\Component\Core\Model\ProductVariantInterface, null given, called in /var/www/html/sylius/bharath/WheelmodeNew/Wheelmode/var/cache/dev/twig/62/627f2d310a26a1c7539746f8de592ca8f3f31200d1d04e4c03269e486bab1ed2.php on line 216**

I am stucked here ,any one have any  idea about this ?

**Comment by CoderMaggie** [comment]
**Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our [Slack channel](http://sylius.org/slack) or [stackoverflow](https://stackoverflow.com/questions/tagged/sylius) ;)
