### ISSUE TITLE
Admin dashboards fails on test environment with SQLite database

### ISSUE THREAD

**Issue by davrodrila** [Sylius/Sylius#13051]
**Sylius version affected**: 1.9.6

**Description**  
I've upgraded Sylius from 1.7.11 to 1.96, and I have found an issue with my testing suite. I have a smoke test set up for the dashboard that just checks we're getting a 200 OK response, and since the 1.9.6 upgrade, that tests it's failing. I narrowed down my issue to the year, date and Months functions set up in Sylius/Bundle/CoreBundle/Doctrine/DQL, which are not capable of supporting SQLite, so thats why the test fails but the website with MySQL works correctly. 

This didn't happen before because the only extension was DATEFORMAT and it didn't throw an error, and since I have DoctrineExtensions enabled, it was automatically capable of providing a platform appropiate alternative to SQLite

**Steps to reproduce**  
Attempt to load the admin dashboard using an SQLite database. 

**Possible Solution**  
Would it be possible to use DATETIME as a default for either MONTH or YEAR, or perhaps give control back to other DQL extensions instead of throwing an error?  That way if we want to give support to other SQL solutions we can, right now I don't think there is a way to do that, aside from overriding the conflicting classes.

**Comment by lortuno** [comment]
@CoderMaggie I'm having the same issue with lastest version of sylius. I have my testing db as SQLite and there are admin sections I cannot functionally test due to this db restriction, which is in a final class, so I cannot even override the method. Is there any solution scheduled any time soon?

**Comment by everwhatever** [comment]
Hi @davrodrila 
We don't support SQLite, but if you have solution you can open PR with fix

**Comment by ebuildy** [comment]
hello, 

I have just did a small PR to support SQLite, just a few files to edit, then it works.

https://github.com/Sylius/Sylius/pull/17254
