### ISSUE TITLE
Unable to remove image from ProductVariant programmatically

### ISSUE THREAD

**Issue by bellu** [Sylius/Sylius#13095]
**Sylius version affected**: 1.10.0

**Description**  
I'm trying to remove some Image from a product variant from a console command.
I got no errors, but the image is still there in the backend.

**Steps to reproduce**  

```
$imagesType = $productVariant->getImagesByType($order);

if(count($imagesType)) {
    $output->writeln(["Removing old image $order"]);

    /** @var ProductImage $imageToRemove */
    foreach ($imagesType as $imageToRemove) {
        $product = $productVariant->getProduct();

        $productVariant->removeImage($imageToRemove);

        $this->productVariantRepository->add($productVariant);
        $this->productRepository->add($product);

    }
}
```

**Comment by stloyd** [comment]
This is not bug, it's support question & you should use either Discussions or Slack channel.

If the code above is exactly what you have then you didn't call removal on entity manager.

```php
$this->entityManager->remove($imageToRemove);
```

That should be placed in that loop and after loop you should do `flush()` on entity manager.

**Comment by bellu** [comment]
Sorry @stloyd for using the wrong channel.
Now it's working fine, even if i didn't understand why for adding i didn't need to use the entityManager directly.

**Comment by mbabker** [comment]
> Now it's working fine, even if i didn't understand why for adding i didn't need to use the entityManager directly.

`$productVariant->removeImage($oldImage)` is only going to remove the relation between the variant and an image (in SQL it's basically `DELETE FROM sylius_product_image_product_variants WHERE image_id = ? AND variant_id = ?` which is only updating the mapping table for the variant and images relationship), that's not going to delete the image from the database on its own and to do that you have to manually call `$em->remove($oldImage)`.  With the way Doctrine relationships are configured, a `$productVariant->addImage($newImage)` call will cascade and add the image to the database if it isn't already there.

**Comment by bellu** [comment]
Thanks @mbabker for the clarification.
