### ISSUE TITLE
[API] ProductVariantNormalizer doesn't handle channel not found exception

### ISSUE THREAD

**Issue by vvasiloi** [Sylius/Sylius#13099]
**Sylius version affected**: 1.11

**Description**  
In https://github.com/Sylius/Sylius/pull/13035 the call to the channel context was moved outside the try-catch block, so the exception is not caught anymore:
https://github.com/Sylius/Sylius/blob/e602281396c5c17939102169283ba1c1ecb6a324/src/Sylius/Bundle/ApiBundle/Serializer/ProductVariantNormalizer.php#L67-L75

Also, the calculator throws `Sylius\Component\Core\Exception\MissingChannelConfigurationException, so maybe that's the exception that should be caught there.

Right now neither exception is caught.

**Comment by timching** [comment]
Hi, I saw this issue when I am working on some pricing-related features.
maybe also need to catch the `Sylius\Component\Core\Exception\MissingChannelConfigurationException` as you said.

but anyone knows is there any reason why we are only catching the `ChannelNotFoundException` exception?
