### ISSUE TITLE
Removing last item should always clear cart

### ISSUE THREAD

**Issue by boskee** [Sylius/Sylius#1310]
When removing last item from the cart, it should be cleared of the shipping cost.

How to reproduce:

1. Start with an empty cart
2. Add an item
3. Proceed to checkout
4. Enter your personal details
5. Select shipping method
6. Go back to cart and click the delete button next to an item
7. Your cart will be emptied, but shipping costs will remain visible in the header. For example, if you select DHL shipping method (from fixtures), you will see the following: "View cart (0) €23.50"

This behaviour doesn't exist if you click "Clear cart" instead of the delete button.

**Comment by michalmarcinkowski** [comment]
Fixed.

**Comment by okwinza** [comment]
@michalmarcinkowski has this been fixed recently or is it just one of many forgotten tickets from the past?

**Comment by michalmarcinkowski** [comment]
@okwinza it was fixed in https://github.com/Sylius/Sylius/pull/5845 ;)
