### ISSUE TITLE
Incoherent total price in OrderTotalRuleChecker

### ISSUE THREAD

**Issue by mdevlamynck** [Sylius/Sylius#13123]
**Sylius version affected**: 1.8, 1.9, 1.0

**Description**  
The rules `OrderTotalGreaterThanOrEqualRuleChecker` and `OrderTotalGreaterThanOrEqualRuleChecker` use the order total to check if a shipping method is available. Depending on when the rule is called, the total can be different for the same cart. For example:

* When computing the list of shipping method for the checkout form the price is the complete total (products + shipping + taxes + promotions).
* During the order processing steps, the price is the total without the adjustements (only products without taxes) since it runs just after OrderAdjustementsClearer.

It results in incoherent shipping method throughout the checkout.

**Steps to reproduce**  
1. Create one shipping method A available if total is bellow 100 with a price of 10.
1. Create a second shipping method B available if total is above 100.
1. Create a cart where items total is bellow 100 but above 91, default shipping method should therefore be A.
1. On the shipping method selection form, only shipping method B is available (items total + estimated shipping cost of A > 100). Only A should be available in this form.

**Possible Solution**  
User `$order->getItemsTotal()` instead of `$order->getTotal()`.

I'm not sure if only products should contribute to the shipping method rule checker. Maybe taxes and promotion should contribute too. But at least shipping method cost should not contribute to shipping method rule checker.

Maybe also update the priority of the steps of order processors to recompute products price and taxes before selecting the shipping method as mentioned in https://github.com/Sylius/Sylius/issues/12554.

**Comment by loevgaard** [comment]
Yes, this is a known problem and I am afraid I was the one who didn't think about this in time :( The solution is to create your own rule checker, i.e. `OrderItemsTotalGreaterThanOrEqualRuleChecker`.

Would be great with a PR ❤️

**Comment by mdevlamynck** [comment]
@loevgaard Done :)

**Comment by Snowbaha** [comment]
I have the same issue, I spent to many hours to search the origin and i have the same result.
All my searches in french on the slack :  
https://app.slack.com/client/T3EQ9BVL2/CBP79GKJS/thread/CBP79GKJS-1636366512.078100
