### ISSUE TITLE
Overriding default xml or yml files

### ISSUE THREAD

**Issue by BaThor** [Sylius/Sylius#13127]
Hello,
how can I override, extend or add  xml files. For example in CoreBundle/Resources/config/services/checkout.xml, I want to add few arguments to one of service, also I want to create my own xml file inside /services. How can I do it? 
I was trying to recreate folder paths in app/Resources/SyliusCoreBundle/config/... but it did not work :/ 

I would be very grateful for your help.
Cheers

**Comment by Zales0123** [comment]
Hello @BaThor and welcome to the community! 🚀 **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our [Slack](http://sylius.com/slack) (preferred) or [forum](https://forum.sylius.com/) ;) We have a very active, developed community, I'm sure someone will be able to help you with your problem. Good luck 🖖
