### ISSUE TITLE
How can I set channel programmatically?

### ISSUE THREAD

**Issue by pawellen** [Sylius/Sylius#13139]
How can I set channel context programmatically?

**Comment by Zales0123** [comment]
Hello Paweł and welcome to the community! 🚀 **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our [Slack](http://sylius.com/slack) (preferred) or [forum](https://forum.sylius.com/) ;) We have a very active, developed community, I'm sure someone will be able to help you with your problem. Good luck :)

**Comment by pawellen** [comment]
Tried but I am getting this information on my email:

![obraz](https://user-images.githubusercontent.com/4718380/150092817-b0cb9ab0-0ed9-4004-9747-d8c7055eebd7.png)


:(

**Comment by vvasiloi** [comment]
@pawellen try a different email client. However, I will make an exception and answer you here.
To set a channel programmatically, you need to add a new channel context, which will have a way to set the current channel, like a `setChannel` method. You can then inject this particular context where you need to set the channel and use the method to do so. If you need additional help, please use the support channels.
