### ISSUE TITLE
Short locale notation altering search to zero-results.

### ISSUE THREAD

**Issue by oleg-andreyev** [Sylius/Sylius#13134]
**Sylius version affected**: 1.10.2

**Description**  
- Go to "Admin Panel"
- Go to "My Account"
- Change Language Preferences and select "English" and not "English (United States)" or something else.
- Save
- Got to "Products" in the admin panel
- Try to search by "name"
- Empty result

This is because all transactions are stored using full local notation en_US, lv_LV and etc.

```sql
SELECT
  DISTINCT id_4
FROM
  (
    SELECT
      DISTINCT id_4,
      code_0
    FROM
      (
        SELECT
          s0_.code AS code_0,
          s0_.created_at AS created_at_1,
          s0_.updated_at AS updated_at_2,
          s0_.enabled AS enabled_3,
          s0_.id AS id_4,
          s0_.variant_selection_method AS variant_selection_method_5,
          s0_.average_rating AS average_rating_6,
          s1_.name AS name_7,
          s1_.slug AS slug_8,
          s1_.description AS description_9,
          s1_.meta_keywords AS meta_keywords_10,
          s1_.meta_description AS meta_description_11,
          s1_.id AS id_12,
          s1_.short_description AS short_description_13,
          s1_.locale AS locale_14
        FROM
          sylius_product s0_
          INNER JOIN sylius_product_translation s1_ ON s0_.id = s1_.translatable_id
          AND (s1_.locale = ?)
        WHERE
          s0_.code LIKE '%white%'
          OR s1_.name LIKE '%white%'
      ) dctrn_result_inner
    ORDER BY
      code_0 ASC
  ) dctrn_result
LIMIT
  10
```

here `locale` argument is "en" not "en_US"

**Possible Solution**  
- Make sure that customer cannot select "short" (en, lv and etc.) locale in "Language Preferences"

**Comment by vvasiloi** [comment]
How about that: an admin should see all resources in all locales, regardless of the account language, which should be mostly used for translating the interface.

**Comment by diimpp** [comment]
This problem appeared through the app multiple times (ajax requests for autocomplete, taxon tree) and was solved by introducing search without specifying locale code.

I guess it's time for grid search filter fix now :)

Though my information may be out of date.
https://github.com/Sylius/Sylius/blob/1cb2981a4ccd89af9928822d8cc86547ed91f03c/src/Sylius/Bundle/AdminBundle/Resources/config/routing/ajax/product.yml#L21

**Comment by molabs** [comment]
I see it like @vvasiloi, the language in the backend shouldn't have any effect on the product list etc.

**Comment by coldic3** [comment]
Hi @oleg-andreyev, thanks for rising the issue. It has been fixed in https://github.com/Sylius/Sylius/issues/13296 :+1:
