### ISSUE TITLE
[RFC] Removing the sylius/theme-bundle from the admin package

### ISSUE THREAD

**Issue by mamazu** [Sylius/Sylius#13143]
**The proposal**
Removing the theming functionality for headless Sylius shops. The current move in Sylius is more and more towards a headless approach and making everything exposed via an API. This means that in the core of Sylius we don't need theming support. This is only needed for shops that have a front-end which is based on Sylius.

**Additional context**
The changes that needed to be made are quite minimal as there is little coupling between the theming system and the admin panel in the first place:
* [BC break] The channel doesn't have a `themeName` property if the shop package is not installed (or just leave it at null)
* This also means that the form and the template have to only have the `themeName` fields rendered when the shop is installed.

This also would speed up the application a little (since the theming bundle also has event listeners on kernel.request).

**Is it a good idea?** 
What do you think.

**Comment by Ferror** [comment]
This would be great for Sylius 2.0 <3
