### ISSUE TITLE
Performance: Usage of RequestStack::getMasterRequest has significant performance impact

### ISSUE THREAD

**Issue by leflings** [Sylius/Sylius#13149]
**Sylius version affected**: 1.9+

**Description**  
The continued usage of `RequestStack::getMasterRequest` in various places has significant performance impact when running on Symfony 5.

Below is a screenshot from a Blackfire profile from a production environment:

![get_master_request_profile](https://user-images.githubusercontent.com/658790/135063101-4fce1e9e-b7f2-4bc2-8b42-a3a5412449e0.PNG)

Here it is shown that `CachedPerRequestChannelContext::getChannel` ends up accounting for ~16% of the wall time for the request.

The large amount of calls into `getMasterRequest` (and subsequent calls to `trigger_deprecation` => `trigger_error`) ends up compounding into a significant chunk of time.

From my testing with various settings of `error_reporting`, and understanding of [this thread](https://stackoverflow.com/questions/1868874/does-php-run-faster-without-warnings), it is an unavoidable performance impact as it is.

**Possible Solution**  

I'm aware that as long as Sylius supports Symfony ^4.4 we have to call `getMasterRequest` as `getMainRequest` isn't added until Symfony 5.

Can we make these calls "symfony version aware" and use `getMainRequest` if available? Perhaps a shim?

**Comment by mbabker** [comment]
In general I'm 👍 on anything that reduces the deprecation count in a Sylius app.  Even with the current 1.10 build on Symfony 4.4, I find it hard to manage deprecations with over 170 of them being logged (and the vast majority coming from things like Sylius' Mailer and Resource bundles).

**Comment by everwhatever** [comment]
Hi @leflings 
This issue doesn't exist on 1.12 and we don't support 1.9 so I have to close the ticket
