### ISSUE TITLE
[API] Phone number and company name can not be added to the address via the endpoint PATCH ​/api​/v2​/shop​/orders​/{tokenValue}​/address

### ISSUE THREAD

**Issue by andrehoffmann30** [Sylius/Sylius#13176]
**Sylius version affected**: 1.10.2

**Description**  
When adding an Adresse to an Order the values for phone number and company name are not added to the address when using the endpoint PATCH ​/api​/v2​/shop​/orders​/{tokenValue}​/address

**Steps to reproduce**  

1. Create a cart via the api
2. Add a product via the api
3. Add the billing address data with phone number and company name via the endpoint PATCH /api​/v2​/shop​/orders​/{tokenValue}​/address
4. Check the address data in the database -> phone number and company name are empty

**Possible Solution**  

https://github.com/Sylius/Sylius/pull/13177

**Comment by coldic3** [comment]
Related PR already merged. Thank you @andrehoffmann30 👍️
