### ISSUE TITLE
One step checkout

### ISSUE THREAD

**Issue by freakpol** [Sylius/Sylius#13205]
I haven't seen all the issues here, and a quick search give me no result, so may be this was asked before.
Is there any plan to add support for one step checkout ?

**Comment by tsogoo** [comment]
There is a paid plugin.
https://store.sylius.com/products/onepagecheckoutplugin-by-bitbag

**Comment by GSadee** [comment]
Hello @freakpol, we are not planning to do that in the UI, but we would like to improve API to be able to perform checkout in any order.
