### ISSUE TITLE
Insert duplicate Customer on checkout for repeating guest customers.

### ISSUE THREAD

**Issue by acornforth** [Sylius/Sylius#13201]
**Sylius version affected**: 1.7 | 1.8 | 1.9 | 1.10

**Description**  
At checkout, repeat guest customers who enter their email address with a different spelling results in a 500 error due to attempting to insert duplicate record (email)

**Steps to reproduce**  
- Checkout as guest entering the email address with a single capital letter.
- Checkout as guest again with the same email, this time all lowercase.

**Possible Solution**  
Modify the Form Event Listeners on CustomerCheckoutGuestType and CustomerGuestType to look up customer by emailCanonical instead of email

**Comment by SirDomin** [comment]
Hey @acornforth I checked out your PR, added behat scenario and it will be merged as soon as its green 💃

**Comment by acornforth** [comment]
@SirDomin Amazing, thanks for that. any idea how long before it's included in a public release?

**Comment by SirDomin** [comment]
@acornforth i changed branch to 1.10, so probably with new release of 1.10+ versions it will be updated
