### ISSUE TITLE
OrderShipmentTaxesApplicator uses all adjustments

### ISSUE THREAD

**Issue by aleho** [Sylius/Sylius#13224]
**Sylius version affected**: 1.9+

**Description** 

OrderShipmentTaxesApplicator uses `$shipment->getAdjustmentsTotal()` instead of a sum of `SHIPPING_ADJUSTMENT` and `ORDER_SHIPPING_PROMOTION_ADJUSTMENT`. I don't think this is correct.

https://github.com/Sylius/Sylius/blob/dc9a42a66e04d55d555dcdac3698ded1ca112f61/src/Sylius/Component/Core/Taxation/Applicator/OrderShipmentTaxesApplicator.php#L64

**Steps to reproduce**  
1) Add any adjustment not meant for shipping to a shipment.
2) Observe OrderShipmentTaxesApplicator using the wrong sum.

**Possible Solution**  

Calculate shipping taxes from sum of shipping related costs as done in e.g. `ShippingPercentageDiscountPromotionActionCommand`).

**Comment by aleho** [comment]
I see this issue has been assigned.

Is there any comment or progress to report?

**Comment by jakubtobiasz** [comment]
Hello @aleho 👋🏼!
I was browsing the issues, and I've found out you closed the issue without any response from our side. Is your bug report is still valid? How did it happen your shipment had an adjustment not meant for shipping? Did you add it manually?

**Comment by aleho** [comment]
@jakubtobiasz Sorry, I cannot say whether this is still happening or not (we stopped using Sylius Plus after filing some critical bugs like these without ever getting feedback).

According to the steps I outlined above I'd say it can be easily verified in a test case.

**Comment by jakubtobiasz** [comment]
Hi @aleho, and thank you for your swift response. I'm sorry to hear that :/. I can only say we improved that area, and if you decide to use Sylius Plus once again, I can promise we'll do our best to answer to any reported issue.

It can be verified by following the steps you provided, but we don't understand the "Add any adjustment not meant for shipping to a shipment." part. We'd like to understand how did you achieve the state, when the shipment has adjustment not meant for shipping.

**Comment by aleho** [comment]
As far as I remember a shipment could have other adjustments, a discount, maybe `ORDER_PROMOTION_ADJUSTMENT`. I really don't remember the details.

I might also have been related to a custom promotion applicatior adding adjustments to the shipment instead of the order (we used to split orders by "vendors" and had to split shipments by vendors).
