### ISSUE TITLE
Replace knpGaufretteBundle with the FlySystemBundle to support all Cloud providers

### ISSUE THREAD

**Issue by zairigimad** [Sylius/Sylius#13233]
**Sylius docs version**: 1.x / latest

I think with FlysystemBundle in the Doc this will cover not only AWS but all the cloud providers that have Flysystem Adapters.
Also, the FlysystemBundle contains a lot of other features and is using async-aws and HttpClient from Symfony wich is good for performance.

**Description**
<!-- Describe what is missing or where exactly is the bug/typo/issue located. Links highly appreciated. --!>

**Comment by stloyd** [comment]
I would not close this RFC, IMHO it has quite a lot of sense due to fact that Fly is way better maintained than the Gaufrette.

Releases:
- gaufette: `0.7.9` in 2019,
- fly: `2.2` in 2022.

**Comment by vvasiloi** [comment]
Fair enough. We can probably easily provide a BC layer, since both libs have adapters for each other.

**Comment by coldic3** [comment]
Hey @zairigimad,

Flysystem will be a default one since Sylius 1.12. You can test it out on Sylius [1.12.0-ALPHA.1](https://github.com/Sylius/Sylius/releases/tag/v1.12.0-ALPHA.1) release 💃
