### ISSUE TITLE
Item count based promotions should rely on total item amount

### ISSUE THREAD

**Issue by boskee** [Sylius/Sylius#1324]
Promotions that are based on item count should either get the total amount of items or a new option should be added. At the moment "Item count == 2 (+ equal)" promotion only works when user adds two different items. 

"Item count" is too ambiguous. I expected it to check against total amount, not item amount. Real world example: Create an Item count based coupon (2 items, equal checked) and then:

1. Start with empty cart
2. Add product to your cart
3. Increase the amount to two/three.
4. Apply promo code
5. The following error is displayed: "Your cart is not eligible to this promotion coupon."

====================

1. Clear your cart.
2. Add an item
3. Add a different item
4. Apply promo code
5. It's applied correctly

I believe that "Item count" rule should either:
1. Split into two options: "Total item count" (items x quantity) and "Unique item count" (number of unique items ordered, discarding quantity), or
2. Check against total item count (sum of items x quantity)

**Comment by PWalkow** [comment]
Yes, it is an issue, in this way "ItemCountRuleChecker" is not working properly. The issue lays deeper, on order model. Which counts only number of OrderItems inside it, not the quantities.
@pjedrzejewski will it be fixed or should we just not disable the 'ItemCountRuleChecker' for now?

**Comment by stloyd** [comment]
In fact this not really an issue, it's the way that items are implemented in cart/order. Yes there is problem that your promotion can't depend on selected quantity, but this rule is clear IMO:
- Your cart must have __X__ unique items,
I guess that problem is more about translations & naming not with implementation.

I can agree that there is missing rule that would check the quantity etc. but this is not (IMO) problem of this particular rule.

**Comment by michalmarcinkowski** [comment]
The promotion rule was renamed to `CartQuantity` and it works as @boskee described (see [Behat scenarios](https://github.com/Sylius/Sylius/blob/master/features/promotion/applying_promotion_rules/receiving_discount_based_on_cart_quantity.feature)).

Checking the **X** unique items is a different rule.
