### ISSUE TITLE
Require Symfony components with versions as recommended

### ISSUE THREAD

**Issue by stefantalen** [Sylius/Sylius#13257]
Right now the `composer.json` (and for Sylius-Standard) does not follow the Symfony recommended pattern for their components, allowing for other version to be installed.
```
"symfony/dependency-injection": "^4.4 || ^5.2",
```
This will also allow for installing 5.3 components.

**Describe the proposed solution**
By setting the version requirements as recommended, there won't be any unexpected installs.
```
"symfony/dependency-injection": "4.4.* || 5.2.*",
```
When used in combination with the `extra` data for Symfony one (or better: Sylius) can specify their Symfony version:
```
"extra": {
    "symfony": {
        "require": "5.2.*"
    }
}
```

**Comment by lchrusciel** [comment]
Hey folks, I know that a long time passed, but we were considering it really, really much. As I'm falling with @mbabker here, we cannot afford to list only the given versions. The question remains open, how should we list versions on Sylius-Standard, but flex is still optional dependency for Symfony and not everyone is using it.

**Comment by mbabker** [comment]
> The question remains open, how should we list versions on Sylius-Standard, but flex is still optional dependency for Symfony and not everyone is using it.

As the standard repo is a template repo, I personally would just build and lock it with the latest supported Sylius + Symfony versions (and have the CI lint the app code on the lowest supported PHP version and run the tests on the highest supported version, no need to go too in-depth with the test suite there as downstream users generally won't be building for multiple PHP versions, the lint build step is really just to make sure that for the version of the template still supporting PHP 8.0 that you don't slip PHP 8.1 features in).  Then if folks need to use a different Symfony version, they update the `extra.symfony.require` key in `composer.json` to the version they want to use.  I personally view it as a starter template that's also good to reference when making upgrades, but at the end of the day it's a tool optimized for new installs, and shipping an opinionated and optimized configuration isn't a bad thing there.

**Comment by lchrusciel** [comment]
thanks for the opinion, seems convincing to me. The only problem I have with this approach is that it will blow up if the customer will try to install Sylius on the lower stack, than the one used to generate `composer.lock` from what I remember. Since support for PHP8 only it shouldn't be that much of a problem, but it may happen anyway. Probably generating it for the lowest supported version would mitigate the problem. Nonetheless, on a major bump, it may be not compatible.

**Comment by mbabker** [comment]
It's a little riskier, but you can also not commit the `composer.lock` to that repo.  https://github.com/drupal/recommended-project is the only starter kit I could find on a quick search that actually commits a lock file.  The skeletons/starters for Symfony, Laravel, Sulu, Concrete CMS, and Winter CMS all don't have the lock file committed (probably for the same reason you've noted).

**Comment by lchrusciel** [comment]
The only possibility is to create starters for each node of the support matrix - that could be possible with subtree split and GitHub actions, but I don't want to go this way. Therefore, for now, I would close this discussion.

Feel free to contact me on slack if you would like to pickup discussion :)
