### ISSUE TITLE
Install new App with Docker not working

### ISSUE THREAD

**Issue by zairigimad** [Sylius/Sylius#13254]
**Sylius version affected**: 1.10
<img width="517" alt="Capture d’écran 2021-10-27 à 18 08 51" src="https://user-images.githubusercontent.com/9056839/139113796-bf1d6ab7-3796-416f-82c2-32d7ca8e06c5.png">

**Description**  
Hello,

following the documentation, I cannot Install Sylius with docker approach.

the error in screenshot

**Comment by suhugong** [comment]
Check https://github.com/Sylius/Sylius-Standard/pull/622/files for a fix

**Comment by Ferror** [comment]
@zairigimad it should be already fixed :)
