### ISSUE TITLE
[API] Retrieve payment configuration endpoint returns 500 error

### ISSUE THREAD

**Issue by Sklico** [Sylius/Sylius#13272]
**Sylius version affected**: 1.10.4

**Description**  
API endpoint "Retrieve payment method configuration" (GET ​/api​/v2​/shop​/orders​/{tokenValue}​/payments​/{paymentId}​/configuration) returns an 500 error with message:

`Argument 2 passed to Sylius\\Bundle\\CoreBundle\\Doctrine\\ORM\\PaymentRepository::findOneByOrderToken() must be of type string, null given, called in vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Controller/Payment/GetPaymentConfiguration.php on line 41`

The problem is, that order token argument is named **"tokenValue"** and this method requires argument named **"id"**.

`$payment = $this->paymentRepository->findOneByOrderToken($request->get('paymentId'), $request->get('id'));`

If I try to call endpoint like this and provide tokenValue also in an id argument in query string, it works, but in my opinion, this is not the right and expected behaviour.

`https://127.0.0.1:8000/api/v2/shop/orders/DbINr_OxDZ/payments/21/configuration?id=DbINr_OxDZ`

**Possible Solution**  
If I understand it properly, it should be enough to rename argument from "id" to "tokenValue", or at least add tokenValue argument as an alternative if id is null

![Screen Shot 2021-11-04 at 9 41 03 AM](https://user-images.githubusercontent.com/6402623/140395340-6798a0f0-abea-4a03-9fe8-fdf3e5bceb34.png)
.

**Comment by SirDomin** [comment]
Hey @Sklico We are aware of existing problem with getting payment configuration, i'm working on this issue.

**Comment by GSadee** [comment]
I'm closing this issue as it should be fixed by https://github.com/Sylius/Sylius/pull/14384
