### ISSUE TITLE
[BUG] Change User's password in backend.

### ISSUE THREAD

**Issue by enkuso** [Sylius/Sylius#1328]
Admin changed one user password in backend, but user cannot login with new password.

**Comment by pjedrzejewski** [comment]
Fixed in #2444.

**Comment by Chrysweel** [comment]
Hello.

@enkuso @JRomeoSalazar @pjedrzejewski I edit password of admin user, but admin user cannot login with new password.

This bug exist ? Or I am doing something wrong ?

**Comment by lchrusciel** [comment]
Can you go with this question to our support Slack channel?

**Comment by lchrusciel** [comment]
Sorry to hear that, maybe some will be willing to help here. Also, can you try to write a failing behat tests and open a PR? It would help us to tackle this issue or at least confirm its existence

**Comment by czende** [comment]
I can confirm that this is still issue. Even with beta3 version.

**Comment by lchrusciel** [comment]
I have open a new issue, cuz this one was about shop user and FOSUserBundle which is not a part of Sylius anymore
