### ISSUE TITLE
[AttributeOverride] Sylius Customer Model

### ISSUE THREAD

**Issue by loicpe9** [Sylius/Sylius#13285]
Hey,
I am having a problem rewriting attributes on the Customer class.
Actually, `email` property is unique in vendor doctrine mapping but i d'ont want it.

Here is my model schema: 
= Sylius\Component\Customer\Model\Customer => MappedSuperClass
== App\Entity\Customer => Single table inheritance 
==== App\Entity\Parent
==== App\Entity\Student
==== App\Entity\Teacher

In vendor, mapping is declared on xml format but my entities are on annotation format.

I add these lines in my Customer entity:

- `@ORM\AttributeOverrides({@ORM\AttributeOverride(name="email", column=@ORM\Column(type="string", name="email", length=255, unique=false, nullable=true)) })`

But this error occured : 
`Invalid field override named 'email' for class 'App\Entity\Customer'. `

I have already tried multiples things but without success 
- I can not redeclare the email doctrine property in my customer entity.

Is it a problem to have annotation for my personal entities but xml in vendor ?
Do you know how to solve it ?

Thanks it advance

**Comment by GSadee** [comment]
Hello @loicpe9! 🚀 **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our [Slack](http://sylius.com/slack) (preferred) ;) We have a very active, developed community, I'm sure someone will be able to help you with your problem. Good luck :)
