### ISSUE TITLE
Need Accosiated product on New Api.

### ISSUE THREAD

**Issue by tsogoo** [Sylius/Sylius#13300]
**Describe the proposed solution**
Add Associated Products related resources and serializations on api_platform. Now there is only AssociationType resource for AdminApi.

**Comment by SirDomin** [comment]
Hey @tsogoo it is part of https://github.com/Sylius/Sylius/issues/11250, feel free to open a pull request 🎸.

**Comment by NoResponseMate** [comment]
Hi @tsogoo 👋 
No clue which version this issue was referencing, but product associations have been covered in API in 1.13.

Cheers 🍻
