### ISSUE TITLE
sylius/resource composer.json  php version Conflicts

### ISSUE THREAD

**Issue by fykyx521** [Sylius/Sylius#13321]
**Sylius version affected**: 1.10.5

**Description**  
https://packagist.org/packages/sylius/resource#v1.7.1
require php7.3
but  sylius require php7.4 | php8.0

**Comment by jacquesbh** [comment]
Hi,

Sylius doesn't use the `sylius/resource` anymore, it uses the `sylius/resource-bundle`: https://github.com/Sylius/SyliusResourceBundle

**Comment by fykyx521** [comment]
"sylius/resource": "^1.7",

in https://github.com/Sylius/Sylius/blob/v1.10.5/composer.json

**Comment by fykyx521** [comment]
only use sylius/product component

composer require sylius/product  in php8
Problem 1
    - sylius/product[v1.10.0, ..., v1.10.4] require sylius/resource ^1.7 -> satisfiable by sylius/resource[v1.7.0, v1.7.1].
    - sylius/resource[v1.7.0, ..., v1.7.1] require php ^7.3 -> your php version (8.0.11) does not satisfy that requirement.
    - Root composer.json requires sylius/product ^1.10 -> satisfiable by sylius/product[v1.10.0, ..., v1.10.4].

**Comment by mbabker** [comment]
Did someone stop the `git subsplit` for the standalone `sylius/resource` package?  https://github.com/Sylius/Resource is a few commits behind https://github.com/Sylius/SyliusResourceBundle/tree/master/src/Component and none of the 1.8 tags from the https://github.com/Sylius/SyliusResourceBundle repo are in the split repo.

**Comment by mbabker** [comment]
Also, just to point out here, the reason this hasn't come up sooner in the context of a full Sylius app install is that `sylius/resource-bundle` replaces `sylius/resource`.  So the right version of the Resource component code gets installed into a Sylius application but only because the code isn't being installed from the split repo (which, isn't up-to-date).

**Comment by fykyx521** [comment]
i only use sylius/product sylius/promotion sylius/order in my laravel project

**Comment by fykyx521** [comment]
> i only use sylius/product sylius/promotion sylius/order in my laravel project
我该怎么做
What shall I do?

**Comment by Zales0123** [comment]
@fykyx521 sorry for the long response. I've just split missing tags for `sylius/resource` component (https://github.com/Sylius/Resource/releases/tag/v1.8.2) and it should be fine :) Please, reopen if the problem still exist
