### ISSUE TITLE
We cannot apply all the options selected for an attribute of type multiple select

### ISSUE THREAD

**Issue by delyriand** [Sylius/Sylius#13326]
**Sylius version affected**: 1.10

**Description**  

If we use an attribute of type multiple select and we choose apply to all translate value, only the first option is applied:

https://user-images.githubusercontent.com/465524/143214031-1134f5ce-4f6d-423f-9c4f-e9f479eb73bd.mov

**Steps to reproduce**  

- Create an attribute of type select
- Add more than one option
- Enable the "multiple"
- Add this attribute to a product
- Select 2 options and click on "Apply to all"

**Possible Solution**

**Comment by Zales0123** [comment]
It's a nasty bug, indeed 😈  cc @kulczy @SirDomin

**Comment by GSadee** [comment]
I'm closing the issue as it should be already fixed by https://github.com/Sylius/Sylius/pull/13803
