### ISSUE TITLE
Template not found.

### ISSUE THREAD

**Issue by tdaryani01** [Sylius/Sylius#1332]
Hi,

I am trying to integrate SyliusProductBundle into my application. I followed the instruction on sylius.org and here is my configuraiton:

sylius_product:
    driver: doctrine/orm
    classes:
        product:
            model: Acme\CoreBundle\Entity\Product
            controller: Acme\ContentBundle\Controller\ProductController
            #repository: ~
            form: Sylius\Bundle\AssortmentBundle\Form\Type\ProductType

My product controller extends Sylius\Bundle\ResourceBundle\Controller\ResourceController and currently doesn't add any actions. I am trying to get the CRUD actions in ResourceController working. I am trying to use the templates included in SyliusProductBundle. However, when I try to browse to products, I get Unable to find template "::index.html.twig". I did some debugging and it seems that $templateNamespace in Sylius\Bundle\ResourceBundle\Controller\Configuration.php is null. How can I set the namespace to point to SyliusProductBundle or am I missing something here?

Thanks
Taher

**Comment by Rvanlaak** [comment]
Same here, but for the `SyliusPromotionBundle`. It think something should be mentioned in the general guide: http://docs.sylius.org/en/latest/bundles/general/index.html
