### ISSUE TITLE
Could be Filters trasnlatable?

### ISSUE THREAD

**Issue by petrjuraseko** [Sylius/Sylius#13336]
https://github.com/Sylius/Sylius/blob/c01dfc4d5036f14acdf3acf0b318ca38f301860e/src/Sylius/Bundle/PromotionBundle/Form/Type/Action/UnitPercentageDiscountConfigurationType.php#L44

Actually I see Filters have no translatable label, cloud be there added line with label?

**Comment by Zales0123** [comment]
Hello @petrjuraseko! Yes, it would be a nice improvement :) Would you give it a try and open a PR? Thanks! 🖖

**Comment by pjurasek** [comment]
Hello @Zales0123 ! I give it a try. Can you review the PR? Thanks. :hand:
