### ISSUE TITLE
1.8: API is documented as disabled by default, but isn't

### ISSUE THREAD

**Issue by rimas-kudelis** [Sylius/Sylius#13346]
In `UPGRADE-API-1.8.md`, one of the first lines states that the new API is disabled by default and one has to explicitly enable it:
https://github.com/Sylius/Sylius/blob/a50e720c25ec79f8aa95116c811744a070440596/UPGRADE-API-1.8.md?plain=1#L3

But this is not true: in fact, the API is enabled, and the documented flag does not exist at all and causes an exception if used.
I don't know which way it was supposed to be, but you either forgot to merge in the "disable API by default" functionality into 1.8 branch, or you added that note to the branch accidentally and should maybe remove it?

**Comment by Zales0123** [comment]
Hello Rimas! That's... true 😅 Somehow this change was merged after 1.8.12, so it's not included in the latest version before the support for 1.8 ended. We will figure out how to handle this problem properly, thank you for the report 🖖

**Comment by everwhatever** [comment]
Hi @rimas-kudelis 
It was already changed, I close ticket
