### ISSUE TITLE
Deprecated EncoderAwareInterface since Symfony 5.3

### ISSUE THREAD

**Issue by bigboss86** [Sylius/Sylius#13418]
**Sylius version affected**: 1.10.0

**Description**  
Symfony\Component\Security\Core\Encoder\EncoderAwareInterface is marked deprecated since Symfony 5.3

**Steps to reproduce**  
Implement Sylius\Component\User\Model\UserInterface

**Possible Solution**  
Since Symfony 5.3, use Symfony\Component\PasswordHasher\Hasher\PasswordHasherAwareInterface instead.

**Comment by Zales0123** [comment]
Hello Damian! Indeed, it should be changed, however, on Sylius 1.10 and 1.11 we still support Symfony 4.4. Therefore, we should probably conditionally implement a new interface based on the installed Symfony version. Are you willing to open a PR with such a change? Thanks in advance! 🎉 🖖

**Comment by bigboss86** [comment]
Hi @Zales0123. It's more complicated than just changing the interface, because it uses another method signature. I think we should also change the User.php class and the User.orm.xml models.
What do you suggest?

**Comment by NoResponseMate** [comment]
For the time being, we've been using [a polyfill](https://github.com/SyliusLabs/PolyfillSymfonySecurity) to circumvent this issue, and security has also been updated in 1.12 to accommodate Symfony 6 so it shouldn't be a problem anymore.

Cheers :beers:
