### ISSUE TITLE
JWT Token not found for New Sylius Admin Api 

### ISSUE THREAD

**Issue by tsogoo** [Sylius/Sylius#13444]
**Sylius version affected**: 1.10.0 and 1.11.0-dev and 1.12.0-dev

**Description**  
Admin Api responds 401. JWT Token not found for correct Admin Tokens.

**Steps to reproduce**  
I got Admin tokens:
for 1.12.0-dev:
curl -X 'POST' \
  'https://master.demo.sylius.com/api/v2/admin/authentication-token' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "email": "api@example.com",
  "password": "sylius-api"
}'

for 1.10.0:
curl -X 'POST' \
  'https://demo.sylius.com/api/v2/admin/authentication-token' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "email": "api@example.com",
  "password": "sylius-api"
}'

I used curl to test following urls:
for 1.12.0-dev:
curl -X 'GET' \
  'https://master.demo.sylius.com/api/v2/admin/taxons?page=1&itemsPerPage=30' \
  -H 'accept: application/json' \
  -H 'Authorization: ADMIN_TOKEN'

for 1.10.0:
curl -X 'GET' \
  'https://demo.sylius.com/api/v2/admin/taxons?page=1&itemsPerPage=30' \
  -H 'accept: application/json' \
  -H 'Authorization: ADMIN_TOKEN'

**Comment by tsogoo** [comment]
Well, I needed to write Authorization: Bearer ADMIN_TOKEN

curl -X 'GET'
'https://demo.sylius.com/api/v2/admin/taxons?page=1&itemsPerPage=30'
-H 'accept: application/json'
-H 'Authorization: Bearer ADMIN_TOKEN'

So Swagger's curl execution missing 'Bearer'

**Comment by jakubtobiasz** [comment]
Hi 👋!

When you paste your token in swagger just add Bearer before.

**Comment by tsogoo** [comment]
>

**Comment by tsogoo** [comment]
> Hi 👋!
> 
> When you paste your token in swagger just add Bearer before inside the input field e.g. 'Bearer MY_TOKEN'.

Yeah! Everybody except me doing this. haha. thanks @jakubtobiasz

**Comment by ebuildy** [comment]
> Bearer

I did too ^^ thanks you to have opened this issue, this help me quickly.
