### ISSUE TITLE
[Promotion] When added a new rule to promotion in console is an js error

### ISSUE THREAD

**Issue by petrjuraseko** [Sylius/Sylius#13447]
**Sylius version affected**: v1.12.0-DEV

**Description**  
On promotions add a new rule there is an javascript error logged in the console. The rule Cart Quantity is not showing the part with Quantity etc.

In console I see:
Uncaught TypeError: e is null

**Steps to reproduce issue**

1. Go to Sylius demo https://master.demo.sylius.com/admin/
2. Select Next release feature (v1.12.0-DEV)
3. Go to Cart promotions - create or update existing one
4. Add rule
5. Check console log

**Comment by CoderMaggie** [comment]
Thanks for reporting! ✌🏻 

Closing this as there is another issue with that in progress: #13463

**Comment by rimas-kudelis** [comment]
Heads up: the fix has now been merged in.

**Comment by GSadee** [comment]
I'm reopening this issue as it looks like it still exists 🕵🏻
