### ISSUE TITLE
Cancel unpaid orders command should not cancel refunded/partially refunded order

### ISSUE THREAD

**Issue by LucaGallinari** [Sylius/Sylius#13442]
**Sylius version affected**: 1.x

**Description**  
The command "sylius:cancel-unpaid-orders" cancels orders that are refunded or partially refunded due to this query [here](https://github.com/Sylius/Sylius/blob/b37023df400d4c76cacab5612f1803c2fe7c2852/src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php#L310): it takes all orders that doesn't have "paid" status for "paymentState" field, but this state could be "refunded" or partially_refunded".

We can discuss about the fact that, maybe, "totally refunded" order could be put in the cancelled state, but this is not absolutely the case for "partially refunded" ones: if i refund one of the item (of a multiple items order) because the customer doesn't want that anymore, i don't want the order to be cancelled.
Btw, i am of the idea that even "totally refunded" ones should not be cancelled.

What do you think?

**Comment by SirDomin** [comment]
Hey @LucaGallinari you are right, we are on it 🚀 .
