### ISSUE TITLE
[CoreBundle] form type extensions should specify a priority

### ISSUE THREAD

**Issue by rimas-kudelis** [Sylius/Sylius#13450]
I tried to remove a field added by a `FormTypeExtension` in the CoreBundle (namely the `themeName` field in `ChannelType` form), and autowiring the extension just didn't cut it: I had to specifically use a negative priority to ensure that my extension applies its effect after the core one.

Thus I think it would make sense for CoreBundle FormTypeExtensions to specify an explicit positive priority. This would ensure that app extensions are always applied after the Core ones.

I can provide a PR, just tell me what priority to use for CoreBundle extensions. Is 10 ok?

**Comment by SirDomin** [comment]
Good idea to add these priorities, default extension should be 0. Feel free to open PR and we will see 🎸
