### ISSUE TITLE
Behat tests don't work with strict typing

### ISSUE THREAD

**Issue by TheDevilOnLine** [Sylius/Sylius#13457]
**Sylius version affected**: 1.11, probably 1.10 as well

**Description**  
`Sylius\Behat\Context\Setup\ProductContext::theProductChangedItsPriceTo` expects the price to be an integer, but the way the test is formatted, the price variable is always within a string, and this results in them being a string.

The `declare(strict_types=1);` line at the top of the file, prevents the string to be casted in to an integer, which throws an error: 
```
Type error: Sylius\Behat\Context\Setup\ProductContext::theProductChangedItsPriceTo(): 
Argument #2 ($price) must be of type int, string given, called in 
vendor\behat\behat\src\Behat\Testwork\Call\Handler\RuntimeCallHandler.php 
on line 110 (Behat\Testwork\Call\Exception\FatalThrowableError)
```

**Steps to reproduce**  
Run the following scenario on PHP 8:
```
Scenario: Set product price
  When the store has a product "Example" with code "example"
  And this product's price is "1000"
```

**Possible Solution** 
I feel there are three possible solutions, but non of them are a golden fix:
**1. Remove the quotes in the test definition**
This will break the BC promise for the tests, so I guess this is not the best solution
**2. Add non-quoted test definitions to the already existing tests** 
This will mess with code completion (new developers won't understand why there's a quoted and non-quoted version) and results in duplicate code
**3. Remove strict typing**
Alllows for other issues to be introduced

Possibly there's another solution that I'm not thinking of.

@Sylius core team: Let me know which solution you think is the best solution, and I'll be more than happy to write a PR.

**Comment by TheDevilOnLine** [comment]
Option 4: Write a `Transform` context

**Comment by SirDomin** [comment]
Hey @TheDevilOnLine When you create scenario without currency it wont get to `LexicalContext`, where it needs to be formatted as a currency value (for example  `And this product's price is "$10.00"`)
