### ISSUE TITLE
Different stockable items

### ISSUE THREAD

**Issue by smarques** [Sylius/Sylius#1347]
Hi, I am looking at the InventoryBundle and have a question. 
Say I have two totally different and independent Stockable Entities. 
How could I handle that?
A) duplicate Inventory Unit Entity (different table for each stockable entity)
B) add a field to the Inventory Unit to help identify which entity the stockable id refers to?
C) ( a bit of a overcomplication IMHO) use a 'pivot' table to abstract stockables, as in:
stockable_id | entity       | entity_id
1                   | 'entity1'   |   1
2                   | 'entity2'   |   1

And one question: why link directly the inventory unit to the stockable and not delegate that to the orderItemInterface entity?
This way you could 'ask' the order item entity to point you to the corresponding stockable object (for example in the standard sylius core example, the order item holds a reference to the variant)

Thanks for any help
sergio

**Comment by michalmarcinkowski** [comment]
Please reopen if still relevant.
