### ISSUE TITLE
Remove ACL layer need for MasterRequest to MainRequest renaming 

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#13470]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.12

- [x] Bump Symfony requirement to 5.4 on master
- [x] Remove all if/else statements introduced in https://github.com/Sylius/Sylius/pull/13251/

Ref: https://github.com/Sylius/Sylius/pull/13251#discussion_r778107488

**Comment by GSadee** [comment]
I'm closing the issue as it has been fixed by https://github.com/Sylius/Sylius/pull/14735
