### ISSUE TITLE
Add support for fixed amount promotions to be calculated for total order price

### ISSUE THREAD

**Issue by Creeperface01** [Sylius/Sylius#13481]
I found that promotions don't work well with taxes. At least from my (or here in 🇨🇿) point of view it's important for the regular customer to know the final price including all the taxes. What I'm facing is that promotions are being calculated from the price without taxes so for instance having coupon for fixed order discount of 100 $ doesn't actually mean that the final price will be 100 $ less.

Another issue is that there's no way to get the prices without promotion which is required for example for invoices where discount is a separate item.

To be honest I'm not sure that is possible without any larger changes to the current codebase.

**Comment by SirDomin** [comment]
Hey @Creeperface01, we are aware of this, could you provide working behat scenario?

**Comment by jakubtobiasz** [comment]
Hi @Creeperface01!

1) It is probably caused because you chose not to include the tax in the price. So, the coupon is also net. When you decide to include the tax in the price, then the coupon is also gross.

2) Order Item carries information about original unit price.

**Comment by jakubtobiasz** [comment]
Our internal QA process qualified this issue as not valid. If you don't agree with that decision, please let me know, I'll reopen it, and we'll revise this issue again.
