### ISSUE TITLE
"Integrity constraint violation: 1048 Column 'locale' cannot be null" on Product API

### ISSUE THREAD

**Issue by Looouuu** [Sylius/Sylius#13503]
**Sylius version affected**: 1.10.8, 1.11.0-ALPHA.1

**Description**  
Hello ! 

I'm trying to use the API, but I cannot create or update product translations. I'm getting
`An exception occurred while executing 'INSERT INTO sylius_product_translation (name, slug, description, meta_keywords, meta_description, short_description, locale, translatable_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params [\"string\", \"string\", null, null, null, null, null, 20]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'locale' cannot be null`

I tried on a clean install of Sylius, same problem.

**Steps to reproduce**  

```php
curl -X 'PUT' \
  'http://127.0.0.1/api/v2/admin/products/000F_office_grey_jeans' \
  -H 'accept: application/ld+json' \
  -H 'Authorization: Bearer [token]' \
  -H 'Content-Type: application/ld+json' \
  -d '{
  "translations": {
    "en_US": {
      "name": "string",
      "slug": "string",
      "locale": "string"
    }
  }
}'
```

Any idea ?

**Comment by TheMilek** [comment]
Hi @Looouuu 💃🏽 
Thank you for your issue.
I've reproduced this problem and it exists, but for now We are focused on Shop context of API. 
Nevertheless We are looking up to repair it in future.
Feel free to open PR with solution 🚀

**Comment by TheMilek** [comment]
I'm closing this issue as it should be fixed by https://github.com/Sylius/Sylius/pull/15508 🎉
