### ISSUE TITLE
Remove symfony/http-kernel 4 symbols usage

### ISSUE THREAD

**Issue by mmenozzi** [Sylius/Sylius#13525]
Like said on #10664, the class `Sylius\Bundle\CoreBundle\EventListener\CircularDependencyBreakingExceptionListener` uses symbols from `symfony/http-kernel` version 4. Sylius does not support Symfony 4 anymore so this class must be fixed to not use those symbols.

Then, symbols added [here](https://github.com/Sylius/Sylius/commit/e09551c016752eff03339cc90ab678afabc3765d) in the ComposerRequireChecker configuration could be removed from the whitelist.

**Comment by Zales0123** [comment]
Absolutely 👍 We generally need to go through the code and remove/fix all the references to not supported Symfony 4 💪 🚀

**Comment by mmenozzi** [comment]
👍
