### ISSUE TITLE
missing some Phpspec tests for HasEnabledEntityValidator

### ISSUE THREAD

**Issue by loic425** [Sylius/Sylius#13586]
**Sylius version affected**: 1.11

**Description**  
`src/Sylius/Bundle/CoreBundle/Validator/Constraints/HasEnabledEntityValidator.php` has no real specs with Phpspec.

[the current phpspec class](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/spec/Validator/Constraints/HasEnabledEntityValidatorSpec.php)

**Comment by ernestWarwas** [comment]
Hi @loic425, thanks for describing the issue. Can you provide a PR with a spec for that? :dancer:
