### ISSUE TITLE
Empty ProductVariant's name causes 500 on frontend

### ISSUE THREAD

**Issue by kptLucek** [Sylius/Sylius#13640]
**Sylius version affected**: 1.10.0

**Description**  
Empty product's variant name causes `500` on product page.
```
Return value of Sylius\\Bundle\\ProductBundle\\Form\\Type\\ProductVariantChoiceType::Sylius\\Bundle\\ProductBundle\\Form\\Type\\{closure}() must be of the type string, null returned
```

**Steps to reproduce**  

1. Product has to has at least 2 variants,
2. Access product variant form from Admin Panel,
3. Clear it's name,
4. Save variant,
5. Edit product, change `Variant selection method` to `Variant choice`
6. Access product's page

**Possible Solution**  

Fallback to product's name in case of empty variant's name

**Comment by Ferror** [comment]
We don't support 1.10 anymore, but I checked and the fallback exists in Sylius 1.11 :)
