### ISSUE TITLE
[API][ApiBundle][ProductReview] Invalid group on item operation  

### ISSUE THREAD

**Issue by petrjuraseko** [Sylius/Sylius#13648]
https://github.com/Sylius/Sylius/blob/56bf4199f4c63e0c9101b1e3eb42bd5e4553583a/src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductReview.xml#L64

Actually the group on this line is `admin:product_review:read`. I expect that the group should be 
`shop:product_review:read`

**Comment by ernestWarwas** [comment]
Hi @petrjuraseko, thanks for the issue. Can you provide us a PR with a fix and some contract tests? 💃

**Comment by GSadee** [comment]
I'm closing the issue as it has been fixed by https://github.com/Sylius/Sylius/pull/14573
