### ISSUE TITLE
[API][ApiBundle][ProductReivew] Shop collection operation missing the normalization_context

### ISSUE THREAD

**Issue by petrjuraseko** [Sylius/Sylius#13649]
https://github.com/Sylius/Sylius/blob/56bf4199f4c63e0c9101b1e3eb42bd5e4553583a/src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductReview.xml#L41

On the shop collection operation is missing `normalization_context`. I would expected there:
```
                <attribute name="normalization_context">
                    <attribute name="groups">shop:product_review:read</attribute>
                </attribute>
```

**Comment by ernestWarwas** [comment]
Hi @petrjuraseko, can you provide us a PR with some contract tests? :dancer:
