### ISSUE TITLE
syntax error, unexpected token "declare"

### ISSUE THREAD

**Issue by ToghrolRc** [Sylius/Sylius#13669]
Hi there. i pretty new to Backend actually so i'm sorry if my question is kinda strange.
i had Sylius on my laptop before and it worked correctly.  i copied the "acme" folder to have a backup in my Flash Drive. after that i changed my windows to Windows11 and now when i want to run my sylius project in new windows , im getting this error:
https://ibb.co/DKb6p6y

also i have my previous DB back up.
please help me. thanks

**Comment by Ferror** [comment]
Hi! I'm not gonna get into this URL.
