### ISSUE TITLE
[Docs][Customization][API] Example of "Removing a field from a response" in "How to customize serialization" works on a field that doesn't exist anymore

### ISSUE THREAD

**Issue by gigamarr** [Sylius/Sylius#13668]
**Sylius docs version**: 1.11.0

**Description**
It's better if example works on a field that is there
[Removing a field from a response](https://docs.sylius.com/en/1.11/customization/api/serialization_customization.html#removing-a-field-from-a-response)

**Comment by everwhatever** [comment]
Hi @gigamarr 
Thank you for your report, it's not a priority for us now. However, feel free to change it

**Comment by jakubtobiasz** [comment]
Hello @gigamarr!
For example, needs it is fair for us to use any name for a field. If you find it helpful to rename them, feel free to contribute, but for now, I am closing this issue.
