### ISSUE TITLE
`sylius:install:sample-data` doesn't print exception message in console

### ISSUE THREAD

**Issue by benjaminmal** [Sylius/Sylius#13675]
**Sylius version affected**: 1.10.9

**Description**  
While writing a custom fixture which throws a exception, I tried to run `bin/console sylius:install:sample-data` and I get this error:

> Symfony\Component\Console\Input\Input::escapeToken(): Argument 1 ($token) must be of type string, null given, called in [...]/vendor/symfony/console/Input/ArrayInput.php on line 120 

**Expected output**
> An error occurred while using the console. Message: {exceptionMessage}.

**Steps to reproduce**  
- Write an `ExampleFactory` and throw exception in `ExampleFactory::create()`
- `bin/console sylius:install:sample-data`

**Debugging**
I found out that when Symfony tried to print the error in the console [here](https://github.com/symfony/symfony/blob/0c1bf57588ae6fe1463945d0b2b68d609c9fb4a6/src/Symfony/Component/Console/EventListener/ErrorListener.php#L42), it tries to escape the param value [here](https://github.com/symfony/symfony/blob/0c1bf57588ae6fe1463945d0b2b68d609c9fb4a6/src/Symfony/Component/Console/Input/ArrayInput.php#L118), but [`Input::escapeToken()`](https://github.com/symfony/symfony/blob/0c1bf57588ae6fe1463945d0b2b68d609c9fb4a6/src/Symfony/Component/Console/Input/Input.php#L191) is expecting a string. The default value for `sylius:install:sample-data --fixture-suite` is null.

**Possible Solution** 
Set `default` as `--fixture-suite` default value.

Not sure if it is a Sylius issue or a Symfony one.

**Comment by TheMilek** [comment]
Hi @benjaminmal 💃🏽 
I'm not not sure if it is a bug or problem with your customization.
Please ask about this problem on our slack 🚀  
sylius.com/slack
Otherwise feel free to reopen this issue with more details

**Comment by FilipJanousek** [comment]
Hi, i have same problem, has anyone solved it?

**Comment by ghost** [comment]
I'v got the same problem. Fixed with `composer install`. I don't know why.
