### ISSUE TITLE
[Bug][Channel] The hostname resolver does not check for the channel status

### ISSUE THREAD

**Issue by lruozzi9** [Sylius/Sylius#13677]
**Sylius version affected**: 1.*

**Description**  
The HostnameBasedRequestResolver searches the channel using the findOneByHostname method of the Channel Repository, but this method or the resolver itself does not check for the channel status (enabled/disabled). So a disabled channel can be navigated.

**Possible Solution**  
Add check for status in the repository (new method findOneActiveByHostname) or in the resolver.

**Comment by GSadee** [comment]
Closing the issue, as it has been fixed by https://github.com/Sylius/Sylius/pull/14155
