### ISSUE TITLE
[Admin] Promotion amount incorrect on summary

### ISSUE THREAD

**Issue by JinbeiStudio** [Sylius/Sylius#13674]
**Sylius version affected**: 1.10.2

**Description**  
When using a coupon that combine an orderPromotionAdjustment and a unitPromotionAdjustment, the amount displayed does not sum the two amount of both adjustment, but instead display only one adjustment. This is because of the merge native function of twig that you use in _totalPromotions.html.twig

**Steps to reproduce**  
Use a coupon that is linked to a promotion with two actins offering both an order level discount and an item level discount.

**Possible Solution**  
The merge of the two array should sum the two amount instead of erasing one with two promotions using the same key.

**Comment by JinbeiStudio** [comment]
<img width="1712" alt="Capture d’écran 2022-02-21 à 17 17 45" src="https://user-images.githubusercontent.com/62211509/155086613-ad5d36e6-f455-4536-8d2b-43c7fa18bf2f.png">

**Comment by Ferror** [comment]
Hi @JinbeiStudio we made some changes in Sylius 1.11 with calculating promotions. Would you like to test it against Sylius 1.11, as we do not maintain 1.10 anymore? <3

**Comment by coldic3** [comment]
Hi @JinbeiStudio, as we don't have feedback, I'm closing it for now. Feel free to let us know if the problem still exists :slightly_smiling_face:
