### ISSUE TITLE
Remove Placehold.it images resolving

### ISSUE THREAD

**Issue by andriusvo** [Sylius/Sylius#13686]
**Sylius version affected**: All versions

**Description**  

Started profiling why our Behat tests became very slow. Find out, that `Mink` is waiting for whole page to be loaded. It was waited for `https://placehold.it/50x50`, but ATM (2022-02-23) this page is not working, so it was failed and page loaded after some time.

**Steps to reproduce**  
Run behat tests which includes any picture from `https://placehold.it/`

**Possible Solution**  

Why not to use any default placeholder from filesystem which will be included in Sylius?
- It will be faster
- We are not relying on 3rd party resources

**Comment by GSadee** [comment]
Fixed by #13750

**Comment by flochntrl** [comment]
@GSadee Hi, the fix is not on the 1.11
