### ISSUE TITLE
[ApiBundle] The parameter should be tokenValue

### ISSUE THREAD

**Issue by petrjuraseko** [Sylius/Sylius#13681]
https://github.com/Sylius/Sylius/blob/ddb01caaf04843d5ff68c04ab3a70ffc1af7ddf2/src/Sylius/Bundle/ApiBundle/Controller/Payment/GetPaymentConfiguration.php#L37

Instead of an `id` it should be `tokenValue`.

**Comment by Prometee** [comment]
@Ferror this also mean that this feature is not yet tested, right ?
BTW I think this issue must be mentioned in the 1.12 version because it still exists.

**Comment by GSadee** [comment]
I'm closing this issue as it should be fixed by https://github.com/Sylius/Sylius/pull/14384
