### ISSUE TITLE
Bundle and more split

### ISSUE THREAD

**Issue by harikt** [Sylius/Sylius#1369]
Hey, 

I was wondering whether we could make a bundle for orm and the component.

Consider ProductBundle . It is tied to symfony framework. But if we could make another layer with ProductDoctrineBundle and making it as dependency in ProductBundle that will help people to use the doctrine also with their favourite framework.

Thoughts on this ?

**Comment by pamil** [comment]
1.0 will stay with the components & bundles, that's for sure.
