### ISSUE TITLE
Adjustments Order_Item_Id is always Null

### ISSUE THREAD

**Issue by Tragllk** [Sylius/Sylius#13707]
**Sylius version affected**: 1.9

**Description**  
We noticed that our cart takes a lot of time to load (Approx 2s) as soon as we had more than 1 different item in cart.
It's not noticeable if you have a small db, but you can still check in it.

When creating adjustments, they are added to order item unit, and never added to order items, due to that, there are no order_item_id in sylius_adjustment.
This causes the method findCartForSummary (OrderRepository) to be a bit longer than expected because of the hydration made on "items.units" (Around 2 sec on our website)

(We also tried with a fresh sylius installation)

**Steps to reproduce**  
Add Item to cart, there should not be any order_item_id different than null in database.
Check cardinality on sylius_adjustment order_item_id index. (Should be 1)

**Possible Solution**  
Fast Fix : remove items.adjustments from hydration

**Comment by ernestWarwas** [comment]
Hi @Tragllk, thanks for the issue. Could you give us more information about your configuration (like: server configuration, DB config, etc.? 🚀

**Comment by everwhatever** [comment]
Hey @Tragllk 
We don't support 1.9 version anymore. If you have still some problems with actual version please open new issue
