### ISSUE TITLE
The breadcrumb on product does not handle the main taxon disabled case

### ISSUE THREAD

**Issue by kgonella** [Sylius/Sylius#13713]
**Sylius version affected**: > 1.8

**Description**  
The breadcrumb on product handle the case if an ancestor taxon is disabled and remove the link. But nothing is done if the main taxon is disabled. 

**Steps to reproduce**  
Choose a main taxon on a product.
Disable the main taxon.
Go to the product page.
The main taxon is linked in breadcrumb and lead to a "not found exception".

**Possible Solution**  
- Consider product as it has no main taxon (change `_breadcrumb.html.twig` line 4)
`{% if product.mainTaxon is not null and product.mainTaxon.enabled %}`
 
- Render the main taxon with no link on it (change `_breadcrumb.html.twig` line 17)
```
{% if not product.mainTaxon.enabled %}
<div class="section">{{ taxon.name }}</div>
{% else %}
<a href="{{ path('sylius_shop_product_index', {'slug': taxon.slug, '_locale': taxon.translation.locale}) }}" class="section">{{ taxon.name }}</a>
{% endif %}
```

**Comment by ernestWarwas** [comment]
Hi @kgonella, thanks for describing the issue. We will merge #13874 in the upcoming sprints 💃
