### ISSUE TITLE
Order Products by productTaxons.position (filter by taxon)

### ISSUE THREAD

**Issue by tsogoo** [Sylius/Sylius#13726]
**Sylius version affected**: 1.11.0

**Description**  

I want to order product by productTaxons.position in `shop/products` api.

**Steps to reproduce**  

In Product.xml:
```
<attribute name="order">
    <attribute name="productTaxons.position">ASC</attribute>
</attribute>
```

Error shows:
`Cannot select distinct identifiers from query with LIMIT and ORDER BY on a column from a fetch joined to-many association. Use output walkers.`

**Comment by ernestWarwas** [comment]
Hi @tsogoo. I think it's not an issue if you want help with customization Sylius, please join us here and ask for help: https://sylius-slackin.herokuapp.com/ 🚀
