### ISSUE TITLE
[Admin][UI] Taxon slug generation broken

### ISSUE THREAD

**Issue by benjamin-vauchel** [Sylius/Sylius#13749]
**Sylius version affected**: 1.10

**Description**  
Taxon slug field does not handle taxon parent field to generate slug.

**Steps to reproduce**  
You can try on Sylius demo : https://demo.sylius.com/admin/taxons/65190/edit

- Slug of `Jeans > Men` category is `jeans/men`
- Parent of `Men` category is `Category / Jean`
- But if you unlock slug field and change taxon name by `Test`
- Slug field is `test` instead of `jeans/test`

**Possible Solution**  
Remove `&& $('#sylius_taxon_parent').is(':visible')` condition on `sylius-taxon-slug.js`. 
The condition ` $('#sylius_taxon_parent').val() != ''` should be enough.

And update `TaxonSlugController` to find parent by `code` instead of `id`.

**Comment by SirDomin** [comment]
Hey @benjamin-vauchel is there any chance you could provide PR with this solution?
