### ISSUE TITLE
Reaching memory limit when creating configurable product.

### ISSUE THREAD

**Issue by ulinskas** [Sylius/Sylius#13742]
**Sylius version affected**: 1.10.7

**Description**  
Reaching memory limit when creating configurable product.
When creating new configurable product, sylius tries to load all existing product options at once and by doing that you can reach your memory limit.

**Steps to reproduce**  
Create multiple options in you DB table `sylius_product_option`
Visit `sylius_admin_product_create` route
If you created enough product options or you have low memory limit, you should get an error `Fatal error: Allowed memory size of *NUMBER* bytes exhausted `

This happens because `ProductOptionChoiceType::configureOptions` function tries to load all product options at once with `$this->productOptionRepository->findAll()`.
```
public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'choices' => function (Options $options): array {
                return $this->productOptionRepository->findAll();
            },
            'choice_value' => 'code',
            'choice_label' => 'name',
            'choice_translation_domain' => false,
        ]);
    }
```

**Comment by ernestWarwas** [comment]
Hi @ulinskas, I have some questions about this issue. How many options do you have in your DB? What was your memory limit? There is any chance would you provide us a solution with some tests and performance tests? We know that using findAll() here is not good at all but right now it is not our priority.

**Comment by ulinskas** [comment]
Hi @ernestWarwas,
We had a lot of options. I can't give you exact number now. But cleaning up helps.
About memory limit - 1GB

I'll try to come up with a nice solution.
