### ISSUE TITLE
[Docs] Add image on entity

### ISSUE THREAD

**Issue by vvasiloi** [Sylius/Sylius#13764]
**Sylius docs version**:  latest

**Description**
Describe how to add one-to-one image on entity, either in https://docs.sylius.com/en/latest/cookbook/images/images-on-entity.html or separately,

**Comment by TheMilek** [comment]
Hello @vvasiloi! 
Hope you're doing well 🍻 
I was wondering if you had any updates on the issue you assigned yourself to? 
Thank you so much for your time and effort! 😄

**Comment by vvasiloi** [comment]
@TheMilek completely forgot about it. Will add some reminders this month. Thanks!

**Comment by Rafikooo** [comment]
Hey @vvasiloi,

This is a friendly reminder in case you forgot about it 😆

Best wishes,
Rafał

**Comment by vvasiloi** [comment]
> Hey @vvasiloi,
> 
> This is a friendly reminder in case you forgot about it 😆
> 
> Best wishes,
> Rafał

On the case, thanks for the reminder!

**Comment by vvasiloi** [comment]
@Rafikooo Done! Waiting for your reviews! ✌️

**Comment by GSadee** [comment]
It has been fixed by https://github.com/Sylius/Sylius/pull/15037
