### ISSUE TITLE
[ApiBundle] ProductImageNormalizer throws an exception when executing from CLI

### ISSUE THREAD

**Issue by EditaG** [Sylius/Sylius#13784]
**Sylius version affected**: 1.11

**Description**  
ProductImageNormalizer has no section check in `supportsNormalization` method so it gets executed everytime we want to serialize product image entity, even outside API context. In our case it's Symfony command. `resolvePath` method gets current request and tries to access query parameter without checking if requests exists.

**Possible Solution**  
Simple check if request is set should do the trick. Or section check in `supportsNormalization` method.

**Comment by GSadee** [comment]
Hello @EditaG! Thank you for reporting an issue, however, our serialization is API-oriented and implemented specifically for API right now, so we won't fix that, at least in the near future. I suggest you fix it on your side 😃
