### ISSUE TITLE
Is this parameter is used or required ?

### ISSUE THREAD

**Issue by FlorentinGarnier** [Sylius/Sylius#13780]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.9

https://github.com/Sylius/Sylius/blob/6650e5726eb81ed37343dd0e628408e0ebcac1e0/src/Sylius/Bundle/OrderBundle/NumberGenerator/OrderNumberGeneratorInterface.php#L20

After evaluation, it seems that this parameter is never used in SequentialOrderNumberGenerator

**Comment by vvasiloi** [comment]
Hi @FlorentinGarnier, as I already [commented on the PR](https://github.com/Sylius/Sylius/pull/13781#issuecomment-1071153790), it was deliberately made this way.

**Comment by vvasiloi** [comment]
For additional information, see [this PR](https://github.com/Sylius/Sylius/pull/5562) where the parameter was introduced, because it wasn't there from the start. There's a comment made by @pjedrzejewski explaining why it was added.
