### ISSUE TITLE
Opcache preload fatal error

### ISSUE THREAD

**Issue by gbere** [Sylius/Sylius#13800]
**Sylius version affected**: 1.11.x

**Description**  
When use opcache.preload:
```bah
NOTICE: PHP message: PHP Fatal error:  Failed to load class Symfony\Bundle\FrameworkBundle\Templating\EngineInterface used by typed property Sylius\Bundle\ShopBundle\Controller\SecurityWidgetController::$templatingEngine during preloading in Unknown on line 0
```

**Possible Solution**  
Remove Symfony\Bundle\FrameworkBundle\Templating\EngineInterface. Templating component was deprecated on Symfony 4.3 and removed on 5.0 and Sylius 1.11.x requires Symfony 5.4

**Comment by vvasiloi** [comment]
Hi @gbere, there's a [PR](https://github.com/Sylius/Sylius/pull/13709) by @mamazu that would solve the issue.
However, the fix won't land in Sylius 1.11, because it still supports Symfony 4.4.
If you want to use preloading with Sylius 1.11, you will have to upgrade to PHP 8.1.

**Comment by mamazu** [comment]
The merge request is from @mmenozzi but close enough. :D

**Comment by vvasiloi** [comment]
Oops, my bad. 😅

**Comment by mmenozzi** [comment]
@vvasiloi Sylius 1.11 does not support symfony 4. My PR should land in Sylius 1.11

**Comment by vvasiloi** [comment]
@mmenozzi I see it does: https://github.com/Sylius/Sylius/blob/0d825301a70dceaa13aad0e7659e7718989a8bb1/composer.json#L73-L112

**Comment by mmenozzi** [comment]
Uhm... You're right I always thought that Symfony 4 support was removed in Sylius 1.11. It's written here for example: https://github.com/Sylius/Sylius/blob/master/CHANGELOG-1.11.md#tldr-4
