### ISSUE TITLE
[Admin] 500 when trying to access a cart in the order list

### ISSUE THREAD

**Issue by mamazu** [Sylius/Sylius#13826]
**Sylius version affected**
`>1.10.9` and probably more

**Description**  
When trying to access a cart in the order listing in the admin panel, Sylius throws a 500. There is no check in the code that checks if the order is actually completed in the `sylius_order_show` route.

**Steps to reproduce**  
* Create a cart in the shop and don't do the checkout
* Look into the database and take the id of the cart
* Go to /admin/orders/<id> with the id and see it's a 500 instead of the expected 404

**Possible Solution**  
Add an event listener to the route that checks if the order is completed and if not then throw a `NotFoundException`. I'll do a merge request for that.

**Comment by ernestWarwas** [comment]
Hi, @mamazu thanks for describing the issue. If you want us to take over and prioritize please open a support ticket 💃
