### ISSUE TITLE
Make a general XXXChoiceType

### ISSUE THREAD

**Issue by winzou** [Sylius/Sylius#1384]
https://github.com/Sylius/Sylius/pull/1382/files#r11612029

> We have something similar on other places (GatewayChoiceType, PaymentGatewayChoiceType, RuleChoiceType...) and another type of choices like ShippingCategoryChoiceType. If you lok at this classes, they all have same implementation. I think we can have one choice type for the cases like this.

**Comment by aRn0D** [comment]
Done by the resourcechoicetype
