### ISSUE TITLE
Javascript data form collection for rules/actions is broken because of harcoded "sylius_promotion" selector

### ISSUE THREAD

**Issue by Geolim4** [Sylius/Sylius#13845]
**Sylius version affected**: 1.10.05

**Description**  
I'm working on a custom entity/resource that use the same mecanism of rules/actions than the promotion entity.
Doing that I copied and changed name of classe/Namespace for my personal use case.
It work great except that the "actions" bloc does not show the sub-configuration field(s).

It is mostly caused by the harcoded "sylius_promotion" selector below:

**Steps to reproduce**  

**Possible Solution**  
Open `vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Resources/private/js/app.js`

Search (line ~62):
```js
  $('#actions a[data-form-collection="add"]').on('click', () => {
    setTimeout(() => {
      $('select[name^="sylius_promotion[actions]"][name$="[type]"]').last().change();
    }, 50);
  });
```

And update the code on the same model than for rules before:
```js
  $('#rules a[data-form-collection="add"]').on('click', (event) => {
    const name = $(event.target).closest('form').attr('name');

    setTimeout(() => {
      $(`select[name^="${name}[rules]"][name$="[type]"]`).last().change();
    }, 50);
  });
```

Which would produce something like:
```js
    $('#actions a[data-form-collection="add"]').on('click', () => {
        const name = $(event.target).closest('form').attr('name');

        setTimeout(() => {
            $(`select[name^="${name}[actions]"][name$="[type]"]`).last().change();
        }, 50);
    });
```

**Comment by Geolim4** [comment]
Just saw that this code has been completely rewritten in 1.11.

But why did you completely hardcoded the "sylius_promotion" in the Javascript ?

This completely block developers of reusing this form component for doing a custom actions/rules mechanism.

**Comment by coldic3** [comment]
Thanks @Geolim4! The fix is already merged and should appear in the nearest release.

**Comment by Geolim4** [comment]
Wonderful ! Thank you !
