### ISSUE TITLE
MoneyIntToLocalizedStringTransformer ignores comma separated numbers in Catalog Promotions Fixed Discount type field 

### ISSUE THREAD

**Issue by sabat24** [Sylius/Sylius#13884]
**Sylius version affected**: 1.1.11

**Description**  
[Here](https://github.com/Sylius/Sylius/commit/cb69b221c0a82f40c96cc8108cd412b705e47d97#diff-70d1ea3d00703668498eb0b1c89c84bc4dd19bc53e73cb5a2ed53ce7c628aea8) you added transformer to the `amount` field. In Polish locales all numbers are formatted with comma as decimal separator. When user enters any amount with decimal part for example `10,10` then `is_numeric` function in [reverseTransform](https://github.com/Sylius/Sylius/blob/cb69b221c0a82f40c96cc8108cd412b705e47d97/src/Sylius/Bundle/PromotionBundle/Form/DataTransformer/MoneyIntToLocalizedStringTransformer.php#L33) method breaks the transformer as `10,10` value isn't considered as numeric.

![obraz](https://user-images.githubusercontent.com/6381661/164008521-e1861ca4-78f1-45b3-8237-759a6b6f9057.png)

The entered value `10,10` is transformed to `null` and the configuration is incorrectly written to the database.

![obraz](https://user-images.githubusercontent.com/6381661/164009356-1d6182d5-4998-42bc-89ac-a5d519f591a5.png)

In your demo if you enter a comma separated value there you will get 500 internal server error.

**Comment by sabat24** [comment]
Yes and in my opinion someone just copied `is_numeric` check from `transform` method into `reverseTransform` method which is incorrect. 

For both transformers `Sylius\Bundle\PromotionBundle\Form\DataTransformer\PercentFloatToLocalizedStringTransformer` and `Sylius\Bundle\PromotionBundle\Form\DataTransformer\MoneyIntToLocalizedStringTransformer` the `$value` check in `reverseTransform` method should looks like: 

```php
if (null !== $value && !\is_string($value)) {
```

not

```php
if (!is_numeric($value)) {
```

Because both transformers extend `Symfony\Component\Form\Extension\Core\DataTransformer\NumberToLocalizedStringTransformer` where Symfony checks that value correctly.

What's more I wouldn't duplicate that check, which may lead to such errors, but I would catch an exception thrown by that core class.

```php

final class MoneyIntToLocalizedStringTransformer extends MoneyToLocalizedStringTransformer
{
    /**
     * @inheritdoc
     */
    public function reverseTransform($value): float | int | null
    {
        // or remove that catch and throw an exception like Symfony does
        try {
            return (int) parent::reverseTransform($value);
        } catch (TransformationFailedException) {
            return null;
        }
    }

    /**
     * @inheritdoc
     */
    public function transform($value): ?string
    {
        if (!is_numeric($value)) {
            return null;
        }

        return parent::transform($value);
    }
}
```

**Comment by vvasiloi** [comment]
@sabat24 I don't know all the implications. I have to review the uses cases and the tests to recommend or endorse a solution.
I'm sure it can't just return the casted value from the parent transformer because it can be null, which will be cast to int as 0. 
I'm all for propagating the exceptions, but it will probably require additional handling up the call chain.

**Comment by sabat24** [comment]
@vvasiloi You are right about the casted value. I just copied original implementation from commit presented here and just change that "checking" condition. 

I took a look how it's implemented in Symfony and they propose following solution:

```
$result = parent::reverseTransform($value);
return null !== $result ? (int) $result : null;
```

I edited my code above with the corrected return.

**Comment by Ferror** [comment]
Hi! @sabat24 would you like to open PR with a recommended solution? We gonna look into it 😄

**Comment by sabat24** [comment]
I can try to go for it.
