### ISSUE TITLE
If customer adds a product that has multiple variants to their cart neither `product_name` or `variant_name` get inserted into `sylius_order_item` table

### ISSUE THREAD

**Issue by gigamarr** [Sylius/Sylius#13916]
**Sylius version affected**: 1.11.4

**Description**  
If customer adds a product that has multiple variants to their cart neither `product_name` or `variant_name` get inserted into `sylius_order_item` table

**Steps to reproduce**  
Add any of multiple variants of a product into cart and check presence of `product_name` and `variant_name` values in `sylius_order_item` table for that order item instance.

**Possible Solution**  
I don't know yet but I'm going to look into it and give updates here

**Comment by TheMilek** [comment]
Hi @gigamarr ✌🏽 
If I understand correctly it is working as it should be.
These values are gonna be filled when the checkout is completed, so i'm closing this issue. 
Feel free to reopen it if needed 💃🏽
