### ISSUE TITLE
Sylius Plus installation guideline

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#13922]
**Sylius docs version**: latest

**Description**
When installing Sylius Plus, there is this guideline step:

> 10. Copy templates that are overridden by Sylius Plus into templates/bundles:
> cp -fr vendor/sylius/plus/src/Resources/templates/bundles/* templates/bundles

There is a catch in here: if you already have template customizations, doing this approach can break your app. or not doing this will put you in the situation where you don't have access to some features because there are missing customizations.

eg. a form is missing a row because the template has some customizations prior to Sylius Plus install.

food for thought to whoever installs Sylius Plus and does not have the row for roles in Admin User edit form :)

**Comment by Ferror** [comment]
Hi @gabiudrescu I get it that it may be frustrating, but arent we all use a control version system in any form that will tell you that something was overridden?

However, I'm really looking forward to your proposal on how we can improve that step <3

**Comment by coldic3** [comment]
Hey @gabiudrescu,
we've refactored templates in Sylius Plus recently and we use Template Events instead so I hope in the nearest future we'll be able to get rid of this step in the installation guide :dancer:
