### ISSUE TITLE
Zone member cannot be the same as a zone.

### ISSUE THREAD

**Issue by JonatanCz** [Sylius/Sylius#13923]
**Sylius docs version**: latest (1.11.0)

**Description**
I have installed Sylius following the [documentation](https://docs.sylius.com/en/1.11/getting-started-with-sylius/installation.html) (added some changes as described in #12893) and now I'm trying to setup zones. This is what I get after submitting the data:

![image](https://user-images.githubusercontent.com/29522138/166552048-cb5e738e-8229-480c-9341-08914d9a3667.png)

The error says:

> Zone member cannot be the same as a zone.

but in [the documentation](https://docs.sylius.com/en/1.11/getting-started-with-sylius/basic-configuration.html#zone) it's clearly written:

> Let’s create one, basic zone named United States for the only country in the system (also United States).

**Comment by vvasiloi** [comment]
There is a fix for that, but it's stale... I also have to rebase it now, since 1.9 is no longer maintained: https://github.com/Sylius/Sylius/pull/12868

**Comment by vvasiloi** [comment]
I will close this as there's already an issue for it: https://github.com/Sylius/Sylius/issues/11881

**Comment by vvasiloi** [comment]
@JonatanCz great news, it was already merged! Watch for the next patch release.
