### ISSUE TITLE
DB migration fails due to existing indexes in messenger_messages

### ISSUE THREAD

**Issue by xelaris** [Sylius/Sylius#13988]
**Sylius version affected**: 1.11.5

**Description**  
After upgrading to Sylius 1.11.5 our deployment fails because the migrations don't run successfully.

```
An exception occurred while executing 'CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)':

SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'IDX_75EA56E0FB7336F0'
```

This happens, because the table wasn't initially created by the migration provided by Sylius, but by our own migrations. The initial Sylius migration `Version20220203115813`, which creates the schema, skips the creation, if the schema exists. But the new migration `Version20220407131547 ` (added with https://github.com/Sylius/Sylius/pull/13847) tries to add the indexes in any case. This could also happen to applications where the `messenger_messages` schema was created via the auto setup. In general it seems as every Sylius installation, which had an update-to-date `messenger_messages` schema before Sylius 1.11, could be affected by this problem.

**Steps to reproduce**  

- Setup Sylius in Version 1.10.x
- Add Symfony messenger with doctrine transport manually, including a proper migration
- Upgrade to Sylius 1.11.5 and execute migrations

**Possible Solution**  

The migration `Version20220407131547` should somehow determine if the indexes need to be added (were already added). Unfortunately it seems as mysql doesn't support something like `CREATE INDEX IF NOT EXISTS`.

**Comment by raneomik** [comment]
Hello, we had similar issue in our CD where we already applied same messenger related migration before https://github.com/Sylius/Sylius/pull/13847 .

  We solved it doing the following : 

- applied the following command on server : `bin/console doctine:migration:execute Sylius\\Bundle\\CoreBundle\\Migrations\\Version20220407131547 --down `  (if using [deployer](https://deployer.org),  in temporary failed CD dir `release` path)
- rectified the migration containing the exact same lines in up & down parts as in [the new migration](https://github.com/Sylius/Sylius/pull/13847/files#diff-3cb6fdc5453be1e603674a4a526fba1367f0c19c1c0221a531e0fe167bc30ae6) by removing them
- relaunched CD  with included migration job/task

hope this helps

**Comment by xelaris** [comment]
@raneomik thank you for confirming this is an actual issue, not only in our setup. Indeed I raised this issue to find a solution, which doesn't involve manual steps. We worked around this issue by adding the migration manually. Something like
`php bin/console doctrine:migrations:version 'Sylius\Bundle\CoreBundle\Migrations\Version20220407131547' --add`

**Comment by lchrusciel** [comment]
hey folks, thanks for raising this issue and sharing a workaround for others. 

if you have any proposals on how to fix it, any PR would be more than welcome.

**Comment by Ferror** [comment]
I think there is no better solution than marking the migration as already executed:
```bash
bin/console doctrine:migrations:version "Sylius\Bundle\CoreBundle\Migrations\Version20220407131547" --add --no-interaction
```

On one hand, we didn't make migration and got the issue that the database schema is not up to date, and on the other hand, we got the issue that if somebody fixed it then they got an error 😢
