### ISSUE TITLE
OrderItemQuantityModifier should call the processor in the `modify` method

### ISSUE THREAD

**Issue by PILLOWPET** [Sylius/Sylius#14010]
I'm working on a Sylius project in which we send requests to update the quantity of the items on the cart page.
Something I noticed is that most of the services/controllers that are using the Sylius `OrderItemQuantityModifier` call the processor right after calling the `modify` method. 

**Describe the proposed solution**

The `modify` method of the `OrderItemQuantityModifier`  should call the orderProcessor just like the `addToOrder` method of the `OrderModifier`

**Describe alternatives you've considered**

I've considered calling the orderProcessor right after using the `modify` method but since I plan on using this method quite a few times, it means I have to think about calling the processor every time.

**Additional context**

I wonder if there is a reason why the processors are not called in the `OrderItemQuantityModifier`

**Comment by vvasiloi** [comment]
OrderItemQuantityModifier can be called multiple times during a request and you don't want to call the processor every time.
If you have 20 products in cart and change the quantity of all of them, then the order will be processed 20 times. :)

**Comment by PILLOWPET** [comment]
Hum I see I guess this is specific to our implementation since we update the cart asynchronously every time a quantity is updated by the user. 

However, the same can be said about the `OrderModifier`'s `'addToOrder` method , we could imagine that multiple articles get added to a cart in a single request (for instance in a reorder request).

**Comment by vvasiloi** [comment]
There is no such thing in Sylius out-of-the-box, you can only add one item at a time.

**Comment by vvasiloi** [comment]
Anyway, that's an argument in the other direction, i.e. remove the call to the order processor from the order modifier.

**Comment by PILLOWPET** [comment]
I agree, the argument is that the modifiers should be consistent in their behaviors and if one processes the order then all of them should too.

**Comment by coldic3** [comment]
Hey @PILLOWPET,
the issue seems resolved. I'm closing it for now but feel free to reopen it if you still have a similar problem :woman_dancing:
