### ISSUE TITLE
Promotions channels are not validated then Promotion Coupon is applied

### ISSUE THREAD

**Issue by andriusvo** [Sylius/Sylius#14087]
**Sylius version affected**: All versions

**Description**  
Promotions channels are not validated then Promotion Coupon is applied

**Steps to reproduce**  
1. Create a Promotion with coupons
2. Disable all channels
3. Enter a promotion coupon code in cart
4. Promotion coupon code is applied to order (which is incorrect), but promotions are not distributed on items (which is correct)

<img width="1133" alt="Screenshot 2022-06-15 at 10 36 57" src="https://user-images.githubusercontent.com/28906026/173770423-f610db2b-56dd-431f-a860-9253df857c51.png">

<img width="1142" alt="Screenshot 2022-06-15 at 10 38 02" src="https://user-images.githubusercontent.com/28906026/173770449-2c369cec-1daf-4c24-a8fe-b508e721f68a.png">

**Possible Solution**  
Implement new PromotionEligibilityChecker, which will check for current channel.

**Comment by NoResponseMate** [comment]
Thanks for noticing the issue @andriusvo 🍻

**Comment by TheMilek** [comment]
Hi @andriusvo,
I'm closing this issue as it should be solved by https://github.com/Sylius/Sylius/pull/14237
Feel free to reopen if you need 💃🏽
