### ISSUE TITLE
[Bug][Doctrine] Wrong schema update for PHP enum mapped property 

### ISSUE THREAD

**Issue by SVillette** [Sylius/Sylius#14097]
**Sylius version affected**: 1.11

**Description**  
When PHP 8.1 enums are used with doctrine (`enumType`), the command `doctrine:schema:validate` returns an error as database does not correspond to mapping (only for Doctrine) and `doctrine:schema:update --dump-sql` always propose the changes for the enum column (e.g. `ALTER TABLE delivery_configuration CHANGE type type VARCHAR(255) NOT NULL;`).

**Steps to reproduce**  
- Create an enum 
- Use the enum as a new typed property in any entity
- Add the following mapping
```    
 type:
      type: string
      enumType: App\Entity\Delivery\DeliveryType
```
- Run `doctrine:schema:validate` or `doctrine:schema:update --dump-sql`

**Possible Solution**  
After a some research, I found that `doctrine/dbal:2.x` was the cause of this issue.
A possible solution is to migrate to `doctrine/dbal:3.x`.

**Comment by kkevindev** [comment]
> **Description** When PHP 8.1 enums are used with doctrine (`enumType`), the command `doctrine:schema:validate` returns an error as database does not correspond to mapping (only for Doctrine) and `doctrine:schema:update --dump-sql` always propose the changes for the enum column (e.g. `ALTER TABLE delivery_configuration CHANGE type type VARCHAR(255) NOT NULL;`).

Having the same problem here.

**Comment by coldic3** [comment]
Hey @kkevindev,
could you try using `doctrine/dbal:3.x` and check if it resolves your problem? Regarding @SVillette comment, it should be a solution.

**Comment by jakubtobiasz** [comment]
Hello @SVillette!
I see no response from you, so I consider this issue as staled. If you still experience this problem, just reopen this issue and let me know :).

**Comment by SVillette** [comment]
Hi @jakubtobiasz,
As I said in [this comment](https://github.com/Sylius/Sylius/issues/14097#issuecomment-1161950929), upgrading to `doctrine/dbal:3.x` without updating existing migrations will lead to errors when installing a new Sylius project (as `json_array` does not exist anymore).

I also asked if you (Sylius Core team), wanted me to submit a PR and I had no answer.
So I'm telling you again: Do you agree with the statements in [this comment](https://github.com/Sylius/Sylius/issues/14097#issuecomment-1161950929) ? And if yes, do you want me to open a PR ?

**Comment by SVillette** [comment]
Also, I don't think I can reopen this issue by myself

**Comment by jakubtobiasz** [comment]
@SVillette oh, I thought if you can answer the reopen is also possible :D. I am reopening then. We will take a look :).

**Comment by jakubtobiasz** [comment]
Hi @SVillette and sorry for late response.

I agree with a comment you mentioned, but keep in mind we can't break compatibility with dbal2. If you have a working solution for both dbal2 and dbal3 feel free to create a PR and ping me, I'll do my best to push this topic as smoothly as I can.

**Comment by SVillette** [comment]
Hi @jakubtobiasz, I think we can close this PR now as Sylius supports `doctrine/dbal:^2.7 || ^3.0`

**Comment by kkevindev** [comment]
> Hey @kkevindev, could you try using `doctrine/dbal:3.x` and check if it resolves your problem? Regarding @SVillette comment, it should be a solution.

Nope, still a problem on the the latest version (2.14.1) of [doctrine/orm](https://github.com/doctrine/orm/releases). See https://github.com/doctrine/orm/issues/10505.

**Comment by SVillette** [comment]
You should check which package prevent `doctrine/dbal` from being updated to `^3.0`. I managed to update it on a Sylius project so it does not seem to be a Sylius issue anymore.

`composer why-not doctrine/dbal ^3.0`

**Comment by kkevindev** [comment]
> You should check which package prevent `doctrine/dbal` from being updated to `^3.0`. I managed to update it on a Sylius project so it does not seem to be a Sylius issue anymore.
> 
> `composer why-not doctrine/dbal ^3.0`



Thanks for this @SVillette. It was indeed a problem of doctrine/dbal@2 and doctrine/dbal@3 fixed it.
