### ISSUE TITLE
Event missing on /cart/

### ISSUE THREAD

**Issue by Nek-** [Sylius/Sylius#14127]
Sylius is excellent in its event system (related to the ResourceController). But the cart route (`OrderController::sumarryAction`) has no event, this makes it impossible to hook on the process and enforce the need to override the route or use dirty hacks.

Having an event dispatched at this place would be nice, WDYT?

**Describe the proposed solution**
Adding an event on the cart route

**Additional context**
The example we had was to retrieve information for statistical analysis.

**Comment by NoResponseMate** [comment]
Hi @Nek- 
Thanks for noticing that.
Would you be able to open a PR to fix it?
