### ISSUE TITLE
Catalog Promotion: Bug when submitting editing Catalog Promotion Action with Entity Associated with it

### ISSUE THREAD

**Issue by codeDestroyerBcn** [Sylius/Sylius#14137]
**Sylius version affected**:  

Observed on **1.11.0** and **1.11.6**

**Description**  

In our company, in our implementation of Sylius, we have custom tags that are used in a form of **Cart Promotion** and **Catalog Promotion**.

We use the autocomplete **ResourceAutocompleteChoiceType**. Since each tag is indeed a entity that will be later be stored in the
configuration column of **_sylius_catalog_promotion_action_** and **_sylius_promotion_action_** (serialized).

This works well in the Cart Promotion Section > Action, but it does not in the Catalog Promotion one > Action.
In **Catalog Promotion** it works in the creation process but when updating (edit) there is the following bug:

`A cycle was detected. Listeners to the PRE_SET_DATA event must not call getNormData() if the form data has not already been set.`

It seems that the data during the edition submit is handled incorrectly when an entity / collection are being handled. 

**Steps to reproduce**  

![Screenshot 2022-07-07 at 18 30 19](https://user-images.githubusercontent.com/95474458/177824534-440d8d8a-ffa8-414e-8c2b-197cb15af12e.png)

1) Have a tag entity simply with and id and a code.
2) Create Form Type that uses uses the tag entity and has as a parent the `ResourceAutocompleteChoiceType`.
3) Create an action that uses the previous TagConfiguration
3) Create a Catalog Promotion with the the action containing the tag selector and add a tag.
4) The creation must succeed and the edition should fail

**What we observed:**  

1) We have noticed in  in `Sylius\Bundle\PromotionBundle\Form\Type\CatalogPromotionActionType`
in line 66. `$formData->setConfiguration($data['configuration']);`
`$formData` indeed contains entities and collection and `$data['configuration']`  injects into the $formData the data in form of arrays.
We don't have all this form manipulation in the cart section.

2) This only occurs in the edition section (inside the block starting at line 64 of `Sylius\Bundle\PromotionBundle\Form\Type\CatalogPromotionActionType`

`

             if ($formData !== null) {
                    $formData->setType($data['type']);
                    $formData->setConfiguration($data['configuration']);

                    if ($data['type'] === FixedDiscountPriceCalculator::TYPE) {
                        foreach ($data['configuration'] as $channelConfiguration) {
                            if ($channelConfiguration['amount'] === '') {
                                return;
                            }
                        }
                    }

                    if ($data['type'] === PercentageDiscountPriceCalculator::TYPE) {
                        if ($data['configuration']['amount'] === '') {
                            return;
                        }
                    }

                    $form->setData($formData);
                }
`

3) Perhaps the standard transformers do not manipulate entities as they should. As a test we created a transformer doing nothing but returning the receiving data and the edition is persisted correctly.

**Comment by HeahDude** [comment]
>$form->setData($formData);

This call should be useless is `$formData` is an object modified by reference.

However this happens on `PRE_SUBMIT` (see https://github.com/Sylius/Sylius/blob/1.11/src/Sylius/Bundle/PromotionBundle/Form/Type/CatalogPromotionActionType.php#L61), so it should not trigger the reported cycle.

I've searched a little and could not find a `PRE_SET_DATA` listener calling `$form->setData(...)`, which should be the cause of such expected error, as `$event->setData(...)` should be called instead.

**Comment by HeahDude** [comment]
Thanks @JoseGarciaCapitoleConsulting for your input.

Again with an object and unless I'm missing an explicit `by_reference => false` somewhere on such field, calling `$form->setData()` should be necessary.

Could you try to change the mentioned block to:
```php
        if ($formData !== null) {
                $formData->setType($data['type']);
                $formData->setConfiguration($data['configuration']);

                // calling the setters above should be enough
                // remove the rest in that `if`
            }
```

**Comment by ghost** [comment]
> Thanks @JoseGarciaCapitoleConsulting for your input.
> 
> Again with an object and unless I'm missing an explicit `by_reference => false` option somewhere on such field, calling `$form->setData()` should NOT be necessary.
> 
> Could you try to change the mentioned block to:
> 
> ```
>         if ($formData !== null) {
>                 $formData->setType($data['type']);
>                 $formData->setConfiguration($data['configuration']);
> 
>                 // calling the setters above should be enough
>                 // remove the rest in that `if`
>             }
> ```

Tried it, but the exception is still being raised, because the action that alters the data to the point of breaking is doing an `$formData->setConfiguration($data['configuration']);` in this context.

**Comment by NoResponseMate** [comment]
@codeDestroyerBcn 
We're aware of this issue, and are researching possible solutions to be implemented in the future.
