### ISSUE TITLE
[CLI FEATURE] admin create command

### ISSUE THREAD

**Issue by crydotsnake** [Sylius/Sylius#14172]
**Describe the proposed solution**

Hello,

It would be cool to have a `sylius:user:create` command that creates an admin user account for the backend. I'm not quite sure, if this feature has been already asked (But I can well imagine that this has been asked before).

**Additional context**

It would be more helpful and save a lot of time.

And since it is already possible to create an admin user in the backend, it can't hurt to have this option in the CLI as well.

**Comment by oallain** [comment]
Hello,

This is an interesting idea, which can surely help some people.
As for the name of the command `sylius:user:create` is too ambiguous, it should be something like `sylius:admin-user:create`.

Regards,

**Comment by crydotsnake** [comment]
> Hello,
> 
> This is an interesting idea, which can surely help some people. As for the name of the command `sylius:user:create` is too ambiguous, it should be something like `sylius:admin-user:create`.
> 
> Regards,

Yes, I agree with you! @oallain

**Comment by urimarti2610** [comment]
I have created a command that creates and admin using `app:admin:create`

You need to pass the email and the password in the command. Like this:
```
app:admin:create my@email.com myPassword123
```

[Go to Git Command &raquo;](https://github.com/urimarti2610/sylius/commit/b69d3daba274aa221a656748b8d084f38374c2dd)
