### ISSUE TITLE
ProductFilter use in_array strict when checking code

### ISSUE THREAD

**Issue by JeanDavidDaviet** [Sylius/Sylius#14203]
**Sylius version affected**: 1.10.7

**Description**  
When using a promotion with a promotion action of _item_percentage_discount_ and filtering by a specific product, the coupon isn't applied.
The filter check the getCode() function of the item which return a string in the **CodeAwareInterface**, but the products ids listed in the coupon are returned as integer.

**Steps to reproduce**  
Create a promotion
Create an action in this promotion : 
- Type : Item percentage discount
- percentage : eg. 50
- product : any product

**Possible Solution**  
Remove the strict parameter of 
```
if (in_array($item->getProduct()->getCode(), $configuration['filters']['products_filter']['products'], true)) {
```
or cast the ids in `$configuration['filters']['products_filter']['products']` as string, to match the getCode()

**Comment by CoderMaggie** [comment]
As 1.10.x is a no longer supported version you can try reproducing this issue on 1.11.

I did not manage to reproduce it therefore I'm closing this issue. Please reopen if needed.
