### ISSUE TITLE
Sylius Plus has two AvailabilityChecker

### ISSUE THREAD

**Issue by kayue** [Sylius/Sylius#14208]
**Sylius version affected**: 1.10

**Description**  
After installing Sylius Plus, there will be two AvailabilityCheckerInterface available in the project

| Interface | Service | Function |
| ---------- | ----- | --- |
| Sylius\Component\Inventory\Checker\AvailabilityCheckerInterface | alias for "sylius.availability_checker.default" | Retrieve stock from variant.onHand entity |
| Sylius\Plus\Inventory\Application\Checker\AvailabilityCheckerInterface | Sylius\Plus\Inventory\Application\Checker\AvailabilityChecker | Retrieve stock from inventory source |
| sylius.availability_checker | alias for "Sylius\Plus\Inventory\Application\Checker\AvailabilityCheckerInterface" | NA |

For a project upgraded from community edition, I would expect the original `Sylius\Component\Inventory\Checker\AvailabilityCheckerInterface` should be an alias of `sylius.availability_checker` instead of `sylius.availability_checker.default`.

This current behavior requires developer to remember to inject `sylius.availability_checker.default` instead of `AvailabilityCheckerInterface`

**Possible Solution**  

I am fixing this internally by adding interface binding in `services.yml`

**Comment by Zales0123** [comment]
Hello @kayue! As this is a potential bug in SyliusPlus, I suppose, please contact our Team through the support portal or some other Plus-relevant channel of communication :) Thanks!
