### ISSUE TITLE
Frontend Cart Button Unusable w/ Large Carts

### ISSUE THREAD

**Issue by mbabker** [Sylius/Sylius#14229]
**Sylius version affected**: 1.11

**Description**  
With the Semantic UI popup plugin's behavior of not rendering a popup if it can't fit it onto the screen, the cart button on the frontend template becomes unusable with large carts (large being subjective, on a desktop it takes ~15 items with the demo store but on mobile in landscape orientation you can probably do it with 3 or 4 items).

**Steps to reproduce**  
Add a lot of stuff to the cart, eventually clicking the button will no longer render the popup, and your browser console will have a "`Popup: Popup does not fit within the boundaries of the viewport <div id=​"sylius-cart-button" class=​"ui circular cart button">​…​</div>`​" message explaining why.

**Possible Solution**  
- Remove the popup behavior from this button
- Add a secondary cart link that is usable without JavaScript enhancement

**Comment by Zales0123** [comment]
Yes! Indeed there is a bug there. On my resolution it's even for 10 items 😱 We definitely need to fix it, as in such a situation it's impossible to access the cart without typing the URL by yourself. There is a potential solution in [this issue on SemanticUI repo](https://github.com/Semantic-Org/Semantic-UI/issues/3004#issuecomment-171412709). @kulczy can you take a look? Thanks! 🖖
