### ISSUE TITLE
Yarn build: sass error

### ISSUE THREAD

**Issue by Hlavos** [Sylius/Sylius#14224]
**Sylius version affected**: 1.11.7

**Description**  
When installing the new Sylius, according to the documentation, I get an error in the "yarn build" phase.

```bash
Message:

gulp-sass no longer has a default Sass compiler; please set one yourself.
Both the "sass" and "node-sass" packages are permitted.
For example, in your gulpfile:

  const sass = require('gulp-sass')(require('sass'));
```

**Steps to reproduce**  
Clear installation Sylius on debian,
node v16.16.0
yarn 1.22.19

**Possible Solution**  
In files
`src/Sylius/Bundle/AdminBundle/gulpfile.babel.js` and `src/Sylius/Bundle/ShopBundle/gulpfile.babel.js` change sass import 

form
```js
import sass from 'gulp-sass';
```

to
```js
import dartSass from ‘sass’;
import gulpSass from ‘gulp-sass’;
const sass = gulpSass(dartSass);
```

**Comment by zpi12lmm** [comment]
This problem has not been solved for quite a long time. I solved it in a hacky way, so if you are looking for a "here and now" solution, this may help you. You will need to create a shell script, and write commands there that will find the desired line and put the correct expression. For example, it might look like this:

```
#!/bin/sh
set -e

# gulp-sass no longer has a default sass compiler
sed -i "s/import sass from 'gulp-sass';/const sass = require('gulp-sass')(require('sass'));/g" vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/gulpfile.babel.js
sed -i "s/import sass from 'gulp-sass';/const sass = require('gulp-sass')(require('sass'));/g" vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/gulpfile.babel.js
```

Next, you will need to put this script before each executed command in the "scripts" property of your package.json file. For example, if you named your shell script "fix-problems.sh", and placed it in the root of your project, it might look like this for the "build" command (you can also define your own command and then apply it everywhere):

```
{
  "scripts": {
    "pre-action-run": "./fix-problems.sh",
    "build": "yarn pre-action-run && gulp build",
  }
}
```

**Comment by Zales0123** [comment]
@jakubtobiasz I know you've been working with gulp recently, can you take a look at it?

**Comment by DeH4eG** [comment]
@Hlavos did you find this error with `"gulp-sass": "^4.0.1"` ?

Because for me this error occurs if i change `gulp-sass` to `5.x.x` version, because from the 5 version `gulp-sass` started to use `dart sass` instead of `node sass`

**Comment by jakubtobiasz** [comment]
In terms of gulp, we recommend staying with `gulp-sass` on a version below five or (which I highly recommend) moving to Webpack. 

👉🏼 https://docs.sylius.com/en/1.12/cookbook/frontend/migrating-to-webpack-1-11-or-earlier.html

**Comment by DeH4eG** [comment]
Thank you for the link
