### ISSUE TITLE
[API][Feature] `minimumPrice` and `maximumPrice` API platform filters for getting product collection

### ISSUE THREAD

**Issue by gigabites19** [Sylius/Sylius#14235]
The ability to fetch products based on a price range is a common requirement for e-commerce applications

**Comment by Zales0123** [comment]
Hello Giga! Indeed, it is 😄 We're focusing right now to cover all UI shop features in our new API, therefore such a functionality is not in our nearest plans (as we do not have it in UI as well :dancer:). Nevertheless, I strongly encourage you to propose such a feature if you would be customizing it in your application.

cc @CoderMaggie @lchrusciel for further prioritization information 🖖

**Comment by gigabites19** [comment]
Hi @Zales0123. Since opening this issue I have discovered that [APIP actually has range filter](https://api-platform.com/docs/core/filters/#range-filter) and it also allows [filtering on nested properties](https://api-platform.com/docs/core/filters/#filtering-on-nested-properties) but still having this configuration abstracted away in the core would be nice. I will gladly open a PR if the feature would be accepted.

**Comment by Rafikooo** [comment]
Hi @gigamarr, you can surely propose a solution. We're following this issue, so if you open a PR you should get feedback in a while. Just remember to test your code well 👍 🚀

**Comment by jakubtobiasz** [comment]
Hi 🙋🏼‍♂️!

As we are not planning to implement this in the nearest future I am closing this issue. If you decide to implement this on your own feel free to mention this issue and ping us.
