### ISSUE TITLE
sylius_channel_pricing_catalog_promotions empty

### ISSUE THREAD

**Issue by TELLO0815** [Sylius/Sylius#14241]
| Q                | A      |
|------------------|--------|
| Bug report?      | no/yes |
| Feature request? | no/yes |
| BC Break report? | no/yes |
| RFC?             | no/yes |
| Sylius version   | 1.11.7  |

With sync and async messenger...
Catalog Promotion is not working. sylius_channel_pricing_catalog_promotions empty. 

With async I get the following message in the messages_message table:
`O:36:\"Symfony\\Component\\Messenger\\Envelope\":2:{s:44:\"\0Symfony\\Component\\Messenger\\Envelope\0stamps\";a:1:{s:46:\"Symfony\\Component\\Messenger\\Stamp\\BusNameStamp\";a:1:{i:0;O:46:\"Symfony\\Component\\Messenger\\Stamp\\BusNameStamp\":1:{s:55:\"\0Symfony\\Component\\Messenger\\Stamp\\BusNameStamp\0busName\";s:16:\"sylius.event_bus\";}}}s:45:\"\0Symfony\\Component\\Messenger\\Envelope\0message\";O:56:\"Sylius\\Component\\Promotion\\Event\\CatalogPromotionUpdated\":1:{s:4:\"code\";s:5:\"sale\";}}`

**[OK] Consuming messages from transports "main"** - but no success. Any idea?

**Comment by TELLO0815** [comment]
Sorry I found it... The problem was that I left the minimum price equal to the original price!!!

**Comment by Zales0123** [comment]
Great @TELLO0815 you've managed to make it work :) ☮️ 🖖
