### ISSUE TITLE
Variant position does not affect frontend display

### ISSUE THREAD

**Issue by ehibes** [Sylius/Sylius#14244]
**Sylius version affected**: 1.11.x

**Description**  

When I create a new option (xs for size for example), I generate a new shirt variant with xs option and change its position to move it first.
On frontend, the variant select tag does not match backend positions.

**Steps to reproduce**  

1. Add a new option
<img width="1048" alt="Capture d’écran 2022-08-19 à 10 59 16" src="https://user-images.githubusercontent.com/487124/185584764-b9a24e47-6941-4273-8bba-663eccbbd1bb.png">

2. Generate a product variant with this option and move it to first place
<img width="1207" alt="Capture d’écran 2022-08-19 à 10 59 38" src="https://user-images.githubusercontent.com/487124/185584767-bc1952e2-2693-424b-bcf3-3f59cb2eff5c.png">

3. Result in frontend
<img width="1183" alt="Capture d’écran 2022-08-19 à 10 59 48" src="https://user-images.githubusercontent.com/487124/185584773-d2f35804-a876-4286-98b6-e4005a089d7a.png">

**Possible Solution**  

On `AvailableProductOptionValuesResolver` class, we should base returned Options on variant position instead of option id.

```
        return $productOption->getValues()->filter(
            static function (ProductOptionValueInterface $productOptionValue) use ($product) {
                foreach ($product->getEnabledVariants() as $productVariant) {
                    if ($productVariant->hasOptionValue($productOptionValue)) {
                        return true;
                    }
                }

                return false;
            },
        );
```

**Comment by Zales0123** [comment]
Hello @ehibes! As far as I see, the problem is you have an option "Variant selection method" selected as "Options matching". It means, there is a set of **options** displayed to be selected instead of product **variants**. Obviously, the position of variants cannot influence the positions of options in any way. To see the result of your change, you would have to change the mentioned property to "Variant choice".

Thanks for being a part of Sylius Community 🎉

**Comment by ehibes** [comment]
So @Zales0123, could we imagine the possibility of rearranging the option values ?

**Comment by ehibes** [comment]
#13467

**Comment by panakour** [comment]
I had the same requirements and I did it in the AvailableProductOptionValuesResolver like so:

```php
<?php

declare(strict_types=1);

namespace App\Resolver;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Sylius\Component\Product\Model\ProductInterface;
use Sylius\Component\Product\Model\ProductOptionInterface;
use Sylius\Component\Product\Resolver\AvailableProductOptionValuesResolverInterface;

final class AvailableProductOptionValuesResolver implements AvailableProductOptionValuesResolverInterface
{
    public function resolve(ProductInterface $product, ProductOptionInterface $productOption): Collection
    {
        if (!$product->hasOption($productOption)) {
            throw new \InvalidArgumentException(
                sprintf(
                    'Cannot resolve available product option values. Option "%s" does not belong to product "%s".',
                    $productOption->getCode(),
                    $product->getCode(),
                )
            );
        }

        $variants = $product->getEnabledVariants()->toArray();

        $availableValues = [];

        foreach ($variants as $productVariant) {
            foreach ($productVariant->getOptionValues() as $optionValue) {
                if ($optionValue->getOption() === $productOption) {
                    if (!in_array($optionValue, $availableValues, true)) {
                        $availableValues[] = $optionValue;
                    }
                }
            }
        }

        return new ArrayCollection($availableValues);
    }
}

```
I just return the options in the the same order as they are assigned in the relation. 

https://github.com/Sylius/Sylius/issues/13467 A position property on optionValues will be a good addition.
