### ISSUE TITLE
[ApiBundle] Bug with the ProductVariantNormalizer, while having ApiProperty readableLink: false

### ISSUE THREAD

**Issue by vygis900** [Sylius/Sylius#14259]
**Sylius version affected**: 1.11.6

**Description**  
Bug in ApiBundle.
While having a variable with `#[ApiProperty(readableLink: false)]` and  using `ProductVariantNormalizer` function `normalize` malfunctions, because it gives a string while it wants an array. 
Specifically  `$data = $this->normalizer->normalize($object, $format, $context);`

The error is this
> Cannot access offset of type string on string at /srv/sylius/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Serializer/ProductVariantNormalizer.php:57)

**Steps to reproduce**  
Create a var using `ProductVariantInterface` or so, give it a ApiProperty with `readableLink: false`, and try it on a GET request.

**Possible Solution**  
Implement some sort of checking if the $data is array if not return $data as array.

**Comment by Zales0123** [comment]
Hello @vygis900! Thanks for the bug report. We will try to reproduce it and come back with some fix/comment. Or you can propose a fix by yourself, it would be great :D 🎉

**Comment by Rafikooo** [comment]
Hi @vygis900,
I tried to recreate your case, unsuccessfully. Please take a glance at my commit if I reproduced your case correctly: https://github.com/Rafikooo/Sylius-Standard/commit/0abc92326bff43419a1232114aee760903f60cd1

It works both for`readableLink: true` and `readableLink: true`
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/40125720/206738839-8048cf7d-690f-47ea-a1bd-a148459bcaf7.png">

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/40125720/206740314-a7b24e10-beaf-4807-92e4-9014cf047175.png">

**Comment by Rafikooo** [comment]
Hello @vygis900, as we haven't heard from you for a while, we assume that this issue isn't valid. Don't hesitate to reopen or create another one if you have any additional questions 🚀
