### ISSUE TITLE
Allow tagging of products

### ISSUE THREAD

**Issue by loevgaard** [Sylius/Sylius#14269]
Allow the tagging of products. This could help users easily select a distinct group of products in various scenarios, i.e. promotions, creating landing pages and much more.

**Comment by vvasiloi** [comment]
What would be the advantage over using taxons?

**Comment by wadjeroudi** [comment]
I guess that taxons need to be displayed in the tree whereas tags won't.

**Comment by loevgaard** [comment]
There's the definitional difference (at least imo). '[Taxonomy](https://en.wikipedia.org/wiki/Taxonomy) is the practice and science of categorization or classification.' whereas I believe tagging _can_, but doesn't have to categorize or classify products.

But then there's the (imo) most important thing: The practical difference. In Sylius you use taxons as categories basically. You have the taxonomy tree that indicates the tree structure and for a lot of stores I think it also mimics their navigation. To use taxonomies as tags would completely bloat this tree and you would be looking for a different solution anyway. That solution is tags ;)

**Comment by vvasiloi** [comment]
You can create as many trees as you want, you don't have to use the category tree for tags.
Just create another tree called Tags. We can ship it with the default Sylius fixtures.
It seems redundant to me to introduce a new concept to solve this problem.
I have done this in the past and had no problems. Change my mind. 😄
![image](https://user-images.githubusercontent.com/7114562/187889791-bb68bc48-c0f5-44ed-8b31-da875b4e7f5a.png)
![image](https://user-images.githubusercontent.com/7114562/187890051-1069d998-7a14-447e-a4dd-27783d04b856.png)

**Comment by loevgaard** [comment]
I can only win this argument with using practical arguments, because I agree that _theoretically_ you're right. But here are a few scenarios for you :D

1. Create 5,000 tags and let me see you load that tree
2. Create 5,000 tags and let me see you add 20 tags to a product
3. Add 20 _new_ tags to a product easily and intuitively. It's not easy and intuitively if you have to 1) create those 20 tags _first_, then 2) save your product without the tags (because you were already editing), then 3) opening the product for editing again to select those 20 tags without an autocomplete.

You can probably counter these arguments, but deep down, Victor... :D

**Comment by vvasiloi** [comment]
The practical issues can be solved on top of the taxonomy.
1. That tree is lazy loaded I believe, isn't it?
2. and 3. Add a text input where you write keywords and hit Enter/Tab, with typeahead/autocomplete/suggestions.

You don't need a new concept, just some UI/UX adjustments.

**Comment by vvasiloi** [comment]
@loevgaard deep down I know that @CoderMaggie will say: just make a plugin. 😉

**Comment by Zales0123** [comment]
Hello Joachim! 😄 As usually - the idea is interesting, but a no-go for us in the nearest future. There are just other priorities we need to focus on :dancer: 

Maybe such a discussion should happen in the [Discussions](https://github.com/Sylius/Sylius/discussions) tab? 🤔 We do not use it very much, but maybe it's a good idea to start using it.

cc @CoderMaggie

**Comment by loevgaard** [comment]
Thanks for the quick response, Mateusz :)

I will just close for now.
