### ISSUE TITLE
SalesDataProvider for Admin Dashboard produces non-standard sql which fails.

### ISSUE THREAD

**Issue by tdestro** [Sylius/Sylius#14266]
**Sylius version affected**: 1.12.0

**Description**  
https://github.com/Sylius/Sylius/blob/641c8060cca41b4ed083f31991e74f4f2a4f8ae6/src/Sylius/Component/Core/Dashboard/SalesDataProvider.php#L43-L135

The following lines above produce non-standard sql which fails on postgres 12.

An exception occurred while executing a query: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "sclr_1" does not exist
LINE 1: ..._.channel_id = $2 GROUP BY sclr_1, sclr_2 HAVING (sclr_1 = $...

[The manual clarifies here:](https://www.postgresql.org/docs/current/sql-select.html#SQL-SELECT-LIST)

An output column's name can be used to refer to the column's value in ORDER BY and GROUP BY clauses, but not in the WHERE or HAVING clauses; there you must write out the expression instead.

[and on stack exchange here. ](https://dba.stackexchange.com/questions/225874/using-column-alias-in-a-where-clause-doesnt-work)

**Steps to reproduce**  
1. Deploy sylius to postgres
2. attempt loading of admin dashboard.

**Possible Solution**  

**Do not use aliases in the having clauses**.

 For year, month, week , spell everything out instead, for example.

                    ->andHaving($queryBuilder->expr()->orX(
                        'YEAR(o.checkoutCompletedAt) = :startYear AND YEAR(o.checkoutCompletedAt) = :endYear AND WEEK(o.checkoutCompletedAt) >= :startWeek AND WEEK(o.checkoutCompletedAt) <= :endWeek',
                        'YEAR(o.checkoutCompletedAt) = :startYear AND YEAR(o.checkoutCompletedAt) != :endYear AND WEEK(o.checkoutCompletedAt) >= :startWeek',
                        'YEAR(o.checkoutCompletedAt) = :endYear AND YEAR(o.checkoutCompletedAt) != :startYear AND WEEK(o.checkoutCompletedAt) <= :endWeek',
                        'YEAR(o.checkoutCompletedAt) > :startYear AND YEAR(o.checkoutCompletedAt) < :endYear'
                    ))

**Comment by vvasiloi** [comment]
This was fixed already fixed in https://github.com/Sylius/Sylius/pull/13432.
