### ISSUE TITLE
[API] disabling a subresource endpoint

### ISSUE THREAD

**Issue by laurentdabbb** [Sylius/Sylius#14268]
**Sylius docs version**: latest

[https://docs.sylius.com/en/1.12/customization/api/customizing_endpoints_using_yaml.html](https://docs.sylius.com/en/1.12/customization/api/customizing_endpoints_using_yaml.html)

Hi,

I use Sylius 1.11. I want to disable some subresource endpoints.   

By overriding the subresourceOperation in my resource configuration file, I'm able to disable the Sylius subresource endpoint.  

```yaml
subresourceOperations: 
    shop_billing_data_get_subresource:
        enabled: false
```
It works fine.  

But, subresource is also declared on the resource property :  
```
<property name="shopBillingData" readable="true" writable="true">
    <subresource resourceClass="%sylius.model.shop_billing_data.class%" collection="false" />
</property>
```
So, Api Platform auto-generate an endpoint for this subresource...  

Unfortunately, I can't remove the subresource on property in my YAML file.  
It seems that we can't remove a subresource declaration on property in API Platform 2.6.8. And I don't understand why...  
I tried to nullify subresource on property :  
```
properties:
    shopBillingData:
        subresource: ~
```
But it is not taken into account. If a property already has a subresource declared, we can't override it :
https://github.com/api-platform/core/blob/2.6/src/Metadata/Property/Factory/ExtractorPropertyMetadataFactory.php#L119

Sylius doc specify a warning about overriding subresource :
**_To remove subresource from Sylius, create new xml file with copied resource class and remove its subresource operations_** ([see commit here](https://github.com/Sylius/Sylius/pull/13948))
=> This doesn't work for me since I upgrade to 1.11. It was working on 1.10, I was able to override XML configuration files. But since 1.11, my XML files are just ignored for already declared resources. I can redefine endpoints via YAML but not by overriding XML files :/

Also, even if this solution worked, it would just be a "bad hack". The goal of merging (extending or overwriting) endpoint configuration is precisely to not override all the configuration file and provide more granularity.

Please, could you explain why I can't disable a subresource on a property ? Could it be considered as a bug on API Platform side ? 
Is there a solution to entirely disable the subresource on Sylius side ?

thanks in advance ;-)

cc @SirDomin

**Comment by coldic3** [comment]
Hey @laurentdabbb, I've recently opened a PR with a fix for overriding XML configs https://github.com/Sylius/Sylius/pull/14236. Can you take a look if it's going to fix your problem? Also, it's fixed in API Platform 2.7 but the PR I've linked should fix it in lower versions including the current one :slightly_smiling_face:

**Comment by coldic3** [comment]
And I forgot about a workaround that I have 🙃

Please try to add `%kernel.project_dir%/config/api_resource` (or any other dir name) to the `api_platform.mapping.paths` in `config/packages/api_platform.yaml` and put XML file you want to override into the `config/api_resource`.

**Comment by laurentdabbb** [comment]
Hi @coldic3,

Thank you for your answer.
I can confirm your fix is working👍 
Now, I'm able to override full XML configuration and extend/add/remove endpoints in YAML at the same time : very nice 😊 

Your workaround also works and I think I'll keep this approach as I find it more elegant :
- overriding full XML files in `%kernel.project_dir%/config/api_resources` 
- extending endpoints with YAML in `%kernel.project_dir%/config/api_platform` 

_(of course, both paths have to be added to the `api_platform.mapping.paths` in `config/packages/api_platform.yaml`)_

So all is OK and my problem is resolved 😆 


However, I still think it's not normal/optimized to have to overwrite the entire XML file to be able to remove the subresource attached to a property. The purpose of extending endpoints via YAML is to only override what we need and continue to benefit from future enhancements/endpoints.
FYI I opened an issue on API Platform related to that : https://github.com/api-platform/core/issues/4906

I'm not sure if it's better to wait for API Platform to provide a solution/fix to allow overriding subresource on a property or if this "patch" should be made by Sylius to improve DX 😏 

Thanks 😉

**Comment by coldic3** [comment]
I'm glad your problem is resolved!

Indeed, the YAML configuration should be able to remove subresources. We spent some time dealing with it and didn't find any elegant solution, but feel free to propose a solution for it if you have some and PRs are welcome as well. However, in [API Platform 3 subresources are completely reorganized](https://github.com/api-platform/core/blob/main/docs/adr/0000-subresources-definition.md) and I hope it will resolve this problem :)
