### ISSUE TITLE
[BUG] Error in product variant choice type when variant has no name

### ISSUE THREAD

**Issue by vvasiloi** [Sylius/Sylius#14276]
https://github.com/Sylius/Sylius/blob/26139f237e699436a2cb0999f0c3049dff350e38/src/Sylius/Bundle/ProductBundle/Form/Type/ProductVariantChoiceType.php#L40

This was introduced in https://github.com/Sylius/Sylius/pull/13268.
Before that, it was using ProductVariant's `__toString`, which wasn't returning the variant's name but the product name and the options set.
The new code returns the variant's name, which is not always set, so it can return null, which will throw an error because the function's return type is `string`.

**Comment by sabat24** [comment]
We fixed that in our project by introducing a new method in `ProductVariant` entity:

```php
// get product name if variant name is empty
public function resolveName(): ?string
{
    return empty($this->getName()) ? $this->getProduct()?->getName() :
$this->getName();
}
```

We added it directly to the entity, because we use it widely in Twig's.
