### ISSUE TITLE
Unused template

### ISSUE THREAD

**Issue by Florian-Merle** [Sylius/Sylius#14275]
**Sylius version affected**: 1.11

**Description**  
I'm not 100% sure, but I think [src/Sylius/Bundle/AdminBundle/Resources/views/Customer/Show/_menu.html.twig](https://github.com/Sylius/Sylius/blob/1.12/src/Sylius/Bundle/AdminBundle/Resources/views/Customer/Show/_menu.html.twig)is not used anymore

**Comment by vvasiloi** [comment]
I couldn't find a usage.
