### ISSUE TITLE
Product bundles in core?

### ISSUE THREAD

**Issue by loevgaard** [Sylius/Sylius#14271]
Would Sylius consider having product bundles in the core?

For reference a product bundle is a product that resembles multiple (sub) products. Here is an example. You have two products `TABLE`, `CHAIR`, but you want to offer your customer a 'family table' with some discount and you create a product (bundle) named `FAMILY_TABLE` having 1 x `TABLE` and 6 x `CHAIR` in it.

Here is an plugin doing it: https://github.com/BitBagCommerce/SyliusProductBundlePlugin

**Comment by Zales0123** [comment]
Hello Joachim! Thank you for this idea. It's definitely a useful feature, but as far as I know, we do not have it in our development plans for the predictable future. cc @CoderMaggie just to be sure ;) Maybe someday! 🚀 

I'm closing it, as it's not relevant for now, please reopen if you feel... it should be opened 😅

**Comment by loevgaard** [comment]
Yeah, just to clarify. Thank you, Mateusz :)
