### ISSUE TITLE
Product taxon position don't affect parent taxon

### ISSUE THREAD

**Issue by ehibes** [Sylius/Sylius#14308]
**Sylius version affected**: 1.11

**Description**  

On the demo store, when I change product position for women t-shirts in `t-shirts/women` taxon, the frontend is reorganized according to the chosen positions. If I make the same on `t-shirts` taxon, the frontend is not affected.  
**Steps to reproduce**  

<img width="1222" alt="Capture d’écran 2022-09-15 à 10 21 27" src="https://user-images.githubusercontent.com/487124/190362773-2b32add9-a28e-44d5-8339-6a0e175e96c4.png">
<img width="1146" alt="Capture d’écran 2022-09-15 à 10 03 24" src="https://user-images.githubusercontent.com/487124/190362829-92b65059-37c2-490e-93b4-54beee5b770e.png">

**Comment by loic425** [comment]
@ehibes Sorry, I've removed your screenshots. Could you add them again please?

**Comment by Rafikooo** [comment]
Hello @ehibes,
thank you for reporting the issue. We confirm that the bug exists. Repair is not in our current priorities, so if you could, don't hesitate to contribute to Sylius. A behat scenario covering this case or even a PR with a solution would be welcome 🚀

**Comment by GSadee** [comment]
Hi @ehibes, I've just wanted to let you know that we will take care of it 😃

**Comment by ehibes** [comment]
I just searched a bit on my side, and it seems that the query returns duplicate products with different positions.
It must come from writing joins, but I'm not expert enough 😄 
![image](https://user-images.githubusercontent.com/487124/197743953-a28e9853-b336-4287-9519-c09e7613cf8e.png)

**Comment by ehibes** [comment]
@Rafikooo @GSadee I made a failing behat scenario to explain the case...
https://github.com/ehibes/Sylius/tree/parent_taxon_product_position
