### ISSUE TITLE
Downloadable product #7180

### ISSUE THREAD

**Issue by skipper-henrik** [Sylius/Sylius#14300]
I don’t see why the proposal/request should be closed. 

[Downloadable product #7180](https://github.com/Sylius/Sylius/issues/7180)

**Comment by TheMilek** [comment]
Hi @eltnap! 
As far as I know, We have no plans to introduce it in the nearest future 💃🏽 
You can look for solutions here: https://docs.sylius.com/en/1.11/book/products/products.html?highlight=virtual#virtual-product-variants-that-do-not-require-shipping
