### ISSUE TITLE
[1.12-BUG-HUNTING] Undefined method called in ImagesRemoveListener

### ISSUE THREAD

**Issue by vasilvestre** [Sylius/Sylius#14347]
**Sylius version affected**: 1.12.0-alpha

**Description**  
Some migration makes ImagesRemoveListener call `getObjectManager` method on `Doctrine\ORM\Event\OnFlushEventArgs` which doesn't exists anymore. `getEntityManager` is now used.

**Steps to reproduce**  
Run sylius-standard migration, the Version20161209095131 fails

**Possible Solution**  
Replace method getObjectManager with getEntityManager on listener & other code

**Comment by vasilvestre** [comment]
https://github.com/Sylius/Sylius/pull/14346 should fix this

**Comment by jakubtobiasz** [comment]
Hi @vasilvestre 🙋🏼‍♂️!
Thanks for your report. This bug also affects `1.11` branch and #14346 is aimed to fix this :D.

**Comment by Rafikooo** [comment]
Since https://github.com/Sylius/Sylius/pull/14346 is already merged, we can close this issue. This change will be available once the new version of Sylius 1.12 will be tagged
