### ISSUE TITLE
# unable to fetch the response from the backend: malformed MIME header: missing colon: "#4 {main}"

### ISSUE THREAD

**Issue by lvwuwei** [Sylius/Sylius#14342]
# unable to fetch the response from the backend: malformed MIME header: missing colon: "#4 {main}"
SERVER issue with server callback error="unable to fetch the response from the backend: malformed MIME header: missing colon: \"#4 {main}\""
[Web Server ] Sep 21 21:16:24 |ERROR  | SERVER GET  (502) /admin ip="176.191.129.xxx"
[PHP-FPM    ] NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\Dotenv\putenv() in /www/wwwroot/xxx.fr/vendor/symfony/dotenv/Dotenv.php:204
[PHP-FPM    ] Stack trace:
[PHP-FPM    ] #0 /www/wwwroot/xxx.fr/vendor/symfony/dotenv/Dotenv.php(570): Symfony\Component\Dotenv\Dotenv->populate()
[PHP-FPM    ] #1 /www/wwwroot/xxx.fr/vendor/symfony/dotenv/Dotenv.php(114): Symfony\Component\Dotenv\Dotenv->doLoad()
[PHP-FPM    ] #2 /www/wwwroot/xxx.fr/config/bootstrap.php(16): Symfony\Component\Dotenv\Dotenv->loadEnv()
[PHP-FPM    ] #3 /www/wwwroot/xxx.fr/public/index.php(7): require('...')
[PHP-FPM    ] #4 {main}
[PHP-FPM    ]   thrown in /www/wwwroot/xxx.fr/vendor/symfony/dotenv/Dotenv.php on line 204

**Comment by Rafikooo** [comment]
Hello @lvwuwei, if you have any problems with your app, do not hesitate to ask our Slack community for help:
https://sylius-devs.slack.com

Greetings 💃
