### ISSUE TITLE
Attempted to call an undefined method in Sylius 1.18

### ISSUE THREAD

**Issue by tulik** [Sylius/Sylius#14356]
**Sylius version affected**: 1.11.7

**Description**  
When running `bin/console sylius:install` there is an error:
```
In ImagesRemoveListener.php line 40:
  Attempted to call an undefined method named "getObjectManager" of class "Doctrine\ORM\Event\OnFlushEventArgs".
```

**Steps to reproduce**  
A fresh Sylius installation doesn't show the error, but it occurs when additional plugins are installed.

**Possible Solution**  
In ImagesRemoveListener.php line 40 replace 
```
$event->getObjectManager()
```
with
```
$event->getEntityManager()
```

**Comment by Rafikooo** [comment]
Hello @tulik, 
thank you for reporting the issue. It has already been fixed here:
https://github.com/Sylius/Sylius/issues/14347

Sylius 1.11 isn't tagged with this change yet, so if you need this change right now, just change the ORM version to `"doctrine/orm": "^2.13"`

Greetings 🚀
