### ISSUE TITLE
Wrong name in sylius_order state machine

### ISSUE THREAD

**Issue by UlrichHP** [Sylius/Sylius#14353]
**Sylius version affected**: 1.10-1.12

**Description**  
If you go to src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_order.yml at the line 95, there is a syntax error.
It should be `sylius_cancel_order` and not `sylis_cancel_order`.

**Comment by UlrichHP** [comment]
I didn't see the PR #13689. Will it be merged soon ?

**Comment by Rafikooo** [comment]
Hi @UlrichHP, since this topic has already been covered [here](https://github.com/Sylius/Sylius/issues/13688) we'll close this issue :)
