### ISSUE TITLE
[Bug Fix] Loading doctrine fixtures 

### ISSUE THREAD

**Issue by Trip09** [Sylius/Sylius#1436]
Command was failing :
> app/console doctrine:fixtures:load --env=dev
> app/console sylius:install --env=dev

![bug-fix-doctrine-fixtures](https://cloud.githubusercontent.com/assets/5668134/2809556/c09bba8e-cd75-11e3-8179-9632bf8cb01d.png)

**Comment by stloyd** [comment]
@pjedrzejewski @aRn0D ping about closing...
