### ISSUE TITLE
Sylius override product Integrity constraint violation

### ISSUE THREAD

**Issue by Bahlaouane-Hamza** [Sylius/Sylius#1438]
I'm trying to override the product bundle, i did it successfuly but getting an error when trying to delete a parent entity that have products as childs

here's the mapping file product.orm.xml

    <?xml version="1.0" encoding="UTF-8"?>
    <doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
                      xmlns:gedmo="http://gediminasm.org/schemas/orm/doctrine-extensions-mapping">

        <mapped-superclass name="Sylius\Component\Product\Model\Product" table="sylius_product">
            <id name="id" column="id" type="integer">
                <generator strategy="AUTO" />
            </id>

            <field name="name" column="name" type="string">
                <gedmo:versioned />
            </field>
            ...
        </mapped-superclass>

    </doctrine-mapping>

and here's my product.orm.xml file

    <?xml version="1.0" encoding="UTF-8"?>
    <doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
                      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                      xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping
                                          http://doctrine-project.org/schemas/orm/doctrine-mapping.xsd">
        <entity name="WeShop\Bundle\CoreBundle\Entity\Product" table="sylius_product">
            <many-to-one field="boutique" target-entity="WeShop\Bundle\BoutiqueBundle\Entity\Boutique" inversed-by="produits">
                <join-column name="boutique_id" referenced-column-name="id" nullable="true" onDelete="SET NULL" />
            </many-to-one>
        </entity>
    </doctrine-mapping>

in WeShop\Bundle\BoutiqueBundle\Entity\Boutique i do have

    <?php
    namespace WeShop\Bundle\BoutiqueBundle\Entity;
    use Sylius\Component\Core\Model\ProductInterface as ProductInterface;
    use Doctrine\ORM\Mapping as ORM;
    use Doctrine\Common\Collections\ArrayCollection;
    
    class Boutique
    {
        private $produits;
    
        public function __construct(){
            $this->produits = new ArrayCollection();
        }
    
        public function getProduits(){
            return $this->produits;
        }
    
        public function setProduits(ProductInterface $produit){
            $this->produits[] = $produit;
            return $this;
        }
    
    }

and in WeShop\Bundle\CoreBundle\Entity\Product i do have this

    <?php
    
    namespace WeShop\Bundle\CoreBundle\Entity;
    use WeShop\Bundle\CoreBundle\Model;
    use WeShop\Bundle\BoutiqueBundle\Entity\BoutiqueInterface as BoutiqueInterface;
    use Sylius\Component\Core\Model\Product as BaseProduct;
    
    class Product extends BaseProduct
    {
        private $boutique;
    
        public function getBoutique()
        {
            return $this->boutique;
        }
    
        public function setBoutique(BoutiqueInterface $boutique = null)
        {
            $this->boutique = $boutique;
    
            return $this;
        }
    }

Working with the boutique entity (store), i can manipulate it the way i want everything is working, now the problem is when i try to delete it i get 

    An exception occurred while executing 'DELETE FROM weshop_boutique WHERE id = ?' with params [2]:
    
    SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`sylius_dev`.`sylius_product`, CONSTRAINT `FK_677B9B74AB677BE6` FOREIGN KEY (`boutique_id`) REFERENCES `weshop_boutique` (`id`))

Please note that a boutique (store) can have multiple products in it, but a product can only be child for one boutique (store)

I do have a documents bundle with the same logic and when i try to delete the boutique (knowing that in the table sylius_product there's no rows referencing the boutique {null} ), the documents get deleted

here's my documents orm xml file 

    <?xml version="1.0" encoding="utf-8"?>
    <doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping http://doctrine-project.org/schemas/orm/doctrine-mapping.xsd">
      <entity table="weshop_documents" repository-class="WeShop\Bundle\DocumentsBundle\Entity\DocumentsRepository" name="WeShop\Bundle\DocumentsBundle\Entity\Documents">
        <id name="id" type="integer" column="id">
          <generator strategy="AUTO"/>
        </id>
        <field name="intitule" type="string" column="intitule" length="255"/>
        <field name="url" type="string" column="url" length="255"/>
        <many-to-one field="boutique" target-entity="WeShop\Bundle\BoutiqueBundle\Entity\Boutique" inversed-by="documents">
          <join-column name="boutique_id" referenced-column-name="id" nullable="false" />
        </many-to-one>
      </entity>
    </doctrine-mapping>

Thank you in advance

**Comment by michalmarcinkowski** [comment]
@Bahlaouane-Hamza this should be fixed right now, please reopen if the issue still occurs.
