### ISSUE TITLE
"Latest" version in docs points to 1.12, which is under development

### ISSUE THREAD

**Issue by elboletaire** [Sylius/Sylius#14399]
**Sylius docs version**: latest

**Description**
When accessing https://docs.sylius.com the version shown by default is the latest stable one (1.11), but the `latest` button in the menu directs to the current in-development version (1.12).

![imatge](https://user-images.githubusercontent.com/153305/193569691-28da8b60-561f-49cd-b17e-5211c60c5ee8.png)

I think version 1.12 should also be shown as a different version like `1.12-dev`, and `latest` should properly point to the latest stable version (which right now is 1.11).

**Comment by CoderMaggie** [comment]
It's always been configured like that. The `latest` was pointing to `master` when it was named so, it is the default configuration of read the docs. We've recently changed the default version to which the `docs.sylius.com/` redirects and it is the latest stable version - 1.11 for now. :)

**Comment by elboletaire** [comment]
Cool, at least it won't confuse anyone. Having the latest development documentation in a different version (let's say "dev", although I named it "1.12-dev" previously) wouldn't be a bad idea either.
