### ISSUE TITLE
API errors are not handled as intented in API Platform

### ISSUE THREAD

**Issue by vasilvestre** [Sylius/Sylius#14391]
**Sylius version affected**: 1.10.x, 1.12-alpha

**Description**  
I'm working on Sylius 1.12 and APIP 2.6 (ATM, will update soon) and I can't have **some** errors shown.
The constraints list errors works, ApiPlatform\Core\Exception\ItemNotFoundException do not work.

`api_platform.yaml`
```
exception_to_status:
    App\Exception\GenericException: 400
```
`Handler.php`
```
try {
    $attribute = $this->iriConverter->getItemFromIri($attribute);
} catch (ItemNotFoundException|InvalidArgumentException $exception) {
    throw new GenericException("Not found error TEST");
}
```

And my API response is :
```
{
    "code": 500,
    "message": "Internal Server Error"
}
```
I can't manage to have error message. The HTTP code is converted to 400.

The statements here do not works: https://api-platform.com/docs/core/errors/#message-scope

**Steps to reproduce**  
Create a project, use the API and use an invalid IRI for exemple.

**Possible Solution**  
This is a bug but a workaround has been given to me.

```
<?php

namespace App\EventListener;

use Symfony\Component\EventDispatcher\Attribute\AsEventListener;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpKernel\Event\ExceptionEvent;

#[AsEventListener(event: 'kernel.exception', method: 'onKernelException', priority: 2)]
class ExceptionListener
{
    public function onKernelException(ExceptionEvent $event): void
    {
        $exception = $event->getThrowable();

        if (str_contains($event->getRequest()->getPathInfo(), '/api/')) {
            $response = new JsonResponse([
                'message' => $exception->getMessage(),
            ],
                $exception->getCode() === 0 ? 400 : $exception->getCode()
            );
            $event->setResponse($response);
        }
    }
}
```

**Comment by lchrusciel** [comment]
We need to dig up where the problem lays and if it is in Sylius (probably yes)

**Comment by TheMilek** [comment]
Hi @vasilvestre!
Thanks for reporting the issue, I reproduced the problem and we We are on it 💃🏽

**Comment by jakubtobiasz** [comment]
Hello @vasilvestre!
Can you check what kind of exception is thrown? It should be an entry starting with `request.CRITICAL` in the prod.log file. I am getting 500, but the message is correct from what I see.

**Comment by vasilvestre** [comment]
> Hello @vasilvestre!
> Can you check what kind of exception is thrown? It should be an entry starting with `request.CRITICAL` in the prod.log file. I am getting 500, but the message is correct from what I see.

My first message specify what api returns with the code provided

**Comment by jakubtobiasz** [comment]
OK, I have managed to reproduce the error. The overall behavior is expected as the returned code is 500

> Depending on the status code you use, the message may be replaced with a generic one in production to avoid leaking unwanted information. If your status code is >= 500 and < 600, the exception message will only be displayed in debug mode (dev and test). In production, a generic message matching the status code provided will be shown instead. If you are using an unofficial HTTP code, a general message will be displayed.

ref: https://api-platform.com/docs/v2.7/core/errors/

However, the problem does not occur on Sylius/Sylius repository, and it seems impossible to override the status code. I'll back to it tomorrow.

**Comment by jakubtobiasz** [comment]
Hello @vasilvestre!

Quick fix:
1. Disable FOSRestBundle in `config/bundles.php`
2. Remove `config/packages/fos_rest.yaml` file
3. Clear the cache

From now, all exception to HTTP status code mapping should work. Currently, when IRI is for example "randomstring" it throws 500, and it should display "Internal Server Error" as all code `5xx` status codes have a generic name when `APP_DEBUG` is turned off. Anyway, you can remap the thrown exception to HTTP 400 or catch and throw your own.

Of course, the fix should be provided soon.

**Comment by vasilvestre** [comment]
> Hello @vasilvestre!
> 
> Quick fix:
> 
> 1. Disable FOSRestBundle in `config/bundles.php`
> 2. Remove `config/packages/fos_rest.yaml` file
> 3. Clear the cache
> 
> From now, all exception to HTTP status code mapping should work. Currently, when IRI is for example "randomstring" it throws 500, and it should display "Internal Server Error" as all code `5xx` status codes have a generic name when `APP_DEBUG` is turned off. Anyway, you can remap the thrown exception to HTTP 400 or catch and throw your own.
> 
> Of course, the fix should be provided soon.

Doing this change the payload and break my tests, there's no `code` and `message` anymore about 403 errors. Just want to say there's BC doing this without notice :)

**Comment by jakubtobiasz** [comment]
There are more problems, like ResourceBundle requiring FOSRestBundle. Moreover, I'll discuss with others whether we prefer to make a BC or fix a bug. We can always create a cookbook until 2.0.

Thanks for your input!
