### ISSUE TITLE
Can't install SymfonyMakerBundle due to conflict with some packages

### ISSUE THREAD

**Issue by TheMatto** [Sylius/Sylius#14418]
**Sylius version affected**: 1.11.9

**Steps to reproduce**  
-Install Sylius
-Require SymfonyMakerBundle: composer require --dev symfony/maker-bundle

**Comment by CoderMaggie** [comment]
Yes, indeed there is a problem with our dependencies. Thank you for reporting @TheMatto, we're on it!

**Comment by jakubtobiasz** [comment]
Hi @TheMatto!
I'm checking if we can remove the conflicting package. As a workaround, you can run `composer require symfony/maker-bundle:~1.39.0` command.

**Comment by jakubtobiasz** [comment]
Hello @TheMatto.
Fixing it in Sylius 1.11 was too time-consuming, but we have resolved your issue in #14551 opened against 1.12 branch, so in the nearest patch release you will be able to use Maker Bundle without any issue 💃🏼. In case of further issues, please let me know, for now, I am closing this topic.
