### ISSUE TITLE
Add a product and specify channel(s)

### ISSUE THREAD

**Issue by duchnoun** [Sylius/Sylius#14423]
**Sylius docs version**: 1.x / latest

How on api (v2) we can create a product and specify the channel ? (one or multiple)
I've try : 
```
curl -X 'POST' \
  'http://xxxxxxxxxxx/api/v2/admin/products' \
  -H 'accept: application/ld+json' \
  -H 'Authorization: Bearer  XXXXXX' \
  -H 'Content-Type: application/ld+json' \
  -d '{
  "mainTaxon": null,
  "images": [

  ],
  "code": "xxxx2",
  "channels": [
    "/api/v2/admin/channels/default",
    "/api/v2/admin/channels/mychannel"
  ],
  "options": [

  ],
  "translations": {
    "fr_FR": {
      "name": "test2 grenoble",
      "slug": "test3grenobleslug",
      "locale": "fr_FR"
    }
  }
}'
```

But channels seem to be read only ? 

Thanks

**Comment by duchnoun** [comment]
Maybe it's not possible ? an idea?

**Comment by duchnoun** [comment]
Hope to get some help :'( Please :'(

**Comment by GSadee** [comment]
It looks like we are not serializing channels while creating the product yet:
<img width="946" alt="image" src="https://user-images.githubusercontent.com/6140884/195293632-c2930f8b-71b8-4dfe-9873-6ad7ce8f0d6a.png">

We will probably add it in the future, but developing admin API is not the highest priority right now. However, you can contribute to the Sylius by adding this field to the serialization and covering proper behat or at least contract tests ([here](https://github.com/Sylius/Sylius/blob/1.12/tests/Api/Admin/ProductTest.php)).

You can also add it in your end application by following [this chapter](https://docs.sylius.com/en/1.11/customization/api/serialization_customization.html) in our documentation, but of course I encourage you to contribute to Sylius 😃
