### ISSUE TITLE
PHP 8.1 with migration Version20201208105207 can result in type error

### ISSUE THREAD

**Issue by AndreasA** [Sylius/Sylius#14436]
**Sylius version affected**: 1.11 & 1.12 (probably older versions as well)

**Description**  
Due to the a change in PHP 8.1 PDO behavior regarding integer values being returned as integers and not strings anymore, see:
https://github.com/doctrine/dbal/issues/5228
and https://www.php.net/manual/en/migration81.incompatible.php#migration81.incompatible.pdo.mysql

The migration Version20201208105207 fails as https://github.com/Sylius/Sylius/blob/v1.12.0-BETA.1/src/Sylius/Bundle/CoreBundle/Migrations/Version20201208105207.php#L80 required an ID to be a string there. It is not cast to string or integer upon call: https://github.com/Sylius/Sylius/blob/v1.12.0-BETA.1/src/Sylius/Bundle/CoreBundle/Migrations/Version20201208105207.php#L41

The easiest solution would probably be to cast accordingly before calling the method or keeping that parameter without a type (as union types only work with 8.1).

It might also be a good idea to check other similar calls.

**Steps to reproduce**  
Use PHP 8.1, do not manually change the stringify setting, ensure adjustments that need to be handled by the Version20201208105207 migration are in the database, execute that migration.

**Possible Solution**  
Cast to string or int on call. Or remove the type for now. Add the stringify configuration to the dbal config in the doctrine.yaml and a corresponding upgrade information but the casting is the better solution.

**Comment by ernestWarwas** [comment]
Hello @AndreasA, thanks for describing an issue. I can confirm that this problem exists. If you want you can contribute and provide a PR with your solution 💃
