### ISSUE TITLE
The cart created by a customer is incorrectly marked as created by a guest

### ISSUE THREAD

**Issue by nicolalazzaro** [Sylius/Sylius#14456]
**Sylius version affected**: 1.11.9

**Description**  
The cart created by a customer authenticated via access token is correctly related to the customer but the created_by_guest column is true, it should be false in this case.

**Steps to reproduce**  
Create a customer, obtain an access token, authenticate, create a new cart.

**Comment by coldic3** [comment]
Hey @nicolalazzaro,
thanks for raising the issue and for the PR that solves it! :slightly_smiling_face: I can confirm the problem exists. I've also checked it on `v1.12` and there `setCreatedByGuest` and `getCreatedByGuest` methods are deprecated in favor of `setCustomerWithAuthorization` and `isCreatedByGuest` so the problem exists only on `v1.11`.
