### ISSUE TITLE
Staging configuration still reference swiftmailer

### ISSUE THREAD

**Issue by vasilvestre** [Sylius/Sylius#14451]
**Sylius version affected**: 1.12.x

**Description**  
There's still a swiftmailer configuration file while mailer is now used by default.
https://github.com/Sylius/Sylius/blob/56dd3a490a47ff9468496cf2f2e8d0f3e63eefbd/config/packages/staging/swiftmailer.yaml#L1

**Steps to reproduce**  
It exists

**Possible Solution**  
Remove it

**Comment by GSadee** [comment]
I'm closing the issue as the entire staging configuration has been already removed 😃
