### ISSUE TITLE
500 when deleting the first root taxon

### ISSUE THREAD

**Issue by Florian-Merle** [Sylius/Sylius#14460]
**Sylius version affected**: 1.12

**Description**  
When deleting the first root taxon (in my example below, it would be "test"), we get a 500 error.

![image](https://user-images.githubusercontent.com/20768914/196714110-a6044a94-6d9f-4c44-8b5d-74b97836658f.png)

In dev, we get the following error

![image](https://user-images.githubusercontent.com/20768914/196714334-e695e035-7909-46ee-a930-a4695bd90bcc.png)

Note that I've been able to reproduce the bug on the demo of sylius

**Comment by GSadee** [comment]
Hi @Florian-Merle, 
thank you for reporting an issue 😃 I've reproduced that on our demo and it seems not to be working as it should, so we will try to fix it in the nearest future 💃🏻

**Comment by GSadee** [comment]
I'm closing the issue as it should be fixed by https://github.com/Sylius/Sylius/pull/14548
