### ISSUE TITLE
[API] Sorting products by price is not channel specific

### ISSUE THREAD

**Issue by j92** [Sylius/Sylius#14487]
**Sylius version affected**: 1.12

**Description**  
I want to sort my products by price on each channel. Right now the sorting takes all channel pricings in account, and not only the one from the current channel. 

| Product  | Channel  | Price |
| ------------- | ------------- | ------------- |
| Sylius Con shirt  | Poland  | 25.00 | 
| Sylius Con shirt  | Germany | 25.00 | 
| Sylius Con stickers  | Poland  | 30.00 |
| Sylius Con stickers  | Germany  | 20.00 |

*Current result when sorting by price ASC on channel Poland:*

1. Sylius Con stickers 30.00
2. Sylius Con shirt 25.00

*Desired result when sorting by price ASC on channel A:*

1. Sylius Con shirt 25.00
2. Sylius Con shirt 30.00

**Steps to reproduce**  
I added a Behat scenario to reproduce the issue here: https://github.com/Sylius/Sylius/pull/14489/commits/eca1836ba11d410c05c13070e5f2a2ab57bdbcad

The test fails with:
```
 And the first product on the list should have name "Sylius Con shirt"
      Expected a value identical to "Sylius Con shirt". Got: "Sylius Con stickers" (Webmozart\Assert\InvalidArgumentException)
```

**Possible Solution**  
Sort by price should look only at the channelPricings for the current channel.
Find the PR here: https://github.com/Sylius/Sylius/pull/14489

**Comment by GSadee** [comment]
I'm closing this issue, as it has been fixed by #14489
