### ISSUE TITLE
[Money] Display format

### ISSUE THREAD

**Issue by winzou** [Sylius/Sylius#1448]
The displayed format is not good according to the locale.
I have French locale and it puts the currency before the amount "€ 999" instead of the other way "999 €".
When I uncomment this line it's OK: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/MoneyBundle/Templating/Helper/MoneyHelper.php#L38
What is this line? Can someone confirm that this is not good?

**Comment by antonioperic** [comment]
should be closed? @winzou @pjedrzejewski @stloyd
