### ISSUE TITLE
Add support for Symfony workflow

### ISSUE THREAD

**Issue by loic425** [Sylius/Sylius#14495]
### Catalog promotion

- [ ] Sylius/Sylius#14494

### Order

- [ ] State machine configuration

**Before Placed Order**
- [ ] sylius_assign_number
- [ ] sylius_assign_token

**After Placed Order**
- [x] sylius_request_shipping
- [x] sylius_request_payment
- [x] sylius_create_payment
- [x] sylius_create_shipment
- [x] sylius_hold_inventory
- [x] sylius_increment_promotions_usages
- [x] sylius_save_addresses_on_customer
- [x] sylius_set_order_immutable_names

**After Canceled Order**
- [x] sylius_cancel_payment
- [x] sylius_cancel_shipment
- [x] sylius_cancel_order_payment
- [x] sylius_cancel_order_shipment
- [x] sylius_cancel_order_inventory
- [x] sylius_decrement_promotions_usages

### Order checkout

- [x] State machine configuration

**After Completed Checkout**
- [x] sylius_create_order
- [x] sylius_save_checkout_completion_date
- [x] sylius_control_payment_state
- [x] sylius_control_shipping_state

**After Selected Shipping**
- [x] sylius_process_cart
- [x] sylius_skip_payment

**After Addressed**
- [x] sylius_process_cart

**After Selected Payment**
- [x] sylius_process_cart

**After Skipped Shipping**
- [x] sylius_process_cart

#### After Skipped Payment
- [x] sylius_process_cart

### Order payment

- [x] State machine configuration

**After Paid**
- [x] sylius_order_paid
- [x] sylius_resolve_state

### Order shipping

- [x] State machine configuration

**After Shipped**
- [x] sylius_resolve_state

### Payment

- [x] State machine configuration

**After Failed Payment**
- [x] sylius_process_order

**After Canceled Payment**
- [x] sylius_process_order

**After Completed Payment**
- [x] sylius_resolve_state

**After Processed Payment**
- [x] sylius_resolve_state

**After Refunded Payment**
- [x] sylius_resolve_state

**After Authorized Payment**
- [x] sylius_resolve_state

### Product Review

- [x] State machine configuration

**After Accepted Product Review**
- [x] sylius_update_rating

### Shipment

- [x] State machine configuration

**Before Shipped**
- [x] sylius_assign_date

**After Shipped**
- [x] sylius_resolve_state

**Comment by jakubtobiasz** [comment]
Closing, as we covered all cases in `1.13` 🎉 .
