### ISSUE TITLE
Proposal for handling oauth registration and login

### ISSUE THREAD

**Issue by smarques** [Sylius/Sylius#1451]
Hi, I needed to work on a flexible oauth solution for an application I am working on, so if you are interested I could implement my solution in Sylius as well.
## Goal:
1. Make it possibile to **enable as many oauth providers as necessary** (facebook, github etc), eventually choosing from application setting page (no change in symfony config files required)
2. **streamline the oauth register/connect flow**
## Oauth Registration

For oauth.register the scenario is:
**User is not registered on the site.**
They click on 'register with [facebook|github|whathaveyou]'
Your goal is to create a new user account and connect it to their account on the oauth provider they have chosen.
At this point you have a few choices:
### the oauth provider has made available to you your prospect user's email
1. you can decide to automatically register the user with minimal information (email and whatever info you get from oauth provider, like name, nickname, etc, by mapping OAUTHBundle info fields to your user info). The user can always update their profile later and with one click they are in your app.
2. you can decide that you want the user to see a registration form with all registration fields, when possibile already populated by the mapping if it is available.
### oauth provider is not giving you the user's email address

(i.e. twitter and the new facebook anonymous login) 
1.  you want the user to see a registration form with all registration fields, when possibile already populated by the mapping if it is available.
## Oauth Login + Connect

A **user has previously registered on your site**. Now they are not logged and they try to login with a new oauth provider they never used before. lets say Twitter for example.
### the oauth provider has made available to you your prospect user's email

You can just connect their oauth info to their existing account. That is, if you trust the oauth provider.
Obviously this means that somebody has hacked your users' fb account they can get into your shops' account as well. But that's the whole point with oauth. :scream: .
### oauth provider is not giving you the user's email address

This is a bit complicated, my best solution is to show them a registration form, with fields pre-filled by any available oauth profile info. You save their oauth data (session or whatever). 
They will have to enter their email, then when they post the form you can check if an account already exists. You will find their account and ask them:
_Is this you? This user has the same email._
_If it IS you please login in to your account with your existing credentials and CONNECT your TWITTER account once you are logged_

The alternative to this is to validate the email address they have provided (sending an email link to click ) and once they have proven its their accounts you could connect it for them.
## Oauth Connect

This is the easiest. Your user is logged in, so we have his user id in our system. They have a way from their profile page to connect more accounts.
They click on any other oauth provider. We get their oauth id, we connect accounts.
## Changes required:

Move oauth ids to their own table, connected 1:n to the user table.
Sth like:
_user_oauth_

| id | user_id | provider | oauth_id | token |
| --- | --- | --- | --- | --- |
| 1 | 12 | facebook | fcbkuniqid | dfdsh...3fd8dn |
| 2 | 12 | twitter | twteruserid | 36783278fdd7 |

You then need to extend a few classes from OauthBundle.

This is what I have from previous experiences implementing oauth login.
What do you guys think?
If you think this is overkill no problem I will just implement it for my app, but I think that easy login with social accounts can be important for online shops.
As an alternative I could make a stand alone (non sylius) bundle for this behaviour, but that would take a lot more time. I am surprised that I could not find any existing bundle that extends oauth in this way.
Do you know if any solution like this (or better) is available on Sym2?

sergio

**Comment by Mustabshir-K** [comment]
Can somebody provide me an easy guide to implement facebook and google login in my sylius project? I am stuck on this provision.
