### ISSUE TITLE
Refresh JWT

### ISSUE THREAD

**Issue by Nek-** [Sylius/Sylius#14517]
When using the Sylius API with a frontend client it's currently required to record the user id/password to request a new JWT. This is because there is no route that allows refreshing a token.

I may have missed it but after a little search, it seems that there's no ticket about it so I just wanted to highlight the need for it in a dedicated issue.

**Comment by jakubtobiasz** [comment]
Hi @Nek-!

Yes, it isn't supported out-of-the-box. Maybe @lchrusciel might tell you if we plan to provide such support directly in Sylius, but for now you can use https://github.com/markitosgv/JWTRefreshTokenBundle as our JWT works on the lexik's bundle.

**Comment by Nek-** [comment]
Yes indeed the solution is to use this bundle, no doubt. I just wanted to create the issue to track that this is something missing, required, and to have your POV about it. (thanks for giving it)

**Comment by mbabker** [comment]
IMO, I wouldn't actually include the JWT refresh token bundle with Sylius-Standard.  Even though it piggybacks off the LexikJWTAuthenticationBundle, the refresh token bundle's storage doesn't cope well with a multi-firewall environment like Sylius', and there are some gotcha's between the two bundles that make it difficult to ID what context things are running in.  https://github.com/markitosgv/JWTRefreshTokenBundle/issues/242#issuecomment-872355983 and https://github.com/lexik/LexikJWTAuthenticationBundle/issues/707#issuecomment-1123035574 have some of my feedback on the matter having worked on improving the refresh token bundle while working with a couple of my company's clients.

**Comment by TheMilek** [comment]
Hi @Nek- 
Since there are multiple issues that might occur due to our firewalls structure, after the discussion with the team we decided to not add this dependency, but thank you very much for raising the issue! 🚀
