### ISSUE TITLE
[Sylius.com] Link to API demo down in French translation

### ISSUE THREAD

**Issue by Nek-** [Sylius/Sylius#14513]
I already reported this but nobody seems to care, besides it affects a lot the image of Sylius IMO. So here I am pushing harder... Sorry for the noise, I think it's necessary.

![Capture d’écran 2022-11-03 à 10 13 16](https://user-images.githubusercontent.com/972456/199684122-cc5dbf64-c9a0-462a-ba97-63c9b9063efd.png)

**Comment by jakubtobiasz** [comment]
Hi @Nek-!
Thank you for your report; I passed this information to the right person, so I hope it will work soon :).

**Comment by jakubtobiasz** [comment]
And... I am back :D. The link is working correctly now, so I let myself close this issue 🖖🏻.
