### ISSUE TITLE
Wrong Rounding of the prices in the percentage discount catalog promotions

### ISSUE THREAD

**Issue by maxmishyn** [Sylius/Sylius#14522]
**Sylius version affected**: 1.11 and above

**Description**  
Percentage discount in catalog promotions makes prices rounding not correct for edge case prices. I.e. new prices €1.205 is rounded to €1.20 instead of €1.21.    

**Steps to reproduce**  

1. Create product with the price of 10.50. 
2. Create and apply catalog promotion with percentage discount of 15% to the product above
3. As a result the new price will be 8.92, but mathematically correct will be 8.93 (exact discounted price is 8.925)

**Possible Solution**  
Reason is in the calculate method of PercentageDiscountPriceCalculator class. Instead of rounding it just casts discounted price to the integer.

Is it worth of fixing for it or there was some logic behind it?

**Comment by SoulPancake** [comment]
@ernestWarwas Can I contribute to this? My suggestion would be to get the ceiling value for anything post 2nd decimal places, Is that a fair assumption for a solution approach?

**Comment by maxmishyn** [comment]
@Anuragkillswitch and  @ernestWarwas It rather should be round() rather than just ceil. Something like
`$price = (int) round($channelPricing->getPrice() - ($channelPricing->getPrice() * $action->getConfiguration()['amount']));`

I can make a PR as I already have this change locally.

**Comment by GSadee** [comment]
I'm closing this issue as it has been fixed by https://github.com/Sylius/Sylius/pull/14669
