### ISSUE TITLE
Only one product attribute is saved when we add them one by one in the product edit page

### ISSUE THREAD

**Issue by delyriand** [Sylius/Sylius#14521]
**Sylius version affected**: 1.10, 1.11

**Description**  

In the admin, when we add attributes to a product one by one and then save it, only the first attribute added is registered.

**Steps to reproduce**  

- Edit or create product 
- Go to attributes tabs
- Choose an attribute in the select and add it 
- Choose another attribute and add it
- Add attribute values and save the product

The first values of the attribute are saved, not the values of the other of attributes added after!

**Possible Solution**  

I think it's the search for the length of the added attributes, in the `src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-product-attributes.js` file, that is the problem. If i replace the JS:

```js
addAttributesNumber($.grep(attributeFormElements, a => $(a).hasClass('attribute')).length);
```

by 

```js
addAttributesNumber(attributeFormElements.find('.attribute').length);
```

The `data-count` value is updated and the saved works.

**Comment by jakubtobiasz** [comment]
Hi @delyriand!
Would you like to create a Behat scenario reproducing the bug and open a fixing PR?

**Comment by delyriand** [comment]
Hi @ jakubtobiasz,

I will try to create the behat scenario :D. Do you have an example?

First, i open a PR with the modified JS to be applied the patch to my project.

**Comment by jakubtobiasz** [comment]
@delyriand here are some examples relating to this part of Admin Panel 👉🏼 https://github.com/Sylius/Sylius/blob/1.13/features/product/managing_products/adding_product_with_text_attribute.feature
