### ISSUE TITLE
Swap currency used for orders/invoices for the user and for admin

### ISSUE THREAD

**Issue by sabliao** [Sylius/Sylius#1453]
*Currently, the orders/invoices shown to the admin use the currencies chosen by the users to navigate and make purchases through the store. The users, on the other hand, see their orders/invoices (in 'My Account') in the currency set for the store's default.

I propose that it would make for a better user experience to swap these views, allowing the users to see their orders/invoices in the currency that they chose while browsing through the store. Another argument could be made that the admin would also rather see orders/invoices in the currency set for the store/currency used to price the products [in the database]. This request comes from the confusion that stemmed from issue #1425.

*This was observed with the complete Sylius demo bundle.

**Comment by michalmarcinkowski** [comment]
Fixed already.
