### ISSUE TITLE
API tokenValue may be missing on new cart

### ISSUE THREAD

**Issue by Nek-** [Sylius/Sylius#14539]
**Sylius version affected**: 1.11 / 1.12 / master

**Description**  

Creating a cart on the website does not create a tokenValue besides it's used as ID with the API. When I try to get an already created cart using the API it does not return the tokenValue.

**Steps to reproduce**  

1. Use the sylius website, login, and add 1 item to cart
2. Use the sylius API, login and use the token for further requests
3. Use the endpoint POST `/v2/shop/orders` to create a cart
4. The cart has no tokenValue and it's not possible to use it with the API

**Possible Solution**  

Generate the tokenValue before inserting the order in the database. (I assume this has consequences that I'm not aware of)

**Comment by everwhatever** [comment]
Hi @Nek- 
Indeed, it would be great to do it :) However, we're currently focusing on other features, so it's not a priority for us now. However, if you would like to give it a try and open a PR with such a change, we would be happy to merge it and/or help with potential problems

**Comment by Nek-** [comment]
Thanks for considering this but it's not a feature it's a real bug since there's no solution. I will try to have a look for sure.

**Comment by coldic3** [comment]
Ok, I get the point now. We'll take a look at it.
