### ISSUE TITLE
Use bigint for prices

### ISSUE THREAD

**Issue by DjLeChuck** [Sylius/Sylius#14557]
**Describe the proposed solution**
When using weak currency such as Ariary (currency of Madagascar), we encounter overflowed value in the database because `int` can not handle the inserted value. Changing concerned fields to `bigint` for prices related columns allowed to fix the issue without any problem (in our case, for our customer website, since 2 years. 😄 )

**Describe alternatives you've considered**
We haven't find any other solution than patch our vendor on each `composer install`

**Additional context**
0,0011 Złoty = 1 Ariary, so when converted to `int`, the maximum value is overflowed if the value is to high.

**Comment by jakubtobiasz** [comment]
Hi @DjLeChuck!
Thank you for raising this topic and providing the potential solution. We'll discuss this internally in the nearest feature, and I will do my best to back to you with any feedback.
