### ISSUE TITLE
Associated Products loaded without proofing if enabled for current channel

### ISSUE THREAD

**Issue by TELLO0815** [Sylius/Sylius#14564]
**Sylius version affected**: 1.11.10

**Description**  
If I have product enabled for channel 1 and 2.
There are associated products, but only enabled for channel 1 and I don't put price for channel 2.
All related products will be loaded, without check if enables for current channel. ERGO if no price ERROR.

**Possible Solution**  
Check on query if product enabled for current channel.

**Comment by coldic3** [comment]
Thanks a lot @TELLO0815 for raising the issue. We are on it 💃
