### ISSUE TITLE
Deprecation for ProductVariantPriceCalculatorInterface but missing service

### ISSUE THREAD

**Issue by stefantalen** [Sylius/Sylius#14590]
**Sylius version affected**: >= 1.8

**Description**  
As of Sylius 1.8 there is a deprecation warning for [`\Sylius\Component\Core\Calculator\ProductVariantPriceCalculatorInterface`](https://github.com/Sylius/Sylius/blob/1.8/src/Sylius/Component/Core/Calculator/ProductVariantPriceCalculatorInterface.php#L20)

It suggests using `\Sylius\Component\Core\Calculator\ProductVariantPricesCalculatorInterface`, however when using Dependency Injection there is no service for that class resulting in an error.

> Cannot autowire service argument "$productVariantPricesCalculator" of method "__construct()" references interface "Sylius\Component\Core\Calculator\ProductVariantPricesCalculatorInterface" but no such service exists. Try changing the type-hint to "Sylius\Component\Core\Calculator\ProductVariantPriceCalculatorInterface" instead.

**Possible Solution**  
Add a service for `\Sylius\Component\Core\Calculator\ProductVariantPricesCalculatorInterface`

**Comment by everwhatever** [comment]
Hi @stefantalen 
Thank you for your report. I checked the 1.11 version because we don't support 1.8 anymore and it works fine. I will close this ticket but if you find similar problem on actual version please let us know and open new ticket
