### ISSUE TITLE
Can't Access Auth API

### ISSUE THREAD

**Issue by mohamad-zbib** [Sylius/Sylius#14592]
I am trying to access the route `/api/v2/shop/authentication-token`, but it's not working 

    {
        "code": 404,
        "message": "Unable to find the controller for path \"/api/v2/shop/authentication-token\". The route is wrongly configured."
    }

i figured that it's defined here `vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Resources/config/routing.yml`, but not sure how to fix

**Comment by nicolalazzaro** [comment]
Hi, are you sure you are sending the "Accept" and "Content-Type" headers supported by your ApiPlatform configuration?

**Comment by Rafikooo** [comment]
We've checked it and as @nicolalazzaro said, it's due to invalid request headers. We can agree that this message is not accurate, but this is a Platform API issue rather than a Sylius issue, so we will close this issue
