### ISSUE TITLE
Tagging OrderTaxesApplicatorInterface

### ISSUE THREAD

**Issue by Florian-Merle** [Sylius/Sylius#14609]
When trying to add a new `OrderTaxesApplicator`, I need to redefine both `sylius.taxation.order_items_based_strategy` and `sylius.taxation.order_item_units_based_strategy` service configuration so they are used by the tax strategies. See https://github.com/Sylius/Sylius/blob/1.13/src/Sylius/Bundle/CoreBundle/Resources/config/services/taxation.xml#L43

What about tagging services implementing `OrderTaxesApplicatorInterface` with either `sylius.taxation.items.applicator` or `sylius.taxation.item_units.applicator` or both . This would allow to inject tagged services into the strategy services.

This would make it more future-proof and easier to create new taxes applicator in a project.

Let me know what you think, and I can implement it 😀

**Comment by vvasiloi** [comment]
@Florian-Merle sounds good! Is it possible to also remove the type argument somehow? 🤔

**Comment by Florian-Merle** [comment]
@vvasiloi I'm not sure what do you mean by the type argument, can you explain?

**Comment by vvasiloi** [comment]
@Florian-Merle sorry, I was thinking about the tax calculation strategies. Those have a `$type` constructor argument and an identical `type` attribute on the `sylius.taxation.calculation_strategy` tag.

**Comment by GSadee** [comment]
Closing as it should be resolved by https://github.com/Sylius/Sylius/pull/14623
