### ISSUE TITLE
Store Customization

### ISSUE THREAD

**Issue by rubencosta13** [Sylius/Sylius#14613]
Is there any way to customize our store? Like any drag and drop components or something like that?

**Comment by vvasiloi** [comment]
No. You can maybe get something similar with [CMS plugin](https://github.com/BitBagCommerce/SyliusCmsPlugin). There's also a [Bootstrap theme](https://github.com/SyliusCrafts/BootstrapTheme). Or if you're adventurous you can try [Netgen Layouts](https://netgen.io/layouts) with their [Sylius integration](https://github.com/netgen-layouts/layouts-sylius).

**Comment by rubencosta13** [comment]
!!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
!!                                                                                 
!!    The service "bitbag_sylius.event_subscriber.resource_delete" has a dependen  
!!    cy on a non-existent service "session". Did you mean one of these: "session  
!!    .factory", "session.storage.factory.native", "session_listener", "data_coll  
!!    ector.request.session_collector", "security.authentication.session_strategy  
!!    ", "security.listener.session.admin", "security.logout.listener.session.adm  
!!    in", "security.listener.session.shop", "sylius.listener.session_cart", "syl  
!!    ius.context.cart.session_and_channel_based", "sylius.storage.cart_session",  
!!     "debug.argument_resolver.session", "debug.argument_resolver.session.inner"  
!!    , "sylius.storage.session"?                                                  
!!                                                                                 
!!  


What does this mean while trying to ``composer update``? Installing CMS Plugin

**Comment by vvasiloi** [comment]
@rubencosta13 probably the plugin does not yet work with Symfony 6.

**Comment by rubencosta13** [comment]
> @rubencosta13 probably the plugin does not yet work with Symfony 6.

I've seen it in the other issue, imma close this one, I think I found the solution, plus is there any discord server / slack for sylius?

**Comment by vvasiloi** [comment]
@rubencosta13 yes, we have Slack, I sent you an invite.
