### ISSUE TITLE
The service "sylius.controller.import_data" has a dependency on a non-existent service "session.flash_bag".  

### ISSUE THREAD

**Issue by rubencosta13** [Sylius/Sylius#14615]
**Sylius version affected**: 1.2

**Description**  
While ``composer update`` I've got this error:
  The service "sylius.controller.import_data" has a dependency on a non-existent service "session.flash_bag".  

**Steps to reproduce**  
``composer update``

**Comment by vvasiloi** [comment]
The error comes from the fact the `session.flash_bag` was deprecated in Symfony 5 and removed in Symfony 6, so you're probably dealing with some code that does not support Symfony 6, perhaps from a plugin.
On a side note, I don't recommend running `composer update` without any arguments as it will update ALL your dependencies at once, which is risky business.
