### ISSUE TITLE
Possible bug, or just me being dumb .....

### ISSUE THREAD

**Issue by rubencosta13** [Sylius/Sylius#14611]
**Sylius version affected**: 1.2

**Description**  
When I try to add any plugins I get pretty much the same message, even tried updating composer... Doesn't seem to work

**Steps to reproduce**  
While trying to ``compose require setono/sylius-gift-card-plugin`` from [sylius-gift-card-plugin](https://github.com/Setono/SyliusGiftCardPlugin) or pretty much any plugin, I get the same kind of problems / errors from composer:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires setono/sylius-gift-card-plugin ^0.11.9 -> satisfiable by setono/sylius-gift-card-plugin[v0.11.9, 0.11.x-dev].
    - setono/sylius-gift-card-plugin[v0.11.9, ..., 0.11.x-dev] require symfony/config ^4.4 || ^5.0 -> found symfony/config[v4.4.0-BETA1, ..., 4.4.x-dev, v5.0.0-BETA1, ..., 5.4.x-dev] but the package is fixed to v6.0.11 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require setono/sylius-gift-card-plugin:*" to figure out if any version is installable, or "composer require setono/sylius-gift-card-plugin:^2.1" if you know which you need.

```
**Things I've tried:**
requiring ``setono/sylius-gift-card-plugin`` with the -W flag, to allow upgrades, but I still have the same issue, as well as using ``:*`` like told on the error message.

**Note:** 
This is not only related to ``setono/sylius-gift-card-plugin`` but all the plugins I've tried, even with the Sylius' ones.

**System Info**
```php```
  PHP 8.0.26 (cli) (built: Dec  3 2022 19:21:17) ( NTS )
  Copyright (c) The PHP Group
  Zend Engine v4.0.26, Copyright (c) Zend Technologies
      with Zend OPcache v8.0.26, Copyright (c), by Zend Technologies

```OS```
  Ubuntu 22.04

```Sylius Deployment method```
  Docker compose

Please let me know if you need any more info, also I've added my composer.json.txt file [here](https://github.com/Sylius/Sylius/files/10155206/composer.lock.txt), kindly take a look at it

**Comment by vvasiloi** [comment]
@rubencosta13 Sylius 1.12 with Symfony 6 support was released just a month ago and probably most plugins were not yet updated.  You can see in the error message that the plugin requires `symfony/config ^4.4 || ^5.0`, but the installed version is `6.0.11`.

**Comment by rubencosta13** [comment]
> @rubencosta13 Sylius 1.12 with Symfony 6 support was released just a month ago and probably most plugins were not yet updated. You can see in the error message that the plugin requires `symfony/config ^4.4 || ^5.0`, but the installed version is `6.0.11`.

So is there anything I can do to perhaps try to fix it? Or downgrade symfony/config, since there are some plugins which are really cool, but they have some issues with it....

**Comment by vvasiloi** [comment]
@rubencosta13 yes, you can make PRs to the plugins you need to support Symfony 6. You probably just need to add `|| ^6.0` to all `symfony/*` dependencies.

**Comment by rubencosta13** [comment]
Another question, how can I delete all data from the prod database, such as taxons, products and stuff like that?
Edit: thanks for your reply

**Comment by rubencosta13** [comment]
> @rubencosta13 yes, you can make PRs to the plugins you need to support Symfony 6. You probably just need to add `|| ^6.0` to all `symfony/*` dependencies.

But then, how do I add it with composer require, I do have to wait for a member to merge it, don't I?

**Comment by vvasiloi** [comment]
> > @rubencosta13 yes, you can make PRs to the plugins you need to support Symfony 6. You probably just need to add `|| ^6.0` to all `symfony/*` dependencies.
> 
> But then, how do I add it with composer require, I do have to wait for a member to merge it, don't I?

Yes. You either wait or use your fork.

**Comment by vvasiloi** [comment]
> Another question, how can I delete all data from the prod database, such as taxons, products and stuff like that? Edit: thanks for your reply

@rubencosta13 I assume you loaded test data to a production environment. There's no easy way to remove that data. You'll have to either remove it manually or do it through SQL.

**Comment by rubencosta13** [comment]
If I decide to use my fork I'd have to upload the files to the shop's directory, am I right?

**Comment by vvasiloi** [comment]
> If I decide to use my fork I'd have to upload the files to the shop's directory, am I right?

No. You just add the fork as a Composer repository: https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

**Comment by rubencosta13** [comment]
Amazing thanks for your time!

**Comment by vvasiloi** [comment]
In this example you can fork the gift card plugin, fix the compatibility with Symfony 6, then run `composer config repositories.sylius-gift-card-plugin vcs git@github.com:rubencosta13/sylius-gift-card-plugin.git`
Then run `compose require setono/sylius-gift-card-plugin` as usual.
