### ISSUE TITLE
Correct typo mistake of a transition

### ISSUE THREAD

**Issue by vasilvestre** [Sylius/Sylius#14630]
The transition name here is sylis_cancel_order instead of sylius_cancel_order

https://github.com/Sylius/Sylius/blob/b2db19d1f73864641cf891f204c61ba44bb87a4c/src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_order.yml#L95

**Comment by Rafikooo** [comment]
Hi @vasilvestre , this issue has already been discussed here: https://github.com/Sylius/Sylius/issues/13688
