### ISSUE TITLE
Inactive administrator can log in in admin

### ISSUE THREAD

**Issue by JordiDekker** [Sylius/Sylius#14652]
**Sylius version affected**: ?, 1.11 & 1.12

**Description**  
When a Sylius administrator is marked as disabled/inactive, it's still working to login. This can be reproduced in at least Sylius version 1.11 and 1.12 (so also in the current demo environment at [demo.sylius.com](http://demo.sylius.com/))

**Steps to reproduce**  
1. Create a new administrator ( https://demo.sylius.com/admin/users/ )
2. Make sure "Enabled" is not selected
3. Save
4. Log in with credentials via admin ( https://demo.sylius.com/admin/  )

**Possible Solution**  
Add check if administrator is enabled before authorization in admin

**Comment by mbabker** [comment]
I can't reproduce this on a client's 1.11 site; on admin login, the code flow reaches `SyliusLabs\Polyfill\Symfony\Security\Core\User\UserChecker::checkPreAuth()` and correctly throws a `DisabledException` when the account is disabled.

With that said, however, the way this is being handled in a fresh Sylius-Standard install is really approaching on being way over-engineered.

Right now, the default install relies on not explicitly configuring the `user_checker` for each firewall and falling back to Symfony's default handling, which uses the `security.user_checker` service.  For B/C reasons, there is `SyliusLabsPolyfillSymfonySecurityBundle` which registers a compiler pass that tries to decorate the `security.user_checker` service to use the `SyliusLabs\Polyfill\Symfony\Security\Core\User\UserChecker` instead (extra emphasis on instead; though the compiler pass registers a constructor argument for the decorated checker, the class itself doesn't take it 🤦).

Why is there a need for all of this complexity?  Why not create a `Sylius\Bundle\UserBundle\Security\User\UserChecker` class that implements Sylius' default account checks and explicitly configure that service as the user checker on each firewall?  It more explicitly declares how user accounts are being checked and breaks a dependency to deprecated Symfony functionality by having Sylius (this monorepo specifically) own the service involved.  IMO this whole compiler pass and decorating the default checker to keep using the default user checker as it was before Symfony removed `Symfony\Component\Security\Core\User\AdvancedUserInterface` in 5.0 is a totally over-engineered bit of code; that polyfill package really shouldn't have more than the interfaces as they were before the deprecated functionality was totally removed.

**Comment by vvasiloi** [comment]
IIRC the polyfill was created for compatibility between SF 4 and 5 and now also extends to 6.
It can't contain just an interface since there are several classes and interfaces that Sylius, including all it's installations and bundles, rely on and were removed from Symfony.

**Comment by mbabker** [comment]
I think my main groan here is you shouldn't be trying to polyfill `Symfony\Component\Security\Core\User\UserChecker` as it was in Symfony 4.4, and that Sylius should've never relied 100% on the default user checker service.  The user checker should become a service in the UserBundle, especially if Sylius intends on keeping support for the features that were represented by `Symfony\Component\Security\Core\User\AdvancedUserInterface` (which for what's exposed through the UI, requires at least its `isEnabled()` method).

There's nothing wrong with having kept support for that interface, but the way that it was done just made me 🤯 when I realized that's how it was working.  Essentially, Sylius is relying on polyfilling functionality that was fully removed from Symfony and said functionality isn't a part of Sylius itself in any meaningful way right now unless we're considering code in the `SyliusLabs\Polyfill` namespace to be a concrete part of Sylius and not a temporary bridging mechanism.

**Comment by everwhatever** [comment]
Hi @JordiDekker 
We cannot reproduce it on 1.11 but we reproduce it 1.12. We try to fix this bug

**Comment by jakubtobiasz** [comment]
Hello @JordiDekker 👋🏼!
We've checked this once again today, and it seems it's working properly. We also checked our tests, and it's covered with Behat scenarios :).
