### ISSUE TITLE
Media directory permissions problem using Docker (Sylius 1.12.1)

### ISSUE THREAD

**Issue by valentin-harrang** [Sylius/Sylius#14653]
**Sylius version affected**: 1.12.1

**Description**  

I just installed Sylius `1.12.1` via Docker (following the documentation) and when I want to upload an image to a product from the admin panel, I get this permissions error:

`2022/12/16 13:26:12 [crit] 32#32: *843 stat() "/srv/sylius/public/media/cache/sylius_small/50/09/d7acd0e47c4b6c598e5fd25fd206.jpg" failed (13: Permission denied), client: 172.18.0.1, server: , request: "GET /media/cache/sylius_small/50/09/d7acd0e47c4b6c598e5fd25fd206.jpg HTTP/1.1", host: "localhost", referrer: "http://localhost/admin/products/22/edit"`

However, there are these lines in the `docker/php/docker-entrypoint.sh` file which is supposed to define the rights on the `public/media` folder : 

```
setfacl -R -m u:www-data:rwX -m u:"$(whoami)":rwX var public/media
setfacl -dR -m u:www-data:rwX -m u:"$(whoami)":rwX var public/media
```

`media` directory in `php` container:

![image](https://user-images.githubusercontent.com/19478137/208382386-4d6853b2-99c2-4299-877c-44cc43b6e1d2.png)

By the way, I think that if you install Sylius via Docker, the product images will not be displayed on the website because of the permissions.

**Steps to reproduce**  

1. Login to admin panel
2. Go to `Products > Media`
3. Upload a media

**Possible Solution**  

?

**Comment by valentin-harrang** [comment]
@nicolalazzaro has the same problem and he didn’t have this problem in the past.

Need help please 🙏

**Comment by vvasiloi** [comment]
Try this fix: https://github.com/Sylius/Sylius-Standard/pull/887

**Comment by valentin-harrang** [comment]
@vvasiloi 

I stopped and removed all containers. I also deleted all volumes and I added `docker/nginx/nginx.conf` file:

```
user  www-data;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
} 
```

And it doesn't work 😕

**Comment by vvasiloi** [comment]
Did you rebuild the image?
Try `docker-compose up -d --build --force-recreate`

**Comment by valentin-harrang** [comment]
Same problem 😕

**Comment by vvasiloi** [comment]
Did you apply all the changes from the PR?

**Comment by valentin-harrang** [comment]
@vvasiloi It works, thank you! 🙏
