### ISSUE TITLE
[Docs] Instructions for submitting a patch are not clear

### ISSUE THREAD

**Issue by alejgr** [Sylius/Sylius#14679]
**Sylius docs version**: 1.13 / latest

**Description**
According to the instructions in the current version (1.13) of the codebase, it seems that we should begin our new feature or bug fix from the master branch. This looks outdated, as there is no master branch now. Should it be from last versioned branch right? e.g. 1.13.   

[Link to docs](https://github.com/Sylius/Sylius/blob/1.13/docs/book/contributing/code/patches.rst#step-2-work-on-your-patch)

**Comment by everwhatever** [comment]
Hi @alejgarciarodriguez 
Thank you for this report, we try our best to fix it
