### ISSUE TITLE
API: Valid `code` values sometimes cause server errors, because IriToIdentifierConverter::isIdentifier() is prone to false positives

### ISSUE THREAD

**Issue by rimas-kudelis** [Sylius/Sylius#14672]
**Sylius version affected**: 1.11.7

I'm currently implementing a custom payment method for Sylius, and while testing out whether and how it works  within the API, I discovered I could not select it as for my order using the `PATCH /api/v2/shop/orders/{tokenValue}/payments/{paymentId}` endpoint.  The error returned was actually error 500 with a rather cryptic message:
```JSON
{
  "code": 500,
  "message": "No resource associated to \"abc\"."
}
```
So I added some breakpoints, started my debugger, and here's what I discovered:
1. when denormalizing the command, [CommandArgumentsDenormalizer](https://github.com/Sylius/Sylius/blob/83ee7d38543906fc57aa0dd6c90d8dfe61e87f50/src/Sylius/Bundle/ApiBundle/Serializer/CommandArgumentsDenormalizer.php#L50-L74) is employed.
2. it uses [IriToIdentifierConverter](https://github.com/Sylius/Sylius/blob/83ee7d38543906fc57aa0dd6c90d8dfe61e87f50/src/Sylius/Bundle/ApiBundle/Converter/IriToIdentifierConverter.php#L76-L89) to decide whether or not an argument provided is an "identifier".
3. the method used (`IriToIdentifierConverter::isIdentifier()`) in fact tests whether the argument can be considered an IRI and returns true if so.
4. it checks that by asking Router whether the identifier matches any of the known routes.
5. in turn, the router will add a leading slash if it's missing, and it seems to also add a trailing one (or just ignore its (non-)existence). In other words, `"abc"` is treated as `"/abc/"`.
6. `"/abc/"` (as well as anything else matching `|/[A-Za-z]{2,4}/|`) matches the `sylius_shop_homepage` route. Thus, the router returns `true`, since the string apparently matches a known route.
7. So my payment method code `"abc"` is suddently considered an IRI and [IriToIdentifierConverter::getIdentifier](https://github.com/Sylius/Sylius/blob/83ee7d38543906fc57aa0dd6c90d8dfe61e87f50/src/Sylius/Bundle/ApiBundle/Converter/IriToIdentifierConverter.php#L41-L74) attempts to convert it to an identifier. And of course fails, because it's was never really meant to be an IRI and the route in question has no `_api_resource_class` parameter.
8. Command deserialization fails at this point with a server error and a cryptic message.

**Possible Solution**  
First of all, I don't think it's necessary to allow operating both IRIs and codes interchangeably. It's an API after all, it's supposed to live under the hood and just do its job. Just one method of identifying stuff should be enough, in my opinion.

But if you do want to keep both methods of identification, perhaps a quick fix for this would be to only defer to the router if the string in question has at least one `/` character in it.

Another option could be for `IriToIdentifierConverter::isIdentifier()` to check for the existence of `'_api_resource_class'` key in the array returned by the router as route info and only to return `true` if the key exists:

```php

    public function isIdentifier($fieldValue): bool
    {
        if (!is_string($fieldValue)) {
            return false;
        }

        try {
            $parameters = $this->router->match($fieldValue);
        } catch (RoutingExceptionInterface) {
            return false;
        }

        return isset($parameters['_api_resource_class']);
    }
```

In fact, the last option is what I resorted to for now: I placed a copy of this buggy class in App namespaces and applied this small fix. Initial testing show that it works. However, I'm not sure if testing for the `/` character wouldn't be more appropriate.

**Comment by nicolalazzaro** [comment]
Hi, I noticed that this error also occurs on shipping if a shipping method code of less than 3 characters is sent
