### ISSUE TITLE
AdminBundle layout__topbar height is too tall

### ISSUE THREAD

**Issue by UlrichHP** [Sylius/Sylius#14714]
**Sylius version affected**: 1.12

**Description**  
In [AdminBundle/Resources/private/sass/_layout.scss](https://github.com/Sylius/Sylius/blob/1.12/src/Sylius/Bundle/AdminBundle/Resources/private/sass/_layout.scss), at line 44, I noticed that **.admin-layout__topbar** `height` is defined at **80px** but that makes it too tall for its content.

![Screenshot_20230113_122339](https://user-images.githubusercontent.com/27560999/212309378-ca131e5c-d36f-48ba-8102-8ca66de71436.png)

**Possible Solution**  
Either remove height, or defined it as `fit-content` or add another value ?

**Comment by everwhatever** [comment]
Hi @UlrichHP 
Can you open PR with fix?

**Comment by UlrichHP** [comment]
Sure, i will do it @everwhatever
Which solution do you prefer ? Remove height or fit-content or a defined value ?

**Comment by jakubtobiasz** [comment]
Fixed in #14761 :). Thanks :).
