### ISSUE TITLE
"No locale has been set and current locale is undefined." when trying to load product fixtures

### ISSUE THREAD

**Issue by claude-cp** [Sylius/Sylius#14738]
**Sylius version affected**: 1.10.1

**Description**  
Getting error "No locale has been set and current locale is undefined." when trying to load product fixture. 
The very weird part is that it **doesn't work only with this one fixture**.

![Screenshot 2023-01-20 at 18 31 58](https://user-images.githubusercontent.com/44572257/213753477-676c5091-8279-456e-850b-92e26f0b6393.png)

As you can see that product is all but identical to the other(s), apart from name.

**Steps to reproduce**  
Attempting to run "sylius:fixtures:load"

**Possible Solution**  
Well, I see some possible solutions from [this thread](https://github.com/Sylius/Sylius/issues/2689), in [this comment](https://github.com/Sylius/Sylius/issues/2689#issuecomment-95908079), and I have checked around in my entities and repos:
- `App\Entity\Product` extends `Sylius\Component\Core\Model\ProductTranslation`.
-  `App\Entity\ProductVariantTranslation` extends `Sylius\Component\Core\Model\ProductVariantTranslation`.
- as for the repos extending `TranslatableResourceRepository`, this suggestion looks outdated, that class was removed.

I found [this other thread also](https://github.com/Sylius/Sylius/issues/2695) which may be related. 

**So, why would it work for the other products, but not that particular fixture ?**

**Comment by everwhatever** [comment]
Hi @claude-cp 
We don't support 1.10 anymore. Try to reproduce this on 1.11 and if it still doesn't work on this version open new ticket

**Comment by claude-cp** [comment]
Ok - I'll leave a reply here, if anybody finds this in the future: 

It turned out that the issue was in our code, the (test) environment was not comprehensive with everything it needed in terms of fixtures and related entities. 

The exception was actually coming from further down the line: 
One of the entities trying to have its name translated. What I had to do was modify that entity to check whether the related entity "hasTranslations", and only then get its (translated) name.

Was a bit hard to identify though because error message and edge case seemed very peculiar.
