### ISSUE TITLE
Replace getConfigurationFormType methods with getType in all calculators/checkers/actions

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#1473]
Make it non-symfony specific and clearer... The form type names can be generated from these generic types. (see Pricing)

**Comment by rvanlaak** [comment]
@pjedrzejewski after upgrading from `0.14` to `0.17` we also had to change `getConfigurationFormType` its values to the FQCN representation. Probably the alias was removed from the service configuration, so would be nice if that can be added to `upgrade.md` too.
