### ISSUE TITLE
Error thrown in Normalizer because an array offset isn't checked

### ISSUE THREAD

**Issue by vasilvestre** [Sylius/Sylius#14748]
**Sylius version affected**: 1.12.0

**Description**  
A warning is throw if no value has been passed to a product attribute value after serialization.

**Steps to reproduce**  
I got an edge case on Product attribute value being sent as null in API, which lead to an error in the code below.
https://github.com/Sylius/Sylius/blob/b2db19d1f73864641cf891f204c61ba44bb87a4c/src/Sylius/Bundle/ApiBundle/Serializer/ProductAttributeValueNormalizer.php#L52

**Possible Solution**  
Maybe we could check that value exists in the default section of match.

**Comment by coldic3** [comment]
Hi @vasilvestre,
thanks for raising the issue! I think your proposed solution is perfectly fine. Would you like to open a PR with a fix?

**Comment by vasilvestre** [comment]
> Hi @vasilvestre,
> thanks for raising the issue! I think your proposed solution is perfectly fine. Would you like to open a PR with a fix?

I tried this solution for a week now and got no issues so far. I will open a PR soon :)

**Comment by coldic3** [comment]
Thanks!

**Comment by GSadee** [comment]
I'm closing this issue as it should be fixed by https://github.com/Sylius/Sylius/pull/14789
