### ISSUE TITLE
Securing an action

### ISSUE THREAD

**Issue by tdaryani01** [Sylius/Sylius#1474]
Hi,

I really like your SyliusResourceBundle and I extend all my customs bundles from it. Thank you very much for the great work you have done creating this bundle. I just have one issue. Sometimes I need to secure an action. Currently, the only I can do this is by overriding showAction or updateAction. However, doing this , I miss on all the benefits(i.e events) of letting resource bundle deal with crud actions. I am wondering if there is a way to do a security check( I have a custom voter that deals with this) before an action is served by ResourceController in SyliusResourceBundle without needing to create my showAction or updateAction?

Thank you
Taher

**Comment by stloyd** [comment]
@pjedrzejewski @aRn0D As we have RBAC support and can easily lock actions when declaring route, I guess this can be closed.
