### ISSUE TITLE
500 error when using HIDDEN computed with query builder in a repository

### ISSUE THREAD

**Issue by kmonmousseau** [Sylius/Sylius#14750]
**Sylius version affected**: since `1.11.12` on `1.11` branch

**Description**  
500 error when using HIDDEN computed with query builder in a repository
`No metadata for DQL alias: computedPriority`

**Steps to reproduce**  
1. Add override of function `findActiveByChannel` on `PromotionRepository` as follows: 
```php
public function findActiveByChannel(ChannelInterface $channel): array
{
    $promotions = $this->filterByActive($this->createQueryBuilder('o'))
        ->addSelect('(CASE WHEN o.code LIKE :freeShippingPrefix THEN o.priority - 9223372036854775807 ELSE o.priority END) AS HIDDEN computedPriority')
        ->andWhere(':channel MEMBER OF o.channels')
        ->setParameter('channel', $channel)
        ->addOrderBy('computedPriority', 'DESC')
        ->setParameter('freeShippingPrefix', 'franco_%')
        ->getQuery()
        ->getResult()
    ;

    return $promotions;
}
```
2. Try to add something to the cart

**Possible Solution**  
It seems it comes from the class `Sylius\Bundle\CoreBundle\Doctrine\ORM\SqlWalker\OrderByIdentifierSqlWalker`, added in this specific version.
For aliased computed fields, the function `appendOrderByIdentifier` fails on `getMetadataForDqlAlias` call (`LogicException` thrown).
If we skip the call to `appendOrderByIdentifier` (line 31), everything works fine (minus the things that this class is supposed to do).

Furthermore, the use of `current` in function `isOrderByIdentifierAllowed` on line 82 is not working as intended: in my case, when evaluating the `computedPriority` that is the second expression, it returns the first one (`o`).
Last thing, this function should probably ignore expression if `hiddenAliasResultVariable` is true (or maybe like in my case, something like `ParenthesisExpression`).

**Comment by coldic3** [comment]
Hey @kmonmousseau, thanks a lot for raising the issue. I'll take a look at that this week :woman_dancing:

**Comment by coldic3** [comment]
The PR with a fix is merged, so it'll appear in the nearest release 🙂

**Comment by kmonmousseau** [comment]
Thank you @coldic3 :slightly_smiling_face:
