### ISSUE TITLE
[API] Some endpoints return 500 errors on unexpected input; proper validation is not done

### ISSUE THREAD

**Issue by rimas-kudelis** [Sylius/Sylius#14764]
**Sylius version affected**: 1.12

**Description**  
API endpoint "Retrieve payment method configuration" (`GET ​/api​/v2​/shop​/orders​/{tokenValue}​/payments​/{paymentId}​/configuration`) returns a 500 error when the referenced payment cannot be found.

There doesn't seem to be any proper validation performed on this request. Instead, an assertion is made that a payment is found (`Assert::notNull($payment)`). The failure of this assertion is not handled in any way, meaning that it ends up bubbling all the way up to the main exception handler and causing the aforementioned 500 response status.

The problematic method is [here](https://github.com/Prometee/Sylius/blob/c841247e0fc93fb88dcb117f68b49b723e752dc7/src/Sylius/Bundle/ApiBundle/Controller/Payment/GetPaymentConfiguration.php#L32-L43).

Instead of the assertion, it would make more sense to check if the value is null and return a 404 response if it is.

**Steps to reproduce**  
- Authenticate with https://demo.sylius.com/api/v2/ (the default example credentials work)
- Issue a `POST /api/v2/shop/orders` request and copy the token of your new cart
- Issue a `GET /api/v2/shop/orders/{tokenValue}/payments/{paymentId}/configuration` request. Use new cart's token for `{tokenValue}` and any random number for `{paymentId}`.
- Enjoy the 500 response you receive

**Other endpoints**
`DELETE /api/v2/shop/orders/{tokenValue}/items/{itemId}` also suffers from this problem due to the assertions made [here](https://github.com/Prometee/Sylius/blob/c841247e0fc93fb88dcb117f68b49b723e752dc7/src/Sylius/Bundle/ApiBundle/CommandHandler/Cart/RemoveItemFromCartHandler.php#L33-L51) (this can reproduced similarly). Possibly, other endpoints as well. I haven't checked them all.

**Comment by coldic3** [comment]
Hey @rimas-kudelis,
thanks for the issue. Indeed assertions should be replaced with I guess 404 errors in most cases. Would you like to open a PR with a fix?

**Comment by TheMilek** [comment]
Hi @rimas-kudelis!
Closing as it should be fixed by https://github.com/Sylius/Sylius/pull/15064 🎉
