### ISSUE TITLE
[API] Set a default address from the API

### ISSUE THREAD

**Issue by Nek-** [Sylius/Sylius#14774]
I've not much to say. From what I understand of [the current API](https://master.demo.sylius.com/api/v2), it's not possible yet to specify a default address. A custom endpoint is probably required.

**Comment by SebLours** [comment]
You have this endpoint:
`curl -X 'PUT  'https://master.demo.sylius.com/api/v2/shop/customers/1'`

**Comment by Nek-** [comment]
That indeed does a nice job at it. Thanks! (and sorry for the noise)
