### ISSUE TITLE
Error 500 on the link see the order of the thank you page

### ISSUE THREAD

**Issue by hmonglee** [Sylius/Sylius#14775]
**Sylius version affected**: 1.12.3

**Description**  
On the thank you page, if we place our order without being logged in but with an existing email in the customer and shop user tables, the button to view the order is displayed.

When we click on it, we get a 500.

`Sylius\Bundle\CoreBundle\Doctrine\ORM\OrderRepository::findOneByNumberAndCustomer(): Argument #2 ($customer) must be of type Sylius\Component\Core\Model\CustomerInterface, null given, called in /srv/sylius/vendor/sylius/resource-bundle/src/Bundle/Controller/SingleResourceProvider.php on line 32`

**Steps to reproduce**  

- Have a customer account.
- Place an order without being logged in.
- On the thank you page, click on view order.

**Possible Solution**  
Redirect to the login page when clicking on view order if we are not logged in.

**Comment by Rafikooo** [comment]
Hello @hmonglee ,

Thank you for reporting the problem, however, I have checked it on both our stable (1.12.7) and dev (1.13.x-dev) versions and when I view the order, I am redirected to the login page, so I assume this problem is no longer valid 💃 

Best regards,
Rafal
