### ISSUE TITLE
sylius/core-bundle branch 1.12.x is out of sync with sylius/sylius 1.12.x

### ISSUE THREAD

**Issue by esserj** [Sylius/Sylius#14778]
We rely on a recent fix with regards to ui-bundle usage in core, and notice that the core-bundle's 1.12 branch is outdated and requires older versions of gaufrette

Is is possible to push these changes to the readonly repo

see https://github.com/Sylius/Sylius/blob/1.12/src/Sylius/Bundle/CoreBundle/composer.json
vs https://github.com/Sylius/SyliusCoreBundle/blob/1.12/composer.json

Thank in advance!

**Comment by GSadee** [comment]
Hi @esserj! Something actually went wrong in our tool for automatic splitting into bundles and components and while the tags were up to date, the branches were no longer. So, thank you for reporting the issue, as we might not have noticed it quickly. Everything should be up to date now.
