### ISSUE TITLE
Strange behaviour of elements in admin panel after migration to webpack

### ISSUE THREAD

**Issue by EsamAl-Dabagh** [Sylius/Sylius#14793]
**Sylius version affected**: 1.12

**Description**  
After migrating from gulp to webpack using the documentation linked below, I've been getting some strange behaviour with various elements in the admin panel. The issues I've noticed:
* Unable to use the toggle buttons
* Unable to expand disclosed sections
* When clicking dropdowns they appear and then instantly disappear

I've found this closed issue (https://github.com/Sylius/Sylius/issues/14401#issuecomment-1284487422) where someone else is describing similar issues.

**Steps to reproduce**  
Follow the steps outlined in this guide: https://docs.sylius.com/en/1.12/cookbook/frontend/migrating-to-webpack-1-12-or-later.html

**Possible Solution**  
The broken elements can be fixed by deleting the configuration for `appAdminConfig` in `webpack.config.js`.

**Comment by jakubtobiasz** [comment]
Hi @EsamAl-Dabagh 🙋🏼‍♂️!
I'll take a look at the upcoming week. Did you try also on a fresh instance?

**Comment by Rafikooo** [comment]
Hey @EsamAl-Dabagh ,

We checked the installation with the docs you mentioned and it works. It is difficult to determine if it is something wrong with Sylius. Can you provide some screenshots or video that shows what is happening? Do you have any significant customization?

Best regards,
Rafal

**Comment by jakubtobiasz** [comment]
Since no response provided, I'm closing this issue. If this issue continues to occur, please let me know, and I'll reopen the issue. Optionally, you can create a new one :).
