### ISSUE TITLE
Production mode loads blank page, dev mode loads Sylius code 200 OK no errors...

### ISSUE THREAD

**Issue by thewhiterabbit** [Sylius/Sylius#14809]
What causes Sylius to load blank in prod mode and no errors in dev mode?

This behavior is very confusing. I also tried prod mode with debug set to 1 and no errors.

Brand new install on Ubuntu 22.04, PHP 8.1.2, MySQL 8.

Please help me understand.

TIA.

**Comment by Rafikooo** [comment]
Hello @thewhiterabbit ,

since your problem isn't framework specific, we encourage you to reach out to our community on slack and share some logs or screenshots 🚀 

Good luck! 💃
