### ISSUE TITLE
[API][User] Check if user is already registered 

### ISSUE THREAD

**Issue by Nek-** [Sylius/Sylius#14815]
**Describe the proposed solution**

In order to be able to reproduce the following behavior on the checkout addressing step with a frontend application, an API endpoint is missing.

https://user-images.githubusercontent.com/972456/219438007-a2afe3b0-5e7a-4b05-9b9d-e29edb7c58ed.mov

**Describe alternatives you've considered**

It's possible to use the AJAX route directly, but I think having this in the API would be better.

**Additional context**

I'd like to take the opportunity to talk around this feature: I'm not sure it's even worth keeping it for security reasons. A standard security audit will highlight such endpoints as security breaches because it exposes who is your customer.

**Comment by jakubtobiasz** [comment]
Hi @Nek- 🙋🏼‍♂️! Thanks for raising this issue.

> I'm not sure it's even worth keeping it for security reasons.

I believe that's the main reason why this feature shouldn't be present in Sylius. It should be an end-project level decision to implement such a feature, and I believe there are better tasks to pick in terms of API :P.

**Comment by Nek-** [comment]
> I believe that's the main reason why this feature shouldn't be present in Sylius.

My point was: the feature exists, but is incomplete. Either you should complete it (this is this issue) or you should remove it (and another issue may be open).

_and to complete my thinking, I think this issue is the one relevant_

**Comment by vvasiloi** [comment]
@jakubtobiasz if you think this feature should be removed because it presents a security issue, then know that you can do the same check by trying to register with an email of a registered user. I would say that you can probably do the same on virtually any other website on the internet. :)

**Comment by vvasiloi** [comment]
To be clear, I am all for not disclosing if a registered user exists, but there's more to it than just removing this feature.
Changes have to be made to the login and registration processes too.

**Comment by jakubtobiasz** [comment]
@vvasiloi this issue is about implementing (or make it easier to implement) this feature in API, not removing it from shop.

**Comment by Nek-** [comment]
Not everything is relevant in a security audit. As you mention @vvasiloi a lot of websites have this "issue". As well as the one that if you copy the cookie session of an admin, you can use his account. I think it's not critical and better to complete the feature rather than try to change errors on the registration.

**Comment by vvasiloi** [comment]
OK. I first understood that you guys are also suggesting to remove this feature from the non-headless (headful?!) implementation because it is, or might be, a security issue.

**Comment by Rafikooo** [comment]
Hello @Nek- 

After careful consideration, we have decided not to address this particular issue as we believe it could pose a potential security risk 🔐 

However, if you wish to implement it in your project on your own, we encourage you to do so. Please feel free to reach out if you have any further questions or concerns 🕺 

Best regards,
Rafał

**Comment by Nek-** [comment]
@Rafikooo , I assume there are plans to remove the existing feature then? Is there an issue about it already?

**Comment by coldic3** [comment]
@Nek- We're not going to get rid of this feature. However, we're not sure what to do with the feature for now.
