### ISSUE TITLE
Exception for entities with composite keys

### ISSUE THREAD

**Issue by sabinebaer** [Sylius/Sylius#14823]
**Sylius version affected**: 1.12.3

**Description**  
We have a custom entity which uses a composite key consisting of two columns. After upgrading to Sylius 1.12.3 the exception `Single id is not allowed on composite primary key in entity <entity>` is thrown when querying data from this entity. The exception is caused by a call to `$metadata->getSingleIdentifierFieldName()` in the new `OrderByIdentifierSqlWalker` (https://github.com/Sylius/Sylius/pull/14685/files#diff-b4a99f191d61094e80838ba2c63905cbf5d83d0b553e1d574bcb0360c7de929bR44) that throws an exception for composite keys. We can fix the problem by setting `order_by_identifier` to `false` - however, I guess this should be either fixed or a more meaningful exception should be thrown if entities with composite keys are not supported for any reason.

**Steps to reproduce**  
Create an entity with composite keys and try to query the data.

**Comment by jakubtobiasz** [comment]
Hi @sabinebaer!
Thank you very much for bringing this issue to our attention. As you might have noticed @coldic3 delivered a solution, and it'll be released along the upcoming patch version 🙌🏻.
