### ISSUE TITLE
Lexik requirement issue

### ISSUE THREAD

**Issue by Laiah** [Sylius/Sylius#14836]
**Sylius version affected**: 1.12

**Description**  
After installing [Synolia's scheduler command plugin](https://github.com/synolia/SyliusSchedulerCommandPlugin) (v.3.3), on my staging env I can't create/edit a command due to an error from [Lexik](https://github.com/lexik/LexikJWTAuthenticationBundle) : `Cannot declare trait Lexik\Bundle\JWTAuthenticationBundle\Security\Authenticator\ForwardCompatAuthenticatorTrait, because the name is already in use`
Lexik seems to have fix the issue on the 3.x branch but I can't upgrade since Sylius requires ^2.11

**Possible Solution**  
Upgrade requirement of lexik/jwt-authentication-bundle ?

**Comment by Rafikooo** [comment]
At the moment there is no stable version of 3.0 yet (only the development version `3.x-dev`), so we can't include it in our deps, but you can try to bypass it by requiring 3.x-dev with an alias:

1. Add `"lexik/jwt-authentication-bundle": "3.x-dev as 2.17.1"` to the `composer.json` in dev section
2. Run `composer update`

Hope this will helps you,
Best Regards 💃
