### ISSUE TITLE
Weird bug with Sylius mailer in CLI

### ISSUE THREAD

**Issue by Geolim4** [Sylius/Sylius#14832]
**Sylius version affected**: 1.11.y

**Description**  
I'm not sure if it's Sylius-related or not, but I've a CLI command that use the Sylius mailer to send a mail.
But the mail template seems to be unable to resolve "money" macro.

**Steps to reproduce**  
Create a basic twig template like this:
```twig
{% extends '@SyliusShop/Email/layout.html.twig' %}
{% import "@SyliusShop/Common/Macro/money.html.twig" as money %}

{% block subject %}
    My subject
{% endblock %}

{% block content %}
    <p>{{ 'my_language_key'|trans({'%number%': order.number, '%amount%': money.convertAndFormat(amount, order.currencyCode)})|raw }}</p>
{% endblock %}

```
This will lead to the following error: ` -rawMessage: "An exception has been thrown during the rendering of a template ("Notice: Undefined index: money")." `
In fact this goes further as I'm not able to use any  macro via import in CLI context with Sylius Mailer service?

**Possible Solution**  
ATM, no idea at all.

**Comment by JoppeDC** [comment]
From the top of my head - I think you need to include the macro within the block.

iirc, the default template would look something like this:
```
{% block content %}
    {% include '@SyliusCore/Email/Blocks/OrderConfirmation/_content.html.twig' %}
{% endblock %}
``` 

Where you would include the macro within the `_content` file. -> Which leads me to believe it should be within the block

**Comment by Geolim4** [comment]
> From the top of my head - I think you need to include the macro within the block.
> 
> iirc, the default template would look something like this:
> 
> ```
> {% block content %}
>     {% include '@SyliusCore/Email/Blocks/OrderConfirmation/_content.html.twig' %}
> {% endblock %}
> ```
> 
> Where you would include the macro within the `_content` file. -> Which leads me to believe it should be within the block

I tried that, it works, but it seems to be glitchy since including the macro out of block works well on web mode (php fcgi).

**Comment by Rafikooo** [comment]
Hello @Geolim4 ,

Since this workaround works and this case is not on the state of our knowledge specific to Sylius, we decided to close this ticket. 
If you have any additional concerns do not hesitate to open another ticket 💃 

Best, Rafał 🚀
