### ISSUE TITLE
the OpenAPI JSON file generated with 'api:openapi:export' contains invalid enum value

### ISSUE THREAD

**Issue by lmichelin** [Sylius/Sylius#14878]
**Sylius version affected**: 1.12.5

**Description**  
The JSON file generated with the `api:openapi:export` command contains invalid enum value for the `/api/v2/shop/product-images/{id}` GET route:

```json
...
    "/api/v2/shop/product-images/{id}": {
      "get": {
        "parameters": [
          {
            "name": "filter",
            "in": "query",
            "description": "Provide one of supported image liip imagine filters.",
            "schema": { "type": "string", "enum": "" }
          },
...
```

The `enum` property must be array.

**Steps to reproduce**  
- bootstrap a sylius project
- run the `api:openapi:export` command or visit the http://localhost:8000/api/v2/docs.json route
- search for the `"enum": ""` string

**Possible Solution**  
In the `src/Sylius/Bundle/ApiBundle/Resources/config/api_resources/ProductImage.xml` file, line 42, remove the enum property or fill it with the supported liip imagine filters.

**Comment by jakubtobiasz** [comment]
Hello,
thanks to @NoResponseMate work, we've managed to resolve this issue.

Thanks for reporting, fix will be released along the Sylius `1.12.8` :).
