### ISSUE TITLE
the /api/v2/shop/authentication-token route is missing from JSON generated with 'api:openapi:export' command

### ISSUE THREAD

**Issue by lmichelin** [Sylius/Sylius#14877]
**Sylius version affected**: 1.12.5

**Description**  
I am using [Orval](https://orval.dev/) to generate an API client and so I need to generate an OpenAPI JSON spec. To get this file, I identified 3 options:
- go to http://localhost:8000/api/v2/docs.json -> ❌ the `/api/v2/shop/authentication-token` route is missing
- go to http://localhost:8000/api/v2?ui=re_doc and click on `Download` -> ✅ the `/api/v2/shop/authentication-token` route is present
- use the `api:openapi:export` command -> ❌ the `/api/v2/shop/authentication-token` route is missing

In order to automate the API client generation, I would prefer the 3rd solution (using the command).

**Steps to reproduce**  
- Bootstrap a sylius project
- go to http://localhost:8000/api/v2/docs.json
- search for `/api/v2/shop/authentication-token` -> ❌ the user login route is missing

**Possible Solution**  
It seems that the `Sylius\Bundle\ApiBundle\Swagger\ShopAuthenticationTokenDocumentationNormalizer` class only affects the swagger UI, and not the generated openapi JSON file.
A possible solution could be to extend the `OpenApiFactoryInterface`, as it is done in the `Lexik\Bundle\JWTAuthenticationBundle\OpenApi\OpenApiFactory` class

**Comment by NoResponseMate** [comment]
Hi @lmichelin 
Can confirm and it seems to be the same case with the admin's endpoint as well.
Would you be so kind to open a PR that covers them in openAPI?
