### ISSUE TITLE
erroneous scss symbol running `encore prod` during upgrade 

### ISSUE THREAD

**Issue by maxperei** [Sylius/Sylius#14883]
```from Css Minimizer
JisonLexerError: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: 100% - $layout-sidebar-width
^.........^
```
error is located here : https://github.com/Sylius/Sylius/blob/df55a701a0fe90c12ce4a495bab3fbe89291a45d/src/Sylius/Bundle/AdminBundle/Resources/private/sass/_layout.scss#L91

**Comment by jakubtobiasz** [comment]
Idk why GitHub didn't close this issue, as the PR containing the closing word has been merged 🤷🏼‍♂️. Anyway, it'll be fixed in the upcoming release (I guess `1.12.6` will be in a few days).
