### ISSUE TITLE
Error when upgrading to jquery 3.6.4

### ISSUE THREAD

**Issue by UlrichHP** [Sylius/Sylius#14888]
**Sylius version affected**: 1.12.5

**Description**  
Upgrading to jquery 3.6.4 causes admin to stop working correctly.
Admin is working fine with jquery 3.6.3

Anyone else having this issue ?

**Steps to reproduce**  
Upgrade jquery to version 3.6.4

![image](https://user-images.githubusercontent.com/27560999/227575902-c80f2749-874d-4c74-9724-d585099a6bcf.png)

**Comment by UlrichHP** [comment]
UPDATE: I installed SyliusStandard and only updated jQuery to v3.6.4 and i have the same errors

**Comment by jakubtobiasz** [comment]
Hello 🙋🏼‍♂️,
Can you provide how you bump the version, whether you rebuild the frontend and on which exactly page you get this error? I bumped jQuery to `3.6.4` and no error on few pages I've checked.

**Comment by UlrichHP** [comment]
Hello @jakubtobiasz.
Sure i updated it with yarn berry (v3.5.0) `upgrade-interactive` command and i have this error on every pages in admin after doing `yarn encore dev` or `yarn encore production.`

When i tried on a fresh new SyliusStandard project, i just updated package.json manually to `"jquery": "^3.6.4"` and did a `yarn build`

The screenshot was taken on the admin dashboard if i remember correctly.

**Comment by jakubtobiasz** [comment]
Do you use `"@sylius-ui/frontend": "^1.0"` or the old version with all packages declared separately? I've found out that we release `1.12.2` SS in Nov 2022, and I introduced `"@sylius-ui/frontend": "^1.0"` package after this date. I've checked it only on the new version, not the old one.

You can compare your packages.json with this one https://github.com/Sylius/Sylius-Standard/blob/1.12/package.json.

**Comment by UlrichHP** [comment]
I use the old version with all packages.

If it's because of this, will `"@sylius-ui/frontend": "^1.0"` be available on `Sylius/sylius` 1.12.* branch or only 1.13 ?
Is there a doc on how to add it to an already existing sylius project ?

Thanks

**Comment by jakubtobiasz** [comment]
@UlrichHP it's on `1.12` branch of SS, but it isn't tagged yet, we'll do it soon. You can copy the content of `package.json`, delete `package.lock`... and it should work :D.

**Comment by UlrichHP** [comment]
@jakubtobiasz it is working on SyliusStandard.

But what about a bigger project using Sylius and other dependencies in it's `package.json` ?
Will there be an upgrade doc on how to add `@sylius-ui/frontend` ?

**Comment by jakubtobiasz** [comment]
The same way. `@sylius-ui/frontend` is a set of the same packages with bumped deps. When we bump any of the deps in `Sylius/Sylius` we release a new version of `@sylius-ui/frontend`. Thanks to it, we can manage deps versions on the end-site, previously we were relying on devs to update the packages while updating Sylius.
