### ISSUE TITLE
Incorrect use of IS_AUTHENTICATED_FULLY with "remember me" functionality

### ISSUE THREAD

**Issue by olia-bn** [Sylius/Sylius#14898]
**Description**  
A few places across multiple bundles check against `IS_AUTHENTICATED_FULLY` (user went through form log in in this session) expecting the weaker behaviour of `IS_AUTHENTICATED_REMEMBERED` (any logged in user, also through "remember me"). [Reference @SymfonyDocs](https://symfony.com/doc/6.3/security.html#checking-to-see-if-a-user-is-logged-in).

Since Sylius offers "remember me" functionality, it may cause unexpedted results.

One of them is described in #9430.

**Steps to reproduce**  
1. Log in shop user with the "remember me" enabled
2. Access Sylius frontend using Remember me functionality
3. Go to product review form

**Possible Solution**  
For #9430, the check can be changed to `is_granted('IS_AUTHENTICATED')` or `is_granted('IS_AUTHENTICATED_REMEMBERED')`. Alternatively `{% if form.author is defined %}` will also solve the issue, since adding the sub form is already dependant on having a logged in user.

All other checks should be reviewed case-by-case, but I believe it's safe to assume that almost anything in a template can be safely replaced with `is_granted('IS_AUTHENTICATED')` (or `IS_AUTHENTICATED_REMEMBERED`)

**Comment by jakubtobiasz** [comment]
Hi @olia-bn 👋🏼!
Thanks for pointing this out, I'll schedule this issue on our upcoming internal meeting to discuss it 🤙🏼.

**Comment by TheMilek** [comment]
Hi @olia-bn!

I wanted to let you know that we have discussed this issue during our meeting and have decided to address it 🎉 
In the meantime, we would greatly appreciate any PR you may have to offer 🍻 

Thank you for your interest and please let us know if you have any further questions or concerns 😄
