### ISSUE TITLE
Allow configuring which non-GET HTTP actions may be applied to already checked out orders

### ISSUE THREAD

**Issue by rimas-kudelis** [Sylius/Sylius#14895]
There are currently two Doctrine query item extensions which limit  accessibility to already checked out orders to GET operations and a few whitelisted non-get operations only. These are `OrderShopUserItemExtension` and `OrderVisitorItemExtension`.

Both of them have a hardcoded list of non-GET routes which are allowed. It would be great if this could be made more flexible by injecting the whitelisted routes into their constructors instead. This would allow adding new post-cart non-GET routes and whitelist them easily without having to decorate these services by copying their class files into our own namespaces.

The files and lines I'm referring to are these:

https://github.com/Sylius/Sylius/blob/0dd5b760d8c7e9fffa0297276968e3c5f1034ccb/src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/OrderShopUserItemExtension.php#L59-L65

https://github.com/Sylius/Sylius/blob/0dd5b760d8c7e9fffa0297276968e3c5f1034ccb/src/Sylius/Bundle/ApiBundle/Doctrine/QueryItemExtension/OrderVisitorItemExtension.php#L65-L67

**Comment by TheMilek** [comment]
Hi @rimas-kudelis! 
It sounds really good to have it 😄 
Could you provide a PR with potential solution? 🚀

**Comment by Rafikooo** [comment]
Hello future readers,

we would like to inform you that we have placed this issue in our backlog. However, If you would like to contribute to the development of Sylius by improving this case, we strongly encourage you to do so 💃

**Comment by Rafikooo** [comment]
Hey @rimas-kudelis,

We have already merged the PR. See if it meets your expectations 🚀 

Best regards,
Rafał
