### ISSUE TITLE
Add customers' addresses management to admin

### ISSUE THREAD

**Issue by elboletaire** [Sylius/Sylius#14906]
Set as feature, although this could be considered a bug, since there's no way to edit addresses from sylius admin. The only place I've seen you can change some addresses is in the orders, and those addresses aren't directly linked to the customer.

**Describe the proposed solution**
To have the addresses management in the customers edit, like in the image below
![imatge](https://user-images.githubusercontent.com/153305/229158792-94354102-d30c-4a6c-9444-045656154cff.png)

**Describe alternatives you've considered**
A specific section only for addresses, but I think adding them in the customers would work for everyone and does not require an additional section in the admin.

**Additional context**
Here's how it looks by default (taken from the demo page):
![imatge](https://user-images.githubusercontent.com/153305/229159277-c792980d-581c-44dc-811a-97f4da00afcf.png)

Note addresses can be seen when using the "show" button in customers, but then if you edit the customer there's no way to add, edit or remove any addresses for the customer.

I personally fixed this in my installation by adding a `CustomerTypeExtension`, but for some reason I still don't comprehend, new records are not properly saving the customer id, so I'm not a good candidate for making a PR sadly.

**Comment by Rafikooo** [comment]
Hello @elboletaire ,

Thanks for sharing your idea, however, we discussed it and decided that it does not fit for our current goals 💃 

Best regards,
Rafal
