### ISSUE TITLE
Error when using Azure ADB2C OAuth2 tokens

### ISSUE THREAD

**Issue by crabatel** [Sylius/Sylius#14954]
**Sylius version affected**: 1.12.7

**Description**  
When using the HWIOAuth2 bundle to allow shop users to log in with Azure, the user receive this error after being redirected to the shop from Azure authorize URL :

```
An exception occurred while executing 'INSERT INTO sylius_user_oauth (provider, identifier, access_token, refresh_token, user_id) VALUES (?, ?, ?, ?, ?)' with params ["azure", "7d702f0b-2c72-457a-891c-3a58e6ba52df", "eyJhbGciOiJSUzI1NiIsImtpZCI6Ii13WFktM...", null, 3]:

SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'access_token' at row 1

```

**Steps to reproduce**  
An HWIOAuth2 Resource Owner must be configured for Azure.

**Possible Solution**  
`UserOAuth` entity defines two columns `access_token` and `refresh_token`  with a type `string`, but this results in columns of `varchar(255)`, however Azure ADB2C tokens can have more than 1000 characters.

Using a type of `text` for both columns solves this error.

Thanks.

**Comment by Rafikooo** [comment]
Hello @crabatel,

Thank you for reporting the problem. We have already fixed it [here](https://github.com/Sylius/Sylius/pull/14930)
Since it will be available from Sylius 1.13, for now rely on your solution 💃 

Best regards,
Rafal :)
