### ISSUE TITLE
PromotionProcessor performance

### ISSUE THREAD

**Issue by stephanietln** [Sylius/Sylius#14983]
Hi all, 
Can someone explain to me why method `findActiveByChannel`  of `PromotionRepository` doesn't filter on promotions without couponBased ? 
I don't understand why when PromotionProcessor is running, the Promotion of a PromotionCoupon is included in `$preQualifiedPromotions`?
When we have a lot of Promotions with coupons, performance is heavily impacted

Thanks for support

**Comment by jakubtobiasz** [comment]
Hello,
all promotions are gathered as any type of promotion is applied if eligible. We could check if there's a coupon code provided and include coupon-based promotions only in such case. 

If you like, feel free to open a PR; otherwise, there's a chance we'll do it, but at a later time.

**Comment by GSadee** [comment]
I'm closing the issue as it has been fixed by #15088
