### ISSUE TITLE
CLI tools broken when anything uses the `sylius.storage.locale` service

### ISSUE THREAD

**Issue by mbabker** [Sylius/Sylius#15011]
**Sylius version affected**: At least 1.11, though it's more Symfony version dependent than Sylius most likely

**Description**  
Any services which run on the command line and use the `sylius.storage.locale` service eventually fail with a `Symfony\Component\HttpFoundation\Exception\SessionNotFoundException` being thrown.  https://github.com/stefandoorn/sitemap-plugin/issues/228#issuecomment-1413586403 is just one example with a full stack trace, I noticed it in my logs for the `setono/sylius-feed-plugin` as well.

**Steps to reproduce**  
Run a console command that uses the `sylius.storage.locale` service in some way (anything using the `sylius.context.locale` service should work here), notice it fails with a `Symfony\Component\HttpFoundation\Exception\SessionNotFoundException`.

**Possible Solution**  
Two things I can immediately think of:

- A listener on the `console.command` event to push a dummied request into the request stack with a runtime backed session (ugly but it would work)
- Add another tagged `sylius.context.locale` service with a higher priority than the `sylius.context.locale.storage_based` service that only provides a locale on CLI so that the storage based service never runs and never needs to read out of the session

(This is probably an issue for all composite context services with a session based storage, but the locale one is probably the most visible case since there are a number of use cases for generating URLs in a CLI context)

**Comment by zambodaniel** [comment]
same here

**Comment by jakubtobiasz** [comment]
Hello,
we added this issue to the backlog.

**Comment by lruozzi9** [comment]
The issue is caused by the v1.10 of the resource-bundle with Symfony 5!
The StorageBasedLocaleContext calls the Sylius\Component\Core\Locale\LocaleStorage that calls the \Sylius\Bundle\ResourceBundle\Storage\SessionStorage. This latter causes problems only on behat test env (in my case) or in cli contexts because there is not a real "request" in the context where it is called (it is obviously in cli, less in behat where a dumb request should exist anyway). So the session on the request stack does not exist.
Instead, using the SessionInterface (as done previously with Sf 5) it works. A temp fix could be decorate the service as follows:
```
    app.storage.session:
        class: Sylius\Bundle\ResourceBundle\Storage\SessionStorage
        decorates: sylius.storage.session
        arguments:
            - '@session'
```

**Comment by mbabker** [comment]
Another solution working for us, decorate the `sylius.context.locale.storage_based` service, catch the `SessionNotFoundException` and wrap it into `LocaleNotFoundException`, and let the composite context keep trying (given that `sylius.context.locale.provider_based` is available and at a lower priority than `sylius.context.locale.storage_based`, letting the composite fall back to this service is getting things working for us):

```yaml
services:
    App\Locale\Context\StorageBasedLocaleContext:
        decorates: sylius.context.locale.storage_based
        arguments:
            - '@App\Locale\Context\StorageBasedLocaleContext.inner'
```

```php
<?php declare(strict_types=1);

namespace App\Locale\Context;

use Sylius\Component\Locale\Context\LocaleContextInterface;
use Sylius\Component\Locale\Context\LocaleNotFoundException;
use Symfony\Component\HttpFoundation\Exception\SessionNotFoundException;

/**
 * Decorator for the {@see \Sylius\Component\Core\Locale\Context\StorageBasedLocaleContext} class to catch {@see SessionNotFoundException} to avoid fatal errors when used in a command-line context.
 *
 * @link https://github.com/Sylius/Sylius/issues/15011
 */
final class StorageBasedLocaleContext implements LocaleContextInterface
{
    public function __construct(
        private LocaleContextInterface $decoratedLocaleContext,
    ) {
    }

    public function getLocaleCode(): string
    {
        try {
            return $this->decoratedLocaleContext->getLocaleCode();
        } catch (SessionNotFoundException $exception) {
            throw new LocaleNotFoundException(null, $exception);
        }
    }
}
```

**Comment by lruozzi9** [comment]
Yes, IMHO this last one is better!

**Comment by Geolim4** [comment]
> Another solution working for us, decorate the `sylius.context.locale.storage_based` service, catch the `SessionNotFoundException` and wrap it into `LocaleNotFoundException`, and let the composite context keep trying (given that `sylius.context.locale.provider_based` is available and at a lower priority than `sylius.context.locale.storage_based`, letting the composite fall back to this service is getting things working for us):
> 
> ```yaml
> services:
>     App\Locale\Context\StorageBasedLocaleContext:
>         decorates: sylius.context.locale.storage_based
>         arguments:
>             - '@App\Locale\Context\StorageBasedLocaleContext.inner'
> ```
> 
> ```
> <?php declare(strict_types=1);
> 
> namespace App\Locale\Context;
> 
> use Sylius\Component\Locale\Context\LocaleContextInterface;
> use Sylius\Component\Locale\Context\LocaleNotFoundException;
> use Symfony\Component\HttpFoundation\Exception\SessionNotFoundException;
> 
> /**
>  * Decorator for the {@see \Sylius\Component\Core\Locale\Context\StorageBasedLocaleContext} class to catch {@see SessionNotFoundException} to avoid fatal errors when used in a command-line context.
>  *
>  * @link https://github.com/Sylius/Sylius/issues/15011
>  */
> final class StorageBasedLocaleContext implements LocaleContextInterface
> {
>     public function __construct(
>         private LocaleContextInterface $decoratedLocaleContext,
>     ) {
>     }
> 
>     public function getLocaleCode(): string
>     {
>         try {
>             return $this->decoratedLocaleContext->getLocaleCode();
>         } catch (SessionNotFoundException $exception) {
>             throw new LocaleNotFoundException(null, $exception);
>         }
>     }
> }
> ```

Agree, StorageBasedLocaleContext must catch SessionNotFoundException indeed.

**Comment by stefandoorn** [comment]
Thanks @mbabker - experiencing it at several places as well.

**Comment by ElBidouilleur** [comment]
I've the same problem but all answers i find not resolve the problem with sylius 1.13.5
