### ISSUE TITLE
Missing method on interface for ShopBasedCartContext

### ISSUE THREAD

**Issue by lruozzi9** [Sylius/Sylius#15021]
**Sylius version affected**: 1.12

**Description**  
The Sylius\Component\Core\Cart\Context\ShopBasedCartContext class has a public method reset invoked by Symfony on kernel.reset tag. The problem is that this method is not added to any interface. It could not be added in CartContextInterface because it will be a BC, but a new interface should be added to inform users that decorate that class of this method.

**Steps to reproduce**  
Decorate the service sylius.context.cart.new_shop_based by implementing the CartContextInterface. 

**Possible Solution**  
Add a new ShopBasedCartContextInterface?

**Comment by GSadee** [comment]
Hi @lruozzi9!

Thank you for providing an issue. There can indeed be a problem when someone decorates this service. 
Probably the best approach would be to add a new interface for this added method, remove the tag from the definition and add it conditionally in a compiler pass when this new interface is implemented.

We've added a task in our backlog to resolve this problem, however, if you would like to contribute with the fix, feel free to open a PR 😃

**Comment by palttamas** [comment]
@GSadee Is this sort of what you were thinking of? https://github.com/Sylius/Sylius/pull/15162

**Comment by jakubtobiasz** [comment]
@palttamas it is :)

**Comment by TheMilek** [comment]
Closing as it should be fixed by https://github.com/Sylius/Sylius/pull/15162

**Comment by lruozzi9** [comment]
Cool 🚀
