### ISSUE TITLE
Complete OpenAPI schema 

### ISSUE THREAD

**Issue by plewandowski** [Sylius/Sylius#15073]
**Describe the proposed solution**
Not sure if a feature... I wish there could published openapi schema for all Sylius endpoints.  Endpoints does not have to be implemented. Schema may change (as new API is experimental). However I think it could be very useful for many people to know how it is going to look like.... it may also trigger many productive discussions :-) 

**Describe alternatives you've considered**
Implementing own endpoints or choosing another platform :( 

**Additional context**
We are planning future integration with Sylius. We are at the point of time where we can choose between:
- Old Sylius API
- New Sylius API which is not completed yet

We can accept that new api is unstable and experimental. What makes it difficult to work with is that we do not know what's new API will offer in near feature.

**Comment by LeoMoshko** [comment]
Good proposition. I think it will be useful to a lot of people

**Comment by Prometee** [comment]
Is it what you were looking for : https://demo.sylius.com/api/v2 ?

**Comment by Rafikooo** [comment]
Hello @plewandowski, thank you for submitting the issue. We're happy to announce you that our API became stable both for the shop and admin parts 🎉 
Here's the full, up-to-date documentation:
https://master.demo.sylius.com/api/v2
Sylius 1.13-RC.1 release:
https://github.com/Sylius/Sylius/releases/tag/v1.13.0-RC.1
