### ISSUE TITLE
Overide checkout process 

### ISSUE THREAD

**Issue by LuigiG34** [Sylius/Sylius#15094]
This is my first time working with Sylius and i find it quite hard to get my hands on any information online regarding it.

I would like to know if anyone knows how i could either : overide the entire checkout process with my own, i have tried to overide to routes but i still get the old ones.

Thank you in advance

**Comment by NoResponseMate** [comment]
Hi @LuigiG34 

There are docs regarding this [here](https://docs.sylius.com/en/1.12/cookbook/shop/checkout.html).
Although they're marked as outdated, AFAIK they **should** still work, with a somewhat strong emphasis on should, but I don't recall any major changes to the checkout process.

If you have other questions regarding customization and such, the fastest way is to ask on our [Slack](https://sylius.com/slack), there's always someone there willing to help.

If that helped, please close the issue.
Cheers :beers:

**Comment by LuigiG34** [comment]
Thank you yes i finished by finding the answer to my question :)
