### ISSUE TITLE
[API] Product filter is not working when specifying multiple taxon codes

### ISSUE THREAD

**Issue by Joklogh** [Sylius/Sylius#15107]
**Sylius version affected**: 1.12.8

**Description**  
When I try to filter products by API endpoint `/api/v2/shop/products` and using `productTaxons.taxon.code[]` as a filter, the endpoint returns an error status code.
The error is the following:
_TypeError: Sylius\Bundle\ApiBundle\Doctrine\QueryCollectionExtension\ProductsByTaxonExtension::addSortingToQuery(): Argument #2 ($taxonCode) must be of type string, array given, called in /usr/src/app/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Doctrine/QueryCollectionExtension/ProductsByTaxonExtension.php on line 51_

**Steps to reproduce**  
Call the `/api/v2/shop/products` endpoint while specifying `productTaxons.taxon.code[]` as a filter

**Comment by jakubtobiasz** [comment]
Hi @Joklogh 👋🏼

Thanks for reporting, we will investigate your issue soon :).

**Comment by Joklogh** [comment]
Thanks a million. Don't hesitate to contact me if you need further clarification.

**Comment by palttamas** [comment]
@jakubtobiasz I made branches that fixes this, PRs

for 1.13 https://github.com/Sylius/Sylius/pull/15160
for 1.12 https://github.com/Sylius/Sylius/pull/15161

**Comment by TheMilek** [comment]
Closing as it should be solved by https://github.com/Sylius/Sylius/pull/15161 🎉 
Thank you @palttamas!

**Comment by Joklogh** [comment]
@TheMilek When can we anticipate rolling the fix out?

**Comment by TheMilek** [comment]
@Joklogh It will be available from the next release of Sylius 1.12, most likely something like next week 🚀

**Comment by jakubtobiasz** [comment]
The next patch version is planned for this week.
