### ISSUE TITLE
Can't install TaxonomiesBundle

### ISSUE THREAD

**Issue by etoileweb** [Sylius/Sylius#1513]
Hi,
I'm trying to use TaxonomiesBundle in a Symfony2 project but I'm stuck. I enabled the bundles in the AppKernel and made all configurations according to the documentation instructions, but I got the following error message: 
```
[Gedmo\Exception\InvalidMappingException]
Unable to find ancestor/parent child relation through ancestor field - [parent] in class - Sylius\Bundle\TaxonomiesBundle\Model\Taxon
```
Any help please?

**Comment by adamelso** [comment]
The docs on the Taxonomy bundle are severely out of date, and I remember running into the same issue as @etoileweb . I've been working it it quite a lot recently so I'll be submitting doc updates soon :).
