### ISSUE TITLE
Possible conflict with stof/doctrine-extensions-bundle 1.8.0

### ISSUE THREAD

**Issue by laurentdabbb** [Sylius/Sylius#15171]
**Sylius version affected**: 1.12.x

**Description**  
In my Sylius project "position" (Gedmo sortable) and "updated_at" (Gedmo timestampable) fields were no more updated for about 10 days. 
Everything works fine in my development environment but in production these fields are only updated on custom entities and not on Sylius ones. 
After investigations, I discovered the problem comes from the latest release of "stof/doctrine-extensions-bundle" (1.8.0). By downgrading to 1.7.2 everything worked fine again.

I don't know what the problem is precisely, but I note this plugin adds a configuration about metadata cache in the latest version. 
I'm using the doctrine configuration provided by Sylius Standard and for production environment a metadata cache driver is defined (but not in dev env). I think it's a clue, but I'm not sure.

**Possible Solution**  
Declare "stof/doctrine-extensions-bundle" ~1.8.0 in conflict. 
Or fix it if possible

Thx

**Comment by jakubtobiasz** [comment]
Hello @laurentdabbb 👋🏼!
We're aware of this issue, and we've added a conflict last week https://github.com/Sylius/Sylius/pull/15154. I guess the next patch version should be released this or next week 😄.
