### ISSUE TITLE
[BUG] This form should not contain extra fields. In checkout billing address step

### ISSUE THREAD

**Issue by lithualien** [Sylius/Sylius#15183]
**Sylius version affected**: 1.12.9 (Tested on demo,sylius.com)

**Description**  
A customer starts the checkout billing address step and tries to complete with invalid data.
After submitting the invalid form user tries to login and the form and receives error of: _This form should not contain extra fields_
The extra field in this case is the Customer entity, $email parameter.
The login action submits whole form, it does not reload the page.

**Steps to reproduce**
Buyer did not log in.
Buyer added a product the cart.
Buyer started checkout process.

https://github.com/Sylius/Sylius/assets/45800655/34b2959f-621f-4417-8300-017bd71b1bb5

**Comment by jakubtobiasz** [comment]
Hello @lithualien 👋🏼,
as far as I remember, I reproduced the bug and I can confirm it exists. @SzymonFilipek can you recheck this on the latest `1.12`?

**Comment by SzymonFilipek** [comment]
Hi @jakubtobiasz, 
I recreated the bug on the 1.12.10 version and can confirm that it still exists.

**Comment by Wojdylak** [comment]
Hi
I recreated the bug and figured out why it happens. After logging in, there is a jQuery script that refreshes the page using `window.location.reload()`. This refresh triggers a form submission with the old CSRF token and email, causing the validation notification to appear. There is a possibility to change this to `window.location.href = window.location.href`, but this would result in losing the data in the form.
