### ISSUE TITLE
Miscalculation of discount with combination of cart promotion rules

### ISSUE THREAD

**Issue by kgonella** [Sylius/Sylius#15199]
**Sylius version affected:** at least 1.11.x and higher

**Description:**
The combination of cart promotion (order discount) and a cart promotion (order item discount) can lead to a miscalculation of the overall discount.

**Steps to reproduce:**

**Shop context:**

**2 products**

- Product A priced at $100
- Product B priced at $75

**2 cart promotions**

- Rule 1: Cart promotion that gives a fixed discount of $50 on the order
- Rule 2: Cart promotion that gives a 100% discount on PRODUCT B

Add the 2 products to the cart.

**CASE 1: Rule 1 has higher priority than Rule 2**

1. Rule 1 is applied first.
   - The $50 fixed discount is distributed between Product A and Product B.
   - Internally, 2 adjustments of -$25 each are created on each product. So Product A is now $75, and Product B is $50.

2. Rule 2 is applied next.
   - Product B is now 100% discounted and goes to $0.

The total discount is $125 ($50 from Rule 1 and $75 from Rule 2).

**CASE 2: Rule 2 has higher priority than Rule 1**

1. Rule 2 is applied first.
   - Nothing is done to the price of Product A. Product B goes from $75 to $0.

2. Rule 1 is applied next.
   - Product A receives an equal part of the $50 order discount (-$25). So Product A is now $75.
   - Then, the UnitsPromotionAdjustmentsApplicator tries to apply the same discount on Product B, but Product B's price is now $0 and can be further discounted.

The total discount is incorrect: $100 ($75 from Rule 2 and only $25 from Rule 1).
You lose $25 of discount that could have been applied.

**Possible Solutions:**

**Solution 1:**
Do some precalculation somewhere between `FixedDiscountPromotionActionCommand`, `UnitsPromotionAdjustmentsApplicatorInterface` to be able to fully dispatch the discount on items.

**Solution 2:**
Create a loop that will handle this case, if at the end of distribution, the discount is not fully applied, loop again on all cart items.

**Comment by GSadee** [comment]
Hi @kgonella!

thank you for reporting the issue, unfortunately, I think you have somewhat confused the different scenarios or just the priorities of cart promotions. I have reproduced the provided by you scenarios and the behaviours are as we expect.

Case 1:
<img width="1132" alt="image" src="https://github.com/Sylius/Sylius/assets/6140884/bb2fb568-694e-463f-bc2b-fe9b80705470">
<img width="1389" alt="image" src="https://github.com/Sylius/Sylius/assets/6140884/eb455f0b-46e5-413e-829a-f112265bd733">
The promotion on the order, which is applied first, is distributed proportionally to both products and then the second promotion applies to the second product to zero its price.

Case 2:
<img width="1122" alt="image" src="https://github.com/Sylius/Sylius/assets/6140884/552288af-7193-4b13-af35-96c7d905b332">
<img width="1405" alt="Zrzut ekranu 2023-08-4 o 09 48 20" src="https://github.com/Sylius/Sylius/assets/6140884/af52be89-4c86-400e-89ff-6f84249b43f1">
The promotion on the order, which is applied second, is distributed in full only to the first product.

Feel free to comment or open a new issue if I have missed something 😃

**Comment by kgonella** [comment]
I'm not confused about the way the cart promotion is applied technically, but as a customer.

If a customer adds a fully discounted product to the cart and then applies a code that removes $50 from the order, they will not get the same total if the shop admin did not set the priority well (order discount with higher priorities than item discounts).

From my customer point of view, I can understand CASE 1 in terms of discount. Case 2 can give me some frustration as to why I didn't get my $50 order discount fully applied.

Now, if we can't do something here in terms of code, we can maybe warn people (developers and end-users) in documentation or user guide.
