### ISSUE TITLE
Catalog promotion action amount is always replaced with comma instead of dot preventing validation

### ISSUE THREAD

**Issue by talbotseb** [Sylius/Sylius#15193]
**Sylius version affected**: 1.12.8

**Description**  

There is a validation error when creating or editing a promotion with a "fixed discount". The system requires the use of a decimal point instead of a comma in the discount amount. However, when editing a promotion, the system automatically inserts a comma in the discount amount, which prevents the form from being validated, even if we don't wish to change the amount.

**Steps to reproduce** 

1. Login to the Sylius platform.
2. Navigate to the catalog promotion creation page.
3. Fill in the necessary fields and in the discount amount of the action, use a comma instead of a decimal point.
4. Try to submit the form, an error prompt appears, preventing validation.
5. Now, change the comma to a decimal point in the discount amount and submit the form again, the form is submitted successfully.
6. Proceed to modify the promotion you just created.
7. Observe that in the amount field, there is a comma automatically inserted instead of a decimal point, preventing the form submission.

**Possible Solution**
<img width="665" alt="Capture d’écran 2023-07-31 à 16 19 59" src="https://github.com/Sylius/Sylius/assets/10520131/8fff0fee-d116-4b9c-a656-06df6299ae74">

The form validation process and the automatic comma insertion when editing promotions should be updated to allow both commas and decimal points, or to enforce consistency in the use of decimal separators.

**Comment by jakubtobiasz** [comment]
Hello @talbotseb 👋🏼
I'm happy to let you know #15214 should resolve your issue. It should be released along with version `1.12.11` :).
