### ISSUE TITLE
Leverage Sonata Admin?

### ISSUE THREAD

**Issue by Richtermeister** [Sylius/Sylius#1519]
Hi all, 

I am aware of Sylius' position on the admin-generator subject, and I also appreciate the use-cases the ResourceBundle has been created for. However, I think the Sonata Admin warrants another serious look. I recently had the pleasure of integrating it into one of my sites, and the experience has been nothing but great.

I agree with the general notion that we don't want to be forced into a certain way of doing things, or limited in our abilities, but looking at the recurring patterns across Sylius' admin area and the related routes and templates, we are incurring a lot of admin-generator-like rigidity and overhead to apply central customizations, while even staying behind the functionality the Sonata Admin would give us out of the box.

Specifically, aside from a reduction in routes and templates to maintain, we would gain the ability to customize our filters and data-grids much more easily, even on a per-user/role base if we wanted. Looking ahead at a more granular permissions system this ability will have to be addressed sooner or later. This would also settle the old argument of whether to show the ID column or not (it just becomes a setting or only super-admins get it, etc).

Furthermore, the bundle supports solid batch actions and export functionality natively and makes it easier to do cross-entity search.

Another pain-point I am starting to encounter with Sylius is to integrate my company's bundles into it. We maintain a set of bundles for recurring needs such as blog/media/calendar, etc, but integrating them into Sylius requires us to update a lot of templates to make the integration seamless. I think if we build our admin area around the Sonata Admin, more and more 3rd party bundles will be drop-in ready without any need for customization.

Please let me know what you think of all this, and thank you for your time.

**Comment by psyray** [comment]
Hi,

I bump up this issue because I think it's really important for admin ergonomy to enable batch process as soon as possible.
Currently, it's a pain to edit multiple resource object (mass deletion, publishing content...).

I think we could quickly implement checkbox column with mass actions dropdown list in the resource object.

I could try to submit a PR for this, but I'm not so aware with the feature part.
Is this mandatory to add a scenario to achieve this action ?

If not I will try to work on it today because I need this part very quickly for my own project, and I prefer working on the Sylius project first to share with others and me too ;)

Please let me know asap.

**Comment by ConneXNL** [comment]
I think it would be great of all parties (Oro, Sonata, Sylius) don't re-invent the wheel and work towards a single solution based on components. This would help drive the Symfony community further too.

**Comment by sagikazarmark** [comment]
@pjedrzejewski May I ask why this is closed? Is there a decision not to use Oro/Sonata? Any plans?

Asking because it is not obvious in this issue.

**Comment by pjedrzejewski** [comment]
@sagikazarmark Sorry, I should have commented here before closing! We are cleaning up all the issues and I was too fast. :) I mentioned it in other issues but for reference: We will very soon provide alternative that works on top of our ResourceBundle and keeps things as simple as possible and also flexible. http://docs.sylius.org/en/latest/bundles/SyliusGridBundle/index.html

I'd love to use OroGridBundle but it is not decoupled from the whole oro platform and moving whole Sylius to oro platform, yeah, not an option at this point. 

Let me know what do you think about GridBundle, we tested it in a big project and worked nicely. Fortunately, we have made plenty of adjustments and improvement during this project and I think that in its current form it is already usable for many use-cases. We see some missing features (mass actions are started, but not completed) but I strongly believe that this approach with YML configuration and nice decoupling is nicer than SonataAdmin php Admin classes etc.

**Comment by sagikazarmark** [comment]
> I'd love to use OroGridBundle but it is not decoupled from the whole oro platform

You mean there are other dependencies, or not split from the main package (or both)?

As @nidup mentioned above, components are getting extracted from the one, huge packages, like AkeneoBatchBundle.

/cc @DimaSoroka

As I can see, there is a possibility to split it from the main repo:

https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/DataGridBundle/composer.json

Haven't played with it yet, but definitely will. Actually the amount of duplicated stuff which concerns me: I am working on a sylius shop installation which should probably work together with an OROCRM installation.

**Comment by DimaSoroka** [comment]
At Oro we do not have any plans to decouple GridBundle yet, but we are open to help with this and maintain decoupled version if someone would like to invest.
