### ISSUE TITLE
Removing the promotion rule when deleting a product affects promotion trigger rules

### ISSUE THREAD

**Issue by laurentdabbb** [Sylius/Sylius#15201]
**Sylius version affected**: 1.12.8+

**Description**  
I think the fix #14932 merged in 1.12.8 cause a bigger issue.
A listener has been added to remove promotions rules of type "contains_product" when the targeted product is removed. But deleting a promotion rule changes the application's promotion rules...

Consider a promotion "PLOP" with an action "free delivery" (100% discount on shipping fees) and a rule "cart contains product with code ABC". This promotion is active.
Deleting ABC productresults in the deletion of the promotion rule on "PLOP" promotion.
From now, "PLOP" promotion  is still active and no longer has rules. This promotion is applicable for all orders. All orders on the store will be shipped for free...

**Possible Solution**  
Do not remove promotion rule.

Thanks.

**Comment by jakubtobiasz** [comment]
Hello @laurentdabbb 👋🏼,
we'll check this in the upcoming sprint (Weeks 36-37).
