### ISSUE TITLE
Error on saving promotion

### ISSUE THREAD

**Issue by kayue** [Sylius/Sylius#1523]
As far as I know something is wrong with `Sylius\Bundle\PromotionBundle\Form\Type\ActionType`

```
Method "configuration" for object "Symfony\Component\Form\FormView" does not exist in SyliusWebBundle:Backend/Promotion:_form.html.twig at line 12
```

**Comment by michalmarcinkowski** [comment]
@umpirsky I suppose it's fixed?

**Comment by umpirsky** [comment]
@michalmarcinkowski I guess, never really checked. You can close and we will reopen if it happens again. ;)

**Comment by michalmarcinkowski** [comment]
:+1:
