### ISSUE TITLE
use PUT update product translations error

### ISSUE THREAD

**Issue by langziyang** [Sylius/Sylius#15238]
**Sylius version affected**: 1.12.10
![image](https://github.com/Sylius/Sylius/assets/2345387/97cef398-aae2-40b7-92b6-3f974dfbd0cb)

**Comment by NoResponseMate** [comment]
Hi @langziyang 👋 

This issue should've been resolved via #15535 in 1.13 as the way we're saving (and validating for that matter) translations was revamped a bit.

Cheers 🍻
