### ISSUE TITLE
Payment from expired session stored as completed

### ISSUE THREAD

**Issue by pierre-dedi** [Sylius/Sylius#15230]
**Sylius version affected**: 1.11.7

**Description**  
Some payments are recorded in the database with the status "completed" while the log returned by the bank contains the following error message: "The consumer is not redirected on payment web pages and session is expired". Thus, when a payment considered valid by the bank is made afterwards, it is not recorded by Sylius.
I have 2 questions :
- Is it possible to add an "Expired" or "Failed" status for the failed payment in this case?
- Is the fact that the second payment is not recorded linked to the fact that the first one is considered "completed" ?

**Steps to reproduce**  
I haven't been able to reproduce the payment session expiration yet.

**Comment by jakubtobiasz** [comment]
Hello @pierre-dedi 👋🏼!

Sylius by default comes with PayPal plugin only, so I can't understand your case fully. Do you develop your own plugin or use a 3rd one? If you're using a community-driven plugin the best choice is to open an issue in the plugin's repository.

**Comment by NoResponseMate** [comment]
Hi @pierre-dedi 👋 

Since there's not enough information to reproduce the issue as well as it being a bit stale I'm closing it. Please open another one if it's still a problem and you can provide more info.

Cheers 🍻
