### ISSUE TITLE
buttons in cart not named according to german button law

### ISSUE THREAD

**Issue by DanielRuf** [Sylius/Sylius#15249]
I think we have to adapt some things for German laws like Buttongesetz / Button-Lösung. "Bestellung aufgeben" is not allowed anymore afaik.
 
Are there legal text plugins for Sylius which do this and more (for WordPress there are "German Market" and "germanized" which cover such topics, that's what I know so far)?
 
https://www.ratgeberrecht.eu/wettbewerbsrecht-aktuell/richtige-beschriftung-des-bestell-buttons-2.html
https://de.wikipedia.org/wiki/Button-L%C3%B6sung

Currently german onlineshops can be fined for the used button texts.

**Comment by DanielRuf** [comment]
There are probably more lines than just these, which have to be adapted to be compliant:

https://github.com/Sylius/Sylius/blob/1.13/src/Sylius/Bundle/UiBundle/Resources/translations/messages.de.yml#L643-L644

**Comment by jakubtobiasz** [comment]
Hello @DanielRuf 👋🏼,
As we aren't from Germany, nor we have teammates from Germany, we can't help too much in that matter.

If you have some spare time, feel free to contribute to the translations by using crowdin (https://crowdin.com/project/sylius). You might also consider looking for other guys from Germany on our Slack (https://sylius.com/slack, we have `#german` channel) and try to create a plugin you mention together.

P.S. If you decide to contribute via crowdin just let me know, I'll accept it :). Such changes can be contributed against `1.12` as it's our currently supported version.

**Comment by shochdoerfer** [comment]
@jakubtobiasz I'll take over ;)

**Comment by shochdoerfer** [comment]
@jakubtobiasz Fixed (if I have not messed anything up on Crowdin).
