### ISSUE TITLE
TaxonomiesBundle

### ISSUE THREAD

**Issue by rseliberty** [Sylius/Sylius#1528]
Hi,
I am working with Taxonomies.
I have a problem when I affect taxons on a product on my product editing page.
I used "$builder->add('taxons', 'sylius_taxon_selection')", the list of taxons is loaded correctly with my different levels of taxons (first level, second level, ...)
When I save my product edition, relations are correctly saved in database (all levels).

But when I edit again my product, the list of taxons (any levels) is already correctly loaded in selector but only first level of taxons are selected.
For example, "Foo" is not selected in product edition but relation database "product_taxon" contains relation between my product and "Foo" taxon.

Example taxons
- T-Shirts
** Foo
- Stickers

Thanks for your time!

**Comment by pjedrzejewski** [comment]
I think this has been fixed. Please let me know if still an issue.
