### ISSUE TITLE
Impossible to login if the encoder_name is different from the hasher defined on UserInterface class

### ISSUE THREAD

**Issue by delyriand** [Sylius/Sylius#15286]
**Sylius version affected**: 1.13 and 1.12

**Description**  

The `Sylius\Component\User\Model\User` class is not compatible with Symfony 6 to retrieve the password encoder via `PasswordHasherFactory`.

Since version 6.0, only the `PasswordHasherAwareInterface` is used: [PasswordHasherFactory diff](https://github.com/symfony/password-hasher/compare/5.4..6.0#diff-f554f2e8aedb0dc6c25450b0ff91ef2c835033c31ccd8fc9024e24ae7a026000R42-R43)

So, the factory doesn't retrieve the `encoder_name` from entity and uses the encoder defined on the class. If the values are different, the customer cannot log in.

**Steps to reproduce**  

1. Install the Sylius fixtures with the customer `shop@example.com`
2. Change the password hasher in `config/packages/security.yaml`, example:

```diff
-        Sylius\Component\User\Model\UserInterface: argon2i
+        Sylius\Component\User\Model\UserInterface: sha256
``` 

3. Try to log in
4. We get the error "Invalid credentials."

**Possible Solution**  

Implement the `PasswordHasherAwareInterface` interface in the `Sylius\ComponentUser\Model\User` class and define the method:

```php
public function getPasswordHasherName(): ?string
{
    return $this->getEncoderName();
}
```

**Comment by diimpp** [comment]
Related https://github.com/Sylius/Sylius/issues/13418
