### ISSUE TITLE
Paypal checkout

### ISSUE THREAD

**Issue by jslegers** [Sylius/Sylius#1530]
I'm a PHP/MySQL+HTML+JS+CSS programmer looking for a lightweight alternative to Pestashop and Drupal Commerce that allows me -- as a programmer -- to more easily add my own customisations.

I tried the Sylius demo, but I got an error when I tried the Paypal checkout. For me, a working checkout with a PayPal test account is an essential feature that needs to work correctly before I consider any solution for my own projects.

Could you look into that? If you can get your Paypal checkout to work correctly out of the box for both real and test accounts, I'll definitely consider Sylius for my next project.

**Comment by kayue** [comment]
This can be close.
