### ISSUE TITLE
mapped-superclass for ZoneMember

### ISSUE THREAD

**Issue by jbbrunsveld** [Sylius/Sylius#1536]
The ZoneMember.orm.xml is not a mapped-superclass. That makes it hard to extend. Of course, in the config.yml I can change the prefered model. But than I'll get two new tables in my schema-dump:  "sylius_zone_member" and "my_zone_member" tables. The first one will never be used. I suppose to transform all entity mappers to mapped-superclass ones. Some mappers already used that strategy. I don't actually know why there are some exceptions to this.

**Comment by lfukumori** [comment]
I have same problem. Any solution for this?

**Comment by pjedrzejewski** [comment]
Should be fixed by https://github.com/Sylius/Sylius/pull/3696.

**Comment by michalmarcinkowski** [comment]
Fixed already.
