### ISSUE TITLE
[Promotion-bundle] End of support with twig/twig 2.x

### ISSUE THREAD

**Issue by brociani** [Sylius/Sylius#15431]
Hi Everyone !

i'm using sylius/promotion-bundle as standalone bundle and noticed as i wanted to upgrade my application
that promotion-bundle conflicts with twig/twig ^3.0.

And Twig version 2.x end of maintenance is scheduled for December 2023. 

Do you plan on supporting version 3.x anytime soon ?

**Comment by tdumalin** [comment]
Hi @brociani , have you find any work around ? I'm also blocked with sylius packages, many of them have conflict with twig 3
