### ISSUE TITLE
In admin form, CheckboxTypes are not saved on Enter key press.

### ISSUE THREAD

**Issue by FabienCharlier** [Sylius/Sylius#15458]
**Sylius version affected**: at least 1.12.6 to 1.12.9

**Description**  
When editing a form on Sylius admin interface, if the user changes the state of a checkbox, then presses Enter, the checkbox is immediately flipped back to its original state.
Clicking Save changes works as intended

Edit : It seems to only take place if flipping the checkbox was your last action in the form. For example, if you flip two checkboxes in a row, only the last one will return back to its original state.

**Steps to reproduce**  
Reproductible on Sylius demo : 
- go to customers menu : https://demo.sylius.com/admin/customers/
- click Edit on any customer
- toggle the "Verified" CheckBox
- press Enter (do not click Save changes, the button works as intended)

Result :
As soon as the key is pressed, the checkbox goes back to its original state

**Possible Solution**

**Comment by diimpp** [comment]
I've reproduced the issue, checking/unchecking last/in focus input is expected behavior, but why it submits form at the same time -- I don't know.

Same for product page as well. Are there any helper JS functions for form submit with enter key press??

**Comment by athish-v** [comment]
Hello @diimpp,
Can I work on this Issue

**Comment by diimpp** [comment]
> Hello @diimpp, Can I work on this Issue

Hello @vpathish, all contributions are welcome! :smiley: 

Contribution guide should answer some of your questions https://docs.sylius.com/en/latest/book/contributing/index.html and you're welcome to join our slack https://sylius.com/slack

**Comment by jakubtobiasz** [comment]
Hi,
this is a default behavior of semantic-ui and we're not planning to touch it. If you want, you might solve your issue on your site. Once we fully migrate to Bootstrap in Sylius 2, the problem won't exist anymore, as Bootstrap doesn't have this behavior.
