### ISSUE TITLE
All travis builds are failed because of time limit.

### ISSUE THREAD

**Issue by makasim** [Sylius/Sylius#1545]
All of my PRs are red because of travis failed. I am sure it is not because of tests are broken. It is not red but gray, and at the end of the log it says:

```
I'm sorry but your test run exceeded 50.0 minutes.
```

I guess it affects not only my PRs. @Sylius/core-team What should we do?

**Comment by stloyd** [comment]
@pjedrzejewski @aRn0D After some hacks & splits most of build no more fail, so I guess we can close this.
