### ISSUE TITLE
inserting products and its belonging attributes via API

### ISSUE THREAD

**Issue by AhmadStudies** [Sylius/Sylius#15456]
hello guys,
Is there any way I can insert a list of producs each one with its specific attributes into Sylius via Api?
or
Is there any way I can insert a list of producs all of them with the same attributes into Sylius via Api?

I will be gratefull to any help 
thanks a lot

**Comment by diimpp** [comment]
Hello @AhmadStudies 

Product attributes management is not implemented yet in new APIP based api.

- https://github.com/Sylius/Sylius/issues/11250
- https://github.com/Sylius/Sylius/issues/13414

You can join our https://sylius.com/slack for support questions.

Closing as duplicate https://github.com/Sylius/Sylius/issues/13414
