### ISSUE TITLE
Checkout prevented when no payment gateway is enabled

### ISSUE THREAD

**Issue by elliot** [Sylius/Sylius#1546]
If a user goes to checkout and there are no payment gateways enabled, it is impossible to get past the payment method step and there is no form of user feedback.

Some platforms prevent checkout entirely when no gateways are configured, and others only display a notice on the payment method page so as to still collect the user details. Is there a preference on how to deal with this situation?

On a similar note, it would be ideal to have a form of "on-boarding" checklist for these kinds of configuration issues - but that's something for down the track.

**Comment by pjedrzejewski** [comment]
For both shipping and payment method missing - we should display a nice info and a link to admin section (to configure more payment/shipping methods) if user is logged in as admin.

**Comment by michalmarcinkowski** [comment]
Fixed.
