### ISSUE TITLE
Fresh install with Docker setup, upload new image in admin 404 not found

### ISSUE THREAD

**Issue by nelsoncv** [Sylius/Sylius#15462]
**Sylius version affected**: 1.12.11

**Description**  
I am getting 404 not found every time i upload a new image, the image is existed in public/media/cache/sylius_small, 
<img width="701" alt="image" src="https://github.com/Sylius/Sylius/assets/16750948/063fe397-0ca8-4dd2-815b-785f09bc2465">

</br>

<img width="471" alt="image" src="https://github.com/Sylius/Sylius/assets/16750948/404a8fd7-f4f7-4825-a3f9-b024af0c37f8">

As shown above folder 20 is newly created and has rwxrwx-- permission, while other folder i have changed using chmod 777.
The only way for image to display at admin and store is to chmod after every upload, may i know is there any extra steps to do for file permission or a solution to it?

P/S: I have followed the guide [here](https://symfony.com/doc/current/setup/file_permissions.html) but i think it has already been added into php/docker-enterpoint.sh

**Steps to reproduce**  

Fresh install following documentation

`docker run --rm -v $(pwd):/app composer create-project sylius/sylius-standard acme --ignore-platform-reqs --no-scripts --no-install`

`cd acme`

`docker compose up -d --build`

`open http://localhost/`

**Possible Solution**  
N/A

**Comment by nelsoncv** [comment]
hi any update from anyone?

**Comment by TakesTheBiscuit** [comment]
Did you recurse the CHMOD to public? Is it similar or related to the bug i just raised here: https://github.com/Sylius/Sylius/issues/15625 ?

**Comment by Wojdylak** [comment]
I close this issue. It duplicated by #15625
