### ISSUE TITLE
\Sylius\Bundle\ResourceBundle\Controller\ControllerTrait::addFlash throw error on Sylius 1.12

### ISSUE THREAD

**Issue by Geolim4** [Sylius/Sylius#15475]
**Sylius version affected**: 1.12.x

**Description**  
This trait is trowing error since the "session" service has been removed from Symfony.
It should be migrated to RequestStack->getSession().

**Steps to reproduce** 
Create a controller that use `\Sylius\Bundle\ResourceBundle\Controller\ControllerTrait` and call short method  `addFlash`

**Possible Solution**  
Posted above

**Comment by Geolim4** [comment]
Nevermind, fixed in https://github.com/Sylius/SyliusResourceBundle/issues/535 any ETA on this fix ? :)

**Comment by zpi12lmm** [comment]
Note: If you're creating your custom controller, I recommend sending the flash message through the [Notifier](https://symfony.com/doc/current/notifier.html) component, which centralizes absolutely all of your notifications in one place.

**Comment by Geolim4** [comment]
> Note: If you're creating your custom controller, I recommend sending the flash message through the [Notifier](https://symfony.com/doc/current/notifier.html) component, which centralizes absolutely all of your notifications in one place.

Thanks but I don't want to add a (another) huge dependency to a big Symfony component just to send... A flashbag message with 5 words on this. 🙄 
This is far from being optimized in my POV.

**Comment by zpi12lmm** [comment]
If you only send flash messages in your project, you could send it directly through the Request object, for example like this: `$request->getSession()->getFlashBag()->add()`

**Comment by Geolim4** [comment]
> If you only send flash messages in your project, you could send it directly through the Request object, for example like this: `$request->getSession()->getFlashBag()->add()`

That exactly what I've suggested in my first message 😆 

>  It should be migrated to RequestStack->getSession().

**Comment by zpi12lmm** [comment]
You can use it right now, avoiding calling the short `Sylius\Bundle\ResourceBundle\Controller\ControllerTrait::addFlash` method.

**Comment by Geolim4** [comment]
> You can use it right now, avoiding calling the short `Sylius\Bundle\ResourceBundle\Controller\ControllerTrait::addFlash` method.

Which require me a major refactoring of my application since I rely on a broken internal method of Sylius.
I have to rewrite the trait since it is no longer compatible with the Symfony ControllerTrait::addFlash which is now completely typed, leading to a compilation error.

**Comment by zpi12lmm** [comment]
In that case, all you have to do is wait for a patch with this fix if you have time to wait, because it might not be soon.

**Comment by zpi12lmm** [comment]
In that case, all you have to do is wait for a patch with this fix if you have time to wait, because it might not be soon.

**Comment by Geolim4** [comment]
> In that case, all you have to do is wait for a patch with this fix if you have time to wait, because it might not be soon.

That issue has been reported a year ago, fixed 2 month ago and still not merged yet :(
https://github.com/Sylius/SyliusResourceBundle/issues/535

**Comment by zpi12lmm** [comment]
I tried to tell you about this, that it is easier to do it yourself than to wait for a patch of fixes.

**Comment by loic425** [comment]
@Geolim4 If I understand, you just need a 1.10 patch release?

**Comment by Geolim4** [comment]
Not at all since the bug appears on 1.12 release 😅

**Comment by loic425** [comment]
> Not at all since the bug appears on 1.12 release 😅

No I mean a sylius/resource 1.10 patch release.

**Comment by Geolim4** [comment]
Ahh yes indeed, that bug appears only since Symfony 5.4/6+ so it's a bit
annoying yes because I'm forced to override this trait while the Symfony
one is already patched. So yes a release would be much appreciated sir 😊

**Comment by loic425** [comment]
> Ahh yes indeed, that bug appears only since Symfony 5.4/6+ so it's a bit annoying yes because I'm forced to override this trait while the Symfony one is already patched. So yes a release would be much appreciated sir 😊

I cannot release myself, but I've reported that on the Sylius core team.

**Comment by NoResponseMate** [comment]
Hi @Geolim4,

I know I'm pretty late to the party, but I can inform you the fix has just been released in [1.10.3 of ResourceBundle](https://github.com/Sylius/SyliusResourceBundle/releases/tag/v1.10.3) which also includes support for Symfony 6.4

The issue should be resolved so I'm closing this, if it persists ping me, and I'll reopen and we'll work on a fix.

Cheers 🍻

**Comment by Geolim4** [comment]
> Hi @Geolim4,
> 
> I know I'm pretty late to the party, but I can inform you the fix has just been released in [1.10.3 of ResourceBundle](https://github.com/Sylius/SyliusResourceBundle/releases/tag/v1.10.3) which also includes support for Symfony 6.4
> 
> The issue should be resolved so I'm closing this, if it persists ping me, and I'll reopen and we'll work on a fix.
> 
> Cheers 🍻

Wonderful @NoResponseMate thank you !
