### ISSUE TITLE
[Shop] Cart page breaks styling on invalid coupon submit

### ISSUE THREAD

**Issue by diimpp** [Sylius/Sylius#15505]
**Sylius version affected**: 1.12

**Description**  
Before
![image](https://github.com/Sylius/Sylius/assets/870747/bba9e796-00b9-4d39-8414-1ff457d97d91)
After
![image](https://github.com/Sylius/Sylius/assets/870747/925f7172-2348-4d8f-a281-9d1b86d92353)

**Steps to reproduce**  
1. Add item to cart
2. Enter incorrect coupon code
3. Press "Checkout"

**Possible Solution**  
Fix css styling as for other cart cases in https://github.com/Sylius/Sylius/pull/15217

**Comment by NoResponseMate** [comment]
Should be fixed via #15507

Cheers :beers:
