### ISSUE TITLE
[Potential Issue] update cart lead to order id appears in url

### ISSUE THREAD

**Issue by cbastienbaron** [Sylius/Sylius#15541]
**Sylius version affected**: 1.x.y

**Description**  

order id appears on url : https://demo.sylius.com/en_US/cart/?id=108642
no need to expose potential number of orders 

**Steps to reproduce**  
go to https://demo.sylius.com/ add an item in cart, next https://demo.sylius.com/en_US/cart/  click on "update cart" btn
REQUEST :  `POST https://demo.sylius.com/en_US/cart/`
RESPONSE Headers:  `Location: /en_US/cart/?id=108642` (part ?id=108642)

**Possible Solution**

**Comment by cbastienbaron** [comment]
thanks @jakubtobiasz

**Comment by jakubtobiasz** [comment]
Thanks are due to @NoResponseMate for opening a PR 😅. And to you, for opening an issue!🎉

**Comment by cbastienbaron** [comment]
my bad :) thanks to the 3 of us ^^ :handshake:
