### ISSUE TITLE
[ADMIN][UI] Administrator form display issue

### ISSUE THREAD

**Issue by Prometee** [Sylius/Sylius#15606]
**Sylius version affected**: 1.12

**Description**  
I spend to much time on filling the administrator form and here is the display of the CSRF token error on this form :
![image](https://github.com/Sylius/Sylius/assets/861820/8e2874c3-4600-49a9-a3e9-686194dd97b4)
(I empty the fields to take the screenshot)

**Comment by NoResponseMate** [comment]
Should be resolved via #15614

Cheers 🍻

**Comment by Prometee** [comment]
Wow really good/quick job @NoResponseMate thank you very much 👌👏😉
