### ISSUE TITLE
[RFC] Drop custom uploading & use something "better"

### ISSUE THREAD

**Issue by stloyd** [Sylius/Sylius#1561]
Hello guys & gals!

After holidays, I started to look at my not finished PRs, and I found that #1284, is good start, but not good way to fix the problem of uploading code.

I done some research, and found that [`VichUploaderBundle`](https://github.com/dustin10/VichUploaderBundle) covers totally our needs, and does even more for us as it supports:
- both ORM & ODM,
- add some useful helpers for templating stuff,
- supports few filesystem libs: Symfony Filesystem, Gaufrette, Flysystem
- and is well tested + documented!

Any feedback is welcome as usually =)

**Comment by amdad** [comment]
Hi guys! 
Just to know. Is there any movement on this matter?

**Comment by cirykpopeye** [comment]
I think this feature might be a good addition to the Sylius platform. Right now it's a pain to add multiple images, especially if you want to sort them afterward.
