### ISSUE TITLE
Bug with docker, chmod required for public directory

### ISSUE THREAD

**Issue by TakesTheBiscuit** [Sylius/Sylius#15625]
**Sylius version affected**: main/master/latest

**Description**  
Run the docker commands, images will be missing

**Steps to reproduce**  
Run the docker commands
Site will show up
No images are on the site

**Possible Solution**  
For now:
`docker compose -f docker-compose.prod.yml exec php chmod -R 777 public`

But you shouldn't have to do this - the public dir should be set to 777 by whatever creates it? perhaps we should remove it in the docker and CREATE it with the right permissions as part of the docker first run?

For example:
https://github.com/Sylius/Sylius/blob/1.13/.docker/dev/Dockerfile#L4
```
RUN rm -rf ./public/media
RUN mkdir ./public/media
RUN chmod -R 777 public
```

See OLD issue:
https://github.com/Sylius/Sylius/issues/5782

**Comment by brucepc** [comment]
Seems to be the same as  #15447

**Comment by Wojdylak** [comment]
Hi @TakesTheBiscuit 

ee just have merged a new docker concept [here](https://github.com/Sylius/Sylius-Standard/pull/935). Could you check if there is steel a problem with the images?

**Comment by Wojdylak** [comment]
Hi @TakesTheBiscuit

I am closing this issue. If you encounter any other problems with docker, feel free to create another issue.
