### ISSUE TITLE
product child taxon not selected

### ISSUE THREAD

**Issue by mitjade** [Sylius/Sylius#1564]
If I have taxons set as nested for more than one level deep and I save a product with that taxon selected it get's saved, but when I edit the product again form does not select that taxon.

If taxon is a child of root taxon, then it works OK. But if I try the online demo this is not a problem. I created a totally clean sylius project and on my local machine this does not work correct.

I managed to to figure out that the taxonomy getTaxons() only gets immediate children, but I guess it should get all siblings.

**Comment by s1yamuza** [comment]
Thank you very much to both. It works great.
