### ISSUE TITLE
Add a new rule to promotion

### ISSUE THREAD

**Issue by faizanktk** [Sylius/Sylius#15659]
There are seven rules in drop down while creating a promotion. I want to add a new rule the drop down "Customer not in Group".
How can i add this custom rule in dropdown?

Thanks

@igormukhingmailcom

**Comment by oallain** [comment]
Hello,

Can you take a look at https://docs.sylius.com/en/1.12/cookbook/promotions/custom-cart-promotion-rule.html ?

**Comment by TheMilek** [comment]
Hi! If you have some troubles with customization please visit our [slack](https://sylius.com/slack) or check the docs above 💃🏽
