### ISSUE TITLE
[RFC] More powerful product builder

### ISSUE THREAD

**Issue by kayue** [Sylius/Sylius#1566]
Hi all

In my project I need to implement an import products from Excel function, and I will need to improve the existing [ProductBuilder](https://github.com/Sylius/Sylius/blob/1f76020d41f7f5dd1e96a59eb88fe6756d58dbd3/src/Sylius/Component/Product/Builder/ProductBuilder.php). And I think I might be able to contribute this code to Sylius if you guys will accept it in core.

### Goal

The goal is to be able to create new product / variant on the with a table like this:

![22aaec6c-e159-11e3-8d80-ca7642989990](https://cloud.githubusercontent.com/assets/193112/3088808/5a8570e6-e576-11e3-8c97-f9fdad47d82c.png)
(Ignore the extra fields please..)

### Proposed API

```php
$productBuilder = $this->get('sylius.product_builder')->create();
$productBuilder->setName('White Quam Stripe Jeans');
$productBuilder->setDescription('White Quam Stripe Jeans');
$productBuilder->setPrice(1200);

// Create taxon on the fly: addTaxon($taxonomyName, $taxonName)
$productBuilder->addTaxon('Brand', 'United Stock Dry Goods');
$productBuilder->addTaxon('Category', 'Clothing');
$productBuilder->addTaxon('Category', 'Jeans');
$productBuilder->addTaxon('Season', 'Spring/Summer');
$productBuilder->addTaxon('Year', '2014');

// Create variant on the fly: addVariant($optionName, $optionValue)
$productBuilder->addVariant('Size', 'S');
$productBuilder->addVariant('Size', 'M');
$productBuilder->addVariant('Size', 'L');

$productBuilder->save();
```

Any feedback is welcome.

**Comment by michalmarcinkowski** [comment]
ProductBuilder is already removed.
