### ISSUE TITLE
[RFC] Make the helper methods of TaxationProcessor protected?

### ISSUE THREAD

**Issue by patkar** [Sylius/Sylius#1567]
I've recently extended the `TaxationProcessor`, but because the helper methods are private I had to copy the whole code, which is not nice. Concretely I wanted to overwrite the `processTaxes(...)` method, to use it like

```php
protected function processTaxes(OrderInterface $order, $zone)
{
    $taxes = parent::processTaxes($order, $zone);

    // do my stuff
}
```

So my proposed change is to make them protected. I know with this you are proposing this methods to a "public API" and further changes are BC breaking for someone, but hey, it's pre-alpha :joy:

**Comment by pjedrzejewski** [comment]
Closing this as we won't make them protected but decouple more and also #605 needs to be fixed properly. :)
