### ISSUE TITLE
[RFC] Tax included in price should be set on product not on tax rate?

### ISSUE THREAD

**Issue by stloyd** [Sylius/Sylius#1568]
Hey there!

I just played a bit with Taxation, and noticed that `TaxRate` model contain `included_in_price` setting, and I think it's wrong, cause that setting should be product specific value (or other stuff that uses `TaxableInterface`).

I.e. when importing stuff from, let's say 3rd party shop, we get prices for products with tax already, we don't want to re-apply taxes on imported products again, yet we know to which tax category this product should go, so why we should "count" tax on our own and _remove it_ from price to get netto prices?

What do you think? Or I'm missing something, some hidden gem =)

**Comment by nicolasricci** [comment]
I agree with @winzou and @stloyd on this.
If you import your product prices with VAT and then create a VAT rate at 20% for EU with the the `included_in_price` option it works well. But then if you want to deliver your products outside EU, no VAT has to be applied on the product price and it is not the case at the moment as the `Sylius\Component\Pricing\Calculator\StandardCalculator` calculate method is returning `getPrice()` directly.

The `TaxRate` should be implemented in the pricing calculator to return the right price according to the tax zone.

Do you agree with this @pjedrzejewski ?

**Comment by ibasaw** [comment]
+1 got same problem. i need to dellver outside EU and tax rate is 0 % so the price of the prroducts are still with VAT 20 %, this is no good. Price and total must be without the TAX price.

How do you do for now guys for this issue ?
