### ISSUE TITLE
SyliusCoreBundle 1.13 depends on non-existing package

### ISSUE THREAD

**Issue by martijnc** [Sylius/Sylius#15742]
**Sylius version affected**: 1.13 (dev)

**Description**  
A recent [merge](https://github.com/Sylius/Sylius/pull/15729) into the 1.13 branch of SyliusCoreBundle introduced a dependency on "sylius/state-machine-abstraction". But this package does not exist (yet), so installing SyliusCoreBundle@1.13 is no longer possible.

**Steps to reproduce**  
Require sylius/core-bundle@1.13

**Possible Solution**  
Publish `sylius/state-machine-abstraction` or remove the dependency.

**Comment by stefandoorn** [comment]
I'm testing an early upgrade to `1.13` and I get this - which seems a bit related:

```
root@2d4eaada35f2:/var/www/html/symfony# bin/console

In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
                                                                                                                                                                            
  The service "Sylius\Bundle\CoreBundle\EventListener\Workflow\Order\CreatePaymentListener" has a dependency on a non-existent service "sylius_abstraction.state_machine".  
```

Code is available, but I think a certain bundle is not loaded, and it's not mentioned in the [1.13 UPGRADE](https://github.com/Sylius/Sylius/blob/1.13/UPGRADE-1.13.md) guide.

**Comment by stefandoorn** [comment]
Adding `Sylius\Abstraction\StateMachine\SyliusStateMachineAbstractionBundle::class => ['all' => true],` to `bundles.php` helps for me.

**Comment by martijnc** [comment]
We don't depend on `sylius/sylius` but on the individual bundles (we don't use the shop and admin bundles), so our install doesn't have the code for the new abstraction and composer cannot install it because there isn't a package for it yet.

The "standalone" 1.13 branch of `sylius/core-bundle` is not installable currently.

**Comment by jakubtobiasz** [comment]
Hi,
@GSadee will create a repository and split the packages soon.

**Comment by esserj** [comment]
Thanks a mil. @GSadee and @jakubtobiasz !

**Comment by GSadee** [comment]
Hi guys!
I'm very sorry it took so long. I have created the appropriate repository and published the package, so everything should be ok now 🎉 . 
Of course, if you have any further problems, please reopen the issue or open a new one.

**Comment by esserj** [comment]
🎉 Thank a lot @GSadee !!
