### ISSUE TITLE
RouteNotFoundException for newly created Page

### ISSUE THREAD

**Issue by sudent** [Sylius/Sylius#1577]
Steps to reproduce:

1. Install sylius
2. Run ``sylius:install`` with fixtures loaded
3. Test homepage - OK
4. Login to backend and go to Pages (Content -> Pages) (while here, #1540 will appear, apply solution)
5. Add new page
6. Fill in details with ``/cms/pages/test``, ``Test``, ``Test`` and submit
7. Go to frontend
8. The following error message will appear:

> An exception has been thrown during the rendering of a template ("None of the chained routers were able to generate route: Route 'Route aware content Symfony\Cmf\Bundle\ContentBundle\Doctrine\Phpcr\StaticContent' not found") in SyliusWebBundle:Frontend:layout.html.twig at line 70

Something to do with dynamic routing for CMF's StaticContent I guess

**Comment by psyray** [comment]
Hi @pjedrzejewski

This one too ;)

**Comment by jeffsacco** [comment]
I am experiencing this issue too.  Not sure what to do at this point.  Might just create a new bundle and create my content in a static pages . . .

Anyone still experiencing this?

**Comment by psyray** [comment]
see #2696
