### ISSUE TITLE
`AsPromotionAction` attribute does not work because the `sylius.promotion_action` tag requires `form_type` to be set.

### ISSUE THREAD

**Issue by martijnc** [Sylius/Sylius#15795]
**Sylius version affected**: 1.13

**Description**  
The `AsPromotionAction` attribute can be used to tag a class as a `sylius.promotion_action`. This is handled by `Sylius\Bundle\PromotionBundle\DependencyInjection\SyliusPromotionExtension::registerAutoconfiguration @ 52`. But this attribute does not support the `form_type` option that is required by the `sylius.promotion_action` tag, see `Sylius\Bundle\PromotionBundle\DependencyInjection\Compiler\RegisterPromotionActionsPass @ 34`.

**Steps to reproduce**  
Add the `AsPromotionAction` attribute to a promotion action implementation (a service), this will result in a `
InvalidArgumentException` because the `form_type` isn't set, but it cannot be set because the attribute doesn't support it.

**Possible Solution**  
Add `form_type` to the `AsPromotionAction` attribute or remove the `form_type` requirement from the `sylius.promotion_action` tag.

**Comment by esserj** [comment]
I would actually consider making the `form_type` optional, maybe adding another attribute and tag for this part makes more sense then a 2-in-1 approach? so that you can tag your form type where it's defined and update the form registry.

**Comment by Wojdylak** [comment]
Hi @martijnc 

Thank you for bringing this issue to our attention. We recognize it as a bug and have created a task to address it in the future. However, if you'd like, feel free to submit a PR - we always appreciate community contributions!

**Comment by Wojdylak** [comment]
I am closing this issue as it has been resolved by PR #15842.
