### ISSUE TITLE
[RFC] Can we simplify cleanup the OrderInterface.

### ISSUE THREAD

**Issue by makasim** [Sylius/Sylius#1585]
I am looking at https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Order/Model/OrderInterface.php from the order component and I think it could be simplified in some ways.  Here some topics to discuss:
- Doc block says it has to return Doctrine's Collection? It means we coupled to doctrine which does not seem right.
- Too many xxxItems methods: `getItems, setItems, countItems, addItem, removeItem, hasItem, clearItems`. Maybe we can remove some of them or even move to `OrderItemsAwareInterface`.
- does the model has to do such operation `calculateItemsTotal`?
- does the model has to do such operation  `calculateTotal`?

**Background**: I want to create "one nice api for all possible payments". For that I need a simple order interface  (which could be extended). Sure, I am looking at sylius order component but for my goals it is too complicated. I need a currency field and total amount. I dont mind to have items as additions though.

**Comment by michalmarcinkowski** [comment]
Deprecated.
