### ISSUE TITLE
Toast message does not close after multiple clicks on the close "X" icon

### ISSUE THREAD

**Issue by Kriz83** [Sylius/Sylius#15863]
**Sylius version affected**: 1.11.* , 1.12.*

**Description**  
All flash messages on the Shop and Admin pages don't disappear when the close button is clicked twice.
It looks like the second click is canceling the closing process.
![image](https://github.com/Sylius/Sylius/assets/20474707/b89a84c2-1709-48ec-8982-902369bf0417)

**Steps to reproduce**  
Perform an action that results in a flash message displaying an ERROR/SUCCESS, such as submitting a registration form.

Rapidly click an even number of times on the “X” icon to close the toast message.

**Comment by Wojdylak** [comment]
Hi @Kriz83 

Sorry, we have to close this issue because it's just how Semantic-UI works. We'll use Bootstrap for the admin panel starting with version 2.0
