### ISSUE TITLE
Installation tutorial fails

### ISSUE THREAD

**Issue by dmeziere** [Sylius/Sylius#15860]
**Sylius version affected**: 1.12.5

**Description**  
The installation tutorial doesn't work. As I expected as soon as I saw JavaScript in the process, it hangs at this point :

```
MyFirstShop$ yarnpkg install
(...)
error https://registry.yarnpkg.com/jquery.dirtyforms/-/jquery.dirtyforms-2.0.0.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Invalid tar header: unknown format."

```
Trying to visualize the package on the yarnpkg website crashed the website (as expected, it is also JS).

**Steps to reproduce**  
https://docs.sylius.com/en/1.12/getting-started-with-sylius/installation.html

**Comment by crydotsnake** [comment]
Hello @dmeziere 

I could net reproduce your issue. How do you have `yarn` installed on your system? And what is your installed `yarn` version?

**Comment by dmeziere** [comment]
Oh, it's the one provided with Ubuntu, let me see ...

```
$ yarnpkg --version
1.22.10
```

**Comment by crydotsnake** [comment]
So you installed it via apt?

I would try to install yarn like its described in the docs:

https://yarnpkg.com/getting-started/install

Seems they dont recommend anymore to install yarn via NodeJS

**Comment by dmeziere** [comment]
Nothing was specified in the tutorial, so i did like i use to, it's true. I understand Sylius has been made by or with JavaScript enthousiasts, maybe i am not the only one to be a PHP enthousiast and JavaScript hater, that uses it by force. This link may have it's place in the tutorial, i think. I will try it after work and tell you.

**Comment by dmeziere** [comment]
This looks like a whole project to install. If i understant well, yarn requires corepack, that requires npm, that doesn't like my version of node.

**Comment by dmeziere** [comment]
This did the trick on Ubuntu 22.04 LTS. 

Node :
```
sudo apt install curl 
sudo curl -o /usr/local/bin/n https://raw.githubusercontent.com/visionmedia/n/master/bin/n
sudo chmod +x /usr/local/bin/n
sudo n stable
```
Then Corepack :
```
sudo npm install -g corepack
```
Then yarn :
```
corepack enable
yarn init -2
yarn set version stable
yarn install

```
Then the tutorial works. Thank you @crydotsnake !

**Comment by crydotsnake** [comment]
Glad its working now!
No Problem :)
