### ISSUE TITLE
Translations w/ nested translations don't display correctly

### ISSUE THREAD

**Issue by sabliao** [Sylius/Sylius#1589]
Translations that rely on an implicit '.0' after it (e.g. 'sylius.form.payment.state' or 'sylius.backend.statistics') don't display correctly. These have other translations nested beneath that last node but also have their own translations. I'm assuming the translation defined by a "0: " beneath that last node is supposed to be for the base translation, but it doesn't display correctly unless I add '.0' to the translation placeholder (e.g. 'sylius.form.payment.state.0').

**Comment by stloyd** [comment]
@pjedrzejewski @aRn0D This was fixed some time ago.
