### ISSUE TITLE
BUG: [AdminBundle] missing <br> Tag in Product media tab twig template

### ISSUE THREAD

**Issue by crydotsnake** [Sylius/Sylius#15908]
**Sylius version affected**: 1.12 (But i believe older Sylius versions as well).

**Description**  

In the new product form when you click to "Media" there is the button for adding multiple media files:

![SCR-20240227-opyn](https://github.com/Sylius/Sylius/assets/39345336/da8d0eb0-3ea3-4a8b-96d1-f15c248018fa)

But the "Add" button has no spacing, therefore it looks a bit squeezed to the UI top header.

If you take a look at the Taxons management and scroll down to the Media section:

![SCR-20240227-oqoj](https://github.com/Sylius/Sylius/assets/39345336/2104025a-c349-4cdf-9c8e-72e5a39c89ac)

there is the same twig logic implemented as in the Product => Media section:

```twig
{% form_theme form '@SyliusUi/Form/imagesTheme.html.twig' %}

<div class="ui segment">
    <h3 class="ui dividing header">{{ 'sylius.ui.media'|trans }}</h3>
    <br>
    {{ form_row(form.images, {'label': false}) }}
</div>
```

The only thing missing there is the `<br>` tag, which provides the space between the "Add" button and the header.

**Steps to reproduce**

1. Navigate to `Products` => `Create` => (Product Type doesent matter) => `Media`
2. See the Button for adding media files is squeezed to the top header.

**Possible Solution**  

Add the missing `<br>` tag the Product media tab twig template.

### After Change

![SCR-20240227-otdi](https://github.com/Sylius/Sylius/assets/39345336/03b0645a-ab98-45eb-9964-2e7672c7baa0)

**Comment by crydotsnake** [comment]
Or as an alternative this could also be solved with a new CSS class that has a `padding-top`. Also this class could be applied to the media section in the taxon management then. To make the spacing consisent.

**Comment by Rafikooo** [comment]
Hello @crydotsnake ,
I'm not a big fan of the `<br>` tag personally, but since we use those in some places in Sylius, I believe we can proceed with this solution 🕺

**Comment by Rafikooo** [comment]
I'm closing the ticket as the PR https://github.com/Sylius/Sylius/pull/15909 has been merged 🚀

**Comment by crydotsnake** [comment]
Hello @Rafikooo 

> I'm not a big fan of the <br> tag personally

Me neither. Maybe we can revisit the topic in the future and give it a clean overhaul 🙂
