### ISSUE TITLE
BUG: Missing spacing between upload image upload button in image_widget

### ISSUE THREAD

**Issue by crydotsnake** [Sylius/Sylius#15938]
**Sylius version affected**: ? - 1.12

**Description**  

Its kinda the same behavior i already described in #15908 

But this is now related to the `sylius_image_widget`, `sylius_product_image_widget`, and the `sylius_taxon_image_widget`.

When you upload a image the image is squeezed to the choose file button which doesent look very nice.

**Steps to reproduce**  
1. Create a Product / Or Taxon
2. Go to Media and upload a image.

**Possible Solution**  

For #15908 i _solved_ it with a `<br>` tag. But i'm not really a fan of that. Here i would solve this via a new CSS class that has a `margin-bottom`. To make it look consistent, i would add the same space as between the Type field, and the choose file button:

<img width="421" alt="before_and_after" src="https://github.com/Sylius/Sylius/assets/39345336/d53a8f3b-635f-4b57-a68c-e36455d6841f">

**Comment by Rafikooo** [comment]
The problem was fixed using https://github.com/Sylius/Sylius/pull/15939
Thanks @crydotsnake for your continued contributions 🎉
