### ISSUE TITLE
CmfRouting + JMSI8nRouting: how to make them work together?

### ISSUE THREAD

**Issue by winzou** [Sylius/Sylius#1594]
Hey,

I have an issue when using the new CMFRouting and my existing JMSI8nRouting integration. I've asked a question on stackoverflow with no answer so far, maybe one of you have the answer!

Here is the question: http://stackoverflow.com/questions/24094880/cmfrouting-jmsi8nrouting-how-to-make-them-work-together

Thanks!

**Comment by michalmarcinkowski** [comment]
Looks like answered (http://stackoverflow.com/a/32397684). Please reopen if still relevant.
