### ISSUE TITLE
How can I return back to the previous form page from the PRE_SUBMIT event with form values?

### ISSUE THREAD

**Issue by Manasmd** [Sylius/Sylius#15944]
I have a custom Entity for a simple basic CRUD operation. The form is rendering fine and works well. However, I am doing some custom validation in the PRE_SUBMIT and would like to redirect back to the form page with user's previously inserted values. 

I have tried it through the URL params and also sessions but both doesn't work.

```

  $builder->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $event) {
    $data = $event->getData();
    if($data['name'] == "unavailable"){
   
     // I would like to redirect back to the form page and pre-fill the name field.
     // I have tried to set it through URL params and as well as in the session (both doesn't) work.
     
     
    }
  }
  
```

**Comment by TheMilek** [comment]
Hi @Manasmd!

Closing this as it is not an issue with Sylius. 😅 
If you need help with customizations or anything else, please join our Slack community: [Sylius Slack](https://sylius.com/slack).

If you still feel that this is an issue with Sylius, feel free to open another issue with more information. 🚀 

Cheers! 🍻
