### ISSUE TITLE
Item /cms/blocks/... not found in workspace default

### ISSUE THREAD

**Issue by winzou** [Sylius/Sylius#1596]
Hi,

I've facing an issue when adding a new CMF block in my project. I can access the creation form, but when I submit it I get this error:

    Item /cms/blocks/my/block not found in workspace default

Hence I cannot add any block.
On Sylius master I can't even display the creation form:

    Fatal error: Call to undefined method Jackalope\Query\QueryResult::count() in
    /app/vendor/pagerfanta/pagerfanta/src/Pagerfanta/Adapter/DoctrineODMPhpcrAdapter.php 
    on line 51

(maybe an issue in older pagerfanta though)

Have anyone managed to do this?

**Comment by pjedrzejewski** [comment]
I think this is fixed now too.
