### ISSUE TITLE
Strange behaviour while extending/overriding PayumBundle

### ISSUE THREAD

**Issue by antonioperic** [Sylius/Sylius#1597]
So this is my flow. I am building custom payment gateway based on Sylius and Payum integration.
I created my payum_override.yml file which contains these lines

sylius_payment:
    gateways:
        paylink_justpay: Paylink JustPay

I included that file after regular Sylius configuration file, so basically I am expecting that everything will be kept and this gateway will be added. But this is what is happening: http://take.ms/JNFt4 
I don't get gateway name, I am getting key as integer

If I change Sylius standard configuration file like this:
sylius_payment:
    classes:
        payment:
            model: Sylius\Component\Core\Model\Payment
            controller: Sylius\Bundle\CoreBundle\Controller\PaymentController
    gateways:
        dummy: Test
        stripe: Stripe
        be2bill: Be2Bill
        paylink_justpay: Paylink JustPay

Everything works well. This is not some major issue but I want to keep Sylius untouched and add some things.

Thanks for helping

**Comment by michalmarcinkowski** [comment]
Please reopen if still relevant.
