### ISSUE TITLE
[Order] Text going out of the frame in the Notes section

### ISSUE THREAD

**Issue by marekrzytki** [Sylius/Sylius#16031]
**Sylius version affected**: 1.12.13

**Description**  
Notes content does not wrap text
![2024-03-21_13-00](https://github.com/Sylius/Sylius/assets/61479357/c1482aba-83e3-4441-84c6-b5910f413e4d)

**Steps to reproduce**  

1. Add any product to the cart and go through checkout
2. On the summary page put a long string value in the Extra Notes field. Value can’t have and space characters.
3. After placing an order go to the admin panel, Order section and show details of the just placed order.

**Possible Solution**  
Text wrap in twig template or notes field length validation.

**Comment by Wojdylak** [comment]
Hi @marekrzytki 

Thank you for bringing this issue to our attention. We acknowledge it as a bug. If you'd like, feel free to submit a PR - aw always appreciate community contributions.

**Comment by Wojdylak** [comment]
I am closing this issue as it has been resolved by PR #16076
