### ISSUE TITLE
[UI] Different product box sizes on the product listing

### ISSUE THREAD

**Issue by marekrzytki** [Sylius/Sylius#16041]
**Sylius version affected**: 1.12.13

**Description**  
The size of the product box on the listing varies depending on the number of products. Can be reproduced on demo: https://demo.sylius.com/en_US/taxons/caps/simple
2 or more products
![2024-03-22_11-59](https://github.com/Sylius/Sylius/assets/61479357/74de7672-1311-4a2c-9fe5-8d93bd9179c2)

Single product
![2024-03-22_11-59_1](https://github.com/Sylius/Sylius/assets/61479357/83eaff3f-865b-46dd-a1d1-42bff30263fb)

**Steps to reproduce**  

1. Find taxon with 2 or more products -> product boxes are same size
2. Disable products, leaving one available -> product box is bigger

**Possible Solution**

**Comment by Rafikooo** [comment]
Hello @marekrzytki , your reported issue is valid. We will fix it later, in Sylius 2.0 release. However, if you'd like to try your hand at proposing the contribution, it would be great. 🕺
