### ISSUE TITLE
Payum Paypal Payment fails with: The totals of the cart item amounts do not match order amounts

### ISSUE THREAD

**Issue by joschi127** [Sylius/Sylius#1612]
I'm not sure if this is related to https://github.com/Sylius/Sylius/issues/1603

Paypal Payment fails for me with the message: The totals of the cart item amounts do not match order amounts

As far as I can see this is because the tax is missing in the total amount.

I can fix this when I change the followings lines in CapturePaymentUsingExpressCheckoutAction:

Original code:

            $details['PAYMENTREQUEST_0_AMT'] = round($order->getTotal() / 100, 2);
            $details['PAYMENTREQUEST_0_ITEMAMT'] = round($order->getTotal() / 100, 2)

Changed version of the code which fixes the issue for me:

            $details['PAYMENTREQUEST_0_AMT'] = round(($order->getTotal() + $order->getTaxTotal()) / 100, 2);
            $details['PAYMENTREQUEST_0_ITEMAMT'] = round(($order->getTotal() + $order->getTaxTotal()) / 100, 2);

But I think this is not the right way to fix it.

Can you give me some hints what would be the right way for a fix so I could submit a PR or have a look at it yourself?

Thanks a lot!

**Comment by michalmarcinkowski** [comment]
Should be fixed already. Please reopen if still relevant.
