### ISSUE TITLE
Api Cart Context calls wrong endpoint method

### ISSUE THREAD

**Issue by ehibes** [Sylius/Sylius#16181]
**Sylius version affected**: ^1.11

**Description**  

Since Sylius 1.11, add to cart endpoint method has changed, from POST to PATCH. 
Meanwhile, the behat api cart context always calls POST method.

**Steps to reproduce**  

[https://github.com/Sylius/Sylius/blob/1.12/src/Sylius/Behat/Context/Api/Shop/CartContext.php#L828](https://github.com/Sylius/Sylius/blob/1.12/src/Sylius/Behat/Context/Api/Shop/CartContext.php#L828)

**Possible Solution**  

Change context call method with PATCH

Is it normal or do I miss something ?

**Comment by Rafikooo** [comment]
Hello @ehibes, from what I can see, we use the `POST` method to perform adding to the cart, don't we?

<img width="583" alt="image" src="https://github.com/Sylius/Sylius/assets/40125720/c5b43d16-b1eb-4fcd-b64d-7c856d334ec0">

[Sylius 1.13 API Documentation](https://master.demo.sylius.com/api/v2)

**Comment by ehibes** [comment]
🙈 You're are right. I just realize Setono/GiftCard plugin rewrite Order api resource config and this is why I have a patch instead of a post. I should open an issue on this plugin. Thanks @Rafikooo
