### ISSUE TITLE
Invalid constraint configuration in AddProductReview.xml

### ISSUE THREAD

**Issue by ramon-nijman** [Sylius/Sylius#16193]
**Sylius version affected**: 1.12.x

**Description**  
Within Symfony 6.4.7, the `src/Sylius/Bundle/ApiBundle/Resources/config/validation/AddProductReview.xml` contains an invalid range constraint config:

The "Symfony\Component\Validator\Constraints\Range" constraint can not use "minMessage" and "maxMessage" when the "min" and "max" options are both set. Use "notInRangeMessage" instead.

https://github.com/Sylius/Sylius/blob/ee77b2b054f866dbc434c21d58bbc135bbebf401/src/Sylius/Bundle/ApiBundle/Resources/config/validation/AddProductReview.xml#L16-L31

Source:
https://github.com/symfony/symfony/pull/54750

**Steps to reproduce**  

**Possible Solution**  
Let's remove the minMessage and maxMessage in `src/Sylius/Bundle/ApiBundle/Resources/config/validation/AddProductReview.xml`.

**Comment by TakesTheBiscuit** [comment]
Up! this has broken a build here and unable to resolve

**Comment by diimpp** [comment]
Resolved at 1.13 with https://github.com/Sylius/Sylius/commit/52adeda39869b5bb6d768576a03933f9a8ddf3bb, but actual for 1.12

**Comment by loevgaard** [comment]
You can resolve it by just installing `symfony/validator` 6.4.6 if you need a quick fix

**Comment by olia-bn** [comment]
FYI, it is long weekend in Poland: 1st and 3rd are holidays and most people take the whole week off. I would not expect any developer action until next week.

**Comment by GSadee** [comment]
I'm closing as it has been fixed by #16196

**Comment by maximehuran** [comment]
When will you release the v1.12.16 with this fix ? 🤩
