### ISSUE TITLE
Catalog promotion is still applying after end date, price is not restored to original

### ISSUE THREAD

**Issue by jdeveloper** [Sylius/Sylius#16206]
**Sylius version affected**: 1.12.12

**Description**  
 Trying Catalog Promotions in Sylius 1.12.12. I've created a catalog promotion based on taxon with a start and end date. The discount is applied to the products of the taxon. However, I'm having an issue when the end date is reached. After the end date has passed, the discount continues to appear on the products. But if I go to the Admin Panel, edit the promotion, and simply click the save button, then the prices are adjusted back to their original values. However, I think I shouldn't have to manually intervene to stop applying the discount, right?

Is this a bug? Or is there a command I need to execute to resolve this issue?

Thanks in advance!! Any help appreciated :pray:

**Steps to reproduce**  
- Create active catalog promotion base on taxon with fixed discount
- Load page with products verifying price discount
- After end of promotion reload paga again, the discount should not be appear but still applies

**Comment by Chrysweel** [comment]
I have tried to reproduce the error and use some catalog promotions from https://demo.sylius.com but I cannot get a catalog promotion to work. 

How can I test a catalog promotion from demo.sylius?

**Comment by ebarbeito** [comment]
Hello. Having the same behaviour here. Thanks in advance for any clarification

**Comment by GSadee** [comment]
Hi guys!

We've just checked that issue and we cannot reproduce it, catalog promotions seem to work properly. 

Of course, as you've noticed, there is a problem with our demo, where the promotions are not being processed at the moment, we will try to fix this as soon as possible. In the meantime, you can check the catalog promotions feature on the Sylius community edition demo: https://master.demo.sylius.com/admin/

And about your potential problem, maybe you have the wrong transport configured or you haven't run the messenger consumer process according to the docs: https://docs.sylius.com/en/1.13/book/products/catalog_promotions.html#catalog-promotion-asynchronicity

**Comment by jdeveloper** [comment]
Hi @GSadee 

I tried it with syn:// config in messenger integrated in a project. Maybe this is the problem. We have tried the standalone version with 1.3 version and with this setup and configuring doctrine as the transport it works well. I will try to configure the transport with doctrine to figure out if it works.

Thanks a lot

**Comment by jdeveloper** [comment]
Hi again

I have tried to use doctrine as the transport in messenger, now all works well. Thanks for all.
