### ISSUE TITLE
As an Admin, I want to resend the confirmation email of an Order that is `fulfilled`

### ISSUE THREAD

**Issue by CoderMaggie** [Sylius/Sylius#16225]
In 1.13 we've introduced a [parameter](https://github.com/Sylius/Sylius/blob/1.13/src/Sylius/Bundle/OrderBundle/Resources/config/app/config.yml#L5) that holds the order states in which we are showing the "Resend order confirmation email" button.
![image](https://github.com/Sylius/Sylius/assets/13198869/85675514-25d9-448e-9985-bfb46fc9950c)
![image](https://github.com/Sylius/Sylius/assets/13198869/0e5a4137-9379-4beb-9ec2-e77323a8477d)

Right now the parameter is set to `new` state only.

I believe a customer might need the order confirmation email (again) even after the order is fulfilled.

While adding this _feature_ please consider adding a scenario for it [here](https://github.com/Sylius/Sylius/blob/1.13/features/order/managing_orders/resending_order_confirmation_email.feature).

**Comment by GSadee** [comment]
Added in #16886
