### ISSUE TITLE
[BUG] Bug when edit taxonomies's permalink.

### ISSUE THREAD

**Issue by liverbool** [Sylius/Sylius#1624]
Before edit permalink: 
> category/books

After i try to edit to **category/booksx** and then save. Permalink have changed to:
> category/category-booksx

The result should be:
> category/booksx

![screenshot jun 19 00 04 09](https://cloud.githubusercontent.com/assets/206804/3317235/cb808ccc-f70a-11e3-94da-ce2ab15f2d5e.png)

**Comment by familie-redlich** [comment]
I run into the same issue :(

it looks to me if an listener, listen on the flush method and overwrite the permalink every time.
but I cannot locate the exact line of code

workflow: 
create taxonomy -> setLocale and setName
create taxon -> setLocale and setName
add taxon to taxonomy // permalink is null
persist taxonomy // permalink is null
flush // permalink is taxon->parent->permalink . '/' . taxon->slug

change taxon permalink to 'abc' // permalink is abc
persist // permalink is abc
flush // permalink is taxon->parent->permalink . '/' . taxon->slug 

hope this help

**Comment by familie-redlich** [comment]
i found the "problem" i TaxonTranslation.orm.xml -> Sylius\Bundle\TranslationBundle\GedmoHandler\TranslationSlugHandler

the method 'transliterate' build the permalink... I would say its "Works as Designed" :)
i subclass (override) TaxonTranslation and the orm mapping to use my own TranslationSlugHandler ... problem solved.

**Comment by nmarmon** [comment]
"Closed", please

**Comment by michalmarcinkowski** [comment]
Should be fixed now.
