### ISSUE TITLE
The documentation should also have `npm` commands

### ISSUE THREAD

**Issue by nbro** [Sylius/Sylius#16265]
**Sylius docs version**:1.13.1

**Description**

The Sylius documentation uses `yarn` to run the JS/Node related commands, but `yarn` is not installed by default when you install `node`. So, I think the default commands should use `npm` instead of `yarn` or, at least, both options should be in the documentation.

**Comment by GSadee** [comment]
Hi @nbro!

Thank you for opening an issue with such a suggestion.

We are currently using `yarn` in the documentation, and we also have a mention that it is needed. So I would suggest leaving it as it is and adding an additional note with information about `npm` that this can be used instead. Feel free to contribute to our documentation, and as this is not a significant issue, I am closing it 🖖🏻
