### ISSUE TITLE
[Api] `Serializer\ImageSerializer` missing `$data['path']` check 

### ISSUE THREAD

**Issue by diimpp** [Sylius/Sylius#16294]
**Sylius version affected**: 1.13

**Description**  
Potential hard to debug place, which can be solved with extra assert.

`ImageNormalizer` operates on assumption, that serialized image will have `path` array element, at the same time `ImageInterface` is commonly used by end-users and serialization of their custom images is up to them, hence presence of `path` is not guaranteed. 

https://github.com/Sylius/Sylius/blob/89bd5e320982faba5a82e9f6fa59a2aaf79ff530/src/Sylius/Bundle/ApiBundle/Serializer/ImageNormalizer.php#L74-L78

**Steps to reproduce**
1. Implement new `CoolImage implements ImageInterface`.
2. Expose `CoolImage` as serialized resource in APIP based api endpoint, but don't serialize `path`.
3. Receive error about "Path is undefined" instead of empty api output. 

**Possible Solution**  

```patch
+++     Assert::notEmpty($data['path], 'Image must have "path" serialized.');
        try {
            return $this->cacheManager->getBrowserPath(parse_url($data['path'], \PHP_URL_PATH), $filter);
        } catch (NonExistingFilterException|\OutOfBoundsException) {
            throw new InvalidArgumentException(sprintf('Filter "%s" is not configured.', $filter));
        }
```
or

```patch
+++     if (empty($data['path])) {
+++         return '';
+++     }
        try {
            return $this->cacheManager->getBrowserPath(parse_url($data['path'], \PHP_URL_PATH), $filter);
        } catch (NonExistingFilterException|\OutOfBoundsException) {
            throw new InvalidArgumentException(sprintf('Filter "%s" is not configured.', $filter));
        }
```

**Comment by Wojdylak** [comment]
Good point, @diimpp.
I think a better solution is to add this check to the `supportsNormalization` function.

**Comment by Wojdylak** [comment]
Supporting the `ImageInterface` class, we cannot be certain that there is a 'path' key in the array. Therefore I have decided to change this class to `Image`. There is an ORM mapping to the `Sylius\Component\Core\Model\Image` class,  which assumes that the `path` field is not nullable.
`Image.orm.xml`
```
<mapped-superclass name="Sylius\Component\Core\Model\Image">
    <id name="id" column="id" type="integer">
        <generator strategy="AUTO" />
    </id>

    <field name="type" column="type" type="string" nullable="true" />

    <field name="path" />
</mapped-superclass>
```
