### ISSUE TITLE
Product grid broken on mobile

### ISSUE THREAD

**Issue by t-n-y** [Sylius/Sylius#16379]
**Sylius version affected**: 1.12.16

**Description**  
after the product grid fix [https://github.com/Sylius/Sylius/pull/16190](https://github.com/Sylius/Sylius/pull/16190), the mobile view is broken
<img width="430" alt="Capture d’écran 2024-06-12 à 11 23 33" src="https://github.com/Sylius/Sylius/assets/3873351/b760c9de-dd1d-4449-9831-0120a1a03390">

**Steps to reproduce**  
Go to a taxon page and resize page to mobile view

**Comment by mpysiak** [comment]
Issue was fixed in https://github.com/Sylius/Sylius/pull/16380
