### ISSUE TITLE
[Admin] Orders index fails to load more than 274 pages (2750 orders)

### ISSUE THREAD

**Issue by mmarousez-dc** [Sylius/Sylius#16425]
**Sylius version affected**: 1.11

**Description**  
When i have more than 274 pages of orders in my admin list, all pages content shom the first 10 orders.

**Steps to reproduce**  
Have more than 2750 orders on your sylius, no filter.

**Comment by CoderMaggie** [comment]
Hi @mmarousez-dc!
I've investigated your issue by asking our community on [Slack](https://sylius.com/slack) if they have this issue on their projects and none have reported problems. The reported issue might result from how you have customized Sylius or your environment's capabilities.

You can see the thread mentioned above 👉🏻 [here](https://sylius-community.slack.com/archives/C3EGDG9LY/p1719222595138539).

Feel free to reopen if you think this is a Sylius issue.

**Comment by mmarousez-dc** [comment]
thanks for reply
