### ISSUE TITLE
How to customize admin dashboard chart ?

### ISSUE THREAD

**Issue by bntdlb** [Sylius/Sylius#16447]
Hi everyone,

First of all thanks for the work, Sylius is improving every update and it's very pleasant !

I'm using Sylius 1.12.15 and I would like to know how to properly customize the admin dashboard chart ?

I would like to change the 2 weeks view into a 1 week view.

Thanks !

**Comment by CoderMaggie** [comment]
I found a PR where we've added the 2 weeks/month/year views, maybe it will inspire you 😅 https://github.com/Sylius/Sylius/pull/11558/files

**Comment by bntdlb** [comment]
Hi @CoderMaggie !

Thanks a lot for the insight.
I've seen those files but I didn't want to override everything and do my own implementation in case of futures evolutions from the team.
I thought that maybe there was a way to customize with yaml files or anything but it seems not.

The best way should probably to do my own javascript function that change the event on the weekly button to send my own request to the api.

Thanks again, you helped me figure out how to do what I need, i'll try to do so.
