### ISSUE TITLE
Class 'Sylius\Component\Promotion\Model\PromotionInterface' does not exist

### ISSUE THREAD

**Issue by faizanktk** [Sylius/Sylius#16512]
#message: "Class 'Sylius\Component\Promotion\Model\PromotionInterface' does not exist"
  #code: 0
  #file: "[/home/bimmertest/frontDev/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/MappingException.php](phpstorm://open?url=file:///home/bimmertest/frontDev/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/MappingException.php&line=94)"
  #line: 94
  trace: {
    /home/bimmertest/frontDev/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/MappingException.php:94 {}
    /home/bimmertest/frontDev/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/RuntimeReflectionService.php:36 {}
    /home/bimmertest/frontDev/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php:252 {}
    /home/bimmertest/frontDev/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php:285 {}
    /home/bimmertest/frontDev/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:82 {}
    /home/bimmertest/frontDev/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php:185 {}
    /home/bimmertest/frontDev/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:288 {}
    /home/bimmertest/frontDev/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:655 {}
    /home/bimmertest/frontDev/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:494 {}
    /home/bimmertest/frontDev/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:808 {}
    /home/bimmertest/frontDev/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:343 {}
    /home/bimmertest/frontDev/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:371 {}
    /home/bimmertest/frontDev/vendor/sylius/sylius/src/Sylius/Bundle/ResourceBundle/Doctrine/ORM/EntityRepository.php:33 {}
    /home/bimmertest/frontDev/src/AppBundle/Service/CreateCart.php:559 {

**Comment by faizanktk** [comment]
PromotionInterface.php exist

**Comment by mpysiak** [comment]
Hi @faizanktk,

It appears that the issue originates from the file /home/bimmertest/frontDev/src/AppBundle/Service/CreateCart.php at line 559 in your end application, rather than being an issue within Sylius itself. Additionally, there is a lack of context and no information provided about the version of Sylius you are using.

For a more detailed and quicker response, I recommend seeking assistance on the [Sylius Slack ](https://sylius.com/slack) channel, where the community can provide some help.

Thank you!
