### ISSUE TITLE
[SyliusMoneyBundle] Configurable twig extension's output pattern

### ISSUE THREAD

**Issue by danakil** [Sylius/Sylius#1656]
I may be wrong but it seems that SyliusMoneyBundle can't adapt its output pattern to the local or usage in a specific country. In France (and others countries like Germany), it is very uncommon to write "€ 250". Instead we should write "250 €".

Other than modifying the pattern in the twig extension, I can't find a way to do it.

**Comment by pamil** [comment]
Money helper uses the current locale now. Moreover, you can force that filter to use the specific locale.
