### ISSUE TITLE
Missing callback wrapper in LocaleChoiceType causes error in Unit Test

### ISSUE THREAD

**Issue by wimulkeman** [Sylius/Sylius#16572]
**Sylius version affected**: 1.12.*, 1.13.*, 1.14.*

**Description**  
The choices in the LocaleChoiceType for the Locales form select options are not loaded through a callback setup. This causes the class to hold to load the values directly while building the form, and holding the same values during the whole runtime.

This differs from the setup used in other similar ChoiseType form elements like the CurrencyChoiceType and the ChannelChoiceType.

The error came to light when writing tests after extending the Channel form.

LocaleChoiceType:
https://github.com/Sylius/Sylius/blob/1.12/src/Sylius/Bundle/LocaleBundle/Form/Type/LocaleChoiceType.php#L43

CurrencyChoiceType:
https://github.com/Sylius/Sylius/blob/1.12/src/Sylius/Bundle/CurrencyBundle/Form/Type/CurrencyChoiceType.php#L40

ChannelChoiceType:
https://github.com/Sylius/Sylius/blob/1.12/src/Sylius/Bundle/ChannelBundle/Form/Type/ChannelChoiceType.php#L40

In normal usage this doesn't make a difference, but it could manifest itself as a bug in testing. When testing the creating of a Channel form in a PHPUnit test, followed by a submit in the same test, this produces an Entity mismapping which triggers the SQL error that a duplicate Locale can't be created.

**Steps to reproduce**  
When test code first builds the form using the PHPUnit WebTestCase from Symfony to first create the client + crawler, following by a submit within the Unit Test.

When populating the database with locales before retrieving the client, locales are created in the table. The locales are saved as choices in the LocaleChoiceType. When the form is filled using the crawler in the PHPUnit test, and the form is submit, Doctrine refreshes its fetched Entity property.  Afterwards it fetches the Locales again from the database and stores them for the submit request. This causes the entity objects to be stored as a new object in Doctrine compared with the initial request (for retrieving the channel form). But the LocaleChoiceForm still has the initial entity objects under its choises option. When submitting the form, the old objects don't match the new objects, causing Doctrine trying to submit the same Locale again for it determines it must be a new entity.

**Possible Solution**  
Adding the callback as a wrapper for the choices values mitigates the described behavior as can also be seen in the Currency and Channel ChoiceType.

**Comment by Wojdylak** [comment]
It has been resolved by PR #16574, so I am closing this issue.
