### ISSUE TITLE
Possible issue with unique username uniqueness when registering via oauth.

### ISSUE THREAD

**Issue by smarques** [Sylius/Sylius#1660]
Hi, I was looking at:
https://github.com/Sylius/Sylius/blob/daa769d13301b53bfd3dad56b42dcdcfa2553332/src/Sylius/Bundle/CoreBundle/OAuth/UserProvider.php#L98

And I think it might be possible (although not so probable) that different users might have the same identifier on two different social networks.

Maybe it might make sense to check for uniqueness before setting the username...
Something along the lines of
$user->setUsername($this->getUniqueUsername($userInformation->getNickname()));

which is what happens here: https://github.com/hwi/HWIOAuthBundle/blob/4c9e19a203a571b9bd459843512afd1d2cd6375a/Form/FOSUBRegistrationFormHandler.php#L158

Or am I mistaken?

Thx!!
s

**Comment by michalmarcinkowski** [comment]
Should be resolved by https://github.com/Sylius/Sylius/blob/daa769d13301b53bfd3dad56b42dcdcfa2553332/src/Sylius/Bundle/CoreBundle/OAuth/UserProvider.php#L63. Please reopen if still relevant.

**Comment by Zales0123** [comment]
I believe it's not relevant anymore #4YearsAgo. Please reopen if you think differently :)
