### ISSUE TITLE
Why prices are integers?

### ISSUE THREAD

**Issue by bigfoot90** [Sylius/Sylius#1662]
Why prices (in moldels) are integers?

**Comment by pierrerigal** [comment]
@bigfoot90 did you try something with this issue ? 

Problem here in France, public price inc VAT (20%) is 0.45€, price can be store as 37 or 38 cents out of tax.

37 is rounded to 0.44€ inc taxes
38 is rounded to 0.46€ inc taxes

Impossible to sell something at 0.45€.

**Comment by michalmarcinkowski** [comment]
@pierrerigal if you configure the tax rate to be 20% included in price and set 0.45€ as a price on a product variant then it will work fine.
