### ISSUE TITLE
Security Step event ordering

### ISSUE THREAD

**Issue by warrenlee** [Sylius/Sylius#1666]
Hi all, I believe that may be a small bug in the Security step where the `$this->saveUser($user)` should be placed in between the `REGISTRATION_SUCCESS` and `REGISTRATION_COMPLETED` events as like in the `FOS\UserBundle\Controller\RegistrationController\registerAction` L61-L70 
Or was it ordered this way intentionally?

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Checkout/Step/SecurityStep.php#L72-L75

**Comment by michalmarcinkowski** [comment]
Please reopen if still relevant
