### ISSUE TITLE
[RFC][ResourceBundle] Removing hard dependencies 

### ISSUE THREAD

**Issue by aRn0D** [Sylius/Sylius#1669]
Related issue #722, for now it is impossible to override the `Configuration`, `FlashHelper`, `DomainManager`, `ResourceResolver` and `RedirectHandler`.

## Overriding `Configuration`
We could use somethink a prototype partern. We could remove "dynamics" parameters (all except the `ParameterParser`) from `Configuration` constructor and declare it as a service. We should create a new interface named `ConfigurationInterface` which will be implemented by `Configuration`. This interface will ask you to set the bundle prefix, the resource name, the template engine and the template namespace to the configuration .`Configuration` will be injected into the `FactoryConfiguration` and the `createConfiguration` method will return a clone of `Confguration`.

## Overriding `FlashHelper`, `DomainManager`, `ResourceResolver` and `RedirectHandler`
These classes should implement a `ConfigurableInterface` which force you to add a `setConfiguration(Configuration $config)` method to these classes. We should declare them as a service and remove config parameter from their constructors. In the `ResourceController`, the `setContainer` could look like :

```php
    public function setContainer(ContainerInterface $container = null)
    {
        parent::setContainer($container);

        $this->resourceResolver = $container->get('resource.resolver.definition')->setConfiguration($this->config);
        $this->redirectHandler = $container->get('redirect.handler.definition')->setConfiguration($this->config);
        $this->flashHelper = $container->get('flash.helper.definition')->setConfiguration($this->config);
        $this->domainManager = $container->get('domain.manager.definition')->setConfiguration($this->config);
    }
```
What do you think about it ?

**Comment by pjedrzejewski** [comment]
Fixed, every controller is a proper service now.
