### ISSUE TITLE
docs: Instruction to install with docker are not up to date in french locale

### ISSUE THREAD

**Issue by Crovitche-1623** [Sylius/Sylius#16730]
It's not the `make init` as it is on the `en` website:

https://sylius.com/fr/telecharger/
<img width="546" alt="image" src="https://github.com/user-attachments/assets/4c00a264-1413-4342-9d3e-59f25aebc56b">

https://sylius.com/download/
<img width="549" alt="image" src="https://github.com/user-attachments/assets/dc977b4c-04c1-4752-af4c-2f8d30bc7670">

**Comment by GSadee** [comment]
Hi @Crovitche-1623, we've fixed that on the website. Thank you for mentioning it 😃
