### ISSUE TITLE
'DOMNodeInserted' mutation event is no longer supported with chrome > 127

### ISSUE THREAD

**Issue by bntdlb** [Sylius/Sylius#16745]
Hi everyone,

Chrome released the version 127 this 07/23/2024 and with it broke the support for DOMNodeInserted event.
See this blog post https://developer.chrome.com/blog/mutation-events-deprecation

**Sylius version affected**: I tried on 1.12.* and 1.13.4 but probably any version using the DOMNodeInserted event

**Description**  
I've noticed it when trying to create a new Cart Promotion, the accordions to switch from a channel to an other for prices configuration are no longer working.
If the form has error or if the form was already filled for example in older Promotion, you still can switch.

**Steps to reproduce**  
You can see it by creating a new Cart Promotion on the current Sylius Admin Demo, then selecting a new Action Type like "Order fixed discount" and see that you cannot switch channel.

Thanks again for all the work you put in Sylius !

**Comment by smashou** [comment]
I was on the same issue. It's concerning everything associated to "collections" and managed by :  `AdminBundle/Resources/private/js/app.js` and the following code 
```js
  $('body').on('DOMNodeInserted', '[data-form-collection="item"]', (event) => {
    if ($(event.target).find('.ui.accordion').length > 0) {
      $(event.target).find('.ui.accordion').accordion();
    }
    if ($(event.target).find('.ui.tabular.menu').length > 0) {
      $(event.target).find('.ui.tabular.menu .item').tab();
    }
  });
  ```

**Comment by smashou** [comment]
I'm proposing the following code to address this issue, but I want to mention that JavaScript is not my specialty, so there certainly is a more optimal way to achieve this. Please feel free to suggest improvements or adjust the code according to best practices.

```javascript
const collectionCallback = (mutationsList) => {
  for (const mutation of mutationsList) {
    if (mutation.type === 'childList') {
      mutation.addedNodes.forEach((node) => {
        if (node.nodeType === Node.ELEMENT_NODE && node.matches('[data-form-collection="item"]')) {
          const element = $(node);
          if (element.find('.ui.accordion').length > 0) {
            element.find('.ui.accordion').accordion();
          }
          if (element.find('.ui.tabular.menu').length > 0) {
            element.find('.ui.tabular.menu .item').tab();
          }
        }
      });
    }
  }
};

const observer = new MutationObserver(collectionCallback);
observer.observe(document.body, { childList: true, subtree: true });
```
The only purpose is to help for "hotfix" if needed.

**Comment by GSadee** [comment]
I'm closing the issues, as it has been fixed in https://github.com/Sylius/Sylius/pull/17262
