### ISSUE TITLE
Currency is not available

### ISSUE THREAD

**Issue by patie** [Sylius/Sylius#1686]
Hi,

i upgraded to dev-master and i have one problem with currencies 

`
An exception has been thrown during the rendering of a template ("Currency "EUR" is not available.") in FrontendBundle:Cart:summary.html.twig at line 42. 
`

on this line is twig extension filter `sylius_price`

i have into parameters.yml

`sylius.currency:                  EUR`

any undocumented changes please ?
thanks

**Comment by Goutte** [comment]
This is confounding for the new user ; when one sets up a new shop, one does not want all the products and users provided by the fixtures, yet wants the shop to run smoothly out-of-the-box.

I see a bunch of solutions :

- Make sure a currency is in the database, regardless of the choice of the user during `sylius:install`. This is not as easy as it looks, and it feels a bit invasive. We'd need to check the currency set up in parameters.yml against the database and add it if missing. 
- Make sure the shop works without any currency set up. This does not look easy either.
- Separate the *demo* fixtures from the *setup* fixtures ? Other data might find their place in the setup fixtures, like countries, a bigger list of currencies, or a credit link to sylius. 

Anyways, this issue has to be solved one way or another before the release, and I bet it's so trivial to many of you old dogs that you do not consider it critical -- yet it is ! Be gentle with the newbs ! ;)

**Comment by inspiran** [comment]
@pjedrzejewski Perhaps an idea would be to add a configurable "mode" to the data fixtures bundle which allows you to switch between loading all fixtures (eg. product, orders) and just only essential data such as tax zones, currency.

**Comment by pjedrzejewski** [comment]
@inspiran yeah, we need to do something like this. My goal is to bring back the web installer to life.

**Comment by Goutte** [comment]
In the end, that would look like, in `sylius:install` :

```
Do you want to load the setup fixtures (recommended) [Y/n] :
Do you want to load the demo fixtures [y/N] :
```

Right ?

---

A web installer really helped wordpress to connect with the non-dev community at large, so it's a good idea.

Maybe tag this issue to the release milestone ?

**Comment by quantizer** [comment]
How I can fix this problem, what I need to add to DB?

**Comment by stloyd** [comment]
@pjedrzejewski @aRn0D As of updates of installer I guess this was fixed too.
