### ISSUE TITLE
Promotion on cart when price (tax excluded) < promotion amount set total to 0

### ISSUE THREAD

**Issue by boreales** [Sylius/Sylius#16940]
**Sylius version affected**: 1.12.19

**Description**  
**Shop context**
All my products are saved with a price out of taxes. I apply the tax rate later with a special service. This part works well.

If I add a cart promotion with an amount of 100€ and the total of products is 120€ it works well and the promotion is applied on the final price taxes included.

If I add the same cart promotion of 100€ but the total of products is 90€, then the items total fall to 0, so the tax is not applied and my whole cart is empty. But if we count the tax rate (21%) we should have a promotion of 100€ on 108,9 so there is a rest to pay but Sylius makes it disappear.

**Steps to reproduce**  
Add some products tax free in back office
Add tax rate programmatically on items
Add a promo code with an amount > of the items total

**Possible Solution**

**Comment by GSadee** [comment]
Hi! This looks like a customisation problem. Therefore, I invite you to the [Slack community](https://sylius.com/slack) to solve the problem.
