### ISSUE TITLE
Index key missing in AddressLogEntry mapping

### ISSUE THREAD

**Issue by kbyjoel** [Sylius/Sylius#17046]
**Sylius version affected**: 1.14.0

**Description**  
When `sylius_address_log_entries` table grows, the `Gedmo LoggableListener` play a very long request
`SELECT MAX(s0_.version) AS sclr_0 FROM sylius_address_log_entries s0_ WHERE s0_.object_id = ? AND s0_.object_class = ?`
and can achieve to very slow mysql requests. On a production environment, i get very long requests : 
`Query_time: 10.867001  Lock_time: 0.000144 Rows_sent: 1  Rows_examined: 552084`

**Possible Solution**  
I overrided `AddressLogEntry `and added an index in `AddressLogEntry.orm.xml` mapping file, on `object_id` and `object_class` fields.
```
<indexes>
    <index columns="object_id,object_class" />  
</indexes>
```

**Comment by mamazu** [comment]
Yes completely agree. And there is already a PR for this: https://github.com/Sylius/Sylius/pull/16096

**Comment by kbyjoel** [comment]
Great ! Thanks @mamazu !

**Comment by NoResponseMate** [comment]
Hi @kbyjoel 👋 

The migration by @mamazu has been merged recently and the indexes will be present in Sylius from 1.14 up.

Cheers 🍻
