### ISSUE TITLE
Error cmf generating routes

### ISSUE THREAD

**Issue by maiksuaco** [Sylius/Sylius#1708]
After add a cmf block or page and visit main page sylius raise an error: it's

CRITICAL - Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("None of the chained routers were able to generate route: Route 'Route aware content Symfony\Cmf\Bundle\ContentBundle\Doctrine\Phpcr\StaticContent' not found") in "SyliusWebBundle:Frontend:layout.html.twig" at line 73." at /home/maiksuaco/workspace/Sylius/vendor/twig/twig/lib/Twig/Template.php line 148 

Loading fixtures does not raise an error because new route is added and is stored in DB...I was thinking if is possible, that can be fixed making a listener and when a new page or block from cmf is inserted then insert a new route too with the new element data, following decouple principle...

**Comment by psyray** [comment]
Hi @pjedrzejewski 

I think you could close this bug, it is resolved ;)

**Comment by jeffsacco** [comment]
I am getting this error when I create a new page

Wondering if this issue was cleared up?

**Comment by jeffsacco** [comment]
Is there some kind of work around we can do?

**Comment by psyray** [comment]
see #2696

**Comment by nmarmon** [comment]
Put the "closed" text if this is solved, then
