### ISSUE TITLE
Livequery fetched from github raw

### ISSUE THREAD

**Issue by fourlastor** [Sylius/Sylius#1709]
Hello, I noticed that Livequery is loaded from ```https://raw.github.com/brandonaaron/livequery/1.1.1/jquery.livequery.js```

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Resources/views/Backend/Promotion/create.html.twig
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Resources/views/Backend/Promotion/update.html.twig

This makes sometimes fail an automated build (it failed for me on Heroku several times) since GitHub will block requests from that machine.

Perhaps, since this library it's under refactoring, it would be wise to include the JS file into the project until you can switch to the new version distributed online via bower or similar.

**Comment by Rvanlaak** [comment]
I'm implementing the `PromotionsBundle` in my `sf2-standard` application, some documentation about the required assets would be great :+1: 

Installed it using Bower now:

    bower install -S brandonaaron/livequery

**Comment by pjedrzejewski** [comment]
Not used anymore.
