### ISSUE TITLE
No price shown for products with variant selection method "options matching"

### ISSUE THREAD

**Issue by saithis** [Sylius/Sylius#1710]
Products with variant selection method "options matching" have no price shown on the products page.

One possible solution would be to split the current cart form into 2 forms.
When changing a options dropdown the form gets submitted to the same URL, but with the selected options in it. 
The options are matched to the right variant, and the price is shown on the page.
Aditionally the variants options are preselected in the dropdowns and added as hidden inputs to the cart form. 
When no options data is found in the URL, then we would have to select one variant as the default one.

This way it would also be possible to copy the URL and send it to a friend without loosing the data which options were selected.

This is roughly the way amazon does it for their product variants.
The only downside would be that the page is reloaded on every change, which could be anoying for the customer.

The only other solution that I can think of right now would be to update the price with javascript (with or without ajax).

**Comment by michalmarcinkowski** [comment]
Fixed in #6161
