### ISSUE TITLE
Migration version Version20240315112656 down does not work as intended

### ISSUE THREAD

**Issue by ccimpoi** [Sylius/Sylius#17171]
The usage of json_decode is wrong.
json_decode with an invalid JSON string returns null and the check
@json_decode($data) === false
is never true so the migration is not skipped as intended.

For invalid JSON data strings the final PHP serialized value is always null after one runs the migration s down method.

https://github.com/Sylius/Sylius/blame/50428c902d0371be72131e5d52a554948e6aee3e/src/Sylius/Bundle/CoreBundle/Migrations/Version20240315112656.php#L84

**Comment by GSadee** [comment]
Hi @ccimpoi, would you like to contribute with the fix?

**Comment by GSadee** [comment]
Resolved by #17507
