### ISSUE TITLE
Create ability to add "related products"

### ISSUE THREAD

**Issue by sivolobov** [Sylius/Sylius#1731]
It is the one of the main feature that bundled in all existing e-commerce platforms. Why it is not realized yet in Sylius?

**Comment by mtthb** [comment]
Related PR: #2361

**Comment by axelvnk** [comment]
Okay, so I took stloyd feature branch and tried it out. My shop has 13k products, these all get loaded into the data-prototype attribute in the back-end, on the product edit page. Which makes the app hit the memory limit. So maybe the form needs a search by name or sku functionality.

**Comment by stloyd** [comment]
@axelvnk That code was not optimized yet, it would be adjusted to work same way we have adding products in orders at backend right now.

**Comment by axelvnk** [comment]
@stloyd Yes, I assumed it wasn't yet finished. I can't seem to find any code related to what you said. I'd like to see that code :) maybe I can optimize it like that in my project.

**Comment by michalmarcinkowski** [comment]
The feature is in progress (https://github.com/Sylius/Sylius/pull/3165) and will be merged in v0.17 ;)

**Comment by michalmarcinkowski** [comment]
Implemented already.
