### ISSUE TITLE
how to dev in Cloud IDE?

### ISSUE THREAD

**Issue by gowy222** [Sylius/Sylius#17384]
docker run --rm -v $(pwd):/app composer create-project sylius/sylius-standard acme --ignore-platform-reqs --no-scripts --no-install

cd acme

make init

```
open http://localhost/  this wont work in Cloud IDE like https://codesandbox.io/
```

**Comment by CoderMaggie** [comment]
Hi! As this is an environment-specific question, please try looking for help on the #support channel of the [Sylius Community Slack](http://sylius.org/slack) or raise a question on [Stackoverflow](https://stackoverflow.com/questions/tagged/sylius) ;)
