### ISSUE TITLE
2.0 RC: deleting a customer triggers an error when generating a URL to redirect to

### ISSUE THREAD

**Issue by rimas-kudelis** [Sylius/Sylius#17443]
**Sylius version affected**: 2.0RC

**Description**  
Deleting a customer by admin fails when generating a redirect URL. The deletion happens successfully though.

**Steps to reproduce**  
In Sylius backend, go to Customer/Customers → specific customer → click Actions/Delete. It seems the URL generation method gets an empty ID instead of the actual ID number.

![paveikslas](https://github.com/user-attachments/assets/604dcdf4-a98c-4abc-be2d-8101f63fe705)

**Comment by GSadee** [comment]
@rimas-kudelis, thank you for reporting an issue, I've just opened a PR with a fix for this issue 👌🏻
