### ISSUE TITLE
2.0 uses incorrect flags in the UI

### ISSUE THREAD

**Issue by rimas-kudelis** [Sylius/Sylius#17467]
**Sylius version affected**: 2.0

**Description**  
Similar to #10416  and other previously reported and previously fixed bugs, Sylius 2.0 again uses incorrect flags in the UI, expecting a language code (when it's not followed by an explicit country code) to correctly match country code. In many cases such assumptions are wrong.

Even for English it is wrong, because there is no country at the moment with code `en`, so the flag is not there. But for other cases, such as Estonian or Czech, it will be even worse because a flag of an unrelated country will be displayed.

**Steps to reproduce**  
Enable English and/or Estonian locale in the [Sylius 2.0 demo](https://v2.demo.sylius.com/admin/locales/). Here's what you will get:
![Sylius locale list](https://github.com/user-attachments/assets/14bea8e8-476a-41db-9923-7955f910e678)

**Possible Solution**  
Review how #10416 was fixed and port the fix to 2.0 branch?

**Comment by GSadee** [comment]
I'm closing this one as the flags problem has been resolved by #17519, with an explanation in the ADR: https://github.com/Sylius/Sylius/blob/2.0/adr/2024_11_28_languages_flags.md
