### ISSUE TITLE
1.14 Channel collector not working in profiler

### ISSUE THREAD

**Issue by JordiDekker** [Sylius/Sylius#17468]
**Sylius version affected**: 1.14.0

**Description**  
After updating to Sylius 1.14 I noticed the channel collector (to switch channels) missed in the profiler bar in the development environment.

**Steps to reproduce**  
Update to Sylius 1.14 and check the profiler bar.

**Possible Solution**

**Comment by GSadee** [comment]
Indeed it looks like the channel collector has disappeared from the profiler bar. Thank you very much for reporting the issue. I have just opened a PR with a fix for this 😃
