### ISSUE TITLE
[2.0][Tests]: Docker config not working for tests in Sylius 2.0

### ISSUE THREAD

**Issue by gitrequests** [Sylius/Sylius#17478]
**Sylius version affected**: 2.0

**Description**  
The docker config may not be suitable for testing the 2.0 version. Is there any documentation on how to run tests in Docker? Does anyone test the Sylius project in Docker?

---

**I noticed some inaccuracies in the project:**

**1. The Dockerfile in `.docker/dev/Dockerfile` uses an outdated image `sylius/standard:1.11-traditional`.**
The description on dockerhub warns that this image is outdated.
https://hub.docker.com/r/sylius/standard

It is suggested to use these images: https://github.com/sylius/docker-images/pkgs/container/sylius-php

I noticed that the docker config in the https://github.com/Sylius/Sylius-Standard repository has already been updated with new images. But in this repository (https://github.com/Sylius/Sylius) they are old.

**2. The compose file in `docker-compose.test.yml` also uses an outdated image in `static` and `behat` services**

**3. If we run Docker now (`docker compose up`, `open localhost`), we will get an error about PHP version incompatibility.**

![Screenshot from 2024-11-18 13-47-14](https://github.com/user-attachments/assets/344a38dd-9fc3-49ec-a697-e3341cb8078e)

**Possible Solution**  
I could suggest a solution, but I can't get into forkflow for testing. Is there any documentation on testing with docker?

**Comment by GSadee** [comment]
Hi, thank you for reporting the issue. I assume that the problem with testing 2.0 with Docker should be resolved by this one: https://github.com/Sylius/Sylius/pull/17528
