### ISSUE TITLE
Why 'sylius' as default validation group?

### ISSUE THREAD

**Issue by gonzalovilaseca** [Sylius/Sylius#1749]
I wonder why 'sylius' is the default validation group for all forms, wouldn't it be better to validate against all groups by default, and specify a validation group only for particular cases?

Having 'sylius' as a default group has two implications:
1) If you want to validate against any group you need to reset the validation groups for all sylius bundles in your config file.

2) Or, in order to keep consistency, validate the new forms against this group by default.

Having Sylius validate against all groups by default would be better I believe (unless I'm missing something here). 

What do you think?

**Comment by teohhanhui** [comment]
This should be fixed. Validation groups should be used to, well, group constraints. Having a "sylius" group that includes everything defeats the purpose. It'd be better to have contextual groups, say, `sylius.admin.product.update`.

**Comment by pamil** [comment]
We can't remove it right now, we can only add new groups to the existing constraints.
