### ISSUE TITLE
PHP 8.4 deprecated implicit null parameter

### ISSUE THREAD

**Issue by JeanDavidDaviet** [Sylius/Sylius#17511]
**Sylius version affected**: I tried with the new 2 version. But I guess it can go back to 1.7 (at least for [ResourceBundle](https://github.com/Sylius/SyliusResourceBundle/blob/1.7/src/Bundle/Controller/ControllerTrait.php#L144))

**Description**  
When using Sylius with PHP 8.4 I got deprecated notices

**Steps to reproduce**  
Create a new project using Sylius-Standard and PHP 8.4, and navigate on the site or use the console
![Capture d’écran 2024-11-25 à 09 17 30](https://github.com/user-attachments/assets/d1b568f2-8987-4c42-9972-c5829eff5fac)

**Possible Solution**  
Use rector with the [ExplicitNullableParamTypeRector](https://getrector.com/find-rule?query=ExplicitNullableParamTypeRector) rules.
But then I don't know if there will be issues with PHPStan and the orders of the arguments, because I noticed some default arguments where used after the implicit nullable parameter. For instance, in vendor/sylius/resource-bundle/src/Bundle/Controller/ControllerTrait.php:146

```php
protected function file($file, string $fileName = null, string $disposition = ResponseHeaderBag::DISPOSITION_ATTACHMENT): BinaryFileResponse
```

**Comment by mpysiak** [comment]
Hi @JeanDavidDaviet,
Thanks for bringing this to our attention. Sylius is not yet ready for PHP 8.4. We will fix the issue in our packages like `ResourceBundle` or `ThemeBundle`. There are also dependencies on external packages, like `PayumBundle` and `LexikJWTAuthenticationBundle`, which will require updates

For now please use PHP 8.3

**Comment by JeanDavidDaviet** [comment]
Alright, thanks for your feedback
