### ISSUE TITLE
Incorrect Case in Service Tag Attributes (AsPromotionRuleChecker and Others)

### ISSUE THREAD

**Issue by ehibes** [Sylius/Sylius#17531]
**Sylius version affected**: >=1.1.13

**Description**  

When declaring a service with attribute AsPromotionRuleChecker for example, an exception is thrown due to bad case `form-type` instead of `form_type` in service tags attributes.
When declaring a service using the AsPromotionRuleChecker attribute (or similar), an exception is thrown due to incorrect casing in service tag attributes. Specifically, `form-type` is used instead of `form_type`.

**Steps to reproduce**  

Create a custom promotion rule checker with the following attribute:
```php
#[AsPromotionRuleChecker('item_by_shipping_category_total', 'label', ShippingCategoryBasedItemTotalConfigurationType::class)]
```
Attempt to use the service and observe the exception caused by the incorrect attribute casing in the service tag.
**Possible Solution**  

Replacing form-type with form_type in [this line](https://github.com/Sylius/Sylius/blob/v1.13.8/src/Sylius/Bundle/PromotionBundle/DependencyInjection/SyliusPromotionExtension.php#L84) resolves the issue.
If this issue is valid, I’d be happy to submit a PR with the necessary changes.

**Comment by Wojdylak** [comment]
Thanks for reporting this! It's definitely a bug. We would really appreciate it if you could contribute with a PR. If you ran into any issues, feel free to reach out - we're happy to help!
