### ISSUE TITLE
Payum error after clear cache . 

### ISSUE THREAD

**Issue by Niavo** [Sylius/Sylius#17547]
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  PHP Warning:  Module "fileinfo" is already loaded in Unknown on line 0
!!  PHP Warning:  Module "gd" is already loaded in Unknown on line 0
!!  PHP Warning:  Module "intl" is already loaded in Unknown on line 0
!!  PHP Warning:  Module "zip" is already loaded in Unknown on line 0
!!
!!  In BaseNode.php line 435:
!!
!!    Invalid configuration for path "payum.security.token_storage": Only one tok
!!    en storage could be configured.
!!
!!
!!  In MainConfiguration.php line 150:
!!
!!    Only one token storage could be configured.
!!
!!

**Comment by GSadee** [comment]
Hi! As far as I can see it is a duplication of https://github.com/Sylius/Sylius/issues/11438, and your problem has been solved on Slack community 🖖🏻
