### ISSUE TITLE
Checkout place order button returns to finalize page with emails enabled

### ISSUE THREAD

**Issue by robholmes** [Sylius/Sylius#1757]
When placing an order, upon clicking the "place order" button on the checkout finalize step, you are immediately sent back to the finalize step, with no messages. You can then click the place order button again, which will then redirect to homepage with "Thank you for your order" message.

Order confirmation emails do get sent every time you click the "place order" button.

To reproduce this bug:
(Symfony 2.3.18, Sylius 0.10.0-dev)
1. Enable emails (my setup is using my Google Apps smtp details to send emails)
2. Enable a dummy payment method
3. Login as customer
4. Add a product to your cart
5. Proceed through checkout, choosing dummy payment method
6. Click "place order" button
7. You should still be on the finalize step, with the same cart
8. Order should be in states of: pending (state), new (payment_state), onhold (shipping_state)
9. Click "place order" button again
10. Order should now be in states of: confirmed (state), completed (payment_state), ready or backorder (shipping_state)

I'm currently trying to isolate the bug, but would be great if someone else can reproduce the issue too, or confirm that they cannot reproduce the issue (meaning it's an issue unique to my setup).

**Comment by michalmarcinkowski** [comment]
No longer valid.
