### ISSUE TITLE
Some help on jms/payment-core-bundle

### ISSUE THREAD

**Issue by AlucardleVash** [Sylius/Sylius#1765]
Does any one have already implement the jms/payment-core-bundle ? maybe with the jms bridge ?
We experience some issues

**Comment by michalmarcinkowski** [comment]
Please post this question on StackOverflow - it is the official support channel for Sylius. Just tag your question with "sylius" and maybe someone will be able to help you! http://stackoverflow.com/questions/tagged/sylius
