### ISSUE TITLE
[ResourceBundle] - PaginatedRepresentation

### ISSUE THREAD

**Issue by zender** [Sylius/Sylius#1769]
When I do API request to index action json response does not contain array of resources. What I get is : {"page":1,"limit":10,"pages":1,"total":1}.

Any idea how to handle that?

**Comment by aRn0D** [comment]
@zender  can you close it?

**Comment by zender** [comment]
if you add "Default" serialization group then it works.

**Comment by skonsoft** [comment]
Thank you zender ! this helped me to solve the problem outside Sylius
