### ISSUE TITLE
Question about Taxonomy Filter Entity

### ISSUE THREAD

**Issue by khyor** [Sylius/Sylius#1778]
Hi,
I use the Staondalone Bundle Taxonomy and Resource for my project

I use the taxonomy with several class with unidirectionnal mapping. (eg: Company, Product, Project, etc.)

is there a way to not display all taxonomies with the sylius_taxon_selection? 

As for options I will wish to display in forms that are useful taxonomy and which directly relates to the entity. 

I thought overload taxonomy class and type form sylius_taxon_selection to give each parent a kind of tag that would serve me to filter the selection for display. Is this a good idea?

**Comment by michalmarcinkowski** [comment]
Please reopen if still relevant or post this question on StackOverflow - it is the official support channel for Sylius. Just tag your question with "sylius" and maybe someone will be able to help you! http://stackoverflow.com/questions/tagged/sylius
