### ISSUE TITLE
ResourceBundle & SettingsBundle require translations from WebBundle

### ISSUE THREAD

**Issue by jrobeson** [Sylius/Sylius#1790]
This makes ResourceBundle not as reusable as it could be.

This also affects reusing SettingsBundle too, since it depends on keys also used by ResourceBundle
NOTE: otherwise im pretty happy with it :)

I'm not sure how it could be solved without some duplication, but then again I've never
worked with translations before.

**Comment by patrick-mcdougle** [comment]
:+1: encountered this annoyance as well.

**Comment by pamil** [comment]
WebBundle is removed now, so it shouldn't be a problem :)
