### ISSUE TITLE
Validator 

### ISSUE THREAD

**Issue by ujhgj** [Sylius/Sylius#1795]
Hello,

I'm trying to add required field `phone` to address entity. I made custrom form and entity for `Address` and validator.xml as well. The problem I faced is that vendor validator is taken in priority. So, if I remove validator.xml from vendors address form acts as I described in my bundle. If I get vendor validator.xml back, I get something like 
`Property phone does not exist in class Sylius\Component\Addressing\Model\Address`
Am I doing something wrong, or it's a bug?

config.yml

    sylius_addressing:
        driver: doctrine/orm
        classes:
            address:
                form: BadBean\Bundle\BagBundle\Form\Type\AddressType
                model: BadBean\Bundle\BagBundle\Entity\Address
        validation_groups:
            address: [badbean]

validator.xml

    <?xml version="1.0" encoding="UTF-8"?>
    <constraint-mapping xmlns="http://symfony.com/schema/dic/constraint-mapping"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:schemaLocation="http://symfony.com/schema/dic/constraint-mapping
                                            http://symfony.com/schema/dic/services/constraint-mapping-1.0.xsd">
        <class name="BadBean\Bundle\BagBundle\Entity\Address">
            <property name="phone">
                <constraint name="NotBlank">
                    <option name="message">sylius.address.phone.not_blank</option>
                    <option name="groups">badbean</option>
                </constraint>
            </property>
        </class>
    </constraint-mapping>

**Comment by michalmarcinkowski** [comment]
Please reopen if still relevant.
