### ISSUE TITLE
Cannot delete promotion because of constraint violation

### ISSUE THREAD

**Issue by sivolobov** [Sylius/Sylius#1799]
> An exception occurred while executing 'DELETE FROM sylius_promotion WHERE id = ?' with params [1]:

> SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`sylius_dev`.`sylius_promotion_order`, CONSTRAINT `FK_BF9CF6FB139DF194` FOREIGN KEY (`promotion_id`) REFERENCES `sylius_promotion` (`id`))

**Comment by michalmarcinkowski** [comment]
This is fixed, instead of exception you will see flash message that promotion is in use and can't be deleted. Later we will add archivization concept (more details [here](https://github.com/Sylius/Sylius/issues/4140)).

**Comment by popama** [comment]
Identify the ID of the promotion and delete from `sylius_promotion_order` table the row which contain it.
