### ISSUE TITLE
Redirects after failed event processing should be configurable in ResourceController

### ISSUE THREAD

**Issue by jrobeson** [Sylius/Sylius#1826]
It is completely possible that i misunderstood the point of what's supposed to happen here, so bear with me.

I added a `pre_create` event to be processed after form submission. 
i called `stop()` in my event when i wanted to force a failure. I expect to end up back to my
form with the flash message set as to why the creation did not succeed. However i end up
somewhere else (but with the flash message set correctly)

it seems to be because of this code in ResourceController 

``` php
         $resource = $this->domainManager->create($resource);

            if (null === $resource) {
                return $this->redirectHandler->redirectToIndex();
            }
```

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php#L181
since there is a `null` `$resource` (due to calling `stop()`) i end up there.

Is there a reason that `redirectToIndex` is used here? Obviously i'm only working
in the context of the ResourceBundle, so i'm not aware of any wider Sylius implications.

It's possible that there should be a separate option for redirecting on failure vs 
success.

**Comment by michalmarcinkowski** [comment]
Fixed.
