### ISSUE TITLE
ResourceBundle: How to pass current user to repository in routing.yml using _sylius option ?

### ISSUE THREAD

**Issue by jbinfo** [Sylius/Sylius#1827]
I want to list all compagnies created by the connected user, so I need to pass @security.context to repository to get user and make a filter.

**Comment by radhwenhamdani** [comment]
comment je peut récupérer cette arguments dans la classe répository avec queryBuilder

**Comment by aa-ahmed-aa** [comment]
i got this error 
![image](https://user-images.githubusercontent.com/9592546/105177433-57d37b00-5b2f-11eb-936f-cb3be17c79cb.png)

**Comment by aa-ahmed-aa** [comment]
on sylius 1.8 to get the authenticated admin you can use the service argument  `expr:service("security.token_storage").getToken().getUser()`
