### ISSUE TITLE
[Request] Doctrine Translations

### ISSUE THREAD

**Issue by Junky2008** [Sylius/Sylius#1832]
To be able to use the site in multilanguage.
ie:
A product description should be in english and dutch if the site is in both. With doctrine translations it should be possible: http://doctrine-phpcr-odm.readthedocs.org/en/latest/reference/multilang.html or maybe with gedmo: http://vincent.composieux.fr/article/manage-multiple-translations-with-doctrine-gedmo-translatable . Has anyone started something like this already?

Junky

**Comment by aRn0D** [comment]
This feature is implemented now !
