### ISSUE TITLE
How to implement Blue Card payment in Sylius ?

### ISSUE THREAD

**Issue by jbinfo** [Sylius/Sylius#1835]

**Comment by michalmarcinkowski** [comment]
Please post this question on StackOverflow - it is the official support channel for Sylius. Just tag your question with "sylius" and maybe someone will be able to help you! http://stackoverflow.com/questions/tagged/sylius

**Comment by jbinfo** [comment]
About one year to close the issue, how much time needed to update the payment documentation on the website ??

**Comment by pjedrzejewski** [comment]
@jbinfo Well, with a project of this size, it takes time to document everything. Keep in mind it is still in alpha and targeted for more experienced Symfony developers who should not have a problem figuring this out, based on the code for existing payments. Anyway, we hope to document it as soon as possible!
