### ISSUE TITLE
[RFC] Doctrine underscore naming strategy

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius#1837]
In doctrine mappings we have always something like:

`<field type="string" name="paymentState" column="payment_state" />`

I discussed with @kayue and we agree that stuff like this should be automated.

We can use http://doctrine-orm.readthedocs.org/en/latest/reference/namingstrategy.html#underscore-naming-strategy for this.

Thoughts?

**Comment by pamil** [comment]
Asked about the same stuff in #5408 and it seems like we won't enforce a naming strategy in Sylius.
