### ISSUE TITLE
Login with username insted of email... is  possible ?

### ISSUE THREAD

**Issue by Chrysweel** [Sylius/Sylius#1849]
Hello.

I integrated Sylius in my symfony2 project 

I saw how Sylius remove field username ( https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Form/Type/RegistrationFormType.php#L27 )

In database the username, and email is the same data.  So I can login with my email only... 

Can I save username and email differents  ? And so can I login with my username ?

FOSUserBundle has a providers:

```
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
```

With Sylius is mandatory to login with email ?

**Comment by stloyd** [comment]
@pjedrzejewski @aRn0D I guess this can be closed as it was fixed.
