### ISSUE TITLE
Is Address validation enabled?

### ISSUE THREAD

**Issue by pestaa** [Sylius/Sylius#1871]
When I submit an order at http://demo.sylius.org/checkout/addressing with the form being left empty, I run into an Internal Server Error. In my project it states that first_name should not be null, which I think is the same problem.

I tried to explicitly enable the "sylius" validation_group for addresses, but to no avail. Looking at the dependency injection it looks implied.

AddressingBundle's validation.xml declares a set of constraints, but none of them seem to apply to either the stock Address entity or an extended one.

I'm missing a piece of the puzzle, but can't find it, please advise.

**Comment by bojanz** [comment]
Related: #2570, which will make the address validation actually useful.

**Comment by Zales0123** [comment]
It's been a while since introducing this issue and it seems to work now, on current master as well as on SyliusDemo. Does anybody still experience this bug?
