### ISSUE TITLE
Backend views autogeneration

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#1881]
How about automatic back-end views generation based on Entity data?

It will help with centralized implementation next functions:
- Sort list by field value (asc, desc) on index;
- Select per page items count & goto page field;
- Filter list (search);
- Add checked items action buttons (delete checked items, disable checked items, ...);
- Add list action buttons (export to xls, send report, ...);
- Add list item action buttons (disable, enable);
- Change position of items;
- etc...

This will help with fast customization. With no need to write a lot of functionality each time on each view. And even more important - this helps Sylius to evolve faster.

(I'm new in Symfony and Sylius, so sorry if my example weird).

```php
class OrderBackend extends Backend {
  function __construct () {
    $this->list->addSortingByField(fieldName, ...);

    $this->list->addInlineEditableField(fieldName, ...);

    $this->list->addFilterByFieldValue('orderTotal', new FilterFromToInput());
    $this->list->addFilterByFieldValue('userPhone', new FilterByPhone());
    $this->list->addFilterByFieldValue('shippingCountry', new FilterBySelectedValue($countries->getList()));

    $this->list->addItemAction('Disable', new InlineAction(function(item){
       //some action
    }));
  }
}
```

```html
{# Filters #}

{# List #}
{% for item in list.items %}
<div class="item">
  {% if (list.hasField(position)) %}<i class="drag-to-change-item-position"></i>{% endif %}
  {% if (list.hasMassActions()) %}<input type="checkbox" name="massActionItemsIds" value="{{ item.id }}" />{% endif %}
  <a href="{{ item.href }}">{{ item.name }}</a>
  {% for button in item.buttons %}
    <a href="{{ button.href }}">{{ button.label }}</a>
  {% endfor %}
</div>
{% endfor %}

{# Action buttons #}
{% for button in buttons %}
<div class="actions">
  <a href="{{ button.href }}">{{ button.label }}</a>
</div>
{% endfor %}
```

**Comment by pjedrzejewski** [comment]
Will be implemented with #1488 and grids.
