### ISSUE TITLE
Multiple tax rates per zone

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#1882]
Realistic Scenario in Canada:
For a business in British Columbia (province) that is selling Canada wide, the tax rate is different per province. To put it simply, customers who are in BC get charged a PST (Provincial sales tax) and a GST (Goods and services tax), and customers who are not in BC either get charged a GST or HST. The details are not important here.

A customer in BC should fall into two zones:
1) Provinces with GST (5% tax)
2) BC (PST of 7%)

However, when I checkout as a customer from BC, I only get charged 7%, and not the 5% GST.

I have tried a bunch of different solutions, but the only way I can get this to work is to create a BC zone, and set the total tax to 12%. Is there a way I can show the user the separate taxes? (Basically, can a user fall into multiple zones, and get charged the taxes from each zone?)

Edit: I have tried a lot of different combinations of zones, and even tried multiple taxes per zone (which seems to throw a non-unique exception on the website, but its fine in the backend).

**Comment by ima-tech** [comment]
Why is this closed? Is there a way to do it?

**Comment by alexsegura** [comment]
Hi @inssein 

Did you end up finding a solution? I have to do this too 🙂

**Comment by maximehuran** [comment]
Maybe related to https://github.com/Sylius/Sylius/issues/11788
