### ISSUE TITLE
[ResourceBundle] TwigExtension and sub request

### ISSUE THREAD

**Issue by Strontium-90** [Sylius/Sylius#1925]
If controller was rendered as partial, this extension will generate wrong sorting links. Example:
We have `resource_details` page with template
```twig
<div data-pjax-container="logs_list">{{- render(path('resource_logs', 'id': resource.id}))</div>
```
Sorting links in `resource_logs` page will referer to `resource_datails` page instead of `resource_logs`.

Problem is here
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Twig/ResourceExtension.php#L95
```php
if (HttpKernel::MASTER_REQUEST !== $event->getRequestType()) 
```
Extension contains master request instead of sub-request.

**Comment by aRn0D** [comment]
@Strontium-90 this is not a bug this is the normal behavior for now. I keep it open in case someone wants to work on it.
