### ISSUE TITLE
[RFC] API Authentication

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius#1931]
This RFC is related with https://github.com/Sylius/Sylius/pull/1787, and I think it deserves separate discussion thread.

One solution is to do what is described in [How to Authenticate Users with API Keys](http://symfony.com/doc/current/cookbook/security/api_key_authentication.html). I vote for upgrading to Symfony 2.4 before this, it should not be hard I guess, at least according to [UPGRADE-2.4.md](https://github.com/symfony/symfony/blob/master/UPGRADE-2.4.md).
If we go this path, should our authentication be stateless?
Should we reuse existing Oauth authentication?

Then there is a question for roles, should we have all existing roles for API users as well (user API and admin API)? 

I am willing to contribute this if I get enough feedback.

@kayue @pjedrzejewski @stloyd @aRn0D @jrobeson @jjanvier @Richtermeister @winzou

**Comment by kayue** [comment]
Now API is working on master branch. We should move on to authentication.
What do you guys think about using JWT? I believe this is a work out of the box solution for us!

- https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md
- http://geshan.blogspot.hk/2014/07/3-bundles-to-get-started-with-rest-in.html

One real life example of JWT is Firebase:

- https://www.firebase.com/docs/rest/guide/user-auth.html#section-rest-token-generation

/cc @pjedrzejewski @stloyd @umpirsky

**Comment by pjedrzejewski** [comment]
We have been using OAuth, requires little configuration and few fixes that we hope to contribute to main repo soon. I'd say this should be standard.

**Comment by kayue** [comment]
@pjedrzejewski I see, looking forward to see your solution!

**Comment by stloyd** [comment]
Personally I would vote for replacing OAuth with something simpler than that... There is plenty of options =)

**Comment by umpirsky** [comment]
Sylius usually offers layer of abstraction and let developers choose what they want to use. Not sure if this is way to go for authentication.

**Comment by pjedrzejewski** [comment]
@umpirsky Well, I am saying about default auth for Sylius api. You can configure Symfony security your preferred way. Our solution is few fixes in SyliusApiBundle and better config. If you want to use different auth, just configure it under security. :)

**Comment by pjedrzejewski** [comment]
I think this can be closed. :)
