### ISSUE TITLE
[Core] "Add product" promotion should run item resolvers

### ISSUE THREAD

**Issue by stloyd** [Sylius/Sylius#1960]
Current approach in that promotion is bugged, cause if you have promotion with product that is normally being sold, and it's not backorderable, you can endup with order that can't be completed (from shop not code perspective) cause you will have missing product ordered.

For fix suggestion see: https://github.com/Sylius/Sylius/pull/1935#issuecomment-57281570

**Comment by pjedrzejewski** [comment]
Not supported anymore.
