### ISSUE TITLE
Update Symfony to 2.4

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius#1966]
Should be pretty simple according to [UPGRADE-2.4.md](https://github.com/symfony/symfony/blob/master/UPGRADE-2.4.md).

**Comment by antonioperic** [comment]
+1

**Comment by patrick-mcdougle** [comment]
Should probably start thinking about moving to 2.7(LTS). Feature freeze is here, and release is likely imminent.

**Comment by jrobeson** [comment]
yep.. Sylius code is spewing all sorts of deprecation notices on 2.7. Maybe we should retitle this issue Update Symfony to 2.7

**Comment by pamil** [comment]
@pjedrzejewski @michalmarcinkowski to be closed :)

**Comment by michalmarcinkowski** [comment]
We're moving to 2.7 :)
