### ISSUE TITLE
OrderInterface::getLastPayment() returns false

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius#1973]
In [OrderInterface.php#L193](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/Model/OrderInterface.php#L193 ) it says that this method returns `PaymentInterface`, but it returns false in [Order.php#L275](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/Model/Order.php#L275).

This can lead to fatal errors if we expect `PaymentInterface`.

In this case I suggest throwing exception or returning null, false is the last thing I expected here.

`OrderInterface::getLastShipment` have similar issue.

**Comment by antonioperic** [comment]
should be closed? cc @stloyd  @pjedrzejewski
