### ISSUE TITLE
Error in extending user model

### ISSUE THREAD

**Issue by Dsazz** [Sylius/Sylius#1975]
1. I created a new User class in WinShop\MainBundle\Entity
   ![1412409686637](https://cloud.githubusercontent.com/assets/7807209/4514980/4fd6201c-4b9e-11e4-9620-b8ecab826fd5.jpg)
2. I've created a User.orm.xml
   ![1412409749386](https://cloud.githubusercontent.com/assets/7807209/4514983/8068cf90-4b9e-11e4-8bb9-a6e9fa696009.jpg)
3. And define my new model in app/config/config.yml
   ![1412410313642](https://cloud.githubusercontent.com/assets/7807209/4514987/a7af7b30-4b9e-11e4-8285-355f11a7d523.jpg)
   Result:
   ![1412410668654](https://cloud.githubusercontent.com/assets/7807209/4514992/054acaba-4b9f-11e4-8f58-2bf73247857d.jpg)

**Comment by nils-m** [comment]
Ok!
This should definitely be in the General Guide or CookBook.
