### ISSUE TITLE
Promotion rule for shipping country is not working

### ISSUE THREAD

**Issue by vytenizs** [Sylius/Sylius#1987]
Hi, if i select promotion and want to add rule with shipping country i get a following error:
The form's view data is expected to be an instance of class Sylius\Component\Addressing\Model\Country, but is a(n) array. You can avoid this error by setting the "data_class" option to null or by adding a view transformer that transforms a(n) array to an instance of Sylius\Component\Addressing\Model\Country.

**Comment by pjedrzejewski** [comment]
This should be fixed now. Please reopen if you still experience this issue.
