### ISSUE TITLE
Having a Prototype that's agnostic of Product

### ISSUE THREAD

**Issue by adamelso** [Sylius/Sylius#2001]
So the interface method `Sylius\Component\Product\Builder\PrototypeBuilderInterface::build(PrototypeInterface $prototype, ProductInterface $product)`, the only method in the interface requires a Product to be passed through as the second parameter.

I wanted to implement my own prototype builder, but not for a Product. I wonder if it is at all possible of easy to separate the concepts of a `Prototype` from that of `Product`? Maybe a prototype bundle/component.

In my use case, I wish to create classified ads that have Attributes and Options, much like Product does. For my Advertisement model, I have implemented `AttributeSubjectInterface` and `VariableInterface`. So in to order to post an ad that's selling a car for example, I'd like to create a Prototype ad for selling cars which would contain specific attributes such as _mileage_ or _engine size_.

Currently I've attempted to replicate what Sylius does with product prototypes directly but this could be abstracted out perhaps.

ps. Can anyone submit an RFC in GitHub Issues? Thanks ;)

**Comment by stloyd** [comment]
@pjedrzejewski @adamelso Is this still relevant as #2225 was merged?
