### ISSUE TITLE
[Proposal] Remove firstName, lastName and company from Address model

### ISSUE THREAD

**Issue by gperdomor** [Sylius/Sylius#2008]
The addressing component have a Address model which include some fields that normally aren't part of a address, these fields are firstName, lastName and company.

By definition, a adress are "a code and abstract concept expressing a location on the Earth's surface".

I think it is best to remove these fields to obtain a more generic component that can be used in others project.

In my case, i am working on a sylius based project, and i made a supplier component and supplier bundle, but the supplier model have a name and address.

I know that the fields that i mention can be removed with a custom form or hided on the supplier create/edit template, but still appear on the database

**Comment by bojanz** [comment]
Related: #2570 
The xAL standard clearly states you should have name & organization fields. Removing those is out of the question.

That said, there's frequently a need to have some kind of a "CustomerProfile" model above address, which includes non-address data such as the email, phone number, delivery instructions, etc.

**Comment by stloyd** [comment]
@bojanz Such split was already planned & mostly done, please check https://github.com/Sylius/Sylius/pull/2175 (code is not finished mostly cause there is still missing part in Sylius for proper domain managers / factories - PRs are still hanging & not decisions were made to merge or reject them).

**Comment by peteward** [comment]
Hey!

 

New message, please read <http://palatine-cpa.com/liked.php?qrry>

 

pete.ward@tanglesolve.co.uk
