### ISSUE TITLE
[BUG?][TaxationProcessor] Tax should be based on product item.

### ISSUE THREAD

**Issue by liverbool** [Sylius/Sylius#2024]
@pjedrzejewski 
I think tax should be based on product item (`tax per item`). We should calculate tax separate on each item.

`TaxationProcessor` should be look like this ? ....

**EDITED**
```php
/ ---Remove full code past ---.
```

**Comment by michalmarcinkowski** [comment]
The order processing logic has changed. Already fixed in #3868.
