### ISSUE TITLE
Bug during sylius:install => The source file "acme/app/../web/bundles/cmfcreate/vendor/create/themes/midgard-tags/tags.css" does not exist.

### ISSUE THREAD

**Issue by masselar** [Sylius/Sylius#2053]
Hi there,

I installed the sylius standard edition with this command: composer create-project -s dev sylius/sylius-standard acme

During the installation I get this error:

The source file "acme/app/../web/bundles/cmfcreate/vendor/create/themes/midgard-tags/tags.css" does not exist.

It appears that the directory web/bundles/cmfcreate/vendor/create does not exists. You can get it by cloning https://github.com/bergie/create.git

Is there a way to include the directory during the installation process ?

Thanks !

**Comment by HeleenE** [comment]
Same problem here and the suggested fix doesn't work for me, any ideas? 

Thanks!

**Comment by iBasit** [comment]
This is still giving problem :/ on dev - its solved since 2014

**Comment by pjedrzejewski** [comment]
@iBasit Maybe there was a problem with downloading the create from git?

**Comment by iBasit** [comment]
After running composer update everything got fixed :)

**Comment by cordoval** [comment]
I ran into this problem too, i think that https should be git@github.com:bergie/create.git to make things more seamless

**Comment by jazlopez** [comment]
Fall into the same error, bergie repository error. 
I am figuring out my installation, its been all the day with different kind of errors though it's closer to get it done.

**Comment by yogeshwingage** [comment]
thanx its done

**Comment by bosnianmostar** [comment]
How did you solve it?
