### ISSUE TITLE
Translate resource names in flash messages

### ISSUE THREAD

**Issue by holyspecter** [Sylius/Sylius#2125]
In my app flash messages for resource actions are translated partially and I'm getting something like that:
`Product provider был успешно создан.` In `FlashHelper` I've found method:
```
private function translateFlashMessage($message, $params = array())
    {
        $resource = ucfirst(str_replace('_', ' ', $this->config->getResourceName()));

        return $this->translator->trans($message, array_merge(array('%resource%' => $resource), $params), 'flashes');
    }
```
which even doesn't try to find translation for resource. So how can I translate me resource name? Maybe I've missed something?

**Comment by jbator** [comment]
I have the same problem, 
It looks like the resource part of the flash message is not translatable yet

**Comment by aRn0D** [comment]
Guys did you have a look to http://docs.sylius.org/en/latest/bundles/SyliusResourceBundle/flash.html ? You can not translate the name of the resource ;) you need to translate it.
