### ISSUE TITLE
[Bug][Blocker][Variation] Product options wrong values

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#2135]
Given we have a product with the following options (and values): T-Shirt size (S, M, XL) and T-Shirt color (Red, Green, Blue). The variant selection method is set to "match".

Then we create only two variants for this product. We choose **Green & S** and **Blue & XL**. Now, when you go to the products detail page (store front). You would expect to have two selectboxes where you can only select the colors `Green, Blue` and `S, XL`. Instead, it will render ALL option values!

Here a screenshot with the problem. Those option values should not be there, since those variants don't exist:
![](http://puu.sh/cO1Zz/b6735519bb.png)

I hope I made my issue clear, this is in my opinion a serious blocker.

@pjedrzejewski @stloyd 

BTW: Running Sylius 0.12.x@dev

**Comment by pjedrzejewski** [comment]
Let's keep it in #917.
