### ISSUE TITLE
how can i handle with "Virtual Product" in Sylius ? 

### ISSUE THREAD

**Issue by wil0** [Sylius/Sylius#2150]
hi, this is not Issue, just ask for help , I want to handle my commerce logic use Sylius, but the default Interface, such as Product, Variant, Payment, is base on shippable, inventoriable product, Is any one got the way to handle with product not shippable, no inventory product? thanks;

**Comment by pjedrzejewski** [comment]
Let's keep discussion here #2176. I agree on every product being shippable. We actually used "E-Mail" shipping method for virtual goods and have some ideas how to make it generic.
