### ISSUE TITLE
Invalid argument supplied for foreach() in /vagrant/app/bootstrap.php.cache

### ISSUE THREAD

**Issue by antonioperic** [Sylius/Sylius#2157]
ContextErrorException: Warning: Invalid argument supplied for foreach() in /vagrant/app/bootstrap.php.cache line 2808

After latest update, I tried to run new version of Sylius and I got this error. Anybody with similar problem?

**Comment by mCzolko** [comment]
I have a Vagrant Box and Symfony app as well, what was your issue with that? I'm getting same error
