### ISSUE TITLE
Use of SauceLabs' Open Sauce plan

### ISSUE THREAD

**Issue by headrevision** [Sylius/Sylius#217]
Next logical step for BDD in Sylius is the use of Open Sauce by SauceLabs. (SauceLabs integration in Sylius is already implemented https://github.com/Sylius/Sylius/pull/206)

https://saucelabs.com/opensource
https://saucelabs.com/opensource/travis

**Comment by lchrusciel** [comment]
AFAIK, no in the plans to be integrated.
