### ISSUE TITLE
Use sylius_cart_item form for item edition

### ISSUE THREAD

**Issue by winzou** [Sylius/Sylius#2186]
Hi,

I'm currently implementing cart item edition to be able to change the variant of a product without the need of deleting the item and adding a new one. I'm with variant_selection_match strategy (= a list of options in the form, matched to a variant on submit).

I'd like to use the same `sylius_cart_item` form that is used for item addition. But I'm seriously blocked when I change the value of an option. Instead of changing the selected variant on the item via `$item->setVariant($newlyMatchedVariant)`, the form is changing the OptionValue of the Variant itself.

So if I change my option from value A to B, the form changes in the db the variant ProductAOptionA to ProductAOptionB, which is a duplicate of the already existing ProductAOptionB! Here are the executed queries:

    DELETE FROM sylius_product_variant_option_value WHERE  variant_id = 1  AND option_value_id = 20
    INSERT INTO sylius_product_variant_option_value (variant_id, option_value_id) VALUES  (1, 30)

(Expected behavior: `UPDATE FROM sylius_order_item SET variant_id = 25 WHERE id = X`)

Does anyone have an idea? Forms are not my cup of tea :-/

Bonus question: when investigating this optionValue changing on the variant itself, I noticed that the `setOptions`, `addOption` and `removeOption` methods are never called on the `Sylius\Component\Variation\Model\Variant` model. How is this value changed? I don't get it.

Thanks for your lights!

**Comment by winzou** [comment]
ping @pjedrzejewski :)

**Comment by pjedrzejewski** [comment]
Please reopen if still relevant on the new shop. The field edited should be ``variant`` and I am pretty sure it should work correctly if you use one of the variant selection form types. (list vs. options)
