### ISSUE TITLE
Reusable packaging

### ISSUE THREAD

**Issue by lbaey** [Sylius/Sylius#2191]
This is not an issue, I need help :
How would you implement reusable package of a product e.g. milk in bottle and the bottle is paid with the first buy and returnable ?
- I was thinking of a product option to have a variant with the price including the returnable bottle but I won't be able to extract the product price.
- Another way would be an attribute, but it seems to me that the code would be too static, or too complex.
- It could also be mecanism based on a tax type, but I want it to be exposed independently from other taxes on the invoice.

Another problem : on the second product buying from the customer, he would return the bottle and be reimboursed with it's value (that brings the impossibility to assign a negative price to an item), although he'd buy another one with the bottle price included. Or else I create a product variant "without bottle" ...

Has anyone implemented something similar ? Any idea ?
Thank you

**Comment by pjedrzejewski** [comment]
@lbaey Sorry for lack of answer here. Please reopen if still relevant in any way. Thank you!
