### ISSUE TITLE
Slideshow blocks creation is having wrong translation

### ISSUE THREAD

**Issue by littlechad** [Sylius/Sylius#2194]
Hi,

When creating a slideshow, the filter dwopdown is showing a wrong selection

![screen shot 2014-11-30 at 5 27 11 pm](https://cloud.githubusercontent.com/assets/3166340/5237444/4d245bfa-78b6-11e4-9356-717fc4322867.png)

Patch:
In the ContentBundle translations messages.en.yml:10 we have

    imagine_block:
            parent: Parent
            internal_name: Internal name
            slideshow_small: 'Slideshow Large (full width)'
            slideshow_medium: 'Slideshow Medium (content)'
            slideshow_large: 'Slideshow Small (side)'

it should be switched into

    imagine_block:
            parent: Parent
            internal_name: Internal name
            slideshow_small: 'Slideshow Small (side)'
            slideshow_medium: 'Slideshow Medium (content)'
            slideshow_large: 'Slideshow Large (full width)'

**Comment by psyray** [comment]
Fixed https://github.com/Sylius/Sylius/pull/2531
