### ISSUE TITLE
[Bug] Locale regression / Session storage

### ISSUE THREAD

**Issue by pfz** [Sylius/Sylius#2199]
It seems that since Session storage has been refactored, locale session doesn't work anymore:
Create 2 locales in administation (ex: FR, DE). Go back to shop, switching doesn't work.
I tried using vagrant and sylius default installation to be sure.

Checkout scenario was lost after completing payment (thus redirection), but it's been solved since this refactoring I don't know how.

**Comment by pjedrzejewski** [comment]
This should be fixed now but there is still some bugs regarding language handling in both frontend and backend.
