### ISSUE TITLE
Administrator login not working

### ISSUE THREAD

**Issue by rajeshmeniya** [Sylius/Sylius#220]
I have just install fresh Sylius package with all steps including datafixture.
But when I run "http://local.sylius-shop.rjm/app_dev.php/administration/login"
Fill my username, password and click "Login" button.

**It's displays me below Exception :**

No route found for "POST /administration/login": Method Not Allowed (Allow: GET, HEAD)
405 Method Not Allowed - MethodNotAllowedHttpException
1 linked Exception: MethodNotAllowedException »

**Comment by Symfomany** [comment]
:+1:

**Comment by mozzymoz** [comment]
Is there a default username and password?
I could not use console sylius:install as it would result in constraint errors in mysql, so I just used doctrine commands to build the database.
