### ISSUE TITLE
Search question

### ISSUE THREAD

**Issue by antonioperic** [Sylius/Sylius#2205]
Hi,
one question about search configuration. Is there any other way to adding attributes search except mapping one by one. For example if we have 100+ attributes for different products it is quite heavy to map them all by hand
cc @agounaris

**Comment by peteward** [comment]
Hi @antonioperic, I haven't forgotten about this, I just haven't had time to do anything about it unfortunately :(

We need to rework search anyway as I've set out in https://github.com/Sylius/Sylius/issues/2305.

We can consider automatically indexing all attributes and options here. Although you have to consider that your search results might be extremely wide in scope if you're throwing very large amounts of content at the search engine.

**Comment by Raisadomua** [comment]
What if the search in sylius 0.12.0-dev does not work:

An exception occurred while executing 'SELECT s0_.item_id AS item_id0, s0_.tags AS tags1, s0_.entity AS entity2 FROM sylius_search_index s0_ WHERE MATCH (s0_.value) AGAINST (?) > 0' with params ["\u0428\u043a\u0430\u0442\u0443\u043b\u043a\u0430"]:

SQLSTATE[HY000]: General error: 1191 Can't find FULLTEXT index matching the column list

?

**Comment by antonioperic** [comment]
@Raisadomua please check this https://github.com/Sylius/Sylius/issues/2158

**Comment by Raisadomua** [comment]
Thank you for watching.
What does "run the indexing command" mean?
After run command: php app/console index:populate
 I have: " There are no commands defined in the "index" namespace".
Thanks.

**Comment by antonioperic** [comment]
@Raisadomua run search:index:populate

**Comment by Raisadomua** [comment]
php app/console search:index:populate

  [InvalidArgumentException]
  There are no commands defined in the "search:index" namespace.
  Did you mean this?
      sylius:search

**Comment by antonioperic** [comment]
yes

**Comment by Raisadomua** [comment]
Which command to execute?

**Comment by antonioperic** [comment]
sylius:search:index                     
That command will Populate the index

**Comment by Raisadomua** [comment]
>php app/console sylius:search:index
Index populate command
PHP Fatal error:  Call to undefined method Sylius\Component\Core\Model\Product::get0() in D:\server\apache24\htdocs\sylius-st\sylius-standard\vendor\s
ylius\sylius\src\Sylius\Bundle\SearchBundle\Indexer\OrmIndexer.php on line 245

Fatal error: Call to undefined method Sylius\Component\Core\Model\Product::get0() in D:\server\apache24\htdocs\sylius-st\sylius-standard\vendor\sylius
\sylius\src\Sylius\Bundle\SearchBundle\Indexer\OrmIndexer.php on line 245

**Comment by agounaris** [comment]
@Raisadomua Do you have products in the database?

**Comment by Raisadomua** [comment]
Yes, I have.
![1](https://cloud.githubusercontent.com/assets/3763603/5887332/afc20040-a3d2-11e4-9075-9f1a92397645.jpg)
![2](https://cloud.githubusercontent.com/assets/3763603/5887333/b33df440-a3d2-11e4-8dc1-62fd758a2860.jpg)
![3](https://cloud.githubusercontent.com/assets/3763603/5887334/b5a360c6-a3d2-11e4-9ec8-586e5c3d1d33.jpg)

**Comment by axelvnk** [comment]
Running the index:populate gives me a  'No locale has been set and currentLocale is empty' exception. Not sure why because my sylius_locale has been set in my config file.

**Comment by michalmarcinkowski** [comment]
SearchBundle was removed, use ElasticSearch or Solr for more advanced search features.
