### ISSUE TITLE
Search Service

### ISSUE THREAD

**Issue by timglabisch** [Sylius/Sylius#2211]
i a just wondering why the sylius_search.finder is stateful, take a look at this:
     
    $this->get('sylius_search.finder')
         ->addTargetType('product')
         ->setFacetGroup('search_set')
         ->find(new SearchStringQuery(
               $request,
               $this->container->getParameter('sylius_search.pre_search_filter.enabled')
           )
   );

why not defining a stateless api like:

    $this->get('sylius_search.finder')->search(
         (new searchContext::fromPhrase(....))
             ->setItemsPeerPage(...)
             ->setPage(...)
             ->setAggregationGroup(AggregationGroup::fromString("search_set')
             ->setTargetType(SearchContext::TARGET_TYPE_PRODUCT)
    )

**Comment by adam-paterson** [comment]
+1

**Comment by PWalkow** [comment]
:+1:

**Comment by pjedrzejewski** [comment]
:+1:

**Comment by michalmarcinkowski** [comment]
SearchBundle is removed.
