### ISSUE TITLE
[RFC] Backorderable per product and not whole store

### ISSUE THREAD

**Issue by waaghals** [Sylius/Sylius#2214]
The setting if products can be back-ordered is now a site wide configuration.
Would be nice if this could be set on a per item basis.

How to handle the settings?
1. Keep side wide configuration and overwrite in product?
or
2. Remove site wide configuration and set the values on every product separably?

**Comment by pestaa** [comment]
I'm exploring this area now, and found this strange too.

In short, the backorder flag seems to be redundant and somewhat misleading.

Available on demand is true by default (as of 0.17alpha anyway), but disabling it for specific products has no effect until you also disable backorders, too.

The flag is used in the availability checker only (to my knowledge), so it might be already considered deprecated.
