### ISSUE TITLE
[RFC][ResourceBundle] Missing list, show events for resource.

### ISSUE THREAD

**Issue by liverbool** [Sylius/Sylius#2223]
For resource-bundle we have `pre_create, post_create, .. update, delete` events, I think we should have something like `pre_list, post_list, pre_view, post_view` too.

Benefit? 
  * allow external service to subscribe and process `resource` e.g. we can implement `acl` system outside of resource-bundle.
  * and many more

/cc @aRn0D @stloyd @pjedrzejewski

**Comment by Niiko** [comment]
It would be great to have event on each resource controller action. 
In that case we can compute some statistics on kernel.terminate event.

I already use it like in detailsAction on productController (but have to override that controller for that).

**Comment by michalmarcinkowski** [comment]
There is already `show` event, so you can easily count number of displays etc.

**Comment by Niiko** [comment]
The show event is only triggered in backend (showAction) not in frontend display (detailsAction).

**Comment by michalmarcinkowski** [comment]
Thanks for pointing that out! We will change that together with the new frontend.

**Comment by michalmarcinkowski** [comment]
Fixed already.
