### ISSUE TITLE
CMF Menu: problem to create menu with static page as child

### ISSUE THREAD

**Issue by kurakin-oleksandr** [Sylius/Sylius#2235]
I tried to create menu with static pages. In `/administration/content/menus/new` I create new menu, add new menu element and set in `Content` my static page. Save, render (via `knp`) -> empty result.
It works with routes and urls.

I also tried to create new route (CMS Route) for static page but it doesn't work at all. I have a validation error during saving.

**Comment by renereed1** [comment]
I've also seen the issue of the validation error during saving of new CMS static pages. Looks like an chicken and egg problem where you can't create a new page without first creating a route, and you can't create a route without first creating a page.

The way I was able to get it to work was first create a new page, but don't define a route. Once the page has been created, edit that page and add the route. An issue with this is it brakes the site. Not ideal for production, but I get this error once I save the page without the route defined:

![screen shot 2015-01-14 at 8 16 53 pm](https://cloud.githubusercontent.com/assets/4702748/5752454/5bea1034-9c2a-11e4-85a4-c3f0af320179.png)

**Comment by kurakin-oleksandr** [comment]
Problem was solved somehow after removing all static pages. But `knp` still doesn't render menu

**Comment by pjedrzejewski** [comment]
Menu support has been removed.
