### ISSUE TITLE
Missing order states

### ISSUE THREAD

**Issue by inspiran** [Sylius/Sylius#2236]
I could not find in any documentation to the actual meaning of each order state.  Some of them are obvious but some might need some explaining in the docs. (eg. "confirmed").   Furthermore I believe two states are missing:

* partial_shipped : indicating that an order was only partially shipped, awaiting a second shipment
* closed (or completed or finished) : indicating that the order is finished by the backend administration.  For instance, an order might need to be processed by the account department after it was shipped.   They then would put the order in a closed state.

How can you see completed orders in the backend admninistration?  Currently they seem to be filtered out here : 

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/OrderBundle/Doctrine/ORM/OrderRepository.php#L34

**Comment by michalmarcinkowski** [comment]
Order states has been reworked, see #4060
