### ISSUE TITLE
eBay and Amazon Integration

### ISSUE THREAD

**Issue by imcodingideas** [Sylius/Sylius#2242]
eCommerce owners invest money and time in opening/migrating to a new eCommerce store. However marketplaces like eBay and Amazon are perfect channels for new or existing businesses. We do 10 million a year on these marketplaces.

Feature Request: 
- Push products to eBay in their proper category
- eBay templates
- eBay profiles ( things like matching attributes to eBay, increase price that gets pushed to eBay i.e. +10% )
- Import orders from eBay -> Store
- Create users after orders from eBay are imported.

What do you think?

**Comment by ikourfaln** [comment]
+1

**Comment by ikourfaln** [comment]
don't do it bot, we are still interested 😉

**Comment by ikourfaln** [comment]
UP... please Bot, don't close this, we still waiting for this feature.

**Comment by pamil** [comment]
These integrations won't make their way into Sylius itself, but they can be developed independently as plugins.

**Comment by michael-kindtner** [comment]
@pamil hi, do you have any info if anyone is currently working on this? I would love to use sylius soon, but that one is simply a showstopper for us. Thx, Michael
