### ISSUE TITLE
[ResourceBundle] make dependency on GEDMO Loggable option

### ISSUE THREAD

**Issue by lsmith77** [Sylius/Sylius#2252]
To enable reuse of Bundles outside of Sylius its important to keep dependencies optional:
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php#L266

Maybe this can be better handed via events?

**Comment by colejarczyk** [comment]
Check this PR #2255
