### ISSUE TITLE
liip/imagine-bundle version conflict

### ISSUE THREAD

**Issue by Tetragramat** [Sylius/Sylius#2258]
Hi, now in Sylius 0.12.0 is required:
Sylius:
* symfony-cmf/media-bundle: ~1.0
* liip/imagine-bundle: ~1.0

ContentBundle:
* symfony-cmf/media-bundle: 1.1.*

WebBundle:
* liip/imagine-bundle: ~1.0

That is resolved in:
* symfony-cmf/media-bundle: 1.1.0
* liip/imagine-bundle: 1.2.1

Now the actual problem:
 symfony-cmf/media-bundle: 1.1.0 
requires 
 liip/imagine-bundle: ~0.12
and conflicts with 
 liip/imagine-bundle: >=1.0

What is real result?
```
request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Could not find data loader "cmf_media_doctrine_phpcr" for "slideshow_small" filter type" at /home/www/tests/my_project/vendor/liip/imagine-bundle/Liip/ImagineBundle/Imagine/Data/DataManager.php line 94 {"exception":"[object] (InvalidArgumentException: Could not find data loader \"cmf_media_doctrine_phpcr\" for \"slideshow_small\" filter type at /home/www/tests/my_project/vendor/liip/imagine-bundle/Liip/ImagineBundle/Imagine/Data/DataManager.php:94)"} []
```
Images do not appear cause of exception

**Comment by stloyd** [comment]
@pjedrzejewski @aRn0D This was fixed some time ago...
