### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by antonioperic** [Sylius/Sylius#2262]
I think there will be some translation issues. The first one i found:
- Cannot add new shipping method: "Please enter shipping method name."

I will try to test this more today, and update this list. Please update this list if you find any other things.

**Comment by stloyd** [comment]
@pjedrzejewski @antonioperic I guess this was fixed by #2301.

**Comment by stloyd** [comment]
@madc For translating the messages in backend/frontend we use: http://translate.sylius.org/ which is automatically creating PRs with changes from time to time. This issue is not about system messages.

**Comment by stloyd** [comment]
@antonioperic I think this issue is fixed, no?

**Comment by antonioperic** [comment]
@stloyd need to test it? I don't know is latest version on demo site, but if it is then it is not possible to add different titles for shipping methods regarding locale

**Comment by aRn0D** [comment]
ping @antonioperic fixed ?

**Comment by antonioperic** [comment]
@aRn0D yes

**Comment by aRn0D** [comment]
:+1: good !
