### ISSUE TITLE
Filename cannot be empty

### ISSUE THREAD

**Issue by peregrina** [Sylius/Sylius#2269]
Hello, I have just installed sylius in my localhost and I have a problem: when I  called the app_dev.php appears this error:

An exception has been thrown during the rendering of a template ("Warning: file_put_contents(): Filename cannot be empty in C:\wamp\www\sylius\vendor\doctrine\cache\lib\Doctrine\Common\Cache\FilesystemCache.php line 117") in SyliusWebBundle:Frontend:layout.html.twig at line 96.

3 errors:

ERROR - The template "CmfCreateBundle::includejsfiles-ckeditor.html.twig" contains an error: Unable to find file "@CmfCreateBundle/Resources/public/vendor/ckeditor/ckeditor.js". 

ERROR - The template "CmfCreateBundle::includejsfiles-hallo-coffee.html.twig" contains an error: Unable to find file "@CmfCreateBundle/Resources/public/vendor/hallo/src/hallo.coffee". 

CRITICAL - Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Warning: file_put_contents(): Filename cannot be empty in C:\wamp\www\sylius\vendor\doctrine\cache\lib\Doctrine\Common\Cache\FilesystemCache.php line 117") in "SyliusWebBundle:Frontend:layout.html.twig" at line 96." at C:\wamp\www\sylius\vendor\twig\twig\lib\Twig\Template.php line 148

Can somebody help me? Thanks!

**Comment by aRn0D** [comment]
@peregrina Have you still this problem ?

**Comment by FDiskas** [comment]
yes

**Comment by fabricek** [comment]
For the 2nd error you can solve it by doing
To solve the error :

    php app/console cmf:create:init-hallo-devel

clear the cache or remove it as usual and rebuild assets (you'll see now hallo-coffee.js)

    php app/console ca:c --env=prod and php app/console ca:c

    php app/console assetic:dump --env=prod --no-debug

Done ! No more errors for this one.
