### ISSUE TITLE
[Translations] JMS Serializer use public method instead of property

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#2270]
Hi,

Since we are not using `Prezent` for entity translations the properties are moved to a different php class `ProductTranslation` for example. Because of this, the JMS serializer configuration in `Resources/config/serializer` are invalid, since those properties don't exist anymore. Only the public methods like `getName()` exist.

I tried to use `public_method` but that does not seem to work. I think we should create virtual properties for all the translatable fields in order to make it serialize correctly.

Do we need to use virtual properties or does someone have a better idea?

**Comment by adamelso** [comment]
Unfortunately virtual properties in Serializer don't work for unserializing. [There is talk](https://github.com/schmittjoh/serializer/issues/171) of adding functionality for using expressions or paths (like Symfony Forms).

Another solution might be to use [Transformers in Fractal](http://fractal.thephpleague.com/transformers/) and replace the JMS Serializer.

**Comment by pjedrzejewski** [comment]
I vote for going with virtual properties for now. Also, exposing translations collection.

**Comment by michalmarcinkowski** [comment]
Fixed already, for crucial API endpoints.
