### ISSUE TITLE
[SearchBundle] Missing Parameters

### ISSUE THREAD

**Issue by aRn0D** [Sylius/Sylius#2277]
`OrmIndexer::nestedValues` expects one argument but it is called several times with two. cc @agounaris and @peteward

See https://scrutinizer-ci.com/g/Sylius/Sylius/inspections/5922a7ae-d631-40bd-83e9-18a5be6b1028/issues/files/src/Sylius/Bundle/SearchBundle/Indexer/OrmIndexer.php?status=existing&selectedLabels%5B0%5D=2&orderField=path&order=asc#inspectioncomment-427867346

Idem for `ElasticsearchFinder::transformFacetsForPresentation`

See https://scrutinizer-ci.com/g/Sylius/Sylius/inspections/5922a7ae-d631-40bd-83e9-18a5be6b1028/issues/files/src/Sylius/Bundle/SearchBundle/Finder/ElasticsearchFinder.php?status=existing&selectedLabels%5B0%5D=2&orderField=path&order=asc#inspectioncomment-427867336

**Comment by aRn0D** [comment]
@agounaris Did you have a loock to that ?

**Comment by michalmarcinkowski** [comment]
SearchBundle was removed so it's no longer valid.
