### ISSUE TITLE
Deleted Users details in Administration

### ISSUE THREAD

**Issue by neok** [Sylius/Sylius#2286]
Create new user in /administration/users/new then delete it.
Go to administration/users/?deleted=1 (show deleted) and click on Details of deleted user:
```
An exception has been thrown during the rendering of a template ("Requested user does not exist.") in SyliusWebBundle:Backend/User:show.html.twig at line 122.
```

**Comment by pjedrzejewski** [comment]
Thanks for reporting, fixed in 2bd080d.
