### ISSUE TITLE
following the ddd + cqrs + event sourcing convention

### ISSUE THREAD

**Issue by parweb** [Sylius/Sylius#2291]
if you don't know what i mean you should view this https://www.youtube.com/watch?v=JHGkaShoyNs
;)

**Comment by pjedrzejewski** [comment]
I like these concepts a lot and we will try to follow it in 1.0 where possible (mostly new code) but full adoption is a great idea for 2.0 in the future. Thanks for suggestion! :) I added this to 2.0 ideas notebook and will close this issue.
