### ISSUE TITLE
Is there zip version of the project, installation is too complex

### ISSUE THREAD

**Issue by fazliddin** [Sylius/Sylius#2292]
Where can I get zip version of the whole project which includes all depedencies?
I tried `composer.phar create-project sylius/sylius-standard -s dev`, but after waiting
two hour it began to ask my github account password and ended with errors.

Cloning `https://github.com/Sylius/Sylius.git` and running `composer update` also
did not work. It says `PHP Fatal error:  Class 'Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle' not found in /var/www/vhost/testdrive/Sylius/app/CliKernel.php on line 30`.

I just wanted to look code and database structure, and test, but did not expect such
complexity.

**Comment by kurakin-oleksandr** [comment]
Did you try "Download Zip" in Sylius' guthub home page (https://github.com/Sylius/Sylius)?

**Comment by kayue** [comment]
It won't download the dependencies.

`composer install` is the recommended way to do this.

**Comment by fazliddin** [comment]
Do you mean `https://github.com/Sylius/Sylius.git` and `composer install`

**Comment by kayue** [comment]
yes.

**Comment by elliot** [comment]
To get around the password issue, go to your GitHub [Applications](https://github.com/settings/applications) settings page and create a personal access token, then run

```composer config --global github-oauth.github.com <TOKEN>```

Make sure you're also running an up-to-date build of composer (```composer self-update```) as there was some recent changes made that vastly reduce the amount of time taken to install deps.

**Comment by fazliddin** [comment]
Yes, elliot, I found this on internet, and it solves problem.
This problem solution must be included in troubleshooting section for installation page.
Because Sylius depend on too many packages.

But afterwards running `php app/console sylius:install` gives error `Extension intl does not exist`.
As I state, project must include zip version of whole code as alternative to composer method.
And project must have web based installation like Joomla.

**Comment by kayue** [comment]
Intl is a PHP extension, requirement of Symfony.

At the current stage Sylius is no where near Joomla...

**Comment by fazliddin** [comment]
I see

**Comment by antonioperic** [comment]
cc @pjedrzejewski this should also be closed
