### ISSUE TITLE
Country::__toString() must return a string value

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius#2293]
After updating to `0.13.*@dev` I got:

```
Whoops, looks like something went wrong.
1/1 ContextErrorException: Catchable Fatal Error: Method Sylius\Component\Addressing\Model\Country::__toString() must return a string value in vendor/symfony/symfony/src/Symfony/Component/Translation/Translator.php line 205
```

`CountryTranslation.name` is null, I think we should convert to string there:

```diff
--- a/src/Sylius/Component/Addressing/Model/CountryTranslation.php
+++ b/src/Sylius/Component/Addressing/Model/CountryTranslation.php
@@ -36,7 +36,7 @@ class CountryTranslation extends AbstractTranslation implements CountryTranslati
 
     public function __toString()
     {
-        return $this->name;
+        return (string) $this->name;
     }
 ```

Same on other places, right?

**Comment by inspiran** [comment]
@umpirsky did you manage to load the standard fixtures with the new translatable component?  Got an Column 'translatable_id' cannot be null  error while loading products.

**Comment by umpirsky** [comment]
@inspiran Yes, after migrating data it works. Looks like there is no case in regular circumstances when this can be null.

**Comment by axelvnk** [comment]
I got this when I moved to production environment where the intl extension wasn't updated. And I had to use 'en' as locale. So en_US was unavailable and the countries that were available were only translated into that locale. 

I guess in normal circumstances this doesn't happen, but that why they are called Exceptions, no? :D

**Comment by Symfomany** [comment]
Look your your sylius_locale in your parameters... Control your __toString()....
