### ISSUE TITLE
[RFC][SearchBundle] Indexing changes and Translatable content

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#2305]
Product Translations have highlighted a couple of problems with the SearchBundle that need addressing and we need some feedback about the best solution to propose for Sylius. 

The SearchBundle has been written to allow simple configuration of what you want to index:

```
sylius_search:
    orm_indexes:
        product:
            class: %sylius.model.product.class%
            mappings:
                id: ~
                name: ~
                description: ~
```

You specify your model to index from and the mappings define the searchable content to put into the search engine. This content can be accessed from relations using the PropertyAccessor, giving it some reasonable out-of-the-box flexibility. 

This ORM configuration was modelled to be similar to the FOSElastica bundle's way of configuring automatic indexing of ORM entities. FOSElastica also has a Listener on postFlush() to look for changes to your defined entity and index it to your search engine. We copied this approach with the ORM Indexer for a drop-in pattern that other search engines could use. However, with a more complex catalogue model we found this listener too simplistic in our own project as it cannot consider updated relations and so we used an alternative approach.

Translations have accentuated this problem as if either of the above are now changed, they are changed in the ProductTranslation model and will not fire the Listener on the Product model (so changes will not be indexed). This is a very obvious flaw but it extends beyond this - what if you rename an Option or Attribute? again, these won't be indexed, only if the Product itself is flushed will any changes automatically propagate to the search engine. In our case there are many, many more relations which if updated will leave our search content stale.

There are a couple of solutions that we have discussed as the best way forward to ensure your search content is as closely synchronised as possible:

**1). Extending the listener so that it can handle relations.**
* This is complex. You need to define all of the relations that could be required (making the config definition more complex and ugly).
* This listener would then need to access all related Products should you change a related Attribute for example. 
* There are then dangers of how or when indexing could be triggered on large-scale applications if relation belong to many products. If you changed an attribute that was used by 75% of your 100,000 product catalogue that is being indexed in 7 different languages... it's going to be a very slow page load!
* Although this approach ensures immediate content updates in the search engine, there is a lot of complexity and risk involved. 

**2). We abandon the listener approach and go for full catalogue reindexing on a regular basis.**
* This is how we have chosen to deal with this issue in our project, It is a brute force approach but removes a lot of the complexity.
* We would improve the generic indexer to flush all content updates directly to the search engine.
* It is more robust, although less elegant and has a downside of a short delay in search content updates.
* It also requires a scheduled task to be setup for regular search engine indexing (although you have to index at least once to start with anyway so it's not that much of a stretch to run a task...).
* We're in favour of this approach.
* If we were to go for this approach we might consider removing FOSElastica and using the native Elastica library since the ease-of-use that FOSElastica provides to get something simple off the ground now is starting to feel like a hindrance for greater control...

*Does anyone have any other ideas or thoughts on this?*

The other, more obvious, issue introduced by translations is making sure we have correct searchable content for your locale. Currently only the default content is searchable, but we need to ensure that, for example, German content is both returned and searched for when using the German locale.

We propose indexing a separate set of content for each of your defined locales. This is less controversial and more straight forward, so should be simple enough to rework. We've done it with multiple indexes for ElasticSearch here and could do something similar for the ORMIndexer. It does however make option 1 even more complex since you might need to index for multiple locales or just one depending on what has been changed...

**Comment by peteward** [comment]
I'm going to close this one because the SearchBundle needs a rewrite and new approaches to this can be considered at that point. FWIW we went for full re-index regularly due to our complex product model and using Elasticsearch to render full categories with ordering. The complexity of detecting changes for reindexing was prohibitive.

**Comment by pjedrzejewski** [comment]
:+1:
