### ISSUE TITLE
First vagrant up command ends with non 0 exit status due to PHPUnit deprecation via pear.

### ISSUE THREAD

**Issue by tifab** [Sylius/Sylius#2311]
As PHPUnit installation is now deprecated via Pear (cf. https://github.com/sebastianbergmann/phpunit/wiki/End-of-Life-for-PEAR-Installation-Method ) we got an error when executing vagrant up command.

```
==> default: err: /Stage[main]//Php::Pear::Module[PHPUnit]/Exec[pear-PHPUnit]/returns: change from notrun to 0 failed: pear -d preferred_state=stable install  pear.phpunit.de/PHPUnit returned 1 instead of one of [0] at /etc/puppet/modules/php/manifests/pear/mod
ule.pp:115
```

Installation process continues but at the end we got 
```
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

We should now use the composer method installation (It seems it's already added in the composer.json) file. 
Maybe we just need to remove the phpunit from the puppet file in manifest folder.

Thanks!

**Comment by liquorvicar** [comment]
Is the vagrant box still current? We're looking to use Sylius on a few projects and we already use vagrant/puppet so would be interested in using the vagrant box. Can probably help out with a full PRs as well if needed...

**Comment by Ma27** [comment]
I'm currently working on #3544 , but I experienced the same error, so I'll fix it, too.
