### ISSUE TITLE
[RFC] Extract the ImageUploader and related classes from Sylius Core

### ISSUE THREAD

**Issue by adamelso** [Sylius/Sylius#2316]
For my project, I was using my own code that I wrote for managing file uploads with Doctrine, but then I've recently converted this to started using the image uploader, the `Image` model and some code copied from the event listener in my project, though I don't require the whole Sylius Core.

I wonder if it's worth extracting these relevant parts from the Core.

**Comment by stloyd** [comment]
I guess this is related to the RFC created by me some time ago: https://github.com/Sylius/Sylius/issues/1561.

**Comment by adamelso** [comment]
@stloyd Interesting, I missed that one, thanks. I've tried using VichUploaderBundle in the past and had all sorts of issues with it, but things may have improved since.
