### ISSUE TITLE
InvalidConfigurationException: Unrecognized option "0" under "sylius_variation.validation_groups.variant"

### ISSUE THREAD

**Issue by antonioperic** [Sylius/Sylius#2320]
Possible bug:

InvalidConfigurationException: Unrecognized option "0" under "sylius_variation.validation_groups.variant"

Config:

sylius_variation:
    validation_groups:
        variant: ['locastic_sylius']

**Comment by stloyd** [comment]
You should [read documentation](http://docs.sylius.org/en/latest/bundles/SyliusVariationBundle/configuration.html) first :)

```php
sylius_variation:
    validation_groups:
        product:
            variant: ['locastic_sylius']

**Comment by antonioperic** [comment]
@stloyd I miss it. thank you
