### ISSUE TITLE
Payment problems

### ISSUE THREAD

**Issue by Faustry** [Sylius/Sylius#2324]
Hi,
 I have a problem with the checkout. When as a user, I try to buy something, I access to my cart, then follow the step in the checkout, choose my payment method and at the end, if i fail my payment (wrong credit card code for example) , Sylius redirects me to the payment method with a flash message telling me that I failed my purchase. Everything is ok. 
 But now  I success my payment and I am redirected to payment method page and got same flash message telling me that I failed my payment again while it should validate the payment. 
The second time when I successed the payment , the payment is still on 'new' status in administation page. Moreover, the payment is confirmed at the bank and the user is debit. 

Thank you for your help.

**Comment by antipodes1010** [comment]
Hello, 

I am getting the same issue here with one of payment gateways, do we have any update or help on this one? Thanks a lot and really appreciate any help /  information !

**Comment by nicolasricci** [comment]
Which gateway are you using?

**Comment by pjedrzejewski** [comment]
Please reopen if still relevant with new shop.

**Comment by medteck** [comment]
We are having this exact same problem with version 1.8.1

**Comment by Zales0123** [comment]
Hello @medteck, can you tell what payment gateway do you have this problem with?
