### ISSUE TITLE
Product accessor uses attribute presentation instead of its name

### ISSUE THREAD

**Issue by kurakin-oleksandr** [Sylius/Sylius#2330]
I spent some time to investigate why my facets were not displayed. I found this code (is used for creating indexes):

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Product/Accessor/ProductAccessor.php#L54

I think it will be more obvious to use attribute name ( `$attribute->getName()` ) instead of its presentation ( `$attribute->getPresentation()` ) even attribute can have many translations.

**Comment by kayue** [comment]
As far as I know `getName()` is for internal use only. `getPresentation()` is the one user see (and search).

You can index both of course.

**Comment by kurakin-oleksandr** [comment]
Exactly! That is why we should use `getName()`.

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml#L236

In this example `color` is presentation of attribute and not its internal name
