### ISSUE TITLE
[RFC] How are product variant images supposed to be displayed?

### ISSUE THREAD

**Issue by mtthb** [Sylius/Sylius#2332]
I did not find anything related to images in behat scenarii. From what I understand we always display master variant image, but is this always the desired behaviour?

1. On a product page, given that I am looking at a T-shirt available in two colours (let's say red & blue) and that default image for product (master product variant image) is a blue T-shirt.
Shouldn't we display master variant images **and** other variants images?

2. The most surprising behaviour here is on cart summary: when red t-shirt is added to cart, we still display the blue picture. Shouldn't we display **only** variant image here and fall-back to master variant image if necessary (ie no variant image)?

For now, what bother me the most is point 2. What do you think?

**Comment by inspiran** [comment]
Fully agree.  Point 2 is bugging my customer too.

**Comment by kayue** [comment]
I agree.
