### ISSUE TITLE
Product images doesn't work (v. 0.12)

### ISSUE THREAD

**Issue by guglielmobossi** [Sylius/Sylius#2337]
In the "out of the box installation" of Sylius v.0.12 (without fixtures) I can't view product images both in the backend and in the frontend. The url "media/cache/resolve/sylius_..." give me 404.
The media folder has full (777) rights.

Thanks in advance.
Guly

**Comment by stloyd** [comment]
@pjedrzejewski @aRn0D I guess this is not a problem anymore...

**Comment by liviucmg** [comment]
If you are using Nginx and setting expiry headers for your images, this might be the problem: https://github.com/liip/LiipImagineBundle/issues/194#issuecomment-102633092
