### ISSUE TITLE
php app/console sylius:install   error no this file bootstrap.php.cache

### ISSUE THREAD

**Issue by ghongzyb** [Sylius/Sylius#2347]
downloaded code Sylius-master.zip from https://github.com/Sylius/Sylius
$ cd sylius
$ php app/console sylius:install

PHP Fatal error:  require_once(): Failed opening required '/Volumes/OSData2/php2/Sylius-master/app/bootstrap.php.cache' (include_path='.:/Applications/MAMP/bin/php/php5.5.14/lib/php') in /Volumes/OSData2/php2/Sylius-master/app/console on line 15

no this file bootstrap.php.cache?

**Comment by renereed1** [comment]
@ghongzyb 

Did you run composer install?

**Comment by ghongzyb** [comment]
@renereed1 
php composer.phar create-project sylius/sylius -s dev
Failed to download sylius/sylius from source: The process "git clone --no-checkout 'git://github.com/Sylius/Sylius.git' '/Volumes/OSData2/php2/sylius/' && cd '/Volumes/OSData2/php2/sylius/' && git remote add composer 'git://github.com/Sylius/Sylius.git' && git fetch composer" exceeded the timeout of 300 seconds

**Comment by ghongzyb** [comment]
@renereed1 
Can you help me to download （php composer.phar create-project sylius/sylius -s dev）source code and the mail give me zyb_2000505@163.com?  Thanks.

**Comment by renereed1** [comment]
@ghongzyb 

I just installed it using

php composer.phar create-project sylius/sylius -s dev

Give it another try, and see if you get the same error?
