### ISSUE TITLE
Define prices based on current locale

### ISSUE THREAD

**Issue by winzou** [Sylius/Sylius#2353]
Hi,

I may miss something, but as far as I can see there is no way to define a pricing strategy based on the current locale (and defined in local currencies: EUR for locale fr, USD for locale en_US, etc.)

The available ZoneCalculator seems based on the User zone (we can fill it only when the user fills its shipping address), and can't define prices in local currencies (it shows only EUR even for zones like US).

We should have a LocaleCalculator responsible of this.

**Comment by pjedrzejewski** [comment]
:+1:

**Comment by pjedrzejewski** [comment]
This is handled by channels.
