### ISSUE TITLE
Database call in the CurrencyContext constructor

### ISSUE THREAD

**Issue by geoffrey-brier** [Sylius/Sylius#2375]
I have custom cache clearers which are responsible to dump the routes (via fos js routing) and translations (via bazinga js translation) of the application when clearing its cache.

The point is that when calling the `bazinga:js-translation:dump` it fails because the `TranslationDumper` of Bazinga depends on Twig which adds all of its extensions including the CurrencyExtension.

Up till now that seems legit but the `CurrencyExtension` depends on the CurrencyHelper which in its turn has a dependency on the `CurrencyContext`.

Now if you take a look at the `CurrencyContext` of the CoreBundle, you can spot the problem:

```php
public function __construct(
        StorageInterface $storage,
        SecurityContextInterface $securityContext,
        SettingsManagerInterface $settingsManager,
        ObjectManager $userManager
    ) {
        $this->securityContext = $securityContext;
        $this->settingsManager = $settingsManager;
        $this->userManager = $userManager;

        parent::__construct($storage, $this->getDefaultCurrency());
    }

    public function getDefaultCurrency()
    {
        // The line below makes a call to the database, but when no database exists it breaks everything!
        return $this->settingsManager->loadSettings('general')->get('currency');
    }
```

What do you think @pjedrzejewski ? And also, in your opinion, should I override the CurrencyContext to make my code work?

**Comment by egeloen** [comment]
@geoffrey-brier @pjedrzejewski I dig into the same issue. What about moving the initialization of the default currency at runtime instead of at construction time? The drawback will be the `CurrencyContext::defaultCurrency` will only be initialized when we call `getDefaultCurrency`. What do you think?

**Comment by advancingu** [comment]
+1 to remove this construction time dependency. Right now the application can't be run from command line when the settings DB schema isn't correctly loaded.

**Comment by pjedrzejewski** [comment]
Definitely in favor of doing this!

**Comment by pjedrzejewski** [comment]
Should be fixed now.
