### ISSUE TITLE
PHP Fatal error:  Allowed memory size of 891289600 bytes exhausted

### ISSUE THREAD

**Issue by Konafets** [Sylius/Sylius#2382]
The error occurs while installing the standard edition via composer

```
$ composer create-project -s dev sylius/sylius-standard acme
Installing sylius/sylius-standard (dev-master 2315b5ca19b7f2fcbdbf204e8a7964daec1c3953)
  - Installing sylius/sylius-standard (dev-master master)
    Cloning master

Created project in acme
Loading composer repositories with package information
Installing dependencies (including require-dev)
PHP Fatal error:  Allowed memory size of 891289600 bytes exhausted (tried to allocate 32 bytes) in phar:///usr/local/Cellar/composer/1.0.0-alpha9/libexec/composer.phar/src/Composer/DependencyResolver/RuleWatchGraph.php on line 47
...
```

I have 850MB in my php.ini for testing but this can't be the solution. No shared hosting will allow this. It looks more like a infinite loop.

**Comment by gperdomor** [comment]
use "php -d memory_limit=-1 composer.phar create-project -s dev sylius/sylius-standard acme"

**Comment by adamelso** [comment]
Try updating your Composer installation (`composer selfupdate`). There's an issue with Garbage Collection which should be addressed in newer versions of Composer. See https://scrutinizer-ci.com/blog/composer-gc-performance-who-is-affected-too

If you still have the same issue, or you are not permitted to update Composer, can you try running the same command with Garbage Collection disabled?

```bash
$ php -d zend.enable_gc=0 `which composer` create-project -s dev sylius/sylius-standard acme
```

**Comment by stloyd** [comment]
Be sure to __always__ use latest Composer: `composer self-update`.

This is not Sylius issue, and as such should be closed, cause you clearly can notice that Composer is failing, not i.e. missing dependencies of Sylius.

**Comment by stloyd** [comment]
@pjedrzejewski @aRn0D IMO this can be closed...
