### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by geoffrey-brier** [Sylius/Sylius#2386]
Hi there ;)

There is a small problem I came across when deploying a website: the doctrine fixtures bundle and the faker library are required only in dev but are loaded by CliKernel resulting in an error when you want to run a command.

IMO there are 2 ways to fix this, either set them as required, else fix the CliKernel to load the fixtures dependencies only in dev and test environment.

I can provide a PR but I would prefer having your opinion @pjedrzejewski

**Comment by pjedrzejewski** [comment]
There is no CliKernel anymore, I fixed this. :)
