### ISSUE TITLE
Is there anyone who has seen this Sylius working?

### ISSUE THREAD

**Issue by sruj** [Sylius/Sylius#2399]
if yes, tell me which version and on which Symfony distribution. 

I'm trying 3rd day install whatever Sylius bundle and i see all the errors, exceptions exist.

**Comment by pjedrzejewski** [comment]
Sorry master branch has several issue atm, which we are actively fixing, together with improving the installation process.

**Comment by sruj** [comment]
kółko ma wielkie świecące felgi, ale się nie kręci.

Good to know I'm not that dumb, I though Im the only one who don't know how to install it.
