### ISSUE TITLE
Account Address Setting page shouldn't show order addresses

### ISSUE THREAD

**Issue by kayue** [Sylius/Sylius#2403]
In https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Controller/Frontend/Account/AddressController.php#L40

```php
public function indexAction()
{
    $view = $this
        ->view()
        ->setTemplate('SyliusWebBundle:Frontend/Account:Address/index.html.twig')
        ->setData(array(
            'addresses' => $this->getUser()->getAddresses(),
        ))
    ;
    return $this->handleView($view);
}
```

This is display all addresses belongs to the user, including completed order's address. I think it should be changed to something like this:

```
'addresses' => [
    $this->getUser()->getBillingAddress(), 
    $this->getUser()->getShippingAddress()
]
```

Any feedback?

**Comment by stloyd** [comment]
I tend to not agree, i.e. Amazon will show all used adresses in orders you have done, and you can remove them (so in this case that address should just lost relation to user).

IMO current approach is totally correct.

**Comment by kayue** [comment]
@stloyd What you said is a different feature. 

In Sylius's account setting page, beside showing addresses, there is also an edit page. Obviously we cannot allow customer edit a completed order's address.

**Comment by stloyd** [comment]
That's why there are `clones` being used, to prevent such things.

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressingStepType.php#L54

**Comment by warrenlee** [comment]
But the list will become longer whenever you visit the addressing page. Most if not all are duplicates.
But isn't the purpose of this page is to set a default address for when ever you place an order?

**Comment by pjedrzejewski** [comment]
How about implementing AddressComparator and adding new address to the address book automatically only when it is not similar?

**Comment by kayue** [comment]
@pjedrzejewski This could be a new feature. 

Right now the problem is we are allowing people to edit a completed order's address, which is not acceptable. I will submit a patch if you agree

**Comment by pjedrzejewski** [comment]
As Joseph said, we clone the address, so it is not possible to edit an address attached to order already? Are you sure it is the case?

**Comment by kayue** [comment]
The cloned address is still belongs to the user.

In addresses page, it should show only the editable addresses (address that
has no order).
Right now we aren't doing any filtering, we just list
everything $user->getAddresses()

**Comment by pjedrzejewski** [comment]
We do not have the address book and it will be possibly reimplemented down the road, so this is irrelevant now.
