### ISSUE TITLE
Problem overriding StaticContent class

### ISSUE THREAD

**Issue by KrunoKnego** [Sylius/Sylius#2413]
I'm trying to override model StaticContent from ContentBundle but I continuously get error:

"StaticContent' is not a valid document or mapped super class." 

Is this Sylius issue or am I doing something wrong?

**Comment by antonioperic** [comment]
@KrunoKnego ,

do like this:
in Sylius configuration
sylius_content:
    driver: doctrine/phpcr-odm
    classes:
        static_content:
            repository: Sylius\Bundle\ContentBundle\Doctrine\ODM\PHPCR\StaticContentRepository
            model: Sylius\Bundle\CoreBundle\Document\StaticContent

Create Document as in namespace model.
In your Resources/config/doctrine folder: http://take.ms/6ddFR

it should work
