### ISSUE TITLE
Wrong MIME Type returned for CSS files (text/html instead of text/css)

### ISSUE THREAD

**Issue by psyray** [Sylius/Sylius#2421]
Hi,

After updating Sylius to the last version (0.13 taken from github friday 30/09) in my project, i'm facing a non loading CSS file.
Capture of firefox console log :
![bug-sylius](https://cloud.githubusercontent.com/assets/1230954/6000798/e98d1136-aae2-11e4-9c97-5d7d4908ed84.png)

After some investigation I found the problem (thanks to this [post] (https://stackoverflow.com/questions/22331505/custom-content-type-in-symfony2-assetic-phpless) ).

It was a recent modification made by @loevstroem in the main.yml config file (src/Sylius/Bundle/CoreBundle/Resources/config/app/main.yml).

The `stop: true` directive was removed from the `- { path: '^/', stop: true }` line and wass causing this problem.

I tried to put `stop: true` again and everything is working fine, CSS are loading correctly.

I'm using less in my project (leafo/lessphp), and maybe this could be an important thing.

In the stackoverflow post, venimus (last post) said to add a rule to prevent exclude assetic, maybe this could solve the problem ?

Any help is appreciated ;)
Thx

**Comment by loevstroem** [comment]
Seems to be result of bad merge when rebasing the branch. Unless you beat me to it, I'll wrap up a fix later..

**Comment by psyray** [comment]
I let you publish the fix because I don't know what could break or not your API Split PR.
Thanks

**Comment by kayue** [comment]
@psyray I saw this before and I think I fixed it with something like this:

```
rules:
    - { path: '^/(checkout|administration|login)', priorities: ['text/html', 'text/csv'], fallback_format: html }
    - { priorities: ['text/html', 'application/json', 'text/css', 'application/javascript', 'text/csv', '*/*'], fallback_format: html }
    - { path: '^/api', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: true }
    - { path: '^/', stop: true }
```
