### ISSUE TITLE
Order deleting Error

### ISSUE THREAD

**Issue by wingsergey** [Sylius/Sylius#2423]
If i want to delete order system gives me following error:
An exception occurred while executing 'DELETE FROM sylius_address WHERE id = ?' with params [14]:

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (sylius_demo.sylius_order, CONSTRAINT FK_6196A1F979D0C0E4 FOREIGN KEY (billing_address_id) REFERENCES sylius_address (id))

Seems it is like #1988 error. But why we need to delete Address if we delete order?

**Comment by michalmarcinkowski** [comment]
Should be fixed by https://github.com/Sylius/Sylius/pull/4235.
