### ISSUE TITLE
Cannot find OmnipayBridge payment

### ISSUE THREAD

**Issue by a2xchip** [Sylius/Sylius#2425]
## Master branch version 0d015923436bfc9e540aaaaaaaed08d86ff6430a

While installing vendors it can not find OmnipayBridge class and gives error during cache cleaning. 

solution is to add "payum/omnipay-bridge": "0.13.*" to composer.json

**Comment by stloyd** [comment]
Can be closed.

**Comment by makasim** [comment]
The payum dependencies has to be corrected. Right now they are `~0.12` which allows 0.13 version too. 

but Sylius does not compatible with Payum 0.13 yet. It must be set too `~0.12.0` or `0.12.*`

**Comment by stloyd** [comment]
Yeah, I just noticed this problem. Will send PR in next few mins.

**Comment by makasim** [comment]
adding this `"payum/omnipay-bridge": "0.13.*"` solves problems but no one tested Sylius + Payum 0.13 so there could be some other bugs.
