### ISSUE TITLE
Sub-repositories not updating on Github

### ISSUE THREAD

**Issue by advancingu** [Sylius/Sylius#2434]
The Sylius sub-repositories are not properly updating on Github. For example, sylius/product is currently on commit 188e96c from January 5 which doesn't include the latest changes from sylius/sylius. This means that composer won't be able to download the latest code when using individual bundles.

Please make sure the sub-repos are always up to date.

cc @pjedrzejewski

**Comment by advancingu** [comment]
Thanks for pushing an update. Is this automatically done now?
Please also register ``sylius/archetype`` on Packagist so it can be pulled without manually setting up a repo entry.

**Comment by pjedrzejewski** [comment]
Something went wrong with the automatic script and I did not notice! Now it is running properly. :) Registered on packagist as well. I'm testing installation of all bundles/components now. Let's see what we find!

**Comment by pjedrzejewski** [comment]
Thanks for the heads up!

**Comment by gperdomor** [comment]
@pjedrzejewski I Can't install archetype-bundle :(
Problem 1
    - The requested package sylius/archetype-bundle could not be found in any version, there may be a typo in the package name.

**Comment by advancingu** [comment]
Can confirm, archetype repos are not working yet. Workaround for now is to add this to ``composer.json``:

    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/Sylius/SyliusArchetypeBundle"
        },
        {
            "type": "vcs",
            "url": "https://github.com/Sylius/Archetype"
        }
    ],

**Comment by pjedrzejewski** [comment]
Should be fixed now, sorry and thank you for your patience! :)
