### ISSUE TITLE
No "sylius/archetype-bundle" in composer

### ISSUE THREAD

**Issue by criolit** [Sylius/Sylius#2438]
Hi everyone,

Does somebody knows why "sylius/archetype-bundle" is not available via composer? I can't install sylius/product-bundle. Any ideas?

Thanks!

**Comment by advancingu** [comment]
For a workaround, see #2434.

**Comment by criolit** [comment]
Cool, thank you!

**Comment by pjedrzejewski** [comment]
Fixed now! :)
