### ISSUE TITLE
Issue: CMF block bundle, Imagine block not displaying Image in front end (MAC MAMP)

### ISSUE THREAD

**Issue by xingshi** [Sylius/Sylius#2441]
Hi Guys 

I have been struggling with this many days and still couldn't find a solution. After looking into it, my problem is that the image in Imagine block not rendered or "resolved" in front end. I have checked the phpcr notes and my block does saved successfully 

    ROOT:
    cms:
      blocks:
          contact:
          block-1:
          block-2:
          block-3:
          welcome-text:
          ccc:
              image:
                  jcr:content:
      pages:
          terms-of-service:
          about-us:
      menus:
      medias:
      routes:
          terms-of-service:
          about:
            

As you can see, but when I render this block in front end using `{{ sonata_block_render({'name': '/cms/blocks/ccc'}) }}` the image is not showing, instead the image URL rendered is something like `http://sylius:8888/app_dev.php/media/cache/resolve/slideshow_small/cms/blocks/ccc/image`

Does anyone know what is missing or what might cause the problem? 

Thanks 

=============================================================================
This is the original question (not very accurate regarding my issue)

I have an issue regarding the image uploading in content block->Imagine blocks, I can see that it use symfony-cmf  block bundle, every other fields are fine and can be saved but the image, after I saved the block it told me that it is successfully saved and when I checked the log, there was no error either, but the image was not uploaded and couldn't be rendered in front end. Please check below screenshot 
![screen shot 2015-02-08 at 16 07 58](https://cloud.githubusercontent.com/assets/1461468/6095352/c50304d2-afac-11e4-8395-976d4dcbc6ce.png)

In front end, the actual url rendered is http://sylius:8888/app_dev.php/media/cache/resolve/slideshow_small/cms/blocks/test/test/image

but when I check my folders the actual path "/resolve/slideshow_small/cms/blocks/test/test/image" was not even created

I have tried to set the whole project folder to be root owner and 777 permissions, it still wouldn't work. 

Does anyone else have the same issue here? 

Thanks

**Comment by pjedrzejewski** [comment]
These images are stored in the database and cached locally via Imagine. Are you sure you are looking in the right place?

**Comment by xingshi** [comment]
Hi @pjedrzejewski 

Thanks for your response, I am new to Sylius, so I could be wrong. 

I have been looked into this issue these days and what I have found was below 

I can see that the image was successfully stored in database table "phpcr_binarydata". But in front end when I wanted to show this image with `{{ sonata_block_render({'name': '/cms/blocks/tss'}) }}` ('tss' is the imagine block name for my test), the url rendered is "http://sylius:8888/app_dev.php/media/cache/resolve/slideshow_small/cms/blocks/tss/image", I am not sure what is wrong, the cache folder is not there in my local server, so it is not cached at all? is there something wrong with the liip imagine bundle?

Thanks again

**Comment by psyray** [comment]
Hi,

I'm using a fresh install of Sylius and no problem for me.
I can't reproduce your problem.

Try launch `php app/console doctrine:phpcr:repository:init` and see what's happening.

I don't have any resolve part in my  media/cache path.
Directly under cache i have the slideshow_* and sylius_* folders.
I think your problem is here. Investigate this resolve folder, why it was here.

Good luck

**Comment by comemanu** [comment]
same problem.  don't know why the path generated contains "/resolve/" and image is not loaded

@xingshi have you found a solution ?
thx

**Comment by psyray** [comment]
Look at this [post] (https://stackoverflow.com/questions/28252279/symfony2-liipimaginebundle-path-cache-probleme) on stackoverflow, this should resolve your problem.
Let us know if this solves the problem and close your issue if this is the case.
Thx

**Comment by comemanu** [comment]
For me,  my problem is finally resolved , and was not a permission problem as my other thumbnails was well generated. 
I was trying  to use a thumbnail that i set in the config with normal loader (default) so in the context of phpcr Document it wasn't loaded..

I had to specify the right loader ( cmf_media_doctrine_phpcr ) for the filter i was trying to use, in the config.yml : 

liip_imagine:
    filter_sets:
        my_filter:
            data_loader: cmf_media_doctrine_phpcr
            quality: 85
            filters:
                thumbnail: { size: [750, 346], mode: outbound }

@xingshi was not in this situatution because as the exemple given , the filter " slideshow_small "  is already well configured with the right loader by the sandbox..

**Comment by informatico-madrid** [comment]
Hi i am with the same issue: 
In block slidehow:
sonata_block_render(item) or sonata_block_render('name': item.image.id) not working, return empty value.
To show image in firefox and chrome i do 
```
<img src="{{ item.image.id | imagine_filter(filter) }}" alt="{{ item.label }}" /> 
```
But Iternet explorer cant show image. I think becouse wrong content type
I am try comemanu solution but i have yet data_loader: cmf_media_doctrine_phpcr in my filter
Chrome and firefox not problem. But if i go to generate url of image download image. with wrong content type
