### ISSUE TITLE
[RFC] Configure OAuth providers in the backend

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#2445]
Hey folks!

My goal is to remove half of the configuration from the parameters.yml.dist, for most of them it is simple. (thanks to SettingsBundle)

For Payum, @makasim implemented #2215, which is great.

For OAuth we need something like this as well, is it possible @stloyd? Can we contribute such feature to HWIOAuthBundle?

Let me hear your thoughts!

**Comment by kayue** [comment]
Do we have the option to keep it in parameters? 
More friendly to developer, which is the selling point of Sylius.

**Comment by pjedrzejewski** [comment]
If you look at parameters.yml.dist, we have quite a lot of params, what if we add even more payment methods etc. This is not really friendly... Perhaps we can keep the possibility to define defaults in parameters, but end user (administrator) has to be able to change important configs, such as backorders or inventory holding time or Stripe creds from the backend, agree? Same for facebook keys.
