### ISSUE TITLE
[CartBundle] does not come with a default item resolver

### ISSUE THREAD

**Issue by advancingu** [Sylius/Sylius#2446]
A default resolver resides in CoreBundle but there is no explicit dependency on CoreBundle in CartBundle. To properly configure CartBundle it is thus necessary to either build a custom service implementing ``ItemResolverInterface`` or to include CoreBundle. Both aren't great solutions to quickly get up and running with Sylius.

I can think of two possible resolutions:
1. Make ``sylius_cart.resolver`` optional in the configuration.
2. Provide and configure as default in CartBundle, a resolver that simply throws an ``ItemResolvingException`` when executed.

Which one is preferred by the Sylius team? Any better alternatives?

**Comment by michalmarcinkowski** [comment]
CartBundle was merged into OrderBundle.
