### ISSUE TITLE
Access denied when calling API resources in 0.13.0

### ISSUE THREAD

**Issue by criolit** [Sylius/Sylius#2448]
Hi,

I am trying to make a request with token and getting access denied error. My steps:

```
php app/console sylius:oauth-server:create-client --redirect-uri="http://sandbox.sylius/app_dev.php" --grant-type="authorization_code" --grant-type="password" --grant-type="refresh_token" --grant-type="token" --grant-type="client_credentials"
```

as a response I've got secret and public id:

```
public id 2i3hj0xo88g0ok804wgo4gkw0gg88c0kokgc0k04s8sscswgog
secret 21x5hwyo6j40w8woowkc04ogg4gg4owgck4c4o88koogwooss4
```

After that I am requesting an access token:

```
GET /app_dev.php/oauth/v2/token?client_id=1_2i3hj0xo88g0ok804wgo4gkw0gg88c0kokgc0k04s8sscswgog&client_secret=21x5hwyo6j40w8woowkc04ogg4gg4owgck4c4o88koogwooss4&grant_type=client_credentials
```

and I get access token with the type of the token

```
{
"access_token": "Y2UzZTZhZGEyOWYwNTk2NTRiMGIyYThmMWEyZTU4OGIxZGVmYWQyZjE3NDI3MDZiZDQwMjg4Y2Q1OGY0ZDc3Yw",
"expires_in": 3600,
"token_type": "bearer",
"scope": null
}
```

When I am trying to access some API resource like:

```
GET /app_dev.php/api/users/ HTTP/1.1
Host: sandbox.sylius
Authorization: Bearer Y2UzZTZhZGEyOWYwNTk2NTRiMGIyYThmMWEyZTU4OGIxZGVmYWQyZjE3NDI3MDZiZDQwMjg4Y2Q1OGY0ZDc3Yw
```

I am getting:

```
{
"code": 403,
"message": "Access Denied"
}
```

That is also happens on products, orders and others API's
Any clue what is wrong or maybe I am doing something incorrect? Thanks

**Comment by stloyd** [comment]
I'm not sure that OAuth is working correctly at all, and personally I would recommend to use something different like simple API keys etc.

**Comment by michalmarcinkowski** [comment]
You have to have ROLE_API in order to access any resources. 

When you obtain token using client_credentials grant type, you are authorized by OAuth, but you can't access any resources, because you don't have ROLE_API...

The authorization configuration is bad right now, but you can try with password grant type and obtain access token for user with ROLE_API, should work.

**Comment by criolit** [comment]
Yes, it works with "password" grand type and by adding to a target user ROLE_API. Thank you
