### ISSUE TITLE
[ResourceBundle][RFC] - Domain manager Events

### ISSUE THREAD

**Issue by zender** [Sylius/Sylius#2458]
When event is dispatched it will be nice if we have access to configuration object.

EX: ResourceEvent $event->getConfiguration();

**Comment by isometriks** [comment]
To add to this, I always thought it might be nice to have access to the configuration in Twig templates as well. Would make it easier to have a standard CRUD template:

```jina
{% set config = sylius_resource_config() %}
{% block title %}{{ 'sylius.resource.' ~ config.resourceName ~ '.title'|trans }}{% endblock %}
```

I can probably think of a bunch of other uses as well. Maybe even just add it to the request in the KernelControllerListener?

**Comment by pjedrzejewski** [comment]
@isometriks That's the plan for new backend! Generic CRUD templates. :) Regarding ResourceEvent, sounds good as well!

**Comment by aRn0D** [comment]
@pjedrzejewski New backend ?

**Comment by aRn0D** [comment]
@pjedrzejewski Do you work on generic template?

**Comment by michalmarcinkowski** [comment]
See Grids and resource Metadata.
