### ISSUE TITLE
Error on checkout when CheckoutScenario validation fails

### ISSUE THREAD

**Issue by peter-fritchley** [Sylius/Sylius#2464]
If you do not pass the validation needed to use the checkout (in the default case having at least one item in your cart) and you try to access /checkout - you get a ProcessValidatorException.

I would expect that if you access the checkout when you have no items - that you would be redirected back to a pre-defined page (homepage, cart etc) and given an error notice. This scenario could happen to your customers quite innocently if they are part way through the checkout when the cache is cleared for example.

**Comment by michalmarcinkowski** [comment]
Fixed in #6105.
