### ISSUE TITLE
Translation not up to date with crowdin

### ISSUE THREAD

**Issue by psyray** [Sylius/Sylius#2470]
Hi,

Why the sylius project translations not correctly updated with the current version ?

I want to update all the missing translations for french language, but i'm stucked with non-sync datas.

Thanks to update translations strings asap ;)

**Comment by psyray** [comment]
no response ?

**Comment by stloyd** [comment]
@pjedrzejewski @jjanvier Seems like auto-sync script is broken again...

**Comment by DarekTw** [comment]
Is there any progress on this issue?
Is there any way to sync polish translation from crowdin?

**Comment by michalmarcinkowski** [comment]
@DarekTw we fixed auto-sync script, so the translations will be synchronized on a regular basis after we set it up.

Related PR https://github.com/Sylius/Sylius/pull/3367.

**Comment by DarekTw** [comment]
Thanks for quick reply, crowdin works, but some translations are missing, and I cant find them to translate.
For example login page looks like this 
![zrzut ekranu2](https://cloud.githubusercontent.com/assets/5491058/10242718/1ef88232-68f3-11e5-8c2b-6c6499f629d0.png)

**Comment by michalmarcinkowski** [comment]
I see that translation keys has been renamed in Sylius repo and aren't updated on Crowdin... We will try to fix it ASAP. Thanks for reporting this :+1:

**Comment by nakashu** [comment]
@michalmarcinkowski any update with missing translation keys on Crowdin? 
Slovak translation is 100% on Crowdin, but inside the admin area I got 119 missing messages.

**Comment by michalmarcinkowski** [comment]
@nakashu @pamil is working on that. You should see missing translation keys on Crowdin today evening/tomorrow morning :wink:

**Comment by pjedrzejewski** [comment]
Should be fixed by #3433.
