### ISSUE TITLE
error : You are not allowed to access this file.

### ISSUE THREAD

**Issue by maneeshdisodia** [Sylius/Sylius#2475]
i used this link to install : http://docs.sylius.org/en/latest/book/installation.html
installation done and complete. database is done and i can view it in phpmyadmin
but when open my browser, i get  
"You are not allowed to access this file. Check app_dev.php for more information."
to overcome any permission issue i give 777 -R  permission to sylius folder
and again sudo chmod -R 777 app/cache app/logs

please help me out

**Comment by kurakin-oleksandr** [comment]
did you install it locally?

**Comment by maneeshdisodia** [comment]
No...I install this on ec2 instance .

**Comment by kurakin-oleksandr** [comment]
That is why you got this error:
https://github.com/Sylius/Sylius/blob/master/web/app_dev.php#L22

It's allowed only for local running

**Comment by maneeshdisodia** [comment]
so, what should i do to made it work.
please help()

**Comment by kurakin-oleksandr** [comment]
Just comment this two line:
`header('HTTP/1.0 403 Forbidden');
exit('You are not allowed to access this file. Check '.basename(__FILE__).' for more information.');`

**Comment by kurakin-oleksandr** [comment]
close issue if it helps

**Comment by maneeshdisodia** [comment]
its work!!
very very thanks @kurakin-oleksandr 

u made my day...thank you very much
