### ISSUE TITLE
MogoDB and Sylius

### ISSUE THREAD

**Issue by houss2040** [Sylius/Sylius#2476]
Hello, can i configure MondoDb database with Sylius Solution ?

**Comment by kayue** [comment]
Sylius is designed to support different kind of database, but it doesn't have an existing solution for MongoDb. Feel free to contribute.

**Comment by houss2040** [comment]
Thanks for response, if i understand i have to specify type of database when i install Sylius and it will generate all schema  ?

**Comment by kayue** [comment]
Yes. In fact someone has already wrote a ODM driver. 

https://github.com/Sylius/Sylius/tree/master/src/Sylius/Bundle/ResourceBundle/Doctrine/ODM

There is also an option in `sylius.yml`, maybe it is related.

```
# src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
sylius_core:
    driver: doctrine/orm
```

Again I haven't tried it before.

**Comment by houss2040** [comment]
Thanks  , i will see this

**Comment by aRn0D** [comment]
Basic support is implemented in the resource bunde but other e-commerce bundles only support doctrine orm. Every contribution is very welcome !
