### ISSUE TITLE
[RFC] SyliusMailer - Dispatch events

### ISSUE THREAD

**Issue by amenophis** [Sylius/Sylius#2479]
Hi all,
For one of my project, il want to use this bundle, but i need to store sent emails in database.

What do you think about adding a event dispatching aroud this: https://github.com/Sylius/SyliusMailerBundle/blob/master/Sender/Adapter/TwigSwiftMailerAdapter.php#L91

I will dispatch email_sent event with a EmailSentEvent object, which will embed rendered subject, rendered body and recipients.

What do you think about this ?

**Comment by pjedrzejewski** [comment]
Yeah, I wanted to add some events to this bundle definitely. Perhaps we can add these to twig swiftmailer and some generic ones to the Sender class. However, for these in twig swiftmailer, we should use to clear naming... If we want to have generic events in Sender.

**Comment by amenophis** [comment]
Will try to implement somthing tonight.
I would be nice if the twig logic can be extracted inside another adapter and have two steps.

Send > PrepareContentAdapter > EmailSenderAdapter

What do you think ?

@pjedrzejewski ?

**Comment by amenophis** [comment]
Close and continue in PR
