### ISSUE TITLE
[RFC] Behat scenarios

### ISSUE THREAD

**Issue by michalmarcinkowski** [Sylius/Sylius#2498]
I came up with an idea that we can speed up Behat scenarios execution by reducing number of flushes on the database. The main point of interest should be the background, where many objects are created and flush is executed many times instead of one time at the end of a background. IMO it will greatly accelerate the features execution speed.

But, it will not be simple, because:
1. There is no @AfterBackground hook
2. Sometimes objects created in the background depend on each other, so we should introduce some kind of cached array of objects

Maybe you have some better ideas how we should approach the issue?

**Comment by danio1024** [comment]
@michalmarcinkowski I've done something like proposed in point 2 in the application that had performance problems with Behat and didn't have any problems with that. Point 1 is little more complex. You could access background steps defined in given feature from `BeforeStep` hook's scope. So on `BeforeFeature` some flag could be set and when there is a step that does not belong to background steps collection then just flush on the db. That is an ugly way to do it, but may do the job.
