### ISSUE TITLE
Bundle configuration: driver consistency

### ISSUE THREAD

**Issue by mtthb** [Sylius/Sylius#2509]
There is a lack of consistency in bundle configuration.
Some of them have default value for "driver" (excerpt from https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ArchetypeBundle/DependencyInjection/Configuration.php):
```php
$rootNode
            ->addDefaultsIfNotSet()
            ->children()
                ->scalarNode('driver')->defaultValue(SyliusResourceBundle::DRIVER_DOCTRINE_ORM)->end()
            ->end()
        ;
```
While some other don't (excerpt from https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/TaxationBundle/DependencyInjection/Configuration.php):
```php
$rootNode
            ->addDefaultsIfNotSet()
            ->children()
                ->scalarNode('driver')->isRequired()->cannotBeEmpty()->end()
            ->end()
        ;
```

Is this on purpose? If not, maybe should we define a standard behaviour.
Only two bundles define a default value: ArchetypeBundle and TranslationBundle.

**Comment by pjedrzejewski** [comment]
I'd say we could configure doctrine/orm by default for all to make the installation easier. What do you people think?

**Comment by amenophis** [comment]
Think it's the good way. It ease the config as you said !
