### ISSUE TITLE
asort() expects parameter array, null given - SearchBundle - OrmFinder.php

### ISSUE THREAD

**Issue by rapemer** [Sylius/Sylius#2518]
ContextErrorException: Warning: asort() expects parameter 1 to be array, null given in /var/www/public_html/shop/src/Sylius/Bundle/SearchBundle/Finder/OrmFinder.php line 271

following will fix it:

if (isset($calculatedFacets[$name]) && !is_null($calculatedFacets[$name])) {
    asort($calculatedFacets[$name]);
}

**Comment by pjedrzejewski** [comment]
Could you submit this as a fix? Thanks!

**Comment by pjedrzejewski** [comment]
Please see our contributing guide - http://docs.sylius.org/en/latest/contributing/code/patches.html.

**Comment by rapemer** [comment]
ok

**Comment by madc** [comment]
Running into the same issue. Proposed fix solves it.

**Comment by pjedrzejewski** [comment]
SearchBundle is gone.
