### ISSUE TITLE
promotion rule type and action type

### ISSUE THREAD

**Issue by poolerMF** [Sylius/Sylius#2522]
hello

I have a question .. how to get promotion rule type or action type FROM ORDER ?

**Comment by elliot** [comment]
Can you explain what you are trying to accomplish?

If you have an ```Order``` object, you can get the ```Promotion``` with it's rules and actions from ```$order->getAdjustments($type = null)```

Have a look at how [Promotion](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Promotion/Model/Promotion.php) works.

**Comment by poolerMF** [comment]
I'm using old version of SYLIUS(updated for multi vendor) and there is still functions like:

    public function getPromotionAdjustments()
    {
        return $this->adjustments->filter(function (AdjustmentInterface $adjustment) {
            return Order::PROMOTION_ADJUSTMENT === $adjustment->getLabel();
        });
    }

now I see, in actual version of SYLIUS there is one function and PromotionAdjustment is Promotion ..
but finally I found method order->getPromotions(), that I want
