### ISSUE TITLE
Possible issue/bug with roles

### ISSUE THREAD

**Issue by antonioperic** [Sylius/Sylius#2525]
Hi,
I just updated Sylius to latest version and trying to login to administration. First I cleared my db, load fixtures and tried to login. I got access denied to administration then I manually add role for administration but now I cannot access to any section for example:products

http://take.ms/lEC4C

cc @pjedrzejewski

**Comment by elliot** [comment]
Looks like you might need to run the ```app/console sylius:rbac:initialize```` command to initialise the permissions.

**Comment by antonioperic** [comment]
@elliot didn't help

**Comment by kurakin-oleksandr** [comment]
I had to add relation between `sylius_user` and `sylius_role` manually using `sylius_user_role`

**Comment by pjedrzejewski** [comment]
@antonioperic Use sylius:install or just sylius:install:setup to create admin user, I will add commands to add roles etc. It does not use fos:user:roles anymore.

**Comment by stloyd** [comment]
@pjedrzejewski @aRn0D This was fixed by #2553.
