### ISSUE TITLE
Error registering already deleted user during checkout

### ISSUE THREAD

**Issue by Dukecz** [Sylius/Sylius#2537]
If you will delete user through database it remains there marked as deleted. If the user uses same email address to register again during checkout process  UniqueConstraintViolationException is thrown.
I guess it should be either catched and/or checked before and shown as message in register form.

**Comment by michalmarcinkowski** [comment]
It's softdeletable issue. Related problem https://github.com/Sylius/Sylius/issues/1326

**Comment by michalmarcinkowski** [comment]
Fixed in #4009.

**Comment by torinaki** [comment]
I guess it may also happen when guest user use email that already belongs to registered one.
I got during checkout:
```
An exception occurred while executing 'INSERT INTO sylius_customer (email, email_canonical, first_name, last_name, birthday, gender, created_at, updated_at, phone_number, currency, is_company, company, company_registration_number, company_address, billing_address_id, shipping_address_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [...]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'dmitry.balabka@gmail.com' for key 'UNIQ_7E82D5E6E7927C74'
```

**Comment by michalmarcinkowski** [comment]
@torinaki that shouldn't be the case, have you tried with the newest master?

**Comment by michalmarcinkowski** [comment]
There is even a behat scenario for that [see](https://github.com/Sylius/Sylius/blob/master/features/legacy/frontend/checkout_finalize.feature#L66).

**Comment by torinaki** [comment]
@michalmarcinkowski thank you. More than sure that it's issue of my custom one-step checkout.

**Comment by michalmarcinkowski** [comment]
Please reopen if you find out that something is wrong in Sylius.
