### ISSUE TITLE
[ResourceBundle] Security issue without SyliusRbacBundle

### ISSUE THREAD

**Issue by amenophis** [Sylius/Sylius#2538]
Hi @pjedrzejewski ,
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php#L455 seems to be a security issue if the SyliusRbacBundle is not registrerd.

**Comment by isometriks** [comment]
It basically just does the same thing as before. The security check never existed before the RBAC so this just lets it through like normally. It would have been nice to pass in any role and not just RBAC codes but it doesn't seem to be a security issue

**Comment by isometriks** [comment]
Although I suppose you could default to the symfony security context with something like this:

```php
$permission = $this->config->getPermission($permission);

if ('ROLE_' === substr(0, 5, $permission)) {
    return $this->get('security.context')->isGranted($permission);
}
```

**Comment by pjedrzejewski** [comment]
@isometriks Good idea!

**Comment by isometriks** [comment]
@pjedrzejewski If you want me to make a PR for that I can

**Comment by pjedrzejewski** [comment]
@isometriks Definitely, I'd appreciate! :)
