### ISSUE TITLE
Sylius throw various object managers( multitenancy)

### ISSUE THREAD

**Issue by braisdesousa** [Sylius/Sylius#2539]
I have two objects managers. Default and Nodefault.
Default object manager is handling  a multi-tentant app( different databases) I need to have Sylius in bouth object managers as diferent shops. (From nondefault objectmanager i will shell extensions to clients who will have it's own shops).

I've been looking for this but i've only found a reference to select the object manager in the Resource Bundle, but not in the way I need.

Is there a way to do this, or just point me, to the directon for achieving this. If i'm successfull i will of course share it with the comunity.

**Comment by pjedrzejewski** [comment]
Using different entity managers is not recommended way to handle multi-tenancy. We will hopefully share some idea or code for doing this. Closing for now because we won't support that in core for now.
