### ISSUE TITLE
CSRF security issue in API

### ISSUE THREAD

**Issue by kayue** [Sylius/Sylius#2543]
```
if ($this->config->isApiRequest()) {
  return $this->container->get('form.factory')->createNamed('', $type, $resource, array('csrf_protection' => false));
}
```

https://github.com/Sylius/Sylius/commit/123a9bb8f81a54b3ad1fbf9d68c43f2eb60b22b6#diff-2ea8b7aa90421224fb0d96dd92b4f960R334

In the line above, we are disabling CSRF if it is an API request, which anyone can mock it by setting HTTP header to `Accept: JSON`.

**Comment by aRn0D** [comment]
@pjedrzejewski Perhaps we can split `ResourceController` into two. One controller for the web and the other one for API. Web controller can work with form and the other one just with validator (we don't need form for API).

**Comment by kayue** [comment]
@aRn0D @pjedrzejewski I am using the [JWT](https://github.com/lexik/LexikJWTAuthenticationBundle) approach in my app. JWT is a way to authenticate user with a token (string), perfect for AJAX requests. 

Since all API endpoint is behind a separated firewall, it is allowed to have different set of user roles than the default firewall. So the way I fix this CSRF issue is, always add a `ROLE_API` role in the JWT [authenticate](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Security/Authentication/Provider/JWTProvider.php#L56) process, the result is CSRF is off when `ROLE_API` is set.

**Comment by aRn0D** [comment]
@kayue yes, we can do the same with FOSRestBundle!

**Comment by elliot** [comment]
Spree also had a similar problem, as discovered by Egor Homakov.

He's got a write up over here: ["Your API Authentication is insecure, and we'll tell you why"](http://sakurity.com/blog/2015/03/04/hybrid_api_auth.html)

**Comment by kayue** [comment]
Thanks for sharing @elliot :+1:

**Comment by michalmarcinkowski** [comment]
Fixed.
