### ISSUE TITLE
Issue when overriding ImagineBlock

### ISSUE THREAD

**Issue by nicolasricci** [Sylius/Sylius#2544]
Hi,

I am having some trouble trying to override the `SyliusContentBundle:ImagineBlock`.

Here are the steps I have followed after going through the documentation.

In my `config.yml`

```yml
sylius_content:
    classes:
        imagine_block:
            form: Zegg\ShopBundle\Form\Type\ImagineBlockType
            model: Zegg\ShopBundle\Doctrine\ODM\PHPCR\ImagineBlock
```

Then in my custom bundle

```php
<?php
namespace Zegg\ShopBundle\Doctrine\ODM\PHPCR;

use Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ImagineBlock as BaseImagineBlock;

class ImagineBlock extends BaseImagineBlock
{
    /**
     * @var string
     */
    protected $subtitle;

.... getters and setters below
```
```php
<?php
namespace Zegg\ShopBundle\Form\Type;

use Sylius\Bundle\ContentBundle\Form\Type\ImagineBlockType as BaseBlockType;
use Symfony\Component\Form\FormBuilderInterface;

class ImagineBlockType extends BaseBlockType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // Add default fields.

        $builder->add('subtitle', 'text', array('required' => false));
    }
```
And finally the PHPCR mapping

```xml
<doctrine-mapping
    xmlns="http://doctrine-project.org/schemas/phpcr-odm/phpcr-mapping"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://doctrine-project.org/schemas/phpcr-odm/phpcr-mapping
    https://github.com/doctrine/phpcr-odm/raw/master/doctrine-phpcr-odm-mapping.xsd"
    >

    <document
        name="Zegg\ShopBundle\Doctrine\ODM\PHPCR\ImagineBlock"
        referenceable="true"
        translator="attribute"
        >

        <field name="subtitle" type="string" translated="true" nullable="true"/>

    </document>

</doctrine-mapping>
```

This results in the following error.

*The form's view data is expected to be an instance of class Zegg\ShopBundle\Doctrine\ODM\PHPCR\ImagineBlock, but is an instance of class PHPCRProxies\__CG__\Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ImagineBlock. You can avoid this error by setting the "data_class" option to null or by adding a view transformer that transforms an instance of class PHPCRProxies\__CG__\Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ImagineBlock to an instance of Zegg\ShopBundle\Doctrine\ODM\PHPCR\ImagineBlock.*

Any idea what I am doing wrong?

Thanks

**Comment by gnsimoes** [comment]
Hi @nicolasricci! Did you solved that issue?
I have the same case and the same error...

Thanks

**Comment by comemanu** [comment]
The same for me, exactly the same error . 
Setting 'data_class' option to null in the form Type doesn't resolve anything as it still says that the form data is "PHPCRProxies__CG__\Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ImagineBlock" ...

@gnsimoes , @nicolasricci  Have you found a workaround since ?

Would be great , thanx.

**Comment by shaunbokes** [comment]
Same here also.

**Comment by comemanu** [comment]
resolve for me. 
It was happening because i was trying to edit a block that i've created before the override process.
So it was not an instance of my class.

I deleted it, create new ones and no problem.

**Comment by kedves** [comment]
Same for me @comemanu . I needed to flush the redis db too.

**Comment by pjedrzejewski** [comment]
Let's close this and see if it occurs again on latest version. Are you guys using Redis for PHPCR?
