### ISSUE TITLE
Product with decimal quantity

### ISSUE THREAD

**Issue by gperdomor** [Sylius/Sylius#2551]
Hi...
What is your opinion about managing decimals on product quantity?
That applies for products which sold by length or weight for example, like 2.3 meters of cloth.

In case that this approach are needed, the changes will be easy at least for OrderBundle and ProductBundle, but not for InventoryBundle because implies change the inventory units approach. Maybe having a decimal value on the inventory unit which represent some kind of quantity of item can be an opcion. In the previous example, 2 inventory units will be created with 1 as quantity value, and a third with 0.3 as quantity value, for represent the decimal quantity of the product...

What do you think?

**Comment by Goutte** [comment]
Decimals, aka floats, are [hard](http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html).
I think you should (that's what I would do) turn the problem around and use _centimeters_ or _grams_ as quantity units. You can then tweak the user interface to render those quantities as floats.

Floats are, more often than not, a Bad Idea ™.
