### ISSUE TITLE
database structure

### ISSUE THREAD

**Issue by rapemer** [Sylius/Sylius#2556]
Some Sylius database tables has bad structure for synchronizations. For example `sylius_product_options` doesn't have AUTO_INCREMENT single PRIMARY KEY, which can cause serious problems with synchronizations between e.g. ERP sync. If you want sync from sylius to ERP only real changes, you can't catch row id, you have to sync every option for that product. It's very bad idea.

I think you should use everywhere AUTO_INCREMENT column at ID and use e.g. UNIQUE(`product_id`, `option_id`).

I hope you will think about it. Every important table should has single AUTO_INCREMENT column Primary Key, cos after some updates it's simple to catch and identify row id.

**Comment by michalmarcinkowski** [comment]
We have `code` field on all entities now, so you should use it for integrations.
