### ISSUE TITLE
[RFC] [TaxonomyBundle] createNew method does not set a root taxon

### ISSUE THREAD

**Issue by axelvnk** [Sylius/Sylius#2557]
Hi there,

I came across an issue in the taxonomy bundle. Not sure wether I should edit the docs for it, or make some code adjustments. 

http://docs.sylius.org/en/latest/bundles/SyliusTaxonomyBundle/taxonomy_and_taxon.html#creating-new-taxonomy-object

Here is stated "To create new taxonomy instance, you can simply call createNew() method on the repository." 

Although this is true, after creating it like this, any taxons added afterwards to the newly created taxonomy, do not appear in the back-end for selection. So I needed to create an empty Taxon, and use setRoot(Taxon $taxon) on the Taxonomy object. After that I was able to properly add other taxons. 

When creating a new taxonomy through the back-end, it automatically does this for you. The taxonomy image you uploaded and see in the overview, is actually the image of the empty root taxon.

I think the most logical thing to do is make sure the createNew method sets an empty root taxon, because I don't think you are able to do this afterwards via the CMS. Or maybe it should be an option, but I think in most (if not all) cases, you would want to create a root taxon.

**Comment by pjedrzejewski** [comment]
Will be fixed in https://github.com/Sylius/Sylius/pull/3480.
