### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by antonioperic** [Sylius/Sylius#2560]
Hi,

I am getting this error

PHP Fatal error:  Call to a member function get() on a non-object in /vagrant/vendor/sylius/sylius/src/Sylius/Component/Translation/Model/AbstractTranslatable.php on line 184

Can anybody help?

**Comment by antonioperic** [comment]
cc @gonzalovilaseca

**Comment by gonzalovilaseca** [comment]
That is because the ``translations`` field in the translatable entity is either not initialised or a wrong value.
I need more info such as how have you defined mapping, your entities etc.

**Comment by antonioperic** [comment]
I am trying to load doctrine:fixtures

**Comment by gonzalovilaseca** [comment]
Standard sylius?or you added some customizations?

**Comment by antonioperic** [comment]
Customization, it is actually integrated with ezPublish 5 
Whcih information you need?

**Comment by gonzalovilaseca** [comment]
Have you extended any base translatable sylius classes? If yes, what's the configuration like?

**Comment by antonioperic** [comment]
For example product
    
sylius_product:
    driver: doctrine/orm
    classes:
        product:
            model: Keyteq\Sylius\CoreBundle\Entity\Product

**Comment by antonioperic** [comment]
Yes, override product was problem, didn have translations in construct
