### ISSUE TITLE
[Rbac] How to deal with anonymous users ?

### ISSUE THREAD

**Issue by geoffrey-brier** [Sylius/Sylius#2562]
Hi, 

I'm trying to upgrade my Sylius version and I'm stuck with `SecurityIdentityProvider` throwing an exception because the anonymous user is the string "anon."

```php
// Code in the SecurityIdentityProvider
if (!$user instanceof IdentityInterface) {
    throw new \InvalidArgumentException('User class must implement "Sylius\Component\Rbac\Model\IdentityInterface".');
}
``` 

Am I missing something ?

**Comment by pjedrzejewski** [comment]
@geoffrey-brier You can disable security in routing under ``_sylius`` node with ``permission: false``. Let me know if that helps!

**Comment by geoffrey-brier** [comment]
Forgive me @pjedrzejewski but I'm not really sure which file I need to modify. Is it the `security.yml` ?

**Comment by geoffrey-brier** [comment]
@pjedrzejewski I just got what you mean, my bad! It was indeed coming from the fact that I overrode the sylius.yml file but did not updated it accordingly?

Thanks again @pjedrzejewski !

**Comment by pjedrzejewski** [comment]
Great! :)

**Comment by kurakin-oleksandr** [comment]
How about default route "sylius_static_content_show"? I also get the same error here

**Comment by pjedrzejewski** [comment]
I think route is configured under ``sylius_core.routing`` node in sylius.yml.

**Comment by kurakin-oleksandr** [comment]
No, This route is configured in `WebBundle/Resources/config/routing/frontend/static_content.yml`

**Comment by kurakin-oleksandr** [comment]
Can you reopen this issue?
