### ISSUE TITLE
Attribute value translation?

### ISSUE THREAD

**Issue by nicolasricci** [Sylius/Sylius#2563]
Hi,

My question is maybe stupid but I don't see at the moment any way to translate attribute values? 

Am I missing something?

Thanks

**Comment by pjedrzejewski** [comment]
@nicolasricci Not yet implemented, but on its way. :)

**Comment by nicolasricci** [comment]
great will it be released with v0.14? I am keen to help if I can on features. Let me know what I can do to help

**Comment by nicolasricci** [comment]
@pjedrzejewski I have seen the decoupling of translations in #2519 which looks great but I still don't see how the AttributeValue model is going to be translatable? Should not it be added in the AttributeBundle configuration?

**Comment by nicolasricci** [comment]
@pjedrzejewski any update on this?

**Comment by nicolasricci** [comment]
ping @pjedrzejewski 
can you let me know if there is anything currently in progress for this feature or I will prepare a PR in the next coming days?
thanks

**Comment by tristanbes** [comment]
Any update on this ? Should this ticket be assigned to a future release ?

**Comment by michalmarcinkowski** [comment]
The attributes will be reworked as well as translations, so it will be fixed in one or the other PR.

**Comment by pjedrzejewski** [comment]
Ref. #3422.

**Comment by asiermarques** [comment]
Is this feature request discarted for this release? 

I really miss this feature.
