### ISSUE TITLE
[RFC][ResourceBundle] Behat context

### ISSUE THREAD

**Issue by aRn0D** [Sylius/Sylius#2568]
DefaultContext is still tighted to Sylius application (it should not...)

* The method `getConfiguration()` is not generic.
* `getRepository()` try to find the service `sylius.repository.resource`
* generatePageUrl() prefixes all routes by `sylius`

The two last points can be fixed by a using a attribute `$applicationName` like the `AbstractResourceExtension`

Some useful methods (from the WebContext) are generic and they should be moved a new context in the resource bundle. Method like `iShouldBeOnThePage`, `iAmOnThePage` or `textShouldAppearOnThePage` for example.

@Sylius/core-team What do you think ?

**Comment by umpirsky** [comment]
I noticed this a while ago. Thanks for raising it. :+1:
