### ISSUE TITLE
[RFC][ResourceBundle] Assign extra data to template

### ISSUE THREAD

**Issue by aRn0D** [Sylius/Sylius#2569]
It would be useful to know the name of the current resource and action. Why? automatize some basics tasks. For example, generate the title of the current page. If you know the action and the resource name, you can easy build a translation key `{{ (resource ~ '.' ~ action) | trans }}` and use it in your layout instead your action template.

@Sylius/core-team What do you think ?

**Comment by aRn0D** [comment]
For the create and update action, we can cal

**Comment by isometriks** [comment]
:+1: How were you planning to do it? I had thought to do this through a twig extension to get maybe `{% set config = sylius_resource_config() %}` although would this possibly get messed up for sub-requests?

**Comment by aRn0D** [comment]
For Now, I just want to talk about it. We could assign them from the `ResourceController` or use events

**Comment by aRn0D** [comment]
@Sylius/core-team feedback ?

**Comment by gperdomor** [comment]
@aRn0D I like it... A practical use, for listings of records, might be have a common template with the auto-translated messages for titles, subtitles, even actions, and multiple templates (one for each resource) which extends the common template and override the table records list.

**Comment by pjedrzejewski** [comment]
Implemented, ``metadata`` is available in all templates.
