### ISSUE TITLE
[RFC] Replace addressing with commerceguys/addressing

### ISSUE THREAD

**Issue by bojanz** [Sylius/Sylius#2570]
Sylius right now has no address validation. The address form and formatted address have the same layout for all countries (meaning that it's slightly or mostly wrong everywhere). When it comes to ecommerce, US-centric address forms are on the top of all lists of customer frustrations, leading to cart abandonment.

So, let's fix that.
# Who am I

Fellow ecommerce developer, maintainer of Drupal Commerce. After struggling with the problem space for a long time, I decided to create the [commerceguys/addressing](https://github.com/commerceguys/addressing) and [commerceguys/zone](https://github.com/commerceguys/zone) libraries to solve this issue across the PHP ecosystem, once and for all. So far, I've spent more than a month full time on research and development.

The Sylius and Drupal Commerce communities don't have the resources to do this work twice, so I'm suggesting to join forces.
# Background

Each country has its own addressing guidelines, mandating which fields are used, in what order, with what labels. Which fields are required, and how postal codes are validated is also a part of those rules.
These rules dictate how the address form is meant to look, and how the address is meant to be validated and formatted.

But where to get those rules for over 200 countries?
They're generally documented in PDF form by the [Universal Postal Union](http://www.upu.int/), but the data is frequently incomplete. It's also missing a good list of subdivisions (adminstrative areas, municipalities for each country). Luckily, Google has created their own [dataset](https://i18napis.appspot.com/address) (for [Android/Chrome needs](https://github.com/googlei18n/libaddressinput)) and made it available under the public domain. This means that we can parse their data, ship it under an MIT license as a part of the library. Since becoming a user of that dataset, I've also documented and reported back [more than 20 issues](https://github.com/googlei18n/libaddressinput/issues), so yay open source.
# The code

So, commerceguys/addressing is:
- The [parsed Google dataset](https://github.com/commerceguys/addressing/tree/master/resources) (and the script that does the parsing).
- The [AddressFormat](https://github.com/commerceguys/addressing/blob/master/src/Model/AddressFormatInterface.php) and [Subdivision](https://github.com/commerceguys/addressing/blob/master/src/Model/SubdivisionInterface.php) model classes & repositories.
- An [Address](https://github.com/commerceguys/addressing/blob/master/src/Model/AddressInterface.php) class, with naming that matches the xAL standard
- [Formatters](https://github.com/commerceguys/addressing/blob/master/src/Formatter/DefaultFormatter.php)
- [Validators](https://github.com/commerceguys/addressing/blob/master/src/Validator/Constraints/AddressFormatValidator.php)
- Symfony Form generation class.

We support locale-specific address formats, allowing China to have one layout when the address is entered in Chinese, and one when it isn't, we also have subdivision translations for official languages (Canadian states in both French and English for example), etc.

Zones are in the separate library, and resemble the Sylius architecture, with the addition of postal code patterns (inclusive/exclusive, with regexp support, as often needed for tax/shipping code)
# Implementation plan
1. Deprecate the sylius/addressing library and bundle.
2. Review the commerceguys/addressing and commerceguys/zone codebase (already partially done by Pawel).
3. Implement a new bundle that registers the formatters/validators in the container, provides doctrine mappings for the Address object. 
4. Complete the Symfony Form generation code, by implementing ajax code that rerenders the address form when the country changes, and swaps lists of subdivisions.
5. Replace the old Address object with the new one, start using the validators/formatters/form generator.

I am assuming that the bundle would live outside of Sylius. I'll need community help on completing it, and making sure it matches Sylius conventions. Who wants to help me?

Note: In this plan Sylius continues to use address formats and subdivisions directly from the library and the loaded JSON files. A next step would be to create a UI for address formats, and import the address formats into DB.
# Future benefits

Adopting commerceguys/addressing and commerceguys/zone also allows Sylius to think about implementing [commerceguys/tax](https://github.com/commerceguys/tax), the tax library now used by FoxyCart and Kong SaaS solutions. But that's a topic for another RFC ;)

**Comment by herodrigues** [comment]
Is this still being developed??

I'd like to contribute

**Comment by bojanz** [comment]
Nobody is working on this AFAIK, so your help would be appreciated.
I've made many improvements to the library in the meantime.

Integrating the data model / validation / formatting would still provide the most gains for the least effort.

**Comment by bojanz** [comment]
Nobody is working on this AFAIK, so your help would be appreciated.
I've made many improvements to the library in the meantime.

Integrating the data model / validation / formatting would still provide the most gains for the least effort.

**Comment by ronlinet** [comment]
I am willing to help too. Do we have any road-map?
