### ISSUE TITLE
Attribute choice ?

### ISSUE THREAD

**Issue by nicolasricci** [Sylius/Sylius#2575]
Hi
I have tried to add an attribute of type "choice" but I don't see how to specify those choices then in the backend. And I have an empty select in the product attribute.

Is it something still in development? There is an unused configuration field in the model. Is it what it is intended for?

Thanks

**Comment by nicolasricci** [comment]
There is a `choices` property missing in the form

see https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Resources/views/Backend/ProductAttribute/_form.html.twig#L7

**Comment by nicolasricci** [comment]
OK mea culpa ... there is in fact an event subscriber in the form that builds the attribute choices from the configuration data ... I am having a look to see how it works and will post further information in this thread later on.

**Comment by aRn0D** [comment]
@pjedrzejewski The js which update dynamically the form seems to not work...

**Comment by nicolasricci** [comment]
yes i just noticed the hidden class on the `property-choices-container`. saving the data works fine though once the form is displayed. 
retrieving them does not work though.
please let us know once the js has been fixed

**Comment by nicolasricci** [comment]
It is creating a bug as well on the product attributes backend
`The options "0", "1", "2" do not exist.`
Configuration saved in database was
`a:2:{i:0;s:7:"value 1";i:1;s:7:"value 2";}`

**Comment by nicolasricci** [comment]
@pjedrzejewski any progress on fixing ths js? 

When saving the attrubute configuration the "choices" parameter is missing as well. 

It should be stored as 

`a:1:{s:7:"choices";a:2:{i:0;s:7:"value 1";i:1;s:7:"value 2";}}`

while it is saving

`a:2:{i:0;s:7:"value 1";i:1;s:7:"value 2";}`

This is working great when adding a product archetype where the attribute is configured but not in edition mode. The javascript does not transform the input text in select.

**Comment by gperdomor** [comment]
please update composer package

**Comment by nicolasricci** [comment]
Reopening this as the attribute value is not retrieved on product edition. 
When adding a choice attribute in edition mode, the input text should be transformed in select with attribute value options as well.
Tested on the latest dev branch.

**Comment by nicolasricci** [comment]
Attribute value is stored as a string and not an array so the following case is wrong in `BuildAttributeValueFormListener`. PR #2674 to fix this

```php
case AttributeTypes::CHOICE:
if (!is_array($attributeValue->getValue())) {
    $attributeValue->setValue(null);
}
```
