### ISSUE TITLE
Sorting products under a taxon

### ISSUE THREAD

**Issue by bwach** [Sylius/Sylius#2576]
Since the default Product:indexByTaxon action is using a finder, it's not taking sorting into consideration therefore we can not use sylius_resource_sort for example. I'd like to ask how to approach this case, should I create another indexAction with taxon in criteria?

**Comment by nicolasricci** [comment]
+1 on this issue. 
I believe this would be achievable by adding an `addSort` to the elasticaQuery in `ElasticsearchFinder` but it would be best if we could use the sylius_resource_sort.

**Comment by nicolasricci** [comment]
@bwach have you made any progress on this?

**Comment by nicolasricci** [comment]
Not sure this is the best approach but in the end I have overloaded the `hydratSearchResults` method from the `SearchIndexRepository` such as

```php
public function hydrateSearchResults($resultSetFromFulltextSearch = array())
    {
        $results = array();
        foreach ($resultSetFromFulltextSearch as $model => $ids) {
            $queryBuilder = $this->em->createQueryBuilder();
            $queryBuilder
                ->select('u')
                ->from($model, 'u')
                ->where('u.id IN (:ids)')
                ->setParameter('ids', $ids);

            foreach ($queryBuilder->getQuery()->getResult() as $object) {
                $results[$object->getPrice()] = $object;
            }
        }

        // how to sort the results
        $this->request->query->get('sort') == 'desc' ? krsort($results) : ksort($results);


        return $results;
    }
```

It did the job for me.

**Comment by lighta971** [comment]
up

**Comment by pjedrzejewski** [comment]
Refers to #2312.
