### ISSUE TITLE
[RFC] Drop support for other templating engines than Twig?

### ISSUE THREAD

**Issue by stloyd** [Sylius/Sylius#2582]
Same way as Symfony 3 is making Twig the only possible default candidate for templating engine, I guess we should consider same for Sylius.

**Comment by aRn0D** [comment]
yep, I am for!

**Comment by patkar** [comment]
And how? Since Sylius uses only Twig, the templating engine of the enduser (the devs who are using Sylius), should decide on their own..

**Comment by kayue** [comment]
If you are not using Twig, you probably are not using Sylius Standard Edition.

I am for aligning with Symfony 3.

**Comment by patkar** [comment]
On my own, I'm using Twig ;) It was a general statement.

I'm interested how you want to drop the support :)

**Comment by pjedrzejewski** [comment]
See my comment in #3258.
