### ISSUE TITLE
[RFC][ResourceBundle] ObjectToIdentifierServicePass

### ISSUE THREAD

**Issue by aRn0D** [Sylius/Sylius#2583]
This compiler pass should be renamed and used to inject the right doctrine object registry in the services. 

@Sylius/core-team What do you think?

**Comment by pjedrzejewski** [comment]
:+1:

**Comment by michalmarcinkowski** [comment]
The issue is no longer valid since `ObjectToIdentifierServicePass` will be removed in https://github.com/Sylius/Sylius/pull/3951.
