### ISSUE TITLE
syslius-standard installation error 'ini_set() session active'

### ISSUE THREAD

**Issue by andrewmclagan** [Sylius/Sylius#2585]
When running `app/console sylius:install` all progresses fine till the `sylius:install:sample-data` command is run and the following error is thrown:

`[Symfony\Component\Debug\Exception\ContextErrorException]
  Warning: ini_set(): A session is active. You cannot change the session module's ini set
  tings at this time`

Across all my `php.ini` files the variable `session.auto_start = 0` is set properly.

I have tried this on multiple environments / servers with the same result.

any ideas?

**Comment by Joostnl** [comment]
I have exact the same problem.. who can help us?

**Comment by andrewmclagan** [comment]
Is it perhaps the current version? Anyone tried an earlier tag?

**Comment by Joostnl** [comment]
Good news. Found a solution that work for me.

Before run the cmd sylius:install. Open app/config.yml and look for:

framework:
    translator:      { fallback: %sylius.locale% }
    secret:          %sylius.secret%
    /****************
    *Other pramaters*
    *****************/
    trusted_proxies: ~
    session:         ~

now change the session as

trusted_proxies: ~
session:
    handler_id:  ~

Run the sylius:install cmd again and your life will never be the same.

Thanks to: San Thapa.

**Comment by michalmarcinkowski** [comment]
PR with fix already opened on Sylius-Standard.
