### ISSUE TITLE
error when create new promotion on shop with 12000 products

### ISSUE THREAD

**Issue by poolerMF** [Sylius/Sylius#2592]
hello

I have shop with more than 12000 products ... when I try to make new promotion, there is error:
```Allowed memory size of 335544320 bytes exhausted (tried to allocate 33554432 bytes) in /vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/ChoiceList/ChoiceList.php line 358```

in another shop with only 7000 products, there is no problem

I'm testing it on sylius version 0.9 ...

can someone test it on actual version of sylius ?

**Comment by michalmarcinkowski** [comment]
The problem is with products select field (it loads all products). We will replace it with autocomplete field after ResourceBundle is reworked.

**Comment by poolerMF** [comment]
ok, thanks for your answer
