### ISSUE TITLE
[LocaleBundle][composer] missing dependency

### ISSUE THREAD

**Issue by mtthb** [Sylius/Sylius#2594]
Composer.json is missing dependency on A2lix/translation-form-bundle.

Used in [LocaleProviderInterface.php](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/LocaleBundle/Provider/LocaleProviderInterface.php).

**Comment by aRn0D** [comment]
@mtthb Yes, you're! Can you send a PR plz ?

**Comment by stloyd** [comment]
@pjedrzejewski @mtthb @aRn0D Can be closed now.

**Comment by aRn0D** [comment]
@yes sir, closed by #2597
