### ISSUE TITLE
[RFC][ResourceBundle] Dependencies

### ISSUE THREAD

**Issue by aRn0D** [Sylius/Sylius#2596]
What do you think about removing the `JmsSerializerBundle` and `BazingaHateosBundle` and putting them as suggestion? By default, the resource bundle has been created to build easily web CRUD, if you want to build a API you just need to add them to your composer.json.

Related PR : 
#2611 (API dependencies)

**Comment by pjedrzejewski** [comment]
:+1:

**Comment by stloyd** [comment]
I guess that if we do that this way, we need to add some check for ApiBundle to throw exception if at least serializer bundle is not enabled (same way we throw that in RBAC bundle when doctrine cache is not enabled).

**Comment by amenophis** [comment]
:+1: agree with @stloyd to check throw exception when needed

**Comment by aRn0D** [comment]
@all I think we should the same with the finite-bundle too

**Comment by amenophis** [comment]
someone work on this ? could take a look

**Comment by aRn0D** [comment]
Related PR : #2611

**Comment by amenophis** [comment]
Addressed in: https://github.com/Sylius/Sylius/pull/2611

**Comment by jrobeson** [comment]
maybe the symfony Serializer component in symfony 2.7 is good enough to use by default over the JMSSerializer, once Sylius supports 2.7
