### ISSUE TITLE
[RFC][ResourceBundle] ObjectToIdentifierType

### ISSUE THREAD

**Issue by aRn0D** [Sylius/Sylius#2601]
This type is used several times by Sylius but it only supports the doctrine orm. It is quite similar to ChoiceResouceType. Perhaps, it should have it as parent?

@Sylius/core-team (especially @winzou ) What do you think ?

**Comment by winzou** [comment]
:+1: 
We just need to make sure that the manager/repository use are compatible with odm and phpcr.

**Comment by pjedrzejewski** [comment]
I would like to have:

* ResourceChoiceType
* ResourceToIdentifierType
* ResourcetoIdentifierHiddenType
* ResourceAutocompleteType

Definitely something we need to do for many use case in and not only in Sylius.

**Comment by michalmarcinkowski** [comment]
Fixed already.
