### ISSUE TITLE
overriding cart validation

### ISSUE THREAD

**Issue by nicolasricci** [Sylius/Sylius#2602]
Hi 

I am trying to override the cart validation and followed the documentation found here http://docs.sylius.org/en/latest/bundles/general/overriding_validation.html 

but it comes back with the following error

```
[ERROR 1845] Element '{http://symfony.com/schema/dic/constraint-mapping}constraint-mapping': No matching global declaration available for the validation root.
```

Here is my validation.xml file

```xml
<?xml version="1.0" ?>

<constraint-mapping xmlns="http://symfony.com/schema/dic/constraint-mapping"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://symfony.com/schema/dic/constraint-mapping
                                        http://symfony.com/schema/dic/constraint-mapping/constraint-mapping-1.0.xsd">
    
    <class name="Sylius\Component\Cart\Model\CartItem">
        <property name="quantity">
            <constraint name="NotBlank">
                <option name="groups">quantity</option>
            </constraint>
            <constraint name="Type">
                <option name="type">hidden</option>
                <option name="groups">quantity</option>
            </constraint>
            <constraint name="Range">
                <option name="min">1</option>
                <option name="groups">quantity</option>
            </constraint>
        </property>
    </class>

</constraint-mapping>
```

Any idea?

**Comment by stloyd** [comment]
Second schema location is invalid.
```xml
<?xml version="1.0" encoding="UTF-8"?>

<constraint-mapping xmlns="http://symfony.com/schema/dic/constraint-mapping"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://symfony.com/schema/dic/constraint-mapping
                                        http://symfony.com/schema/dic/services/constraint-mapping-1.0.xsd">

**Comment by nicolasricci** [comment]
Well spotted thanks !! I will make sure the documentation is updated then.

**Comment by nicolasricci** [comment]
I have tested this a little bit too fast yesterday as I had commented the loading of the validation.xml file in my bundle. I still have the same issue then :(
Any other idea?

**Comment by nicolasricci** [comment]
OK I believe the issue does not come from the constraint mapping declaration itself but the fact that the `Sylius\Component\Cart\Model\CartItem` is somehow not loaded. I have tried the same declarations with a `validation.yml` and here is the error

There is no extension able to load the configuration for "Sylius\Component\Cart\Model\CartItem" (in .../Resources/config/validation.yml). Looked for namespace "Sylius\Component\Cart\Model\CartItem", found none' in vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php on line 333

My mapping info is however correct    

[OK]   Sylius\Component\Cart\Model\CartItem

**Comment by nicolasricci** [comment]
Fixed

**Comment by murnieza** [comment]
When you resolve issue please mention how you did it before closing.
