### ISSUE TITLE
Pricing calculators don't seem to work

### ISSUE THREAD

**Issue by winzou** [Sylius/Sylius#2607]
Hey,

It seems that the pricing calculators don't work.
Calculators like ZoneBased or GroupBased requires a "zones" or "groups" index in the `$context` given to their `calculate` method. But as far as I can see, this context is always empty.

We have:
* views call `sylius_calculate_price(variant)` without the 2nd argument which is our `$context`
* PricingExtension doesn't fill it and calls `PricingHelper($variant, $context)` so `$context` is still empty
* PricingHelper doesn't fill it and calls `DelegateCalculator($variant, $context)`
* DelegateCalculator doesn't fill it and calls `*Calculator($variant, $config, $context)`
* GroupBasedCalculator (for example) doesn't fill it and look for the "groups" index in $context, which doesn't exist, then directly return the default price instead of matching it against the user group.

I'm testing with current master and prices are wrong.

**Comment by nicolasricci** [comment]
+1 on this
It has to be fixed as well in `ItemResolver` where the configuration array is missing as well

`$item->setUnitPrice($this->priceCalculator->calculate($variant, $context));`

**Comment by pjedrzejewski** [comment]
Should be fixed with new shop and cart logic.
