### ISSUE TITLE
[RbacBundle] Dynamically add roles and permissions? 

### ISSUE THREAD

**Issue by aramalipoor** [Sylius/Sylius#2610]
Is there currently a way for a bundle to dynamically introduce new roles, permissions, hierarchy to `RbacBundle`? 

If there is none, what are your suggestions if I want to create a PR for that?

**Comment by aramalipoor** [comment]
@pjedrzejewski /cc

**Comment by stloyd** [comment]
No there is no current way to do that. But I have an idea how to do that, but I don't have enough time to create an prototype...

**Comment by aramalipoor** [comment]
@stloyd Ok, If you can tell me about your ideas around it I may find some free to to implement it maybe ;)

**Comment by aramalipoor** [comment]
@stloyd ping ;)

**Comment by jeffsacco** [comment]
I am in need of this too.  Need to add a role for merchants.

Probably will be working on something.

**Comment by pjedrzejewski** [comment]
@aramalipoor Sorry for getting back to you so late but what do you mean by "dynamic"?

**Comment by michalmarcinkowski** [comment]
Rbac was removed.
