### ISSUE TITLE
[RBACBundle] Posible error on change default permission

### ISSUE THREAD

**Issue by gperdomor** [Sylius/Sylius#2613]
As @pjedrzejewski says in #2481

> You can also change the default permission to something else or disable the security check via routing:
> 
><pre>_sylius:
>     form: sylius_product_prices
>     permission: sylius.product.update_prices</pre>

I have a custom project which uses other bundles like taxonomy for example, i want to configure my project roles and permissions using the <code>myapp.taxonomy.index</code> format, but by default the permission for that resource is <code>sylius.taxonomy.index</code>...

When a tried to change the default permission like mentioned before, using my custom permission <code>myapp.taxonomy.index</code>, i get a 403 exception, because the ResourceController validate the <code>sylius.tanxonomy.myapp.tanxonomy.index</code> instead of my custom permission.

**Comment by pjedrzejewski** [comment]
Taxonomy resource belongs to Sylius, so I think it should stay in the sylius namespace here. Is there any other reason than naming convention on your side?

**Comment by gperdomor** [comment]
No, there is no other reason... In that case, if can't override this behavior, the documentation should be updated to indicate how the parameter works, because the documentation on #2481 seems to be wrong or may be misinterpreted...

**Comment by pjedrzejewski** [comment]
Rbac is gone for now.
