### ISSUE TITLE
[Enhancement][WebBundle] Add to cart AJAX + mini cart summary

### ISSUE THREAD

**Issue by axelvnk** [Sylius/Sylius#2627]
Hi everyone,

For a clients project I felt the need to use AJAX to add products to the cart without having to redirect to the summary everytime. I also made a smaller version of the cart summary, which also updates after every click on an add to cart button. 

This might be a nice addition to the WebBundle and I would love to contribute my code to the project. Here is a short video of the functionality I created. (Still rough around the edges though...)

https://www.youtube.com/watch?v=YEFh1sshdLg

If there is interest in this functionality, I will refactor this and put it inside a Sylius fork, so it's usable for any project.

**Comment by pjedrzejewski** [comment]
Looks really cool and that's the goal for new theme. :) Are you using default cart actions or something more is needed for this to work?

**Comment by axelvnk** [comment]
@pjedrzejewski Currently the default cart actions always redirect to the cart summary page. So I extended the CartController and CartItemController and added practically the same actions but made some changes to have json responses. Also leaving out the redirect to summary and eliminating the flash messages. Otherwise they would be all printed out when the user visits another page.

**Comment by axelvnk** [comment]
Maybe we can first start by adding the ajax friendly actions to both controllers, or work with a boolean in the current actions, like so.

``````
public function removeAction($id, $ajax = null)
{
    if ($ajax) {
        //do something
     }
}

```````
This would not affect current functionality, but only expands the possibilities.

**Comment by amenophis** [comment]
Maybe use API actions that return JSON or XML ?

**Comment by axelvnk** [comment]
@amenophis Not sure if that's necessary, because the only info that is needed from the ajax call is wether or not the data processing was successful (imo). I notify the user when something went wrong and when the action was successful. 

I also make an ajax call to request a rendered template of the mini cart summary after an item is added or removed from the cart. That's how my mini cart stays up to date. I thought this was the easiest way since the grand total needs to get updated as well.

**Comment by amenophis** [comment]
yes, the API could respond 2xx in case of success, or 4xx/5xx in case of error.
Thinks it can be better to implement this functionnality like this.
It would be usefull if you want to build entirely a front with a Javascript framework like angularjs or other.
All server interactions would work in the same way (getProducts, getProduct, addToCart, getCart, ...)

**Comment by axelvnk** [comment]
@amenophis you're right. Would make more sense :)

**Comment by nicolasricci** [comment]
@axelvnk I am really interested by this add to cart AJAX feature! I was going to implement the same kind of thing for a project so it could save me time if you could share it.

**Comment by axelvnk** [comment]
@nicolasricci 

First you need controller actions to which you can post with AJAX. So, for me, I just extended the Sylius CartItemController like this : http://pastebin.com/UWZAkcQF

next, you need to configure Sylius to use YOUR cartitemcontroller instead of the default one like this : http://pastebin.com/LrYHNaUj

You also need controller actions for your ajax cart itself. So you extend the sylius cartcontroller and override it in your config (as we just did for the cartitemcontroller). http://pastebin.com/qDcUdHir

I also made a new CartType form and used that one instead of the default sylius one. http://pastebin.com/JHifnWWq

The only thing left is for you to create some new twig templates for the cart. You COULD use the default sylius cart templates for that :) but they're too wide. You can find them in the WebBundle/Resources/views/Frontend/Cart/.....html.twig Adjust them as you see fit..

Also, Sylius uses its controllers as a service. Some things get injected, like the Configuration.. So you should define your routing for your ajax controller methods like this http://pastebin.com/jBfqtev4

I will probably create a video tutorial on how this all works. I still want to enhance my code btw. Maybe I'll put some work in it and create a pull request

**Comment by nicolasricci** [comment]
@axelvnk thanks for sharing :+1:

**Comment by nicolasricci** [comment]
works like a charm thanks again :+1:

**Comment by michalmarcinkowski** [comment]
@axelvnk Sounds nice! :+1: 

Would be great if you found time to make a PR.

**Comment by axelvnk** [comment]
@michalmarcinkowski I will, maybe I'll find some time next weekend. But I'm thinking the WebBundle's base template needs some changes because the mini-cart will be too wide to fit the current sidebar. Can I improve the WebBundle's base theme first? Maybe I can put the mini-cart in like some sort of pop-up when u click on your cart in the menu bar at the top. Kind of like at www.asos.com

**Comment by michalmarcinkowski** [comment]
That's great! Regarding the frontend, I think you should discuss it with @pjedrzejewski, because as far as I know the new theme is in progress, so there will be many changes in the WebBundle.

**Comment by axelvnk** [comment]
Okay so I haven't gotten around to preparing my code for contribution yet. But I have created a YouTube channel and I'm planning on doing bi-weekly tutorials. I'm starting off with Sylius tutorials only. My first video just got uploaded (https://www.youtube.com/watch?v=SmqvycR6lfQ) some feedback would be great. I hope to do another one next weekend already, about how to get started and all round architecture of Sylius. @pjedrzejewski

**Comment by axelvnk** [comment]
@pjedrzejewski , @michalmarcinkowski , @nicolasricci , @stloyd 

Just to let you guys know I have been working on putting my feature in a standard Sylius setup. Here's what I got so far. 

https://www.youtube.com/watch?v=fh27qTssDhk

I might already commit what I have right now, but the CartBundle and WebBundle are too tightly coupled. Because I am returning a rendered version of the mini-cart via JSON in my CartItemController and CartController actions. So I need to refactor this, so I just return a JSON with the data i need to render my cart, instead of returning a JSON with the rendered html of the cart.

Some extra user feedback is also necessary (front-end work). Like showing the mini cart when a product is added and stuff..

**Comment by nicolasricci** [comment]
good job on both sylius tutorial and ajax cart demo :+1: 
I don't really think you are missing anything on the ajax cart apart, as you mentioned, displaying mini cart when a product is added. Another option would be to have a small animation for the user to understand that the cart has been updated such as the one on http://www.archiduchesse.com. On our project (still in development) we display the mini cart for a few seconds before hiding it.
Hope this helps and keep up the good job

**Comment by axelvnk** [comment]
I don't think it's okay for me to use a template from the WebBundle in the CartBundle. I do that [here] (https://github.com/axelvnk/Sylius/blob/e8fcc55667c195cccfd791494982b9100c1de515/src/Sylius/Bundle/CartBundle/Controller/CartItemController.php) for now in the bottom 2 actions. I'll create the PR and we can still comment on the diff. That way the co-creators can join in in a good way.

**Comment by gonzalovilaseca** [comment]
@axelvnk Do you plan a PR soon? We are having the same requirement but before starting to code it I would like to know if this is going to be added to Sylius soon.
Thanks.

**Comment by axelvnk** [comment]
@gonzalovilaseca hi, im sorry i havent finished it and am very busy at the moment. But be my guest to clone my fork of sylius. It's almost functional, but has some tiny bugs. I also use templates from the webbundle to return rendered in a json response in the cartbundle.. so not very clean because both bundles have to be able to work separately..

**Comment by michalmarcinkowski** [comment]
Should work fine now.
