### ISSUE TITLE
[RbacBundle] Why there are permissions with numeric code?

### ISSUE THREAD

**Issue by aramalipoor** [Sylius/Sylius#2632]
I was playing around with `RbacBundle` and saw that for every permission we have another permission with same data but with a numeric code! And they're all placed under `root` permission.

I don't know, but there might be a problem with merging process of the config!

Really! What are these?!!

![db-screenshot](https://cloud.githubusercontent.com/assets/1164589/6881409/eb671c54-d57b-11e4-9dc6-b2530bcae432.png)

**Comment by pjedrzejewski** [comment]
Haha, that is super weird... Maybe it is bug in initialize command?

**Comment by aramalipoor** [comment]
@pjedrzejewski Yeah weird :dancers: I found that the problem may be with `Configuration` information.
