### ISSUE TITLE
TaxonSelectionType - performance improvment

### ISSUE THREAD

**Issue by vasile-dincuta** [Sylius/Sylius#2644]
Hello

First of all, this is not a bug, everything is working well, but i want to bring into your attention a real situation which on our case transformed into a nasty performance issue. I didn't know where to exactly write this, so i choosed this place.

We are re-developing an existing moto e-commerce website on top of Sylius, and i'm the 'lucky' leader of the team;). We didn't spot this issue until we imported the existing website 'categories' tree on sylius taxons system. 
There are more then 3000 taxons organized as a tree with levels: 
- Vehicle type(Motorcycle, Trike, Scooter, ATV, ...)
  - Bike manufacturer(Honda, Yamaha, ...)
    - Bike Model(BT, DT, FJ, …)
      - Cylinder Capacity
        - Model Type

When you want to create/update a product, the 'TaxonSelectionType' class works with the  'TaxonSelectionToCollectionTransformer' which recursively calls the 'processObjects' method in order to properly transform the taxons into array. The result: over 5000 queries to db :(

My solution is to redesign the multi select field for taxons to an AJAX tree field which extends https://github.com/mar10/fancytree/. I'm not saying that is the best solution, i'm relatively new on symfony, and maybe you will imagine something better.

I just want to bring to your attention this use case and maybe you will take into consideration this for further releases.

Regards.

**Comment by michalmarcinkowski** [comment]
This class does not exist anymore.
