### ISSUE TITLE
[TranslationBundle] Circular reference when LocaleProvider uses a Doctrine repository

### ISSUE THREAD

**Issue by cdaguerre** [Sylius/Sylius#2652]
You get a circular reference exception when implementing a `LocaleProvider ` that uses a Doctrine repository, since the repository depends on the Doctrine connection and the Doctrine connection depends on the listener which in turn depends on the locale provider.
Easy fix would be decoupling compile time metadata listeners from runtime listeners.
Should I make a pull-request?

**Comment by aRn0D** [comment]
@cdaguerre Yes don't be shy sir ;)

**Comment by pjedrzejewski** [comment]
This should be solved now.
