### ISSUE TITLE
[CoreBundle] Adding images to product by URL

### ISSUE THREAD

**Issue by axelvnk** [Sylius/Sylius#2653]
Hi everyone,

I had to create some functionality to add a way of adding images to a product in Sylius. I thought it might be a nice extra and of course i'm willing to share my code. 

The client had a lot of product images on his/her content website already and wanted to use the URL's to these pictures, to quickly add them to the products on the webshop. 

Here's a demo : 
https://www.youtube.com/watch?v=ELr2TCqVkI0

This requires a small adjustment to the ProductVariantType in the CoreBundle and some adjustments in the template.

**Comment by steffenbrem** [comment]
@axelvnk Nice feature, can you create a PR for this? I think more people are looking for this.

**Comment by pjedrzejewski** [comment]
:+1: I'd leave that for a bit later when we have a deeper look at the whole UI of image management. (uploading via input, drag and drop + url)
