### ISSUE TITLE
[RFC] ESI support

### ISSUE THREAD

**Issue by patkar** [Sylius/Sylius#2655]
How is the state of ESI support. When this should be applied? Can we create a Pull Request for it already or should we wait for some specific stability (beta?)?

**Comment by kayue** [comment]
This should be something optional, since it is in the View only.
You can already use ESI in Sylius.

**Comment by patkar** [comment]
Yes, but then I have to replace all template with `render(include(...))` in my own bundle to modify it. I think Sylius should use per default `render_esi(include(...)`, since Symfony can detect if ESI capable proxy is present or not and if not `render_esi` does the same as `render`.

So, Sylius should support it by default, but as optional part. Or by default with the Symfony reverse proxy, so performance for pure PHP runtime may be better as now?

**Comment by patkar** [comment]
Btw. it's not only a thing of the view. Every controller action need proper cache header, if they can get cached long (i.e. the detail view of a page) or should be not (i.e. the price of a product). The proper cache configuration of every site and fragment is important.

**Comment by kayue** [comment]
@patkar +1 on proper cache header in core.

BTW I haven't seen `render(include(...))` before. Do you mean `render(controller(...))`?
`render(controller(...))` is not good for performance, it is not something we should use everywhere, and definitly not a `include` replacement.

**Comment by patkar** [comment]
Sorry, yes, I meant `render(controller(...)` and `render(url(...)`. It's not good for performance, when the fragment is not cached, at least with Symfony HttpCache. To create a good site with fine ESI structure this will become mandatory to use `render_esi(controller(...)`.

**Comment by kayue** [comment]
I think we can make Sylius friendly for implementing ESI by adding better cache header, but I don't think it is the right time to do optimization in the theme. 

PS: Twig cache is an good option to do caching too https://github.com/asm89/twig-cache-extension

**Comment by patkar** [comment]
That's the reason, why I asked for it :) So better wait for new design and almost beta?

I don't like the idea of a twig cache extension. It will never get the performance boost a Varnish. The main pro of a ESI proxy is, cached sites/fragments will never reach Sylius, so no kernel booting, events, etc.

So making controls ESI friendly with cache control, adding fragment controllers and stuff is possible in the moment? It think this is a big task, because aside of controllers all events must be checked, if they have side effects on the content and caching, etc.

**Comment by kayue** [comment]
Rendering a view via controller, instead of Twig include, only makes the code harder to maintain. IMO at the current stage Sylius should avoid extra complexity.

I am fine with adding extra cache header though. Simple change.

Let's wait for @pjedrzejewski's thought... I am not the maintainer here :p

**Comment by gonzalovilaseca** [comment]
Cache headers could also be set for routes instead of having them in the controller. 
I find this way much easier to maintain.

**Comment by pjedrzejewski** [comment]
My current plan is to include FOSHttpCache bundle for start. We tested it on a project and worked really well. The project is using API in 99% of cases but I am pretty sure it does not matter.

**Comment by tristanbes** [comment]
:+1: or FOSHttpCache because they support multiple backend (varnish, nginx)

**Comment by psren** [comment]
see #7777
