### ISSUE TITLE
Bundle Product Type

### ISSUE THREAD

**Issue by aftabnaveed** [Sylius/Sylius#2657]
Hi

Does Sylius currently support Bundle products (please do not confuse it with Symfony Bundles), for instance if I would want want to sell a computer set,   which would have optional RAM HDD etc on discount price, can I create a bundle out of that?

If not, I would like to come up with my own, is there way to extend or add this feature to existing admin panel ?

**Comment by kayue** [comment]
- Sylius doesn't have this feature built in.
- Yes you can write your own. Probably have to extend some classes and override some services.

**Comment by aftabnaveed** [comment]
And how can I do that, can you please guide me in a rigjt direction? I do
see a product interface, but then in Admin I dont see any option for
choosing product type.

Thank you

**Comment by mojzis** [comment]
Looks like something could be acheived with promotions - there is a promotion that adds products to a product.

**Comment by pjedrzejewski** [comment]
Let's keep the discussion in #3415.
