### ISSUE TITLE
[BUG] order over current stock limit?

### ISSUE THREAD

**Issue by nicolasricci** [Sylius/Sylius#2660]
Hi,
It looks like the current stock limit for a product is not checked before adding it to the basket. 
I have managed to add twice the same product to my basket while the current stock is set to 1 and proceed to checkout without any error message. Is there any configuration I am missing there?
Tested on latest 0.14-dev
Thanks for your feedback on this.

**Comment by kayue** [comment]
There is an "Available on demand" in each product, make sure you turn it off first.

**Comment by nicolasricci** [comment]
thnaks @kayue but it is already turned off for this product.
I have managed to reproduce on it on a fresh Sylius v0.13 install. Will try to update to 0.14-dev branch but I have doubt it has been fixed
Backend: 
https://www.dropbox.com/s/pi1wdu5w0doarpc/Screen%20Shot%202015-04-16%20at%2008.47.44.png?dl=0
Frontend:
https://www.dropbox.com/s/7fp4qnjhgee594n/Screenshot%202015-04-16%2008.50.04.png?dl=0

**Comment by nicolasricci** [comment]
OK mea culpa i have found the culprit ... in my parameters.yml I had
`sylius.inventory.backorders_enabled: true`
