### ISSUE TITLE
[Promotion] Make coupon length configurable

### ISSUE THREAD

**Issue by rvanlaak** [Sylius/Sylius#2665]
The public function `CouponGenerator->generateUniqueCode()` has the coupon length [hardcoded in it](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Promotion/Generator/CouponGenerator.php#L67). What about making this configurable via the `parameters` and thereafter via the `settings` module?

**Comment by stloyd** [comment]
There is PR for that already: #2389.

**Comment by Rvanlaak** [comment]
:+1: did search through the issues, but forgot the PRs
