### ISSUE TITLE
[PromotionBundle] sylius_promotion_coupon_to_code not defined as a service

### ISSUE THREAD

**Issue by Rvanlaak** [Sylius/Sylius#2668]
The formType `sylius_promotion_coupon_to_code` is not defined in the config, by which it is not extendable in the way the other FormTypes are. It should be added to the config if I'm right?

Or is this the wrong type to use in my frontend cart?

**Comment by aRn0D** [comment]
You should look at the  `services.xml ` in the `PromotionBundle` I found it 
```xml
        <service id="sylius.form.type.promotion_coupon_to_code" class="%sylius.form.type.promotion_coupon_to_code.class%">
            <argument type="service" id="sylius.form.transformer.promotion_coupon_to_code" />
            <tag name="form.type" alias="sylius_promotion_coupon_to_code" />
        </service>
```

**Comment by Rvanlaak** [comment]
:+1: was initially looking for a way to extend it, in the way entities are configurable via the `%...class%` parameters. But overriding the form entity myself and creating it in my controller myself also solved this.
