### ISSUE TITLE
Possible to return a more meaningful payment error message?

### ISSUE THREAD

**Issue by kayue** [Sylius/Sylius#2678]
Right now Sylius only able to tell whether the payment is successful or not. (by looking at payment state)

Is it possible to return a more meaningful error message back to the user?

/cc @makasim

**Comment by makasim** [comment]
There are two solutions I have in mind:

* Extend current GetStatusInterface with some method for it.
* Create a separate request (GetErrorMessage).

I personally prefer the second one.

**Comment by kayue** [comment]
@makasim Thanks for the feedback. For the 2nd solution, I think you meant a request for extracting error message from payment details. This solution assume all information is available in payment details. Did I get it right?

**Comment by makasim** [comment]
Yes sure,
