### ISSUE TITLE
When we are trying to update a page in cmf 1.2~ (used with sylius) we get a weird error

### ISSUE THREAD

**Issue by antonioperic** [Sylius/Sylius#2682]
When we are trying to update a page in cmf 1.2~ (used with sylius) we get a weird error

ContextErrorException: Warning: strpos() expects parameter 1 to be string, array given in /var/www/sylius/vendor/jackalope/jackalope-doctrine-dbal/src/Jackalope/Transport/DoctrineDBAL/Util/Xpath.php line 50

Stack trace:

http://pastie.org/10106904

Any ideas on how to resolve this? Tried with xdebug and it seems that xpath receives an array value instead of literal but its beyond me why it happens. As with all the issues this worked correctly before and nothing has changed :)

Thanks in advance!

**Comment by pjedrzejewski** [comment]
Should be fixed now.
