### ISSUE TITLE
Homepage loading very slowly on vagrant vm

### ISSUE THREAD

**Issue by liquorvicar** [Sylius/Sylius#2687]
We have set up a custom VM to use with Sylius but we are having issues where the site takes a long time to load (and I mean long, minutes rather than seconds). A regular PHP script on the same VM loads almost instantly likewise does Sylius using the built-in web server in my local PHP. I'm not quite sure where the issue lies but I'm struggling to diagnose the problem as I'm relatively new to Symfony. Looking at the profiler, it looks like Twig is taking most of the time (almost 50 seconds, I've posted a dump below). Might be worth noting that while the page is loading, top on the VM shows pretty constant, high CPU usage by the apache process.

Any ideas?

Rendering Call Graph

main 48572.74ms/100%
└ SyliusWebBundle:Frontend/Homepage:main.html.twig 36894.24ms/76%
│ └ SyliusWebBundle:Frontend:layout.html.twig 36894.11ms/76%
│   └ SyliusWebBundle:Frontend:layout.html.twig::block(title) 125.57ms/0%
│   └ SyliusWebBundle:Frontend:layout.html.twig::block(stylesheets) 889.02ms/2%
│   └ SyliusWebBundle:Frontend:layout.html.twig::block(javascripts)
│   └ SyliusWebBundle:Frontend:layout.html.twig::block(header) 2271.07ms/5%
│   │ └ knp_menu.html.twig::block(root) 4.48ms/0%
│   │ │ └ knp_menu.html.twig::block(list) 4.29ms/0%
│   │ │   └ knp_menu.html.twig::macro(attributes)
│   │ │   └ knp_menu.html.twig::block(children) 4.09ms/0%
│   │ │     └ knp_menu.html.twig::block(item) 1.40ms/0%
│   │ │     │ └ knp_menu.html.twig::macro(attributes)
│   │ │     │ └ knp_menu.html.twig::block(linkElement)
│   │ │     │ │ └ knp_menu.html.twig::macro(attributes)
│   │ │     │ │ └ SyliusWebBundle::menu.html.twig::block(label)
│   │ │     │ └ knp_menu.html.twig::block(list)
│   │ │     └ knp_menu.html.twig::block(item) 1.21ms/0%
│   │ │     │ └ knp_menu.html.twig::macro(attributes)
│   │ │     │ └ knp_menu.html.twig::block(linkElement)
│   │ │     │ │ └ knp_menu.html.twig::macro(attributes)
│   │ │     │ │ └ SyliusWebBundle::menu.html.twig::block(label)
│   │ │     │ └ knp_menu.html.twig::block(list)
│   │ │     └ knp_menu.html.twig::block(item) 1.33ms/0%
│   │ │       └ knp_menu.html.twig::macro(attributes)
│   │ │       └ knp_menu.html.twig::block(linkElement)
│   │ │       │ └ knp_menu.html.twig::macro(attributes)
│   │ │       │ └ SyliusWebBundle::menu.html.twig::block(label)
│   │ │       └ knp_menu.html.twig::block(list)
│   │ └ knp_menu.html.twig::block(root)
│   │ │ └ knp_menu.html.twig::block(list)
│   │ └ knp_menu.html.twig::block(root)
│   │   └ knp_menu.html.twig::block(list)
│   └ SyliusWebBundle:Frontend:layout.html.twig::block(flashes)
│   └ SyliusWebBundle:Frontend:layout.html.twig::block(main) 33521.05ms/69%
│   │ └ SyliusWebBundle:Frontend/Homepage:main.html.twig::block(slideshow_full) 232.48ms/0%
│   │ └ SyliusWebBundle:Frontend:layout.html.twig::block(sidebar) 25635.22ms/53%
│   │ │ └ SyliusSearchBundle::search_form.html.twig
│   │ │ └ SyliusSearchBundle::filter_form.html.twig
│   │ │ └ knp_menu.html.twig::block(root)
│   │ │ │ └ knp_menu.html.twig::block(list)
│   │ │ └ SyliusWebBundle:Frontend/Product:latestSidebar.html.twig
│   │ │ └ SyliusWebBundle:Frontend/Homepage:main.html.twig::block(slideshow_sidebar) 4.92ms/0%
│   │ └ SyliusWebBundle:Frontend/Homepage:main.html.twig::block(content) 7639.88ms/16%
│   │   └ SyliusWebBundle:Frontend/Product:latest.html.twig 100.04ms/0%
│   │     └ SyliusWebBundle:Frontend/Product:macros.html.twig::macro(grid) 53.75ms/0%
│   │       └ SyliusWebBundle:Backend/Macros:alerts.html.twig::macro(info)
│   └ SyliusWebBundle:Frontend:layout.html.twig::block(gallery) 40.05ms/0%
│   │ └ SyliusWebBundle::gallery.html.twig
│   │   └ SyliusWebBundle::gallery.html.twig::block(block)
│   └ SyliusWebBundle::confirm-modal.html.twig 1.47ms/0%
│   └ SyliusWebBundle:Frontend:layout.html.twig::block(footer) 5.22ms/0%
│     └ knp_menu.html.twig::block(root) 1.77ms/0%
│       └ knp_menu.html.twig::block(list) 1.71ms/0%
│         └ knp_menu.html.twig::macro(attributes)
│         └ knp_menu.html.twig::block(children) 1.57ms/0%
│           └ knp_menu.html.twig::block(item)
│           │ └ knp_menu.html.twig::macro(attributes)
│           │ └ knp_menu.html.twig::block(linkElement)
│           │ │ └ knp_menu.html.twig::macro(attributes)
│           │ │ └ SyliusWebBundle::menu.html.twig::block(label)
│           │ └ knp_menu.html.twig::block(list)
│           └ knp_menu.html.twig::block(item)
│           │ └ knp_menu.html.twig::macro(attributes)
│           │ └ knp_menu.html.twig::block(linkElement)
│           │ │ └ knp_menu.html.twig::macro(attributes)
│           │ │ └ SyliusWebBundle::menu.html.twig::block(label)
│           │ └ knp_menu.html.twig::block(list)
│           └ knp_menu.html.twig::block(item)
│             └ knp_menu.html.twig::macro(attributes)
│             └ knp_menu.html.twig::block(linkElement)
│             │ └ knp_menu.html.twig::macro(attributes)
│             │ └ SyliusWebBundle::menu.html.twig::block(label)
│             └ knp_menu.html.twig::block(list)
└ @WebProfiler/Profiler/toolbar_js.html.twig 43.04ms/0%
  └ @WebProfiler/Profiler/base_js.html.twig

**Comment by ARoddis** [comment]
Du you use a nfs share? Thats what usualy helps speeding up VagrantBoxes quite a bit.

But in the case of symfony2 the io-operations of the cache and twig etc are the crux.
Usualy Sylius checks if it is running in a VagrantEnvironment:

 /**
     * @return boolean
     */
    protected function isVagrantEnvironment()
    {
        return (getenv('HOME') === '/home/vagrant' || getenv('VAGRANT') === 'VAGRANT') && is_dir('/dev/shm');
    }

If you changed those "markers" in your box sylius cant guess correctly. Than it want write all the cachefiles to the shared-memory but to disk, which in this case is a fileshare. 

And even worse if THAT is not a nfs-share. ;)

**Comment by liquorvicar** [comment]
We weren't using an NFS share. I have switched the synced folder to NFS and it has dramatically improved performance (now 2-4 secs per request). However, one of our dev team is currently on Windows so as it stands NFS is not an option for our vagrant box (we are trying to cajole him off Windows!). I know that the dev environment is much slower than production but are response times of 2-4 seconds in the expected range for Sylius/Symfony in a dev environment? 

I have manually set the VAGRANT env variable in apache on a non-NFS vm and I'm still seeing request times of 40 seconds plus. It looks like it is using shared memory:
[vagrant@pdqcf vagrant]$ df -h
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/VolGroup-lv_root
                      194G  1.4G  183G   1% /
tmpfs                 504M   13M  491M   3% /dev/shm
/dev/sda1             477M   42M  410M  10% /boot
vagrant-root          1.3T   93G  1.2T   8% /vagrant
etc_puppet            1.3T   93G  1.2T   8% /etc/puppet
tmp_vagrant-puppet_manifests-b9fa23d534f3cc55ba4db0e33f913df0
                      1.3T   93G  1.2T   8% /tmp/vagrant-puppet/manifests-b9fa23d534f3cc55ba4db0e33f913df0
[vagrant@pdqcf vagrant]$ ls -all /dev/shm/sylius/cache/dev/
total 5148
drwxrwxr-x 11 vagrant vagrant     480 May  5 09:54 .
drwxr-xr-x  3 vagrant vagrant      60 May  5 09:53 ..
drwxrwxr-x  2 vagrant vagrant     540 May  5 09:54 annotations
-rw-rw-r--  1 vagrant vagrant  167597 May  5 09:53 appDevDebugProjectContainerCompiler.log
-rw-rw-r--  1 vagrant vagrant 1659138 May  5 09:53 appDevDebugProjectContainer.php
-rw-rw-r--  1 vagrant vagrant  116105 May  5 09:53 appDevDebugProjectContainer.php.meta
-rw-rw-r--  1 vagrant vagrant 1576659 May  5 09:53 appDevDebugProjectContainer.xml
-rw-rw-r--  1 vagrant vagrant  249512 May  5 09:53 appDevUrlGenerator.php
-rw-rw-r--  1 vagrant vagrant  370361 May  5 09:53 appDevUrlGenerator.php.meta
-rw-rw-r--  1 vagrant vagrant  340425 May  5 09:53 appDevUrlMatcher.php
-rw-rw-r--  1 vagrant vagrant  370361 May  5 09:53 appDevUrlMatcher.php.meta
drwxrwxr-x  4 vagrant vagrant     100 May  5 09:55 assetic
-rw-rw-r--  1 vagrant vagrant    7284 May  5 09:53 classes.map
-rw-r--r--  1 vagrant vagrant  264082 May  5 09:53 classes.php
-rw-r--r--  1 vagrant vagrant   23924 May  5 09:53 classes.php.meta
drwxrwxr-x  5 vagrant vagrant     100 May  5 09:54 doctrine
drwxrwxr-x  2 vagrant vagrant      40 May  5 09:52 hateoas
drwxrwxr-x  2 vagrant vagrant      40 May  5 09:52 jms_serializer
drwxr-xr-x 10 vagrant vagrant     220 May  5 10:24 profiler
drwxrwxr-x  2 vagrant vagrant      80 May  5 09:54 sessions
-rw-rw-r--  1 vagrant vagrant   98753 May  5 09:53 templates.php
drwxrwxr-x  2 vagrant vagrant    2280 May  5 09:54 translations
drwxr-xr-x 36 vagrant vagrant     720 May  5 09:56 twig
-rw-r--r--  1 vagrant vagrant     183 May  5 09:54 version_info.json

Any other ideas/suggestions?

**Comment by ARoddis** [comment]
Im using NFS on Windows with not that many problems. (I play World Of Warcraft on windows. ;), otherwise i use linux as well.) 

Try this: 

https://github.com/GM-Alex/vagrant-winnfsd

**Comment by liquorvicar** [comment]
Ah! Thanks for the link. I saw the comment in the docs about NFS not working on Windows but didn't think to explore further. Will try that.

When you say it gets a bit quicker, do you mean 1-2 seconds? Or responses measurable in milliseconds? If the former, is there a best practice for doing css/html tweaking in Symfony? 1-2 seconds might be acceptable for backend work but it could get pretty annoying for frontend devs.

**Comment by ARoddis** [comment]
I usually dont use the normal Symfony2 Assetmanagement. I am more comfortable with a Gulp-Setup, together with autoreload setup:

http://gulpjs.com/
https://github.com/vohof/gulp-livereload

That nearly deminishes the "lag" for frontend developers as well. (I do ALOT of angular.js development myself...never had much problems that way)

I concat all my files to 1 -3 JsFiles and one CSS File. That works rather well.

**Comment by liquorvicar** [comment]
Ok, thanks
