### ISSUE TITLE
[Easy] Better/cleaner solution for extending translatable entities

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#2692]
Hi,

You cannot override a translatable without overriding the `getTranslationClass` method, this is caused because in the translatable class `get_class` is used. Because of this you need to implement this method in every class you extend it.

A better solution would be to use the `get_called_class` method, which binds late and prevents the above  behaviour. I struggled with this issue, it took me two hours to find out I needed to implement the `getTranslationClass` method in my own translatable classes.

See this stackoverflow for an example of what I mean: [Link to SO](http://stackoverflow.com/questions/4274630/get-class-in-static-method-and-inheritance-php)

@pjedrzejewski What do you think, should we change this? It would have saved me a lot of time.

**Comment by aRn0D** [comment]
Related PR #2648
