### ISSUE TITLE
Move TranslationLocaleProvider from the CoreBundle to a component.

### ISSUE THREAD

**Issue by adamelso** [Sylius/Sylius#2693]
After upgrading Sylius (which I'm using Sylius like a library rather than the app), while running my Behat scenarios I was getting the exception:

> Request must be defined. (RuntimeException)

After some digging, I found I was able to fix the problem by registering the contextual TranslationLocaleProvider service:

```xml
<service
  id="sylius.translation.locale_provider.contextual"
  class="Sylius\Bundle\CoreBundle\Locale\TranslationLocaleProvider">
    <argument type="service" id="sylius.context.locale" />
</service>
```

I don't have CoreBundle registered in my Symfony app, but I still ended up registering this class, which makes me think that the class could be moved to a component, or a lower-level bundle. Question being where exactly to move it to (Core? LocaleBundle?).

**Comment by aRn0D** [comment]
I think class can be moved into a component because it is not related to Symfony. I think we should update `TranslationBundle` to explain that too.

**Comment by michalmarcinkowski** [comment]
Should be fixed already. /cc @pamil
