### ISSUE TITLE
Promotion entity broken on dev ResourceBundle

### ISSUE THREAD

**Issue by rvanlaak** [Sylius/Sylius#2698]
After updating `sylius/resource-bundle` the Promotion entity seems to be broken. It can not find its relation with the `rules` anymore:

    Updating sylius/resource-bundle dev-master (ada589b => 3ff5390)
    Checking out 3ff5390905483da17a0d4f31dae6feb80987ca64

Results into:

    [Semantical Error] line 0, col 83 near 'r LEFT JOIN o.actions': Error: Class 
    Sylius\Component\Promotion\Model\Promotion has no association named rules

**Comment by aRn0D** [comment]
have you still got this problem ?

**Comment by Rvanlaak** [comment]
The problem occurs in the `FormType`, where the default `PromotionType` does add the rules and actions as collections.

Did solve it by removing it from my own custom type, and make separate pages for adding rules and actions to a promotion.

```php

public function buildForm(FormBuilderInterface $builder, array $options)
{
    // ...
    $builder->remove('rules');
    $builder->remove('actions');
    // ...
}
```
I'm not using the full Sylius stack, but implemented the `PromotionBundle` into an existing Symfony application. There are some other minor fallbacks I've reported about that :+1:

**Comment by michalmarcinkowski** [comment]
Should be fixed now, please reopen if still relevant.
