### ISSUE TITLE
One of the newest commits to the CMF-Routing-Component breaks "entityrouting" over {{path(entity)}}

### ISSUE THREAD

**Issue by ARoddis** [Sylius/Sylius#2699]
It is commit e10f3f8, which introduces a bug? not shure if intended by the cmf-guys. The Event in the "generate"-method of the DynamicRouter creates a "RouterGenerateEvent"-Event now. Which saves the name of the Event, which in this case is an Object. Than the dispatcher will SET the name to the string provided to the dispatcher, effectively overriding the object, saved in the name-property in the EventInstance.

I think its a bug in the CMF-Routing-Component because the "generate"-method should be able to handle objects in the nameparameters as it is checked everywhere else... 

VersatileGeneratorInterface SHOULD be able to handle objects in the name-parameter.

**Comment by ARoddis** [comment]
See here: https://github.com/symfony-cmf/Routing/issues/137

**Comment by pjedrzejewski** [comment]
Was fixed in CMF.
