### ISSUE TITLE
SyliusGridBundle does not install

### ISSUE THREAD

**Issue by sebheitzmann** [Sylius/Sylius#2701]
I have tried to follow the install instruction like in the doc.

http://docs.sylius.org/en/latest/bundles/SyliusGridBundle/installation.html

But it say that the package doesn't exist. Unable to find it on github too.

Is this bundle still alive ?

Thanks

**Comment by amenophis** [comment]
Hi @sebheitzmann,
SyliusGridBundle is not yet released, so it sounds normal !

@pjedrzejewski Did you have a release date ?

**Comment by aRn0D** [comment]
@amenophis has right, it is not release for now. @pjedrzejewski pushed the doc to tell to the community that he works on it. Looks a the grid branch on the main repo.

**Comment by gperdomor** [comment]
@pjedrzejewski @aRn0D first of all, the grid bundle is amazing, only have one question, i read the documentation but i don't see the posibility to hide an action based on resource data or logged user, for example, if the resource are previously deleted, or the user have no permissions to do delete that resource, the deleted action can't be shown, this apply for custom actions too... Is this contemplated?
