### ISSUE TITLE
Following standard install steps on "app/console sylius:install" hitting fatal error

### ISSUE THREAD

**Issue by paceto256** [Sylius/Sylius#2702]
3/5 [|||||||||||||||||           ]  60%PHP Catchable fatal error:  Method Sylius\Component\Core\Model\Taxon::__toString() must return a string value in /home/paceto/proj/sylius/vendor/friendsofsymfony/elastica-bundle/Transformer/ModelToElasticaAutoTransformer.php on line 139
paceto@paceto-Lenovo-Yoga-2-Pro:~/proj/sylius$ vim /home/paceto/proj/sylius/vendor/friendsofsymfony/elastica-bundle/Transformer/ModelToElasticaAutoTransformer.php

**Comment by paceto256** [comment]
tried to change the locale ... same situation

**Comment by nicolasricci** [comment]
This is linked to a recent PR I have made. I will submit a patch. In the meantime if you want to fix it update the __toString() methods so it returns $this->getValue()
It should fix your issue.

**Comment by paceto256** [comment]
Thank you bro.
I set on the installation steps locale = bg_BG  and it works fine.

**Comment by nicolasricci** [comment]
OK good if you found a workaround, this is still an issue though and I will submit a PR to fix it later on. Thanks for reminding me  about it :)

**Comment by nicolasricci** [comment]
Actually I got it confused with AttributeValue on which I have worked recently ... I will have a look at this Taxon thing though

**Comment by paceto256** [comment]
Sorry taking your time out of the issue context, but in case you know

I recently I translated sylius on Bulgarian here http://translate.sylius.org/project/sylius/bg

Do you know how can I have these translations commited in ./src/Sylius/Bundle/AddressingBundle/Resources/translations/* or at least to download these back to commit locally ?

**Comment by nicolasricci** [comment]
Well there should be an auto-sync with crowdin.
Anything broken @pjedrzejewski @jjanvier?
