### ISSUE TITLE
it says "| sylius.settings.timezone_deprecated |  ERROR!  |"

### ISSUE THREAD

**Issue by mclxly** [Sylius/Sylius#2704]
When I run "app/console sylius:install", it says "| sylius.settings.timezone_deprecated |  ERROR!  |".
Please help.
----------------------------------------------------------------
Step 1 of 4. Checking system requirements.
sylius.settings
+-------------------------------------+----------+
| Requirement                         | Status   |
+-------------------------------------+----------+
| sylius.settings.version             | OK!      |
| sylius.settings.version_recommanded | OK!      |
| sylius.settings.timezone            | OK!      |
| sylius.settings.timezone_deprecated |  ERROR!  |
| sylius.settings.detect_unicode      | OK!      |
| sylius.settings.detect_unicode      | OK!      |
| sylius.settings.short_open_tag      | WARNING! |
| sylius.settings.magic_quotes_gpc    | OK!      |
| sylius.settings.register_globals    | OK!      |
| sylius.settings.session.auto_start  | WARNING! |
+-------------------------------------+----------+

----------------------------------------------------------------
CentOS release 6.6 (Final)
PHP Version 5.5.22
date.timezone	Asia/Chongqing	Asia/Chongqing

**Comment by cordoval** [comment]
did you take a look at the code? https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/InstallerBundle/Requirement/SettingsRequirements.php#L51-L57

**Comment by mclxly** [comment]
@cordoval Thank you for tip.

Solution:
Asia/Chongqing -> Asia/Hong_Kong

Btw. Still curious, "Asia/Chongqing" is not in the list of deprecated timezones.

**Comment by cordoval** [comment]
feel free to PR the php repository :+1: :older_man:
