### ISSUE TITLE
[SettingsBundle] PR #/2685 did not solve the problem. It still requires sylius.cache

### ISSUE THREAD

**Issue by jrobeson** [Sylius/Sylius#2705]
Turns out i still had sylius.cache defined. It looks like the resolution here: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/SettingsBundle/DependencyInjection/SyliusSettingsExtension.php#L68

doesn't pick up on the parameter from the code here: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/SettingsBundle/DependencyInjection/SyliusSettingsExtension.php#L54

I'd suggest reverting #2685 and let's try another way. Any suggestions?

**Comment by aRn0D** [comment]
Fixed 2756, thanks for reporting that issue.
