### ISSUE TITLE
controller exception override from api breaks 404/500 symfony pages

### ISSUE THREAD

**Issue by cordoval** [Sylius/Sylius#2709]
I had to override back again the 

```yaml
twig:
    exception_controller: 'twig.controller.exception:showAction'
```

because @pjedrzejewski set it for the api, the used exception controller is coming from the FOSRestBundle. However I wonder how can we keep both functionalities?

I believe that in the case where the request is http we should act like before and when it is json or other xml for instance we should let the new exception controller from FOSRestBundle act. cc @lsmith77 

any thoughts?

**Comment by lsmith77** [comment]
what advantages does the twig exception controller have over the fos rest bundle exception controller for non json requests?

**Comment by cordoval** [comment]
These is the one symfony uses by default and that is documented. I guess we would do well to find out when to use one or the other or a hybrid.

**Comment by cordoval** [comment]
ping @pjedrzejewski any insight?
