### ISSUE TITLE
[Proposal][AddressingBundle] Remove CountryTranslation and use Intl Component

### ISSUE THREAD

**Issue by gperdomor** [Sylius/Sylius#2710]
Hi, i like to discuss about Country model, right now, countries are created in the Sylius backend, in that creation process, user should add a country name, or many country names depending on configured locales and a iso name. From my point of view, this is not the best way to do that.

Why?...

Simply, users can create countries that not really exist, or create countries with incorrect name or incorrect iso name, for example, a country with name <code>Venezuela</code> and iso name <code>US</code>.

The required changes basically are modify the getName method from Country model, to use Intl Component, delete CountryTranslation.php CountryTranslationInterface.php, CountryTranslation.orm.xml.

I wait comments for prepare a PR if you are agree with this...

**Comment by pjedrzejewski** [comment]
Definitely in favor. :+1:

**Comment by stloyd** [comment]
Yep :+1:

**Comment by aRn0D** [comment]
:+1:

**Comment by gperdomor** [comment]
@pjedrzejewski @stloyd @aRn0D done. Please check the #2720 PR for review :smile:

**Comment by michalmarcinkowski** [comment]
@gperdomor thanks for idea! The change will be applied after https://github.com/Sylius/Sylius/pull/3074 merge.
