### ISSUE TITLE
Can't login to demo administration panel

### ISSUE THREAD

**Issue by kwreczycki** [Sylius/Sylius#2712]
I can't login to administration panel on http://demo.sylius.org/administration/login.
Any ideas what's happend ?

**Comment by jimbocoder** [comment]
+1, it has been like this for a couple months at least!  I asked in IRC but this is probably a better place.

**Comment by Feldgradron** [comment]
Same problem here.

**Comment by jimbocoder** [comment]
@pjedrzejewski I know you guys are busy, but I can't stress enough how important a working demo is.  When trying to sell my employer and clients on the Sylius concept, a demo goes a long way.  If I can help in any way with this, please let me know.  I can set it all up, or even provide hosting.
