### ISSUE TITLE
StateResolver getShippingState() When No Shipments

### ISSUE THREAD

**Issue by GazEdge** [Sylius/Sylius#2718]
Class Sylius\Component\Core\OrderProcessing\StateResolver

When resolveShippingState($order) is called, the shipping state is incorrectly set to 'partially_shipped' if there are no shipments.

Solution is to modify private method getShippingState(OrderInterface $order) to handle case where there are no shipments

Solution 1: Throw exception if no shipments 

    protected function getShippingState(OrderInterface $order)
    {
        $states = array();

        foreach ($order->getShipments() as $shipment) {
            $states[] = $shipment->getState();
        }
        
        if(empty($states)) throw new NoShipmentsFoundException();

        . . . 

Solution 2: Return response 'no_shipments'

    protected function getShippingState(OrderInterface $order)
    {
        $states = array();

        foreach ($order->getShipments() as $shipment) {
            $states[] = $shipment->getState();
        }
        
        if(empty($states)) return OrderShippingStates::NO_SHIPMENTS;

        . . .

**Comment by pjedrzejewski** [comment]
Maybe we should have a state ``not_shippable`` or ``no_shipments``. What do you think?

**Comment by GazEdge** [comment]
yes, I think thats a good idea.

**Comment by michalmarcinkowski** [comment]
Fixed.
