### ISSUE TITLE
Shipping calculations don't support complex return values

### ISSUE THREAD

**Issue by jimbocoder** [Sylius/Sylius#2719]
This is similar to #690 with the same desired feature with a different motivation.

It's sufficient to return a single numeric value with deterministic calculators like `flat_rate`, but many API-based calculators will return additional useful information along with the quoted shipping price.  Things like estimated delivery date, explanation for any additional surcharges, or other notes would be useful to have returned along with the price.

I haven't been able to figure out a clean way of doing this without a backwards-compatibility break, but I'm still rather new to Sylius and Symfony itself.  If a clean strategy could be discussed and proposed I would happily do the groundwork for this feature.

**Comment by kayue** [comment]
Sample respond: https://www.postmen.com/api/v2/rates/post-rates

**Comment by pjedrzejewski** [comment]
Let's continue the discussion in a single issue, please. :) Good idea Jim! @jimbocoder
