### ISSUE TITLE
How to handle "Cash on delivery" with normal payment methods in Sylius projects

### ISSUE THREAD

**Issue by tameribrahim** [Sylius/Sylius#2722]
We're working on an ecommerce website that has different payment options, one of them is "Cash on delivery", in addition to Paypal , How can we handle this?
Is it something that need coding , or just some configuration changes?

**Comment by kayue** [comment]
All the concept is there (payment status in order), so I think this is more of a workflow problem rather than coding. 

Some coding is needed when using Sylius at this stage.

**Comment by tameribrahim** [comment]
Thank you @kayue

**Comment by tameribrahim** [comment]
@kayue Still I couldn't get it, can you give me a push, like where to start?
"Cash on Delivery" as a payment method should has a reference to a payment gateway -which is missing in the docs- , So how to handle this?
Also, I think there's nothing to do with State Machine -also missing in docs-, What I understand is it handles the transitions from<->to , and it's linked with NextStep and PreviousStep in the Payment workflow, Am I right?
Thanks in advance.

**Comment by tameribrahim** [comment]
@kayue  Still I couldn't get it, can you give me a push, like where to start?
"Cash on Delivery" as a payment method should has a reference to a payment gateway -which is missing in the docs- , So how to handle this?
Also, I think there's nothing to do with State Machine -also missing in docs-, What I understand is it handles the transitions from<->to , and it's linked with NextStep and PreviousStep in the Payment workflow, Am I right?
Thanks in advance.

**Comment by kayue** [comment]
@tameribrahim You can use the "dummy" payment gateway for your cash on delivery.

Transition only manage the Order object (states), it doesn't change the checkout flow.
