### ISSUE TITLE
taxon has no permalink

### ISSUE THREAD

**Issue by familie-redlich** [Sylius/Sylius#2732]
Hi,

I see in SyliusCoreBundle:ProductController line 50 
$this->get('sylius.repository.taxon')->findOneByPermalink($permalink);

if i use the default controller it throws an error "has no field 'permalink'

**Comment by nicolasricci** [comment]
Hi,

The permalink belongs now to the Translation entity so this is indeed not working.

Here is the correct method to use

```php
public function findOneByPermalink($permalink)
    {
        return $this->getQueryBuilder()
            ->where('translation.permalink = :permalink')
            ->setParameter('permalink', $permalink)
            ->orderBy($this->getAlias().'.left')
            ->getQuery()
            ->getOneOrNullResult();
    }
```

I will submit a PR for this

**Comment by nicolasricci** [comment]
Done #2733

**Comment by familie-redlich** [comment]
thx works perfect :)

**Comment by pjedrzejewski** [comment]
Thank you for reporting and fixing, you are awesome guys!
