### ISSUE TITLE
Link to view products by taxon is throwing No route found Exception

### ISSUE THREAD

**Issue by liquorvicar** [Sylius/Sylius#2734]
- Fresh install of Sylius (commit: c38485c581007f8f29fd8ba9f02b6d55537d920c). 
- Ran sylius:install and sylius:install:setup but did not load the sample data
- Logged into admin area and created one taxonomy with one root taxon and one child taxon
- Created one product belonging to the child taxon

Expected:
- When I click on the product link from homepage I see the product
- When I click on the child taxon in homepage I see the product

Actual:
- When I click on the product link from homepage I see the product
- When I click on the child taxon in homepage I get the following error:
 No route found for "GET /t//flooring/wood" (from "http://127.0.0.1:8000/app_dev.php/")
404 Not Found - NotFoundHttpException
1 linked Exception:

    ResourceNotFoundException » 
[1/2] ResourceNotFoundException: None of the routers in the chain matched this request
GET /app_dev.php/t//flooring/wood HTTP/1.1

I'm not a Symfony expert but I can see the relevant routes defined in vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml
It looks like it's finding the %sylius.model.product.class% route but not the %sylius.model.taxon.class% route.

Any ideas why? Happy to submit a PR if it is an issue and you can point me in the right direction.

**Comment by liquorvicar** [comment]
It looks like the taxons are created correctly when using the sample data (or our own bespoke fixture data) but not when added through the admin interface.

**Comment by michalmarcinkowski** [comment]
@liquorvicar I remember there was an issue with taxons, that sometimes taxonomy was created without a root taxon, maybe it is somehow connected.

**Comment by liquorvicar** [comment]
That would make sense. I have done a few more tests and I can add a taxon to a taxonomy that I have created via the fixtures and it works fine. However if I add a taxon to a taxonomy I have created through the admin interface then it breaks.

**Comment by liquorvicar** [comment]
I've done a little more digging.

It looks like when adding a taxonomy directly (as in a fixture) a root taxon is created with an entry in sylius_taxon_translation with the relevant name/slug/permalink. When adding a taxonomy via the admin GUI this does not happen. A root taxon is generated but it doesn't have the related entry in the _translation table. From reading the code/debugging, it looks like the fixture set up calls \Sylius\Component\Taxonomy\Model\Taxonomy::setName directly, which sets the name on the root taxon automatically. But when I add a breakpoint here and debug through adding a new taxonomy from the web interface, this method is not called.

I'm not an expert on Symfony but it looks like adding an EventListener to the Taxonomy form would solve the problem. Not sure if that is the best solution though. Will prepare a PR so it can be discussed.

**Comment by jeffsacco** [comment]
Would you happen to have any advice from someone who has currently built a site and is trying to get this fix in place.  I added the code from your patch and still cannot get any routes to pick up for taxons.

Any guidance would be greatly appreciated

**Comment by jeffsacco** [comment]
Actually, I added your code to another copy of symfony than the one I was refreshing in my browser :P

Worked like a charm !!

Good job :+)

**Comment by liquorvicar** [comment]
Glad it worked for you ;-)

Nice avatar...
