### ISSUE TITLE
Custom install process

### ISSUE THREAD

**Issue by liquorvicar** [Sylius/Sylius#2735]
We're working on setting up a custom install for our Sylius app. We've started doing it by just copying the install commands to our AppBundle and editing them to suit our requirements. But obviously this isn't a very future-proof way of doing it as any changes to the core that affect the install process will not be reflected in our commands. Has anyone come up with a better way of doing this?

**Comment by patrick-mcdougle** [comment]
Just extend the functions that you need to extend, and leave the other functions alone. The beauty of OOP!

**Comment by liquorvicar** [comment]
Not sure that really helps. We were looking to customise \Sylius\Bundle\InstallerBundle\Command\InstallCommand bu removing the setup stage and adding our own fixtures setup to the end of the process. I'm not sure extending that class is really a better way of doing it (especially as I try to avoid inheritance unless it's absolutely necessary). My main concern is that if there are steps added to \Sylius\Bundle\InstallerBundle\Command\InstallCommand that are necessary to get the app working we might miss out on those. I may be overthinking it as if that happens our app will probably break and we'll be able to look at the changelog here to see what's changed. I was really wondering if anyone had a better way of doing this; maybe via one of the config files etc

**Comment by pjedrzejewski** [comment]
We will think about custom installation process support, but currently you can just override what is possible. (classess, commands, templates) I am closing this as it is not going to happen anytime soon I think. :(
