### ISSUE TITLE
Container extension "liip_imagine" is not registered

### ISSUE THREAD

**Issue by rizaergun** [Sylius/Sylius#2738]
[Symfony\Component\DependencyInjection\Exception\LogicException]  
  Container extension "liip_imagine" is not registered              
                                                                    
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception
                                                     
  [RuntimeException]                                                         
  An error occurred when executing the "'cache:clear --no-warmup'" command. 

Why do i get an error?

**Comment by aRn0D** [comment]
When have you got that error? Do you use the sylius standard edition?

**Comment by pjedrzejewski** [comment]
Please reopen if still relevant. Thanks!
