### ISSUE TITLE
[Promotion] Applied to orders after adding

### ISSUE THREAD

**Issue by rvanlaak** [Sylius/Sylius#2739]
Our custom implementation of the PromotionBundle separates adding the Rules and Actions from adding a Promotion. We first add a Promotion, and thereafter add the Rules and Actions. 

This can result in an empty promotion that will be applied to an order by the processor. The documentation already states that a `Promotion` without an `Action` is not effective, but I think this should be solved in the `PromotionProcessor` directly:

1. By counting the number of Actions and not process the Promotion any further if there are no actions
2. By introducing an 'active' flag, and let the `PromotionRepository` take that flag into account.

The second option has my :+1: because otherwise the same will occur between adding two actions.

**Comment by pjedrzejewski** [comment]
Let's add ``enabled`` boolean flag to Promotions. But after #3098 is merged.

**Comment by Rvanlaak** [comment]
:+1:

**Comment by pjedrzejewski** [comment]
#3098 is merged, so if someone is willing to do a PR with this change, it will be awesome! :+1:

**Comment by rvanlaak** [comment]
Will add this on my TODO list for the PromotionBundle, but will changing the types in there be enough to make this work in the WebBundle?
