### ISSUE TITLE
Can i use the sylius api with c# client/server application?

### ISSUE THREAD

**Issue by tuxado** [Sylius/Sylius#2744]
hello

i read the cook book of the api and i see that use the RESTful for web services but i dont know if i should using Rest or Soap for best security level.

can we use the sylius api with a c# client/server applicationthat i will create to manage for example the payment (create/edit/delete) with web services and with best secuity level? or i should use soap for more security and cleanest architectural programming ?

thx

**Comment by maiksuaco** [comment]
I think REST is better...

2015-05-18 16:24 GMT-03:00 tuxado <notifications@github.com>:

**Comment by elliot** [comment]
> Can i use the sylius api with c# client/server application?

Yes. You can use any language or framework you like, as long as it can make HTTP requests and parse JSON. That's the beauty of REST.

As for REST vs. SOAP - neither one is more secure than the other. That said, Sylius does not support SOAP but it can output XML from the REST endpoints.

**Comment by tuxado** [comment]
thx... i have a final question about the API can we add for each user his own secret id and client id to get for each user his own access token?

**Comment by michalmarcinkowski** [comment]
@tuxado What is your use case for that?

Client id and secret id are used by the client application not the user.

Standard workflow:
You have a mobile application, generate secret id and client id in Sylius and use it in your mobile app. When the user tries to authenticate through your mobile app, the app sends user credentials together with its client id and secret id. Sylius responds with token (which is assigned to client and user) and the user uses this token to authenticate on each request.

**Comment by tuxado** [comment]
hi michalmarcinkowski

i use this app to make a multi-stores website with a multivendor and every vender will have his own secret id and client id to manage his own store from any app client web and c# (c# in his shop)

for example if i use one general secret id and client id for mobile app this kind of app can be easely decripted and the website hacked and the hacker can get acces to all informations of all vendors with only one secret id and client id

i would like create a something like facebook page secret id and client id and if this secret id and client id are hacked only this page are affected not all page of facebook

thx

**Comment by michalmarcinkowski** [comment]
OAuth2 allows you to authenticate users using their credentials (http://oauthlib.readthedocs.org/en/latest/oauth2/grants/password.html). Associate each vendor user with corresponding channel and grant access to appropriate resources and that's it. Secret and client id is not enough to 'hack' the website, in order to get access to the resources you have to know credentials, so it's fully secure.

**Comment by tuxado** [comment]
hi, thank you michalmarcinkowski for clarification and i will see this possibility and at the same time
i hope if i can generate App id and secrete Id to access to the owner ressource and editing o dleting thems look like facebook api or paypal api...

thx
