### ISSUE TITLE
sylius-0.14-dev install error

### ISSUE THREAD

**Issue by ruibinyang** [Sylius/Sylius#2745]
Fatal error: Uncaught exception 'Symfony\Component\Filesystem\Exception\IOExcept
ion' with message 'Cannot rename "E:\xampp\htdocs\sylius\app\cache\de_" to "E:\x
ampp\htdocs\sylius\app\cache\dev".' in E:\xampp\htdocs\sylius\vendor\symfony\sym
fony\src\Symfony\Component\Filesystem\Filesystem.php:262
Stack trace:
#0 E:\xampp\htdocs\sylius\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBun
dle\Command\CacheClearCommand.php(90): Symfony\Component\Filesystem\Filesystem->
rename('E:\xampp\htdocs...', 'E:\xampp\htdocs...')
#1 E:\xampp\htdocs\sylius\vendor\symfony\symfony\src\Symfony\Component\Console\C
ommand\Command.php(245): Symfony\Bundle\FrameworkBundle\Command\CacheClearComman
d->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Co
mponent\Console\Output\NullOutput))
#2 E:\xampp\htdocs\sylius\vendor\symfony\symfony\src\Symfony\Component\Console\A
pplication.php(900): Symfony\Component\Console\Command\Command->run(Object(Symfo
ny\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\
 in E:\xampp\htdocs\sylius\vendor\symfony\symfony\src\Symfony\Component\Filesyst
em\Filesystem.php on line 262

**Comment by patrick-mcdougle** [comment]
Delete all the files in app/cache and try again. Probably a permissions problem.

**Comment by Jiidy** [comment]
I did it but still the same issue..

**Comment by ruibinyang** [comment]
install sylius-dev-0.15 also the same error.
someone can help?

**Comment by patrick-mcdougle** [comment]
Can you run `ls -la` in the app/cache directory and give the result here?

**Comment by ruibinyang** [comment]
![error](https://cloud.githubusercontent.com/assets/9670092/7905001/6efd5bca-0842-11e5-9f4a-ce8968bbda2c.jpg)

**Comment by ruibinyang** [comment]
use the follow comment:
composer create-project -s dev sylius/sylius
cd sylius
php app/console sylius:install

**Comment by jmiridis** [comment]
It seems there is an open filehandle.
I inserted a sleep just before the Symfony's FileSystem::rename() method throws the IOException. Checking what was locking the 'de_' folder, I found out it was the php process/command itself.
With a tool I unlocked the folder (which I guess closes any open file handles on it). When the sleep was over, I got the following error, hope it helps to track down where the open handle comes from:

Fatal error: Uncaught exception 'Symfony\Component\Debug\Exception\ContextErrorException' with message 'Warning: SessionHandler::write(): write failed: Bad file descriptor (9)' in W:\Symfony2\Sources\sylius\sylius\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy.php on line 77

Symfony\Component\Debug\Exception\ContextErrorException: Warning: SessionHandler::write(): write failed: Bad file descriptor (9) in W:\Symfony2\Sources\sylius\sylius\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy.php on line 77

Call Stack:
  101.5858  154942648   1. session_write_close() UNKNOWN?:0
  101.5858  154943312   2. Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy->write() UNKNOWN?:0
  101.5858  154943360   3. SessionHandler->write() W:\Symfony2\Sources\sylius\sylius\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy.php:77
  101.5858  154944536   4. Symfony\Component\Debug\ErrorHandler->handleError() W:\Symfony2\Sources\sylius\sylius\vendor\symfony\symfony\src\Symfony\Component\HttpFoundation\Session\Storage\Proxy\SessionHandlerProxy.php:77

**Comment by pamil** [comment]
It's not a Sylius bug, but common permissions or locking issue connected with Symfony's `cache:clear` command Sylius is using. I think this issue it's much more likely to happen on Windows. 

See:
[Previous Sylius issue on this topic](https://github.com/Sylius/Sylius/issues/2604)
[Symfony issue on this topic](https://github.com/symfony/symfony/issues/10325)
[StackOverflow question on this topic](http://stackoverflow.com/questions/9062365/symfony-warning-rename-app-cache-dev-app-cache-dev-old-access-den)

**Comment by Symfomany** [comment]
Can you launch this command?
php app/console sylius:install:check-requirements

**Comment by michalmarcinkowski** [comment]
@ruibinyang as @pamil said, it is not related to Sylius.
