### ISSUE TITLE
[CartBundle] Cart uses the Order Repository?

### ISSUE THREAD

**Issue by patrick-mcdougle** [Sylius/Sylius#2746]
Hello,

I'm having an issue with the Cart Bundle. I get this error message when loading the /cart page.

> Argument 1 passed to Sylius\Component\Cart\Event\CartEvent::__construct() must be an instance of Sylius\Component\Cart\Model\CartInterface, instance of Sylius\Component\Order\Model\Order given, called in /vendor/sylius/cart-bundle/Provider/CartProvider.php on line 103

I suspect that this is because in the services.xml file we have the following lines
`<service id="sylius.repository.cart" alias="sylius.repository.order" />`
`<service id="sylius.repository.cart_item" alias="sylius.repository.order_item" />`

I see that there's a perfectly good CartRepository in the Doctrine/ORM directory, and AFAIK it doesn't have a service associated with it.

Is this correct? I'm pretty new to using sylius, so pardon my potential ignorance on the matter.

Let me know how this "should" be done, and I'd be happy to fix.

Thanks!

**Comment by gonzalovilaseca** [comment]
Yes, cart is stored as an order with `checkout_state` = `cart`.
