### ISSUE TITLE
ORMTranslatableListener::postLoad() depends on Request

### ISSUE THREAD

**Issue by aderuwe** [Sylius/Sylius#2748]
See https://github.com/Sylius/Sylius/blame/c8ed8168cf8656ef49357084b5e81f3ee07c8ec6/src/Sylius/Bundle/TranslationBundle/EventListener/ORMTranslatableListener.php#L175

This breaks things when used in CLI context where no request is available - or I'm doing something wrong.

Any idea?

**Comment by pjedrzejewski** [comment]
The locale provider should fallback to default locale if there is no request... That is my first thought, what do you think about this solution?
