### ISSUE TITLE
[Translations] Traits?

### ISSUE THREAD

**Issue by patrick-mcdougle** [Sylius/Sylius#2749]
Pretty new to the project, but is there a reason that we're not using traits instead of class inheritance? By using traits, we should be able to decouple the bundles a lot easier. Instead of inheriting doctrine fields through extending parent classes, we could just add a translatable trait that adds the required fields.

Thoughts?

**Comment by jimbocoder** [comment]
I haven't seen this specifically stated, but I believe Sylius intends to support PHP 5.3 for the foreseeable future, thus no traits.  The composer file specifies `php >= 5.3.9`.

**Comment by michalmarcinkowski** [comment]
True, the traits weren't used because of the PHP 5.3 support, BUT actually in the short term we are going to move to PHP 5.4 and stop supporting PHP 5.3. 

@patrick-mcdougle if you have some free time, we will be more than happy to see the PR with Translations changed to traits :)

@gonzalovilaseca @pjedrzejewski do you see any drawbacks/barriers?

**Comment by gonzalovilaseca** [comment]
No, in fact I would have done it with traits if it had been supported. Way better IMO.

**Comment by aRn0D** [comment]
@pjedrzejewski when do you plan to move to php5.4? 0.17 ?

**Comment by bicpi** [comment]
Is it worth to consider the stable library [DoctrineBehaviors](https://github.com/KnpLabs/DoctrineBehaviors) for this (and more like Timestampable, Softdeletable)?

**Comment by steffenbrem** [comment]
This would make Sylius much more flexible. I currently have the issue that I cant extend the TreeRepository without copying Sylius code. So having this, would have fixed this easily.

**Comment by michalmarcinkowski** [comment]
The traits are now supported! @patrick-mcdougle are you willing to work on this?

**Comment by patrick-mcdougle** [comment]
I'm willing but I don't think I'll be able to get to it in a reasonable amount of time. I've got a big project at work that's eating all my time and when it's over I've got a backlog of a couple personal projects that I need to work on.

**Comment by michalmarcinkowski** [comment]
Roger that. Thanks for quick response, so we will probably take care of that earlier :wink:

**Comment by gonzalovilaseca** [comment]
@michalmarcinkowski Let me find some time during the following week to do it.

**Comment by michalmarcinkowski** [comment]
Done
