### ISSUE TITLE
Empty cart with price

### ISSUE THREAD

**Issue by aguerre** [Sylius/Sylius#2753]
I will explain the scenario : 
I added a product in my cart. Then, in the backoffice, I added options (And change zone too) to this product. 
Back in the frontend, I tried to checkout the product and had 400 bad request errors, which seems legit.
So, I've decided to delete the product, always present in my cart. This caused 2 errors : "Product removed due to availability", ok, and "Impossible to remove product from cart".
Since, my cart is empty but its total due is 70€, and I doesn't know how and why.

**Comment by pjedrzejewski** [comment]
Please let us know if you can still reproduce this issue. Thank you!
