### ISSUE TITLE
Important notice about Symfony version, maintainers please read ASAP

### ISSUE THREAD

**Issue by psyray** [Sylius/Sylius#2754]
Hi,

We currently have a bug in the ContentBundle #2696 
This seems to involve the [DoctrinePHPCRBundle] (https://github.com/doctrine/DoctrinePHPCRBundle)

@dbu find [the problem] (https://github.com/doctrine/DoctrinePHPCRBundle/pull/193#issuecomment-103795310) but, if I understand correctly, this seems to force Sylius to use Symfony 2.6.6 because the DoctrinePHPCRBundle will bump to this version.

Is this possible for Sylius to use the 2.6.6 version ?
Will this not created BC breaks ?

I will test the fixed branch of DoctrinePHPCRBundle to help @dbu to validate his fix.

So @pjedrzejewski @stloyd @aRn0D .... thanks to reply ASAP and give us and @dbu your opinion

**Comment by dbu** [comment]
if there are concerns, please discuss in https://github.com/doctrine/DoctrinePHPCRBundle/pull/193 to keep discussion in one place.

**Comment by dbu** [comment]
the explanation for the version bump is in https://github.com/doctrine/DoctrinePHPCRBundle/pull/193#issuecomment-103795310 btw. before that, we would need to do a lot of customizing of the form type.

note that symfony 2.3.27 and will also be kept supported, only the end-of-life versions 2.4 and 2.5 not.

and when using older versions of symfony people can use older versions of the phpcr-bundle i think. its just that as soon as they use the document form type together with a querybuilder or a too new version of symfony, they will run into problems.

**Comment by aRn0D** [comment]
Symfony 2.7 will be released soon! @pjedrzejewski, I guest we will move on it ?

**Comment by pjedrzejewski** [comment]
I think we will bump it to 2.7 as soon as it is release. Together with 5.4 bump.

**Comment by aRn0D** [comment]
@pjedrzejewski good!

**Comment by liverbool** [comment]
@pjedrzejewski :+1:

**Comment by antonioperic** [comment]
@pjedrzejewski hola!

**Comment by pjedrzejewski** [comment]
Fixed in #2763. Thank you for reporting!
