### ISSUE TITLE
sensionGeneratorBundle and symfony 2.3

### ISSUE THREAD

**Issue by chaimawetcha** [Sylius/Sylius#2769]
i install a sylius project and i want to add a service.. i start buy creating a bundle but the command: $php app/console generate:bundle give me this error
' [InvalidArgumentException]
  Command "generate:bundle" is not defined.
'
 i find that i have to add SensioGeneratorBundle but it tells me that there is a compatibility problem
.. i'm new in sylius and i'm blocked and i need help please
@pjedrzejewski  @antonioperic @jrobeson

**Comment by antonioperic** [comment]
@chaimawetcha  I newer uses SGB in Sylius, just do your bundle manually. You will have less "junk" in code and will think about everything by yourself

**Comment by rapemer** [comment]
Command "generate:bundle" is not defined.

your AppKernel does not contain SensioGeneratorBundle

http://symfony.com/doc/current/bundles/SensioGeneratorBundle/index.html

**Comment by michalmarcinkowski** [comment]
@chaimawetcha we do not use it in dev. You should use Sylius-Standard to start a project (it is already included in the AppKernel there).

**Comment by Symfomany** [comment]
Okay with create-project in composer?

**Comment by Symfomany** [comment]
But in dev we can use  composer require sensio/generator-bundle ?
