### ISSUE TITLE
[SettingsBundle] OptionsResolverInterface is deprecated in 2.6

### ISSUE THREAD

**Issue by jrobeson** [Sylius/Sylius#2775]
It is now recommended to use OptionsResolver directly.  How should this be solved for the SettingsBundle? Should we simply inline the methods of the OptionsResolverInterface in SettingsBuilderInterface? or replace SettingsBuilderInterface ?

Here's a link to the overview of the changes to OptionsResolver itself: https://github.com/symfony/symfony/blob/master/UPGRADE-2.6.md#optionsresolver

**Comment by aRn0D** [comment]
@jrobeson we will dump to the 2.7 soon, for now Sylius is develop for the 2.3.

**Comment by jrobeson** [comment]
soon? how soon?

**Comment by Rvanlaak** [comment]
2.7 LTS has been released yesterday, so probably from now on ;)

**Comment by coudenysj** [comment]
What is the roadmap for supporting 2.7? How can I help?

**Comment by pjedrzejewski** [comment]
Sylius uses 2.7 now.

**Comment by rvanlaak** [comment]
Will bumping it to the 2.8 LTS throw too much errors?
