### ISSUE TITLE
Different composer.json between SyliusCore and SyliusCoreBundle

### ISSUE THREAD

**Issue by Jojolam44** [Sylius/Sylius#2777]
Hi,

I can't install your SyliusCoreBundle because composer can't solve dependencies.
SyliusCoreBundle => "knplabs/knp-gaufrette-bundle":   "~0.1" => "knplabs/gaufrette":  "~0.1",
Core => "knplabs/gaufrette":  "0.2.*@dev",

Is this normal or is it a bug?

Thanks.

**Comment by pjedrzejewski** [comment]
This is a bug, we hope to resolve all issues with composer.jsons.

**Comment by pjedrzejewski** [comment]
This should be fixed now.
