### ISSUE TITLE
Cannot recreate Taxon after deleting

### ISSUE THREAD

**Issue by msumme** [Sylius/Sylius#2778]
To reproduce:

1. Delete a taxon.
2. Try to create a new taxon with the same name

![image](https://cloud.githubusercontent.com/assets/462931/7799627/ebeb5418-02cd-11e5-84b2-ed2c80839edd.png)

**Comment by msumme** [comment]
If anybody has an idea of what the correct fix would be, I'd put in a PR.

I can only see a few options.

1. Soft-delete translations and make index reference the deleted_at column.
2. Hard-delete translations (not ideal given that taxons are only soft-deleted).
3. Undelete button for deleted taxons (and the ability to move into new trees)

However, those don't fully address another issue with this, which is that you cannot have 2 Taxons in different Taxonomies with the same name.

**Comment by michalmarcinkowski** [comment]
I would say that we should add an undelete button and validator to prevent exception. We've already discussed that taxon name should be unique under one parent. Take a look at #2431

**Comment by nmarmon** [comment]
Maybe this deserves the word "Closed" as a label?

**Comment by msumme** [comment]
Has it been fixed?

**Comment by nmarmon** [comment]
No, you are right, there is. I'm going to see how to resolve it.

**Comment by michalmarcinkowski** [comment]
@nmarmon take a look at my comment https://github.com/Sylius/Sylius/issues/2778#issuecomment-105284897

**Comment by pjedrzejewski** [comment]
Yes, I think we should have a restore button, but still we need to avoid the exception and perhaps add a validator for this.

**Comment by michalmarcinkowski** [comment]
Will be fixed in #3773.

**Comment by michalmarcinkowski** [comment]
Fixed in #3773
