### ISSUE TITLE
[BUG][UserBundle] Using wrong UserInterface.

### ISSUE THREAD

**Issue by liverbool** [Sylius/Sylius#2784]
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/UserBundle/OAuth/UserProvider.php#L17

Should be:

```php
use Sylius\Component\User\Model\UserInterface as SyliusUserInterface;
```

cc. @michalmarcinkowski

**Comment by michalmarcinkowski** [comment]
@liverbool Good catch! :+1: 

Fixed in the coming PR. Thanks for pointing that out :)
