### ISSUE TITLE
How can i create custom service for a frontend controller  extended from resourcecontroller

### ISSUE THREAD

**Issue by tuxado** [Sylius/Sylius#2787]
I want to add a costumised services for a frontend controller  extended from resourcecontroller like this 

    $ sylius_product:
    driver: doctrine/orm
    classes:
        product:
            model: Sylius\Component\Core\Model\Product
            controller: Sylius\Bundle\CoreBundle\Controller\ProductController
            repository: Sylius\Bundle\CoreBundle\Doctrine\ORM\ProductRepository
            form:
                default: Sylius\Bundle\CoreBundle\Form\Type\ProductType
            translation:
                model: Sylius\Component\Core\Model\ProductTranslation
                form:
                    default: Sylius\Bundle\CoreBundle\Form\Type\ProductTranslationType
            frontend:
                account:
                    controller: Sylius\Bundle\WebBundle\Controller\Frontend\Account\ProductController
                    repository: sylius.repository.product
                    form:
                        default: Sylius\Bundle\CoreBundle\Form\Type\ProductType
                    translation:
                        model: Sylius\Component\Core\Model\ProductTranslation
                        form:
    $                            default: Sylius\Bundle\CoreBundle\Form\Type\ProductTranslationType

i add some code to dependencies injections extension of the product bundle but i stuck to inject the configuration argument.

    $ public function process(array $config, ContainerBuilder $container)
    {
	$controllerConfiguration = new Definition('Sylius\Bundle\ResourceBundle\Controller\Configuration');
        $controllerConfiguration
            ->setFactoryService('sylius.controller.configuration_factory')
            ->setFactoryMethod('createConfiguration')
            ->setArguments(array($this->prefix, $this->resourceName, $this->templates))
            ->setPublic(false)
        ;
	
		
		
		$productFrontendAccountControllerClass = $config['classes']['frontend']['account']['controller'];
		
		$productFrontendAccountController = new Definition($productFrontendAccountControllerClass);
		

		$fieldFormType
            ->setArguments(array($controllerConfiguration));
		
		$container->setDefinition('sylius.controller.frontend.account.product', $productFrontendAccountController);	
		
		return parent::process($config, $container);
	}

Can any one explaine me how to performe this 

thx

ps : i dont know how to add code in issue :) it why i add  $ at the begining of some lines

**Comment by rapemer** [comment]
1. step config.yml

        sylius_resource:
            resources:
                app.[component_name]:
                    drive: doctrine/orm
                    templates: AppWebBundle:Frontend/Somefolder
                    classes:
                        model: # namespace of your entity (model)
                        repository: repostiory must extends Sylius EntityRepository (use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository; ... extends EntityRepository)

2. step create services services.yml

        # 2.1. EntityManager alias:
        app.manager.my_component:
            alias: doctrine.orm.default_entity_manager

        # 2.2. create configuration
        app.config.my_component:
            class: Sylius\Bundle\ResourceBundle\Controller\Configuration
            public: false
            factory_service: sylius.controller.configuration_factory
            factory_method: createConfiguration
            arguments: [app, my_component, null]

        # 2.3. controller as service:
        app.controller.my_component:
            class: App\Bundle\AppBundle\Controller\Backend\MyCustomController
            arguments: [@app.config.my_component]
            calls:
                - [setContainer, [@service_container]]

3. step create user permissions inside CMS
    - app.manage.my_custom (it's root permission)
    - app.my_custom.show (parent app.manage.my_custom)
    - app.my_custom.index (parent app.manage.my_custom)
    - app.my_custom.create (parent app.manage.my_custom)
    - app.my_custom.update (parent app.manage.my_custom)
    - app.my_custom.delete (parent app.manage.my_custom)

4. step create routing routing.yml

        app_my_custom_index:
            path: /administration/custom
            defaults:
                _controller: app.controller.my_custom:indexAction
                _sylius:
                    permission: show
                    template: AppWebBundle:Frontend/Somefolder:index.html.twig

**Comment by tuxado** [comment]
thank you for this explication i will try this solution because the frontend product form thas not propagate events when create a new product and i should extend the product frontend controller from the product backend controller with a some user autorisation condition

**Comment by pjedrzejewski** [comment]
Please post this question on StackOverflow - it is the official support channel for Sylius. Just tag your question with "sylius" and maybe someone will be able to help you! http://stackoverflow.com/questions/tagged/sylius

**Comment by herodrigues** [comment]
@pjedrzejewski, sorry for commenting in a closed issue, but how about to put @rapemer's solution in the docs? I was looking for something similar and couldn't found in the docs. His answer is very helpful
