### ISSUE TITLE
Allow Different User Providers

### ISSUE THREAD

**Issue by patrick-mcdougle** [Sylius/Sylius#2795]
I want to define my own `User` class that isn't persisted in the database.

In order to implement all the methods it feels natural to extend the `Sylius\Component\Core\Model\UserInterface`. This is all fine and dandy, until the FOS user bundle assumes that your user class is an entity and tries to save the last login date. Mine isn't a doctrine managed entity. I'm choosing to store my users differently.

Therefore, I propose that the implementation of `Sylius\Component\Core\Model\User` implements the FOS `UserInterface` directly as opposed to inheriting it from the `Sylius\Component\Core\Model\UserInterface`.

Thoughts?

**Comment by patrick-mcdougle** [comment]
Actually, since the entity extends FOS BaseUser, it already inherits the FOS UserInterface.

**Comment by patrick-mcdougle** [comment]
Partially related to #1641

**Comment by michalmarcinkowski** [comment]
@patrick-mcdougle we no longer use FOSUserBundle. Check our new Customer/User model.
