### ISSUE TITLE
Help needed, Can't access the app_dev.php nor app.php after a clean install

### ISSUE THREAD

**Issue by TrueLoop** [Sylius/Sylius#281]
Hi, i went through all the steps of installation without any problem but i get this message when i try to access the site via my apache server which is rooted to "../sylius/web/"

mywebsite.com/app_dev.php   ->  Error msg : You are not allowed to access this file check app_dev.php for more info.

I therefore checked app_dev.php and saw that it send this error message when it is not in array of IP's.

So i commented all the if block. but then when i reload, i get a blank page.

I also installed sylius for prod environement but it isn't working too.

Any help would be apreciated.

Cheers, Oliver.

**Comment by umutuluer** [comment]
It is my solution, i dont know it is correct but it works. 

you can comment the code block

`if (isset($_SERVER['HTTP_CLIENT_IP'])
    || isset($_SERVER['HTTP_X_FORWARDED_FOR'])
    || !(in_array(@$_SERVER['REMOTE_ADDR'], ['127.0.0.1', '::1']) || php_sapi_name() === 'cli-server')
) {
    header('HTTP/1.0 403 Forbidden');
    exit('You are not allowed to access this file. Check '.basename(__FILE__).' for more information.');
}`

**Comment by Blueblazer172** [comment]
if you comment that out you are having less security cause then the dev environment would be accessable from anyone who reaches the page. Definitely dont do that! Instead add your ip to the array ['127...', ''YOUR_IP']
