### ISSUE TITLE
Load sample data errors

### ISSUE THREAD

**Issue by w2713** [Sylius/Sylius#2817]
After running the command app/console sylius:install, an error is displayed:

Load sample data? (y/N) y
Loading sample data...
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Unknown formatter "streetAddress"' in /var/www/tuinfo.ru/vendor/fzaninotto/faker/src/Faker/Generator.php:167
Stack trace:
#0 /var/www/tuinfo.ru/vendor/fzaninotto/faker/src/Faker/Generator.php(149): Faker\Generator->getFormatter('streetAddress')
#1 /var/www/tuinfo.ru/vendor/fzaninotto/faker/src/Faker/Generator.php(188): Faker\Generator->format('streetAddress')
#2 /var/www/tuinfo.ru/src/Sylius/Bundle/FixturesBundle/DataFixtures/DataFixture.php(144): Faker\Generator->__get('streetAddress')
#3 /var/www/tuinfo.ru/src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadOrdersData.php(64): Sylius\Bundle\FixturesBundle\DataFixtures\DataFixture->createAddress()
#4 /var/www/tuinfo.ru/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/AbstractExecutor.php(121): Sylius\Bundle\FixturesBundle\DataFixtures\ORM\LoadOrdersData->load(Object(Doctrine\ORM\EntityManager))
#5 /var/www/tuinfo.ru/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtu in /var/www/tuinfo.ru/vendor/fzaninotto/faker/src/Faker/Generator.php on line 167

**Comment by coudenysj** [comment]
@w2713 Is this still occurring?

**Comment by nickyat** [comment]
Same issue. 
One to one as describe w2713. Correct install only without load simple data.
