### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by xurshid29** [Sylius/Sylius#2820]
Hi,
how do you install this project?
This version is failing with such error:
```
[UnexpectedValueException]                                                                                                                                        
  RecursiveDirectoryIterator::__construct(/var/www/sylius.dev/sylius/vendor/liip/imagine-bundle/Liip/ImagineBundle): failed to open dir: No such file or directory
```
And `Sylius Standard Edition` version is failing with this:
```
[Symfony\Component\Validator\Exception\NoSuchMetadataException]  
  The class or interface ""en_US, de_DE"" does not exist.
```

**Comment by antonioperic** [comment]
@xurshid29 I have the same problem, did you find solution maybe?

**Comment by xurshid29** [comment]
@antonioperic No. I spent 6 hours, but no luck.

**Comment by antonioperic** [comment]
did you use composer update or install?

**Comment by xurshid29** [comment]
Neither `composer install/update` nor `sylius:install` didn't help. I think this related to bundles' versions,,

**Comment by antonioperic** [comment]
cc @pjedrzejewski @aRn0D  do you maybe can help with this?

**Comment by coudenysj** [comment]
@xurshid29 @antonioperic What version are you installing?

**Comment by xurshid29** [comment]
@coudenysj  What installs `create-project sylius/sylius-standard -s dev` command. I've already removed the project, I can't remember the version, but seems like that command installs the v0.14.0.

**Comment by coudenysj** [comment]
@xurshid29 What step is failing?

I've installed the current version locally, and the output is in http://pastebin.com/vAGv8sJJ.

Please verify the following:

```
php -m | grep intl
cat composer.json | grep sylius/sylius
```

**Comment by antonioperic** [comment]
@coudenysj I don't have problem anymore, with new versions everything works ok

**Comment by xurshid29** [comment]
@coudenysj @antonioperic  OK, we can close the issue. I've already began to create my own e-commerce framework on top of Symfony2, removed the Sylius completely from my system, as it seems too buggy for me..

PS:// There are multiple Symfony2 projects work on my server. My server configuration is OK,

**Comment by antonioperic** [comment]
We can close yes
