### ISSUE TITLE
Model class parameter for custom resources

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius#2821]
When configuring your resource, like documented in http://docs.sylius.org/en/latest/bundles/SyliusResourceBundle/configuration.html, would be nice to set model class parameter in container config.

**Comment by aRn0D** [comment]
@umpirsky We should parse the configuration like the "advanced" way. For that, we need to refactor the extension and specify a common configuration structure.

Related PR/issue : #2520, #2651, #2622

**Comment by pjedrzejewski** [comment]
I am actually thinking we should remove advanced configuration from bundles and simply use ``prepend`` to configure everything under ``sylius_resource`` configuration.

1. We want to have 1:1 functionality for both cases.
2. That will remove a lot of code and duplication from resource bundle.

Basically make Sylius use the simple configuration inside of bundles. What do you guys think? @Sylius/core-team @michalmarcinkowski

**Comment by michalmarcinkowski** [comment]
@pjedrzejewski Good idea! :+1:

**Comment by steffenbrem** [comment]
@pjedrzejewski Nice, like that idea too. Would simplify it a lot! :+1:

**Comment by michalmarcinkowski** [comment]
Fixed in #3721
