### ISSUE TITLE
Locale issue on install:  The class or interface "en_US" does not exist.           

### ISSUE THREAD

**Issue by antonioperic** [Sylius/Sylius#2823]
http://take.ms/TRSiZ

tep 2 of 4. Setting up the database.
Creating Sylius database for environment dev.
 4/4 [||||||||||||||||||||||||||||] 100%
Warning! This will erase your database. Your current environment is dev.

Step 3 of 4. Shop configuration.
Please enter list of locale codes, separated by commas or just hit ENTER to use "en_US". For example "en_US, de_DE".

                                                                   
  [Symfony\Component\Validator\Exception\NoSuchMetadataException]  
  The class or interface "en_US" does not exist.                   
                                                                   

sylius:install:setup

**Comment by iBet7o** [comment]
same problem https://github.com/Sylius/Sylius/issues/2810

**Comment by antonioperic** [comment]
if you set symfony/symfony: "~2.3.30" in composer.json and then hit update this is resolved
