### ISSUE TITLE
500 error on the create product pages

### ISSUE THREAD

**Issue by coudenysj** [Sylius/Sylius#2839]
I'm not sure if I should report errors about the demo application in this repository, but here goes:

http://demo.sylius.org/administration/products/new and http://demo.sylius.org/administration/products/edit/x result in a 500 error.

I would like to see the flow how products are made.

**Comment by coudenysj** [comment]
@pjedrzejewski Can you look up the exception in the logs? I'm happy to write a fix for it, but now I don't have a clue what is happening.

**Comment by nmarmon** [comment]
Maybe if the application online is broken in some features you have to install Sylius in your local machine. See http://docs.sylius.org/en/latest/book/installation.html

**Comment by coudenysj** [comment]
I already have it up and running locally, I was just wondering if I could help fix the demo site so other users can see what Sylius can do.

**Comment by michalmarcinkowski** [comment]
Demo is now sync with master and the issue no longer occurs. Thanks for reporting @coudenysj! :+1:

**Comment by pjedrzejewski** [comment]
:fireworks:
