### ISSUE TITLE
[RFC] Multiple Shipping Addresses

### ISSUE THREAD

**Issue by patrick-mcdougle** [Sylius/Sylius#2842]
Anyone have a clear idea on what it would take to ship order items to different addresses? For example if I am buying 5 shirts for 5 of my friends, I would need to place 5 orders instead of making one order with 5 shipping addresses.

There's a business case for this too, since there's usually a fixed cost for payment processing, so minimizing (by allowing 5 different ship-to addresses) total number of orders results in decreased costs and increased profits.

Thoughts?

**Comment by pjedrzejewski** [comment]
This is currently not implemented and won't be possible in 1.0. But definitely interesting use-case. I could not find any related issues, so I will mark this as a feature request.

**Comment by patrick-mcdougle** [comment]
I think the path forward for this would be adding address information to the shipment entity (and maybe the cart item)?

**Comment by pjedrzejewski** [comment]
@patrick-mcdougle Yes, this makes sense!

**Comment by vanclei** [comment]
Hi @patrick-mcdougle , did you find a way to implement this?

Cheers

**Comment by patrick-mcdougle** [comment]
I did, but it starts to get complicated when dealing with taxes and coupons. We essentially had to highly modify some of the tax and promotion processing to make it work. In short, start storing the address as a value object on the shipments themselves as opposed to storing them on the order. Sorry, I can't really share any code from that, because it's proprietary. Sorry.

**Comment by vanclei** [comment]
Hi Patrick, thank you for your reply.  I'll have a look, and do not worry about proprietary.

cheers

**Comment by patrick-mcdougle** [comment]
I think this is still a compelling feature that should eventually get on a roadmap.

**Comment by psren** [comment]
stale bot sucks...

**Comment by tudorradubarbu** [comment]
Anyone got more news on this one?
