### ISSUE TITLE
[ResourceBundle] The paginate parameter can not be overwritten in query string

### ISSUE THREAD

**Issue by cdaguerre** [Sylius/Sylius#2846]
Controller `Configuration` checks the `params` set by the `onKernelController` listener and general settings but never checks the query.

I'm not sure this is expected behaviour, but if it is, I think we could introduce a `paginatable` setting...

**Comment by aRn0D** [comment]
I don't understand can you explain us a bit more, plz ?

**Comment by pjedrzejewski** [comment]
Will be fixed in #2255 as well.
