### ISSUE TITLE
[ResourceBundle] Configuration and ConfigurationFactory should not depend on ParametersParser

### ISSUE THREAD

**Issue by cdaguerre** [Sylius/Sylius#2847]
Right now, the only reason the Controller `Configuration` requires the `ParametersParser` is to process expression language in redirect parameters [here](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Controller/Configuration.php#L232).

IMO, this logic could be moved to the `RedirectHandler`, which would notably remove the dependency on the `ParametersParser` from both the  `Configuration` and the `ConfigurationFactory`.

Furthermore, I think the parser should get an interface and be registered a parameter/service to allow increased extendability.

**Comment by pjedrzejewski** [comment]
This is fixed in #2255.
