### ISSUE TITLE
Out of memory with lots of variants - loading /administration/products/

### ISSUE THREAD

**Issue by msumme** [Sylius/Sylius#2860]
I have a shop where each product will have ~1000 variants (3 option sets all of which apply to each product in almost every combination).

I noticed that I cannot load the /administration/products page as it runs out of memory (128M).

I was looking into the EXTRA_LAZY associations from Doctrine to see if that might help, but unfortunately it will not currently, as the "hasVariants" functionality relies on getVariants(), which in turn calls "filter()" on the Collection, requiring every element to be loaded from the database.

This is not scalable to large complex stores, unfortunately.

When I have those products loaded, I cannot even load the home page of the web store. 

This is a problem with the variant model in general - it doesn't scale well for made to order products that have a lot of custom option combinations.  In our particular case, the options (materials we can use) change over time, making the store even harder to manage with the variant model.

So - I guess other than the bug report, I was wondering if there were any suggestions for my use case that don't use variants?  I couldn't get the products to add to the cart properly w/o variants, unfortunately, so I'm not really sure what the right way to handle this is.

Any help would be appreciated.

**Comment by msumme** [comment]
Part of the issue is ProductRepository::createFilterPaginator - line 66:

```php
  $queryBuilder = parent::getCollectionQueryBuilder()
            ->addSelect('variant')
            ->leftJoin('product.variants', 'variant')
        ;
```

The "select('variants')" ensures that the variants are always loaded, even when they shouldn't be, like in catalog pages, and other places where you only want the list of products.

This can be a pretty big performance issue when a site has high traffic.

**Comment by msumme** [comment]
The other part of the issue is that a LOT of calls rely on the masterVariant.

It would be better if masterVariant were a oneToOne relationship instead of what it is currently, where it is found by iterating through the entire list of variants.

That means that ALL the variants always have to be loaded every time a product's properties are accessed.

That leads to the same performance issue as well.

**Comment by msumme** [comment]
Actually, w/ 1000 variants per product, most of the front-end is unusable as well without a high memory limit.

**Comment by steffenbrem** [comment]
@msumme I also think that having the `masterVariant` as a `one-to-one` is a good idea, I have thought about this a lot. So this issue might be fixed if the masterVariant is a one to one and the `createFilterPaginator` method does not join on the variants?

**Comment by msumme** [comment]
Yes, I overrode the models and if it's a one-to-one and the addSelect('variants') is removed, then it works in the admin.

Symfony profiler said it was only taking about 32MB of memory to load after that.

My updated product class looks like this:

```php

class Product extends BaseProduct 
{

 /**
     * 
     * @var BaseVariantInterface
     * @ORM\OneToOne(targetEntity="ProductVariant")
     * @ORM\JoinColumn(name="master_variant_id", referencedColumnName="id", nullable=true)
     */
    private $masterVariant;

...

 /**
     * {@inheritdoc}
     */
    public function setMasterVariant(BaseVariantInterface $masterVariant)
    {
        parent::setMasterVariant($masterVariant);
        $this->masterVariant = $masterVariant;
        
        return $this;
    }
    
    /**
     * {@inheritdoc}
     */
    public function getMasterVariant()
    {
        return $this->masterVariant;
    }

}
```

**Comment by msumme** [comment]
This doesn't really fix the front-end, which still can fail when you have too many variants, especially on product pages with "Variant choice" enabled.

However, I don't think "Variant choice" would be a great option for products with that many options, for obvious usability reasons.  So that's less of an important issue.

**Comment by msumme** [comment]
And the failures in the front-end seem to have more to do with twig needing to send one giant response than anything else.  That may be harder to fix.

**Comment by jeroendesloovere** [comment]
This is definitely something to fix.
A master variant is a solution that I have also used in a custom shop.

The only problem with a master variant is that if you want your shop to show all variants, instead of all the master variants.
For example:

Mostly, you are only showing master variants on the frontend index.
1. "T-shirt: sylius is nice"
2. "T-shirt: sylius is awesome"

But sometimes customers want to show all variants on the frontend index.
1. "T-shirt: sylius is nice - blue"
2. "T-shirt: sylius is nice - red"
3. "T-shirt: sylius is nice - green"
4. "T-shirt: sylius is awesome - blue"
5. "T-shirt: sylius is awesome - red"
6. "T-shirt: sylius is awesome - green"

**Comment by pjedrzejewski** [comment]
Should be fixed in new admin.
