### ISSUE TITLE
[MailerBundle] Missing Email translations

### ISSUE THREAD

**Issue by gperdomor** [Sylius/Sylius#2870]
Hi...

As emails can be configured using twig templates or database, could be necessary translation when the email is configured on the database side.

**Comment by nicolasricci** [comment]
any progress on the email translations?

**Comment by mgonyan** [comment]
I can take this feature over but i will need your help guys @michalmarcinkowski, @gperdomor, @nicolasricci, @pjedrzejewski to define the requirements. Questions:
* Assuming the user saves the template using twig format how are we going to allow the using to add the translations, as far as i've seen there is not translation section for the emails in the backend.
* Are we assuming the user will use twig format to create the emails, can they use variables ?

Many thanks

**Comment by pjedrzejewski** [comment]
@mgonyan Awesome!

1. We need to make Email entity translatable with appropriate fields. (have a look at other entities, which support translations)
2. Yes, they can use variables. Each e-mail can have different variables available. Not sure how to define them to display in the backend.

**Comment by mgonyan** [comment]
@pjedrzejewski thank you,

Ok i am working in a PR to do it,

**Comment by IndraGunawan** [comment]
there is a way to translate the email title?
