### ISSUE TITLE
[OrderBundle] Can't find OrderControler

### ISSUE THREAD

**Issue by kkochanski-neurosys** [Sylius/Sylius#2878]
Hi,

In documentation it was mentioned that OrderBundle contains OrderController:
http://docs.sylius.org/en/latest/bundles/SyliusOrderBundle/summary.html

DI define service for OrderController under sylius.controller.order:
https://github.com/Sylius/SyliusOrderBundle/blob/master/DependencyInjection/Configuration.php

Sf command: container:debug can find this service, but:

1) There is no OrderController: https://github.com/Sylius/SyliusOrderBundle/tree/master/Controller
2) Sf error: Attempted to load class "OrderController" from namespace xxxxx Do you need to "use" it from another namespace?
3) In vendor: sylius/order-bundle/Controller there is no OrderController

Should it work in this way?

**Comment by michalmarcinkowski** [comment]
In the configuration there should be ResourceController (like here https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/UserBundle/DependencyInjection/Configuration.php#L171) and the docs are not updated to the latest version....

Thanks for reporting this! :wink:

If you have some time you can make a PR with fixes (you can also update the docs on https://github.com/Sylius/Sylius-Docs).

**Comment by michalmarcinkowski** [comment]
Fixed :)
