### ISSUE TITLE
Catchable Fatal Error: Object of class Symfony\Cmf\Bundle\ContentBundle\Doctrine\Phpcr\StaticContent could not be converted to string 

### ISSUE THREAD

**Issue by nicolasricci** [Sylius/Sylius#2883]
I did not have the time yet to dig this one further but I have the following error when editing a static content type.
Anyone with the same issue?

**Comment by nicolasricci** [comment]
This is linked to the sylius_static_content_choice not being able to load the choice options apparently. 
This is broken on the current demo as well

**Comment by nicolasricci** [comment]
@dbu @pjedrzejewski any idea about this issue with CMF?

**Comment by coudenysj** [comment]
@nicolasricci What version are you using? I'm able to edit a page.

**Comment by nicolasricci** [comment]
I am using the master branch. Demo website, which is up to date I guess, is broken as well
http://demo.sylius.org/administration/content/static-contents//cms/pages/terms-of-service/edit

**Comment by coudenysj** [comment]
Ok, thanks. Found the error.

Will try to create a PR for it.

**Comment by michalmarcinkowski** [comment]
@nicolasricci is it solved? Can it be closed?

**Comment by nicolasricci** [comment]
@michalmarcinkowski yes all good now.
thanks @coudenysj
