### ISSUE TITLE
Can't add name for new country - not available for edit

### ISSUE THREAD

**Issue by amoraru** [Sylius/Sylius#2890]
![add new country](https://cloud.githubusercontent.com/assets/12938527/8226261/bd14a726-15a5-11e5-9b75-26f34b3ee1b2.png)

Default country United States can't be edit too, we can see in breadcrumbs that we are on United States country but we can't see it in name input
![edit default united states](https://cloud.githubusercontent.com/assets/12938527/8226299/1c2181da-15a6-11e5-9b73-91433cdfb0cd.png)

This error is on last standard sylius, v 0.15.0-dev

**Comment by patrick-mcdougle** [comment]
I assume this is a locale/translation problem. Do you have php-intl installed? Do you have a default locale in your config?

**Comment by pamil** [comment]
I think that after merging #3035, there should not be any possibility to add new countries. The only scenario is to restore previously deleted country. @michalmarcinkowski WDYT?

**Comment by michalmarcinkowski** [comment]
We will use Intl for countries, so add new country page will be simply select of countries defined in Intl. The names and translations are already in Intl, so there will be no possibility to edit country name or it's translation. @pamil is already working on that.

**Comment by pamil** [comment]
#3074 solves this issue.

**Comment by nmarmon** [comment]
Then the label should be "Closed" ?
