### ISSUE TITLE
Can't add name for new shipping method - not available for edit

### ISSUE THREAD

**Issue by amoraru** [Sylius/Sylius#2893]
![shipping](https://cloud.githubusercontent.com/assets/12938527/8231798/a6168ebc-15d3-11e5-8edc-0c1b866913e8.png)

**Comment by nmarmon** [comment]
Maybe it is a problem with privileges? What is the exact text of the error?

**Comment by nmarmon** [comment]
I install Sylius again, and I can now write a name for the shipping method. Is it solved? During the installation, I choose to have more thaan one currency, for example. Maybe that has changed something?

**Comment by pamil** [comment]
Same as @nmaron, it works on default Sylius installation form master branch, @pjedrzejewski @michalmarcinkowski think it can be closed too :)
![zrzut ekranu z 2015-09-02 11 37 09](https://cloud.githubusercontent.com/assets/1897953/9627839/2799686e-5167-11e5-8a49-8275e9e045d8.png)
