### ISSUE TITLE
Error create new route

### ISSUE THREAD

**Issue by amoraru** [Sylius/Sylius#2894]
A "__toString()" method was not found on the objects of type "Symfony\Cmf\Bundle\ContentBundle\Doctrine\Phpcr\StaticContent" passed to the choice field. To read a custom getter instead, set the option "property" to the desired property path.

**Comment by coudenysj** [comment]
Duplicate of #2883.

**Comment by michalmarcinkowski** [comment]
Fixed by https://github.com/Sylius/Sylius/pull/2952
