### ISSUE TITLE
Validation not working add new slideshow

### ISSUE THREAD

**Issue by amoraru** [Sylius/Sylius#2895]
I've tried to set up a slideshow. Instead of get a nice error, to tell me what field should I complete, I have the following error.
I've just select image to upload and enable it. All the other fields for add slide where empty 

NodeName property "name" may not be empty in document of class "Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\ImagineBlock

**Comment by psyray** [comment]
@amoraru 
The internal name is mandatory
![selection_071](https://cloud.githubusercontent.com/assets/1230954/9412980/628214a8-482f-11e5-89e9-7b9a56a4601d.png)

I will fix the cascade validation of the collection form to prevent raising an exception

**Comment by psyray** [comment]
Fix done, waiting for remarks or merge ;)
