### ISSUE TITLE
[REQUEST] Link to Variant in WebBundle/Resources/views/Frontend/Product/show.html.twig

### ISSUE THREAD

**Issue by marmotte31** [Sylius/Sylius#2904]
Hello Folks,
Can someone please explain me how to create a lin to the variant of a product un the show.html.twig ?
src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Product/show.html.twig

**Comment by coudenysj** [comment]
@marmotte31 Where would you link that to? The show.html.twig file [contains a list of variants](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Product/show.html.twig#L57-L105) (look at the radio buttons on http://demo.sylius.org/p/book-et-by-nicolette-harvey).

**Comment by pjedrzejewski** [comment]
Hi @marmotte31! Please post this question on StackOverflow - it is the official support channel for Sylius. Just tag your question with "sylius" and maybe someone will be able to help you! http://stackoverflow.com/questions/tagged/sylius

**Comment by marmotte31** [comment]
hi @pjedrzejewski ok it's done ;)

hello @coudenysj I've modified this show.html.twig page (no radio button anymore) and I want to put a link on these variant.
