### ISSUE TITLE
Order confirmation email - possibly on the wrong event

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#2915]
I was just reading the docs for emails (http://docs.sylius.org/en/latest/book/emails.html), and it mentions that order confirmation email is sent after order has been paid for.

However, it clearly seems like the order confirmation email is sent in the finalize step, and not after the purchase step.

Is the documentation incorrect, or is this a bug? And if it's a bug, is the fix as easy as changing the event name inside the mailer xml? (from ```<tag name="kernel.event_listener" event="sylius.checkout.finalize.complete" method="sendOrderConfirmationEmail" />``` to ```<tag name="kernel.event_listener" event="sylius.checkout.purchase.complete" method="sendOrderConfirmationEmail" />```

If it is a bug, and my solution above is correct, I could send a PR right away.

**Comment by kayue** [comment]
Shouldn't it use state machine to send email?

**Comment by inssein** [comment]
@kayue do you have an example of that already happening somewhere else? Right now its just https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/EventListener/MailerListener.php, wired up by https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/mailer.xml.

**Comment by inssein** [comment]
So I just replaced the event with a compiler pass for now, until we figure it out that its a bug and it gets fixed in Sylius. The only thing to note is that ```sylius.checkout.purchase.complete``` does not work because it sends a PurchaseCompleteEvent with a Payment. I resorted to using the ```sylius.checkout.purchase.pre_complete``` for now, which works.

**Comment by kayue** [comment]
@inssein Sorry for the late reply.

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/state-machine.yml#L110-L121

To send order confirmation email is sent after order has been **paid** for, it should be listen to the `confirm` transition. 

Personally I would avoid hooking into steps event, but I think we have been doing so for some time.

**Comment by inssein** [comment]
@kayue ah interesting, didn't know about that, still got lots to learn. I guess the order confirmation email functionality must have been written before addition of a state machine. Perhaps next weekend I could put in an RFC to upgrade the email event listeners to use the state machine instead.

**Comment by pjedrzejewski** [comment]
@inssein That would be great! We should move everything to state machine.

**Comment by kayue** [comment]
:+1:

**Comment by michalmarcinkowski** [comment]
Should be fixed by #2959.
