### ISSUE TITLE
inventory.backorders_enabled vs. isAvailableOnDemand (priority)

### ISSUE THREAD

**Issue by poolerMF** [Sylius/Sylius#2920]
hello

there is global parameter **sylius.inventory.backorders_enabled** and there is option **isAvailableOnDemand** for every product variant

**what has bigger priority ?**

in AvailabilityChecker.php, functions isStockAvailable and isStockSufficient:

    if ($this->backorders || $stockable->isAvailableOnDemand()) {
        return true;
    }

there should by **&&** instead of **||** ?

**Comment by patrick-mcdougle** [comment]
no, backorders is a global option across the whole store, and `isAvailableOnDemand()` allows a stockable (Usually ProductVariant) to effectively turn on backordering on the stockable level.

**Comment by poolerMF** [comment]
yes .. but WHEN backorders is enabled
I have produt which is not isAvailableOnDemand, currently I do not have any piece for selling .. but on page customer still can buy product ... becouse of "$this->backorders ||"

it's not right logic .. there should be AND

**Comment by steffenbrem** [comment]
It should not be AND, since if you do that then when you have backorders disabled, isAvailableOnDemand will be ignored. You do not want that behaviour.

**Comment by michalmarcinkowski** [comment]
@poolerMF it's confusing, but the **sylius.inventory.backorders_enabled** is global, so when you set it to ``` true ``` all products are available on demand no matter if  ``` isAvailableOnDemand ``` method returns true or false. It means you can't disable individual products - use this option if you want all products to be available on demand.

If you want to be able to enable/disable products separately, turn ``` backorders ``` off (false) and set ``` availableOnDemand ``` on each product, whether you allow for it or not.

**Comment by pjedrzejewski** [comment]
We will think about making it more clear and maybe move it to settings bundle, but for now it works exactly as @michalmarcinkowski said. Thanks for raising this issue!
