### ISSUE TITLE
[Bug] Taxonomies bundle broken, wrong dependencies

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#2922]
Hi,

When you try to install the `sylius/taxonomies-bundle` along with the latest `sylius/resource-bundle`, you will get the following error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sylius/taxonomies-bundle dev-master -> satisfiable by sylius/taxonomies-bundle[dev-master].
    - sylius/taxonomies-bundle dev-master requires sylius/resource-bundle 0.9.*@dev -> no matching package found.
```

I am using the following stability setting:

```json
{
    "minimum-stability" : "dev",
    "prefer-stable" : true
}
```

Does the `composer.json` of the `sylius/taxonomies-bundle` needs an update to the latest `resource-bundle` version (it is using `0.9.0` now) in order to work correctly? Currently I can't proceed with a project I am working on since I need this bundle.

**Comment by steffenbrem** [comment]
Channel bundle has the same problem!

**Comment by steffenbrem** [comment]
I guess those bundles need to be released under there own tags and have their `composer.json` branch alias updated to `0.15.x-dev`?

**Comment by michalmarcinkowski** [comment]
You should install ``` sylius/taxonomy-bundle ```. Could you try again and confirm it is working?

**Comment by steffenbrem** [comment]
@michalmarcinkowski Aaah, how stupid haha. Kinda confusing though, having two bundles with identical  names.

**Comment by steffenbrem** [comment]
Closing this, but will reopen another issue for the channel bug. I see @pjedrzejewski did fix it in the main repo, but it also needs to be in the split repos (channel and channel-bundle).

**Comment by michalmarcinkowski** [comment]
Thanks for rising it. Taxonomies-bundle has been abandoned on packagist from now, so I hope nobody will have this issue again :)
