### ISSUE TITLE
Run channel bundle and channel component split on the main repo (they are not in sync now)

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#2924]
@pjedrzejewski I guess you are the one that does the splits of the main repo. Could you sync the channel bundle and channel component repo so that I can use the standalone bundle?

**Comment by michalmarcinkowski** [comment]
@steffenbrem should be resolved. Could you check if it's installing?

**Comment by steffenbrem** [comment]
@michalmarcinkowski Yes it is! :+1: Thanks
