### ISSUE TITLE
[RFC] About upgrade procedure 

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius#2933]
Last week I was updating Sylius from version 0.12 to 0.14. 

Maybe I am missing something but there is upgrade procedure missing as in [UPGRADE.md](https://github.com/Sylius/Sylius/blob/master/UPGRADE.md) I found only instructions for upgrading from 0.9.0 to 0.10.x.

What do you think about writing (from now on) detailed upgrade procedure like Symfony does. And describe what to change in order to make existing code works with new version, rather then listing what had been changed?

**Comment by umpirsky** [comment]
@pjedrzejewski What do you think about writing upgrade instruction each time we break BC?

**Comment by michalmarcinkowski** [comment]
We discussed it earlier and starting from now, we will try to always write upgrade instruction :)

**Comment by umpirsky** [comment]
@michalmarcinkowski Great, that would be awesome. In case you don't have time, or you need help, please ping me and I will help. It costs me more time to figure out upgrades then help you write them. :)

Cheers! :)

**Comment by michalmarcinkowski** [comment]
@umpirsky Sure! First UPGRADE.md in progress :wink:
