### ISSUE TITLE
Multitenancy

### ISSUE THREAD

**Issue by paq85** [Sylius/Sylius#2941]
It would be great to have multitenancy support so we can provide Sylius as Software-as-a-Service (SaaS).
https://en.wikipedia.org/wiki/Multitenancy

Are there any plans for such a feature?

There's "multi-site" support in progress but it's not the same: https://github.com/Sylius/Sylius/issues/321

**Comment by pjedrzejewski** [comment]
@paq85 We do not plan to support multitenancy out of the box for 1.0, but it is already possible to customize this Sylius to provide this feature. That being said, hopefully we will see some plugins for 1.0 and maybe support it in 2.0.

**Comment by steffenbrem** [comment]
What would be the main differences from a `Channel`? I am having a multi tenancy setup too myself, but I just use channels for this and extend Sylius models where needed. Only thing I did was introduce a `Workspace` that customers, channels etc. are linked to. Or do I have the wrong idea of a Channel?
