### ISSUE TITLE
Foreign key constraint violation when deleting some entities (e.g. Zone)

### ISSUE THREAD

**Issue by ahmadrabie** [Sylius/Sylius#2950]
When the user tries to delete a Zone, Country, Province or Address, because of the foreign key constraints he's going to see a ForeignKeyConstraintViolation exception. Which in many cases confuses regular users.

What do you think is the best way to handle this situation?

Some suggestions are as follows:
* Show a user friendly message which warns user that this entity is being used.
* Allow him to provide a `force` or `yes-to-delete-all` kind of option so we will remove all related entities.
* Use `SET NULL` constraint in some situations, `CASCADE DELETE` is some others.

If we want to show a human-readable message (instead of the scary exception) where is the correct place to catch the exception? I think catching `PDOException`s with [error code `1451`](https://dev.mysql.com/doc/refman/5.5/en/error-messages-server.html#error_er_row_is_referenced_2) (which is for foreign key constraints on update and delete) in resource controller `deleteAction`, can be a good idea.

What do you guys think? :)

**Comment by pjedrzejewski** [comment]
We can't mute all exceptions related to foreign keys. We should catch only these, which we expect to happen and handle them = fail gracefully with human-readable message. I am not sure we can come up with a generic solution at the moment, but maybe after resource bundle refactoring.

**Comment by michalmarcinkowski** [comment]
Fixed by [this listener](https://github.com/Sylius/Sylius/blob/f5d1b5f7fe845adfcc2fac485d6e19cd1708e03b/src/Sylius/Bundle/ResourceBundle/EventListener/ResourceDeleteSubscriber.php). Thanks for reporting!
