### ISSUE TITLE
"Invalid argument supplied for foreach()" error when using cart

### ISSUE THREAD

**Issue by faheem00** [Sylius/Sylius#2954]
Hello, I am using your Cart Bundle. I have set out the configurations and resolver classes as specified in your documentation. I have extended both the Cart and CartItem classes to add custom fields in the entities. After I add a product to cart, the resolver resolves the cart as usual and returns an item, but an exception occurs right after that - 

<code>Warning: Invalid argument supplied for foreach() in vendor/sylius/order/Model/OrderItem.php at line 254</code>

```php
        $this->adjustmentsTotal = 0;
        foreach ($this->adjustments as $adjustment) {
            if (!$adjustment->isNeutral()) {
                $this->adjustmentsTotal += $adjustment->getAmount();
            }
```

But the thing is, I am not using adjustment in the cart, I do not have any need for it. So why this error is showing here? I used the <code>sylius_cart_item_add</code> route to automatically add the product to cart.

Please help me out here, at first glance I really enjoyed the simplicity and modularity of Sylius, and I would very much like to continue enjoying its usage. Thanks in advance.

**Comment by michalmarcinkowski** [comment]
Have you implemented constructor in your custom CartItem class? Maybe you have forgotten to call ``` parent::__construct(); ```? It seems like the array isn't initialized, but should be, because of the line: https://github.com/michalmarcinkowski/Sylius/blob/4d50e0345383476562cb58ae8696b65af32b175a/src/Sylius/Component/Order/Model/OrderItem.php#L85-85.

**Comment by faheem00** [comment]
I did indeed forgot to call parent::_construct(), and after calling the constructor It seems to have done the trick! Thanks a lot for your help. I know it's an obvious logic to call parent constructor in case you extend any class, but if you still can include the parent constructor call in your sylius cart bundle docs, I think it might save some head scratching for some developers in the future. Thanks for your effort to build Sylius, looking forward to the stable version!
