### ISSUE TITLE
Bundle about sylius Reward Point

### ISSUE THREAD

**Issue by ghost** [Sylius/Sylius#2955]
1.Customer every day login or sepcial day can get point
2.Point exchange coupons
or other idea？

**Comment by antonioperic** [comment]
we are planing to work on Loyalty feature very soon

**Comment by gabiudrescu** [comment]
Loyalty as in a % of cashback from the total order amount?

**Comment by PWalkow** [comment]
@ghost It's somehow already added into PromotionBundle, you may create a 'promotion' that will add an AdjustmentInterface to the Order/OrderItem. There is also a 'rule' about nth order for client, you can achieve that already without adding new code. Add a listener for the calculations of the cart and you have it. All you have to do is find a name for your cashback 'flag'.

**Comment by benyang2015** [comment]
anybody work this?

**Comment by Snake-Tn** [comment]
@ghost , @benyang2015 , Send me a full requirements for this plugin, And I may help on developing it.

**Comment by Snake-Tn** [comment]
I'm starting the development of a reward plugin : https://github.com/Snake-Tn/SyliusRewardPlugin 
I estimate it be done within 1 month from now.
