### ISSUE TITLE
Migrating from a 1.x Magento installation

### ISSUE THREAD

**Issue by dav-m85** [Sylius/Sylius#2956]
Easy question, but not trivial answer. Is anyone already experienced in migrating a Magento store to Sylius? And if yes provide some scripts/info on how to tackle it :)

A minimal scope would be orders, products, clients.

**Comment by pjedrzejewski** [comment]
Hi David! I do not know anyone who migrated from Magento to Sylius with all the data. We once used Akeneo to do that. We will definitely look into Migrating guides when we approach 1.0.

Please post this question on StackOverflow - it is the official support channel for Sylius. Just tag your question with "sylius" and maybe someone will be able to help you! http://stackoverflow.com/questions/tagged/sylius

**Comment by dav-m85** [comment]
Question live at [stackoverflow](http://stackoverflow.com/questions/31573843/migrate-from-magento-to-sylius) :coffee:

**Comment by pjedrzejewski** [comment]
We will do our best to provide migration guides soon after release.
