### ISSUE TITLE
Sorting by translatable field (broke Country backend)

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#2961]
I see that sorting translatable fields is still a todo, but it has currently broken things in the backend for:
1) Sorting taxonomy by name
2) The countries page (as it is default sorted by name).

Is there already something in the works?

**Comment by inssein** [comment]
The problem lies within EntityRepository of ResourceBundle.

```PHP
    /**
     * @param QueryBuilder $queryBuilder
     *
     * @return Pagerfanta
     */
    public function getPaginator(QueryBuilder $queryBuilder)
    {
        return new Pagerfanta(new DoctrineORMAdapter($queryBuilder, true, false));
    }
```

The third parameter needs to be true in order to use an output walker for pagination. This is required for all translatable fields.

Does an EntityRepository know whether an Entity is translatable or not? If so, it'd be a simple fix that I can send a PR for.

**Comment by inssein** [comment]
@winzou just fixed #2 with https://github.com/Sylius/Sylius/pull/2987

**Comment by winzou** [comment]
Oh I didn't see this issue. I actually didn't fix anything, just made things working for countries at least.

**Comment by inssein** [comment]
@winzou yeah, you fixed the countries page. It was broken because it was sorting on a translatable field, which is still a todo. I think the countries page will still break if you click on country name label, as it will try sorting by name again.

**Comment by michalmarcinkowski** [comment]
Fixed by https://github.com/Sylius/Sylius/pull/3074
