### ISSUE TITLE
[ContentBundle] Can't use sylius/content-bundle as standalone.

### ISSUE THREAD

**Issue by liverbool** [Sylius/Sylius#2962]
Here's my basic config:
https://github.com/Joypricecorp/balltoro-com/commit/41cc4e8a3ef489007aee048e44fc4f9411ffd018

#### Problem
I'v followed http://symfony.com/doc/master/cmf/book/installation.html#set-up-the-database 
<img width="929" alt="screen shot 2558-07-05 at 15 34 52" src="https://cloud.githubusercontent.com/assets/206804/8510953/76d4021e-232b-11e5-965b-b0cfe624a742.png">

**I try to comment out on `LoadPagesData` file at `Line: 33`**

<img width="822" alt="screen shot 2558-07-05 at 15 37 56" src="https://cloud.githubusercontent.com/assets/206804/8510961/11d544a8-232c-11e5-9dae-dfb6bb637fc4.png">

** And run again**:
<img width="1332" alt="screen shot 2558-07-05 at 15 40 46" src="https://cloud.githubusercontent.com/assets/206804/8510964/442e0480-232c-11e5-9925-20ced028cdf7.png">

Anyone can help :0

@sylius-team @pjedrzejewski

**Comment by liverbool** [comment]
@aramalipoor any suggestion? :)

**Comment by coudenysj** [comment]
@liverbool What happens if you run `php app/console doctrine:phpcr:init:dbal` with the extra paramters `--drop --force`?

You also want to run `php app/console cache:clear` before running the load fixtures command.

**Comment by aramalipoor** [comment]
@liverbool One of my colleagues ran into the same issue a few weeks ago, I'm not sure what went wrong then.

I've used your code from your AppBundle but could not reproduce this error! Try @coudenysj suggestion and make sure your vendors versions is the same as e.g. Sylius.

What line exactly causing this issue?

**Comment by liverbool** [comment]
@coudenysj Thanks for your advice.
@aramalipoor THANKS for **"`make sure your vendors versions is the same as e.g. Sylius.`"**
@pjedrzejewski `ContentBundle` in https://packagist.org/packages/sylius/content-bundle#dev-master still not update `CMF` to `~1.2`.

**Comment by aramalipoor** [comment]
@liverbool You're welcome, I'm happy you've found your issue ;)

**Comment by nmarmon** [comment]
Then is it solved?

**Comment by liverbool** [comment]
@nmarmon Change CMF to ~1.2, It's worked! Confirm.

**Comment by psyray** [comment]
@liverbool 
Could you close the bug plz ;)

**Comment by michalmarcinkowski** [comment]
@psyray shouldn't we update the https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ContentBundle/composer.json to use ~1.2 version before closing this?

**Comment by psyray** [comment]
Yes I will update it

**Comment by psyray** [comment]
OK done, waiting merge

**Comment by liverbool** [comment]
I'm waiting for merge, Thanks @psyray I'll close.

**Comment by nmarmon** [comment]
Great work!
