### ISSUE TITLE
Capifony - Deployment Strategy

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#2966]
I see that Sylius comes with an initial capistrano deployment script. However, it fails to work in numerous ways. I know I had a previous installation working, but there are various issues when deploying for the first time. I am hoping these issues are simple, as perhaps the demo website is deployed with capifony.

When we first deploy the website, I need to set "cache_warmup" and "dump_assetic_assets" to false, otherwise "cap deploy" fails as it tries to talk to the database, which isn't setup yet.

Once I have it deployed the first time, and I run the installation procedure, its all fine.

**Comment by mojzis** [comment]
BTW, capifony doesnt work with the current version of capistrano, so it would probably be better to switch to capistrano/symfony ?

**Comment by Symfomany** [comment]
Can we write an article or a part of documentation with Capifony & usage of Capfile? Thx!

**Comment by Symfomany** [comment]
Existing Docker Image(HUB) official for Sylius with Elastica etc...?

**Comment by Symfomany** [comment]
Use Rocketter to deploy in server :)

http://rocketeer.autopergamene.eu/#/docs/rocketeer/README

**Comment by Symfomany** [comment]
Or Deployer tool:

http://deployer.org/

**Comment by kayue** [comment]
@mojzis I have used both Capistrano 2 and 3. 

Capistrano 2 with Capifony is a lot more friendly as it work out of the box. 

```ruby
# config valid only for current version of Capistrano
lock '3.4.0'

set :application, 'xxx'
set :repo_url, 'xxx'
set :deploy_to, '~/xxx'

# Default value for :linked_files is []
set :linked_files, fetch(:linked_files, []).push(
  'app/config/parameters.yml'
)

# Default value for linked_dirs is []
set :linked_dirs, fetch(:linked_dirs, []).push(
  'app/logs', 
  'app/var', 
  'web/media'
)

# Copy vendor from previous version
set :copy_files, [
  'vendor',
  'node_modules'
]

# Default value for keep_releases is 5
set :keep_releases, 3

namespace :deploy do
  after :updating, 'deploy:update_assets_version'
  after :updated, 'symfony:assetic:dump'
  after :updated, 'deploy:doctrine_migrate'
end
```

Custom tasks:

```
namespace :deploy do
  desc 'Update assets version'
  task :update_assets_version do
    on roles(:app) do
      execute "sed -i 's/\\(assets_version: \\)\\(.*\\)$/\\1 #{Time.now.to_i}/g' #{fetch(:release_path)}/app/config/config.yml"
    end
  end

  desc 'Apply doctrine migrations'
  task :doctrine_migrate do
    invoke "symfony:console", "doctrine:migrations:migrate", "--no-interaction", "app"
  end
end
```

**Comment by webda2l** [comment]
Capistrano 3 is the right way. http://williamdurand.fr/2015/04/11/on-capifony-and-its-future/

**Comment by Symfomany** [comment]
:+1:  @webda2l

**Comment by gperdomor** [comment]
I use Capistrano 3 with Symfony2 and Bower plugin without problem :)

**Comment by Symfomany** [comment]
Capistrano 3 isn't compatible with Capifony ?

**Comment by Symfomany** [comment]
Why doen't use PHP tool like Rocketer http://rocketeer.autopergamene.eu/#/docs/docs/I-Introduction/Getting-started & provide tacks and best practises http://deployer.org/docs/tasks

**Comment by kayue** [comment]
Capistrano 3 don't need Capifony, it has its Symfony module (but it doesn't feature match with Capifony)

I think deployment is completely out of Sylius's scope here.

**Comment by pjedrzejewski** [comment]
Sylius no longer ships with Capistrano scripts by default.
