### ISSUE TITLE
[ResourceBundle] Split translation files by translation domains

### ISSUE THREAD

**Issue by bigfoot90** [Sylius/Sylius#2968]
Split translation files by translation domains, so each bundle has own translation domain.

Just for reference:
Forms: http://symfony.com/doc/current/reference/forms/types/form.html#translation-domain
Views: http://symfony.com/it/doc/current/reference/twig_reference.html#trans-default-domain

**Comment by pjedrzejewski** [comment]
What is the point for that? If I recall correctly we used something like this before and it has been very annoying in maintance and no real benefit. I think messages should stay in ``messages`` and ``validators`` translation domains.
