### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bigfoot90** [Sylius/Sylius#2972]
If the form validation fails the first time, the ```cancel``` button doesn't go to Resource show but remains on the edit/create form.

**Comment by coudenysj** [comment]
This is caused by the usage of HTTP_REFERER as a fallback, to change it, every `create()` and `update()` macro call in the twig files should have parameter (see https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Macros/actions.html.twig).
