### ISSUE TITLE
Wrong currency when using stripe checkout

### ISSUE THREAD

**Issue by carlowens** [Sylius/Sylius#2980]
When trying to checkout a basket using a currency like GBP, when I get to the final payment page, the stripe dialogue box has the correct amount but always uses USD ($ in front of the amount).  I have GBP as my default currency within config.yml and three currencies configured within my admin (GBP, USD and EUR).

Not had a chance to see what the issue is yet but thought id put it on here incase its just something simple I am missing.

This is with version 0.14

**Comment by michalmarcinkowski** [comment]
Should be fixed now.
