### ISSUE TITLE
Remove Locale entity and store enabled locales and default locale in SettingsBundle

### ISSUE THREAD

**Issue by ahmadrabie** [Sylius/Sylius#2981]
I'm not sure but I think we can remove Locale entity since it's only storing an enabled flag and nothing else.

So I think it's possible to store enabled locales (and also the default one) in settings bundle and read from that.

Am I correct or missing something?

**Comment by pjedrzejewski** [comment]
We need to keep the Locale entity as it is needed for some custom configurations and also SettingsBundle currently stores serialized data, which is not easy to search etc. I believe Locale should stay a separate entity.
