### ISSUE TITLE
Adopt Material Design Lite in Sylius backend

### ISSUE THREAD

**Issue by kayue** [Sylius/Sylius#2983]
Just an idea, Google released their Material Design Lite (http://www.getmdl.io/), and I think it will work  on Sylius's backend.

http://www.getmdl.io/templates/dashboard/index.html

We don't want to spend much time on styling backend, and yet we want it looks good. I think MDL does the job.

**Comment by pjedrzejewski** [comment]
I planned to use this one http://materializecss.com/about.html, what do you think? The material design lite looks too basic for our use case.

**Comment by aRn0D** [comment]
@pjedrzejewski It is done students. It does not means it is not bad but we need to think about student vs company support.

**Comment by kayue** [comment]
Since Material Design Lite is an "official" release, I doubt will people continue to maintain materializecss.

On the other hand, [Material Design Lite uses namespaced BEM classes](http://www.getmdl.io/started/index.html#general-rules), which is a very verbose way to name CSS classes compare to Bootstrap. 

I think the biggest blocker is MDL missing a form template, which is essential part of Twitter Bootstrap.

**Comment by foopang** [comment]
I like https://github.com/almasaeed2010/AdminLTE

**Comment by RobertLangore** [comment]
Will materializecss be used? Is it confirmed?
Will it be used both for frontend and backend?
Will it be implemented in version 0.17.0?

**Comment by pjedrzejewski** [comment]
Hey Robert! That was the plan, but due to the fact we are running short on time, I think we will stick to Bootstrap for the backend and just improve the UI we have now. That would also allow us to upgrade easily to Bootstrap4 in the near future.

**Comment by RobertLangore** [comment]
Ok. So I guess bootstrap will also be used for the frontend. Are there any problems if someone uses materializecss for the frontend? Are there bundles (in Sylius) that can generate html code based in boostrap?
Will boostrap also be used in the future (frontend, backed)? Are there any plans to switch to materializecss in the future (time permitting, and maybe when materializecss will be at version 1.0.0)?
