### ISSUE TITLE
Searchable drop down lists does not match choices

### ISSUE THREAD

**Issue by agounaris** [Sylius/Sylius#2984]
Hello there,

The promotions form is not able to load in our app just because we have a lot of variants and the request timeouts, so I'm building a search and autocomplete bundle using the chosen plugin (maybe this will be a nice PR for sylius) and I have an issue matching the selected value during form validation. 
Here are a couple of screenshots...

<img width="500" alt="screenshot 2015-07-09 14 02 49" src="https://cloud.githubusercontent.com/assets/1845809/8595956/678fe158-2644-11e5-94b4-de6a5b07e980.png">

<img width="500" alt="screenshot 2015-07-09 14 03 37" src="https://cloud.githubusercontent.com/assets/1845809/8595970/76f1262a-2644-11e5-8fdd-7ad79c8e2c56.png">

The variant 221407 definitely exists in the database and I have disabled any on top validation from the form, the sylius default validation group, I have tried to set the value with PRE_SUBMIT and POST_SET_DATA events on ContainsProductConfigurationType and many more...but it still fails.

Any idea of what is going wrong will be really helpful and I think this will be a useful bundle for the majority of the sylius users.

**Comment by pjedrzejewski** [comment]
WebBundle has been removed, so this UI is gone.
