### ISSUE TITLE
PromotionType fields are required updating

### ISSUE THREAD

**Issue by rvanlaak** [Sylius/Sylius#2985]
I'm not using the full Sylius stack, but only make use of the `PromotionBundle` and it's dependencies (`Registry`, `MoneyBundle`, `Resource`, `Storage`).

Currently we use `0.14.0` but since that update the form fields of all types (eg. `PromotionType`, `ActionType`, `RuleType`) are set to required again.

The `PromotionType` itself does not seem to be changed, so why are the fields set to required again?
https://github.com/Sylius/Sylius/commits/master/src/Sylius/Bundle/PromotionBundle/Form/Type/PromotionType.php

Because I override the `PromotionType` I can solve this by getting al formFields manually, but this looks like a bug to me:

```php

public function buildForm(FormBuilderInterface $builder, array $options)
{
	parent::buildForm($builder, $options);

	$startsAt = $builder->get('startsAt');
	$options = array_merge($startsAt->getOptions(), array('required' => false));
	$builder->add('startsAt', 'datetime', $options);
    // ...

```

Tried to narrow this down to a specific commit, but unfortunately was not able to do this. Did already exclude the upgrade from symfony 2.6.4 to 2.7.1 as the cause of the problem. The problem was introduced somewhere between the following an `0.14.0`:

    "sylius/resource-bundle": "dev-master#ada589b",

Extending the type and globally setting required to false was enough before:

```php
    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver);

        $resolver->setDefaults(array(
	        'required' => false,
        ));
    }
```

**Comment by Rvanlaak** [comment]
The problem lies in the new `configureOptions` that was introduced in `2.7`. Renaming it back to `setDefaultOptions` solves this.

**Comment by pjedrzejewski** [comment]
Sylius now requires 2.7.

**Comment by rvanlaak** [comment]
Great! Why don't support the 2.8 LTS version, which API should be the same?

**Comment by pjedrzejewski** [comment]
2.7 is minimum, should work with 2.8. :)
