### ISSUE TITLE
Sample data can't be loaded if intl extension isn't installed

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#3000]
`sylius:install` throws an exception while trying to load sample data if intl extension isn't installed.

Sample data should not require intl extension or intl extension should be required/suggested :)

**Comment by kayue** [comment]
intl extension is required by Symfony I think.

**Comment by pamil** [comment]
@kayue Symfony provides `intl` replacement for `en` locale only in [Intl component](https://github.com/symfony/symfony/tree/2.8/src/Symfony/Component/Intl).

**Comment by Symfomany** [comment]
Yes for __toSTring implement foe example, install intl module php5-intl for internationalisation
