### ISSUE TITLE
Error filters taxonomy - Home page (Taxon has no field or association named name)

### ISSUE THREAD

**Issue by jgcabral** [Sylius/Sylius#3004]
When i want to filter by some category proyect throw me exception: 

[Semantical Error] line 0, col 107 near 'name = :taxo': Error: Class Sylius\Component\Core\Model\Taxon has no field or association named name.

Sorry if topic is mistake.

Thanks.

**Comment by Symfomany** [comment]
Yes me too :)
![capture du 2015-07-15 16 12 11](https://cloud.githubusercontent.com/assets/1421325/8700481/4a34ea82-2b0c-11e5-935e-be9ebca9a261.png)

**Comment by nmarmon** [comment]
Can you provide the situation in which the error occurs, please? Step by step, because I have use the taxonomies, but not  the filters.

**Comment by pjedrzejewski** [comment]
This is because translatable field has been moved to taxon translation. We should update the configuration or repository. Thank you for reporting!

**Comment by jgcabral** [comment]
Thanks pjedrzejewski. I was thinking solve other way but if already exists fix for issue is great.

**Comment by pjedrzejewski** [comment]
@jgcabral Issue is not fixed yet, you can have a look and submit a PR if you find time. I will appreciate it! Thanks!
