### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by cordoval** [Sylius/Sylius#3007]
if someone installs not the fixtures and sets the locale to just en when creating a product gives errors because the translation table lacks a not null name, weird

**Comment by Symfomany** [comment]
Look at sylius_locale parameter && install your assets with:
"scripts": {
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Symfony\\Cmf\\Bundle\\CreateBundle\\Composer\\ScriptHandler::downloadCreateAndCkeditor",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Symfony\\Cmf\\Bundle\\CreateBundle\\Composer\\ScriptHandler::downloadCreate"

        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Symfony\\Cmf\\Bundle\\CreateBundle\\Composer\\ScriptHandler::downloadCreateAndCkeditor",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Symfony\\Cmf\\Bundle\\CreateBundle\\Composer\\ScriptHandler::downloadCreate"

        ]
    },


php app/console sylius:install:assets
&& composer update 

Look here:
http://docs.sylius.org/en/latest/book/installation.html

**Comment by cordoval** [comment]
yeah probably because the assets did not install correctly because the bergie/create does not install properly for some reason.

**Comment by Symfomany** [comment]
Yes :)

**Comment by pjedrzejewski** [comment]
Most of locale related issues will be fixed with https://github.com/Sylius/Sylius/pull/3104.
