### ISSUE TITLE
recommendations are not clear

### ISSUE THREAD

**Issue by cordoval** [Sylius/Sylius#3008]
```bash
equirements --env=prod
+-------------------------------+---------------------------------------------------------------------+
| Issue                         | Recommendation                                                      |
+-------------------------------+---------------------------------------------------------------------+
| short_open_tag                |                                                                     |
| session.auto_start            |                                                                     |
| sylius.extensions.accelerator | Install and enable a PHP accelerator like APC (highly recommended). |
+-------------------------------+--------------------
```

not sure what the recommendation is here, is obvious for someone that knows but ...

**Comment by Symfomany** [comment]
![Uploading Capture du 2015-07-15 16:02:15.png…]()
apt-get install php-apc 
&& 

; configuration for php apc module  
extension=apc.so  
apc.shm_size=100

**Comment by Symfomany** [comment]
![capture du 2015-07-15 16 02 15](https://cloud.githubusercontent.com/assets/1421325/8700254/05da669c-2b0b-11e5-86b2-fe39269e7cdc.png)

**Comment by cordoval** [comment]
that is for apc, i am talking about the others as well

**Comment by Symfomany** [comment]
Documentation is comming...:) his translate too :p

**Comment by cordoval** [comment]
this is not documentation if you read the description. The columns under the Recommendation head are empty. That is a bug.

**Comment by michalmarcinkowski** [comment]
Should be fixed now.
