### ISSUE TITLE
Does Cookie storage actually persist?

### ISSUE THREAD

**Issue by kayue** [Sylius/Sylius#3009]
CookieStorage's set method only set data to the request's cookies header, I think the data won't persist until we set cookie in the HTTP respond. Am I missing anything?

https://github.com/Sylius/Sylius/blob/0c15f8353e5c70817d7d4d23c5ff53eccd4f8015/src/Sylius/Component/Storage/CookieStorage.php

/cc @stloyd

**Comment by kayue** [comment]
Generally I think we need to attach the cookie to Respond:

```php
    public function __construct(EventDispatcherInterface $eventDispatcher, $cookieDomain)
    {
        $this->eventDispatcher = $eventDispatcher;
        $this->cookieDomain = $cookieDomain;
    }

    public function setData($key, $value)
    {
        parent::setData($key, $value);

        $this->eventDispatcher->addListener('kernel.response', function (FilterResponseEvent $event) use ($value) {
            $event->getResponse()->headers->setCookie(
                new Cookie('key', $value, new \DateTime('+1 days'), '/', $this->cookieDomain, false, false)
            );
        });
    }
```

**Comment by pjedrzejewski** [comment]
@stloyd Could you clarify this? I think it does not work at all right now.

**Comment by winzou** [comment]
I confirm the CookieStorage is wrong right now.

@kayue can you please provide PR for your code snippet? It seems fine to me.

**Comment by kayue** [comment]
@winzou OK~

**Comment by lologhi** [comment]
:+1:
