### ISSUE TITLE
Ability to reorder product images

### ISSUE THREAD

**Issue by liviucmg** [Sylius/Sylius#3012]
One should be able to reorder a product's images using a drag-n-drop mechanism, using something like [jQuery UI Sortable](https://jqueryui.com/sortable/).

**Comment by liviucmg** [comment]
If I manage to find some time for this, will you accept a PR?

**Comment by pjedrzejewski** [comment]
@liviucmg Of course! That would just awesome. :)

**Comment by pjedrzejewski** [comment]
But please consider #2975 as it changes a lot regarding media management.

**Comment by stefantalen** [comment]
Any change this might make it to the roadmap?
