### ISSUE TITLE
Ability to pick product thumbnail from list of images

### ISSUE THREAD

**Issue by liviucmg** [Sylius/Sylius#3013]
From what I can tell, Sylius always picks the first image as the product's thumbnail. There should be a "Use this as thumbnail" column with radio options.

**Comment by liviucmg** [comment]
If I manage to find some time for this, will you accept a PR? :)

**Comment by liviucmg** [comment]
Bump. :)

**Comment by pjedrzejewski** [comment]
@liviucmg Definitely! Already commented this in another issue, but remember to have a look at #2975.

**Comment by michalmarcinkowski** [comment]
Now you can assign `code` to image and get specific image in the template. Using `thumbnail` code will make this image display as thumbnail :)
