### ISSUE TITLE
Request Object will be removed in 3.0!

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3016]
Warning:

Doesn't use $this to get Request Objet:
$request = $this->getRequest();

It's not compatible with sf 3.0

Use (Request $request) scope in your actions.

**Comment by Symfomany** [comment]
To solve this issue, add getRequest() in ResourcesController like:

  public function getRequest()
    {

        return $this->container->get('request_stack')->getCurrentRequest();
    }

**Comment by kayue** [comment]
@Symfomany `request_stack` is not available in Symfony 2.3

So we probably should upgrade to 2.7 first..

**Comment by Symfomany** [comment]
Upgrade my Sf2 in 2.7 :)

**Comment by pjedrzejewski** [comment]
No need to point out all the things in issue, we should take care of all of them when we start the migration.
