### ISSUE TITLE
Use Var DUmper Componant for Debug

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3020]
In this solution, there are huge objects. To debug, you 
![capture du 2015-07-15 23 04 03](https://cloud.githubusercontent.com/assets/1421325/8709865/d2931da2-2b45-11e5-9e5f-4f9e69610060.png)

**Comment by Symfomany** [comment]
Require this componants http://symfony.com/doc/current/components/var_dumper/introduction.html

**Comment by kayue** [comment]
xdebug does the same already, no need to include it in Sylius.

**Comment by Symfomany** [comment]
Var Dumper is more prettify  :+1: 
If you’re an Xdebug user, you’re probably used to a slightly better looking output than the raw PHP prints. Still, few good solutions existed that beautified this output for us enough to make it worth installing a dev dependency. Until VarDumper.

**Comment by Symfomany** [comment]
Sorry, it's stay better than XDEBUG...and more prettify :)
![capture du 2015-07-17 16 27 46](https://cloud.githubusercontent.com/assets/1421325/8749273/e0837c7a-2ca0-11e5-82d2-953f43472a27.png)

**Comment by tom10271** [comment]
You may configure your IDE to listen for xdebug event. You can set break points and once PHP run it, you can view the complete callstack and variables' value etc. Keeps dumping variable is kind of painful in debugging.

**Comment by kayue** [comment]
@Symfomany I think Sylius's core shouldn't be opinionated on what debug tool to use.

**Comment by armababy** [comment]
Definitely last thing you want is to have is anything forced in your work cycle. This does look like single scenario case.
