### ISSUE TITLE
Cron - Documentation

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#3024]
I can see that there are about three commands that need to run every now and then (depending on configuration):
- sylius:cart:purge
- sylius:order:purge
- sylius:order:release

Are the above correct? Am I missing any?

Finally, what section of the docs does this belong in? Perhaps I could write it.

**Comment by inssein** [comment]
ping @michalmarcinkowski @pjedrzejewski

**Comment by pjedrzejewski** [comment]
@inssein I think this should be in the installation notes, but I'd like to have a single cron command and use something like #1580 for Sylius tasks and custom commands.

**Comment by inssein** [comment]
Ah okay. For anyone wondering, I am using https://github.com/yzalis/Crontab for now, and setup cron through my own installation command.
