### ISSUE TITLE
Use Voters or ACL 

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3026]
Use Voters or ACL to verify in CRUD is object (taxo, product,...) is mine no?

**Comment by kayue** [comment]
Sylius has RBAC implemented already.

**Comment by Symfomany** [comment]
This is it ?
 https://github.com/Sylius/SyliusRbacBundle

**Comment by steffenbrem** [comment]
@kayue But can you also say that you can only view certain objects that are yours with the RBAC system?

**Comment by Symfomany** [comment]
Yes like Voters for example or ACLs :+1:

**Comment by kayue** [comment]
@steffenbrem Right. 

Not sure what is your use case tho.

**Comment by jimbocoder** [comment]
An example use case would be allowing API users to view order details for orders they created.  RBAC will require the "show order" permission, but I believe that would imply that the user can show all orders.

That said, there's nothing stopping a developer using Sylius from adding such voters himself (I do exactly this).  I have mixed opinions whether this belongs in the Sylius project core, but I lean towards yes.  Running voters adds a lot of extra processing to the authorization layer, so perhaps it could be configurable.  It would give Sylius a concept of "data ownership" though which is pretty important for any suitably generic API.

:+1:

**Comment by steffenbrem** [comment]
@kayue exactly what @jimbocoder is saying.

**Comment by gperdomor** [comment]
Maybe one solution for simple permissions could be use doctrine blameable extension and use the repository to get only the entities based on the createdBy field of each entity... But, this is a problem when multiple users need permission for the same resource, like a group of users for example

**Comment by kayue** [comment]
I agree. 

I think it is just matter of where to add ACL, controller or routing config. 

Voter is slow so I prefer not to call it too often.
