### ISSUE TITLE
Bug in sort Designation of products in back-office

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3027]
http://localhost:8000/administration/products/?sorting%5Bname%5D=asc

I've 500 error in product when i sort all products by Designation (title)

![capture du 2015-07-16 12 03 07](https://cloud.githubusercontent.com/assets/1421325/8720387/b9cdd04c-2bb2-11e5-96e8-d55b9fe75396.png)

**Comment by nmarmon** [comment]
Can you specify the problem? Give an example of how you do it, and then it fails.
