### ISSUE TITLE
Incomplete translation for French

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3034]
Hye everyone!

I contribute to translate all Sylius CMF for french people in french language...other french to make that?

@winzou you too ? :)

Thx for all frenchies to advance ...

**Comment by Symfomany** [comment]
![capture du 2015-07-16 14 05 45](https://cloud.githubusercontent.com/assets/1421325/8722350/0738ed88-2bc4-11e5-98be-8d45925d9da9.png)

**Comment by Symfomany** [comment]
Globally, in all backend , missing < 200 translations for french .... go ahead! :)
![capture du 2015-07-16 14 10 34](https://cloud.githubusercontent.com/assets/1421325/8722393/7eb3e926-2bc4-11e5-8bfe-fc0106294e82.png)

**Comment by lce-fr** [comment]
Hi ! I am trying Sylius for a client, I will definitely add some if I choose to keep using it !

**Comment by pjedrzejewski** [comment]
Translation process happens on translate.sylius.org!
