### ISSUE TITLE
Phpspec:  67 broken with methods not found in Models

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3037]
There are methods not defined in Models?

![capture du 2015-07-16 14 49 15](https://cloud.githubusercontent.com/assets/1421325/8722937/fe089d16-2bc9-11e5-9575-c2f090429e80.png)

**Comment by michalmarcinkowski** [comment]
``` ShippingMethodTranslation ``` doesn't have ``` ShippingMethod ``` class methods. It only has translatable fields (in this case ``` name ```). All Sylius' specs are green.
