### ISSUE TITLE
[Proposal] New Backend Theme & WebBundle for Sylius E-Commerce 

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3041]
I purpose in my App a new theme for Admin based on Responsive Boostrap Theme  

+ New Menu
+ New Assets
+ New Widgets
+ New VIews
+ New Macros
+ New Form Theme
+ New Layouts

See folloging screenshots:

![capture du 2015-07-16 17 31 19](https://cloud.githubusercontent.com/assets/1421325/8727648/1fa1795e-2be1-11e5-9523-3b6715ad516b.png)

![capture du 2015-07-16 17 33 31](https://cloud.githubusercontent.com/assets/1421325/8727650/2449242a-2be1-11e5-9871-3316f013608c.png)
![capture du 2015-07-16 17 33 38](https://cloud.githubusercontent.com/assets/1421325/8727651/24612dc2-2be1-11e5-84e9-eaa5916e5b71.png)
![capture du 2015-07-16 17 33 43](https://cloud.githubusercontent.com/assets/1421325/8727652/2470ef6e-2be1-11e5-9151-4b6b55e32126.png)
![capture du 2015-07-16 17 33 49](https://cloud.githubusercontent.com/assets/1421325/8727653/247455dc-2be1-11e5-801a-34612ccb960f.png)
![capture du 2015-07-16 17 33 55](https://cloud.githubusercontent.com/assets/1421325/8727654/2475e988-2be1-11e5-808c-96e5bffbb17f.png)
![capture du 2015-07-16 17 34 00](https://cloud.githubusercontent.com/assets/1421325/8727655/24781bb8-2be1-11e5-89ea-027aca269b08.png)
![capture du 2015-07-16 17 34 12](https://cloud.githubusercontent.com/assets/1421325/8727656/247b7e8e-2be1-11e5-9432-3209cfaa4058.png)
![capture du 2015-07-16 17 34 22](https://cloud.githubusercontent.com/assets/1421325/8727657/2482fdd0-2be1-11e5-954f-8ac78f4109c7.png)
![capture du 2015-07-16 17 34 26](https://cloud.githubusercontent.com/assets/1421325/8727658/248a51de-2be1-11e5-8441-913a921d9680.png)
![capture du 2015-07-16 17 34 40](https://cloud.githubusercontent.com/assets/1421325/8727659/248def42-2be1-11e5-8262-dcf5c50c0b96.png)
![capture du 2015-07-16 17 34 48](https://cloud.githubusercontent.com/assets/1421325/8727661/24933560-2be1-11e5-8c8d-d7cb0c96216b.png)
![capture du 2015-07-16 17 34 54](https://cloud.githubusercontent.com/assets/1421325/8727660/249272c4-2be1-11e5-9a08-d285725c4169.png)
![capture du 2015-07-16 17 34 59](https://cloud.githubusercontent.com/assets/1421325/8727662/249a5a34-2be1-11e5-80ab-08cbf873a9a7.png)
![Uploading Capture du 2015-07-16 17:35:06.png…](r)

**Comment by tedawebguy** [comment]
What about using [AdminLTE](https://almsaeedstudio.com/themes/AdminLTE/index2.html)? It looks fairly slick.

**Comment by pjedrzejewski** [comment]
Things like this should be discussed beforehand, don't you think? Also, are you using a MIT compatible theme? It looks like proprietary template from shop. We are going to rework Sylius admin with materializecss framework.
