### ISSUE TITLE
Use render() in ajax with hinclude for huge requests like stats

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3043]
Use Asynchronous Content with hinclude.js
Controllers can be embedded asynchronously using the hinclude.js JavaScript library.

http://symfony.com/fr/doc/current/book/templating.html

{{ render_hinclude(controller('...')) }}
{{ render_hinclude(url('...')) }}

**Comment by Strontium-90** [comment]
Using [pjax](/defunkt/jquery-pjax) for loading only body all pages will increase speed greatly!

**Comment by Symfomany** [comment]
Hinclude is nativly supported :)

{% render '...:news' with {}, {'standalone': 'js'} %}

# app/config/config.yml
framework:
    # ...
    templating:
        hinclude_default_template: AcmeDemoBundle::hinclude.html.twig

http://symfony.com/fr/doc/current/book/templating.html#contenu-asynchrone-avec-hinclude-js

**Comment by Strontium-90** [comment]
> Hinclude is nativly supported :)

Can you submit form by hinclude?

**Comment by Symfomany** [comment]
JUst render content & block with tag HTML with hx:include. It's very fast & easy :)

http://mnot.github.io/hinclude/

**Comment by pjedrzejewski** [comment]
This is something to consider later, when we work on the frontend. Closing this for now.
