### ISSUE TITLE
Use Annotation Format to metada of Entities Model

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3044]
In Best Praticies, Communauty has recommanded to use annotation format to handle metadatas of columns in Models 
Annotations are by far the most convenient and agile way of setting up and looking for mapping
information.

http://symfony.com/pdf/Symfony_best_practices_2.7.pdf?v=4

**Comment by Strontium-90** [comment]
Annotations is simply, but it does not follow IoC pattern.

**Comment by aRn0D** [comment]
We don't use annotations because the models are generics, they can be use with an ORm and ODM. Thanks for feedback.
