### ISSUE TITLE
Use BCRYPT instead of SHA512

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3045]
It's recommanded to use BCRYPT(most recents) instead of SHA512 for encoders to encode password in security

http://symfony.com/fr/doc/current/reference/configuration/security.html#utiliser-l-encodeur-bcrypt

**Comment by Symfomany** [comment]
If your users have a password, then we recommend encoding it using the bcrypt encoder, instead of the
traditional SHA-512 hashing encoder. The main advantages of bcrypt are the inclusion of a salt value to
protect against rainbow table attacks, and its adaptive nature, which allows to make it slower to remain
resistant to brute-force search attacks.
With this in mind, here is the authentication setup from our application, which uses a login form to load
users from the database:

**Comment by steffenbrem** [comment]
I am using `bcrypt` too with Sylius and wanted to mention that you want to use `setPassword` in test fixtures to skip the long encryption and so speed up the tests. Are there any plans to make Sylius use `bcrypt` by default?

**Comment by steffenbrem** [comment]
@pjedrzejewski Any plans on introducing this?

**Comment by teohhanhui** [comment]
This is a security risk. :disappointed:

**Comment by teohhanhui** [comment]
https://security.stackexchange.com/questions/52041/is-using-sha-512-for-storing-passwords-tolerable

**Comment by psihius** [comment]
Sylius does not use `password_hash` to store passwords?

It should...

**Comment by pamil** [comment]
Yeah, it would be great to have it in 1.2, but we have to provide the full migration path for existing users.

**Comment by pamil** [comment]
I've opened #9560 to coordinate further efforts, let's make it happen in v1.3.0 release 🎉
