### ISSUE TITLE
Best practise: use $form->isSubmitted() 

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3046]
In your validation form, use $form->isSubmitted()  in addition to $form->isValid()

Ex: Line 70 in CartController
        if ($form->handleRequest($request)->isValid()) {...}

This isn't technically needed, since isValid() first calls isSubmitted().
But without this, the flow doesn't read well as it looks like the form is always processed (even on the GET request).

**Comment by michalmarcinkowski** [comment]
That is common practice. It's logical that the form cannot be processed on a GET request. I don't see any benefit of using ``` isSubmitted ``` method.
