### ISSUE TITLE
Use ParamConverter instead of findOr404() in your controller of ResourcesBundle

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3047]
It's recommanded to use ParamConverter in ResourcesController instead of findOr404() with criterias and implement dynamycally Param hinting

http://symfony.com/fr/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html

**Comment by okwinza** [comment]
@Symfomany , if you don't mind me asking but do you even sleep? :)

**Comment by Symfomany** [comment]
:+1:

**Comment by aRn0D** [comment]
What do you mean? Using it like that? it is impossible because the `ResourceController` is generic, it works for every models.

**Comment by Symfomany** [comment]
Interface hinting like ModelInterface or create ParamConverter by implements  ParamConverterInterface with supports() no?

**Comment by Symfomany** [comment]
http://stfalcon.com/en/blog/post/symfony2-custom-paramconverter

**Comment by Strontium-90** [comment]
Resource controller is configured by yml. No need annotations here.

**Comment by bigfoot90** [comment]
@aRn0D You should allow to put the model's interface into the ParamConverter's class attribute, and then resolve the interface like you do with the doctrine entity relations.

**Comment by pjedrzejewski** [comment]
We do not use annotations.
