### ISSUE TITLE
Whats is the best practise to begin a new E-commerce project...?

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3049]
Whats is the best practise to begin a new E-commerce project...?
Create Bundles ? Create a new Namespace ? Override some layers of Bundles? Modify Bundles ? Modify Components?

Whats are steps to create a new project?

**Comment by Symfomany** [comment]
Example: To begin, Override WebBundle in DashboardController in my Bundle with config ? (http://docs.sylius.org/en/latest/bundles/general/overriding_controllers.html)

**Comment by kayue** [comment]
Run as it is, override only if needed...

**Comment by Symfomany** [comment]
Thx! How can you override DashboardController in WebBundle for example? You write directly in this bundle?

**Comment by kayue** [comment]
@Symfomany One option is to override the route, point it to your own controller. If it is from resource bundle then you can change the config in `sylius.yml`, or override the service.

**Comment by Symfomany** [comment]
Okay so, i juste configure like that for example to override:
sylius_web:
    driver: doctrine/orm
    classes:
        backend:
            dashboard:
                controller: Sylius\BackendBundle\Controller\DashboardController

and call in routing:
sylius_dashboard:
    path:     /main
    defaults: { _controller: sylius.controller.backend.dashboard:mainAction }

**Comment by kayue** [comment]
so this can be close now? :)

**Comment by Symfomany** [comment]
Yes its is juste for everyone who beginning in Sylius :) Thx @kayue
