### ISSUE TITLE
Add methods in OrderRepository and not override

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3051]
What is the best practise if i want to add methods in OrderRepository and not override this to use after  in service? create a parent service? an absract common service?

**Comment by kayue** [comment]
Why not override?

**Comment by Symfomany** [comment]
Because i want to keep all methods implemanted by Sylius :)

**Comment by tom10271** [comment]
Overrides and extends extends from the original one may be?

**Comment by kayue** [comment]
@Symfomany If you are adding method then it is not implemented by Sylius anymore... 

I think override / extend is the solution.

**Comment by Symfomany** [comment]
Example: It's missing in ProductRepository method which count all product, i write in ProductRepository or how extends this?
![capture du 2015-07-17 16 58 40](https://cloud.githubusercontent.com/assets/1421325/8750000/38839a3c-2ca5-11e5-97b4-26892a2ae575.png)

**Comment by Symfomany** [comment]
Or Dynamucally implemented in EntityRepository class in Sylius\Bundle\ResourceBundle\Doctrine\ORM

**Comment by tom10271** [comment]
Set your own repository in sylius.yml and then inside your repository class extend it from the default sylius' one

**Comment by Symfomany** [comment]
Yess in my config.yml :+1:

**Comment by steffenbrem** [comment]
@Symfomany http://docs.sylius.org/en/latest/bundles/general/overriding_repositories.html

**Comment by kayue** [comment]
@Symfomany I think this can be close now.
