### ISSUE TITLE
Notice: Undefined index: percent

### ISSUE THREAD

**Issue by Buri** [Sylius/Sylius#3052]
in vendor/sylius/sylius/src/Sylius/Component/Payment/Calculator/PercentFeeCalculator.php at line 29

**Comment by Symfomany** [comment]
Yes i have same issue when i go to payment step in frontend

**Comment by nmarmon** [comment]
Can you explain the steps you do to get this error, please?

**Comment by pjedrzejewski** [comment]
@Buri Could you help us reproduce this issue? Thanks!

**Comment by michalmarcinkowski** [comment]
This issue is probably caused by https://github.com/Sylius/Sylius/issues/3131

**Comment by Buri** [comment]
Sorry for late feedback, yes those two are indeed related. This is also possible when creating payments via fixtures.

**Comment by Zubis** [comment]
hi guys,

I had the same problem but I fixed it by changing the *sylius_payment_method* table. I added the index percent in the column *fee_calculator_configuration* like this:
 
**a: 2: {s: 7: "percent"; i: 1; s: 6: "amount"; i: 1;}**

it's a temporary fix, but it works perfectly well to bypass the problem ;)

**Comment by michalmarcinkowski** [comment]
After #3348, it shouldn't occur any more.
