### ISSUE TITLE
Not choice language when create taxonomy

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3057]
I'm a french and I don't have choice to write in english my taxonomy.. What is the configuration for french?

![capture du 2015-07-17 17 14 25](https://cloud.githubusercontent.com/assets/1421325/8750393/5c34e664-2ca7-11e5-9c30-6025dd6f7828.png)

**Comment by Symfomany** [comment]
Then, when i want to create a product with my taxonomy written in english... :)
![capture du 2015-07-17 17 16 49](https://cloud.githubusercontent.com/assets/1421325/8750450/b27e0816-2ca7-11e5-855b-a99ae8e4873d.png)

**Comment by Symfomany** [comment]
Taxon & Taxonomy translation write in en_GB in my database ....

**Comment by gperdomor** [comment]
french locale is created?... I created a new taxonomy and taxon on a fresh sylius install and i don't get the __toString related errors...

**Comment by Symfomany** [comment]
french locale ya ! Do you have a link to your project on github based on Sylius in french please?

**Comment by nicolasricci** [comment]
@Symfomany are you sure your french locale is created in ```/administration/locales/```?

**Comment by gperdomor** [comment]
@Symfomany no, but verify that French locale is created and enabled in /administration/locales/ like @nicolasricci says...

**Comment by soifou** [comment]
as @gperdomor and @nicolasricci said, you have to create/enable your french locale in `administration/locales/`

not an issue at all...
