### ISSUE TITLE
Bug in create product

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3058]
I don't add image & attributs when i create a product 
![capture du 2015-07-17 17 21 29](https://cloud.githubusercontent.com/assets/1421325/8750577/86150e2c-2ca8-11e5-9bf6-dca1f255021f.png)
![capture du 2015-07-17 17 21 49](https://cloud.githubusercontent.com/assets/1421325/8750578/86173026-2ca8-11e5-8639-4607ed4bcbd2.png)

**Comment by umpirsky** [comment]
@Symfomany Thanks for reporting. Can you please describe your scenario, what happens, and what you expect instead? I don't quite understand the issue.

**Comment by Symfomany** [comment]
Wgen i'm going to new product action, & i click on image tab to handle images of product , i have nothing to add an image in the product added

**Comment by nmarmon** [comment]
Maybe it can be a problem of privileges?

**Comment by Symfomany** [comment]
But no, i think this issue is about translation in form...

**Comment by nmarmon** [comment]
**Attributes:** In the sidebar menu, go to *ASSORTMENTS->Configure attributes* and define some ones. Then go to products, create one and in tab "attributes" click on button "ADD" and select one from the drop-down menu that will appear. Finally "save changes"

**Images:** go to "web" folder and create one which name is "media". Give all privileges to that folder, and return to sylius. There, when you create a product, select tab "images" and click on "ADD IMAGE". Click then on "Choose file", and select one. Save it.

In images, probably when you select one, it doesn't appear when you choose her, but when you save, it appears in the registry of the product. Try it.

I don't know how can influence the translation. Tell if the lines above help you.
