### ISSUE TITLE
Use nelmio/alice instead fzaninotto/Faker

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3060]
For fixtures installation, we can use nelmio/alice . It gives you a few essential tools to make it very easy to generate complex data with constraints in a readable and easy to edit way

**Comment by jimbocoder** [comment]
Is there a particular advantage over faker you have in mind?  Not sure it's worth the effort to rewrite what is ultimately pretty non-essential code, unless there's some deficiency right now.

**Comment by pjedrzejewski** [comment]
Alice has been discussed already, it hardcodes model classes and makes fixtures useless if you modify any of your models. We won't use it for now.
