### ISSUE TITLE
Invoice Genetarion

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#3064]
I see that knp/snappy is configured to generate invoices, but I ran into a lot of problems, and it still doesn't work for me. Has anybody had success setting it up?

The current problem I am up against is that assets are all relative in the layout (css, js), and they can't be found by wkhtmltopdf (because we first render the html, save it to a file, and pass the file along to wkhtmltopdf, at which point relative urls make no sense).

Also, does anyone know why the invoice is not available until the order is shipped? You can view the same information when you view the details of the order, whats the difference?

Edit: the demo site should be having the same problems.

**Comment by inssein** [comment]
I found the solution to my last problem, but I got another problem

Solution to relative paths:
Include a <base> tag (```<base href="{{ app.request.scheme ~ '://' ~ app.request.httpHost }}" />```)

New Problem: OrderController uses ->renderView which directly references the template, and doesn't allow for template inheritance.

**Comment by inssein** [comment]
Summary:
* Install wkhtmltopdf using the static binaries provided on their website. On CentOS 7, the wkhtmltopdf that came with epel didn't work. (Problems with unpatched qt?). This also installs wkhtmltopdf inside /usr/local/bin, so you have to adjust the knp snappy bundle configuration to point to the right path.
* Ensure <base> tag is properly setup
* Override invoice template and set it up accordingly.

**Comment by kayue** [comment]
@inssein In my project I just render in HTML and admin will save as PDF.... just fyi

**Comment by pjedrzejewski** [comment]
@inssein Yes, there are some issues with wkhtmltopdf on some distributions. But Sylius implementation seems to be ok, it just needs to be properly installed.
