### ISSUE TITLE
[RFC] Renaming Country::isoName to more appropriate name

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#3066]
Right now, `Country::isoName` contains country codes from [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).

It's rather not a fortunate name, so I'm thinking about refactoring `isoName` to `isoCode`, `countryCode` or simply `code`. What do you think about that? Which name do you prefer?

**Comment by michalmarcinkowski** [comment]
We will introduce ``` code ``` field for most entities, in order to uniquely identify objects during import/export or API calls from other systems. IMO we could change this field to be simply ``` code ```. @Sylius/core-team ?

**Comment by Symfomany** [comment]
:+1:  @michalmarcinkowski

**Comment by kayue** [comment]
+1 for `code`

**Comment by pamil** [comment]
:+1: `code`

**Comment by gperdomor** [comment]
+1 for <code>code</code> too

**Comment by patrick-mcdougle** [comment]
I personally like isoCode because it reminds us that the values we place in there should be taken from the ISO 3166-1 alpha-2 standard and shouldn't be just any old abbreviation.

**Comment by pjedrzejewski** [comment]
``code`` it is then! :+1:

**Comment by pamil** [comment]
Fixed by #3696.
