### ISSUE TITLE
Mock AbstractQuery to test setFirstResult() and setMaxResults()

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3068]
Whith Phpspec, I don't Mock AbstractQuery to test setFirstResult() and setMaxResults() ?

Not Query because this is a Final Class...

![capture du 2015-07-20 17 27 04](https://cloud.githubusercontent.com/assets/1421325/8779627/8ef81d3c-2f04-11e5-986b-37c4de3a4938.png)

Any idea?

**Comment by Symfomany** [comment]
https://gitter.im/DashboardHub/PipelineDashboard/archives/2015/03/16

It would be seem the same issue with phpspec...

**Comment by Symfomany** [comment]
This is my code:

   function it_get_adverts(
        $em,
        QueryBuilder $builder,
        AbstractQuery $query,
        FilterCollection $filterCollection,
        Expr $expr,
        EntityRepository $er,
        ArrayCollection $arrayCollection,
        Paginator $paginator
    ){

        $em->createQueryBuilder()->shouldBeCalled()->willReturn($builder);


        $builder->select('a')->shouldBeCalled()->willReturn($builder);
        $builder->from(null, "a", null)->shouldBeCalled()->willReturn($builder);
        $builder->leftJoin('a.image', 'i')->shouldBeCalled()->willReturn($builder);
        $builder->addSelect('i')->shouldBeCalled()->willReturn($builder);
        $builder->leftJoin('a.categories', 'c')->shouldBeCalled()->willReturn($builder);
        $builder->addSelect('c')->shouldBeCalled()->willReturn($builder);
        $builder->orderBy('a.date', 'DESC')->shouldBeCalled()->willReturn($builder);
        $builder->getQuery()->shouldBeCalled()->willReturn($query);
        $query->setFirstResult(1)->shouldBeCalled()->willReturn($builder);
        $query->setMaxResults(20)->shouldBeCalled()->willReturn($builder);

        $this->getAdverts(1,20)->willReturn($paginator);
    }

**Comment by steffenbrem** [comment]
@Symfomany The `AbstractQuery` does not have the method `setFirstResult` and indeed the `Query` is final so it cannot be extended by `phpspec`, hence the error. Since you are using an external library (Doctrine), it would be better I think to write an integration test for it instead of a unit test.

**Comment by Symfomany** [comment]
Okay so you advice me to use Behat integration test for my repository's method ?

How do you write with a real object Query with willReturn() method? Can you write some example with my code please?

**Comment by steffenbrem** [comment]
@Symfomany Hi, well using a real `Query` object will require a lot of stubbing and since Doctrine is quit complex, you will soon find out that you are testing Doctrine's behaviour, rather than stuff you own. The `Query` object requires the `EntityManager`, so you will need to stub the internals of how the `EntityManager` interacts with the `Query` class. I will not recommend you doing this.

While I am not an expert with using phpspec and behat I do know that it is bad practise to test code you do not own. I think it is better to look on how you can write an integration test for it using Behat for example.

**Comment by Symfomany** [comment]
He confirmed: https://twitter.com/Stof70/with_replies?lang=fr:

Christophe Coevoet ‏@Stof70  35 minil y a 35 minutes 
@Symfomany don't mock Doctrine in your specs. You don't own its API, which mean you cannot guarantee your double works the same

**Comment by Symfomany** [comment]
:+1:  @steffenbrem

**Comment by Symfomany** [comment]
I'm sorry really:
I should use Functional Testing :)

http://symfony.com/doc/current/cookbook/testing/doctrine.html

First : "Unit testing Doctrine repositories in a Symfony project is not recommended"

**Comment by steffenbrem** [comment]
@Symfomany Ah nice, good to know I was not wrong :+1:. I am also learning the art of testing everything correctly. And yeah I've read that post on the symfony website too. It feels better to do it that way.

**Comment by Symfomany** [comment]
Thx @steffenbrem ! But like a Controller Class...With Behat !

**Comment by steffenbrem** [comment]
@Symfomany Yeah you just instantiate the whole thing. A plusside is that the actual query is fired, so you know if you made a mistake messing up a many-to-many relationship or something or a wrong alias. A more solid test for you repositories in my believe :+1:

**Comment by Symfomany** [comment]
Do you Know Codeception? http://codeception.com/
