### ISSUE TITLE
switch out of file cache from default

### ISSUE THREAD

**Issue by cordoval** [Sylius/Sylius#3069]
bad for sharedhosting or when there is a quota about how many folders one can create

switching out of file cache from default :+1:

**Comment by inssein** [comment]
Isn't file the default cache for majority of symfony?

**Comment by kayue** [comment]
@cordoval Which part are you referring to? Cache settings should be configurable in `config.yml`.

**Comment by pjedrzejewski** [comment]
Filesystem cache is sensible default, keep in mind a lot of people try out Sylius locally.
