### ISSUE TITLE
PHP super globals should never be used

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3072]
Not in test api: ApitTestCase: use the container to get request stack 
protected static function getKernelClass()
    {
        if (isset($_SERVER['KERNEL_DIR'])) {
            $dir = $_SERVER['KERNEL_DIR'];

            if (!is_dir($dir)) {
                $phpUnitDir = static::getPhpUnitXmlDir();
                if (is_dir("$phpUnitDir/$dir")) {
                    $dir = "$phpUnitDir/$dir";
                }
            }
        } else {
            $dir = static::getPhpUnitXmlDir();
        }

        $finder = new Finder();
        $finder->name('CliKernel.php')->depth(0)->in($dir);
        $results = iterator_to_array($finder);
        if (!count($results)) {
            throw new \RuntimeException('Either set KERNEL_DIR in your phpunit.xml according to http://symfony.com/doc/current/book/testing.html#your-first-functional-test or override the WebTestCase::createKernel() method.');
        }

        $file = current($results);
        $class = $file->getBasename('.php');

        require_once $file;

        return $class;
    }

**Comment by pamil** [comment]
It's a test case and it's environment variable set by `PhpUnit`. It's OK to use that variable here, `Symfony2` [uses it too](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php#L103).
