### ISSUE TITLE
absolute path constants __DIR__ and __FILE__ should not be used

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3075]
in Sylius/src/Sylius/Bundle/ApiBundle/Test/ApiTestCase.php

in  $expectedResponse = file_get_contents(__DIR__.sprintf('/../Tests/Responses/%s.json', $filename));

use $kernel->locateResource like  $kernel->locateResource(sprintf('@AcmeDemoBundle/Tests/Responses/%s.json', $filename));
so $this->get('kernel')->locateResource('@AcmeDemoBundle/Resources/foo/bar.xml');

**Comment by inssein** [comment]
Might help the maintainers if you could submit this as a PR.

**Comment by pamil** [comment]
It's a test case, what are the pros of not using absolute path constants?
