### ISSUE TITLE
RouteProvider inject container by ContainerInterface

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3076]
Why in RouteProvider injecting container in the class RouteProvider of CoreBundle/Routing/RouteProvider @gonzalovilaseca  to use in RoutingRepositoryPass andwork just with a parameter instead inject parameters directly?

**Comment by gonzalovilaseca** [comment]
IIRC it had to be done this way as a workaround to a `ServiceCircularReferenceException`

**Comment by michalmarcinkowski** [comment]
It's Symfony Container issue.
