### ISSUE TITLE
Type hinting in lambda function zones

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3077]
In createCheckoutShippingForm() when you create Api Form

return $this->createApiForm('sylius_checkout_shipping', $order, array(
            'criteria' => array(
                'zone' => !empty($zones) ? array_map(function ($zone) {
                    return $zone->getId();
                }, $zones) : null,
                'enabled' => true,
            ),
        ));

$zone is hinting with ZoneMatcher class ?

**Comment by pjedrzejewski** [comment]
I do not understand the question. Please reopen if you are able to clarify or post it on StackOverflow.
