### ISSUE TITLE
best practice with multilingual site and search index

### ISSUE THREAD

**Issue by nicolasricci** [Sylius/Sylius#3080]
Hi,

I have a Sylius project currently in progress with both English and French locales.

Can anybody share any experience regarding the fos_elastica search index configuration? The taxon filter is working perfectly fine in English (default language) but not in French and I have read FOSElasticaBundle does not handle very well multiple locales in search index.

Thanks for your help

**Comment by Symfomany** [comment]
:+1:

**Comment by coudenysj** [comment]
There are a few things to keep in mind when searching in multiple languages.

The approach I usually take is to have one document per language, so you can apply a filter on it. It makes no sense to do queries in multiple languages, because you have different stemming rules, etc...

Take a look at https://www.elastic.co/guide/en/elasticsearch/guide/current/language-pitfalls.html.

**Comment by nicolasricci** [comment]
@coudenysj thanks for your feedback. 
This is the approach I went for, creating separated indexes for my 2 languages. However I still have an issue I don't understand. I have created a custom `query_builder_method` for each index. Example below for the French index

```
    public function createFrenchProductBuilder($entityAlias)
    {
        $qb = $this->createQueryBuilder($entityAlias);

        $qb->select($entityAlias, 'g')
            ->leftJoin($entityAlias . '.translations', 't')
            ->leftJoin($entityAlias . '.taxons', 'ta')
            ->leftJoin('ta.translations', 'tat')
            ->andWhere('t.locale = fr_FR')
            ->andWhere('tat.locale = fr_FR');

        return $qb;
    }
```
The products are correctly indexed in French but only accessible from the English taxons ... and I did not manage to figure out if this is related to the elasticsearch indexation or the Sylius implementation.

**Comment by nicolasricci** [comment]
OK forget it ... it looks like everything is working in the end. I just had an issue in my import script for the French products and the category I was testing on was obviously empty!! I am fixing the import script and will close the issue if everything is OK.

**Comment by nicolasricci** [comment]
Well this is still not working in the end. If I call the `indexByTaxonAction` with the English slug I have some results and none with the French one. Can anybody with a multilingual site try and let me know if they have the same issue?

**Comment by nicolasricci** [comment]
I will have another look this week about this issue. Any other Sylius user with some feedback to help me out? @michalmarcinkowski @coudenysj

**Comment by nicolasricci** [comment]
For information and those who would have the same issue I managed to find a solution (not sure it is the cleanest though)
I had to overwrite the `compileElasticaTaxonQuery` method in `ElasticsearchFinder` and use the QueryString query instead of the Terms Filter.
```
$elasticaQueryString = new \Elastica\Query\QueryString($taxon);
$query = new \Elastica\Query\Filtered($elasticaQueryString);
```
