### ISSUE TITLE
customer_id missing from AddressingBundle schema

### ISSUE THREAD

**Issue by nicolasricci** [Sylius/Sylius#3082]
Hi,

I had to override the Address model and just realized the customer_id field added when the customer / user separation has been done has never been added to the AddressingBundle schema in https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AddressingBundle/Resources/config/doctrine/model/Address.orm.xml (or I am missing sth??)

**Comment by michalmarcinkowski** [comment]
Because the AddressingBundle doesn't know anything about the customer. The relation is established in the CoreBundle https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Address.orm.xml.

**Comment by nicolasricci** [comment]
True... Then the question is how to override the Address model without dropping the customer_id?

When updating the schema such as 

```
<?xml version="1.0" encoding="UTF-8"?>
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping
                                      http://doctrine-project.org/schemas/orm/doctrine-mapping.xsd">

    <entity name="Acme\Entity\Address" table="sylius_address">
        <field name="state" column="state" type="string" length="255" nullable="true"/>
    </entity>

</doctrine-mapping>
```

the `d:s:u --dump-sql` command results in 

```
ALTER TABLE sylius_address DROP FOREIGN KEY FK_B97FF0589395C3F3;
DROP INDEX IDX_B97FF0589395C3F3 ON sylius_address;
ALTER TABLE sylius_address ADD state VARCHAR(255) DEFAULT NULL, DROP customer_id;
```

**Comment by michalmarcinkowski** [comment]
Are you sure your entity extends from **core** ``` Sylius\Component\Core\Model\Address ``` ?

**Comment by nicolasricci** [comment]
My bad ... thx

**Comment by michalmarcinkowski** [comment]
Glad that I could help :wink:
