### ISSUE TITLE
Move the need for doctrine/migrations: ~1.0@dev to "Dev Requirements"

### ISSUE THREAD

**Issue by joshualjohnson** [Sylius/Sylius#3084]
Since this package will be one that only developers use for db migration, there is no need to require it as a project requirement. It should be a dev requirement. Also this requirement is making it so that our projects have to allow for minimum-stability to be set to "dev" which then means we are changing the libs that our library requires.

**Comment by michalmarcinkowski** [comment]
You don't have to allow for dev in your minimum-stability, the notation ``` ~1.0@dev ``` means that this explicit package can be in dev, all others will be in stable if you will not change that. Anyway, there is first stable release of ``` doctrine/migrations ```. so we will update the requirement to stable soon.
