### ISSUE TITLE
When release Alpha version? Beta ? RC? LTS?

### ISSUE THREAD

**Issue by Symfomany** [Sylius/Sylius#3087]
When Sylius Solution release Alpha version? Beta ? RC? LTS?

**Comment by hasandz** [comment]
I guess, we need some predictions for that page: http://sylius.org/roadmap

**Comment by herodrigues** [comment]
@Symfomany This is not really a issue. Consider to delete it.

**Comment by michalmarcinkowski** [comment]
The roadmap (http://sylius.org/roadmap) will be updated soon.
