### ISSUE TITLE
What value should not be blank?

### ISSUE THREAD

**Issue by dgmdevelopment** [Sylius/Sylius#3089]
Keep getting error "This value should not be blank." when installing.  What value is it referring to? Terminal scrolls too fast to see the error and i cant scroll back to see it.  Thanks for helping this newbie out!

**Comment by nmarmon** [comment]
When appears that error? During the installation, there are a few parameters that you need to fill. In my case, at least, are these ones:

sylius.database.name (sylius)

sylius.database.user (root)

sylius.database.password (null)

sylius.currency_importer.ecb.base_currency (EUR)

The other parameters can remain empty.

Do you see this url http://docs.sylius.org/en/latest/book/installation.html? May it helps you.

**Comment by pjedrzejewski** [comment]
Please post this question on StackOverflow - it is the official support channel for Sylius. Just tag your question with "sylius" and maybe someone will be able to help you! http://stackoverflow.com/questions/tagged/sylius
