### ISSUE TITLE
Payum offline & capture payment action service as private

### ISSUE THREAD

**Issue by SebLours** [Sylius/Sylius#3092]
I want to add the payum offline gateway as a payment method.
When i want to put an order i have an error because the "sylius.payum.offline.action.capture_payment" service is not callable.

This service is set as private:
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/PayumBundle/Resources/config/services.xml#L86

```xml
<service id="sylius.payum.offline.action.capture_payment" class="%sylius.payum.offline.action.capture_payment.class%" public="false">
    <tag name="payum.action" factory="offline" />
</service>
```

Is it a bug ?

**Comment by makasim** [comment]
Yes it is, and as far as I know it was fixed here https://github.com/Sylius/Sylius/pull/2888

**Comment by SebLours** [comment]
Oupss sorry, i'm in 0.14 ...
Thanks !
