### ISSUE TITLE
Possible bug in Sylius\Component\Core\Locale\LocaleContext

### ISSUE THREAD

**Issue by gperdomor** [Sylius/Sylius#3101]
In Sylius\Component\Core\Locale\LocaleContext, the __construct function calls parent::__construct, so this LocaleContext must be extend Sylius\Component\Locale\Context\LocaleContext right?

**Comment by pamil** [comment]
Thanks for information, I've been already working on it in #3094 (`LocaleContext`/`LocaleProvider` will be moved out to another PR soon).

**Comment by pamil** [comment]
@gpredomor It will be solved by #3104, I think this may be closed now :)

**Comment by gperdomor** [comment]
@pamil +1 thanks

**Comment by nmarmon** [comment]
This issue is "closed" then?

**Comment by michalmarcinkowski** [comment]
@nmarmon will be closed after https://github.com/Sylius/Sylius/pull/3104 merger
