### ISSUE TITLE
Allow to differentiate between "Main Category" and "linked categories"

### ISSUE THREAD

**Issue by mojzis** [Sylius/Sylius#3112]
Quite often, a product would be in 1 "main" category (probably something you want to show in a listing on the homepage), but then you would also "link it" in other categories, for the product to appear in their lists as well.
To be able to do this, we would probably need to add some attribute to the TaxonProduct link (that is "upgrade" it to an entity on itself), or allow to setup "fields" that use the same taxonomy again.
I think this would be a great improvement to Sylius itself and have a feeling it cant be achieved out of the box now.

**Comment by pjedrzejewski** [comment]
Yes, I want to add this as well, cause we need that in every project. Basically, a main taxon! This gives us a lot of flexibility, cause some products can use category as main taxon or a brand or any other taxonomy item. :)

**Comment by pjedrzejewski** [comment]
Implemented in #3466.
