### ISSUE TITLE
Product builder - dont do fluent getters :)

### ISSUE THREAD

**Issue by mojzis** [Sylius/Sylius#3113]
The prodcut builder has a *__call* function that returns [**$this**](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Product/Builder/ProductBuilder.php#L97) under every circumstances, even for gettters, which is slightly illogical and very impractical for debugging :)
I would suggest adding a condition so "get" functions would return the actual value.

**Comment by michalmarcinkowski** [comment]
The ProductBuilder will be removed soon.

**Comment by mojzis** [comment]
interesting :) when ? what will come instead ? should i submit a patch at all ? thanks and sorry for so many questions :) (we have a rather large migration in the building, at the moment using the ProductBuilder, so its future is of interest to us :)

**Comment by michalmarcinkowski** [comment]
The ProductBuilder will be removed when someone will have time to do it :smile:  After #2255 merge, there will be a factory for object creation.

If you want to submit a patch, the best solution will be to remove the ProductBuilder :wink: 

Thank you @mojzis for raising that topic!

**Comment by mojzis** [comment]
product builder is gone, closing :)

**Comment by pjedrzejewski** [comment]
:+1:
