### ISSUE TITLE
sylius:cart:purge -> findExpired orders

### ISSUE THREAD

**Issue by poolerMF** [Sylius/Sylius#3122]
hello

in Sylius\Bundle\CoreBundle\Doctrine\ORM\OrderRepository -> findExpired() there is comparing row updatedAt ... 

this should be expiresAt ?

**Comment by poolerMF** [comment]
there should by update of expiresAt, when user successfully made payment ... 

becouse ... if user is shopping 2,5 hours ... then complete order ... 15 minutes later made payment ... CRON automatically delete this order 15 minutes after payment

**Comment by michalmarcinkowski** [comment]
@poolerMF the query takes into account the order state and doesn't clear completed orders.

**Comment by poolerMF** [comment]
I'm sorry, I made mistake ...I thought command sylius:ORDER:purge ...
but as I see, commands sylius:order:purge and sylius:cart:purge calls uses expiresAt < now

in both commands, situation is same as I described abowe ... on cartChange (product remove, add, change) or on order complete ... row expiresAt must be updated

**Comment by jimbocoder** [comment]
I think that would be a business decision to be made.  In some industries, it makes perfect sense to extend the cart's expiration time whenever it is modified in any way.  In other industries (such as event ticketing, with limited inventory in high demand) the last thing you want to do is allow someone to hoard all your inventory just by juggling items in and out of their cart.  Not sure of the correct approach to satisfy all the cases, but I can see @poolerMF's point.

**Comment by poolerMF** [comment]
ok then
