### ISSUE TITLE
[SearchBundle] Fails when override Product class

### ISSUE THREAD

**Issue by xavilondo** [Sylius/Sylius#3124]
Hi

When i override Product class as described on: https://www.youtube.com/watch?v=GXBvL_zDux8

When i try to search a product I receive the following error:

An exception has been thrown during the rendering of a template ("None of the chained routers were able to generate route: Route 'Sylius\Component\Core\Model\Product' not found") in SyliusSearchBundle:SearchResultSnippets:product.html.twig at line 5.

Any guidance would be greatly appreciated.

Sylius version: 0.14

**Comment by mojzis** [comment]
Can you try working against master ? it works fine for us :)

**Comment by pjedrzejewski** [comment]
@xavilondo Hi Xavi! :) Have you figure it out?

**Comment by xavilondo** [comment]
Hi! I updated everything but still fails.

You mean use master of Sylius? Im using 0.14 but i don't know if i can update to master directly so im in production and User class seems to be changed. Would I have problems if i update to master?

**Comment by pjedrzejewski** [comment]
@xavilondo There are a lot of BC breaks, but also huge amount of bug fixes. I'm not sure how heavily customized is your project - the difficulty of the upgrade depends on that.

**Comment by xavilondo** [comment]
@pjedrzejewski I'm reading about upgrading 0.14 to 0.15:

"-Execute migration script to migrate your data into the new model schema.
-The migration script migrates only default data, if you have some customizations on any of affected entities you should take care of them yourself!"

What is the migration script? And how i can customize it? I just customized the User and Product entities with an artist string like this:

class User extends BaseUser
{
    private $artist;
    public function getArtist()
    {
        return $this->artist;
    }
    public function setArtist($artist)
    {
        $this->artist = $artist;
    }
}

**Comment by michalmarcinkowski** [comment]
Here is a migration script https://github.com/Sylius/Sylius/blob/master/app/migrations/Version20150531210410.php.

It looks like this is a new field on User entity, so there will be no need to modify the migration script as it shouldn't remove the field (test it before using on production of course :smile:).

**Comment by zwierzi** [comment]
Try to rebuild search index:

app/console sylius:search:index

I had the same problem and it helped me:)

**Comment by xavilondo** [comment]
Thank you @zwierzi ! It solved my problem :D

**Comment by pjedrzejewski** [comment]
:+1:
