### ISSUE TITLE
Folder "media" in the installation of sylius

### ISSUE THREAD

**Issue by nmarmon** [Sylius/Sylius#3125]
For example, to save a image that will be used for a product. When someone creates a product, there is a tab which name is "images", where in theory you can add images. But "media" folder doesn't exists, and sylius needs it. When I try to add an image, if I didn't create that folder before, the image doesn't save in nowhere.

Why not to create this folder from the installation? If there is some problem with the edition, set the necessary privileges to allow that mode from sylius project.

A very small change, but useful, or not?

**Comment by nes15411** [comment]
i have the same problem, i customized the product entity but when i save the product sylius show me this error:

Catchable Fatal Error: Argument 1 passed to Sylius\Component\Core\Model\Image::setFile() must be an instance of SplFileInfo, string given, called in C:\xampp\htdocs\sylius-standard\vendor\symfony\symfony\src\Symfony\Component\PropertyAccess\PropertyAccessor.php on line 410 and defined

**Comment by pjedrzejewski** [comment]
I think this is fixed now. :)
