### ISSUE TITLE
[Payment] Validation for payment methods fee calculators is not working

### ISSUE THREAD

**Issue by michalmarcinkowski** [Sylius/Sylius#3131]
When I'm editing payment method and I leave empty fee (amount or percent) I can save my method with blank fee what shoudn't be possible.

**Comment by pjedrzejewski** [comment]
@Zales0123 Validation is missing/not working on configuration form.

**Comment by michalmarcinkowski** [comment]
This fix should resolve https://github.com/Sylius/Sylius/issues/3052

**Comment by michalmarcinkowski** [comment]
Fixed in #3348
