### ISSUE TITLE
Deleting all channels breaks admin interface; no validation to prevent delete

### ISSUE THREAD

**Issue by msumme** [Sylius/Sylius#3135]
If you delete all the channels, you get the following: 

![image](https://cloud.githubusercontent.com/assets/462931/9282058/4c504ad8-428f-11e5-8800-f0404bc00f7f.png)

It appears you cannot use the product AT ALL without channels, which is inconvenient since you have to remember to tag channels in every single product you create, and have to remember to add channel logic into any customizations you add.

Is there a plan to let the product work without enabling channels, or at least having only one channel that is a default channel (i.e. all products are by default added to it)?

**Comment by michalmarcinkowski** [comment]
In the application there should exist at least one channel. We have to prevent deleting all channels. 

If you don't plan to use multichannel functionality you should assign everything to one channel. Perhaps, when there is only one channel we could by default assign eveything to it, but that would be UX improvement (topic for later).

Thanks for reporting that @msumme!

**Comment by msumme** [comment]
You're welcome @michalmarcinkowski - I want to see Sylius get finished and be strong.

**Comment by michalmarcinkowski** [comment]
Look forward to the new roadmap! We aim high, but with community help everything is possible! We're going to improve project organization, so we can develop Sylius more efficiently, because the hard work is ahead of us.

**Comment by gperdomor** [comment]
@michalmarcinkowski you said that only one channel is needed, but this channel must be enabled too, right? I use a custom constraint validation to handle entities with that logic. Tonight i will prepare a PR :)

**Comment by pjedrzejewski** [comment]
@gperdomor Awesome!

**Comment by gperdomor** [comment]
@pjedrzejewski @michalmarcinkowski please review the PR #3150, the constraint is based on the symfony docs and it's generic for use with other models, not only with channels.

**Comment by pjedrzejewski** [comment]
Fixed in #3150.
