### ISSUE TITLE
[RFC] Concurrency

### ISSUE THREAD

**Issue by patrick-mcdougle** [Sylius/Sylius#3138]
I don't see any sort of concurrency control in place. We should probably audit the places where concurrency can be a problem and use proper database locking where appropriate.

The place where I concurrency could potentially be an issue is in a scenario where two users (U1 & U2) place an order really close to the same time. The two requests to complete checkout run concurrently, so the following scenario could happen:

U1 checks on hand quantity of a product variant on line 142 of InventoryOperator.php (let's say it's 1)
U2 checks on hand quantity of the same product variant on line 142 of InventoryOperator.php (it's still 1 because U1 hasn't updated it, nor flushed yet).
U1 continues, decrementing the on hand quantity on 150 of InventoryOperator.php and eventually flushes decrementing on hand count of 0 in the database.
Meanwhile U2 doesn't know that on hand should now be 0. It continues, decrementing its on hand quantity to zero as well, and eventually flushes. Updating on hand quantity on hand to 0 in the database again!

We've now oversold!

I'm not well versed in how doctrine can help with database locking or if optimistic vs pessimistic is better. Does anyone have any thoughts about how this should be solved?

**Comment by michalmarcinkowski** [comment]
Thank you Patrick for raising that up. We already have a few issues about race conditions (issue you described - https://github.com/Sylius/Sylius/issues/2776) and have it in mind.

IMO doctrine optimistic locking will be a good choice in most of places, but we have to consider each scenario separately and define what fits there best.

The concurrency control is something we would like to introduce in the nearest future and we would appriciate any kind of help there.

**Comment by kayue** [comment]
@patrick-mcdougle We temporary hold stock when user visit payment page. This solved most of the problem, esp. when you use payment like PayPal, it could take few minutes before checkout complete, this is when oversold will happen.

**Comment by patrick-mcdougle** [comment]
@kayue, that doesn't really solve the concurrency problem, it simply narrows the window in which it can happen. It doesn't eliminate it.

**Comment by pjedrzejewski** [comment]
@patrick-mcdougle @kayue @michalmarcinkowski Let's keep this discussion in one place - #2776.
