### ISSUE TITLE
[RFC] Add Ecotax field

### ISSUE THREAD

**Issue by tristanbes** [Sylius/Sylius#3140]
Wouldn't be a good idea to add the Ecotax field on a product ? 

A lot of european country has this tax which applies for certain type of goods.
It's a tax computed based on the digit of the bar code (see an example attached). I can't find any logic on that so you can't compute it automatically.

A solution would be for a single product to add other taxes (or to handle the ecotax only)
It would have a main tax and extra taxe(s) who would either be a flat price or a % with a customized label

The ecotax needs to be added on the invoice on a separate line for the product. You can't "add" it to the product price. 

What do you think ?
We'll propose a pull request, Do you have any recommendation on this before we start the work ?

**Comment by tristanbes** [comment]
We'll propose a PR for that, if you have recommendation before we start the work, we'll be happy to hear
@michalmarcinkowski @pjedrzejewski

**Comment by stloyd** [comment]
@tristanbes Why do you need to add new field? Can't this be done with custom tax calculator and cart/order item adjustments?

**Comment by tristanbes** [comment]
@stloyd, Well right now, you can have only one taxable category for a product.

What we need is : 
- [x] a taxable category for a product
- [ ] another tax that doesn't always apply (only certain type of goods) and when it applies, it differs from product to product, because the tax is entered by the administrator according by the price and on the digits of the bar code.
- [ ] On the invoice add a small line under the product like this (the picture itself is crappy, couldn't find other pic under my hand) 

<img width="470" alt="capture d ecran 2015-09-17 a 17 27 48" src="https://cloud.githubusercontent.com/assets/346010/9937552/8bf73600-5d61-11e5-8470-22e7773bbc65.png">

Even if we could add multiple tax from the choice list, it wouldn't solve the problem as the ecotax differs from product to product.

**Comment by tristanbes** [comment]
@stloyd: The other solution would be only **cosmetic**
We add a field to the backoffice and it'll used only to inform the customer how much ecotax he paid.
The ecotax would be added manually to the price.
