### ISSUE TITLE
Add more documents for an order (order, preparatory, withdrawal)

### ISSUE THREAD

**Issue by tristanbes** [Sylius/Sylius#3143]
Currently there's only the possibliity to download the invoice from the frontend part.

Therefore, some documents are misisng:
- Order's PDF
- Preparatory delivery bills
- Right of withdrawal pdf form

It would be nice if we could download those document on the backoffice too (inside the order section)

**Comment by pjedrzejewski** [comment]
Definitely something we want to add. I was thinking about generic action, which would simply use appropriate template and have all the order information. This would allow the developer to add many different documents.

**Comment by remibaar** [comment]
Too bad this feature has been removed from the BETA1 milestone as this is one of the most important feature for companies (in Europe). The financial administration requires documents of invoices and credit invoices. For me this is the main reason holding back using Sylius. 
Is there something I can do to help implement this feature? As I understand it would probably require some structural changes of the structure of the orders.
