### ISSUE TITLE
FatalErrorException in Order.php line 23: Compile Error: Cannot inherit previously-inherited or override constant STATE_CART from interface Sylius\Component\Order\Model\OrderInterface

### ISSUE THREAD

**Issue by yopop666** [Sylius/Sylius#3149]
Hi,

I have installed Sylius, it works, but sometimes I get "FatalErrorException in Order.php line 23: Compile Error: Cannot inherit previously-inherited or override constant STATE_CART from interface Sylius\Component\Order\Model\OrderInterface".

To get rid of this I must restart httpd service.

The trace of this error:
in Order.php line 23
in DebugClassLoader.php line 153
at DebugClassLoader->loadClass() in DebugClassLoader.php line 0
in DebugClassLoader.php line 153
at DebugClassLoader->loadClass() in DebugClassLoader.php line 0
in DebugClassLoader.php line 153
at DebugClassLoader->loadClass() in DoctrineORMDriver.php line 0
at ReflectionClass->__construct() in DoctrineORMDriver.php line 38
at DoctrineORMDriver->getRepositoryDefinition() in AbstractDatabaseDriver.php line 68
at AbstractDatabaseDriver->load() in AbstractResourceExtension.php line 272
at AbstractResourceExtension->loadDatabaseDriver() in AbstractResourceExtension.php line 102
at AbstractResourceExtension->configure() in SyliusOrderExtension.php line 34
at SyliusOrderExtension->load() in MergeExtensionConfigurationPass.php line 55
at MergeExtensionConfigurationPass->process() in MergeExtensionConfigurationPass.php line 39
at MergeExtensionConfigurationPass->process() in Compiler.php line 117
at Compiler->compile() in ContainerBuilder.php line 614
at ContainerBuilder->compile() in Kernel.php line 546
at Kernel->initializeContainer() in Kernel.php line 138
at Kernel->boot() in Kernel.php line 193
at Kernel->handle() in app_dev.php line 43
at {main}() in app_dev.php line 0

Anyone can help me?

Thanks in advance.

**Comment by pjedrzejewski** [comment]
What is your Sylius version? Exact commit.

**Comment by yopop666** [comment]
I guess that my Sylius installed version it is 0.14.

In my composer.json file i have these settings
{
    "name":        "sylius/sylius",
    "type":        "project",
    "description": "E-Commerce platform for PHP, based on Symfony framework.",
    "license":     "MIT",
    "homepage":    "http://sylius.org",
    "authors": [
        {
            "name":     "Paweł Jędrzejewski",
            "homepage": "http://pjedrzejewski.com"
        },
        {
            "name":     "Sylius project",
            "homepage": "http://sylius.org"
        },
        {
            "name":     "Community contributions",
            "homepage": "http://github.com/Sylius/Sylius/contributors"
        }
    ],
    "require": {
        "php":                                  ">=5.3.9",
        "a2lix/translation-form-bundle":        "~2.0",
        "doctrine/collections":                 "~1.2",
        "doctrine/common":                      "~2.3",
        "doctrine/doctrine-bundle":             "~1.3",
        "doctrine/doctrine-cache-bundle":       "~1.0",
        "doctrine/doctrine-fixtures-bundle":    "~2.2",
        "doctrine/doctrine-migrations-bundle":  "~1.0",
        "doctrine/migrations":                  "~1.0@dev",
        "doctrine/orm":                         "~2.4",
        "doctrine/phpcr-odm":                   "^1.2.2",
        "friendsofsymfony/elastica-bundle":     "^3.0.2",
        "friendsofsymfony/oauth-server-bundle": "~1.4",
        "friendsofsymfony/rest-bundle":         "~1.5",
        "friendsofsymfony/user-bundle":         "2.0.*@dev",
        "fzaninotto/faker":                     "~1.2",
        "hwi/oauth-bundle":                     "~0.3",
        "incenteev/composer-parameter-handler": "~2.0",
        "jackalope/jackalope":                  "^1.1.4",
        "jackalope/jackalope-doctrine-dbal":    "^1.1.2",
        "jms/serializer-bundle":                "~0.13",
        "jms/translation-bundle":               "~1.1",
        "knplabs/knp-gaufrette-bundle":         "~0.1",
        "knplabs/knp-menu-bundle":              "~1.1",
        "knplabs/knp-snappy-bundle":            "~1.2",
        "liip/imagine-bundle":                  "~1.0",
        "mathiasverraes/money":                 "~1.2",
        "omnipay/omnipay":                      "~2.3",
        "payum/omnipay-bridge":                 "~0.14.0",
        "payum/payum":                          "~0.14.0",
        "payum/payum-bundle":                   "~0.14.2",
        "sensio/distribution-bundle":           "~2.3",
        "stof/doctrine-extensions-bundle":      "~1.1",
        "swiftmailer/swiftmailer":              "~5.0",
        "symfony-cmf/block-bundle":             "~1.2",
        "symfony-cmf/content-bundle":           "~1.2",
        "symfony-cmf/create-bundle":            "~1.2",
        "symfony-cmf/media-bundle":             "~1.2",
        "symfony-cmf/menu-bundle":              "~1.2",
        "symfony-cmf/routing-bundle":           "~1.2",
        "symfony/assetic-bundle":               "~2.3",
        "symfony/event-dispatcher":             "~2.3",
        "symfony/expression-language":          "~2.4",
        "symfony/form":                         "~2.3",
        "symfony/framework-bundle":             "~2.3",
        "symfony/intl":                         "~2.3",
        "symfony/monolog-bundle":               "~2.3",
        "symfony/options-resolver":             "~2.3",
        "symfony/property-access":              "~2.3",
        "symfony/swiftmailer-bundle":           "~2.3",
        "symfony/symfony":                      "~2.3",
        "symfony/twig-bundle":                  "~2.3",
        "twig/extensions":                      "~1.0",
        "twig/twig":                            "~1.11",
        "white-october/pagerfanta-bundle":      "~1.0",
        "willdurand/hateoas-bundle":            "~0.4",
        "winzou/state-machine-bundle":          "~0.2",
        "sensio/generator-bundle": "^2.5"
    },
    "require-dev": {
        "behat/behat":                          "~3.0",
        "behat/symfony2-extension":             "~2.0",
        "behat/mink-extension":                 "~2.0",
        "behat/mink-browserkit-driver":         "~1.2",
        "behat/mink-selenium2-driver":          "~1.2",
        "behat/mink":                           "~1.6",
        "coduo/php-matcher":                    "~1.0",
        "phpspec/phpspec":                      "~2.1",
        "phpunit/phpunit":                      "~4.1"
    },
    "replace": {
        "sylius/addressing":         "v0.14.0",
        "sylius/addressing-bundle":  "v0.14.0",
        "sylius/api-bundle":         "v0.14.0",
        "sylius/archetype":          "v0.14.0",
        "sylius/archetype-bundle":   "v0.14.0",
        "sylius/attribute":          "v0.14.0",
        "sylius/attribute-bundle":   "v0.14.0",
        "sylius/cart":               "v0.14.0",
        "sylius/cart-bundle":        "v0.14.0",
        "sylius/contact":            "v0.14.0",
        "sylius/contact-bundle":     "v0.14.0",
        "sylius/content":            "v0.14.0",
        "sylius/content-bundle":     "v0.14.0",
        "sylius/core":               "v0.14.0",
        "sylius/core-bundle":        "v0.14.0",
        "sylius/currency":           "v0.14.0",
        "sylius/currency-bundle":    "v0.14.0",
        "sylius/fixtures-bundle":    "v0.14.0",
        "sylius/flow-bundle":        "v0.14.0",
        "sylius/installer-bundle":   "v0.14.0",
        "sylius/inventory":          "v0.14.0",
        "sylius/inventory-bundle":   "v0.14.0",
        "sylius/locale":             "v0.14.0",
        "sylius/locale-bundle":      "v0.14.0",
        "sylius/money-bundle":       "v0.14.0",
        "sylius/order":              "v0.14.0",
        "sylius/order-bundle":       "v0.14.0",
        "sylius/payment":            "v0.14.0",
        "sylius/payment-bundle":     "v0.14.0",
        "sylius/payum-bundle":       "v0.14.0",
        "sylius/pricing":            "v0.14.0",
        "sylius/pricing-bundle":     "v0.14.0",
        "sylius/product":            "v0.14.0",
        "sylius/product-bundle":     "v0.14.0",
        "sylius/promotion":          "v0.14.0",
        "sylius/promotion-bundle":   "v0.14.0",
        "sylius/registry":           "v0.14.0",
        "sylius/resource":           "v0.14.0",
        "sylius/resource-bundle":    "v0.14.0",
        "sylius/search":             "v0.14.0",
        "sylius/search-bundle":      "v0.14.0",
        "sylius/sequence":           "v0.14.0",
        "sylius/sequence-bundle":    "v0.14.0",
        "sylius/settings-bundle":    "v0.14.0",
        "sylius/shipping":           "v0.14.0",
        "sylius/shipping-bundle":    "v0.14.0",
        "sylius/storage":            "v0.14.0",
        "sylius/taxation":           "v0.14.0",
        "sylius/taxation-bundle":    "v0.14.0",
        "sylius/taxonomy":           "v0.14.0",
        "sylius/taxonomy-bundle":    "v0.14.0",
        "sylius/translation":        "v0.14.0",
        "sylius/translation-bundle": "v0.14.0",
        "sylius/variation":          "v0.14.0",
        "sylius/variation-bundle":   "v0.14.0",
        "sylius/web-bundle":         "v0.14.0"
    },
    "scripts": {
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Symfony\\Cmf\\Bundle\\CreateBundle\\Composer\\ScriptHandler::downloadCreateAndCkeditor",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Symfony\\Cmf\\Bundle\\CreateBundle\\Composer\\ScriptHandler::downloadCreateAndCkeditor",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ]
    },
    "autoload": {
        "psr-0": { 
            "Sylius\\": "src/",
            "":"src/"
        }
    },
    "config": {
        "bin-dir": "bin"
    },
    "extra": {
        "branch-alias": {
            "dev-master": "0.14-dev"
        },
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        }
    }
}

**Comment by jimbocoder** [comment]
@yopop666 `composer info sylius/sylius` will display the exact commit hash to help reproduce the error.

**Comment by yopop666** [comment]
After I execute <code>composer info sylius/sylius</code>  I find one line with
<code>
source   : [git] https://github.com/Sylius/Sylius.git f01a3b4846439d6eae7223cd7852a058c981a2a9
</code>

I supose that  the hash is <b>f01a3b4846439d6eae7223cd7852a058c981a2a9</b>

Thanks for help!

**Comment by pjedrzejewski** [comment]
What is your PHP version and os?

**Comment by yopop666** [comment]
My php version is 5.4.44 and the os is CentOS release 6.5 (Final).

**Comment by yopop666** [comment]
Hi, 
After some investigation I fount that if I reset the just the cache (with **apc_clear_cache()**  ) not the web server,the sylius application works again.I guess that the cache it's the problem.
