### ISSUE TITLE
[Backend] Payments list crashes when there are payments that belong to deleted orders

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#3153]
Since I have been running the cron tasks, it has been cleaning out stale orders. However, this has broken the payments listing page in the backend.

It should probably not list payments or attempted payments of deleted orders, which would void this error.

Edit: Or delete the payments when we delete an order?

**Comment by michalmarcinkowski** [comment]
It's softdeletable issue, IMO the payments should be softdeleted together with the order.

**Comment by pjedrzejewski** [comment]
Yeah, we should cascade softdelete them. :+1:

**Comment by tristanbes** [comment]
Oh, that's why the payment page is 500'ing from time to time on the demo ;-)

**Comment by pjedrzejewski** [comment]
Fixed in #3194.
