### ISSUE TITLE
Payment state cannot be marked as authorized

### ISSUE THREAD

**Issue by antonioperic** [Sylius/Sylius#3154]
Hi, 
I am trying to add new payment method and trying to complete payment with marking request as authorized in Payum.
Payment has state for authorized, but as I can see in payment transition there is no state for authorized. There is process (pending) but ne authorized.

@winzou do I thinking wrong about this one or we need to add state for authorizing.

This is situation when you do only reservation of total amount on clients credit card. That is not completed state yet but authorized state.

Let me know if you need additional info.

cc @makasim

**Comment by pjedrzejewski** [comment]
Yeah, I think we miss this transition...

**Comment by kayue** [comment]
How about `processing`?

**Comment by kayue** [comment]
FYI list of PayPal states: https://www.paypal.com/us/webapps/helpcenter/helphub/article/?solutionId=FAQ2334

**Comment by antonioperic** [comment]
Processing works - I mean it can be set as status but we need to change event then.
Regarding statuses I talked with @makasim and he also agreed that right status is authorized

**Comment by pjedrzejewski** [comment]
Yes, we definitely need ``authorized`` as status. Then capture to make it complete.d

**Comment by bretto36** [comment]
Has anyone done any work on this, i'd like to add it to my site.

**Comment by makasim** [comment]
The status is already there: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/PayumBundle/Request/GetStatus.php#L152

 I guess there must be a flow in state machine to handle this case. Also authorize is not a final step and depending on a payment gateway you may need some later processing. Like do capture in 10 days.

**Comment by bretto36** [comment]
Yes we would need an event to fire when capturing the payment, which would call the linked payment gateway.

**Comment by pjedrzejewski** [comment]
Implemented in #8552.
