### ISSUE TITLE
[UserBundle] CustomerAwareListener uses CartEvent class

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#3155]
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/UserBundle/EventListener/CustomerAwareListener.php#L40

**Comment by Mac2k3** [comment]
This can be closed due to following commit I guess: 
https://github.com/Sylius/Sylius/commit/bf4fd4166616aab0af6e9a485c377fe070a6aded

**Comment by pjedrzejewski** [comment]
@Ma27 Thanks for the heads up! :+1:

**Comment by Ma27** [comment]
wrong username I guess :D

**Comment by pjedrzejewski** [comment]
@Ma27 Yes, sorry! :) I meant @Mac2k3. :+1:
