### ISSUE TITLE
[OrderBundle] [RFC] Order total is mapped as an integer in database 

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#3163]
https://github.com/Sylius/Sylius/blob/0c15f8353e5c70817d7d4d23c5ff53eccd4f8015/src/Sylius/Bundle/OrderBundle/Resources/config/doctrine/model/Order.orm.xml#L58

Order total is an integer, and there are few checks of this state. For example Payment model checks if given value is an integer https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Payment/Model/Payment.php#L177

But the integer is stored on 32 bits in MySQL environment https://dev.mysql.com/doc/refman/5.1/en/integer-types.html

In this case the bigest available price of cart has to be lower then 21 474 836.47. In some country's it can not be enough(for example 1 USD = 22,396.42 VND ).
IMO We should allow to keep bigger numbers in database. WDYT?

**Comment by jimbocoder** [comment]
I think this sounds very reasonable, and with limited downside.

**Comment by kayue** [comment]
I think `int` is reasonable. Developer can override schema if they want.

**Comment by jimbocoder** [comment]
The ORM won't let you change the column type with an override, that I am aware of.

**Comment by lchrusciel** [comment]
Another thing is changing mapping to bigint results in string mapping in doctrine. As i wrote before some of properties requires int value. In consequence you will have to override some models, like payment, otherwise you will have red build and whole your app won't work. The customers won't be able to finish payment. Right now it is impossible to have bigger total order value then 21 millions of your currency.

**Comment by pamil** [comment]
If we are going to represent that values as PHP integer, only 64bit PHP will be appropriate. Moreover, even 64bit PHP on 64bit Windows wouldn't be enough, because Windows integer are always 32bit :) 

Anyway, I'm for storing money as `bigint` in Doctrine and integer in PHP.

**Comment by nakashu** [comment]
I tried locally one possible workaround thats quite easy, until a proper solution is delivered.

Modify exchange rates for currencies..

Using currencies exchange rates, you can set it in multiples of 10 to what ever you like
As this only affects the presentation of the price, and doesn't touch forms or storage. you can make 10$ display like 10 000$.
Only additional place for modification would be in forms to hint (add note), that values are in millions or whatever.

Maybe a proper fix idea: what about scientific notation.

**Comment by bendavies** [comment]
In my project I use bigint, and use a VO (https://github.com/keiosweb/moneyright) to represent amounts everywhere in my code.

**Comment by pjedrzejewski** [comment]
@lchrusciel Closing this as it is quite old issue and we will reconsider money handling for 2.0. :)
