### ISSUE TITLE
Perform Git tree split on LocaleBundle (it is outdated and contains very important bugfix)

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#3166]
Hi,

@pamil Did a very important bugfix (https://github.com/Sylius/Sylius/commit/3f5daec5f08f699cd863731dfa61fe231e73cbb5) for the `LocaleBundle`.

@pjedrzejewski Could you please run the split thing on the LocaleBundle so it gets updated in both github and packagist? Would appreciate it!

**Comment by pjedrzejewski** [comment]
@steffenbrem Split is running. :)

**Comment by pjedrzejewski** [comment]
Split completed.

**Comment by steffenbrem** [comment]
@pjedrzejewski Many thanks! :+1:

**Comment by pjedrzejewski** [comment]
@steffenbrem You're welcome. I am hoping that Fabien will release Symfony git split tool soon, cause coming up with optimal solution is really hard. :+1:
