### ISSUE TITLE
Account password change doesn't work

### ISSUE THREAD

**Issue by gonzalovilaseca** [Sylius/Sylius#3167]
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

Password change in account doesn't work. 
For what I've found the problem seems to be in the User controller:
```
    protected function handleChangePassword(UserInterface $user, $newPassword)
    {
        $user->setPlainPassword($newPassword);

        $this->domainManager->update($user);

        $dispatcher = $this->get('event_dispatcher');
        $dispatcher->dispatch(UserEvents::PASSWORD_RESET_SUCCESS, new GenericEvent($user));

        if ($this->config->isApiRequest()) {
            return $this->handleView($this->view($user, 204));
        }
        $this->addFlash('success', 'sylius.user.password.change.success');

        return new RedirectResponse($this->generateUrl('sylius_account_homepage'));
    }
```
The plain password is encoded by a listener of the ``PASSWORD_RESET_SUCCESS`` event, but the entity is persisted before with `` $this->domainManager->update($user);``. So at the point where the entity is persisted, the encoded password hasn't been updated.

If this sounds reasonable I'll open a PR to fix it and also check that the reset works properly.

**Comment by michalmarcinkowski** [comment]
@gonzalovilaseca actually we should have two events there (pre and post) as it is in resource. If you want to make a PR, please split this event into:

```
PRE_PASSWORD_RESET
POST_PASSWORD_RESET
```
The first one should be dispatched before flush, the second one after (replaces SUCCESS). Then attach the password updater to PRE event and everything should work fine.

If you have more time you could do the same for password change events (they are also wrong...).

Thank you @gonzalovilaseca for reporting that! :+1:

**Comment by michalmarcinkowski** [comment]
BTW.
In method `handleChangePassword` we should dispatch `PRE_PASSWORD_CHANGE` and `POST_PASSWORD_CHANGE`. I've already corrected it in my UserBundle improvement (WIP - https://github.com/michalmarcinkowski/Sylius/pull/6/files#diff-4f4c5540de8e56b05f4e9184911081bdL244).

**Comment by gonzalovilaseca** [comment]
@michalmarcinkowski Ok, will do a PR soon.

**Comment by michalmarcinkowski** [comment]
Great!

**Comment by jimbocoder** [comment]
I just ran into this myself.  Since this truly is a blocker, I'd propose merging #3173 more immediately, and a follow up PR to refactor the password events as described above by @michalmarcinkowsk when that work is finished. The need for the refactor is a separate and less severe deficiency IMHO.

**Comment by gonzalovilaseca** [comment]
PR here: https://github.com/Sylius/Sylius/pull/3184 
@michalmarcinkowski check if the change pswd events are ok please.

**Comment by michalmarcinkowski** [comment]
Everything ok, already merged. Thanks again!
