### ISSUE TITLE
How to use Sylius bundles in Yii1 project

### ISSUE THREAD

**Issue by fazliddin** [Sylius/Sylius#3174]
As stated in Sylius doc, it consists of finely decoupled bundles which may be used in any php project independenly.

I have developed CMS in Yii1 and want to add ecommerce feature. I am planning to fully use Sylius's ecommerce bundle set. But I can not figure out some aspects of the integration anyhow.

How is routing problem is solved? My CMS has backend dashboard with main menu and I will add links to Sylius controllers, when pressed sylius controller must be loaded and my admin theme must be applied.

How is template system integrated?

How is access controll is resolved? My CMS uses simple user db table where role field holds user role as string: `admin`, `manager` and I want only admin user accessed ecommerce part: `Yii::app()->user->isAdmin()`.

So is it possible case?

**Comment by kayue** [comment]
If you are using Yii1 than you won't be using the "full" Sylius.
Instead you will be using Sylius components individually.

**Comment by fazliddin** [comment]
One more question. sylius/sylius repo includes all bundles, but bundles are also available as separate read only repos. Why do we need such duplication?

**Comment by gperdomor** [comment]
@fazliddin yes, sylius/sylius contains all bundles, is the main project and all bundles work together, all bundles are integrated in core bundle... The standalone bundles are provided to use in other projects. For example, if you need handle users in your project, you can need install only the UserBundle (and dependencies), not all bundles.

**Comment by fazliddin** [comment]
I see that it is very flexible approach. I am curious how is it done technically. Let's say I clonned sylius/sylius repo and began development of my own bundles inside `sylius/sylius/src/Sylius/Bundle` dir. But How do I make my bundle available as separate repo for composer? What is main idea behind making those separate repos read-only? I am sorry if my questions are trivial.

**Comment by pjedrzejewski** [comment]
@fazliddin Hello Fazliddin!

1. All these repositories are automatically (although process is not perfect) generated everyday using git subtree split. https://makingsoftware.wordpress.com/2013/02/16/using-git-subtrees-for-repository-separation/
2. If you start a project on Sylius full-stack, you should use github.com/Sylius/Sylius-Standard.
3. With Yii, you will be able to only use raw PHP E-Commerce components provided by Sylius.

If you have any further questions, please head to http://stackoverflow.com/, it will be much better place for discussion and questions. We try to keep the github issues clean and delegate the community support to SO. Thank you for your interest in Sylius! :)

**Comment by fazliddin** [comment]
Thank you very much!

**Comment by pjedrzejewski** [comment]
@fazliddin You're welcome, see you around! :)
