### ISSUE TITLE
[RFC][SearchBundle] Make automatic indexing configurable

### ISSUE THREAD

**Issue by jimbocoder** [Sylius/Sylius#3179]
The `OrmListener` class in SearchBundle is responsible for keeping the search index updated when relevant objects are changed, like Products and related entities.

This introduces a lot of (surprisingly heavy) computation, especially when doing any bulk updates.  For projects such as my own at the moment, which have no need for the search index, that ends up being a waste.  Other projects might find it preferable to do bulk reindexing using the `sylius:search:index` console command with a cron job or similar, rather than updating the index on the fly.

My proposal is to register the listener only if the bundle configuration has it enabled, and to allow it to remain enabled by default.

Happy to provide the PR if this sounds good.

**Comment by gperdomor** [comment]
Sounds good, maybe could be a parameter in parameters.yml file.

**Comment by pjedrzejewski** [comment]
Definitely in favor of doing that. I'm not sure about putting in the parameters.yml. I plan to remove as much parameters as possible from that file and avoid adding new ones. What do you guys think? Ideally, we keep only standard symfony params.

**Comment by mojzis** [comment]
I think it'd be great to add a condition here:
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/SearchBundle/Listener/OrmListener.php#L65
so ie during bulk import one could set the auto indexing off 
and that condition would have to ask a parameter i guess ? cant think of a better place where to put it ?
would help us a lot actually :)

**Comment by michalmarcinkowski** [comment]
SearchBundle was removed.
