### ISSUE TITLE
Migration to Sylius

### ISSUE THREAD

**Issue by codingideas** [Sylius/Sylius#3182]
I need to migrate to Sylius from vanilla php commerce but the migration guide http://docs.sylius.org/en/latest/migration/index.html is empty. I don't even know how to start?

**Comment by kayue** [comment]
Sylius doesn't provide any migration script at this moment. It hasn't even reach beta yet. 

I am afraid you have to wrote your own script.

**Comment by mojzis** [comment]
There is some debate in here : #379 . We have used https://github.com/ddeboer/data-import with great results :).

**Comment by pjedrzejewski** [comment]
@mojzis You used it to migrate legacy data to Sylius? Or used for something else with great results. :)

**Comment by mojzis** [comment]
Yes, to Sylius :) Still working on it, hoping to be able to outsorce parts later on ...

**Comment by pjedrzejewski** [comment]
@mojzis That would be just awesome! We need to talk about this and maybe figure out some stuff for migration guide. Thanks!
