### ISSUE TITLE
sylius.settings.timezone_deprecated

### ISSUE THREAD

**Issue by rameshlohala** [Sylius/Sylius#3186]
Hello,

I have the following error when I run "php app/console sylius:install"

timezone            | OK! 
timezone_deprecated |  ERROR!
...
[RuntimeException]
Some system requirements are not fulfilled. Please check output messages and fix them.

**Comment by pjedrzejewski** [comment]
Please post this question on StackOverflow - it is the official support channel for Sylius. Just tag your question with "sylius" and maybe someone will be able to help you! http://stackoverflow.com/questions/tagged/sylius
