### ISSUE TITLE
[SyliusUserBundle] Templates are harcoded

### ISSUE THREAD

**Issue by gperdomor** [Sylius/Sylius#3190]
In renderLogin of SecurityController, the template are configure to use a SyliusWebBundle template, so UserBundle can't use standalone.

In the case of UserController some functions use SyliusWebBundle templates too.

**Comment by michalmarcinkowski** [comment]
Already working on separation of UserBundle from Core and Web bundles. Look for PR in coming days :wink:

**Comment by gperdomor** [comment]
:+1: thank you :D

**Comment by pamil** [comment]
@pjedrzejewski @michalmarcinkowski #3197 is already merged :)

**Comment by michalmarcinkowski** [comment]
I will prepare basic email templates in a separate PR. Closing.

**Comment by gperdomor** [comment]
:+1: thank you @michalmarcinkowski :D
