### ISSUE TITLE
ShipmentItem missing from doctrine mapping ??

### ISSUE THREAD

**Issue by nicolasricci** [Sylius/Sylius#3206]
Hi,

I have just realized that the Shipment model has an $items property which refers to a `ShipmentItemInterface`. 

However I don't have any `sylius_shipment_item` table in my database and the `doctrine:schema:update` task tells me i am up to date.

There must be something missing somewhere...

Thanks
Nicolas

**Comment by pjedrzejewski** [comment]
Actually, in Sylius Core, InventoryUnit and ShipmentItem are the same. So your shipment items are in sylius_inventory_unit table.

**Comment by nicolasricci** [comment]
OK thanks for pointing it out. The ShipmentItem.orm.xml is quite confusing then.
