### ISSUE TITLE
[Money] Formatting Currency

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#3207]
I just changed the currency of my store from CAD to USD, and I realized that all the prices no longer show the currency code. This seems pretty confusing, and I can't seem to find an easy solution.

The problem seems to be with NumberFormatter (Sylius\Bundle\MoneyBundle\Templating\Helper\MoneyHelper::formatAmount). When the locale is 'en_US', and currency is 'USD', it doesn't print out the currency code.

I understand how this could be a feature of NumberFormatter, but there doesn't seem to be an option to not do this.

**Comment by pjedrzejewski** [comment]
Thanks for reporting, we will look into this! Exact steps to reproduce will be helpful. :)

**Comment by inssein** [comment]
@pjedrzejewski just set the locale to 'en_US' and currency to 'USD'. You will not see the currency listed anywhere, except if you change your locale to something that uses dollars (I used 'en_CA') to test.

The source of the problem is NumberFormatter:

```php
$formatter = new NumberFormatter('en_US', NumberFormatter::CURRENCY);
echo $formatter->formatCurrency(1399, 'USD');
```

Will return ```$1,399.00```. If you change the locale to 'en_CA', it will return ```US$1,399.00```.

**Comment by pamil** [comment]
There are two English locales that always renders currency symbols:
 - `en_001` - English (World)
 - `en_150` - English (Europe)

You can do that customisation for your application by implementing `Sylius\Bundle\MoneyBundle\Formatter\MoneyFormatterInterface` (you will probably want to decorate `Sylius\Bundle\MoneyBundle\Formatter\MoneyFormatter`).
