### ISSUE TITLE
Allow for multiple stores or store fronts

### ISSUE THREAD

**Issue by smuriu** [Sylius/Sylius#321]
Hello,

I would suggest in a future version to allow to create, configure and manage inventory, sales, etc for multiple stores with one Sylius installation. Possibly with some configuration shared among all stores. Some users would also be restricted to manage or access just one store while others may be able to access or manage multiple (or all) stores. What do you think?

**Comment by tristanbes** [comment]
:+1: @steffenbrem

**Comment by brunoroux** [comment]
:+1: @steffenbrem 
that would be awesome

**Comment by codebakery-ch** [comment]
Can I do something to help with this or is this even still planned? It's on the road map (even checked), so not sure what the current status is... But it is the single missing feature for me :) I want to implement geo based searching for products/stores on this.

**Comment by pjedrzejewski** [comment]
New issue #2941.

**Comment by marvinjewelz** [comment]
Hi @codebakery-ch , have you made any progress for having Store Owners who can login to their own store.

**Comment by codebakery-ch** [comment]
hi @marvinjewelz
actually no, after the PR got rejected, I went on to make my own solution, not based on sylius...
