### ISSUE TITLE
Make Product toggleable

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#3213]
Allow for disabling and enabling products with ToggleableInterface.

**Comment by michalmarcinkowski** [comment]
Must have feature :+1:

**Comment by pamil** [comment]
Same with `ShippingMethod`, `PaymentMethod`, `Currency`, `Channel` and many more :)

**Comment by gperdomor** [comment]
:+1:

**Comment by gperdomor** [comment]
Toggleable <code>Channel</code>, <code>Currency</code>, <code>PaymentMethod</code> and <code>ShippingMethod</code> are handle in #3226, #3227, #3228, and #3229

**Comment by pamil** [comment]
@gperdomor wow, that's great! I'll take a look at these tomorrow :)
