### ISSUE TITLE
Rename SyliusApiBundle to SyliusOAuthServerBundle and move routing to core

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#3214]
Hey guys!

SyliusApiBundle is just an integration layer between Sylius and FOSOAuthServerBundle. I think we should rename it appropriately and move all routing configuration and API tests to CoreBundle, which seems like the appropriate place.

This would make Sylius more flexible, by allowing not only OAuth authentication for API.

Let me know what do you think.

**Comment by aRn0D** [comment]
:+1:

**Comment by michalmarcinkowski** [comment]
:+1:

**Comment by gperdomor** [comment]
:+1:

**Comment by pjedrzejewski** [comment]
Now I think it should be the other way around, move FOSOAuth integration to SyliusOAuthServerBundle and move API related stuff to ApiBundle. That would make both bundles optional.
