### ISSUE TITLE
Class Doctrine\ODM\MongoDB\DocumentManager does not exist

### ISSUE THREAD

**Issue by paceto256** [Sylius/Sylius#3215]
when I checkout the sylius/sylius project and run:

bin/phpspec run -fpretty

It Breaks with:
<code>
----  broken examples

        Sylius/Bundle/ResourceBundle/Doctrine/ODM/MongoDB/DocumentRepository
  43  ! is initializable
        exception [exc:ReflectionException("Class Doctrine\ODM\MongoDB\DocumentManager does not exist")] has been thrown.
</code>

when using the translate command like this:
php app/console translation:extract bg --dir=./src/Sylius/Bundle/TranslationBundle --output-dir=./src/Sylius/Bundle/TranslationBundle/Resources/translations/ --output-format yml

The same error:
<code>
PHP Fatal error:  Class 'Doctrine\ODM\MongoDB\DocumentRepository' not found in /home/paceto/test/Sylius/src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/MongoDB/DocumentRepository.php on line 25
</code>

**Comment by paceto256** [comment]
Maybe to add "doctrine/mongodb-odm-bundle": "~3.0" dependency to  "require" composer.json ?

**Comment by pjedrzejewski** [comment]
In one of my branches I have added SkipExtension from Akeneo guys, to skip these specs. We do not want to force installing MongoDB to simply run the specs. Doctrine ODM requires mongo to be installed and they enforce that via composer.

**Comment by pjedrzejewski** [comment]
I will close this when my PR is merged. #2255

**Comment by paceto256** [comment]
My actual issue was with running the translation command for the TranslationBundle:

php app/console translation:extract bg --dir=./src/Sylius/Bundle/TranslationBundle --output-dir=./src/Sylius/Bundle/TranslationBundle/Resources/translations/ --output-format yml

where I'm getting:
<code>
PHP Fatal error:  Class 'Doctrine\ODM\MongoDB\DocumentRepository' not found in /home/paceto/proj/monparfume/src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/MongoDB/DocumentRepository.php on line 25
</code>

But if you are able to decouple the ResourceBundle from Doctrine it should be also fine if I get you right.

**Comment by michalmarcinkowski** [comment]
Fixed in https://github.com/Sylius/Sylius/pull/3357

**Comment by michalmarcinkowski** [comment]
I realized than only PHPspec issue is resolved, not `app/console translation:extract`

**Comment by pamil** [comment]
There is an issue on JMSTranslationBundle` side, but you can avoid errors by adding `--exclude-dir=Tests --exclude-dir=ODM` to your command.

**Comment by stloyd** [comment]
IMO we should drop usage of `JMSTranslationBundle`... The code is "dead", and it's not used commonly in Sylius, as well it can produce errors due too it's bugs.

**Comment by pamil** [comment]
It's fixed, we got AkeneoSkipExampleExtension now.

**Comment by michalmarcinkowski** [comment]
What about https://github.com/Sylius/Sylius/issues/3215#issuecomment-137461374?

**Comment by pamil** [comment]
Can be solved using https://github.com/Sylius/Sylius/issues/3215#issuecomment-143692394, also we've followed this proposition https://github.com/Sylius/Sylius/issues/3215#issuecomment-143693027 in #6378 and `JMSTranslationBundle` is no longer installed with Sylius.

**Comment by michalmarcinkowski** [comment]
:+1: closing then.
