### ISSUE TITLE
orderConfirmation.html.twig has empty body block

### ISSUE THREAD

**Issue by liviucmg** [Sylius/Sylius#3220]
OrderConfirmation.html.twig, along with a few others, have empty body blocks. There should be some sane defaults, at least as a starting point. The order confirmation could be something like "Hello {{ user }}, this is an email confirmation for your products: {{ list_of_products }}.". I am going to implement them anyway for a client. Would you accept a PR as well?

Cheers!

**Comment by pjedrzejewski** [comment]
@liviucmg Of course we will accept a PR. Just keep them simple, because I think everyone will customize them anyway. :)

**Comment by michalmarcinkowski** [comment]
Fixed.
