### ISSUE TITLE
[RFC] Order shouldn't have currency property

### ISSUE THREAD

**Issue by kayue** [Sylius/Sylius#3222]
I have been looking into multiple currency implementation lately, and found that Order shouldn't have a currency property.
- Order's currency can be vary based on the payment method, some payment method can only accept one currency, some can accept more.
- An order could contain multiple payments, and each payment can be settle in different currency.

So it doesn't really make sense to have a currency property in Order object.

**Comment by kayue** [comment]
I think at least the order currency should be updated when payment is confirmed, it makes sure order and payment have the same currency.

**Comment by michalmarcinkowski** [comment]
I don't see a real use case for supporting payments in many currencies for a single order, in what currency we store the amounts then? What exchange rates are applied? It's too complex and not really common. What is more, we can be sure there will be rounding issues. Now the orders are placed in a one currency that is immutable and all amounts are stored in the currency of the order.
