### ISSUE TITLE
[RFC] Consider using auto-deploy with Platform.sh for PRs

### ISSUE THREAD

**Issue by stloyd** [Sylius/Sylius#3246]
Just finished reading: http://symfony.com/blog/how-we-auto-deploy-documentation-pull-requests-with-platform-sh and I think we should re-consider (we had something similar in old days) auto-deploy for PRs to the Platform.sh for much easier testing on various platforms (and also on different browsers etc. when it comes to the UI).

What do you think guys & gals?

**Comment by pjedrzejewski** [comment]
I love the idea and the only reason we stopeed using stage1 - it was unrealiable... With Platform.sh, is it free for open source? I can't find any info.

**Comment by stloyd** [comment]
Didn't find anything about open source support, I guess you would need to reach them via mail/twitter & ask.

About integration I found this: https://platform.sh/deploy-github-pull-request/

**Comment by stefandoorn** [comment]
@Crell Probably knows the answer to this ;-)

**Comment by Crell** [comment]
I'm unclear what you're asking about? :-)  Platform.sh offers sponsored hosting for web sites for OSS projects and local communities/meetups/confs.  Track me down in our Slack or a Twitter DM to get that set up.

If you mean using Platform.sh to test out PRs against the codebase itself, that's a different animal.  We'd have to discuss that in more detail.  Again, track me down in Slack if you're interested.

**Comment by pamil** [comment]
Update since 2015: Sylius uses Platform.sh for hosting [demo application](http://demo.sylius.org/). Having PRs support would be nice as well, I'll try to contact with you on Slack next week :)
