### ISSUE TITLE
Taxation Bundle wont work (if follow docs)

### ISSUE THREAD

**Issue by Mrkisha** [Sylius/Sylius#3247]
I haven't managed to make TaxationBundle work as a stan-alone bundle for my project. I had really hi hopes, but now I'm stuck.

Documentation is so poor. Even when I go trough source code I've managed to come to some point and than I hit the wall again.

so I'm in route `tax-rates/`
and I'm getting this error:
`InvalidTypeException in ArrayNode.php line 267:
Invalid type for path "sylius_taxation.classes.tax_category.form". Expected array, but got string`

**Comment by pjedrzejewski** [comment]
Thank for reporting, we need to update the documentation, but this is a lot of work and will happen iteratively. Sorry for the inconvenience. :/

**Comment by Zales0123** [comment]
I hope with provided documentation fixes it will be more comfortable to use TaxationBundle ;) I think it can be closed.

**Comment by Mrkisha** [comment]
Some how, after hours and hours of digging into code of SyliusTaxationBundle, I've made it to work. If there is interest I'm willing to create a Cookbook example about. Let me know what do you guys think.

**Comment by michalmarcinkowski** [comment]
@Mrkisha that would be great! The documentation is something we certainly need to work on, so we're open to any kind of help there :wink:

**Comment by pjedrzejewski** [comment]
@Mrkisha :+1:
