### ISSUE TITLE
[RFC] Use Traits to handle common entities

### ISSUE THREAD

**Issue by gperdomor** [Sylius/Sylius#3248]
With the #3110 merged,Sylius now require PHP 5.5, so can we use Traits, so i propose use some traits to handle common properties and methods which are repeated on many entities, like: <code>Gedmo\Timestampable\Traits\TimestampableEntity</code>, <code>Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity</code>, and also create a new trait for toggleable entities

**Comment by stloyd** [comment]
Yes, this is one of reason Sylius is migrating to newer PHP version, to be able to use advantages of the language :wink:

**Comment by pjedrzejewski** [comment]
Yes, but before we introduce traits, let's discuss them here - what and where we want to use to avoid misusing them.

My quick list:
* Timestampable
* Softdeleteable
* Translatable
* Sortable

**Comment by michalmarcinkowski** [comment]
I would add also `Toggleable` :wink:

**Comment by gperdomor** [comment]
what about entities with images? I would add also <code>ImageTrait</code>

**Comment by patkar** [comment]
Traits for all the XyzAwareInterface stuff?

**Comment by stloyd** [comment]
@patkar Mostly, yes. That would allow to greatly reduce amount of duplicated code between components.

**Comment by pjedrzejewski** [comment]
@patkar @stloyd This is wrong usage of traits. It only hides complexity. XyzAware is not a trait.

**Comment by stloyd** [comment]
@pjedrzejewski Ah right, I misread that @patkar mentioned "aware" :wink:

**Comment by patkar** [comment]
I don't get it, why not. For example the `OrderAwareInterface`. Most models implementing this interface have to repeat the same implementation. A `OrderAwareTrait` would supply a default code for all models sharing the same standard implementation.

A more complex model with other implementation of `OrderAwareInterface` must indeed code it's own implementation.

**Comment by pjedrzejewski** [comment]
The thing is, with this approach, you can have a monstrum class, which uses 53445 traits and it only hides its complexity, which is wrong. We could do that for every common property, like Name, Id, Description etc. But this is wrong usage of trait, it hurts the quality of code.

**Comment by patkar** [comment]
It's a valid and good argument.

I've always used traits to extract common getters and setters for relations which are used in multiple entities. For example address. But yes, it hides the implementation.

**Comment by aRn0D** [comment]
Agreed with @patkar, we just need to limit the number of trait we want to use by classes and we need to be vigilant when we reviews PRs!

**Comment by pjedrzejewski** [comment]
@aRn0D @patkar :+1:
