### ISSUE TITLE
Missing controllers

### ISSUE THREAD

**Issue by kkarski82** [Sylius/Sylius#3250]
I've just recently noticed that there is a bit of a problem with the WebBundle services configuration.

Parameters:
```sylius.controller.frontend.account.profile.class``` is declared as ```Sylius\Bundle\WebBundle\Controller\Frontend\Account\ProfileController``` (no such file)
```sylius.controller.frontend.account.class``` is declared as ```Sylius\Bundle\WebBundle\Controller\Frontend\Account\AccountController``` (no such file)

Services:
```sylius.controller.frontend.account.profile``` and ```sylius.controller.frontend.account```

That's in ```WebBundle/Resources/config/services.xml```

**Comment by michalmarcinkowski** [comment]
Fixed in #3285
