### ISSUE TITLE
Sylius Paypal IPN Refund not working

### ISSUE THREAD

**Issue by Buri** [Sylius/Sylius#3251]
When refunding payment in Paypal, notify action is correctly send and logged in sylius administration, however no change is made to the payment.

Is this correct/intended behaviour or should it react automatically on refund notifications?

**Comment by pjedrzejewski** [comment]
Currently the "refund" button only marks it as refunded in Sylius. We need integration with Payum action. /cc @makasim

**Comment by makasim** [comment]
Payum support only refund of paypal pro payment atm (and some others gateways), the rest have to be implemented.
