### ISSUE TITLE
Frontend is not respecting the channel_based pricing 

### ISSUE THREAD

**Issue by paceto256** [Sylius/Sylius#3253]
1. I install 3 Instances of Sylius  (admin.com, chan1.com, chan2.com)
2. I created a channels for  chan1.com and chan2.com (the channels are defined fine because I am able to hide products just for one channel)
3. In admin.com I define a product "A" that is associated with  chan1.com and chan2.com
When defining the product "A" I am creating channel_based prices and I type 2 different prices for each channel.

Current behaviour:
The price in both channels chan1.com and chan2.com fallback to the default price.

Expected behaviour:
Each channel to respect the channel_based price associated to it.

**Comment by pjedrzejewski** [comment]
Note to self/anyone who fixes it: Current channel is not passed in template to the pricing twig function.

**Comment by michalmarcinkowski** [comment]
Should be fixed now.
