### ISSUE TITLE
Choice attributes are reset to first values when editing a product

### ISSUE THREAD

**Issue by paceto256** [Sylius/Sylius#3254]
1. I create a Product "A" with two "choices attributes".
2. I go to edit this product and click on the attributes tab

Current:
The select menus for both choice attributes are set to the first available value, but not to the database value, so If you click "Save Changes" the real values of the attributes will be overwritten.

Expected:
The select menus should be set according to the database values of the attributes.

**Comment by mingxing** [comment]
Hi, any update or a patch to fix it? Thank you

**Comment by pjedrzejewski** [comment]
This will be resolved by https://github.com/Sylius/Sylius/pull/3608.

**Comment by Zales0123** [comment]
After attribute types system change it should not happen anymore.

**Comment by michalmarcinkowski** [comment]
Please reopen if still relevant.
