### ISSUE TITLE
[RFC] Introduce PhpSpecSkipExampleExtension for phpspec

### ISSUE THREAD

**Issue by stloyd** [Sylius/Sylius#3260]
With the extension https://github.com/akeneo/PhpSpecSkipExampleExtension for phpspec we would be able to finally make specs passing even if env is not fully compatible with those specs.

I guess this will be also must have for PHP 7 to pass well as the extensions are not yet converted to that version.

**Comment by pamil** [comment]
There's one issue that prevents from using it - https://github.com/akeneo/PhpSpecSkipExampleExtension/issues/9.

**Comment by pjedrzejewski** [comment]
Included in #2255 + what @pamil said.

**Comment by michalmarcinkowski** [comment]
Fixed in v1.2.0 https://github.com/akeneo/PhpSpecSkipExampleExtension/issues/9.

**Comment by pamil** [comment]
@pjedrzejewski I had to implement it in #3337 to get PhpSpec running on PHP 7 without any errors, but rebasing Resource refactoring with that changes shouldn't be hard :)
