### ISSUE TITLE
[FORMS][UX] - unclickable upload button area (in blocks)

### ISSUE THREAD

**Issue by nakashu** [Sylius/Sylius#3263]
All upload buttons for images/files have currently unclickable areas and/or poorly clicable areas.
This is only really visible in content/block(images/slideshow), as 80% of the button is unclickable, but the same problem is present in products, etc.
Only the bottom part of the button is clickable.

The issue is because of using absolute positioned <span> that should be make the "fake" button.
The real <input> is with opacity: 0 above this fake span button ..
The problem is the margins are making it offset too low.

From my point of view the position: absolute / hover above thing is bad, as it could be done way easier using <label for="id-of-input"> instead of the <span> with the input hidden all together.
Plus removing of unnecessary css rules.

Also the fake button styles on the button have fixed width of 200px, that will definitely make some problem with translations.

I will make an PR if the are no objections for this approach?
It would be good place to start with all this contribute/fork/pr combos stuff

```
// WebBundle/Resources/views/Common/forms.html.twig
// lines 18-20
{% if 'file' == type %}
        <label class="btn-primary btn-lg file-overlay" for="{{ form.vars.id }}"><i class="icon-folder-open"></i> {{ 'sylius.form.choose_file'|trans }}</label>
{% endif %}
```

**Comment by pjedrzejewski** [comment]
@nakashu Go for the PR, I think this is a good fix. :) We will replace it with some js dropzone library later on. :)

**Comment by nakashu** [comment]
PR Was merged .. should be fixed .. closing
