### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by PurpleBabar** [Sylius/Sylius#3273]
Hi everybody, i'm getting this error on install :/

php app/console sylius:install
Installing Sylius...

Step 1 of 4. Checking system requirements.
+-------------------------------+----------------------------------------------------------------------------+
| Issue                         | Recommendation                                                             |
+-------------------------------+----------------------------------------------------------------------------+
| short_open_tag                |                                                                            |
| session.auto_start            |                                                                            |
| sylius.extensions.accelerator | Installer et activer un accélérateur PHP comme APC (fortement recommandé). |
+-------------------------------+----------------------------------------------------------------------------+
Success! Your system can run Sylius properly.

Step 2 of 4. Setting up the database.
Creating Sylius database for environment dev.
 1/4 [||||||||                    ]  25%PHP Fatal error:  Cannot redeclare class Gedmo\Loggable\Entity\MappedSuperclass\AbstractLogEntry in /home/vagrant/share/weeknlearn/vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity/MappedSuperclass/AbstractLogEntry.php on line 13

                                                                                                 
  [Symfony\Component\Debug\Exception\FatalErrorException]                                        
  Compile Error: Cannot redeclare class Gedmo\Loggable\Entity\MappedSuperclass\AbstractLogEntry  
                                                                                                 

doctrine:schema:create [--dump-sql] [--em [EM]]

I already tried reinstalling... do i need to change gedmo version or wait a patch coming from you ? 

thx for the reply

**Comment by herodrigues** [comment]
Try to clean your cache

```bash
php app/console cache:clear
```

**Comment by pjedrzejewski** [comment]
Hello @PurpleBabar!

Please post this question on StackOverflow - it is the official support channel for Sylius. Just tag your question with "sylius" and maybe someone will be able to help you! http://stackoverflow.com/questions/tagged/sylius

**Comment by PurpleBabar** [comment]
Hello @pjedrzejewski,
thx for the reply, i manage to solve my problem, changing several things in my configuration. :)
thx @herodrigues  for the reply too :)

i actually reinstalled the project in the standard edition and it worked. (first install was with the *composer create-project -s dev sylius/sylius* installation, and i redid it with *composer create-project -s dev sylius/sylius-standard acme* installation)

Thx to you two
