### ISSUE TITLE
[Addressing] composer.json not up to date

### ISSUE THREAD

**Issue by Lowlo** [Sylius/Sylius#3275]
Hello,
I think Addressing is not up to date with the Sylius/Sylius repository.
We can see differences between the two composer.json files.

Thanks for all your work.

**Comment by pjedrzejewski** [comment]
@Lowlo Thank you for the heads up, I started the repo update script.

**Comment by Lowlo** [comment]
I'm sorry to disturb but i don't see update.
Thanks for your time.

**Comment by Lowlo** [comment]
ping @pjedrzejewski
