### ISSUE TITLE
API request returns hwi_oauth_security (/connect) route as response.

### ISSUE THREAD

**Issue by goemaere** [Sylius/Sylius#3276]
Hi, 

I tried to use the Sylius API by using following guide:
http://docs.sylius.org/en/latest/api/authorization.html

Authorization seems okay because no 'bad request' errors occur.

If I try to fetch, for example, a list of all taxonomies, I'm getting a Sylius\Api\InvalidResponseFormatException because the API returns me the contents of the hwi_oauth_security (/connect). It's the one with the amazon/facebook/google login links.

I tried with the [HTTPful library](http://phphttpclient.com/), and with [Lakios' client](https://github.com/Lakion/sylius-api-php). Both same response. This is on Sylius 0.14 btw, I tried this on a fresh install too, also same response.

Am I missing something here?

**Comment by pjedrzejewski** [comment]
Hello @goemaere!

Please post this question on StackOverflow - it is the official support channel for Sylius. Just tag your question with "sylius" and maybe someone will be able to help you! http://stackoverflow.com/questions/tagged/sylius
