### ISSUE TITLE
Update taxes on order update ?

### ISSUE THREAD

**Issue by SebLours** [Sylius/Sylius#3299]
Hi,

When an order is updated in the backend (item price update), taxes are not recalculated.
To resolve it, i have add the "sylius.order.pre_update" event to the "sylius.listener.order_taxation" listener to apply taxes.

May i do a PR to resolve it or it is not a desired behavior ?

Nice day
Seb

**Comment by michalmarcinkowski** [comment]
Hi Sébastien, thanks for reporting this.

Every listener that listens to `sylius.cart_change` event should be moved on Doctrine onFlush event (like refresh listener in the comming PR https://github.com/Sylius/Sylius/pull/3351/files#diff-74784ab13887420c41c9400c30b5e8c2R25) to ensure it is invoke every time the Cart/Order is changed without need to remeber to dispatch `sylius.cart_change` event.

I think it will resolve this issue. If you have some time you can try this solution.

**Comment by pjedrzejewski** [comment]
The backend order editing is very temporary solution, we will rework it as we work on adding an order functionality.

**Comment by michalmarcinkowski** [comment]
Order editing in the backend is not available in the new admin and probably will be added after 1.0
