### ISSUE TITLE
[BUG] Date expiration of coupon

### ISSUE THREAD

**Issue by thiphamyp** [Sylius/Sylius#3302]
When I create or edit a coupon (There is no expiration field)
The expiration date is set automatically to NOW()
I can not use this coupon on shopping cart because it already expired

I am on version `0.16-dev`

**Comment by inssein** [comment]
@thiphamyp should be fixed in master now. Could you confirm?

**Comment by tristanbes** [comment]
@thiphamyp you can close the ticket :+1:

**Comment by michalmarcinkowski** [comment]
Closing, as this is fixed already.
