### ISSUE TITLE
[RFC] Migrations

### ISSUE THREAD

**Issue by michalmarcinkowski** [Sylius/Sylius#3303]
Issue
-------
Right now we don't run migrations on CI, so we don't validate if migrations work or even exist. Let's be honest they are not handled properly right now.

Solution
-----------
I suggest removing all existing migrations and generate first migration that will build the v0.15 database schema and do `app/console do:mig:mig` instead of `app/console do:sc:cr` on travis. Thanks to that we can validate that migrations work and there is nothing missing.

Enhancement
------------------
We can create `sylius:migrate` command which will run all migrations from `/vendor/sylius/sylius/app/migrations/` to ease Sylius update on existing projects (e.g. using Sylius-Standard).

**Comment by gperdomor** [comment]
:+1:

**Comment by kayue** [comment]
:+1:

**Comment by pamil** [comment]
:+1:, any ideas on testing reverting migrations?

**Comment by pamil** [comment]
Made PR with that changes (#3326). Do you think that migrations should be per change or per version?

 - Creating them per change may result in similiar operations being executing more times than needed (ex. creating table X, changing X.Y columnt type, adding new field X.Z etc.) 
 - Creating them per version drops support for those, who uses current dev version (and they can be really big).

IMHO we should add new migrations per change during development phase and bind them into one while releasing new version.

**Comment by michalmarcinkowski** [comment]
@pamil your last sentence is the way we should handle them :wink:

**Comment by pamil** [comment]
Anyway, what with Sylius bundles that we want to keep standalone and use migrations as well? I guess we will have to store these doubled, although we can use the same "cleaning" policy as with the application ones.

**Comment by vikey89** [comment]
:+1:

**Comment by pamil** [comment]
Solved by #6417.

**Comment by pamil** [comment]
Travis runs migrations and validates schema, so we can be sure that migrations are up-to-date.
