### ISSUE TITLE
[RFC] Travis running PhpSpec on PHP 7

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#3312]
As for now, we don't run PhpSpec on PHP 7 due to issues with typehint. There is [a tool](https://github.com/digitalkaoz/typehint-to-docblock) that converts typehints to docblocks, that works like a charm on PHP 7. 

Should we use it for now or wait for native PhpSpec support for typehints on PHP7?

**Comment by digitalkaoz** [comment]
is it working for the sylius specs?

**Comment by pamil** [comment]
@digitalkaoz sure, it works both on PHP 5 and PHP 7. It will be done on Travis side, we will still use typehints in specs.

**Comment by digitalkaoz** [comment]
thats how i do it in my projects...just questioning if the tests passes or there are some bugs with the conversion

**Comment by pamil** [comment]
For now, I tested only a few components, but I don't think that something will break up unexpectedly.

**Comment by digitalkaoz** [comment]
great lets hear me the progress :) hopefully @phpspec fixes php7 compat soon that this workaround will be obsolete

**Comment by pjedrzejewski** [comment]
@pamil I'd say we can do it. :)

**Comment by pamil** [comment]
It works - #3337 :)

**Comment by digitalkaoz** [comment]
yiiihaa :)
