### ISSUE TITLE
[Core][MoneyHelper] - default locale should not return current locale

### ISSUE THREAD

**Issue by nakashu** [Sylius/Sylius#3321]
based on this: [#3071#issuecomment-141682129](https://github.com/Sylius/Sylius/issues/3071#issuecomment-141682129)

in Sylius\Bundle\CoreBundle\Templating\Helper\MoneyHelper getDefaultLocale should return *default* locale instead of *current* locale.

```
 /**
     * {@inheritdoc}
     */
    protected function getDefaultLocale()
    {
        return $this->localeContext->getCurrentLocale();
    }
```

It return the unexpected, and down the road starts up the session, which block cache clearing in console as described, in the above mentioned comment.

I can fix this, if it is confirmed as bug and not an intention.

**Comment by pamil** [comment]
Wrote a quick PR with fixed method, probably I had done it by accident while refactoring whole locale thing.

**Comment by nakashu** [comment]
thanks @pamil

**Comment by pamil** [comment]
#3323 is merged, guess it can be closed now.
