### ISSUE TITLE
[RFC] - should On DELETE: cascade be set for everything product related ?

### ISSUE THREAD

**Issue by nakashu** [Sylius/Sylius#3349]
Currently there are tables in the product tree that have On DELETE: **CASCADE** set.
For example

| FK on | Pointing To |
| --- | --- |
| sylius_product_variant | sylius_product |
| sylius_product_translation | sylius_product |

But trying to delete a product from the main table will fail due to constrains violation, for few other tables like that have "on Delete" set to **RESTRICT**. like 

| FK on | Pointing To |
| --- | --- |
| "sylius_product_variant_image" | "sylius_product_variant" |
| "sylius_order_item" | "sylius_product_variant" |

This inconsistency makes impossible to delete a record in sylius_product table and let it cascade to delete all related data.
Even if you want to use the cascading that are set like for the translation table, first you would have to delete all record that are FKs with restrict set on.

I understand that in production, you should not really delete existing products that were part of orders or whatever, and only set them deleted status / time. Although there are some use cases where cascade delete would be nice like:
- importing products;  set status disabled; review import; clear import because of some problems (cascade delete);  re-import with fixed data.
- manual deletions in db while developing.

There should be done one of two things:
- Let cascade everything on delete for a specific chain: eg. delete product archetype, and cascade to products, variants, images, orders, archetype attributes and options
- restrict cascade for everything on delete for a specific chain.

**Comment by CoderMaggie** [comment]
Hi! I am not sure, but I believe this is not relevant anymore. The issues with deleting resources in Sylius will be solved by archivization approach.
☮️
