### ISSUE TITLE
[CartBundle] Reaccess to shipment step in checkout process generate error

### ISSUE THREAD

**Issue by Arminek** [Sylius/Sylius#3353]
How to reproduce:

1. Start with an empty cart
2. Add an item
3. Proceed to checkout
4. Enter your personal details
5. Select shipping method
6. Go back anywhere on site
7. Repeat the steps above

![zrzut ekranu 2015-09-24 o 16 38 41](https://cloud.githubusercontent.com/assets/6368946/10076247/d1ff60a4-62da-11e5-85ae-92f07829db8a.png)

**Comment by michalmarcinkowski** [comment]
Thanks for reporting :+1: 

Closing this one as it is tha same issue as https://github.com/Sylius/Sylius/issues/2979
