### ISSUE TITLE
[RFC] Consider using DoctrineEnumBundle

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius#3360]
I tried recently [DoctrineEnumBundle](https://github.com/fre5h/DoctrineEnumBundle) and I really liked it. 

We can use it to replace constants like `OrderInterface::STATE_*`.

Reasons to use it:
- Extract constants to well defined enum types.
- Use more optimal data types for fields like order state (e.g. smallint).
- Proper enum validation with `@DoctrineAssert\Enum` constraint.
- Automatic form type guessing with `EnumTypeGuesser`.
- Easy rendering with Twig readable extension.
- Hook for Doctrine migrations.

**Comment by diimpp** [comment]
:+1:
