### ISSUE TITLE
Idea - Change theme with parameters 

### ISSUE THREAD

**Issue by codingideas** [Sylius/Sylius#3361]
I have a idea that we can talk about while we everyone works on the current version: http://sylius.org/roadmap 

What i suggest is that we are able to have two features:

Child themes.
Change theme in the URL.

The benifit of changing the theme in the URL is for a/b testing. I can see myself testing conversion rate between entire themes - a vs b in google analytics content experiments. However if you're testing a full theme while the visitors browse it needs to be set in a cookie. 

Now child themes are a mirror of the parent with overrides for the parent. This way CRO guys and test different home pages such as with products vs with categories or maybe moving positing on the add to cart to test goal flow. 

This is just a conversation I wanted have some some of you guys. I feel adding this type of functionality would bring some good marketers to pitch this software to their clients.

**Comment by pjedrzejewski** [comment]
Have you seen #2844? :)

**Comment by codingideas** [comment]
I haven't but I am reading the comments there. Should I merge my comment to there?

**Comment by pjedrzejewski** [comment]
@codingideas Yes, please! :)
