### ISSUE TITLE
Feature Request: Enhanced Ecommerce

### ISSUE THREAD

**Issue by imcodingideas** [Sylius/Sylius#3363]
https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce?hl=en

I would like to prepose added Enhanced Ecommerce to Sylius. It would be cool to have Impression Data specifcally.

**Comment by ikovacic** [comment]
Hi, we published Ehnanced Ecommerce bundle a month ago.

https://github.com/webburza/sylius-google-ecommerce-bundle

**Comment by pjedrzejewski** [comment]
This is a task for external bundles. Bravo and thank you @ikovacic! :)
