### ISSUE TITLE
[RFC] Promotions Enhancements - Benefits & Filters

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#3368]
This RFC describes a suggested approach to improving the promotions system within Sylius to cover a much wider set of use-cases than it currently does.

For a longer description of how these limitations were discovered see #1810, but to summarise - Currently there’s no way of filtering the target of your promotion logic beyond being applied to the whole order. You cannot apply it only on certain OrderItems that match a criteria.

We spend a lot of time last week researching possible permutations of promotions along with a few whiteboard sessions. Our resulting approach is based on these permutations and trying to model them from the admin users’ perspective whilst respecting the existing code as far as possible. No serious code has been written yet, we wanted to put it out for feedback first.

Firstly here are the scenarios that we looked at trying to model (all starred ones cannot be achieved with the current functionality):
- Get 20% off your first order
- Get 20% off if spend more than 200
- Get a free gift if you buy at least one dress
- Get a free gift for every dress you buy*
- Get a 10% off jacket if you buy trousers*
- Get free shipping if you spend more than 500
- Get a free gift card and 20% off dresses if you buy dress*
- Get 10% off any sale dresses*
- Get 10£ off suits if you spend more than 500 and get free shipping*
- Get 20% off suits if you spend more than 500 and get 50£ off order*
- Get 10% off bow tie and belts if you buy jackets or trousers*
- Get 10% off on dresses if these costs more than 300 and get 15 off jackets if these costs more less than 250 when you place first order*

The easiest way to explain the proposal is visually. These visuals are not final and after discussing with a UX designer they could definitely be simplified, but will hopefully make sense in the following format to those familiar with the existing engine:

![screen shot 2015-09-28 at 15 07 05](https://cloud.githubusercontent.com/assets/7068515/10139387/8c62dfda-65fa-11e5-9316-ab8ba1d09e12.png)

This mock-up screenshot models a very complex promotion.
### Explanation:

Rules still exist, they decide whether your basket qualifies for the promotion and will be run in the same way. Your order must pass all rules.

Actions have changed and now consist of 2 parts - Benefits and Filters.
Benefits are what we previously called Actions and reflect what the customer gets from this promotion. 
Filters decides which of the PromotionSubject components (OrderItems) are valid targets for that Benefit. It could be a very simple promotion where the target is the ‘Whole Order’ or a subset of the OrderItems defined by some logic.
It’s possible that a single Benefit could require multiple Filters that are applied together (AND).
You can have multiple Actions for a single promotion and multiple Filters per Benefit.
### More Detail:

Multiple Actions were decided on because in my experience most promotions (if not all) will be exclusive, but may often have multiple ‘parts’. Some of the examples above could possibly be achieved with allowing multiple promotions to be used together, but this feels like a dirty solution if you can’t control which promotions can be used in combination - which you can’t in Sylius! and I wouldn’t want it anyway, it gets very messy. There’s an argument to remove inclusivity altogether...

The layout has been changed to put Benefits first (this is because when we started talking about them as humans we realised that the benefit was always the first and most important point when defining the promotion).
### Short-comings:

Currently we haven’t modelled ‘OR’ with Filters (e.g. get 10% off all Dresses or items > £250). this was because adding this kind of complexity to the logic building felt a step too far for this phase. It’s doable, and the biggest challenge would be the UI, but for now if you want to implement this you should do so as a developer within your custom Filter, and we look forward to someone adding builder logic in future!

Please let us know what you think - are there any cases that this won't work for that affect you? anything we've missed?

**Comment by PWalkow** [comment]
### Filters:
Filters would work by limiting the OrderItems in the Order like on the screenshot (both examples are shown).
##### Let me try to explain this example:
Any order that will pass rules will get to filters and orderItems will be filter down in the order from top to bottom so
- by archetype: Dresses ( now we are having only Dresses)
- by cost more than 300 ( now we are having only Dresses that costs more than 300)

In this example benefit of 'Percentage discount' will be applied to Dresses that costs more than 300 (any other item in the Order will not get any benefit)

##### Second example is:
- by archetype: Jackets ( now we are having only Jackets)
- by cost less than 250 ( now we are having only Jackets that costs less than 250)
- by most expensive one ( now we are having only one Jacket that is most expensive among these that cost less than 250)

In this example benefit of 'Fixed price discount' will be applied to the most expensive jacket that cost less than 250.

**Comment by brunoroux** [comment]
I spent some time trying to fully understand this and mostly trying to see if it would fit our common promotions. And it just does. So :+1:

**Comment by tristanbes** [comment]
I'm :+1: too and must admit it took me some time too :) great proposition guys

**Comment by peteward** [comment]
Just and update, we have a PR for much of this work, it depends on some changes to Adjustments in another PR but we are getting there...

**Comment by Mr-Negative** [comment]
@peteward  any update about it?

**Comment by peteward** [comment]
Most of this functionality was implemented by the Lakion team as 'Filters' however there's no UI to adding these on 'Actions' yet. It isn't too complicated to do though (i've done it for our project).

I'm not sure if Lakion intend to add this for 1.0 though. It would be a shame if they didn't since most of the hard work has been done.
