### ISSUE TITLE
Order, Payment and Shipment state-machine states and transitions.

### ISSUE THREAD

**Issue by aramalipoor** [Sylius/Sylius#3374]
I looked through `sylius_order`, `sylius_payment` and `sylius_shipment` to create a diagram out the states and transitions of each one.

What confuses me is that what is the application flow (real user order placement) regarding these states and transitions?! It would be good if you could point to a doc or maybe write one up now!

These are the diagram's I've come up with, I can polish them until they're ready to be used in documentations (or even notice some bugs and missing transitions :p):

[**Order States & Transitions**](http://creately.com/diagram/if5975wv1/Order%2BStates%2B%2526%2BTransitions)
![Order States and Transitions](http://creately.com/jupiter/diagram/image/if5975wv1)

[**Shipment States & Transitions**](http://creately.com/diagram/if4wn9q61/Shipment%2BStates%2B%2526%2BTransitions)
![Shipment States and Transitions](http://creately.com/jupiter/diagram/image/if4wn9q61)

[**Payment States & Transitions**](http://creately.com/diagram/if5975wv2/Payment%2BStates%2B%2526%2BTransitions)
![Payment States and Transitions](http://creately.com/jupiter/diagram/image/if5975wv2)

**Comment by aramalipoor** [comment]
Holly molly I just realized there is a page in the wiki for that!! https://github.com/Sylius/Sylius/wiki/Status

**Comment by kayue** [comment]
Good chart. We should highlight the starting point. 

Also the cart can be confusing if developer read it as a flow chart. For example "Cart -> Pending -> Released -> Confirmed" doesn't make sense because "Released" shouldn't be part of the flow.

**Comment by aramalipoor** [comment]
Thanks for the feedback, fixed it ;)

**Comment by michalmarcinkowski** [comment]
As @aramalipoor mentioned here https://github.com/Sylius/Sylius/pull/3403#issuecomment-146228329, since we have `authorized` state on a `Payment` we should have one more transition `authorize` from `pending` and `processing` states. Moveover `complete` from `authorized` to `completed` and `cancel` from `authorized` to `canceled`.
