### ISSUE TITLE
[RFC] Copy SKU and product name to order item

### ISSUE THREAD

**Issue by patkar** [Sylius/Sylius#3392]
The SKU and the product name should be copied to the order item to have a immutable order view.

When a product gets changed, the order item is changed and a generated invoice is not correct anymore.

Ok, on the first look it may sound simple. But if you think about it, there is more data to be copied. IMHO all the attribute and option (names and) values for the bought variant must be copied to, so a later change doesn't affect the order item.

**Comment by pjedrzejewski** [comment]
Definitely, perhaps we will use logged data to display appropriate product info in order view. This way we can avoid duplication.
