### ISSUE TITLE
root taxonomy permalink

### ISSUE THREAD

**Issue by MichaelKubovic** [Sylius/Sylius#3394]
hi folks!

I'm working with latest release 0.15 and trying to make a simple url structure to work with single taxonomy (called category). How should one achieve the following link structure?

/a   (list of taxons under the taxon a - a is not the root taxon)
/sub-a (list of products)

/b (again list of taxon under the taxon b)
/sub-b (list of products)

Currently current the automatically created root taxon has fixed permalink which doesn't really fit in. :) The rest could be solved with custom SlugHandler I guess or maybe with just a bit of gedmo sluggable configuration.

**Comment by pjedrzejewski** [comment]
Hello Michael!

Please post this question on StackOverflow - it is the official support channel for Sylius. Just tag your question with "sylius" and maybe someone will be able to help you!http://stackoverflow.com/questions/tagged/sylius
