### ISSUE TITLE
[Feature Request] Add cli commands to manage user, groups, roles, like at FOS UserBundle

### ISSUE THREAD

**Issue by diimpp** [Sylius/Sylius#3395]
Hi everyone,

Would be cool to have such set of cli commands for development needs.

I would like to try to implement it, if it have a chance to be merged.

**Comment by aramalipoor** [comment]
Related to #3386

**Comment by pjedrzejewski** [comment]
Hello Dmitri! This is a very good idea, let's keep the discussion in one issue - #3386.
