### ISSUE TITLE
Support for packages of products

### ISSUE THREAD

**Issue by songecko** [Sylius/Sylius#3415]
Hi @pjedrzejewski, what are your opinion about integrate this feature. So, a package (a product itself) with a list of products available to select. The user can select a package and select some products. Take a look at this webpage for reference: https://www.honest.com/bundles (for example, essentials bundle).

Thanks for your time.

**Comment by pjedrzejewski** [comment]
Hey @songecko!

I'd love to support that, but I fear that this particular feature won't make it for 1.0.0. We get a lot of requests and I think for 1.0.0 we will support it via extension/plugin, but not in the core. There is no simple way to handle it with current architecture. It is easy to add is as customization, but it would complicate the core too much.

**Comment by xrow** [comment]
Hi @pjedrzejewski,

can you roughly estimate how much time is needed to fullfill this feature? 

Important would be also that product packages (you might also called them bundles) would need work on products with different tax rates. An example in Germany would be: 7% Tax on a print magazine and 19% on an epaper. Together you can sell them as a package for a certain price and later you would want to show the different tax rates for the different parts of the product seperatly in the cart. http://www.boersenverein.de/ebundle

**Comment by michalmarcinkowski** [comment]
Hi @xrow,

It's a big feature, that will complicate a lot of stuff. I'm afraid it will not be included in 1.0 release. We're focusing right now on stabilization of Core and resolving all fundamental issues that prevents us from 1.0 and this is an extra feature that definitely needs very solid foundation, so we can't introduce it in the nearest future.

You can try to create it as an "extension" that will leave outside of Core and integrate it in your application. We will be definitely interested in this feature in the future, so we could work on that together later.

**Comment by xrow** [comment]
@michalmarcinkowski I have a slight Idea what big means in this context. Thanks for your feedback. Though I can`t belive yet that you could just "extend" that functionality. At least for us we are not yet in the need for having an instant demand on that feature.
