### ISSUE TITLE
Lots of missing translations in SyliusWebBundle

### ISSUE THREAD

**Issue by pfwd** [Sylius/Sylius#3416]
When running 

    php app/console debug:translation en SyliusWebBundle --only-missing

I see

     --------- ---------- --------------------------------------------------- ------------------------------------------ 
      State     Domain     Id                                                  Message Preview (en)                      
     --------- ---------- --------------------------------------------------- ------------------------------------------ 
      missing   messages   sylius.breadcrumb.api_client.index                  sylius.breadcrumb.api_client.index        
      missing   messages   sylius.api_client.create_header                     sylius.api_client.create_header           
      missing   messages   sylius.api_client.create                            sylius.api_client.create                  
      missing   messages   sylius.api_client.index_header                      sylius.api_client.index_header            
      missing   messages   sylius.api_client.secret                            sylius.api_client.secret                  
      missing   messages   sylius.api_client.no_results                        sylius.api_client.no_results              
      missing   messages   sylius.api_client.update_header                     sylius.api_client.update_header           
      missing   messages   sylius.menu_node.publishable                        sylius.menu_node.publishable              
      missing   messages   sylius.menu_node.start_date                         sylius.menu_node.start_date               
      missing   messages   sylius.menu_node.end_date                           sylius.menu_node.end_date                 
      missing   messages   sylius.promotion_coupon.per_customer_usage_limit    sylius.promotion_coupon.per_customer_...  
      missing   messages   sylius.order.no_payments                            sylius.order.no_payments                  
      missing   messages   sylius.history                                      sylius.history                            
      missing   messages   sylius.pricing.volume_based.min                     sylius.pricing.volume_based.min           
      missing   messages   sylius.pricing.volume_based.max                     sylius.pricing.volume_based.max           
      missing   messages   sylius.pricing.volume_based.price                   sylius.pricing.volume_based.price         
      missing   messages   sylius.pricing.volume_based.no_results              sylius.pricing.volume_based.no_results    
      missing   messages   sylius.pricing.volume_based.button.add              sylius.pricing.volume_based.button.add    
      missing   messages   sylius.option.values                                sylius.option.values                      
      missing   messages   sylius.email                                        sylius.email                              
      missing   messages   email.order_comment.subject                         email.order_comment.subject               
      missing   messages   email.order_comment.header                          email.order_comment.header                
      missing   messages   email.order_confirmation.subject                    email.order_confirmation.subject          
      missing   messages   user.password_reset.subject                         user.password_reset.subject               
      missing   messages   email.shipment_confirmation.subject                 email.shipment_confirmation.subject       
      missing   messages   email.customer_welcome.subject                      email.customer_welcome.subject            
      missing   messages   sylius.user.password.reset.header                   sylius.user.password.reset.header         
      missing   messages   sylius.user.password.reset.button                   sylius.user.password.reset.button         
      missing   messages   sylius.checkout.finalize.order.no_payment_charges   sylius.checkout.finalize.order.no_pay...  
      missing   messages   sylius.frontend.menu.sidebar.links                  sylius.frontend.menu.sidebar.links        
      missing   messages   sylius.form.user.remember_me                        sylius.form.user.remember_me              
 --------- ---------- --------------------------------------------------- ------------------------------------------ 

This was discovered when noticing that the email message on the administrator login was missing

I think there is an issue with having messages ending with ':' like id: Customer ID : in Yaml files. There are quite a few examples of this in the WebBundle

**Comment by pfwd** [comment]
I've created a PR for the strings ending with : https://github.com/Sylius/Sylius/pull/3431
This PR simply add quotes around those strings which fixes some of the translation messages.  
But there are still quite a few missing.

**Comment by michalmarcinkowski** [comment]
Closing as WebBundle is already removed.
