### ISSUE TITLE
Product-Attributes: Values are always text inputs in product editing form

### ISSUE THREAD

**Issue by BNEP** [Sylius/Sylius#3434]
Hello, 
generating attributes of the type choice or checkbox. Then when editing products, there are only text input fields instead of selects or checkboxes. If i write in some value in this text input fields and save the product, the next time i edit it, the correct inputs are rendered.

**Comment by BNEP** [comment]
Sorry, this bug is already documented in #3129

**Comment by pjedrzejewski** [comment]
Thanks for finding a duplicate and closing this issue, helps a lot in issues maintanance! :+1:
