### ISSUE TITLE
Cannot create Taxonomy

### ISSUE THREAD

**Issue by Sp0ng3b0b** [Sylius/Sylius#3435]
When trying to create a Taxonomy, I receive this exception:

```
An exception occurred while executing 'INSERT INTO sylius_taxon (tree_left, tree_right, tree_level, deleted_at, path, taxonomy_id, parent_id) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, 8, 11]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'tree_left' cannot be null
```

Im using latest dev-master with demodata installation. Maybe im doing something wrong, i couldnt find anything about it with google.

**Comment by herodrigues** [comment]
I tried in the demo and in my application and everything is ok.

Issue tracker should be used only for reall issues.
Please, post this answer in Stackoverflow with the tag 'sylius'

**Comment by Sp0ng3b0b** [comment]
It was an issue with apc doctrine caching. This ticket can be closed then. Next time i'll ask stackoverflow first thanks!

**Comment by goemaere** [comment]
How did you fix this?

**Comment by Sp0ng3b0b** [comment]
I just cleaned my APC Cache, maybe disabling it in dev enviroment helps too.

**Comment by goemaere** [comment]
I'm only having this problem on production with APC enabled. Clearing APC (and all other caches) does not help. Any other workaround for this?

It is probably the same issue as https://github.com/Sylius/Sylius/issues/1363
