### ISSUE TITLE
[RFC] - Opening Hours implementation | channel / shop

### ISSUE THREAD

**Issue by nakashu** [Sylius/Sylius#3438]
Hi

I need to implement opening hours for a shop and would like to know the community opinion about the presented implentation, as this is something that should probably be in the core later.
## Reson

This would be mainly used by all shop in the food industry with delivery like pizza places and other restaurants, where you deliver the food with your own stuff, and can order it for a specific hour and/or day.
## Usecases
- shop (channel) got regular opening hours, when they can deliver/ship orders, communicate or accept new orders.
- shop owner must be able to change these
- shop owner must be able to set repetition in any form, eg .like every 3rd day of week, or every 2nd week of year 2016. 24th of december every year.
- in checkout process only days and hours when shop is opened must be shown for possible delivery.
- opening hours could be shown on the web
## Implementation proposal

First thing would be the model of the table. From what I thought about this crontab like design should cover all the usecases:

| channel_id | year | month | day | week | week_day | start_time | duration | opened |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 1 | * | * | * | * | 1 | 08:00 | 240 | 1 |
| 1 | * | * | * | * | 1 | 13:00 | 240 | 1 |
| 1 | * | * | * | * | 2 | 08:00 | 480 | 1 |
| 1 | * | * | * | * | 7 | null | null | 0 |
| 1 | * | 12 | 24 | null | null | null | null | 0 |

Duration is in minutes, but can be seconds. Reason for not using time as in start_time is so it could span over midnight.

Translation of the table is: 
- opened every Monday from 0800 - 1200 | 1300 - 1700
- opened every Tuesday from 0800 - 1600
- closed every Sunday
- closed on 24.Dec every year

I am just not sure if this is the right way or if we should build an event like system for instance with the ICS format.

Opinions ?
Thanks

**Comment by adamelso** [comment]
I like the idea. :+1: Regarding the implementation, I vote in favour of the ICS format ([RFC 5455](http://tools.ietf.org/html/rfc5545)) over Crontab, given that it is more accessible and commonly used. Also it allows exporting to calendars and for one-off events like Amazon's "holiday mode", and can also be used for other features.

**Comment by nakashu** [comment]
@adamelso If we would do the ICS format, do you have any idea how to implement it.

From what I understand the format is file based, and from what I search I couldn't find any relational db variant of it. 
This is probably just my ignorance, but should the data be in DB so everything would be on one place. 
Also how would searching work?

**Comment by peteward** [comment]
This sounds like a good extension to shipping methods. We have done something slightly similar where our ShippingMethods can relate to a Calendar where you can define custom events (such as holidays when you do not deliver) and can detect weekends where delivery is slower. This means we can give a good approximation to the customer of when they will receive their products.

I think there's a lot that could be done here but I'm not sure that it's a core Sylius feature for now. It's something that would be a really good Sylius Marketplace Extension though when it gets that far ;)
