### ISSUE TITLE
[Backend] Currencies code are channel aware

### ISSUE THREAD

**Issue by rpg600** [Sylius/Sylius#3439]
Hi.
When editing the general settings we can choose the default currency, however the code list does not contains all the enabled currencies but only those belonging in the first existing channel.

In fact the `ChannelAwareCurrencyProvider` service is injected to the `CurrencyCodeChoiceType`.

I think we should use the `CurrencyProvider` service for the backend, and the `ChannelAwareCurrencyProvider` service for the frontend.

**Comment by pjedrzejewski** [comment]
Thank you for the report Reinis, this is definitely an issue we need to fix. We generally need a nice way to handle "defaults", both globally and per channel.

My current idea is that every channel will have many currencies and one default. Of course this brings some problems, cause what if default is not in the list of enabled etc. Happy to hear alternatives. :)

**Comment by rpg600** [comment]
Yeah it's a good idea, maybe we should not enable/disable currencies globally, but rather select the enabled currencies per channel with a select multiple box (so i can have USD enabled in channel A but disabled in channel B). Plus a second select box not multiple this time in order to select the default currency (this field will be required and the selected default currency will be automatically considered as enabled).

**Comment by pjedrzejewski** [comment]
@rpg600 Makes sense to me!

**Comment by axelvnk** [comment]
@pjedrzejewski since this is related to my issue #3671  . I would gladly pick this one up as well. How is the general default currency handled now?

**Comment by rpg600** [comment]
Hello @axelvnk, actually the default currency is a general setting and has the wrong provider so all currencies are not visible.
The logic is the following : we try to get the currency from the current customer, otherwise we get the one from the session and the default one if null.
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Context/CurrencyContext.php#L67

As already said, every channel must have a default currency and we must ensure that this default currency is in the list of the selected available currencies (with a custom validator maybe).

Another thing : i don't know if it's a good idea to retrieve the currency from the customer since we don't know if this currency is still available for the current channel.

**Comment by michalmarcinkowski** [comment]
The currencies management has been completely reworked, this issue is resolved already.
