### ISSUE TITLE
Backend Payment page error

### ISSUE THREAD

**Issue by psyray** [Sylius/Sylius#3440]
Hi,

I update Sylius GIT project today, and while trying to access Payment form/list from backend this error was returned
```
An exception has been thrown during the rendering of a template ("Could not convert database value "" to Doctrine Type array") in SyliusWebBundle:Backend/PaymentMethod:index.html.twig at line 24. 
```
Log trace returned this sql query just before error
```
DEBUG - SELECT s0_.name AS name0, s0_.description AS description1, s0_.gateway AS gateway2, s0_.environment AS environment3, s0_.is_enabled AS is_enabled4, s0_.fee_calculator AS fee_calculator5, s0_.fee_calculator_configuration AS fee_calculator_configuration6, s0_.created_at AS created_at7, s0_.updated_at AS updated_at8, s0_.id AS id9 FROM sylius_payment_method s0_ WHERE s0_.id IN (?) ORDER BY s0_.name DESC 
```

I investigate and I found that in database the fee_calculator & fee_calculator_configuration fields was empty.
The error comes from those empty fields
Those fields were introduced 3 months ago in this commit dff85d7adb1ddbbb7fab3b7b348fbebdf273c088
And the installer fill those fields in this commit 446bd69bc6c943ed844fd0a17bdaee0b9a178f65

A doctrine migration script was forgotten :-1: 
@Zales0123 it'up to you ;)

**Comment by psyray** [comment]
Enjoy the fix ;)
Tested and working

**Comment by pjedrzejewski** [comment]
Thank you for the report and fix Raynald!
