### ISSUE TITLE
[RFC] Reworking Adjustments to work at the InventoryUnit level

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#3441]
We have run into an issue with OrderItem-level Adjustments. They create a lot of complexity when trying to cope with the following:

* **Refunds** - This is not core Sylius yet, but when a customer returns an item for a refund, they are very likely to return less than the full quantity of the OrderItem.  As Adjustments are at the OrderItem level, if you have promotional adjustments these need to be 'reversed' only for the quantity that is being returned. While this is doable it gets complex quite quickly.
* **Financial Reporting at an InventoryUnit level**. This is a very common requirement for any enterprise system that you might want to integrate with (we have several). If you want to know how much a single sold unit is worth after adjustments you have to consider the quantity. If you add in refunds here this becomes incredibly difficult to quantify how much an item was worth.

I’ve done a review of several other Open Source commerce systems and none of them seem to deal with this particularly well – we think we can make Sylius stand out in this respect.

Our proposal is to handle Adjustments for OrderItems at the InventoryUnit level, but to keep the relationship with OrderItem in such a way that it still works without a huge BC break. We are suggesting quite a big fundamental change, but it shouldn’t break how Adjustments are used in existing reports.

We will add the following to the Adjustment entity:
* `inventoryUnitId`
* `isRefund`

To illustrate how this would look in a cut-down database table:
* There is an OrderItem with id 7, it has a quantity of 3 with a unitPrice of $50.
* It has a 20% discount promotion on this item which is applied.
* Tax is calculated and applied afterwards.

![screen shot 2015-10-15 at 17 36 44](https://cloud.githubusercontent.com/assets/7068515/10520674/58e22280-7363-11e5-8505-9f56c76790df.png)

* We record every adjustment (above shows promotion and tax) at the InventoryUnit level, but also keep the relation with the OrderItemId. This means that existing methods that just add up adjustments on OrderItem still work, such as:

```
/**
 * {@inheritdoc}
 */
public function calculateAdjustmentsTotal()
{
    $this->adjustmentsTotal = 0;

    foreach ($this->adjustments as $adjustment) {
        if (!$adjustment->isNeutral()) {
            $this->adjustmentsTotal += $adjustment->getAmount();
        }
    }

    return $this;
}
```

* It also means that listing adjustments still works, although there will be more of them.
* Order-level adjustments are unaffected (shipping).

This is a very big deal for us. We will have to make this change but I would like to make it in Sylius core rather than have Reiss differ a lot from the platform.
Also Adjustments are featured heavily in promotions and @PWalkow is reworking promotions now #3368 . He’s made good progress but this is a fundamental and underlying change that we would need to make first. It has big implications on promotions such as “BOGOF”  so we want to get community agreement first.

We are aware that Sylius doesn’t really do much with refunds currently, but this will pave the way for a very solid system around it. We might also be able to contribute some of our Returns/Refunds work in the future with this in place.

Any comments on this are very much welcome.

**Comment by gonzalovilaseca** [comment]
@peteward I totally agree with everything, well done!

**Comment by kayue** [comment]
@peteward We have something similar implemented in our Sylius.

- Refund is called "Credit Memo" in our system, we copy this from Magento, and it can be positive or negative.
- Instead of modifying inventory unit, we added `quantity_ordered`, `quantity_refunded` to our OrderItem.
- Keep in mind that we need to take care of multi-currency.

**Comment by aramalipoor** [comment]
:+1:

**Comment by peteward** [comment]
@kayue I really like the Sylius Adjustment model, I think it's great for keeping both a present and historical track of finances.

I think Adjustments sound equivalent to Credit Memo really since they can also be positive or negative. The reason that we're suggesting an `isRefund` flag is to simplify understanding and querying.  A refund adjustment won't always negative - if you're refunding an item with a promotion adjustment then you will need a positive refund adjustment to the original promotion adjustment(!) as shown in the second to last row in the above table.

Having an isRefund flag means you can find the answers to common reporting questions excluding or including refunds very easily, such as:

*How much was spent on Promotion X excluding refunds?*

```SELECT SUM(amount) FROM adjustment WHERE origin_type = 'Promotion' and origin_id=X and is_refund = 0```

*How much was spent on Promotion X net of refunds?*

```SELECT SUM(amount) FROM adjustment WHERE origin_type = 'Promotion' and origin_id=X```

There are many other use-cases where this flag becomes very handy - summing shipping refunds, item refunds, etc.


We did also consider the idea of a `quantity_refunded` and possibly a `quantity_ordered`, although I would have thought `quantity_ordered` = `quantity` - `quantity_refunded`?  I would also suggest calling it `quantity_returned` as the word *return* covers a wider scope of refund or exchange for another product.

Having said that this PR isn't going to dive into fully implementing a Returns system, but providing some foundations for it.


Do you have any concerns or ideas about multi-currency? Since currency isn't really handled at the adjustment level I don't think this really touches it, and everything still relates to currency as before.

**Comment by kayue** [comment]
@peteward If we are only discussing applying Adjustment to InventoryUnit, I have the following comments:

- Once order is confirmed, it is better to not modify any `Adjustment` that has applied to the `Order`. I would just add more new positive / negative adjustment on top of it.

Speaking of refund system in general:


- `Adjustment` only reflect money amount changes, but doesn't reflect quantity change. So you do need `CreditMemo` model to record these information.
- We have `CreditMemo` and `CreditMemoItem` model. Same idea as `Order` and `OrderItem`.
- In our `OrderItem` model quantity for "ordered", "refunded", "returned", "cancelled", because adjustment doesn't reflect quantity change. When we run reports we only run it on "ordered" quantity, so the number in report won't be constantly changing.

**Comment by peteward** [comment]
@kayue yes I thought about modifying the adjustments post-checkout originally, because I thought InventoryUnits were not created until after the order is confirmed,  but because they are created at the time of being added to cart, it seems sensible to start as you mean to continue. 

Just to clarify, we're not suggesting **separate** adjustments for OrderItem and InventoryUnit, we would only have them defined at the InventoryUnit level but also relate them to OrderItem, so you have both at the finest level of detail.  With an adjustment of $30 on an OrderItem with Quantity = 3, there would only be adjustment entries like this:

```
$10
$10
$10
```

NOT:

```
$30
$10
$10
$10
```

If we start by assigning  Adjustments by InventoryUnits at the point of creation then it means the logic for creating them is handled in one place and the adjustment is consistent throughout it's lifecycle. Otherwise it might feel like some kind of magic that transforms adjustments after checkout and is harder to follow. It also impacts how promotions will create and revert their adjustments (this is the most complicated application of adjustments and it's something we are also working on improving).


For the larger returns model I think this section is a bigger debate for another time. Your model sounds very interesting. Our model isn't perfect, so I wouldn't want to impose it on Sylius :)
