### ISSUE TITLE
[UserBundle] Improve register with email confirmation

### ISSUE THREAD

**Issue by gperdomor** [Sylius/Sylius#3444]
Hi everyone!.

I wanna know your opinion about implementing email confirmation considering this:
- On <code>customer.pre_create</code> event, the <code>user</code> must be disabled and a <code>confirmation token</code> should be generated (use the same field used in password request).
- The confirmation email must contains a link to a new <code>confirmAction</code> which use the <code>confirmation token</code> as parameter, the action validate the token and enable the user and set the <code>confirmationToken</code> to null.
- The <code>ConfirmAction</code> should redirect to login if the token is valid and dispatch <code>pre_confirm</code> and <code>post_confirm</code> events.
- As the <code>user</code> is created with <code>disabled</code> state, the <code>AutoLoginListener</code> is no longer works, so should be deleted.
- The <code>prepareResetPasswordRequest</code> method on the <code>UserController</code> must verify the status of the user for prevent the execution when the user is disabled (show the flash message <code>sylius.user.email.not_exist</code> for example)

**Comment by pjedrzejewski** [comment]
Actually, I'd like to have this toggleable. So basically being able to easily enable/disable the listeners responsible for autologin and confirmation token generation/email + disabling user. Just like FOSUserBundle is doing it, IIRC. Thoughts?

**Comment by gperdomor** [comment]
Any progress here? or defined workflow for this?

**Comment by michalmarcinkowski** [comment]
Currently we're implementing email verification. The workflow is the following:
1. Register and autologin - the user is able to login but his email is not verified
2. Send email with email confirmation link
3. Visit confirmation link (your email will be verified)

And also a possibility to resend confirmation email.
1. [Logged in user] Go to my account profile -> click "resend confirmation email" link
2. [Not logged in user] Go to resend confirmation email page -> fill in your email -> press "Resend" button (same as request password reset)

I would suggest to wait for this functionality and then we can add configurable option to disable user account at default and enable it after verification. It will only require to disable autologin listener, disable `UserRegistrationFormSubscriber` which enables user on registration form submit and enable user after the verification.

**Comment by gperdomor** [comment]
@michalmarcinkowski +1... I will wait then :D

**Comment by krafas** [comment]
@michalmarcinkowski do you have any news about this feature? At what stage it is now?

**Comment by michalmarcinkowski** [comment]
The email verification feature is already merged (see #5029), so this feature can be easily added now.

We don't plan to implement this feature soon, but if anyone from community is willing to work on it, we will be happy to help 😉
