### ISSUE TITLE
[BUG] Not all translations is being loaded

### ISSUE THREAD

**Issue by kayue** [Sylius/Sylius#3446]
### The Problem

Assume we are in CN locale now. When I try to display taxon name...

```php
// find by ID
$taxon = $this->get('sylius.repository.taxon')->findOneBy(['id' => 14]);
$taxon->getName(); // Works

// find by slug
$taxon = $this->get('sylius.repository.taxon')->findOneBy(['slug' => 'keychains']);
$taxon->getName(); // Not work! fallback to English
```

### The Cause

We have the following taxon translation table. Please note that the CN translation doesn't have slug.

```
+-----------------+-----------+-----------+--------+
| translatable_id | name      | slug      | locale |
+-----------------+-----------+-----------+--------+
|              14 | 匙        | NULL      | cn     |
|              14 | Keychains | keychains | en     |
+-----------------+-----------+-----------+--------+
```

This happens because `$taxon->translations` doesn't have all the record. 

Let's look at the query. 

When we query by `id`, it should returns 2 records. All good.

```sql
SELECT * 
FROM 
  sylius_taxon s0_ 
  LEFT JOIN sylius_taxon_translation s1_ ON s0_.id = s1_.translatable_id 
WHERE 
  (s0_.id = ?) 
```

However, when we query by `slug`, it returns only 1 record, because the CN translation doesn't have slug. This is why it failed to load CN translation.

```sql
SELECT * 
FROM 
  sylius_taxon s0_ 
  LEFT JOIN sylius_taxon_translation s1_ ON s0_.id = s1_.translatable_id 
WHERE 
  (s1_.slug = ?) 
```

/cc @pjedrzejewski

**Comment by kayue** [comment]
In some cases Doctrine will issue a separated request to get all translations. However it doesn't happen in this case.

**Comment by umpirsky** [comment]
@kayue One more interesting test case:

```php
// find by ID
$taxon = $this->get('sylius.repository.taxon')->findOneBy(['id' => 14]);
$taxon->getName(); // Works

// find by slug
$taxon = $this->get('sylius.repository.taxon')->findOneBy(['slug' => 'keychains']);
$taxon->getName(); // Not work! fallback to English

// find by slug, then by ID
$taxon = $this->get('sylius.repository.taxon')->findOneBy(['slug' => 'keychains']);
$taxon = $this->get('sylius.repository.taxon')->findOneBy(['id' => 14]);
$taxon->getName(); // Not work! fallback to English
```

**Comment by umpirsky** [comment]
One more find. For locale en:

```php
$this->getContainer()->get('sylius.repository.taxon')->findOneBy(['slug' => 'category'])->getName();
// Category
```

```php
$this->getContainer()->get('sylius.repository.taxon')->findOneBy(['slug' => 'categoria'])->getName();
// null
```

So it returns `null` even there is English translation for category Taxon if you find it by spanish slug.

**Comment by pjedrzejewski** [comment]
OK, that is very bad... I hope this is something on our side and not default Doctrine/Extensions behavior. Did you get any ideas for the possible fix?

**Comment by kayue** [comment]
@pjedrzejewski It could be Doctrine's problem, because translation does work on some more complex query. 

I personally think it is because when query is simple (`findBySlug`), Doctrine think it has the entire `$taxon->translations` already. It doesn't realize it is doing a JOIN...

**Comment by kayue** [comment]
@pjedrzejewski We probably don't have time to dig into this deeper... :(

**Comment by pjedrzejewski** [comment]
@kayue That's ok, thanks for reporting this! I will to investigate. :)

**Comment by pjedrzejewski** [comment]
Should be fixed in the latest master.
