### ISSUE TITLE
Currency Importer not working

### ISSUE THREAD

**Issue by winzou** [Sylius/Sylius#3447]
Hi,

The https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Currency/Importer/EuropeanCentralBankImporter.php is not really working, I guess nobody is actually using it.

First the option base_currency is just ignored and it considers that EURO is the base one.
Second in https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Currency/Importer/AbstractImporter.php#L52 we have `in_array($code, $managedCurrencies)` whereas `$code` is a string and `$managedCurrencies` is an array of objects. Thus we never pass the if and don't update currencies.

**Comment by pjedrzejewski** [comment]
This is for now not supported.
