### ISSUE TITLE
[Dependencies] authorizenet-php-api is abandoned

### ISSUE THREAD

**Issue by herodrigues** [Sylius/Sylius#3451]
Just a quick remind when running composer update

```bash
Package ajbdev/authorizenet-php-api is abandoned, you should avoid using it. 
Use authorizenet/authorizenet instead.
```

It should be updated in composer.json file

**Comment by michalmarcinkowski** [comment]
Sylius doesn't have this package as a dependency, it's This library comes from Payum composer.json https://github.com/Payum/Payum/blob/master/composer.json#L61. The issue is already opened there https://github.com/Payum/Payum/issues/407.
