### ISSUE TITLE
[QUESTION] Why ROLE_SYLIUS_ADMIN and ROLE_ADMINISTRATION_ACCESS?

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#3453]
I've got these roles in my user.roles field in the DB. There seems to be code meaning attached to both.

Are both required? Should there be two (one seems to imply the other - it would be weird to be an admin without administration access)?

Is this needed at all with the RBAC setup? Is it outstanding legacy?

**Comment by pjedrzejewski** [comment]
``ROLE_SYLIUS_ADMIN`` is legacy from "before-RBAC" era. Right now we use Symfony roles to restrict access to specific URLS (like API/admin), but RBAC decides who is the admin and who is not. Probably this is not included in the migration or you have not run it. Please reopen if anything is not clear. Of course all this will go to the docs to make things clear.

**Comment by michalmarcinkowski** [comment]
So we should adjust the confusing fixtures https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadUsersData.php#L36. Should I open other issue for that?

**Comment by peteward** [comment]
Yes there's quite a few references to both:

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Resources/views/Frontend/layout.html.twig
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Controller/Frontend/Account/OrderController.php
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Controller/Backend/SecurityController.php

Definitely needs a clean-up here around the uses of both.

**Comment by cdaguerre** [comment]
and here ;)
https://github.com/Sylius/Sylius/blob/master/app/config/security.yml#L35

**Comment by pjedrzejewski** [comment]
Let's use this issue. :)

**Comment by pjedrzejewski** [comment]
@cdaguerre Ouch, we should have a separate role for that to give it more flexibility, not every user with admin access should be able to impersonate. :) Good catch! :+1:

**Comment by cdaguerre** [comment]
@pjedrzejewski Actually someone already had that in mind here: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml#L669

**Comment by pjedrzejewski** [comment]
@cdaguerre Ok, I think I have a problem with remembering my own ideas. https://github.com/Sylius/Sylius/blame/master/src/Sylius/Bundle/CoreBundle/Resources/config/app/sylius.yml#L669 :D

**Comment by cdaguerre** [comment]
@pjedrzejewski :+1: Too much work, get some rest!
