### ISSUE TITLE
Taxonomies Bundle instructions are incomplete/wrong

### ISSUE THREAD

**Issue by Ingannatore** [Sylius/Sylius#3454]
After following the guide [here](http://docs.sylius.org/en/latest/bundles/SyliusTaxonomyBundle/installation.html), I run into the same problem as #304 (missing informations on the dependency to TranslationBundle).

After setting up all the dependencies, I've added the [container configuration](http://docs.sylius.org/en/latest/bundles/SyliusTaxonomyBundle/installation.html#container-configuration) to my `config.yml` and I run into the following error:

> [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
> The child node "classes" at path "sylius_taxonomy" must be configured.

To avoid any problems, I directly copied all the configurations from [here](http://docs.sylius.org/en/latest/bundles/SyliusTaxonomyBundle/summary.html#configuration-reference) and then I run into another error:

> [Symfony\Component\Config\Definition\Exception\InvalidTypeException]
> Invalid type for path "sylius_taxonomy.classes.taxonomy.form". Expected array, but got string

I fixed the last error by setting both `sylius_taxonomy.classes.taxonomy.form` and `sylius_taxonomy.classes.taxon.form` to `~`.

**Comment by michalmarcinkowski** [comment]
We are working on documentation for all components (see PRs https://github.com/Sylius/Sylius-Docs/pulls) and the bundles are next in the line, so we will update all installation notes soon.

Thanks for your feedback Matteo! :+1:

**Comment by Ingannatore** [comment]
Glad to be of any help :)

**Comment by michalmarcinkowski** [comment]
Closing this as bundles installation should work fine now.
