### ISSUE TITLE
TaxonomiesBundle - Unable to find template "::index.html.twig"

### ISSUE THREAD

**Issue by Ingannatore** [Sylius/Sylius#3455]
After following the guide [here](http://docs.sylius.org/en/latest/bundles/SyliusTaxonomyBundle/installation.html) with a couple of fixes from #3454, I've tried to navigate to the `sylius_taxonomy_index` route (`/app_dev.php/taxonomy/taxonomy/`) but I run into this error:

> Unable to find template "::index.html.twig"
> "The file "views/index.html.twig" does not exist (in: /home/matteo/Sviluppo/portolano-store/app/Resources)."

What am I missing? Some configurations?

**Comment by pjedrzejewski** [comment]
Bundles currently do not have default templates, but we are going to fix that with generic ui for all Sylius bundles. Unfortunately for now you need to define the template yourself. You can use SyliusWebBundle templates as an example, for Taxonomies they are pretty simple. :)

**Comment by Ingannatore** [comment]
Thank you :)
