### ISSUE TITLE
German translations are missing

### ISSUE THREAD

**Issue by Buri** [Sylius/Sylius#3456]
All files with german translations are empty, only with author info.

**Comment by pjedrzejewski** [comment]
Hello Jakub! We are in progress of reworking the translation synchronization process. All translations should be available in Sylius repository very soon. Also, we only sync "Approved" translation keys. If you want to help with proofreading process, drop me an e-mail to pawel@sylius.org. Closing this for now, cause we have a lot of other languages missing as well, we will effectively fix that over next few days.

**Comment by Buri** [comment]
Great, thanks for info!
