### ISSUE TITLE
[RFC] Calculators should be stateless

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#3458]
Hey folks,

Another mind-blowing issue to discuss. :) Born from my comment in #3409.

Basically, all our calculators (for shipping, prices, taxes) need to be state-less and not rely on any services, which use:

* Hostname (channels)
* User (address etc.)
* Session (language etc.)

We might want to run them when editing the Order in the backend and many other scenarios. Right now it will take currently logged in user, current channel, currency and so on, we obviously should pass these to the options of the calculator.

Issues to resolve:

* Passing context (i.e. current channel) in templates when displaying prices;
* Passing appropriate context in cart for example, so that we do not need to modify the cart resolver everytime we want to introduce something more to the pricing calculation context;
* You tell me! :)

Happy brainstorming. :)

**Comment by PWalkow** [comment]
Yes, all services should be stateless... Another example of state-full service is cartProvider which is having... cart inside.
