### ISSUE TITLE
[RbacBundle] Create several permissions at once

### ISSUE THREAD

**Issue by herodrigues** [Sylius/Sylius#3459]
I was thinking in a better way to create permissions, that is, user creates several root permissions and its nodes at once:

|-- root permission 1
|---- root_1_permission_1
|---- root_1_permission_2
|---- root_1_permission_n 

|-- root permission 2
|---- root_2_permission_1
|---- root_2_permission_2
|---- root_2_permission_n

A button "Add root permission" and then, inside each new root permission, a button "Add child permission".

What do you guys think?

**Comment by pjedrzejewski** [comment]
Hey Herinson! Definitely a good idea. I'd leave it for later though, UI should be last focus right now.

**Comment by michalmarcinkowski** [comment]
RbacBundle was removed.
