### ISSUE TITLE
Cannot overload LoadTaxonomiesData fixture

### ISSUE THREAD

**Issue by pfwd** [Sylius/Sylius#3467]
I get the following error when when overloading LoadTaxonomiesData fixture and running 
    
    php app/console sylius:install

    [Doctrine\DBAL\Exception\UniqueConstraintViolationException]                                                                                                                                                                               
      An exception occurred while executing 'INSERT INTO sylius_taxon_translation (name, slug, permalink, description, locale, translatable_id) VALUES (?, ?, ?, ?, ?, ?)' with params ["Category", "category", "category", null, "en_EN", 11]:  
      SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'en_EN-category' for key 'permalink_uidx'

This is because the Sylius taxonomies fixture is loaded before my child fixture. This is shown when running 

    php app/console doctrine:fixtures:load

    Careful, database will be purged. Do you want to continue Y/N ?y
    > purging database
    > loading [10] AppBundle\DataFixtures\ORM\LoadLocalesData
    > loading [10] AppBundle\DataFixtures\ORM\LoadPaymentMethodsData
    > loading [10] Sylius\Bundle\FixturesBundle\DataFixtures\ORM\LoadRbacData
    > loading [10] AppBundle\DataFixtures\ORM\LoadRbacData
    > loading [10] Sylius\Bundle\FixturesBundle\DataFixtures\ORM\LoadTaxonomiesData
    > loading [10] AppBundle\DataFixtures\ORM\LoadImagesData
    > loading [10] AppBundle\DataFixtures\ORM\LoadCountriesData
    > loading [10] AppBundle\DataFixtures\ORM\LoadCurrencyData
    > loading [10] AppBundle\DataFixtures\ORM\LoadGroupsData
    > loading [10] AppBundle\DataFixtures\ORM\LoadContactTopicData
    > loading [10] AppBundle\DataFixtures\ORM\LoadTaxonomiesData

This is how the overloaded fixture starts:

    namespace AppBundle\DataFixtures\ORM;

    use Doctrine\Common\Persistence\ObjectManager;
    use Sylius\Bundle\FixturesBundle\DataFixtures\ORM\LoadTaxonomiesData as BaseFixture;
    use Symfony\Component\Yaml\Parser;

    class LoadTaxonomiesData extends BaseFixture
    {

**Comment by pjedrzejewski** [comment]
Perhaps we should think about having fixtures somehow configurable via container? Define them as services, so that you can change the class? I see a lot of people struggling with overriding them. Also, I think we will need to have different sets of fixtures, like "sample-data" for demo purposes and "minimum" fixtures.

**Comment by pfwd** [comment]
:+1: That sounds good. I noticed that in the InstallerBundle InstallSampleDataCommand we are not allowing a --fixtures argument. It might be easier to make this option configurable. It would also be good to allow the --no-interaction flag to be set to false as this would help with debugging.

Lines 65 - 69 of InstallSampleDataCommand

    $commands = array(
            'doctrine:fixtures:load'       => array('--no-interaction' => true),
            'doctrine:phpcr:fixtures:load' => array('--no-interaction' => true),
            'sylius:search:index',
         );

**Comment by michalmarcinkowski** [comment]
`doctrine:fixtures:load` command takes all classes that are `.../DataFixtures/ORM/` folder of any bundle, so extending the base fixtures will not work here (as you can see). IMO possibility to 'choose' fixtures in the parameters.yml is not so bad solution (AkeneoPIM does that) and perhaps we could merge it for now and think of a better solution later.

**Comment by michalmarcinkowski** [comment]
Take a look at our new fixtures implementation!
