### ISSUE TITLE
Package ajbdev/authorizenet-php-api is abandoned

### ISSUE THREAD

**Issue by pfwd** [Sylius/Sylius#3473]
The following warning is shown when running composer install or update
  
    Package ajbdev/authorizenet-php-api is abandoned, you should avoid using it. Use authorizenet/authorizenet instead.

It looks like its an issue with the payum/payum and payum/authorize-net-aim packages

I know these packages are outside of our control but this message is not going to instill confidence to new users.  

Could we bump the package versions at all?

**Comment by stloyd** [comment]
This was already fixed in Payum & this is not bug of Sylius. Sylius just needs to update dependencies.

btw. such issue was already reported few days ago.

**Comment by pfwd** [comment]
@stloyd My bad.  I couldn't see the issue when I searched for it.  As it has already been raised I will close the issue
