### ISSUE TITLE
Shipping Methods empty?

### ISSUE THREAD

**Issue by yingtho** [Sylius/Sylius#3475]
I have set two shipping method that use flatrate (using CATEGORY_REQUIREMENT_MATCH_ANY) and checked the code in MethodsResolver->getSupportedMethods and it returns the two shipping methods. I just can't see them in the frontend at http://sylius.dev/app_dev.php/checkout/shipping and don't know whats wrong.
Can someone please help?

**Comment by pjedrzejewski** [comment]
Please post this question on StackOverflow - it is the official support channel for Sylius. Just tag your question with "sylius" and maybe someone will be able to help you!http://stackoverflow.com/questions/tagged/sylius
