### ISSUE TITLE
Problem with mysql 5.7

### ISSUE THREAD

**Issue by lewbor** [Sylius/Sylius#3478]
When testing Sylius with mysql 5.7, there is an error in Reports (sql query): `SELECT DATE(u.created_at) as date, count(u.id) as user_total FROM sylius_user u WHERE (u.created_at >= ?) AND (u.created_at <= ?) GROUP BY date(date) ORDER BY date(date) ASC`. 
Error message: `Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'sylius_test.u.created_at' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"`

**Comment by pjedrzejewski** [comment]
@lewbor have you found anything about this issue in Doctrine project tracker? Are we sure it is only affecting Sylius? Thanks for the report!

**Comment by lewbor** [comment]
It seems to me problem is in query syntax in Sylius/Bundle/UserBundle/Doctrine/ORM/UserRepository.php on line 141.
You can check it in older version of mysql: SET GLOBAL sql_mode = 'only_full_group_by';

**Comment by michalmarcinkowski** [comment]
Reports were removed.
