### ISSUE TITLE
Coupon Filters in Backend

### ISSUE THREAD

**Issue by liviucmg** [Sylius/Sylius#3482]
There should be some filters in the backend for coupons, at least for "Code". Use-case: My client as a promotion with about 20000 coupons, and wants to see if a specific coupon has been used or not. 

Would you accept a PR for this?

Thanks!

**Comment by michalmarcinkowski** [comment]
Sure! What is your idea for that?

**Comment by liviucmg** [comment]
I already wrote `CoreBundle/Form/Type/Filter/CouponFilterType` and `WebBundle/Resources/views/Backend/Coupon/filterForm.html.twig` and changed `WebBundle/Resources/views/Backend/Coupon/index.html.twig` to include the filter form. Basically now I have the **code** filter working, but it's case-sensitive. To make it case-insensitive. I will probably have to write a custom CouponRepository with a createFilterPaginator method and a custom $queryBuilder.

Please tell me if I am on the right track or totally off. :)

**Comment by michalmarcinkowski** [comment]
Please open a WIP pull requrest, so we can give you more detailed feedback :wink:

**Comment by michalmarcinkowski** [comment]
Implemented already ;)
