### ISSUE TITLE
 [SyliusResourceBundle] - Form/DefaultFormFactory.php

### ISSUE THREAD

**Issue by nicovak** [Sylius/Sylius#3486]
Hi, I just find something that can be improved in the ResourceBundle.

The `EntityManager` should be `ObjectManager` wich allows to easily switch ORM / ODM

    public function create($resource, EntityManager $entityManager)

In this case, We have an error with an ODM configuration. The instace passed will be: `Doctrine\ODM\MongoDB\DocumentManager`

    use Doctrine\ORM\EntityManager;
    use Doctrine\ORM\Mapping\ClassMetadataInfo;

You should pass one more argument to the consctructor to handle this.

**Comment by pjedrzejewski** [comment]
Will be refactored in #2255. Still it supports only generation for ORM, not for ODM. We will see if it is possible to add it easily.
