### ISSUE TITLE
Pricing configuration fields are not shown when updating product

### ISSUE THREAD

**Issue by pfwd** [Sylius/Sylius#3487]
The pricing rules cannot be selected when updating a product

Steps to reproduce
1) From the admin section edit a product
2) Change the 'Pricing' rule from standard to any other option e.g. Volume Based or Customer Zone
3) Notice that the form doesn't update and the new fields are not displayed

If you save the form with a different pricing rule and then go back to edit the product the new fields are displayed.

This could be as simple as a Javascript issue not showing the correct fields when the option changes.

EDIT:
Using Safari on a Mac with JS turned on. No errors in console

**Comment by pjedrzejewski** [comment]
This is being worked on for the new admin. Closing this as it is related to the old ui.
