### ISSUE TITLE
[CRITICAL][BUG][TaxonomyBundle] Deletion inconsistency

### ISSUE THREAD

**Issue by gperdomor** [Sylius/Sylius#3514]
Hi!...

When a <code>taxonomy</code> is deleted, is deleted from <code>sylius_taxonomy</code> table, but his taxons still exist in <code>sylius_taxon</code> table because <code>taxon</code> is a <code>softdeleteable</code> entity, and the <code>taxons translation</code> still exist too.

IMO, we should consider two scenarios:
- Option A: <code>taxonomy</code> and <code>taxon</code> should be <code>softdeleteable</code> entities.
- Option B: <code>taxon</code> entity should not be <code>softdeleteable</code>, and <code>taxons</code> and <code>taxons translations</code> will be deleted when a <code>taxonomy</code> is deleted.

What do you think?

In addition to the previous problem, there is another more critical:
When you delete a <code>taxonomy</code> not only his children <code>taxons</code> are deleted, taxons with other parent are deleted too.

To replicate this, load the default sylius fixtures and delete the <code>Category</code> taxonomy, then try to view the details of <code>Brand</code> taxonomy and you will get the following error: <code>Error: Call to a member function getChildren() on null</code>.

If you explore the <code>sylius_taxon</code> table, you will see a lot of deleted taxons, even the taxons of <code>Brand</code> taxonomy.

**Comment by pjedrzejewski** [comment]
Any reason why taxons are softdeleteable, does not make sense to me and I can't recall a moment when we made them this way...

**Comment by aramalipoor** [comment]
+1 To have no softdeleteable on taxon! (Or no where else too :D)

**Comment by gperdomor** [comment]
@pjedrzejewski @aramalipoor i vote for have no softdeleteable taxons, but big problem here is the deletion of taxon which aren't childrens of the main taxonomy/taxon which i wanna delete.

**Comment by aramalipoor** [comment]
Maybe these links help you on this:

http://stackoverflow.com/questions/16575114/doctrine-2-entities-relations-remove
http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/working-with-associations.html

It can be handled on Doctrine ORM level using event listeners or lifecycle events, or on resource level using ResourceBundle events. Doctrine level is obviously the better one to go.

**Comment by aramalipoor** [comment]
BTW I was always wondering why we don't merge Taxon and Taxonomy entities into one entity and a lot of our headaches goes away by nature!

**Comment by michalmarcinkowski** [comment]
Will be fixed in #3773.

**Comment by aramalipoor** [comment]
@gperdomor hope it's fixed now and you can close this issue.

**Comment by pjedrzejewski** [comment]
I think it is fixed, if still valid in your custom app, please reopen.
