### ISSUE TITLE
[ORDER] Adding new item with quantity lower then 0 results in 500 code.

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#3522]
As I wrote in a title adding new order item with quantity lower then 0 results with Internal Server error, but should return Bad Request. It is because we are checking quantity value in a [OrderItem object](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Order/Model/OrderItem.php#L96). We should provide some validation in a form for that I guess.

**Comment by michalmarcinkowski** [comment]
I guess you're talking about the API? Should be fixed on master, could you validate that?

**Comment by michalmarcinkowski** [comment]
Right now we can't set lower than 0 quantity.
