### ISSUE TITLE
[Core] Taxon should not be softdeleteable

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#3523]
The problem solved by #1146 was about deleted products. When removing a taxon, we should simply remove it from all products (deleted and not deleted). Delete it completely and forget. :) Otherwise we will have issues like #3514.

Anyone willing to give us a hand with this little bug? :)

**Comment by michalmarcinkowski** [comment]
Will be fixed by #3761.

**Comment by aramalipoor** [comment]
Can be closed.

**Comment by michalmarcinkowski** [comment]
Thanks @aramalipoor! :+1:
