### ISSUE TITLE
Sylius Web Bundle Installation Issue 

### ISSUE THREAD

**Issue by Siddharth22** [Sylius/Sylius#3526]
I have successfully installed SyliusCartBundle and "add-to-cart" functionality is working fine on product page. So for next process checkout page I need  SyliusWebBundle as mentioned in https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Cart/summary.html.twig

So I installed SyliusWebBundle through composer  and  When I configured SyliusWebBundle in Appkernel.php then I got this error -

    ServiceNotFoundException in CheckExceptionOnInvalidReferenceBehaviorPass.php line 58:
    The service "sylius.menu_builder.frontend" has a dependency on a non-existent service      "sylius.authorization_checker".

I am installing this bundles in my existing project for online Buy Option.

Or

Is it not possible to install SyliusWebBundle and other's SyliusBundle in Symfony 2+ Existing project ?

And Please also help me which sylius bundles required for creating a eCommerce system in existing project. 
  
Any Help Will be highly Appreciated !

Thanks  !

**Comment by michalmarcinkowski** [comment]
You can use every Sylius bundle independently, but unfortunately the frontend (`SyliusWebBundle`) you can't be used without `SyliusCoreBundle`. We plan to provide default UI templates for Bundles, but right now you can only copy and modify the templates or inspire by them and write your own.
