### ISSUE TITLE
[FixturesBundle] Use the available locales for Faker

### ISSUE THREAD

**Issue by skigun** [Sylius/Sylius#3530]
It seems that only the default local and `es_ES ` local was used for the fakers generator.
Sylius fixtures use a generator "faker" for each local.
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/FixturesBundle/DataFixtures/DataFixture.php#L76

So when you load fixtures from another local, if the corespondant faker doesn't exit, it will throw an error.

**Comment by pjedrzejewski** [comment]
:+1:
