### ISSUE TITLE
Validation slideshow block parent object invalid

### ISSUE THREAD

**Issue by axelvnk** [Sylius/Sylius#3532]
When submitting the create new slideshow block form, I get an error saying 'The value is not valid'. And the parent input field renders hidden. 

Any ideas as to why?

<img width="1201" alt="screen shot 2015-11-05 at 15 14 59" src="https://cloud.githubusercontent.com/assets/6803540/10970601/0d9082ae-83d0-11e5-9811-bfc41099d060.png">
<img width="1205" alt="screen shot 2015-11-05 at 15 15 11" src="https://cloud.githubusercontent.com/assets/6803540/10970600/0d7ab3fc-83d0-11e5-905c-6e47da366c86.png">

**Comment by michalmarcinkowski** [comment]
Slideshow block was removed.
