### ISSUE TITLE
Resources are not supported in serialized data

### ISSUE THREAD

**Issue by gperdomor** [Sylius/Sylius#3533]
Hi!.

I have a list of taxonomies which are loaded using a custom method, in the backend works fine. I have a select in the frontend which i want to load using the same custom repository method but i got this when pagination is disabled:
<code>Resources are not supported in serialized data. Path: Monolog\Handler\StreamHandler -> Symfony\Bridge\Monolog\Logger -> Symfony\Bridge\Doctrine\Logger\DbalLogger -> Doctrine\DBAL\Logging\LoggerChain -> Doctrine\DBAL\Configuration -> Doctrine\DBAL\Connection -> Doctrine\ORM\EntityManager -> Doctrine\ORM\Query -> Doctrine\ORM\Tools\Pagination\Paginator -> Pagerfanta\Adapter\DoctrineORMAdapter -> Pagerfanta\Pagerfanta</code>

Route example in backend:
<code><pre>taxonomy_index:
    path: /taxonomies
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxonomy:indexAction
        _sylius:
            template: MyBundle:Backend/Taxonomy:index.html.twig
            paginate: 25
            repository:
                method: createFilterPaginator
                arguments: [$criteria, $sorting, $deleted]
            sortable: true
            sorting:
                name: asc</pre></code>

Route in frontend:
<code><pre>api_taxonomy_index:
    path: /api/taxonomies
    methods: [GET]
    defaults:
        _controller: sylius.controller.taxonomy:indexAction
        _sylius:
            paginate: false
            permission: false
            repository:
                method: createFilterPaginator
                arguments: [$criteria, null, false, 1, 'expr:service("channel.context.channel").getChannel()']
            sorting:
                name: asc</pre></code>

It's a bug or i'm doing something wrong?

**Comment by pjedrzejewski** [comment]
Interesting, not sure what can be cause here. Should generally work fine, it looks like something with Pagerfanta and Monolog.

**Comment by gperdomor** [comment]
@pjedrzejewski Other thing, if you configure the api route, to use serialization groups, the result is a JSON of JSON, instead an Array of JSON,  this break mi UI.

As workaround you can using <code>$quryBuilder->getQuery()->getArrayResult</code> in the repository.

**Comment by tonicospinelli** [comment]
@gperdomor @pjedrzejewski I get the similar bug, I'm using ODM MongoDB and probably it happens when paginate is disabled because the `findAll` method is called from repository and it returns a Cursor object instead array.

I solve it in my project detecting if resource is instance of `CursorInterface` and call `toArray()` method.

I'm using MongoODM and get similar error. From current version `0.17` I fix it with this changes.
```php
// src/AppBundle/Controller/ResourcesCollectionProvider.php

namespace AppBundle\Controller;

use Doctrine\MongoDB\CursorInterface;
use Sylius\Bundle\ResourceBundle\Controller\RequestConfiguration;
use Sylius\Bundle\ResourceBundle\Controller\ResourcesCollectionProvider as BaseResourcesCollectionProvider;
use Sylius\Component\Resource\Repository\RepositoryInterface;

class ResourcesCollectionProvider extends BaseResourcesCollectionProvider
{
    /**
     * {@inheritdoc}
     */
    public function get(RequestConfiguration $requestConfiguration, RepositoryInterface $repository)
    {
        $resources parent::get($requestConfiguration, $repository);
        if ($resources instanceof CursorInterface) {
            $resources = $resources->toArray();
        }
        return $resources;
    }
}
```

```yaml
app/config/services.yml
parameters:
        sylius.resource_controller.resources_collection_provider.class: AppBundle\Controller\ResourcesCollectionProvider
```

**Comment by tonicospinelli** [comment]
I will send a fix ASAP :smile:
