### ISSUE TITLE
[FlowBundle] Step history lost in some cases

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius#3538]
We started to get some issues with our checkout flow, suddenly users are seeing 404 page in the middle of checkout process. This happens in ~1% of cases.

In order to debug this problem, we override `Coordinator.forward()` method:

```php
try {
    $this->context->rewindHistory();
} catch (NotFoundHttpException $e) {
    $referer = null;
    if (null !== $this->context->getRequest()) {
        $referer = $this->context->getRequest()->headers->get('referer');
    }

    $this->logger->warning(sprintf(
        '%s Referer: %s. Step history: %s.',
        $e->getMessage(),
        null === $referer ? 'N/A' : $referer,
        serialize($this->context->getStepHistory()
    )));
   // ...
}
```

Here are some logs we found:

```
[2015-11-04 21:49:19] flow.WARNING: Step "addressing" not found in step history. Referer: /checkout/addressing. Step history: a:0:{}. [] []
[2015-11-04 21:59:56] flow.WARNING: Step "delivery_and_payment" not found in step history. Referer: /checkout/delivery_and_payment. Step history: a:0:{}. [] []
[2015-11-05 00:49:45] flow.WARNING: Step "delivery_and_payment" not found in step history. Referer: /checkout/delivery_and_payment. Step history: a:0:{}. [] []
[2015-11-05 00:49:54] flow.WARNING: Step "delivery_and_payment" not found in step history. Referer: /checkout/delivery_and_payment. Step history: a:0:{}. [] []
[2015-11-05 00:50:00] flow.WARNING: Step "delivery_and_payment" not found in step history. Referer: /checkout/delivery_and_payment. Step history: a:0:{}. [] []
[2015-11-05 00:50:05] flow.WARNING: Step "delivery_and_payment" not found in step history. Referer: /checkout/delivery_and_payment. Step history: a:0:{}. [] []
[2015-11-05 01:37:53] flow.WARNING: Step "addressing" not found in step history. Referer: /checkout/addressing. Step history: a:0:{}. [] []
[2015-11-05 03:08:55] flow.WARNING: Step "addressing" not found in step history. Referer: N/A. Step history: a:0:{}. [] []
```

@pjedrzejewski Ever had issues like this? May it be session related issue?

**Comment by pjedrzejewski** [comment]
Something new to me, but can be session related issue. I was thinking about saving that on the Order itself, not in the session. (as an alternative storage, sesssion would be still supported)

Basically, being able to put Flow on top of StateMachine of some object. (and making checkout steps a state flow for Order, with state machine bundle) Thoughts?

No idea what can cause this right now, is the session still there? Cause it looks like someone clicks Next >, but in the meantime they loose the currently used session.

**Comment by umpirsky** [comment]
Exactly.

We tried to overcome this issue by implementing custom validator, and checking if address is there etc.

Do you think saving checkout state in database in separate entity that is related with order? That may be interesting, I was having similar ideas. Not sure if entire session is gone (I hope not), that would be a really serious issue. :)

**Comment by pjedrzejewski** [comment]
Actually, I would save it on order, as a separate ``checkoutState``, or ``checkoutStep`` field. That holds the current step. So we would need to change the logic, instead of checking if step is in history, we would check if it is in possible transitions of state machine or something like that. I kinda did that (without state machine) on API CheckoutController. (which is temporary solution)

**Comment by umpirsky** [comment]
I must disagree here. Checkout state simply does not naturally belongs to order model. It would be better to have this two things decoupled somehow. Order should not know about checkout process at all IMO.

**Comment by pjedrzejewski** [comment]
Yeah, I agree it feels a bit dirty. We could consider introducing a Checkout model, which holds all information relevant for user's checkout and a relation to order. This way we have a clear separation and could actually do some extra stuff with checkout - hold more info for tracking etc, which does not needs to live on the order. Thoughts? (This does not sounds like a small change :D)

**Comment by umpirsky** [comment]
That sounds better in deed. It can be simple. I guess new model and custom `Sylius\Bundle\FlowBundle\Storage\StorageInterface` implementation can do the job.

**Comment by kayue** [comment]
@umpirsky FYI our session is not completely gone, because the user is still logged in and the cart is still there. Just the steps are gone...

**Comment by umpirsky** [comment]
Well, that makes this bug even more mystical. I'm curious if @pjedrzejewski's approach would overcome this issue.

**Comment by kayue** [comment]
@umpirsky I am satisfy with our custom validator solution - valid order content (eg: address) instead of checking step history :)

It is more API friendly too if we can remove session!

**Comment by umpirsky** [comment]
Yes, would be cool if we can offer alternative for session storage.

**Comment by michalmarcinkowski** [comment]
FlowBundle is already removed #6005.
