### ISSUE TITLE
Problem on creating a search controller

### ISSUE THREAD

**Issue by PurpleBabar** [Sylius/Sylius#3543]
Hi guys, 

i'm having a hard time using the search bundle, i would like to override the template of result but cant seem to make it work... i tried creating a search controller myself but all i get is : "Catchable Fatal Error: Argument 1 passed to Sylius\Bundle\ResourceBundle\Controller\ResourceController::__construct() must be an instance of Sylius\Bundle\ResourceBundle\Controller\Configuration, none given...".

This i driving me crazy... anyone has an advice ? or a best practice to follow ? 

Thanks

**Comment by pjedrzejewski** [comment]
Sorry for lack of any answer. If still relevant, please post this question on StackOverflow - it is the official support channel for Sylius. Just tag your question with "sylius" and maybe someone will be able to help you! http://stackoverflow.com/questions/tagged/sylius

That being said, SearchBundle is not usable standalone. Are you using full-stack Sylius?

**Comment by PurpleBabar** [comment]
Hi I'm using full stack Sylius, i finally changed method and put my template in app/Resources/[...], and it worked. :) 

Don't apologize for the lack of answer, the framework is really great and i love working with it ;)

Thanks for the advice, i'll try posting on stackoverflow next time.

Have a great day, and happy new year :)

**Comment by pjedrzejewski** [comment]
@PurpleBabar Thank you for feedback and kind words, Happy New Year! :fireworks:
