### ISSUE TITLE
Vagrant installs incompatible (old) version of PHP

### ISSUE THREAD

**Issue by mhujer** [Sylius/Sylius#3544]
It installs PHP 5.4.45, but the minimal version for Sylius is 5.5.9, therefore it is not possible to install Sylius in Vagrant.

**Comment by Ma27** [comment]
I guess that's because we fetch a wrong PPA.
I may have some time to have a proper look a that tonight and then I'll open a PR for that

**Comment by pjedrzejewski** [comment]
@Ma27 That would be awesome, thanks!
