### ISSUE TITLE
'Configure Topics' Heading needs to be in lower case

### ISSUE THREAD

**Issue by pfwd** [Sylius/Sylius#3545]
Only a small issue: 
The 'T' in 'Topics' should be in lower case like all other headings in the admin area. 
Take a look at the image for better explanation
<img width="194" alt="screen shot 2015-11-07 at 11 28 48" src="https://cloud.githubusercontent.com/assets/126350/11014985/a78d069c-8543-11e5-8e45-99cb702adc2c.png">

**Comment by michalmarcinkowski** [comment]
The support system is already reworked and this will be fixed in the comming PR https://github.com/Sylius/Sylius/pull/3164/files#diff-b5efaa54923b5d44ed3b96b3f08273f9L96

**Comment by pfwd** [comment]
OK @michalmarcinkowski I will close this once the PR has been merged.  Thanks for letting me know
