### ISSUE TITLE
Creating a new product shows broken translation

### ISSUE THREAD

**Issue by pfwd** [Sylius/Sylius#3546]
From the Admin screen click on new product. Notice this text 'sylius.form.product.translations'
<img width="618" alt="screen shot 2015-11-07 at 11 41 23" src="https://cloud.githubusercontent.com/assets/126350/11015000/9e3d4948-8544-11e5-94bc-d3197cb70036.png">

**Comment by pjedrzejewski** [comment]
Thanks for reporting! There is plenty of such small bugs in the UI, but here I'd not bother too much because we are going to change the way of managing translations. These tabs will be gone. :)

**Comment by pfwd** [comment]
@pjedrzejewski OK thanks.  I will close when its fixed. Many thanks

**Comment by michalmarcinkowski** [comment]
No longer an issue.
