### ISSUE TITLE
Deleting a tax category linked to a product throws sql error

### ISSUE THREAD

**Issue by pfwd** [Sylius/Sylius#3547]
1) Make sure you have a product linked to the 'Taxable goods' tax category
2) From the Admin screen click on 'Taxation Categories' 
3) Click on the delete button for 'Taxable goods'
4) On the popup screen click on delete to confirm
Notice this error:

    An exception occurred while executing 'DELETE FROM sylius_tax_category WHERE id = ?' with params [4]:

    SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`sylius_dev`.`sylius_product`, CONSTRAINT `FK_677B9B749DF894ED` FOREIGN KEY (`tax_category_id`) REFERENCES `sylius_tax_category` (`id`))

I suggest we add a check for products linked to tax categories and prevent/warn the user that this action cannot be performed until the links have been removed.

**Comment by pjedrzejewski** [comment]
Fixed in #3561. Thanks for reporting Peter.
