### ISSUE TITLE
[RFC] Customers/Users Admin Redesign

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#3549]
Hi,

We're reworking the user admin for our project and I realised it's a bit broken and lacking in features anyway. The 2 main issues are:
- You can't update a Customer's details without making them a User (since a password is required).
- There's no ability to manage customer addresses

My team has come up with the following wireframe to layout the admin page that gives management over the address book, a distinguishing of 'type' and the ability to save customer and user independently:

http://e190ok.axshare.com/

Whilst a lot of this is very Reiss-specific, would people be interested in a version following this design for the core product so we 'fix' the functionality?

We would keep the account confirmation stuff for Sylius (we're not using it) and removing anything specific to Reiss.

If you're interested I'll get my team to build another wireframe that shows exactly what we will produce before we start anything.

**Comment by pjedrzejewski** [comment]
First point has been fixed in #4037, managing addresses will come in new admin.
