### ISSUE TITLE
[RFC] improve vagrant environment

### ISSUE THREAD

**Issue by Ma27** [Sylius/Sylius#3557]
during the work on #3544 I detected the following issues:

- a precise64 is very old. I'd recommend a trusty64
- some of the puppet modules are very old and should be updated (example42/apache has already a 3.x release)
- the codestyle can be improved (use __always__ single quotes, align the arrows properly)
- every VM should have a name an auto-generated name
- the "database" resource is deprecated
- the apache dotconf process fails
- the php.ini modification process fails
- the elastica install process fails
- the documentary of the README.md in the vagrant directory can be improved:
    - instead of modifiing the etc/hosts file, the hostmanager plugin should be used
- we could create another shell provisioner that runs the composer installation, so sylius is ready to use after "vagrant up" has finished

I guess we should discuss which points are useful and which not before starting the work on it.

/cc @pjedrzejewski

**Comment by norzechowicz** [comment]
Guys, are u open for replacing puppet with ansible? I think it could work on that

**Comment by Ma27** [comment]
sry, I'm lacking time to do this. If noone else would like to do this, I'm
fine with that.

2016-04-25 10:50 GMT+02:00 Norbert Orzechowicz <notifications@github.com>:

**Comment by pamil** [comment]
Should be improved by #6418.
