### ISSUE TITLE
error : __tostring() must return a string value

### ISSUE THREAD

**Issue by tuxado** [Sylius/Sylius#3562]
Hi,

I have this error on the choice type it appear when the choice entity name it will be translated for more then one locale when i forfetch the entities name of the object choice thé entity with a multi translatés name return null name value for current local  but thé other with single local name return right value  ...
Can have some suggestions to resoleve this issues because i try all  solution en this forum ans nothing work

**Comment by pjedrzejewski** [comment]
Hi @tuxado, you need to a bit more specific, are you using full-stack Sylius or just some bundles? Is it your custom entity or something coming from Sylius?

**Comment by tuxado** [comment]
hi @pjedrzejewski tkx for your quick replay 

the probleme probably come from the sylius beacuase also the taxon entity return the same error when i provide a multi translation for the field 'name' i create a new class to test and understand if only the taxon class make this error but also the new class that i create based on the taxon hirarchie return the same errors ::
...
            *****
		$categories = $repository->getCategoriesAsList($options['category'], $options['root']);

			if (null !== $options['filter']) {
                $categories = array_filter($categories, $options['filter']);
            }
          //function call (string) $value that is setup at null from the AbstractTranslatable class
            return new ObjectChoiceList($categories, null, array(), null , 'id', null);
			***
	...
the error come from this function of the AbstractTranslatable
...		
	public function translate($locale = null)
    {

		***
		// if the entity name have only the default translation like en_US it return $this->currentTranslation
		if ($this->currentTranslation && $locale === $this->currentTranslation->getLocale()) {
            return $this->currentTranslation;
        }
        if (!$translation = $this->translations->get($locale)) {
            if (null === $this->fallbackLocale) {
                throw new \RuntimeException('No fallback locale has been set.');
            }
			
			// if the entity name is created with translations for en_US and fr_FR this function it create new categoryTranslation from the 
			// Sylius\Component\Category\Model\CategoryTranslation class and all variable of this class are null
			// and when ObjectChoiceList call _tostring function it return the exception 
			
            if (!$fallbackTranslation = $this->translations->get($this->getFallbackLocale())) {
                $className = $this->getTranslationClass();
                $translation = new $className();
                $translation->setLocale($locale);
                $this->addTranslation($translation);
            } else {
                $translation = clone $fallbackTranslation;
            }
        }
        $this->currentTranslation = $translation;
        return $translation;
    }

....


the translation function return a current translation if the entity have only the default translation provided, and it create a new  $translation = new $className() when i provide a multi translation for the entity at the creation form but the $translation have all fields setted on null on the ObjectChoiceList and when the ObjectChoiceList call _tostring  it return the error because we can not cast a null value to string ... note that the translations names are perfecly setted on the database with perfect rellation 

id =1 | translation_id = 1 | name =category 1 |  local = en_US
id =2  | translation_id = 2 |   name =category 2 |  local = en_US
id =3   | translation_id = 2 | name =categorie 2 |  local = fr_FR

default local are setted to en_US at the database and at the yml parameters

when i delete the id = 3 the error desapear and all work fine beacause  the translation use the currenttranslation to provade the taxonTranslation class and not create a new value for the translation_id = 2 on  $translation = new $className(); but when i edit the translation_id=2 and i provide fr_FR the website crach again and return the error 

it seem that the  $translation = new $className(); create the translation class after the data come from the database where it give a null value for all fields

hope i has been clear en my explication

**Comment by NeverResponse** [comment]
/cc @michalmarcinkowski 

Cannot reproduce.
Seems it got fixed somewhere along the way.
