### ISSUE TITLE
Composer install fails on memory limit of 1Gb

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#3565]
I'm trying to install Sylius on my vagrant box. I set PHP to use 1024M as memory limit, but that ain't enough apparently. Ofcourse I can raise it, but I think that ain't suitable for everyone.

Not sure how it can be fixed though. Output of composer run can be found in this gist: https://gist.github.com/stefandoorn/55b1611e6c4fa9111ef5. Yes, normally I won't run it as root but it was easier on the VM to test quickly :)

PHP version = 5.6.15
Composer version = 2a8a9a4592674acec8e57de13f36357fb89ec746

**Comment by stefandoorn** [comment]
When I got the memory limit to 1.5Gb I get this:

````
[1143.7MB/41.97s] Your requirements could not be resolved to an installable set of packages.
[1143.7MB/41.97s]
  Problem 1
    - Installation request for sylius/sylius 0.16.*@dev -> satisfiable by sylius/sylius[0.16.x-dev].
    - sylius/sylius 0.16.x-dev requires ext-gd * -> the requested PHP extension gd is missing from your system.
  Problem 2
    - behat/mink-extension v2.0.0 requires behat/behat ~3.0,>=3.0.5 -> satisfiable by behat/behat[v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9].
    - behat/mink-extension v2.0.1 requires behat/behat ~3.0,>=3.0.5 -> satisfiable by behat/behat[v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9].
    - behat/mink-extension v2.1.0 requires behat/behat ~3.0,>=3.0.5 -> satisfiable by behat/behat[v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9].
    - behat/behat v3.0.9 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - behat/behat v3.0.8 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - behat/behat v3.0.7 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - behat/behat v3.0.6 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - behat/behat v3.0.5 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - behat/behat v3.0.15 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - behat/behat v3.0.14 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - behat/behat v3.0.13 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - behat/behat v3.0.12 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - behat/behat v3.0.11 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - behat/behat v3.0.10 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - Installation request for behat/mink-extension ~2.0 -> satisfiable by behat/mink-extension[v2.0.0, v2.0.1, v2.1.0].

[305.5MB/43.67s] Memory usage: 305.49MB (peak: 1143.93MB), time: 43.67s
`````

Perfect, so then I install the missing extensions and try again. Then it continues and starts installing things:

[1147.1MB/54.01s] Analyzed 8412 packages to resolve dependencies
[1147.1MB/54.01s] Analyzed 531285 rules to resolve dependencies

But as you can see, it needs nearly 1.2Gb memory in this situation.

**Comment by stloyd** [comment]
This is not issue of the Sylius. Problem is in Composer & PHP memory management, try to disable some extensions in CLI like XDebug etc.

**Comment by stefandoorn** [comment]
True, but one could reason that the amount of dependencies is so high that it takes so much memory. I got it fixed, but we can assume more people are going to run in this problem. I hardly have extensions installed actually (no xdebug etc). Mainly want to share it as a discussion, maybe there is a way to improve things so less people run into installation problems. The easier it is, the better in the end :)

**Comment by pjedrzejewski** [comment]
I believe we could possibly move some dependencies to "suggest" and make certain features optional, that would not be much though. I don't want to change project dependencies because of the performance problem with the package manager. I think best we could do is to try optimize our awesome Composer even more. It is already much better than it was not so long time ago. :)

Also, just to clarify: installing Sylius Standard or Sylius from composer.lock? The latter should be much faster and lighter on memory.

**Comment by stefandoorn** [comment]
Makes sense. I installed a fresh Sylius Standard. Installing from composer.lock goes way better indeed.  

Maybe it's also a bit too early indeed to optimize this, but e.g. people not wanting to use elasticsearch also don't need these packages (suggest). But the big memory usage seems around the PHPCR packages. If I had all the time of the world I would definitely checked Composer to see for improvements, but not right now :)

**Comment by mojzis** [comment]
there is a [very long discussion](https://github.com/composer/composer/issues/1898) in composer issue queue, [one suggestion](https://github.com/composer/composer/issues/1898#issuecomment-43555661) being to fix the versions of referenced projects, because composer is getting busy downloading and parsing the ever bigger history of projects. that could be a relatively painless thing to do :)

**Comment by pjedrzejewski** [comment]
@mojzis @stefandoorn Great suggestions, we should definitely do this. :)

**Comment by jeroendesloovere** [comment]
Reducing the memory limit would be great!
Since that's a problem I have run into multiple times when trying to install Sylius.

**Comment by Lufolas** [comment]
You can use "php -dmemory_limit=2G" while waiting for the project to have a less memory cost.

**Comment by pamil** [comment]
Anyway, you only need to run `composer update` during development, `composer install` on production server takes much less memory. Using PHP 7 may help as well (if you're deploying on PHP 5, fake it using `platform` configuration option in `composer.json`).
