### ISSUE TITLE
Customer can block stock in his own order

### ISSUE THREAD

**Issue by goemaere** [Sylius/Sylius#3573]
Let's say we have a ProductVariant with 1 OnHand/in stock, and no backordering available.

Given following workflow:
- Customer puts ProductVariant in Cart
- Starts checkout
- Chooses to pay on an external payment provider site
- Finalizes Order >> ProductVariant OnHold
- Is redirected to the external payment provider site
- Cancels/fails the payment
- Is redirected back to Sylius payment screen
- Chooses other (or same) payment method
- Tries to finalize again >> Error: ProductVariant is out of stock.

It's still the same Order, the error should not occur.

This is a pretty serious bug for webshops with low stock, it can lose you customers!
Bug is similar to https://github.com/Sylius/Sylius/issues/1434 I guess

**Comment by ibasaw** [comment]
news ? i got variant with on_hold value and block the command even if i got still 1 on_hand

Where, what can release the on_hold varient? I try all sylius command cli, and got always my on_hold with vlaues...

**Comment by pjedrzejewski** [comment]
Should be fixed now.
