### ISSUE TITLE
[RFC] Adding an image to promotions

### ISSUE THREAD

**Issue by brunoroux** [Sylius/Sylius#3579]
So the feature is pretty much what's said in the title. I just want your opinion on this.

To me, an image, especially when it comes to promotions can make for a whole bunch of text (when promotion is on a product or a taxonomy) and is easier on the eyes.

So the point of this would be to allow to add an image on a promotion and then display this image on the product page or on the taxonomy page.

What do you think ?

**Comment by pjedrzejewski** [comment]
Hmmm, there is currently no way to associate a promotion to a specific product or taxonomy. You can do it via rules, but no easy way to get that info on product/category page for example. How do you imagine using this image? I could see use-case for displaying something special in cart/order summary or somewhere else.

Also, we should standardize way of handling images in Sylius (see #2975 - possible solution) before we eventually do this.

**Comment by tristanbes** [comment]
The use case is to display for example a Ribbon on top on the product image(s), to visually inform that the product has a special reduction

**Comment by kayue** [comment]
Even though I needed the same feature, I don't think this should be in core. 

First as @pjedrzejewski said promotion doesn't tie with product, instead it actually ties with Order / Order Item. Second, finding valid promotions can be a slow process, depends on how many promotion you are running at the same time and how complex the rules is.
