### ISSUE TITLE
[FlowBundle] Error in readme

### ISSUE THREAD

**Issue by tristanbes** [Sylius/Sylius#3587]
Hey,

In the [readme](https://github.com/Sylius/SyliusFlowBundle/blob/master/README.md) of the repository there are multiple example given with `$context->complete();` 

Yet, there is no method `complete` in the `ProcessContextInterface` it should be `$this->complete();` if I make no mistake.

**Comment by pjedrzejewski** [comment]
Fix in #3588, thanks for reporting!
