### ISSUE TITLE
Trying to overwrite the product wont recognize original mapping 

### ISSUE THREAD

**Issue by caramba1337** [Sylius/Sylius#3593]
Hi,

I try to overwrite the product model as described in the documentation.

Entity
    <?php

    namespace Vimeda\Bundle\ProductBundle\Entity;

    use Sylius\Component\Product\Model\Product as BaseProduct;

    class Product extends BaseProduct
    {
        /**
         * @var string
         */
        protected $type;

        public function __construct()
        {
            parent::__construct();
        }

        /**
         * {@inheritdoc}
         */
        public function getType()
        {
            return $this->type;
        }

        public function setType($type)
        {
            $this->type = $type;
        }

    }

Product.orm.xml
<?xml version="1.0" encoding="UTF-8"?>
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping
                                      http://doctrine-project.org/schemas/orm/doctrine-mapping.xsd">

    <entity name="Foo\Bundle\ProductBundle\Entity\Product" table="sylius_product">

        <field name="type" column="type" type="string" nullable="true" />

    </entity>

</doctrine-mapping>

config.yml

    sylius_product:
        driver: doctrine/orm
        classes:
            product:
                model: Foo\Bundle\ProductBundle\Entity\Product

However, if i migrate the database it seems like some parts of the original schema aren't recognized anymore, because it trys to drop them from the table

        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('DROP TABLE sylius_product_channels');
        $this->addSql('DROP TABLE sylius_product_taxon');
        $this->addSql('ALTER TABLE sylius_product DROP FOREIGN KEY FK_677B9B749DF894ED');
        $this->addSql('ALTER TABLE sylius_product DROP FOREIGN KEY FK_677B9B749E2D1A41');
        $this->addSql('ALTER TABLE sylius_product DROP FOREIGN KEY FK_677B9B74E64AACD3');
        $this->addSql('DROP INDEX IDX_677B9B749DF894ED ON sylius_product');
        $this->addSql('DROP INDEX IDX_677B9B749E2D1A41 ON sylius_product');
        $this->addSql('DROP INDEX IDX_677B9B74E64AACD3 ON sylius_product');
        $this->addSql('ALTER TABLE sylius_product ADD type VARCHAR(255) DEFAULT NULL, DROP tax_category_id, DROP shipping_category_id, DROP restricted_zone, DROP variant_selection_method');

**Comment by pjedrzejewski** [comment]
@caramba1337 You should extend the core component, not product one. :)

**Comment by caramba1337** [comment]
@pjedrzejewski Thanks Pawel. But the docu itself says you should extend the component? http://sylius.readthedocs.org/en/latest/bundles/general/overriding_models.html
  use Sylius\Component\Taxation\Model\TaxRate as BaseTaxRate;

**Comment by nakashu** [comment]
@caramba1337 @pjedrzejewski but this is also a bug with the mapped supperlcass in doctrine, that prevents it from picking up indexes from the supperclass.
http://www.doctrine-project.org/jira/browse/DDC-3418

It should be fixed, in doctrine 2.5, but because of the paging issues, sylius uses doctrine <2.5.
https://github.com/Sylius/Sylius/issues/3268#issuecomment-139600135

**Comment by pjedrzejewski** [comment]
@nakashu In this case I don't see the bug you referenced here, all fields seem to be properly inherited from component model, hm?

@caramba1337 Yes, but this is general overriding guide for bundles, not for full platform - we will have that separate and add note to avoid confusion. Thanks for reporting this problem. :)

**Comment by nakashu** [comment]
@pjedrzejewski .. you are right, I focued on the indexes only, and didnt see the other tables.

**Comment by caramba1337** [comment]
okay got it now. i was confused because of the part in the documentation. thank you guys
