### ISSUE TITLE
 need advice - generate path to specific product 

### ISSUE THREAD

**Issue by soerenmartius** [Sylius/Sylius#3612]
Hi,

i am new to sylius and just about discovering the system. So i've found sylius main configuration yaml file where you can define prefixes for product detail pages. I am just wondering if there is a way to generate the path to a specific product without passing the whole object itself {{ path(product) }}.

Is there a way to generate a path like {{ path('show_product', product.id) }} ?
Many thanks

**Comment by pjedrzejewski** [comment]
Seems like currently no, we removed the ``sylius_product_show`` route, which is not good of course. We should definitely bring it back. Thanks for opening this issue. :)

**Comment by caramba1337** [comment]
In which version do you deleted it? i would just grep it out of a old version.

**Comment by michalmarcinkowski** [comment]
Path to product can be simply generated using `{{ path('sylius_shop_product_show', {'slug': product.slug}) }}`
