### ISSUE TITLE
Flexible variants by Marcos Passos

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#362]
This is a copy of the RFC by @marcospassos.

This RFC tries to address the issue when you have numerous (possibly price-altering) product options and you don't want to create variants for each combination. Products like sandwiches, pizzas, etc, are impossible to work just with variants. Think in a product like Subway's sandwich that might have more than 5.000.000 combinations, is impossible to create a variant and pick a price for each combination.

**Important**
This RFC contemplates all options where user cannot modify the value, only choose among the predefined ones. In this context, if the user has control over the value, then it's a customization (read more on #363).
### Proposal

The purpose of this RFC is bring up a discussion for a solution that enables the creation of highly customizable products without the need to create a variant for each combination.
#### Subway sandwiches:
- There are some primary sandwiches: Ham, Veggie Delite, Roast Beef, Subway Club, etc.
- The customized sandwich must be based on a primary sandwich
- When a sandwich is sold, the stock should be decreased (including customized sandwiches). The sandwiches stocks are trackable by product, not by ingredients.
- Sandwiches contains a bread, stuffing, salads, sauces, etc
- You can choose just one bread
- You can choose zero or more salads without additional costs
- You can choose up to 3 sauces without additional costs
- You can choose up to 1 cheese without additional costs. Extra cheese is charged.
#### Pizzas:
- The available flavours are: Margherita, Chicken Fiesta, 5 Pepper, Deluxe Veggie, etc
- You can create a customizable pizza
  - The customizable pizza must be based in the available flavours
  - If small, you can choose just one flavor
  - If medium, you can choose up to two flavors
  - If large, you can choose up to three flavors
  - The price can be calculated in different ways: the highest value, lowest, average, etc
#### Softwares:
- To buy a computer, is necessary choose an operating system
- The operational systems are also products
- The computer's page has a list of compatible operational systems
- When a OS is chosen, the price is added to the computer price
- The OS stock unit should be adjusted
#### Introduce a customization layer

Currently, if you have an option set "Colors" with 10 colors and you need to reuse this set, except one of these colors, you have to duplicate this set and remove the unavailable color. Adding a customization layer in the relationship entity, you can do the customization needing without replicating the option set. Furthermore, you can set specific configurations (I'll talk about this later) like multiple selection, calculator type, default selection, changes in the title, price adjustments, selection rules (selection min, max, etc), etc.

![Class Diagram0](https://f.cloud.github.com/assets/943036/433676/bfeefa18-aee2-11e2-89a7-b22dc0935563.png)
#### Introduce an Option Calculator

There are several cases where you have a logic to define the price based on customer option combination. For example:
- If you buy a small pizza, you can choose just one flavor, but if you choose a medium size you can choose up to 2 flavor, paying for the more expensive flavor.
- If you buy a computer, you have 2GB included in the price, but you can choose 4GB, 8GB or 16GB paying the difference.
- If you buy a cake, you can choose the candies that will come over the cake. Each candy has a price and should be summed in order to get the price.

My suggestion is introduce a `OptionCalculator` in the `ProductOption`, mentioned previously, so you can choose the pricing logic per option set.

The product price is given by: product base price + sum of all product options (calculated by `OptionCalculator`).

The calculator should accept additional configuration. In the following example, there are 3 types of cheese available. All have the same price, and one can be chosen without additional cost, but extra cheeses are charged. So, the `SumCalculator` can be used passing the `discount` parameter.

``` php
$option = new Option();
$option->setName('Cheese');

$productOption = new ProductOption($option);
$productOption->setCalculator('sum', ['discount' => 1.5]);
```
#### Change the variant transformer

Currently, `DataTransformer` tries to find a variant that contains all option values selected by the user.

My suggestion is introduce a new property in the product to specify the combination policy. 
For now, the available options would be:
- Explicit - The user can do any combination defined by variants.
- Flexible - The user can do any combination, except the combination excluded by `VariantExclusion`.

These are the transformer processing steps:
- If the product combination policy is "explicit", then a variant should be returned or a exception should be thrown.
- If the product combination policy is "flexible", then the transformer checks if the user's combination isn't excluded by a `VariantExclusion`. If so, throws an exception, otherwise looks for a variant that matches with the user input (allowing stock tracking). If any variable is found, then the master variant should be returned.
#### General changes
- Store the selected options by user in the sale order, once the variant is not enough anymore to determine the options that have been chosen.
### API

``` php
$option = new Option();
$option->setName('Flavors');

$productOption = new ProductOption($option):
// Default calculator is SumCalculator (sum all selected options)
$productOption->setCalculator('average');

$pepperoni = new OptionValue();
$pepperoni->setValue('Pepperoni');

$pep = new ProductOptionValue($pepperoni);
$pep->setAdjustment(new Adjustment(15.00));
$productOption->addValue($pep);

$veggie = new OptionValue();
$veggie->setValue('Veggie');

$veg = new ProductOptionValue($veggie);
$veg->setValue('Delicious Vegetables'); // slight modification
$veg->setAdjustment(new Adjustment(5.00));
$productOption->addValue($veg);

$selectedValues = [$pep, $veg];

$registry = ...;
$calculator = $registry->getCalculator($productOption->getCalculator());
echo $calculator->calculate($selectedValues); // prints 10.00 or (15.00 + 5.00) / 2

$pizza = new Product();
$pizza->setName('Customized Pizza');
$pizza->addOption($productOption);

$pepperoniVariant = new Variant();
$pepperoniVariant->setTitle('Pepperoni Feast');
$pepperoniVariant->addValue($pep);
$pizza->addVariant($pepperoniVariant);

$veggieVariant = new Variant();
$veggieVariant->setTitle('Fresh Veggie');
$veggieVariant->addValue($veg);
$pizza->addVariant($veggieVariant);

$transformer = new VariantToCombinationTransformer($pizza);
$variant = $transformer->reverseTransform([$pep]);
echo $variant->getName(); // prints "Pepperoni Feast"
$variant = $transformer->reverseTransform([$pep, $veg]); 
echo $variant->getName(); // prints "Customized Pizza", from master variant
```

**Comment by MichaelKubovic** [comment]
If I understand it correctly, the very first step would be to replace many-to-many relationship between Product and Option with ProductOption entity. If I wanted to implement this in my custom bundle, I'd need to override Product class, especially $options attribute. And here comes the problem, because VariableInterface, implemented by Product class, declares addOption's signature as addOption(OptionInterface $option).

Does that mean that I one cannot simply implement FlexibleVariants without touching Sylius codebase?

**Comment by diimpp** [comment]
Future? :(
A must have for shop with digital goods. In fact, I think it's required just everywhere.

**Comment by MichaelKubovic** [comment]
@diimpp It's not that hard to implement on your own. I'm happy to share code snippets with you if you want. Live sylius-powered example https://www.t3works.sk/t3/vystavne-stanky/t3-tower

**Comment by diimpp** [comment]
@MichaelKubovic That would be very kind of you. Thank you. :+1:

**Comment by nakashu** [comment]
@diimpp also if you check current labels you'll see that all version labels were removed.
So it could also mean that it would be implemented before 1.0.0 or 2.0.0 ... but no exact version is defined.

**Comment by MichaelKubovic** [comment]
@diimpp let's take it offline. I'm avail on skype: michael.kubovic

**Comment by Mr-Negative** [comment]
@MichaelKubovic Hi, could you share it with me? i need it badly.

**Comment by mablae** [comment]
@MichaelKubovic I am also looking for an example of this kind of configuration. Do you run your implementation with Sylius 1.0.0 already? Would you share your snippets like suggested above? 

Thanks in advance

**Comment by MichaelKubovic** [comment]
The above mentioned project was frozen on a pre-alpha version and is of no real value now. I'd still recommend coding it yourself to fit your requirements directly. At the end of the day you want to buy a Variant that links several Option Values and some custom calculator that knows how to calculate price based Option Values.

**Comment by mablae** [comment]
Okay thank you anyways, @MichaelKubovic . I will try it. 

Currently my mental model is stuck, is a ProductVariant has to be persistet at all with your approach?

**Comment by MichaelKubovic** [comment]
Depends on what kind of information are you willing work with. I think it's a good idea because Variant is well known entity in Sylius and many interfaces already work with it, at least CartItem and Calculator. But it's up to you to decide what part of information is preserved by OptionValue instance, and what information is persisted elsewhere in Cart/Order. Let's continue this discussion on slack, maybe I can help you there.
