### ISSUE TITLE
restricted zone implemented wrongly

### ISSUE THREAD

**Issue by Sp0ng3b0b** [Sylius/Sylius#3620]
Im still not sure how the restricted zone features is intended. I want to sell my products only to customers from germany so i created a zone (without a scope) containing only germany. I set the products restricted zone to germany. 
When i have given an adress i cant put the item in my cart. If i have not, i can add it to my cart. So i thought i am using it wrong. 

I created a zone "All but germany" and set it as the restricted zone. Now i can put it my cart. But when i should see the shipping selection in the checkout process i get the message "Product %product% removed from cart since it is not available in your country."

I have one shipping category and one shipping method using the same zone as above. So my guess is the feature is not correctly implemented.

**Comment by inssein** [comment]
This was pretty confusing for me as well. You have to create two zones:
* All but Germany
* Germany

The product's restricted zone should be "All but Germany", and the shipping method must be set to zone "Germany".

**Comment by Sp0ng3b0b** [comment]
Okay thanks will give it a shot and report back :+1:

**Comment by inssein** [comment]
@Sp0ng3b0b awesome! Please don't forget to close the issue as well.
