### ISSUE TITLE
[Routing] Sub routes (e.x. /about-us/extra-route)

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#3629]
Currently you can only have routes at the top level, sub routes are not supported. So you could never create a content page and make the URL `/about-us/extra-route` route to it. Is there currently something going on on how we could solve this?

The issue lies with that the PHPCR `Route` document works with parents and children. Should we adjust the form type so you can link a route to an existing route as its parent?

**Comment by steffenbrem** [comment]
Any ideas on what might be best for this? I was thinking of making an embedded field `parent` on the `RouteType` so you can nest parents to infinity.

**Comment by pjedrzejewski** [comment]
@steffenbrem This idea totally makes sense to me, I think this is how routes should work as well, so that ``/about-us/extra-route`` document is child of ``/about-us`` route document, although I am not sure if it is correct from the perspective of CMF. Maybe @psyray or @dbu could help us here. :)

**Comment by dbu** [comment]
yep, that is the idea. the PHPCR-ODM routes look at the configured "base path" and take whatever path they have below that as their url. because of the parent-child tree and `/` being the separator for that, you can't have a sub path without the parent - you always need a parent route to attach the child to. with the ORM documents, the path is just a string field and no need for a parent to exist. but if you don't want a real page at the parent, you can just create a RedirectRoute there and redirect to either the child or the home or whatever. that will also be nice when a user edits a URL hoping to move up in the navigation. and there is a RoutingAutoBundle that can generate routes automatically if needed, including parents.

**Comment by psyray** [comment]
Hi,
I'm working on a tree browser to permit this use case, like in Sonata
![selection_222](https://cloud.githubusercontent.com/assets/1230954/11508276/32751584-9858-11e5-974a-3ac57b32121f.jpg)

Redirect route are not implemented yet.

I post the progress in this thread

**Comment by dbu** [comment]
interesting. ideally that would be a stand-alone component. at the CMF
we worked on and off on a CmfTreeBrowserBundle (which in its first
iteration is the base of SonataDoctrinePhpcrAdminBundle).

there is also marmelab/ng-admin which is a pure js think on top of API.
that could be another road to go.

unless you need a very specific and tightly coupled tree browsing
specific to sylius, it would be awesome if we could join efforts there.

**Comment by psyray** [comment]
I'm currently using the CmfTreeBrowserBundle to reach my goal, thanks for this :+1: 

marmelab/ng-admin is really awesome, but I think it's a bit difficult to implement in Sylius, maybe i'm wrong. @pjedrzejewski ?

Currently the SyliusContentBundle is only a bundle for Sylius, and need to be specific, I don't know if it could be turned into a component to be more flexible. My Symfony knowledge is not enough to talk about this.

I'm OK to work together to produce a complete tree browsing, easy to integrate in any CMF project.

@pjedrzejewski : According to the Sylius arch, do you think the content part could be turned into component ?

**Comment by dbu** [comment]
not sure how much reusable content can be. i just meant the tree ui and api
logic.

**Comment by psyray** [comment]
Wrong reflexion for me... sorry.

OK go with tree ui and api logic.

The next question is : Have you an idea on how to do this ? :D

I don't know correctly the TreeBrowser usage, I'm currently in the analyze process.
Your bundle refer to the [Symfony docs] (http://symfony.com/doc/master/cmf/bundles/tree_browser/introduction.html).
I read it and every tree examples refer to Sonata.
It's a bit complex to extract the basic information to implement tree.

I understand that the steps are :
- Insert bundle and config in composer and appKernel
- Insert basic route (tree and FOSJS)
- Add tree config to DependencyInjection/Configuration.php
- Create controller to manage tree action
- Create tree controiller service to acces controller from anywhere
- Create twig file with JS rendering tree

I'm currently here in my implementation

What are the next steps ?

**Comment by psyray** [comment]
up !
I could work on it, but I need feedback ;)

**Comment by pjedrzejewski** [comment]
@psyray Hey Raynald! I will have a look at this during the weekend and let you know. Your workflow sounds good but I have never used TreeBundle before. Before we add it, let's consider if we can perhaps achieve the same thing without using the whole bundle. I will elaborate on that after some research. Thanks!

**Comment by psyray** [comment]
Thx for feedback @pjedrzejewski
