### ISSUE TITLE
Cant install the standard edition fails on dependancies 

### ISSUE THREAD

**Issue by nslocomotives** [Sylius/Sylius#3644]
Please can you assist i think the composer file in the standard package needs some work, I'm following the steps on your main website to install the standard edition to start my project, i wasn't expecting to have to start fixing issues from the get go. 

Nigel.

heres the output i get. 

Nigels-iMac:NetBeansProjects nigelsmith$ php -dmemory_limit=-1 /bin/composer create-project sylius/sylius-standard -s dev
Installing sylius/sylius-standard (dev-master 4a2f05e8ab0611de14569f4417242b13621e546f)
  - Installing sylius/sylius-standard (dev-master master)
    Cloning master

Created project in /Users/nigelsmith/NetBeansProjects/sylius-standard
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sylius/sylius 0.16.*@dev -> satisfiable by sylius/sylius[0.16.x-dev].
    - sylius/sylius 0.16.x-dev requires doctrine/phpcr-odm ^1.3@rc -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by nslocomotives** [comment]
I think i may have opened this against the wrong sylius repo this is for sylius-standard

**Comment by nslocomotives** [comment]
so this is this https://github.com/Sylius/Sylius/issues/3595 issue, I'm sorry i didn't see it in the closed list.  I added the line to the composer.json file that was downloaded and reran composer install, and it seams to have got me through, will this be fixed in the standard edition, or do i need to raise this issue on that repo too?

**Comment by pjedrzejewski** [comment]
@nslocomotives Yes, please do open an issue on SE repository. We will fix this as soon as possible. :+1:
