### ISSUE TITLE
Why can we not delete shipping methods anymore?

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#3654]
@gperdomor, you're PR #3229 deleted the route that allows the deletion of a shipping method.

While the additions you made seem good and sensible, why should you not be able to delete a shipping method? What if you made a mistake while creating one? 

I can understand that you might not want to allow the deletion of used shipping methods - but this should be done through validation or doctrine cascade rules, or make the entity soft-deletable. I wouldn't remove the ability to delete this entity.

This was a BC break, as it's broken our app.

**Comment by pjedrzejewski** [comment]
I don't think we will want to make more entities softdeleteable, I'd vote for the opposite. :) If you define the route on your side, will that work for you?

**Comment by peteward** [comment]
We certainly can, or we could add it back into Sylius if we think it should be (I don't want both to happen)?

As part of the UI rework it would probably be better to move Delete buttons onto the View / Edit page rather than Index pages as default. Delete can be dangerous in such positions (as well as using a lot of screen space). If you need to delete in bulk then I think this could be done by tickboxes and a Delete Selected or similar.

**Comment by okwinza** [comment]
IMO toggable approach is better in this case but i think we can combine the better parts of each one.

e.g. only allow to delete shipping method if it is not used anywhere(no orders with such method, no carts, etc)

What do you think?

**Comment by peteward** [comment]
Yes, agreed. Togglable is good, a definite improvement.  But I still think delete is needed.

**Comment by michalmarcinkowski** [comment]
@peteward can't you just edit the shipping method in which you made a mistake? I know it is a better UX to allow for deleting everything, but we have relations to other entities and softdeletable is not considered as a good solution, because it complicates stuff...

Probably the solution would be to come up with some generic listener that checks if they are any relations to the entity and then prevents from removing it, but it will require to take care of every relation between entities in whole Sylius, so probably a lot of code and logic...

@peteward do you think that deleting the shipping method is a must have feature?

**Comment by peteward** [comment]
@michalmarcinkowski I think fundamentally you should be able to delete something you create if it's not used. I can think of lots of use-cases where someone on my admin team my create something because they were told the wrong information, or were preparing something another team member built at the same time, or were just trying out the page. Leaving it around for someone else to perhaps edit later isn't great.

I don't love soft-deletable either, I'm not suggesting we should use it here, it's just an option.

I don't see why you would have delete for lots of entities but not shipping methods. I also don't think a generic listener that you are talking about is necessary, you should be able to do it through Doctrine relationships. Basically you don't want a shipping method to be deleted if it's been used in a Shipment. In which case correct doctrine config should prevent it happening anyway (although not the friendliest error message).

**Comment by michalmarcinkowski** [comment]
@peteward I don't think we should depend on database exceptions when handling delete errors. This is the reason for having a listener that will validate the possibility to remove entity. We will open an RFC and maybe find some better solution for this issue, but that's the first thing I thought of.

**Comment by peteward** [comment]
Agreed, definitely in a perfect world.

But for now, you at least know that the entity won't be removed if it shouldn't be. Not great user experience but in the Sylius world of a million things to implement by Christmas to get a stable release, it's not going to be high on anyone's implementation list.

Then you might argue the same about deleting a shipping method...

I will add the route back into our project and we'll see what happens in the longer term.

**Comment by michalmarcinkowski** [comment]
You're right! Let's move forward with the database exception catch to fix current errors and then think about a better solution.

**Comment by michalmarcinkowski** [comment]
Implemented in #4047.
