### ISSUE TITLE
[Taxonomy] Error when creating taxons with same name

### ISSUE THREAD

**Issue by gperdomor** [Sylius/Sylius#3661]
Hi...

We can now override taxon translations thanks to @pamil, but now we have this new issue.

The problem is the generation of permalink which is not unique and the doctrine insert fails.

In my case, i have a new field called <code>serie</code>, should be nice having a way to configure/override the mapping for use some extra fields (the new fields) in the slug generation

Also i tried to override the slug configuration with the following code but without success:

<code><pre>
    attributeOverride:
        slug:
            column: slug
            unique: false
            gedmo:
                slug:
                    fields:
                        - name
                        - serie
                    unique: true
        permalink:
            column: permalink
            unique: false
            gedmo:
                slug:
                    unique: false
                    fields:
                        - name
                        - serie
                    handlers:
                        "Sylius\Bundle\TranslationBundle\GedmoHandler\TranslationSlugHandler":
                            relationField: translatable
                            relationParentRelationField: parent
                            parentFieldMethod: getPermalink
                            locale: locale
                            translate: translate
                            separator: /
</pre></code>

**Comment by michalmarcinkowski** [comment]
Fixed already.
