### ISSUE TITLE
[TaxonomyBundle][TranslationBundle] Weird behavior with slug generation

### ISSUE THREAD

**Issue by gperdomor** [Sylius/Sylius#3662]
I notice some problems when edit taxons.

1 - When you create a new taxon and only set the name, you will get something like this in sylius_taxons_translations:

| name | slug | permalink | locale |
| --- | --- | --- | --- |
| Test | test | PTN/test | en_US |

PTN represent the parent taxonomy name.
Result: Everything fine... for now...

2 - When you edit that taxon and change the name to "Test 2", you will get something like this in sylius_taxons_translations:

| name | slug | permalink | locale |
| --- | --- | --- | --- |
| Test 2 | test-2 | PTN/test-2 | en_US |

Result: Slug and permalink are updated automatically (weird behavior IMO)

3 - When you edit that taxon and change the permalink to "PTN/test-2-edited", you will get something like this in sylius_taxons_translations:

| name | slug | permalink | locale |
| --- | --- | --- | --- |
| Test 2 | test-2 | PTN/PTN-test-2 | en_US |

Result: Only permalink are updated but the value is prefixed with the PTN (too weird behavior)

**Comment by gperdomor** [comment]
maybe is related to #3661

**Comment by mojzis** [comment]
i think it would be great to add a checkbox on the form, if the user wants the slug + permalink changed automatically or not or they want to set it manually ... of course the same settingcould be accessible from code ... ie we now have problems migrating products where we want to maintain the slug for historical reasons, but it gets set automatically ...

**Comment by pjedrzejewski** [comment]
@mojzis I :+1: this idea. Could you open a separate issue with this suggestion, please?

**Comment by michalmarcinkowski** [comment]
Fixed already.
