### ISSUE TITLE
[RFC] [ChannelBundle] Channel entity should maybe extend from AbstractTranslatable

### ISSUE THREAD

**Issue by axelvnk** [Sylius/Sylius#3670]
I'm building a webshop with multiple storefronts. I made a menu that I can print out, but I need to have different localized names for my store fronts aka channels. Because one shop is the UK store, the other is the Belgium store.. So making the name field translatable would be ideal...

**Comment by pjedrzejewski** [comment]
I am not sure about this, but if we do this, let's wait until we rework Resource bundle and translations. Will be much simpler. :)

**Comment by axelvnk** [comment]
@pjedrzejewski okay. No problem, let me know and I'll help out. Working on adding the defaultLocale and defaultCurrency fields to the Channel model right now (#3671).
