### ISSUE TITLE
[RFC] [ChannelBundle] Channel should have a defaultLocale field

### ISSUE THREAD

**Issue by axelvnk** [Sylius/Sylius#3671]
Now, when you open a storefront through its domain, it automatically uses the sylius_locale parameter. However, if that locale is not part of the enabled locales for that channel, it doesn't make any sense to load the storefront with that locale enabled... Even if the default locale is also enabled for that channel, a defaultlocale field would be nice, for more control.

I would be happy to do this myself and create a pull request for us to discuss.

**Comment by pjedrzejewski** [comment]
Agree, I think we should also have default Currency on every channel.
