### ISSUE TITLE
[Rbac][Possible Bug] Permission issue with static content

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#3672]
If your not logged in you cannot view static content, which should be possible obviously. Currently Sylius configured CMF to use the `ResourceController` to show `StaticContent`, so this means it goes through Sylius authorization process. Because of the following line: https://github.com/Sylius/Rbac/blob/master/Authorization/AuthorizationChecker.php#L64 you can never pass this authorization (since it will always return `false`). 

Shouldn't it only try to authorize when the permission actually exists in the database, so we could leave out the `sylius.static_content.show` permission in the `rbac` configuration, so it will always be granted.

Am I missing something or is this a bug?

**Comment by pjedrzejewski** [comment]
We should disable the security for this route then, in Sylius routing:

```
app_route_xyz:
    ...
    _sylius:
        permission: false
```
