### ISSUE TITLE
[ResourceBundle] update action in resource controller do not check for stopped events

### ISSUE THREAD

**Issue by aleherse** [Sylius/Sylius#3676]
Hello everyone,

The problem is that I created an event listener for an event like sylius.order.pre_create, I stopped the event propagation but it didn't work.

I followed the trace and checked that `$this->domainManager->update($resource);` is not returning to updated resourcer or the event in case it was stopped.

I will shortly sent a PR with the required change, though I don't know if it will have any side effect.

**Comment by pjedrzejewski** [comment]
Thanks for report and fix. :+1:
