### ISSUE TITLE
[ReportBundle] Error after component installation

### ISSUE THREAD

**Issue by Infernosquad** [Sylius/Sylius#3683]
Just installed SyliusReportBundle as component in my project following these [docs](http://docs.sylius.org/en/latest/bundles/SyliusReportBundle/installation.html) and got this error after:

    The service "sylius.form.type.report" has a dependency on a non-existent service "sylius.registry.report.data_fetcher".

**Comment by pjedrzejewski** [comment]
Thank you for reporting Artem, we just updated Components documentation and will progress with bundles shortly.

**Comment by michalmarcinkowski** [comment]
Should be fixed already.
