### ISSUE TITLE
Backordered Products - How do they ship?

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#3687]
I am just trying out backorders in my Sylius application, and it's not immediately clearly how to fulfill a backordered product.

When someone places an order for a product that is backordered, how do you then ship the inventory? Pressing "ship" in the back end throws a 500 as there is no transition from 'backordered' to 'shipped'. 

I see a transition called 'prepare' that moves an item from 'backordered' to 'ready' first. Is there no UI for that yet?

**Comment by michalmarcinkowski** [comment]
The backorders are removed from master, once they will be back we will make sure they are well documented 😉

**Comment by kubaceg** [comment]
I can't find any other pieces of information about backorders in sylius. This feature is actually in latest (1.7.5) sylius or it's still abandoned?

**Comment by lchrusciel** [comment]
This feature has never been brought back, it is something that needs to be done on your own or with some plugin(tho I'm not sure if such plugin exists).
