### ISSUE TITLE
[Backend] Order creation

### ISSUE THREAD

**Issue by rpg600** [Sylius/Sylius#3688]
Hello everyone, we are currently able to edit orders thanks to https://github.com/Sylius/Sylius/pull/1864.
But is there any plans in order to implement the creation feature ? Can it fit into the v0.16 ?

**Comment by gabiudrescu** [comment]
I wonder if you can impersonate the user as an admin and place the order on his behalf. Is that an option for you?

**Comment by mingxing** [comment]
If we want to create orders with program(like import), how can we do that?

Thank you

**Comment by steffenbrem** [comment]
@mingxing Check out the fixtures that are provided with Sylius at https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadOrdersData.php

**Comment by mingxing** [comment]
You are awesome, thank you!

**Comment by kironet** [comment]
Still "Not implemented yet" Any plans to update?

**Comment by olivier1208** [comment]
Hi
Is it implemented now ?
Thanks all 👍

**Comment by kironet** [comment]
No its not, go check out demo.

**Comment by kironet** [comment]
Looks like it's released now and still does not have feature to create orders from admin panel?

**Comment by gabiudrescu** [comment]
@kironet no, but I don't think it's that hard to customize the current logic to accommodate this behavior. 

the idea of creating orders directly implies some customization that should not lie in the core. for example: do you want to create orders with promotions? if so, what's different than impersonating a user and completing an order on his behalf?

**Comment by stefandoorn** [comment]
Question is also whether you need to have certain functionality in core. For me Sylius is more like the base to handle online sales and other channels should flow into a generic order system where order management from all channels comes together.

**Comment by alexrowesoap** [comment]
I think this should be a feature. Every other ecommerce solution offers this, and if Sylius is supposed to be competing with the other players in the market, it should offer what is considered standard funtionality by the rest of the industry.
In regards to this not being something that is core behaviour, I ask: why not? Sure, it cannot be expected to hande bespoke checkout logic, but as orders and promotions are a part of the core, there is no logical reason for this to not exist in a basic form.
As an example, if a store has a complex frontend product flow (eg a questionaire) it cannot be expected for staff that know the system to proccess an order on the frontend if taking a telephone or internal order.

**Comment by lchrusciel** [comment]
Please, share your thoughts here: https://github.com/orgs/Sylius/projects/2

This issue will be covered in https://github.com/Sylius/Sylius/issues/9501
