### ISSUE TITLE
[ResourceBundle] FlashHelper is always created. isApiRequest always fails in setContainer

### ISSUE THREAD

**Issue by bendavies** [Sylius/Sylius#3697]
Hi,

[This](https://github.com/Sylius/SyliusResourceBundle/blob/abce974d97e357f4499d44d22586c6a7c532331b/Controller/ResourceController.php#L86) check will always fail as [request](https://github.com/Sylius/SyliusResourceBundle/blob/abce974d97e357f4499d44d22586c6a7c532331b/Controller/Configuration.php#L142) is always null at this point in time. 
Request is only set on the configuration later by the [Listener](https://github.com/Sylius/SyliusResourceBundle/blob/abce974d97e357f4499d44d22586c6a7c532331b/EventListener/KernelControllerSubscriber.php#L99)

This is a problem for me, because i'm only using the resource bundle for a stateless API, so if the flash helper is instantiated, i get a session write error when it sets a message on resource creation/update/whatever.

Not sure on the best way to fix, but if you have an idea, I'm happy to submit a PR.

**Comment by michalmarcinkowski** [comment]
This issue is fixed in https://github.com/Sylius/Sylius/pull/2255. Flashes management has been reworked and are done by listener in the new ResourceController.

**Comment by bendavies** [comment]
Right!
Well it seems that is a rather long running refactor.

If there is a quick fix for this issue then it's probably worth fixing it rather waiting for that PR to be merged?

**Comment by gperdomor** [comment]
+1 for quick fix

**Comment by michalmarcinkowski** [comment]
@bendavies unfortunately there is no quick fix... We plan to merge the new Controller till the end of year, if you are not able to wait for it I suggest to grab this branch and try to do something similar in your project.

**Comment by bendavies** [comment]
@michalmarcinkowski yep, I already have a workaround in my project by overriding ResourceController, so not massive urgency from me.

**Comment by bendavies** [comment]
fixed!

**Comment by pjedrzejewski** [comment]
:+1:
