### ISSUE TITLE
SyliusFlowBundle deprecation notice for Symfony 2.8

### ISSUE THREAD

**Issue by andreopmaria** [Sylius/Sylius#3698]
I use Symfony 2.8 and try to prepare for 3.0, watching deprecated notes.

The Process\SyliusScenario class extends Symfony\Component\DependencyInjection\ContainerAware that is deprecated since version 2.8, to be removed in 3.0. Use the ContainerAwareTrait instead

**Comment by gabiudrescu** [comment]
I have tried a pull request based on your issue. Hope its fine. 

Also, I have a question: can you tell me the link where I can see the deprecation notice for this?

**Comment by michalmarcinkowski** [comment]
The FlowBundle was removed.
