### ISSUE TITLE
[PromotionBundle] dependant of CoreBundle ?

### ISSUE THREAD

**Issue by VaN-dev** [Sylius/Sylius#3707]
Trying to install the PromotionBundle alone. First, [this bug] (https://github.com/Sylius/Sylius/issues/1191) occured to me, when trying to install PromotionBundle. So I installed MoneyBundle to get rid of this bug. And now I'm facing another bug :

`Service of type "fixed_discount" does not exist`

Looks like this service is registered in CoreBundle.. Is PromotionBundle also dependant of CoreBundle ? installing CoreBundle install the whole Sylius package. There is something wrong about your dependancies imo..

**Comment by michalmarcinkowski** [comment]
Thanks for reporting that David! We plan to make tests for individual bundles to be sure they work fine standalone.

**Comment by pjedrzejewski** [comment]
Fixed.
