### ISSUE TITLE
Promotion coupons not applied until cart has address?

### ISSUE THREAD

**Issue by Sp0ng3b0b** [Sylius/Sylius#3708]
When a customer adds a coupon based promotion to his cart, its not applied to cart until registration is completed (im not using guest checkout yet) and he has entered his address in /checkout/addressing. Is this intended or a bug? 
The coupon is simple fixed discount without any rules. When user is logged in, its applied immediately. 
This would not be a problem if i didnt want to display the entered promotions in the cart.
I am using a custom ajax action for it:

    public function applyCoupon() {
        $eventDispatcher = $this->getEventDispatcher();^
        $request = $this->get("request")->request->all();
        $coupon = $request["coupon"];
        $coupon = $this->get("sylius.form.transformer.promotion_coupon_to_code")->reverseTransform($coupon);
        if(!$coupon) {
            return new Response(null,Response::HTTP_BAD_REQUEST);
        } else {
            /** @var Coupon $coupon */
            $cart = $this->getCurrentCart();
            /** @var OrderInterface $cart */
            $cart->addPromotionCoupon($coupon);
            $event = new CartEvent($cart);
            $event->isFresh(true);

            $eventDispatcher->dispatch(SyliusCartEvents::CART_CHANGE, new GenericEvent($cart));
            $eventDispatcher->dispatch(SyliusCartEvents::CART_SAVE_INITIALIZE, $event);
            return new Response(null,Response::HTTP_OK);
        }
    }

**Comment by pjedrzejewski** [comment]
Could you give us the configuration of the promotion? What kind of rules you have setup?

@Sylius/core-team This may be a bug so let's keep it here for now.

**Comment by Sp0ng3b0b** [comment]
Promotion:
name: xmas, priority:0, exclusive: 0, usage_limit: 999999999, used: 0, coupon_based:0, 

Action: 
type: fixed_discount, configuration: a:1:{s:6:"amount";i:500;}

Coupon:
code: xmas2015, usage_limit: 999999999, used: 0, per_customer_usage_limit: 1

I just tried again with guest checkout, after submitting my address data i get two(strange?) flash messages saying my coupon was added to cart.

**Comment by michalmarcinkowski** [comment]
The coupons should work fine now.
