### ISSUE TITLE
[RFC] Rework the payment flow in checkout

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#3710]
Hello folks!

I am working with @gabiudrescu on improving the Sylius checkout regarding the payment handling and here is what we have figured out. I think it will be best to illustrate it with Behat scenarios we have prepared and then discuss the more technical details:

```
@checkout
Feature: Checkout with offline payment
  In order to pay with cash or by external means
  As a Customer
  I want to be able to complete checkout process without paying

  Background:
    Given that store is operating on a single channel
    And default currency is USD
    And there is user "john@example.com" identified by "password123"
    And catalog has a product "PHP T-Shirt" priced at $19.99
    And store allows paying offline

  Scenario: Successfully placing an order
    Given I am logged in as "john@example.com"
    And I added product "PHP T-Shirt" to cart
    When I proceed selecting offline payment method
    And I confirm my order
    Then I should see see the thank you page
```

Something more advanced:

```
@checkout
Feature: Checkout with PayPal Express Checkout
  In order to buy products
  As a Customer
  I want to be able to pay with PayPal Checkout Express

  Background:
    Given that store is operating on a single channel
    And default currency is USD
    And there is user "john@example.com" identified by "password123"
    And catalog has a product "PHP T-Shirt" priced at $19.99
    And store allows paying with PayPal Checkout Express
    And I am logged in as "john@example.com"

  Scenario: Being redirected to the PayPal Express Checkout page
    Given I added product "PHP T-Shirt" to the cart
    When I proceed selecting PayPal Checkout Express payment method
    And I confirm my order
    Then I should be redirected to PayPal Checkout Express page

  Scenario: Cancelling the payment
    Given I added product "PHP T-Shirt" to the cart
    And I confirmed my order selecting PayPal Checkout Express payment method
    And I am on the PayPal Checkout Express page
    When I cancel my PayPal payment
    Then I should be redirected back to the order payment page
    And I should see one cancelled payment and new one ready to be paid

  Scenario: Successful payment
    Given I added product "PHP T-Shirt" to the cart
    And I confirmed my order selecting PayPal Checkout Express payment method
    And I am on the PayPal Checkout Express page
    When I sign in to PayPal and pay successfully
    Then I should be redirected back to the thank you page

  Scenario: Payment failed
    Given I added product "PHP T-Shirt" to the cart
    And I confirmed my order selecting PayPal Checkout Express payment method
    And I am on the PayPal Checkout Express page
    When I sign in to PayPal but fail to pay
    Then I should be redirected back to the order payment page
    And I should see one failed payment and new one ready to be paid

  Scenario: Retrying the payment with success
    Given I added product "PHP T-Shirt" to the cart
    And I confirmed my order selecting PayPal Checkout Express payment method
    But I failed to pay
    And I am redirected back to the order payment page
    When I try to pay again
    And I sign in to PayPal and pay successfully
    Then I should be redirected back to the thank you page

  Scenario: Retrying the payment and failing
    Given I added product "PHP T-Shirt" to the cart
    And I confirmed my order selecting PayPal Checkout Express payment method
    But I failed to pay
    And I am redirected back to the order payment page
    When I try to pay again
    And I sign in to PayPal but fail to pay
    Then I should be redirected back to the order payment page
    And I should see two failed payments and new one ready to be paid
```

Retrying the payment from my account page:

```
@checkout
Feature: Retrying to pay the order from my account panel
  In order to complete my unpaid orders
  As a Customer
  I want to be able to access the order payment page from my account panel

  Background:
    Given that store is operating on a single channel
    And default currency is USD
    And allows paying with PayPal Checkout Express
    And there is user "john@example.com" identified by "password123"
    And I am logged in as "john@example.com"
    And I have one unpaid order #000001 with total $29.99

  Scenario: Seeing the unpaid order in the list
    When I view my order history
    Then I should see one order with total of $29.99 and pending payment

  Scenario: Accessing the order payment page
    Given I am viewing my order history
    When I retry payment on my order #000001
    Then I should be redirected to PayPal Checkout Express page
```

```
@checkout
Feature: Changing the method on the order payment page
  In order to try different payment methods
  As a Customer
  I want to be able to change the method after checking out

  Background:
    Given that store is operating on a single channel
    And default currency is USD
    And there is user "john@example.com" identified by "password123"
    And catalog has a product "PHP T-Shirt" priced at $19.99
    And store allows paying with PayPal Checkout Express
    And it also allows offline payment
    And I am logged in as "john@example.com"

  Scenario: Retrying the payment with offline payment
    Given I added product "PHP T-Shirt" to the cart
    And I confirmed my order selecting PayPal Checkout Express payment method
    But I failed to pay
    And I am redirected back to the order payment page
    When I try to pay again with offline method
    Then I should be redirected back to the thank you page
```

Goals of these changes:

* Finally, having a proper thank you page and not a redirect to homepage
* Better UX for failed payments
* Proper handling of offline payments
* First step on proper flows with state machine
* Foundation for handling split payments

From technical point of view:

* Removing the purchase step from checkout and replacing it with a standalone controller for paying a single payment - you can link to that payment from anywhere (e-mail reminder, my account section, order payment page);
* Adding a order payment page - If there is a single payment - redirect to gateway, if multiple - display a list of payments with "Pay" button for each. In standard scenario there will always be a single payment with status "new", but we want to support split payments too;
* Moving whole checkout payment processing logic to state machine, killing all these listeners etc.

Side work:

As you can see, new scenarios differ from what we have now and this is just first step. We plan to implement this feature using nicer contexts and PageObject extension, keeping existing Behat stuff in place, but experimenting with something cleaner. We can't go 1.0 with our current Behat contexts cause they are already very hard to maintain.

Our @Arminek can start on this very soon, so please let us know if you have any ideas/comments to this approach. :)

**Comment by pjedrzejewski** [comment]
I'd also like to rework Payment and Order payment states. Currently we have:

Order.state -https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Order/Model/OrderInterface.php#L31
Payment.state, which are also used as Order.paymentState values - https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Payment/Model/PaymentInterface.php#L24

I'd avoid touching Order.state for now, as it is out of scope for this RFC. That being said, I'd like to do the following:

* Make sure we have all states for Payment.state, I know we need:

    * checkout - For payments created during the checkout, they should not appear in the cart;
    * new - Payments for completed checkouts, when customer hits "Confirm my order" button, all payments with state "checkout" should turn into "new" payments, which can be paid later in the process (via order payment page);
    * pending - We need some field to store more information about why is it pending, some gateway provide this info, would be great to store it;
    * cancelled - If customer cancels his payment on gateway page or inside Sylius;
    * failed - When charging the customer failed on the gateway side;
    * authorized - For CC payments;
    * processing - When the customer needs to wait for the result of the payment, gateway is processing or if he pays with the Offline payment method, then someone in the admin area needs to confirm the payment or automatically via some kind of bank integration etc.;
    * refunded - We do not support refunds, but will in the future, for now we should be able to mark a payment as refunded in the backend;
    * void;
    * unknown;

We have all these states on PaymentInterface, so it is fine. But currently they are used for Order.paymentState too, which is wrong.

The paymentState field on the order should represent the "sum" of all payment states on this order. I propose defining following states:

* completed - Order.total === sum of "completed" Payment.amount(s) on this order. 
* balance_due - Order total !== sum
* cancelled - Order has been cancelled so the same goes for payment;

Order.state and Order.shippingState will be related but we can't do everything at once, so we need to keep the current flow for other states.

All this should happen through our StateMachine and we should remove all listeners related to payment processing.

**Comment by peteward** [comment]
Sounds good. This is quite different to how I am used to do things but makes sense for flexibility.

One point:

```
As a Customer
....
And I should see two failed payments and new one ready to be paid
```

As a customer, do I really care about seeing failed payments? Especially 2 of them. If a new one is going to be created automatically then maybe just a message about the failure rather than seeing something failed? I don't think a failed payment has any value to the customer.

**Comment by pjedrzejewski** [comment]
@peteward Good point, I will update the scenarios!

**Comment by pjedrzejewski** [comment]
For reference: https://github.com/Sylius/Sylius/issues/485. I think we also need to modify the offline method so that it sets payment to processing and now completed by default. So that the store can somehow verify the payment.

**Comment by gabiudrescu** [comment]
@peteward from the user perspective, you care less about multiple failed payments. but from admin user perspective, you care a little bit more :) if the user is calling your customer support to complain about a failed payment, you might need some extra information.

take into consideration the followings:
* first failure is because you don't have money on your credit card / PayPal account
* 2nd failure is because credit card processing entity / PayPal marked the user as "fraudulent activity"

You need to make that obvious for the admin user.

On the second thought, I think it would be relevant for the user too: make it obvious to him in "MyAccount" he tried 2 times to pay for an order and he was denied multiple times for different reasons, given the payment gateway is able to give you the reason for rejecting that payment. 

What do you think about the modification below?

```
  Scenario: Retrying the payment and failing
    Given I added product "PHP T-Shirt" to the cart
    And I confirmed my order selecting PayPal Checkout Express payment method
    But I failed to pay because I have insufficient funds in my PayPal account
    And I am redirected back to the order payment page
    When I try to pay again with another PayPal account
    And I sign in to PayPal
    But fail to pay because I am marked as fraudulent
    Then I should be redirected back to the order payment page
    And I should see two failed payments for two different reasons and new one ready to be paid
```

Please pardon any mistake with my the scenario above, as my Behat skills are yet (very) limited.

**Comment by peteward** [comment]
Hi @gabiudrescu,

I 100% agree about seeing them as an admin user. It's just that the behat scenarios were written from the customer perspective, and I was just trying to understand if this was of relevance.

I don't think a customer really cares about how many times they failed to pay. They just want to try again and pay successfully. 

But this is a very minor point, the process and scenarios as a whole make sense :+1:

**Comment by michalmarcinkowski** [comment]
The payment flow is already reworked 😉

**Comment by gabiudrescu** [comment]
how eager was I and @pjedrzejewski about getting this done no later than December '15 :smile: 

well... this reminds me that I should write to Pawel, preferably Monday morning
