### ISSUE TITLE
[SQL Injection][PHPCR] There is a security flaw in the DocumentRepository

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#3713]
The following line is vulnerable for SQL injections: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Doctrine/ODM/PHPCR/DocumentRepository.php#L100

We should put the values of those in parameters, but I can't get this to work in `phpcr-odm@1.3`.

**Comment by steffenbrem** [comment]
Or is this not a problem?

**Comment by pjedrzejewski** [comment]
For potential security issues please follow this guide - http://docs.sylius.org/en/latest/contributing/code/security.html.

Anyway, I do not know how literal works in PHPCR, will try to check this today. Any help with fixing that appreciated! Thanks for reporting!

**Comment by steffenbrem** [comment]
I am sorry, will do that from now on.

**Comment by pjedrzejewski** [comment]
@steffenbrem No worries! :)

**Comment by steffenbrem** [comment]
Maybe @lsmith77 or @dbu knows if this is safe to use.

**Comment by dbu** [comment]
@steffenbrem that is the query builder, so i think it should be safe. the code compiling this to sql for doctrine dbal is this, and it esacpes: https://github.com/jackalope/jackalope-doctrine-dbal/blob/master/src/Jackalope/Transport/DoctrineDBAL/Query/QOMWalker.php#L700

but if you want to scan over that file again, please do. maybe we missed something. if you find something, best email david@liip.ch and lukas@liip.ch so we can fix it before announcing that there was a problem.
