### ISSUE TITLE
Product Variant Image title and description

### ISSUE THREAD

**Issue by pfwd** [Sylius/Sylius#3720]
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Fixed tickets |  |
| License | MIT |
| Doc PR |  |

I need to add a optional title and description to the product variant images. 
I'm more than happy to develop this as a extension but wanted to check if there was any need/want for me to do this as a PR?

Minor changes would include:
- Adding title and description to Image model
- Adding title and description fields to ImageType
- Updating backend form twig
- Adding label translations

**Comment by pjedrzejewski** [comment]
Sounds good to me!

**Comment by peteward** [comment]
This would probably be something provided by #3350, but no harm adding a manual option too.

**Comment by aramalipoor** [comment]
@pjedrzejewski IMO any kind of development on images/media before merging #2975 can cause BC breaks/headaches ;)

**Comment by Sp0ng3b0b** [comment]
It would be awesome if its possible to make image file names more self speaking, for seo purposes :)
:+1:

**Comment by gabiudrescu** [comment]
:+1: sounds good to me too. 

From my knowledge product variation is created based on an attribute, maybe you should take into consideration adding those titles & descriptions automatically, with an event on photo upload, based on the attribute used for variation.

Feature example:

```gherkin
Given there is a product called "TShirt Tom&Jerry"
And it has attribute "Color" 
And attribute "Color" has value "Black"
And it has productID "23234"
Then product photos should be named "TShirt_Tommy_Jerry_23234_Black.jpg"
```

**Comment by pamil** [comment]
@Sp0ng3b0b @gabiudrescu customizing image paths should be much easier to change after #3703, I'll consider that in further refactoring.

**Comment by gabiudrescu** [comment]
@pamil :+1:
