### ISSUE TITLE
Error message is not shown if Behat scenario fails (on Travis using test_cached environment)

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#3727]
Due to the latest optimizations, the cached suite is executed with `kernel.debug` parameter set to `false`. It speeds up our suite a lot, but also comes with a cost - uploaded error logs does not contain error messages.

Setting back `kernel.debug` to `true` is not an option, so I found out that we need to overwrite `twig.controller.exception` service.

```xml
<service id="twig.controller.exception" class="%twig.controller.exception.class%">
    <argument type="service" id="twig" />
    <argument>%kernel.debug%</argument>
</service>
```

If we set the second parameter to `true`, we will receive dev-like error messages without any other overhead cost.

**Comment by michalmarcinkowski** [comment]
:+1: Let's override this service in the test environment.

**Comment by pamil** [comment]
It should have been solved some time ago :)
