### ISSUE TITLE
FOSRestBundle listener needed for SyliusPromotionBundle?

### ISSUE THREAD

**Issue by rvanlaak** [Sylius/Sylius#3742]
The docs tell us that the `FOSRestBundle` is needed in order to use the `PromotionBundle`. http://docs.sylius.org/en/latest/bundles/SyliusPromotionBundle/installation.html#adding-required-bundles-to-the-kernel

We recently upgraded libxml to `2.9.2` and the restbundle it's `BodyListener` throws an `BadRequestHttpException` because it is registered on `kernel.event` and we have XML nodes that are > 10MB (see https://github.com/symfony/symfony/pull/16873 for more info). Because of the listener we can't handle this in the controller ourselves.

So, given we don't use the actual `WhiteOctoberPagerfantaBundle`, `FOSRestBundle` and `JMSSerializerBundle` ourselves, would it hurt if we remove these bundles from the kernel? In what specific cases are these bundles really needed?

**Comment by Zales0123** [comment]
It's been a while 😄 These bundles are used in **SyliusResourceBundle**, which is a base for almost every bundle in Sylius. Feel free to open if you have any more questions :)
