### ISSUE TITLE
Failed to remove directory

### ISSUE THREAD

**Issue by jelti** [Sylius/Sylius#3745]
Hello,
i'm using windows 8 and ve downloaded the sylius/sylius  using

composer.phar create-project sylius/sylius -s dev

My problem is that when i try the command 

php.exe app/console sylius:install -e prod

im always getting the error
Symfony\Component\Filesystem\Exception\IOException]                         
  Failed to remove directory "C:\Users\jelti.BISNET\Desktop\dev\mosite\app\ca  
  che\prod_old\annotations\1c". 

i ve tried many things but nothing is working

when i try to remove the cache sub directories manualy windows tell me that the file name is too long and that the files will be removed definetly. Is that reason of my problem?

Thanks in advance
M.

**Comment by gperdomor** [comment]
The failed remove issue, can occur when when you clear the cache and the web browser is still loading a page of the project, but the file name issue is not related to sylius, the path of the route to file seems to be to long.

try to put the project in the root of C drive: <code>C:\\mosite\\</code> or <code>C:\\Projects\\mosite\\</code>
