### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by malutanpetronel** [Sylius/Sylius#3747]
I was trying to install sylius more than once without success.
I am using a vagrant with ubuntu on a windows host. The vagrant machine host with success sites in symfony2, wordpress, magento... but sylius installation failed with different issues.

First after clonig the git project I did composer.phar install and then sylius:install

Opened the site and noticed it loads very slow and then issued clear:cache --env=dev

I was able to open then the /app_dev.php with a error that the select from sylius_channel cannot find column default_locale_id.

Dropped the db, recreated it now I do a install for sylius again

Will it work mates ?

**Comment by pjedrzejewski** [comment]
Unfortunately Windows support is experimental and not a priority right now. Sorry for that. We do not have enough people on Windows machines to help with these issues. We have AppVeyor setup to run nightly builds but it is crazy slow and has a lot of errors. As much as I'd love to, I can't promise improvement for Windows support anytime soon. We definitely will look into this before 1.0 but right now there is not time and resources for that...

**Comment by pjedrzejewski** [comment]
Also, it seems like db schema is not up-to-date. Try running ``sylius:install`` again and reset the database + load fixtures.

If this is still relevant and my suggestion above does not help, please post this question on StackOverflow - it is the official support channel for Sylius. Just tag your question with "sylius" and maybe someone will be able to help you! http://stackoverflow.com/questions/tagged/sylius

**Comment by malutanpetronel** [comment]
Hi pjedrzejewski

Today just installed a new vagrant version which seems to allow smb shares under windows which is much faster ! I will do in the evening a retry and let you know... However the installation was working and fixtures in the db where loaded to the end. Cannot imagine that the fixture were not loaded corectly as there was not failure, but I could eventually ask you if the fixtures are corectly synced with the code you are testing ? Sometimes it happen to have modifications in the DB directly which are not reflected in the migrations or code anymore... Hope it is not the case... but maybe you can check.
