### ISSUE TITLE
[ResourceBundle] Can't ignore translation config.

### ISSUE THREAD

**Issue by liverbool** [Sylius/Sylius#3748]
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/DependencyInjection/Configuration.php#L82-L113

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/DependencyInjection/SyliusResourceExtension.php#L57-L68

Now `resource-bundle` enforce to config `translation` part. I think it's not comfortable using.

cc/ @pjedrzejewski

**Comment by pjedrzejewski** [comment]
I will check it but I tried it with custom/standalone resource without translation and worked fine.

**Comment by pjedrzejewski** [comment]
Do you get an error? It is optional. I actually want to create an RFC about merging Translation into Resource (same for bundles) because it is a difficult task to decouple them properly, so we don't have it right at the moment, yet we get all the overhead with maintenance of 4 packages instead of 2.

**Comment by liverbool** [comment]
This code block will never `false`.
```php
if (isset($resourceConfig['translation'])) {
    ....
}
```

case of


```php
->arrayNode('translation')
    ->addDefaultsIfNotSet()
    ->children()
    ....
```

To fix it for now i just remove `->addDefaultsIfNotSet()`.

```php
->arrayNode('translation')
    ->children()
    ....
```

**Comment by bendavies** [comment]
ref https://github.com/Sylius/Sylius/pull/3749

**Comment by nakashu** [comment]
@liverbool @pjedrzejewski got the same issue, liverbool fix work for me also.
-

**Comment by liverbool** [comment]
:+1: solved, Thanks you all ***Syliusers***.

**Comment by michalmarcinkowski** [comment]
Thank you guys for reporting and fixing! :+1:
