### ISSUE TITLE
[Bug] Changing content of second menu node gives "This value is not valid." error

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#3752]
I have made a video to show the issue: https://www.youtube.com/watch?v=F8DbT2ytAlg (tested on `demo.sylius.org` and my own sylius installation)

When you create a new menu, and create two menu nodes linking to the same content it will save fine. But if you have different content for one menu node, it fails and gives you "This value is not valid.".

I am not sure if this is a recent bug or one introduced in `0.16` only.

Symfony profiler:
![Profiler](http://puu.sh/m0qNK/736ab52408.png)

**Comment by steffenbrem** [comment]
The issue lies in the `DoctrineChoiceLoader::loadChoicesForValues` method. It fails to retrieve the entities by id for the second time only, first time it loads correctly. That is why you cannot have two different content on two menu nodes. I will try and figure out why this is happening.

**Comment by steffenbrem** [comment]
This is of the first menu node, as you can see `$unorderedObjects` is correctly filled with the existing page.
![XDebug](http://puu.sh/m0rSr/6799e0fbbf.png)

**Comment by steffenbrem** [comment]
The SQL2 query generated by the query builder for the first run on a menu node:
```
SELECT * 
FROM 
	[nt:unstructured] AS e 
WHERE 
	(ISSAMENODE(e, [/channels/1/pages/contact]) 
	AND (e.[phpcr:class] = 'Mango\Component\Content\Model\StaticContent' 
	OR e.[phpcr:classparents] = 'Mango\Component\Content\Model\StaticContent'))

And here the SQL2 query for the second menu node, it is alot longer and weird:
```
SELECT * 
FROM 
	[nt:unstructured] AS e 
WHERE 
	(((((ISSAMENODE(e, [/channels/1/pages/contact]) 
			AND (e.[phpcr:class] = 'Mango\Component\Content\Model\StaticContent' 
            OR e.[phpcr:classparents] = 'Mango\Component\Content\Model\StaticContent'))
    AND ISSAMENODE(e, [/channels/1/pages/contact])) 
	
    AND (e.[phpcr:class] = 'Mango\Component\Content\Model\StaticContent' 
	OR e.[phpcr:classparents] = 'Mango\Component\Content\Model\StaticContent'))
    
	AND ISSAMENODE(e, [/channels/1/pages/about-us])) 
	AND (e.[phpcr:class] = 'Mango\Component\Content\Model\StaticContent' 
	OR e.[phpcr:classparents] = 'Mango\Component\Content\Model\StaticContent'))
```

**Comment by steffenbrem** [comment]
@dbu Do you know why the queries generated like this? It seems an issue with `DoctrinePHPCRBundle`.

**Comment by steffenbrem** [comment]
This issue is fixed if I add the following code to `Doctrine\ODM\PHPCR\Query\Builder\QueryBuilder`:

```php
public function __clone()
{
    $this->converter = clone $this->converter;
}
```

**Comment by sjonkeesse** [comment]
👁‍🗨

**Comment by steffenbrem** [comment]
I think we need to depend on master phpcr-odm, then this is fixed.

**Comment by steffenbrem** [comment]
@pjedrzejewski Should I submit a PR to make sure we use the latest `phpcr-odm`? Or do you want to wait till they tag a stable release?

**Comment by pjedrzejewski** [comment]
I am fine with requiring latest phpcr-odm right now and switching back to stable as soon as it is released. :) Go ahead @steffenbrem, thanks!

**Comment by steffenbrem** [comment]
@pjedrzejewski I've submitted a PR with the needed changes to fix this bug :+1:

**Comment by dbu** [comment]
i hope to tag 1.3.1 tomorrow. we need to hunt down some setup issues.

**Comment by pjedrzejewski** [comment]
Awesome, thanks @steffenbrem and @dbu!

**Comment by pjedrzejewski** [comment]
Menu support is removed.
