### ISSUE TITLE
Introduce code to Taxonomy

### ISSUE THREAD

**Issue by aramalipoor** [Sylius/Sylius#3760]
We're having some situation that if `Taxonomy`s had a unique `code` it would help us a lot. Do you think adding such field is good?

Our current issue is with our theme's default data fixtures, which a `code` on Taxonomy would help us a lot to offer a seamless, stable and bug-free experience for our users.

I would be happy to PR if you're agreed.

**Comment by pjedrzejewski** [comment]
We have code on Taxon right now, but yeah, would be good to add it to taxonomy too unless #3761 makes sense. :) Let's discuss it first before we work on this.

**Comment by michalmarcinkowski** [comment]
Closing as this will not be relevant after #3773 is merged :)
