### ISSUE TITLE
Remove Taxonomy entity in favor of Taxon entity

### ISSUE THREAD

**Issue by aramalipoor** [Sylius/Sylius#3761]
Having two entities has raised a few headaches for us, I'm not sure but it seems if we had only one entity e.g. `Taxon` and any taxon without a parent is simply root; a lot of those duplicates and headaches would go away. IIRC I saw a conversation about this somewhere in the issues!

I'm not sure why they are separated at all?
\cc @pjedrzejewski

**Comment by pjedrzejewski** [comment]
I implemented Taxonomy and Taxon inspired by Spree. I'd love to get rid of Taxonomy and just have a Taxon entity.

Some useful links:

* http://stackoverflow.com/questions/17427705/spree-why-there-is-a-taxonomy-and-a-taxon-model
* https://guides.spreecommerce.com/api/taxonomies.html
* https://guides.spreecommerce.com/user/configuring_taxonomies.html
* http://grokbase.com/t/gg/spree-user/1369paf863/taxon-vs-taxonomy
* https://github.com/spree/spree/blob/master/core/app/models/spree/taxon.rb

**Comment by pjedrzejewski** [comment]
It appears there is no reason to have Taxonomy and Taxon separated. :D That being said, I wonder how it plays out with Gedmo Tree extension. That would mean multiple roots support is required, which is the case but I hope it won't be that hard to change the current structure.

**Comment by aramalipoor** [comment]
That's great. I'll try to play around with it in my free time. We can also make `TaxonRepository` tree-aware if I could find the time to do Atlantic18/DoctrineExtensions#1493 too ;)
