### ISSUE TITLE
[Core] Deleted related resources still appear on order show page

### ISSUE THREAD

**Issue by cdaguerre** [Sylius/Sylius#3766]
Because the softdeletable filter is disabled [here](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Doctrine/ORM/OrderRepository.php#L67), deleted payments (and other related resources) still appear.
Why is disabled anyway?

**Comment by cdaguerre** [comment]
@pamil Are you sure this is a good idea?
It would for instance error for the [same reason you raised here].(https://github.com/Sylius/Sylius/issues/3065)

**Comment by cdaguerre** [comment]
@pamil Ahhhh sorry, didn't see you were just reenabling it...

**Comment by pjedrzejewski** [comment]
I think we should see everything that happened to the order, even if it is deleted, so it should stay this way. We want to get rid of softdeleteable anyway. Please reopen if you have anymore questions.

**Comment by pjedrzejewski** [comment]
@cdaguerre Thanks for reporting of course! :)
