### ISSUE TITLE
Create order at backend

### ISSUE THREAD

**Issue by mingxing** [Sylius/Sylius#3770]
Hi guys

Could we create backend order now? It display "Not implemented yet.".

Thank you
Simon

**Comment by pjedrzejewski** [comment]
Duplicate of https://github.com/Sylius/Sylius/issues/3688.

**Comment by pjedrzejewski** [comment]
@mingxing Please continue discussion in the issue I linked above. :) Thanks!

**Comment by synerskills** [comment]
Thank you a lot!
