### ISSUE TITLE
@pamil, why did you default DoctrineORMOutputWalker to true?

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#3775]
In your recent merged PR, in the Entity Repository:

```
-        return new Pagerfanta(new DoctrineORMAdapter($queryBuilder, true, false));
+        return new Pagerfanta(new DoctrineORMAdapter($queryBuilder, true, true));
```

This reverts a very explicit one-line change I merged a while ago in #3495.

Pagination on a million row table now back up to 60 seconds page load time.

I'm guessing you made this change for some reason, what was it? Is there a use-case where we do want OutputWalkers? I think the default should be false and only set to true where you really need it.

**Comment by pjedrzejewski** [comment]
Ouch, I totally forgot about this when merging the PR. I believe this was changed to the sake of Doctrine ORM 2.5 compatiblity. Right, @pamil?

@peteward For such large collections of resources, I was thinking about using ElasticSearch. With Grids implemented, we will implement ElasticSearch driver for Grid, so you would be able to use it for customers/products backend etc.

**Comment by peteward** [comment]
@pjedrzejewski, that's an interesting idea. I've been toying with the idea of pushing more data to Elasticsearch but it starts to snowball with the content you would end up pushing into it.

For us so far Customers is the main set of data we've migrated from our existing MySQL DB into our Sylius one, but we'll soon have the following all in the millions:

* Orders
* OrderItems
* OrderItemUnits
* Payments
* Shipments
* OrderReturns

Does it really make sense to duplicate all of this kind of data (and some of it gets very large - our current live DB is 15GB) into an alternative storage mechanism that must be synchronised? You're adding overhead of storage costs and an maintaining consistency between them. If you search for an entity through elasticsearch to then change it through MySQL, the changes really need to be reflected immediately when you get back to the grid. FosElastica can do this, but when there are complex relations involved it gets challenging (as we found with our project). I'm guessing you're talking about an alternative engine to MySQL? not introducing it as a requirement?

Anyway, this is slightly away from the point here. 

I can't see anything in DoctrineORM 2.5 that suggests this should be an issue, the only PR related supposedly fixes something that could have been an issue, not introducing one: https://github.com/doctrine/doctrine2/issues/3648

I think paginated queries against any size of dataset shouldn't be run with querywalkers active here, it's just that we can see the results very obviously in our project.

This isn't killing us because we've already worked around this call, but I spotted it whilst upgrading today and it looks wrong.

So it would be good to know the reasoning behind the change and see if there's another way around whatever problem this was trying to solve.

**Comment by pjedrzejewski** [comment]
@peteward My idea was to use it for products and customers but only for really small subset of data that is used in the grid view, only to search and browse them quickly. When you display a single customer etc. it would of course use the ORM storage. :) Anyway, idea for a bit later.

**Comment by peteward** [comment]
ping @pamil

**Comment by pamil** [comment]
@peteward Sorry for getting back to this issue so late, I had been writing a reply, but I've dive too deep into code and totally forget about it.

The point of that unfortunate change was to support Doctrine ORM >=2.5. It wasn't fixing the real issue, but I didn't realise it will come with so drastically changed performance.

I'll make an Sylius issue about the real issue and link to it here in a moment.

**Comment by pamil** [comment]
Can be closed.
