### ISSUE TITLE
Auto translations with crowdin - not running ?

### ISSUE THREAD

**Issue by nakashu** [Sylius/Sylius#3789]
Just want to ask if the auto updater works ? #3433

There are no new translations in crowdin since merge of that PR, and quite a few new translation keys where added to master since then.

thanks

**Comment by michalmarcinkowski** [comment]
The auto sync is not running, we will try to fix this soon.

**Comment by michalmarcinkowski** [comment]
It should work now (see #3904). I believe it runs update daily.

/cc @pamil

**Comment by nakashu** [comment]
i was watching SyliusBot messages last few days. 
Made translation on crowdin today. So I will check tomorrow if it worked, and will close the issue afterwards

Thanks.

**Comment by pamil** [comment]
@michalmarcinkowski it is set to run every Saturday at ~15:30 now. I'll generate extra one tomorrow morning just before I'll start the translation keys renaming.

**Comment by nakashu** [comment]
@pamil Seems the auto update still got some problems. Last update was 16 days ago #4038.
thanks
