### ISSUE TITLE
Data import and export

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#379]

**Comment by mojzis** [comment]
any  thoughts about which way sylius will go ? https://github.com/ddeboer/data-import or akeneo ?

**Comment by BitOne** [comment]
It's definitely two absolutely different things (Akeneo vs ddeboer/data-import). Akeneo is a full fledge standalone application with import/export facilities and UI to enrich, translate products information, with a big emphasize on data quality checking.

ddeboer/data-import is more about reading and converting data format. In fact ddeboer/data-import could be used in Akeneo connectors.

Another thing we were talking about is the akeneo/BatchBundle (https://github.com/akeneo/BatchBundle). This provides import and export infrastructure with monitoring. It has concepts close to ETL and could be used with ddeboer/data-import as well, as it's more on the framework side (it define the import/export execution flow whereas ddeboer/data-import is more about concrete format manipulation).

If you don't need the full Akeneo application, a interesting solution would BatchBundle+ddeboer/data-import to manage your import and export.

**Comment by michalmarcinkowski** [comment]
In this PR https://github.com/Sylius/Sylius/pull/3156 you will find the initial version of data import and export for Sylius.

**Comment by olegsv** [comment]
Are there any news regarding the integration of batch import functionality into Sylius?

**Comment by Zales0123** [comment]
As far as I know there are no plans for now to implement such a functionality to _Sylius_, at least until release of stable version. Of course as we already have possibility to [create plugins for Sylius](http://docs.sylius.org/en/latest/plugins/creating-plugin.html) there is a high possibility that plugin with such a functionality would be created ;)

**Comment by bitbager** [comment]
Is this still in the backlog or maybe has anybody implemented it and would like to share it with OpenSource? 😢

**Comment by czende** [comment]
This would be great! Any update on this?

**Comment by kochen** [comment]
I have a small Order Export solution I plan to release as a plugin as soon as time allows.

**Comment by bitbager** [comment]
Perfect. Has anyone thought about configurable product information export?

**Comment by czende** [comment]
@bitbager I'm working on import and export commands, but its really complicated, because of multiple relations and possibilities. For now I have just structure for exporting simple products and their relations (taxons, attributes, shippings, images paths etc) into simple CSV file.

**Comment by diimpp** [comment]
https://github.com/FriendsOfSylius/SyliusImportExportPlugin

There is this new cool plugin, which is based on [portphp/portphp](https://github.com/portphp/portphp) (Previously known as as [ddeboer/data-import](https://github.com/ddeboer/data-import))

**Comment by lchrusciel** [comment]
The issue can be closed then, can't it?
