### ISSUE TITLE
No route found for "GET /p/"

### ISSUE THREAD

**Issue by jelti** [Sylius/Sylius#3793]
Hello guys,
i've just installed a fresh version of sylius/sylius-standard (using composer -s dev)
Unfortunately, when i create a new product in the administration part and try to display it on the visitor side (homepage of the site), i get an exception
 NotFoundHttpException: No route found for "GET /p/"

could you help me please?
thanks in advance
M JELTI

**Comment by pjedrzejewski** [comment]
WebBundle is gone, please reopen if still in trouble.
