### ISSUE TITLE
[RFC] Translation keys and their location

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#3794]
Hello folks!

As we are approaching completely new interface: SyliusUiBundle, SyliusAdminBundle and SyliusShopBundle, we need to finalize the conventions for translation keys.

@pamil Finished working on auto-sync from Crowdin and hopefully soon we will have a converter working, which will help us preserving a lot of existing keys, so do not worry about losing all translations. Some will be lost (or just removed) in the process, that's for sure, but we have figured out a nice way to keep a lot of them.

### Keys

I'd like to propose following conventions for the keys:

* Form labels (``messages`` domain):

``sylius.form.<form_type_name_without_sylius_prefix>.<field_name>``, which is inline with current translation keys. For example:

``sylius.form.product.name``
``sylius.form.tax_rate.zone``

Only change I'd do here is the configuration forms for all promotions, shipping calculators etc. Instead of following the convention above, they would simply be:

``sylius.form.configuration.<field_name>``.

For example: ``sylius.form.configuration.amount`` or ``sylius.form.configuration.zone``.

* Validation (``validators`` domain):

``sylius.<resource_name>.<field_name>.<constraint_name>`` for property constraints.
``sylius.<resource_name>.<constraint_name>`` for class constraints.

For example:

``sylius.product.name.not_blank``
``sylius.tax_rate.zone.not_blank``
``sylius.channel.enabled``

This is pretty much inline with what we have now. Maybe we will need to fix some of class constraint.

* Flashes (``flashes`` domain):

Pretty much the same as we have currently:

``sylius.<resource_name>.<action_name>`` for success flashes.
``sylius.<resource_name>.<custom_name>`` for other flashes.

* User Interface:

This is where revolution happens. :D We currently have a pseudo  separation of frontend and backend. I think that is silly. There will be phrases shared by both and there is really no point in  translating them twice. I think we should have the simplest approach, where we use translation keys which are pretty much exactly the phrase to translate. To illustrate it:

Instead of ``sylius.backend.header.tax_category`` we will have just ``sylius.ui.tax_categories`` to display "Tax Categories``.

Instead of ``sylius.frontend.account_header_dashboard`` we will have just ``sylius.ui.account``. There will be no "lower levels" so no ``sylius.ui.account.banana`` or anything like that.

Reasoning:

* Simpler translation keys
* Much much less keys and no duplication
* Very hard to come up with generic keys that match context
* Easier to change UI, you don't need to rework translation keys to match the context

### Location of the keys

Form and validation translations go to the bundles that use them, that's it. So if there is "zone" field on TaxRate in Core, it goes to core, but "name" field that is from component, goes to TaxationBundle. Simple as that.

Regarding location of "ui" translations:

They go to SyliusUiBundle. I know this is not perfect but I do not see a better solution atm. So:

``sylius.ui.yes`` and ``sylius.ui.no`` goes to SyliusUiBundle but ``sylius.ui.tax_categories`` goes too. Not perfect because SyliusUiBundle is supposed to be generic and not coupled to Sylius and it will be in every aspect but will have some keys in it. I'd like to avoid creating something like ``SyliusTranslationsBundle`` or ``SyliusTranslationMessagesBundle`` or ``SyliusDictionaryBundle`` unless you think it is a good idea that would make SyliusUiBundle nicer.

It is late and I may have missed something but let me hear your thoughts. We are going to work on templates very soon so we should have this figured out and documented somewhere in the docs.

**Comment by gperdomor** [comment]
<blockquote><code>sylius.ui.yes</code> and <code>sylius.ui.no</code> goes to SyliusUiBundle</blockquote>
Good for me, that labels are generic.

<blockquote>but  <code>sylius.ui.tax_categories</code> goes too</blockquote>
This is not generic, so i think in this case, should be inside <code>TaxBundle</code>

**Comment by peteward** [comment]
Sounds good.

I think you will find exceptions to the idea of having no sublevels, but it's a good starting principle to simplify the structure. I think tying everything together admin and frontend will not always work but you can handle by exception.
