### ISSUE TITLE
[Attribute] Adding a "checkbox" attribute throws an exception

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#3798]
```
A cycle was detected. Listeners to the PRE_SET_DATA event must not call setData(). You should call setData() on the FormEvent object instead.
500 Internal Server Error - RuntimeException
```

Steps to reproduce:

1. Create a new attribute of type "checkbox", ``is_promoted`` for example.
2. Fill name and price for the product, add the attribute.
3. Submit the form.

/cc @Zales0123

**Comment by Lowlo** [comment]
Remove the preSubmit event from BuildAttributeValueFormSubscriber fix this error, but i have not tested it more deeply.

**Comment by Zales0123** [comment]
I think it can be fixed after https://github.com/Sylius/Sylius/pull/3825 merging ;)

**Comment by michalmarcinkowski** [comment]
True :+1:
