### ISSUE TITLE
Rest api does not translate

### ISSUE THREAD

**Issue by tuxado** [Sylius/Sylius#3799]
Hello, i have the api does not translate entities i clear the cache but the same result stile returned any idea how to resolve thiss?

tkhx

"_embedded": {
"items": [1]
0:  {
"translations": {
"en_US": {
"locale": "en_US"
"id": 1
"name": "product"
"slug": "product"
"description": "product"
"short_description": "product"
}
}
"current_locale": "en_US"
"fallback_locale": "en_US"
"id": 1
"created_at": "2016-01-01T09:12:51+0400"
"updated_at": "2016-01-01T09:13:12+0400"
}
}

**Comment by pjedrzejewski** [comment]
Could you tell me what is wrong in this example? Seems like you have only one translation for the product. Do you need anything more?

**Comment by tuxado** [comment]
the "translations" field it should be name and description i suspect the default locale that not be set on the api i will see that another time

**Comment by pjedrzejewski** [comment]
I clearly see "name" and "description" under ``translations -> en_US`` path. Please reopen if you still have any issue with the translation response. Thanks!

**Comment by tuxado** [comment]
Hi , In  thé API docs thé name and description are under thé item  but on my case thé name are under translation i dont knoW if there are something wrong with thé mapping fields

**Comment by michalmarcinkowski** [comment]
@tuxado your response is correct. We have translatable name and description right now, so that's why you have these fields nested.

**Comment by tuxado** [comment]
Hi Michal

Then we should write a new yml configuration for jms serializer to set thé translation field directelly under thé item object and not under translations array because ot seem thé jms ignore thé mapping of fields on dependency configuration file

Thé new jms sérialiser for product i change thé description and name lines:

Sylius\Component\Product\Model\Product:
    exclusion_policy: ALL
    xml_root_name: product
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
        attributes:
            expose: true
            max_depth: 2
        createdAt:
            expose: true
            type: DateTime
        updatedAt:
            expose: true
            type: DateTime
    virtual_properties:
        getVariants:
            serialized_name: variants
    virtual_properties:
        getName:
            serialized_name: name
    virtual_properties:
        getDescription:
            serialized_name: description


 but i still tell my self that there is something wrong on thé jms or on thé mapping

**Comment by michalmarcinkowski** [comment]
That is how the translations work right now, we will work on making the responses more API friendly in the nearest future.

**Comment by tuxado** [comment]
Tkx for this clarification then i will use thé virtual_properties as a hack for the translation with the API and the core 0.16 and waiting thé final release of 0.16 to upgrade thé all fonctionalities
