### ISSUE TITLE
Class "model" is not configured for resource

### ISSUE THREAD

**Issue by tuxado** [Sylius/Sylius#3811]
hi, i configure a new controller without using model that isn't required in my case but i got this error message it seem that the ressource not authorize configuration like :

						->arrayNode('some_controller')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->arrayNode('classes')
                                    ->addDefaultsIfNotSet()
                                    ->children()
								
										->scalarNode('controller')->defaultValue('Sylius\Bundle\SomeBundle\Controller\SomeController')->end()
									->end()
								->end()
                                ->arrayNode('validation_groups')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->arrayNode('default')
                                            ->prototype('scalar')->end()
                                            ->defaultValue(array('sylius'))
                                            ->cannotBeEmpty()
                                        ->end()
                                    ->end()
                                ->end()
							->end()
						->end()
						

the error :

Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Class "model" is not configured for resource "sylius.some_controller".' in ...\Sylius\Component\Resource\Metadata\Metadata.php:126 Stack trace: #0 ...\Sylius\Bundle\ResourceBundle\DependencyInjection\Driver\Doctrine\DoctrineORMDriver.php(44): Sylius\Component\Resource\Metadata\Metadata->getClass('model') #1 ...\Sylius\Bundle\ResourceBundle\DependencyInjection\Driver\AbstractDriver.php(34): Sylius\Bundle\ResourceBundle\DependencyInjection\Driver\Doctrine\DoctrineORMDriver->addRepository(Object(Symfony\Component\DependencyInjection\ContainerBuilder), Object(Sylius\Component\Resource\Metadata\Metadata)) #2 ...\Sylius\Bundle\ResourceBundle\DependencyInjection\Extension\AbstractResourceExtension.php(37): Sylius\Bundle\ResourceBundle\DependencyInjection\Driver\AbstractDriver- in ...\Sylius\Component\Resource\Metadata\Metadata.php on line 126 

any idea how fix that? tkx

**Comment by pjedrzejewski** [comment]
Model should be always required. There is no resource without model.

1. Why you define a whole configuration structure? You don't need to do that.
2. What will your controller do if it is not associated with a resource? If you need a simple controller, not related to SyliusResourceBundle functionality, then you can just go standard Symfony way, use controller notation or register it as a service etc.

**Comment by tuxado** [comment]
hi, pjedrzejewski  

i try to upgrade to 0.16 and i add field using two template for product, the controler are used with ajax to switch between the two templates in the product form in this case we dont require any model only choise field that switch the templates and i need to call the controller with route it work in the 0.15 but stuk in 0.16..

Ah if i untherstand if the controller not use a rescource we will not able to call the controller with sylius.controller.somecontroller on the route and all the app as sylius 0.15 and we will call it with the full path as symfony do?

**Comment by pjedrzejewski** [comment]
I am not sure I understand your use-case. Please open a question on StackOverflow it it's still a problem: http://stackoverflow.com/questions/tagged/sylius You should just create a separate controller and avoid overriding/using configuration tree.
