### ISSUE TITLE
Access to user list from API is denied

### ISSUE THREAD

**Issue by starspire** [Sylius/Sylius#3815]
When accesing to user list via API from user api@example.com (from fixtures) 403 error denied is thrown. Adding addition roles and permissions don't help. Accessing other users actions also denied. Other routes like products work correctly.

**Comment by pjedrzejewski** [comment]
Thanks for reporting!

**Comment by starspire** [comment]
@pjedrzejewski I found why this bug appears. This is caused by splitting user into user and customers and there are only permision 'sylius.customer.index' and no 'sylius.user.index'. Moreover there aren't api actions listing customers (I think this would be enough because we need customer to create cart not a user). I can fix it, say me only which way shall I follow (creating new routes for customers or displaying customers on users route). Maybe there is a need to do both: create new routes for customers and fixing permissions for users.

**Comment by michalmarcinkowski** [comment]
@starspire definitely permissions bug. We can do both, add permissions for users actions and also expose customer routes for API (this can be useful).

**Comment by lchrusciel** [comment]
Will be fixed in #4009
