### ISSUE TITLE
Clean up ResourceBundle forms

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#3816]
Helloes!

Currently we have some generic forms in ResourceBundle:
- ResourceChoiceType - https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Form/Type/ResourceChoiceType.php, which is used for all generated forms `sylius_tax_category_choice` etc.

With my refactoring, you can use it also for custom resources. The implementation is not good though, because we inject the driver and full name and there we decide about the part.

It should be `DriverInterface` implementation responsibility to create appropriate class and inject correct stuff.

So [here](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/AbstractDriver.php#L148) we should inject correct values already and `MetadataInterface` to generate the form name etc.

This change can be left for later because it works fine right now. Other forms are a bit worse:

I won't even dig into what is going on here - https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/DependencyInjection/Compiler/ObjectToIdentifierServicePass.php but this CompilerPass should be removed.

Let's start from implementing the simplest one:

`ResourceToIdentifierType` with `ResourceToIdentifierTransformer` (current implementation is fine, let's just rename it from ObjectToIdentifier). It should be generated just like the `choice` form type for every resource that has it defined. So if `sylius.product` resource has `to_identifier` configuration node defined, then it should get `sylius_product_to_identifier` form type.

In the end, I'd like to have (if needed) following form type available for each resource:

`sylius_tax_category`
`sylius_tax_category_choice`
`sylius_tax_category_to_identifier`
`sylius_tax_category_to_hidden_identifier`
`sylius_tax_category_autocomplete` - This is much needed and would use the one above.

The good news is that @tuka217 will work on these with me in the coming weeks. :) Any help/ideas/suggestions appreciated!

**Comment by bendavies** [comment]
You should consider the 2.8 deprecation of form type names in this refactor.
> Instead of referencing types by name, you should reference them by their fully-qualified class name (FQCN) instead

see https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md for more info.

**Comment by pjedrzejewski** [comment]
Yeah and this is a big problem for us. :/ I started discussion here - https://twitter.com/pjedrzejewski/status/673838287312654336.
