### ISSUE TITLE
CartEvent isFresh() is deprecated

### ISSUE THREAD

**Issue by flajos** [Sylius/Sylius#3820]
Sylius\Component\Cart\Event::isFresh() method is deprecated.
In the past it was used to recalculate the cart totals: 

    if ($event->isFresh()) {		
        $this->refreshCart($cart);		
    }

The checking for the isFresh() values were removed in commit 93218a3206fea527cba1846f02485796cf572455. The refreshing of the cart is solved now with the RefreshCartListener which listens to SyliusCartEvents::CART_CHANGE event.

The Sylius\Component\Cart\Event::isFresh() method is not checked currently anywhere. It is only set in the CartController and CartItemController as a remnant of the old code. As it is not used it can be removed.

**Comment by michalmarcinkowski** [comment]
Fixed in #3821
