### ISSUE TITLE
Tax category in product variant not in product

### ISSUE THREAD

**Issue by hubikz** [Sylius/Sylius#3829]
I can find scenario when product variants have different tax rates.

In Poland audiobooks on CD have 5% VAT rate and audiobooks without CD (only file for download) have 23% VAT rate.

So in this case You can't add some book with variants as a different media type.

What do You think about this change?

**Comment by a1ku** [comment]
+1. Totally valid scenario.

**Comment by pjedrzejewski** [comment]
Sounds reasonable to me, can't remember the reasoning behind putting it on the product instead of variant.

**Comment by pjedrzejewski** [comment]
Implemented in #3915, thanks for suggestion!
