### ISSUE TITLE
Is it possible to use translations via annotations?

### ISSUE THREAD

**Issue by ufik** [Sylius/Sylius#3830]
I have a table, where I would like to use translations from sylius I am extending my table with AbstractTranslatable and I have as well table with translations.

```
Option extends AbstractTranslatable

class OptionTranslation extends AbstractTranslation
```

I can see that, in other tables from sylius it will automatically create `translatable_id` and `locale` columns, but in my case no. What am I missing?

**Comment by pjedrzejewski** [comment]
Is your entity registered as a Resource under ``sylius_resource``?

**Comment by ufik** [comment]
No, it's not, is there any documentation about this topic?

So it's necessary to register this entity as resource, any example? I have to say, that I am creating new bundle and it's just bare symfony2 bundle, I didn't use any approach from sylius as I didn't find much about it in docs.

**Comment by ufik** [comment]
Ok, I followed http://docs.sylius.org/en/latest/bundles/SyliusResourceBundle/configuration.html and it's working. Sorry about that, closing issue.

**Comment by pjedrzejewski** [comment]
@ufik No worries, thanks for closing the issue! :+1:
