### ISSUE TITLE
Shipping STATE_BACKORDERED not available on edit page form

### ISSUE THREAD

**Issue by senicar** [Sylius/Sylius#3837]
I'm not sure if this is valid issue but from what i can tell there is no "Backordered" shipping state available in shipping edit form?

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ShippingBundle/Form/Type/ShipmentType.php#L31

but it is defined in

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Shipping/Model/ShipmentInterface.php#L27

If shipment was marked as "backordered" automatically on checkout, it will be resetted with "checkout" by default if I go in the shipping edit mode - to add/update tracking number for example.

Same would go for STATE_ONHOLD.

regards
Senicar

**Comment by pjedrzejewski** [comment]
We should remove all the forms for editing state. All should happen through transitions so we will be getting rid of that soon. Instead you will be able to apply transitions from the UI and correct things will happen. :)

**Comment by senicar** [comment]
Ok

until then however, I still need to allow the administrator/editor to update the shipping details. I plan to simply add *backordered* and *on hold* choices to the form. Is this a relatively safe solution or where this two option omitted because of certain edge-case scenarios going wrong?

Thanks

**Comment by michalmarcinkowski** [comment]
As @pjedrzejewski wrote, we should apply state machine transitions to manage states. All states have it's transitions available in the UI already.
