### ISSUE TITLE
[UserBundle] Shouldn't depend on sylius-cart !!

### ISSUE THREAD

**Issue by liverbool** [Sylius/Sylius#3845]
I think `sylius/user-bundle` should not require `sylius/cart` and https://github.com/Sylius/SyliusUserBundle/blob/df166511e801a47d9cdc294e768097291beea15e/EventListener/CustomerAwareListener.php
should move to `core-bundle` instead.

ping @pjedrzejewski

**Comment by pjedrzejewski** [comment]
Yes, we are well aware of that and this will be removed soon, but we can't do that quickly enough, so for now it's better to make the bundle installable this way. We will very soon remove that listener.
