### ISSUE TITLE
Comparing products and add a favorite?

### ISSUE THREAD

**Issue by Avtonom** [Sylius/Sylius#3846]
Do comparing products features, and add a favorite? If not, it is planned to add?

**Comment by michalmarcinkowski** [comment]
Hi @Avtonom, these features are not implemented yet. We're working hard on Core stabilization and 1.0 release, so extra features are not our focus right now and it's more like a future effort.

**Comment by Avtonom** [comment]
Thanks for the quick response! Feedback is very important for the beginning of the project.
I could do this.
Please give some advice how I implement this functionality.

**Comment by Avtonom** [comment]
@michalmarcinkowski ?

**Comment by pjedrzejewski** [comment]
Hello @Avtonom! It's great that you want to help us and I'd love to have this functionality in core, but we are now focusing on getting the last must-have features merged and stabilization of the whole code base. It's tough to decide which feature goes in to the core and which not, there is a lot of pressure from many sides. :) But in case of this feature, I am sure it can be implemented as a Community bundle, future plugin or maybe even in core, but after 1.0. I hope you understand. :) 

That being said, I am pretty sure it will be quite easy to implement it as a custom feature just for your project. Or maybe even a Symfony2 bundle that extends Sylius with this functionality!
