### ISSUE TITLE
Rename description field to label on Adjustment

### ISSUE THREAD

**Issue by michalmarcinkowski** [Sylius/Sylius#3849]
The `Adjustment` model has `description` field which is used as a label right now i.e. by setting its value to "EU VAT (23%)". IMO we should add a separate `label` field which will be used for displaying and adjustments aggregation purposes (get all VAT 7% adjustments or get all VAT 23% adjustments) and leave `description` for additional info i.e. "Tax refund on item return (11.01.2016)".

**Comment by peteward** [comment]
Sounds like duplication to me.

Just looking at your example:
* The fact that it's a `refund` (also the were `reversal` has been suggested) should be identified by a flag of some sort - easy for querying and in models.
* It would therefore still be a TAX type adjustment
* The dates are already stored.

There's nothing in your description that couldn't be pulled already.

This table is quite likely to be the largest permanent table in the Sylius DB, we should avoid growing it anymore than is absolutely necessary. For us this table will launch at > 10,000,000 rows.

**Comment by michalmarcinkowski** [comment]
I thought that leaving a `description` will give us flexibility to add some additional info about the adjustment, but I'm convinced that it's redundant. How about renaming the `description` field to `label`? I find it more appropriate looking at the way we use it right now.

**Comment by peteward** [comment]
yes that does seem more suitable.

It's funny because there used to be a `$label` field that we changed to `$type`, but bringing label back to replace description seems more accurate.

**Comment by michalmarcinkowski** [comment]
I'm glad we agree on that :)

**Comment by pjedrzejewski** [comment]
Changed in #3880.
