### ISSUE TITLE
The form's view data is expected to be of type scalar, array or an instance of \ArrayAccess, but is an instance of class Proxies\__CG__\Sylius\Component\Payment\Model\PaymentMethod

### ISSUE THREAD

**Issue by antonioperic** [Sylius/Sylius#3856]
Flow:
- add item to cart
- go to cart
- go to checkout
- enter address
- select shipping method
- select payment method
- go to review site
- go anywhere on site and start flow again on payment method part it brokes 

version 014

The form's view data is expected to be of type scalar, array or an instance of \ArrayAccess, but is an instance of class Proxies\__CG__\Sylius\Component\Payment\Model\PaymentMethod. You can avoid this error by setting the "data_class" option to "Proxies\__CG__\Sylius\Component\Payment\Model\PaymentMethod" or by adding a view transformer that transforms an instance of class Proxies\__CG__\Sylius\Component\Payment\Model\PaymentMethod to scalar, array or an instance of \ArrayAccess. 

When payment method is set and i am trying to go from shipping step to payment again

**Comment by michalmarcinkowski** [comment]
Looks like same issue as with ShippingMethod (#2979). The checkout will be reworked soon, so we will hopefully get rid of all issues :)

**Comment by michalmarcinkowski** [comment]
This should be resolved already.
