### ISSUE TITLE
Adding new on-hand inventory to an out-of-stock product doesn't update order shipping state

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#3857]
When you have an order that has inventory units that are in the state `backordered` and you add new on-hand to the product variant (stockable). The shipping state of those inventory units (including the order) are still on `backordered`. Shouldn't it first fill all the backorders of that product variant and then update the `onHand` with the remaining inventory count?

> New products created in the system can be given a starting “on hand” inventory level. You can subsequently set new inventory levels and the correct things will happen, e.g. adding new on-hand inventory to an out-of-stock product that has some backorders will first fill the backorders then update the product with the remaining inventory count.
> - https://guides.spreecommerce.com/developer/inventory.html (thirth paragraph)

### Expected behaviour
When I add new inventory to the out-of-stock product variant, then all orders that have backordered inventory units should then be filled first and then the remaining inventory count should be the new `onHand` value.

**Comment by sjonkeesse** [comment]
I would like to see a flowchart.

**Comment by sjonkeesse** [comment]
If it is been done automatically there is no control to ship some orders before others. 
Lets say you have two orders:
order 1 with 4x variant 1 - all in backorder (ordered first)
order 2 with 3x variant 1 - all in backorder (ordered last)
Next there are 3 new variants (1) coming in for stock. Than in most cases I would rather ship order 2 first to have less orders open.
WDYT @steffenbrem

**Comment by michalmarcinkowski** [comment]
Closing as support for backorders was removed.
