### ISSUE TITLE
[Promotions] Can't use "add_product" action on promotion, error: "This value should be of type numeric."

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#3863]
When you edit or create a new promotion and use the `add_product` action type and select a product variant you will get the validation error `This value should be of type numeric.`.

It seems that the `DataTransformer` is not transforming the way it should transform it. In the demo of Sylius it is working, but on the latest installation it is broken. @pjedrzejewski Do you know what is different on the demo sylius vs the master repo?

**Comment by steffenbrem** [comment]
I've switched the code that is in the `transform` method to the `reverseTransform` and vice versa and the bug was resolved. It seems that somehow Symfony changed the way the data transformers work?

**Comment by flajos** [comment]
Yep, it's solved in fc345d670ff0eb900c2591d7a3f1e944de16f6fd

**Comment by michalmarcinkowski** [comment]
Closing then. Lajos thanks for confirming! 👍
