### ISSUE TITLE
[TranslationBundle] AbstractTranslatable translate method behaves incorrectly

### ISSUE THREAD

**Issue by Sp0ng3b0b** [Sylius/Sylius#3864]
I am using Resource and Translationbundle in a small project. I was trying to get the current url in other languages. Therefor im looping to all locales and trying to call 
  $translatableEntity->translate($locale)->getSlug()

It seems that this doesnt work as only one translation is loaded (the current locale)

**Comment by pjedrzejewski** [comment]
Could you give us exact steps to reproduce?

**Comment by Sp0ng3b0b** [comment]
Im going to post the exact steps this evening. Maybe i can find the problem, i didnt look too much for it yet.

**Comment by pjedrzejewski** [comment]
@Sp0ng3b0b Thanks! :)

**Comment by michalmarcinkowski** [comment]
This should work fine now.
