### ISSUE TITLE
It is possible to add variant to cart withou choosing any variant

### ISSUE THREAD

**Issue by antonioperic** [Sylius/Sylius#3865]
I tried to add variant to cart without picking any option variants and that works. There should be some validation for this on backend not just required in frontend

http://take.ms/7brGp

**Comment by antonioperic** [comment]
FIxed by #3867

**Comment by pjedrzejewski** [comment]
Thanks for reporting and a quick fix! :+1:

**Comment by antonioperic** [comment]
@pjedrzejewski :+1:
