### ISSUE TITLE
Add new country form validation - wrong values in dropdown

### ISSUE THREAD

**Issue by axelvnk** [Sylius/Sylius#3869]
<img width="1429" alt="screen shot 2016-01-14 at 10 25 22" src="https://cloud.githubusercontent.com/assets/6803540/12320503/48fe3cfe-baa9-11e5-8be0-dd9d3a2cc62a.png">

The validation on the country menu states that the value must be exactly 2 characters long. So when the form is submitted after choosing an ISO code, you get a validation error.

When looking at the HTML, you can see that the country name is inside the value attribute and the ISO code is inside the body of the option element. I think these two should be switched. It'll be easier to find a country in the dropdown too. Not sure if the list is already sorted by country name. If not we should do so.

I will solve this issue myself by the way.

**Comment by pjedrzejewski** [comment]
Will be fixed in #3696.

**Comment by pjedrzejewski** [comment]
Actually, this is most likely a BC break in Symfony. Introduced in 2.7.8. It used to be the other way around - code was the value and not label... in the ``locale`` and ``country`` choice types. :/

**Comment by michalmarcinkowski** [comment]
Fixed in #3982
