### ISSUE TITLE
[Bug] You cannot patch channels aware resources, it won't update the channels collection

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#3896]
When you use the API to `PATCH` for example a promotion or product, which has a has many relationship with `channels`, it currently fails to update the channels of a product.

The cause of this is because `expanded` is set to `true` on most of the `sylius_channel_choice` form fields.

This is working perfectly fine:

``` php
$builder
    ->add('channels', 'sylius_channel_choice', array(
        'multiple'    => true,
        'label'       => 'sylius.form.promotion.channels',
    ))
;
```

This will break when you `PATCH` a product or promotion (the channels will remain untouched):

``` php
$builder
    ->add('channels', 'sylius_channel_choice', array(
        'multiple'    => true,
        'expanded'    => true,
        'label'       => 'sylius.form.promotion.channels',
    ))
;
```

> Note that you can add new channels with `expanded` set to `true`. The issue only appears to be when you delete some from the collection.

Anyone knows why the bug is resolved when leaving out the `expanded` option?

**Comment by pjedrzejewski** [comment]
I believe it is because expanded & multiple both set to true are checkboxes and with expanded set to false it is a multi select and can be that it takes a different input, I am not sure. We should have API specific forms for such cases I think. I'd need to verify my theory or you can just call it with a PUT request in both cases. I am pretty sure you will get an error which will explain why it works. (missing or extra fields)

**Comment by steffenbrem** [comment]
@pjedrzejewski Not sure if it might be useful, but I fixed it for me to globally force the `expanded` option to `false` through a normalizer:

```php
/**
 * ResourceChoiceType
 *
 * @author Steffen Brem <steffenbrem@gmail.com>
 */
class ResourceChoiceTypeExtension extends AbstractTypeExtension
{
    /**
     * @inheritDoc
     */
    public function getExtendedType()
    {
        return ResourceChoiceType::class;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        // force choice fields to never be expanded, this causes issues.
        // see the following issue for more details: https://github.com/Sylius/Sylius/issues/3896
        $resolver->setNormalizer('expanded', function() {
            return false;
        });
    }
}
```

**Comment by steffenbrem** [comment]
Is this still an issue?

**Comment by michalmarcinkowski** [comment]
I think it's not. Please reopen if still relevant.
