### ISSUE TITLE
Error when creating a imagine block

### ISSUE THREAD

**Issue by pfwd** [Sylius/Sylius#3897]
Login to admin area
Click Blocks under Content
Click Imagine Block
Click Create Imagine Block
Notice error
When doing this locally I get this error on Dev:

Catchable Fatal Error: Argument 3 passed to Sylius\Bundle\ContentBundle\Form\Type\ImagineBlockType::__construct() must be an instance of Liip\ImagineBundle\Imagine\Filter\FilterConfiguration, none given, called in /app/cache/dev/appDevDebugProjectContainer.php on line 12323 and defined

This can be replicated on the demo site

**Comment by lighta971** [comment]
Me too after updating 0.16-dev.
The Bundle/ContentBundle/Resources/config/services.xml file disapeared.

**Comment by pjedrzejewski** [comment]
Fixed in #3900.

**Comment by pjedrzejewski** [comment]
Thanks for the report!
