### ISSUE TITLE
Docs links in individual components are broken

### ISSUE THREAD

**Issue by djmattyg007** [Sylius/Sylius#3898]
I've only checked the User and Pricing components, but if they're anything to go by, all of the links to docs.sylius.org in the readme files for individual components are all 404ing.

**Comment by michalmarcinkowski** [comment]
The links are invalid. Correct links should be [User](http://docs.sylius.org/en/latest/components/User/index.html) and [Pricing](http://docs.sylius.org/en/latest/components/Pricing/index.html).
