### ISSUE TITLE
[UI] Admin UI responsive issue

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius#3899]
On 13" display with 2560 x 1440 resolution admin looks like this:

![sylius dashboard - chromium_066](https://cloud.githubusercontent.com/assets/208957/12371838/2c0b5e80-bc41-11e5-8703-d9e0b35d0508.png)

With zoom level of 90% it looks better:

![sylius dashboard - chromium_067](https://cloud.githubusercontent.com/assets/208957/12371837/2c07e3fe-bc41-11e5-8017-632c06e0a5e9.png)

Maybe this should be tweaked in CSS.

Chromium 47.0.2526.106 Ubuntu 15.10 (64-bit).

**Comment by pjedrzejewski** [comment]
I don't think we want to spend too much time on this UI, see #3646.

**Comment by umpirsky** [comment]
@pjedrzejewski OK, just a heads up. It is a minor issue, I thought it is quick CSS fix.
