### ISSUE TITLE
run behat test failed 

### ISSUE THREAD

**Issue by superjavason** [Sylius/Sylius#390]
when i run behat test , i got `PHP Fatal error:  Maximum function nesting level of '100' reached, aborting!`, can anyone tell me how to fix it? thanks

``` bash
─[0] <git:(master✱)> ./bin/behat                                    
@addressing
Feature: Countries and provinces
    In order to create tax and shipping zones
    As a store owner
    I want to be able to manage countries and their provinces

  Background:                             # features/backend/countries.feature:7
PHP Fatal error:  Maximum function nesting level of '100' reached, aborting! in /Users/superjavason/myworks/sylius/vendor/symfony/symfony/src/Symfony/Component/Routing/Matcher/Dumper/DumperCollection.php on line 109
```

**Comment by sampart** [comment]
Do you have any more information about why behat and xdebug conflict in this way?  In particular, I'm wondering whether there's another solution other than disabling xdebug.

**Comment by mabl0** [comment]
You can set `xdebug.max_nesting_level=1000` in /etc/php5/conf.d/20-xdebug.ini.
This is not specific to behat as some console commands can trigger this error too.
