### ISSUE TITLE
Created a new Entity with sylius_image 

### ISSUE THREAD

**Issue by mingxing** [Sylius/Sylius#3901]
Hi guys

I created a new entity with a form, I tried to learn the progress of product_variant_image, luckily I have almost done.
However, when I want to edit the product, I got an error:
```
The form's view data is expected to be an instance of class Sylius\Component\Core\Model\ProductReviewImage, but is an instance of class Sylius\Component\Core\Model\ProductVariantImage. You can avoid this error by setting the "data_class" option to null or by adding a view transformer that transforms an instance of class Sylius\Component\Core\Model\ProductVariantImage to an instance of Sylius\Component\Core\Model\ProductReviewImage.
```
I think the problem is that, there is only one service for sylius_image in form.xml:
```
<service id="sylius.form.type.image" class="%sylius.form.type.image.class%">
            <argument>%sylius.model.product_variant_image.class%</argument>
            <tag name="form.type" alias="sylius_image" />
 </service>
```
How can I create another one? Do you have some suggestion?

By the way, in the form type, I added:
```
->add('images', 'collection', array(
                'type'         => 'sylius_image',
                'allow_add'    => true,
                'allow_delete' => true,
                'by_reference' => false,
                'label'        => 'sylius.form.review.images'
            ))
```
Best Regards
Simon

**Comment by okwinza** [comment]
See #3843 for how to register your custom form type

**Comment by mingxing** [comment]
Hi Okwinza

Thanks for your guide. However I am a bit confused that the form type is using the same %sylius.form.type.image.class% like product image.

Do I need create a new ImageType?

Best Regards
Simon

**Comment by mingxing** [comment]
Got it, thank you!

**Comment by axelvnk** [comment]
It seems weird to me that by default the data class of the sylius_image form type is ProductVariantImage. It would make more sense if there was a type name sylius_product_variant_image and have that data class. A base image form type would be fine. I just don't expect the sylius_image form to have a data class that specific..

**Comment by michalmarcinkowski** [comment]
@axelvnk good point! :+1:

**Comment by axelvnk** [comment]
@michalmarcinkowski I'm happy to do it myself and open PR. Or maybe we need someone elses opinion first? @pjedrzejewski ?

**Comment by michalmarcinkowski** [comment]
I'm sure @pjedrzejewski will accept this PR, but he had some thoughts about product media, so let's wait for his input here :)

**Comment by michalmarcinkowski** [comment]
Fixed on the master.
