### ISSUE TITLE
Flaw with new Zone / Province structure

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#3902]
Hi,

I'm just working through updating our app to the latest in master. I've got problems with Provinces and the new Zone structure. 

Firstly Provinces now MUST have a code (even though the provinces of some countries are not code-based). This is OK I guess, I've just set code = name for some countries that have this issue - GB for example.

At Reiss we have provinces for 4 countries so far that we ship to regularly - US, GB, Canada and Australia. However there seems to be a design requirement for code not only to be defined but also to be *unique*.

This is an issue in our dataset (which is not unusual). For example

```
ID   COUNTRY_ID  NAME               CODE
48	 238	     Washington	        WA
221	 14	         Western Australia  WA
```

Here we have 2 different countries that use identical codes because unlike countries there's no international standard for provinces and their codes.

This firstly breaks the DB structure of a requirement for a unique code. This is not really a major issue as we could just make the unique constraint on (`country_id`, `code`). However it does expose a fairly major flaw in the new Zone to ZoneMember architecture.

My understanding of the ZoneMember changes are that instead of ZoneMember relating to a Province or Country directly, a ZoneMember is ALWAYS a Zone, which then has a code which can relate to the 'external' entity by `type` and `code`. I think this is correct?

If so, this works fine for country but not for province, because province's code can't be unique due to the above situation. 

I can think of a few solutions but none of them seem perfectly clean to me. What do you think?

**Comment by pjedrzejewski** [comment]
@peteward In our case, we just follow a convention where the province code is ``country_code-province_code``, so for example ``US-FL`` etc.

Generally the new structure does not change any logic, it just replaces db relations with code and yeah, we require them to be unique but that's it, you could just come up with some custom codes if there is no standard. Does it help? I am not sure I entirely understood the problem you described so please correct me if I miss something.

Thanks for discussing this! :+1:

**Comment by peteward** [comment]
But surely part of the whole convenience of using 'code' directly on entities like address is that it has visible sense to the end user so you don't need to do look-ups on another entity?

When rendering an address around the system, the following is something you might show:

```
1 University of Florida,
Gainesville,
FL  32611-9500
US
```

There might be times when you want the names instead so you might do:

```
1 University of Florida,
Gainesville,
Florida
32611-9500
United States
```

But one thing you definitely won't be displaying is:

```
1 University of Florida,
Gainesville,
US-FL  32611-9500
US
```

So the use of code directly for province has basically been lost, because code is not relevant to anything in this format other than internally to Sylius. It's not relevant to a customer, nor to an admin user, nor to any external system that might want a US state code - Payment, Fraud, Couriers, Tax, etc. These will all want a code which could have been easily provided with:

```
$address->getProvinceCode()
```

and previously was available very cleanly with:

```
$address->getProvince()->getCode()
```

Now this can only be achieved by injecting the repository everywhere you need it (or injecting some ProvinceProvider) and then getting the 'real' code from the one you are storing throughout Sylius.
 
It feels like a significant backwards step really.

Injecting the countryRepository to get the country name where you need it isn't great, but this province structure is much worse.

Unless I'm missing some magic way of getting a _real_ province or country code directly from something like an address object?

**Comment by peteward** [comment]
@pjedrzejewski any thoughts?

I've read through the full PR #3696, but can't see anything special to handle provinces here. They seem a bit broken to me unless you're either not using them or in a single-country situation. 

I can see why the changes were made to simplify zones memberships and it's good from that point of view, but it falls down if your province codes on address entities aren't really codes that you want to display/communicate.

It would be good to get some guidance. I'm thinking I might have to reintroduce the Address -> Province relation and we'll also need another `code` field of some sort for the equivalent of the state code, but I can't call it code so...

Tough one!

**Comment by peteward** [comment]
@pjedrzejewski does this make sense?

**Comment by michalmarcinkowski** [comment]
The province code should be unique by country_id **and** code, so the [following line](https://github.com/michalmarcinkowski/Sylius/blob/ce17eaeaaa5af36825f40e41940341ee70b7d313/src/Sylius/Bundle/AddressingBundle/Resources/config/doctrine/model/Province.orm.xml#L18-L18) must change.

I think that @pjedrzejewski will agree with me that the province code can stay two letter e.g. `WA` and will not have to be `US-FL` since we always have country code and can query by country and province to obtain unique result. This way the described issue is resolved, because you can obtain province code by calling `$address->getProvince()` (probably will be renamed to `getProvinceCode`. 

Obtaining country name is easier now, all you have to do is invoke `Intl::getRegionBundle()->getCountryName($countryCode, $locale);`. Country code can be obtained from address by calling `$address->getCountry()` (probably will be renamed to `getCountryCode`). 

There is also a [sylius_country_code_choice](https://github.com/michalmarcinkowski/Sylius/blob/ce17eaeaaa5af36825f40e41940341ee70b7d313/src/Sylius/Bundle/AddressingBundle/Form/Type/CountryCodeChoiceType.php) which handles country selection and a [Twig extension](https://github.com/michalmarcinkowski/Sylius/blob/0f3205e11699004dba3072e349c3673c6e396c58/src/Sylius/Bundle/AddressingBundle/Twig/CountryNameExtension.php) which handles displaying country name in templates (see [sylius_country_name](https://github.com/michalmarcinkowski/Sylius/blob/0f3205e11699004dba3072e349c3673c6e396c58/src/Sylius/Bundle/WebBundle/Resources/views/Common/Address/_show.html.twig#L12-L12)).

The countries support IMO is now better and the same is about to be done with Provinces. Now you can display the code without need to query/join. In the initial PR there is no 'ProvinceNameProvider', but we will implement it in the same way we did for country. You will need to pass country and province code and you will obtain province name. I don't think it breaks anything or introduces some limitations, did I miss something?

**Comment by peteward** [comment]
Hi @michalmarcinkowski, 

Thanks for getting back to me!

I agree with you, that was my initial thought.

The only problem with not having a unique province code is that it breaks the shiny new ZoneMember structure, which relies on code being unique for any of the 3 entities that it's parent Zone.type specifies.

I can't really think of an easy way around this without hacking up this nice new model :(   It might be to use the related entity id in the ZoneMember model instead of code, but that sort of goes against the idea of the new design.

In a way it's Province.code that goes against the design by not being completely unique, but it doesn't really work on the address entity if it were to change in this way.

**Comment by peteward** [comment]
@michalmarcinkowski, do you understand the issue here? We could have a Skype call to discuss if I'm not explaining myself clearly. Thanks!

**Comment by peteward** [comment]
ping @pjedrzejewski @michalmarcinkowski

**Comment by pjedrzejewski** [comment]
What if:

* We enforce prefixing the province code with country code. So in database there will be US-FL etc., which solves the problem with ZoneMember matching.
* We provide an easy way to display only the 2nd part of the code, so let's say ``$address->getProvinceCodeWithoutCountry()`` or any better name cause this one sucks. :)
* We provide another Twig helper:

```
address.countryCode // Outputs 'US'
address.provinceCode // Outputs 'US-FL'
address.provinceCodeWithoutCountry // Outputs 'FL'
address.countryCode|sylius_country_name // Outputs 'United States of America'
address.provinceCode|sylius_province_name // Outputs 'Florida' or whatever is saved on Province entity with code 'US-FL'
```

In PHP:

```
echo $provinceNameProvider->get($address->getProvinceCode); //  Outputs 'Florida' or whatever is saved on Province entity with code 'US-FL'
```

It sucks to inject a service just to get the name but:

a) we can easily cache it, so it won't hit the db;
b) I'd say you rarely need to use it anyway, because the logic can operate on codes very well and you render e-mails and html pages with Twig.

Regarding user experience, we could somehow automatically prefix the province codes with country code, so in the form you would need to just type FL and it would be saved as US-FL etc.

What do you think?

**Comment by michalmarcinkowski** [comment]
@peteward sorry for not responding earlier, but I was off yesterday.

How about making the ZoneMember code for Province like `{countryCode}-{provinceCode}`? This way we can have provinces with codes like `WY` etc. and ZoneMembers with code `US-WY`, do you think it will be fine?

/cc @pjedrzejewski

**Comment by peteward** [comment]
hmm it's a difficult one!

This sounds like it's probably the best solution.... There is an unfortunate naming confusion that `address.provinceCode` isn't going to be what you might think in most cases, and having to use `address.provinceCodeWithoutCountry` feels clunky, but I don't have a better idea!

Reducing address.provinceCode to only the non-unique code means that you would have to look-up with 2 joins on Country.code and Province.code so this is definitely not desirable.

Would we store the `true` province code separately anywhere? I'm just thinking about getting province codes outside of the address context where you don't have the country code immediately available - like if you're just rendering a list in the backend? Again, it means there has to be some service to join on country and you're always relying on some magic to get you the 'real code'.

But I don't have a better idea...

**Comment by michalmarcinkowski** [comment]
After giving it some more thoughts I think we should go with the logic @pjedrzejewski proposed. Keep the unique code on Province (`US-FL`) and simply add a method  `getProvinceCodeWithoutCountryCode` to the model (can anyone come up with a better name, please?) that will return simply `FL`, so you can use it anywhere you need. This way we will have consistent data model and treat the `code` field exactly the same in the whole system.

**Comment by peteward** [comment]
Maybe just `getProvince()`?  There are places in Sylius where `getCurrency()` returns just the code (even though an object exists).

**Comment by michalmarcinkowski** [comment]
I would say we should be as explicit as possible. When I call `getCurrency()` method I would expect `Currency` object not currency code. IMO it only confuses and the method that returns currency code instead of object should be renamed to `getCurrencyCode()`.

**Comment by peteward** [comment]
* `getProvinceShortCode`
* `getNativeProvinceCode`
* `getRawProvinceCode`
* `getAnythingButWhateverYouDoDontRenameItToAdministrativeAreaCode`

**Comment by pjedrzejewski** [comment]
@peteward hahaha :D I think ``getProvinceShortCode`` is the best we can figure out right now, let's not spend too much time here. :)

**Comment by michalmarcinkowski** [comment]
:+1: for `getProvinceShortCode`

**Comment by peteward** [comment]
ok sounds good.  As soon as this is done I'll continue our update to master

**Comment by peteward** [comment]
So I thought about this some more... I forgot about the most important use-case for us :)

In GB we don't have province codes, we only have names; Greater London, Kent, Hampshire, etc. `shortCode` doesn't feel right for these because they are neither codes nor short.

It did get me thinking about the Province structure though, we could have; `code`, `abbreviation` and `name`. Name would be mandatory, abbreviation optional. Code could therefore be set with something like:

```
$this->code = $this->getCountry()->getCode() . '-' . $this->abbreviation ?: $this->name;
```

You would end up with codes of 'US-FL', 'AU-WA' and 'GB-Greater London'.  For the Address method you were suggesting this gives you a sensible display element for use in most scenarios without needing to retrieve the province object.

But we still need a name for it... `getProvinceDisplay()`, `getProvincePresentation()`?  

wdyt?

**Comment by michalmarcinkowski** [comment]
The ISO standard also applies to GB (see "Second-level subdivisions" [section](https://en.wikipedia.org/wiki/ISO_3166-2:GB)), so I suppose you can use these codes.

The name of the province should be (and I suppose it is) mandatory and can be used for display. The usage will be the same as for country, so `address.provinceCode | sylius_province_name`. The mapping will be cached on PROD, so this will not affect the performance.

Do you see any limitations of this approach?

**Comment by peteward** [comment]
Interesting!

No one would ever use this though in practice in the UK. If we displayed someone's GB province as 'GLG' form 'GB-GLG' (meaning Glasgow) they wouldn't understand - it's never used.

So are you saying that we would then _always_ display the name, so then always have to use an external service to get it? Using 'Florida' instead of 'FL'  to be explicit?

Presumably there's an underlying helper that the twig function uses so that it can be used outside of twig? (integrations and API calls etc).  It's fine in twig, a little bit heavy if you have to inject this helper whenever you're communicating provinces, but it seems the best option. 

I still think that there could be a debate about a situation where you might want to get the abbreviation instead of the name and it's sensitive to the country. So for a UK province you will never want 'GLG' but for a US State it's perfectly acceptable (and often desirable). There could be a method that retrieves the 'shortest' version, which in some countries will be code/abbreviation, others will be name?

Country could have a `province_short_display_field` = `abbrevation` / `name` ?

**Comment by peteward** [comment]
or... you don't need anything on the Country.

If you have `code`, `abbreviation` and `name` as explicit fields on Province, then `sylius_province_abbrevation` could fallback to providing name if abbreviation isn' provided (in GB provinces for example)

**Comment by peteward** [comment]
thoughts? If there's any chance of getting a resolution merged in before the weekend it would be amazing - it will give me the chance to get our app updated.

**Comment by pjedrzejewski** [comment]
@peteward Sorry but I got lost here, what's the difference between "abbreviation" and "code"? Let's take an example:

```
address.countryCode // Outputs 'US'
address.provinceCode // Outputs 'US-FL'
address.provinceShortCode // Outputs 'FL'
address.countryCode|sylius_country_name // Outputs 'United States of America'
address.provinceCode|sylius_province_name // Outputs 'Florida' or whatever is saved on Province entity with code 'US-FL'
```

```
echo $provinceNameProvider->get($address->getProvinceCode); //  Outputs 'Florida' or whatever is saved on Province entity with code 'US-FL'
```

What is the real code? To me it seems that while it may be not widely adopted in practice, official/standard codes are US-FL and GB-HAM.

Yes, injecting a service into these few places where you need to send the province name is a trade off, but I believe it is worth having much simpler and faster zone management and matching.

Otherwise you will have all helps and methods available in templates/emails. (see above) What are we still missing there?

Regarding UX in admin, if that's really an issue to enter GB-HAM instead of just HAM, then we can easily prefix it with country in php/js. (not in core)

How often do you change provinces anyway?

**Comment by peteward** [comment]
@pjedrzejewski that example works great for the US, or for any country that has province codes that people actually use.

But take GB for example:

```
address.countryCode // 'GB'
address.provinceCode // 'GB-HAM'
address.provinceShortCode // 'HAM'  - but this is useless. No one in GB knows what 'HAM' means (even if it's an 'official' code). You would never see this output as part of an address
```

Addresses are rendered in lots of places. You will end up in a situation where for some countries using address.provinceShortCode works (US being the obvious one), but many others it doesn't (UK being one). I would never use it without checking the country type first - which is clunky.

So I can see 2 options. The first one is a bit of a workaround:

```
address.countryCode // 'GB'
address.provinceCode // 'GB-Hampshire'
address.provinceShortCode // 'Hampshire'  - but this isn't short or a code :)  
```

While the above could work, it doesn't feel clean and correct to be using something called `provinceShortCode` when it's not. It would be confusing to developers and it also means being inconsistent in your configuration against the ISO 3166-2 naming scheme. 

An alternative would be to add an extra field called `abbreviation` to provinces where the administrator can choose how to refer to a country's provinces 'in short'.

e.g.

```
code      abbreviation     name
US-WA     WA               Washington 
AU-WA     WA               Western Australia
GB-HAM    Hampshire        Hampshire
```

Or you could leave `abbreviation` blank for Hampshire and have a twig function `sylius_province_abbreviation` which would fallback to using the name if it doesn't fit.

With this approach you wouldn't use the 'shortcut' to remove the country part from the code, you would _always_ do a look-up on Province. In which case you could argue for a return to a 'proper' relation on Province by id... 

This would mean that you would have confidence in using province.abbreviation or province.name, knowing you'll get a workable response without hacking stuff at the model level.

If you don't like this then I'm totally happy to go with your suggestion. But I know that you are making a lot of major design decisions now to avoid changing stuff in future and having to deal with BC. This may seem trivial but it will cause people a lot of headaches in future if the address model changes.

Make a decision and go for it :+1:  ;)

**Comment by pjedrzejewski** [comment]
@peteward So we would actually persist "Hampshire" as abbreviation on the Address? To avoid using ``address.provinceCode|sylius_province_name`` which would return "Hampshire" exactly, according to your example.

**Comment by peteward** [comment]
If you are using `address.provinceCode|sylius_province_name` then you have lost the advantage of removing the relationship between address and province in the first place. Why not just do `address.province.name`?

You have to do this because the proposed `address.provinceShortCode` method doesn't work for provinces where the code isn't meaningful. If you can't use it for one country then you won't use it for any because of the complexity and overhead in checking if it's relevant for that country. So having province.code on the address entity becomes pointless because you will never use it because you can't rely on it.

So...

Either hack 'Hampshire' into the Province code as 'GB-Hampshire' so that you _can_ rely on address.provinceShortCode() to give you something consistently meaningful across different country's provinces.

OR

Just drop address.provinceCode and put the address.province relation back with a province.abbreviation attribute to define the 'shorter' way to refer to that province compared to name (as per my table above).

Adding address.countryCode made sense because it's **always** meaningful. address.provinceCode is not, but you need a way to rely on it consistently to make it worth having instead of a relation.

**Comment by peteward** [comment]
I've reread all of this to see if I was being confusing but it all makes sense to me! If you're still not seeing my point then maybe we should have a quick skype call/chat to go over it rather than waste more time in this mega-issue?

**Comment by peteward** [comment]
OK this is my final attempt!

The case for `Province.abbreviation` is to reintroduce what was lost by enforcing a unique `Province.code`.

Before these recent changes we had the following dataset for Province:

```
country  iso_name   name             
US       WA         Washington       
US       WY         Wyoming   
GB       Kent       Kent                   
GB       Hampshire  Hampshire   
AU       VI         Victoria
AU       WA         Western Australia 
````

Whilst you could argue that 'Kent' isn't an isoName, it gave you a way to render the 'short' version (abbreviation) of a province name in an acceptable way regardless of the country. 

With the suggestions for using the ISO-3166-2 province code under the new structure we have:

```
country  code      name
US       US-WA     Washington
US       US-WY     Wyoming
GB       GB-KEN    Kent
GB       GB-HAM    Hampshire
AU       AU-VI     Victoria
AU       AU-WA     Washington
```

This is great for the new ZoneMember design :+1:  and it looks cleaner in theory for addresses but you have lost the ability to get the `abbreviation` (that was in iso_name) when rendering addresses.

So by adding this back in, we have 2 suitable options for rendering an address depending on whether you want a 'short' version or a long, named version. 

```
country  code      abbreviation name
US       US-WA     WA           Washington
US       US-WY     WY           Wyoming
GB       GB-KEN    Kent         Kent
GB       GB-HAM    Hampshire    Hampshire
AU       AU-VI     VI           Victoria
AU       AU-WA     WA           Washington
```

It's worth noting that many integrations to external systems _require_ this abbreviation/code in it's 2 letter format for some countries. I know Paypal is one in it's address verification service for the US. Our tax provider ThomsonReuters is another. Whilst doing this by removing the country component from code is possible, it's not very clean and explicit - which is one of the coding fundamentals of Sylius isn't it - being explicit?

If you want to render an address in a short way you can now do:
```
{{ address.street }}
{{ address.city }}
{{ address.province.abbreviation }}, {{ address.postcode }}
{{ address.countryCode }}
```
A longer way can be done as:
```
{{ address.street }}
{{ address.city }}
{{ address.province.name }}, 
{{ address.postcode }}
{{ address.countryCode|sylius_country_name }}
```

Because the ISO 3166-2 format of province codes is not reliable for rendering there seems to be no point in having it on the Address entity. 

It makes sense for countryCode because you can rely on this in 75% of the cases to produce a universally known country code such as 'US' that everyone understands, looking up the name for the other 25% is a very acceptable trade-off.

I can't think of a situation where provinceCode makes sense to render on it's own and since you can't rely on "just removing the country code" (e.g. 'HAM') you will _always_ be forced to do a look-up against Province to get the name (or abbreviation if you agree to adding it). Even if you cache this, it's still extra work and complexity when you've got a relational database designed to do this for you.

So if it always requires a look-up then it's effectively useless and I suggest reverting to an entity relation `Address.province`

**Comment by pjedrzejewski** [comment]
@peteward What if we get a compromise:

1. There are significant benefits to not having any relations on address:
 * You can send the address in json or whatever format, deserialize it and push to all Sylius services, get taxes, zones etc.
 * No need to join it anywhere, which means simple queries for carts, orders etc. + much faster zone matching. Consistency.
 * When we rely on codes, we can also use existing data sets, like from CommerceGuys to load default configuration etc. with ease.

I strongly believe we should avoid changing our data model and especially add a relation just for displaying purposes, business logic and view are separate things. So, while not perfect, he is my proposal for compromise:

* Add an ``abbreviation`` field to Province model.
* Keep the address model as it is now.
* Add another helper:

```
{{ address.street }}
{{ address.city }}
{{ address.provinceCode }}
{{ address.provinceCode|sylius_province_name }} // $name property of the corresponding Province.
{{ address.provinceCode|sylius_province_abbreviation }} // $abbreviation property of the corresponding Province.
{{ address.postcode }}
{{ address.countryCode }}
{{ address.countryCode|sylius_country_name }} 
```

PHP:

```
$provinceNamingProvider->getName('US-FL');
$provinceNamingProvider->getAbbreviation('US-FL');
```

We cache it properly and it is faster than relation. Only drawback I see here is that you need to inject a service in places where you want to have name or abbr of the Province, but I'd say it's worth all the other benefits.

What do you think?

**Comment by peteward** [comment]
Fine, agreed! :+1:

**Comment by pjedrzejewski** [comment]
@peteward I will leave this open but please close if you use the solution and everything is ok, thanks for interesting discussions! I'm glad we have found something that works for everyone, yay for the community! :+1:

**Comment by peteward** [comment]
I think we'll all be very pleased to see this one closed.

I'll be updating over the weekend.

**Comment by peteward** [comment]
:+1:
