### ISSUE TITLE
[RFC][ApiBundle] Sparse Fieldsets 

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius#3912]
Sometimes with bigger numbers of items per page and serialization config which product lots of nested data structures, response time can be more then several seconds and response size can measure in MB.

What would be cool (not sure if possible), is to allow client to request that an endpoint return only specific fields in the response on a per-type basis by including a fields[TYPE] parameter - [sparse fieldsets](http://jsonapi.org/format/#fetching-sparse-fieldsets).

I would like to know if something like this is supported by REST libraries we use.

**Comment by pjedrzejewski** [comment]
@umpirsky Most of resources have very rough serializer configuration, but we will be tweaking it one by one. We can use serialization groups for that, I am not sure if it would be easy to support sparse fields though.

**Comment by umpirsky** [comment]
@pjedrzejewski Can serialization group be specified in the routing config?

**Comment by nakashu** [comment]
@umpirsky @pjedrzejewski field exclusion should not be hard.

Working solution is here: http://jolicode.com/blog/how-to-implement-your-own-fields-inclusion-rules-with-jms-serializer
For the sake if the site would die, I'll this here also, it the same just formated to answer on stack.
http://stackoverflow.com/questions/33126812/symfony-fosrestbundle-show-selected-fields

**Comment by pjedrzejewski** [comment]
@umpirsky Yes:

```
...
    _sylius:
        serialization_groups: [foo, bar]
```

**Comment by pjedrzejewski** [comment]
@nakashu Nice, we could use that! :+1: Thanks for the link.

**Comment by umpirsky** [comment]
@nakashu @pjedrzejewski Very cool, thanks for the info guys. Will close this now as it seems to be pretty flexible. Will try it out. :+1:

**Comment by umpirsky** [comment]
@pjedrzejewski Maybe I can contribute this thing? It works really well.

**Comment by pjedrzejewski** [comment]
@umpirsky That would be really cool!

**Comment by umpirsky** [comment]
@pjedrzejewski Qick and dirty WIP pushed https://github.com/Sylius/Sylius/pull/3938.
