### ISSUE TITLE
DatetimeAttributeType - wrong casing?

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#3913]
Shouldn't this be all lower case?

https://github.com/Sylius/Sylius/blob/50cfdb51f8c3617b106312dc3acea3c6cb44df8b/src/Sylius/Bundle/AttributeBundle/Resources/config/doctrine/model/AttributeValue.orm.xml#L28

Apologies I don't have time to check this right now but currently `dateTime` only works in DB queries but there's no other reference of it with this case anywhere, it's all lower case as `datetime` in the storage definitions:

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Attribute/Model/AttributeValueInterface.php#L24

It could be fine, it just seems like it could be wrong...

**Comment by peteward** [comment]
This looks fixed in the above PR, I'll reopen if there are any further issues but should be fine.

**Comment by pjedrzejewski** [comment]
@peteward Thanks for closing, that helps a lot! :+1:
