### ISSUE TITLE
[ThemeBundle] Provide templates from database (first layer of resolving), so they are editable in admin

### ISSUE THREAD

**Issue by koemeet** [Sylius/Sylius#3919]
What would it take to let the theme bundle handle themes stored on another place than the filesystem, lets say a database? 

Is the theme bundle tightly coupled to the filesystem?

**Comment by pamil** [comment]
I think it is quite tough job. I tried to reuse Symfony code as much as possible and it made some limitations. ThemeBundle needs to know about all the themes just when the container is built - Symfony's translator needs the resources to be passed as constructor argument, the assets needs to be installer and dumped by Assetic etc. 

If we would want to have templates loading at the runtime, custom template loader implementing `\Twig_LoaderInterface` would be the best choice. At this moment, we are using default `\Twig_Loader_Filesystem` with custom template locator - you might want to have a look at `Sylius\Bundle\ThemeBundle\Templating\Locator` to see template locating logic (which mainly proxies paths to resource locators) and `Sylius\Bundle\ThemeBundle\Locator` for resource locators (we do not use all their power, as setting them as default resource locators can allow us to swap configuration files like routing or services).

ThemeBundle is in fact a set of decorators, every one of them can be replaced by one another. My main focus was to make the opt-in and opt-out as simple and trouble-free as possible. Back then when I was writing the first version of TB I wasn't able to code it more generically, Symfony itself doesn't encourage to do so too. 

Anyway, ThemeBundle in coming weeks will be still under heavy development, so there is a chance something will change.

**Comment by steffenbrem** [comment]
@pamil Thanks for your response! I currently have made my own theme bundle to manage theme inheritance etc. and templates from the database. It's currently very tightly coupled to my application, but I think I will try and build upon your work here and see if I can make it work. 

I was thinking about having simple interfaces that manage providing them templates source etc. but I am not sure if this is practical. I will get back to this after I have fiddled around with the ThemeBundle of Sylius.

**Comment by steffenbrem** [comment]
@pamil I have looked into your code for the TB and I think it might actually be quite easy to add an extra layer in front of it to support database template loading. As you where saying the TB right now is an extra layer on top of the default TemplateFileLocator (for templates at least). So database loading will indeed only require a implementation of the `Twig_LoaderInterface`. We could simply inject `sylius.context.theme` here and use that to find the template in the database.

I am currently reworking my own theme bundle and I am trying to integrate it with your work, so you have those nice theme folders in `app/themes` and can sync those back to the DB. Right now I have proper caching and everything working correctly.

From what I see, it might be a nice feature to have for Sylius to be able to edit specific templates in the admin! I need those things for a client and I can open source my work if it all works out well. Would be nice to have that in core :).

About translations etc. I haven't looked into that yet.
