### ISSUE TITLE
Probleme after Clearing the cache for the dev environment with debug true

### ISSUE THREAD

**Issue by benakacha** [Sylius/Sylius#3920]
sylius.order.pending.duration ('3 hours'): 
wkhtmltopdf.bin_path (/usr/bin/wkhtmltopdf): 
wkhtmltoimage.bin_path (/usr/bin/wkhtmltoimage): 
Clearing the cache for the dev environment with debug true
Download or update create

error: RPC failed; result=56, HTTP code = 200
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Script Symfony\Cmf\Bundle\CreateBundle\Composer\ScriptHandler::downloadCreateAndCkeditor handling the post-install-cmd event terminated with an exception

                                                                          
  [RuntimeException]                                                      
  Running git clone https://github.com/bergie/create.git failed with 128

**Comment by pjedrzejewski** [comment]
Seems to be a problem with github and cloning of the repository. Could you try it again in a moment and see if it works?

**Comment by michalmarcinkowski** [comment]
@benakacha please reopen if still relevant.
