### ISSUE TITLE
Should it be mandatory to have a Base Currency?

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#3922]
I think so, just wondering if there are any situations where it would be acceptable not to have it?

We're doing a PR for adding exchange rate to orders and also to reporting where we want to show that the totals are in base currency. But what if there is no base currency...?

We could just the text display of base currency blank if it doesn't exist, I'm just wondering if it ever wouldn't exist?

**Comment by pjedrzejewski** [comment]
We want and need to enforce it, otherwise we can have some interesting bugs. :D First steps has been made in #3895 and #3814.

**Comment by peteward** [comment]
OK, sounds good. We will make it handle it gracefully for now.
