### ISSUE TITLE
Cannot impersonate a Customer

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#3925]
Probably a low priority one, but an interesting issue to consider for future. Since impersonation uses Symfony's standard User framework I'm not sure how easy this would be.

In our model we have a roughly a 50/50 split of Customers who are Users and those who are not.

The workaround for us will be that if we need to impersonate a Customer for and reason then we have to convert them into a User - not the end of the world..

**Comment by michalmarcinkowski** [comment]
Why do you want to impersonate a Customer? If you would like to make an order as specific customer you can simply use its email address with the guest checkout. Is there something I'm missing?

**Comment by peteward** [comment]
It's good from a customer services perspective that if a customer is having problems ordering and they call on the phone you can impersonate and inherit their cart and be straight at the same point in checkout. It can be painful to have to walk through the full process entering all addresses and personal details.

Although with our project's cart caching that doesn't seem to work anyway! Not sure about core sylius though...
