### ISSUE TITLE
[RFC] Usage of assertion library

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#3928]
In Sylius there are many places when we're validating arguments and that logic is often duplicated. Agreeing on some assertion library will make our codebase cleaner.

My proposition: [beberlei/assert](https://github.com/beberlei/assert).

**Comment by pjedrzejewski** [comment]
I'd need to think a bit more and do some research before we go this way because it will affect many places and conventions, but I always thought about it and currently do not see anything against. :+1:

**Comment by Zales0123** [comment]
I'm :+1: :+1: :+1: with some assertion library (of course after profound research ;))

**Comment by bendavies** [comment]
:+1:

**Comment by bburnichon** [comment]
As Assertion library, there also is [webmozart/assert](https://github.com/webmozart/assert)

**Comment by michalmarcinkowski** [comment]
:+1: for using library. Let's do some research and decide on the best one! :)

**Comment by lchrusciel** [comment]
:+1:

**Comment by gperdomor** [comment]
As i said in #4376, i propose [webmozart/assert](https://github.com/webmozart/assert) which is based in [beberlei/assert](https://github.com/beberlei/assert), and as the developer said:

> What's the difference to beberlei/assert?
>This library is heavily inspired by Benjamin Eberlei's wonderful assert package, but fixes a usability issue with error messages that can't be fixed there without breaking backwards compatibility.
>This package features usable error messages by default. However, you can also easily write custom error messages:
>
><code>Assert::string($path, 'The path is expected to be a string. Got: %s');</code>
In beberlei/assert, the ordering of the %s placeholders is different for every assertion. This package, on the contrary, provides consistent placeholder ordering for all assertions:
>
>- %s: The tested value as string, e.g. "/foo/bar".
>- %2$s, %3$s, ...: Additional assertion-specific values, e.g. the minimum/maximum length, allowed values, etc.

**Comment by pjedrzejewski** [comment]
We go with Bernhard's lib. ;)

**Comment by gperdomor** [comment]
@pjedrzejewski @pamil @michalmarcinkowski maybe we have some problems with assertion library, when you send a form, the <code>setMethods</code> are called and throws the exceptions if the assertion fails, so you get an error 500 instead the form validation errors.
