### ISSUE TITLE
[RFC] Resolving channels, selecting currencies, locales and exceptions

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#3929]
Helloes!

Current channel resolving logic is wrong and same goes for selecting currency, locale etc.
We are simplifying the installer in #3814 so there is no channels, countries, locales etc. by default. So unless you load fixtures you will have a raw Sylius install with only base currency defined.

Overview of current state:

* Look for channel with LIKE hostname, which is just terrible solution implemented by me; (sorry! :D)
* If not found, get the default channel which means first channel found in repository;
* If there are no channels -> throw doctrine exception and 500 error.

Expected behavior:

* Find a channel by hostname. (for now, later I'd like to have ability to attach custom resolvers and decide on different factors than hostname, could be even locale or country of shipping)
* If not found, throw UnresolvedChannelException;
* Handle it via kernel.exception listener and display a 404 for customers and nice information page for admins / devs in dev mode, saying that Sylius could not decide about current channel with links to the backend etc.

Pretty much the same behavior should be done for not configured currencies, locales etc. but that's for future.

Let me know what do you think!

**Comment by pamil** [comment]
:+1:, we may create an instance of `Symfony\Component\HttpFoundation\RequestMatcherInterface` for every channel and configure it like in Symfony Security component (but using CLI Installer for the first time & web backend later).

Also, I would like to get `ChannelContextInterface::setChannel()` removed - it only creates confusion, if one wants to set current in code, they can implement channel context interface with setter.

`Sylius\Component\Core\Channel\ChannelConextInterface` should be removed at the same time, as it only changes docblock.

Last but not least, default `ChannelContext` itself shouldn't include caching (sorry! :D), caching should be implemented as a decorator.

**Comment by pjedrzejewski** [comment]
@pamil :+1: on all points.

**Comment by michalmarcinkowski** [comment]
:+1:

**Comment by peteward** [comment]
It's also worth considering that not everyone will use channel by hostname (we don't). I haven't checked how this is implemented, but consider abstracting it to something like a `ChannelResolverStrategy` that could be replaced more easily for people who use channel differently. Even if you only implement your version above.

**Comment by pjedrzejewski** [comment]
@peteward absolutely, Strategy is a nicer name than custom resolvers, see my first point -> ``(for now, later I'd like to have ability to attach custom resolvers and decide on different factors than hostname, could be even locale or country of shipping)``.

**Comment by peteward** [comment]
apologies, missed that part :)

**Comment by pjedrzejewski** [comment]
@peteward No worries, I am fast reading github as well, otherwise I'd need to live here. :D

**Comment by tristanbes** [comment]
@peteward how do you use the channel feature if not by hostname ? i'm curious there.

**Comment by peteward** [comment]
url prefix:

* /us/ = US store
* /eu/ = EU store
* /rw/ = Rest of World store

etc.

**Comment by tristanbes** [comment]
thanks :)
