### ISSUE TITLE
Running tests in local env

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius#3934]
Just run them:

```
$ ./bin/phpunit 
PHPUnit 4.8.18 by Sebastian Bergmann and contributors.

...........................F

Time: 9.92 seconds, Memory: 81.50Mb

There was 1 failure:

1) Sylius\Bundle\ThemeBundle\Tests\Functional\TranslationTest::testTranslations
Failed asserting that 'BUNDLE/Resources/translations: BUNDLE/Resources/translations
app/Resources/BUNDLE_NAME/translations: app/Resources/BUNDLE_NAME/translations
app/Resources/translations: app/Resources/translations
THEME/BUNDLE_NAME/translations: THEME/BUNDLE_NAME/translations
THEME/translations: THEME/BUNDLE_NAME/translations
PARENT_THEME/BUNDLE_NAME/translations: PARENT_THEME/BUNDLE_NAME/translations
PARENT_THEME/translations: PARENT_THEME/BUNDLE_NAME/translations
' contains "THEME/translations: THEME/translations".

/home/umpirsky/Projects/Sylius/src/Sylius/Bundle/ThemeBundle/Tests/Functional/TranslationTest.php:26

FAILURES!
Tests: 28, Assertions: 54, Failures: 1.
```

Can you please hint me @pamil?

**Comment by pamil** [comment]
To be honest I have no idea why you've encountered this issue, it works both for me and Travis, seems like the themed application-level translation files cannot be found. 

I would check if there are `message.en.yml` files in the following directories: `ThemeBundle/Tests/Functional/app/DefaultTestCase/themes/{First,Second}TestTheme/translations/`.

**Comment by pjedrzejewski** [comment]
Works for me locally without any problem.

**Comment by umpirsky** [comment]
I already checked, they are:

```
umpirsky@zenbook:src/Sylius/Bundle/ThemeBundle/Tests/Functional/app/DefaultTestCase/themes$ tree .
.
├── FirstTestTheme
│   ├── TestBundle
│   │   ├── public
│   │   │   └── theme_asset.txt
│   │   ├── translations
│   │   │   └── messages.en.yml
│   │   └── views
│   │       └── Templating
│   │           ├── bothThemesTemplate.txt.twig
│   │           └── vanillaOverridedThemeTemplate.txt.twig
│   ├── theme.json
│   ├── translations
│   │   └── messages.en.yml
│   └── views
│       └── Templating
│           └── bothThemesTemplate.txt.twig
└── SecondTestTheme
    ├── TestBundle
    │   ├── public
    │   │   └── theme_asset.txt
    │   ├── translations
    │   │   └── messages.en.yml
    │   └── views
    │       └── Templating
    │           ├── bothThemesTemplate.txt.twig
    │           └── lastThemeTemplate.txt.twig
    ├── theme.json
    ├── translations
    │   └── messages.en.yml
    └── views
        └── Templating
            ├── bothThemesTemplate.txt.twig
            └── lastThemeTemplate.txt.twig

18 directories, 15 files
```

Looks like it loads translation from `src/Sylius/Bundle/ThemeBundle/Tests/Functional/app/DefaultTestCase/themes/FirstTestTheme/TestBundle/translations/messages.en.yml` and expected is to load it from `src/Sylius/Bundle/ThemeBundle/Tests/Functional/app/DefaultTestCase/themes/FirstTestTheme/translations/messages.en.yml`.

That is what I guessed based on the values inside. 
Thanks.

**Comment by pamil** [comment]
@umpirsky got something that can help us with debugging this issue:

 -  Comment out this line in `Tests/Functional/ThemeBundleTestCase.php` in `tearDown`:
```php
$this->deleteTmpDir(self::TEST_CASE);
```
 - Run phpunit
 - Go to `sys_get_temp_dir() . '/' . Kernel::VERSION . '/' . $testCase` directory (`Kernel::VERSION` ~ `2.7.7`, `$testCase` = `DefaultTestCase`)
 - Go deeper into `cache/frameworkbundletestdefaulttestcase` directory
 - Dump `appFrameworkbundletestdefaulttestcaseDebugProjectContainer.php` here :)

**Comment by umpirsky** [comment]
@pamil https://gist.github.com/umpirsky/5ffc48ac53cdd0a012d6.

For me it is:

```php
// ...
 8 => '/home/umpirsky/Projects/Sylius/src/Sylius/Bundle/ThemeBundle/Tests/Functional/app/DefaultTestCase/themes/FirstTestTheme/translations/messages.en.yml', 
 9 => '/home/umpirsky/Projects/Sylius/src/Sylius/Bundle/ThemeBundle/Tests/Functional/app/DefaultTestCase/themes/FirstTestTheme/TestBundle/translations/messages.en.yml
///
```

And for you probably something like:

```php
// ...
 8 => '/home/umpirsky/Projects/Sylius/src/Sylius/Bundle/ThemeBundle/Tests/Functional/app/DefaultTestCase/themes/FirstTestTheme/TestBundle/translations/messages.en.yml
 9 => '/home/umpirsky/Projects/Sylius/src/Sylius/Bundle/ThemeBundle/Tests/Functional/app/DefaultTestCase/themes/FirstTestTheme/translations/messages.en.yml', 
///
```

I think I had something similar before, and if I remember correctly Symfony finder component orders files based on some system related setting, not sure if locale.

**Comment by pamil** [comment]
@umpirsky yeah, that's right, I forgot about separating bundle and app translations! :) I'll send fix for that at tomorrow's morning, kinda weird it kept working correctly on both Ubuntu and OS X.

**Comment by umpirsky** [comment]
@pamil (un)lucky coincidence. :)

**Comment by michalmarcinkowski** [comment]
Should be fixed. @umpirsky please reopen if still relevant.
