### ISSUE TITLE
Not update any fields if update username (User && Customer)

### ISSUE THREAD

**Issue by ZhukV** [Sylius/Sylius#3939]
If i want a update username and another field (password as example), then only username will be update.

Because you @michalmarcinkowski can not change any fields on `preUpdate` event and run repeatedly `flush` action.
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/UserBundle/EventListener/DefaultUsernameORMListener.php#L58

Please read the Doctrine2 ORM Documentation!

If you want change field on `flush` action, you should use `onFlush` event and call to `recomputeSingleEntityChangeSet` for change new field.

**Comment by michalmarcinkowski** [comment]
The lifecycle events at first looked like a good choice, but indeed it is a terrible solution ([good reading])(http://vvv.tobiassjosten.net/symfony/update-associated-entities-in-doctrine/).

Thanks for reporting this issue, we will fix it ASAP!

**Comment by pjedrzejewski** [comment]
Fixed in #3970, thank you guys! :)
