### ISSUE TITLE
[RFC] Fixtures should implement DependentFixtureInterface

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius#3947]
Just noticed that there is `DependentFixtureInterface`, which allows you to define fixture dependencies. In this case there is no need to mess with loading order. Sounds like an improvement to me.

What do you think?

**Comment by stloyd** [comment]
@umpirsky Side note: please don't tag `RFC` with tags `Awaiting Feedback` & `Easy Pick`, those two should be left for issues & bugfixes/features IMO ;)

**Comment by umpirsky** [comment]
@stloyd Fixed. ;)

**Comment by michalmarcinkowski** [comment]
We have a brand new FixturesBundle now where this is no longer valid 😉
