### ISSUE TITLE
Adding locale bug

### ISSUE THREAD

**Issue by yopop666** [Sylius/Sylius#3952]
On
http://demo.sylius.org/administration/locales/new
the select has switched keys with values.
Now have options like
```<option value="Afrikaans">af</option>```
and must be
```<option value="af">Afrikaans</option>.```

If you will create new locale now, when you will edit a Channel for example you will receive
**Catchable Fatal Error: Method Sylius\Component\Locale\Model\Locale::__toString() must return a string value**

If you will create new locale and will choose **af** now, in **sylius_locale** database table, stored name will be **Afrikaans** not **af**

**Comment by michalmarcinkowski** [comment]
Unfortunately it's Symfony BC break... (see [similar issue](https://github.com/Sylius/Sylius/issues/3869#issuecomment-171778661)) We will fix it ASAP.

**Comment by michalmarcinkowski** [comment]
Already fixed
