### ISSUE TITLE
TranslationBundle: ODMTranslatableListener is broken

### ISSUE THREAD

**Issue by bendavies** [Sylius/Sylius#3955]
The service definition for `ODMTranslatableListener` is completely wrong.
Also It looks like `ODMTranslatableListener` should extend `AbstractTranslatableListener`, but it doesn't.

It was broken in https://github.com/Sylius/Sylius/commit/6be08f847f7fea3def754b05c562989f0f06276d

**Comment by michalmarcinkowski** [comment]
@bendavies is it still an issue?

**Comment by bendavies** [comment]
@michalmarcinkowski i have never used it, only noticed it was broken when it was fixing the `ORMTranslatableListener`.

Just having a look, `ODMTranslatableListener` isn't currently defined as a service...so yes, it looks broken.

**Comment by michalmarcinkowski** [comment]
Ok, thanks!

**Comment by Zales0123** [comment]
We no longer support MongoDB since Sylius **1.3**. I believe it can be closed then 🐃 :)
