### ISSUE TITLE
Create new page gave error "This value is not valid." under Publish end date

### ISSUE THREAD

**Issue by achristodoulou** [Sylius/Sylius#3958]
Url: http://demo.sylius.org/administration/content/static-contents/new

I fill the form with the following values:
```
Published: checked
Publish start date: 2016 Jan 1 10 : 10
Publish end date: 2020 Jan 1 10 :10
Internal name: my_home_page
Title: Homepage
Body: ASSSA S AS ASASASSasdas dasd asd sa
```

and when I press the create button I got the error "This value is not valid." under Publish end date.

Also I would like to ask you why there is Publish end date for a page, what is the meaning?

**Comment by okwinza** [comment]
IIRC the idea about publish dates was to allow some date-specific content. Say, promotions info, some kind of announment, etc. So publish end date was introduced to spare you from disabling it yourself once they're no longer needed.

**Comment by michalmarcinkowski** [comment]
Fixed as there are no publish dates anymore.
