### ISSUE TITLE
When set pricing based on customer group, amount is not showing in front-end in products page

### ISSUE THREAD

**Issue by achristodoulou** [Sylius/Sylius#3964]
1. Create customer group
2. Create a product and set Pricing: Customer Group Based
3. Edit product and set amount for the specified group in Pricing configuration (can only see field of pricing configuration after editing product #3487) 
4. Login using a user of the specified group
5. Go to product specific page and the group based amount is not showing up. It only displays when you add to cart and see it from there.

**Comment by pjedrzejewski** [comment]
This will be reworked in new admin and shop. This issue is related to the old UI, so I will close this. Thanks for reporting! :)
