### ISSUE TITLE
[Translation] Use traits instead of AbstractTranslatable class

### ISSUE THREAD

**Issue by ahmadrabie** [Sylius/Sylius#3965]
I want to use `PaymentBundle` in my own project, and I have to extend `PaymentMethod` model, but I do not want to use Translations here. 

Currently `PaymentMethod` is extending `AbstractTranslatable` so I have to bring in whole translation bundle and stuff.

Do you think introducing `TranslatableTrait` and decouple bundles below from `TranslationBundle` and use that trait in `Core` would be a good idea? If you think so I can submit a PR for this ;)

Bundles coupled to AbstractTranslatable:
* Taxonomy
* Product
* Attribute
* Option
* PaymentMethod
* ShippingMethod
* Archetype
* Topic

**Comment by michalmarcinkowski** [comment]
Done.
