### ISSUE TITLE
Administration dashboard permission

### ISSUE THREAD

**Issue by Buri** [Sylius/Sylius#3968]
Users that can view administration can see information from all areas on their dashboard regardless if they have permission to that section. For example, user that is in only role "content_editor" can see last orders and last registered users

**Comment by pjedrzejewski** [comment]
@Buri Yes, dashboard is not using rbac permissions yet. We will adjust that as we rework Admin UI, see #3646. Thanks for reporting this issue so we can track it properly. :)

**Comment by peteraba** [comment]
@pjedrzejewski  I guess this can be closed. I just wish it was more obvious how to get into the admin :)
