### ISSUE TITLE
api/products endpoint error

### ISSUE THREAD

**Issue by xantrix** [Sylius/Sylius#3969]
Hi guys :)
I’m using the v0.16.0 release of this amazing ecommerce project and when I call the "api/products" endpoint I get this error:
“The method getPresentation not found in class Sylius\Component\Attribute\Model\AttributeValue"
Any idea ?
All other endpoints works well!

**Comment by michalmarcinkowski** [comment]
The attributes system has changed and it looks like the serialization configuration was not updated... There is no `presentation` field on Attribute class any more.

**Comment by mathielen** [comment]
+1

**Comment by vikey89** [comment]
+1

**Comment by pjedrzejewski** [comment]
Fixed in #3973. :)
