### ISSUE TITLE
OptionValue lacks of translation system

### ISSUE THREAD

**Issue by vikey89** [Sylius/Sylius#3975]
Hi guys,
there is any reason why ```src/Sylius/Component/Variation/Model/OptionValue.php``` lacks of translation system?

Thanks :)

**Comment by pjedrzejewski** [comment]
No particular reason I think, I believe it should be pretty straightforward to implement. Definitely something we want before 1.0. Same for AttributeValue but this one can be more complex. :) If you would like to give it a shot, then I will be happy to have it in the core. :+1: 

If you start on it and in any doubt, please comment here so we can save some review time, it's better to do small steps and get them reviewed than coming with a large PR. :)

**Comment by vikey89** [comment]
I'm more than happy to make a try in contributing :)

**Comment by xantrix** [comment]
A "must have" feature! :+1:

**Comment by pjedrzejewski** [comment]
@vikey89 Great! This should be a good starting point - http://docs.sylius.org/en/latest/contributing/index.html. Open a PR as soon as you do the first commit, we will be glad to help! :)

**Comment by vikey89** [comment]
Thanks @pjedrzejewski for your feedback :)

**Comment by vikey89** [comment]
Hi @pjedrzejewski  I'm working on this issue and I need a clarification.
The [OptionValue](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Variation/Model/OptionValue.php) Object already has a getPresentation method that returns the name of the Option.
To add the translation value, I should add a presentation field in OptionValue.
So I changed `getPresentation` in `getPresentationOption`, but this involves a refactoring in a lot of templates e.g [macros.html.twig](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Resources/views/Backend/ProductVariant/macros.html.twig#L38) in order to substitute `option.presentation` in `option.presentationOption`.

Is the templates refactor correct?

**Comment by vikey89** [comment]
any suggestions? @pjedrzejewski @michalmarcinkowski

**Comment by michalmarcinkowski** [comment]
Why renaming `value` of `OptionValue` to `presentation` in the first place?

**Comment by vikey89** [comment]
I haven't renamed `value` to `presentation`, I have added `presentation` field to manage values translation of `OptionValue`.

**Comment by michalmarcinkowski** [comment]
There was a `value` field ([see here](https://github.com/Sylius/Sylius/pull/4051/files#diff-038d3968c1792d11339545c9fa8cf0beL121)) and now you added `presentation` field ([see here](https://github.com/Sylius/Sylius/pull/4051/files#diff-038d3968c1792d11339545c9fa8cf0beR126)). IMO we can call it `value` so there will be no problem with name conflict.

**Comment by pjedrzejewski** [comment]
Actually, I think OptionValue and OptionValueTranslation should look like this:

OptionValue:
* code
* translations

OptionValueTranslation:
* name (renamed from presentation)

This way we have immutable code for every option value (useful in UI, importing, etc.) and name is translatable.

Wdyt?

**Comment by vikey89** [comment]
ok for me, but I used `presentation` like name of field and not `name`. 
I've finished and I'm waiting to code review and feedback.

**Comment by vikey89** [comment]
[PR #4051](https://github.com/Sylius/Sylius/pull/4051) merged

**Comment by pjedrzejewski** [comment]
:+1:
