### ISSUE TITLE
[RFC] Having just one variant instead of master variant

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#3976]
Hey folks!

Nothing has been done here and nothing decided yet, this is just an RFC to get some feedback and feeling about possible solution to the "master variant problem". In #3773 we get rid of this silly rootTaxon and another thing that I really don't like is the masterVariant concept. Yes, it simplifies a lot of stuff, but if you look at Sylius codebase, it is used really in just few places, all the logic is operating on the variant itself.

Explaining the concept and handling it is really annoying, especially for products with many variants, you always have this one extra variant with silly "master" true/false flag you need to care about. Then you need to decide about the relation, initially we had ``master_variant_id`` column on Product and ``variants`` collection, but it was bad solution and we changed that to having master variant inside of ``variants`` with master = true. That sucks too. :D

So, my proposal is to simply have Product and Product.variants collection. This would simplify a lot of stuff we handle right now and ease implementation of other things that we are missing now:

* What if someone adds an option to the product?
* What if I had only masterVariant and now I want to have 2 variants, I create 1 variant or 2 and previous orders use this old masterVariant?
* What if I had 2 variants and now I want to add one more option?

To me it makes perfect sense that simple products come with a single variant and configurable ones have more than 1 variant. Pretty much every product can come in variations at some point so I think it is not an overkill to talk about variant even when initially there is one. Let's take a Book as example, yeah it usually is simple product, but what if you introduce digital version etc. It can be a separate product or another variant, I'd let the developers/merchants to decide how to handle that.

I don't see any drawbacks in terms of performance, we already handle variants collection and get the master variant from there. There is plenty of things to consider but right now the only con I see is the not very well known feature of storing defaults on master variant. It is used in generator only I think.

This would allow us to handle options even better, let's take an example: If I have a Book that comes with a single variant, and at some point I decide to add a hardcover and digital edition, I add an option and attach it to the product. Sylius would require to assign the options to new and existing variations, so all variants have an appropriate option defined. Same for adding one more option to existing product, it would generate new combinations and require to configure new options to existing variants.

I know it is not perfect, but until we figure it out we could only allow changing options when creating the product. That's better than having all the bugs and mistakes in the backend.

There is probably more stuff that needs to be figured out, but I would really like to stop explaining what masterVariant is, it sounds like an odd concept. There is no such thing in the eCommerce domain.

In terms of BC, quick search on our repo: https://github.com/Sylius/Sylius/search?l=php&q=MasterVariant&utf8=%E2%9C%93

We do not use it that much and it should be really use to change. In existing projects, that would basically mean doing ``$product->getVariants()->first()`` instead of  ``getMasterVariant()``.

WDYT?

**Comment by peteward** [comment]
100% agree.  Not that it really affects our project, we just have to remember when querying to ignore it currently ;)

But it makes sense that you would always have a single variant - we do this in some situations with gift card products that we sell and other accessories

I see your problem about defaults on a variant, but I think you can overcome it! ;)

**Comment by cdaguerre** [comment]
> I know it is perfect, but until we figure it out we could only allow options when creating the product. That's better than having all the bugs and mistakes in the backend.

I agree even though it's not perfect ;)

**Comment by pjedrzejewski** [comment]
@peteward @cdaguerre Thanks for the feedback guys!

**Comment by acrnogor** [comment]
I have an example with almost identical implementation to your No-Master-Variant example. 
Lets say you're running a store that sells just about anything, and you want to sell a complete bedroom as a product. See my current project and this exact example here: http://www.emmezeta.hr/namjestaj/spavaca-soba/spavace-sobe/48429/lidia-spavaca-soba/#pr_opis-content
So basically, you have a base product (single product ID) that has ProductVariants that are not these same items with different options, but more like part of the same set. In my example, you add the Variants to the cart, every variant has different SKU, different price, etc, but when listing on category page, i can opt out to list it as a solo product in its category. Or I can implement a search page where every variant shows as a 'separate' result. 

As for database schema - products table in my example contains a different title for BedroomSetProduct (i.e. "SuperCool Bedroom Pro", all other fields are mostly dates and relations. Price can be shown as "per item" or as SUM(total) of all variants.
And product_variants table contains very similar structure like in Sylius, but no master variant. And 

I'm not sure how other e-commerce software solves this problem (Prestashop, Magento?), but HTH.

**Comment by kayue** [comment]
:+1: 

Default value can just be stored in the `Product`, such as price.

**Comment by ahmadrabie** [comment]
@pjedrzejewski I think when you say:
`doing $product->getVariants()->first() instead of getMasterVariant()`
it means that some times we need to display one of variants as master variant for example in taxonomy page.
what is your solution if someone want to display 3RD variant of the product as default variant (price,image,stock,...)?

**Comment by pjedrzejewski** [comment]
@ahmadrabie That's a good point, I think we could make the variants sortable! This would be useful in many other cases.

**Comment by michalmarcinkowski** [comment]
MasterVariant is removed :)
