### ISSUE TITLE
Upload of product variant image fails with odd exception when php.ini max upload size stops it

### ISSUE THREAD

**Issue by Amunak** [Sylius/Sylius#3983]
Basically what the title says. When you try to upload an image to ProductVariant, and it is stopped by php.ini, the form ignores it because there is no validation.Then MimeTypeGuesser throws an exception because it receives no path to file.

We have fixed it by adding validation constraint, so feel free to use that: https://github.com/ThreeSixtyEu/Sylius/commit/416e04e5f5151ae7c14ac10dfe1697d4d2f2eab2

**Comment by pjedrzejewski** [comment]
Thanks for the report and solution, we will try to include it soon! :+1:

**Comment by michalmarcinkowski** [comment]
Fixed.
