### ISSUE TITLE
[RFC] - CartItemController more flexible redirects/responses

### ISSUE THREAD

**Issue by nakashu** [Sylius/Sylius#3988]
I am currently making some changes in `CartItemController` for a project , that would probably benefit also for the core, and need initial comments for the approach.

#### Problem

Currently there are `addAction` and `RemoveAction` where 95% of time you don't need to change the resolving login / flash handling, as you can override the Resolver itself if needed or just hook to the dispatched events.

The limitation is with the `redirectAfterAdd / redirectToCartSummary` methods:

* `redirectAfterAdd()` is private, so you cannot overriding its login inside your controller, and are left with copy paste 
* `removeAction` calls only redirectToSummary.
* inside the redirect methods you are missing the whole context, namely the `cartItem` that was just added / removed, this limits uses where you need to dynamically redirect to page with current `cartItem `only

#### Usecases:

* you want to handle additional query parameters (passed to the route) on which you'll decide where to redirect. Although it is possible to do now, if you overrid the `redirectToSummary` it seems dirty if in the end you will go to homepage for instance based on the parameters.
* you want do dynamically generate route with current cartItem ID or other data. For instance you add a laptop to cart and want to show page with adjustments/accessories like extended warranty. Here you can buy the same product/variant twice but with different accessories.
* ajax handling of adding and removing, where you need different response for ajax requests.

#### Solution:

* make 2 methods - responseAfterAdd / responseAfterRemove - both protected
* pass second parameter `$cartItem` to these

With this you can handle all above scenarios, just by overriding those two methods instead of whole actions, without any BC.

#### Sample
```php
protected function responseAfterAdd (RequestConfiguration $configuration, CartItemInterface $item = null)
    {
        $request = $configuration->getRequest();

        if ($request->query->has('_redirect_to')) {
            return $this->redirectHandler->redirect($configuration, $request->query->get('_redirect_to'));
        }

       // if you override this you can do what you please like
       if ($request->isXmlHttpRequest())
            return new JsonResponse(['stuff' => 'ajax_stuff']);

        return $this->redirectToCartSummary($configuration);
    }
```

I'll make the PR, if this looks sensible.

Its also partialy related to this issue #2627 concerning the redirect to summary page.

**Comment by adamelso** [comment]
:+1: Came across this issue today; would also like to use it in an AJAX request without duplicating the code too much :)

**Comment by nakashu** [comment]
Just found another issue with cartItemResolver / CartSubscriber

When adding product to cart . . the cartItem that is present in the controller after the save event is finished will the correct only for the first addAction .. on the next ones where only quantity is incremented, you'll get new cartItem Object without ID or other information.

The issue is that when the save / increment event in subsciberr is going, it will only update the object in Cart if it was present. It wont replace/update the newly created from controller.

Also there isn't a way how to retrieve the last added cartitem to cart.

Maybe the equals() method on CartItem as it is used in CartSubscriber. Or anyone got better way?

**Comment by nakashu** [comment]
Update for the samplte method so it would be more flexible the second parameter could be array() paramteres / context. Or if anyone got good idea for and object here.

#### Sample
```php
protected function responseAfterAdd (RequestConfiguration $configuration, array $item = [])
```

**Comment by peteward** [comment]
:+1: something like this.

**Comment by michalmarcinkowski** [comment]
@nakashu I think this is already resolved. Please reopen if there are still any issues.
