### ISSUE TITLE
Migrations - Code

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#3989]
Did Sylius figure out migrations? I know the current ones are stored in app/migrations, but they are all the automatically generated ones.

The current problem is that if you are upgrading from before all the entities had a code field, your migrations will fail because a lot of entities add a code field, and then create a unique index. Creating the index will fail if there are more than two rows in the table, as both the code fields are empty.

I manually modified my migrations to copy over a default value, either the name, id, or something else that was relevant.

**Comment by awerffeli** [comment]
i'm having the same issue when upgrading to v0.16. will probably go for the same solution as you did.
