### ISSUE TITLE
[InventoryBundle] Checking whether a product is available to order or not

### ISSUE THREAD

**Issue by kasrakhosravi** [Sylius/Sylius#3990]
Just came across this Twig extension used in (WebBundle/Frontend/Product) which apparently check to see whether a product is available to be ordered by customer or not.

```php
{% if not product.hasVariants and not sylius_inventory_is_available(product.masterVariant) %}
   ...
{% endif %}
````

But I couldn't clearly see how does this (sylius_inventory_is_available) twig extension function work? The logical thing is that when the `onHand` field in product form is 0, this function should return a `false` value but this is not the case. 

Anybody care to explain the reasoning behind this function and explain how it is possible to check for product availability?

**Comment by pjedrzejewski** [comment]
@kasrakhosravi This one is for checking if inventory is available. Default impl is here - https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Inventory/Checker/AvailabilityChecker.php

**Comment by kasrakhosravi** [comment]
:+1: Thanks Pawel

**Comment by kasrakhosravi** [comment]
@pjedrzejewski IMO the default concept of product availability checking is alittle confusing but I am only talking from my point of view and also my own limited experience. If you think I'm wrong please correct me :) 

I think that it is better to set `AvailableOnDemand` and `Backorder` by default to false because I think it will confuse shop owner that has set `onHand` to 0 and see that orders are still being submitted in the system and have no idea where to disable `backorder` or he/she had no idea that she has set `AvailableOnDemand` to true (because it is being set to true by default)

**Comment by ibasaw** [comment]
How to put the product on "out of stock" ?

i had variant choice, on master product, stock is set to 0, all my products/variant are ondemand OFF

i had no more stock available in any variant and the product always show: available !?

**Comment by michalmarcinkowski** [comment]
`AvailableOnDemand` and `Backorder` features are temporary removed. The availability checker has the logic for checking if product is "out of stock".

Please reopen if something is still not clear.
