### ISSUE TITLE
[RFC] There should be a tax rate applicable to shipping fee

### ISSUE THREAD

**Issue by axelvnk** [Sylius/Sylius#4001]
It seems like it's not yet possible to choose a tax category for your shipping method. However it is important to show the different taxes that make up for the total price at checkout. 

In the screenshot below, I have a product that go at a reduced tax rate of 6% because the product is food., but shipping costs however are bound to have a standard tax rate applied to them. Which in my country is 21%. 

<img width="446" alt="screen shot 2016-01-28 at 11 48 11" src="https://cloud.githubusercontent.com/assets/6803540/12642332/3b69a544-c5b5-11e5-9105-8dde2222693d.png">

<img width="1203" alt="screen shot 2016-01-28 at 11 56 28" src="https://cloud.githubusercontent.com/assets/6803540/12642469/3ccc3d9c-c5b6-11e5-8d9f-22bf801493ca.png">

How Sylius is right now, it only shows the shipping fee as is. Not specifying the taxes that are included in the shipping price. If you sell to companies, it's important to be specific. For consumers it's less important, but I think it's mandatory by the government laws in Belgium at least..

I already did all the changes myself in my current project. With some modifications I can apply it to the current Sylius branch.

**Comment by pjedrzejewski** [comment]
@axelvnk We just added this functionality in https://github.com/Sylius/Sylius/pull/3907, is there anything missing there? :)

**Comment by axelvnk** [comment]
Ahh, didn't see that PR. Sorry. I guess this can be closed then. :)
