### ISSUE TITLE
[RFC][User] Remove softdeletable from User and Customer entity

### ISSUE THREAD

**Issue by michalmarcinkowski** [Sylius/Sylius#4004]
Hey folks!

It's time to fix the user re-registration issue! Current problem is that because of softdelete we can't register again after the account has been removed. Related issues #1326, #2537.
#### Solution

The simplest solution for this issue is to remove softdelete from User and Customer. I would say we should start with removing the possibility to delete Customers, but instead add possibility to only remove Customer's accounts (Users). This way we will avoid broken relations issues since all relations are on the Customer and the Customer will never be removed, but will have a possibility to remove the User account.
#### Drawback

Probably expected behavior from User perspective:

```
Given I had an account in the shop
And I placed 2 orders
When I delete my account
And I register again with the same email as previous
Then I shouldn't see any orders in my orders history
```

Current logic:

```
Given I had an account in the shop
And I placed 2 orders
When I delete my account
And I register again with the same email as previous
Then I will see the 2 orders I placed before
```

Not sure about practical or legal issues for this case (every information should be deleted from the database after account removal?), so looking forward to feedback from you guys! Of course that will be better behavior than current one (not able to re-register) and there is no problem in implementing some listener that will clear Customer's history in some controlled way on re-registration etc., so IMO it's definitely a good start to tackle this.

Starting scenario should look like:

```
Given there was user „john@example.com”
But his account was deleted
When I try to register again with email „john@example.com”
Then I should be successfully registered
And I should be able to login
```

**Comment by aramalipoor** [comment]
:+1: for no softdeletable at all!

**Comment by okwinza** [comment]
Although i don't like softdeleteables too, there are number of places where it's crucial:

- Order
- Shipment method(carrier)
- User account

So just purging user information from DB is a really bad idea as this kind of info is very useful for various purposes(statistical, marketing stuff, etc).

It would be much better to change registration logic and merge accounts in case user wants to register again.

**Comment by nakashu** [comment]
Accounts should never be deleted imho, as @okwinza said, because you will loose lot of data that are crucial for the shop (statistical, marketing stuff, etc).

About legal issues, at least in EU, you should delete all data (on request, eg. delete account) by which you can identify the person explicitly.

Stuff like insurance num, email, combination of name and address should all be deleted, from legal point of view. 
But as you want to keep it for statistical purposes, you can just replace these data, with random stuff like deleted.email.24@domain.com, and replace names with "john doe", thus your legal obligations should be fulfilled.

I say keep the softdeletable, as data for reports and statistics are extremely important today for any serious e-commence. The easiest thing would be to have a unique index on (email, is_deleted). I sorted it like this in situations where I track deleted users by status (bool or int), and not by datetime.

**Comment by michalmarcinkowski** [comment]
@okwinza @nakashu I don't know why you're saying about loosing any data crucial for shop when deleting the User account does not delete any valuable information since all the Customer's information (name, email, gender, date of birth) and all relations like orders, addresses etc. are hold on Customer entity that will never be removed. We want to gather all possible information that's why there is a Customer and User separation. The Customer is a person that deals with a system, but is not registered User. Not sure how many information we can gather legally, so we will try to make it optional (togglable).

@okwinza during the registration User is associated with a Customer (you can call it merge logic), so all data are preserved. Regarding the email confirmation it is totally possible to introduce it, but the logic will remain the same (despite the fact that User account will be disabled by default and enabled only after confirmation). I may want to delete my personal data and order history from the system and I would be surprised if after registering again after my account deletion my history would show up.

@nakashu that's what I thought about the legal obligation. Looks like fulfilling the data with random strings is the only way here to be in accordance with the law. Probably we should consider that as a next step, but again this could be optional (togglable) since that's the EU law and I believe there are countries where it's not a problem to keep the data anyway.

Thanks for your feedback guys! Looking forward to more input ;)

**Comment by peteward** [comment]
:+1: @michalmarcinkowski 

I think Customer is the only situation where a resource may need to have it's data *deleted* without actually wanting to delete it, and random strings is the only way to fulfil it, not soft-deletable anyway.

Anything else you just don't allow it to be deleted *if it's been used*. Soft-deletable doesn't help, but toggleable states for things like 'old' shipping methods that may not be used anymore but still have historical relevance is important.

However there is still a use-case for 'deleting' - and that's mistakes or tests. It's possible that someone places a test order and they explicitly DO want to delete it - to remove it from skewing statistical data. Likewise if an Admin user creates a resource, such as a promotion or shipping type, they need the ability to remove that resource if it's never been used. Quite often we have new team members who "play around" in the admin system trying out features and checking if something is possible, they need to be able to delete things if doing so has no negative impact on the system. 

But yes, soft-deletable doesn't seem to offer much in any use-case I can think of (#3654).

**Comment by okwinza** [comment]
Agree with @peteward :+1:

**Comment by michalmarcinkowski** [comment]
That's exactly what we want to achieve.

I would say we will have 3 actions for customer in the backend:
1. Delete account - hard delete User account, but leave Customer untouched
2. "Mask" Customer - fill customer's sensitive data with random stuff, leave it in the database
3. Delete Customer - hard delete Customer, all his addresses, orders, details

@peteward thanks for input, we're going to smash #3654 next week! :)
