### ISSUE TITLE
[API] Broken index endpoints.

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#4018]
For now I have found at least 4 broken routes. They are: 

```
/api/products/
/api/orders/
/api/checkouts/
/api/users/
```

You are not able to check theirs index, but show endpoint works totally properly. Something is probably broken with serialize configuration. Since these endpoints are quite crucial we should fix them immediately.

**Comment by pjedrzejewski** [comment]
@lchrusciel They are broken on demo.sylius.org too, I assume it's too deep serialization. We need to write tests for them. Ideally I'd write a blog post about this because we have ApiTestCase in and everything but wheeen... :/

**Comment by lchrusciel** [comment]
I have tried to cover /api/orders/ with some tests when I met this problem. Maybe I will be able to fix this.

**Comment by michalmarcinkowski** [comment]
@lchrusciel after merging [this](https://github.com/Sylius/Sylius/pull/4037), which endpoints are still not working?
