### ISSUE TITLE
How can I redirect user to a step directly ?

### ISSUE THREAD

**Issue by jbinfo** [Sylius/Sylius#4027]
I have a user register form with four steps.

If a user logout before to complete all steps, on the next login the user is redirected to the step left, but when I do that it redirect me to the first step ?

**Comment by jbinfo** [comment]
@aRn0D @michalmarcinkowski @winzou

**Comment by pjedrzejewski** [comment]
@jbinfo Could you give us more info? Are you using Sylius as a whole? What do you mean by 4 steps in registration?

**Comment by jbinfo** [comment]
@pjedrzejewski I'm using only the FlowBundle, when the user register(signup), it's required to fill more infos, about four steps, each step contains a form, if for example the user leave the website and return to login, I redirect user to the step who is on the last time.

Suppose the user is on the third step, when login event, I redirect user to the third step, but it's not working because the context initialization I think? how to accomplish that

**Comment by jbinfo** [comment]
@pjedrzejewski any update please ?

**Comment by pjedrzejewski** [comment]
@jbinfo Do you have any code replicating the issue? Because it is really hard to guess what is going on if you are not using Sylius but custom implementation. FlowBundle currently uses session to save steps, so if you logout - you will loose information about the steps. :/

**Comment by jbinfo** [comment]
Okey, I think I have found a solution, save the current step on DB and after login try to check if all steps are done if not then redirect to the current step.
```php
// ....

$scenario = $this->container->get('sylius.process.coordinator')->loadScenario($scenarioAlias);
$process = $this->container->get('sylius.process.builder')->build($scenario);
$process->setScenarioAlias($scenarioAlias);

$step = $process->getStepByName($user->getRegisterStep()); // $user->getRegisterStep() is where the step name is saved on DB

$this->flowContext->initialize(
    $process,
    $step
);

$this->flowContext->addStepToHistory(
    $this->flowContext->getCurrentStep()->getName()
);

$url = $this->router->generate(
    'sylius_flow_display',
    [
        'scenarioAlias' => $user instanceof Talent ? 'tfr' : 'cfr',
        'stepName' => $this->flowContext->getCurrentStep()->getName(),
    ]
);

return new RedirectResponse($url);

// ....
```
