### ISSUE TITLE
[RFC] Taxonomy why Nested Sets pattern?

### ISSUE THREAD

**Issue by olegatro** [Sylius/Sylius#4033]
Hi, sorry if my question not clever. 

Why  taxonomy build on nested sets pattern ? I read about some trees patterns, and think closure table pattern more flexible and ease create request (my opinion). Closure table allow a taxon to belong to multiple trees.

**Comment by pjedrzejewski** [comment]
If I remember correctly, Doctrine Extensions were not supporting ``closue-table`` strategy when we implemented this. Thanks for the suggestion, I will definitely have a look! :+1:

**Comment by michalmarcinkowski** [comment]
Hi Oleg,

I wanted to take a deeper look at Closure tables, but didn't have time yet. Did you do some comparison of these two patterns? Maybe you can share your thoughts with us?

Nested set comes with an expensive costs for update, insert and delete operations, but is fast for querying what is the most important for categorization. I'm not sure if we need to allow one taxon to belong to multiple trees, can you give a use case for that?

**Comment by okwinza** [comment]
The only decent example i could come up with is when you want to highlight some taxons i.e. create new taxonomy named SALE/Editor choice/Whatever.  With our current implementation you're forced to do such thing on product level while closure table allows you to just add an additional parent node for your taxon leaving products untouched.

On the other hand, closure table is expensive on large trees and depth level.

Just my 5 cents.

**Comment by nakashu** [comment]
What @okwinza said is the usecase we also use, but mostly for seasonal highlighting.
As seasons tend to repeat, doing these changes on product level is very timeconsuming if you got more than 50 products.

**Comment by okwinza** [comment]
Seems like Doctrine Extensions does support CT: https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/tree.md#closure-table

I will try to mess with it in the upcoming days. Cause it make sense to switch our current strategy.
