### ISSUE TITLE
[RFC] Follow-up emails

### ISSUE THREAD

**Issue by koemeet** [Sylius/Sylius#4039]
In about one or two months, I will need to implement this feature. With follow-up emails I mean for example that if you buy a medicine and that medicine lasts for two weeks, you will get an e-mail in two weeks that reminds you that you have to re-buy that medicine, because it is almost empty. I think this is a great way to interact with your customers, and maybe you want this in Sylius Core?

Are you guys implementing this feature yourself, if so, what would be the planning on this. Otherwise, I would gladly help and provide a PR in the coming month.

It might be a good idea to share some thoughts on this subject.

For example, should we allow store owners to assign e-mails to certain products, and those e-mails can be delayed (for example the two weeks from my example above).

Also, we probably need cron jobs, is a solution for this already present in Sylius? What would be a good path to follow here.

**Comment by pjedrzejewski** [comment]
For 1.0 minimum we want following e-mails:

* Customer welcome e-mail;
* Forgot password reminder;
* Order e-mail;
* Shipment e-mail;
* Order notification for e-mail admin;

That would be it for the "minimum", then we perhaps have a look at payment reminders, follow-ups, etc.

That being said, we should definitely discuss and figure out unified approach for managing these e-mails. Right now we have these ``email_managers`` and works good although naming could be possibly improved. And of course most of them should be attached to state machine, not listeners.

Quick thoughts from top of my head, happy to hear more and I will hopefully describe it in more detail soon.

**Comment by okwinza** [comment]
@pjedrzejewski do we have something of your list in core or it is still on paper? And can you tell more about these `email_managers ` please? I'm facing the same task right now.

**Comment by pjedrzejewski** [comment]
So far we have this: https://github.com/Sylius/Sylius/tree/master/src/Sylius/Bundle/CoreBundle/EmailManager

Right now they are attached to events though, and should be to state machine. So dev can decide whether to send the order confirmation e-mail when checkout is completed or when the order is paid etc.

The plan for emails and pretty much most of logic in Sylius is right now:

![MEME](http://i.imgur.com/qXs8qqf.jpg)

**Comment by inssein** [comment]
not true @pjedrzejewski, I re-did them so that they were attached to the state machine (https://github.com/Sylius/Sylius/blob/322157b1f02dd1b101c2b13588b876de79b7dbdb/src/Sylius/Bundle/CoreBundle/Resources/config/state-machine.yml#L122).

**Comment by gabiudrescu** [comment]
@pjedrzejewski we already have something implemented regarding these two:

- Forgot password reminder;
- Order e-mail;

if you want, we can share the code and see if it can be open sourced.

**Comment by pjedrzejewski** [comment]
@inssein Ah, right! Sorry I totally forgot. :+1: 

@gabiudrescu Sure thing! I will be glad to have a look.
