### ISSUE TITLE
Entity class 'Talent' used in the discriminator map of class 'AppBundle\Entity\User' does not exist

### ISSUE THREAD

**Issue by jbinfo** [Sylius/Sylius#4046]
I want to work with `SyliusMailerBundle` to manage mails, when I try to execute this command:
```shell
php app/console doctrine:schema:update --force
```
It show me this error:
```
[Doctrine\ORM\Mapping\MappingException]                                                               
Entity class 'Talent' used in the discriminator map of class 'AppBundle\Entity\User' does not exist. 
```
When I remove `SyliusMailerBundle` and `SyliusResourceBundle` from `AppKernel` the problem gone.

My `User` entity:
```php
/**
 * @ORM\Entity
 * @ORM\Table(name="`user`")
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({"talent"="Talent", "company"="Company"})
 */
abstract class User extends BaseUser
{
    // ....
}
```
I have two types of user `Talent` and `Company` that extends the `User` entity.

I have found an entry on the `sylius-dev` Google group same problem: https://groups.google.com/forum/#!topic/sylius-dev/MgzLzgDKIxY

Any advice please, thank you.

**Comment by michalmarcinkowski** [comment]
Try mapping your class as `MappedSuperclass`.

**Comment by pjedrzejewski** [comment]
@jbinfo I have never tried but I am pretty sure this won't work... having 2 different user classes with SyliusUserBundle. We would like to support it, but right now it is not the case, most likely.

**Comment by jbinfo** [comment]
@pjedrzejewski I'm working with `FOSUserBundle` and `PUGXMultiUserBundle` what I want is only the `SyliusMailerBundle` to manage mails.

**Comment by jbinfo** [comment]
@michalmarcinkowski Do you think if I changer `User` entity to be `MappedSuperclass` still work with `FOSUserBundle` ?

**Comment by pjedrzejewski** [comment]
@jbinfo No, if you use FOSUserBundle then it should be fine. Did you register Company and Talent as resources in SyliusResourceBundle? It can be that SRB does not support entities with discriminator maps.

**Comment by jbinfo** [comment]
@pjedrzejewski No, I didn't register any resource, my config file:
```yml
sylius_mailer:
    driver: doctrine/orm # Configure the doctrine orm driver used in the documentation.
    sender:
        name: My website
        address: no-reply@my-website.com
```
Right now I don't use SRB in my app, it's just a hard dependency for `SyliusMailerBundle`

**Comment by pjedrzejewski** [comment]
Well, then it is really strange, because Sylius bundles should not affect it then. Have you tried replacing "Talent" with full class name? (with namespace)

**Comment by jbinfo** [comment]
@michalmarcinkowski @pjedrzejewski it's working with `MappedSuperclass` the doctrine update command now execute without error and in database there is a table `sylius_email`. 

My new `User` entity annotations definition:
```php
/**
 * @ORM\Entity
 * @ORM\Table(name="`user`")
 * @ORM\InheritanceType("JOINED")
 * @ORM\MappedSuperclass()
 */
abstract class User extends BaseUser
{
    // ....
}
```

Thank you :)

**Comment by steffenbrem** [comment]
@jbinfo Great you've found a solution :+1: If everything is resolved, could you close this issue please?

**Comment by jbinfo** [comment]
@steffenbrem done, thank you.

**Comment by pjedrzejewski** [comment]
:+1:

**Comment by aa-ahmed-aa** [comment]
I get the same error with message
```
Entity class 'BotmeCategory' used in the discriminator map of class 'Botme\ECommerceBundle\Entity\Category' does not   
  exist.
```
where should i use `MappedSuperclass`
