### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by fabirus** [Sylius/Sylius#4048]
Hello, the french translator don't translate all the text in adminstration area...
Thanks You

**Comment by tristanbes** [comment]
You can help translate french words here: http://translate.sylius.org/project/sylius/fr#

**Comment by pjedrzejewski** [comment]
@fabirus We are constantly working on the translation on Crowdin platform as Tristan has pointed out above. If you want to help out, please have a look there! :) Thanks!
