### ISSUE TITLE
translation and currencies not showing

### ISSUE THREAD

**Issue by fabirus** [Sylius/Sylius#4058]
hello translation and currencies not showing in the layout.html.twig of webbundle

Thanks you

**Comment by pjedrzejewski** [comment]
@fabirus Could you give us a bit more detail, please? What do you mean by that? You need to load fixtures or configure currencies and locales.

**Comment by fabirus** [comment]
i loaded fixtures but it don't showing in the layout ```
<div class="locale-menu masthead pull-right">
                {{ knp_menu_render('sylius.frontend.locale', {'template': 'SyliusWebBundle:Frontend:menu.html.twig'}) }}
            </div>
            <div class="currency-menu masthead pull-right">
                {{ knp_menu_render('sylius.frontend.currency', {'template': 'SyliusWebBundle:Frontend:menu.html.twig'}) }}
            </div>
```

**Comment by BenjaminGoetz** [comment]
I got the same problem, here.

After you mentioned loading fixtures I did a `doctrine:fixtures:load` and a `doctrine:phpcr:fixtures:load` but to no avail.

You also mentioned configuring currencies and locales, can you be more specific? Can you, for example, give me a link to the corresponding documentation?

**Comment by michalmarcinkowski** [comment]
WebBundle was removed. Translations and currencies are working correctly on the current shop :)
