### ISSUE TITLE
composer install fails symfony-cmf/routing-bundle ^1.4.0-RC1

### ISSUE THREAD

**Issue by pfwd** [Sylius/Sylius#4059]
Running composer install I get

    composer install
    You are running composer with xdebug enabled. This has a major impact on runtime performance.      See https://getcomposer.org/xdebug
     Loading composer repositories with package information
     Installing dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.

      Problem 1
         - Installation request for sylius/sylius dev-master -> satisfiable by sylius/sylius[dev-master].
         - sylius/sylius dev-master requires symfony-cmf/routing-bundle ^1.4.0-RC1 -> no matching package found.

    Potential causes:
     - A typo in the package name
     - The package is not available in a stable-enough version according to your minimum-stability setting
     see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

    Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems

I'm not sure if this is an issue with Sylius or symfony-cmf/routing-bundle

My composer.json

    {
    "name":        "sylius/sylius-standard",
    "description": "Sylius Standard Edition, base application for Sylius powered E-Commerce projects.",
    "keywords":    ["symfony", "symfony2", "sylius", "distribution", "ecommerce", "cart", "shopping"],
    "type":        "project",
    "license":     "MIT",
    "homepage":    "http://sylius.org",
    "authors": [
        {
            "name":     "Paweł Jędrzejewski",
            "homepage": "http://pjedrzejewski.com"
        },
        {
            "name":     "Sylius project",
            "homepage": "http://sylius.org"
        },
        {
            "name":     "Community contributions",
            "homepage": "http://github.com/Sylius/Sylius/contributors"
        }
    ],
    "require": {
        "php":                          ">=5.3.3",
        "sylius/sylius":                "dev-master",
        "doctrine/migrations":          "~1.0@dev",
        "sensio/generator-bundle":      "~2.3"
    },
    "require-dev": {
        "behat/behat":                  "~3.0",
        "behat/symfony2-extension":     "~2.0",
        "behat/mink-extension":         "~2.0",
        "behat/mink-browserkit-driver": "~1.2",
        "behat/mink-selenium2-driver":  "~1.2",
        "behat/mink":                   "~1.6",
        "coduo/php-matcher":            "~1.0",
        "phpspec/phpspec":              "~2.1",
        "phpunit/phpunit":              "~4.1",
        "stfalcon/tinymce-bundle": "dev-master"
    },
    "scripts": {
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Symfony\\Cmf\\Bundle\\CreateBundle\\Composer\\ScriptHandler::downloadCreateAndCkeditor",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Symfony\\Cmf\\Bundle\\CreateBundle\\Composer\\ScriptHandler::downloadCreateAndCkeditor",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ]
    },
    "autoload": {
        "psr-0": {
            "": "src/",
            "Context": "features/"
        }
    },
    "config": {
        "bin-dir": "bin"
    },
    "extra": {
        "branch-alias": {
            "dev-master": "0.17-dev"
        },
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        }
    }
}

**Comment by okwinza** [comment]
try requiring `dev-master` of routing-bundle instead.

**Comment by pfwd** [comment]
@okwinza Yes the fix in my case was to add 
    
    "symfony-cmf/routing-bundle": "dev-master"

to my composer.json file. I'm not sure this is the best fix though. Surely any Sylius dependencies should be managed by the Sylius composer.json

**Comment by okwinza** [comment]
Well, travis is doing fine so it has to be something on your end. I will
dig it further in the nearest future tho.

**Comment by michalmarcinkowski** [comment]
We updated to the stable version. Should be resolved.
