### ISSUE TITLE
slideshows frontend template

### ISSUE THREAD

**Issue by fabirus** [Sylius/Sylius#4062]
hello please how can edit the slideshows template render in frontend...
Thanks you

**Comment by pjedrzejewski** [comment]
Sorry, slideshows are not properly supported and will most likely be removed for now, until we have time to properly implement both backend and frontend. That being said, you should be able to customize the template quite easily, have a look at http://symfony.com/doc/current/cmf/bundles/block/types.html#render-the-slideshow.

**Comment by fabirus** [comment]
i have the latest sylius how can remove it??

**Comment by pjedrzejewski** [comment]
@fabirus Remove what? You can create your own template and use it for rendering the slideshow according to the cmf docs. :)

**Comment by ibasaw** [comment]
just override the gallery.html.twig

**Comment by michalmarcinkowski** [comment]
Sylius uses Stackoverflow as its official support channel. For future support questions please post at http://stackoverflow.com/questions/tagged/sylius and tag your questions with sylius.
