### ISSUE TITLE
Attribute autocomplete

### ISSUE THREAD

**Issue by xantrix** [Sylius/Sylius#4063]
Hi guys, for a client I need to have an product attribute containing a very large list of values (about 20k, a set of different Materials) and I can’t split these in different attributes.

I’m not sure if [Choice attribute type](https://github.com/Sylius/Sylius/pull/3948) aims to handle also a case like this so I’m going to:
1. Use a normal text field attribute
2. Make a dedicate CRUD interface (outside of Sylius, in my project) to handle these values (with Translations)
3. Hack the Sylius backend attribute to show up a sort of [select2](https://select2.github.io/) widget and autocomplete values from a dedicated json endpoint

Should [Choice attribute type](https://github.com/Sylius/Sylius/pull/3948) support large set of values or this is a different feature ?

**Comment by pjedrzejewski** [comment]
What you are doing makes 100% sense, choice type is definitely not suitable for storing 20k different choices, because the options are stored in serialized configuration.

I will leave this open to maybe have some discussion but as I said, your solution is the way to go IMO. :)

**Comment by xantrix** [comment]
Thanks a lot for your immediate feedback @pjedrzejewski :) I will follow these steps for now :+1:

**Comment by gabiudrescu** [comment]
I'd also be interested in this development. @xantrix do you take into consideration in open sourcing this?

**Comment by xantrix** [comment]
hey @gabiudrescu sure! I can do these steps with a PR in a separate fork or a gist, because I if understand well the Sylius implementation will be different. I will write back here as soon I have something ready !
