### ISSUE TITLE
Issue with PaymentProvider when order amount = 0 on purchase

### ISSUE THREAD

**Issue by awerffeli** [Sylius/Sylius#4066]
I experienced this problem when using a voucher that reduces the order amount to 0. On purchase the user gets redirected the payment provider which returns an error because the passed amount is 0. I wonder if it's better to address this issue in `PurchaseStep` or in the GatewayFactory's Actions or somewhere else. Does anyone have any thoughts on this?

**Comment by michalmarcinkowski** [comment]
Same as https://github.com/Sylius/Sylius/issues/5961.
