### ISSUE TITLE
Problem overriding ProductTranslation validation

### ISSUE THREAD

**Issue by gperdomor** [Sylius/Sylius#4068]
Hi everyone!...

I need to change the validation parameters in product translations.

<pre><code>sylius_product:
    resources:
        product:
            classes:
                ...
            translation:
                classes:
                    ...
                validation_groups:
                    default: [my_custom_group]
</code></pre>

I only use the description field, and only need validate the min length. This is the validation file:
<pre><code>Sylius\Component\Product\Model\ProductTranslation:
    properties:
        description:
            - Length:
                min: 200
                minMessage: sylius.product.description.min_length
                groups: [my_custom_group]</pre></code>

The parameters in container are updated:

<pre><code>sylius.validation_groups.product                          ["Default","sylius"]                                                                                    
sylius.validation_groups.product_archetype                ["Default","sylius"]                                                                                    
sylius.validation_groups.product_archetype_translation    ["Default","sylius"]                                                                                    
sylius.validation_groups.product_attribute                ["Default","sylius"]                                                                                    
sylius.validation_groups.product_attribute_translation    ["Default","sylius"]                                                                                    
sylius.validation_groups.product_attribute_value          ["Default","sylius"]                                                                                    
sylius.validation_groups.product_option                   ["Default","sylius"]                                                                                    
sylius.validation_groups.product_option_translation       ["Default","sylius"]                                                                                    
sylius.validation_groups.product_option_value             ["Default","sylius"]                                                                                    
sylius.validation_groups.product_translation              ["Default","my_custom_group"]                                                                                   
sylius.validation_groups.product_variant                  ["Default","sylius"]   
</code></pre>

But... In the creation form still see the original validations :(...

I need to do something else?

**Comment by pjedrzejewski** [comment]
In creation form, you are using ``sylius_product`` form type and it uses validation groups of products. This would work if you edit translation directly through ``sylius.controller.product_translation:updateAction``. So you need to configure validation_group per form, not per entity really. :( No easy way to improve that unfortunately, at least at this point.

**Comment by gperdomor** [comment]
@pjedrzejewski mmmm...

In <code>createAction</code> and <code>updateAction</code> of <code>ResourceController</code> this code is called <code>$form = $this->getForm($resource);</code> but <code>getForm</code> has a second parameter and we can pass form options to the form, including <code>validation_groups</code>. What do you think about handle this options in the route configuration? something like this:

<code><pre>sylius_product_create:
    path: /new
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.product:createAction
        _sylius:
            template: ...
            form: some_sylius_form
            form_options:
                validation_groups: some_validation_groups
                another_option: ...
                ...
            redirect: sylius_backend_product_index
</pre></code>

In the controller we can have something like: <code>$form = $this->getForm($resource, $this->getFormOptions());</code>

**Comment by pjedrzejewski** [comment]
I was thinking about adding this feature. Maybe to keep things consistent we could have config like:

```yaml
_sylius:
    form: foo

and

_sylius
    form:
        type: foo
        options:
            display_pricing: true
```

**Comment by gperdomor** [comment]
@pjedrzejewski done in #4101 using your syntax :D

**Comment by michalmarcinkowski** [comment]
Done in #4101
