### ISSUE TITLE
Access denied to sylius_backend_product_association_type_index

### ISSUE THREAD

**Issue by pfwd** [Sylius/Sylius#4070]
I've just updated to 0.17.0-dev and ran all the migrations and I cannot access the product association page.
example.com/administration/product-association-types/

These are my admin roles:

ROLE_USER
ROLE_SYLIUS_ADMIN
ROLE_ADMINISTRATION_ACCESS

**Comment by pjedrzejewski** [comment]
@pfwd Same suggestion as in #4071.

**Comment by pfwd** [comment]
Fixed after running

    sylius:rbac:initialize
