### ISSUE TITLE
Access Denied to sylius_backend_metadata_container_customize

### ISSUE THREAD

**Issue by pfwd** [Sylius/Sylius#4071]
This could be related to #4070 
I've just updated to 0.17.0 and I cannot access /administration/metadata/customize/Product-112
Is there anything I need to alter to the existing products. I have ran the migrations etc..

My roles are
ROLE_USER
ROLE_SYLIUS_ADMIN
ROLE_ADMINISTRATION_ACCESS

**Comment by pjedrzejewski** [comment]
@pfwd Have you run ``sylius:rbac:initialize``?

**Comment by pfwd** [comment]
Yes that solved it. Thanks
I didn't see that in the upgrade doc

I will close both of the issues

**Comment by pjedrzejewski** [comment]
:+1:
