### ISSUE TITLE
[Support Request] Missing pages and content after upgrading to 0.17

### ISSUE THREAD

**Issue by pfwd** [Sylius/Sylius#4073]
I created pages, routes and simple blocks before upgrading from 0.16 to 0.17 and now they are missing in Sylius admin area.
I can see them in the database via the ` php app/console doctrine:phpcr:node:dump --prop` command.
I can see differences between the old and new pages like so:

Old missing pages:
```
  - phpcr:class = Symfony\Cmf\Bundle\ContentBundle\Doctrine\Phpcr\StaticContent
  - phpcr:classparents = Array(    [0] => Symfony\Cmf\Bundle\ContentBundle\Model\StaticContentBase    [1] => Symfony\Cmf\Bundle\ContentBundle\...
```

New pages:
```
  - phpcr:class = Sylius\Bundle\ContentBundle\Document\StaticContent
  - phpcr:classparents = Array(    [0] => Symfony\Cmf\Bundle\ContentBundle\Model\StaticContentBase    [1] => Symfony\Cmf\Bundle\ContentBundle\...
```

I'm guessing that the difference in phpcr:class is the issue. 
Does anyone know how I can migrate the old content so it shows in the Sylius admin?

**Comment by steffenbrem** [comment]
@pfwd I think the best solution is to run a migrate class on your current dataset, `doctrine/phpcr-odm` has a command for this, it's called `doctrine:phpcr:document:migrate-class`.

Available Symfony console command for phpcr odm are:

```
doctrine:phpcr:document:convert-translation      Convert fields to translated or back to untranslated, and between different strategies after a refactoring.
doctrine:phpcr:document:migrate-class            Update the class name stored in the repository, e.g. after refactoring.
doctrine:phpcr:fixtures:load                     Load data fixtures to your PHPCR database.
doctrine:phpcr:init:dbal                         Prepare the database for Jackalope Doctrine-Dbal.
doctrine:phpcr:jackrabbit                        Start and stop the Jackrabbit server
doctrine:phpcr:mapping:info                      Shows basic information about all mapped documents
doctrine:phpcr:mapping:verify-unique-node-types  Verify that documents claiming to have unique node types are truly unique
doctrine:phpcr:migrator:migrate                  Migrates PHPCR data.
doctrine:phpcr:node-type:list                    List all available node types in the repository
doctrine:phpcr:node-type:register                Register node types in the PHPCR repository
```

**Comment by pjedrzejewski** [comment]
@steffenbrem Nice, I did not know about this command. :+1:

**Comment by steffenbrem** [comment]
@pjedrzejewski You also have a phpcr migrations bundle from dantleech (https://packagist.org/packages/dantleech/phpcr-migrations-bundle). I haven't used it, but it might be worth looking at to prevent future changes.

**Comment by pfwd** [comment]
Thank you @steffenbrem  running:
`php app/console doctrine:phpcr:document:migrate-class "Symfony\Cmf\Bundle\ContentBundle\Doctrine\Phpcr\StaticContent" "Sylius\Bundle\ContentBundle\Document\StaticContent"`

Worked the magic

@pjedrzejewski I think we should put this in the upgrade notes just in case someone else hits this issue
