### ISSUE TITLE
Convert to default currency

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius#4075]
I have following use case:

I have some prices stored in the system. Prices have different currencies, e.g.:

| Price        | Currency  |
| ------------ |-----------|
| 24           | EUR       |
| 45           | USD       |
| 112          | PLN       |

And I want to convert them to default currency.

Looks like not possible as it can only convert from the default currency.

How should we approach this?

**Comment by michalmarcinkowski** [comment]
Right now the convert does `$valueInBaseCurrency * $currency->getExchangeRate()`, in order to make it work the other way around we should do `$valueInOtherThanBaseCurrency / $currency->getExchangeRate()`. I would implement `convertToBase` method to handle this.

**Comment by umpirsky** [comment]
Another approach would be to make `convert()` more flexible with optional third parameter `convert($amount, $from, $to)`. But that would be a BC break.

**Comment by michalmarcinkowski** [comment]
If you're willing to contribute then I would go for making two separate methods in `CurrencyConverter` class:
 * `convertFromBase($amount, $targetCurrencyCode)`
 * `convertToBase($amount, $actualCurrencyCode)`

Let's do all the BC breaks ASAP.

**Comment by umpirsky** [comment]
@michalmarcinkowski In addition, we can leave `convert()` and mark it deprecated and remove it in the next version.

**Comment by michalmarcinkowski** [comment]
Sounds like a good plan :+1:

**Comment by pjedrzejewski** [comment]
@umpirsky @michalmarcinkowski ``convertToBase($amount, $sourceCurrencyCode)``?

**Comment by michalmarcinkowski** [comment]
@pjedrzejewski :+1: I lacked that word :smile:

**Comment by umpirsky** [comment]
@pjedrzejewski :+1:
