### ISSUE TITLE
Installation problems on MAC + MAMP

### ISSUE THREAD

**Issue by jeroendesloovere** [Sylius/Sylius#4078]
**Problem**
Hi, in the last year I've tried a lot of times to install Sylius.
Unfortunately **I've never been able to get Sylius installed**.
There is always an error being thrown in one of the installation steps.

It is really frustration to not getting this to work.
I'm using a MAC and MAMP Pro.

**Latest error**
Today I tried the installation again in the hope that it would work for once...
I used:
```bash
composer create-project sylius/sylius-standard my_project
cd my_project
app/console sylius:install
```
Seems like I'm stuck in ```sylius:install``` step 1 today.
![schermafbeelding 2016-02-08 om 14 59 56](https://cloud.githubusercontent.com/assets/588616/12887452/a5448ac0-ce74-11e5-9a30-30e460484bac.png)

**What is the MAMP Pro path?**
What do I need to fill in into ```sylius.database.path: /Applications/MAMP/db``` ?
Normally I need to fill in a ```database.unix_socket:   /Applications/MAMP/tmp/mysql/mysql.sock # only when using MAMP``` to get a sylius project to work on MAMP PRO.

Can anybody point me in the right direction?

**Comment by pamil** [comment]
You need to install `intl` extension, I don't have any idea how to do it in MAMP, have never been using it.

**Comment by jeroendesloovere** [comment]
I'll try to install ```intl extension```.

**Comment by jeroendesloovere** [comment]
**How I installed INTL extension**
I've managed to get ```intl extension``` installed using the [following instructions](http://codingexplained.com/operating-systems/mac/installing-php-intl-extension-os-x-mavericks)

**How I fixed database for Mac + MAMP**
Then I fixed my config and parameters file using https://github.com/Sylius/Sylius/issues/2343

**Memory limit problem**
Then I had a memory limit problem.
![schermafbeelding 2016-02-11 om 17 49 12](https://cloud.githubusercontent.com/assets/588616/12983221/9425adc0-d0e8-11e5-85a9-41dcd59e0715.png)

Which I fixed by doing:
```bash
vi /etc/php.ini
```
Then changed
```bash
memory_limit = 1G
```
Pressed **esc** and then **ctrl-z** 
and again **ctrl-z**

Then did
```bash
php app/console sylius:install
```

**Comment by michalmarcinkowski** [comment]
That's great you managed to resolve this! Thanks for a detailed solution! :+1:
