### ISSUE TITLE
[Behat] Replace DefaultFranceChannelFactory with DefaultChannelFactory

### ISSUE THREAD

**Issue by michalmarcinkowski** [Sylius/Sylius#4082]
Current `DefaultFranceChannelFactory` creates single "France" channel and also "France" country and zone, but it shouldn't. The idea is to replace it with `DefaultChannelFactory` whose sole responsibility will be creating default channel. Then in the separate steps we will define zones and shipping countries (as we do already).

**Comment by michalmarcinkowski** [comment]
After giving it some thoughts together with @pjedrzejewski we agreed to have the following:
 * `Given the store operates on a single channel` - this step will only create an 'empty' channel
 * `Given the store operates on a single channel in "France"` - this step will create a preconfigured channel for France, it means:
  * Set EUR as default currency
  * Create "France" country and zone

This will reduce the backgrounds for scenarios where this details are not necessary.

**Comment by pjedrzejewski** [comment]
:+1:
