### ISSUE TITLE
[RFC] Rename Shipment.items => Shipment.units?

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4083]
Since in full-stack Sylius a Shipment.item is an OrderItemUnit (not OrderItem) this could get confusing very quickly.

wdyt?

**Comment by pjedrzejewski** [comment]
@peteward Sounds reasonable to me, as it tracks individual units anyway.

**Comment by michalmarcinkowski** [comment]
Thanks for your contribution! :+1:
