### ISSUE TITLE
Order shipping methods by channel

### ISSUE THREAD

**Issue by yopop666** [Sylius/Sylius#4086]
Hi,
I'm trying to make all checkout steps in one page with ajax calls on checkout routes, but when get shipping method form, the app shows me all shipping methods, not current channel shipping method.

In **Sylius\Bundle\CoreBundle\Form\Type\Shipping\ShippingMethodChoiceType** **$options['channel']** is null even if it is settend  in **Sylius\Bundle\CoreBundle\Form\Type\Checkout\ShippingStepType**. It is like somewhere channel is unset.

If I make standard sylius checkout the shipping methods are correct.

Please give some help.

Thanks.

**Comment by michalmarcinkowski** [comment]
What is your strategy for resolving channels? Do you resolve channel based on `url` or some other criteria? Does it work for not ajax calls?

**Comment by yopop666** [comment]
I leave existing sylius channel resolver**$channel = $this->channelContext->getChannel()**. It works for not ajax calls. I tested on ajax call and in **Sylius\Bundle\CoreBundle\Form\Type\Checkout
ShippingStepType**  

```
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $options = array('criteria' => $options['criteria'], 'channel' => $this->channelContext->getChannel());
        $builder
            ->add('shipments', 'collection', array(
                'type'    => 'sylius_checkout_shipment',
                'options' => $options
            ))
        ;
    }
```
In builder the channel is corect  , but in **sylius_checkout_shipment** form type ```$options['channel']``` is **null**.

**Comment by pjedrzejewski** [comment]
We should not use the context here, but get the channel from underlaying data = order. That would eliminate this bug.

**Comment by yopop666** [comment]
Thank you for help.

**Comment by pjedrzejewski** [comment]
It is still an issue, I will leave this open. :)

**Comment by michalmarcinkowski** [comment]
It's shouldn't be an issue anymore :)
