### ISSUE TITLE
How to set a Product price correctly

### ISSUE THREAD

**Issue by xantrix** [Sylius/Sylius#4087]
Guys this should be trivial but I’m not completely sure about how to set a price with decimal part in a product.
I’m doing a migration script creating products programmatically and I’m using $variant->setPrice(); that accepts only an integer.

Which helper class should I use?

**Comment by pjedrzejewski** [comment]
@xantrix Sylius operates on all money values as integers. So if you want 99.99 price -> use 9999. Let me know if you need any further help. I will leave it open.

**Comment by okwinza** [comment]
@pjedrzejewski this is quite odd solution IMO. What's the reason behind not using floats?

**Comment by pjedrzejewski** [comment]
@okwinza Because you lose precision with floats - http://stackoverflow.com/questions/3730019/why-not-use-double-or-float-to-represent-currency any few other articles, good read can be http://programmers.stackexchange.com/questions/171798/how-to-handle-monetary-values-in-php-and-mysql.

**Comment by pjedrzejewski** [comment]
"If I had a dime for every time I've seen someone use FLOAT to store currency, I'd have $999.997634" -- Bill Karwin

**Comment by steffenbrem** [comment]
@pjedrzejewski You could also use a value object to represent `Money`, not sure if this is something you want in Sylius, but it might improve usability.

**Comment by michalmarcinkowski** [comment]
@steffenbrem we plan to introduce the money value object. Probably https://github.com/moneyphp/money but there will be a separate RFC about that :)

**Comment by xantrix** [comment]
Great, so it should be simple as this:

```
//two examples
//4,912 := 491200
//49.12 := 4912
$intPrice =  (int)( number_format($data['old_db_price'], 2, '.', '') * 100);
$product->getMasterVariant()->setPrice($intPrice);
```

Thanks for your support :)

P.s. :+1:  for money value object.

**Comment by steffenbrem** [comment]
@xantrix Yes you are right, multiply your floats or doubles by `100` and cast it to be an integer and you are doing it fine :+1:.

**Comment by xantrix** [comment]
@steffenbrem sure! Thanks!
