### ISSUE TITLE
[RFC] Set prefer-stable: true in all composer.json files

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#4088]
According to discussion https://github.com/Sylius/Sylius/pull/4056/files#r52156361. Thoughts?

**Comment by pamil** [comment]
Obviously I'm for it :+1:

**Comment by michalmarcinkowski** [comment]
I don't see any drawbacks of this, so :+1:

**Comment by acrobat** [comment]
This issue can closed as all the missing "prefer-stable" properties were added in #4415

**Comment by pjedrzejewski** [comment]
@acrobat :+1:
