### ISSUE TITLE
Rename "Offline" to "Cash" or "Check" in scenarios

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#4091]
"Offline" is name of gateway in Sylius, but you will rarely or never see "Offline" as customer. We should use something along these lines:
- Pay with cash
- Cash
- Check
- Pay on pick-up

**Comment by aramalipoor** [comment]
Cash on Delivery

**Comment by gabiudrescu** [comment]
:+1: for Cash on Delivery - I think this is the most established eCommerce term.

Why I don't like the others:
- Pay with cash - does not _feel_ natural for me - no other objective reason
- Cash - too simple, not enough details
- Check - nobody pays with checks in Europe and I believe in USA they're dead also
- Pay on pick-up - this can be confusing for shops that deliver to their own kiosks or something similar :)

Personally, I like "Offline" but if Sylius wants to approach DDD, my lucky guess is "Offline" is not a very common term in the eCommerce domain when you talk about payments with customers.
