### ISSUE TITLE
Sorting order by customers' last names scenario is back again

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#4098]
I removed it in #3978 as the last names were randomly generated and the scenario wasn't easy to implement correctly on old Behat contexts. It came back in https://github.com/Sylius/Sylius/commit/417acc36becb8c36dff25f3dde13792d5f2601b7#diff-921f4f8a959926bd284ae3051441dad5R115 and should be removed again :)

**Comment by michalmarcinkowski** [comment]
Thanks for fixing!
