### ISSUE TITLE
[attribute] - not possible to add mutliple attributes of same type

### ISSUE THREAD

**Issue by nakashu** [Sylius/Sylius#4108]
In the new attribute system there is a serious limitation.

If you want to add multiple attributes of same type to a product you cant.
After adding the first type, it won't appear in the selection anymore.

Usecases:
Book - have multiple authors
Shirt - is made of multiple fabrics
Pizza - have multiple ingredients

**Comment by michalmarcinkowski** [comment]
@nakashu as I recall, it should be possible for the backend logic and is just limited in the frontend. We will investigate that and get back to you :)

**Comment by nakashu** [comment]
@michalmarcinkowski you were right its just on the client side, handled in javascript.
Exactly it is in `AttributeBundle\Resources\public\js\sylius-attribute.js` in `controlAttributesList` function. I can make a PR with fix but would like to know why this handling exists there in the first place.
@Zales0123 can you please explain the reasoning behind this function, and hidding of existing attributes?

@michalmarcinkowski btw I would say this is a bug not a feature request

**Comment by Zales0123** [comment]
@nakashu while creating new attributes system, the main concept was that attributes are singular, as each of them describes specific characteristic of subject. Of course, there are some use cases where it is unfortunate (e.g. those, which you've described). Surely, this is sth to concern, how it should be handled:
- by new attribute type (``Collection``?) - however there we're making harder to validate array elements
- by allowing to add multiple attributes
- by adding a "multiple" flag on attribute to configure multiple attribute possibility

@michalmarcinkowski @nakashu @pjedrzejewski wdyt about it?

**Comment by nakashu** [comment]
@Zales0123 thanks for response.
I would say the best/easiest solution for now would be the 3rd one (flag). Also it could be with reversed logic (4rd option).

* by adding a "unique/exclusive/single" flag on attribute to disable multiple attributes of that type.

this would mean currently we would only need to add it to the checkbox type (and probably percent), where it doesn't make sense to have multiples of it. Everywhere where end user inputs the values you can find possible usecases.

* date/datetime - multiple "revision date", for a book
* integer - multiple "revision number", for a book

Also the content manager won't add multiple attributes of a type if it isn't logical. Enforcing it by code should be based on business model, and not by default.

**Comment by pjedrzejewski** [comment]
This is definitely nice feature, but I'd wait with introducing it till we have existing functionality covered with new scenarios. We cannot predict how it will behave and I am sure there will be bugs with multiple attributes of the same type.

**Comment by nakashu** [comment]
@pjedrzejewski the thing is, the behaviour (allow multiple), was there before the rework. 
Model is prepared to handle it right away. Its blocked only by js, and hidding element in the DOM.

**Comment by pjedrzejewski** [comment]
@nakashu If we can bring it back by tweaking the JS/html, then I am ok, but I can't promise to focus on that right now. :(

**Comment by nakashu** [comment]
I can make the PR no problem, but wanted discuss the approach and why it was blocked in the first place. Thanks

**Comment by nakashu** [comment]
@Zales0123 can you please clarify some code in current implementation, if it got some important meaning or if it was done to gain speed, specifically these two parts in *attributeValueForms.html*

Why is the hidden input build manually here, and not in the type/controller?
```twig
<div class="form-group">
    {% set id = form.vars.label|replace(' ', '_')|lower %}
    <label class="col-lg-2 control-label required" for="{{ id }}">{{ form.vars.label }}</label>
    <input type="hidden"
           name="{{ metadata.applicationName }}_{{ subject }}[attributes][{{ count }}][attribute]"
           id="{{ metadata.applicationName }}_{{ subject }}_attributes_{{ count }}_attribute"
           value="{{ attributeId }}"/>
    <div class="col-lg-10">
        {{ _self.formField(form, count, id, '', subject, metadata.applicationName) }}
    </div>
</div>
```

Why all the trouble with the `data-name` and then replacing it in the js, why not having it build upfront fully?
```twig
{% macro formField(item, count, id, prefix, subject, applicationName) %}
    {% if item.children|length > 0 %}
        {% set prefix = prefix~'_'~item.vars.name %}
        {% for child in item.children %}
            {{ _self.formField(child, count, id, prefix) }}
        {% endfor %}
    {% elseif item.vars.name != '_token' %}
        {% set namePrefix = prefix|replace({'_': ']['}) %}
        {% set dataName = applicationName~'_'~subject~'[attributes]['~count~namePrefix~']['~item.vars.name~']' %}

        {{ form_widget(item, {'id': id, 'attr': {'data-name': dataName }}) }}
    {% endif %}
{% endmacro %}
```

thanks
