### ISSUE TITLE
Undefined index 'disabled' when using getQueryBuilderForChoiceType in PaymentMethodRepository

### ISSUE THREAD

**Issue by axelvnk** [Sylius/Sylius#4118]
In Sylius\Bundle\PaymentBundle\Doctrine\ORM\PaymentMethodRepository there is a method defined like this : 
```
 public function getQueryBuidlerForChoiceType(array $options)
    {
        $queryBuilder = $this->getCollectionQueryBuilder();

        if (!$options['disabled']) {
            $queryBuilder->where('method.enabled = true');
        }

        return $queryBuilder;
    }
```

You can pass options to this function, however these seem to be required.. Since you check if the value of the array key 'disabled' in these options is false. That means the array key NEEDS to exist, otherwise this code will raise an exception.

It's also very confusing to me that the options is called 'disabled' when the actual entity method is called enabled.. But I guess changing that breaks BC. I'd like to change this method to first check if the 'disabled' key exists and then checking its value..

**Comment by michalmarcinkowski** [comment]
Fixed in #4119.
