### ISSUE TITLE
Question: can Product have different color-variants with each different sizes.

### ISSUE THREAD

**Issue by jeroendesloovere** [Sylius/Sylius#4120]
I want to know if the current PHP Component Product is capable of doing the following:

Product title = "Shoe Mercurial high"
- Blue (= color)
    - 40 (= size)
    - 41
    - 42
    - 43
- Red
    - 43
    - 44
    - 45
- Grey
    - 41
    - 42
    - 43

When visiting the sylius demo-site and sylius PHP documentation,
I don't think that this is possible? Am I right?

**Comment by michalmarcinkowski** [comment]
If I understood correctly in order to achieve that you simply create Product with two options (color and size) and the following 10 variants:

1. Blue, 40
2. Blue, 41
3. Blue, 42
4. Blue, 43
5. Red, 43
6. Red, 44
7. Red, 45
8. Grey, 41
9. Grey, 42
10. Grey, 43

The end user will not be able to order color Grey and size 45. Is that what you're asking?

**Comment by jeroendesloovere** [comment]
@michalmarcinkowski, indeed, sadly the demo wasn't available anymore.
Isn't there a more user-friendly way to create lots of variants (which is always a pain in the ass for customers)?
For example:
![schermafbeelding 2016-02-18 om 10 56 23](https://cloud.githubusercontent.com/assets/588616/13139741/503ee568-d62e-11e5-8abd-5769fee073f3.png)

**Comment by jeroendesloovere** [comment]
I think that there is a problem in the website.

**What I did**
* Deleted "small" - "red" in administration
* Deleted "medium" - "red" in administration

**Problem**
 Then I visited the website, but I can still select "small"/"medium" + "red"
![schermafbeelding 2016-02-18 om 14 57 57](https://cloud.githubusercontent.com/assets/588616/13145332/45897ddc-d650-11e5-991f-09f057c10cf6.png)

=> When I click "Add to cart", I'm redirected to the cart with an error "select variant"
![schermafbeelding 2016-02-18 om 14 57 54](https://cloud.githubusercontent.com/assets/588616/13145331/456d643a-d650-11e5-963c-b06c0078f188.png)

This seems like an UX-flaw.

**Comment by michalmarcinkowski** [comment]
The options system is generic and very flexible, so it's not possible to deliver generic UI that will be able to handle creation of variants with infinite number of options. 

E.g. You sell a beer in packages, you have the following options: 
container - bottle/can
package - 4/6/12 pack
volume - 0.5L/1.0L
How would you model the UI for creating variants?

If you need that UI you can very simply implement it on your own.

**Comment by pjedrzejewski** [comment]
@jeroendesloovere We definitely miss the proper UX for a lot of variants. Hopefully we can improve that in future versions and we will definitely put a focus on that. For now we do not have anything special planned. :/ If you try to implement solution for your project, feel free to let us know if you run into any trouble. Will be great to discuss and maybe use it in the future.

**Comment by jeroendesloovere** [comment]
@michalmarcinkowski and @pjedrzejewski : thanks for the answers!
