### ISSUE TITLE
Can not complete payment of order, controller is not callable

### ISSUE THREAD

**Issue by treoden** [Sylius/Sylius#4125]
Hi
When I view an order from backend and click complete button (Payment block), I got this error:
![image](https://cloud.githubusercontent.com/assets/6950941/12998063/d1b74a2a-d171-11e5-809b-18003e6630e4.png)

I think controller or action method was missing. Thanks

**Comment by lchrusciel** [comment]
will be resolved in #3980

**Comment by michalmarcinkowski** [comment]
Should be fixed, please reopen if still valid.
