### ISSUE TITLE
Knp menu Bug

### ISSUE THREAD

**Issue by yopop666** [Sylius/Sylius#4127]
Going on  [orders](http://demo.sylius.org/administration/orders/), the menu have active on orders link.
Going on orders [second page](http://demo.sylius.org/administration/orders/?page=2) the menu doesn't have active class on orders link.

I fixed this issue injecting  container in BackendMenuBuider
and  replacing
```
$menu->setCurrentUri($this->request->getRequestUri());
```

with
```
$routeName = $this->request->get('_route');
$uri = $this->container->get('router')->generate($routeName, $this->request->get('_route_params'));
$menu->setCurrentUri($uri);
```

For the moment it works, but I am not sure if it is OK to be like that.

**Comment by michalmarcinkowski** [comment]
It's fixed in the new admin panel.
