### ISSUE TITLE
Question: address situation

### ISSUE THREAD

**Issue by jeroendesloovere** [Sylius/Sylius#4130]
Hi, what happens in the following situation:

* When a Customer has one default address used for billing and shipping
* He orders a product with that default "billing and shipping" address (order get billing_address_id and shipping_address_id = 1)
* And then a day later he decides to change his default "billing and shipping" address in "his account".

=> This will cause problems for that order, since you don't know the "old and required" address anymore. Or does Sylius has a fallback for this and is it looking at "hey address, you are mentioned in an order, I will create a new address-id"?

**Comment by peteward** [comment]
Hey, copies of the customers address are stored and associated directly against the order for billing and shipping to avoid this issue.

**Comment by steffenbrem** [comment]
I guess that when they add a new address and set that as default everything is fine. But when you edit an existing address, the order will indeed be shipped to that new address.

**Comment by steffenbrem** [comment]
@peteward Does this mean that you always have the address as described by the customer on checkout? Even if they change that exact same address in their address book?

**Comment by peteward** [comment]
Our implementation might be a bit different here so I've just checked core code to be sure!

If you look in the `AddressTypeStep` form, there's the following code:

```
                /* @var $order OrderInterface */
                $order = $event->getData();
                if ($order->getShippingAddress() === null && $customer->getShippingAddress() !== null) {
                    $address = clone $customer->getShippingAddress();
                    $address->setCustomer(null);
                    $order->setShippingAddress($address);
                }

                if ($order->getBillingAddress() === null && $customer->getBillingAddress() !== null) {
                    $address = clone $customer->getBillingAddress();
                    $address->setCustomer(null);
                    $order->setBillingAddress($address);
                }
```

So the customer's selected address for an order is always cloned and disassociated from the Customer. Any editing of either an address in an address book or an address in an order post-checkout will not contaminate / break one-another.

There is also the `CheckoutAddressingListener` which clones the customer's entered address at checkout back into their address book as default shipping and billing if they don't already have one.

**Comment by jeroendesloovere** [comment]
Okay @peteward, thanks for investigating.
Seems like every problem has a fallback.
