### ISSUE TITLE
Add permission check on links in templates

### ISSUE THREAD

**Issue by Niiko** [Sylius/Sylius#4137]
Hi,

What about add a permission check on links in admin templates ?
I see twig extension "sylius_is_granted" already existing. So it will be easy to hide or disable them

As an example on SyliusWebBundle:Backend/Order:show.html.twig
```twig
{% if not order.shippingState is constant('Sylius\\Component\\Shipping\\Model\\ShipmentInterface::STATE_SHIPPED') %}
    {{ buttons.edit(path('sylius_backend_order_update', {'id': order.id})) }}
 {% endif %}
 {{ buttons.delete(path('sylius_backend_order_delete', {'id': order.id})) }}
```
will be
```twig
{% if not order.shippingState is constant('Sylius\\Component\\Shipping\\Model\\ShipmentInterface::STATE_SHIPPED') and sylius_is_granted('sylius.order.update') %}
    {{ buttons.edit(path('sylius_backend_order_update', {'id': order.id})) }}
 {% endif %}
 {% if sylius_is_granted('sylius.order.delete') %}
    {{ buttons.delete(path('sylius_backend_order_delete', {'id': order.id})) }}
  {% endif %}
```

I am already working on it for my purpose, i would be happy to submit PR for every administration templates and permissions.

**Comment by michalmarcinkowski** [comment]
We're reworking the backend and will drop support for the old one soon [see more here](https://github.com/Sylius/Sylius/pull/3646).

**Comment by Niiko** [comment]
Oh, totally missed it!

I'm working on tag release 0.16, i will switch right away to see how help on new backend.

Thanks.

**Comment by Niiko** [comment]
With rbac removal, maybe we can close it no ?

**Comment by michalmarcinkowski** [comment]
True :)
