### ISSUE TITLE
[RFC] Translation locale handling

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#4147]
Let's forget about LocaleBundle for a moment and how it is handling/managing locales and focus on ResourceTranslations.

Each translatable resource has a collection of Translations. Each translation consists of:

* locale
* fields which are translatable, for example: name, description

While using translatable resources, we have to consider 3 different locales (or no?):

* default locale: Main locale of the whole application, which is required by default to be filled in forms and is used unless any other is selected by the user.
* current locale: Current locale in which resources will be translated when using proxy methods.
* fallback locale: Locale which will be used if selected current locale is not available for given resource.

Also, it would be great to have access to available locales, for example to render appropriate forms.

I think we need to modify https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Translation/Provider/LocaleProviderInterface.php:

```php
<?php

interface LocaleProviderInterface
{
    public function getDefaultLocale(); // en_US
    public function getCurrentLocale(); // de_DE
    public function getFallbackLocale(); // en_US (I think initially we should always set default as fallback.
    public function getAvailableLocales(); // [en_US, de_DE, fr_FR]
}
```

Questions:

* What should happen if fallback locale is not available as well?
* How we define these out of context of Sylius?

What I propose as answer to question no. 2:

```
# app/config/config.yml

sylius_resource:
    translations:
        default_locale: en_US
        available_locales: [en_US, fr_FR, de_DE]
```

That would be default ArrayLocaleProvider implementation. For Sylius itself we would use LocaleBundle and return codes of only enabled locales, etc.

**Comment by peteward** [comment]
sounds good but what's the use-case where `fallbackLocale` != `defaultLocale` ?

**Comment by pjedrzejewski** [comment]
@peteward When you want to configure custom fallback, for example, you could configure fallback from de_CH to de_DE and have en_US as default. I think the order would be: de_CH -> de_DE -> en_US. en_US is default locale so it has to be defined. That being said, one can change the default locale later on, so this does not really ensure that you always get some translation. Unless we enforce default locale just like we enforce base currency - not changeable for store as a whole, just for channels.
