### ISSUE TITLE
[RFC] Behat tags

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#4149]
I just noticed that we are using tags like ``ui-cart`` - https://github.com/Sylius/Sylius/blob/master/features/shop/apply_correct_tax_for_items_with_the_same_tax_rate.feature#L1.

My initial idea with these tags was to combine them.

```
@cart @ui @domain
Feature: XYZ

@taxation
Feature: ABC

@ui @domain
Scenario: A

@ui
Scenario: B

@domain @api
Scenario: C
```

https://github.com/Sylius/Sylius/blob/master/etc/behat/suites/ui_cart.yml#L26 This could be changed to:

```
tags: @cart && @ui
```

This has following benefits:

* We can easily mark whole features as "cart" or "checkout" suite, etc.
* We can easily make specific scenarios run through UI and Domain, without repeating the suite name

I am pretty sure Behat supports that.

**Comment by michalmarcinkowski** [comment]
:+1: realized the same yesterday! :smile:

**Comment by pamil** [comment]
:+1:, this way we can run `bin/behat --tags cart` to run both UI and domain tests for cart.
