### ISSUE TITLE
[RFC] Remove softdelete and ensure proper cascading for Order

### ISSUE THREAD

**Issue by michalmarcinkowski** [Sylius/Sylius#4153]
Part of #4140.

We should remove the softdeletable to be able to completely remove the `Order` entity. The following scenarios will also cover proper cascading for all relations.

##### Technical hints:
 * Remove softdelete from order
 * Add proper cascading and not nullable constraints

##### Requirements:
 * The scenarios should be implemented first in the @domain context then in the @ui, with usage of the same steps, but different contexts.

```
Background:
    Given the store operates on a single channel in France
    And the store has product "PHP T-Shirt"
    And the store ships everywhere for free
    And the store allows paying with "Cash on Delivery"
    And the customer "john.doe@gmail.com" placed an order "#00000022"
    And the customer chose "Free" shipping to "France" with "Cash on Delivery" payment
    And the customer bought single "PHP T-Shirt"
```

* [x] Deleted order should disappear from the registry (Domain)
* [ ] Deleted order should disappear from the registry (UI)
```
Scenario: Deleted order should disappear from the registry
    When I delete order "#00000022"
    Then this order should not exist in the registry
```
* [ ] ~~Not being able to delete the order when a promotion was applied (Domain)~~
* [ ] ~~Not being able to delete the order when a promotion was applied (UI)~~
```
Scenario: Not being able to delete the order when a promotion was applied
    Given the there was promotion "Christmas sale" applied to the order "#00000022"
    When I try delete this order
    Then I should be notified I can't remove this order
    And the order should still exist in the order registry
```
* [x] Payments of a deleted order should disappear from the registry (Domain)
* [ ] Payments of a deleted order should disappear from the registry (UI)
```
Scenario: Payments of a deleted order should disappear from the registry
    When I delete order "#00000022"
    Then there should be no "Cash on Delivery" payments in the registry
```
* [x] Shipments of a deleted order should disappear from the registry (Domain)
* [ ] Shipments of a deleted order should disappear from the registry (UI)
```
Scenario: Shipments of a deleted order should disappear from the registry
    When I delete order "#00000022"
    Then there should be no shipments with "Free" shipping method in the registry
```
* [x] Order items are deleted together with an order (Domain)
```
Scenario: Order items are deleted together with an order
    When I delete order "#00000022"
    Then the order item with product "PHP T-Shirt" should not exist
```
* [x] Billing and shipping addresses are deleted with an order (Domain)
```
Scenario: Billing and shipping addresses are deleted with an order
    When I delete order "#00000022"
    Then it's billing and shipping addresses should not exist
```

**Comment by peteward** [comment]
```
 Not being able to delete the order when a promotion was applied (Domain)
 Not being able to delete the order when a promotion was applied (UI)
```

Why not? 

As long as adjustments and assocations are deleted I don't see the use of a promotion as a possible reason not to delete something. 

What happens if you place a test order during `Christmas Sale` and a promo is automatically applied but you want to delete it?

**Comment by michalmarcinkowski** [comment]
@peteward actually you're right! I thought about use case when you placed an order using a coupon and deleted it, then the same coupon can be used once again, but I realize that this behavior makes sense :smile:
