### ISSUE TITLE
Code requirement is not working for Taxonomy new form

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#4162]
Steps to reproduce:

- go to /administration/taxonomies/new
- fill in a name
- add a photo
- leave code empty
- press Create

What happens:
- you get an ugly ORM error claiming code should not be empty

What should happen:
- form object should handle this and notice the user there's a required field empty

It seems to me that b4929c90262640303020de31400b06fdb5373495 introduced the idea of code for Taxons but it is not making it mandatory, although schema it seems to state other wise - [form available here](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Form/EventSubscriber/AddCodeFormSubscriber.php#L63)

The funny thing is that the form appears to have "mandatory" for this field but somehow this still does not solve the problem:

**Comment by michalmarcinkowski** [comment]
No konferencji valid since Taxonomy entity has been removed.
