### ISSUE TITLE
[RFC] - Should promotions priority (and other) be configurable per channel

### ISSUE THREAD

**Issue by nakashu** [Sylius/Sylius#4165]
This is very likely an after stable release issue but I'll leave it here for reference. 
Currently promotions priority is configured globally

As you can enable promotions per channel now, options like priority could be configured per channel
Possibly others like
- exclusive
- start_at?
- ends_at?
- usage_limit?

Still it is possible to overcome this by creating specialized promotion per channel, with different configurations.

**Comment by michalmarcinkowski** [comment]
That would be a nice feature, but since we can achieve similar behavior creating promotion per channel it has low priority for now. Thanks for sharing for thoughts! :+1:
