### ISSUE TITLE
Can`t create second menu item with link type "Content"

### ISSUE THREAD

**Issue by BlackIceWizard** [Sylius/Sylius#4186]
Hi,

Seems there is a problem with PHPCR in menu form.

Steps for getting error:

1) Open form "Creation menu" on admin side, fill with any data and then press "Save changes"
...Now a new menu has been created
2) Open form "Editing menu" for menu, that was created in previous step, press "Add menu element", fill any data (with link type "Content") in menu item form and then press "Save changes" again
...Now a first item for menu has been created
3) Repeat step "2"
...Now we see error "This value is not valid." for field "Content" of form "Menu item".

If the value of the field "Content"  in the first menu item and second menu item identical, the error does not occur.

The same error occurs on the demo site too. I checked an half hour ago.

Symfony form debuger output for field "Content":
```
Symfony\Component\Validator\ConstraintViolation
Object(Symfony\Component\Form\Form).children[children].children[1].children[content] = /cms/pages/shipping-and-payment
Caused by:
Symfony\Component\Form\Exception\TransformationFailedException
Unable to reverse value for property path "content": The choice "/cms/pages/shipping-and-payment" does not exist or is not unique
Caused by:
Symfony\Component\Form\Exception\TransformationFailedException
The choice "/cms/pages/shipping-and-payment" does not exist or is not unique
```

**Comment by michalmarcinkowski** [comment]
The menu support was removed.
