### ISSUE TITLE
Can`t create new API client

### ISSUE THREAD

**Issue by BlackIceWizard** [Sylius/Sylius#4190]
Hi!

Steps to get the error:
1) Open admin side.
2) Click on "API clients" in left side menu
3) Click "sylius.api_client.create" (is translation missing?)

Error subject:
```
Catchable Fatal Error: Argument 2 passed to Sylius\Bundle\ResourceBundle\Controller\ResourceFormFactory::create() must implement interface Sylius\Component\Resource\Model\ResourceInterface, instance of Sylius\Bundle\ApiBundle\Model\Client given, called in src\Sylius\Bundle\ResourceBundle\Controller\ResourceController.php on line 225 and defined
500 Internal Server Error - ContextErrorException
```
The same error on the demo site (http://demo.sylius.org) .

**Comment by lchrusciel** [comment]
We've missed a few interfaces in a ApiBundle. It will be fixed soon.

**Comment by pjedrzejewski** [comment]
@BlackIceWizard Should be fixed now. :) Thanks for reporting!

**Comment by BlackIceWizard** [comment]
I'm glad if that helps. I like your project.
