### ISSUE TITLE
[ReportBundle] Naming configurationType should not be prefixed

### ISSUE THREAD

**Issue by Niiko** [Sylius/Sylius#4196]
Hi,

I noticed that in Sylius\Bundle\ReportBundle\Form\EventListener\BuildReportRendererFormSubscriber the is this an automatic prefix for formType name
```php
$formType = sprintf('sylius_renderer_%s', $renderer->getType());
```

According to docs, we can have a name like this in CustomConfigurationType
```php
    public function getName()
    {
        return 'acme_renderer_custom';
    }
```

But in facts, the name has to be "sylius_renderer_acme_renderer_custom" to get it working.

Also, in documentation, there is missing on custom renderer code (4.1) this mandatory part of code
```php
    /**
     * @var EngineInterface
     */
    private $templating;

    /**
     * @param EngineInterface $templating
     */
    public function __construct(EngineInterface $templating)
    {
        $this->templating = $templating;
    }
```

So, can i remove this prefix, fix tests and documentation and submit a PR in that way.

**Comment by pjedrzejewski** [comment]
Hi @Niiko! You are right, documentation is wrong here. If you can remove the prefix without any side effect (I can't remember any) then I am definitely :+1:!

**Comment by Niiko** [comment]
According to https://github.com/Sylius/Sylius-Docs/issues/421, maybe reports needs to be associated with their compatible renderers ?

**Comment by Niiko** [comment]
Close after removal of report bundle
