### ISSUE TITLE
[taxation] - zone tax applicator cannot be called consequently (preserves state)

### ISSUE THREAD

**Issue by nakashu** [Sylius/Sylius#4202]
In a use case where you combine Addressing and Payment steps to one, and on success dispatch corresponding `pre_` events `Sylius\Component\Core\Taxation\OrderItemsTaxesByZoneApplicator` method `apply` will fail with following error:

> Catchable Fatal Error: Argument 1 passed to Sylius\Component\Core\Taxation\OrderItemsTaxesByZoneApplicator::addAdjustment() must implement interface Sylius\Component\Core\Model\OrderItemUnitInterface, boolean given, called in D:\_www\chutnekytice\src\Fatchilli\AppBundle\Taxation\OrderItemsTaxesByZoneApplicator.php on line 82 and defined

Problem is when iteration over OrderItemUnit collection, the internal pointer is left at the end, and on the subsequent call the script will fail, as the collection keeps the position of pointer.

event to dispach to reproduce are:

```php
     $this->dispatchCheckoutEvent(SyliusCheckoutEvents::ADDRESSING_PRE_COMPLETE, $order);
     $this->dispatchCheckoutEvent(SyliusCheckoutEvents::PAYMENT_PRE_COMPLETE,` $order);
```

simple workaround fix would be to reset the pointer after applying tax adjustments:

```php
    $units = $item->getUnits();
    $units->first(); // ensure subsequent calls wont fail
    foreach ($splitTaxes as $key => $tax) {
        if (0 === $tax) {
            continue;
        }
        $unit = $this->getNextUnit($units);
        $this->addAdjustment($unit, $tax, $taxRate->getLabel(), $taxRate->isIncludedInPrice());
    }
    // or reset here $units->first();       
```

but still the code looks fragile and I would probably go with something like this:

```php
    $filteredTaxes = array_filter($splitTaxes, function ($tax) {
        return 0 !== $tax;
    });

    if ($units->count() != count($filteredTaxes)) {
        throw new \InvalidArgumentException('The number of tax items is greater than number of units.');
    }

    foreach ($units as $unit) {
        $this->addAdjustment($unit, current($filteredTaxes), $taxRate->getLabel(), $taxRate->isIncludedInPrice());
        $filteredTaxes->next();
    }
```

**Comment by michalmarcinkowski** [comment]
Thanks for reporting this! :+1: 

I think the best solution will be to reset the pointer before loop:
```
...
$units->first();
foreach (...
```
We are then sure we start from the first item. The fragility is also [here](https://github.com/michalmarcinkowski/Sylius/blob/b26cdd44b3e39cb48f4c0e0847b31d55b7d3bdf6/src/Sylius/Component/Core/Taxation/OrderItemsTaxesByZoneApplicator.php#L115-L115) since the `current` method returns `true` not `null` so the condition will never be met.

**Comment by nakashu** [comment]
@michalmarcinkowski with the second solution I provided, you don't need to call the `getNextUnit()`.
The count difference is handled before hand and unit iteration is handled by the foreach on valid data.

**Comment by michalmarcinkowski** [comment]
The second solution is wrong.

1) We shouldn't filter out the `0` taxes, see the following example:

```
Given the store has product "Pencil" priced at "€0.04"
And the store has "VAT" tax rate of 10% for "Pencils" within "FR" zone
When I add 10 products "Pencil" to my cart
Then my cart total should be "€0.44"
And my cart taxes should be "€0.04"
```
In this scenario we have 10 units but 4 cents to distribute. Splitting 4 cents to 10 parts will result in the following array: `[1, 1, 1, 1, 0 , 0, 0, 0, 0, 0]`, filtering out the `0`s:
```
$filteredTaxes = array_filter($splitTaxes, function ($tax) {
        return 0 !== $tax;
    });
```
Will result in exception here:
```
if ($units->count() != count($filteredTaxes)) {
    throw new \InvalidArgumentException('The number of tax items is greater than number of units.');
}
```

2) Swapping the `foreach` subject from array with taxes to array of units does not simplify anything. What is the difference between:

```
foreach ($units as $unit) {
        $this->addAdjustment($unit, current($filteredTaxes), $taxRate->getLabel(), $taxRate->isIncludedInPrice());
        $filteredTaxes->next();
    }
```
And:
```
foreach ($splitTaxes as $key => $tax) {
    $unit = $units->current();
    if (null === $unit) {
        throw new \InvalidArgumentException('The number of tax items is greater than number of units.');
    }
    $units->next();
    $this->addAdjustment($unit, $tax, $taxRate->getLabel(), $taxRate->isIncludedInPrice());
}
```
?

**Comment by nakashu** [comment]
Currently in the code, the `if (0 === $tax)` is doing the filtering, or am i wrong ?

```php
    foreach ($splitTaxes as $key => $tax) {
        if (0 === $tax) { // this line filters out taxes
            continue;
        }
        $unit = $this->getNextUnit($units);
        $this->addAdjustment($unit, $tax, $taxRate->getLabel(), $taxRate->isIncludedInPrice());
    }
```

**Comment by nakashu** [comment]
1. You are right about the exception, the conditions should be modified for the scenario, but currently in the code, the `if (0 === $tax)` is doing the filtering, anyway, it is just taken apart from the exception.

2. The difference is that you don't need to reset the pointer in the end as $splitTaxes is array and not object, that will keep the pointer location. The other one is lower nesting level / clearer code (in my point of view at least).

thanks for feedback.

**Comment by michalmarcinkowski** [comment]
Thanks for fixing!
