### ISSUE TITLE
Archetype edit Bug

### ISSUE THREAD

**Issue by next-sentence** [Sylius/Sylius#4204]
Scenario:

1. Create a new archetype named Archetype A
2. Create a second archetype Archetype B with parent Archetype A
3. Then, if I edit Archetype A, parent field is selected with Archetype B and can't be removed and if I press save changes it cause break nested error when `$archetype->getOptions()` or `$archetype->getAttributes()`  is called

I guess 
```
'query_builder' => function (RepositoryInterface $repository) use ($currentArchetype) {
                    return $repository
                        ->createQueryBuilder('o')
                        ->where('o.id != :id')
                        ->setParameter('id', $currentArchetype->getId())
                    ;
}
```
in `Sylius\Bundle\ArchetypeBundle\Form\EventListener\ParentArchetypeListener` class must be changed

sorry for my english)

**Comment by pjedrzejewski** [comment]
Archetypes have been removed.
