### ISSUE TITLE
add API  for CartItemController

### ISSUE THREAD

**Issue by videni** [Sylius/Sylius#4207]
CartItemController is supposed to work with API, but  every action will redirect  ,which breaks API.  is this in schedule?

**Comment by michalmarcinkowski** [comment]
We think about getting rid of `CartItemController` and simply use `create/delete` actions from `OrderItemController`.

**Comment by pjedrzejewski** [comment]
This gist illustrates my idea: https://gist.github.com/pjedrzejewski/0eb9f6490aa134b7f565

Not entirely sure this will work out, but would dramatically simplify the whole cart logic and allow us to very easily support cart API, both through standard shop API and restful API. Actually, only thing I see here to figure out is how to move logic from ItemResolver to validations on cart/cart item.

**Comment by michalmarcinkowski** [comment]
Should work fine for API now 😉
