### ISSUE TITLE
[Variation] Introduce code for option values and replace presentation with name

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#4213]
Option should have:

* code
* name (translatable)

OptionValue should have:

* code
* value (translatable)

Somehow we have ended with ``name``, ``presentation`` and ``code`` at the same time. :)

**Comment by vikey89** [comment]
@pjedrzejewski the goal of this issue is rename `value` of OptionValue in `name`. It's correct?

**Comment by michalmarcinkowski** [comment]
Not exactly. The goal of this issue is to remove current `name` from `Option` and rename `presentation` to `name`. The current `name` of `Option` is exactly the same as `code`, so it's duplicated. The `OptionValue` entity is correct :)

**Comment by vikey89** [comment]
ah ok, now I understand thanks :)

**Comment by nakashu** [comment]
this should be closed
