### ISSUE TITLE
composer installation with symfony 2.7.3

### ISSUE THREAD

**Issue by solve-it** [Sylius/Sylius#4215]
Problem 1
    - Conclusion: don't install symfony/symfony v2.7.9
    - Conclusion: don't install symfony/symfony v2.7.8
    - Conclusion: don't install symfony/symfony v2.7.7
    - Conclusion: don't install symfony/symfony v2.7.6
    - Conclusion: don't install symfony/symfony v2.7.5
    - Installation request for sylius/cart-bundle ^0.16.0 -> satisfiable by sylius/cart-bundle[v0.16.0].
    - Conclusion: remove symfony/symfony v2.7.3
    - Conclusion: don't install symfony/symfony v2.7.3
    - sylius/cart-bundle v0.16.0 requires symfony/framework-bundle ^2.7.5 -> satisfiable by symfony/symfony[v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9], symfony/framework-bundle[v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.2].
    - don't install symfony/framework-bundle v2.7.5|don't install symfony/symfony v2.7.3
    - don't install symfony/framework-bundle v2.7.6|don't install symfony/symfony v2.7.3
    - don't install symfony/framework-bundle v2.7.7|don't install symfony/symfony v2.7.3
    - don't install symfony/framework-bundle v2.7.8|don't install symfony/symfony v2.7.3
    - don't install symfony/framework-bundle v2.7.9|don't install symfony/symfony v2.7.3
    - don't install symfony/framework-bundle v2.8.0|don't install symfony/symfony v2.7.3
    - don't install symfony/framework-bundle v2.8.1|don't install symfony/symfony v2.7.3
    - don't install symfony/framework-bundle v2.8.2|don't install symfony/symfony v2.7.3
    - Installation request for symfony/symfony == 2.7.3.0 -> satisfiable by symfony/symfony[v2.7.3].

Installation failed, reverting ./composer.json to its original content.

**Comment by pamil** [comment]
Just use `^2.7.3` instead of `2.7.3` :)

**Comment by solve-it** [comment]
where should i effect that change ? i ran the composer require syliusCartBundle command and it generated the above. ps am a newbie

**Comment by solve-it** [comment]
i installed  v0.15.0 instead
