### ISSUE TITLE
create an alternative checkout flow  for mobile

### ISSUE THREAD

**Issue by videni** [Sylius/Sylius#4220]
the typical checkout flow  for mobile is quite different from the traditional one,  a customer can add address, select shipping method, payment in one  single step, then purchase  after he/she confirms the cart, still  he can change payment method in purchase step.

**Comment by nakashu** [comment]
You can modify the checkout process as you want. In short you 

 * create your scenario
 * create your steps and add them to scenario
 * tag your classes, and create routes

This should help: http://docs.sylius.org/en/latest/bundles/SyliusFlowBundle/
Also look how the default scenario is and steps are created.

Parts of our combined steps:

// scenario

```php
    /**
     * {@inheritdoc}
     */
    public function build(ProcessBuilderInterface $builder)
    {
        $builder
            ->add('summary', new SummaryStep())
            ->add('combined', new CombinedStep()) // shipping, payment, address
            ->add('finalize', new FinalizeStep())
            ->add('purchase', 'sylius_checkout_purchase')
            ->setDisplayRoute('sylius_checkout_display')
            ->setForwardRoute('sylius_checkout_forward')
            ->setRedirect('sylius_homepage');
        ;
    }
```

// combined step 

```php  
   /**
     * {@inheritdoc}
     */
    public function displayAction(ProcessContextInterface $context)
    {
        $order    = $this->getCurrentCart();
        $customer = $this->getCustomer();

        $this->dispatchCheckoutEvent(SyliusCheckoutEvents::ADDRESSING_INITIALIZE, $order);
        $this->dispatchCheckoutEvent(SyliusCheckoutEvents::PAYMENT_INITIALIZE, $order);
        $this->dispatchCheckoutEvent(SyliusCheckoutEvents::SHIPPING_INITIALIZE, $order);

        $form = $this->createCheckoutCombinedForm($order, $customer);

        return $this->renderStep($context, $order, $form);
    }
```

**Comment by michalmarcinkowski** [comment]
The FlowBundle has been removed and now checkout is more flexible.

Sylius uses Stackoverflow as its official support channel. For future support questions please post at http://stackoverflow.com/questions/tagged/sylius and tag your questions with sylius.
