### ISSUE TITLE
[Behat][RFC] Proposal of LexicalContext

### ISSUE THREAD

**Issue by Zales0123** [Sylius/Sylius#4225]
We're all now participants of a great adventure with new behat scenarios and contexts ;) There are some really big changes and many other ideas are created over and over. Which is obviously good :smile: 

I've been thinking about implementing something like ``LexicalContext``, which could hold some reusable steps (or probably mainly ``@Transform``ers). Two examples:
- ``@Transform this|that {resourceName}`` - return last implemented/hold in ``sharedStorage`` resource with proper type
- ``@Transform it`` - any last implemted/hold in ``sharedStorage`` resource

It could be useful for steps like ``Given there is a promotion "Christmas Sale"/And it gives "€106.00" fixed discount to every order`` and many others.
Moreover, there could be some data transforming ``@Transform``ers. For example, usually we need to get integer from ``"€106.00"`` string, or float from ``10%``, so:
- ``@Transform "(€|£|\$)([^"]+)"``: ``"€106.00"`` -> ``10600``
- ``@Transform "([^"]+)%"``: ``"10%"`` -> ``0.1``

I think it could be quite useful and would avoid duplication of some logic/private methods ;)

**Comment by pamil** [comment]
:+1:, but I'd like to keep those two related to shared storage apart to the other ones, just to let developers choose what they want to use.

**Comment by lchrusciel** [comment]
:+1: Splitting SharedStorageContext and LexicalContext sounds reasonable too.

**Comment by Zales0123** [comment]
Agreed :+1:

**Comment by pjedrzejewski** [comment]
Nice idea and implementation. :+1:
