### ISSUE TITLE
[Promotion] ActionFactory should go to Core & ActionInterface::TYPE_FIXED_DISCOUNT too

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#4229]
Promotion component does not know any types of discounts, so:

* ActionFactory added in #4223 should go to the core component
* ActionInterface::TYPE_FIXED_DISCOUNT should be moved to FixedDiscountAction::TYPE

**Comment by Zales0123** [comment]
We must remember to add missing promotion types' constants (for example for ``shipping discount``) and moreover use them everywhere where it should be used - as mentioned in [this discussion](https://github.com/Sylius/Sylius/pull/4275#discussion_r53915764)
