### ISSUE TITLE
[crowdin] - SyliusBot is lazy with translations, and crowdin is missing keys

### ISSUE THREAD

**Issue by nakashu** [Sylius/Sylius#4236]
On jan 18 @pamil:
> it is set to run every Saturday at ~15:30 now. I'll generate extra one tomorrow morning just before I'll start the translation keys renaming.https://github.com/Sylius/Sylius/issues/3789#issuecomment-172601420

Last PR from syliusBot was 17 days ago.

Also translation keys/string on crowdin are missing, could it be synchronized now on both sides?
Is there a possibility to have new translations key send to crowding on every PR merge to master, as it seems now it not automated.

Thanks

**Comment by pjedrzejewski** [comment]
@nakashu We hope to fix that as soon as possible, Kamil is a bit busy with something else now but I will do my best to find a moment for him to take a look what is wrong with Crowidn. ;)

**Comment by nakashu** [comment]
@pjedrzejewski thanks ... could we then get just one manual update if its possible?

**Comment by aramalipoor** [comment]
:+1:

**Comment by pamil** [comment]
Related issue with reply - #4333, PR with translations - #4354 :)

**Comment by aramalipoor** [comment]
@pamil Thank you Kamil :+1:

**Comment by nakashu** [comment]
synchronization is back :tada:
