### ISSUE TITLE
 unable  to serialize a collection of objects with serialization group

### ISSUE THREAD

**Issue by videni** [Sylius/Sylius#4245]
right now , it is not possible to serialize a collection of objects with serialization group,  the result set will be empty if add a  serialization group to a collection.

**Comment by lchrusciel** [comment]
Only if you will use HATEOAS pagination or serialization group different then _Default_. Check customers API to see how it works. With these [routing configurations](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ApiBundle/Resources/config/routing/customer.yml) and [customer serialization](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/UserBundle/Resources/config/serializer/Model.Customer.yml) you can get [following responses](https://github.com/Sylius/Sylius/tree/master/src/Sylius/Bundle/CoreBundle/Tests/Responses/Expected/customer)

**Comment by videni** [comment]
Yep, I use HATEOAS pagination to list a collection of objects,   I defined several serialization groups for that entity ,  each would be used in different  list API,    I think JMSSerializer should add a ability to make a class transparent , such as the Hateoas\Representation\PaginatedRepresentation,  if we make  PaginatedRepresentation transparent to JMSSerializer , then  JMSSerializer will just simply ignore any serialization group of  this class,  but still  serialize all its properties.  in this way, we can add any group name to HATEOAS pagination.

**Comment by lchrusciel** [comment]
That make sense. Are you able to add such config and contribute to Sylius?
