### ISSUE TITLE
Can`t search by taxon on frontend

### ISSUE THREAD

**Issue by BlackIceWizard** [Sylius/Sylius#4251]
Hi!

It is about the search form on the user of the frontend in the upper left corner of the screen (Search Bundle).

The error occurs when you try to search for something in any taxon on the frontend. When the taxon is not selected, the error does not appear.

Error:
`[Semantical Error] line 0, col 107 near 'name = :taxo': Error: Class Sylius\Component\Core\Model\Taxon has no field or association named name`

Reproduced on demo site too: http://demo.sylius.org/search/?search_param=T-Shirts&q=shirt

**Comment by Niiko** [comment]
For information, works with elasticsearch engine.

**Comment by michalmarcinkowski** [comment]
SearchBundle was removed. It's no longer valid.
