### ISSUE TITLE
[SettingsBundle] Remove concept of Transformers

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#4253]
Not a priority but we should keep settings as simple as possible and avoid giving them too much power, thus I think we should remove the concept of Transformers - https://github.com/Sylius/Sylius/tree/master/src/Sylius/Bundle/SettingsBundle/Transformer. This requires moving the default tax zone configuration to the Channel (at a relation to zone), which makes sense anyway.

**Comment by aramalipoor** [comment]
What about when you want to have a `Homepage Taxon` settings in your theme and it should be `sylius_taxon_choice`? If I get it right that `Id number <-> Taxon model` transformation is done by the form type.

**Comment by steffenbrem** [comment]
@aramalipoor is right, you definitely want to be able to have transformations on your setting parameters. I think it is a nice feature, settings would become way less interesting without it.
