### ISSUE TITLE
[Behat] Error in scenario : Seeing review list after product deletion

### ISSUE THREAD

**Issue by Niiko** [Sylius/Sylius#4277]
When running tests : 

```
  Scenario: Seeing review list after product deletion
PHP Fatal error:  Call to a member function press() on null in /home/niiko/repositories/Sylius/src/Sylius/Bundle/ProductBundle/Behat/ProductContext.php on line 391
```

**Comment by pjedrzejewski** [comment]
Try ``show_auto: true`` in Behat to see the actual response, then we will have more info about the error. :)

**Comment by Niiko** [comment]
Thanks for the hint. After an update, problem was moving.

But, my bad. I was missing in test environment : 
- assets (especially js)
- chromedriver

**Comment by pjedrzejewski** [comment]
:+1:
