### ISSUE TITLE
[ThemeBundle] Context aware themes

### ISSUE THREAD

**Issue by takeit** [Sylius/Sylius#4280]
Hi,

I found your ThemeBundle meeting most of my requirements and it looks really nice - good job guys! Although, it misses one major feature imo.

I'm developing a multi-tenancy app, and one of my requirements is to make themes which are tenant context aware (it can be also some other context aware, e.g. channel context in your case, so in general: context aware themes).

This will give me more flexibility:
- it will be possible to have a theme per channel (in your case)/tenant (in my case)
- themes synchronization could be done for current context only. For example: once I add a new theme for `tenant/channel A` I would want to synchronize all themes only for the `A` context - I don't need to synchronize it for all channels/tenants while it was only changed for single tenant/channel.

This would be also nice to make it configurable so you can use this feature or just the basic behaviour.

What do you think about it? Or maybe this can be achieved already and I'm not aware of it?

Best,

**Comment by pamil** [comment]
Hello Rafał!

I've just finished an enormous ThemeBundle refactoring and I'm back at integrating it with Sylius Core, which will result in channel-aware theme context, it should be done in the next few days.

The themes synchronization is definitely the way to go, I'm thinking about a service that will synchronize (update database info, dispatch add / remove / update events) for a single theme passed to it as an argument. It will allow to fulfill your needs with quite small amount of code just to collect themes that needs synchronization and call the synchronizer for them.

**Comment by takeit** [comment]
@pamil When do you expect this to be done? is there any PR for that ?

**Comment by pamil** [comment]
@takeit channel aware theming is already in Core, but the synchronization itself haven't changed since this issue was created. 

I'm quite busy these days and I won't be able to code another ThemeBundle feature, but feel free to contribute and ask me any questions about TB (especially now, while there's no documentation yet :crying_cat_face:).

**Comment by takeit** [comment]
good news! Could you point me directly where it is implemented in Core, please?

Sure, I will take a look into this synchronization :)

**Comment by pamil** [comment]
In the code: `Sylius\Component\Core\Theme\ChannelBasedThemeContext`
In the Behat features: `features/channel/managing_themes_per_channel.feature` and `feature/channel/displaying_themed_channel_webiste.feature`
In the administration panel: you can set theme per channel while editing channel

**Comment by takeit** [comment]
Hi @pamil I managed to find some time and do some changes in regards of this PR. I'm gonna create a PR today and push my changes but I was wondering, why do you need so many [repositories](https://github.com/Sylius/SyliusThemeBundle/tree/master/Repository) what's the reason behind it ? You also catch some exceptions, e.g. here in [find()](https://github.com/Sylius/SyliusThemeBundle/blob/master/Repository/FailsafeThemeRepository.php#L59) method of the `FailsafeRepository` but this will never throw an error but will return `null` instead. Maybe I am missing something ?

Another thing is that in `InMemoryRepository` you are [loading all themes](https://github.com/Sylius/SyliusThemeBundle/blob/master/Repository/InMemoryThemeRepository.php#L31) in construct which is not a good idea imo, this should be delayed as much as possible, imagine you have a lot of themes, it will take some time to load them all from files.

**Comment by takeit** [comment]
> Another thing is that in InMemoryRepository you are loading all themes in construct which is not a good idea imo, this should be delayed as much as possible, imagine you have a lot of themes, it will take some time to load them all from files.

ahh ok I just noticed this service is lazy loaded :)

**Comment by pamil** [comment]
Theme synchronisation has been removed and ThemeBundle has been reworked once again, I guess it can be closed.
