### ISSUE TITLE
Access Denied in API endpoints using a custom user

### ISSUE THREAD

**Issue by xantrix** [Sylius/Sylius#4294]
I got an "Access Denied." trying to use API endpoints with my Admin user (rather than api@example.com user), also setting "Can access REST API" permission correctly.

This may occur due to ROLE_API vs ROLE_API_ACCESS as security role.
Everything works well using ROLE_API_ACCESS so I made a PR for changing old references
#4290 

Let me know if anyone experienced the same issue.
![sylius-can-access-rest-api](https://cloud.githubusercontent.com/assets/2573859/13291837/a2126b68-db19-11e5-98e9-8eeaff86d112.png)

**Comment by pjedrzejewski** [comment]
:+1: for reporting and fixing, awesome!
