### ISSUE TITLE
Modifying Order after finalizing results in stock faults

### ISSUE THREAD

**Issue by goemaere** [Sylius/Sylius#4298]
Given following workflow:

Customer puts ProductVariant in Cart
Starts checkout
Chooses to pay on an external payment provider site
Finalizes Order >> ProductVariant OnHold
Customer is redirected to the external payment provider site
Customer changes his mind, does not pay, and goes back/back/back in browser
Customer empties Cart
ProductVariant stays OnHold 

>> Stock faults

+ I can imagine some other bugs if the Customer puts other stuff in his Cart or uses a Coupon code

**Comment by pjedrzejewski** [comment]
What version are you using? In #4054 we have extracted the purchase step out of checkout flow, so as soon as you confirm your order you leave the checkout and cannot modify it.

**Comment by goemaere** [comment]
Not on master, seems like the changes in #4504 would be a solution for this bug. I guess this issue can be closed than. Would you recommend using master in production at this moment?

**Comment by okwinza** [comment]
@goemaere Sylius is yet to hit stable release so master is the way to go if you don't want to mess with all the bugs that already fixed here.

As a drawback you might have to rebase your stuff once in a while to be in sync with master.

**Comment by michalmarcinkowski** [comment]
That is already fixed.
