### ISSUE TITLE
How do you generate all the specs with is initializable?

### ISSUE THREAD

**Issue by lfbn** [Sylius/Sylius#4300]
Hi,

I've noticed that in the source code there are several spec files with only the is initializable method. This was generated automatically for all existing classes, or manually?

Thanks!

**Comment by pjedrzejewski** [comment]
These are probably remains of first steps with phpspec, when we thought it is a good idea. Speccing existing code does not make sense unless it does not work correctly, then you spec it and pretty much implement from scratch. So generating it for all classes does not make sense. To answer your question - it was done manually. :)

```bin/phpspec desc Foo/Bar`` creates a blank spec with ``it_is_initializable`` example. :) Please reopen if you have further questions. :)
