### ISSUE TITLE
Mailer needs pre_render event

### ISSUE THREAD

**Issue by Tetragramat** [Sylius/Sylius#4329]
Not actual EMAIL_PRE_RENDER https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/MailerBundle/Renderer/Adapter/TwigAdapter.php#L66, 
but the real one.
I have two examples where I need pre_render event:
1. change subject/body template depending on data
2. switch locale before (and after) render in case the actual locale is not the same as recipients locale

**Comment by Tetragramat** [comment]
In current sylius 1.0.5 is issue still actual.
In https://github.com/Sylius/Sylius/blob/v1.0.5/src/Sylius/Bundle/MailerBundle/Renderer/Adapter/EmailTwigAdapter.php#L45 is called event EMAIL_PRE_RENDER which is AFTER rendering of the email. 
If I want to change locale/data/etc before rendering of the template then I need to do hack to call render again.

**Comment by leroy0211** [comment]
Issue stil exists. 
The `SyliusMailerEvents::EMAIL_PRE_RENDER` is dispatched when the email is already rendered, so it should be called `SyliusMailerEvents::EMAIL_POST_RENDER`. 

A REAL `SyliusMailerEvents::EMAIL_PRE_RENDER` should be dispatched too (with the email and data).
