### ISSUE TITLE
Crowdin translation context not in sync with current Sylius version

### ISSUE THREAD

**Issue by kasrakhosravi** [Sylius/Sylius#4333]
I came across few instances in Crowdin which the context was different from the actual form label. For instance under ShippingBundle/messages.en.yml in Crowdin we have `additional_item_cost` while it should be `additional_unit_cost`. I was wondering if the Sylius version which is available in Crowdin is different from the current Sylius we are currently using in our project and if yes, is it possible to update the Crowdin contexts?

We have also started translating Sylius in Persian. Can you also merge it into codebase?
https://crowdin.com/project/sylius/fa#

**Comment by ahmadrabie** [comment]
:+1:

**Comment by aramalipoor** [comment]
:+1:

**Comment by aramalipoor** [comment]
@pjedrzejewski :+1:

**Comment by pamil** [comment]
I've just generated one by hand - #4354, there's some issue with capturing translations from ThemeBundle's fixtures I'll have to fix :)

**Comment by michalmarcinkowski** [comment]
Should be fine already, please reopen if something is still incorrect
