### ISSUE TITLE
[Theme] Theme bundle is not installable 

### ISSUE THREAD

**Issue by ahilles107** [Sylius/Sylius#4334]
There is no stable release of sylius/resource-bundle (no ^0.17 version on github/packagist) - so bundle is not installable now ;/ 

//cc @pamil 

```
$ composer update sylius/theme-bundle
Loading composer repositories with package information
Updating dependencies (including require-dev)


  [Composer\DependencyResolver\SolverProblemsException]
    Problem 1
      - Installation request for sylius/theme-bundle 0.17.x-dev -> satisfiable by sylius/theme-bundle[0.17.x-dev].
      - sylius/theme-bundle 0.17.x-dev requires sylius/resource-bundle ^0.17 -> no matching package found.
  Potential causes:
   - A typo in the package name
   - The package is not available in a stable-enough version according to your minimum-stability setting
     see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
```

**Comment by ahilles107** [comment]
And why we need now `sylius/resource-bundle` instead just `sylius/resource`? It creates for us new problems (like downgrading `fos/rest-bundle` from 2.0 to 1.5).

**Comment by pamil** [comment]
@ahilles107 You need to add the following lines to your `composer.json`:

```
"minimum-stability": "dev",
"prefer-stable": true,
```

It wasn't an issue before as you probably had `sylius/resource` in your `composer.json` required too.

Resource bundle is required in order to allow easier model overriding and support for multiple drivers achievable with minimal effort. Anyway, `friendsofsymfony/rest-bundle` is used only in `ResourceController`, which isn't used. Is there any way not to require it or require it conditionally? /cc @pjedrzejewski

**Comment by michalmarcinkowski** [comment]
@ahilles107 I think `sylius/resource-bundle` should be compatible with the `friendsofsymfony/rest-bundle: ^2.0` you can try to update the `composer.json` and check if there are any incompatibilities.

**Comment by ahilles107** [comment]
I all works on our side - we did for now alias in composer.json for it. But i didn't checked it with Sylius (if all tests pass after upgrading it to 2.0). You think that i can be changed in sylius/resource-bundle require section?

**Comment by michalmarcinkowski** [comment]
If there are no incompatibilities with Sylius in `2.0` I think we could change require to `^1.5|^2.0`. /cc @pjedrzejewski

**Comment by ahilles107** [comment]
Yep, but 2.0 is still not released/tagged (it's 2.0.x-dev) - it will not be a problem?

**Comment by michalmarcinkowski** [comment]
I thought it's released already :) Sorry for the hassle, but we should depend only on stable versions :disappointed:

**Comment by ahilles107** [comment]
I thought so. It's still in development https://packagist.org/packages/friendsofsymfony/rest-bundle. So for us only option is aliasing it in composer.json. 

But anyway - my issue is solved after adding 

```
"minimum-stability": "dev",
"prefer-stable": true,
```

Thank You @pamil.
