### ISSUE TITLE
[SEO] Channel locales, prevent duplicate content

### ISSUE THREAD

**Issue by koemeet** [Sylius/Sylius#4342]
Right now you can assign the same locale multiple times to different channels, this can cause duplicate content which is really bad for SEO.

I think a good solution is to make a unique constraint between a channel and a locale, so that a different channel cannot have a locale that is already linked to a channel.

So if `Channel A` has locales `en_US` and `nl_NL`, then `Channel B` cannot be linked to `en_US` and `nl_NL`.

WDYT?

**Comment by peteward** [comment]
I think this assumes too much about your particular use-case of channel (although probably the most common one).

Channels could be used to distinguish a mobile app feed from a website so would break this use-case.

**Comment by steffenbrem** [comment]
@peteward Indeed you are right, but wouldn't it then be good to define what kind of type a specific channel is? So you the locale constraint only applies to `website` type channels. I think it is good to enforce good SEO. In your case you could define the mobile app feed channel as anything other than the `website` channel type and so it could assign the same locale again.

I really think something has to change here.

**Comment by peteward** [comment]
In our case we actually have an extra layer of Zone with scope = content between Channels and locales. Channel can have many Content Zones which have a single Locale.

So our implementation is different again and your suggestion wouldn't affect us negatively :)

I think that there are many pitfalls to SEO and I'm not sure that enforcing an application-level restriction is necessarily the best way to prevent one here. I don't know what other people think?

**Comment by tristanbes** [comment]
> Channels could be used to distinguish a mobile app feed from a website so would break this use-case.

True.
