### ISSUE TITLE
[Theme] Translator fallbacks not working

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4343]
We're not using themes yet, I've just updated to master and fallback locales don't work. Is there something I need to configure?

0.16 (well about 4 weeks ago..):

![image](https://cloud.githubusercontent.com/assets/7068515/13380292/1b39356a-de37-11e5-9abc-1119e2d8ad46.png)

master:

<img width="562" alt="screen shot 2016-02-28 at 17 30 32" src="https://cloud.githubusercontent.com/assets/7068515/13380707/04b0ad8c-de41-11e5-8dac-77eccd75cd16.png">

**Comment by peteward** [comment]
Updated with the correct second screenshot!

**Comment by pamil** [comment]
Good catch Peter, I'm on it! :)

**Comment by pjedrzejewski** [comment]
Thank you @peteward for reporting!

**Comment by peteward** [comment]
thank you both for resolving so quickly - I'll continue the update... :+1:
