### ISSUE TITLE
What is the plan for multiple store?

### ISSUE THREAD

**Issue by videni** [Sylius/Sylius#4344]
I only found document related to store  [here](http://docs.sylius.org/en/latest/book/channels.html) , it says 

> Channel model represents a single sales channel, which can be one of the following things:
>Webstore
>Mobile application
>Cashier in your physical store
>Or pretty much any other channel type you can imagine.

But it is still not clear what the multi-store will be. from my understanding,  I think  multi-store is much like amazon.com,  a retailer  wants to sell his products on amazon.com, then he asks administrator of amazon.com to create a store form him, he logins in  and  adds his products ,  starts to trade.  I think it's very important to clarify  the direction of  a functionality, so the community knows how to contribute.

**Comment by gabiudrescu** [comment]
are you talking about multi-tenant Sylius instances? 

something like shopify?

**Comment by gperdomor** [comment]
@patkar and own users/customers?

**Comment by videni** [comment]
@patkar,yep, that is what I think,  will sylius go this way?

**Comment by okwinza** [comment]
Hey @videni.
From your description it looks like you're talking about some sort of "Patform as a Service" behaviour.
I highly doubt Sylius will go this way because it is not generic and should stay out of scope of this repo at least IMO.

The current multi-channel implementation relies on shared users/orders/products/etc data otherwise it's not a channel but a completely different Sylius installation.

Although i'm pretty much argee with @patkar that there is still a room of stuff to implement for proper multi-channel support.

**Comment by videni** [comment]
@okwinza ,@patkar, sorry for I din't describe it clearly, this is what I thought multi-channel is: 

1.  A channel doesn't manage customers, but it has channel administrators.
2.  A store admin can only manage products belonged to his channel.
3.  A customer can buy products from each channel.

it is much like ebay.If  Sylius doesn't go this way, it might be better if  we separate it properly , so it is  possible for us to extend it.

**Comment by patkar** [comment]
This is not what multi-channel in eCommerce means. Channels are separate sales-channels, e.g. a own mobile shopping app (via API), a ebay/amazon export, Points of Sale, etc.

Not a marketplace what you mean

**Comment by steffenbrem** [comment]
Indeed what @patkar is saying, multi-channel is implemented correctly in Sylius right now.

@videni What you are looking for is implementing an extra layer (I do that too), let's call it a `Workspace`. Almost all root entities will be linked to a single `Workspace` (channels, products, taxonomies etc.). In your case you would have multiple workspaces containing a single `Channel` that will represent the online shop. You do not want to abuse channels to achieve what you want. 

With that setup each tenant could have a it's own workspace (or even multiple), it's then up to you if you want to abstract away multi-channel or not.

**Comment by videni** [comment]
@steffenbrem, @patkar ,thanks for pointing me the right direction.

**Comment by enekochan** [comment]
@steffenbrem I'm new to Sylius and I need to implement that same extra layer to be able to have multiple stores (each store in a different subdomain with it's own separated products, customers, users, ...). Could you elaborate in how you made it work? Thanks!

**Comment by younes0** [comment]
@enekochan did you figure it out ?

**Comment by enekochan** [comment]
@younes0 Haven't started with this yet but found this PR that may be helpful https://github.com/Sylius/Sylius/pull/3479
