### ISSUE TITLE
[Theme] After rebasing with master sylius.theme.repository.failsafe.inner does not exist

### ISSUE THREAD

**Issue by aramalipoor** [Sylius/Sylius#4358]
@pamil I was using ThemeBundle in our project but after rebasing with that HUGE refactor now I see this error and I don't have a clue why?! Can you help me through this update? Should I wait for a few weeks before rebasing with Theme? :)

By the way you did an amazing job in ThemeBundle! Cheers :beers: 

```
[Symfony\Component\DependencyInjection\Exception\InvalidArgumentException]  
The service definition "sylius.theme.repository.failsafe.inner" does not exist.   
```

It is of course related to, `ThemeBundle/Resources/config/services/driver/doctrine/orm.xml`
```xml
<service id="sylius.theme.repository.failsafe"
        class="%sylius.theme.repository.failsafe.class%"
        decorates="sylius.repository.theme"
        public="false">
  <argument type="service" id="sylius.theme.repository.failsafe.inner" />
  <argument type="service" id="sylius.theme.repository.in_memory" />
</service>
```

**Comment by pamil** [comment]
Hello Aram! Could you determine the stacktrace of this exception? I've got no idea what may cause it right now.

**Comment by aramalipoor** [comment]
Now It's fixed. I don't know why!? 

But anyway should `<argument type="service" id="sylius.theme.repository.failsafe.inner" />` be `<argument type="service" id="sylius.repository.theme.inner" />`?

**Comment by pamil** [comment]
IMO this was an issue related to old container cache. That decorator syntax is valid and [symfony docs](http://symfony.com/doc/current/components/dependency_injection/advanced.html#decorating-services) confirms it.

**Comment by pamil** [comment]
@aramalipoor I guess it can be closed :)

**Comment by aramalipoor** [comment]
Sorry for late response, yes it works perfect now ;)
