### ISSUE TITLE
Channel could not be found

### ISSUE THREAD

**Issue by vikey89** [Sylius/Sylius#4360]
Hi guys,
if you try to add more than one channel you should get this error in home page:

An exception has been thrown during the rendering of a template ("Channel could not be found!") in SyliusWebBundle:Frontend:layout.html.twig at line 57.

You can add the new channel in demo sylius site and you should get error in home page.

**Comment by pjedrzejewski** [comment]
The logic is following:

If you have a single channel - it automatically resolves it on whatever hostname. If you have more than 1, you need to configure hostnames. Later we want to add a nice page pointing you to the backend on admin and something pretty for the customer.

**Comment by vikey89** [comment]
ok thanks for your support request :)
