### ISSUE TITLE
[Crodwin] Missing files

### ISSUE THREAD

**Issue by gperdomor** [Sylius/Sylius#4363]
I tried to translate <code>messages</code> file of <code>ResourceBundle</code> but only <code>flashes</code> and  <code>validations</code> are available.

Actual content of spanish translation is:
<code><pre>sylius:
  form:
    collection:
      add: Añadir
      delete: sylius.account.address.action.delete
</pre></code>

**Comment by pamil** [comment]
It looks like Crowdin treats this file as duplicated.

![screen shot 2016-03-01 at 14 32 50](https://cloud.githubusercontent.com/assets/1897953/13428403/a27e8668-dfba-11e5-92e3-c906d91e8306.png)

**Comment by pamil** [comment]
If you search for "Delete":

https://crowdin.com/translate/sylius/all/en-es#q=Delete

There's `sylius.form.collection.delete` just under `sylius.account.address.action` as a duplicate, I don't know whether it is what we want to achieve, as two translations may have the same value in English but not in other languages.

**Comment by gperdomor** [comment]
@pamil any way to prevent this behaviouir? if happen in Spanish, can happen in any language too.

**Comment by pamil** [comment]
@gperdomor should be fixed by now, let me know if there's any new problem :)

**Comment by pjedrzejewski** [comment]
@gperdomor Please reopen if still exists.
