### ISSUE TITLE
[Bug] installing a clean version of Sylius renders an error

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#4367]
Steps to reproduce:

- run `composer create-project sylius/sylius`

What happens:

I receive some errors:
```
> Symfony\Cmf\Bundle\CreateBundle\Composer\ScriptHandler::downloadCreateAndCkeditor
Download or update create
Script Symfony\Cmf\Bundle\CreateBundle\Composer\ScriptHandler::downloadCreateAndCkeditor handling the post-install-cmd event terminated with an exception

                                                
  [ErrorException]                              
  chdir(): No such file or directory (errno 2)  

```

Initially, I thought this was a problem of our Sylius instance, where we also encountered this, but it seems I can reproduce it with Master too. 

In another Sylius instance where we have CI enabled, we have solved this the quick & dirty way:
`mkdir vendor/symfony-cmf/create-bundle/Resources/public/create -p`
`mkdir vendor/symfony-cmf/create-bundle/Resources/public/vendor -p`
and only then
`composer install --no-interaction --optimize-autoloader --dev --verbose`

I don't think this is a Sylius issue per-se, but rather something inherited from CKEditor / CMF bundle. 

---
Later edit: after managing to run Sylius on the localhost, I bumped into the error below - I suspect it's linked somehow with the issue above - the fact Composer did not finish install phase entirely and correctly.

```
An exception has been thrown during the compilation of a template ("Unable to find file "@CmfCreateBundle/Resources/public/vendor/create/lib/jquery-htmlclean/jquery.htmlClean.js".") in "CmfCreateBundle::includejsfiles-hallo.html.twig".

```

--- 
Later later edit: using the trick from CI solved the issue on localhost too. 

I'd tag this bug as DX :)

**Comment by michalmarcinkowski** [comment]
Fixed as we don't use Ckeditor anymore.
