### ISSUE TITLE
[Bug] Can not increase order-item-unit quantity from existing order

### ISSUE THREAD

**Issue by sjonkeesse** [Sylius/Sylius#4368]
When I increase the item quantity in an existing order I get an error that some parameters are missing for inserting new order-item-units. This error occurred recently in the master branch.

![screenshot 2016-03-01 10 13 19](https://cloud.githubusercontent.com/assets/1044439/13442303/d6b92c9e-dffb-11e5-99f2-e01a3393f723.png)

**Comment by steffenbrem** [comment]
When removing the `$uow->commit($entity)` line in the `OrderItemInventoryListener` it updates the order item correctly and the unit is also added. Not sure why this code is in there, it seems that is the trouble maker.

**Comment by steffenbrem** [comment]
@umpirsky @winzou Do you know what is going on here? It has been a while since the `OrderItemInventoryListener` has been made, but I don't know for sure if the `commit` can be left out or not.

**Comment by umpirsky** [comment]
@steffenbrem I guess it is there for a reason. You can experiment by removing it and submitting pull request, we will see - if the build fails, then it needs to stay probably. :)

**Comment by michalmarcinkowski** [comment]
Should be fixed now.
