### ISSUE TITLE
[Admin] Managing currencies

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#4375]
* [x] Adding
* [x] Validation of currency code uniqueness
* [x] Validation of required fields
* [x] Editing (checkbox)
* [x] Immutability of currency code while editing
* [ ] Toggling (via Ajax) on index
* [ ] Prevent editing of base currency

**Comment by michalmarcinkowski** [comment]
Because of #4589 I would also add:
* [ ] Prevent editing of base currency

**Comment by pjedrzejewski** [comment]
@michalmarcinkowski :+1:
