### ISSUE TITLE
[DX] Using assertion library in component classes

### ISSUE THREAD

**Issue by gperdomor** [Sylius/Sylius#4376]
Hi...

Currently, Sylius handle some validations inside <code>set</code> methods, for example, in <code>ProductVariant</code> we have the following <code>setPrice</code> function:

<pre><code>public function setPrice($price)
{
    if (!is_int($price)) {
        new \InvalidArgumentException('Price must be an integer.');
    }
    $this->price = $price;
    return $this;
}</code></pre>

The variable type is validated, but you can set a negative price, which is not logic for me, so you can fix it with this:

<pre><code>public function setPrice($price)
{
    if (!is_int($price)) {
        new \InvalidArgumentException('Price must be an integer.');
    }

    if (!$price > 0) {
        new \InvalidArgumentException('Price must be greater than 0.');
    }

   ... // More validations

    $this->price = $price;
    return $this;
}</code></pre>

What do you think about using [this](https://github.com/webmozart/assert) to handle this situations and get an more cleaner code? for example:

<pre><code>public function setPrice($price)
{
    Assert::integer($price, 'The price must be an integer. Got: %s');
    Assert::greaterThan($price, 0, 'The price must be a greater than 0. Got: %s');

    $this->price = $price;
    return $this;
}</code></pre>

**Comment by michalmarcinkowski** [comment]
There is already pending discussion [here](https://github.com/Sylius/Sylius/issues/3928).

**Comment by gperdomor** [comment]
@michalmarcinkowski thanks, i will cose this...

**Comment by gperdomor** [comment]
Closed... Duplicate of #3928
