### ISSUE TITLE
[Product Review] Using interface instead of class implementation

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4381]
I'm fairly sure that these should be interfaces not class implementations?:

https://github.com/Sylius/Sylius/blob/3c02eef2a12a76062317af94b971bb0b183d3476/src/Sylius/Bundle/CoreBundle/Form/Type/ProductReviewAdminType.php#L35

I get an error because it's trying to use a `sylius_customer` database table instead of a `reiss_customer` one, I presume the same is true of Product.

Although, I can't be sure that changing it definitely works since trying to load 1,000,000 customers and 100,000 products into select boxes kinda blows up my webserver :)

**Comment by michalmarcinkowski** [comment]
Of course these should be interfaces, thanks for reporting :+1: 

Regarding select boxes, the autocomplete is coming soon! :)

**Comment by nakashu** [comment]
These form types have probably the same problem i guess?

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Form/Type/OrderItemType.php#L55
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Form/Type/Api/OrderItemType.php#L32
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Form/Type/Api/ProductType.php#L30

**Comment by michalmarcinkowski** [comment]
Fixed already.
