### ISSUE TITLE
[Metadata] How do I use it?

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4382]
All I've got is a button to edit default metadata, I can't add anything else for an entity:

![screen shot 2016-03-03 at 09 13 13](https://cloud.githubusercontent.com/assets/7068515/13489682/4f25c82a-e120-11e5-9080-d19971c0d319.png)

**Comment by pjedrzejewski** [comment]
@peteward We definitely need to prepare docs, but just a quick hint: http://demo.sylius.org/administration/metadata/customize/Product-101

**Comment by peteward** [comment]
How do you get to that page? :)

**Comment by pamil** [comment]
@peteward I've put the product metadata customization button on product index page :)

![screen shot 2016-03-03 at 10 21 25](https://cloud.githubusercontent.com/assets/1897953/13489890/c1cfc624-e129-11e5-9fd6-8904c4865350.png)

**Comment by peteward** [comment]
ahhhh ok.  Any other places or just products for now?  Sorry it was such a huge PR I haven't read it fully for a long time...

**Comment by pamil** [comment]
We no longer have Metadata component & bundle in `Sylius/Sylius`.
