### ISSUE TITLE
PHPCR per channel

### ISSUE THREAD

**Issue by yopop666** [Sylius/Sylius#4399]
Hi,
I want to make blocks available per channel.
I think that phpcr_node table must have channel_id column and after this to filter in repository by channel if it is given in criteria.
1. It is good my logic?
2. How can I add channel_id to  phpcr_node?I did't know what entity to extend to implement this logic.
3. What repository should be extended to add filter by channel?

**Comment by patkar** [comment]
The phpcr tables exist only as underlying tables for the PHPCR-DBAL implementation. If one would switch to jackrabbit, you would not have phpcr tables anymore, thus you can not add channel_id to PHPCR. There is no entity for PHPCR.

IMHO the correct way would be a global PHPCR workspace for global snippets and then one workspace per channel for channel scoped content.

**Comment by yopop666** [comment]
Thank you for answer @patkar.
Suppose that I have a new namespace 'test_namespace'.To preserve sylius logic I must create default sylius paths, but with namespace 'test_namespace'?
example
Sylius defaults:
/  with namespace 'default'
/cms  with namespace 'default'
/cms/blocks with namespace 'default'
/cms/pages with namespace 'default'
/cms/menus with namespace 'default'


/  with namespace 'test_namespace'
/cms  with namespace 'test_namespace'
/cms/blocks with namespace 'test_namespace'
/cms/pages with namespace 'test_namespace'
/cms/menus with namespace 'test_namespace'

**Comment by patkar** [comment]
Sorry, I'm not in deep in Sylius PHPCR implementation. It was only a quick explanation how PHPCR works, and that it is not be simple as adding a channel_id column to the phpcr tables.

**Comment by steffenbrem** [comment]
@yopop666 You want to have a uni-directional mapping from the ORM to PHPCR. I've made a gist for you containing code I use to be able to map multiple (or one) `Channel` objects to a single PHPCR node (for example a `SimpleBlock` document). 

The gist: https://gist.github.com/steffenbrem/237e54f51c59e7b793a8

The `AbstractReferenceListener` is a base class used to easily map a specific PHPCR document to ORM entities. It supports lazy references and a lazy collection, so no queries are made to the MySQL db when fetching a block from the content repository (until you call `$document->getChannels()` of course). 

You can implement your own by extending the `AbstractReferenceListener` and implement the required abstract methods that is needs to be able to achieve a proper mapping between your entities and PHPCR documents.

You then need to register your listener so `doctrine_phpcr` picks up changes or load events to your document. A service definition will look something like this:

```
<service id="mango_content.listener.phpcr.channels_reference" class="Mango\Bundle\ContentBundle\EventListener\PHPCR\ChannelsReferenceListener">
    <argument type="service" id="doctrine.orm.entity_manager"/>
    <tag name="doctrine_phpcr.event_subscriber" priority="-1"/>
</service>
```

**Comment by steffenbrem** [comment]
@yopop666 Did you solve this?

**Comment by steffenbrem** [comment]
You could also simply use the channel as a parent path, so store it under `/cms/channels/1/pages`. This is how I have implemented it myself right now, since it didn't make sense to have the same page on 2 or more channels (aka webshops).
