### ISSUE TITLE
[RFC] Prefer stable in bundles' & components' composer.json

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#4408]
Right now, we download unstable dependencies and this may end with dev dependencies everywhere, failing tests and some unusual packages installed together:

```
- Installing symfony/twig-bridge (3.0.x-dev 75a8e36)
    Cloning 75a8e368c3bba891f9f8ce9dfc92a47a2bef869d
- Installing symfony/twig-bundle (2.8.x-dev 166c91b)
    Cloning 166c91ba49b2e7272052fc15327eab3a1947e3c1
```

The solution is to add `"prefer-stable": true` so we won't install any dev dependencies unless it is really needed. It should also install faster.

**Comment by pjedrzejewski** [comment]
:+1:

**Comment by pamil** [comment]
Already applied
