### ISSUE TITLE
[Behat] Not all scenarios are included in travis build

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#4410]
_edited_
During work on #3854 I had plenty places where my code could not work, and because of that I decided to run behats feature after feature on my local machine. It seems that some of suits are not included to travis build. For example tags `@legacy_product` or `@legacy_orders`
![zrzut ekranu 2016-03-07 o 17 37 04](https://cloud.githubusercontent.com/assets/6213903/13576042/fba9ec7a-e48b-11e5-841c-5023861f86a3.png)

**Comment by pamil** [comment]
There's no `legacy_products` suite. The `@legacy_products` is a tag. Running Behat with specific file will test the feature using every suitable suite, in this case - `@legacy_products` is still parsed by `products` suite. This may lead to confusion :)

IMHO the suites with tags `@legacy_products` should be tagged as `@legacy @product`, the suite name should be renamed from `products` to `legacy_product` and it should filter the scenarios by `@legacy && @product`.

This way we can run all product suites by `behat --tags @product` - both the legacy ones and the future ones in each possible environment (`ui`, `domain`, etc.)

**Comment by lchrusciel** [comment]
@pamil, ok I didn't explain problem correctly. And sure, what have you written make sense. But still It doesn't resolve problem of broken tests. I have found at least 3 places where the code is broken, but tests are still green.

**Comment by pamil** [comment]
Where are these broken tests? The one scenario from the screenshot is executed on Travis and it is passing.

**Comment by pjedrzejewski** [comment]
I don't think we should spend too much time working on the legacy, let's leave it as is. ;) We will remove them soon. :D

**Comment by michalmarcinkowski** [comment]
@lchrusciel I verified that all scenarios are executed on travis. I also checked it on my local env and the scenariou you mentioned wasn't passing on `master` branch for me also, but after cache clear it is green now :)

**Comment by lchrusciel** [comment]
Commands I used to reproduce this issue:
```
git pull upstream master
rm -fr app/cache/*
app/console do:da:dr --env test --force
app/console do:da:cr --env test
app/console do:sc:cr --env test
bin/behat features/legacy/backend/orders.feature --stop-on-failure 
```
Result?
![bugzol](https://cloud.githubusercontent.com/assets/6213903/13602779/fffd1d80-e538-11e5-8e28-5170bed0e310.png)

It has to be broken, because I forgot to remove deleted property from orders twig template... I want to fix it right now, but still I guess there is an issue.

**Comment by michalmarcinkowski** [comment]
This scenario is executed, but maybe [this](https://github.com/michalmarcinkowski/Sylius/blob/16750b4f651a21172f82af97050af85f4d3da7af/src/Sylius/Bundle/ResourceBundle/Behat/WebContext.php#L42) silences the exception and the status code is not validated on travis what makes this step green?

**Comment by pamil** [comment]
@michalmarcinkowski that assertion is run and does not throw `UnsupportedDriverActionException`.

I think that it passes on Travis as we're using production-like (`test_cached`) environment instead dev-like (`test`).

**Comment by pamil** [comment]
Fixed by #4438, can be closed.

**Comment by lchrusciel** [comment]
:tada:

**Comment by michalmarcinkowski** [comment]
@lchrusciel and @pamil good job! :+1:
