### ISSUE TITLE
[Fixtures][Install] OutOfBoundsException while installing fixtures

### ISSUE THREAD

**Issue by Zales0123** [Sylius/Sylius#4411]
After recent changes on *Syliius* master, there is (again) problem with loading sample data.
![zrzut ekranu 2016-03-07 o 20 49 57](https://cloud.githubusercontent.com/assets/6212718/13581255/4f2f1900-e4a6-11e5-8440-88ca503458c6.png)

I think it's next reason, why we should definitely implement Sylius installation tests as soon as possible ;)

**Comment by gonzalovilaseca** [comment]
Having same error here too.

**Comment by pjedrzejewski** [comment]
Fix provided in https://github.com/Sylius/Sylius/pull/4421.
