### ISSUE TITLE
Sylius can not guarantee that the state choice types have the same states as the state machine

### ISSUE THREAD

**Issue by sjonkeesse** [Sylius/Sylius#4412]
Currently the order, payment, shipping etc. state choice types currently have there states defined statically, for example:  https://github.com/Sylius/Sylius/blob/2b3d386df2ad60de968e19fb63720194083fa3fe/src/Sylius/Bundle/OrderBundle/Form/Type/OrderStateChoiceType.php#L28

For example the `released` state is missing but defined in the state machine:
https://github.com/Sylius/Sylius/blob/322157b1f02dd1b101c2b13588b876de79b7dbdb/src/Sylius/Bundle/OrderBundle/Resources/config/state-machine.yml#L11

Because of this the states are not always in sync (as it is now also in the file linked before). Wouldn't it be a better idea to have the state machine state configurations from the `sm.configs` container parameter be injected into those choice types? This way you can guarantee that you can only set states as defines in the state machine.

How should we approach this problem.

**Comment by michalmarcinkowski** [comment]
Fixed.
