### ISSUE TITLE
0.14 to 0.17 migrations issues

### ISSUE THREAD

**Issue by MichaelMackus** [Sylius/Sylius#4414]
Is there any reason why taxons, promotions, etc. are using the new "CodeAwareInterface"? It doesn't look like its being referenced at all, and its quite troublesome IMO since users will have to modify all the sylius migrations to update the `code` field to a relevant & unique value. I don't see what the use of a `code` field on the Taxon, for example - there's already an `id`, `slug`, and `name` that seems to cover all the bases.

I understand for something like shipping method/category, but it seems like its littered everywhere in many entities in the system.

**Comment by okwinza** [comment]
The main purpose is to have a valid persistent identificator for an entity which is not affected by environment change. `id` is auto-generated thus unreliabe, `slug` is based on locale and so on.

For example, it is critical when you're managing your stuff via some ERP-like software.
This way you can use `code` field to link your Sylius entity(product, taxon, etc) to ERP one.

**Comment by MichaelMackus** [comment]
@okwinza got it. I figured it out after enough migration tweaking.

Maybe it would be helpful to add some more documentation in the Upgrade markdown docs. I noticed the migrations were incomplete and took a lot of tweaking.

If I find some time I will submit a PR. Its good to have persistent ids though, and agree its a step in the right direction

**Comment by pjedrzejewski** [comment]
@MichaelMackus Hey Michael, sorry for problems with upgrade, but Sylius is moving quite fast right now - we are doing our best to provide some help, but most of energy goes to development. I will be happy to accept a PR with some tips for upgrade based on your experience, thanks!

**Comment by MichaelMackus** [comment]
Understandable, thanks for the input. Happy with all the changes so far and this is definitely a fast moving project!

I have a few things to submit, just have to get them organized and submit a proper PR when I find the time.
