### ISSUE TITLE
Unrecognized option "classes" under "sylius_order" 

### ISSUE THREAD

**Issue by solve-it** [Sylius/Sylius#4420]
i installed SyliusCartbundle on my symfony 2.8.3 app and after config  when i run  
$  php app/console doctrine:schema:update --force

i get error
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  ←[39;49m
←[37;41m  Unrecognized option "classes" under "sylius_order" 

this is my config .yaml
sylius_cart:
    resolver: app.cart_item_resolver # The id of our newly created service.
    classes: ~ # This key can be empty but it must be present in the configuration.

sylius_order:
    driver: doctrine/orm # Configure the doctrine orm driver used in documentation.
    classes:
        order:
            model: AppBundle\Entity\Cart # If you have created a custom Cart entity.
        order_item:
            model: AppBundle\Entity\CartItem # If you have created a custom CartItem entity.

sylius_money: ~

**Comment by Zales0123** [comment]
Sylius resources configuration has changed a bit some time ago. [Look here](https://github.com/Sylius/Sylius/blob/master/UPGRADE.md#general) to see how does configuration should look like.

**Comment by solve-it** [comment]
I have changed my conf to 
sylius_cart:
    # The driver used for persistence layer.
    driver: ~
    # Service id of cart item resolver.
    resolver: app.cart_item_resolver
    # Cart provider service id.
    provider: sylius.cart_provider.default
    # The id of cart storage for default provider.
    storage: sylius.cart_storage.session
    resources:
        cart:
            classes:
                controller: Sylius\Bundle\CartBundle\Controller\CartController
                form:       Sylius\Bundle\CartBundle\Form\Type\CartType
            validation_groups:
                default: [ sylius ]
        cart_item:
            classes:
                controller: Sylius\Bundle\CartBundle\Controller\CartItemController
                form:       Sylius\Bundle\CartBundle\Form\Type\CartItemType
            validation_groups:
                default: [ sylius ]


now i get 

  [Symfony\Component\Config\Definition\Exception\InvalidTypeException]                             
  Invalid type for path "sylius_cart.resources.cart.classes.form". Expected array, but got string

**Comment by solve-it** [comment]
`sylius_cart:
    # The driver used for persistence layer.
    driver: ~
    # Service id of cart item resolver.
    resolver: app.cart_item_resolver
    # Cart provider service id.
    provider: sylius.cart_provider.default
    # The id of cart storage for default provider.
    storage: sylius.cart_storage.session
    resources:
        cart:
            classes:
                controller: Sylius\Bundle\CartBundle\Controller\CartController
                form:       Sylius\Bundle\CartBundle\Form\Type\CartType
            validation_groups:
                default: [ sylius ]
        cart_item:
            classes:
                controller: Sylius\Bundle\CartBundle\Controller\CartItemController
                form:       Sylius\Bundle\CartBundle\Form\Type\CartItemType
            validation_groups:
                default: [ sylius ]`

**Comment by aramalipoor** [comment]
```yml
  form: Sylius\Bundle\CartBundle\Form\Type\CartType
```
should be
```yml
  form:
    default: Sylius\Bundle\CoreBundle\Form\Type\CartType
```
for your previous comment.

**Comment by solve-it** [comment]
thanks
