### ISSUE TITLE
undefined method named "setVariant" error

### ISSUE THREAD

**Issue by solve-it** [Sylius/Sylius#4431]
when i try to add item to cart i get error
 Attempted to call an undefined method named "setVariant" of class "Sylius\Component\Cart\Model\CartItem". 

i made the setVariant call in my service 

`namespace AppBundle\Service\Cart;
use Sylius\Component\Cart\Model\CartItemInterface;
use Sylius\Component\Cart\Resolver\ItemResolverInterface;
use Sylius\Component\Cart\Resolver\ItemResolvingException;
use Doctrine\ORM\EntityManager;

class ItemResolver implements ItemResolverInterface
{
    private $entityManager;
    public function __construct(EntityManager $entityManager)
    {
        $this->entityManager = $entityManager;
    }
    public function resolve(CartItemInterface $item, $request)
    {
        $productId = $request->query->get('productId');

        // If no product id given, or product not found, we throw exception
        if (!$productId || !$product = $this->getProductRepository()->find($productId)) {
            throw new ItemResolvingException('Requested product was not found');
        }
        // Assign the product to the item and define the unit price.
        $item->setVariant($product);
        $item->setUnitPrice($product->getPrice());
        // Everything went fine, return the item.
        return $item;
    }
    private function getProductRepository()
    {
        return $this->entityManager->getRepository('AppBundle:Product');
    }
}`
am using syliusCartbundle v0.17.0 on symfony 2.8.3

**Comment by Zales0123** [comment]
It's correct. ``setVariant`` method is not method of class ``CartItem`` but ``OrderItem`` from *Core*, which extends ``CartItem``. As you're using *CartBundle* as standalone, there is no dependency between it and *CoreBundle*.

**Comment by pjedrzejewski** [comment]
@solve-it Yes, if you do not use core, you need to integrate the CartItem with whatever you need. Can be Product from Sylius or Book from your custom app, etc.
