### ISSUE TITLE
Set Promotion/Coupon to Order

### ISSUE THREAD

**Issue by vikey89** [Sylius/Sylius#4439]
Hi guys,
I’m migrating an old database with a brand new Sylius project and I need to have old orders with related promotions.
Can I create an order applying a discount through promotion/coupon?
I saw `setPromotionCoupon` on `Order` but it did not apply the discount.

**Comment by pjedrzejewski** [comment]
You will need to call the promotion applicator on order. :)

**Comment by vikey89** [comment]
Thanks Pawel :)
