### ISSUE TITLE
Empty and whithout i18n email templates

### ISSUE THREAD

**Issue by BlackIceWizard** [Sylius/Sylius#4440]
Hi!

Directories:

```
src/Sylius/Bundle/WebBundle/Resources/views/Email
src/Sylius/Bundle/WebBundle/Resources/views/Frontend/Email
```

include email templates to the client. But all templates except `passwordReset.html.twig` with an empty body. It's hard to guess what the dynamic information must be displayed in these templates for full customer information. Besides the information that is described in the template `passwordReset.html.twig` not multilingual. An experienced programmer will get out of this situation, but all others would have to:
1) look for these templates rather than simply correct translation in the translation files
2) look for some variables are omitted in these templates to correctly display the information about ordering and shipment
3) move the body of the message is already written in the template `passwordReset.html.twig` to the translation files

**Comment by pjedrzejewski** [comment]
WebBundle is gone. :)
