### ISSUE TITLE
[RFC] [Core] Remove sylius_taxation settings and move default tax Zone to Channel

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#4446]
Hi!

I think we should have default tax zone configurable per channel, not globally. It would make a lot of things simpler.

If you agree, the steps would be following:

* Write scenarios for choosing default tax zone in the admin area;
* Add ``defaultTaxZone`` field to Channel;
* Add select to the form;
* Remove sylius_taxation settings from services/code and UI;
* Update fixtures;
* Update tax related stuff (Processors etc.)

I actually think we can later do the same with shipping, add ``defaultShippingZone`` for channel, so that we can estimate shipping when we do not know the shipping address of the customer yet.

**Comment by michalmarcinkowski** [comment]
Done.
