### ISSUE TITLE
[Resource] Mapping with interfaces

### ISSUE THREAD

**Issue by gperdomor** [Sylius/Sylius#4447]
How can i use interfaces in YML mapping?.

Wich is the purpose of <code>interface</code> parameter inside <code>sylius_resource</code> configuration?.

I created a custom bundle, with entities configured as documentation says.

I know that i can do it extending <code>AbstractResourceBundle</code> and overriding the <code>getModelNamespace</code> and <code>getModelInterfaces</code> but there is a way to do it without do this, in a more simple way?

**Comment by pjedrzejewski** [comment]
Actually, it should work out of the box, if it's not - then it's a bug. :/

**Comment by gperdomor** [comment]
I'm using 0.17.0 and not work... tonith i will test with master branch

**Comment by gperdomor** [comment]
The problem is <code>ResolveDoctrineTargetEntitiesPass</code>, wich is called only when the bundle extends the <code>AbstractResourceBundle</code>

**Comment by gperdomor** [comment]
I try to play with <code>RegisterResourcesPass</code> to try to fix this issue.

First i change the <code>RegisterResourcesPass</code> to:

<pre><code>class RegisterResourcesPass implements CompilerPassInterface
{
    /**
     * {@inheritdoc}
     */
    public function process(ContainerBuilder $container)
    {
        if (!$container->hasParameter('sylius.resources')) {
            return;
        }

        $resources = $container->getParameter('sylius.resources');
        $registry = $container->getDefinition('sylius.resource_registry');

        $interfaces = [];

        foreach ($resources as $alias => $configuration) {
            $registry->addMethodCall('addFromAliasAndConfiguration', [$alias, $configuration]);

            if (array_key_exists('interface', $configuration['classes'])) {
                $alias = explode('.', $alias);
                $interfaces[$configuration['classes']['interface']] = sprintf('%s.model.%s.class', $alias[0], $alias[1]);
            }
        }

        $resolver = new DoctrineTargetEntitiesResolver();
        $resolver->resolve($container, $interfaces);
    }
}</code></pre>

That code handle the interfaces configured in every bundle's configuration tree, so the next step is remove the function <code>getModelInterfaces()</code> from the <code>SyliusXXXXXBundle.php</code> files. This cause that <code>ResolveDoctrineTargetEntitiesPass</code> do nothing (My idea is remove this compiler). I do this for all bundles except SyliusProductBundle which still use the old approach.

This approach seem to work, but for some reason, i get an error in phpunit [test](https://travis-ci.org/gperdomor/Sylius/builds/117202378).

For review the changes --> [here](https://github.com/gperdomor/Sylius/commit/2b96007cf6216a4bbffa60044c36e86718882da7)

I don't know if this is the best solution but at least is a first step to solve the issue.

**Comment by gperdomor** [comment]
ping @pjedrzejewski

**Comment by pjedrzejewski** [comment]
Sounds like a good solution! About PHPUnit test error, seems like service is missing, this exception is thrown by Sylius, so I'd look into the place where it is thrown and see why it is not there. Perhaps test setup is incorrect. :+1:

**Comment by pjedrzejewski** [comment]
This should be resolved by #4693.
