### ISSUE TITLE
[Variation] Product Options are broken on cyrillic locale

### ISSUE THREAD

**Issue by okwinza** [Sylius/Sylius#4449]
Prior to #4237 we had `name` field for internal use and translatable `presentation` to display for options. That internal name was useful to store transliterated name of an option which is then passed to a form builder and so on.

But with it gone and replaced with proper translatable `getPresentaion()` we now get an empty form name exception because Behat's `Urlizer::urlize()` cannot into cyrillic(it just returns empty string). 

Here is the [Breaking point](
https://github.com/Sylius/Sylius/blob/92949a767fd26ef54ecaade570eb86662998a80e/src/Sylius/Bundle/VariationBundle/Form/Type/VariantMatchType.php#L45)

Proposed solutions:

- Replace `Urlizer::urlize()` with something decent like `Slugify` which is available somewhere in `vendor` dir IIRC.
- Reintroduce a field to store transliterated name for internal use.

WDYT?

**Comment by michalmarcinkowski** [comment]
@okwinza can't we simply change `Urlizer::urlize($option->getName())` into `$option->getCode()`?

**Comment by pjedrzejewski** [comment]
:+1: That's is why having codes is cool.

**Comment by okwinza** [comment]
@michalmarcinkowski yes thats one possible way out but i'm not sure about readability. 
Are we fine with something like 'sylius_cart_item_variant_23' if `code` is just some kind of external id like in my case for example?

**Comment by michalmarcinkowski** [comment]
I think that this value is not processed nor displayed anywhere, so the readability doesn't matter here.
