### ISSUE TITLE
ThemeAwareTranslator bloats the container

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4450]
Hi,

Since updating to 0.17 with the Theme bundle the amount of memory required to compile the container is obscene.

I have been working with the Symfony team to reduce this and there will be an [improvement on the way](https://github.com/symfony/symfony/pull/18048) in an upcoming version. 

However, my container here is still 6MB. When compiled into opcache this is 12mb. It's a huge amount of memory to be consuming. 

While taking a look at the container there's one particularly long line - this ThemeAwareTranslator service is 250k characters long. I don't want to suggest too much micro-optimisation, but perhaps there could be another way of writing this that might not need to list out every single translatable resource?

**Comment by pamil** [comment]
Hello Peter,

the biggest issue here is having too much translation files (over 2 thousands). The loader I wrote was replicating the current logic for base resources.

We can make the translation loader lazy, so it won't load that huuuge array every time we create translator but only on demand (`kernel.debug` enabled and not empty `cache_dir`).

After that, I can think of the following solution:
 - loading only resources which locales are defined (so if I have a shop that sells only in Poland and UK, I won't load Spanish or Albanian locales)
 - caching the found resources outside the container (Doctrine Cache?) so the compiled container won't include them

**Comment by peteward** [comment]
They sound like good ideas. Only loading resources for defined locales definitely sounds sensible.

**Comment by pamil** [comment]
There were two translator definitions, each one having the list of loaded files, #6338 fixes it.
