### ISSUE TITLE
[RFC] Should we skip 0 value tax adjustments on shipping?

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4452]
Skipping 0 value tax amounts is done for OrderItemUnits, but it is not done for Shipping.

Skipping 0 value in general is an interesting thought, but it reduces Adjustment bloat and in any case you want to display it explicitly you can fallback to 0 in a template so I think it's OK :+1: 

However it should probably be consistent?

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/Taxation/OrderShipmentTaxesByZoneApplicator.php#L76

If agreed we'll PR this since it's trivial to check for 0 here.

Thoughts?

**Comment by pjedrzejewski** [comment]
:+1:

**Comment by Zales0123** [comment]
:+1:

**Comment by peteward** [comment]
OK we'll do a PR for this shortly

**Comment by michalmarcinkowski** [comment]
:+1:
