### ISSUE TITLE
[RFC] Double-rounding on tax

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4454]
Hi,

I know me and @michalmarcinkowski have had some fun conversations about tax rounding in the past :)  but currently I think there's a flaw in the implementation as integer rounding is done twice.

The process of calculation and distribution are split into 2 separate services which are called here:

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/Taxation/OrderItemsTaxesByZoneApplicator.php#L80

By default the [`IntegerDistributor`](https://github.com/Sylius/Sylius/blob/777ed6f4d2d855ee8b2c49d7be8427e4f193352e/src/Sylius/Component/Core/Distributor/IntegerDistributor.php#L33) will take the tax amount and split it across units to ensure the tax for individual units adds up as closely as possible to the original tax amount. However this amount has already been rounded by the [`DefaultCalculator`](https://github.com/Sylius/Sylius/blob/322157b1f02dd1b101c2b13588b876de79b7dbdb/src/Sylius/Component/Taxation/Calculator/DefaultCalculator.php#L31) so it's not actually that accurate.

In our case we are writing a different distributor, because we cannot charge customers different tax amounts for the same item because they may have bought 2 instead of 1 - it's a business rule.

Scenario from @mmckelviereiss on my team:

* An item with an amount with quantity of 1, amount  395 and tax of 20% = 65.83333333333333 tax
* Which gets rounded by the calculator to 65.83 and then applied to 1 unit at 65.83.
* If we quantity of 2 then it's an amount of 790 and tax of 20% = 131.6666666666667
* Which gets rounded by the calculator to 131.67.
* The distributor will then use this rounded 131.67 / 2 = 65.835
* Our business rounding gives us 65.84

If the unrounded value was returned from the calculator:
* 131.6666666666667 / 2 = 65.8333333335
* Our distributor will then round to a consistent 65.83.

So the double-rounding is a problem.

Ideally we don't want to override the entire `OrderItemsTaxesByZoneApplicator`, really we should only have to override the `IntegerDistributor` to override from the unrounded (non-integer) value.

Ideas:
* Inject the distribution into the calculator and pass in the number to split the calculation into (defaulting to 1).
* Add (yet another) service layer here to do it - seems excessive.

Thoughts?

**Comment by michalmarcinkowski** [comment]
@peteward our current logic rounds only once.

> If we quantity of 2 then it's an amount of 790 and tax of 20% = 131.6666666666667
Which gets rounded by the calculator to 131.67. 

That is correct.

> The distributor will then use this rounded 131.67 / 2 = 65.835
Our business rounding gives us 65.84

That is **not** current behavior. Right now the distributor will split this value into 2, so one Unit will receive 65.84 and the second unit will receive 65.83, so the tax total will be equal to the value rounded only once.

We have already discussed that there are two levels on which we can round tax: **OrderItem** level and **OrderItemUnit** level. We decided to provide default implementation for rounding on OrderItem level for now. I didn't have time yet to look at your changes in [taxation](https://github.com/Sylius/Sylius/pull/4406), but it probably adds more flexibility which we need since we would like to support both levels in Core. 

The rough idea is to have a setting in the admin that allows you to choose on which level you want to round taxes. This way we will either use one strategy or another. From technical point we probably need to extract the [tax distribution logic](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/Taxation/OrderItemsTaxesByZoneApplicator.php#L80-L91) to another service and have two distribution strategies. We would be definitely interested in having this in Core, so if you're working on it would be great to share the ideas on Github! :)

**Comment by michalmarcinkowski** [comment]
Single responsibility is the solid rule we try to follow everywhere we can, so I don't think introducing `OrderItemUnitApplicator` service will be overhead (especially having in mind our use cases and the complexity of taxes) :)

**Comment by peteward** [comment]
hi @michalmarcinkowski, thanks for replying.

I agree that the code doesn't break the default Sylius implementation of rounding, because the current implementation of the Distributor is taking an integer value and ensuring that exact same amount is fully accounted for across all units.

I remember our discussion about this and I fully understand why you opted for this approach. It's not the one we are using as you know :smile:, but it wouldn't surprise me if there's a 50/50 split in people wanting the 2 approaches.

What I like about the implementation is the separation of the Distributor should allow you to conveniently override this service to write implement your own approach. Our problem is that by rounding before you distribute, it breaks our approach.

We **need** the distributed tax amount to be consistent across units:

```

/**
 * @author Mark McKelvie <mark.mckelvie@reiss.com>
 */
class TaxIntegerDistributor implements IntegerDistributorInterface
{
    /**
     * {@inheritdoc}
     */
    public function distribute($amount, $numberOfTargets)
    {
        if (!$this->validateNumberOfTargets($numberOfTargets)) {
            throw new \InvalidArgumentException('Number of targets must be an integer, bigger than 0.');
        }
        $amount = (int) round($amount / $numberOfTargets);
        $result = [];
        for ($i = 0; $i < $numberOfTargets; ++$i) {
            $result[] = $amount;
        }
        return $result;
    }
```

In this above implementation we divide and round to get a consistent tax value per unit.

But... the amount coming in has already been rounded so we've lost precision that gives us a consistent result (as per our scenario).

As I said, we want to avoid wholesale overriding here, and considering our use-case is quite strong, it would be a really good start to atleast make it really simple to plug in our approach, even if it's not the default or not built into Sylius as standard for 1.0. 

We just want to ensure flexibility really - the same with the PR relating to an external TaxApplicator in certain circumstances, it's just not quite easy enough to do out of the box yet... but it's close!

I hope that makes sense!

**Comment by peteward** [comment]
ahhhh ok, I see what you mean... 

A whole different applicator which would calculate at the Unit level. Yeah yeah that makes sense.

This could be something we roll into the idea behind the custom Applicators PR.

**Comment by peteward** [comment]
@michalmarcinkowski, just to let you know that we're working on a PR that includes the alternative OrderItemUnit-level tax application strategy in addition to supporting custom/third party strategies.

We'll have something up this week hopefully.

**Comment by michalmarcinkowski** [comment]
Good to hear that! Thanks for the update, I will definitely have a look as soon as you open the PR. Will it be based on #4406?

**Comment by peteward** [comment]
Yes it will be loosely based on that one, but quite a lot needs to change to have a solid architecture.
