### ISSUE TITLE
A coupon can only be used in a single order

### ISSUE THREAD

**Issue by gonzalovilaseca** [Sylius/Sylius#4456]
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | 
| License       | MIT
| Doc PR        |

In this commit https://github.com/Sylius/Sylius/commit/d537d28abed34138484de2410162a97fc4c6b8d6 the `many to many` relationship between orders and coupons was changed to a `one to one`. 
Therefore even if a coupon can be used several times you get an exception when saving the cart.
I guess it should be changed to `many to one`. 
If so I can make a PR for it.

**Comment by pjedrzejewski** [comment]
Argh, that's a nasty bug. PR highly appreciated!
