### ISSUE TITLE
Shipping methods set on channel are ignored in checkout shipping step

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#4458]
Let's say you have three shipping methods: `DHL`, `FedEX` and `UPS Ground`. There is also one zone named `EU` and all shipping methods are used for that zone. We also have a channel, let's call it `DEFAULT`, that has only one shipping method: `DHL`. With this setup I will explain the issue with current shipping step in checkout.

Right now, when I would order a product and fill in the country `Netherlands` (which is a `EU` zone member) all the shipping methods will show up. This is not expected, I would expect that only the `DHL` shipping method would be available, since that is the only one active for the `DEFAULT` channel.

I have read through the code and I see that in the `Sylius\Bundle\CoreBundle\Form\Type\Checkout\ShipmentType` there is a `channel` option, but it is not used properly, it doesn't do anything meaningful. 

Would it be a good idea to merge the `criteria` option passed in to the `ShipmentType` with `['channel' => $channel]`? So that you can handle that in a repository and perform the necessary joins to only show the shipping methods for that zone and channel.

A small code snippet example:
```php
// Sylius\Bundle\CoreBundle\Form\Type\Checkout\ShipmentType
// ... 
$builder
    ->addEventListener(FormEvents::PRE_SET_DATA, function(FormEvent $event) use ($notBlank, $criteria, $channel) {
        $form = $event->getForm();
        $shipment = $event->getData();

        // this code is added to merge the criteria with the passed in channel
        if (null !== $channel) {
            $criteria = array_replace($criteria, [
                'channel' => $channel,
            ]);
        }

        $form->add('method', 'sylius_shipping_method_choice', [
            'label' => 'sylius.form.checkout.shipping_method',
            'subject' => $shipment,
            'criteria' => $criteria,
            'expanded' => true,
            'constraints' => [
                $notBlank,
            ],
        ]);
    });
```

**Comment by michalmarcinkowski** [comment]
Fixed on master.
