### ISSUE TITLE
Remove softdelete filters toggling in the repositories

### ISSUE THREAD

**Issue by michalmarcinkowski** [Sylius/Sylius#4461]
We have almost finished removing softdelete from all entities, but the filters are still being disabled in the repositories (e.g. [here](https://github.com/michalmarcinkowski/Sylius/blob/4cb6495742ac4b05bea3d312a374d19203232747/src/Sylius/Bundle/CoreBundle/Doctrine/ORM/PaymentRepository.php#L28-L28)). Disabling this filter doesn't make sense anymore since the entities are not softdeleteable, so we should remove that from repositories.

**Comment by pjedrzejewski** [comment]
As soon as last soft-delete is removed we should disable this filter in general and we will get exception whenever it is disabled/enabled.

**Comment by michalmarcinkowski** [comment]
Sounds like a plan :)

**Comment by michalmarcinkowski** [comment]
Fixed in #4767.
