### ISSUE TITLE
ShippingMethod in shipping action

### ISSUE THREAD

**Issue by BlackIceWizard** [Sylius/Sylius#4468]
Hi!

I have exactly the same error as this guy:
[stackoverflow.com](http://stackoverflow.com/questions/35741576/sylius-empty-string-insted-of-shippingmethod-in-shipping-action)

> In http://localhost:8000/checkout/shipping I got an error
> 
> CRITICAL - Uncaught PHP Exception Symfony\Component\Form\Exception\UnexpectedTypeException: "Expected argument of type "Sylius\Component\Core\Model\ShippingMethod", "string" given" at /home/krzysztof/Dokumenty/praca/smartbyte/sylius/src/Sylius/Bundle/ResourceBundle/Form/DataTransformer/ObjectToIdentifierTransformer.php line 58
> and the $value of transform method is an empty string.
> 
> It's strange because I got this error only on my project version, and on contribute version everything is ok, despite the version of sylius is in both the same (latest commit). Moreover I don't overwrite ShippingMethod so I don't now why this strange behaviour happens.

To get this error only need to get on the selection the shipping method page when ordering the product.

**Comment by BlackIceWizard** [comment]
After half a day with the debugger I found no critical changes in the last Sylius commits. I drew attention to the version of Symfony. She's: 2.8.3. I rolled up to 2.8.0 and the problem has been resolved.I did not understand what was the cause of the error. But the fact remains - in the selectшщт the delivery method form of Symfony v2.8.3 is not working.

**Comment by peteward** [comment]
hi @BlackIceWizard,

We are on 2.8.3 and had the same problem but it was in our application code, not Sylius.

We found that specifying a 'data_class' as a form option incorrectly now blows up forms when you bind data dynamically to any extensions of the `ChoiceType` form. However, I've just had a look at Sylius and I can't see the same issue that we had.

In case it helps, it was this PR that broke things for us - the changes to ChoiceType specifically:

https://github.com/symfony/symfony/pull/17760/files

**Comment by steffenbrem** [comment]
The bug is in symfony `2.7.10` and in `2.8.3` (and some others in the 2.3 and 3.0 branch). Using `2.7.9` and `2.8.2` will resolve this bug for now.

**Comment by aramalipoor** [comment]
Possibly fixed by #4372
