### ISSUE TITLE
[Metadata] Update form is broken

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4472]
Update won't overwrite the values, it doesn't seem to save them.

I've tried digging into the ResourceController and after submitting the form the Metadata object doesn't have the updated values, so something about the form?

Sorry, I don't have more time to look at this now.

**Comment by peteward** [comment]
@pamil @pjedrzejewski this is the one blocker for me

**Comment by pamil** [comment]
Hi @peteward, I don't have too much time right now to work it out, but it may be connected with the metadata serialization in metadata container. `Sylius\Bundle\MetadataBundle\Model\MetadataContainer` has a hack that allows to serialize the inner metadata, if the data is set correctly to `Sylius\Bundle\MetadataBundle\Model\MetadataContainer::$metadataAsObject` but is not persisted, there's an issue. If that data is not updated at all, then something must've gone wrong with the form.

Anyway, the update should be partially covered by "Setting Twitter metadata as empty removes it" scenario at `features/legacy/backend/metadata/metadata_customization.feature`, does it pass for you?

**Comment by pamil** [comment]
Will be fixed by #4670.
