### ISSUE TITLE
[UiBundle][UserBundle] Duplicate Security controller

### ISSUE THREAD

**Issue by gperdomor** [Sylius/Sylius#4477]
Why we have one <code>SecurityController</code> inside <code>UiBundle</code> and another in <code>UserBundle</code>. We need remove one of them

**Comment by michalmarcinkowski** [comment]
It is temporary and we definitely need to remove one of them, but first we should decide which one :)

**Comment by gperdomor** [comment]
my vote is for delete the controller inside <code>UiBundle</code>

2016-03-14 3:54 GMT-04:30 Michał Marcinkowski <notifications@github.com>:

**Comment by pjedrzejewski** [comment]
My idea was to remove the one from UserBundle, because the one in SyliusUiBundle is more generic.

**Comment by gperdomor** [comment]
@pjedrzejewski from my point of view, both controllers do the same, the controller in UserBundle extends the Controller class and the other not, but if you delete the first one, when use the UserBundle standalone, we need implement the security controller again. So, why not update the UserBundle controller with the canges introduced in the UiBundle and delete the UiBundle controller?, soud more logic to me :D
