### ISSUE TITLE
[Metadata] Deleting is broken

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4478]
Deleting through the ResourceController calls:

```
    /**
     * {@inheritdoc}
     */
    public function remove(ResourceInterface $resource)
    {
        if (null !== $this->find($resource->getId())) {
            $this->_em->remove($resource);
            $this->_em->flush();
        }
    }
```

`find()` on the default Resource EntityRepository is:

```
    /**
     * @param mixed $id
     *
     * @return null|object
     */
    public function find($id)
    {
        return $this
            ->getQueryBuilder()
            ->andWhere($this->getAlias().'.id = '.intval($id))
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
```

but the `id` for Metadata is a string, in my case 'Product' so it's wrongly casting a string to an integer and when you have more than 1 metadata you get a `NonUniqueResultException`.

The obvious solution would be to create `MetadataContainerRepository` and override this method to not cast. I just wanted to be sure that this is the correct solution as there's a comment in the code here that suggests something was expected to change [here](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Metadata/Provider/MetadataProvider.php#L66) but I don't think this refactoring happened as expected.

**Comment by peteward** [comment]
@pamil @pjedrzejewski  I think this one may be fixed now because this find method was removed? I can check and confirm this after we updated to 0.18-dev

**Comment by pamil** [comment]
:+1:, 0.18 should have it already fixed
