### ISSUE TITLE
[Metadata] Failed twig rendering blows up the subject page

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4479]
It took me a while to work out how to use the dynamic Twig rendering of metadata strings, i was very excited to see this working :smile: !

However I only got there after various failed attempts. You need to use `{{ subject.VAR }}` e.g.:

**DESCRIPTION:**

```
Reiss {{ subject.gender.name }} {{ subject.name }} {{ subject.archetype.name }} in {{ subject.colour.name }} new in for {{ subject.season.name }}
```

This works great, but if you mis-type something (which is very easy while using a basic typing interface and building up long strings) then your frontend subject page will throw an exception that does not get caught.

In the (much) longer term there will hopefully be a UI that prevents you getting it wrong, but even then I think we need to handle this more gracefully.

Ideally I think the following should be considered:
- Fallback to the next provider in the hierarchy (although this doesn't actually look that easy from a glance...) It would probably mean that ALL pieces of metadata would have to fallback for that render target (e.g. if the 'title' was broken for Page metadata you would have to fallback for every metadata component on the Page - title, keywords, description, etc.), I don't think you could easily fallback on a single property.
- Log any failures somehow so we can know that your desired rendering failed on a page?
- Perform a preview of rendering when you save it. This is very easy when it's a direct subject like a specific product, less so if it's something more generic like the catch-all default for products. Maybe it would pick one at 'random' to choose as an example for rendering?

**Comment by pamil** [comment]
We no longer have Metadata component & bundle in `Sylius/Sylius`.
