### ISSUE TITLE
[Metadata] No translation support

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4481]
My initial thought was that this would be very challenging but it's probably not _that_ bad.

I'm not sure whether this would follow the generic pattern (I haven't caught up with the recent refactoring of Translations) or just use a composite key of `id` & `locale`.

The UI would probably need the most work, but could be considered as part of other rework.

I think this is extremely important, there's not much point in a wonderful SEO Metadata feature if you can't translate it, it would be unusable to anyone with a multi-language store.

**Comment by pamil** [comment]
We no longer have Metadata component & bundle in `Sylius/Sylius`.
