### ISSUE TITLE
[Metadata] Using DefaultPage sitewide 

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4482]
There are 2 intertwined issues here:
- You can't just render the page defaults without having an object implementing the MetadataSubjectInterface to pass (so you can't use your page defaults on any page).
- SEO Metadata settings should be removed once you can as they are confusing and duplication.

On the product page currently it is using this quite ugly looking call:

```
{% block head %}
    {{ sylius_metadata_render(product, null, { 'defaults': {
        'title': settings.title|default('sylius.meta.frontend_title'|trans),
        'description': settings.meta_description|default('sylius.meta.frontend_description'|trans),
        'keywords': settings.meta_description|default('sylius.meta.frontend_keywords'|trans)
    } })|raw }}
{% endblock %}
```

The `defaults` are being passed in through the template which shouldn't be necessary.
- We should remove these settings entirely from Sylius and rely on the DefaultPage SEO Container settings.
- This special root SEO settings should not be deletable, to prevent you destroying SEO for your site. They should also probably be defaulted on install via Fixtures.
- Any rendering object could then call the page as follows because defaults will always be used as a final fallback:

```
{% block head %}
    {{ sylius_metadata_render(product) }}
{% endblock %}
```
- The default call for the parent theme layout should then be as follows so that if a subject is not passed, it just uses the `DefaultPage`:

```
{% block head %}
    {{ sylius_metadata_render() }}
{% endblock %}
```

We could also consider renaming this twig function for more clarity to something like `sylius_page_metadata_render` because I can see many more uses of rendering like ALT tags for images and clearly distinguishing from these would be sensible.

Based on #4481 this would also mean that SEO Metadata will be translatable sitewide and you don't have to worry about trying to accommodate this through settings.

**Comment by pamil** [comment]
We no longer have Metadata component & bundle in `Sylius/Sylius`.
