### ISSUE TITLE
[Metadata] No UI for building Archetype Metadata

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4484]
As shown by #4483, the code is there for this really powerful feature, but there's no UI for actually building Product Archetype Metadata content.

I tested it by URL `app_dev.php/administration/metadata/Archetype-3` and it worked fine. So it probably just needs links adding to the admin UI for Archetype.

EASY PICK!

**Comment by pamil** [comment]
We no longer have Metadata component & bundle in `Sylius/Sylius`.
