### ISSUE TITLE
[Metadata] No support for Taxons

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4485]
Generally, the most important pages in SEO terms for any ecommerce store are Home page, Category pages and Product Pages.

We definitely need Category/Taxon support for Metadata. 

Adding Page-level metadata should be quite simple. The hierarchy in this case would be to iterate up the Taxon tree to find a parent with metadata. 

It would then just be a case of adding UI support for editing/viewing them.

**Comment by pamil** [comment]
We no longer have Metadata component & bundle in `Sylius/Sylius`.
