### ISSUE TITLE
[Metadata] Admin UI and workflow

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4486]
Currently the Admin UI doesn't do the power of this feature justice.

It feels disjointed, is missing in some areas (Archetypes) and doesn't have the best workflow. 

You can't view product product metadata information from the product admin section currently, you can only edit it (permissions could be an issue here if you don't have permissions to edit but can't see the detail). 
Once you have edited through this route you are taken to the View Metadata page but can't get back to the Product page you came from - so have lost your flow. You are in the Metadata section but there's no way to create new metadata here, only edit.

In our use-case we will have an SEO specialist who will want to work on SEO as a whole topic. They need to have the tools easily accessible in one place with consistent flow. While smaller operations may not have someone dedicated to do this, they are still quite likely to approach SEO metadata management as a 'bulk operation', going through the site and populating the data when required, so the same should apply to most users.

I don't want to do dive in and make many changes to the UI considering the amount of work that's going on rebuilding the admin UI, but here are some suggested changes:
- Make SEO data visible on the admin screens where possible without requiring an edit:
  - This could affect Product, Taxon and Archetype listing pages.
  - Space is at a premium here so it could be done with an ontouch/onhover icon overlay on the listing pages? The icon would only display if an entity has it's own overriding metadata, otherwise left blank.
  - This would work for pages like Archetype which doesn't actually have a 'Show' page, only a list view.
  - It should also be added as a tab or section to the Show Product page.
- After editing metadata provide a useful way of returning to your flow. Currently it goes to a View Metadata page, showing what you've just edited. 
  - We could forward the referer so that after the View page you can get back to exactly what you were looking at (this would be ideal if you are editing metadata for products in bulk and still want the assurance of seeing what you just edited).
  - Or provide suitable links back to what you're editing. If you edited a specific product metadata the links could be back to viewing that specific product and a separate link going back to listing all products.
  - Or just return back to the referer instead of View page (probably the easiest to start with).
- Improve the SEO Metadata index page so it feels more useful. You land on it and all you've got is a button to `Customize Default Metadata`, it feels like an unfinished feature:
  - Add a button / link configure default Product Metadata to the SEO metadata index page.
  - Add some information or links to setting up the SEO for taxons, archetypes and products on the SEO Metadata index page.
- Consider rewording the language used on actions. `Metadata` is a very generic word (perhaps more so for developers). The buttons of `Customize X Metadata` are very long. Also I'm not sure why it's `Customize` instead of the standard `Edit`. Is this to try and differentiate that it's a hierarchy so will have _some_ content, you can just `customize` what it's going to be?  I would opt for something like  `Edit SEO`, `Edit SEO Metadata` or `SEO Metadata` - clearer and shorter.

**Comment by pamil** [comment]
We no longer have Metadata component & bundle in `Sylius/Sylius`.
