### ISSUE TITLE
[Metadata] Support for ImageMetadata

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4487]
The other important use-case for this feature is adding a consistent interface to add HTML attributes such as alt and title tags to product images whenever they are rendered.

Something like
```
    <img src="X.jpg" {{ sylius_metadata_render(product, 'image') }} />
```

As there's no documentation for this feature yet, I'm just glancing at the code. It looks like we would need to add the following:

* Custom Model
* Custom Renderer
* Form type

I'm not sure then if it needs a separate Twig extension function to specifically call for the ImageMetadata type or not?

Finally caching is definitely going to be an issue with this - if you're displaying 200 products on a page it's going to be working very hard...

Any pointers here would be great.

**Comment by peteward** [comment]
@pamil @pjedrzejewski - would be good to get just a short comment here about how to get started and we can look at adding it. 

Thanks!

**Comment by peteward** [comment]
Hi @pamil, I'm going to start looking at some improvements I can contribute to the Metadata system this week, can you write me a few tips here to get me started? 

Then I will start looking at the other issues that I've opened.

Thanks.

**Comment by peteward** [comment]
Hi @pamil,

I've had a look at how this works in more detail.

My use-case is that I want to use Metadata for the following:
* Product img alt attributes
* Product title element attributes (tooltips or just for good SEO) on a range of HTML elements
* Product urls

It seems that the current Core implementation stores the `PageMetadata` in the `MetadataContainer`.
The information that I want to add is not page-based. It would be wrong to add it there. It also blows up rendering because the renderer renders every property on the object, so it doesn't work anyway.
I need a separate object to store these properties.

I can think of 2 ways of doing it (so far):

### Metdata Wrapper
Creating a parent entity wrapping around `PageMetadata` which acts as a collection for different types of Metadata.

### Metadata Scope
Modify the persisted metadata so that we add a `scope`. `PageMetadata` could have the scope `page`. I could add a scope of `entity` or similar for other attributes managed through an `EntityMetadata` object, or possibly split into individual components.

* A wrapper would mean less upheaval in some places but more complexity in fetching and rendering.
* Splitting by scope would be an advantage when it comes to compiling and processing metadata as the current implementation does the following:
  * pulls out the full hierarchy
  * compiles(merges) all properties in that hierarchy
  * processes them (renders with twig). 
This is quite heavy and applied fully whenever you request even a single property. This isn't too bad for page-level metadata because you're generally rendering everything once for a page. If you're doing it just to get an alt tag it seems like a huge waste of effort (even if caching will be added).
* The downside of using the scope is that it makes the admin forms more complicated, but it's probably a better to push complexity here than introduce any performance penalties in end-use.

I'm not going to worry about caching at this stage, it will come later.

Let me know what you think.

**Comment by peteward** [comment]
I tried the Metadata Wrapper approach because it felt like the simplest to get something working - it was and it worked, but the architecture wasn't right.

It was easy to get the following but you would be forced to accept these universally which doesn't make sense in all cases, so I will try scope instead and work out a solution for forms:

![screen shot 2016-05-24 at 07 51 07](https://cloud.githubusercontent.com/assets/7068515/15494832/704cff42-2184-11e6-822f-5a9656a85be9.png)

**Comment by pamil** [comment]
We no longer have Metadata component & bundle in `Sylius/Sylius`.
