### ISSUE TITLE
Shipment state on order does not work as expected

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#4488]
When you place an order and you mark it's shipment as shipped, then the shipment state on the order is not updated, nor is the `state` on the order, it should be updated to be `shipped`. I am not sure if there is already work in progress to enhance those state transitions. When is an order expected to be `shipped`?

Might this be because the form type `ShipmentType` only sets the `state` property on the `Shipment` but does not invoke the statemachine to apply the new state, hence the `shipmentState` on the order is not updated?

Should we maybe apply the state in a `POST_SUBMIT` form event? What is the best approach for this problem?

**Comment by michalmarcinkowski** [comment]
There is pending discussion about order states [here](https://github.com/Sylius/Sylius/issues/4060). Your input will be valuable.

Everything should be done through state machine and we will work on fixing that everywhere in Sylius soon. If you would like to help we can share our thoughts and decide on the best approach.

**Comment by michalmarcinkowski** [comment]
Fixed already.
