### ISSUE TITLE
Problem with unit testing

### ISSUE THREAD

**Issue by lewbor** [Sylius/Sylius#4490]
When running unit tests on clear Sylius installation (without composer cache), there are error in ThemeBundle in TranslationTest::testTranslations(). In debug mode - order of translation files is strange: first is resourse/translations/messages.en.yml, and then Bundle/TestBundle/Resources/translations/messages.en.yml, and messages from bundle override messages from resourse folder. A possible reason of this behavior is that ThemeBundle does not have a composer.lock, and composer using symfony/finder:2.8, which have a different file iterating order.

**Comment by pamil** [comment]
Should be fixed by now (#4897).

**Comment by pjedrzejewski** [comment]
Please reopen if still an issue, thanks!
