### ISSUE TITLE
Change design of Sylius front end

### ISSUE THREAD

**Issue by napestershine** [Sylius/Sylius#4492]
Hi

I am new to Symfony as well as Sylius. Can anyone guide me how can I change design of Sylius front end. I want to use the Kuteshop template in it?

I want to change the front end UI of the Sylius project.

TIA

**Comment by inssein** [comment]
Currently you would have to override the WebBundle and from there, override the templates that you want to change (layout.html.twig, etc). I understand that this is changing in the coming revisions, so you may want to wait it out a little.

**Comment by napestershine** [comment]
Hi @inssein ,

Thank you so much for a response.
What i understand by your reply is I have to do template overriding as I do in Symfony applications. But I gave it a try and I failed.

What I did is:
I copied my css, js, images etc files in web directory in a separate folder with name template (template/asstes/css/*, template/assets/js/* and so on). Then I created a folder app/resources/SyliusWebBundle/Views/frontend/Homepage and also I created a file app/resources/SyliusWebBundle/Views/frontend/layout.html.twig. I defined the assets and other components but no result.

My template assets was not showing up, also I was not getting any information in it.

Does it help to get some solution to me?

Thanks so much

**Comment by okwinza** [comment]
@napestershine just put up a new bundle(e.g. 'AcmeWebBundle') and copy all of SyliusWebBundle content to this new bundle.

Then, in your new bundle class:
```
    public function getParent()
    {
        return 'SyliusWebBundle ';
    }
```
http://symfony.com/doc/current/cookbook/bundles/inheritance.html

**Comment by napestershine** [comment]
Hi @okwinza ,

Thanks so much for a response.

So I should do like, I copy and paste the SyliusWebBundle's content in src/DemoBundle and then change its content. right?

**Comment by okwinza** [comment]
@napestershine pretty much yeah. Spend some time reading the docs -- it's all explained there.

**Comment by napestershine** [comment]
@okwinza  Thanks so much. :)

**Comment by napestershine** [comment]
Can someone give a perfect solution, I am stuck at it's front end

**Comment by steffenbrem** [comment]
@napestershine You can watch the youtube channel of @axelvnk (symfoniac). He has some great tutorials on how to get started. Here a quick for your specific issue: https://www.youtube.com/watch?v=FbujTxpd3WY

**Comment by michalmarcinkowski** [comment]
Have a look at the [documentation](http://docs.sylius.org/en/latest/customization/template.html). 

Sylius uses Stackoverflow as its official support channel. For future support questions please post at http://stackoverflow.com/questions/tagged/sylius and tag your questions with sylius.
