### ISSUE TITLE
[Behat] How explicit should we be during implementation of new behats?

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#4494]
During work on #4445 I had a problem to implement two of four features: [code uniqueness](https://github.com/lchrusciel/Sylius/blob/managing-locales/features/localization/managing_locales/locale_unique_code_validation.feature) and [empty code](https://github.com/lchrusciel/Sylius/blob/managing-locales/features/localization/managing_locales/locale_validation.feature). I had trouble to implement validation features, because I'm not able to choose different option than listed. Are you ok with leaving them for later or should I remove this features?

**Comment by pjedrzejewski** [comment]
@lchrusciel Closing, as we discussed today that we verify that option cannot be selected in the UI and separate scenario for API, later.
