### ISSUE TITLE
Display name for ProductVariant

### ISSUE THREAD

**Issue by dkarlovi** [Sylius/Sylius#4501]
For [our solution of integrating Sylius with Google Analytics' e-commerce](https://github.com/webburza/sylius-google-ecommerce-bundle), we need to fetch a proper display name for a product variant. Currently, the only way to do this currently is via [`ProductVariant::__toString`](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/Model/ProductVariant.php#L111-L126) which is not ideal, but we still use it.

We also need this functionality while **adding** the product to the cart (as the information which variant is being added is available at event time, not render time), so we need enough information about each variant option to consistently construct the name.

Please consider adding a functionality which would:
- allow for fetching of variant display name
- add enough information when rendering product variant selectors to be able to construct the end variant display name client-side

Thanks.

**Comment by gorkalaucirica** [comment]
`ProductVariant` already has `getName()` method.  I guess this issue is outdated.

**Comment by michalmarcinkowski** [comment]
You're right, thanks Gorka!
