### ISSUE TITLE
[RFC] [DX] Inconsistent method naming for PHPUnit.

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#4506]
Some of our tests have use close to phpspec snake_case convention like [here](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ThemeBundle/Tests/Translation/DependencyInjection/Compiler/TranslatorLoaderProviderPassTest.php) or [here](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Tests/Controller/CustomerApiTest.php), but others use typical phpunit camelCase convention like [here](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Tests/Controller/CountryApiTest.php) or [here](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Tests/Controller/ShippingCategoryApiTest.php). I would prefer to use the first one, but it is not only my call. WDYT? Which tests should be adjusted?

**Comment by pamil** [comment]
:+1: for the same syntax as in PHPSpec and `/*** @test */` annotations.

**Comment by pjedrzejewski** [comment]
snake_case + annotation +1
