### ISSUE TITLE
[Behat] [DX] Rename TableManipulator to TableReader?

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#4511]

**Comment by Arminek** [comment]
TableRowAccessor ?

**Comment by pjedrzejewski** [comment]
@Arminek Are we sure it will only access rows? Perhaps we want to check table header, etc. Separate service just for that would be an overkill imho.

**Comment by pamil** [comment]
`TableAccessor` seems like a most suitable name for me

**Comment by Arminek** [comment]
TableAccessor and TableChecker. Inject table accessor into table checker and voila :P

**Comment by Zales0123** [comment]
For now, I'm for ``TableAccessor`` ;)

**Comment by pamil** [comment]
Can be closed, it was renamed to TableAccessor.
