### ISSUE TITLE
Shows products in Production environment

### ISSUE THREAD

**Issue by napestershine** [Sylius/Sylius#4517]
Hi

I just installed a fresh Sylius application. I deployed to my live server.
It shows no products on local server but shows products on live server.
How can i remove them from live environment?

Also live website is much different than the local one.

Here is url: http://webmoneycafe.com/offer/web/

Also I am attaching images:

![a](https://cloud.githubusercontent.com/assets/8603325/13801032/4f7f01a4-eb54-11e5-8180-069fad5b6b70.JPG)
![b](https://cloud.githubusercontent.com/assets/8603325/13801033/4f8af360-eb54-11e5-9e67-2ed9479a3dfd.JPG)

Thanks

**Comment by inssein** [comment]
@napestershine you most likely loaded the products during the installation. You can delete the database and re-run the installation command, and make sure you say no to loading sample data.

**Comment by Zales0123** [comment]
:+1: also beware of having right permissions on required directories (``web/media``, ``web/bundles``, ``web/assets`` etc.), as I can see images of products are not displayed and it can be a reason ;)

**Comment by napestershine** [comment]
@Zales0123 , I am having windows environment so I don't think there is any permission issue.

**Comment by napestershine** [comment]
@inssein , if that is the problem then it should behave same on local and production. why is it behaving  differently?

**Comment by Zales0123** [comment]
@napestershine ok, if it's about Windows I'll keep silence :smile: 
However, while runnning ``sylius:install`` command, you have one question ``Warning! This will erase your database. Your current environment is dev. Load sample data? (y/N)``. If you answer ``y``, installer loads fixtures configured in *FixturesBundle* into your database, which you must've done on your production server.

**Comment by lchrusciel** [comment]
@napestershine If you are using Windows, I am not sure, if are able to help you. Windows support is still in progress...

**Comment by napestershine** [comment]
Well Thanks so much @Zales0123  and @lchrusciel , I guess this problem can be resolved. I am stuck in another problem. I want to integrate my own html template in Sylius, can you give some guidance about it?

Thanks so much

**Comment by pjedrzejewski** [comment]
Nice! Let's continue in #4492 then.
