### ISSUE TITLE
[ResourceBundle] resource.settings not taken in account

### ISSUE THREAD

**Issue by plusdepseudo** [Sylius/Sylius#4524]
Hi everyone,

After I've updated to v17 it seems that resource.settings (ie: filterable, etc) are not taken in account anymore.

There is a $defaultParameters param in constructor of RequestConfigurationFactory but it is never used. In code below I added an array_merge and everything works as on v16 (filters and sorts)
Did I missed something or is this a bug ?

Best regards
Cyril

```
in sylius\resource-bundle\Controller\RequestConfigurationFactory.php

    public function create(MetadataInterface $metadata, Request $request)
    {
        $parameters = $this->parseApiParameters($request);
        $parameters = array_merge($this->defaultParameters, $parameters);  //<<<<HERE
        $parameters = $this->parametersParser->parseRequestValues($parameters, $request);

        return new $this->configurationClass($metadata, $request, new Parameters($parameters));
    }
```

and config:
```
in sylius\resource-bundle\Resources\config\controller.xml
        <service id="sylius.resource_controller.request_configuration_factory" class="%sylius.resource_controller.request_configuration_factory.class%">
            <argument type="service" id="sylius.resource_controller.parameters_parser" />
            <argument>%sylius.resource_controller.request_configuration.class%</argument>
            <argument>%sylius.resource.settings%</argument>  <<<HERE
        </service>
```

**Comment by lchrusciel** [comment]
@plusdepseudo Are you willing to open a PR with fix?

**Comment by plusdepseudo** [comment]
Ok with pleasure it will be my first one ever ! :)

2016-03-17 9:08 GMT+01:00 Łukasz Chruściel <notifications@github.com>:

**Comment by pjedrzejewski** [comment]
@plusdepseudo Nice! Have a look here - http://docs.sylius.org/en/latest/contributing/code/patches.html, should be helpful. :) Open PR as soon as you have some code, we will try to help. :)
