### ISSUE TITLE
Promotions - Fairly broken in 0.18

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#4544]
Since my upgrade to Sylius 0.18, promotions have broken down quite a bit.

Errors:
 - Migration of promotions has left with a lot of broken rules (a lot of the actions and the rules are now renamed)
 - ~~The taxon rule doesn't work. When you add a taxon rule, the next page has rendering issues due to an error with Taxon::__toString throwing an exception, and furthermore, the TaxonRuleChecker fails because ```$configuration['taxons']->contains``` is not a function.~~
 - The PromotionEligibilityChecker does not differentiate between pre-qualified promotions and checks when in the cart (one should throw flash messages, the other should not).

The first error is reproducible on the demo, and presumable the second is too, but I cannot test because you can no longer edit any promotion with older actions or rules.

**Comment by manact** [comment]
Don't know if I had to report it here but, in 0.18:
- Promotion based on user group report the following validation error "Client group must be numeric"

The select tag is correctly formed.
Label type:
`<option selected="selected" value="customer_group">User Group</option>`
Label groupe_clients:
`<option selected="selected" value="1">Revendeur</option>`

`<span class="help-block form-error"> Cette valeur doit être de type numeric. </span>`

**Comment by manact** [comment]
I don't know if I have to open another issue but:
When trying to validate a promotion based on user group the validation error is "Value must be numeric":

`<span class="help-block form-error"> Cette valeur doit être de type numeric. </span>`
