### ISSUE TITLE
Catchable Fatal Error: Argument 3 passed to Sylius\Bundle\CartBundle\Form\Type\CartItemType::__construct() must be an instance of Symfony\Component\Form\DataMapperInterface, none given,

### ISSUE THREAD

**Issue by ideal-it-solutions** [Sylius/Sylius#4546]
sorry if this question is naive am new to sylius i notice there is a great deal of work going on sylius, i commend your effort, if am to contribute it will be in the documentation. i tried to research on http://docs.sylius.org/en/latest/bundles/SyliusCartBundle but i don't know which is outdated or not and its really frustrating.
I was able to install and configure sylius as stand alone for cart and order along with the dependency bundle.
i could add product to cart item with the 

> sylius_cart_item_add
without any problem. also i added form to my twig

            ` {% set form = sylius_cart_form({'data_class': url}) %} {# You can pass options as an argument
                   . #}

                   <form action="{{ path('sylius_cart_item_add', {'productId': selectedProduct.id}) }}" method="post">
                       {{ form_row(form.quantity)}}
                       {{ form_widget(form._token) }}
                       <input type="submit" value="Add to cart">
                   </form>`

The product was added but the quantity didn't reflect also when it redirect to the cart summary i get error `Catchable Fatal Error: Argument 3 passed to Sylius\Bundle\CartBundle\Form\Type\CartItemType::__construct() must be an instance of Symfony\Component\Form\DataMapperInterface, none given, called in C:\xampp\htdocs\nkw\app\cache\dev\appDevDebugProjectContainer.php on line 4417 and defined `

 my question is 
> how can i use a form to add product to cartitem from my app default controller such that the user can select the quantity of products desired and add to cart ? i have been on this for weeks.

**Comment by TheMadeleine** [comment]
I think we have that issue covered already. If I understand correctly of course. Item quantity is an available feature :)

And actually there is no CartBundle anymore. 

Am I right @michalmarcinkowski, @pjedrzejewski ?

**Comment by michalmarcinkowski** [comment]
@TheMadeleine that is true 😉
