### ISSUE TITLE
[RFC] Storing documenation in Sylius repository

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#4563]
What do you think about moving [Sylius/Sylius-Docs](https://github.com/Sylius/Sylius-Docs) into `/docs/` directory?

**Pros:**
 - easier contributing (one repository instead of two separate ones)
 - much more eyes watching (263 on Sylius compared to 18 on Sylius-Docs)
 - ability to require documentation in some PRs

**Cons:**
 - bigger repository
 - more builds on Travis (we can avoid it by encouraging people to use "[ci skip]" in documentation only commits)

**Comment by gabiudrescu** [comment]
we keep the docs in GIT with the main repo too - so, from our point of view, go for Docs in the same place with code.

**Comment by gperdomor** [comment]
@pamil One <code>/docs/</code> directory in the root of Sylius or separate the docs by bundle? (one <code>/docs/</code> directory inside every bundle?)

**Comment by pamil** [comment]
@gperdomor one global `/docs/`, everything stays the same expect that we will commit changes to `Sylius/Sylius`, not `Sylius/Sylius-Docs`.
