### ISSUE TITLE
[Promotion] Fatal error on promotion with taxon rule display

### ISSUE THREAD

**Issue by Zales0123** [Sylius/Sylius#4570]
If promotion is configured with "Taxon" filter, fatal error is shown on ``show`` action:
![zrzut ekranu 2016-03-21 o 15 25 01](https://cloud.githubusercontent.com/assets/6212718/13921656/43f564c6-ef79-11e5-8da3-6f96b164d2be.png)

**Comment by michalmarcinkowski** [comment]
Already reported in #4544
