### ISSUE TITLE
[Bug][AttributeBundle] Values relationship on attribute model is broken

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#4578]
I will post a code example that I have used to test if this really is a bug in Sylius master.

```php
// this is not working...
$attribute = $this->get('sylius.repository.product_attribute')->find(1);
echo gettype($attribute->getValues()); // Output: NULL (not correct! I expect a PersistentCollection)

// this works fine
$values = $this->get('sylius.repository.product_attribute_value')->findBy([
    'attribute' => 1
]);
echo gettype($values); // Output: array (correct)
```

Right now you cannot use the `getValues` method on an `Attribute` model, doctrine never initialises a proper `PersistentCollection` for it, it is just `NULL`.

**Comment by steffenbrem** [comment]
I think the `values` one-to-many is never initialised inside the `LoadMetadataSubscriber` of the `AttributeBundle` (https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AttributeBundle/EventListener/LoadMetadataSubscriber.php).

I could submit a PR that properly sets the `values` relationship on every attribute subject (inside the `LoadMetadataSubscriber` of course). Would that be a proper fix for this? Give me a yes and I will start working on a fix.

**Comment by steffenbrem** [comment]
Okay, I've made a PR with a proper bug fix for this issue! :+1:

**Comment by pjedrzejewski** [comment]
:+1:
