### ISSUE TITLE
Fos Rest Error on Composer Install [post-install-cmd]

### ISSUE THREAD

**Issue by DanPhyxius** [Sylius/Sylius#4585]
Hi guys,

i'm trying to migrate to Docker Environment but i get an error on post-install-cmd of composer install.
It seems to be relateds to fos_rest:

>  [Symfony\Component\Config\Definition\Exception\ForbiddenOverwriteException]  
>   Configuration path "fos_rest.format_listener.rules" cannot be overwritten. You have to define all options for this path, and any of its sub-paths in one configuration section.  

<img width="1440" alt="schermata 2016-03-22 alle 06 11 09" src="https://cloud.githubusercontent.com/assets/4693301/13942670/42604776-eff5-11e5-8bf6-7d94d022d4f4.png">

I think my Docker machine is good because i can enter through browser and i get the same error:

<img width="1432" alt="schermata 2016-03-22 alle 06 18 33" src="https://cloud.githubusercontent.com/assets/4693301/13942769/0a279d68-eff6-11e5-9911-47be5474e86f.png">

Any idea how could i fix that? :)

Thanks,
Dan

**Comment by michalmarcinkowski** [comment]
No longer an issue with Sylius.
