### ISSUE TITLE
[TaxonomyBundle][BUG] Can't create new taxon.

### ISSUE THREAD

**Issue by liverbool** [Sylius/Sylius#4629]
<img width="1080" alt="screen shot 2559-03-27 at 03 39 28" src="https://cloud.githubusercontent.com/assets/206804/14062332/a9ee33a4-f3cd-11e5-83bf-8809da7086c3.png">

PS. I try to remove `gedmo:slug` config, it's work!
cc/ @aramalipoor

**Comment by Zales0123** [comment]
@liverbool Have you tried it with the most current master? After introducing [Sylius translations type](https://github.com/Sylius/Sylius/pull/4318/) it should not happen anymore ;)

**Comment by liverbool** [comment]
@Zales0123 Fixed!

**Comment by Zales0123** [comment]
Glad to here that :+1:
