### ISSUE TITLE
GridBundle isn't on packagist as stated in documentation

### ISSUE THREAD

**Issue by itinance** [Sylius/Sylius#4630]
The documentation of SyliusGridBundle [relates to](http://docs.sylius.org/en/latest/bundles/SyliusGridBundle/installation.html) packagist for installation:

`$ composer require sylius/grid-bundle:v0.15.0`

Unfortunatly, this bundle isn't part of the 0.17.01-tag and thus not on packagist, nor it exists as separate bundle on github right now.

**Comment by pjedrzejewski** [comment]
I will register it soon, I need to update docs accordingly. :)

**Comment by TheMadeleine** [comment]
https://packagist.org/packages/sylius/grid-bundle

It's arrived on packagist some time ago. :)
Can be closed - @pjedrzejewski, @michalmarcinkowski.
