### ISSUE TITLE
Unknown listener used MongoDBODMTranslatableListener

### ISSUE THREAD

**Issue by ivankaranjac** [Sylius/Sylius#4643]
Unknown class used in service definitions Sylius\Bundle\TranslationBundle\EventListener\MongoDBODMTranslatableListener in:
- https://github.com/Sylius/SyliusTranslationBundle/blob/master/Resources/config/services.xml#L31
- https://github.com/Sylius/SyliusResourceBundle/blob/master/Resources/config/services.xml#L43
- https://github.com/Sylius/SyliusResourceBundle/blob/master/Resources/config/translation.xml#L21

**Comment by michalmarcinkowski** [comment]
Thanks for reporting this @ivankaranjac! :+1:

The class was probably renamed to `Sylius\Bundle\ResourceBundle\EventListener\ODMTranslatableListener` so this should be updated ASAP.

**Comment by pjedrzejewski** [comment]
Sylius as a whole does not support MongoDB, only individual bundles, that's why we have this bug. We should add some tests for MongoDB if we want to support it in SyliusResourceBundle 1.0.

**Comment by bendavies** [comment]
https://github.com/Sylius/Sylius/issues/3955

**Comment by pjedrzejewski** [comment]
Let's keep the discussion in #3955 then.
