### ISSUE TITLE
Order editing problem

### ISSUE THREAD

**Issue by Buri** [Sylius/Sylius#4647]
When editing order, remove order item from order, then add another product to order -> error `The form's view data is expected to be an instance of class Sylius\Bundle\CoreBundle\Model\ProductVariant, but is a(n) integer. You can avoid this error by setting the "data_class" option to null or by adding a view transformer that transforms a(n) integer to an instance of Sylius\Bundle\CoreBundle\Model\ProductVariant`
When first adding, then removing from order, this error does not happen

**Comment by MatthieuG9** [comment]
Hi!

The same error appear in the checkout process : 
1. enter an address
2. click on "continue"
3. right after I click on "back"

**Comment by michalmarcinkowski** [comment]
Should be resolved already.
