### ISSUE TITLE
Allow doctrine/orm > 2.5 for bundles

### ISSUE THREAD

**Issue by dragosprotung** [Sylius/Sylius#4650]
All the bundles disallow `doctrine/orm` > 2.5 (except `ApiBundle` and `ThemeBundle` as `require-dev`)

I looked over **some** of the bundles and there is no particular reason why the limit should exist.
Tests also pass without a problem.

Is there a particular reason that I do not see ? Would it be possible to change the requirements of the bundles while keeping the same requirements in the main composer.json (I can submit a PR) ?

**Comment by pjedrzejewski** [comment]
Please see https://github.com/Sylius/Sylius/issues/3268 and let's continue the discussion there, as this is the only blocker for us. :/
