### ISSUE TITLE
How do you handle order cancellation?

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#4655]
Preconditions:
* product "A" has 3 stock units available

Steps to reproduce:
* add 1 qty of product "A" to cart 
* place an order with offline payment
* observe the product "A" stock count = 2

At this moment, the customer calls customer support and asks for this order to be cancelled because he doesn't want it anymore.

What steps should the customer support operator do in order to achieve the followings:
* order state change from Ready to Cancelled
* product "A" stock count increase from 2 to 3

I tried to cancel the payment or the shipment, change the order state, delete payments, shipment, order... nothing.

Am I missing something here? Is there something we need to develop or am I pushing the wrong buttons?

**Comment by gabiudrescu** [comment]
@tuka217 I have seen #5148 got merged in master, but nothing about stock / inventory management in the modifications there.

I would be grateful if you could let us know if the behavior described above is addressed by your pull request or not.

**Comment by michalmarcinkowski** [comment]
@gabiudrescu right now there is no logic behind order cancellation, we will be reworking the inventory now and this feature will be implemented in next release.

**Comment by gabiudrescu** [comment]
@michalmarcinkowski next release as in ~ 1.0.0beta1 or post 1.0 ? I'm asking so that I know how to prioritize internally some stories linked to this behavior.

**Comment by michalmarcinkowski** [comment]
The order cancellation is already implemented and will be included in 1.0.0-alpha release :)
