### ISSUE TITLE
[RFC][payum] Ability to configure payment credentinals in backend

### ISSUE THREAD

**Issue by makasim** [Sylius/Sylius#469]
Right config is the only way to configure payment credentials. It was asked several times in other projects to allow this from admin panel. For example one account was blocked and an admin want to switch to another.

Thoughts?

**Comment by tristanbes** [comment]
We're considering working on this issue. Can we have a **re-fresh sum up on what's needed and tips on how to structure/architecture the whole thing**.

Also, we need to remind that it's not only about "api credentials" but we also need to consider storing binaries files, and extra stuff (bin files, a merchant id and password and a key file unique per merchant and stuff like that). More on this there: https://github.com/Payum/Payum/issues/499

ping @makasim // @pjedrzejewski

**Comment by makasim** [comment]
@tristanbes do you have an idea how to store binary file to db? I though about storing a path to the binary file which is on the filesystem

**Comment by tristanbes** [comment]
The idea is to store only the configuration of the payment itself on the DB so that means that 
- api credentials
- merchant id 
- hash (text)
- binary file of a key file unique per client, for example, 

name of the file `certif.fr.031281234300099`
content of the file:
```
z9RC5z8xipv29Ps0AtC6fGJf5B632a0SbgZHweg6z9ydp1nfbMREZpLfV5jUPOGUvZ
gBZtxAxfnKS1amfWh8y6Bli8MusSd7bTVjPK89kyGbY6G5rUOuZt1Le7yQ1Nc7f8w5
A2iT1K0LkKRjpUf6sO9VZgwOauQm6Xu1r9ufvyqqxeBrPtiIsQHeRU7BWdrtLA0tOR
KjVbwazCgLMfcVhBQEvmh4ygbih1bD2LChMsVCuC9rVkAYf1kglHMPyQGUqlJTOWp7
CRmbbFXyRrZnDhIcYqZgB9tryWQv47p4LM04YcrakKOmlrCCCsrVk4Y5t5iN1vBSDG
6w8kGZGWPoA2wNKB9pJRqjLjzFw3mQ9Ox9TVHVp8r76trGW77K9He2w4AdYBQyyr4m
EZvsqZ10FI7EMnBTdZDDzJFqeQBRFqpS9b4G0FGHbvJJLM9jZUw5ExtOKrMxmgKi4N
g2kkDsRqe3Z3Rz5HdAtjdYTX2vRQD0cQJXU3J8aQV8QwhogSVydwe86DPM7JAzsenJ
jKnx33U40qXejFVGNd83teINmKfDuJiZb7IaectsoRLTN0qqJGUB0FXNGgffuowLkH
asyscdo3TR7eqxDskf11LjWNqwbF5M9Mb3eHvxaYk8Uco2JfkVL7OglMHnNNKqLnXK
eaNqPv1Lo0OBgVIxwiGNJYeSsWu6atJj6utvHVmXbJlyfxeyiaaFthHpZPRkYtpeRy
coplfPuqZCXZ8fdwVl5cRpj0twSaYRNqtJKDOBbBjowD8IRLNqDcRLFRzHoOEa8KYs
9VfkXL28tMd8lBkV6x6PTYgC1GiqiBepRjAxyMjGqfh04kUf3i2tEr
jGVAhgAgnfqJTKlH2BeqhJKlZw7k4BaIkuoUfFLNlB75AzYk3sBnADXDYKtdsSWhU1
IlVdqJZ1KUh59OyDuuxNZcwu51WGrKC6Qtm6RK6XUtpt0nTHZ3xUVJHuGNWSSobdsv
lOBgXTNnayqfbLvg8CqAFB0TBw0ATL48LF1TK0dU4Nzk5JSC7xK8rfEIRpyjGkvzrm
vqLlWMRgPCNeHcJ2mmWxtTo3LZb9pluAFz2zd3htXQEVy8OL2KsH79ZqcnwpSOqRPm
IpCtzFnlhq5V8QlC1hE7ibCxaqwaw4QWRuawP3BBwmKQrGjHnWwZztO6bJ6R7L3toB
cWRigqS6OyBWIXdHxm28oTZvoCeOVj0IOtqzQXwnMP2wVKYf6JNa5PglD89URPyW48
NLkGeXwFyTkNrqYlDsiAVIYLZYJDABj54RQGVhqxZpCVAWvDSg7fWGg0hZW2mK2EBz
cb3FAlDlO7Wh4Zy2xM79ZVPuavga4pCBKlnQNjwOPbJCi2PDCjt66x1zD
144661C1B3B6B11DDC2665A9686A825C71273D86856CC13FC23AB2A4421B0140A1
14FA9D9875392BE57F80FD4D3050D1D6BC2645E04DB0E3E2A6FBE611CFA4B5E420
9C8150F7F023122qQr1zR6dLlJOiMDbG6OGmKSYrbRLjNxgYF6O0LOphKqjcTtEjC4
qRYApJkYmWXLLANZnBVrpYPSvFAu25aUMaSwcELNUKcpgFq5tsI1wG
144661C1B3B6B11DDC2665A9686A825C71273D86856CC13FC23AB2A4421B0140A1
14FA9D9875392BE57F80FD4D3050D1D6BC2645E04DB0E3E2A6FBE611CFA4B5E420
9C8150F7F023122qQr1zR6dLlJOiMDbG6OGmKSYrbRLjNxgYF6O0LOphKqjcTtEjC4
qRYApJkYmWXLLANZn46w0I65L63PlBVrpYPSvFAu25aUMaSwcELNUKcpgFq5tsI1wG
112BFDB506FB4D66BE33110ABDF412E432855E0EB869332664B43A4734F063A22C
F6B31BE3A61FF4123E2E893648569C78903B982F9422BE4761eFcB1ZxNnOK4rRiC
YhZYW3QiL6OW9eXqQr1zR6dLlJOiMDbG6OGmKSYrbRLjNxgYF6O0LOphKqjcTtEjC4
qRYApJkYmWXLLANZn46w0I65L63PlBVrpYPSvFAu25aUMG
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
SIPSATIS_MICHELDENISO20/04/2009,V4,CYBERPLUS,PROD++++++++++++++++
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++END
```

The binary of the payment backend itself does not change and is made available from the bank. It must be configured at the payum configuration level so I guess this should be stored using the filesystem and not the DB. For example, in our multi-tenant setting, one binary file is shared accross client. Only their configuration changes but not the binary files.

**Comment by GSadee** [comment]
I guess that this feature was introduced in #7237 (by @Zales0123)
