### ISSUE TITLE
[Translation] Configure the way translations relationship is bound

### ISSUE THREAD

**Issue by winzou** [Sylius/Sylius#4691]
Hello again,

I'm using Translation/Resource bundles to manage my translations in the database.
There is this [ORMTranslatableListener](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/EventListener/ORMTranslatableListener.php) that is binding the relationship between the *Translatable and the *Translation entities.

Unfortunately this listener binds the relationship against a hardcoded array in its private method `mapTranslatable`:

```
    $metadata->mapOneToMany([
        'fieldName' => 'translations',
        'targetEntity' => $translationResourceMetadata->getClass('model'),
        'mappedBy' => 'translatable',
        'fetch' => ClassMetadataInfo::FETCH_EXTRA_LAZY,
        'indexBy' => 'locale',
        'cascade' => ['persist', 'merge', 'remove'],
        'orphanRemoval' => true,
    ]);
```

The thing is that I'm currently adding some Doctrine 2nd level cache to my application, and it needs an additional index in the array, something like `'cache' => array('usage' => ClassMetadataInfo::CACHE_USAGE_NONSTRICT_READ_WRITE),`

Currently there is no way for me to add this additional index. Relationships in Doctrine cannot be overridden, and this method is private. I actually need to duplicate the full listener in my app.

There should be a way to alter this hardcoded array around which the relationship is built.

Thanks!

**Comment by pjedrzejewski** [comment]
Definitely, although I am not sure what would be the proper way right now without too much overhead. :/

**Comment by nakashu** [comment]
Shouldn't this be possible with association override ?
http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/inheritance-mapping.html#association-override

http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/tutorials/override-field-association-mappings-in-subclasses.html

**Comment by winzou** [comment]
Nope, it can only override a few things like name of join columns, etc. But it's not possible to add info on the association.

**Comment by nakashu** [comment]
If I am not wrong from what I tried, unrecognized options in the override configuration will be ignored by doctrine.
So to have the configuration in one place, sylius specific options for the relation could be added there, and used dynamically in the listener. 
But still seems a bit dirty just wildly dropping it in there.
