### ISSUE TITLE
No RDFa mapping found

### ISSUE THREAD

**Issue by kurakin-oleksandr** [Sylius/Sylius#4699]
I got error `No RDFa mapping found for "Sylius\Bundle\ContentBundle\Document\StringBlock`
after running command from UPGRADE doc:
 `/console doctrine:phpcr:document:migrate-class "Symfony\Cmf\Bundle\BlockBundle\Doctrine\Phpcr\StringBlock" "Sylius\Bundle\ContentBundle\Document\StringBlock"`

**Comment by michalmarcinkowski** [comment]
What version do you use? Maybe [this](https://github.com/Sylius/Sylius/issues/4073) discussion will help you.

**Comment by kurakin-oleksandr** [comment]
I'm using 0.17 version. As I see Sylius has rdf-mappings only for two types:
`Sylius.Bundle.ContentBundle.Document.SimpleBlock.xml`
`Sylius.Bundle.ContentBundle.Document.StaticContent.xml`

and not for others (in my case for string block)

**Comment by kurakin-oleksandr** [comment]
I've solved my problem by converting all string blocks to simple:
`app/console doctrine:phpcr:document:migrate-class "Sylius\Bundle\ContentBundle\Document\StringBlock" "Sylius\Bundle\ContentBundle\Document\SimpleBlock"`

**Comment by michalmarcinkowski** [comment]
Your solution was not correct, you have converted `StringBlock` to `SimpleBlock`, but actually the proper solution is to simply add the missing RDF mapping (see #4801) :) Thanks for reporting! 👍

**Comment by pjedrzejewski** [comment]
Thanks for reporting Aleksandr!
