### ISSUE TITLE
Application in Docker Environment very slow

### ISSUE THREAD

**Issue by DanPhyxius** [Sylius/Sylius#4700]
Hi guys,

for my team, i'm trying to use the Docker Build available here.
Everything go fine but application in development is real slow and each page load in about 40seconds.

<img width="1440" alt="schermata 2016-04-06 alle 10 12 45" src="https://cloud.githubusercontent.com/assets/4693301/14310101/6ea674da-fbe0-11e5-829a-cddd1d065ad4.png">

With a docker-compose ps, this is actually the container:

<img width="768" alt="schermata 2016-04-06 alle 10 13 40" src="https://cloud.githubusercontent.com/assets/4693301/14310109/7d20a7ce-fbe0-11e5-940f-a1d0067476e3.png">

as you can see, when i start the Data container, it always exit with Status 0.

How explained [here](https://github.com/Sylius/Sylius/tree/master/etc/docker), i tried to use, in PHP container, the setfacl command but always i get:

setfacl: Operation not supported

My machine is a Macbook Retina with 16GB of Ram and CPU 2,5 GHz Intel Core i7. 

What could i do to to fix that and speed up the application?

Thanks a lot guys!

**Comment by amenophis** [comment]
Hi,
Are you using docker-machine with virtualbox driver ?
If yes, you should use https://github.com/adlogix/docker-machine-nfs to improve file share performances !

**Comment by DanPhyxius** [comment]
@amenophis 

You save my day!!! Now page loading is 550ms! 
I come from Italy, but sooner or later i'll buy you a beer! 

Thanks a lot!

We can close the issue!

**Comment by michalmarcinkowski** [comment]
Glad that it worked for you!

PS. You can close your issues yourself :)
