### ISSUE TITLE
[CartBundle] Repository is not mapped (and thus not implementing CartRepositoryInterface)

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#4710]
```sylius.repository.cart``` is a default resource bundle entity repository, and not Sylius\Bundle\CartBundle\Doctrine\ORM\CartRepository

**Comment by pjedrzejewski** [comment]
Thank you Hussein for reporting!

**Comment by inssein** [comment]
This is still not fixed. We set sylius.repository.cart.class, but never reference it.

**Comment by inssein** [comment]
@pamil I thought the fix was to add ```repository: %sylius.repository.cart.class%``` in CoreBundle/Resources/config/app/sylius.yml``` for the sylius_cart declaration, but ```sylius.repository.cart.class``` is not yet defined.
