### ISSUE TITLE
[Zone] No rbac permissions defined for sylius.zone_member.delete

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4715]
Permission denied: Deleting a zone member from the View Zone admin page.

I'm on 0.17 but I can't see any definition for this permission in master either. I'm not sure if the UI is going to change in a way that this is no longer needed.

**Comment by pjedrzejewski** [comment]
I think we have removed delete button some time ago and it is not going to be back, are you sure you have not overridden the template? Please reopen if still an issue. :)

**Comment by peteward** [comment]
How do you remove zone members then?

**Comment by pjedrzejewski** [comment]
In the zone edit screen. This solves a lot of problems, like "at least 1 member" validation checks, etc.

**Comment by peteward** [comment]
ok makes sense, will take a look, thanks.
