### ISSUE TITLE
[Shipping Method] Example real use case(s) of category requirement : none

### ISSUE THREAD

**Issue by oatto** [Sylius/Sylius#4719]
I can't figure it out when to use category requirement match : none (None of units have to match the method category)

```
switch
 ($method->getCategoryRequirement()) {
             case ShippingMethodInterface::CATEGORY_REQUIREMENT_MATCH_NONE:
                 return 0 === $numMatches;
```

**Thank you in advance**

**Comment by lchrusciel** [comment]
Lets say, you have 3 categories: Light, Regular and Heavy(for items heavier than 5kg). And you have a Shipping Method for light items only (lighter then 5 kg). Than, you can choose Heavy as a Category and select none option, so no items can be heavier than 5 kg in a pack.

**Comment by oatto** [comment]
@lchrusciel  Thank you for your answer.

But if I select none option, when the items in the cart are all heavy then this shipping method won't be appeared on the shipping step of checkout right?

**Comment by lchrusciel** [comment]
If you select none option, than if any of items was heavy it wouldn't be possible to choose this method. Heavy maybe is not the best example. Fragile will be better case. You can choose, that some of shipping methods can't be chosen if any of items is from Fragile category.
