### ISSUE TITLE
Method "deleted" does not exist for order

### ISSUE THREAD

**Issue by kurakin-oleksandr** [Sylius/Sylius#4720]
Method "deleted" for object "Sylius\Component\Core\Model\Order" does not exist in
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Resources/views/Backend/Order/history.html.twig#L22

Maybe it relates to #4140

**Comment by lchrusciel** [comment]
It is related to #4235. It is a bug, this if should be removed.
