### ISSUE TITLE
[RFC] Managing services definitions across multiple files

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#4726]
Hello folks!

While I was surfing through Sylius, most of our `DependencyInjection\Sylius*Extension` classes loading multiple files are doing it on the PHP side like:

```php
// SyliusMoneyExtension.php

$loader->load('services.xml');
$loader->load('templating.xml');
$loader->load('twig.xml');
```

or

```php
// SyliusCurrencyExtension.php

$configFiles = [
    'services.xml',
    'templating.xml',
    'twig.xml',
];

foreach ($configFiles as $configFile) {
    $loader->load($configFile);
}
```

They're all files that are always loaded no matter what happens, so I came up with an idea to include additional files in the main one (usually `services.xml`) using imports:

```php
$loader->load('services.xml');
```

```xml
<imports>
    <import resource="templating.xml" />
    <import resource="twig.xml" />
</imports>
```

This approach will apply only to files statically included, the dynamic ones like database driver dependent configuration (#4721) or the ones included only in test environment will still be loaded in extension class.

What do you think? :camel: :dromedary_camel:

**Comment by pamil** [comment]
The last call before alpha release. Should we change our current services organisation?

Proposing the following structure:
 - `Resources/config/services.xml` for all different services that are always loaded
 - `Resources/config/services/*.xml` for grouping services, always imported by the `Resources/config/services.xml`
 - `Resources/config/services/integrations/*.xml` for services definitions loaded dynamically (eg. translations / grid support in ResourceBundle)

The current `Resources/config/driver/*.xml` (like `Resources/config/driver/doctrine/orm.xml`) should be moved to `Resources/config/services/integrations/doctrine/orm.xml` etc.

This way we lower the includes in `*Extension.php` file to:
 - global services file: `Resources/config/services.xml`
 - integrations services: `Resources/config/services/integration/*.xml`


What do you think?

**Comment by pjedrzejewski** [comment]
Sounds very good to me.
