### ISSUE TITLE
[Order] Sylius\Component\Order\Model\Order::removeItem() calculates itemsTotal incorrectly

### ISSUE THREAD

**Issue by sblaut** [Sylius/Sylius#4727]
The removeItem function calls `$item->setOrder(null)`, which will call `removeItem($this)` again, if the item already has an order. This causes the item price to be subtracted twice from the cart total.
```
public function removeItem(OrderItemInterface $item)
    {
        if ($this->hasItem($item)) {
            $item->setOrder(null);
            $this->items->removeElement($item);
            $this->itemsTotal -= $item->getTotal();
            $this->recalculateTotal();
        }
    }
```
https://github.com/Sylius/Order/blob/master/Model/Order.php#L209

```
    public function setOrder(OrderInterface $order = null)
    {
        $currentOrder = $this->getOrder();
        if ($currentOrder === $order) {
            return;
        }
        $this->order = null;
        if (null !== $currentOrder) {
            $currentOrder->removeItem($this);
        }
        if (null === $order) {
            return;
        }
        $this->order = $order;
        if (!$order->hasItem($this)) {
            $order->addItem($this);
        }
    }
```
https://github.com/Sylius/Order/blob/master/Model/OrderItem.php#L116

The tests do pass. I believe this is because in the test cases `null !== $currentOrder` is never true and therefore `removeItem()` is never called twice.

**Comment by michalmarcinkowski** [comment]
Hi @sblaut, the items total will be subtracted only once because there is a check `if ($this->hasItem($item))` and if the item is already removed the total will remain untouched. Am I missing something?

**Comment by sblaut** [comment]
Hi @michalmarcinkowski, In my case `$this->hasItem($item)` is true both times, because the item is removed in line 210, only after `$item->setOrder(null)` is called on line 209.

Here is what happens: I have an order with an item inside that I want to remove, so I call `$order->removeItem($orderItem)` (from a Controller). A breakpoint on line 116 in OrderItem model gets hit, `removeItem` is called twice and the price is reduced twice. The same breakpoint is never hit when running the test suite and the tests pass.

I may be missing something here, but for now I fixed the problem by overwriting the `removeItem` function and swapping around line 209 and 210.

```
    public function removeItem(OrderItemInterface $item)
    {
        if ($this->hasItem($item)) {
            $this->items->removeElement($item);
            $item->setOrder(null);
            $this->itemsTotal -= $item->getTotal();

            $this->recalculateTotal();
        }
    }
```

**Comment by michalmarcinkowski** [comment]
@sblaut you're right, there is a bug! Please open a PR with changing the `removeItem` method to the following:
```php
public function removeItem(OrderItemInterface $item)
    {
        if ($this->hasItem($item)) {
            $this->items->removeElement($item);
            $this->itemsTotal -= $item->getTotal();
            $this->recalculateTotal();
            $item->setOrder(null);
        }
    }
```
