### ISSUE TITLE
Customer email canonical validation case insensitivity

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#4733]
The email unique validation on the `Customer` model is currently checking against the `email` field, but it should check agains the `emailCanonical` field. This causes bugs when using PostgreSQL which does not have a case-insensitive collation. Is this something that should be fixed on the Sylius side? In my opinion I think it does, but I let that decision over to you guys :+1:  

We can't simply validate against the `emailCanonical` field since it is being set on `prePersist`. So I am not sure what a good solution is to handle this case.
```xml
<class name="Sylius\Component\User\Model\Customer">
        <constraint name="Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity">
            <option name="message">sylius.customer.email.unique</option>
            <option name="fields">email</option>
            <option name="groups">sylius</option>
        </constraint>
<!-- ... -->
```

Maybe something like http://symfony.com/doc/current/reference/dic_tags.html#validator-initializer could be used to achieve this:

```xml
<constraint name="Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity">
    <option name="message">sylius.customer.email.unique</option>
    <option name="fields">emailCanonical</option> <!-- This is what you want -->
    <option name="errorPath">email</option>
</constraint>
```

**Comment by pjedrzejewski** [comment]
Yeah, I think we should fix this on Sylius side. Initializer sounds like a good idea!

**Comment by steffenbrem** [comment]
Okay great! I will make a PR for it to fix this :+1:

**Comment by steffenbrem** [comment]
PR is up and ready! :smile:
