### ISSUE TITLE
[Metadata] Discussion

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#4737]
I have been looking at the Metadata bundle and component today, there are a few things I wanted to talk about.

Firstly, I think we should switch from just Twitter Card to [Open Graph](http://ogp.me/) fields, and then supplement that with platform specific fields (facebook app id, twitter card type, twitter site, etc). This is what I am currently doing for static pages, and it makes sense. What do you guys think?

Secondly, there are a few big things still left in Metadata, such as support for Translations (https://github.com/Sylius/Sylius/issues/4481) and https://github.com/Sylius/Sylius/issues/4482.

So far all the issues about Metadata have not received any feedback, but I understand that you guys are busy. I don't mind doing work in this area, it would just be nice to clarify the issues with you guys, and hear any other feedback you may have.

@peteward @pjedrzejewski @pamil

**Comment by peteward** [comment]
Hi @inssein,

Sadly I think it's unlikely that much more work will be done on this for 1.0 so if you are willing to help on some approvements that align with the goals then that would be great! 

I think Twitter Cards were really just an initial example of how something could be implemented - they weren't intended to be the only option and there is definitely scope for more.

I'm hoping to add a couple of small improvements but I'm not sure that I will get a chance to tackle some of the big issues (translations and caching) anytime soon.

For admin improvements I'm waiting until the new Admin has stabilized.

Thanks.

**Comment by pamil** [comment]
The main issue on the implementation side now is the integration with Doctrine. As I've mentioned in #4670:

> Metadata cannot be stored as object ORM type, because objects are
compared (===) by reference, not by value, what means that changes
would not be persisted.

> The only working way I have found is to store metadata as text
type and serialize it on MetadataContainer::setMetadata() method
call. However, after every metadata modification we have to use that
method once again, if not - changes won't be persisted.

The current implementation is quite unfortunate:

```php
$metadataContainer = new MetadataContainer();
$pageMetadata = new PageMetadata();

$pageMetadata->setFoo('Before setMetadata');

$metadataContainer->setMetadata($pageMetadata); // Serializes page metadata at that moment

$pageMetadata->setFoo('After setMetadata');

$metadataContainer->getMetadata()->getFoo(); // Returns 'After setMetadata', looks good

// But under the hood...
// $metadataContainer has serialized metadata with foo set to 'Before setMetadata'
// So if we get that from the database

$metadataContainer = $metadataContainerRepository->find(42);
$metadataContainer->getMetadata()->getFoo(); // Returns 'Before setMetadata', shit happens
```

**Comment by inssein** [comment]
@pamil ah yeah I missed that, remember reading about it. Will hopefully get a chance to take a look at it this week and see if there are other / better ways of storing metadata.

**Comment by pamil** [comment]
Metadata component & bundle were removed.
