### ISSUE TITLE
Can not create new taxon or update existing one

### ISSUE THREAD

**Issue by kurakin-oleksandr** [Sylius/Sylius#4743]
I get error while creating new taxon: "Integrity constraint violation: 1048 Column 'name' cannot be null"
According to log: Sylius tries to save one translation twice but second time without correct data:

`INSERT INTO sylius_taxon_translation (name, slug, permalink, description, locale, translatable_id) VALUES (?, ?, ?, ?, ?, ?)`
`Parameters: { 1: 'My root taxon', 2: my-root-taxon, 3: root, 4: 'My root taxon', 5: ua, 6: 289 }`

`INSERT INTO sylius_taxon_translation (name, slug, permalink, description, locale, translatable_id) VALUES (?, ?, ?, ?, ?, ?)`
`Parameters: { 1: null, 2: '', 3: '', 4: null, 5: ua, 6: 184 }`

I've set only one language ("ua")

I'm using version 0.18-dev

**Comment by kurakin-oleksandr** [comment]
Ok, I found a problem. Some taxons didn't have translations.
Query to find such taxons:
`SELECT * FROM sylius_taxon s LEFT JOIN sylius_taxon_translation st ON s.id=st.translatable_id WHERE st.id IS NULL;`

After adding translations everything works good.
But I still don't understand how missing translation relates to creating new taxon

**Comment by sprik** [comment]
The problem persist in newly version and in new admin, seems that the taxonomy must have all translations, but why that? @pjedrzejewski

**Comment by michalmarcinkowski** [comment]
Should be fixed now.
