### ISSUE TITLE
[Doctrine] can't resolve model class in .orm file

### ISSUE THREAD

**Issue by oatto** [Sylius/Sylius#4745]
From this closed PR : https://github.com/Sylius/Sylius/pull/4693

When I try to override an interface to use my custom interface then the doctrine resolver, which resolves the mapping model class and its interface, can't find the model class of the config interface. For example, if I override user class model also with interface, so doctrine entity mapping(.orm) will not be able to find the mapping class of the original interface which has been overriden with my configuration.

**Comment by liverbool** [comment]
ping @gperdomor @pamil

**Comment by pjedrzejewski** [comment]
We should remove the interfaces from configuration, because you **cannot** change it.

**Comment by pjedrzejewski** [comment]
Unless it is your own resource.
