### ISSUE TITLE
What is the status of the SoftDeleteableFilter?

### ISSUE THREAD

**Issue by coudenysj** [Sylius/Sylius#4761]
I get some errors on the current master branch due to calls to the softdeleteable filter.

What is the status of the usage of this filter? I would like to clean up the codebase to avoid errors, but I'm not sure what components still are allowed to have a `deletedAt` field.

**Comment by michalmarcinkowski** [comment]
Softdelete shold be removed completely already. What needs to be done to get rid of it fully:
* [ ] Remove SoftdeleteInterface
* [ ] Remove SoftdeleteTrait
* [ ] Ensure that all `deletedAt` fields and `set/getDeletedAt` methods are removed from models
* [ ] Ensure that all `deletedAt` references are removed from repositories
* [ ] Remove softdeleteable filter and all its usages in repositories

**Comment by pjedrzejewski** [comment]
@michalmarcinkowski :+1:

**Comment by coudenysj** [comment]
Thanks @michalmarcinkowski, I'll try to fix this and create an MR.

**Comment by michalmarcinkowski** [comment]
That's great! 👍

**Comment by coudenysj** [comment]
One more question: should all the tests testing the "isDeleted" be removed too? (e.g. `it_recognizes_stockable_as_not_available_if_variant_was_deleted`)

**Comment by pjedrzejewski** [comment]
@coudenysj Yep! :)
