### ISSUE TITLE
Payment Gateway provider

### ISSUE THREAD

**Issue by yopop666** [Sylius/Sylius#4773]
Hi,

My curent version of sylius is sylius-standard v0.17.
I want to set parameters for gateways dynamic.

For example, for gateways(existing gateways in version 0.16):
stripe
be2bill
stripe_checkout
paypal_express_checkout

I want to make a provider foreach gateway that take next parameters from database ( based on some criteria ):
```paypal.express_checkout.username
paypal.express_checkout.password
paypal.express_checkout.signature
paypal.express_checkout.sandbox

stripe.publishable_key
stripe.secret_key
stripe.test_mode

be2bill.identifier
be2bill.password
be2bill.sandbox
```
I don't find in docs how to make this change.

Please give me some tips.

**Comment by yopop666** [comment]
In database exist table ```sylius_gateway_config```. For what is this table? What data must contain?

**Comment by makasim** [comment]
Payum allows you to store gateways configs in the database. Unfortunately there is not UI for it in Sylius yet.

Docs: https://github.com/Payum/Payum/blob/master/src/Payum/Core/Resources/docs/configure-gateway-in-backend.md and  the bundle
https://github.com/Payum/PayumBundle/blob/master/Resources/doc/configure-payment-in-backend.md

**Comment by yopop666** [comment]
Thank you @makasim. Can I have a dynamic number of gateways?
I want that every sylius channel to have his credentials, for example:
Channels:
- **channel1**
- **channel2**

Payment gateways
- **Paypal1** with credentials for **channel1**
- **Be2bill1** with credentials for **channel1**
- **Paypal2** with credentials for **channel2**
- **Be2bill2** with credentials for **channel2**

Suppose that I will add **channel3** then credentials for paypal and be2bll will be given.

Can I have this configuration without adding nothing to ```config.yml```?

**Comment by michalmarcinkowski** [comment]
Sylius uses Stackoverflow as its official support channel. For support questions please post at http://stackoverflow.com/questions/tagged/sylius and tag your questions with sylius.
