### ISSUE TITLE
Sylius remove toolbar midgardToolbar

### ISSUE THREAD

**Issue by Billybroksen** [Sylius/Sylius#4779]
I would like to know does anyone of you got an experience with a this midgardToolbar or whatever it is on the top of the sylius e-commerce frontend page, I have a kind of issue because I would like to hide/remove that stuff, and I don't know where exactly to look and what exactly to do, to get that stuff away.

![nav](https://cloud.githubusercontent.com/assets/17853339/14496643/168dea76-0194-11e6-82a7-c68d77a88726.png)

**Comment by michalmarcinkowski** [comment]
Sylius uses Stackoverflow as its official support channel. For support questions please post at http://stackoverflow.com/questions/tagged/sylius and tag your questions with sylius.
