### ISSUE TITLE
[FlowBundle] Skipping a step based on previous step

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#4780]
Currently there are some steps that I am skipping in my checkout flow. Any step in which there is only one choice, should be skipped. There are various ways to do this, but I haven't found a good way for the ShippingStep.

Problem: You don't know if you need to skip the ShippingStep until after the AddressingStep has been completed.

Currently I am handling this inside the ShippingStep::displayAction() and moving forward if there is only one option. This worked well until I realized that I essentially broke the back button. (When you are in PaymentStep and click back, you go back to ShippingStep, which throws you back to PaymentStep).

I have tried various other ways to fix this bug (like rewrite step history), but I am not having any luck.

Currently I can think of two other possible solutions, none that I like:
 - In ShippingStep, if there is only one possible option, and state is STATE_SHIPPING_SELECTED, move further back.

- In AddressingStep, if there is only one shipping method, then set the data and and then  ->setNextStepByName() to the right step. 

What are the other possible solutions?

**Comment by patrick-mcdougle** [comment]
Considering that FlowBundle has been removed from Sylius #6005 , you might want to look at how the new checkout process works in current Sylius.
