### ISSUE TITLE
[Cart] - saving cart will change persist, product variant options - if variant field is present

### ISSUE THREAD

**Issue by nakashu** [Sylius/Sylius#4791]
**usecase:**
- customer should be able to change product variant inside cart summary
- You have t-shirts with selection method "variant match"
- options "color"(blue, red) and "size"(S, XL)
- customer adds product variant to cart with options: `color => blue`, `size => S`
- when you extend the cart summary with with variant field - same as in product detail page.
  change options to `color => red`, `size => XL` and save

**problem**
- the original `ProductVariant` will now have new options, in the process creating a duplicate in the database and keep its original price
- So in a way you can add cheap product to cart, change it to expensive variant and go forward with the order.

**expected behaviour**
- After changing options in the cart and saving, a new matching for `ProductVariant` will occur and replace the reference on the `CartItem object` without touching the `ProductVariant` object
- Also without changing the CartItem ID - eg. removing it and adding again to cart.

It seems that some that there is a referenced OptionsCollection or ProductVariant somewhere in the code and It get updated, instead of just being transformed. in the VariantMatchType.
If anyone got experience with similar use case please share how you solved it.

**code to reproduce**

``` php
// Sylius\Bundle\CoreBundle\Form\Type\CartItemType.php
public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);

        if (isset($options['product']) && $options['product']->hasVariants()) {
            $type = Product::VARIANT_SELECTION_CHOICE === $options['product']->getVariantSelectionMethod() ? 'sylius_product_variant_choice' : 'sylius_product_variant_match';

            $builder->add('variant', $type, [
                'variable' => $options['product'],
            ]);
        }
// ADDED part - for it to be available in Cart summary page.
        $builder->addEventListener(FormEvents::POST_SET_DATA, function(FormEvent $event) use ($options) {

            $builder = $event->getForm();
            if (!$event->getData()->getVariant()) {
                return;
            }

            $product = $event->getData()->getVariant()->getProduct();

            if (isset($product) && $product->hasVariants()) {
                $type = Product::VARIANT_SELECTION_CHOICE === $product->getVariantSelectionMethod() ? 'sylius_product_variant_choice' : 'sylius_product_variant_match';

                $builder->add('variant', $type, [
                    'variable' => $product,
                ]);
            }
        });
    }
```

``` twig
{# WebBundle/Resources/view/Frontend/Cart/_item.html.twig #}
...
... current code 
...
<tr>
    <td colspan="5">{{ form_row(item.variant) }}</td>
</tr>


```

**Comment by nakashu** [comment]
If anyone got any idea / pointers why is the option changed after transformation .. I'll be grateful.

**Comment by nakashu** [comment]
any idea how to sort this out, or why it persists anyone?

**Comment by pjedrzejewski** [comment]
This seems like a bug then. This approach is a bit problematic currently anyway (I want to fix it soon), because you skip all the checks done in the item resolver. So stock is not checked for example, when you change the variant this way. I currently have no clue why would it change options of the original variant... :/

**Comment by nakashu** [comment]
So the proper place/way to handle this would be implement service (CartManager?) that should handle all cart add/remove/update actions on Cart while also using the itemResolver.

Afterwards everywhere change on cart should be done using the service.

I'll try dig deeper on the option update part, but its seems that while using the transformer and propertySetter .. new values on the options Objects are persisted because of existing references

**Comment by MichaelMackus** [comment]
:+1: for a CartManager-esque service like @nakashu says. In my experience, the ItemResolver has always been a pain point in Sylius - although I know its since been removed since Alpha. But it would still be nice to have a service that we can call add/remove/update on without worrying about all the infrastructure-level details.
