### ISSUE TITLE
Sylius e-commerce, remove/replace some stuffs from homepage after login

### ISSUE THREAD

**Issue by Billybroksen** [Sylius/Sylius#4796]
Hello guys, I need some help about editing frontend part on sylius e-commerce home page after user log in.

Acctualy I want to remove/hide this toolbar from my shop so could anyone help me to do this?

![toolbar](https://cloud.githubusercontent.com/assets/17853339/14556134/d9de6be6-02f6-11e6-825d-0755aac49381.png)

**Comment by pjedrzejewski** [comment]
You need to override layout (I assume you do with your custom theme) and skip these lines:

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Resources/views/Frontend/layout.html.twig#L29
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Resources/views/Frontend/layout.html.twig#L149

**Comment by bosnianmostar** [comment]
Thanks a lot mate! It works, but I also have one more issue, and I would like to ask you if you might help me, acctualy I edited css file from assets and it wont apply on my frontend part, even if I am sure that's the file I need to edit. Here are two photos that will explain everything : 

![error_frontend](https://cloud.githubusercontent.com/assets/17853339/14560546/d2fc10a2-0310-11e6-91e6-c9cf0ea2e899.png)

![frontpart](https://cloud.githubusercontent.com/assets/17853339/14560545/d2f8aeee-0310-11e6-80ba-322833bf8317.png)

so maybe there is another file I should look for or something like that? :/

**Comment by michalmarcinkowski** [comment]
Sylius uses Stackoverflow as its official support channel. For support questions please post at http://stackoverflow.com/questions/tagged/sylius and tag your questions with sylius.
