### ISSUE TITLE
Variant class hardcoded in Product

### ISSUE THREAD

**Issue by Richtermeister** [Sylius/Sylius#480]
The CoreBundle Product constructor currently instantiates a concrete Variant. This makes it impossible to use a different Variant implementation without replacing the entire constructor.

I'm not familiar enough with Doctrine to know if the variant should be given to the Product constructor.. this would also create a dependency between the Product and Variant repositories.

Thoughts?

**Comment by pjedrzejewski** [comment]
FINALLY!!! Fixed. :)

**Comment by Richtermeister** [comment]
![AWESOME!!!!](http://i.giphy.com/MOWPkhRAUbR7i.gif)
