### ISSUE TITLE
Sylius e-commerce, hide main menu 

### ISSUE THREAD

**Issue by Billybroksen** [Sylius/Sylius#4806]
Hello guys, I am wondering how to hide main menu from sylius homepage

![sylius-menu](https://cloud.githubusercontent.com/assets/17853339/14562850/60c7258a-031f-11e6-8237-65f69d1d18f7.png)

If anyone could help me I would be very thankful, 

Thanks :)

**Comment by a2xchip** [comment]
@bosnianmostar What do you mean saying "hide"? You can extend SyliusWebBundle and overwrite homepage template deleting menu block if it is the only thing you need.

**Comment by michalmarcinkowski** [comment]
WebBundle has been removed.
