### ISSUE TITLE
[GridBudnle] has hard dependency on Doctrine ORM.

### ISSUE THREAD

**Issue by dantleech** [Sylius/Sylius#4809]
The ORM driver's DI service has a dependency on `doctrine.orm.entity_manager`, and it therefore not possible to use this bundle without the Doctrine ORM (I would like to add support for PHPCR-ODM).

Would it be possible to either only load the Doctrine ORM / DBAL configurations when ORM/DBAL is existing, or add a configuration option which enables drivers?

**Comment by pjedrzejewski** [comment]
Absolutely, good idea!
