### ISSUE TITLE
[ServiceRegistry] Add context to the constructor

### ISSUE THREAD

**Issue by dantleech** [Sylius/Sylius#4814]
Currently if a "service" is not found then the following exception is thrown:

```
Service of type "boolean" does not exist.
```

This would be less confusing as:

```
Grid field type "boolean" does not exist.
```

Would suggest adding a context to the service registry constructor, e.g.

```php
new ServiceRegistry('Grid field', FieldTypeInterface::class);
```

**Comment by brunoroux** [comment]
:+1:

**Comment by pjedrzejewski** [comment]
Sounds good to me!

**Comment by pjedrzejewski** [comment]
Thank you for good idea and implementation! 👍
