### ISSUE TITLE
"Catchable Fatal Error: Method Sylius\Component\Product\Model\OptionValue::__toString() must return a string value

### ISSUE THREAD

**Issue by igorladela** [Sylius/Sylius#4816]
An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Method Sylius\Component\Product\Model\OptionValue::__toString() must return a string value") in SyliusWebBundle:Backend/ProductOption:index.html.twig at line 24.

I installed latest version and tried create first ProductOption.

http://localhost:8000/administration/product-options/?id=1

**Comment by michalmarcinkowski** [comment]
Should be fixed now.
