### ISSUE TITLE
Sylius check for routes

### ISSUE THREAD

**Issue by bosnianmostar** [Sylius/Sylius#4817]
Hello guys, 

I am working with Sylius e-commerce (Symfony 2), and I want to know is it possible to check for example is my route accessed (on my layout.html.twig).

For example if i have 3 kind of routes : 

 ../aboutus
.. /home
.. /contact

and how I could check if my ../home is accessed so I can do some actions for example something like : 

"IF... { } .."

Thanks,

Cheers

**Comment by bosnianmostar** [comment]
Maybe (in a twig template - html.layout.twig)
{{ app.request.get('_route') }}
 
{{ app.request.getUri }}?

**Comment by pjedrzejewski** [comment]
Hi @bosnianmostar, this is not really related to Sylius, but to Symfony in general.

```
{{ app.request.attributes.get('_route') }}
```

This will give you current route name. Cheers!
