### ISSUE TITLE
[Resource] Traits and annotations

### ISSUE THREAD

**Issue by gperdomor** [Sylius/Sylius#4824]
Hi...

Currently we have some traits:
 - TimestampableTrait
 - ToggleableTrait
 - TranslatableTrait

But you can't use them with Annotation mapping... So, I think that we need add a proper traits for that cases.

The other problem is the location of that traits, they should be inside Resource Component or Resource Bundle?
 1. Inside Resource Component: Add doctrine as dependency (for me this is the proper option)
 2. Inside Resource Bundle: Can't be used outside symfony.

WDYT?

**Comment by michalmarcinkowski** [comment]
Done.
