### ISSUE TITLE
ClassNotFoundException in Taxonomy.php line 24: Attempted to load class "AbstractTranslatable" from namespace "Sylius\Component\Translation\Model". Did you forget a "use" statement for another namespace?

### ISSUE THREAD

**Issue by stylssimo** [Sylius/Sylius#4838]
I am using Symfony 2.8. I installed taxonomy bundle as docs.sylius.com says using composer. I am having issue below. Please help me to solve this issue.
ClassNotFoundException in Taxonomy.php line 24:
Attempted to load class "AbstractTranslatable" from namespace "Sylius\Component\Translation\Model".
Did you forget a "use" statement for another namespace?

**Comment by michalmarcinkowski** [comment]
Please use the newest master version of the TaxonomyBundle, modify composer.json to use `"sylius/taxonomy-bundle": "0.18.x"`.

**Comment by stylssimo** [comment]
I get these messages when I try to install using composer:

composer require "sylius/taxonomy-bundle": "0.18.x"
- InvalidArgumentException] Could not find package 0.18.x at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

composer require "sylius/taxonomy-bundle": "dev-master"
- InvalidArgumentException] Could not find package dev-master at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

composer require "sylius/taxonomy-bundle": "0.18.x-dev"
- InvalidArgumentException] Could not find package 0.18.x-dev at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by pjedrzejewski** [comment]
What is your minimum stability setting in composer.json?

**Comment by stylssimo** [comment]
I am sorry. I did not check the minimum stability in my composer.json file. Now I am downloading to test with Symfony 2.8.x version. Thanks for your quick response. @pjedrzejewski

**Comment by stylssimo** [comment]
After installation I added classes to my AppKernel.php. I am getting these errors: I have not changed /added in config.yml file yet.

ServiceNotFoundException in CheckExceptionOnInvalidReferenceBehaviorPass.php line 58:
The service "sylius.factory.taxon" has a dependency on a non-existent service "sylius.translation.locale_provider".

**Comment by michalmarcinkowski** [comment]
[This](https://github.com/Sylius/Sylius/pull/3940) PR is meant to fix this issue :)

**Comment by michalmarcinkowski** [comment]
The `AbstractTranslatable` class is already removed.
