### ISSUE TITLE
The travis setup does not run functional tests with the specified version

### ISSUE THREAD

**Issue by stof** [Sylius/Sylius#484]
All tests going through Apache (when using Selenium) are using the PHP version installed through APT (either 5.3 or 5.4 depending on the version of Ubuntu used on Travis), not the PHP installed by Travis. This means that the tests don't run on the expected version.
The way to fix it is to use php-fpm (available in the travis setup alongside the CLI PHP) instead of installing mod_php.

For our work app, I'm doing a setup with nginx and php-fpm instead of apache+php-fpm

**Comment by antonioperic** [comment]
@pjedrzejewski  closed?

**Comment by pamil** [comment]
@pjedrzejewski @michalmarcinkowski to be closed, right now there are no functional tests, these from #3055 are using correct PHP version

**Comment by stof** [comment]
Indeed, the Travis setup was totally changed since this issue was reported. Closing.
