### ISSUE TITLE
Cancel an order item

### ISSUE THREAD

**Issue by Jojolam44** [Sylius/Sylius#4845]
Hi,

I wonder if there isn't a way to cancel an order item and not the entire order ?
I don't want to soft-delete it but just cancel it (by a state ?!). I want to keep it in the order for display purpose.

Thanks for your help.

**Comment by michalmarcinkowski** [comment]
Hi @Jojolam44, currently there is no way to cancel only one order item and exclude it from total. You would have to implement this logic on your own if you need this.

**Comment by Jojolam44** [comment]
Thanks for your quick answer. I hope it will be implemented in future versions.
I'll implement my own logic but it will not be as effective as you can do :-)
