### ISSUE TITLE
[RFC] Offline payments

### ISSUE THREAD

**Issue by makasim** [Sylius/Sylius#485]
**Clarify**: Offline payments means (for example) someone give you cash and you sell him a product.

I've started working on offline payment extension for payum (I need it on the project I work on). Right now I want to make it as simple as possible.

For sylius I think it could be useful in order creation logic in the backend.

So leave your comments\wishes and so on here.

**Comment by antonioperic** [comment]
@pjedrzejewski this can be closed, we have offline payment method completed
