### ISSUE TITLE
[Promotion] Product Rule

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#4850]
I think we should rename ```ContainsProductRuleChecker``` to ```ContainsProductVariantRuleChecker```. and then introduce another ```ContainsProductRuleChecker``` that actually performs checks on the actual product.

Currently, there is no way to do a "product" level check. For example, if I have a product with 3 variants, it will list 4 of them when using the product rule (3 variants + master). I thought selecting the master would would work, but I just read the code and it wouldn't.

What do you guys think? @Zales0123

**Comment by pjedrzejewski** [comment]
Makes sense to me. Best would be if we have a single product rule, that allows you first select the product and then optionally variant - would allow us for a bit better UX, I think. But right now I'd be ok with 2 separate rules! ;)

**Comment by Zales0123** [comment]
I'm also 👍  with that, ``ContainsProductRuleChecker`` name could be really misleading, as we're checking variant. 2 separate rules are for now the best option ;)

**Comment by inssein** [comment]
@pjedrzejewski @Zales0123 I was just implementing it and realized that there was a lot of code duplication between the two. 

I had another idea that would still work as long as we are still keeping the master variant idea. If the variant is a master variant, you check that the product is the same. Does that work?

**Comment by pjedrzejewski** [comment]
@inssein Master variant will go away very soon. :(

**Comment by michalmarcinkowski** [comment]
`ContainsProductRuleChecker` is already implemented :)
