### ISSUE TITLE
Sylius e-commerce, overriding templates

### ISSUE THREAD

**Issue by Billybroksen** [Sylius/Sylius#4851]
Hello guys, I am wondering which template I should override to edit this part of my app:

![productovereride](https://cloud.githubusercontent.com/assets/17853339/14737323/c951f5b0-087b-11e6-862e-e831869d5796.png)

My paths ( I Think they are ok ): 

![fodlersoverriding](https://cloud.githubusercontent.com/assets/17853339/14737390/22a52268-087c-11e6-8060-7740f36d3e61.png)

**Comment by michalmarcinkowski** [comment]
Please post such questions on stackoverflow under "sylius" tag, it's the official support channel, maybe someone will be able to help you there.
