### ISSUE TITLE
[DX] Recompiling container on configuration class change

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#4853]
**Steps to reproduce:**
 - Modify `DependencyInjection/Configuration` class in the bundle eg. change the default factory class

**Actual result:**
 - Container isn't recompiled in `dev` enviroment and the application still uses the old factory class

**Expected result:**
 - In `dev` environment container should be automatically rebuilt and the application should use new factory class

It can be technically solved by calling `$containerBuilder->addObjectResource()` or `$containerBuilder->addClassResource()` in the bundle extension.

**Comment by pjedrzejewski** [comment]
This should probably be opened on the Symfony repo.

**Comment by pamil** [comment]
In fact, Symfony does not enforce using `Config` component to configure the container extension, so it's on our side, especially with `ResourceBundle` based on configuration.
