### ISSUE TITLE
Legacy admin - tabbed translations form

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4857]
With the removal of A2lix, we've lost the tabbed layout for form translations which means everything is displayed inline in a long list (not so great with 8 languages). I can understand why no effort was put in here since Sylius will be moving to the new admin, unfortunately some of us will be stuck with the old one:

![image](https://cloud.githubusercontent.com/assets/7068515/14766322/02c456a8-09fd-11e6-8ebb-96e095863cdf.png)

I've copied over and tidied up the A2lix layout for our project, would you be interested in a PR for this?:

![image](https://cloud.githubusercontent.com/assets/7068515/14766325/1acea492-09fd-11e6-8834-44aeaf141820.png)

**Comment by pjedrzejewski** [comment]
@peteward Yes, please - that would be great!
