### ISSUE TITLE
New categorization/taxonomy is not visible

### ISSUE THREAD

**Issue by Billybroksen** [Sylius/Sylius#4868]
Hello guys, 

I have found issue looks like, because after I create my taxonomy in categorization (admin-dashboard)
it's not visible on my store homepage as a new category or smth like that.

If anyone could help me I would be very thankful

**Comment by michalmarcinkowski** [comment]
You have to expose the taxonomy in your channel. Go to the default channel edit page and select newly added taxonomy, that should help.

**Comment by Billybroksen** [comment]
Excelent :) thanks

**Comment by michalmarcinkowski** [comment]
Does it worked for you?

**Comment by Billybroksen** [comment]
Yes

**Comment by michalmarcinkowski** [comment]
Closing then :)
