### ISSUE TITLE
Sylius override default homepage product list

### ISSUE THREAD

**Issue by Billybroksen** [Sylius/Sylius#4871]
Hello guys, I am wondering which template I should override to change some stuffs, I am exploring sylius e-commerce and I am learning a lot about that so I am having some crazy ideas also, and one of them right now is, which product (if it is product template) template I should override to change my homepage products list, for example I would like to experiment with products on my homepage right now, I would like to load taxonomies instead of products ( on products places ).

Thanks guys,
Billy

**Comment by michalmarcinkowski** [comment]
Sylius uses Stackoverflow as its official support channel. For support questions please post these at http://stackoverflow.com/questions/tagged/sylius and tag your questions with sylius.
