### ISSUE TITLE
Overriding templates seems to be broken

### ISSUE THREAD

**Issue by itinance** [Sylius/Sylius#4872]
As demonstrated in [this tutorial](https://www.youtube.com/watch?v=FbujTxpd3WY) on youtube and following the knowledge of bundle-inheritation of Symfony2 i tried to override some templates with no success. 

TL;DR: template overriding is not working right now with 0.17.0 standard edition.

**Steps to reproduce:**

**1. setup sylius standard edition:**

1. composer.phar create-project sylius/sylius -s dev
2. cd sylius-standard
3. app/console sylius:install
4. app/console server:start
5. open 127.0.0.1:8080
(all 5 steps work pretty fine)

**2. override some templates, e.g. layout.html.twig from SyliusWebBundle**

I tried 2 different approaches. 

_First One:_

I. in AppBundle.php, add method "getParent":

```
class AppBundle extends Bundle
{
    /**
     * @return string
     */
    public function getParent()
    {
        return 'SyliusWebBundle';
    }
}

```
II. create a new template file in "src/AppBundle/Resources/views/Frontend/layout.html.twig" with some content.

This template should override the already existing Frontend/layout.html.twig but it will be ignored.

_Approach Two:_

Then i tried another approach alfter i found that under "app/Resources/SyliusWebBundle" the standard edition already is prepared with a SyliusWebBundle-Like directory structure of "Resources/views" containing "Backend" und "Frontend" as empty subdirectories. So i also placed a layout.html.twig file in the directory app/Resources/SyliusWebBundle/Frontend.

In both cases nothing happens and the overrided template will be ignored. Instead the original template is used. For sake of completeness i also tried other template files from SyliusWebBundle without any success. Clearing the cache did not help either.

Nevertheless, i do wonder which approach would be preferred by the sylius maintainers in the future?
And is there any workaround right now being able to use own templates?

**Appendix:**
I attach my directory structure with file contents of both approaches:

![sylius-issue-template-overriding](https://cloud.githubusercontent.com/assets/1758597/14787059/1b5ec44a-0b02-11e6-831f-a3e06cfc9c31.png)

**Comment by pjedrzejewski** [comment]
That is really strange, because both methods should work correctly, we prefer to use ``app/Resources`` and I think that will be the recommended way to override templates + theming, which is still quite experimental... Could you push the repo to GitHub, we will try to reproduce the issue locally?

**Comment by itinance** [comment]
Thx for fast reply! Here it is: [https://github.com/itinance/SyliusIssue4872](https://github.com/itinance/SyliusIssue4872)

**Comment by itinance** [comment]
On further investigation i found the following:

after executing "app/console assets:install" my "overrides" would be recognized, but the result was an exception stating that i have to put the overridden files into "app/Resources/AppBundle...." instead of the "src/AppBundle/Resources/views..."

So i created this directory and could finally override layout.html.twig

**Comment by itinance** [comment]
I updated my demo-repo to a working approach: [https://github.com/itinance/SyliusIssue4872](https://github.com/itinance/SyliusIssue4872)

So at the end I think the [tutorial-video](https://www.youtube.com/watch?v=FbujTxpd3WY) should be just removed from youtube and replaced with a working approach, which means to override the templates in  /app/Resources instead of /src/{BundleName}/Resources.

**Comment by peteward** [comment]
We use overrides in `/src/Reiss/WebBundle/Resources/` where `ReissWebBundle` extends `SyliusWebBundle` and have never had a problem with template inheritance from version 0.9 through to 0.18-dev.
