### ISSUE TITLE
[Resource] Catch foreing key on resource deletion

### ISSUE THREAD

**Issue by gperdomor** [Sylius/Sylius#4874]
Hi...

I found a possible bug when you try to delete a resource from api, if that resource is used by other resource, the <code> $this->repository->remove($resource);</code> method throw an exception and the response is an "Internal server error"... I think we should throw a proper message using: 

<pre><code>
try {
    $this->repository->remove($resource);
    $this->eventDispatcher->dispatchPostEvent(ResourceActions::DELETE, $configuration, $resource);
} catch(ForeignKeyConstraintViolationException $e){
    if (!$configuration->isHtmlRequest()) {
        return $this->viewHandler->handle($configuration, View::create([
            'error' => [
                'code' => $e->getSQLState(),
                'message' => $e->getMessage(),
            ]
        ], 500));
    }
}
</code></pre>

**Comment by michalmarcinkowski** [comment]
Fixed in #4911. @gperdomor thanks for reporting and fixing! :+1:
