### ISSUE TITLE
[Promotions] OrderItems-based promotion adjustments not being removed 

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4877]
If I use **Order Percentage Discount** promotion, the adjustments appear to be applied to the OrderItems, but they are never cleared, so you end up with a repeating discount heading towards a zero total order:

![screen shot 2016-04-26 at 10 47 34](https://cloud.githubusercontent.com/assets/7068515/14814307/a7eca56c-0b9d-11e6-86eb-eeea01f9ba07.png)

If I use **Item Percentage Discount** there's no bug, it removes the adjustments before reapplying them.

What's the difference between these anyway?

**Comment by michalmarcinkowski** [comment]
I suppose the #4768 PR will resolve this. Probably the promotion adjustments are not cleared from Order level, but we will have a look at this.

**Comment by peteward** [comment]
Thanks @michalmarcinkowski, indeed it looks like it should.

**Comment by michalmarcinkowski** [comment]
@peteward should be fixed by https://github.com/Sylius/Sylius/pull/5066, please confirm.

**Comment by michalmarcinkowski** [comment]
Closing, @peteward please reopen if still relevant.

**Comment by michalmarcinkowski** [comment]
No worries, hope there will be no need to reopen :)
