### ISSUE TITLE
Sylius menu overriding 

### ISSUE THREAD

**Issue by Billybroksen** [Sylius/Sylius#4878]
Hello guys, I saw that menu on dashboard and menu on frontend are using same files looks like, because when I change something on my menu (categories/taxonomies) on frontend, changes are applying also on my dashboard menu, and it's making me a problem.

Could anyone give me some ideas or solutions how to avoid that, I want to edit frontend categories / menu only.

Cheers

**Comment by pjedrzejewski** [comment]
Could you describe what do you do exactly? Are you using an event listener? Also, no need to prefix issues with Sylius. :) This is Sylius repository. 😃

**Comment by Billybroksen** [comment]
Okay Pawel, I will keep that in mind :) thanks mate.
Well what I am doing, I am experiment with sylius because of many reasons, for me that's best way to learn some stuffs, and what I want to do for now is to list my categories from the left sidebar on the products places. (on the middle of homepage where ussualy we see products)
And I did it, but now I want to add some style to them and when I apply that changes, same changes are applying on my admin dashboard, how to avoid that, I guess I should override some files etc :) 

I added image where we ussualy list categories/taxonomies: 

![wizard](https://cloud.githubusercontent.com/assets/17853339/14816512/b09d1b92-0bb1-11e6-94d5-94e3d673a9be.png)

Same image applied to dashboard menu 

![dashboard](https://cloud.githubusercontent.com/assets/17853339/14816538/cd18f52a-0bb1-11e6-9aa9-48ab52336259.png)

**Comment by Billybroksen** [comment]
I solved it, I will post answer very soon

**Comment by napestershine** [comment]
@Billybroksen where is answer?
