### ISSUE TITLE
Sylius faceted search

### ISSUE THREAD

**Issue by mcbuckets** [Sylius/Sylius#4888]
i have sylius 0.15 based webshop and search integrated. I'm trying to make a faceted search depending on selected categories(taxons). For example if i have washing machines, dishwashing machines, shavers, irons and stuff like that every one of them has different attributes. How ca i do faceted search based on selected taxons.

So, i would like when i click on washing machines with attributes( rpm, volume etc.) that filters related to washing machines attributes appear but when i click lets say dishwashers i'd like to display filters with attributes related to dishwashers.

I have this by now and it works but not in described way. It displays only brands and price regarding category(taxon).

`
    
    sylius_search:

    search_form_template: 'SyliusSearchBundle::search_form.html.twig'
    engine: elasticsearch
    classes:
       search:
          controller: Acme\Bundle\SearchBundle\Controller\SearchController
          repository: Acme\Bundle\SearchBundle\Doctrine\ORM\SearchIndexRepository

     filters:
        pre_search_filter:
            enabled: true
            taxonomy: KATEGORIJE
        facet_groups:
            search_set:
                values: [categories, brands, memorija, price, operativni_sustav]
            categories_set:
                values: [brands, memorija, price, operativni_sustav]
            all_set:
                values: [categories, brands, memorija, price, operativni_sustav]
        facets:
            categories:
                display_name: 'Kategorija'
                type: terms
                value: ~
            brands:
                display_name: 'Proizvođač'
                type: terms
                value: ~
            price:
                display_name: 'Raspon cijena'
                type: range
                values:
                    - { from: 0, to: 50000}
                    - { from: 50001, to: 200000}
                    - { from: 200001, to: 5000000}
            made_of:
                display_name: 'Material'
                type: terms
                value: ~
            color:
                display_name: 'Available colors'
                type: terms
                value: ~
            operativni_sustav:
                display_name: 'Operativni sustav'
                type: terms
                value: ~
            memorija:
                display_name: 'Memorija'
                type: terms
                value: ~

**Comment by ibasaw** [comment]
+1

**Comment by pjedrzejewski** [comment]
Hi @mcbuckets, this is unfortunately not possible not out of the box, but definitely something we want. I don't know when we will look at this though, sorry. Current search is not very good in terms of DX, so we will be cleaning it up a bit soon, then we can look at more features.

**Comment by mcbuckets** [comment]
Hi @pjedrzejewski , thanks for your reply. Workaround it is :)

**Comment by pamil** [comment]
SearchBundle was removed.
