### ISSUE TITLE
Sylius cart overriding with new custom design

### ISSUE THREAD

**Issue by Billybroksen** [Sylius/Sylius#4890]
Hello guys, I am using sylius and I am trying to learn as much as possible +I am very new to symfony, and I am wondering how could I link (because I edited/overrided template/homepage) my new designed cart with existing sylius card..

here is photo of what I am talking about :

![cartshop](https://cloud.githubusercontent.com/assets/17853339/14851072/bbe4b1e6-0c7d-11e6-9871-14d8bac0c5dd.png)

Thanks a lot, 

cheers!

**Comment by michalmarcinkowski** [comment]
Sylius uses Stackoverflow as its official support channel. For support questions please post at http://stackoverflow.com/questions/tagged/sylius and tag your questions with sylius.
