### ISSUE TITLE
Location of sylius  -  login/logout buttons

### ISSUE THREAD

**Issue by Billybroksen** [Sylius/Sylius#4892]
Hello guys,

Where should I look for sylius login/logout buttons, in a case I want to replace them I mean to move them somewhere else on my homepage ( for example to add their functionality and events to some of my custom buttons somewhere on a homepage)

**Comment by pjedrzejewski** [comment]
These are added right now via KNPMenu, but you can easily generate proper routes in template, wherever you need. :) Check routes in configuration or in menu builder. Please reopen if still an issue. Thanks!
