### ISSUE TITLE
Sylius e-commerce, overriding cart actions

### ISSUE THREAD

**Issue by Billybroksen** [Sylius/Sylius#4899]
Hello guys,

I need some help about overriding actions about my shoping cart, acctualy what I want to do is next (pay attention to selected area) :

![cartbug](https://cloud.githubusercontent.com/assets/17853339/14880168/b23bb9b8-0d2d-11e6-88c0-2b894aa3704b.png)

So I want to do next things on a correct way:  remove text "View cart" and "(0)" <- number of items in my cart

So I want to make it look something like this:

![cart2bug](https://cloud.githubusercontent.com/assets/17853339/14880221/f3067c44-0d2d-11e6-95b0-385969c347ce.png)

Thanks a lot guys,

Cheers

**Comment by Billybroksen** [comment]
anyone? :/

**Comment by pjedrzejewski** [comment]
This is built in MenuBuilder (which is a terrible way to do this), so you need to override it right now. Generally I do not recommend using it and rendering the cart manually with twig. ;)

**Comment by Billybroksen** [comment]
It is this file (image below ) ? could you give me advice which lines I should edit and how to override that action on a proper way, because I want to do it on a proper way and to override it as It should be, well I am doing this just because I am curious, probably I will undo changes :))

Thanks pawel for your reply, I really appreciate that :)

Cheers

**Comment by Billybroksen** [comment]
Mate, how to override this on a proper way, struggling with this whole day and its not going :/

**Comment by michalmarcinkowski** [comment]
The ugly way will be http://docs.sylius.org/en/latest/cookbook/extending-menu.html and `$menu['cart']->setLabel('My label');` if you want to display the cart total you should use the same logic as [here](https://github.com/michalmarcinkowski/Sylius/blob/f10d5c77f04b7f75e0388fe3859720c6b0b380c6/src/Sylius/Bundle/WebBundle/Menu/FrontendMenuBuilder.php#L141-L141)

**Comment by Billybroksen** [comment]
Hmmmm, I just want to hide part  "View cart(0)", and nothing else, i tried few stuffs but it seems its not working :/

**Comment by okwinza** [comment]
@Billybroksen see [here](https://github.com/Sylius/Sylius/blob/f5d1b5f7fe845adfcc2fac485d6e19cd1708e03b/src/Sylius/Bundle/WebBundle/Resources/translations/menu.en.yml#L125)

**Comment by Billybroksen** [comment]
Thanks guys,

That is what I was looking for, exactly like that: 

![results](https://cloud.githubusercontent.com/assets/17853339/14888876/8934ea7e-0d5c-11e6-93de-d5d268cd0281.png)

and is it possible to switch places to amount 0.0 and currency €, to make it look something like this : 

![results](https://cloud.githubusercontent.com/assets/17853339/14888972/01c37f82-0d5d-11e6-8f13-515860a9c526.png) ?

Thanks guys again, 

cheers

**Comment by Billybroksen** [comment]
Thanks okwinza,

 that was what I was looking for, but I am wondering now how to remove this "€" - currency from my homepage, or how to edit that, in case I want to write insted of € just EUROS :)) 

if anyone could help me I would appreciate that!

Thanks a lot guys,

Cheers

**Comment by Billybroksen** [comment]
Noone could help me where and what to override to remove currency icon (€) from cart? :/

**Comment by ibasaw** [comment]
@Billybroksen you can just do your own view and get easily information with the cart varibale in twig

**Comment by michalmarcinkowski** [comment]
Sylius uses Stackoverflow as its official support channel. For future support questions please post at http://stackoverflow.com/questions/tagged/sylius and tag your questions with sylius.
