### ISSUE TITLE
Newsletter support

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#490]
There was a SyliusNewsletterBundle some time ago. I think I might find it somewhere in my forgotten backups.

I think it's pretty basic functionality for an e-commerce app.
I'd say we simply start with giving an ability for user to submit and confirm their e-mail. The bundle had "send out" feature as well as editing the newsletters, but I think it requires reworking.

So, are you guys interested in having this inside the core? :)

**Comment by lchrusciel** [comment]
It would be best to just integrate with some existing solution or implement it as a plugin. Closing

**Comment by stefandoorn** [comment]
https://github.com/bitbag-commerce/mailchimp-plugin
