### ISSUE TITLE
PHP 7 odm issues

### ISSUE THREAD

**Issue by antonioperic** [Sylius/Sylius#4903]
Hi, guys... I am trying to deploy Sylius with PHP7 but I am getting this error

PHP Fatal error:  Cannot use 'String' as class name as it is reserved in /home/kruna7/source/28-04-2016-11-49-25/vendor/doctrine/phpcr-odm/lib/Doctrine/ODM/PHPCR/Mapping/Annotations/String.php on line 32

do you have any idea how to resolve this?

cc @pjedrzejewski @michalmarcinkowski

**Comment by michalmarcinkowski** [comment]
What version do you use? It was resolved long time ago :) Updating `doctrine/phpcr-odm` to v1.3 should help.

**Comment by antonioperic** [comment]
@michalmarcinkowski 

seems it is
from composer.lock

,
        {
            "name": "doctrine/phpcr-odm",
            "version": "1.3.1",
            "source": {
                "type": "git",
                "url": "https://github.com/doctrine/phpcr-odm.git",
                "reference": "094accbb0c5e3394cde29b26ec1db8f7abeb08c0"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/doctrine/phpcr-odm/zipball/094accbb0c5e3394cde29b26ec1db8f7abeb08c0",
                "reference": "094accbb0c5e3394cde29b26ec1db8f7abeb08c0",
                "shasum": ""
            },
            "require": {
                "doctrine/annotations": "^1.2",
                "doctrine/common": "^2.4",
                "doctrine/data-fixtures": "^1.0",
                "doctrine/instantiator": "^1.0.1",
                "php": "^5.3.9|~7.0",
                "phpcr/phpcr": "^2.1.1",
                "phpcr/phpcr-implementation": "^2.1.0",
                "phpcr/phpcr-utils": "^1.2.8",
                "symfony/console": "^2.3|^3.0"
            },
            "conflict": {
                "jackalope/jackalope-doctrine-dbal": "<1.1.5"
            },
            "require-dev": {
                "liip/rmt": "~1.2",
                "symfony/phpunit-bridge": "^2.7|^3.0",
                "symfony/yaml": "^2.3|^3.0"
            },
            "suggest": {
                "jackalope/jackalope-doctrine-dbal": "^1.1.5",
                "jackalope/jackalope-jackrabbit": "^1.0",
                "symfony/yaml": "^2.3|^3.0"
            },
            "bin": [
                "bin/phpcrodm",
                "bin/phpcrodm.php"
            ],
            "type": "library",
            "extra": {
                "branch-alias": {
                    "dev-master": "1.3-dev"
                }
            },
            "autoload": {
                "psr-4": {
                    "Doctrine\\ODM\\PHPCR\\": "lib/Doctrine/ODM/PHPCR"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Lukas Kahwe Smith",
                    "email": "smith@pooteeweet.org"
                },
                {
                    "name": "David Buchmann",
                    "email": "david@liip.ch"
                },
                {
                    "name": "Jordi Boggiano",
                    "email": "j.boggiano@seld.be"
                }
            ],
            "description": "Object-Document-Mapper for PHPCR",
            "homepage": "http://www.doctrine-project.org",
            "keywords": [
                "database",
                "odm",
                "phpcr"
            ],
            "time": "2016-04-06 05:20:39"
        },

**Comment by michalmarcinkowski** [comment]
You have here `require "doctrine/annotations": "^1.2",` check if this library is also at least `1.3`.

**Comment by Jojolam44** [comment]
If you come from an "old" version of Sylius you may have this line in your app/autoload.php :
`AnnotationRegistry::registerFile(__DIR__.'/../vendor/doctrine/phpcr-odm/lib/Doctrine/ODM/PHPCR/Mapping/Annotations/DoctrineAnnotations.php');`
Just comment or remove it.

**Comment by antonioperic** [comment]
@Jojolam44 thnx that helped
