### ISSUE TITLE
Add "special price" to products

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#491]
This has been already implemented in the sandbox IIRC. Not sure why I haven't moved it here, but yeah, having this simpel tool to display products as "promotion" with discounted price would be cool.

Basically, if user enters "specialPrice" (or better name?), we normal price is crossed out and we use the special price.

**Comment by benjamindulau** [comment]
What's the state on this? For a project we need to implement product specific promotions (by channel) in a way that we can:

* Show the discounted price next to a crossed out "normal" price on a product item
* List all products with a specific discount in a dedicated page
* Have a coupon applying to only one specific product in the cart

I'm not sure #1216 addresses this. What would be the right strategy to implement this behavior in the current Sylius version (0.18 atm)? Through the PricingBundle? PromotionBundle?

**Comment by ibasaw** [comment]
for now, how to add special price like 'sales' with 20%, 30 % ?
