### ISSUE TITLE
app_dev.php ultra slow

### ISSUE THREAD

**Issue by ibasaw** [Sylius/Sylius#4912]
hi,
i know that in dev mode this is normal to be slower than in prod env BUT is 2 minutes is normal to display homepage of sylius on app_dev.php ?

i think got something broken in my config, don't got this problem at all with all other my projects.

really frustrating.

any advise ?

sf2.8.4-dev - sylius 0.17-dev

**Comment by peteward** [comment]
The usual culprit for this kind of slow page load would be the following in your config_dev.yml:

```
assetic:
    use_controller: true
```

Change to false and use `asset:dump` / `assetic:watch` on the console instead.

**Comment by ibasaw** [comment]
that's it  thank you @peteward

**Comment by rafaelcavalcanti** [comment]
Just testing and continuing ultra slow.

I5 / 6GB / 1TB
Windows 7 + Xampp (PHP 7.0.13)

I already turn on or trying xdebug, opcache... its don't work with Windows?

![slow](https://cloud.githubusercontent.com/assets/12388/20980513/fc69f68e-bc97-11e6-982d-8085d014be7c.png)

**Comment by gabiudrescu** [comment]
could you try to run it with Blackfire and provide some profile for such a request?

**Comment by rafaelcavalcanti** [comment]
I don't have access to this tool. I give up use Sylius with windows. I installed on a cloud storage, even thinking that the application could be used (for tests) in whatever system operation. Thanks for the support.
