### ISSUE TITLE
Administration of PromotionBundle with more than 20 thousand products killing server

### ISSUE THREAD

**Issue by rapemer** [Sylius/Sylius#4916]
I have 22.503 total products. I have 1249 taxons total.

When I try to create a new promotion (/administration/promotion/create) every product and taxon is loaded and this takes about 100 - 140 seconds!

It will be better to use AJAX calling by Select2.

**Comment by michalmarcinkowski** [comment]
Hi Lukáš,

There is a [PR with autocomplete](https://github.com/Sylius/Sylius/pull/3951) functionality. We will be working on getting this finished and merged soon.

**Comment by krafas** [comment]
@michalmarcinkowski #3951 is merged, but promotion rules still haven't ajax for loading variants, taxons, etc at rules. Is it not done yet?
