### ISSUE TITLE
Consider user friendly image uploading

### ISSUE THREAD

**Issue by asidorov01** [Sylius/Sylius#492]
We could add drag and drop file uploader:
http://html5demos.com/dnd-upload

OR multi-select html5 uploader

http://fineuploader.com/fine-uploader-demo.html

**Comment by aramalipoor** [comment]
I would definitely recommend [Plupload](http://www.plupload.com/) over Dropzone.js since it provides a much better javascript API. I had to migrate to Plupload due to a lack of functionality and consistency in Dropzone's API.

**Comment by pjedrzejewski** [comment]
Moving the discussion to newer issues #1561.
