### ISSUE TITLE
 Cannot load resource "@StAppBundle/Controller/"

### ISSUE THREAD

**Issue by ibasaw** [Sylius/Sylius#4925]
Got a bundle in namespace St, try to use this route config in routing.yml:

```
st_backend:
resource: "@StAppBundle/Controller/"
type:     annotation
```

and got error:

```
  [Symfony\Component\Config\Exception\FileLoaderLoadException]
 Cannot load resource "@StAppBundle/Controller/". Make sure the "StAppBundle" bundle is correctly      registered and loaded in the application kernel class. If the bundle is registered, make sure the bundle path "@StAppBundle/Controller/" is not empty.
```

my controller is fine and i was forced to add it to composer.json

```
    "autoload": {
    "psr-0": { "Sylius\\": "src/", "St\\": "src/", "Argentum\\TranslationBundle": "vendor/" }
}
```

this config work on other sf2 project, in sylius don't want

**Comment by ibasaw** [comment]
with annotaion, it doesn't work, but with routes in yml it works ...

**Comment by diimpp** [comment]
Still actual, just tried in my beta.2 project, some people reported it to be actual on 1.0.

**Comment by lchrusciel** [comment]
The problem seems to be related rather to composer and psr autoload map. `"Sylius\\": "src/", "St\\": "src/"` doesn't feel right. Also, please follow `psr-4` recommendation.

**Comment by diimpp** [comment]
Mentioned 1.0 issue was reported on a fresh sylius-standard installation, my usage was also from AppBundle.

It looks to me, like annotation routing is getting disabled somewhere, rather than some usage error.
