### ISSUE TITLE
Wishlists

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#493]
The title says it all, even most basic wishlist functionality where you can add/remove products would be cool.
1. One wishlist per user (simplest scenario)
2. Multiple wishlists per user (a bit more complex)

I think that we should do it Sylius-way, and it should not be coupled to the Product model. It should support any model / any use case.

**Comment by ychanan** [comment]
Our team is working hard on making a Wishlist Bundle, and we expect to have it ready in a week or two.

**It will be configurable to allow for single or multiple wishlists per user.** In the latter case, each wishlist will have a name and a separate URI for sharing, and the option to make it public or private.

It will of course feature CMS additions and full front-end integration, with "Add to Wishlist" controls on product pages, "Add to Cart" from the wishlist page, a separate section in the  user's dashboard to create/edit their wishlists if the bundle is configured to work with multiple wishlists etc.

We'll keep you posted. :)

**Comment by ivangrgur** [comment]
Hi guys! As @ychanan announced we just published the new wish list bundle! Take a look, we appreciate your comments! :)  https://github.com/webburza/sylius-wishlist-bundle

**Comment by lchrusciel** [comment]
Since @webburza has provided a bundle, this issue can be closed.
