### ISSUE TITLE
Not able to setup new Sylius project

### ISSUE THREAD

**Issue by shairyar** [Sylius/Sylius#4934]
I am trying to setup new project by following the [guidelines](http://docs.sylius.org/en/latest/book/installation.html#bootstrap-a-new-sylius-project) and when I get to the command
`php app/console sylius:install`

I get the following error after about 37% progress

` Allowed memory size of 134217728 bytes exhausted (tried to allocate 91 bytes) `

I searched for this and the issues reported before are linked with production environment and I am just getting started and installing it.

Inside `php.ini` `memory_limit` is `128MB`

What can I do to fix this?

**Comment by nakashu** [comment]
Hi @shairyar the easy fix is increase your memory limit in php.ini to 256MB or maybe event 512MB.

for more see here https://github.com/Sylius/Sylius/issues/4590

**Comment by shairyar** [comment]
I am working on local computer and I did try increasing the memory limit to 256 MB and that gave me another error

`Error: Maximum function nesting level of '100' reached, aborting! `

**Comment by shairyar** [comment]
I increased the memory limit to 512MB
I added the two functions from [#4590](https://github.com/Sylius/Sylius/issues/4590)

Still getting 

`Error: Maximum function nesting level of '100' reached, aborting!`

**Comment by nakashu** [comment]
@shairyar that xdebug thingy

again in your php.ini or xdebug.ini - depend on your server
change `xdebug.max_nesting_level = 100` to some higher value like 200 or 500

or just disable xdebug altogether, as it will make your dev enviroment a bit slow.

http://stackoverflow.com/questions/4293775/increasing-nesting-functions-calls-limit

**Comment by shairyar** [comment]
@nakashu many thanks for the tip, disabling xdebug made it work.

Looking forward to dig in 👍

**Comment by pjedrzejewski** [comment]
Thanks @nakashu, closing this, we should add these to the docs. :)
