### ISSUE TITLE
IS there API for Taxonomies and Taxons?

### ISSUE THREAD

**Issue by DanPhyxius** [Sylius/Sylius#4955]
Hi guys,

refer to [API Documentation](http://docs.sylius.org/en/latest/api/index.html), i'm looking for API to retrieve taxonomies and taxons lists.

Is there something on Sylius core?

Thank you in advance,
Dan

**Comment by next-sentence** [comment]
[reference](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ApiBundle/Resources/config/routing/main.yml#L24)

**Comment by DanPhyxius** [comment]
@next-sentence 
Great! That's what i was looking for! Thank you for reference!
