### ISSUE TITLE
Inconsistency with getting adjustment totals considering neutrality

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4956]
Is there any reason why when requesting the adjustment total of a particular type (e.g. Tax), `OrderItemUnit` will retrieve a total that excludes neutral adjustments, whereas `Order` and `OrderItem` includes them?

This inconsistency is causing a few headaches in our project.

By default the `adjustmentsTotal` on all 3 objects does not consider neutrality, and this makes sense when you want the overall total, but when it's for a particular type then you probably would want to include them?

Our only use-case of neutral adjustments is tax. Our tax adjustments are not always netural. In the US we charge tax in addition to our prices so they are NOT neutral, everywhere else they are. 

When we are asking for these totals we want to know how much tax there was regardless of whether it was neutral or not. As it currently stands, if I ask an `OrderItemUnit` it's tax total, I'll get a misleading response (especially when compared to `Order` and `OrderItem`). For neutral adjustments it's going to return 0 whereas in the US it will return the actual tax value.
### Order

```
    public function getAdjustmentsTotal($type = null)
    {
        if (null === $type) {
            return $this->adjustmentsTotal;
        }

        $total = 0;
        foreach ($this->getAdjustments($type) as $adjustment) {
            $total += $adjustment->getAmount();
        }

        return $total;
    }
```
### OrderItem

```
    public function getAdjustmentsTotal($type = null)
    {
        if (null === $type) {
            return $this->adjustmentsTotal;
        }

        $total = 0;
        foreach ($this->getAdjustments($type) as $adjustment) {
            $total += $adjustment->getAmount();
        }

        return $total;
    }
```
### OrderItemUnit

```
    public function getAdjustmentsTotal($type = null)
    {
        if (null === $type) {
            return $this->adjustmentsTotal;
        }

        $total = 0;
        foreach ($this->getAdjustments($type) as $adjustment) {
            if (!$adjustment->isNeutral()) {
                $total += $adjustment->getAmount();
            }
        }

        return $total;
    }
```

My suggestion would be to remove the neutrality check on `OrderItemUnit::getAdjustmentsTotal()` but 
I'm wondering if there's a reason or use-case for these being different that I hadn't thought of?

**Comment by peteward** [comment]
@michalmarcinkowski any thoughts on this one?

**Comment by michalmarcinkowski** [comment]
@pamil sorry for late answer, for now we can remove the neutrality check on `OrderItemUnit` to make it consistent, but we would need to rethink the concept of tax included in price and find a good solution to all use cases it produces. I will try to find some time to open RFC about current issues and possible solutions in the nearest future.

**Comment by peteward** [comment]
no problem, i removed it from our fork anyway. 

I'll let you know if we come across any problems but everything seems to work well now.
