### ISSUE TITLE
Consider using Symfony CMF Media bundle to handle not only images for products

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#496]

**Comment by aramalipoor** [comment]
@pjedrzejewski What is your progress towards handling media? IMO you can consider using SonataMediaBundle since it has some great features like CDN and file systems, thumbnails using ImagineBundle, different providers, API form type, serialization, etc.

**Comment by aramalipoor** [comment]
@pjedrzejewski I've started to work this (`CmfMediaBundle` integration) for our project and also to add it to Sylius, if I could do it right.

Can you provide me with some suggestions and directions to stop me from wandering around and working on the right stuff? (e.g. How to correctly reference Image documents to ORM entities?!)

I hope I can be of any help :)

**Comment by aramalipoor** [comment]
Ref. #2975
