### ISSUE TITLE
Getting value out of textarea on a show.html.twig form

### ISSUE THREAD

**Issue by Billybroksen** [Sylius/Sylius#4960]
Hello, 

I'm very new to symfony2 and sylius, I am exploring a lot but sometimes I am facing problems like I have today, well my problem is next, I overrided show.html.twig and I placed (added by myself) textarea on a content of a page, and now I would like to ask you guys, how could I get value out of that textarea and to store it to some var or something like that in case I want to do something with that value. It is impossible to write standard php code inside of a twig, smth like: 

<?PHP

$textareacontent= $_POST['textareaname'];
print ($textareacontent);

?>

 because there is not html, head and body tags so I can place my php code inside..

**Here is content of my show.html.twig**

![texta](https://cloud.githubusercontent.com/assets/17853339/15069275/d7aabb18-137c-11e6-9fa9-bf6791770524.png)

thanks mates

**Comment by pjedrzejewski** [comment]
@Billybroksen I'd recommend starting from Symfony basics, before diving into Sylius. Symfony has the best documentation I have ever read - http://symfony.com/doc/current/index.html. Without knowing the fundaments of Sylius (symfony framework) it can be quite difficult to achieve what you want.

**Comment by Billybroksen** [comment]
I am allready reading that book its amazing, but I like to explore a lot and to play with different things. You are right absolutely.

But could you give me some tips what I should do to achieve that so I will dig and explore more and more : )

Thx Pawel

**Comment by michalmarcinkowski** [comment]
Sylius uses Stackoverflow as its official support channel. For support questions please post at http://stackoverflow.com/questions/tagged/sylius and tag your questions with sylius.
