### ISSUE TITLE
Enabling Security

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#4961]
From the demo site:

![screen shot 2016-05-06 at 11 05 57](https://cloud.githubusercontent.com/assets/7068515/15070185/a4df3788-137a-11e6-9d8d-57fd369af6af.png)

Please turn on security! :D

I'm not sure what this is for, any ideas?

**Comment by pamil** [comment]
It looks like it is used only in `Sylius\Bundle\CoreBundle\Authorization\ToggleableAuthorizationChecker`, which is Rbac authorization checker.

**Comment by peteward** [comment]
OK, what surprised me was that it was unticked for me yet RBAC is working. But I think this was because the setting previously wasn't saved in my DB and it defaults to enabled in this case.

Anyway, you might want to rethink about labelling this for the new Admin UI  :)

**Comment by pamil** [comment]
Indeed, it's a weird label :) If Rbac is working with "security" disabled, then `Sylius\Component\Rbac\Authorization\AuthorizationChecker` may be used instead, which doesn't respect that setting (the toggleable one is used only in test environments IIRC).
