### ISSUE TITLE
Product Measures - Manage and add new 

### ISSUE THREAD

**Issue by DanPhyxius** [Sylius/Sylius#4969]
Hi guys!

Actually, about Product Measures, we have:

- length
- height
- depth
- width

actually, for our project, we needs 2 new measures:

- diameter
- thickness

how could we add this measures without lose Sylius compatibility?
Is there some way to add this measures to Sylius core?

Thank you in advance to everyone,
Dan

**Comment by pjedrzejewski** [comment]
Hi Dan,

I'd suggest extending ProductVariant model - http://docs.sylius.org/en/latest/bundles/general/overriding_models.html and adding these as separate fields if you want to use them just like Sylius core measures. Another solution is to use product attributes system. (in admin)
