### ISSUE TITLE
Variant model contains "unmapped" options property

### ISSUE THREAD

**Issue by coudenysj** [Sylius/Sylius#4980]
It looks like the `$options` property in the [Variant model](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Variation/Model/Variant.php#L48) can never contain data, because it is not mapped in the [mapping file](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/VariationBundle/Resources/config/doctrine/model/Variant.orm.xml).

Is it possible that this is a leftover of earlier refactoring?

**Comment by pjedrzejewski** [comment]
It is mapped dynamically: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/VariationBundle/EventListener/LoadMetadataSubscriber.php#L133.

**Comment by pjedrzejewski** [comment]
Closed by accident, sorry! Let me know if something is unclear, please close otherwise. Thanks!

**Comment by coudenysj** [comment]
Thanks @pjedrzejewski, didn't catch that.

Submitted MR #4981 to fix the issue which lead to creating this issue.
