### ISSUE TITLE
Non-existent parameter "currency"

### ISSUE THREAD

**Issue by RobertLangore** [Sylius/Sylius#4984]
After updating I got this error:

  - Updating sylius/sylius dev-master (f52aa48 => 0e9fec4)
    Checking out 0e9fec4bdf18d67664887d9dd95c91614cb22f15

Package league/url is abandoned, you should avoid using it. Use league/uri instead.
Writing lock file
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
  You have requested a non-existent parameter "currency". Did you mean one of
   these: "sylius.currency", "sylius.currency_importer.open_exchange_rates", "sylius.currency_importer.ecb.base_currency"?

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception

  [RuntimeException]
  An error occurred when executing the ""cache:clear --no-warmup"" command:

    [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
    You have requested a non-existent parameter "currency". Did you mean one of these: "sylius.currency", "sylius.currency_importer.open_exchange_rates", "sylius.currency_importer.ecb.base_currency"?

**Comment by michalmarcinkowski** [comment]
You should update your `parameters.yml` file after https://github.com/Sylius/Sylius/pull/4261 changes.

**Comment by RobertLangore** [comment]
1. composer create-project -s dev sylius/sylius-standard s018
2. change sylius "dev-master": "0.17-dev"  to "dev-master": "0.18-dev" && composer update
3. I get the above error
4. change the parameters.yml file with the latest from sylius/sylius && composer update
5. I again got the above error

By the way after step 2, are there other operations to do? For example if after the latest commit in sylius/sylius there are database schema changes: it is enough doing "doctrine:schema:update --force" or should I do "sylius:install"?

**Comment by michalmarcinkowski** [comment]
The #4261 PR was merged today morning and the Sylius-Standard edition hasn't been updated to the newest master yet. Overriding all config files (`app/config`) on Sylius-Standard with Sylius/Sylius `app/config` files should fix the issues.

**Comment by RobertLangore** [comment]
Ok. After overriding all the config files in app/config I get the error:
PHP Fatal error:  Interface 'HWI\Bundle\OAuthBundle\Connect\AccountConnectorInterface' not found in \vendor\sylius\sylius\src\Sylius\Bundle\UserBundle\OAuth\UserProvider.php on line 35

About updating Sylius-Standard: for future updates; shouldn't it be updated as soon as there are bc breaks, to avoid these situations (when working with latest version of sylius)?

**Comment by Niiko** [comment]
hwi/oauth-bundle move from require to dev dependencies.

just add it in your composer.json
```json
       "require-dev": {
            "mikey179/vfsStream": "^1.6",
            "hwi/oauth-bundle": "~0.3"
```

**Comment by pjedrzejewski** [comment]
I will work on a fix for this tomorrow, sorry for the BC break. :/

**Comment by michalmarcinkowski** [comment]
Shouldn't be an issue any more. Please reopen if still relevant.

**Comment by optimum-web** [comment]
Hi guys, 

Same here ,  
                                                                                                                                                                                     
[demo.loc] out:   [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]                                                                                                      
[demo.loc] out:   You have requested a non-existent parameter "currency". Did you mean one of these: "sylius.currency_importer.open_exchange_rates", "sylius.currency_importer.ecb.base_currency"?  
[demo.loc] out:           
installed with command:  composer create-project -s stable sylius/sylius-standard .'

**Comment by RobertLangore** [comment]
Hi,

I had no problems with it: installed today dev and stable version (after your comment).

May it be a problem with the cache of composer? You can try to clear composer cache:  composer clearcache (I cleared composer cache a couple of days ago due to another problem I had).
