### ISSUE TITLE
[Forms] - Disable choice options translations for performance

### ISSUE THREAD

**Issue by nakashu** [Sylius/Sylius#4995]
For all choice options that are already translated and/or doesn't need to be translated the translation domain on form type should be disabled.

```php
public function configureOptions(OptionsResolver $resolver) 
{
    $resolver->setDefaults([
        'choice_translation_domain' => false,
    ])
}
```

In dev environment with around 500 options in a select box the performance increase is around 1 second at times.

reference:
http://symfony.com/blog/new-in-symfony-2-7-form-and-validator-updates#added-choice-translation-domain-domain-to-avoid-translating-options
http://symfony.com/doc/current/reference/forms/types/choice.html#choice-translation-domain

Not complete list of choice types
* taxon
* option
* attribute
* country
* zone members

**Comment by peteward** [comment]
province too, definitely yes 👍

**Comment by pjedrzejewski** [comment]
👍

**Comment by peteward** [comment]
@nakashu, are you going to do a PR for this?

**Comment by nakashu** [comment]
@peteward dont have the time now, probably next week. Your welcome to take upon the task if you have the time.

**Comment by peteward** [comment]
OK I'll try and do it later today

**Comment by pjedrzejewski** [comment]
Thanks for the idea @nakashu and @peteward for the patch!
