### ISSUE TITLE
[Theme] Idea of multiple theme on a single channel

### ISSUE THREAD

**Issue by KannipaB** [Sylius/Sylius#4996]
Hello guys,

For my project I was in need of multiple theme designs for different devices, but in one channel now, can select just one theme. 

For example, if I have channel "Japan" which sell in Japan, I want multiple themes for each devices : mobile, tablet and PC. So users will see the theme depend on their device.
I need some ideas about creating multiple theme/style for different devices with single channel.

So, Any ideas?

**Comment by steffenbrem** [comment]
Good idea! But I think this may already be possible with a little tweaking. You can implement your own `ThemeContextInterface` and enable it. See http://docs.sylius.org/en/latest/bundles/SyliusThemeBundle/your_first_theme.html?highlight=theme_context#custom-theme-context for more information about customising the theme context.

It would be nice of course, too have a mechanism in core that could handle this scenario. But for now it is easily achievable!

**Comment by KannipaB** [comment]
@steffenbrem 
Thank you for your helpful answer! :blush: 
So, I'm front-end developer who does not an expert in programming at all. Could you expand more detail with implementing this.

Pardon me, What is SO on github. :cold_sweat:
Thanks anyway. :blush:

**Comment by pjedrzejewski** [comment]
@KannipaB Steffen meant http://stackoverflow.com/, tag your question with "sylius" and someone will help! :)

**Comment by KannipaB** [comment]
@pjedrzejewski Thank you so much. :joy:

**Comment by steffenbrem** [comment]
@KannipaB I am sorry it took so long, I didn't saw the SO question till yesterday. I have put up an answer for you I think that is good enough for you to fix your issue, see: http://stackoverflow.com/questions/37267516/idea-of-multiple-theme-on-a-single-channel-in-sylius/37787515#37787515

**Comment by KannipaB** [comment]
Thanks a lot @steffenbrem :smile:

**Comment by takeit** [comment]
@KannipaB you can also take a look at [this PR](https://github.com/superdesk/web-publisher/pull/57/files) where we implemented multiple themes for each devices based on device detection feature which we ported from [LiipThemeBundle](https://github.com/liip/LiipThemeBundle#device-specific-themestemplates) and integrated it with SyliusThemeBundle.

Maybe this can be bundled into SyliusThemeBundle in the future. /cc @pjedrzejewski

**Comment by liverbool** [comment]
Just note here is some mobile detect lib: https://github.com/serbanghita/Mobile-Detect

**Comment by KannipaB** [comment]
@takeit Thanks you very much for your help. :)

**Comment by pamil** [comment]
As mentioned, it can be quite easily implemented in userland code and we rather keep ThemeBundle as small as it is possible. I guess it can be closed then.
