### ISSUE TITLE
[RFC] Implement StyleCI?

### ISSUE THREAD

**Issue by dantleech** [Sylius/Sylius#4997]
[Style CI](https://styleci.io/) is a (free) CI service for code styles, it can take care of things such as aligning, whitespace, missing use statements, etc and provides a way to the same coding standards across the entire project.

It analyzes pull requests and will fail if the pull request has code style issues (which happens 90% of the time in my experience) and can either provide a PR to fix them, or you can download a patch and apply it locally.

We use this in the Symfony CMF, e.g. https://styleci.io/analyses/8L3Agk

There are presets for the PSR coding standard and also a preset for the Symfony coding standard.

**Comment by michalmarcinkowski** [comment]
@dantleech thanks for rising this up! Would be great to set it up.

We had included the CS checks in our build, but it was very annoying and we decided to remove it and go with StyleCI (see [related PR](https://github.com/Sylius/Sylius/pull/4129#issuecomment-183256719)). Unfortunately we didn't find time to set it up, but it's probably good time to refresh the topic :)

**Comment by pjedrzejewski** [comment]
Actually, we had StyleCI running for a while, but there were 2 issues IIRC:

1. We could not set which status check on github is required (now resolved)
2. Due to phpspec we need a bit more specific configuration and I could not achieve that with StyleCI options.
