### ISSUE TITLE
[RFC] Return immutable collections in models

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#5000]
Now, we're using the following syntax for the resources with collections:

```php
class Taxon implements TaxonInterface
{
    protected $children;

    public function __construct()
    {
        $this->children = new ArrayCollection();
    }

    public function getChildren()
    {
        return $this->children;
    }

    public function addChild(TaxonInterface $taxon)
    {
        if (!$this->hasChild($taxon)) {
            $taxon->setParent($this);

            $this->children->add($taxon);
        }
    }
}
```

That allows us to get the children and add a child directly to the collection, though we'd like to allow it only through `Taxon::addChild(TaxonInterface $taxon)`:

```php
$taxonChildren = $taxon->getChildren();
$taxonChildren->add($childTaxon);

$taxon->addChild($childTaxon);
```

This RFC proposes to use `Collection::toArray()` method on every getter that returns a collection to ensure that all child taxons are added through a dedicated methods and so on.

```php
class Taxon implements TaxonInterface
{
    public function getChildren()
    {
        return $this->children->toArray();
    }
}
```

**Comment by peteward** [comment]
hmm that's quite a significant change.

There are lots of useful auxiliary methods on ArrayCollection which you'll be preventing unless you explicitly provide an interface to them through the wrapping object - like `filter()`, `matching()` and `exists()`.

Is it really worth it?

**Comment by michalmarcinkowski** [comment]
If we would like to still return `ArrayCollection` I believe that simple `return clone $this->children;` should work fine.

I'm definitely for encapsulation and immutability,  but as Peter mention, this is a big change that will require some effort (changing all current `getCollection()` methods implementation). 

It also has drawbacks like increased memory consumption (the collection will be duplicated on each `getCollection()` method call, what can result in several "the same" collections in memory at the same time).  Probably that's not the only issue here.

We could make an experiment about that, but I'm not sure if it's worth our effort to focus on it now.
