### ISSUE TITLE
problem with Sylius install

### ISSUE THREAD

**Issue by slim123321** [Sylius/Sylius#5002]
HY everyone,
Im trying to install sylius and i face those prbolems;

C:\xampp\htdocs\Nouveau dossier\sylius>php app/console sylius:install
Installing Sylius...

Step 1 of 4. Checking system requirements.
sylius.extensions
+-------------------------------+----------+
| Requirement                   | Status   |
+-------------------------------+----------+
| JSON                          | OK!      |
| Session                       | OK!      |
| Ctype                         | OK!      |
| Tokenizer                     | OK!      |
| SimpleXML                     | OK!      |
| APC                           | OK!      |
| PCRE                          | OK!      |
| PHP-XML                       | OK!      |
| Multibyte String              | OK!      |
| Iconv                         | OK!      |
| Exif                          | OK!      |
| Intl                          |  ERROR!  |
| Fileinfo                      | OK!      |
| sylius.extensions.accelerator | WARNING! |
| PDO                           | OK!      |
| GD                            | OK!      |
+-------------------------------+----------+
sylius.filesystem
+------------------------------+--------+
| Requirement                  | Status |
+------------------------------+--------+
| vendors                      | OK!    |
| sylius.filesystem.cache      | OK!    |
| sylius.filesystem.logs       | OK!    |
| sylius.filesystem.parameters | OK!    |
+------------------------------+--------+
+-------------------------------+-----------------------------------------------
----------------------+
| Issue                         | Recommendation
                      |
+-------------------------------+-----------------------------------------------
----------------------+
| short_open_tag                |
                      |
| session.auto_start            |
                      |
| Intl                          | Install and enable the intl extension.
                      |
| sylius.extensions.accelerator | Install and enable a PHP accelerator like APC
(highly recommended). |
+-------------------------------+-----------------------------------------------
----------------------+

  [RuntimeException]
  Some system requirements are not fulfilled. Please check output messages an
  d fix them.

sylius:install:check-requirements

please someone can help me?

**Comment by pjedrzejewski** [comment]
You are missing intl extension.

**Comment by slim123321** [comment]
how can i fix it?

**Comment by slim123321** [comment]
i fix the intl extension problem now i have another error

Success! Your system can run Sylius properly.

Step 2 of 4. Setting up the database.
Creating Sylius database for environment dev.



  [Doctrine\DBAL\Exception\ConnectionException]
  An exception occured in driver: SQLSTATE[HY000] [2002] Aucune connexion nÆa
   pu Ûtre Útablie car lÆordinateur cible lÆa expressÚment refusÚe.






  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[HY000] [2002] Aucune connexion nÆa pu Ûtre Útablie car lÆordinateu
  r cible lÆa expressÚment refusÚe.






  [PDOException]
  SQLSTATE[HY000] [2002] Aucune connexion nÆa pu Ûtre Útablie car lÆordinateu
  r cible lÆa expressÚment refusÚe.



sylius:install:database

please help me and thank you

**Comment by michalmarcinkowski** [comment]
Have you provided credentials to the database in `parameters.yml` file?

**Comment by michalmarcinkowski** [comment]
Let's continue [there](https://github.com/Sylius/Sylius/issues/5006).
