### ISSUE TITLE
duplicate entry coupon code on cart update

### ISSUE THREAD

**Issue by ibasaw** [Sylius/Sylius#5003]
hi,

I'm on the cart page, apply the coupon code for the second time, no limit in the administration and i got this error:

    UniqueConstraintViolationException: An exception occurred while executing 'UPDATE sylius_order SET adjustments_total = ?, total = ?, promotion_coupon_id = ?, updated_at = ? WHERE id = ?' with params [-830, 7470, 1, "2016-05-11 16:30:13", 28]:

    SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'UNIQ_6196A1F917B24436'

in my DB, here the index

        UNIQ_6196A1F917B24436	BTREE	Yes	No	promotion_coupon_id	4	A	Yes	

 a coupon code could be used by many users, so many orders

**Comment by michalmarcinkowski** [comment]
Which version do you use? There is `manyToOne` relation [configured](https://github.com/michalmarcinkowski/Sylius/blob/cb97c955d97a91affc4305974469ccf959fe8e68/src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Order.orm.xml#L39-L39), so there shouldn't be unique constraint.

**Comment by ibasaw** [comment]
0.17

**Comment by michalmarcinkowski** [comment]
I tried on master and this error does not occur. Probably it was fixed in the meantime.

**Comment by michalmarcinkowski** [comment]
@ibasaw please reopen if you managed to reproduce it on `master`.
