### ISSUE TITLE
problem with Sylius install Database connection

### ISSUE THREAD

**Issue by slim123321** [Sylius/Sylius#5006]
Hy everyone,
I'm installing sylius and i face some problems when i do php app/console/sylius:install and this is the error : 

Success! Your system can run Sylius properly.

Step 2 of 4. Setting up the database.
Creating Sylius database for environment dev.

[Doctrine\DBAL\Exception\ConnectionException]
An exception occured in driver: SQLSTATE[HY000] [2002] Aucune connexion nÆa
pu Ûtre Útablie car lÆordinateur cible lÆa expressÚment refusÚe.

[Doctrine\DBAL\Driver\PDOException]
SQLSTATE[HY000] [2002] Aucune connexion nÆa pu Ûtre Útablie car lÆordinateu
r cible lÆa expressÚment refusÚe.

[PDOException]
SQLSTATE[HY000] [2002] Aucune connexion nÆa pu Ûtre Útablie car lÆordinateu
r cible lÆa expressÚment refusÚe.

sylius:install:database

please help me and thank you

**Comment by michalmarcinkowski** [comment]
Have you provided credentials to the database in `parameters.yml` file?

**Comment by slim123321** [comment]
THIS IS my file parameters.yml  : 

parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3307
    database_name: sylius
    database_user: root
    database_password: null
    phpcr_user: root
    phpcr_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: EDITME
    locale: en_US
    currency: USD
    wkhtmltopdf.bin_path: /usr/bin/wkhtmltopdf
    wkhtmltoimage.bin_path: /usr/bin/wkhtmltoimage

**Comment by michalmarcinkowski** [comment]
You should provide credentials of your database user, see [symfony documentation](http://symfony.com/doc/current/book/doctrine.html).
