### ISSUE TITLE
sylius:install:sample-data -v

### ISSUE THREAD

**Issue by embaka** [Sylius/Sylius#5015]
Loading sample data...
 1/3 [||||||||||                  ]  33% 31 secs
                                                                                                                         
  [Doctrine\ODM\PHPCR\PHPCRException]                                                                                    
  Register phpcr:managed node type first. See https://github.com/doctrine/phpcr-odm/wiki/Custom-node-type-phpcr:managed  
                                                                                                                         
Exception trace:
 () at /var/www/sylius/vendor/doctrine/phpcr-odm/lib/Doctrine/ODM/PHPCR/UnitOfWork.php:2338
 Doctrine\ODM\PHPCR\UnitOfWork->executeInserts() at /var/www/sylius/vendor/doctrine/phpcr-odm/lib/Doctrine/ODM/PHPCR/UnitOfWork.php:2214
 Doctrine\ODM\PHPCR\UnitOfWork->commit() at /var/www/sylius/vendor/doctrine/phpcr-odm/lib/Doctrine/ODM/PHPCR/DocumentManager.php:752
 Doctrine\ODM\PHPCR\DocumentManager->flush() at /var/www/sylius/vendor/sylius/sylius/src/Sylius/Bundle/FixturesBundle/DataFixtures/PHPCR/LoadBlocksData.php:60
 Sylius\Bundle\FixturesBundle\DataFixtures\PHPCR\LoadBlocksData->load() at /var/www/sylius/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/AbstractExecutor.php:121
 Doctrine\Common\DataFixtures\Executor\AbstractExecutor->load() at /var/www/sylius/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/PHPCRExecutor.php:69
 Doctrine\Common\DataFixtures\Executor\PHPCRExecutor->Doctrine\Common\DataFixtures\Executor\{closure}() at /var/www/sylius/vendor/doctrine/data-fixtures/lib/Doctrine/Common/DataFixtures/Executor/PHPCRExecutor.php:76
 Doctrine\Common\DataFixtures\Executor\PHPCRExecutor->execute() at /var/www/sylius/vendor/doctrine/phpcr-bundle/Command/LoadFixtureCommand.php:172
 Doctrine\Bundle\PHPCRBundle\Command\LoadFixtureCommand->execute() at /var/www/sylius/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /var/www/sylius/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:860
 Symfony\Component\Console\Application->doRunCommand() at /var/www/sylius/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:192
 Symfony\Component\Console\Application->doRun() at /var/www/sylius/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:92
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/sylius/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:123
 Symfony\Component\Console\Application->run() at /var/www/sylius/vendor/sylius/sylius/src/Sylius/Bundle/InstallerBundle/Command/CommandExecutor.php:75
 Sylius\Bundle\InstallerBundle\Command\CommandExecutor->runCommand() at /var/www/sylius/vendor/sylius/sylius/src/Sylius/Bundle/InstallerBundle/Command/AbstractInstallCommand.php:128
 Sylius\Bundle\InstallerBundle\Command\AbstractInstallCommand->runCommands() at /var/www/sylius/vendor/sylius/sylius/src/Sylius/Bundle/InstallerBundle/Command/InstallSampleDataCommand.php:71
 Sylius\Bundle\InstallerBundle\Command\InstallSampleDataCommand->execute() at /var/www/sylius/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /var/www/sylius/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:860
 Symfony\Component\Console\Application->doRunCommand() at /var/www/sylius/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:192
 Symfony\Component\Console\Application->doRun() at /var/www/sylius/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:92
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/sylius/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:123
 Symfony\Component\Console\Application->run() at /var/www/sylius/app/console:17

**Comment by pjedrzejewski** [comment]
Run ``app/console doctrine:phpcr:repository:init`` - this is part of the ``sylius:install:database`` command, but if you do not use it - you have to run it manually. Let me know if that helps!

**Comment by bwach** [comment]
@pjedrzejewski stumbled upon the same thing, sylius:install:database solves the problem.
