### ISSUE TITLE
Shipping cost by destination

### ISSUE THREAD

**Issue by yaidelferrales** [Sylius/Sylius#5017]
I'm developing a Shipping calculator based on fedex service API, but I need the destination of the shipping, and the ShippingSubjectInterface object, the calculate method receives doesn't allow me to get that info.

**Comment by pjedrzejewski** [comment]
Hi @yaidelferrales, are you using Sylius as a whole or only the shipping bundle? If you have core, then your shipping subject interface object is a shipment, so you should have access to the Address. If you use shipping component/bundle standalone, then you need to handle it somehow, based on your implementation of the subject.

**Comment by yaidelferrales** [comment]
Hi and thank you for the quick response.
I'm using Sylus as a whole (v0.17.0), but the class **Shipment** in the namespace **Sylius\Component\Shipping\Model** does not have any Address.

**Comment by michalmarcinkowski** [comment]
@yaidelferrales the class in core `Sylius\Component\Core\Model\Shipment` has `order` and the order has shipping address :)

**Comment by michalmarcinkowski** [comment]
Sylius uses Stackoverflow as its official support channel. For future support questions please post these at http://stackoverflow.com/questions/tagged/sylius and tag your questions with `sylius`.
