### ISSUE TITLE
RFC: Price administration on Sylius

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#5021]
Hi everyone,
We have recently created a link between our ERP and Sylius. We are now able to get from the ERP a lot of price versions:
- bare prices / cost price
- prices with margin included
- margin categories etc.

We are thinking in importing the lowest price (cost price - the price we purchase the goods from our suppliers) and use the taxation system to apply margins for profit.

The system with tax, tax category and zones seems quite fit for that - imho. I would like to know if someone else is using it and if there is any feedback on this.

**Comment by pjedrzejewski** [comment]
Hmmm, interesting idea, but that can be a bit confusing - Sylius will treat them as taxes, while they are not. That being said, if it works in your model - then yeah, why not. Although I was thinking about introducing additional field ``cost`` to ProductVariant, to calculate margins.

**Comment by gabiudrescu** [comment]
we think of prices as a sum of multiple factors; for example:
- acquisition price
- margin
- VAT
- environment taxes (for electronics)

all these are actually adjustments with various scope: margin is for profit, VAT is for the gov., environment taxes go separately on the invoice etc.

by using tax categories (e.g. product types such as sweets, beverages, clothes etc, product brand or even product sizes), we think we would have the flexibility of generating with very little development effort a very good tool for our commercial department.

in the end, the logic behind taxes and price administration is the same: you add something up on top of the base price with different purposes.

sure, it's not the most semantic way of expressing things - but if this really becomes confusing, we can cheat and change the translation keys :dancer: 

personally, I see no gain from re-building the same logic of taxes just to rename it into price administration.
