### ISSUE TITLE
[Resource][Form] Why did ObjectToIdentifierTransformer get reversed?

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#5027]
The `DataTransformerInterface` [on github](https://github.com/symfony/form/blob/master/DataTransformerInterface.php) specifies:

* `transform()`  Transforms a value from the original representation to a transformed representation.
* `reverseTransform()` Transforms a value from the transformed representation to its original representation.

This seems logical and sensible to me, but `ObjectToIdentifierTransformer` seems to have been reversed so the opposite happens - and it blows up our forms as a result.

It happened in [this PR](https://github.com/Sylius/Sylius/pull/4702), it seems very wrong to me.

I can only think that the other changes in this PR which add an extra condition for `multiple` means that it wasn't actually ever called after the change so no one noticed it was broken.

Unless I'm wrong somehow?

**Comment by bendavies** [comment]
Just came across this. what's going on here?

**Comment by peteward** [comment]
Yeah it's quite a bad bug, I'm just not sure what the intentions were originally to suggest a fix.

@Zales0123 @pjedrzejewski ?

**Comment by pjedrzejewski** [comment]
We should revert that and @tuka217 has reworked the transformation forms (for autocomplete use) in #3951 and this is included in our current sprint so should land soon. I think the fix was supposed to resolve a bc break between Symfony 2.7 and 2.8 in the shipping form checkout. That being said, I don't have clue why this form type would be used there, so maybe we can revert that and fix the checkout form instead.

**Comment by Zales0123** [comment]
I think the reason of this whole mess with ``ObjectToIdentifierTransformer`` is the fact it's used in two different situations. In some of them we need to get identifier from object, in other *vice versa*. I don't remember what are this edge cases (hopefully will remember soon 😄 ) but I'm pretty sure I've struggling with both of them while working with ``ObjectToIdentifierTransformer``.

**Comment by bendavies** [comment]
I've opened a PR #5063.

**Comment by patrick-mcdougle** [comment]
See Symfony\Component\Form\ReversedTransformer might be helpful to deal with this problem.

**Comment by pjedrzejewski** [comment]
This is now resolved with 2 separate form types: ``from_identifier`` and ``to_identifier``. See #3951.
