### ISSUE TITLE
assets/admin missing

### ISSUE THREAD

**Issue by Flaxis** [Sylius/Sylius#5034]
I have installed the standard edition of Sylius, everything seems to work fine, except when I try to access the admin section... The web/assets/admin doesn't get installed, so all references to that path break.

I have already tried the following:
sylius:install
cache:clear
Clearing cache using rm -rf app/cache/*
assetic:dump
sylius:theme:assets:install
sylius:install:assets

I haven't changed anything in the code yet.

**Comment by lchrusciel** [comment]
Try to run `gulp`. Check [quick install](https://github.com/Sylius/Sylius#quick-installation) section. We are migrating from old admin which is available under `/administration/*` to `/admin/*` and thats why there are two admin panels.

**Comment by Flaxis** [comment]
I see now. I didn't have a packages.json or Gulpfile.js after installing Sylius using Composer create-project. I copied them from github and installing the assets works now. There's still a problem in Chromium 49.0.2623 where the sidemenu can't be opened but I guess that should be another issue on its own.
To be honest I'm just checking out Sylius to see if it's a good alternative to Magento, but I guess it's just too early :) I might get involved in development at some point :)
