### ISSUE TITLE
 how to generate  a  Behat feature definition snippets automatically in Sylius?

### ISSUE THREAD

**Issue by videni** [Sylius/Sylius#5037]
the official document says   ` bin/behat  feature_file_path.feature `can generate   definition snippets automatically,  I take the deleting_account.feature  as an example, it run the test instead generate snippets. 

```
bin/behat  features/user/managing_users/deleting_account.feature
```
Does this mean you write all  definitions by hands? what is the effective way to use Behat  in Sylius?  can anybody add some document on how to use Behat  ,Selenium in Sylius please?

**Comment by mheki** [comment]
hi @videni 
you can either copy generated methods into your context class or run:
```
bin/behat  features/user/managing_users/deleting_account.feature --append-snippets
```

Please note your context file has to implement `SnippetAcceptingContext`.
More in the official behat documentation:
http://docs.behat.org/en/v3.0/guides/2.definitions.html#definition-snippets

**Comment by videni** [comment]
@mheki , thanks , using this way ,it will generate the bootstrap directory , I found a better way , Behat is a feature integrated into PHPStorm, `alt+enter `  key can generate corresponding snippets automatically.
