### ISSUE TITLE
Cyrillic name in variations, problem again.

### ISSUE THREAD

**Issue by asidorov01** [Sylius/Sylius#505]
Hi!

Like in #475 we have problem with variations on frontend.
I specified russian variation name and product page throw 500 error.

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/VariableProductBundle/Form/Type/VariantMatchType.php#L33

We can:

1. Use id, what is preferable for me. Because it can be used in complex JS applications because it's primary key and can be natively handled with BackBone.

2. Add +1 field to database - slug and switch current functionality to that. I guess this is looks like over engineering.

3. Other suggestions?

**Comment by michalmarcinkowski** [comment]
Should be resolved already.
