### ISSUE TITLE
[Variation] Refactor VariantCombinationValidator

### ISSUE THREAD

**Issue by Zales0123** [Sylius/Sylius#5050]
While working on https://github.com/Sylius/Sylius/pull/4936, I've been struggling with `VariantCombinationValidator`. It definitely requires some refactoring and logic changes. Especially `matches` method should be rethink - the main thing that should be implemented is checking if `Variant` contains the same options (and all of them) as its `Variable` (`Product`).

**Comment by michalmarcinkowski** [comment]
It's been reworked.
