### ISSUE TITLE
[Question] Remove ability to delete an order

### ISSUE THREAD

**Issue by mheki** [Sylius/Sylius#5052]
Hi guys,
I'm quite new to Sylius, apologies if that has  already been discussed...

I've found out an Order is a resource which can be deleted.
That is my concern... do we really want to delete an order? It's not a use case in a real world - you can cancel an order, but it remains in the history.
Since Sylius is not stable yet I thought I could raise this discussion.
What would be a reason to delete an order?

**Comment by Cathmor** [comment]
I don't think that you want to remove the ability to delete but you definitely want to restrict the roles and remove the user ability to delete an order. And the ability to restrict roles is already built in.

**Comment by michalmarcinkowski** [comment]
Hello Marek! Deleting an order can be useful when you create test orders (this also can happen on prod database) and want to get rid of them. Of course you shouldn't delete any order that was placed by a customer and the recommended way is to cancel it.

**Comment by mheki** [comment]
Thanks for your replies!
Two things coming to my mind:

- I thought about orders stored and not removed from the system as it
happens in some others e-commerce or banking systems. You can cancel
a previous transaction, but not delete. It may be a business requirement.
But if you have your own way of dealing with that, that's fine - I don't
want to troll ;)


On 17 May 2016 at 21:47, Michał Marcinkowski <notifications@github.com>
wrote:

> Hello Marek! Deleting an order can be useful when you create test orders
> (this also can happen on prod database) and want to get rid of them. Of
> course you shouldn't delete any order that was placed by a customer and the
> recommended way is to cancel it.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Sylius/Sylius/issues/5052#issuecomment-219848714>
>



-- 
*Marek Pietrzak*
Software Engineer,
Zend Certified PHP Engineer,
SensioLabs Certified Symfony Developer (Expert)

*Inviqa*
enterprise open source

skype: mpietrzak.inviqa
e-mail: mpietrzak@inviqa.com
phone (direct): +44 20 3179 9555

phone: +44 20 3179 9555
twitter: @Inviqa <http://twitter.com/#%21/Inviqa>
*inviqa.com <http://www.inviqa.com>*

Disclaimer
This email and any attachments may be confidential and are intended solely
for the use of the addressee. Any views or opinions expressed are those of
the author and may not represent those of Inviqa. If you are not the
intended recipient of this email, you must neither take any action based
upon its contents, nor copy or show it to anyone. Please contact the sender
if you believe you have received this email in error.

**Comment by a2xchip** [comment]
@mheki This activity stands as "softdeletable" (some projects name it as "registry") and it was implemented in previous Sylius versions and then removed because of some unknown for me reasons.

**Comment by mheki** [comment]
@a2xchip soft deletes are pretty bad and related to the infrastructure layer. By not using delete I mean not using it at all for some resources because of the business requirements. Orders may be a pretty good example - Order cancelled means more than simply soft deleted.

**Comment by michalmarcinkowski** [comment]
@mheki It is not a problem to remove possibility of deleting order if that is your requirement, but we do not want to prevent it from a platform level. You can either restrict this functionality to specific persons or remove it completely.

@a2xchip The softdeletable is causing a lot of problems, look at [this RFC](https://github.com/Sylius/Sylius/issues/4140) I explained there our approach to deleting stuff.

**Comment by mheki** [comment]
thanks for the conversation 👍
