### ISSUE TITLE
Error: Call to a member function search() on null

### ISSUE THREAD

**Issue by ibasaw** [Sylius/Sylius#5053]
hi, when i try to do search with elasticsearch, got this error:

    Error: Call to a member function search() on null in src/Sylius/Bundle/SearchBundle/Finder/ElasticsearchFinder.php at line 153

    $objects = $this->targetIndex->search($elasticaQuery);

$elasticaQuery is not null, this is an objet

    object(Elastica\Query)#20269 (3)

what is my mistake ?

here my config

    fos_elastica:
    ....
            types:
               product:
                   mappings:
                       name:
                           type: string
                       description: ~
                       slug: ~
                       price:
                          type: integer
                       channels:
                          type: string
                          index: not_analyzed
                       taxons:
                          type: string
                          index: not_analyzed

**Comment by peteward** [comment]
It's not the `$elasticaQuery` that's NULL, it's the `targetindex`, which is injected into that service.

This is the `fos_elastica.index.sylius` service - do you have the index defined in your config?

**Comment by ibasaw** [comment]
got this in my config:

    fos_elastica:
    clients:
        default: { host: %service_elastic_host%, port: %service_elastic_port%, logger: true }
    indexes:
        website:
            index_name: msb_%kernel.environment%

**Comment by peteward** [comment]
I don't have the code in front of me but try changing `website` => `sylius` or change the `index_name: sylius`

**Comment by ibasaw** [comment]
yes, that's it, thank you !
