### ISSUE TITLE
[SettingsBundle] SettingsController references non-existent template 

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#5054]
`SettingsController::updateAction` uses `SyliusSettingsBundle:Settings:update.html.twig` as a default template, but that file does not exist.

**Comment by jrobeson** [comment]
that was a consequence of this change https://github.com/Sylius/Sylius/commit/a3a596ed967d3e32f8043e4b215f29c16029db24 . I think you're supposed to provide your own now, but the documentation wasn't updated.
