### ISSUE TITLE
[ShippingBundle] Relay pickup implementation

### ISSUE THREAD

**Issue by psyray** [Sylius/Sylius#5077]
Hi,

A simple question.
I need to provide to our customer a DPD pickup method which permit to customer to choose a relay to receive his goods.
Create shipping method in admin is easy, but display the pickup selection on the choice in frontend not.

For my use case, DPD is providing a complete doc to implement their shipping method.
The process is :
- Customer data typing in front (address) -> managed by Sylius
- Customer shipping method choice -> managed by sylius
- Sent data to DPD webservice via HTTP GET or POST, or SOAP 1.1/1.2 -> to implement (subject of this issue)
- Manage data response (XML) and save to db -> to implement

My first think was to add, under the frontend shipping method choice (radio button), a button which open a lightbox popup with the corresponding DPD pickup relay.
When customer has made his choice, save pickup info to db and continue checkout process.
In my use case, i don't have the possibility, without doing override, to add such a functionality (onclick event).
This use case is really frequent and I think Sylius should let the possibility to add a onclick javascript event on the radio button to permit this use case (or any other thing).

Is there a way to cleanly integrate DPD pickup (or others pickup method) ?

Thanks for reply

**Comment by psyray** [comment]
@pjedrzejewski and others who are interested to implement this functionality.

I achieve this by adding two new fields to Shipment and ShippingMethod entities to manage relay.
- In Shipment I 've added **relayCode** property, _to keep relay customer choice in checkout process_.
- In ShippingMethod  I 've added **relay** property, _to clearly identify what method depends on getting a relay choice via web service_.

By adding this two property I was able to add a checkbox in admin to set what shipping method is a relay and I add form field to specify webservice url and key.

On the checkout shipping form : 
- First, I've added a small JS to display a button while checking a shipping method choice defined in admin as relay (disappear if not relay), which open a pop-up to permit customer to choose his relay,
- Second, I've modified the form to add an hidden input which store the relay id chosen by customer on pop-up close

To manage this popup, I've added a controller, with two routes which fetch datas by AJAX via API.
- First route _to get relay based on the customer billing address_.
- And second _to get relay around a specific city_.

And last, to manage the submission, I've added a listener on ShippingForm which **store data to db** (_on complete event_) and **get relay details** (_on initialize event_).

Here is some screen capture to illustrate the process
**Shipping Checkout Form**
![selection_479](https://cloud.githubusercontent.com/assets/1230954/15518738/966f849a-21fe-11e6-941d-dbc17a78279a.jpg)

**Relay pop-up choose** 
![selection_480](https://cloud.githubusercontent.com/assets/1230954/15518786/c5c227ac-21fe-11e6-9f9a-3c630325d9b9.jpg)

**Error on shipping form if a shipping method is a relay and no id filled in hidden field**
![selection_481](https://cloud.githubusercontent.com/assets/1230954/15518850/0cda67da-21ff-11e6-818f-cb5071d1cbc0.jpg)

**Relay informations displayed to customer**
![selection_482](https://cloud.githubusercontent.com/assets/1230954/15518985/9a1d2ab0-21ff-11e6-8b3a-20fb0644d893.jpg)

Et voilà :)

@pjedrzejewski 
Do you think this use case should be applied to Sylius ?
I could submit a PR if you want.

**Comment by okwinza** [comment]
@psyray this looks extremely useful, great work!
I doubt this would be seen in core anytime soon tho as it's not a generic feature.

But it is still a viable and common used feature so please open a PR. I'd be happy to contribute.
