### ISSUE TITLE
Little bug with flash bag for multiple coupon promotions

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#5085]
#### Expected behaviour
When I enter a valid coupon code of a promotion, I expect that the flash bag only contains success flashes.

#### Actual behaviour
When entering a valid coupon code of a promotion, it adds the `sylius.promotion_coupon.not_eligible` flash message which we don't want, since the promotion coupon code is valid.

#### Explanation
This is happening when you have two coupon based promotions that have no rules and only actions. The piece that is causing this behaviour is https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Promotion/Checker/CouponsEligibilityChecker.php#L49. It will always fail if you have multiple promotions with coupon codes.

How can I best approach this issue? Should I remove the dispatching of that event in the checker?

**Comment by inssein** [comment]
I thought this bug was fixed. I still get https://github.com/Sylius/Sylius/issues/5008 though.

**Comment by michalmarcinkowski** [comment]
Should be fixed in https://github.com/Sylius/Sylius/pull/6273.
