### ISSUE TITLE
Pb Menu

### ISSUE THREAD

**Issue by MattZ9** [Sylius/Sylius#5092]
Hello !

I extended SyliusWebBundle. I logged in admin I removed the original categories and produtcs, and I took my categories and my products.
But I have nothing in my menu now, I don't understand why...
Someone would have an idea please ?

Thank you for your help, urgent.

**Comment by pjedrzejewski** [comment]
@MattZ9 Have you checked the query executed? In Symfony web profiler, what did you customize exactly in SyliusWebBundle?

**Comment by MattZ9** [comment]
I tried with the original sylius project (with no extends) and I have the same pb : no menu.
I looked in Symfony web profiler, the 5th query : 
```
SELECT t0.code AS code1, t0.tree_left AS tree_left2, t0.tree_right AS tree_right3, t0.tree_level AS tree_level4, t0.id AS id5, t0.path AS path6, t0.tree_root AS tree_root7, t0.parent_id AS parent_id8 FROM sylius_taxon t0 INNER JOIN sylius_channel_taxon ON t0.id = sylius_channel_taxon.taxon_id WHERE sylius_channel_taxon.channel_id = ?
Parameters: [1]
```

**Comment by MattZ9** [comment]
During the installation, I installed the fixtures. After that i removed categories and products manually from the admin environment, and added my categories and products.

**Comment by MattZ9** [comment]
I search since many days.. I don't understand. Do I have to purge the DB before my entries ? Maybe there are some conflicts.

**Comment by pjedrzejewski** [comment]
This is stupid and will be fixed, but now you need to assign proper taxons to Channel in the update channel screen. Hope it helps.

**Comment by MattZ9** [comment]
Yes ! It solves my problem ! :+1: Thank you !
