### ISSUE TITLE
how to find  translation file for a translation key  ?

### ISSUE THREAD

**Issue by videni** [Sylius/Sylius#5099]
I found some translation mistakes, but I don't know how to  find translation file for a translation key  , can anyone point me out?

**Comment by okwinza** [comment]
If you want to fix some translations you'd better do it via https://crowdin.com/project/sylius

**Comment by videni** [comment]
@okwinza , since I can't find  the translation file in Sylius, I can't  find which file in Crowdin, Crowdin doesn't have the function to search  keywords.

**Comment by okwinza** [comment]
@videni 

If you can't find the translation key you can simply use the search.
All translations are divided into these files;

- messages.%lang_code%.yml
- flashes.%lang_code%.yml
- menu.%lang_code%.yml

These can be found in SyliusWebBundle/Resources/translation.

But keep in mind that this will soon change as WebBundle will be replaced with ShopBundle and UIBundle

**Comment by videni** [comment]
@okwinza ， thanks，  is there a utility that can display translation file for translation key  ? it seems I have heard that but I don't remember its name,   As we know  not all translations are in SyliusWebBundle, that is  the best way to solve this problem.

**Comment by okwinza** [comment]
@videni its called Symfony Web Debug Toolbar
The ones which aint listed in these files are loaded dynamically and its mostly shop specific stuff like product names, categories, etc. In this case you can edit their translation in admin dashboard.

**Comment by michalmarcinkowski** [comment]
Think this can be closed.
