### ISSUE TITLE
how to simulate this  relation using Sylius product prototyping system?

### ISSUE THREAD

**Issue by videni** [Sylius/Sylius#5100]
Assume we have 100 car models, and we have product which can only be used for 20 of them.  when a customer tries to buy this product, we want  the customer  to choose his car model first, it seems it is impossible to  simulate this relation using Sylius product prototyping system, what do you say?

**Comment by peteward** [comment]
It sounds like Car Models could be Product Archetypes. 

You choose a Product Archetype first, then you are shown the available Products that use this Archetype.

It depends what else you need I guess.

**Comment by videni** [comment]
@peteward ,if I understand you correctly, both the product  and car model are archetypes,  but how to add relation from product to car model?   lets say when a administrator creates a product , the administrator wants this product can be used to 20 car models, it seems the car model could be a   
option of the product archetype, but  all the values of a option would be showed out, we only want to show 20  not 100 for  customer to choose.

**Comment by peteward** [comment]
OK I understood now.

I don't think there's anything out of the box to do what you want (correct me if I'm wrong someone!).

One fairly simple option might be to add the Car Models as individual attributes with a checkbox / boolean value (so Mercedes E-Class, Mercedes B-Class, Mercedes A-Class would all be individual Attributes). Then you have a many-to-many between Car Models and Products.

However presumably you would need to differentiate these attributes from others both in the admin UI and in the frontend. To do this you could either do something hacky like prefixing something like `CarModel_` to the front of attribute codes and write queries to target these. Alternatively for a more 'correct' approach you could add a Category or grouping system to attributes. However the attribute system is quite complex. If you're going down this route then you might find it easier to just add your own many-to-many entity system for CarModel to Product with a simple ResourceController CRUD.

**Comment by videni** [comment]
@peteward , thanks for your help, using option or attribute will make this function very complex,   I will try to add a  many-to-many mapping from CarModel to Product.
