### ISSUE TITLE
[Metadata] Child MetadataSubjects of different types throws Exception

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#5101]
```
abstract class AbstractMetadata implements MetadataInterface
{
    /**
     * {@inheritdoc}
     */
    public function merge(MetadataInterface $metadata)
    {
        if (!$metadata instanceof $this || !$this instanceof $metadata) {
            throw new \InvalidArgumentException(
                sprintf(
                    'You can only merge instances of the same classes. Tried to merge "%s" with "%s".',
                    get_class($this),
                    get_class($metadata)
                )
            );
        }
```

The problem with this is the use-case of a child subject within the hierarchy having a different type of Twitter Card.

e.g. You could have a `ProductArchetype` with a `SummaryCard` but then override this at the individual `Product` level with a `SummaryLargeImageCard`.

The exception could be caught, but because this is a recursive action it would break all outstanding merging. 

My proposal is not to throw an Exception and instead just return silently to allow the recursive processing to continue. It won't merge something it can't so should be harmless.

**Comment by pamil** [comment]
We no longer have Metadata component & bundle in `Sylius/Sylius`.
