### ISSUE TITLE
[ThemeBundle] Disable Translator

### ISSUE THREAD

**Issue by winzou** [Sylius/Sylius#5113]
Hi,

Is there a way to disable anything related to translations in the ThemeBundle when the global symfony configuration indicates:

    framework:
        translator:
            enabled: false

Because for now it gives me this error:

    Warning: array_merge(): Argument #2 is not an array in vendor\sylius\theme-
    bundle\Translation\Provider\CompositeTranslatorResourceProvider.php line 40

Thanks!

**Comment by pjedrzejewski** [comment]
Good catch! I am pretty sure it is about not loading a file when it is enabled, but not sure: @pamil can shed some light on this. :)

**Comment by pamil** [comment]
We shouldn't run any compiler passes from `@ThemeBundle/Translation/DependencyInjection/Compiler` when `framework.translator.enabled` is `false`, I'll see what I can do (it's like reverse-prepend :)).

**Comment by winzou** [comment]
Hi @pamil, did you get some time to have a look at this? Thanks!

**Comment by pamil** [comment]
Sorry it took so long @winzou, you shouldn't get that error again with #5339 and the following configuration:

```yaml
sylius_theme:
  support:
    translations: false
```

**Comment by pjedrzejewski** [comment]
Hope it helps @winzou, thanks for the report!
