### ISSUE TITLE
Tax rates not applied

### ISSUE THREAD

**Issue by yaidelferrales** [Sylius/Sylius#5122]
I'm trying to apply a tax to all products, but I can't get it to work. I have created the tax category and I also have assigned that category to one product, but when I add that product to the shoping cart no tax is applied. (the tax category has a tax rate assigned of 5%)

Can you please tell me if I'm missing something?

**Comment by pjedrzejewski** [comment]
What is your zones configuration? And default tax zone?

**Comment by yaidelferrales** [comment]
Default tax zone: Canada
I have only one zone and it applyes to Canada and the scope is shipping

**Comment by michalmarcinkowski** [comment]
Please have a look at the [docs](http://docs.sylius.org/en/latest/book/taxation.html), maybe you will find it useful.
