### ISSUE TITLE
Controller "sylius.controller.user:changePasswordAction" for URI "/account/change-password" is not callable.

### ISSUE THREAD

**Issue by ibasaw** [Sylius/Sylius#5123]
sylius 0.18 when i try to change password in the frontend account

    CRITICAL - Uncaught PHP Exception InvalidArgumentException: "Controller "sylius.controller.user:changePasswordAction" for URI "/account/change-password" is not callable."

**Comment by ibasaw** [comment]
found it, an old override of controller in my config.yml...sorry for this one

**Comment by pjedrzejewski** [comment]
@ibasaw No worries, thanks for closing!
