### ISSUE TITLE
Taxes in Summary

### ISSUE THREAD

**Issue by yaidelferrales** [Sylius/Sylius#5132]
The cart summary is displaying the prices with all the taxes applied (5% in my case), but in the taxes area displays a **0**. The product price is 260 + 13(taxes) = 273. Using Sylius version 0.17.

![cart](https://cloud.githubusercontent.com/assets/19334411/15625591/5cf8e50a-2472-11e6-9247-10cb539df691.png)

**Comment by pjedrzejewski** [comment]
Hi @yaidelferrales, could you share your template? What version are you using? We have just merged few things that should simplify the templates.

**Comment by michalmarcinkowski** [comment]
Not an issue on current master.
