### ISSUE TITLE
[Resource] (RFC) Metadata Registry - hasByClass / specific exception when not found.

### ISSUE THREAD

**Issue by dantleech** [Sylius/Sylius#5135]
Currently when I need to determine if Sylius has metadata for a specific object I need to do the following:

``` php
try {
    $metadata = $this->registry->getByClass($classFqn);
} catch (\InvalidArgumentException $e) {
    return false;
}
```

This is not ideal as an `InvalidArgumentException` is ambiguous.

I propose adding a `hasByClass` method or throwing a `ResourceMetadataNotFound`
exception.

**Comment by pjedrzejewski** [comment]
Sounds good to me!
