### ISSUE TITLE
More functionallity to product in REST API

### ISSUE THREAD

**Issue by tato469** [Sylius/Sylius#5158]
I noticed that [Products at the API REST](http://docs.sylius.org/en/latest/api/products.html) is very simple. When you create a product you only can provide name, description, price, shortDescription. How could I add masterVariant or upload the photo?

If these features are not implemented, I could try to develop them.

**Comment by okwinza** [comment]
Hello @tato469 could you please describe your usecase?

**Comment by tato469** [comment]
I mean, I want to create new product but as is described in the [docs](http://docs.sylius.org/en/latest/api/products.html#creating-an-product) the parameters are name, description, price and shortDescription(Optional). So at the documntation there is not any reference to upload a photo for the product or add options.

**Comment by okwinza** [comment]
@tato469 the current implementation of Sylius' REST API is quite limited and can be complicated sometimes. What is your exact scenario in this case? Are you trying to import products from some kind of (ERP/Warehouse) external software?

**Comment by tato469** [comment]
Yes I want to allow to create products from other platform hosted in other server. 
I will try to create these basic functions, I will post here with the results.

**Comment by okwinza** [comment]
@tato469 in this case you might try it the other way around: create a bundle in your Sylius app, connect it to your software(via api or DBAL or w/e) and use the fixtured-style approach(https://github.com/Sylius/Sylius/tree/3e7fd7a4f801eeaa5f3f359c3b9ec44205fe0c4f/src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM). This way you get all the freedom working with entities and more.

I had exact the same task and tried to solve it via REST API but it was(and still is) quite limited for it.

By the way, the concept of MasterVariant got removed in latest master so keep this in mind.

**Comment by tato469** [comment]
Ok, thanks for the advices.
