### ISSUE TITLE
sylius_contact redirect to login page ?

### ISSUE THREAD

**Issue by ibasaw** [Sylius/Sylius#5159]
hi,

why the route sylius_contact redirect to login page ?

How to override this action ?

I want guest can see and send form from contact page

**Comment by ibasaw** [comment]
i had created my own controller for this action...but i don't undesrtand your logic here.

guest on website must write on contact page.

**Comment by tchapi** [comment]
+1, same behavior here : `sylius_contact` route redirects to `/login`, whereas I guess it shouldn't.

I have tried to add a route in `security.yml` to allow anonymous access but to no avail.

**Comment by coox** [comment]
👍

**Comment by tchapi** [comment]
Anybody has a workaround for that ? Or a least an explanation as to why it does redirect to `/login` ?

**Comment by tchapi** [comment]
Ok, As far as I can tell, it's just a matter of adding

    permission: false

under the `_sylius` node in `vendor/sylius/sylius/src/Sylius/Bundle/WebBundle/Resources/config/routing/frontend/contact.yml`

Anybody know how I can override this file n my own Bundle, for now ? It doesn't seem to be fixed yet (looking in https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/WebBundle/Resources/config/routing/frontend/contact.yml)

Thanks !

**Comment by michalmarcinkowski** [comment]
No longer valid.
