### ISSUE TITLE
Postgresql Out-of-Range exception

### ISSUE THREAD

**Issue by behram** [Sylius/Sylius#5160]
if you use 2147483648 or higher integer for id field pg throws exception. like below;

```
An exception occurred while executing 'SELECT t0.email AS email1, t0.email_canonical AS email_canonical2, t0.first_name AS first_name3, t0.last_name AS last_name4, t0.birthday AS birthday5, t0.gender AS gender6, t0.created_at AS created_at7, t0.updated_at AS updated_at8, t0.phone_number AS phone_number9, t0.id AS id10, t0.currency AS currency11, t0.billing_address_id AS billing_address_id12, t0.shipping_address_id AS shipping_address_id13, t14.username AS username15, t14.username_canonical AS username_canonical16, t14.enabled AS enabled17, t14.salt AS salt18, t14.password AS password19, t14.last_login AS last_login20, t14.confirmation_token AS confirmation_token21, t14.password_requested_at AS password_requested_at22, t14.locked AS locked23, t14.expires_at AS expires_at24, t14.credentials_expire_at AS credentials_expire_at25, t14.roles AS roles26, t14.created_at AS created_at27, t14.updated_at AS updated_at28, t14.id AS id29, t14.customer_id AS customer_id30 FROM sylius_customer t0 LEFT JOIN sylius_user t14 ON t14.customer_id = t0.id WHERE t0.id = ?' with params ["2147483648"]:

SQLSTATE[22003]: Numeric value out of range: 7 ERROR: value "2147483648" is out of range for type integer
```

`/administration/customers/2147483647/edit` -> 404 (normal)
`/administration/customers/2147483648/edit` -> 500 exception

Related Links;
- https://www.postgresql.org/docs/9.1/static/datatype-numeric.html
- https://github.com/ojs/ojs/issues/1502

**Comment by slm** [comment]
+1

**Comment by slm** [comment]
That's very important for me. I have got so money. If that issue has been closed. I will give ONE MILLION DOLLARS who solves.

**Comment by pamil** [comment]
What is the result of running it on `prod` environment? It should fail gracefully.

**Comment by pamil** [comment]
Two years later, I wouldn't think of it as a bug. In order to get that `500` error, you have to manually change the `id`. There's no way I know of application itself would serve you a link like that.

**Comment by behram** [comment]
Yeah, it's not a bug, at the same time not a server error too, because of that we think like it must be a 404 like Mysql database. And we implemented a Request Listener. 

Related -> https://github.com/academic/vipa/commit/2e71fcc30f660f4fb63736b599429117db6c1573#diff-8563f7f5b328ae84be6eb0c958b280f1R39
