### ISSUE TITLE
Invalid method name that leads to confusion and bugs

### ISSUE THREAD

**Issue by michalmarcinkowski** [Sylius/Sylius#5173]
After changing the logic to always save currency code instead of `Currency` object on `Order` the method `get/setCurrency` was never renamed to `get/setCurrencyCode`. That leads to confusion and bugs. Example can be found in the new [Setup/OrderContext](https://github.com/michalmarcinkowski/Sylius/blob/5b4f09a6f5a636aab8ec6f7f3a088f0cb6a20cb9/src/Sylius/Behat/Context/Setup/OrderContext.php#L469-L469) where we set and typehint to `CurrencyInterface` which later leads to bugs which were not revealed in the main repo yet.

The same situation can be found on `Payment` model which also has `get/setCurrency` method that actually accepts currency code not an object.

### The solution 
- [x] Rename all `get/setCurrency` methods that accept currency code to `get/setCurrencyCode`
- [x] In `setCurrencyCode` method we should use `Assert::string` to ensure we don't set any object
- [x] Add [Currency validation constraint](http://symfony.com/doc/current/reference/constraints/Currency.html) to models, in order to prevent from setting invalid code
- [x] Rename all variables that represents currency code to `currencyCode` instead of `currency` that indicates an object

**Comment by pjedrzejewski** [comment]
👍 👍 👍

**Comment by michalmarcinkowski** [comment]
Done in #5228.
