### ISSUE TITLE
Order items not persisted ?

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#5181]
When following the docs to create an order programmatically, the order items are not persisted in the database, whereas the order is. If I try to persist them with `persist($orderItem)` then Sylius issues an error complaining about the wrong type (`/Core` or `/Model`). 

Here is the code I use :
```php
$orderItemFactory = $this->getOrderItemFactory();
$orderItemQuantityModifier = $this->get('sylius.order_item_quantity_modifier');

$order = new Order();
$orderItem = $orderItemFactory->createNew();

$orderItem->setUnitPrice(1000);
$orderItemQuantityModifier->modify($orderItem, 4);

$orderItem->setOrder($order);

$em = $this->getDoctrine()->getManager();
$em->persist($order);
$em->flush();
```

**How do we persist the order items ?** Is there a better way to create a cart programmatically ?
Thanks a lot ;)

**Comment by okwinza** [comment]
Hello @tchapi Could you copy/paste the whole error message please?

**Comment by tchapi** [comment]
`Found entity of type Sylius\Component\Order\Model\Order on association Sylius\Component\Core\Model\OrderItem#order, but expecting Sylius\Component\Core\Model\Order`

**Comment by okwinza** [comment]
@tchapi yep, since you're using Sylius as a whole, you should stick to `Core` classes and stuff because its the only component that couples everything together.

For example, `Order` component doesn't know anything about `Shipment` and thus cannot be used directly in your app.

**Comment by okwinza** [comment]
as for how to create an order -- take a look at FixturesBundle. It illustrates all the api and logic needed to create an order pretty well.

https://github.com/Sylius/Sylius/blob/3e7fd7a4f801eeaa5f3f359c3b9ec44205fe0c4f/src/Sylius/Bundle/FixturesBundle/DataFixtures/ORM/LoadOrdersData.php

**Comment by tchapi** [comment]
So If I want to add an item to the cart, the way used in the **FixturesBundle** is the correct way to do this, with `sylius.factory.order` and `sylius.factory.order_item`, right ?

**Comment by okwinza** [comment]
@tchapi yep

**Comment by tchapi** [comment]
Ok alright, I'll try that — thanks a lot !
