### ISSUE TITLE
[resource] Metadata debug command.

### ISSUE THREAD

**Issue by dantleech** [Sylius/Sylius#5191]
I think it would be nice to have a `resource:debug` command or similar:

```
$ ./app/console resource:debug
# .. list of all registered resources
```

```
$ ./app/console resource:debug my_resource
# .. show complete metadata for named resource
```

**Comment by Niiko** [comment]
Agree, but debug:resource instead, as all debug commands in sf

**Comment by dantleech** [comment]
Yeah - `debug:resource` could conflcit with other things however. So would prefer to prefix: `sylius:debug:resource` ?
