### ISSUE TITLE
Using latest version of Sylius

### ISSUE THREAD

**Issue by RobertLangore** [Sylius/Sylius#5194]
Installed sylius standart with v0.18 of sylius and then changed the sylius version to 0.19 (the latest).
After `composer update`, I'm getting the error:
`Fatal error: Class 'Sylius\Bundle\CoreBundle\Kernel\Kernel' not found in app\AppKernel.php on line 5`

It's a cached file: I don't know if from composer or sylius (symfony).
How can this error be fixed?

I saw that AppKernel.php, AppCache.php and some config files (in app/config; all apart config_test_cached.yml, router_test_cached.php and routing_dev.yml) where changed in sylius/sylius and these are not reflected in sylius/standart. Even after I manually copied these files in sylius/sylius, I get the same error. I regenerated the "bootstrap.php.cache", but that didn't help.

**Can the updating to the latest version on sylius/sylius be done in a simpler way?**
Updating the sylius/standart repo to reflect the latest changes in sylius/sylius, and updating the necessary files in sylius/standart throught composer or git. Or to have:
sylius/standart-stable --> refers to the latest stable version of sylius/sylius (v0.18 now) 
sylius/standart-latest --> refers to the latest dev version of sylius/sylius (v0.19 now) 

After applying the latest updates of sylius/sylius, what other operations should be performed:
- if there are changes in the databse structure or data: is doctrine:schema:update --force sufficient or sylius:install is necesary?
- sylius:install:assets
- sylius:install:sample-data?

**Comment by RobertLangore** [comment]
When installing sylius yesterday `composer create-project -s dev sylius/sylius-standard` with dev stability, it installed the sylius v0.19. Some days ago, and I think 2 days ago, it installed sylius v0.18.

So now `-s dev` is installing from dev-master with the last commit as specified in packagist. This is ok, but it is not possibile to the latest commit via composer update. This is still ok, if the git source is updated regurarly for sylius/sylius in packagist, making sure that also sylius/sylius-standart is updated if necessary.

@pjedrzejewski Can you confirm that it is going to be this way?

`composer create-project -s stable sylius/sylius-standard` is installing the latest stable version (v018 now).

**Comment by pamil** [comment]
Sylius-Standard just got updated :tada:
