### ISSUE TITLE
[Bug] PayumBundle GetStatus contains 2 unimplemented methods

### ISSUE THREAD

**Issue by a2xchip** [Sylius/Sylius#5199]
Bug caused because of payum [update](https://github.com/Payum/Payum/commit/a0aca14e822a70008d9dded87dab346baf8c4795) throws error during checkout using offline payment method. v0.17

**Comment by makasim** [comment]
These methods are there https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/PayumBundle/Request/GetStatus.php#L182

**Comment by makasim** [comment]
I think the problem comes from older sylius version when you try to upgrade only payum libs.

**Comment by a2xchip** [comment]
0.17 without any upgrade

**Comment by michalmarcinkowski** [comment]
No longer valid.
