### ISSUE TITLE
Remove ShippableAddressConstraint from AddressingBundle

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#5203]
This https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AddressingBundle/Validator/Constraints/ShippableAddressConstraintValidator.php#L58 should go away, especially from AddressingBundle.

We should reimplement this logic on the CoreBundle if needed.

**Comment by michalmarcinkowski** [comment]
It's already removed.
