### ISSUE TITLE
[User] Customer Registration event

### ISSUE THREAD

**Issue by dantleech** [Sylius/Sylius#5204]
Currently if the a customer registers, a standard resource controller `ResourceActions::CREATE` event is fired.

But this is no guarantee that this was a *customer* registering themselves, or a customer being created in the backoffice, or from anywhere.

Would it make sense to add a specific `CustomerActions::REGISTRATION` event? or is there already a way to distinguish the context of a registration?

**Comment by michalmarcinkowski** [comment]
Actually there is a specific `register` event dispatch on registration, [see routing configuration](https://github.com/michalmarcinkowski/Sylius/blob/5009463405dee467e3503b210f3a30e274ec9414/src/Sylius/Bundle/WebBundle/Resources/config/routing/frontend/user.yml#L8-L8).

We should consider adding costants for all relevant events, but I that's a topic for separate RFC.

**Comment by dantleech** [comment]
Great, thanks. Constants would be great, but not sure how constants would work in the current architecture - would be better to specify the whole event name instead of a suffix, as then you could inject the constant values into the container and use `%events_customer_registration%` as a value f.e.

**Comment by dantleech** [comment]
(see http://symfony.com/doc/current/components/dependency_injection/parameters.html#array-parameters)
