### ISSUE TITLE
500 error on http://demo.sylius.org/

### ISSUE THREAD

**Issue by leogout** [Sylius/Sylius#5206]
Hi, an error 500 occurred while I was navigating on http://demo.sylius.org/
I don't know if it's the right place to warn you about this..
The last thing I did before it crashed was filtering some stickers by price here : 
- http://demo.sylius.org/t/category/stickers
- This was the full query (untouched) : http://demo.sylius.org/t/category/stickers?filters%5B%5D%5Bprice%5D=0%7C2000&q=&search_param=

I don't think it will help more than the logs but I thought it could be useful.

**Comment by lchrusciel** [comment]
Does anybody else encountered this problem? It is working now. 

@leogout You have been looking into Sylius, when demo has been restarted probably. There is a cron job for that.

**Comment by leogout** [comment]
Yeah that seems to work now. It was down for about 20 minutes. If it seems normal for you sorry for the false alarm.
