### ISSUE TITLE
[Documentation] Order

### ISSUE THREAD

**Issue by harikt** [Sylius/Sylius#5207]
Hey,

I thought of playing again with sylius and its components.

Noticed a few issues in the documentation .

When looking at  http://docs.sylius.org/en/latest/components/Order/basic_usage.html#items-management

we have 

```php
<?php

use Sylius\Component\Order\Model\Order;
use Sylius\Component\Order\Model\OrderItem;

$order = new Order();

$item1 = new OrderItem();
$item1->setName('Super cool product');
$item1->setUnitPrice(1999); // 19.99!
$item1->setQuantity(2);

$item2 = new OrderItem();
$item2->setName('Interesting t-shirt');
$item2->setUnitPrice(2549); // 25.49!

$order->addItem($item1);
$order->addItem($item2);
$order->removeItem($item1);
```

If you look more closely there is no `setName` , `setUnitPrice` , `setQuantity` .

I was looking more into the code to fix the documentation, but didn't completely get what all things I need to do to fix the same. In case if someone is here to help .

Below is what I did to try 

```php
$item1 = new Identity();
$item1->setName('Super cool product');
$item1->setValue(1999); // 19.99!

$item2 = new Identity();
$item2->setName('Interesting t-shirt');
$item2->setValue(2549); // 25.49!

$cart->addIdentity($item1);
$cart->addIdentity($item2);
```

I am wondering how we can add the quantity. Looks like it needs `OrderItem` , but how is `OrderItem` linked to `Identity` and more questions.. I will again look more if I can figure out myself.

Thank you

**Comment by okwinza** [comment]
Hey @harikt 
Things are changed a little bit too fast around here for now so docs will be out-of-date untill Sylius hits stable.

As i mentioned in #5181 the best way to get some insight into Sylius underlying API is to dive into FixturesBundle.

**Comment by harikt** [comment]
Hey @okwinza ,

Thank you for your fast reply. I will look into the fixtures bundle.

If you think we can close the issue, please do.

Thanks once again.
