### ISSUE TITLE
[RFC] A way to change response code and/or body of ResourceController::updateAction 

### ISSUE THREAD

**Issue by koemeet** [Sylius/Sylius#5222]
Right now the `updateAction` is forcing a `204` and provides you with an empty `View` object (no data in it). Before you had the resource with it and you could for example override the `ViewHandler` and manipulate the response to be `200` with the serialized resource with it. 

For my API that I build around all Sylius resources I am in need to have the whole resource serialized in the payload when you update it, instead of a `HTTP 204 No Content`. 

Before this change happend, I achieved it by doing the following in a decorated view handler:

``` php
/**
 * {@inheritdoc}
 */
public function handle(RequestConfiguration $requestConfiguration, View $view)
{
    if (Response::HTTP_NO_CONTENT === $view->getStatusCode() && null !== $view->getData()) {
        $view->setStatusCode(Response::HTTP_OK);
    }

    return $this->viewHandler->handle($requestConfiguration, $view);
}
```

It is not the cleanest solution, but it worked for me. Right now I am stuck since the whole data property of the view is `null`.

This problem was introduced by PR https://github.com/Sylius/Sylius/pull/5161.

**Comment by bendavies** [comment]
how about supporting returning responses from the events?
https://github.com/Sylius/Sylius/blob/6fa42871f1e22a777044928cadd2e9c94ede48ae/src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php#L314

**Comment by bendavies** [comment]
note that @michalmarcinkowski says at the bottom of #5161 that it could be made configurable in the future.

**Comment by pjedrzejewski** [comment]
@bendavies That would be cool for other reasons too! :)

@steffenbrem What if we make it configurable? I see some usecases for getting 200 with a resource after update, for mobile api responses where number of requests is quite important. Would be perfect to configure it globally and per route. Although I am not too happy about adding more stuff to ``_sylius`` config. :D

**Comment by bendavies** [comment]
@pjedrzejewski sorry, i removed the comment. since you replied, what i said was, what about supporting returning responses from events.

**Comment by steffenbrem** [comment]
@bendavies I think that is the best way to implement it in the ResourceController indeed. Something like a `ResourceResponse` event?

**Comment by bendavies** [comment]
`ResourceControllerEvent` is already used. what about adding an optional response?

**Comment by steffenbrem** [comment]
What do you mean exactly with an optional response?

**Comment by bendavies** [comment]
take a look at `ResourceControllerEvent`. you can set a code and message that is returned by the ResourceController currently.
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php#L243

So support for setting a whole response could be added

**Comment by steffenbrem** [comment]
Yeah that could indeed simplify it! Then we would need a `ResourceControllerPreEvent` and `ResourceControllerPreEvent`? Or woud the `view` property be `null` when you dispatch the `pre_create` for example?

**Comment by steffenbrem** [comment]
But I don't think you have an easy way to override a `post_update` for all resources at the same time I guess. Since they happen based on the resource name, or is there an easy way around that that I don't know of.

**Comment by bendavies** [comment]
well, it's just an intial idea. I'll let the sylius guys flesh it out ;)
