### ISSUE TITLE
[Bug] Adding order item in admin bugs, EntityHiddenType removed

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#5231]
I noticed that you cannot add order items for an existing order, since it still uses the `entity_hidden` form type for it's `variant` field. 

![Bug](http://puu.sh/pnZo6/af156f9539.png)

I saw there are a lot of types now, `*_*_from_identifier` etc. not sure why they should be used for form types like `OrderItemType`, but shouldn't a simple `ResourceChoiceType` suffice here?

**Comment by pjedrzejewski** [comment]
If you want to modify an order, you should cancel it and create a new one for now.
