### ISSUE TITLE
[UiBundle] Coupling between UiBundle and currency bundle[

### ISSUE THREAD

**Issue by dantleech** [Sylius/Sylius#5236]
The Form theme has references to:
- A twig function defined in the CurrencyBundle (`sylius_currency_symbol`)
- The global variable `sylius_locale_name` (defined in the `LocaleBundle`)

This means that I need to reimplement the whole form theme if I want to use the UI bundle without these two bundles.

Could we separate the bundle-dependent blocks from the generic blocks?

Maybe we could put the
- generic blocks in the `UiBundle` (as now)
- the currency block in the `CurrencyBundle`
- the locale in `LocaleBundle`
- a Sylius admin theme (including all three) in `AdminBundle`?

**Comment by Zales0123** [comment]
I don't know is it a case to use our `UiBundle` in any other application. And in the not-so-long future, we would probably like to refactor our templates a lot (or even think about some proper front-end application). Feel free to open if you want to discuss a little bit more about that :)
