### ISSUE TITLE
Customer Addresses cascade delete?

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#5237]
This association between Addresses and Customers currently orphans and Address if the Customer is deleted:

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/doctrine/model/Address.orm.xml#L18

I'm probably going to change this in our project - unless anyone can thing of a good reason for it? I don't see the value in a customer address without it's customer?

**Comment by michalmarcinkowski** [comment]
The customer addresses should be removed together with customer. However the customer address is cloned to `Order` and the relation to customer probably stays. It is probably also the cause of duplicating the addresses after checkout and the reason we `set null` on delete. Of course it is a bug and should be resolved.

**Comment by peteward** [comment]
Hey @michalmarcinkowski,

I just checked in our app and customer relation is not cloned for order addresses, although not sure if this is something we changed.

**Comment by michalmarcinkowski** [comment]
On `master` it is in [AddressingStepType](https://github.com/Sylius/Sylius/blob/1b91d94b8aaa404a6e25d2113497f0405a7ca291/src/Sylius/Bundle/CoreBundle/Form/Type/Checkout/AddressingStepType.php#L53) :)

Cascade deleting will reveal the bug which will result in deleting address of all orders of this customer, so here after cloning we should `setCustomer(null)`.

**Comment by peteward** [comment]
hmm it does though on the very next line?

**Comment by michalmarcinkowski** [comment]
You're right! Don't know how I missed that 😞  Then I don't see any reason we shouldn't cascade delete addresses.

**Comment by peteward** [comment]
Another one that should cascade:

https://github.com/Sylius/Sylius/blob/f5d1b5f7fe845adfcc2fac485d6e19cd1708e03b/src/Sylius/Bundle/OrderBundle/Resources/config/doctrine/model/Comment.orm.xml#L39

Apologies I'm crazy busy to do a PR, just pointing these out then it's up to you...

**Comment by pjedrzejewski** [comment]
@peteward No worries, we will take care of that, thanks for the pointers! :)

**Comment by michalmarcinkowski** [comment]
Already fixed.
