### ISSUE TITLE
[ResourceBundle] MappedSuperClassSubscriber, why Sylius class only ?

### ISSUE THREAD

**Issue by alx-bongard** [Sylius/Sylius#5241]
Hi all and congratulation for your good work,

I use SyliusResourceBundle in `0.18` and i have this error =>

`MappingException in MappingException.php line 566:
It is illegal to put an inverse side one-to-many or many-to-many association on mapped superclass ...`

In my case i work on clean code strategy, so i use `mapped-superclass` for clean Model and `entity` for other part of Model.

In  [ORMMappedSuperClassSubscriber.php](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/EventListener/ORMMappedSuperClassSubscriber.php) one check is `isSyliusClass` for set or unset association mapping.

My mapped superclass is not a Sylius mapped supperclass, so if I comment this check my mapped superclass and my entity work fine. I d'ont understand why this check. Can you explain me, please.

**Comment by okwinza** [comment]
Initially it was done in #5075 to fix #5040 but it looks like there are still some edge-cases like yours left behind.

I assume #5233 should fix your issue.

**Comment by alx-bongard** [comment]
Thanks @okwinza, effectually #5233 fix my issue. I wait merge.
