### ISSUE TITLE
[Resource] Do not check for permission by default

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#5261]
We should configure ``_sylius: permission:`` setting for all admin routes (and generate it for the ones, which are generated automatically) and make it ``false`` by default. It is really annoying to disable permissions for shop routes. See #5260.

**Comment by inssein** [comment]
Iv'e got this most of the way (adjusted RequestConfiguration and the admin routes), but I cannot figure out how to get the generated routes to not check for permission. Any pointers?

**Comment by pjedrzejewski** [comment]
Implemented in #5279. Community FTW!
