### ISSUE TITLE
[Checkout] ProcessValidatorException when navigating back from payment screen

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#5264]
When you place an order and are on the payment screen (let's say a Paypal screen) and you then press the back button to navigate back, you will get a `ProcessValidatorException`.  Wouldn't it be better to make this transition nicer? A lot of customers just press the back button instead of cancelling the payment from within Paypal itself. It is a bit harsh to instantly display this error.

Should we maybe redirect them back to the cart or maybe back to just the `finalize` step? How do you guys solve this problem?

**Comment by pjedrzejewski** [comment]
This will be solved with the new checkout in ShopBundle, which goes outside of checkout process when order is confirmed (last step) and paying for it is a completely separate action, which you can invoke from thank you page, my account, send a link in e-mail or whatever.

That being said, I am pretty sure it should be the behavior of current checkout in WebBundle too, you should just configure a different return url for PayPal? To go back to order pay page and not a checkout step?

**Comment by steffenbrem** [comment]
I am sorry if I was unclear, but I meant when you press the back button in the browser, not the "cancel" button on the payment screen, which would indeed take you to the return url. I see that a lot of my customers are simply using the browser history to go back to cancel a payment, and when you do that action it goes into a 500 error with that exception. If the new `ShopBundle` fixes this it would be nice, but I think it may be an issue with the Flow component. Haven't had time to really look into that issue yet.

**Comment by peteward** [comment]
We had the same issues and rewrote various aspects of the Process component to make it more flexible for the checkout use-case

**Comment by michalmarcinkowski** [comment]
Already fixed in #5956 and #5945.
