### ISSUE TITLE
[RFC] Single-page checkout feature 

### ISSUE THREAD

**Issue by aramalipoor** [Sylius/Sylius#5288]
Hey guys,

A few of our clients requested us this feature, ability to have a single-page checkout so that visitor can quickly place their orders.

As far as I know this is not an easy task and should be done is Sylius core, or at least with close collaboration with you guys.

So how do you think is safest and most stable way to achieve this, if even possible? Where should we start from? Is it something that's possible to do in v1.0?

**Comment by inssein** [comment]
I would love to hear the opinions on this as well. If we can put a plan together I can help with the development.

**Comment by okwinza** [comment]
The only more or less clean solution i can think of right now is to use ajax to load checkout steps on demand and somehow track current state and available transitions client-side.

This feature is quite tricky as it tends to easily turn into mess if poorly designed(hello prestashop).

**Comment by psihius** [comment]
I'd say client is just asking for trouble.
All experience points to the fact that you have to split it into steps, otherwise people just are unable to complete a checkout. Active client experience even, redoing one project majorly because of this - previous developers screwed royally on that part.

**Comment by pjedrzejewski** [comment]
I close this one, because #1685 has more infos. :)
