### ISSUE TITLE
Overring template does not work properly

### ISSUE THREAD

**Issue by Ivan0905** [Sylius/Sylius#5290]
Hi, i am attempting to override the default template.

File location: src/App/WebBundle/Resources/views/Frontend/layout.html.twig

src/App/WebBundle/AppWebBundle.php contains:

    public function getParent()
    {
        return 'SyliusWebBundle';
    }

I am running on "^0.18@dev".

You should edit the youtube tutorial or remove it (Getting Started), since it does not work.

**Comment by okwinza** [comment]
Hi @Ivan0905, regarding youtube tutorials - i'm afraid they're not official so it's hard to do something about it except waiting for a new ones :)

In my current project i use exact the same approach on overriding templates and it works just fine.
Can you post your AppKernel.php? Make sure your WeBundle is loading last.

**Comment by stiffroy** [comment]
Hi @Ivan0905  I would recommend not to override the web bundle with a app bundle rather override the web bundle templates in the theme. Before Sylius v 0.16 I did it in the way you are doing. I did also follow the youtube tutorial that time. But I would mention that many things have changed in Sylius at present. They have the new themes bundle and I think we should use it for making life simple. Though there are some problem in loading the translations in the theme (check issue #5289 for it) I think it will be solved very soon.

The positive point of using the theme over a bundle is:
1. you can separate the view completely from the logic
2. you can override multiple bundle templates within a single theme (like web bundle, shipping bundle, core bundle, search bundle, etc)

You can check my folder structure for this:
<img width="273" alt="screen shot 2016-06-21 at 22 43 37" src="https://cloud.githubusercontent.com/assets/13282223/16246027/b2bab15e-3803-11e6-81f4-3624e82c0e42.png">

You can get the know-how about the theme bundle here:
http://docs.sylius.org/en/latest/bundles/SyliusThemeBundle/index.html
