### ISSUE TITLE
[Product][Order] Revert and Restore action are missing

### ISSUE THREAD

**Issue by Niiko** [Sylius/Sylius#5320]
Hi,

maybe i'm missing something, but as mentionned in #3762 revertAction and restoreAction do not exists anymore but still in routing.yml

- Order revertAction
- Product revertAction
- Product restoreAction

**Comment by pjedrzejewski** [comment]
Good catch! These should be removed from the routing and UI if exist anywhere.

**Comment by Niiko** [comment]
Ok, will do it.
