### ISSUE TITLE
Dashboard report error

### ISSUE THREAD

**Issue by ibasaw** [Sylius/Sylius#5341]
hi,

on the file Dashboard/main.html.twig, i had changed the line 25 by this

    {{ render(controller('sylius.controller.report:embedAction', {'report': 'salestotal2016'})) }}

I got a report in my DB and doctrine found it by the query

    SELECT t0.name AS name1, t0.description AS description2, t0.code AS code3, t0.renderer AS renderer4, t0.renderer_configuration AS renderer_configuration5, t0.data_fetcher AS data_fetcher6, t0.data_fetcher_configuration AS data_fetcher_configuration7, t0.id AS id8 FROM sylius_report t0 WHERE t0.code = 'salestotal2016' LIMIT 1;

the phpmyadmin result:

```
    Sales Total
Sales total 2016
salestotal2016
sylius_renderer_chart
a:2:{s:4:"type";s:3:"bar";s:8:"template";s:42:"Syl...
sylius_data_fetcher_sales_total
a:4:{s:5:"start";O:8:"DateTime":3:{s:4:"date";s:26...
1
```

but got this error on dashboard now:

`An exception has been thrown during the rendering of a template ("Notice: Undefined index: end") in SyliusWebBundle:Backend/Dashboard:main.html.twig at line 25.`

What is my error ? i only changed the value ReportCode by the code of my report: salestotal2016

**Comment by Niiko** [comment]
Have you 'end' information in column : data_fetcher_configuration ? I can see you have "start"

```sql
a:3:{s:5:"start";O:8:"DateTime":3:{s:4:"date";s:26:"2011-01-01 00:00:00.000000";s:13:"timezone_type";i:3;s:8:"timezone";s:13:"Europe/Berlin";}s:3:"end";O:8:"DateTime":3:{s:4:"date";s:26:"2011-01-01 00:00:00.000000";s:13:"timezone_type";i:3;s:8:"timezone";s:13:"Europe/Berlin";}s:7:"country";s:5:"WORLD";}
```

**Comment by ibasaw** [comment]
here mine

    a:4:{s:5:"start";O:8:"DateTime":3:{s:4:"date";s:26:"2016-01-01 00:00:00.000000";s:13:"timezone_type";i:3;s:8:"timezone";s:12:"Europe/Paris";}s:3:"end";O:8:"DateTime":3:{s:4:"date";s:26:"2016-12-31 00:00:00.000000";s:13:"timezone_type";i:3;s:8:"timezone";s:12:"Europe/Paris";}s:6:"period";s:3:"day";s:13:"empty_records";b:0;}

**Comment by Niiko** [comment]
I have another problem, because of postgresql usage...

```
An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT DATE(o.completed_at) as date, TRUNCATE(SUM(o.total * o.exchange_rate)/ 100,2) as "total sum " FROM sylius_order o WHERE (o.completed_at >= ?) AND (o.completed_at <= ?) GROUP BY date(date) ORDER BY date(date) ASC' with params ["2016-01-01 00:00:00", "2016-12-31 23:59:59"]:

SQLSTATE[42883]: Undefined function: 7 ERREUR: la fonction truncate(numeric, integer) n'existe pas
LINE 1: SELECT DATE(o.completed_at) as date, TRUNCATE(SUM(o.total * ...
```

But is your report working correctly in report  detail page ?

**Comment by ibasaw** [comment]
![report](https://cloud.githubusercontent.com/assets/313704/16310212/45c6f70e-3931-11e6-9c74-2579a69253ee.jpg)

yes, i got results

**Comment by Niiko** [comment]
Ok, i think that's it : 

On dashboard, we have : 
```twig
 {{ render(controller('sylius.controller.report:embedAction', {'report': report})) }}
```
And on report show we have
```twig
 {{ render(controller('sylius.controller.report:embedAction', {'report': report, 'configuration' : configuration})) }}
```

So, "just" need to get configuration from report if no configuration provided in request
