### ISSUE TITLE
[Promotion] PromotionApplicator needs to consider eligibility of filters 

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#5346]
`PromotionApplicator`:

```
    public function apply(PromotionSubjectInterface $subject, PromotionInterface $promotion)
    {
        foreach ($promotion->getActions() as $action) {
            $this->registry
                ->get($action->getType())
                ->execute($subject, $action->getConfiguration(), $promotion)
            ;
        }

        $subject->addPromotion($promotion);
    }

```

`UnitFixedDiscountAction`:

```
    public function execute(PromotionSubjectInterface $subject, array $configuration, PromotionInterface $promotion)
    {
        if (!$subject instanceof OrderInterface) {
            throw new UnexpectedTypeException($subject, OrderInterface::class);
        }

        if (0 === $configuration['amount']) {
            return;
        }

        $filteredItems = $this->priceRangeFilter->filter($subject->getItems()->toArray(), $configuration);
        $filteredItems = $this->taxonFilter->filter($filteredItems, $configuration);

        foreach ($filteredItems as $item) {
            $this->setUnitsAdjustments($item, $configuration['amount'], $promotion);
        }
    }
```

If the filters filter out all items then no adjustments are created which is good, but there's no indication back to the processor that this action effectively did not apply. `$subject->addPromotion($promotion);` is done regardless of any filtering.

At least 1 action needs to have been applied for this promotion to successfully be applied.

**Comment by pjedrzejewski** [comment]
I remember we have discussed it internally and was sure that this is covered. That being said, we will check it, thanks for report! /cc @michalmarcinkowski @Zales0123

**Comment by peteward** [comment]
I'm pretty sure it's not covered, but I will be working on this over the weekend so I will confirm for sure.

**Comment by peteward** [comment]
confirmed.

The obvious approaches would be for actions to either throw an exception if they're not applied or return a boolean to indicate if they were applied. Either could also be used for edge cases such as an amount discount of 0 which effectively does nothing anyway.

The PromotionApplicator will then only add the Promotion to the Order if at least one of it's actions are successful.

This is the approach I'm going to take in our project anyway. 

I also found it surprisingly easy to add Filters to the Item-based actions forms. It didn't take long at all so I suggest you look at doing this for 1.0 because it does make promotions a lot more usable - especially since you've done most of the hard work already.

**Comment by peteward** [comment]
The problem is in probably every promotion action, e.g. 0`FixedDiscountAction`:

```
    public function execute(PromotionSubjectInterface $subject, array $configuration, PromotionInterface $promotion)
    {
        if (!$this->isSubjectValid($subject)) {
            return;
        }

```

It will return early if the subject is invalid but as there's no indication to the PromotionApplicator so it will still always add this promotion to the Order.

**Comment by michalmarcinkowski** [comment]
Fixed https://github.com/Sylius/Sylius/pull/6933 🎉
