### ISSUE TITLE
[Promotions] Usage is confusing

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#5354]
This represents the 'total number of times this promotion can be used', which seems like a less-common use case than what I confused it with - 'how many times a single customer can use this promotion'.

1). I think a rule checker should be added for the latter.
2). You should clarify the naming of 'Usage' because I think a lot of people would take my understanding of usage and expect it to be on a per-customer basis.

**Comment by peteward** [comment]
unfortunately you can't write a rule checker that does any checking based on the promotion, because you can't get access to it inside the checker:

```
interface RuleCheckerInterface
{
    /**
     * @param PromotionSubjectInterface $subject
     * @param array                     $configuration
     *
     * @return bool
     */
    public function isEligible(PromotionSubjectInterface $subject, array $configuration);

    /**
     * @return string
     */
    public function getConfigurationFormType();
}
```

`isEligible()` passes an array, not the `Rule` object, so you can't get at the original `Promotion`.

**Comment by michalmarcinkowski** [comment]
This has been clarified in the docs.
