### ISSUE TITLE
[Order] StateResolver to use state machine?

### ISSUE THREAD

**Issue by dantleech** [Sylius/Sylius#5366]
The StateResolver changes the state of the order directly - this means that the state machine is not used, and no event is fired which could be used to notify something that, f.e., the payment has been completed.

Should the SM be used here? If not - what would be the best way to trigger some action when the order has been paid for?

**Comment by pjedrzejewski** [comment]
This is absolutely wrong and we will be changing that soon. Yes, it should use state machine. :)

**Comment by dantleech** [comment]
@pjedrzejewski do you think this will make it in to 0.19 ?

**Comment by dantleech** [comment]
Not really sure why I tweeted this question, but: is this a big task? Would I be stepping on anybodies toes if I took it on?

**Comment by okwinza** [comment]
@pjedrzejewski this looks critical to me. Would love to see it fixed b4 tag.

**Comment by dantleech** [comment]
I will make a PR shortly

**Comment by dantleech** [comment]
See #5377

**Comment by michalmarcinkowski** [comment]
Already fixed.
