### ISSUE TITLE
findOneByName inconsistent behaviour

### ISSUE THREAD

**Issue by vcraescu** [Sylius/Sylius#5374]
For all translatable entities `findOneByName` implementation from the repo makes use of `getOneOrNullResult`() method which will throw an exception when more than one record is returned.
On all the other entity (non-translatable) repositories `findOneByName` is implemented using `findOneBy([...])` which does not throw any exception at all.

`findOneByName` should have same behaviour across all the entities otherwise it will lead to errors and confusion.
`getOneOrNullResult` should be replaced by `getResult()` and just first record fetched for all translatable entities. This is the default behaviour of `findOneBy` method from `EntityRepository` and should be maintained.

Thanks!

**Comment by gabiudrescu** [comment]
@pjedrzejewski are you open to PR for these issues?

**Comment by michalmarcinkowski** [comment]
Fixed in #6172
