### ISSUE TITLE
[Checkout] Accessing /checkout/addressing directly (or through behat) triggers a 400 (ProcessValidatorException)

### ISSUE THREAD

**Issue by ylastapis** [Sylius/Sylius#5376]
in vendor/sylius/sylius/src/Sylius/Bundle/FlowBundle/Validator/ProcessValidator.php at line 124

Maybe linked to https://github.com/Sylius/Sylius/issues/5264

**Comment by pjedrzejewski** [comment]
Could you give us steps to reproduce, please? Thank you!

**Comment by ylastapis** [comment]
Hi @pjedrzejewski 

I just fetched the last dev-master branch on sylius, and accessed /checkout/addressing.
I'm supposed to get a 404 right ?

**Comment by michalmarcinkowski** [comment]
Already fixed in #5956 and #5945.
