### ISSUE TITLE
[Order] Abandoning orders / Payment failure

### ISSUE THREAD

**Issue by dantleech** [Sylius/Sylius#5382]
This is potentially just a question:

- What happens when payment fails and the user goes away and loses their session?

I would expect the order to be abandoned/released(?) by something like [ExpiredOrdersReleaser](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Releaser/ExpiredOrdersReleaser.php). This expires orders based on the state `pending`.

- Will failed payments be abandoned?

In dev-master it seems my orders stay in the `new` state and never reach `pending` (will need to verify this).

**Comment by antonioperic** [comment]
ping @pjedrzejewski @michalmarcinkowski

**Comment by dantleech** [comment]
@pjedrzejewski @kayue @foopang I can see that the order purger expires only orders in `pending` state - but my orders only seem to remain in `new` state until `completed`. Is this expected behavior atm?

**Comment by michalmarcinkowski** [comment]
`ExpiredOrdersReleaser` has been removed, now you can configure the time after each the orders are automatically cancelled by `CancelUnpaidOrdersCommand`.
