### ISSUE TITLE
[RFC] Naming of subject-aware classes like Option, Attribute or Association

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#5384]
Right now, we have:
 - `Sylius\Component\Product\Model\Archetype`
 - `Sylius\Component\Product\Model\Option`
 - `Sylius\Component\Product\Model\Variant`

but:
 - `Sylius\Component\Product\Model\ProductAssociation`

`Sylius\Component\Product\Model\Variant`, but `Sylius\Component\Product\Factory\ProductVariantFactory`.

`Sylius\Bundle\ProductBundle\Form\EventSubscriber\ProductOptionFieldSubscriber` but `Sylius\Bundle\ProductBundle\EventListener\ArchetypeUpdateListener`.

There are a lot inconsistencies for these kind of subject-aware classes and it's definitely the issue we must cope with before v1.0, because it takes way too much time to figure out what is the naming used in some cases.

In my opinion, we should prefix all subject-aware classes with their subject name, eg. there's `Sylius\Component\Variation\Model\Variant` that does not know anything about its subject, but `Sylius\Component\Product\Model\Variant` does, so it should be renamed to `Sylius\Component\Product\Model\ProductVariant`.

What do you think? :camel:

**Comment by peteward** [comment]
yes definitely 👍

**Comment by pamil** [comment]
Moreover, we have `Sylius\Component\Product\Model\OptionInterface` without any additional behaviour (marker interface), but `Sylius\Component\Product\Model\Product` does not enforce its options to implement it anyway. We end up using the one from Variation component and Product component interchangeably.

One more argument for prefixing is the situation, when we have two subjects with options and we want to overwrite them in CoreBundle - a conflict arises. We haven't encountered it yet, nevertheless there is general variant `Sylius\Component\Variation\Model\Variant`, product aware `Sylius\Component\Product\Model\Variant` and another one product aware `Sylius\Component\Core\Model\ProductVariant` with its name prefixed :tada:

**Comment by pjedrzejewski** [comment]
👍

**Comment by pamil** [comment]
We will probably need a list of models to change:
- [x] Product - Option (#6150)
- [x] Product - Variant (#6150)
- [ ] Promotion - Coupon (#6273)
- [ ] Promotion - Rule
- [ ] Promotion - Action

**Comment by pamil** [comment]
Closing this one, extracted the rest of renaming changes as sub-issues.
