### ISSUE TITLE
sylius:theme:assets:install not copying assets

### ISSUE THREAD

**Issue by moonraking** [Sylius/Sylius#5392]
I am not sure this is a bug or a support request.
I have started to make a them in app/themes as in the docs.  I have got the system overriding templates and I think it is a really clever way of doing it.

Now I would like the assets to install from app/themes/MyTheme/public sylius:theme:assets:install doesn't seem to do this. I would have expected it to.

Am I meant to put all assets into a bundle, or can I just have generic assets for the theme.  I feel I would like the sylius:theme:assets:install to copy/symlink app/themes/MyTheme/public.

**Comment by moonraking** [comment]
So It would seem that the sylius:theme:assets:install does not copy/symlink app/themes/MyTheme/public to web/bundles/_themes/my-theme/.

Also app/themes/MyTheme/public only copies/symlinks from app/themes/MyTheme/MyBundle/Resources/public if there is a src/MyBundle/Resources/public

Maybe it should be a feature of sylius:theme:assets:install to copy/symlink app/themes/MyTheme/public to web/bundles/_themes/my-theme/ as fonts, icons etc maybe part of a theme and not necessarily part of a functional bundle.

Or is the recommended usage that one creates app/themes/MyTheme/SyliusWebBundle/Resources/public and distributes the theme resources in that way.  (this assumes that the author has SyliusWebBundle installed).

shane

**Comment by jupiter01** [comment]
I just ran into this problem when checking out sylius.  Placed assests in mytheme/public, however they seem to be m.i.a. Cleared cache etc. Any advice.

**Comment by jupiter01** [comment]
Maybe I have the wrong idea on how this works, I thought by placing logo.png in mytheme/public it would replace the logo of the enabled theme.

**Comment by zacbrac** [comment]
How I got this working was by placing it in `theme_dirAppBundle/public/shop/img`

**Comment by markmeson** [comment]
> How I got this working was by placing it in `theme_dir/AppBundle/public/shop/img`

I tried this also but it has no effect for me. I literally placed logo.png in every possible location I could think of but none works. (the one referred to by SyliusShopBundle's _header.html.twig)
` 4             <a href="{{ path('sylius_shop_homepage') }}"><img src="{{ asset('assets/shop/img/logo.png') }}" alt="Sylius logo" class="ui     small image" /></a>`

**Comment by csgrant83** [comment]
Wanted to add that I am also experiencing this issue, and I have tried `/AppBundle/public`
`/AppBundle/public/shop` and `/AppBundle/public/shop/img` and `/AppBundle/public/assets/shop/img`
The only thing that works is replacing the default files in the root public folder.

**Comment by teratux** [comment]
Stumbling on to this, I can provide some more info.  In the project I have this only works when in DEV mode, when running the sylius:theme:assets:install command I'm getting a correct _themes directory in public.  When I switch to PROD this doesn't work. On sylius 1.5.2.  This is the only solution I have for the moment, anybody else with this?
