### ISSUE TITLE
[ResourceBundle] default_page_size param unused/misleading

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#5399]
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/DependencyInjection/Configuration.php#L148

You would assume changing this would alter the default max per page but it doesn't, you have to change `paginate` instead. This parameter currently appears to be unused.

I think this param should either be removed or better, rework so that it is used instead of `paginate` which doesn't really describe that it's the number of items to paginate by.

**Comment by mvar** [comment]
`allowed_paginate` doesn't seem to be used either.

**Comment by pjurasek** [comment]
I run in the same issue in few days ago as @peteward. I assume the same behavior after set `default_page_size` that the max per page would alter with that value. The term `paginate` is a bit misleading, that would set the max per page in pagination.
