### ISSUE TITLE
MoneyHelper locale

### ISSUE THREAD

**Issue by vcraescu** [Sylius/Sylius#5400]
[MoneyHelper](https://github.com/Sylius/Sylius/blob/0d3c0c8ce6703188249efb8358fa897109b7fac6/src/Sylius/Bundle/CoreBundle/Templating/Helper/MoneyHelper.php)

Any reason why the default value for the locale parameter is `$this->localeContext->getDefaultLocale()` but not `$this->localeContext->getCurrentLocale()`?

Don't see any reason why I'm supposed to do this in template:
`12345|sylius_money(null, app.request.locale)` 
Current locale should be used instead by default.

**Comment by pamil** [comment]
Should be solved by now, Core's `MoneyHelper` uses `LocaleContext` to get current locale code.
