### ISSUE TITLE
[RFC] Usage of Doctrine naming strategy

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#5408]
Related: https://github.com/Sylius/Sylius/pull/5395#discussion_r69283483

We already have some conventions:
 - model class `Sylius\...\Model\FooBar` has table name `sylius_foo_bar`
 - model property `Model::$fooBar` has column name `foo_bar`

We may enforce them with [Doctrine naming strategy](http://doctrine-orm.readthedocs.io/projects/doctrine-orm/en/latest/reference/namingstrategy.html), remove all existing hardcoded table names / column names and just forget about it.

**Comment by pamil** [comment]
There's an another issue for that: https://github.com/Sylius/Sylius/issues/1837, but it's quite old.

**Comment by pamil** [comment]
Last call before alpha - should we enforce the naming convention it?

**Comment by pamil** [comment]
Anyone?

**Comment by pjedrzejewski** [comment]
I'd prefer to keep them in the files. It is not much overhead, we have not touched them for a long time and this approach is mostly known for Symfony devs. Naming strategy is something that not everyone is aware of.

**Comment by pamil** [comment]
Agreed, we don't know how this will affect custom entites too.
