### ISSUE TITLE
Customer registration date format in admin

### ISSUE THREAD

**Issue by stiffroy** [Sylius/Sylius#5411]
In the administration panel ```http://the.domain.name/app_dev.php/administration/customers/```
The customer registration date format is using a wrong twig filter ```filter_date()```.
```
src/Sylius/Bundle/WebBundle/Resources/views/Backend/Customer/macros.html.twig      line 29
```
I did not get proper time to dig into the function but if the normal ```date()``` function is used which is a core filter from Twig, the date is formatted properly. I have made the changes but cannot create a pull request.

@pjedrzejewski Can you please change the code or tell me how can I create a pull request?

**Comment by michalmarcinkowski** [comment]
Fixed on master.
