### ISSUE TITLE
[ Suggestion ] Date format

### ISSUE THREAD

**Issue by jvahldick** [Sylius/Sylius#543]
It would be possible to add something like that?
http://twig.sensiolabs.org/doc/extensions/intl.html

It is interesting that the date format was displayed according to the country.

**Comment by axelvnk** [comment]
Since you have to pass a locale to the localizeddate filter, should we maybe set up a global variable to get the users locale from the request?

Another option is to extend the filter and set the locale ourselves so we don't have all this clutter in the templates.

**Comment by pjedrzejewski** [comment]
Ref. #2275.

**Comment by aramalipoor** [comment]
Actually Ref. #3232
