### ISSUE TITLE
[Checkout] Checkout step directly back link

### ISSUE THREAD

**Issue by KannipaB** [Sylius/Sylius#5431]
In each checkout step process of Sylius e-comerce I have menu like this:

![screen shot 2016-07-05 at 7 04 58 pm](https://cloud.githubusercontent.com/assets/12539405/16584689/7c8c3f50-42e7-11e6-9551-a679165b6419.png)

Now I can handle previous step by back button, But if I want to go back to the first step directly and click again to latest step by link. Is there any way to do it? 

Thank you for your answer :)

**Comment by videni** [comment]
I don't think add a go back link can stop customer from checking the same step again,  what if a customer goes back by browser `go back` menu,   this still will throw the [error](https://github.com/Sylius/Sylius/issues/5336) addressed in this link

**Comment by michalmarcinkowski** [comment]
This feature is already implemented #5956.
