### ISSUE TITLE
set default permission as true for  route as before

### ISSUE THREAD

**Issue by videni** [Sylius/Sylius#5432]
permission is a serious problem, I  suggest set the default permission as true , not false. 

RequestConfiguration.php

```
 /**
     * @return bool
     */
    public function hasPermission()
    {
        return false !== $this->parameters->get('permission', false); // change to true instead 
    }
```

if developers don't want to check permission for a route , he should set permission as true. this restriction can force  developer to understand what he is doing , I remember  , this is default implementation before ,  but it  is change to false currently why?

**Comment by michalmarcinkowski** [comment]
Not valid anymore.
