### ISSUE TITLE
[OSX] Whats best server to install for dev purposes. On XAMPP clean  sylius very slow front rendering.

### ISSUE THREAD

**Issue by Mr-Negative** [Sylius/Sylius#5437]
Installed locally using xampp. Rendering homepage on dev mode + sylius demo data = rendering second time 1241 ms (yellow)  (first much much slower). Is it normal? How to speed it up /can I? I understand that it would be a lot faster without dev mode, but i think its maybe too much as it is?  My xampp doesn't have APC, but it has OPcache isn't it? Doesn't it work similar way?

**Comment by okwinza** [comment]
>xampp
You're using Windows aren't you?

On my dev server(Debian, php7) it takes about 300ms to load a category page with more than 1k products in it including brands block and search filters. In prod mode it keeps running under 180ms avg and there is still room for further optimizations.

So open up your profiler and see what exactly slows the process. But i bet it's twig -- in dev mode it's recompiles every template on every request.

**Comment by Mr-Negative** [comment]
No im on OSX, Yosemite, pretty powerfull (8gb 2,5 GHz Intel Core i5), and im testing it without any other software working in background. But it's php 5.6 would it made so much difference, Becouse i tried to install  xampp 7.0 but it had problems with php-int so i abandoned it But it works same in builded inside server. There is some  missing  translate messages could it be it?
![zrzut ekranu 2016-07-05 o 20 16 07](https://cloud.githubusercontent.com/assets/4626156/16595065/9b1d882e-42ed-11e6-8cfa-25ac1391a2cc.png)
And yes twig is slowest (homepage.main and layout about 900ms) but i think its very slow. I have some symfony experience and it wasn't so slow (but yeah i understand that sylius is powerfull etc)

**Comment by okwinza** [comment]
Well it's more about your environment rather than Sylius itself.
Just checked my php 5.6 suite - 350ms devmode avg.

And yeah, xampp sucks.

**Comment by Mr-Negative** [comment]
I'm new in osx, i moved from windows so i knew XAMPP and i saw that there is osx version so i'm using it. Is there better alternative? I'm open to changing if it would be way faster.  Server (7.0 , (changable with 5,6 would be nice addition) + Mysql + phpmyadmin +  php-intl/pecl

**Comment by dkisselev** [comment]
Check if you have xdebug enabled, it significantly slows down symfony's render times. You shouldn't be getting over 1000ms on an OSX machine even with xdebug enabled, but it might help.

**Comment by Zales0123** [comment]
@Mr-Negative check out [installation docs](http://docs.sylius.org/en/latest/book/installation.html#accessing-the-shop) that has been merged recently - we strongly recommend to use PHP7 and build-in web server. I remember it was a huge speed change for comparing to PHP5.6 and Apache (I haven't worked with XAMPP for years, but I'm pretty sure it is even slower ;))

**Comment by Mr-Negative** [comment]
@dkisselev it's disabled, @Zales0123  Well, i can't see it in this doc, but i'm pretty blind ;-). BUT, i will try to install 7 if its better.  But i have question. When i use builin server now, it renders pretty much the same, not any significant improvement (if any), but it is using same version of php as xampp. So my question is, whats the php.ini of this build-in web server, and second - is it possible that this missing messages actually slow it? Becouse i use symfony in other projects, (but without sylius) and this errors can slow down a lot,

**Comment by lchrusciel** [comment]
So maybe it would be worthy to work on a MAMP, and install everything with homebrew? It should not be as slow as you describes it.

**Comment by Mr-Negative** [comment]
ok. thanks guys.

**Comment by Mr-Negative** [comment]
So, i'm writing it for sake of other who will be searching maybe. 
I installed 7.0 version with homebrew
`brew php70-intl`
and
`brew php70-opcache`
And im using builded server and now its waaaaaaay faster. First loading multiple times faster, next one about one half/one third.
