### ISSUE TITLE
[bug] old Administrator / editing cms pages / editing menus

### ISSUE THREAD

**Issue by Mr-Negative** [Sylius/Sylius#5438]
Clean installation. Old Administator/
http://127.0.0.1:8000/app_dev.php/administration/content/static-contents//cms/pages/terms-of-service/edit 

> Impossible to access an attribute ("vars") on a null variable in SyliusWebBundle:Backend/Content/StaticContent:_form.html.twig at line 7
> 500 Internal Server Error - Twig_Error_Runtime

In menus (first click) and blocks (selecting blocks/creating new)
http://127.0.0.1:8000/app_dev.php/administration/content/menus/

> The parameter "sylius.phpcr_odm.repository.class" must be defined.
> 500 Internal Server Error - InvalidArgumentException

Or it is becouse of abandoning old administator and moving to new admin?

**Comment by DanPhyxius** [comment]
Same here, what is this new admin? 

Where can i find it? We've deploy a new application for a customer but this bug is blocking for us. :)

Thank you for any response!

**Comment by michalmarcinkowski** [comment]
The old admin is deprecated and not supported anymore. It is already removed on master.

Try adding:
```
sylius_resource:
    drivers:
        - doctrine/orm
        - doctrine/phpcr-odm
```

**Comment by DanPhyxius** [comment]
Hi @michalmarcinkowski, thank you for your response.

What do you mean with "old admin"? 

What is the admin in the sylius demo online? 

P.S.: What is the Sylius version of online demo? It looks like different from 1.0.0-dev.

Thank you for your help! :)

**Comment by pjedrzejewski** [comment]
This won't be supported anymore, but you can quite easily migrate this to new admin on your own. Also, the demo will be updated soon. :)

**Comment by DanPhyxius** [comment]
Thank you @pjedrzejewski for your answer! :)

Could you give me an url for setup the new admin?
I can see the /admin path on my installation but i can't get js/app.js and css files. 
I tried to do "npm install" and "gulp" on vendor/sylius/sylius but nothing happen.

Thank you,
Dan
