### ISSUE TITLE
[notbug/featureRequest?] sylius demo data can't be deleted, the product is in use. More info in error should be displayed.

### ISSUE THREAD

**Issue by Mr-Negative** [Sylius/Sylius#5439]
When i try to delete 

> Sticker "quidem"

or any other product installed via demo data from install script

> Error
> Cannot delete, the product is in use.

Shouldn't it be possible?

**Comment by okwinza** [comment]
In your case you have 3 options:
1) Find and delete every cart/order where this product is in
2) Disable the product
3) Don't install fixtures when asked.

**Comment by Mr-Negative** [comment]
Yeah i understand it and i'm ok with it ;-), but isn't it something to look in/ shouldn't i report it when i saw it? Is it bug or is it becouse of orders? Becouse if its becouse of orders then i think it should change error info to something more cleaner like? `Error
Cannot delete, the product is in use in order`

**Comment by okwinza** [comment]
@Mr-Negative you're right, it would be much more helpful if there was any pointer to a blocking entity.
