### ISSUE TITLE
[Order] Should sylius_order:number be nullable?

### ISSUE THREAD

**Issue by dantleech** [Sylius/Sylius#5445]
Currently the schema allows order number to be nullable. Should it be not-nullable?

```

MariaDB [sylius_loyalty_dev]> explain sylius_order;
+---------------------+---------------+------+-----+---------+----------------+
| Field               | Type          | Null | Key | Default | Extra          |
+---------------------+---------------+------+-----+---------+----------------+
| id                  | int(11)       | NO   | PRI | NULL    | auto_increment |
| ...                 | .......       | ..   | ... | ....    | .............. |
| number              | varchar(255)  | YES  | UNI | NULL    |                |
```

**Comment by pjedrzejewski** [comment]
It is also used for carts, which do not have numbers. So we either make it non nullable for Order component, and override it in Core/Cart or leave it this way. Thoughts?

**Comment by dantleech** [comment]
Ah I see, In that case, I guess the best solution would be to have some state specific validation. But I think in my case I am accidentally using a Cart instead of an Order. So happy to close this.

**Comment by dantleech** [comment]
r
