### ISSUE TITLE
How to extend Sylius?

### ISSUE THREAD

**Issue by skafandri** [Sylius/Sylius#5449]
I checked the excellent documentation on how to [customize Sylius](http://docs.sylius.org/en/latest/customization/model.html) and I found it very clear. If I understood well, I need to create an AppBundle. I have couple of questions.

- How do I require another bundle? Let's say RabbitMQBundle. If I require it in composer.json it will cause some really messy conflicts in composer.lock when I try to merge a newer version of Sylius.
- Updating tests for extended behaviours, I will make some changes to the Country so I will need to add/update tests in **tests/Controller/CountryApiTest.php** and **features/addressing**. Again this will cause hard merging time

Adding couple of bundles (and their required configurations), updating couple of dozens of features will make a potential merge to upgrade Sylius prohibitively hard.

Am I missing something? This is not the correct way to extend Sylius?

**Comment by pjedrzejewski** [comment]
@skafandri Thanks for the feedback! You should be using Sylius-Standard. :) 

@TheMadeleine I think we need to emphasize on using Sylius-Standard for projects a bit more in the docs. (maybe mention it in customization guide more)

**Comment by skafandri** [comment]
@pjedrzejewski Thanks! It makes much more sense now. I was indeed misled by the documentation (I assumed, and cloned sylius/sylius)
Looks much better now.

**Comment by TheMadeleine** [comment]
@skafandri https://github.com/Sylius/Sylius/pull/5414 here comes the proper documentation for the installation process :) :P finally.
