### ISSUE TITLE
[RFC] [Resource] Dispatch general events, not specific events.

### ISSUE THREAD

**Issue by dantleech** [Sylius/Sylius#5456]
Currently event names use runtime data such as "application name" and "metadata name".

For example:

```
sylius_product_pre_create
sylius_foobar_pre_create
```

This has (at least) three distinct disadvantages:
- We cannot define constants to refer to these events (unless in userland code). Any third-party event subscriber is at risk of the source event name being changed.
- Event names cannot be easily discovered.
- Very hard to make a subscriber that listens to ALL f.e. pre-create events from the resource controller[1]
  
  I would suggest simplifying the process, removing the resource-specific EventDispatcher and issuing events:

```
pre_create
post_create
show
... etc
```

This shifts the burden of responsibility for acting on events to the event listeners themselves (you could also create an event listener which emulates the current behavior).

The only argument I can currently see for this approach is a performance one, but performance impact would be imperceptible, and in anycase, this is not a performance critical path - and this same strategy is used by the Doctrine ORM where performance cost is much more valuable.

[1] My use case is to automatically set the parent on a PHPCR document from the request.

**Comment by pjedrzejewski** [comment]
How about having both?

**Comment by pamil** [comment]
@dantleech I came into your use case this week, why not set the parent during its creation in a factory (https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ContentBundle/Factory/StaticContentFactory.php)? Or am I missing some PHPCR insight?

**Comment by dantleech** [comment]
> How about having both?

We could dispatch the "old" events from an event subscriber listening to the new more general events maybe? Then they could either be deprecated or left as first-class citizens.

> I came into your use case this week,

I need access to the Request object, so the events here seem the best place (they have the request config as an argument).

Despite that it would be possible to inject the request stack to the factory, although that seems wrong, I did consider it - but ruled it out as a solution because I could not specify the [factory as a resource service](https://github.com/Sylius/Sylius/issues/5296). How did you accomplish it?

**Comment by dantleech** [comment]
@pamil also, are you aware of the [parent_path](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/Doctrine/DoctrinePHPCRDriver.php#L51) option on the resource PHPCR driver?

**Comment by pamil** [comment]
Yup, injecting a RequestStack instance into a factory does not feel good. I just decorated the factory provided by ResourceBundle by:
```xml
<service id="sylius.factory.static_content.parent_path" class="Sylius\Bundle\ContentBundle\Factory\StaticContentFactory" decorates="sylius.factory.static_content">
    <argument type="service" id="sylius.factory.static_content.parent_path.inner" />
    <argument type="service" id="doctrine_phpcr.odm.document_manager" />
    <argument>%cmf_content.persistence.phpcr.content_basepath%</argument>
</service>
```

Didn't know about this, I'll definitely take a look there and I'll probably remove these factories in favour of it.

**Comment by ste93cry** [comment]
I agree with @dantleech in not having a lot of events to subscribe of, but instead of having some well defined events and move the logic that checks the resource type into the event listener. This way there could be only one event listener that catches all events (now it's a mess because a tag should be added for each resource and each event)

**Comment by dantleech** [comment]
@pjedrzejewski what do you think?
