### ISSUE TITLE
Parallel item update with AJAX causing error for adjustment 

### ISSUE THREAD

**Issue by Pitoune** [Sylius/Sylius#5460]
When I do several update on cart items with AJAX call, the order is recalculated through OrderRecalculator. 
This cause trouble with the PromotionProcessor as it applies promotion for all AJAX call so I get some database issue: a duplicate entry for key order_item_unit_id in table sylius adjustment.

I hope I am understandable.

**Comment by Zales0123** [comment]
It's been a long time and a lot of things changed in Sylius :) Feel free to reopen this if needed, but I believe such a bug should not happen right now (we have loaders on forms). Thanks! 🚀
