### ISSUE TITLE
Route for updating custom SettingsSchema

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#5475]
I have created my own `AcmeSettingsSchema.php` and according to the docs, to update the values in the backend I can do :
 
    <a href="{{ path('sylius_settings_update', {'namespace': 'meta'}) }}">Edit SEO</a>

... with the custom namespace I have created (see http://docs.sylius.org/en/latest/bundles/SyliusSettingsBundle/editing_settings.html) but this doesn't seem to work anymore on the 0.18/0.19. What is the correct route / path now ? I have not found any hint in the code of SyliusSettingsBundle.

Thanks a lot !

**Comment by tchapi** [comment]
Well, I guess I can close this now since you remove the SettingsBundle from Sylius ... why ?

**Comment by michalmarcinkowski** [comment]
@tchapi SettingsBundle is not used by Sylius Core, but will remain in the repo and will be supported.
