### ISSUE TITLE
Data enabled default value is wrong

### ISSUE THREAD

**Issue by vcraescu** [Sylius/Sylius#5477]
[CoreContext.php](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Behat/CoreContext.php#L220)

> isset($data['enabled']) ? $data['enabled'] : true

should be

> isset($data['enabled']) ? $data['enabled'] : 'yes'

because at line 782 (same file) 

>  $user->setEnabled('yes' === $enabled);
 
Basically this makes all the users disabled by default.

**Comment by lchrusciel** [comment]
I would say, that `yes` is a wrong value. If we are working with boolean state of variable, we should use true/false. IMHO, a proper fix, should change [this line](https://github.com/vcraescu/Sylius/blob/231accb9ad2e11359084a7884db3d94c52e08a09/src/Sylius/Bundle/CoreBundle/Behat/CoreContext.php#L782) and all of others of `yes` occurrence. Nevertheless, AFAIK all of old Context class would be deleted in a nearest future.
