### ISSUE TITLE
[RFC] Introducing components

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#549]
Hey folks! This is a big one, so please fasten your seatbelts.

I'd like to extract everything not symfony-specific into standalone components.
I don't think I have to explain the idea, because it's exactly the same thing as with Symfony. Library + bundle, which is integration layer with the framework.

I'll start with 1 fun fact about this idea... I already did it, twice.

First, in quite early stages of development, when Sylius had much less features than now. I reverted this, because I had a feeling that the components were very, very small and simply not useful for anything else than Symfony2 bundles.

Second, it was not so long time ago, but before the reorganization of repositories on github. We had around ~20 (or even more) active bundles, so the change resulted in 40 repositories to maintain/fork/track issues and so on... it was a bit painful to manage, believe me.

With our current github structure and use of subtree split, it's super simple to do and manage. I created bash scripts for subtree splits and tagging releases, so it's just matter of adding new repos to the list.

Now, I want to do this third and last time. :)

**Pros & Why**...
- It always felt to me like the right and natural way to develop app, without coupling to the framework and generally, avoiding the strict coupling with anything whenever possible.
- Allows for wider adoption and more collaboration. This is the most important point for me. I've already heard few voices from the Laravel community about porting Sylius there. While my personal and professional choice is Symfony2, I don't see a reason why people could not benefit from our ideas/libraries using different frameworks. "It's an implementation details!" to quote two very smart guys.
- Most of the code used by developers will live in components, the bundles will be only for configuration and services definition, so there is no problem with remembering what comes from bundle and what from library.
- I dream about Drupal and Sylius integration. This should make it at least a bit simpler.
- I don't like where we're going with ResourceBundle (being central bundle for other ones, doing quite a lot more than 1 thing it was supposed to provide - resource management)
- Makes the bundles lighter and doing only what the should do.
- (good read) http://williamdurand.fr/2013/08/07/ddd-with-symfony2-folder-structure-and-code-first/
- (good read) http://richardmiller.co.uk/2013/06/18/symfony2-bundle-structure-bundles-as-integration-layers-for-libraries/

**Cons**...
- It means 2x more repositories and composer packages, but well, I'd say it's not a very big problem with our current github organization.
- It may look a bit more complex for newcomers, but when you get the idea, it can be simpler to learn, because you can dive in the components without the need to learn Symfony & Sylius all at once.
- Quite a lot of the Sylius "coolness" comes from the Symfony flexibility (tagged services, very good doctrine integration and so on), so I don't know how easy it will be to use our components with other frameworks. (because I have never used them, so this is just my little concern coming from lack of knowledge)

**Problems to tackle during the change**...

The extraction of components itself will be pretty simple, but there are some questions.
1. Where should we put the doctrine mappings? Libraries or bundles?
2. I'm on the edge with models. I'm pretty sure that we'll end up putting them in the components, but I'd like to hear your opinion. Models represent the business domain, so it does not feel entirely right to have them "so far away" from the application source code. (in the component) On the other hand, Sylius components would be slightly different (not in all, but most cases) from other php libraries, because they do not necessarily belong to low level (framework) like Finder or HttpKernel components from Symfony.
3. With this reorganization, I have this idea of simplifying the namespaces. I'm not entirely convinced yet, but what do you think about these proposals?

`Sylius\\Bundle\\FooBundle\\`
`Sylius\\Component\\Foo\\`

or

`Sylius\\FooBundle\\`
`Sylius\\Foo\\`

or leaving the component.

`Sylius\\FooBundle\\`
`Sylius\\Component\\Foo`

Reason is simple, `TaxationBundle` already contains the "bundle" suffix, so there will be no conflicts / confusion. And it makes things shorter.

What do you think?

/cc @weaverryan (we talked several times about it, I hope you're proud I finally wrote this RFC :D)

**Comment by mtpultz** [comment]
Hi, I've been looking at Sylius for e-commerce and wonder if it could be pulled into Laravel.  I've been reading through a couple different discussions regarding this, but I've come to the end here, and the last comment is almost 2 years ago.  Is Sylius available for use as a package(s) for Laravel 5?  Or did this lose momentum?

**Comment by pjedrzejewski** [comment]
@mtpultz Hey Martin! Sylius is available as standalone PHP packages. Everything that is not coupled to Symfony goes into components. Have a look at  the recently updated components docs - http://docs.sylius.org/en/latest/components/index.html It should be helpful in getting an idea how you can use them in laravel app. :)

**Comment by mtpultz** [comment]
Thanks @pjedrzejewski, that's great.  Just noticed you use Doctrine.  I think that might prevent the use of Laravel's ORM - Eloquent.  Though I'm not sure of that yet.  Is the admin UI available for use outside of Sylius?  Not familiar with Symphony 2, but if this works with Eloquent.  I'll take the admin UI and make it into Laravel Blade templates and through them into a PR.

**Comment by pjedrzejewski** [comment]
@mtpultz In components we only require interfaces from Doctrine and currently it is only one interface, ObjectManager. We will soon replace that with much simpler interface of our own, so you will be able to fully decouple from Doctrine. Anyway, we use Repository pattern and I believe you could still create Repository classes which simply use Eloquent inside, what do you think?

**Comment by rickmills** [comment]
"We will soon replace that with much simpler interface of our own, so you will be able to fully decouple from Doctrine."

Was this ever completed @pjedrzejewski ? Looking into the feasibility of using Sylius with Laravel and really dont want to have to bring Doctrine in.

**Comment by pjedrzejewski** [comment]
@rickmills Unfortunately we stick to using ObjectManager interface so you need to add the``doctrine/common`` package, although it contains mostly interfaces, not actual ORM/ODM implementation.

**Comment by Bonobomagno** [comment]
There is any suggested flow for integrating it in laravel?
In fact i would like to use the elasticsearch integration.
