### ISSUE TITLE
Import Products

### ISSUE THREAD

**Issue by yaidelferrales** [Sylius/Sylius#5492]
Hello, I'm trying to import some products into my sylius database but I only get errors after importing the products.

I've done a diff on the database between an imported product and a product created by the admin system, and there are no differences.

I get an error on line 202: SyliusWebBundle/FrontEnd/HomePage/main.html.twig
  {{ render(url('sylius_partial_product_latest_b_supplement')) }}

This is my database importer. Inside the project there is a file name products.csv, with the format of owr products.
https://yaidelferrales@bitbucket.org/billionaires_from_once/importer.git

Thanks in advance, and let me know if you need any additional information

**Comment by okwinza** [comment]
Hey @yaidelferrales! Please post full error message with trace info if possible.
Also it would be nice to see some code of your importer(the sylius part)

**Comment by michalmarcinkowski** [comment]
Please post such questions on stackoverflow under "sylius" tag, it's the official support channel, maybe someone will be able to help you there.
