### ISSUE TITLE
[bug] VariationBundle Forms OptionValueType and OptionValueTranslationType misslabeled/switched around?  

### ISSUE THREAD

**Issue by Mr-Negative** [Sylius/Sylius#5496]
So.
`VariationBundle\Form\Type\OptionValueType`
have 
```
public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('translations', 'sylius_translations', [
                'type' => sprintf('sylius_%s_option_value_translation', $this->variableName),
                'label' => 'sylius.form.option.name',
            ])
            ->addEventSubscriber(new AddCodeFormSubscriber())
        ;
    }
```

and 

`VariationBundle\Form\Type\OptionValueTranslationType`
have
```
public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('value', 'text', [
                'label' => 'sylius.form.option_value.value',
            ])
        ;
    }
```

Shouldn't be other way around?

**Comment by pjedrzejewski** [comment]
Why?

**Comment by Mr-Negative** [comment]
If i use it like this in builder in frontend
```
foreach ($options['variable']->getOptions() as $i => $option) {
            foreach ($option->getValues() as $y => $value) {
                $builder->add($value->getCode(), sprintf('sylius_%s_option_value_translation', $this->variableName), [
                'label' => $value->getName(),
                ]);
            }    
        }
```

it render
![zrzut ekranu 2016-07-12 o 13 17 24](https://cloud.githubusercontent.com/assets/4626156/16765212/105ea4ca-4833-11e6-8dfc-41ee637ac2f0.png)

When
`foreach ($options['variable']->getOptions() as $i => $option) {
            foreach ($option->getValues() as $y => $value) {
                $builder->add($value->getCode(), sprintf('sylius_%s_option_value', $this->variableName), [
                'label' => $value->getName(),
                ]);
            }   
        }`

![zrzut ekranu 2016-07-12 o 13 19 01](https://cloud.githubusercontent.com/assets/4626156/16765245/3d2f812c-4833-11e6-8996-a706f631bbbf.png)

So when i use without `_translation` it shows translation, i think it should be other way around?

**Comment by Mr-Negative** [comment]
Oh. Ok i undestand it now.This is like child form. My mistake, sorry.
