### ISSUE TITLE
[supportRequest] creating getters/setters doctrine:generate:entities adds private $condition variable 

### ISSUE THREAD

**Issue by Mr-Negative** [Sylius/Sylius#5502]
Why `app/console doctrine:generate:entities AppBundle`
adds 
`/**
     * @var string
     */
    private $condition;`
in all appBundle entities, and creates getter and setter for it, and doesn't create getters and setters for rest of variables?

yep, i'm lazy ;-)

**Comment by michalmarcinkowski** [comment]
You should ask Doctrine :)

**Comment by carlcraig** [comment]
@Mr-Negative i had similar issue, found solution here http://stackoverflow.com/questions/37928897/unknown-condition-autogenerate-on-symfony-2-8
