### ISSUE TITLE
Moving on from WebBundle - what's the status etc.

### ISSUE THREAD

**Issue by Mr-Negative** [Sylius/Sylius#5524]
So i read in documentation (and here in github) that you planing to move from old webBundle and abandon it and move into ShopBundle. I see that in Shop there is a lot of front views done, so my questions are:
- am I wrong?
- Is it planned for current milestone (or any ETA)?
- What is not done yet /what feature is it waiting on to moving ?

My frontend creator would like to do his job and i would like to point him to right direction and inform him whatswhat.

**Comment by gabiudrescu** [comment]
@Mr-Negative why don't you try using a Theme and work with your own templates?

**Comment by Mr-Negative** [comment]
@gabiudrescu Well it does make sense. Is this ThemeBundle used somewhere now or it is for now not fully done yet?

**Comment by gabiudrescu** [comment]
not that I know. 

but it's pretty simple to create one - follow the docs here: http://docs.sylius.org/en/latest/bundles/SyliusThemeBundle/index.html

basically, if you create the folder structure from here (http://docs.sylius.org/en/latest/bundles/SyliusThemeBundle/your_first_theme.html#theme-structure) and import the theme via composer, you're all set for starting to work on it.

**Comment by Mr-Negative** [comment]
thank you very much, i will look at it :-)

**Comment by inssein** [comment]
@gabiudrescu are you using the theme bundle extensively? I just tried to play around with it for a while, but not having as much luck. For example, I can easily override the `SyliusShopBundle/views/Homepage/index.html.twig`, but say I wanted to override `SyliusShopBundle/views/layout.html.twig`, I have no luck.

Seems like the theme bundle won't override the way `{% extends ... %}` works.

**Comment by gabiudrescu** [comment]
@inssein my experience is limited with ThemeBundle, as we just started to work with it. but we plan to use it extensively in the upcoming 3 months, when we will migrate all our UIs to this.

**Comment by pjedrzejewski** [comment]
WebBundle has been removed from the Kernel and will soon be removed from the repository.

**Comment by gabiudrescu** [comment]
WebBundle - and now his watch has ended. 

thanks for the info @pjedrzejewski
