### ISSUE TITLE
downloadable products

### ISSUE THREAD

**Issue by gholami-mohammad** [Sylius/Sylius#5525]
How to define a downloadable product for my shop?

**Comment by FatalError404** [comment]
I'm having the same issue here, from the documentation I did not see any way to do it.

**Comment by lchrusciel** [comment]
It is not an issue. Please move this question to stackoverflow. 

Regular product will do the job. Just add a `DownloadableTaxCategory` which will have tax rate with 0. Product can be extended with additional field url, or something similar. 

Can be closed /cc @michalmarcinkowski

**Comment by michalmarcinkowski** [comment]
I labeled it "Documentation" since it will be a frequent question so it's worth to describe it in our docs. I would leave it open till we put it in the backlog.

**Comment by TheMadeleine** [comment]
I've just put it into the docs backlog @michalmarcinkowski :)

**Comment by michalmarcinkowski** [comment]
Thanks @TheMadeleine 👍
