### ISSUE TITLE
[Flow] Process validation error handling

### ISSUE THREAD

**Issue by dantleech** [Sylius/Sylius#5526]
The process/flow uses closured for error handling. The message is:

![an_error_occured](https://cloud.githubusercontent.com/assets/530801/16912699/a3e67c00-4cdd-11e6-9d2f-9c1d922a03da.png)

due to this closure:

```php
    {
        $builder
            ->add('security', 'sylius_checkout_security')
            // ...
            ->validate(function () {
                return !$this->getCurrentCart()->isEmpty();
            })
        ;
    }
```

This is extremely opaque and we could clearly give a clear exception message here.

Solutions:

- Throw the exception from the `validate()` method.
- Add the exception message as a second argument to `validate()` on the builder.
- ... ?

**Comment by dantleech** [comment]
@pjedrzejewski I guess this is irrelevant as the FlowBundle is being removed?

**Comment by pjedrzejewski** [comment]
Well, we most likely won't remove FlowBundle, just not use it in the core. It is used by some other projects and we want to still support it - that being said, I'd be super happy if someone wants to adopt it. :D

**Comment by michalmarcinkowski** [comment]
Closing as FlowBundle is not supported anymore.
