### ISSUE TITLE
[Order] Flattening 

### ISSUE THREAD

**Issue by choomz** [Sylius/Sylius#5534]
After some check, i'm wondering how Sylius currently handle flat orders.

I saw the Gedmo loggable extension, some properties are indeed mapped to the log tables, but actually, it looks like that there is only on way to handle it through the history menu.

How can we store orders info to prevent changing datas if product name / shipping & billing adresses are updated post order ?

Should we store some version ? Actually orders are only handled through the resource bundle ?

Thanks for your help.

Cheers :)

**Comment by gabiudrescu** [comment]
I'm also a bit worried about this - how do other Sylius users make sure the order does not change after checkout if the products become un-available or if the address used has been edited.

**Comment by choomz** [comment]
I ended up with 2 more fields in sylius_order table : billingAddressVersionId & shippingAddressVersionId, and also another in the sylius_order_item table : productVariantVersionId.

After that, you need to override order show controller (front & back) and connect the ressource with the log_entry table, based on order status (if completed, take saved version).

Version number are saved in a state machine callback, on complete.

I also override LogEntry with 2 custom entities : one for addresses, one for product.

Hope it helps

**Comment by michalmarcinkowski** [comment]
The shipping and billing address is saved on order, so it won't change until you manually edit the order in the backend. Regarding products, you can't remove product that was already ordered and enabling/disabling it doesn't influence the order at all. The only vulnerability is the product name, right now when you change name of the product you will see the new name on order details page for previous orders.

**Comment by gabiudrescu** [comment]
the product name changing is still a problem in Sylius. and from accounting point of view, it's not very nice to have an invoice issued for the product «Sticker "rerum"» and 2 months later, this product name to be «John Doe Product - ckerSti "rurem"» or something like that.

**Comment by pamil** [comment]
@gabiudrescu is #8874 a solution you are looking for?

**Comment by gabiudrescu** [comment]
yup, kinda.

but I think this PR is not available on demo.sylius.org, right? before adding that comment, I tried it there and I could change the name of the product and have it changed in the order item too.

**Comment by stefandoorn** [comment]
It's merged to 1.1 upcoming version :)

**Comment by gabiudrescu** [comment]
I have the feeling a Continuous deployment setup on demo.sylius.org could be useful in these cases.
