### ISSUE TITLE
How add script code when purchases were successful

### ISSUE THREAD

**Issue by Skiba260** [Sylius/Sylius#5538]
Hi , 
I want add script code to sylius (google ecommerce raport) when purchases were successful.
How can I do this  ?

**Comment by gabiudrescu** [comment]
the simplest (and dirty) way I could possibly think about would be "echo-ing" every relevant thing from the Order object in the twig template of the thank you page.

the nice and good way of doing this I'm thinking would be by:

- create a custom serializer for the Order object
- create a service to prepare the Order object for serialization
- create a twig function that calls the service mentioned above
- use that twig function in the thank you page template

or try this magic method: //github.com/webburza/sylius-google-ecommerce-bundle (cc @webburza)

**Comment by Skiba260** [comment]
Thanks for answer. I add controller and template "thank you page" and forward after products were ordered.

**Comment by michalmarcinkowski** [comment]
Looks like it should be closed.
