### ISSUE TITLE
ResourceBundle created form. Is there way to use them in other places?

### ISSUE THREAD

**Issue by Mr-Negative** [Sylius/Sylius#5543]
I created new resource via http://docs.sylius.org/en/latest/bundles/SyliusResourceBundle/index.html
 and it's working 
`http://127.0.0.1:8000/product-options/new`
shows form.
![zrzut ekranu 2016-07-19 o 22 04 42](https://cloud.githubusercontent.com/assets/4626156/16964655/e0d59e82-4dfc-11e6-94d1-42de25936c1c.png)

Question is, now i would like to  use it in some other entity as form field type.
Something like in any other form:
```
 $builder
            ->add('productOptions', 'collection', [
                'type' => 'app_product_option_type',
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,
                'button_add_label' => 'Dodaj opcje',
            ]) ;
```
is it possible? how

**Comment by videni** [comment]
@Mr-Negative ，do you mean you want to embed form in another form?  I believe you can reference this document [symfony form](http://symfony.com/doc/current/book/forms.html).

**Comment by Mr-Negative** [comment]
@videni  Well kind of, but form created via ResourceContoller so if im not mistaken you need to do something like
`use AppBundle\Form\Type\ProductOptionType`
and you don't have this kind of entity to use in other contoller. Basicly there is no form.type. for it/or i didn't find it.

**Comment by videni** [comment]
@Mr-Negative , you need to define that form yourself,  and the let the ResourceController know the you want to use. you can do something like (this)[ file:///Users/vidy/www/Sylius/docs/build/bundles/SyliusResourceBundle/forms.html#custom-resource-form], 
or associates them in the Configuration.php of your bundle. please reference any bundle Sylius provides.

**Comment by Mr-Negative** [comment]
Yeah, i know how to do it this way, but you need to create form from groundup... But you confirmed my throughts so thank you.
