### ISSUE TITLE
Migrate from /administration to /admin (new Admin UI)

### ISSUE THREAD

**Issue by DanPhyxius** [Sylius/Sylius#5563]
Hi guys! 

Could you give me an url for setup the new admin?
I can see the /admin path on my installation but i can't get js/app.js and css files. 
I tried to do "npm install" and "gulp" on vendor/sylius/sylius but nothing happen.

<img width="1436" alt="schermata 2016-07-21 alle 10 06 02" src="https://cloud.githubusercontent.com/assets/4693301/17016306/d29465dc-4f2e-11e6-95f5-9e7386ea5796.png">

Edit. 
Maybe i got a solution in this issue:
https://github.com/Sylius/Sylius/issues/#5034

I manually copied package.json and Gulpfile from this repo to my docroot and use:

npm install
gulp

on my docroot and this is the result:

<img width="1440" alt="schermata 2016-07-21 alle 10 30 39" src="https://cloud.githubusercontent.com/assets/4693301/17016292/c5b3dd34-4f2e-11e6-98a2-97e8b5bd7e5b.png">

but, if i go to every different route i get the follow errors:

<img width="1424" alt="schermata 2016-07-21 alle 10 30 48" src="https://cloud.githubusercontent.com/assets/4693301/17016297/c91fa78c-4f2e-11e6-8bc0-2664cb2f0024.png">

for Grid sylius_admin_product, sylius_admin_customer (and so on.. :) ).

What i'm wrong?

Thank you for your help! 
Dan

**Comment by michalmarcinkowski** [comment]
Looks like the grids are not imported, make sure you have [this line](https://github.com/Sylius/Sylius-Standard/blob/master/app/config/config.yml#L7).

**Comment by DanPhyxius** [comment]
Thank you @michalmarcinkowski! This fix a lot of stuff! :)

Actually it looks like the new Admin is a minimal version (many features are missed) while the old one is a complete product for our customer.

It would be a good idea to use the old administration panel for our purpose? :) 

Thank you,
Dan

**Comment by michalmarcinkowski** [comment]
Probably no longer relevant, but answering your question, if you are able to maintain old admin on your side it's fine, but be prepared for a lot of BC breaks... 😕 

I think this can be closed.
