### ISSUE TITLE
[resource][phpcrodm] Map date fields in form builder etc.

### ISSUE THREAD

**Issue by dantleech** [Sylius/Sylius#5586]
Currently the `Sylius\Bundle\ResourceBundle\Doctrine\ODM\PHPCR\Form\Builder\DefaultFormBuilder` form builder "guesses" all the field types:

``` php
$formBuilder->add($fieldName, null, $options);
```

It should be improved to add appropriate field types, e.g. `date` etc. according to the metadata.

**Comment by pjedrzejewski** [comment]
@dantleech Isn't it done by form framework itself? I did not want to duplicate the logic of form guessers. They use doctrine metadata already IIRC.

**Comment by dantleech** [comment]
Hmm, that sounds familiar yes. Will have a look, maybe there is some PHPCR-ODM guesser missing.
