### ISSUE TITLE
[ResourceBundle] ResourceFormFactory is not compatible with Symfony 2.8+

### ISSUE THREAD

**Issue by ste93cry** [Sylius/Sylius#5590]
I don't know if this can be considered a bug, a feature request or neither of the two, but let me explain the problem first: I'm using the `ResourceBundle` with Symfony 2.8. From that version of Symfony, how a form is declared (and istantiated) was changed. Instead of using an alias name for each form type, the FCQN of the type class is used ([#15079](https://github.com/symfony/symfony/pull/15079)). If a FCQN is used as the form type in the resource config, the default `ResourceFormFactory` tries to instantiate the form type by doing a simple `new $className()`, and then pass the instance to the underlying form factory. This causes two problems: the first is a deprecation message triggered by the `createNamedBuilder` method that doesn't accept anymore an instance of the form type, and the second is that not using an alias there is no way to have a form that takes arguments in the constructor (e.g. injected services). My suggestion is to remove the check for the FCQN in the Sylius form factory, and always let the underyling Symfony form factory to instantiate the form by using the specified type, whatsever it is.

**Comment by ibasaw** [comment]
seem like this is my problem with https://github.com/Sylius/Sylius/issues/5558

i can't use injected service in my form constructor with sylius form type class

**Comment by ste93cry** [comment]
That is the issue I'm talking about. I provided in the description of the issue the solution, if you want to give it a try (it works for me)

**Comment by ibasaw** [comment]
is that file https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Controller/ResourceFormFactory.php @ste93cry  you talk about ?

**Comment by ste93cry** [comment]
Yes it is. In my project I overridden that class and removed the lines 42 to 44

**Comment by ibasaw** [comment]
i had already tried to comment these lines, but got always same problem....maybe i must to try to extend this class

**Comment by ibasaw** [comment]
can i see your extended class @ste93cry  ?

**Comment by ste93cry** [comment]
Here it's the code of the method. As I said above, I just removed that lines

```php
class ResourceFormFactory implements ResourceFormFactoryInterface
{
    /**
     * @var FormFactoryInterface $formFactory The form factory
     */
    private $formFactory;

    /**
     * Constructor.
     *
     * @param FormFactoryInterface $formFactory The form factory
     */
    public function __construct(FormFactoryInterface $formFactory)
    {
        $this->formFactory = $formFactory;
    }

    /**
     * {@inheritdoc}
     */
    public function create(RequestConfiguration $requestConfiguration, ResourceInterface $resource)
    {
        $formType = $requestConfiguration->getFormType();
        $formOptions = $requestConfiguration->getFormOptions();

        if ($requestConfiguration->isHtmlRequest()) {
            return $this->formFactory->create($formType, $resource, $formOptions);
        }

        return $this->formFactory->createNamed('', $formType, $resource, array_merge($formOptions, ['csrf_protection' => false]));
    }
}
```

**Comment by ibasaw** [comment]
@ste93cry always got this error with constructor

    Catchable Fatal Error: Argument 1 passed to St\AppBundle\Form\Type\TaxonType::__construct() must be an instance of St\AppBundle\Form\Type\Tools, string given

**Comment by ste93cry** [comment]
Check your service definition for the form type, it seems that you're passing wrong arguments to the constructor. Btw, we're going a bit off-topic here. If someone from the @Sylius team wants to comment about this issue, I would be happy to prepare a PR

**Comment by ibasaw** [comment]
i pass the service as i always do with my own form type class, but only sylius class form type don't want to   construct fine. look at https://github.com/Sylius/Sylius/issues/5558

**Comment by pdias** [comment]
I don't know if is the same problema, but to solve the deprecation message i hev changed two files in ResourceBundle (ResourceFormFactory and RequestConfiguration).

ResourceFormFactory.php (commented code lines like ste93cry)

```
public function create(RequestConfiguration $requestConfiguration, ResourceInterface $resource)  {
        $formType = $requestConfiguration->getFormType();

        /*if (false !== strpos($formType, '\\')) {
            $formType = new $formType();
        }*/

        $formOptions = $requestConfiguration->getFormOptions();

        if ($requestConfiguration->isHtmlRequest()) {
            return $this->formFactory->create($formType, $resource, $formOptions);
        }

        return $this->formFactory->createNamed('', $formType, $resource, array_merge($formOptions, ['csrf_protection' => false]));
    }
```

and RequestConfiguration.php (with this code will try to get the form from the route _sylius parameters, if not find, will try in the metadata). 

```
    public function getFormType()
    {
        if($form = $this->parameters->get('form')) {  
            if (is_array($form) && array_key_exists('type', $form)) {
                return $form['type'];
            }
        } else {  
            if($this->metadata->hasClass('form')) {  
                return $this->metadata->getClass('form')['default'];  
            }  
        }
        
        return sprintf('%s_%s', $this->metadata->getApplicationName(), $this->metadata->getName());  
    }

```

**Comment by ibasaw** [comment]
@pdias don't solve my problem ;)
and don't know if it solve the issue itself
