### ISSUE TITLE
[ResourceBundle] ResourceController ACL check impossible to do on resource

### ISSUE THREAD

**Issue by ste93cry** [Sylius/Sylius#5591]
In the `ResourceController` class the `isGrantedOr403` checks whether access for a given permission is granted to the current logged-in user. However, it's common to check the permission on the resource itself and not on a generic route action. What I propose is to move the call to that method after the resource(s) has been retrieved, and pass the collection or the instance of the resource itself to the `isGranted` method of the authorization checker.

**Comment by plusdepseudo** [comment]
Hi,
It would also allow to use ActionVoter to add resource based permission checking !

Best of all would be to modify the interface `AuthorizationCheckerInterface `to be compatible with Symfony's one
exemple:
`public function isGranted(RequestConfiguration $configuration, $permission);`
change to:
`public function isGranted($permission, $object = null);`
would then allow to use `Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface`
in` sylius_resource: authorization_checker` config
simple and efficiant out of the box permission checking :) otherwise I've to code a Bridge just to swap those two parameters :/

thx

**Comment by ste93cry** [comment]
>Best of all would be to modify the interface AuthorizationCheckerInterfaceto be compatible with Symfony's one

I would directly use the `AuthorizationChecker` service to check the permissions by passing the retrieved resource and the permission set in the configuration of the resource

**Comment by ste93cry** [comment]
@pjedrzejewski any thoughts on this? I see no reason to have another `AuthorizationCheckerInterface`, we should just use the Symfony's authorization checker by passing as attribute the permission name and as subject the resource

**Comment by dannyvw** [comment]
Any update on this? Looks like the same problem as in #7990. I agree with the proposal of @ste93cry so we can easily check the permissions of the resource.

**Comment by dannyvw** [comment]
@pjedrzejewski Any thoughts about this issue? So someone can build this?

**Comment by pierre-H** [comment]
any news ?

**Comment by costinel-draculet** [comment]
any update on this?

**Comment by sabat24** [comment]
I needed that feature as well and I resolved it in following way.

1. I created my custom Resource Authentication Checker

```php
<?php

declare(strict_types=1);

namespace App\Sylius\Security\Authorization;

use Sylius\Bundle\ResourceBundle\Controller\AuthorizationCheckerInterface as ResourceAuthorizationCheckerInterface;
use Sylius\Bundle\ResourceBundle\Controller\RequestConfiguration;
use Sylius\Bundle\ResourceBundle\Controller\SingleResourceProviderInterface;
use Sylius\Component\Resource\Model\ResourceInterface;
use Sylius\Component\Resource\Repository\RepositoryInterface;
use Sylius\Component\Resource\ResourceActions;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

final class ResourceAuthorizationChecker implements ResourceAuthorizationCheckerInterface
{
    public function __construct(
        private SingleResourceProviderInterface $singleResourceProvider,
        private ContainerInterface $container,
        private AuthorizationCheckerInterface $authorizationChecker,
    ) {
    }

    public function isGranted(RequestConfiguration $configuration, string $permission): bool
    {
        // We need to recreate original permission action, because Sylius permission is a string like `sylius.channel.create`
        // We shouldn't ask provider to find a resource for non-resource aware actions like `INDEX` and `CREATE`
        // It can be more generic if you only dispatch events here and listen for them somewhere in your application

        if (
            in_array(
                $permissionAction,
                [ResourceActions::INDEX, ResourceActions::CREATE, ResourceActions::BULK_DELETE],
            )
        ) {
            return $this->authorizationChecker->isGranted(
                $permissionAction,
                $configuration->getMetadata()->getClass('model'),
            );
        }

        /** @var RepositoryInterface $repository */
        $repository = $this->container->get($configuration->getMetadata()->getServiceId('repository'));
        $resource = $this->findOr404($configuration, $repository);

        return $this->authorizationChecker->isGranted($permissionAction, $resource);
    }

    private function getPermissionActionFromPermission(string $permission): string
    {
        $lastDotPos = strrpos($permission, '.');

        if ($lastDotPos !== false) {
            return substr($permission, $lastDotPos + 1);
        } else {
            return $permission;
        }
    }

    /**
     * @throws NotFoundHttpException
     */
    private function findOr404(RequestConfiguration $configuration, RepositoryInterface $repository): ResourceInterface
    {
        $resource = $this->singleResourceProvider->get($configuration, $repository);
        if ($resource === null) {
            throw new NotFoundHttpException(
                sprintf('The "%s" has not been found', $configuration->getMetadata()->getHumanizedName()),
            );
        }

        return $resource;
    }
}
```

2. I override  the default one in `config/packages/_sylius.yaml`

```yaml
sylius_resource:
    authorization_checker: 'App\Sylius\Security\Authorization\ResourceAuthorizationChecker'
```

3. I changed the Access Decision Manager default behaviour in `config/packages/security.yaml`

```yaml
security:
    access_decision_manager:
        allow_if_all_abstain: true
```

4. Example voter supports method

```php
protected function supports(string $attribute, mixed $subject): bool
    {
        if (!in_array($attribute, [ResourceActions::SHOW, ResourceActions::UPDATE])) {
            return false;
        }

        if (!$subject instanceof MyResourceObject && $subject != MyResourceObject::class) {
            return false;
        }

        return true;
    }
```

One drawback I found is that if you use default Resource controller actions the `findOr404` will be called twice: here and in original ResourceController.
