### ISSUE TITLE
Locale from Channel not set

### ISSUE THREAD

**Issue by sprik** [Sylius/Sylius#5600]
Hi, 

I use a multi-channel installation of Sylius and I configure each channel with its locale but when I change the hostname to go on a specific channel the locale doesn't change but sylius use only the locale configured in parameters.yml as locale attribute.

The channel is of course successful changed, the debug bar tell me the current channel.

**Comment by pamil** [comment]
I'm currently reworking the locale related logic in #5597, so it should be fixed soon :)

**Comment by sprik** [comment]
thanks @pamil 

Do you know when this part could be released?

**Comment by pamil** [comment]
I hope it will get merged this week.

**Comment by sprik** [comment]
thanks @pamil

**Comment by EgorDenisenko** [comment]
I find some solution to resolve this issue. If anyone is interested, I posted it, or you can write me an email: Ashbringer09@gmail.com

**Comment by michalmarcinkowski** [comment]
Fixed in https://github.com/Sylius/Sylius/pull/5597.
