### ISSUE TITLE
Shipping method new : amount is not display

### ISSUE THREAD

**Issue by ibasaw** [Sylius/Sylius#5603]
hi,

I can modifiy my shipping method, the amount input is visible, but when i want to create a new one, the amout input is not rendered....form.configuration is null

Do you know why the amont input is not rendered ?

**Comment by pjedrzejewski** [comment]
What is your Sylius version and installation? Seems like your JS might be broken.

**Comment by ibasaw** [comment]
you are absolutely right! that was it ! Thank you @pjedrzejewski
