### ISSUE TITLE
[UiBundle] Shop related js in private/js/app.js

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#5613]
Is the plan to have a shop specific app.js? It seems like there is some stuff in the UiBundle's app.js that probably should not be there.

The problem I have specifically is `$('.card .image').dimmer({on: 'hover'});`. I am trying to make a site with semantic ui via the Theme bundle, and all my images on any cards have this image dimmer.

Unfortunately I don't see an easy way of overriding this in my template either. 

Edit:
Just realized that even if this was in the ShopBundle, it would cause problems for me as there is no easy way to override it. Perhaps we should use an additional CSS selector class for sylius specific cards.

**Comment by pjedrzejewski** [comment]
Fixed already.
