### ISSUE TITLE
SyliusWebBundle not registered.

### ISSUE THREAD

**Issue by sprik** [Sylius/Sylius#5614]
Hi, 

I updated with the last version of sylius with composer but I have this error:

[LogicException]                                                                                
Bundle "XXXXXSyliusWebBundle" extends bundle "SyliusWebBundle", which is not registered.

Which is the problem? Before the update all works fine!
Thanks

**Comment by ylastapis** [comment]
You should now extends the SyliusShopBundle :)

It has been unplugged here https://github.com/Sylius/Sylius/pull/5535

**Comment by DanPhyxius** [comment]
Same issue here, it seems all our frontend doesn't not work anymore! :(

Could you tell me something more about this new kind of integration? @ylastapis 

What's the steps we're to do to get migration? 

We're close to an application deploy and this issue can be hard to handle for us! :)

Thank you for your answer,
Dan

**Comment by okwinza** [comment]
@DanPhyxius i suggest you either 1) rollback to the older version and handle the migration after your deploy or 2) dive into new ShopBundle and rebuild your frontend according to it.

**Comment by DanPhyxius** [comment]
Hi @okwinza, thank you for your answer! :)

Is there any instructions or documentation about the new ShopBundle customization? 

I think it would be better to handle compatibility with latest version, so our company would try to manage these changes. :)

Thank you,
Dan

**Comment by pamil** [comment]
Old WebBundle was rewritten into two independent bundles: ShopBundle and AdminBundle. They are all based on CoreBundle, which is the glue between all other Sylius components and bundles.

The way you customize them stays the same. Feel free to ask any questions.

**Comment by DanPhyxius** [comment]
Hi @pamil,

thank you. We'll study the new Bundle and we'll try to manage the rebuild. :) 

Let's check soon with (i hope!) good news! :)

Dan
