### ISSUE TITLE
Possible Issue with checkout translations

### ISSUE THREAD

**Issue by bretto36** [Sylius/Sylius#5640]
When checking out using the Standard Shop Bundle code (OrderController:updateAction). The translation 

sylius.checkout.finalize.order.promotion_discount

does not resolve to anything. It's currently in the WebBundle, but doesn't load for ShopBundle code. 

Do i just add the same value into the ShopBundle translation files? I will do the changes just want to know if that's the right place to put it

**Comment by michalmarcinkowski** [comment]
The translation key should be changed to `sylius.ui.promotion_discounts` and moved to the `UiBundle`.
