### ISSUE TITLE
Resources or not shown in the correct locale through the api

### ISSUE THREAD

**Issue by hvanoch** [Sylius/Sylius#5649]
Lets say I want to display all taxon in locale nl_BE through the api.
The path would be /api/nl_BE/taxons.
Currently this is not possible because of the locale used for the resources comes from the LocaleContext which uses the session and our current request. So it always shows the default locale. 

What is the best approach to fix this? 

One option could be to create a custom LocaleContext and check if the current route matches as an api request. Then we always use the locale provide by the request and discard our session storage, cause  an api should be sessionless as far as i know.

Any thoughts

**Comment by ylastapis** [comment]
I asked the same here : https://github.com/Sylius/Sylius/pull/5597

I've written some workarround waiting for an answer here:  https://gist.github.com/ylastapis/a4c1f2dab80febf17f24ffb560a952ef

If you have a better option :)

**Comment by hvanoch** [comment]
Hi @ylastapis 

As far as I can see it still uses the LocalContext for "remembering" the locale. It does that by saving it to the session. So we need a way to bypass the SessionStorage when we are using the locale in API requests.

API request should be stateless/sessionless, but currently a new session would be started for each API request, which results in setting a Session Cookie, which means no easy caching, and so on...

I currently wrote a solution by creating a custom LocalContext which gets injected with the RequestStack. It then checks if the current path of the request starts with /api. If so then Locale is always read from the Request and not the "Storage" thus bypassing the creation of a new session.
Definitely not the most elegant solution so recommendations are very welcome.
https://gist.github.com/hvanoch/ba9d28db3e5dc092973783d9e7239a3d

**Comment by pamil** [comment]
Good catch @hvanoch and @ylastapis! I just have written the fix in #5654 :)

**Comment by pamil** [comment]
Just note that the `_locale` should be one of the available locales (in core Sylius that means it should be present in channel's locales and it should be enabled).

**Comment by ylastapis** [comment]
@pamil thanks for your feedback, i'll try your fix soon :)

**Comment by ylastapis** [comment]
@pamil it's working like a charm :) thanks
