### ISSUE TITLE
[feature request /support request] Showing what entity is blocking delete comand for other entity

### ISSUE THREAD

**Issue by Mr-Negative** [Sylius/Sylius#5660]
Is there way to show what entity blocking erasing of other entity?

Because when you try delete product that is used in example in order, you will have  info that you can't because it's in use. It would be nice to have info like 

```
Error
Cannot delete, the product is in use IN ORDER nr 212

```

**Comment by daryush** [comment]
You mean here only Products used on Orders? Or also i.e. when ProductAttribute is used in Product?

**Comment by Mr-Negative** [comment]
Well, everywhare really.
