### ISSUE TITLE
support request - install Deploying sylius from dev to prod proper way.

### ISSUE THREAD

**Issue by Mr-Negative** [Sylius/Sylius#5664]
How to do proper migrating from dev to prod.
when i started server locall with php app/console server:start 127.0.0.1:8001 -env=prod 
it still gives me dev env when accessing via http://127.0.0.1:8000/ (without app_dev)

**Comment by michalmarcinkowski** [comment]
All you need to know is described [here](http://symfony.com/doc/current/setup/built_in_web_server.html).
