### ISSUE TITLE
Product Bundle Event Subscriber

### ISSUE THREAD

**Issue by atij** [Sylius/Sylius#5668]
hi,

Product bundle cannot be integrated without core bundle as it uses getFirstVariant() in ProductOptionFieldSubscriber. 

/** Options should be disabled for configurable product if it has at least one defined variant */
$disableOptions` = (null !== $product->getFirstVariant()) && (false === $product->hasVariants());

Can you please review it?

Thank you,
Andrei

**Comment by tuka217** [comment]
Hi, 
the ProductOptionSubsciber use now DefaultVariantResolver from Variation component, so you should be able to use it without CoreBundle :)

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ProductBundle/Form/EventSubscriber/ProductOptionFieldSubscriber.php#L62

**Comment by michalmarcinkowski** [comment]
@tuka217 👍
