### ISSUE TITLE
Support Request - Prefilling Checkout Data

### ISSUE THREAD

**Issue by bretto36** [Sylius/Sylius#5670]
How do i get the Checkout pages (eg Addressing page) to default with the logged in User's First and Last name, phone number, etc

At the moment it's blank everytime i check out. I'm hoping to add some of the checkout fields to the customers table so that the customers address will default to their profile address.

**Comment by bretto36** [comment]
The customer that is passed to the form (option = 'customer') has the correct id but does not have any other values from the database.

**Comment by ibasaw** [comment]
i think i had did it, on my addressing.htl.twig, i added this to have prefilled data from DB

you must override this template and try this:

    {{ form_widget(form.shippingAddress.lastName, {'value' : app.user.getCustomer.getLastName}) }}

**Comment by bretto36** [comment]
Ah, i made it way too complicated in my head! Thank you!
