### ISSUE TITLE
[AdminBundle][Product] create simple product with variant code.

### ISSUE THREAD

**Issue by wannaporn** [Sylius/Sylius#5677]
Hi,

In case of adding simple product form, product code is set to variant code by `SimpleProductSubscriber`.  Why do you use `form.variant.code` at https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_details.html.twig#L10 ?

Thank you.

**Comment by michalmarcinkowski** [comment]
Thanks for reporting! Most likely we should remove this line :)
