### ISSUE TITLE
[RFC] Introduce to TranslatableRepositoryInterface.

### ISSUE THREAD

**Issue by liverbool** [Sylius/Sylius#5685]
Let’s everyone thinks if we use `TranslatableRepositoryInterface` for `repository` that associated with translation.

Now we have a problem `cross-cutting` with translatable repository because it have to coding the original order separately.

If we introduce to use `TranslatableRepositoryInterface` will give us more options to eliminate `cross-cutting` , i.e. using `decorate` or the `event hooks`.

@Sylius

**Comment by michalmarcinkowski** [comment]
Done!
