### ISSUE TITLE
[AdminBundle] small visual Bug in customer edit . Field autocomplete

### ISSUE THREAD

**Issue by Mr-Negative** [Sylius/Sylius#5691]
When phone number in database is NULL, than browser keep writing there email adress by himself to phone form field. In Opera 39.
I would attach screen but github have some temp problems with images.

**Comment by bretto36** [comment]
Yes, this is a browser bug in many browsers. If there is a field above a password field and it's empty. The browser attempts to fill in a remembered email address. A fix is to add a password field at the top of the form with style="display:none". That generally tricks browsers into not doing the faulty behavior

**Comment by Mr-Negative** [comment]
Thank you. if it's browser bug that case is closed :-)
