### ISSUE TITLE
Support Request - Validating Cart on Checkout

### ISSUE THREAD

**Issue by bretto36** [Sylius/Sylius#5695]
I'm using the standard install. Can anyone tell me where I can put some custom validation to check that items are still available to someone whilst checking out. 

I have a restriction on the availability on items in the cart where they schedule the hire of an item. If the item is already hired for the date they have selected they can't add it to the cart. But if someone else manages to order it before them then anyone who still has it in their cart should be alerted. 

Is there an existing area that checks stock level? I can't seem to find anywhere.

And can it redirect back to the cart to show an error message?

**Comment by michalmarcinkowski** [comment]
We already implemented logic for that. Have a look at [Behat feature](https://github.com/michalmarcinkowski/Sylius/blob/df93d04bbd63938597748aa9249c886299f9beb7/features/inventory/checkout_inventory/validating_product_quantity_on_checkout_complete.feature#L2-L2).

Please reopen if there is an issue.
