### ISSUE TITLE
Payment method delete restriction

### ISSUE THREAD

**Issue by vcraescu** [Sylius/Sylius#5706]
On [Payment.orm.xml](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/PaymentBundle/Resources/config/doctrine/model/Payment.orm.xml#L23) method column should have on-delete="restrict" instead of "set null". Payment method and credit card are quite crucial information and their deletion should be restricted as long as there's a payment referencing them. 
Also, if the payment method is deleted, payments index screen from administration will probably crash. 

Do you accept a PR?

**Comment by michalmarcinkowski** [comment]
You're right. Sure we will accept a PR!

**Comment by michalmarcinkowski** [comment]
Fixed in https://github.com/Sylius/Sylius/pull/7227.
