### ISSUE TITLE
Sylius Issues

### ISSUE THREAD

**Issue by avlok003** [Sylius/Sylius#5727]
Hi,

I have found one vulnerability in the system.when i have access this URL http://demo.sylius.org/login and after login I have go to Edit profile details and change the password then no one can able to login with the DEMO:  Username or Email / Password

Note: Please fix it at your end. I have changed it same as your demo password mention at your website.

Thanks & Regards
Avlok

**Comment by michalmarcinkowski** [comment]
Hi Avlok, thanks for reporting. Right now there are separate accounts for admin and shop, so your not able to do it, we will update the demo ASAP 😉
