### ISSUE TITLE
How to extend ContentBundle StaticContent? can't find database mapping settings.

### ISSUE THREAD

**Issue by Mr-Negative** [Sylius/Sylius#5739]
Hi, i like to add new bool to static content,  extended class, form etc, but  i can't find where is /and how to extend doctrine phpcr mapping.
Is it proper place
sylius/sylius/src/Sylius/Bundle/ContentBundle/Resources/config/doctrine/StaticContent.phpcr.xml in first place?

**Comment by michalmarcinkowski** [comment]
There were several discussion about it, please take a look [here](https://github.com/Sylius/Sylius/issues/5301) maybe it will help.
