### ISSUE TITLE
Design is not coming properly

### ISSUE THREAD

**Issue by napestershine** [Sylius/Sylius#5746]
HI

I just install sylius on my system Ubuntu 16.04, PHP 7.x, MySQL 5.7.x, apache. I am getting following screen when i run 
`$php app/console server:run
`
![image](https://cloud.githubusercontent.com/assets/8603325/17542819/a720558a-5ee9-11e6-8038-59cbc985b89a.png)

**Comment by bretto36** [comment]
`php app/console assets:install`
try running the above command

**Comment by napestershine** [comment]
@bretto36  Thanks for support. I have run that command. But same results.

**Comment by napestershine** [comment]
Console showing following errors:
![image](https://cloud.githubusercontent.com/assets/8603325/17543070/9838714a-5eeb-11e6-881b-d393e3f77635.png)

**Comment by bretto36** [comment]
Oh you'll need to install `npm` and `gulp` then run `npm run gulp`

Install node (follow instructions here): https://github.com/npm/npm
Then install gulp using NPM: npm install gulp -g

Then run npm run gulp in the sylius base dir

**Comment by napestershine** [comment]
@bretto36  Thanks for support. I have installed npm 
```
$sudo apt-get install nodejs
$sudo apt-get install npm
$npm install gulp -g
```

now I am trying to run 
`$npm rum gulp `
in sylius dir. it gives following error:
`root@wmc:/opt/lampp/htdocs/sylius/sylius-standard# npm run gulp
npm ERR! Linux 4.4.0-34-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "gulp"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! missing script: gulp
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/lampp/htdocs/sylius/sylius-standard/npm-debug.log
`

**Comment by bretto36** [comment]
Did gulp install successfully? It seems to be unable to find the gulp command

try just running command `gulp`

**Comment by ylastapis** [comment]
You should just install it locally (```npm install gulp```) and then just run ```gulp```

**Comment by napestershine** [comment]
Hi

Thanks for support.

```
root@wmc:/opt/lampp/htdocs/sylius/sylius-standard# npm install gulp
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
root@wmc:/opt/lampp/htdocs/sylius/sylius-standard# gulp
module.js:328
    throw err;
    ^

Error: Cannot find module 'gulp-if'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/lampp/htdocs/sylius/sylius-standard/Gulpfile.js:2:14)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)

```

**Comment by ylastapis** [comment]
```npm install```:)

**Comment by bretto36** [comment]
Probably need to add all this to the sylius-standard docs

**Comment by napestershine** [comment]
Thanks so much @bretto36  and @ylastapis. Solved !!

**Comment by TheMadeleine** [comment]
I know you might not be used to it... but it is already in the docs :D http://docs.sylius.org/en/latest/book/installation.html

**Comment by lchrusciel** [comment]
And also in [README](https://github.com/Sylius/Sylius#quick-installation). If you prefer to run just gulp, then you should install a gulp globally(or add it to bash).
