### ISSUE TITLE
[Shop][Admin] Order's payment processing

### ISSUE THREAD

**Issue by tuka217** [Sylius/Sylius#5750]
When the store ships somewhere for free then the payment on order show is different than total price of order. 

![screen shot 2016-08-10 at 10 17 48](https://cloud.githubusercontent.com/assets/8963048/17546749/ddb44ddc-5ee3-11e6-908b-7fd890b9af7b.png)
![screen shot 2016-08-10 at 10 18 17](https://cloud.githubusercontent.com/assets/8963048/17546760/e7a3b346-5ee3-11e6-9e07-38c7c7ad1004.png)

**Comment by bretto36** [comment]
Can you post a screenshot of the rows related to that order in the sylius_payment table? Just want to confirm it's not putting the incorrect total in the database

**Comment by bretto36** [comment]
Also are you using multiple currencies?

**Comment by tuka217** [comment]
![screen shot 2016-08-11 at 08 34 16](https://cloud.githubusercontent.com/assets/8963048/17580377/7bf9455a-5f9e-11e6-9b45-092ddbfede03.png)

**Comment by tuka217** [comment]
And I use multiple currencies, but it's happens also when I have one default currency.

**Comment by michalmarcinkowski** [comment]
@tuka217 can you confirm it's resolved?

**Comment by tuka217** [comment]
Yups, it's resolved :)
