### ISSUE TITLE
Running behat feature for static contents complains  'Item "/" not found in workspace "default"'

### ISSUE THREAD

**Issue by videni** [Sylius/Sylius#5751]
I am adding the slideshow block management to the new admin ui,  it  is almost  the same as  the StaticContent, I have finished the jobs, but when I try to write Behat feature to test them, it give me this error
> Item "/" not found in workspace "default" (PHPCR\PathNotFoundException)

running command
bin/behat  -s ui_managing_static_contents 

also lead to this exception.

**Comment by pamil** [comment]
Just run `app/console doctrine:phpcr:repository:init` with proper environment (Behat uses `test` one).

**Comment by videni** [comment]
@pamil , still the same.

```
 app/console doctrine:phpcr:repository:init --env=test
```
```
Successfully registered system node types.
Executing initializer: CmfBlockBundle
  [PHPCR\PathNotFoundException]
  Item "/" not found in workspace "default"

  [PHPCR\ItemNotFoundException]
  Item "/" not found in workspace "default"
```

**Comment by videni** [comment]
however running
```
doctrine:phpcr:repository:init  --env=dev
```
doen't  give this error.

**Comment by Zales0123** [comment]
I've encountered the same error but after removing cache with ``rm -rf app/cache`` it vanished in the eternity (probably ``app/console cache:clear --env test`` would also do the job). Please, let us know if it worked for you.

**Comment by videni** [comment]
@Zales0123, I can't reproduce this problem again, I solved  this problem by generating all fixtures for test environment.
