### ISSUE TITLE
Checkout - Pay before confirmation

### ISSUE THREAD

**Issue by bretto36** [Sylius/Sylius#5758]
Hi, I was wondering if anyone knows how i could go about putting a paypal payment step in the middle of the checkout process. So someone would authorize a payment after selecting "Paypal" from the payment options, then be taken back to the checkout process to finalise the order and money would be taken then. 

I'm trying to avoid the situation where someone creates an order but never pays. Has anyone had any experience with this?

**Comment by gabiudrescu** [comment]
@bretto36 I'd rather use a notification like 'hey, you need to pay so we can ship this order to you' - a cart recovery email.

rather than modifying the workflow as you say.
