### ISSUE TITLE
Not able to login to admin

### ISSUE THREAD

**Issue by napestershine** [Sylius/Sylius#5759]
HI 

When I try to login to admin it shows following:

![image](https://cloud.githubusercontent.com/assets/8603325/17577626/babf7ef4-5f9d-11e6-9286-a98b74053b30.png)

**Comment by bretto36** [comment]
Does  http://localhost:8000/app_dev.php/admin/login give you anything different?

**Comment by napestershine** [comment]
Thanks for Support @bretto36 .
It showed a different page. but I am not able to login. Can you write all steps Please.

**Comment by Zales0123** [comment]
Is there any chance you could provide some more detailed information?
- what does the page on ``admin/login`` looks like?
- did you run ``sylius:install``?
- did you load sample data?

Any more information would be useful, because "I am not able to login" honestly says nothing ;)

**Comment by napestershine** [comment]
Hi @Zales0123 

- I have added screenshot in my post. When I executed http://localhost:8000/app_dev.php/admin/login
I was at a login screen. There I tried to login as administrator account created during installation. I got same above error page again.

-  Yes, I run sylius:install
- How can I load sample data, please share.

Thanks so much

**Comment by napestershine** [comment]
Hi

`app/console sylius:install:database` resolved problem.

Thanks so much.

**Comment by Zales0123** [comment]
Great 👍  Please remember to run **whole** ``sylius:install`` command (which consist of ``sylius:install:database``, ``sylius:install:sample-data``, ``sylius:install:setup`` etc.) if you want to restart *Sylius* project ;)
