### ISSUE TITLE
can't add simple product

### ISSUE THREAD

**Issue by napestershine** [Sylius/Sylius#5760]
Hi

When I click on Create product->simple Product I get following screen:
![image](https://cloud.githubusercontent.com/assets/8603325/17580545/0dd90352-5fbd-11e6-9ca2-9f7534d66ad9.png)

**Comment by lchrusciel** [comment]
Do you fulfill a Sylius [requirements](http://docs.sylius.com/en/latest/book/requirements.html#php-required-modules-and-configuration)? It appears that you are missing an intl extension. I have just install a latest dev-master and everything works fine.

**Comment by napestershine** [comment]
Hi @lchrusciel  I have already intl extension in it. I followed sylius documentation.

**Comment by bretto36** [comment]
Hi @napestershine - I found i was changing the wrong php.ini file when i initially set it up. Easiest way to check that it's enabled properly is do a `echo phpinfo()` and find the intl module in the output. 

I'm running wamp and had to change the phpForApache.ini file not the php.ini file

**Comment by napestershine** [comment]
Thanks for support @bretto36 

I have enabled intl. Please see below screen shot.

![selection_001](https://cloud.githubusercontent.com/assets/8603325/17613933/c5ac468e-607f-11e6-98c4-55d5b52797b3.png)

**Comment by bretto36** [comment]
@napestershine Can you go to the Admin area, and edit your channel. Can you ensure there are locales in the list and a default locale is selected please. I had an issue when setting up that the database didn't link up the locale correctly to the channel. You may need to add a locale in the Locales section of the admin area

**Comment by napestershine** [comment]
Thanks problem solved :)
