### ISSUE TITLE
[CoreBundle][HwiOauth] Type error on HwiOauth authentication

### ISSUE THREAD

**Issue by ylastapis** [Sylius/Sylius#5761]
Argument 2 passed to Sylius\Bundle\CoreBundle\OAuth\UserProvider::__construct() must implement interface Sylius\Component\Resource\Factory\FactoryInterface, instance of Sylius\Bundle\CustomerBundle\Doctrine\ORM\CustomerRepository given

From here https://github.com/Sylius/Sylius/commit/f26f57d0b5e86eb62cae4071e81c506b15563684

Forgot to update service definition in hwi_oauth.xml.

PR on the go

**Comment by ylastapis** [comment]
@pjedrzejewski 

Am I supposed to open a ticket each time I submit a small PR like this one or should I just submit PR with description in it ?

Thanks

**Comment by pjedrzejewski** [comment]
@ylastapis If you want to only report an issue, please open a ticket, but if you work on a solution already, PR is enough. :)

**Comment by Mustabshir-K** [comment]
Hi, i am getting problem to configure the facebook login in sylius? Can somebody help me?
