### ISSUE TITLE
 [BUG] Sylius installer cannot be called if database exist and does not contains schema.

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#5764]
Step to reproduce: 
1. Clean Sylius installation (wit database, but without schema).
2. app/console sylius:install
3. Say no for database reset
4. See the following error:
![zrzut ekranu 2016-08-11 o 09 10 33](https://cloud.githubusercontent.com/assets/6213903/17581101/a2ded9dc-5fa3-11e6-9f55-77cc25d382a2.png)

**Comment by bretto36** [comment]
If you've manually created the database and not put the schema in then you should probably choose y so it can do the creation. If you choose not to reset it it's going to try and look for channels and workspaces that don't exist. 
Do you think a change in the text would make it easier to understand. 

"It appears your database already exists. Would you like to add/reset the schema?"

**Comment by lchrusciel** [comment]
The problem is, that we have assume that phpcr is initialed if doctrine database exist. It is an easy pick.

**Comment by lchrusciel** [comment]
@bretto36 after few thoughts, you are right, that the message is just misleading. I will just change a message. Thank you.
