### ISSUE TITLE
[ResourceBundle] Set the form's action and method in the controller

### ISSUE THREAD

**Issue by ste93cry** [Sylius/Sylius#5769]
At the moment neither the form action nor the form method are set during form creation by the `ResourceFormFactory` and `NewResourceFactory` classes. This is not itself a problem, because we can set them by passing the related options to the `form_start` Twig's method. However, we have to do it for every template we create where a resource form is used. My proposal is to set those two options during form's creation. The user will then be able to override anyway the set value via template if he wants, and the code will continue to work as usual. I would be happy to create a PR if you're interested in this issue.

**Comment by pjedrzejewski** [comment]
👍

**Comment by ste93cry** [comment]
Unfortunately (imho) there seems to be no reliable way to determine the action currently being executed (create, update or delete) inside the `ResourceFormFactory` or the `RequestConfigurationFactory` classes. When the form factory returns, the form is already built so there is no way to change its configuration to set the method and action. I could make those two classes aware of the resource action by passing a third method to their `create` method, but this would break the BC. How do you suggest to handle this problem?

**Comment by pjedrzejewski** [comment]
@ste93cry I'd be ok with this kind of BC break. :)

**Comment by ste93cry** [comment]
I've prepared a PR, but I'm not an expert of phpspec so please review the tests carefully. I would like to know what do you think about my implementation details
