### ISSUE TITLE
Promotions: how to offer a discount only on a specific subset of products

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#5772]
Preconditions:
 - I have 3 products in cart, from 3 different taxons: 2 books, 3 perfumes, 4 SD Cards
 - I want to configure a coupon based campaign to get a 15% discount for books

Steps to reproduce:
 - create a campaign with the following rules:
 -- taxon = books
 - and the following actions:
 -- item percentage discount = 15%
 - go to cart and add a coupon from this campaign

What happens:
 - all products, incl. perfumes and sd cards have 15% discount

----

I know that I might expect something from Sylius that was not intended like that, but I'd like to know from any Sylius user / developer around here if I'm doing something wrong while configuring the campaign. 

How can I, as of Sylius vanilla, configure a 15% discount voucher for a subset of products from a cart based on the taxon of those products?

---- 

This situation reminds me of a joke: imagine a newly wed couple. the husband, a great programmer, is sent by his wife to the grocery store with a  note: "buy a loaf of bread. if they have eggs, buy 10". he returns home with 10 loaf of breads :ghost:

**Comment by Zales0123** [comment]
Great question, indeed! There is a simple but also quite confusing answer - you can achieve it, but you can't 😄  Let mi explain.

Promotion consist of two main parts:
- actions - this is obvious, you get 15% off every unit 
- rules - the point is, rule is only a condition in which promotion is applied, so it cannot imply which unit can get a discount

There is also a third, mysterious concept, strictly connected with actions - filters. As we see in [UnitPercentageDiscountAction implementation](https://github.com/Sylius/Sylius/blob/40f2299456126decb86b60f11403f5793630b11c/src/Sylius/Component/Core/Promotion/Action/UnitPercentageDiscountAction.php#L37), there are two filters configured - *Taxon* and *PriceRange*. [Taxon filter](https://github.com/Sylius/Sylius/blob/9eb2821d0b464324423e49d30106e3349a793adb/src/Sylius/Component/Core/Promotion/Filter/TaxonFilter.php) can be used to filter (:smile:) items from specific taxon on which promotion should be applied. Simple and elegant.

*Suma sumarum*, in your case, you should configure 3 things:
- rule from taxon **books**
- action with 15% off
- filter for action on taxon **books**

And here we are, you can't do this right now 😞  Although we have filters implemented and [even test written for them](https://github.com/Sylius/Sylius/blob/master/features/promotion/receiving_discount/receiving_fixed_discount_on_products_from_specific_taxon.feature) there is no UI for actions filters yet.
![zrzut ekranu 2016-08-11 o 19 52 53](https://cloud.githubusercontent.com/assets/6212718/17598964/3bc09650-5ffd-11e6-8e90-d5f761482011.png)

So you could either abandon this idea **or** wait for filters UI implementation **or** implement it by yourself ;) Hope I've explained everything clearly, sorry for a long answer 😄  🕙

**Comment by gabiudrescu** [comment]
@Zales0123 thanks for the detailed answer. I find it very helpful. 

Due to some business constraints, we cannot abandon the idea nor wait for filters UI implementation in Sylius Vanilla, probably starting next week, we'll be working on this admin UI improvement. It seems like an easy job and we'll try to contribute to Sylius with it, too.

**Comment by gabiudrescu** [comment]
Last night, I read some of the issues and realized the idea of filters has been discussed in #3368, so I think it would be better to move the discussion over there.
