### ISSUE TITLE
Cart Add Action: "_redirect_to" param doesn't work

### ISSUE THREAD

**Issue by DanPhyxius** [Sylius/Sylius#5773]
Hi guys,

maybe i made a mistake but i'm not able to override the redirect on "add to cart" feature.
I use a similar form for the "/cart/add?id=<product_id>" action and the method works well, but it
redirect me to /cart route.

I'd like to override the cart with a custom path and i saw that there is, at the very end of CartItemController:addAction method, the code:

`    return $this->redirectAfterAdd($configuration);`

with the follow:

```
if ($request->query->has('_redirect_to')) {
    return $this->redirectHandler->redirect($configuration, $request->query->get('_redirect_to'));
}
```

but i'm not able to make redirect work. Any help?

Thanks a lot,
Dan

**Comment by bretto36** [comment]
I was able to get this to work. This is my form start code

`{{ form_start(form, {'action': path('sylius_shop_cart_item_add', {'id': product.id, '_redirect_to': errorRedirectPath})}) }}`

**Comment by DanPhyxius** [comment]
Hi @bretto36,

now it works, thank you!! :)
