### ISSUE TITLE
implement slideshow block for new AdminBundle

### ISSUE THREAD

**Issue by videni** [Sylius/Sylius#5777]
I have implemented the slideshow block for the new AdminBundle, but there are several issues remained:

1. When saving SlideshowBlock and ImagineBlock , automatically set the SlideshowBlock as  the parent of ImagineBlock   

2. Can't find the file input for ImagineBlock, when writing behat feature.

Sylius\Behat\Page\Admin\SlideshowBlock\CreatePage
``` 
  $slides = $this->getElement('slides')->findAll('css', 'div[data-form-collection="item"]');
 /**
   * @var NodeElement
   */
   $slide = end($slides);

  $collectionIndex = count($slides) - 1;     //   sylius_slideshow_block_children_0_image

$slide->attachFileToField(sprintf('sylius_slideshow_block_children_%d_image',$collectionIndex),'books.jpg');  //why input with this id doesn't exist?
```

please give me some ideas, so I can continue these work.  the related PR is  [5776](https://github.com/Sylius/Sylius/pull/5776)

**Comment by pjedrzejewski** [comment]
@videni Sorry, see my comment in #5776.
