### ISSUE TITLE
Images not showing up

### ISSUE THREAD

**Issue by napestershine** [Sylius/Sylius#5782]
Hi 

I just installed sylius on AWS with ubuntu apache2 php7.0, MySQL 5.7
I am getting following screen:
![selection_002](https://cloud.githubusercontent.com/assets/8603325/17621412/bc9e0dd0-60b0-11e6-987f-0838fdb730ac.png)

Whats wrong with it?

**Comment by pjedrzejewski** [comment]
Open the image url and you should see the exception or check logs.

**Comment by bretto36** [comment]
Check that all the web/media folder is writable (777)

**Comment by napestershine** [comment]
Thanks for support, it was permission and installation issue. May be new commits in master resolved it as I run composer update it resolved. 

:)
