### ISSUE TITLE
[supportRequest] What would be best approach to convert one order to many on completed state of checkout?

### ISSUE THREAD

**Issue by Mr-Negative** [Sylius/Sylius#5788]
So,  long story short, i need to convert one order to multiple (based and grouped by taxon of every item and other logic but its beside point).
I think i  should do this when in stata machine 

```
 sylius_create_order:
                    on: ["complete"]
                    do: ["@sm.callback.cascade_transition", "apply"]
```

but i can't find where this action is applying this callback and what it is doing.  Any hints?

**Comment by Niiko** [comment]
I don't know if it's the best way, but for instance, i do it with override of Sylius\Bundle\CoreBundle\Controller\OrderController afterPayAction.

```php
/**
     * @param Request $request
     *
     * @return Response
     */
    public function afterPayAction(Request $request)
    {
        $configuration = $this->requestConfigurationFactory->create($this->metadata, $request);

        $token = $this->getHttpRequestVerifier()->verify($request);
        $this->getHttpRequestVerifier()->invalidate($token);

        $status = new GetStatus($token);
        $this->getPayum()->getGateway($token->getGatewayName())->execute($status);
        $payment = $status->getFirstModel();
        $order = $payment->getOrder();

        $orderStateResolver = $this->getOrderStateResolver();
        $orderStateResolver->resolvePaymentState($order);
        $orderStateResolver->resolveShippingState($order);


        $this->getOrderManager()->flush();

        return $this->redirectToRoute(
            $configuration->getParameters()->get('redirect[route]', null, true),
            $configuration->getParameters()->get('redirect[parameters]', [], true)
        );
    }
```

**Comment by pjedrzejewski** [comment]
The story is too short... Converting one order to multiple is easily doable, but your business logic is probably not that simple. We need to more info and perhaps use StackOverflow for that question, we want to migrate the community support there and to slack, to clean up the issues.

**Comment by Mr-Negative** [comment]
Stackoverflow has in this moment very few sylius users :-/. So, i have different adresses( and scheduledDate) for each different orderItem in order/cart. When checkout is completed, i need to sort them and group by this parameters.
So one order:
- one pizza for adress A and date A
- one fish for adress B and date B
- one spaghetti for adress B  and date B
Will be:
two orders:
- one pizza for adress A and date A
second:
- one fish for adress B and date B
- one spaghetti for adress B  and date B

I will need to redistribute adjustments probably too, but it isn't a problem. I need some inspiration where to put this convert order to multiple orders logic.

**Comment by michalmarcinkowski** [comment]
Right after checkout, so either on checkout `complete` transition or `create` transition of order state (depends on your approach to converting the order).
 
Anyway, isn't it more appropriate to simply create two shipments for this order instead of converting it to multiple?
