### ISSUE TITLE
[RFC] Empty admin panel.

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#5790]
Just after sylius installation, should an admin panel be empty? 

![empty admin panel](https://cloud.githubusercontent.com/assets/6213903/17650693/5ca69578-6254-11e6-8629-a8c2c33fc376.png)

**Comment by gabiudrescu** [comment]
as far as you don't install dummy data, I see no problem in showing 0s. in the end, if you're a new venture, you don't have data, yet :)

**Comment by lchrusciel** [comment]
@gabiudrescu yea, sure. I just got used to see some sample data.

**Comment by vesse** [comment]
@lchrusciel  How did you get to the admin panel in the first place? I did

```bash
composer create-project -s dev sylius/sylius-standard acme
cd acme
php app/console sylius:install
npm install
node_modules/.bin/gulp
php app/console server:start 127.0.0.1:8000
```

but cannot see admin panel anywhere nor do any of the URLs I've found work (like `/admin` or `/administration`). The Symfony Profiler Security page shows `[ROLE_USER, ROLE_ADMINISTRATION_ACCESS, ROLE_ALLOWED_TO_SWITCH]` in my roles.

**Comment by lchrusciel** [comment]
@vesse You have missed a `/` at the end of admin route. The "admin" homepage is `http://127.0.0.1:8000/admin/dashboard` in your example.
Admin and shop are totally decoupled, thats why you don't have any button on a shop panel to access it. 

Nevertheless the admin panel is currently unavailable on a master and you can need #5789 to be able to login in.

**Comment by lchrusciel** [comment]
@gabiudrescu of course, it was so obvious. It is not a problem with empty admin, it is a problem with our installer. Because we have problem #5762 I didn't set up a database before calling a `sylius:install`. But I didn't notice, that in this case, it won't ask to load sample data. So I guess, I can close this issue. 
So, to finally set up a Sylius and see sample data you can either go this way:
1. Don't have database
2. Call `sylius:install`
3. Call `sylius:fixtures:load`
or: 
1. Set up a database `doctrine:database:create`
2. Set up a schema `doctrine:schema:create`
3. Call `sylius:install`
