### ISSUE TITLE
The service “security.authentication.manager” has a dependency on a non-existent service “sylius.user_provider.name_or_email”

### ISSUE THREAD

**Issue by carbide20** [Sylius/Sylius#5796]
Hi,

I'm installing a new copy of Sylius on my Mac under PHP 7.0.8.

I'm following the instructions exactly, but run into an issue when I run:

It throws the following error:

`The service “security.authentication.manager” has a dependency on a non-existent service “sylius.user_provider.name_or_email”`

I've also tried doing a 'composer update', but it throws the same error after running the command:                                                                                 
  
`An error occurred when executing the "'cache:clear --no-warmup'" command `

Additionally, trying to run "cache:clear --no-warmup" from the root dir of the Sylius install throws the same error.

Please let me know what additional info I can provide to help solve this. Thanks!

**Comment by carbide20** [comment]
It appears that when I ran this: 

`php composer.phar create-project -s dev sylius/sylius-standa‌​rd somefolder `

as documented here: docs.sylius.org/en/latest/book/installation.html

I got the issue as reported. However, when I installed using:

`php composer.phar create-project sylius/sylius `

as documented here: https://github.com/Sylius/Sylius#quick-installation

it worked as expected. I'm not sure if this was the result of the folder, or of the -s dev option, and am not sure if this is a bug any longer, or a discrepency between the two pages of documentation, or simply user error on my part. Would love to hear someone weigh in on whether this is important, or if I should simply close it out now that my issue is fixed. Thanks!

**Comment by lchrusciel** [comment]
In #5539 the signature of a provider has changed, and we have forget to update Sylius-Standard to this changes. Sylius-Standard is a separate project, that is just based on it, so you should make an issue there. Nevertheless, thanks for reporting, we would try to fix it as soon as possible.

**Comment by gorkalaucirica** [comment]
@carbide20 @lchrusciel I created a PR updating the security.yml in Sylius-standard, that should fix the issue

**Comment by pamil** [comment]
Should be already solved as Sylius-Standard just got updated.
