### ISSUE TITLE
Shipping availability checker

### ISSUE THREAD

**Issue by yaidelferrales** [Sylius/Sylius#5802]
I'm building a shipping module for FEDEX, and I want to check if it's possible to send a package to an address. In order to do that, I want to build a checker that allows me to know if, depending on the delivery time, I can send the package or not. The checkers I have seen in sylius are executed for every shipping method. So my question is: can I make a checker for an specific shipping method and how to register that checker? If not possible, how can I know the name of the method in the checker?

**Comment by michalmarcinkowski** [comment]
Hi @yaidelferrales from what I understand it should be possible. Please post such questions on stackoverflow under "sylius" tag. It's the official support channel.
