### ISSUE TITLE
Braintree Integration

### ISSUE THREAD

**Issue by DanPhyxius** [Sylius/Sylius#5803]
Hi guys, hi @pjedrzejewski, 

is anyone working (or maybe, it's done) on Braintree integration for Sylius?
I need that for a customer so i would like to understand if i have to make it from myself! :)

If not, what is a right way to do that? 

Thanks a lot,
Dan

**Comment by pjedrzejewski** [comment]
Hi @DanPhyxius, you should first check if Payum supports braintree properly, I have seen some integrations. This can be helpful too: http://stackoverflow.com/questions/23995316/sylius-adding-a-new-payum-gateway-rabobank-omnikassa

**Comment by DanPhyxius** [comment]
Thank you @pjedrzejewski for your answer.
It seems there is no plug&play support for braintree, so we'd to create it.

Also, i'm looking for "bank transfer case" on Sylius, something like:

- order is completed
- customer make a bank transfer payment
- back office set the order as "payed"

Is there anything like that in Sylius? 

Thank you! :)

**Comment by bretto36** [comment]
@DanPhyxius with regards to the bank transfer payment method. I think that already exists. You can utilise the built in offline method. Then add instructions when you create the payment method in the admin area. You can already mark an order as paid at any stage in the Admin area order show page. So that can be used when the payment has been transferred

**Comment by jeroendesloovere** [comment]
Hi @DanPhyxius any news about a braintree Bundle for Sylius?

**Comment by DanPhyxius** [comment]
Hi @jeroendesloovere,

we integrated BT without a real bundle but with a custom service in our platform, so not actually used a braintree bundle! :)

**Comment by Keloo** [comment]
+1 for the Braintree support.

**Comment by Keloo** [comment]
@DanPhyxius what service did you use?

**Comment by psihius** [comment]
Sylius uses Payum library for payment processing and I saw they have a Braintree gateway module already.

**Comment by garak** [comment]
Any news?
