### ISSUE TITLE
[RFC] Sylius roadmap, timeline and etc.

### ISSUE THREAD

**Issue by liverbool** [Sylius/Sylius#5808]
Hello @Sylius,

First of all, I very appreciate the hard working of everyone, and the direction of Sylius V1 is quite clear and more flexible with shopping platform, coding is simpler and stronger also.

However, it seems that the key feature of many parts were dropped off and we don’t see the roadmap of bringing those features back (e.g. #5650).

We have several projects that we are trying to keep update on Sylius version and try to determine period of time for the release, which is impossible if we don’t know period time of Sylius roadmap.

We would like to update features of Sylius if possible, but the problem is our team are not fluent in Behat writing which very difficult in PR also.

We are very pleased if Sylius will share  insider information (Roadmap, Timeline) of dev with us/community.

:) Thank you.
 cc. @pjedrzejewski

**Comment by Niiko** [comment]
Same here, for a new project which will start on half september

**Comment by liverbool** [comment]
According to the road map, I think the it is more obvious about the planning and many parts, which aren't  related with the shopping system, will be temporary excluded on version 1.0.

So, version 1.0 should be going as the plan. But sadly about the RBAC, it should be an important basic system (don't sure, how's a plan for ACL).

I think that the highest priority system should be an inventory system which is the core of system e.g. Stock clearance, inventory tracking, #5855 and more. (include @Niiko tagged)

It would be pleased, if Community could participate scrum in the backlogs. So Community could help to prioritise the works.

We are really appreciate your team !

cc. @pjedrzejewski @michalmarcinkowski @pamil

**Comment by pjedrzejewski** [comment]
@liverbool We definitely want to include the community more in the backlog building! We are constantly brainstorming about the possibilities and will take some actions soon.

**Comment by pjedrzejewski** [comment]
Plan is pretty clear now, let's do this! :)
