### ISSUE TITLE
Currency drop down not showing

### ISSUE THREAD

**Issue by napestershine** [Sylius/Sylius#5809]
Hi

as per code in sylius, when I have more than one currency it should show an option on front end for changing currency but I do not show it. 

Can you provide any solution?

Thanks

**Comment by pjedrzejewski** [comment]
@napestershine Did you enable it for the channel? (edit channel)

**Comment by napestershine** [comment]
@pjedrzejewski  Sorry But I didn't understand your question. I am attaching screen shots. May be it will make clear the situation.

![selection_001](https://cloud.githubusercontent.com/assets/8603325/17728110/333c1b4e-647b-11e6-86a2-927436fcc5c5.png)
![selection_002](https://cloud.githubusercontent.com/assets/8603325/17728112/334f6136-647b-11e6-85b7-0cc0fa085e0e.png)
![selection_003](https://cloud.githubusercontent.com/assets/8603325/17728111/334da6ca-647b-11e6-9eb8-ab65317a6758.png)

**Comment by pjedrzejewski** [comment]
@napestershine When you edit a channel, you can select which currencies are enabled for this particular channel. :)

**Comment by napestershine** [comment]
@pjedrzejewski  okay now it's showing up. Thanks so much :)

**Comment by napestershine** [comment]
Is it possible to have exchange rates automatically somehow on some API or some other way?

**Comment by michalmarcinkowski** [comment]
@napestershine you can use API (Currency edit) and/or implement service that will operate directly on entity.

Closing as the main issue was resolved. Please post such questions on stackoverflow, it's the official support channel.
