### ISSUE TITLE
Currency not found

### ISSUE THREAD

**Issue by napestershine** [Sylius/Sylius#5812]
Hi
I created a new channel,  In_in, assigned currency to INR. But when I run the app I got this page

![selection_004](https://cloud.githubusercontent.com/assets/8603325/17728416/bbf54ec8-647c-11e6-83fd-f4d9dc73aed5.png)

**Comment by napestershine** [comment]
I try to disable another channel, but same problem persists. Finally when I deleted new channel error gone. What's solution?

**Comment by lchrusciel** [comment]
It is not a problem of currency, but it is channel resolving case. On a symfony toolbar you can choose which channel you want to use, and error would be gone. It will be just saved in cookie. Channel should be resolved also based on different urls.

Unfortunately, an error message can be `quite` misleading. We should rename this issue, and leave it open until we will present something more meaningful.

**Comment by napestershine** [comment]
@lchrusciel  can you explain about channels in sylius, I am bit confused in it

Thanks

**Comment by lchrusciel** [comment]
Check our great documentation -> [Channels](http://docs.sylius.com/en/latest/book/channels.html) 🎉

**Comment by napestershine** [comment]
Is it possible to load a specific channel for specific country?

**Comment by lchrusciel** [comment]
If you would prepare a proper url mapping, why not?

**Comment by napestershine** [comment]
@lchrusciel  Thanks so much :)

**Comment by michalmarcinkowski** [comment]
@napestershine have you figure out what was the issue here?
