### ISSUE TITLE
Can't access Crud for admin user section in admin, error 403

### ISSUE THREAD

**Issue by enekochan** [Sylius/Sylius#5826]
I've just done a Sylius/Sylius-Standard installation and then updated Sylius/Sylius to the latest version (doing a `composer update` it is updated to f9005a78d501ba3f261d8592cc1dedd110d23047) and although I can see the new menu option for Administrator users management (added in https://github.com/Sylius/Sylius/pull/5797) in the admin area I get a "403 Access Denied error" if I try to access it. I've checked that currently logged in user has `ROLE_ADMINISTRATION_ACCESS `. Am I missing something?

**Comment by pjedrzejewski** [comment]
@enekochan Try running ``sylius:rbac:initialize``.

**Comment by enekochan** [comment]
Thanks! It worked :) I had seen the SyliusRbacBundle among the other bundles but didn't know what it was for.
