### ISSUE TITLE
Call to a member function getCode() on null

### ISSUE THREAD

**Issue by napestershine** [Sylius/Sylius#5827]
HI

I installed Sylius yesterday. Everything went well. Today I run composer update. It went well too. Then I run 
`$php app/console sylius:install`

I got following screen:
![selection_006](https://cloud.githubusercontent.com/assets/8603325/17760655/f9402544-651e-11e6-9274-699b3afef4f1.png)

Thanks

**Comment by GSadee** [comment]
Please look at existing issues and do not duplicate them: https://github.com/Sylius/Sylius/issues/5762

**Comment by michalmarcinkowski** [comment]
Closing in favor of #5762.
