### ISSUE TITLE
CustomerGroupRuleChecker is not defined in Core\services

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#5831]
I have the following error : 

```
Rule checker service "customer_group" does not exist, available rule checker services: 
 "cart_quantity", "contains_taxon", "item_total", "nth_order", "shipping_country", "taxon", 
"total_of_items_from_taxon"
```

Effectively, `customer_group`  is now missing from  `sylius.promotion_rule_checker` definition in `services.xml` , but the Class and Type are still there in the **CoreBundle**.

Are you planning on removing it or is it a bug ?
thanks

**Comment by pjedrzejewski** [comment]
We have disabled it for now, but hopefully it comes back for the 1.0 release.

**Comment by pamil** [comment]
Related to #6436.

**Comment by michalmarcinkowski** [comment]
Closing in favor of #6436.
