### ISSUE TITLE
[CRITICAL] Use of Undefined class constant 'ShipmentInterface::STATE_RETURNED'

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#5834]
Hi,
This constant does not exist anymore... and this blocks a lot of things when working with orders ...

Bad use of constant is here : https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/Model/Order.php#L463

**Comment by Niiko** [comment]
Strange, i found it in the interface https://github.com/Sylius/Sylius/blob/1b91d94b8aaa404a6e25d2113497f0405a7ca291/src/Sylius/Component/Shipping/Model/ShipmentInterface.php#L30

**Comment by tchapi** [comment]
yes, but not in master : https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Shipping/Model/ShipmentInterface.php

**Comment by Niiko** [comment]
Oh, right :/

**Comment by tchapi** [comment]
I reckon this has now been fixed 👏
