### ISSUE TITLE
Set curl SSL Version for PayPal

### ISSUE THREAD

**Issue by gseidel** [Sylius/Sylius#5837]
I was using the Sylius Project (v0.19.0) with demo data and add a PayPal payment method (paypal_express_checkout) and add my credentials to the Payum config. But when i try to checkout my cart i got following error.

> cURL error 35: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (see http://curl.haxx.se/libcurl/c/libcurl-errors.html

I found out that the PayPal API has changed since this year and SSLv3 is not supported anymore. 

https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1913&viewlocale=en_US#TLS

That's ok, but i can't set the version of the ssl connection globally. It's only possible on the curl call itself (CURLOPT_SSLVERSION). I don't know if someone can fix it in this project, because i'm not so familiar with the payment module. I know that guzzle has an option for that and payum does not depend on a certain http client. So maybe someone can fix it here :)

I read that upgrading my php version can fix that problem but im already using PHP 5.6.7 and OpenSSL 1.0.2f

**Comment by gseidel** [comment]
@makasim i see you are familiar with sylius and author of payum, maybe you can help here?

**Comment by makasim** [comment]
long story short, you have to make sure you have the cipher required by paypal, most likely it will be tls1_2 or so. You can simply achieve that by making sure you have the latest version of php, curl, openssl and the kernel. 

There are more info on the issue: https://github.com/Payum/Payum/search?q=ssl&type=Issues&utf8=%E2%9C%93

**Comment by gseidel** [comment]
@makasim thanks for your quick answer, i will take a deeper look into it .
