### ISSUE TITLE
Wrong Cart Total Price with Empty Cart

### ISSUE THREAD

**Issue by DanPhyxius** [Sylius/Sylius#5840]
Hi guys,

i found out that there is an issue on online demo of Sylius when you create a new account.
In this case, after account creation, i saw that there is a non zero cart total price ($1.10) with empty cart.

<img width="1055" alt="schermata 2016-08-19 alle 10 08 49" src="https://cloud.githubusercontent.com/assets/4693301/17803200/43b3773a-65f5-11e6-8a1a-2c5a627be7ba.png">

Is this an issue? 

P.S.: I would like to male QA for /admin (new version) on demo version. What is the admin credentials? With a new account i got a 403 forbidden. :) 

Thank you,
Dan

**Comment by Niiko** [comment]
There is a separation with users, there are shop users (as you create it) that can only access shop, and admin users for /admin.

Credentials are 
login : sylius@example.com 
password : sylius

**Comment by DanPhyxius** [comment]
Thank you @Niiko!

I was trying to do sign in with admin credentials on shop users login!

**Comment by DanPhyxius** [comment]
I reopen issue for money bug!

**Comment by michalmarcinkowski** [comment]
The default shipping method is assigned to the cart on each cart change (e.g. user log in), that causes non zero total for empty cart. This is a bug since it should not assign anything to an empty cart and we're already working on a fix.

**Comment by michalmarcinkowski** [comment]
Should be fixed in https://github.com/Sylius/Sylius/pull/5845. Please reopen if still relevant.
