### ISSUE TITLE
Installing assets. 

### ISSUE THREAD

**Issue by sruj** [Sylius/Sylius#5849]
step by step I follow http://docs.sylius.org/en/latest/book/installation.html#

In part Installing assets I did:
- sudo apt-get update
- sudo apt-get install nodejs
- npm install
- npm run gulp
- php app/console assets:install
- php app/console server:start 127.0.0.1:8000

and visited http://127.0.0.1:8000/ is working but without assets (there is no css style and js)

/web/assets/  directory is empty

**Comment by enekochan** [comment]
Try running just `gulp` instead of `npm run gulp`, that works for me. If you need it install gulp globally.

**Comment by sruj** [comment]
that works! thanks.
