### ISSUE TITLE
Big store with large number of products

### ISSUE THREAD

**Issue by DanPhyxius** [Sylius/Sylius#5850]
Hi guys!

For a customer, we have to create a big multichannel store with more than 50k of products for store.

Lately we have followed a lot the development of Sylius and we would like to use that as Core for this project. 

Obviously, we can't use the MySQL based solution for search and filtering products, so we thought about Elastic Search integration.

Is there any way to use ElasticSearch for products? If yes, how we could keep products into Elastic sync with product events (such as "add cart" event)?

Our problem is to figure out if we can keep synchronized the Elasticsearch indexes.

Any idea?

Thank you,
Dan

**Comment by gabiudrescu** [comment]
hi @DanPhyxius.

I'm product owner for bestvalue.eu, which uses Sylius, and we rely on ElasticSearch only for listings. anything else is MySQL - product page, cart etc.

AFAIK, we keep Elastic in sync with product information via lifecycle events. once in a while, if things get out of sync, we run fos:elastica:populate and in a couple of minutes, everything is up and running.

I highly recommend you this if you want to learn more on the subject: https://github.com/Sylius/Sylius/issues/4659#issuecomment-204894804

**Comment by DanPhyxius** [comment]
Hi @gabiudrescu,

thank you for your answer, it's what we're looking for. 
We're trying to get it work! 

Have a nice day,
Dan

**Comment by gabiudrescu** [comment]
you're welcome. I'd close this issue if I would be you, so we can keep the issue list on Sylius clean :)
