### ISSUE TITLE
Do Sylius have product searching feature?

### ISSUE THREAD

**Issue by napestershine** [Sylius/Sylius#5852]

**Comment by steffenbrem** [comment]
The recommended way is to use ElasticSearch and use a good bundle, such as https://github.com/FriendsOfSymfony/FOSElasticaBundle to integrate it into Symfony 2 in a nice way. Take a look at it's usage (https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/usage.md) to get an impression of how easy the API is to working with it.

Sylius used to have a `SearchBundle` but that has been removed. It is simply enough to do it yourself though, the bundle makes it very easy.
