### ISSUE TITLE
Can't delete product

### ISSUE THREAD

**Issue by napestershine** [Sylius/Sylius#5853]
Hi

In my sylius admin panel when I try to delete any product it ask for confirmation and when I click yes , it just refresh the page but still shows the same dummy products there. It doesn't get delete.

Any solution?

Thanks

**Comment by tchapi** [comment]
Is there any error message ? There should be. It could be that your products are used in an order for instance

**Comment by napestershine** [comment]
No there was no error showing. It just refresh the page. And its a fresh installation.

**Comment by michalmarcinkowski** [comment]
Fixed already.
