### ISSUE TITLE
Route 'sylius_user_security_login' does not exist anymore

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#5859]
In **UserBundle\Controller\UserController**, line  [217](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/UserBundle/Controller/UserController.php#L217), there is still a reference to a deleted route : 

```
$redirectRouteName = $request->attributes->get('_sylius[redirect]', 'sylius_user_security_login', true);
```

should be : 

```
$redirectRouteName = $request->attributes->get('_sylius[redirect]', 'sylius_shop_login', true);
```

There are some other occurences throughout the file too.

**Comment by lchrusciel** [comment]
Can be closed /cc @michalmarcinkowski

**Comment by tchapi** [comment]
Well, `sylius_user_security_login` is still present in the SecurityController and this route does not exist ...

**Comment by lchrusciel** [comment]
Oh, sorry. My mistake. Thanks @tchapi
