### ISSUE TITLE
OrderPricesRecalculator fails fetching user groups

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#5860]
Hi,
When creating a new user from the frontend, **OrderPricesRecalculator->process()** fails to get the groups of the customer, and gives us a 500 : 

    Call to a member function toArray() on null

The problem is [here](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/OrderProcessing/OrderPricesRecalculator.php#L43): 

     $context['groups'] = $customer->getGroups()->toArray();

I guess that `$customer` is not initialized yet and `getGroups()` return `null`.

Anything we can do to avoid this ?
Thanks a lot for your help !

**Comment by patrick-mcdougle** [comment]
`getGroups()` should always be an arrayCollection. It's initialized in the constructor of Customer. Perhaps something else is going on?

**Comment by pjedrzejewski** [comment]
@tchapi Does it happen on current master?

**Comment by tchapi** [comment]
I'll try asap and tell you. I agree with @patrick-mcdougle, since it's initialized as an \ArrayCollection in the constructor, but I still had the problem when posting this issue.

**Comment by tchapi** [comment]
Ok, blunder on my side — thanks for your help, it directed me to the culprit.
