### ISSUE TITLE
Shipping categories ?

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#5861]
Hi
I noticed that in the 1.0 branch, products' shipping categories are not taken into account when checking out the cart — the rules of each shipping categories are not taken into account and all shipping methods are displayed, regardless of the products

Is this normal ? Is there a new configuration / thing to do to make this work as intended ?

thanks

**Comment by steffenbrem** [comment]
From what I can tell there is no code implemented for this yet. To make it work you should look into the `MethodsResolverInterface`. If you use the core, you could base yours on `ShippingMethodsByZonesAndChannelResolver`.

**Comment by steffenbrem** [comment]
I guess this is fixed by adding the `ShippingMethodEligibilityCheckerInterface` to the `ShippingMethodsByZonesAndChannelResolver`.

If someone from @Sylius/core-team could confirm, I could work on a PR.

**Comment by steffenbrem** [comment]
@tchapi Check out the PR I just submitted for a potential fix for your issue.

**Comment by tchapi** [comment]
Hi @steffenbrem — your PR looks good, but why do they remove / change that in the first place ? It was perfectly working before... I'll try your code when I have a chance, Thanks !
