### ISSUE TITLE
Error when visiting: http://demo.sylius.org/admin/routes/new

### ISSUE THREAD

**Issue by jeroendesloovere** [Sylius/Sylius#5879]
**Problem**
Can't create a new route.

**Steps to reproduce**
* Open and login to the [sylius demo](http://demo.sylius.org/admin)
* Click in the left navigation on "[routes](http://demo.sylius.org/admin/routes)"
* Click in the right on "[Create](http://demo.sylius.org/admin/routes/new)"

Then the error occurs
![schermafbeelding 2016-08-24 om 09 55 54](https://cloud.githubusercontent.com/assets/588616/17922756/f5c7f84e-69e0-11e6-8439-0ba97275fdd8.png)
![schermafbeelding 2016-08-24 om 09 57 14](https://cloud.githubusercontent.com/assets/588616/17922797/256b1d74-69e1-11e6-9f33-cfe7c44a7d81.png)

**Comment by michalmarcinkowski** [comment]
Fixed.
