### ISSUE TITLE
How to install a Sylius platform EQUAL TO the online demo one?

### ISSUE THREAD

**Issue by ulisse73** [Sylius/Sylius#5880]
Hi to all,
please, I'm creating a new Sylius based project and I'd love to have the same version of the online demo, mostly the same look and feel (http://demo.sylius.org/).
Someone could quickly tell me which is the correct and exact version to download?

Very thanks to you all.

**Comment by bnd170** [comment]
Wich php version you have?

**Comment by ulisse73** [comment]
5.5.9, but I know that the demo version requires ^5.6 minimum version.
I will proceed to install it before the installation.

**Comment by bnd170** [comment]
Update php to ^5.6 then try to install sylius :)

**Comment by ulisse73** [comment]
Sylius/Sylius or also Sylius/Sylius-Standard?
And what version, dev-master?

**Comment by lchrusciel** [comment]
@ulisse73 If you want to see the closest site to the current demo, you should check a dev-master of Sylius/Sylius. New demo was set up about one week ago.

**Comment by ulisse73** [comment]
Thanks @lchrusciel !

**Comment by ulisse73** [comment]
Hi @lchrusciel,
I updated my php version to 5.6 and proceed to install the dev version of Sylius/Sylius.
The installation was successfull, but the app doesn't shows the default Sylius theme (no CSS), and then the admin created user is not able to login (no users in db table).

How can I solve?
Thanks.

**Comment by lchrusciel** [comment]
@ulisse73 did you run `npm install` and `npm run gulp`? In which table did you look for that? `sylius_admin_user`?

**Comment by ulisse73** [comment]
Also running gulp, I've no theme.
I noticed that in the sylius_channel table, in the row relative to default channel, the 'theme_name' field value is equal to NULL!  May be this the reason?

**Comment by ulisse73** [comment]
About the theming, all is ok.
But I can't login as admin. (With or without load sample data).
