### ISSUE TITLE
Remove resource dependency from mailer (make it optional)

### ISSUE THREAD

**Issue by sagikazarmark** [Sylius/Sylius#5881]
As far as I can see, resource is not a hard dependency for mailer. I found it a little bit hard to use in non-sylius projects as it requires a bunch of additional dependencies, which I might not even need. In the most simple cases, I only want to configure mails in a YAML file, why do I need doctrine and the resource for that?

Therefore, I propose the following:
- Make resource optional
- Separate the config email provider part from the default email provider
- Make resource bundle optional in mailer bundle

What do you think? I haven't considered if it's a BC break or not (it probably is from a dependency point of view, but it shouldn't be on the code level).

**Comment by pjedrzejewski** [comment]
Would be very cool, I just fear it requires too much work to decouple it from ResourceBundle...

**Comment by sagikazarmark** [comment]
I do not recommend any breaking changes. My recommendation to make the resource stuff optional dependency and leave all implementations where they are at the moment. That would allow people to use mailer without resource if they want. For example: in a project I only use YAML configuration.

So it's not about completely decoupling. I do think it makes sense to have some default implementations in place.

**Comment by sagikazarmark** [comment]
Would you accept a PR?

**Comment by Koc** [comment]
@Zales0123 looks like it is already fixed, isn't?

**Comment by michalmarcinkowski** [comment]
Yes it is :) Thanks Konstantin for helping with support!
