### ISSUE TITLE
theme specific translation are reported as "missing" in the profiler

### ISSUE THREAD

**Issue by havvg** [Sylius/Sylius#5883]
When using translation files on a theme basis (by putting them into `app/Resources/themes/my-theme/translations/messages.en_US.yml` etc.), all used keys are reported missing, although all of them are correctly translated by the system.

**Comment by gabiudrescu** [comment]
are you sure the missing keys are not from en locale, instead of en_US?

maybe you could post a screenshot of your profiller for a better understanding of the problem.

**Comment by bnd170** [comment]
Did you clear cache? Symfony2 needs to clear cache after dictionary create, dev envoirment inclusive.

**Comment by havvg** [comment]
Yes, I cleared the cache and it's working as expected (the translation is correct).

The only thing is the profiler is reporting any translation message as missing as soon as the files are located in `app/Resources/themes/my-theme/translations/*.yml`

A minimal example (`de_DE` is the `default_locale` in this example):
![screen shot on 2016-08-25 at 17-41-35](https://cloud.githubusercontent.com/assets/126898/17975798/62f4e142-6aeb-11e6-922f-8117b817298c.png)

**Comment by michalmarcinkowski** [comment]
@pamil @NeverResponse is it still an issue?
