### ISSUE TITLE
sylius/core 1.0.x-dev requires sylius/customer ^1.0 -> no matching package found.

### ISSUE THREAD

**Issue by emodric** [Sylius/Sylius#5887]
I'm using `sylius/core` as a dev dependency to one of my bundles for unit tests.

With 0.19, everything works fine, I can install the package and use it.

However, on `^1.0@dev`, I get the following error:

```
  Problem 1
    - Installation request for sylius/core ^1.0 -> satisfiable by sylius/core[1.0.x-dev].
    - sylius/core 1.0.x-dev requires sylius/customer ^1.0 -> no matching package found.
```

**Comment by michalmarcinkowski** [comment]
You should modify your `composer.json` file and add `minimum-stability: dev` to use unstable packages.

**Comment by emodric** [comment]
I did. That's not the issue. The issue is that `sylius/customer` package does not exist at all on Packagist, in any version.

https://packagist.org/packages/sylius/customer

**Comment by michalmarcinkowski** [comment]
Probably it's not added to the subtree-split, thanks for reporting. /cc @pjedrzejewski

**Comment by emodric** [comment]
Hi @michalmarcinkowski @pjedrzejewski,

Would it be possible to add `sylius/customer` subtree split to Packagist any time soon to fix installs of `sylius/core`?

Thanks!

**Comment by michalmarcinkowski** [comment]
Thought it's already done... Unfortunately @pjedrzejewski is out of office, so last week of September is the earliest date.

**Comment by pamil** [comment]
Also blocks #6031, #6032.

**Comment by pjedrzejewski** [comment]
@emodric I hope to have a look at this soon. Thanks for your patience! :)

**Comment by pamil** [comment]
Should be solved by now - https://packagist.org/packages/sylius/customer

**Comment by michalmarcinkowski** [comment]
@emodric please reopen if still an issue.

**Comment by emodric** [comment]
Works fine, thanks!
