### ISSUE TITLE
[Docs] Models are not in bundle, but in component

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#5901]
For example, in this file `docs/bundles/SyliusPromotionBundle/models.rst` we have: All the models of this bundle are defined in Sylius\Bundle\PromotionBundle\Model.

But in PromotionBundle there is no Model folder...
![image](https://cloud.githubusercontent.com/assets/5156054/18005885/76071498-6ba5-11e6-9f3d-5256de0f7dd8.png)

While in component:
![image](https://cloud.githubusercontent.com/assets/5156054/18005917/9d45308a-6ba5-11e6-8519-17952c924854.png)

Is it me or the docs should be updated?

**Comment by bnd170** [comment]
For those who already have installed bundles with models in the Component directory, is there any solution to pass them to the Bundles folder?

**Comment by TheMadeleine** [comment]
@pjedrzejewski, @michalmarcinkowski - Solved by #5904

**Comment by michalmarcinkowski** [comment]
@TheMadeleine have you checked that the issue was only in `Promotion` docs?

**Comment by TheMadeleine** [comment]
Not yet, but I will check that today ;)
