### ISSUE TITLE
[ ResourceBundle ] - Criteria not really filtered if the option paginate false is defined

### ISSUE THREAD

**Issue by jvahldick** [Sylius/Sylius#5905]
There is something missing on https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Controller/ResourcesResolver.php#L33

If the route has some criteria, it isn't really filtered when the option paginate: false is defined.

**Comment by bretto36** [comment]
You should make a Pull Request for this

**Comment by jvahldick** [comment]
I'll fix this night together with #5857

**Comment by michalmarcinkowski** [comment]
Fixed.
