### ISSUE TITLE
[payum/payum-bundle] required version in sylius/sylius and sylius/payum-bundle are different 

### ISSUE THREAD

**Issue by Pitoune** [Sylius/Sylius#5909]
The required version for package payum/payum-bundle are different in sylius/sylius and sylius/payum-bundle.
- https://github.com/Sylius/Sylius/blob/v0.19.0/composer.json#L54
- https://github.com/Sylius/Sylius/blob/v0.19.0/src/Sylius/Bundle/PayumBundle/composer.json#L30

**Comment by michalmarcinkowski** [comment]
Fixed already.
