### ISSUE TITLE
Error on calculating taxes

### ISSUE THREAD

**Issue by sprik** [Sylius/Sylius#5913]
Hi,

I configured tax rate for my product but seems that the calculation is not correct

Here an example
![schermata 2016-08-29 alle 18 39 56](https://cloud.githubusercontent.com/assets/4373852/18059215/3c6e65fe-6e18-11e6-8925-b9dec55ffd60.png)

My item is 89€ but 22% is 19,58€ not 16,05€
I configured 22% as included in price.

**Comment by michalmarcinkowski** [comment]
If you configured your tax rate as 22% included in price then everything is correct:

Price of a product without tax: **72,95€**
Tax: **16,05€** (72,95 * 22%)
Total price with tax included: **89,00€**

Where do you see a mistake?

We probably should add examples of tax rates excluded/included in price to the docs. /cc @TheMadeleine

**Comment by sprik** [comment]
you're right!!!

maybe you should add some examples!

Thanks
