### ISSUE TITLE
Create product archetype with option leads to 500 because of translation = null

### ISSUE THREAD

**Issue by Sicaine** [Sylius/Sylius#5922]
Hi,

we are using sylius v0.19 and changed the locale to de_DE.

When you create an product archetype in Sylius Admin and add an option to it, the admin page product archetype fails with a 500. The 500 is issueed because the Options name is null.

There was a bug, which i can't find anymore, about doctrine which doesn't get all translations automatically when there is some subquery or something similiar.

    public function getName()
    {
        return $this->translate()->getName();
    }

**Comment by pjedrzejewski** [comment]
Sorry, but archetypes are removed in branch v1.0.x and we won't be releasing bugfixes for v0.19.x. Generally you should not change your locale in parameters.yml, when you have something in the database already.
