### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by coll3ctor** [Sylius/Sylius#5924]
Hello!

I tried to install Sylius standart edition (not for contributing) using rules from this page: http://sylius.org/get-started

But, after that i got this:

<img width="932" alt="Sylius installation trouble" src="https://cloud.githubusercontent.com/assets/1884457/18087937/404203ae-6ec0-11e6-9c9e-fdac8c41ed01.png">

So, there are messages:

``
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for jeremykendall/php-domain-parser 3.0.0 -> satisfiable by jeremykendall/php-domain-parser[3.0.0].
    - jeremykendall/php-domain-parser 3.0.0 requires ext-intl * -> the requested PHP extension intl is missing from your system.
  Problem 2
    - Installation request for league/uri 4.1.1 -> satisfiable by league/uri[4.1.1].
    - league/uri 4.1.1 requires ext-intl * -> the requested PHP extension intl is missing from your system.
  Problem 3
    - league/uri 4.1.1 requires ext-intl * -> the requested PHP extension intl is missing from your system.
    - payum/payum 1.3.2 requires league/uri ~4.0 -> satisfiable by league/uri[4.1.1].
    - Installation request for payum/payum 1.3.2 -> satisfiable by payum/payum[1.3.2].
``

Help me pls, how i can install Sylius ?

**Comment by lchrusciel** [comment]
Please, ask such a question on stackoverfllow, under Sylius tag.

**Comment by mbabker** [comment]
The answer's right in the message

> the requested PHP extension intl is missing from your system

You need to install PHP's `intl` extension.  `apt-get install php-intl`, `brew install phpXX-intl`, or whatever installation method your system is using will do it.  Or if you're compiling PHP yourself, pass the `--enable-intl` argument into your configuration command.

**Comment by coll3ctor** [comment]
@mbabker yea, thanks, i've installed this extension and installation was successful! thank you!

**Comment by VladyslavDP** [comment]
I have the same problem, but I've installed intl extension. What is the problem?

**Comment by coll3ctor** [comment]
@VladyslavDP, i think you should watch what another extensions you need to install, may be it is not just intl.
