### ISSUE TITLE
[RFC][Behat] Inventory units consistency

### ISSUE THREAD

**Issue by michalmarcinkowski** [Sylius/Sylius#5934]
Right now in our feature files we use `items` instead of `units` for inventory steps e.g. `there is 1 item of product "PHP T-Shirt" available in the inventory`

In order to have uniform dictionary and make it consistent with implementation, when talking about inventory units (number of units of a product available in the inventory) IMO we should use the word `unit` instead of `item`. I'm not an expert in english eCommerce dictionary, but I think it will be more understandable for everyone. WDYT?

**Comment by gabiudrescu** [comment]
IMO, unit is more appropriate as it is also easier to associate it with SKU - stock keeping unit. 

should item be used in a non-inventory context such as product page, listing etc. while unit whenever it's a cart / checkout / inventory context?
