### ISSUE TITLE
Duplicate Menu displaying in Account Area

### ISSUE THREAD

**Issue by bretto36** [Sylius/Sylius#5942]
Menu appears twice in the latest version see screenshot 
![capture](https://cloud.githubusercontent.com/assets/6217994/18128732/9ac1613e-6fca-11e6-8e39-d8661ffc20ac.PNG)

I can't figure out what's causing it. Seems to call the list block twice (once in the root block) and then a second time for no reason.

**Comment by michalmarcinkowski** [comment]
It's probably because of update to knp menu bundle 2.0, looks similar to #5867. Thanks for reporting!

**Comment by bretto36** [comment]
I have tried fixing this but i'm not sure if it's a good fix.
