### ISSUE TITLE
Checkout api has been removed by #5814

### ISSUE THREAD

**Issue by alecslupu** [Sylius/Sylius#5943]
In the #5814 @pamil has removed The Checkout Api Is there any plan to refactor that, or will be removed ?

At the moment Sylius/Sylius and Sylius/Sylius-Standard are not in sync, therefore, checkout API on Sylius/Sylius is broken.

**Comment by ylastapis** [comment]
Yep here : https://github.com/Sylius/Sylius/pull/5896

**Comment by alecslupu** [comment]
Is there any branch on 1.0-dev that i could acually use to make a api based ecommerce ?

**Comment by ylastapis** [comment]
I don't think so.
You should wait for this PR to be merged. Sylius team is working hard to release the 1.0 by the end of [november](http://sylius.org/blog/sylius-roadmap-update).

@Zales0123 any news on this one ?

**Comment by Zales0123** [comment]
@ylastapis I'm pretty sure I'll able to make it mergable until end of the week ;)

**Comment by ylastapis** [comment]
Should be good now. @alecslupu ?

**Comment by michalmarcinkowski** [comment]
Closing as API has been reworked.
