### ISSUE TITLE
Payment of 0€ order

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#5961]
Hi
When I have a cart that totals 0€ (_or whatever currency_), for example due to promotions being applied, and when I have `paypal_express` configured (and working properly), the order will never transition to "paid". 

It's getting stuck at the **thank-you** page and Payum never seems to acknowledge that the order is 0€ so that it's actually paid...

Any configuration I'm missing ? Or is it normal and I should implement this myself ?

Thanks !

**Comment by bretto36** [comment]
Hmmm, that wasn't the case for mine previously. I have just updated to the latest version so i'll check if this is happening to me as well. Mine was previously marking it as paid when the total was 0

**Comment by tchapi** [comment]
Yeah, that's what I think it should do. I don't think I've modified anything that broke this, but who knows. Tell me when you got a chance to test on your side - thanks a lot !

**Comment by bretto36** [comment]
Can confirm on a fresh install of sylius the order continues to say "Awaiting Payment" as the status. You would have to manually process the order in the show order page in the admin area to get it to go to paid state.

**Comment by tchapi** [comment]
Ok, I will. Thanks !!

**Comment by steffenbrem** [comment]
I guess you should also want to leave out the payment method in the checkout process. I understand that there are solid use-cases for this for things like a one time fixed amount coupon.

**Comment by bretto36** [comment]
Yes it would be handy to skip the payment method section entirely (but it would likely still appear in the steps view at the top), leaving the payment method page in might not be such a big deal for now. Getting the checkout process to mark it as paid is definitely a higher priority.

**Comment by tchapi** [comment]
Agreed @bretto36 !

**Comment by steffenbrem** [comment]
@bretto36 From the top of my head there is a simple way. Just look at the `OrderController::payAction` method. That is the action that get's triggered when you place your order and a payment is still `new`. That way you can prevent any real payment provider redirects and also set the payment to payed if the total is zero.

As a side note, this is better to be handled by the state machine, but if you want a simple solution the above will do it for you for now.

**Comment by steffenbrem** [comment]
If you want a proper solution to this look into the `sylius_order_checkout` graph. This one is used for state transitions of an orders checkout state. You can add a callback there to set the payment to paid.

**Comment by tchapi** [comment]
hmm... yes, but to which transition should I set this callback ? I've tried many but didn't succeed

**Comment by steffenbrem** [comment]
You should use the `complete` transition or the `select_payment` transition.

**Comment by tchapi** [comment]
Ok thanks, I'll try that !

**Comment by tchapi** [comment]
Now that the checkout process has changed again in the current master, this is still the case (order is in `awaiting_payment` state), and I guess 0€ payment should really be transitionned to `paid` automatically..

If I try to do it manually, the `complete` or `select_payment` transitions are too early for that, since they arrive before the user completes its order. So I'm doing this, which works right now, but I'm not sure is the best way : 

```yml
winzou_state_machine:
    sylius_order_payment:
        callbacks:
            after:
                # When requesting payment, let's automatically pay 0€ orders
                update_free_orders:
                    on: ["request_payment"]
                    do: ["@my_bundle.item_callback", "updateFreeOrders"]
                    args: ["object"]
```

Does it look good to you ? The user is still selecting a payment method for 0€, but that's another problem that can be addressed differently and is less an issue.

**Comment by tchapi** [comment]
I would happily close this but I'd like to make sure that using the state machine to address this scenario is the correct way to go. @pjedrzejewski || @michalmarcinkowski ?

**Comment by tchapi** [comment]
Aaaaaaand it's now broken again, thanks to : 

```
if (null === $payment) {
            throw new NotFoundHttpException(sprintf('Order with token "%s" has no pending payments.', $tokenValue));
        }
``` 

in **PayumController**.

Now we can't update the payment state since if we do, the PayumController gives us a 404. And if we don't, the payment never transitions to "completed", and so the order is not completed.

So we're stuck here without a solution to have free orders. Guys ? Any ideas ?
