### ISSUE TITLE
Improve configuration imports

### ISSUE THREAD

**Issue by khusseini** [Sylius/Sylius#5965]
Hi there,

I am currently evaluating sylius' REST API, and trying to take away everything that is not needed for running the REST API. So far so good, however I think some bundle configuration can be modified to be able to avoid running into trouble with 3rd party bundle configuration like assetic or twig.

One idea that comes to mind is to split the config.yml files further into its sections.
For example the configuration for the CoreBundle could be split into:

```
core-bundle
|
+-- app
|   |
|   +-- config
|       |
|       +-- config.yml        # main config file for the standard edition, imports everything below
|       +-- bundles.yml       # sylius bundle imports
|       +-- doctrine.yml
|       +-- assetic.yml
```

This way one can easily cherrypick the bundles and configurations depending on the Symfony setup.
What do you guys think?

**Comment by pjedrzejewski** [comment]
We need to clean up the ApiBundle and your use-case will only require removing shop and admin bundles from Kernel and config imports. I don't think we want to change the configuration structure at this point.

**Comment by mozzymoz** [comment]
One thing that bothered me most with the configuration is, that a lot of bundles use assetic, which I have long kicked from my projects. I like to keep my vendors clean, but yes, but then again I could simply write my own configuration. It was a motivation of laziness to split up configuration files for the bundles :)
