### ISSUE TITLE
Guzzle packages abandoned, new versions to be utilized

### ISSUE THREAD

**Issue by kshishkin** [Sylius/Sylius#5967]
Following bundles trigger below warning while being pulled with composer:
### Bundles:

settings-bundle
resource-bundle
omnipay-bundle
pricing-bundle
### Warning:

Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.

**Comment by pjedrzejewski** [comment]
Thanks for reporting, we will have a look at upgrading these to proper packages. :) Although I am almost sure it is our 2nd level deps.
