### ISSUE TITLE
[SyliusTranslationBundle] Is it necessary to depend on ResourceBundle

### ISSUE THREAD

**Issue by aistis-** [Sylius/Sylius#5985]
Hello, I would like to use standalone bundle of translations, but it comes with ResourceBundle overhead. Is it really necessary to have it as a dependency?

**Comment by pjedrzejewski** [comment]
SyliusTranslationBundle was merged into ResourceBundle in latest branch, so there is no way to use it standalone. If you don't use ResourceBundle, then go for DoctrineBehaviours or Gedmo Extensions for Doctrine.

**Comment by aistis-** [comment]
Oh I see. As I see Gedmo extensions have an approach for translating by single field (single entity could have multiple records in database in same locale of same entity, BUT with different property) and DoctrineBehaviours is more like Sylius translations? It is single translation record per locale for an entity. Am I right? I think it has a better performance and more intuitive, what do you think @pjedrzejewski?
