### ISSUE TITLE
Accessing to a checkout step with an empty cart throws an error

### ISSUE THREAD

**Issue by gorkalaucirica** [Sylius/Sylius#5988]
Steps to reproduce:
* Visit http://demo.sylius.org/checkout/address with an empty cart

Error thrown:
`Binding entities to query parameters only allowed for entities that have an identifier.`

**Comment by tchapi** [comment]
Same behaviour here, in fact, this error happens whenever you access an url corresponding to a step that is not the actual step of your cart, as far I as I can tell.

**Comment by tchapi** [comment]
And I guess this is related to https://github.com/Sylius/Sylius/pull/5956 somehow

**Comment by tchapi** [comment]
Still present in the current master ...

**Comment by michalmarcinkowski** [comment]
Not any more :)
