### ISSUE TITLE
Suggestion - Add Between to ExpressionBuilder

### ISSUE THREAD

**Issue by bnd170** [Sylius/Sylius#5989]
I'm doing a DateRangePicker for the filters of my grids, but i cant search rows between two dates because your expression interface have not the between expression. :(

**Comment by pjedrzejewski** [comment]
You can use ``greaterThan`` and ``lessThan`` combination, that is ``between``.

**Comment by bnd170** [comment]
Yep, it is right! Thanks for the tip.

**Comment by bnd170** [comment]
@pjedrzejewski seems like it not working properly.

I'm doing that:


 ```
$dataSource->restrict($dataSource->getExpressionBuilder()->greaterThanOrEqual($field, $dateStart));
$dataSource->restrict($dataSource->getExpressionBuilder()->lessThanOrEqual($field, $dateFinish));
```
But in query i'm getting this:

> SELECT count(DISTINCT d0_.id) AS sclr0 FROM dinamic_sylius_post d0_ LEFT JOIN sylius_admin_user s1_ ON d0_.admin_user_id = s1_.id WHERE d0_.createdAt >= ? AND d0_.createdAt <= ?
> Parameters: ['2016-10-27 23:59:59', '2016-10-27 23:59:59']

The variables are different, i checked that. It is a limitation by field? One value for field?

**Comment by bretto36** [comment]
Can you post the code where you set dateFinish

**Comment by bnd170** [comment]
Yes, of course, ill post all my function:

    public function apply(DataSourceInterface $dataSource, $name, $data, array $options)
    {
        if (empty($data)) {
            return;
        }

        $field = isset($options['field']) ? $options['field'] : $name;

        $dates = explode('___', $data['value']);

        $dateStart = new \DateTime($dates[0]);
        $dateFinish = new \DateTime($dates[1]);

        $dateFinish->setTime(23,59,59);

        $dataSource->restrict($dataSource->getExpressionBuilder()->greaterThan($field, $dateStart));
        $dataSource->restrict($dataSource->getExpressionBuilder()->lessThan($field, $dateFinish));
    }

On my `$data['value']` get two dates separated by `___`. I explode it to get the two differennt dates.

Also I change time for dateFinish to include all the finish date day.
