### ISSUE TITLE
Remove  "doctrine/orm": "^2.4.8,<2.5", in sylius/core components

### ISSUE THREAD

**Issue by kzap** [Sylius/Sylius#5999]
`sylius/user` package requires `doctrine/orm`, pretty sure it should be `doctrine/common`
using `doctrine/orm` makes its pretty hard to use the components with other libraries like Laravel which use `Symfony/console 3.x`

Composer error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sylius/user v0.19.0 requires doctrine/orm ^2.4.8,<2.5 -> satisfiable by doctrine/orm[v2.4.8].
    - sylius/core v0.19.0 requires sylius/user ^0.19 -> satisfiable by sylius/user[v0.19.0].
    - Installation request for sylius/core ^0.19.0 -> satisfiable by sylius/core[v0.19.0].
    - Conclusion: remove symfony/console v3.1.4
    - Conclusion: don't install symfony/console v3.1.4
    - doctrine/orm v2.4.8 requires symfony/console ~2.0
```

**Comment by kzap** [comment]
Also sylius/promotion

**Comment by kzap** [comment]
mainly the issues here is different symfony versions 2.8 and the components requiring doctrine/orm

or you could support doctrine 2.5.2 which supports symfony 3.x

i mainly found it was hard to use Sylius with Laravel 5.3 which requires Symfony 3.1.*
I had to use Laravel 5.2 or 5.1

and requiring doctrine for components is highly coupled, that should be for the Bundles but not the core components

**Comment by pamil** [comment]
It's caused by #3836.

**Comment by michalmarcinkowski** [comment]
The issue is that we shouldn't use `doctrine/orm` in components, but decoupling from it won't be simple in a few places.

**Comment by winzou** [comment]
I just bumbed into this issue as well. I want to use the promotion bundle but cannot as `sylius/promotion` requires `doctrine/orm: <2.5`. Would it be possible to loosen the constraint? Or to put the constraint only on the core? An issue in sorting products should not prevent one to use only the promotion bundle!

**Comment by kzap** [comment]
Yes requiring doctrine/orm bring makes the core components highly coupled as it brings in all the requirements of the doctrine project.

for the bundles this is fine, thats for Symfony but core components? it makes no sense, and it was only used as a return type, there is no logical use of the doctrine/orm i could find in the core components

i was not able to get it working with the latest Laravel because of this and I find myself forking all the components just to remove this dependencies.

**Comment by pamil** [comment]
I sent #6031, which drops the upper constraint.

Anyway, components should be decoupled from `doctrine/orm` package.
