### ISSUE TITLE
PhpSpec, Behat, PhpUnit in Sylius workflow

### ISSUE THREAD

**Issue by ylastapis** [Sylius/Sylius#6037]
This is not another thread about qualities & drawbacks of these tecs, I'm just trying to understand how they are used into Sylius process.

As far as I understand, reading [this](http://docs.sylius.org/en/latest/contributing/code/bdd.html)
- Behat is used to describe (has very verbose) & test the business requirements. Scenarios are written by the Customer (Sylius Users / Core team) with the @todo tag to describe the needs.
- Phpspec is used to "design" the implementation of the new requirement & used to check if the developper has a good comprehension of what needs to be done. Read by the Core Team, to check if everything is correct.
- PhpUnit is used to test almost anything, looks like redundant with Behat. It seems it's used to test specifically Api Calls.

When a new functionality is ready, the developper has to implement the Behat tests, and then remove the @todo tag in it.

Thanks for your feedback :)

Some interesting discussions on Behat here : 
- [Use behat to test API](https://github.com/Sylius/Sylius/issues/5383)
- [New Behat contexts are final](https://github.com/Sylius/Sylius/issues/4201)
- [How does Behat tests and profiles work](https://github.com/Sylius/Sylius/issues/4025)

**Comment by gabiudrescu** [comment]
I had pretty much the same question in mind and I got the answer here: #5956

**Comment by michalmarcinkowski** [comment]
@ylastapis please also have a look at [our Behat guide](http://docs.sylius.org/en/latest/behat/index.html).

We use PHPUnit mainly for testing API (using [ApiTestCase](https://github.com/Lakion/ApiTestCase) library) and configuration (using [SymfonyConfigTest](https://github.com/matthiasnoback/SymfonyConfigTest) library).

**Comment by ylastapis** [comment]
Thanks @michalmarcinkowski, 
I was asking that question mainly to understand your workflow and use it as a best practice with my team :)
