### ISSUE TITLE
Create page twig error

### ISSUE THREAD

**Issue by arnotae** [Sylius/Sylius#6049]
I found this error when I'm going to "admin" -> "pages" -> "create a new pages" in 0.19 :

```
Impossible to access an attribute ("vars") on a null variable in SyliusWebBundle:Backend/Content/StaticContent:_form.html.twig at line 8
```

Error line : 

```
{{ forms.readonly(form.parent,form.parent.vars.value,'/cms/pages') }}
```

Does anyone success to correct that ?

**Comment by michalmarcinkowski** [comment]
The static content will be shipped as an extension to Core soon.
