### ISSUE TITLE
[Bug] Taxes don't take into account Promotions

### ISSUE THREAD

**Issue by winzou** [Sylius/Sylius#605]
Currently, TaxationProcessor applies its taxes independently from promotions that could be already applied.

Example: 
- Items total = 100€
- Promotion total = 10€ (a coupon offering 10% discount)
- => Tax (20% / included in price) total = 20€

So the guys would be paying 90€ with 20€ taxes instead of 18€.

This is because taxes are applied on each item and finaly summed. But the promotion total is an adjustment in addition to the order total, no link to each item total.

What would be the solution?

Apply the promotion on tax total? What if each item has a different tax applied?

It's a tricky issue!

**Comment by psyray** [comment]
What's going on about this issue ?
I think, [as explained by] (https://github.com/Sylius/Sylius/issues/605#issuecomment-29746437) by @simshaun , promotions need an option to define what tax behavior apply to fulfill each customer use case

**Comment by patrick-mcdougle** [comment]
Furthermore, as an added complexity, if you ever want to be able to ship to multiple destinations in a single order, tax needs to be applicable on a shipment level as well because in the US sales tax is calculated on shipping address.

**Comment by michalmarcinkowski** [comment]
It is already fixed and covered with Behat scenarios (see https://github.com/Sylius/Sylius/pull/7187/files).
