### ISSUE TITLE
[RFC] Product, taxon etc. media management

### ISSUE THREAD

**Issue by koemeet** [Sylius/Sylius#6052]
Are there any plans for improvements for media management for products and taxons? I was thinking about using a `Medium` entity that has a specific `type`, which could be: `file`, `image`, `youtube`, `vimeo` etc. For the actual reference we could add the `reference` field which can store a single string (youtube video id or the path to the image) OR we could do a serialized array to make it more flexible.

With this as the first step, you could include youtube videos on products, alongside images etc. and render them however you want.

I have it implemented like this myself and would like to know what you guys think about having this in core?

**Comment by pjedrzejewski** [comment]
Would be very useful indeed, but this kind of improvement won't be part of 1.0 unfortunately. :(

**Comment by pjedrzejewski** [comment]
@steffenbrem When we do it for 1.x or 2.x, would be great if you can share your idea and/or implementation! :)

**Comment by steffenbrem** [comment]
Sure when time is there I will share my stuff! Only on resource- and api-level though, since I don't use the `AdminBundle`.

**Comment by gabiudrescu** [comment]
I recommend Akeneo Product Asset Manager as an inspiration - I've read something from their docs and watched some YouTube videos and they've got quite a nice product
