### ISSUE TITLE
Override template for a specific Taxon?

### ISSUE THREAD

**Issue by maurosergiosilva** [Sylius/Sylius#6057]
On Sylus can I have a template associated with an specific Taxon!?

**Comment by patrick-mcdougle** [comment]
One way you could potentially do this, not sure if it's a "hack" or not, but you could add the following to your routing file:

    sylius_shop_taxon_show_test:
        path: /taxons/test
        methods: [GET]
        defaults:
            _controller: sylius.controller.taxon:showAction
            _sylius:
                template: SyliusShopBundle:Taxon:show_test.html.twig
                repository:
                    method: findOneByPermalink
                    arguments: ['test']

You would replace the word "test" with the permalink of the taxon you want to have a custom template. Then you would create the template file listed. Of course, you can't change the permalink without causing trouble...so this might not be a sustainable solution.

**Comment by maurosergiosilva** [comment]
Thanks Patrick,
Im investigating if I can use Sylius as alternative to Magento and those Taxon Landing Pages are very importante to SEO.
I was thinking doing like Magento do, add one new Tab in Taxon  where I culd decide how Taxon Page will be rendered:
1. Just Static Block
2. Static Block before Product List
3. Just Product List (default) 
Or something like that...
Thanks

**Comment by michalmarcinkowski** [comment]
You can do that in several ways. E.g. you can customize Taxon entity and add a field that will indicate which layout should be used and based on that field render appropriate template in Twig (very simple customization).

Please post such questions to stackoverflow under "sylius" tag, it's the official support channel.

**Comment by maurosergiosilva** [comment]
Thanks for Help Michał Marcinkowski.
I will do that next time.
