### ISSUE TITLE
Notice: Undefined index: state_machine

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#6058]
When accessing the thank you page.

in vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Checkout/CheckoutResolver.php at line 118 :

```php
    private function getRequestedTransition(Request $request)
    {
        return $request->attributes->get('_sylius')['state_machine']['transition'];
    }
```

I'm on the latest master.

Thanks

**Comment by michalmarcinkowski** [comment]
Does your thank you page url contains `/checkout`?

**Comment by tchapi** [comment]
Uh, yes it does ... is this bad ?

**Comment by michalmarcinkowski** [comment]
Removing `/checkout` from url for thank you page will resolve your issue, but we probably should think about some improvement to the `CheckoutResolver` to prevent such issues... /cc @Arminek

**Comment by tchapi** [comment]
Ah, ok thanks, I'll try that right away. Is this a _route priority_ kind-of issue ?

**Comment by michalmarcinkowski** [comment]
There is a "firewall" introduced for `/checkout` url which restrict access to checkout steps, see #5945.

**Comment by tchapi** [comment]
So far your fix works perfectly so I'll close for now
