### ISSUE TITLE
Redirect loop in login

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#6060]
Whenever I change the password of a user in the backend, if this user is logged, it will end up being stuck in a redirect loop for every page he tries to load :

```
request.INFO: Matched route "sylius_shop_login". {"route_parameters":{"_controller":"sylius.controller.security:loginAction","_sylius":{"template":"DraftWebBundle:Frontend/User:login.html.twig"},"_route":"sylius_shop_login"},"request_uri":"http://draft.local/app_dev.php/login"} []
security.DEBUG: Read existing security token from the session. {"key":"_security_shop"} []
...
security.DEBUG: User was reloaded from a user provider. {"username":"blablabla","provider":"SyliusBundleUserBundleProviderUsernameOrEmailProvider_0000000037bd630a000000004f621a104641de21708ac5ef2f753764a383d466"} []
security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\ProviderNotFoundException(code: 0): No Authentication Provider found for token of class \"Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken\". at /Symfony/Component/Security/Core/Authentication/AuthenticationProviderManager.php:107)"} []
```

**Comment by tchapi** [comment]
Anybody else has this bug or is able to reproduce ? It's quite consistent on my side — everytime I modify a customer in the backend, the frontend gets a redirect loop behavior..

**Comment by tchapi** [comment]
I noticed that this behavior happens when I change the password of a logged user in the backend. Apparently, any other change does not produce this bug

**Comment by Webarkitekt** [comment]
I experience the same bug after the user register

**Comment by pamil** [comment]
May be related with #6283.

**Comment by tchapi** [comment]
Still the case after https://github.com/Sylius/Sylius/pull/6565

**Comment by tuka217** [comment]
Hi, I tried to reproduce your bug. I registered new customer and log in to store. Then I changed the password of this customer as administrator (the customer was still log in). After that I could log out and log in as this customer and do every action as usual. Do you have still this problem after updating to the newest version of Sylius?

**Comment by tchapi** [comment]
That's true ;) It is now fixed !
