### ISSUE TITLE
[ThemeBundle] PathResolver

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#6061]
I am trying to figure out why the `ThemeBundle` has a `PathResolver` that does the following:

```PHP
    /**
     * {@inheritdoc}
     */
    public function resolve($path, ThemeInterface $theme)
    {
        return str_replace('bundles/', 'bundles/_themes/' . $theme->getName() . '/', $path);
    }
```

It's breaking my ckeditor integration as the ckeditor autoloads files (`bundles/ckeditor`), but it gets changed to `bundles/_themes/...`.

cc @pamil

**Comment by inssein** [comment]
Sorry to be annoying @pamil - but any idea why this is necessary. I can help get this out of they way if you point me in the right direction.

**Comment by pamil** [comment]
The reasoning behind this is that we can't easily change relative paths hardcoded in some assets, so installing them in directory per each theme should solve it. Did you try to use `app/console sylius:theme:assets:install`?

PS. No problem with pinging me, I miss some issues sometimes. :)

**Comment by inssein** [comment]
Ah, missed running the command. Going to close this bug, but maybe this should be addressed differently? Slightly awkward in the `_themes` directory, and also need to address some deployment concerns.
