### ISSUE TITLE
$this->get('templating')->exists() broken ?

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#6067]
I have an issue after updating to the latest master (I was 20 commits late or so).

In a controller :

```php
$this->get('templating')->exists($templateName)
```
returns `true` for any `$templateName`, i.e. for any string, like "blablabla" or whatever. Doesn't work if I encapsulate the string in a `TemplateReference` either. It worked perfectly before updating.

Am I missing something ?

**Comment by lchrusciel** [comment]
Probably this PR was responsible for this #5958. Without this fix, we weren't able to access an exception page on symfony profiler. Can you debug it and try to resolve this issue?

**Comment by tchapi** [comment]
Well, the issue is that you return `true` all the time ;) I don't know how themes work (I'm not using themes) but I guess your overriden function should test the existence of the template somehow ?

**Comment by tchapi** [comment]
I confirm that this is fixed by the above merged PR. Thanks guys ! 👍
