### ISSUE TITLE
[Bug][Channel] Setting default locale on channel that isn't in its locales collection

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#6070]
You can break the whole channel if you set the `defaultLocale` of a channel to a locale that isn't set on the channels `locales` collection. I found this out on the Sylius demo app, and right now the whole demo is broken (Sorry 😛 ). 

There should be some validation constraint that checks if the `defaultLocale` of a channel is also present on the `locales` collection.

**Comment by patrick-mcdougle** [comment]
I have confirmed this bug locally.

**Comment by patrick-mcdougle** [comment]
@steffenbrem If you get a chance, please take a look at my PR / checkout my branch to try my fix.

**Comment by steffenbrem** [comment]
Looks as a nice addition, the `Choice` validator! Thanks for preparing a fix 😄

**Comment by michalmarcinkowski** [comment]
Fixed in https://github.com/Sylius/Sylius/pull/6978.
