### ISSUE TITLE
The variant field on CartItemType

### ISSUE THREAD

**Issue by bnd170** [Sylius/Sylius#6073]
![captura de pantalla 2016-09-13 a las 8 57 18 1](https://cloud.githubusercontent.com/assets/5690663/18464245/1d3915b6-7990-11e6-964c-ddebde86b39e.png)
I found a strange thing.
On product view, with a simple product (Without variants) the CartItemType shows a checkbox input. I have no idea about what the field do, can someone explain me it please?

**Comment by michalmarcinkowski** [comment]
Have you customized the OrderItem entity?

**Comment by bnd170** [comment]
Nope, I didn't

**Comment by michalmarcinkowski** [comment]
Probably the issue is in [_addToCart template](https://github.com/michalmarcinkowski/Sylius/blob/680d8186684dae786910db867664e8c580aa2641/src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_addToCart.html.twig#L15).

**Comment by bnd170** [comment]
That was what I was asking if that was a bug or something intentional

**Comment by bretto36** [comment]
Created a pull request for this one. The add to cart template and the cartitemtype form weren't matching the logic. So i removed the form.variant from the form type when it's a simple product and removed from the add to cart. The "DefaultVariantResolver" will find the variant for the product when it's a simple product.

**Comment by bnd170** [comment]
Thanks for fix it!
