### ISSUE TITLE
[Bug][UI] In the cart we should display code of a specific variant instead of a product code 

### ISSUE THREAD

**Issue by michalmarcinkowski** [Sylius/Sylius#6076]
On a cart summary page (probably also in other places) we [display a product code](https://github.com/michalmarcinkowski/Sylius/blob/0b555349a55f65b69e601efcab9aed34b2cc0b3b/src/Sylius/Bundle/ShopBundle/Resources/views/Common/Product/_variant.html.twig#L8-L8) instead of a variant code. Each item is associated with specific variant and its code should be displayed.

**Comment by bretto36** [comment]
Does it display the product code only when it is a simple product?

**Comment by michalmarcinkowski** [comment]
Unfortunately it always display product code. We have the same code visible even for different variants of the same product.
