### ISSUE TITLE
What kind of controller naming format Sylius use in yaml config files?

### ISSUE THREAD

**Issue by pleca** [Sylius/Sylius#6099]
f.e. lets compare two routing yaml files:

[ShopBundle/Resources/config/routing/product.yml][1]

[ShopBundle/Resources/config/routing/taxon.yml][2]

both have _controller atribute:

    _controller: sylius.controller.product:showAction
and

    _controller: sylius.controller.taxon:showAction

and both match same controller:
[ResourceBundle/Controller/ResourceController:showAction](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php#L167)

 - What kind of controller naming format Sylius use in yaml config files? Why it not looks like `Bundle:Controller:action` ?

 - How to find this controller other than hunting it in the project code?

  [1]: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ShopBundle/Resources/config/routing/product.yml
  [2]: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ShopBundle/Resources/config/routing/taxon.yml

**Comment by steffenbrem** [comment]
Sylius uses controllers as services (see: http://symfony.com/doc/current/controller/service.html). To easily find the related code to that service I suggest you to install the Symfony2 plugin for PHPStorm, you can find it here: https://plugins.jetbrains.com/plugin/7219?pr=idea.

**Comment by tchapi** [comment]
Side note : Taxons and products are both _Resources_, so in fact, these routes both use the generic **ResourceController** :  `Sylius\Bundle\ResourceBundle\Controller\ResourceController`

You can use the `debug:container` utility of the cli to check it up : 

    php app/console debug:container sylius.controller.product

**Comment by pleca** [comment]
I appreciate both answers.

**Comment by steffenbrem** [comment]
@pleca If you've found the answers useful, please close this issue 😄

**Comment by pleca** [comment]
@steffenbrem (I installed phpstorm and Symfony plugin but its impossible to click on _controller: sylius.controller.product:showAction inside routing yaml definition and find service declaration. You probably meant to use Symfony plugin by click on service name and find related code. But i cant find controller service definition)

Could You give me tip how to find controller service definition, lets stick to this service sylius.controller.product which is service for this controller https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php 

Nothing in here https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Resources/config/controller.xml and here https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Resources/config/services.xml

**Comment by steffenbrem** [comment]
The plugin uses the build container in your cache folder. So you should make sure that symfony has properly build your definitions once.

This are my settings for the plugin, maybe you can spot a difference:
![d](https://puu.sh/raea7/0fcba6117a.png)

**Comment by steffenbrem** [comment]
Also you should use `Ctrl + click` or `Cmd + click` to go through your the files.

**Comment by pleca** [comment]
wow, I like it. ( "Enable Plugin" was not selected). I still dont know where in project is definition of service `sylius.controller.product` (I don't mean controller class but service definition in yaml or xml) , anyway I have more benefits from this topic than I ask for.

**Comment by steffenbrem** [comment]
@pleca When you are in the class of that specific service definition you can click on the cog icon next to the class name in order to jump to the **actual** yaml or xml specification of that service.

**Comment by pleca** [comment]
no way to find definition of service named sylius.controller.product, but I can live with that

**Comment by steffenbrem** [comment]
Oh lol, I guess I was too tired yesterday haha. It is auto-generated btw, by the `ResourceBundle`. It processes the configuration and defines those services based on the resource config. Here is the actual code that sets the controller service: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/DependencyInjection/Driver/AbstractDriver.php#L87
