### ISSUE TITLE
[Support Request] Remove guest checkout option 

### ISSUE THREAD

**Issue by bretto36** [Sylius/Sylius#6107]
What's the simplest solution for removing the guest checkout option for Sylius. 

Change the security.yml to make it require logged in user? (this doesn't redirect with a message to say register or login)

Customise the controller (uses the updateAction on the resource controller which i'd prefer to leave as is as it's likely to update in the future)

Any other options? There used to be a config option but that seems to be unavailable

**Comment by steffenbrem** [comment]
I would probably make an access control based on the `/checkout/.+` path, so that you cannot access those endpoints as a guest. That would be enough.

**Comment by bretto36** [comment]
Thanks Steffen, i've done the access control through the security.yml file. Just wanted to make sure i was doing it in a way that made sense

**Comment by steffenbrem** [comment]
Great! I've also answered your SO question so others can find a solution to this quicker 👍
