### ISSUE TITLE
Style issue on Chrome for login page

### ISSUE THREAD

**Issue by bretto36** [Sylius/Sylius#6108]
http://demo.sylius.org/login - If you go to the login page on chrome the divider is pushed to the left of the box. If you remove left: auto from the styles it works. Not sure if removing it affects anything else though
![sylius-issue](https://cloud.githubusercontent.com/assets/6217994/18499467/828d6f28-7a82-11e6-9aca-71395983b608.PNG)

Updated to the latest Chrome version just to make sure and it's still not displaying. Seems to see the order of the css differently to firefox.

**Comment by Niiko** [comment]
I think that's more a semantic-ui problem than a sylius no ?

In fact, i have chrome 51.0.2704.79 (64 bits) on ubuntu 16.04LTS, and everything is ok.

**Comment by tchapi** [comment]
I neither have this glitch in Chrome `Version 46.0.2490.86 (64-bit)` nor Chromium `Version 44.0.2403.155 (64-bit)`. Any user-defined styles in your browser maybe ? An extension that could intervene in your css ?

**Comment by lchrusciel** [comment]
It is not a problem of Sylius nor Semantic UI, it is a problem of Chrome itself. Check [this semantic issue](https://github.com/Semantic-Org/Semantic-UI/issues/4342).

Can be closed probably.

**Comment by steffenbrem** [comment]
The whole spec of W3C actually changed this, the guys from Semantic UI are currently trying to undo those changes on the spec. Until then even more browsers could bring this issue if they adhere to the newer spec.

**Comment by bretto36** [comment]
Closing. Thanks for the heads up on the W3C changes and the semantic issue
