### ISSUE TITLE
[Api] Creating product attribute error: "`createNew()` not supported, use `createdType()` instead"

### ISSUE THREAD

**Issue by koemeet** [Sylius/Sylius#6117]
The type should either be passed in the url path, so `POST /product-attributes/text` for example. Or we should maybe enable `createNew()` so the `type` could be passed in the actual payload, which is in my opinion nicer. We could use a doctrine event listener to set the `storageType` automatically if needed or only do it on the form in a `POST_SUBMIT` listener.

**Comment by pjedrzejewski** [comment]
I am in favor of including the type in the payload, the only reason not to do this in UI was to simplify the forms (no need to dynamic JS), in API it should work like a charm when sent in payload. 👍

**Comment by pjedrzejewski** [comment]
It is passed as "type" via request now and we keep it this way in 1.0. :)
