### ISSUE TITLE
Where is the promotion rule checker customer_loyalty?

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#6118]
All code is still in place but the service definition is gone, any idea if this is intentional or is this removed by accident?

**Comment by steffenbrem** [comment]
The same for `contains_product` rule checker btw.

**Comment by michalmarcinkowski** [comment]
These services don't work correctly, we need to add tests for them and appropriate fix.

**Comment by pamil** [comment]
Can be closed as:
 - customer loyalty rule checker was removed in #6435 
 - customer group has specific issue in #6436 
 - contains product will be probably reworked by @lchrusciel
