### ISSUE TITLE
Cant install ProductBundle to existing project.

### ISSUE THREAD

**Issue by kironet** [Sylius/Sylius#6125]
Hey, 
I installed clear new symfony2 project, and tried to install http://docs.sylius.org/en/latest/bundles/SyliusProductBundle/installation.html, I did all steps, but after I called the command `php app/console doctrine:schema:update --force`
It showed me this error: 

>  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]  
> The service "sylius.factory.product" has a dependency on a non-existent service "sylius.translati on.locale_provider".

**Comment by kironet** [comment]
Any ideas?

**Comment by bretto36** [comment]
I can't even find a reference to that in the SyliusProductBundle code. Is there anything in the logs file that can give us the trace log

**Comment by kironet** [comment]
Here is screen. 
![capture](https://cloud.githubusercontent.com/assets/2453329/18587674/7588075a-7c23-11e6-9f17-a57bda16783d.PNG)

> Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "sylius.factory.product" has a dependency on a non-existent service "sylius.translation.locale_provider". in DOMAIN/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php:58 Stack trace: #0 DOMAIN/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(42): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processReferences(Array) #1 DOMAIN/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php(53): Symfony\Component\DependencyInjection\Compiler\CheckExceptionOnInvalidReferenceBehaviorPass->processDefinition(Object(Symfony\Component\DependencyInjection\Definition)) #2 /ho in DOMAIN/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/CheckExceptionOnInvalidReferenceBehaviorPass.php on line 58

**Comment by steffenbrem** [comment]
@kironet The product factory that comes with Sylius does not require the locale provider service. Try removing your cache folder and make sure you are on the latest product bundle.

**Comment by steffenbrem** [comment]
Ah hold on, the culprit is the `ServicesPass` that is used by the `ProductBundle` (https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ProductBundle/DependencyInjection/Compiler/ServicesPass.php#L40).

**Comment by patrick-mcdougle** [comment]
If there truly is a dependency on the localeBundle, we should make sure that it's in the composer.json file.

**Comment by patrick-mcdougle** [comment]
Are we sure that the ServicesPass is even needed anymore? Is it possible that the ResourceBundle is handling all of that stuff now? If not, should it be?

**Comment by mozzymoz** [comment]
Oh I haven't seen this ticket before. I opened this one https://github.com/Sylius/Sylius/issues/6276 and solved the locale issue. But I am getting another error when doing a `app/console doctrine:schema:create`

```bash
ATTENTION: This operation should not be executed in a production environment.

Creating database schema...

  [Doctrine\Common\Persistence\Mapping\MappingException]                  
  Class 'Sylius\Component\Product\Model\ProductInterface' does not exist  
                                                                          
```

**Comment by mozzymoz** [comment]
I have run now a `doctrine:schema:validate` and got following errors:

```bash
[Mapping]  FAIL - The entity-class 'Sylius\Component\Product\Model\ProductVariant' mapping is invalid:
* The target entity 'Sylius\Component\Product\Model\ProductInterface' specified on Sylius\Component\Product\Model\ProductVariant#product is unknown or not an entity.

[Mapping]  FAIL - The entity-class 'Sylius\Component\Product\Model\ProductOption' mapping is invalid:
* The target entity 'Sylius\Component\Product\Model\ProductOptionValueInterface' specified on Sylius\Component\Product\Model\ProductOption#values is unknown or not an entity.

[Mapping]  FAIL - The entity-class 'Sylius\Component\Product\Model\ProductOptionValue' mapping is invalid:
* The target entity 'Sylius\Component\Product\Model\ProductOptionInterface' specified on Sylius\Component\Product\Model\ProductOptionValue#option is unknown or not an entity.

[Mapping]  FAIL - The entity-class 'Sylius\Component\Product\Model\Product' mapping is invalid:
* The target entity 'Sylius\Component\Product\Model\ProductAttributeValueInterface' specified on Sylius\Component\Product\Model\Product#attributes is unknown or not an entity.


                                                                          
  [Doctrine\Common\Persistence\Mapping\MappingException]                  
  Class 'Sylius\Component\Product\Model\ProductInterface' does not exist  
```

**Comment by mtthb** [comment]
@mozzymoz I had to add SyliusAssociationBundle.

In kernel:
```php
    return [
            ...
            new Sylius\Bundle\LocaleBundle\SyliusLocaleBundle(),
            new Sylius\Bundle\ProductBundle\SyliusProductBundle(),
            new Sylius\Bundle\AssociationBundle\SyliusAssociationBundle(),
            new Sylius\Bundle\ResourceBundle\SyliusResourceBundle(),
            new Sylius\Bundle\AttributeBundle\SyliusAttributeBundle(),
        ];
```

In config.yml:
```yaml
sylius_association:
    resources:
        product:
            subject: "%sylius.model.product.class%"
            association:
                classes:
                    model: Sylius\Component\Product\Model\ProductAssociation
                    interface: Sylius\Component\Product\Model\ProductAssociationInterface
```

**Comment by michalmarcinkowski** [comment]
Fixed.
