### ISSUE TITLE
Typo sylius.authenticaiton.success_handler

### ISSUE THREAD

**Issue by kadinho** [Sylius/Sylius#6131]
There is a typo in 

security.yml line 45

**authenticaiton** should be **_authentication_**

cause the following exception when updating or installing

  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  The service "security.firewall.map.context.shop" has a dependency on a non-existent service "sylius.authenticaiton.success_handler"

Note: I get this error when updating to 8dc04fc

**Comment by lchrusciel** [comment]
@michalmarcinkowski can be closed, already fixed in #5975

**Comment by michalmarcinkowski** [comment]
@lchrusciel 👍
