### ISSUE TITLE
[Bug][Core] Order::isInvoiceAvailable uses undefined constant STATE_RETURNED

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#6139]
The `Order::isInvoiceAvailable` still uses the `ShipmentInteface::STATE_RETURNED` constant, which has been removed. See: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/Model/Order.php#L494

**Comment by tchapi** [comment]
In fact, there are no more invoices in Sylius, so this function can be removed altogether I guess
