### ISSUE TITLE
Can't setup HWIOAuthBundle for Facebook connect integration 

### ISSUE THREAD

**Issue by gdecorbiac** [Sylius/Sylius#6141]
I would like to add social connect buttons in my Sylius shop but I can't manage to do that.
I installed HWIOAuthBundle via composer :

    $ composer require hwi/oauth-bundle

Then, according to [HWIOAuthBundle documentation](https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/1-setting_up_the_bundle.md), here are my config files:

**app/config/routing.yml**
    
    hwi_oauth_redirect:
        resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
        prefix:   /connect

    hwi_oauth_connect:
        resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
        prefix:   /connect

    hwi_oauth_login:
        resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
        prefix:   /login

    facebook_login:
        path: /login/check-facebook

**app/config/config.yml**

    hwi_oauth:
        firewall_names: [secured_area]
        resource_owners:
            any_name:
                type:                facebook
                client_id:           <client_id>
                client_secret:       <client_secret>
                options:
                    display: popup #dialog is optimized for popup window
                    auth_type: rerequest # Re-asking for Declined Permissions

**app/config/security.yml**

    firewalls:
        secured_area:
            anonymous: ~
            oauth:
              resource_owners:
                  facebook:           "/login/check-facebook"
              login_path:        /login
              use_forward:       false
              failure_path:      /login

              oauth_user_provider:
                  service: sylius.oauth.user_provider

When I start the server, I get this error :

    [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                              
    The service "sylius.oauth.user_provider" has a dependency on a non-existent service "sylius.factory.admin_user_oauth".

Is-it a bug ?

**Comment by bretto36** [comment]
Are you using the full sylius package or just some bundles?

**Comment by gdecorbiac** [comment]
I installed Sylius according to the documentation, so I assume I'm using the full sylius package

**Comment by ylastapis** [comment]
Check that PR https://github.com/Sylius/Sylius/pull/5763

**Comment by gdecorbiac** [comment]
Indeed, it seems to be the same issue. Thank you

**Comment by Mustabshir-K** [comment]
Hi, I am also using HWIOAuth in my sylius shop but i m stuck with  following error, even i include new \HWI\Bundle\OAuthBundle\HWIOAuthBundle() in AppKernel.php File and  i also follow your way to integrate HWIOAuth in sylius but coudlnt find any solution can any one provinde me simple tutorial for this provision.

I am facing this  error

Fatal error: Uncaught exception 'Symfony\Component\DependencyInjection\Exception\InvalidArgumentException' with message 'There is no extension able to load the configuration for "hwi_oauth" (in C:\xampp\htdocs\gcapplication\app/config\config.yml). Looked for namespace "hwi_oauth", found "sylius_installer", "sylius_order", "sylius_money", "sylius_currency", "sylius_contact", "sylius_locale", "sylius_settings", "sylius_cart", "sylius_product", "sylius_archetype", "sylius_channel", "sylius_variation", "sylius_attribute", "sylius_taxation", "sylius_shipping", "sylius_payment", "sylius_mailer", "sylius_report", "sylius_promotion", "sylius_addressing", "sylius_inventory", "sylius_taxonomy", "sylius_flow", "sylius_pricing", "sylius_sequence", "sylius_content", "sylius_search", "sylius_rbac", "sylius_user", "sylius_ui", "sylius_admin", "sylius_metadata", "sylius_association", "sylius_review", "sylius_core", "sylius_web", "sylius_resource", "sylius_grid", "winzou_state_machine", "sylius_api", "sonata_block", "cmf_core", "cmf_block in C:\xampp\htdocs\gcapplication\vendor\symfony\symfony\src\Symfony\Component\Config\Loader\FileLoader.php on line 130

After include HWIOauth in AppKernel i found this issue

Fatal error: Uncaught exception 'Symfony\Component\DependencyInjection\Exception\InvalidArgumentException' with message 'There is no extension able to load the configuration for "firewalls" (in C:\xampp\htdocs\gcapplication\app/config\security.yml). Looked for namespace "firewalls", found "sylius_installer", "sylius_order", "sylius_money", "sylius_currency", "sylius_contact", "sylius_locale", "sylius_settings", "sylius_cart", "sylius_product", "sylius_archetype", "sylius_channel", "sylius_variation", "sylius_attribute", "sylius_taxation", "sylius_shipping", "sylius_payment", "sylius_mailer", "sylius_report", "sylius_promotion", "sylius_addressing", "sylius_inventory", "sylius_taxonomy", "sylius_flow", "sylius_pricing", "sylius_sequence", "sylius_content", "sylius_search", "sylius_rbac", "sylius_user", "sylius_ui", "sylius_admin", "sylius_metadata", "sylius_association", "sylius_review", "sylius_core", "sylius_web", "sylius_resource", "sylius_grid", "winzou_state_machine", "sylius_api", "sonata_block", "cmf_core", "cmf_blo in C:\xampp\htdocs\gcapplication\vendor\symfony\symfony\src\Symfony\Component\Config\Loader\FileLoader.php on line 130


Can anyone please help me ?
Thanks in advance.

**Comment by jmarcone** [comment]
currently on Sylius 1.7 to prevent that you need to add the bundle in "config/bundles.php" with following format.
`HWI\Bundle\OAuthBundle\HWIOAuthBundle::class => ['all' => true],`
