### ISSUE TITLE
Use an uuid4 as default value for code aware form types

### ISSUE THREAD

**Issue by koemeet** [Sylius/Sylius#6143]
I am using this myself and it may be useful to be included in Sylius code. A lot of customers are confused about what to do with the code field, so I use the following notation in the `AddCodeFormSubscriber` class:

``` php
$form->add('code', $this->type, [
    'label' => $this->label, 
    'disabled' => $disabled, 
    'empty_data' => Uuid::uuid4()->toString(),
]);
```

I am using the https://github.com/ramsey/uuid library.

Would a PR with this be appreciated?

**Comment by bretto36** [comment]
So do you still display this to the user on the product show page?

**Comment by steffenbrem** [comment]
@bretto36 In my case I don't show the code field at all. It just serves it's purpose as a globally unique id.
