### ISSUE TITLE
[RFC] How should we handle thank you page by default

### ISSUE THREAD

**Issue by Arminek** [Sylius/Sylius#6160]
There is two approaches which we figure out:

The first one is to store order id in session after checkout complete step and then unset it after thank you action.

The second one is to add generated token to order and then combination of order id and token value will give you access to this page.

What do you think is the best way to handle this, any feedback is highly appreciated.

**Comment by pamil** [comment]
IMHO the second approach sound better and more flexible :tada:

**Comment by Zales0123** [comment]
Agreed, 👍  for second approach

**Comment by inssein** [comment]
Second approach makes sense, but I am totally confused by the thank you page right now. I am currently upgrading previous Sylius website to what is on master, and the thank you page is something you see before you pay, which lets you switch your payment method?

**Comment by bretto36** [comment]
@inssein Yep, agreed the default thank you page is very strange. It lets you change payment methods even when there is only 1 payment method to choose from. 
I vote for the second approach too. If we unset a session value when we are redirected back to the thank you page after payment it technically may not work.

**Comment by Arminek** [comment]
Thx for your feedback 👍 . 💃

**Comment by pamil** [comment]
I guess it can be closed since #6104 was merged :)
