### ISSUE TITLE
[RFC] Removing promotion's coupon per customer usage limit

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#6167]
This feature has no tests, creates difficulties (#5134) and has no sense (if I can buy something as guest or make a new account).

It can be replaced by giving each user an unique coupon with its own usage limit.

**Comment by tchapi** [comment]
It stills makes sense when you have a coupon ( say, SUMMER_SALE_16) available for all your customers but that you want to limit its use to 1 time per customer, no ? You don't set any general limit on the coupon nor on the promotion, but you set one on the _per-customer_ limit.

**Comment by inssein** [comment]
@tchapi what pamil was saying that its not really much of a deterrer as one could easily sign up for a new account and use the coupon.

**Comment by kayue** [comment]
@pamil This type of promotion code can be easily found in the ecommerce world, I think we should keep it.

**Comment by tchapi** [comment]
@inssein sure if a customer wants to use it on different accounts it will work in this case ... but you can already do this on every amazon or ebay out there, and still people don't do it, or it's so anecdotal that it's not really an issue

**Comment by ibasaw** [comment]
keep it, don't remove it

**Comment by pamil** [comment]
All right, seems like it's needed, I'll make it work even better then :tada:
