### ISSUE TITLE
Need help overriding Products Entity

### ISSUE THREAD

**Issue by kadinho** [Sylius/Sylius#6169]
Hello,

I override the Products entity following the docs here:

http://docs.sylius.org/en/latest/customization/model.html

But when i update or create the schema i'm getting the following exception:

[ReflectionException]
  Property AppBundle\Entity\Product::$reviews does not exist

Any ideias ?

Thx in advance

regards
CV

**Comment by kadinho** [comment]
Sorry im extending the Component model and i must extend Core model...

Sylius\Component\Core\Model

Please close.

CV

**Comment by okwinza** [comment]
@kadinho there is a button just below to close this ^^
