### ISSUE TITLE
[Payum] obtainCreditCard unable to render form

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#6170]
Have you guys got a credit card form going with sylius master? No matter what I do, I cannot include any form elements in the template.

The error I get is `Template "form_div_layout.html.twig" is not defined in...` . I tried to use a debugger and follow it through, but it might be some interference with ThemeBundle (cc @pamil).

Edit: Tried manually specifying form theme as well, but that results in similar error. (`Template "form_div_layout.html.twig" is not defined in @SyliusUi/Form/theme.html.twig at line 1.`)

**Comment by inssein** [comment]
@michalmarcinkowski this is quite a big issue for me, is there a sylius master implementation that uses the credit card form that works? I think it's a theme bundle issue, but I could be wrong (@pamil).

**Comment by michalmarcinkowski** [comment]
Take a look at https://github.com/Sylius/Sylius/pull/6361.

**Comment by inssein** [comment]
@michalmarcinkowski while it resolves a lot of payment bugs, I don't think it fixes the template bug. The credit card template doesn't use any symfony forms, and thus doesn't run into this issue.
