### ISSUE TITLE
AdjustmentAmount for Promotion

### ISSUE THREAD

**Issue by christophebeling** [Sylius/Sylius#6198]
Hey, 

i'm trying to get the adjustment amounts grouped by promotions. From what i see now i can only get the adjustment of a certain unit or the total adjustment amount for an order. 
For our current use case we need to show all promotions that have been applied to the cart with the adjustment total amount for every single promotion.

**Comment by michalmarcinkowski** [comment]
`$adjustment->getOriginCode()` - will return `code` of promotion that applied the adjustment. You can group the adjustments by these codes :)

Sylius uses Stackoverflow as its official support channel. For future support questions please post them on http://stackoverflow.com/questions/tagged/sylius, just tag your question with `sylius`.

**Comment by christophebeling** [comment]
Thank you for you're fast reply. Unfortunately this change is not available in the current version of the order bundle yet. Is there any other way?

**Comment by michalmarcinkowski** [comment]
Previously there was `originator` you should be able to obtain this information from it. Take a look at [this PR](https://github.com/Sylius/Sylius/pull/5537).
