### ISSUE TITLE
Translation keys which are used in Sylius Templates are missing

### ISSUE THREAD

**Issue by kr1x** [Sylius/Sylius#6206]
Good evening,

as I am currently working on an existing Sylius instance, I discovered, that there are plenty of translation keys used, which are not defined by Sylius, like the following ones:

_sylius.backend.menu.main.metadata_:
I can't even find any usage in this project, where this key should be translated?

_sylius.backend.logout_:
Translated here: https://github.com/Sylius/SyliusWebBundle/blob/master/Menu/BackendMenuBuilder.php#L62
But the only "logout" key defined in the menu.en.yml is "sylius.frontend.menu.main.logout"

_sylius.breadcrumb.dashboard_:
Translated here:
https://github.com/Sylius/SyliusWebBundle/blob/88f415c12ba74a537202203d83993ea5ec50eee0/Resources/views/Backend/_breadcrumb.html.twig#L2
But the only "dashboard" key defined in menu.en.yml is "sylius.backend.menu.main.dashboard"

Have I missed something to update or is this a general problem with the current versions? I also tried to install a fresh version of sylius and I discovered the same keys that were not translated.

Thank you in advance for your help :-)

**Comment by Niiko** [comment]
Which version are you using ?
On master, WebBundle was removed, as said in [roadmap](http://sylius.org/blog/sylius-roadmap-update)

I don't know if 0.19 will be fixed because of the focus on v1 for november.

**Comment by kr1x** [comment]
Actually, I'm using the latest stable release, which means 0.19.0. 
And yes, I know that the WebBundle is going to be removed in the 1.0 version.

Nonetheless I was a little bit confused, because the current state of the WebBundle uses translation keys which are not defined in the same version of the same repository.

I highly support the increased focus on the next version and I don't mind if those missing translation keys won't be added in the current version, because it is no problem for me to add those translation keys to my own translation files :-)

**Comment by michalmarcinkowski** [comment]
The WebBundle was removed, I hope we have all translations in current version :)
