### ISSUE TITLE
sylius/archetype-bundle dev-master requires sylius/variation-bundle ^1.0

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#6221]
We're using the Archetype Bundle in our project but due to the recent commits here removing the Variation bundle, we have a problem : 

```
sylius/archetype-bundle dev-master requires sylius/variation-bundle ^1.0 -> no matching package found.
```

How can we fix this ? Just adding the variation bundle again in our `composer.json` does not work, it cannot find the package : 

```
Problem 1
  - Installation request for sylius/archetype-bundle dev-master as 1.0-dev -> satisfiable by sylius/archetype-bundle[dev-master].
  - sylius/archetype-bundle dev-master requires sylius/variation-bundle ^1.0 -> no matching package found.
```

Thanks a lot !!

**Comment by tchapi** [comment]
I guess this is the same principle as in this ticket : https://github.com/Sylius/Sylius/issues/5887 ?

**Comment by tchapi** [comment]
Nobody ? :cry:

**Comment by michalmarcinkowski** [comment]
The Archetype and Variation bundles are removed from master and will remain available in `v0.19`. In order to use them you should lock these bundles on `v0.19` instead of `dev-master` or `1.0-dev`.

**Comment by tchapi** [comment]
But ArchetypeBundle requires `"^1.0"` so adding : 

        "sylius/variation-bundle": "0.19",

doesn't work :

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sylius/archetype-bundle dev-master requires sylius/variation-bundle ^1.0 -> satisfiable by sylius/sylius[1.0.x-dev, 1.0-dev], sylius/variation-bundle[1.0.x-dev].
    - sylius/archetype-bundle dev-master requires sylius/variation-bundle ^1.0 -> satisfiable by sylius/sylius[1.0.x-dev, 1.0-dev], sylius/variation-bundle[1.0.x-dev].
    - Can only install one of: sylius/variation-bundle[v0.19.0, 1.0.x-dev].
    - don't install sylius/variation-bundle v0.19.0|remove sylius/sylius 1.0.x-dev
    - don't install sylius/variation-bundle v0.19.0|remove sylius/sylius 1.0-dev
    - Installation request for sylius/variation-bundle 0.19 -> satisfiable by sylius/variation-bundle[v0.19.0].
    - Installation request for sylius/archetype-bundle dev-master as 1.0-dev -> satisfiable by sylius/archetype-bundle[dev-master].
```

Or am I missing something ?

**Comment by tchapi** [comment]
Wouldn't it work if you bumped up the version of VariationBundle, like you did for the ArchetypeBundle previously (like https://github.com/Sylius/SyliusArchetypeBundle/commit/e2e020cafffeee867e09c17a66898d806f49fb74 I guess) ?

**Comment by michalmarcinkowski** [comment]
You should install ArchetypeBundle `v0.19` version, not the dev-master. The composer of `v0.19` is correct (see [here](https://github.com/Sylius/SyliusArchetypeBundle/blob/v0.19.0/composer.json)).

**Comment by tchapi** [comment]
Not working either ... and going back to Sylius 0.19 is not an option ;)

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - don't install sylius/resource-bundle v0.19.0|don't install sylius/sylius dev-master
    - don't install sylius/resource-bundle v0.19.0|remove sylius/sylius dev-master
    - sylius/archetype-bundle v0.19.0 requires sylius/resource-bundle ^0.19 -> satisfiable by sylius/resource-bundle[v0.19.0].
    - Installation request for sylius/archetype-bundle 0.19 -> satisfiable by sylius/archetype-bundle[v0.19.0].
    - Installation request for sylius/sylius dev-master as 1.0-dev -> satisfiable by sylius/sylius[dev-master].
```

**Comment by tchapi** [comment]
Ok, I managed to resolve the requirements but the variation bundle breaks everything. I think this PR I just made could help anyone still using the **ArchetypeBundle** : https://github.com/Sylius/SyliusArchetypeBundle/pull/1 WDYT?
