### ISSUE TITLE
Cannot add product variant

### ISSUE THREAD

**Issue by starspire** [Sylius/Sylius#6224]
When trying to add a variant to customizable product I get:
`Could not load type "sylius_product_option_value_collection"`
from `FormRegistry.php` line 92.
It comes from `BuildProductVariantFormSubscriber.php`:
```
$form->add($this->factory->createNamed('options', 'sylius_product_option_value_collection', $productVariant->getOptions(), [
                'options' => $product->getOptions(),
                'auto_initialize' => false,
            ]));
```
I searched for such a form type but can't find one so maybe during merge of VariationBundle to ProductBundle it would drop or the name is incorrect.

**Comment by gdecorbiac** [comment]
This bug has been fixed by PR [6264](https://github.com/Sylius/Sylius/pull/6264)
The issue should be closed now
