### ISSUE TITLE
Customer Subscribed to Newsletter never displayed in admin area

### ISSUE THREAD

**Issue by bretto36** [Sylius/Sylius#6228]
When a customer is subscribed to the newsletter (done in the Personal information section of the Account area). It is never displayed anywhere in the admin? Should it be put on the edit customer, or the show customer page?

**Comment by pjedrzejewski** [comment]
It is displayed already, but we will be reworking the customer details page view in the coming weeks.

![zrzut ekranu 2016-09-28 o 09 49 08](https://cloud.githubusercontent.com/assets/614970/18904933/ea2c4152-8560-11e6-8463-0a6f0b55bd29.png)
