### ISSUE TITLE
Reasoning for Removing Expires at from Order

### ISSUE THREAD

**Issue by bretto36** [Sylius/Sylius#6229]
Can anyone explain the reasoning for removing the expires_at column from the orders table? 

I use that in my current project. So i'll have to re-add it manually if i want to use it. I just want to know what the reasoning was for it's removal.

**Comment by pjedrzejewski** [comment]
It was added several years ago and was supposed to be used for expired cart purging, but it only complicated stuff. We will rely on updatedAt field. As you said, you can easily re-add it. :) Please reopen the issue if you still have any questions regarding this, thanks!: )
