### ISSUE TITLE
[Bug] [Promotion] Percentage Discount can be more than 100%

### ISSUE THREAD

**Issue by TheMadeleine** [Sylius/Sylius#6247]
I'm adding a new promotion with a **PercentageShippingDiscountAction**, and I give it 200% of ``amount``. I make it couponBased and give it a coupon.

![image](https://cloud.githubusercontent.com/assets/13198869/18954379/1093ed98-8653-11e6-83af-40d9b1b8b241.png)

What happens in the Cart while applying this promotion with a coupon?
The shipping cost was **$54.34** before applying the coupon.

![image](https://cloud.githubusercontent.com/assets/13198869/18954425/5600649c-8653-11e6-9dfe-f34152b8242d.png)

**A discount of 200% was given. Which in fact made the order's total equal to 0.00$!** Therefore we see it affect not only shipping costs but the whole order's total.

**Comment by pjedrzejewski** [comment]
Very nice bug report, thank you! :)

**Comment by TheMadeleine** [comment]
Was fixed in #6272 and can be closed now :)
