### ISSUE TITLE
[Payum] Exception for NotifyRequest when using Omnipay Bridge

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#6249]
I am using Payum and the Payum OmnipayBridge in production for some time now and most of the payments (95%) go through properly. But sometimes I get a message from the payment provider Mollie that the webhook returns a 500 error. Now it turns out that the `notify` url returns the following error:

![d](https://puu.sh/rrMTP/fac0213b99.png)

I have been trying to find out what is missing but don't know if it's a bug in Sylius or Payum itself.

I am using sylius `0.19` and the latest stable payum.

@makasim Do you maybe know why the notify url is failing?

**Comment by makasim** [comment]
The omnipay bridge does not support notify request. Though it should be easy to add. We need an payum action which supports Notify request and correctly proxy data to omnipay gateway related methods. 

https://github.com/Payum/OmnipayBridge/tree/master/src/Action

**Comment by makasim** [comment]
The issue is not related to Sylius. Could you please re open it here https://github.com/Payum/OmnipayBridge
