### ISSUE TITLE
Product filtering based on properties/options

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius#625]
This is common use case in most shops.

I have implemented one for http://bgbstudio.com/proizvodi/av-risiveri

We had custom filter set for each product category. Creating filters in admin by property, option, price, taxonomy...

![screenshot at 2013-11-20 12 31 28](https://f.cloud.github.com/assets/208957/1581489/540acbae-51d7-11e3-9396-66dd4a994e4d.png)

**Comment by bitbager** [comment]
Now you can use our free https://github.com/BitBagCommerce/SyliusElasticsearchPlugin 🙂
