### ISSUE TITLE
Allow injecting path prefix into private/js/semantic-ui-api-actions.js in ShopBundle

### ISSUE THREAD

**Issue by emodric** [Sylius/Sylius#6254]
It would be really helpful if we could somehow inject a configurable path prefix into `private/js/semantic-ui-api-actions.js` in Shop bundle.

Background:

I'm creating an integration with eZ Platform & Sylius: https://github.com/netgen/ezplatform-sylius. In the integration, all Sylius routes are prefixed with `/shop/` or `/sylius/admin/` in [main routing files](https://github.com/netgen/ezplatform-sylius/blob/1.5-sylius/app/config/sylius_routing.yml#L11-L17)

For the most part, this works very well, apart for some Ajax actions in the frontend, like adding a product into basket, which redirects to `/cart`, instead of `/shop/cart` after adding a product.

@crevillo discovered that the culprit are hardcoded paths in [`private/js/semantic-ui-api-actions.js`](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ShopBundle/Resources/private/js/semantic-ui-api-actions.js#L16).

Is there an other recommended way to override these paths maybe?

**Comment by michalmarcinkowski** [comment]
Fixed.

**Comment by Arminek** [comment]
@emodric Yep there is another way to do this you can simple use `data-url` semantic api calls automatically search on the element `data-url` or `data-action`. So we decided to drop this `semantic-ui-api-actions.js` and use `data-url`.
