### ISSUE TITLE
[RFC][Promotion] Unable to use the same coupon code for multiple promotions

### ISSUE THREAD

**Issue by koemeet** [Sylius/Sylius#6255]
I just stumbled onto this and I think the code should not be unique, since you can have multiple promotions that could be active with the same coupon code. Is this intentional or just a missing feature?

**Comment by steffenbrem** [comment]
To support this behaviour, I think the best thing would be to remove the `promotionCoupon` from the `Order` and use string property `couponCode` (isn't necessary to make it work, but it would be a lot cleaner). Then we can use this code in the `CouponsEligibilityChecker` and use it something like this:

```php
protected function isCouponEligible(PromotionInterface $promotion, PromotionCouponAwareSubjectInterface $subject)
{
    $coupon = $this->couponRepository->findOneByCodeAndPromotion($subject->getCouponCode(), $promotion);

    if (null === $coupon) {
        return false;
    }

    return $this->isCouponEligibleToLimit($coupon, $subject->getCustomer());
}
```

The reason to use the repository to fetch the actual coupon entity is for better performance, sometimes you have thousands of coupons.

With only these changes I think the coupons system is much more flexible. WDYT?

**Comment by rvanlaak** [comment]
Why would you want to be able to activate multiple promotions if you can also add as many rules and actions as you'd like? These actions in my opinion make it an `1..n` relationship, don't think the coupon should do that.

**Comment by steffenbrem** [comment]
@rvanlaak I had a case where the same coupon code should have different sets of promotions that don't belong together. Since rules and actions are applied on top of each other I need separate promotions.

**Comment by rvanlaak** [comment]
Interesting scenario, but still I think this shouldn't be handled by allowing two identical coupons. Your scenario basically states that sets of rules and actions should be linkable.

**Comment by lchrusciel** [comment]
@steffenbrem with #6489 it will be possible to do it with only one code. 

The promotion is applicable if customer bought anything from T-Shirt or Stickers taxon(current taxon rule). The we will have two actions defined with filtration. First will have 10% discount for T-Shirt taxon, the second one 20% for Stickers. Then you need to use only one coupon code.

**Comment by steffenbrem** [comment]
Promotion action filters will solve several use cases, which is cool to see. But I still think it would be very useful, because what if you want the 20% discount on stickers to be active on a certain date? With only action filters this isnt possible. I strongly believe coupon codes should be able to live across multiple promtions.

**Comment by michalmarcinkowski** [comment]
Promotion should represent a single promotion campaign which rules and actions should be clear and constant throughout the whole duration of promotion. I would say we should rather allow for applying multiple coupons to a single order than a single coupon to multiple promotions. IMO a single coupon should be uniquely connected to a specific promotion.
