### ISSUE TITLE
[User] Forgot Password

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#6262]
Sorry for the barrage of issues this weekend, just creating them as I see, and will fix what I get time for.

Forgot Password doesn't work the way it is, and there are a few problems:
1) The email sends the wrong link.
2) Once the link is adjusted, you realize "sylius.user.resetting.token_ttl" is not set anywhere, and it has to be set to a DateTime interval (P1D).
3) Once you do that, the template for resetting is broken because of a bad route

**Comment by pjedrzejewski** [comment]
@inssein Could you include any error logs/messages, please?

**Comment by inssein** [comment]
For each of the issues? If any one of those is not clear, let me know and I'll do my best by including logs and/or exactly where its incorrect.
