### ISSUE TITLE
[Shop] Wrong total on order item with discounts

### ISSUE THREAD

**Issue by Zales0123** [Sylius/Sylius#6267]
![zrzut ekranu 2016-10-03 o 13 45 26](https://cloud.githubusercontent.com/assets/6212718/19036554/ccb07382-8970-11e6-8ee9-d49470cefa87.png)

I suppose, order item "total" should be $560.00 - it seems as it contains also ``order`` promotions.
Promotion applied - 20% for every "jacket" product (``order_unit`` promotion) and $50 for whole order (``order`` promotion).

**Comment by patrick-mcdougle** [comment]
Related to #605 and #6190
