### ISSUE TITLE
SessionCartSubscriber calls getChannel

### ISSUE THREAD

**Issue by jorge-marques** [Sylius/Sylius#6279]
Currently, the SessionCartSubscriber component calls the getChannel method on cart. Since this component is part of the OrderBundle it throws an error when the bundle is used standalone.

Here's the spot, on the `onKernelResponse` method:

```
if (null !== $cart && null !== $cart->getId() && null !== $cart->getChannel()) {
  $session = $request->getSession();

  $session->set(
    sprintf('%s.%s', $this->sessionKeyName, $cart->getChannel()->getCode()),
    $cart->getId()
  );
}
```
Is this somehow intentional?

**Comment by michalmarcinkowski** [comment]
This class should be moved to `Core`. Perhaps we could provide channel independent implementation in `OrderBundle`.
