### ISSUE TITLE
[RFC] Extracting validation configuration from one big file to small, per-class files

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#6282]
Since Symfony 2.7 we can put validation constraints configuration not only into bundle's `Resources/config/validation.xml` but also into `Resources/config/validation/*.xml` files.

We can make validation configuration more similar to Doctrine mappings, JMS serializer configuration by extracting each class validation to an independent file like `Resources/config/validation/Product.xml` etc.

This proposition does not change the performance on production environments.

**Comment by pjedrzejewski** [comment]
Let's do this before tag.
