### ISSUE TITLE
listeners for sylius.cart_item.pre_create are not called

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#6318]
If I declare a listener like this : 

    my_app.test:
        class: My\Bundle\Service\Listener
        tags:
            - { name: kernel.event_listener, event: sylius.cart_item.pre_create, method: preCreate }

It is never called when I add an item in the cart. `sylius.order_item.pre_create` does not work either.
According to this PR https://github.com/Sylius/Sylius/pull/6134 and the actual master codebase (namely in `OrderItemController::addAction()` ), it looks like the event is dispatched, but the listeners are never called.

Am I missing something ?

**Comment by tchapi** [comment]
Ok, the bug is here : (in https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/OrderBundle/Controller/OrderItemController.php#L75)

     $event = $this->eventDispatcher->dispatchPreEvent('sylius.cart_item.pre_create', $configuration, $newResource);

This line is dispatching the event `sylius.order_item.pre_sylius.cart_item.pre_create` (!).
It should be :  

     $event = $this->eventDispatcher->dispatchPreEvent(ResourceActions::CREATE, $configuration, $newResource);

... and the listener should listen to `sylius.order_item.pre_create`. It's quite an easy fix I think ;)

**Comment by pjedrzejewski** [comment]
@tchapi Could you submit a PR, please? :)
