### ISSUE TITLE
[RFC] Should payments be stored in the order currency?

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#6319]
I am thinking about using my own implementation of the CurrencyConverter to to apply rounding logic on numbers after they have been converted. For example, if the product we are selling is $1000 USD, but some customers prefer to pay in CAD, we would rather show a nice rounded number, than the exact decimal conversion.

I already have this part working well, but I can foresee accounting issues if we ever change the way we round numbers, because we never store the final converted amount, we only store the exchange rate of the order at the time.

I had a PR to initially fix some of the currency issues (https://github.com/Sylius/Sylius/pull/6259) that took care of this. Would it make more sense to do it once like in the PR, rather than do it in every ConvertAction or the generic CaptureAction?

**Comment by michalmarcinkowski** [comment]
We reworked that recently, now you always pay in the same currency that the amounts are stored (base currency is per channel).
