### ISSUE TITLE
[Bug][Payum] Update payment state extension does not work for notify

### ISSUE THREAD

**Issue by steffenbrem** [Sylius/Sylius#6337]
Hi,

I noticed that the current implementation of the `PaymentStateExtension` ([source](https://github.com/Sylius/Sylius/blob/4bf30cee02d6d066dd3aff568b54c03c98791475/src/Sylius/Bundle/PayumBundle/Extension/UpdatePaymentStateExtension.php#L67)) is not taking `notify` requests into account. Some providers will use the notify url to later mark it as paid. As of right now, when a notify request is triggered the payment details are updated properly but not its state. This is because it always expects a top-level `GetStatus` request otherwise the whole payment state check is skipped.

I propose we check for both `GetStatusInterface` and `Notify` so the payment state is updated properly. Also the priority of the `PaymentStateExtension` should be before the `DoctrineStorage` extension, otherwise the payment state isn't even persisted to the DB.

/cc @makasim

**Comment by makasim** [comment]
👍

**Comment by steffenbrem** [comment]
Would it be preferable to load the `SyliusPayumBundle` before `PayumBundle`? That way the changes are flushed properly. I know that it used to be loaded after the `PayumBundle` but is that still needed?

Otherwise I will just load the `objectManager` in the extension and flush it manually there.

**Comment by makasim** [comment]
You can try to add append=true to extension service tag

This way it will be executed before storage extension
чт, 6 окт. 2016 г. в 18:40, Steffen Brem <notifications@github.com>:

**Comment by steffenbrem** [comment]
Nice, i've used the `prepend` attribute, much cleaner 👍
