### ISSUE TITLE
[Tax Adjustements] Tax Adjustements "disappear" after completing the addressing step

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#6341]
I have a cart, with correct tax calculation (_and a tax adjustement correctly stored in DB_). As soon as I complete the addressing step, the tax adjustments is removed from the `sylius_adjustement` table, thus tax is now 0.

I have a single tax rate (20%) attached to a zone that includes the country I'm shipping and invoicing in. It worked before (can't tell when the break happened though), and I didn't change the configuration related to taxes. Is there a BC break that I missed regarding taxes ?

It looks like a bug to me where too many rows get deleted after the`PUT /checkout/address`

**Comment by pjedrzejewski** [comment]
Can you provide a scenario which illustrates the issue? Have a look at our tax scenarios. :) Thank you!

**Comment by tchapi** [comment]
Ok, apparently I found the problem : If you define two zones that have the same countries in it, albeit having different scopes, the `getTaxZone()` method in **OrderTaxesProcessor** matches a zone regardless of the scope, and in my case, chooses a _shipping-scope_ zone that is not related to a tax category / tax rate, thus no taxes.

IMO, scope should be enforced more strongly, else it becomes impossible to have two separate zones for taxes and shipping, which is a real serious issue.

I would do something like : 

    $zone = $this->zoneMatcher->match($shippingAddress, 'tax');

at https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/OrderProcessing/OrderTaxesProcessor.php#L104

and in the admin, add the scope field.

**Comment by tchapi** [comment]
Hi @pjedrzejewski,
I don't think this is a feature request... it's a serious issue if one cannot create different zones for different scopes. Taxes and shipping are definitely not treated the same way .Take any country in Europe for instance. It's most likely that I can ship to any country in Europe for the same rate, thus creating a shipping zone for Europe makes sense. But taxes don't work that way ... and I will have a specific tax rate for my country, and another in all other european fellow countries.
The scope is really a simple way to resolve this problem, and is already implemented — WDYT ?

**Comment by pjedrzejewski** [comment]
@tchapi I labeled this as "feature request" because there is no UI for scopes in the new admin. I wanted to leave this as a feature for the devs / customizations, but it perhaps makes sense to expose it in the UI. I hope to have a look at it soon, thanks!

**Comment by tchapi** [comment]
Ok, got it, thanks a lot !

**Comment by tchapi** [comment]
Would you consider a PR for the UI (with limited scope choices for now, `tax` and `shipping` maybe), and the change in my above comment regarding the **OrderTaxesProcessor** ?

**Comment by tchapi** [comment]
Any chance you guys can look at this ? Because the actual behaviour still prevents Sylius from having tax zones different from shipping zones, which is highly incapacitating for an e-commerce website ... it's a no go if we want to ship throughout Europe so we cannot deploy until you fix this..

**Comment by tchapi** [comment]
Addressed in https://github.com/Sylius/Sylius/pull/7049
