### ISSUE TITLE
Documentation of Routing configuration mentions not existing file

### ISSUE THREAD

**Issue by davalb** [Sylius/Sylius#6369]
The documentation here: http://docs.sylius.org/en/latest/bundles/SyliusProductBundle/installation.html#routing-configuration says to add this
```
sylius_product:
    resource: "@SyliusProductBundle/Resources/config/routing.yml"
```
to `app/config/routing.yml`
But `@SyliusProductBundle/Resources/config/routing.yml`is not in the SyliusProductBundle. Is this line maybe outdated?

**Comment by pix-art** [comment]
@davalb You're right, this is still from the old days before everything was moved to resource bundle. Now all resource routes are handled from the resource bundle. I created a PR to remove this part.

**Comment by davalb** [comment]
thank you @pix-art !
