### ISSUE TITLE
How to enable or use product Reviews?

### ISSUE THREAD

**Issue by castwayalldc** [Sylius/Sylius#6391]
I've been trying to search a guide to enable or to show a form for create reviews for products but i haven't been able to find a way to make it work, i haven't seen anything about this in docs, i really appreciate if anyone can help.

I am using v0.17.0 of sylius.

**Comment by pjedrzejewski** [comment]
@castwayalldc If this is a new project, I'd recommend working with dev-master or waiting couple of days for 1.0.0.alpha tag. Reviews will be back within new few patches.

**Comment by castwayalldc** [comment]
Thank you @pjedrzejewski, and yes, this is a new project, i already found a way to add a new action in the product controller so i can allow users to add the review. Dont know if its the best practice but i guess is ok while that patch comes up.

**Comment by castwayalldc** [comment]
@pjedrzejewski how do i install sylius dev-master without having all bundle files inside src folder of the project?.

Is there any way to have all that files back on vendor, i made some custom entities and controllers and i wouldnt like to lose all of those changes, appart the dev-master version does not go out of memory on composer update.

**Comment by pjedrzejewski** [comment]
@castwayalldc You should use Sylius-Standard repository, but it will be updated in couple of hours. :)

**Comment by castwayalldc** [comment]
Ok Thank you
