### ISSUE TITLE
[Frontend] Shipping address validation fails

### ISSUE THREAD

**Issue by pborreli** [Sylius/Sylius#640]
Maybe related to #529 
![save-address](https://f.cloud.github.com/assets/77759/1604953/e440b4d2-53ca-11e3-812e-3b49e9084c0e.png)

**Comment by piermont** [comment]
@pamil This seems to still be happening on version 1.2.7. At first I thought it was due to the way I was importing the provinces (correct format should be XX-XX). I've tried that with country code GB and province GB-XX and still fails.
