### ISSUE TITLE
Help can't override HomepageController:indexAction from SyliusShopBundle

### ISSUE THREAD

**Issue by yosriMekni** [Sylius/Sylius#6403]
i overrided the HomepageController From SyliusShopBundle:indexAction to pass same data and display it in the index.html.twig but an exception keep appearing even if i clear the cache :

Catchable Fatal Error: Argument 1 passed to AppBundle\Controller\CustomHomepageController::__construct() must be an instance of Symfony\Bundle\FrameworkBundle\Templating\EngineInterface, none given, called in C:\wamp3\www\acme\app\cache\dev\appDevDebugProjectContainer.php on line 1619 and defined 

this is a link to my code :
http://stackoverflow.com/q/40003590/5092143

*excuse my english

**Comment by tchapi** [comment]
See my answer on StackOverflow — you miss the constructor argument in your service definition

**Comment by yosriMekni** [comment]
thx @tchapi  , now another exception appeared : An exception has been thrown during the rendering of a template ("None of the chained routers were able to generate route: Route 'sylius_shop_login' not found") in SyliusShopBundle:Homepage\Menu:_security.html.twig at line 7

**Comment by michalmarcinkowski** [comment]
@yosriMekni Sylius uses Stackoverflow as its official support channel. Please keep this discussion there. Thanks!

PS. You probably didn't import the shop routing

**Comment by yosriMekni** [comment]
ok , and thx
