### ISSUE TITLE
sylius_cart_form does not exist anymore

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#6423]
What is the replacement to get a form from the product ?

**Comment by inssein** [comment]
I duplicated what they had into my own Twig extension as I needed the form as well.

The helper in this case is `sylius.templating.helper.cart`.

```PHP
    /**
     * @return array
     */
    public function getFunctions()
    {
        return [
            new \Twig_SimpleFunction('sylius_cart_form', [$this, 'getItemFormView'])
        ];
    }

    public function getItemFormView(array $options = [])
    {
        return $this->helper->getItemFormView($options);
    }
```

I am guessing Sylius removed it because of the way they render the add to cart (render(url())).

**Comment by tchapi** [comment]
Yes, that's what I have done too. Seems like an easy solution. Thanks !
