### ISSUE TITLE
Make use of CustomerGroupRuleChecker

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#6436]
`Sylius\Component\Core\Promotion\Checker\Rule\CustomerGroupRuleChecker` is not tagged as rule checker and has no tests. We should make use of it in Sylius Core.

**Comment by tchapi** [comment]
Yeeees please ;)

**Comment by gabiudrescu** [comment]
Can I vote with 2 hands for this? we heavily rely on groups for marketing and promotions at bestvalue.eu

**Comment by michalmarcinkowski** [comment]
Done in #6959.
