### ISSUE TITLE
Redirect user to the register view after cart validation

### ISSUE THREAD

**Issue by Webarkitekt** [Sylius/Sylius#6454]
Hello,

I don't want the user to be able to checkout without creating a ShopUser Account.
We don't want to use the CustomerUser, because we think it's not very user friendly for our shop workflow.
So if the user is not logged i need him to register before adding the shipping/billing address.
Is there a way to redirect the user to the login / register view after cart validation and then to come back to the address view ? 

Thanks

**Comment by lchrusciel** [comment]
Probably the fastest way to achieve this, would be adding `{ path: "/checkout.*", role: ROLE_USER }` to `access_control` section in `app/security.yml`. Then, It would be required to login to access a checkout part. (Similar to access control for `account` path)

Anyway, such a questions should be asked on stackoverflow, as it is our main support channel.

Can be closed. /cc @pjedrzejewski @michalmarcinkowski

**Comment by Webarkitekt** [comment]
This is definitely an easy and very nice solution ;)
Thanks

Next time i will ask on stackoverflow.
