### ISSUE TITLE
[CoreBundle] AbstractResourceFixture could be in ResourceBundle

### ISSUE THREAD

**Issue by Niiko** [Sylius/Sylius#6456]
I'm currently using some of components/bundles of sylius to a custom project.

I want to use fixtures with resources, here is bundles used from my composer.json : 

```
        "sylius/fixtures-bundle": "dev-master",
        "sylius/grid-bundle": "dev-master",
        "sylius/resource-bundle": "dev-master",
        "sylius/user-bundle": "dev-master",
        "sylius/ui-bundle": "dev-master",
```

To write some fixtures, i have to extends Sylius\Bundle\CoreBundle\Fixture\AbstractResourceFixture.

For now, i duplicate this code and that's not a problem. I understand that ResourceBundle has not to be dependent of FixturesBundle in any way.

WDYT ?

**Comment by pamil** [comment]
Good catch! In fact we can put it directly in `FixturesBundle`, just removing some `ResourceBundle` dependencies (eg. `LazyOption` uses `RepositoryInterface`).

**Comment by Niiko** [comment]
Ok, will PR that one

**Comment by pamil** [comment]
Just need to think under which namespace we should put it not to bring confusion. The classes to be moved are `AbstractResourceFixture`, `LazyOption` and `ExampleFactoryInterface`.

Also, we should put explicit `doctrine/common` dependency in FixtureBundle's `composer.json`, as `doctrine/data-fixtures` doesn't guarantee to always require it.

**Comment by Niiko** [comment]
I agree, the choice of namespace name is a little bit tricky on that one.
