### ISSUE TITLE
Better naming for taxon-related rule checkers

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#6457]
- `TaxonRuleChecker` allows us to check if we have at least one product from at least one given taxon
- `ContainsTaxonRuleChecker` allows us to check if we have N products from the given taxon

Their names don't say enough I think 🐫

**Comment by gabiudrescu** [comment]
these rules created lots of discussions in our company, too.

TaxonRuleChecker with the default translation "Taxon" makes me think that cart should have all products from the taxons, not at least one from at least one given taxon.

I believe the behavior from TaxonRuleChecker could be achieved by using ContainsTaxonRuleChecker with value 1 which should translate in terms of UI like this:
 - rule "Contains number of items from taxon"
 - first option: "Taxons: Books, Stickers"
 - second option: "1 item"

to make it more semantic, I'd switch the form configuration to make it look like this:
![image](https://cloud.githubusercontent.com/assets/5156054/19660289/cfdf7260-9a37-11e6-95d6-1d3e57836bad.png)

----

if you still want to keep TaxonRuleChecker as a separate rule, I'd go for the following semantics:
 - className: ContainsFromMultipleTaxonsRuleChecker
 - label: Contains at least one from taxons
![image](https://cloud.githubusercontent.com/assets/5156054/19660377/2fa5b858-9a38-11e6-9db4-3d99e5af2fe8.png)

----

Anyway, I still have this question in my mind: why don't you modify ContainsTaxonRuleChecker to accommodate the behavior of multiple select for taxons from TaxonRuleChecker? 

What's the downside?

Or point the user to add multiple "ContainsTaxonRuleChecker" to achieve the same behavior from "TaxonRuleChecker" ?
