### ISSUE TITLE
[Shop] Add to cart doesn't show error message

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#6466]
If something will gone wrong during add to cart action, Sylius will not inform the user unfortunately.

<img width="1440" alt="zrzut ekranu 2016-10-19 o 13 41 30" src="https://cloud.githubusercontent.com/assets/6213903/19517481/c7d17440-9601-11e6-9d4d-862f5e908c82.png">

![zrzut ekranu 2016-10-19 o 13 41 59](https://cloud.githubusercontent.com/assets/6213903/19517494/d7d0b0ea-9601-11e6-8662-d9a1a5a5802c.png)

**Comment by jbator** [comment]
When I tried to add unavailable product to the cart I got this error:

`{"code":500,"message":"Expected argument of type \"lius\\Component\\Core\\Model\\OrderItem::setVariant() must implement interface Sylius\\Component\\Core\\Model\\ProductVariantInterface\", \"NULL\" given"}`

**Comment by pjedrzejewski** [comment]
Fixed.
