### ISSUE TITLE
Instalation error 

### ISSUE THREAD

**Issue by modogo2000** [Sylius/Sylius#6469]
Hello,

I try to install sylius for the first time but I have an issue .

This command is ok 

php composer.phar create-project -s dev sylius/sylius-standard mrk

But when I try this one 

php app/console sylius:install
Installing Sylius...

Step 1 of 4. Checking system requirements.
PHP Fatal error:  Class Sylius\Bundle\CoreBundle\Installer\Requirement\SettingsRequirements may not inherit from final class (Sylius\Bundle\CoreBundle\Installer\Requirement\RequirementCollection) in /var/www/html/mrk/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Installer/Requirement/SettingsRequirements.php on line 17

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Compile Error: Class Sylius\Bundle\CoreBundle\Installer\Requirement\SettingsRequirements may not inherit from final class (S
  ylius\Bundle\CoreBundle\Installer\Requirement\RequirementCollection)

I don't know what to I'm following the installation documentation.

Best regards

**Comment by michalmarcinkowski** [comment]
Are you sure you're using the newest version? This issue has been fixed already (see https://github.com/Sylius/Sylius/issues/6426).

**Comment by modogo2000** [comment]
Hi,

I'm using this command composer create-project -s dev sylius/sylius-standard acme

Best regards

**Comment by pamil** [comment]
Will be fixed by Sylius/Sylius-Standard#131.
