### ISSUE TITLE
[UiBundle] should not have a dependency on currency bundle and locale bundle

### ISSUE THREAD

**Issue by Niiko** [Sylius/Sylius#6473]
In fact, ui form theme has a dependency on 'sylius_currency_symbol' filter, which his in currency bundle.

``` twig
{% block money_widget -%}
    <div class="ui labeled input">
        <div class="ui label">{{ currency|sylius_currency_symbol }}</div>
        {{- form_widget(form) -}}
    </div>
{%- endblock money_widget %}

{% block sylius_translations_row -%}
    <h4 class="ui dividing header">{{ form_label(form) }}</h4>
    <div class="ui grid">
        {% for translation in form %}
            <div class="four wide column">
                {{ form_label(translation, translation.vars.name|sylius_locale_name) }}
            </div>
            <div class="twelve wide column">
                {{ form_widget(translation) }}
            </div>
            {{- form_errors(form) -}}
        {% endfor %}
    </div>
{%- endblock sylius_translations_row %}

{% block sylius_product_option_value_widget %}
    <div class="ui segment">
        {{ form_row(form.code) }}
            <div class="five fields">
            {% for locale, translationForm in form.translations %}
                {{ form_row(translationForm.value, {'label': locale|sylius_locale_name}) }}
                {% if 0 == loop.index % 5 %}
                </div>
                <div class="five fields">
                {% endif %}
            {% endfor %}
            </div>
    </div>
{% endblock %}

```

I don't know how to remove that dependency. We can remove that block override on form theme, and add it in core maybe, with an extend of ui form theme ? But we then need to change every template with that new one.

WDYT ?

**Comment by loic425** [comment]
I had the same problem yesterday with a project.
I've also seen some ui translations in this bundle which are very specifics to sylius.

**Comment by Zales0123** [comment]
Over two years and it's still the case 😄 On the other hand, is there any use-case for using *SyliusUIBundle* without the **Sylius** itself? And if there is no such thing, perhaps we should not allow downloading *UiBundle* separately? cc @pamil

**Comment by loic425** [comment]
@Zales0123 Maybe It could be the solution to make a fork of this bundle for projects like Monofony.
Use Resource/Grid/Ui combination allows you to build a backend as faster as on a Sylius project.
