### ISSUE TITLE
[AdminBundle] Products without a taxon are not visible on products page

### ISSUE THREAD

**Issue by sweoggy** [Sylius/Sylius#6485]
As title, is this the intended behaviour?

I discovered this issue when I was adding products to an otherwise empty shop, with no taxons at all. To remedy the situation I had to create a taxon and visit each product's edit url directly and assign that taxon. Afterwards all products were visible.

**Comment by pjedrzejewski** [comment]
I just checked and it works. You only need to assign product to the channel. (we may improve that UX soon) but taxon should not affect this. Product is displayed both on the admin and latest products box in shop. Please reopen if still an issues after you try setting the channel.

**Comment by sweoggy** [comment]
You seem to be correct, I thought I chose a default channel, but apparently I did not (works fine now without taxon).
