### ISSUE TITLE
Error with sylius:install:sample-data

### ISSUE THREAD

**Issue by Alcondez** [Sylius/Sylius#6487]
I have a fresh install of sylius-standard, and when I do sylius:install:sample-data I get the following error:

Load sample data? (y/N) y
Loading sample data...
 0/1 [|                           ]   0%

  [Symfony\Component\Debug\Exception\ContextErrorException]  
  Catchable Fatal Error: Argument 1 passed to Sylius\Component\Core\Model\Channel::addPaymentMethod() must implement interface Sylius\Component\Payment\Model\PaymentM  
  ethodInterface, null given, called in /home/developer10/Repos/edevel/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php on  
  line 134 and defined 

The project is up and running locally, I just cant load the sample data.  Did I miss something during the installation?

**Comment by yukoff** [comment]
I'm facing the same issue, I defined two payment gws in config without luck. Further investigation showed there are at least two arrays with nulls:
```
$options[payment_methods] => Array
        (
            [0] =>
            [1] =>
        )
```
and
```
$options[shipping_methods] => Array
        (
            [0] =>
            [1] =>
            [2] =>
        )
```
so even with some hacking it will fail later on shipping methods with error
```
Type error: Argument 1 passed to Sylius\Component\Core\Model\Channel::addShippingMethod() must implement interface Sylius\Component\Shipping\Model\ShippingMethodInterface, null given, called in /home/yukoff/sandbox/sylius/vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Fixture/Factory/ChannelExampleFactory.php
```
