### ISSUE TITLE
Sylius/Sylius-Standard improvement suggestion

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#6497]
I was trying to install the latest version of Sylius/Sylius-Standard to see how it would be for a newcomer, and I realized that it still brings you 0.18. 

Why not 0.19? 

Or by using `composer create-project sylius/sylius-standard . -s alpha` - to install the latest alpha tag?

**Comment by pjedrzejewski** [comment]
@gabiudrescu I tagged Sylius yesterday, but today I will update the standard edition and release a blog post. :)
