### ISSUE TITLE
Alpha1 feedback

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#6498]
I've installed the latest version and I'll try to post here all the feedback I see (from the user point of view):
- the links here point to nowhere: 
  ![image](https://cloud.githubusercontent.com/assets/5156054/19575507/7fe2ccb2-9717-11e6-8851-46e59514b2eb.png)
- the media button here does nothing: 
  ![image](https://cloud.githubusercontent.com/assets/5156054/19575558/d12c6902-9717-11e6-90c1-b08c7df89d24.png)

I'll play with it more tomorrow, but so far - congrats to all of you who pulled this off!

**Comment by pjedrzejewski** [comment]
The links in the footer are just placeholders, we do not have a CMS in core now. :) We may make them functional with LakionSyliusCmsBundle at some point.
