### ISSUE TITLE
Sylius : add entity administrator to admin panel

### ISSUE THREAD

**Issue by yosriMekni** [Sylius/Sylius#6509]
I have created a new entity and i want to add it's adminisrator to admin panel in admin dashboard i've followed the steps in the sylius docs but no changes :
AppBundle/Resources/config/services.yml:

services: app.admin.menu_builder_listener: class: AppBundle\EventListener\MenuBuilderListener tags: - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addBackendMenuItems } - { name: kernel.event_listener, event: sylius.menu_builder.backend.sidebar, method: addBackendMenuItems }
AppBundle\EventListener\MenuBuilderListener.php :

`<?php

namespace AppBundle\EventListener;

use Sylius\Bundle\UiBundle\Menu\Event\MenuBuilderEvent;
use Sylius\Bundle\WebBundle\Event\MenuBuilderEvent as FrontendMenuBuilderEvent;

class MenuBuilderListener
{
/**
* @param MenuBuilderEvent $event
*/
public function addBackendMenuItems(MenuBuilderEvent $event)
{
$menu = $event->getMenu();

$menu->addChild('backend_main')
    ->setLabel('Test Backend Main');
}

/**

@param FrontendMenuBuilderEvent $event
*/
public function addFrontendMenuItems(FrontendMenuBuilderEvent $event)
{
$menu = $event->getMenu();

$menu->addChild('frontend')
->setLabel('Frontend Menu Item');
}
}`
i tried clearing cache but no chance

**Comment by yosriMekni** [comment]
@pjedrzejewski can you take a look to my issue plz

**Comment by lchrusciel** [comment]
Please, consider folowing:
1. Add markup to improve readability of your problem
2. Post it on a stackoverflow with `sylius` tag.

We would be really happy to help you, but SO is our main support channel. This one is not an issue. It is a support request.

Probably can be closed.

**Comment by yosriMekni** [comment]
i have actually posted my issue on stackoverflow : http://stackoverflow.com/questions/40158530/sylius-add-entity-administrator-to-admin-panel , but no help .
well you can close this issue because i've fixed it .
