### ISSUE TITLE
[SettingsBundle] How about planning for settings?

### ISSUE THREAD

**Issue by liverbool** [Sylius/Sylius#6523]
I would like to use SettingBundle in Core, How about this bundle?

cc @pamil @pjedrzejewski

**Comment by pjedrzejewski** [comment]
SettingsBundle is not going anywhere, although we are not using it in the core itself.

**Comment by liverbool** [comment]
Any planing to refactor the SettingBundle?

**Comment by pjedrzejewski** [comment]
@liverbool We did that recently, what else would you like to change? :)

**Comment by liverbool** [comment]
Nothing @pjedrzejewski I just want to make sure to using it in my production.

**Comment by pjedrzejewski** [comment]
Go for it! :)
