### ISSUE TITLE
[SonataIntlBundle] Is it needed?

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#6525]
This bundle is added to main composer file, but it isn't in bundles which use it. 

Nevertheless, `format_date` is used only 8 times(7 after #6521) in whole Sylius project. I haven't checked rest of its filters yet. Do we really need it? If so, we should add it to AttributeBundle(used forth times), AdminBundle(used twice) and ShopBundle(used once)

**Comment by Niiko** [comment]
FYI, It was originally added in #5385 

In fact, we can just extract this logic but we have ton maintain it. 

Localized dates are required, especially in multi-zone shops.

**Comment by lchrusciel** [comment]
Sure, so we should just add it to AttributeBundle, AdminBundle and ShopBundle requirements. Thanks for explanation @Niiko!
