### ISSUE TITLE
[Core] Attempted to call an undefined method named "guessExtension" of class "SplFileInfo".

### ISSUE THREAD

**Issue by crevillo** [Sylius/Sylius#6533]
Hi. i'm trying to build a script that reads files from a ftp server and tries to assign those images to a product. i was trying to use the ImageUploader for it, something like 
```php
<?php
 $productImageFactory = $this->getContainer()->get('sylius.factory.product_image');
 $imageUploader = $this->getContainer()->get('sylius.image_uploader');

 $productImage = $productImageFactory->createNew();
 
/** @var ProductImage $image */
 $image = $productImageFactory->createNew();
 $image->setCode(basename($file));
 $image->setFile(new \SplFileInfo("/tmp/" . $file));
 $imageUploader->upload($image);
?>
```

Problem is the uploading file saying
```
[Symfony\Component\Debug\Exception\UndefinedMethodException]   Attempted to call an undefined method named "guessExtension" of class "SplFileInfo".    Did you mean to call "getExtension"?  
```

As far i can see, http://php.net/manual/es/class.splfileinfo.php, error seem legit, as there is no `guessExtension` method in that class... 

Or am I missing something? 

Thank you.

**Comment by isometriks** [comment]
I think you need to use this: https://github.com/symfony/http-foundation/blob/master/File/File.php or UploadedFile. That hint should probably be changed though as the ImageInterface does only require \SplFileInfo yet the uploader uses that quessExtension method because Symfony uploaded files are turned into the above UploadedFile

**Comment by crevillo** [comment]
Thanks. using File indeed works for me. i'm closing this then. Thanks a lot for the explanation.
