### ISSUE TITLE
[Settings] - How enable SyliusSettingsBundle

### ISSUE THREAD

**Issue by nietzcheson** [Sylius/Sylius#6534]
I want enable [this bundle](http://docs.sylius.org/en/latest/bundles/SyliusSettingsBundle/index.html). I follow all steps. But, the routing indicate in the doc (**"@SyliusSettingsBundle/Resources/config/routing.yml"**) doesn't exist within the bundle. 

In fact, no information [here](http://docs.sylius.org/en/latest/book/settings.html)

Any idea?

**Comment by michalmarcinkowski** [comment]
The SettingsBundle was removed from Core and will be transferred to a different repository
