### ISSUE TITLE
Creating Product press enter to submit form does nothing - Easy Pick

### ISSUE THREAD

**Issue by bretto36** [Sylius/Sylius#6548]
If you press enter to submit the form on a create simple product page. It gives a js error which stops the page from processing the form. 

Issue is on this line in product-attributes.js (line 58 i believe)

$(this).parent().find('select').val().forEach(function(item) {
data += 'sylius_product_attribute_choice[]=' + item + "&";
                });

If i click submit button it's fine. But only happens when i press enter on a form field.

**Comment by Zales0123** [comment]
Still an issue 💃  @kulczy can you take a look at this?

**Comment by pamil** [comment]
Fixed by #10213.
