### ISSUE TITLE
Change product sitemap urls or disable ProductUrlProvider

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#6556]
Hi
I'm trying to change the urls created by the **ProductUrlProvider**. I know I can add a new provider for the sitemap, but how can I change **ProductUrlProvider** ? The class is `final` so I cannot extend it.

I'd like to disable it, or to be able to change its behaviour

Thanks !

**Comment by tchapi** [comment]
Anyone ? It's quite important for the SEO that we can override the default behavior for **ProductUrlProvider**.. Removing this provider altogether is also an option but to date it's not possible, is it ?

**Comment by Arminek** [comment]
@tchapi Sorry about that #6861. Sitemap feature is a great for independent sylius extension.

**Comment by tchapi** [comment]
Waiting for that extension soon then, because an e-commerce website without sitemap is totally pointless, don't you think ?

**Comment by tchapi** [comment]
Nevermind, I'll reimplement it
