### ISSUE TITLE
Column 'code' cannot be null when I try to add picture

### ISSUE THREAD

**Issue by lucassimonin** [Sylius/Sylius#6561]
Hi,

I got this error in BO (v1.0.0-alpha) when I try to add a picture to my product :

An exception occurred while executing 'INSERT INTO sylius_product_image (code, path, owner_id) VALUES (?, ?, ?)' with params [null, "32\/dd\/28f0b9dba5559620edebbb6094ad.jpeg", 425]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'code' cannot be null

I got the same issue on demo (Error 500) can you fix this issue please ?

Thanks

**Comment by GSadee** [comment]
Could you give us some details about that? I've tried to recreate this bug, but everything locally and also on demo looks good.

**Comment by lucassimonin** [comment]
If you add picture by here :

![image](https://cloud.githubusercontent.com/assets/5131392/19768588/643adcac-9c58-11e6-8197-d9f622de9b90.png)

Nothing happend (We think that), but when you tried to submit you got :

![image](https://cloud.githubusercontent.com/assets/5131392/19768616/909b07c2-9c58-11e6-83fc-09f5e39d680b.png)

**Comment by GSadee** [comment]
Ok, we have a problem that validation message doesn't appear, because a code is required.

**Comment by lucassimonin** [comment]
Oh ok I understand the problem thank you :)
