### ISSUE TITLE
[Shop] Problem with two users trying to buy units of a product with few stock

### ISSUE THREAD

**Issue by crevillo** [Sylius/Sylius#6572]
To illustrate what i'm trying to say, here's how to proceed
- Set one product to tracked and set inventory available to 3
- Now open one browser and add two units of that product to the cart
- Open a second browser and add two units of the same product too
- In the first browser complete your checkout process
  - at that moment, you will have `on_hand = 3` and `on_hold = 2` for that product
- now try to finish the checkout process in the second browser. 
  - you will be prompted from your data
  - you will be prompted to choose shipping method
  - you choose one shipping method, click "Next" button and you will be still in the shipping method selection screen with no error warning or anything similar. 

What i would be expect is if in my cart i have 2 units in the product, i couldn't start the checkout process at all.  Sylius should tell me something "hey, sorry, but somebody was quicker than you and we have no stock for that"

**Comment by patrick-mcdougle** [comment]
This is a duplicate of #2776
