### ISSUE TITLE
Missing tag on packages

### ISSUE THREAD

**Issue by Raptek** [Sylius/Sylius#6579]
Is there any reason why packages such as Grid, GridBundle and Storage aren't tagged as v1.0.0-alpha.1?

**Comment by michalmarcinkowski** [comment]
Thanks for reporting! Something must went wrong during tagging. @pjedrzejewski please have a look at this issue.

**Comment by michalmarcinkowski** [comment]
As reported in #6737, CustomerBundle also...

**Comment by pjedrzejewski** [comment]
I just released v1.0.0.alpha.2 on all packages, sorry for the trouble! Storage has been removed.
