### ISSUE TITLE
Issue with currency and locales admin panel 

### ISSUE THREAD

**Issue by yosriMekni** [Sylius/Sylius#6585]
i've added some currencies and locales in the admin panel but when i dump locales and currencies varibles in the "_locale.html.twig" and "_currency.html.twig" its only shows one element wich is the first one in the sylius_currency and sylius_locale tables , knowing that i've make sure that their are aperfectly added

**Comment by michalmarcinkowski** [comment]
What do you mean by "dump locales and currencies varibles in the "_locale.html.twig" and "_currency.html.twig""? If you want to display them in shop, make sure they are assigned to the channel.

**Comment by michalmarcinkowski** [comment]
I guess it is resolved, please reopen if still an issue.
