### ISSUE TITLE
[Review] ReviewBundle coupled with ProductBundle

### ISSUE THREAD

**Issue by Zales0123** [Sylius/Sylius#6594]
While working on reviews, I realized that *ReviewBundle* is sadly coupled with *ProductBundle* - in ``services.xml`` we use [resource events for product_review](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ReviewBundle/Resources/config/services.xml#L30) and [product manager and repository](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ReviewBundle/Resources/config/services.xml#L43) which don't exist in *ReviewBundle* itself 😕  🌵

**Comment by michalmarcinkowski** [comment]
Should be fixed by #6811.

**Comment by GSadee** [comment]
I'm not sure if we fixed this coupling https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ReviewBundle/Resources/config/services.xml#L23

**Comment by michalmarcinkowski** [comment]
It won't break anything, this event will never be dispatched, so this listener will never get invoked, but the ReviewBundle can be installed and used without ProductBundle.
