### ISSUE TITLE
Unable to override or customize productController 

### ISSUE THREAD

**Issue by yosriMekni** [Sylius/Sylius#6598]
I'm using Sylius version 1.0.0-alpha.1 i followed all steps in th [docs](http://docs.sylius.org/en/latest/customization/controller.html) . But i'm unable to override ProductContoller in the AppBundle.
link to [Stackoverflow](http://stackoverflow.com/q/40347294/5092143)

This is the code that i'm using :
`<?php
namespace AppBundle\Controller;

use FOS\RestBundle\View\View;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Sylius\Bundle\CoreBundle\Controller\ProductController as BaseProductController;
use Sylius\Bundle\ResourceBundle\Controller\ResourceController;
use Sylius\Component\Resource\ResourceActions;

class ProductController extends ResourceController
{
public function allProdSpecificTaxonAction(Request $request, $taxonName){

    $locale = $this->get('sylius.context.locale')->getLocale();
    /** @var Taxon $taxon */
    $taxon = $this->get('sylius.repository.taxon')
    ->findByName($taxonName,$locale);
    var_dump($taxon);
    exit;
}
}

?>`

I get this error ; 

`Attempted to load class "ProductController" from namespace "Sylius\Bundle\CoreBundle\Controller".
Did you forget a "use" statement for another namespace?`

**Comment by next-sentence** [comment]
You should extend ResourceController, seems ProductController has been deleted.

**Comment by yosriMekni** [comment]
when i do that this error appeared :
InvalidConfigurationException in ArrayNode.php line 317:
Unrecognized option "classes" under "sylius_product"

**Comment by next-sentence** [comment]
try this config
```
sylius_product:
    resources:
        product:
            classes:
                controller: AppBundle\Controller\ProductController
```

**Comment by yosriMekni** [comment]
i've tried that and it gives me : 404 Not Found

**Comment by next-sentence** [comment]
I guess you don't have that product you try to load and this method gives you 404
`   $product = $this->findOr404($configuration); 
`

**Comment by yosriMekni** [comment]
actually  i've changed my action in the controller  , and it want executed it , 
this my routing :
`app_bundle_product:
    path: /products/cat/{taxon.name}
    defaults:
        _controller: sylius.controller.product:allProdSpecificTaxonAction`
my productController : 
`class ProductController extends ResourceController
{
public function allProdSpecificTaxonAction(Request $request, $taxonName){

    $locale = $this->get('sylius.context.locale')->getLocale();
    /** @var Taxon $taxon */
    $taxon = $this->get('sylius.repository.taxon')
    ->findByName($taxonName,$locale);
    var_dump($taxon);
    exit;}}`

**Comment by yosriMekni** [comment]
i dont think its a Support Request , it should be Potential Bug because i've followed this docs :
http://docs.sylius.org/en/stable/bundles/general/overriding_controllers.html

**Comment by yosriMekni** [comment]
if its a documentation bug can you plz tell me the proper way to override the controller ?

**Comment by yosriMekni** [comment]
i've managed to do some changes  and now an other exception appeared : 
this my post on [http://stackoverflow.com/q/40347294/5092143](stackoverflow)
Catchable Fatal Error: Argument 1 passed to Sylius\Bundle\ResourceBundle\Controller\ResourceController::__construct() must implement interface Sylius\Component\Resource\Metadata\MetadataInterface, none given, called in C:\wamp3\www\sidratsoft_website\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Controller\ControllerResolver.php on line 186 and defined

**Comment by next-sentence** [comment]
use  sylius.controller.product:allProdSpecificTaxonAction instead of  AppBundle:Product:allProdSpecificTaxonAction

```
app_bundle_product:
path: /products/cat/{taxon}
defaults:
    _controller: sylius.controller.product:allProdSpecificTaxonAction
```

**Comment by yosriMekni** [comment]
it works ,thank you very much ;)

**Comment by bretto36** [comment]
Please close the issue if this is resolved

**Comment by michalmarcinkowski** [comment]
The documentation still needs to be updated, opened a separate issue about that :)

**Comment by artyom-wcd** [comment]
still outdated in 2020
