### ISSUE TITLE
[Promotion] Unable to overwrite Action factory

### ISSUE THREAD

**Issue by rvanlaak** [Sylius/Sylius#6602]
We've upgraded `0.17` to `0.19`, and now aren't able to manually add promotion actions anymore. After diving into the code I've spotted the problem, decorating the factory is wrong. The related error is:

> Warning: Missing argument 1 for Sylius\Component\Resource\Factory\Factory::__construct(), called in /www/vendor/sylius/resource/Factory/Factory.php on line 39 and defined

The code that is responsible for the error can be found in the [`SyliusPromotionExtension`](https://github.com/Sylius/Sylius/commit/6757589a6d05ecc0441ee172d0de0f33f43401a3#diff-cb1b8612a570d72d1050f43e4dffeb49L81).

What is happening, is that the `Factory::$className` actually is the original `Factory` class itself. So when [`createNew`](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Resource/Factory/Factory.php#L39) is executed, it doesn't create a `sylius.model.promotion_action.class` but a new version of the decorated `Factory`.

I think the overwriteActionFactory should be changed to the following code, but before filing a PR I'd like to get your feedback first.

```php
    /**
     * @param ContainerBuilder $container
     */
    private function overwriteActionFactory(ContainerBuilder $container)
    {
        $promotionActionFactoryClass = $container->getParameter('sylius.factory.promotion_action.class');
        $promotionActionModelClass = $container->getParameter('sylius.model.promotion_action.class');

        $decoratedPromotionActionFactoryDefinition = new Definition($promotionActionFactoryClass, [$promotionActionModelClass]);
        $container->setDefinition('sylius.factory.promotion_action', $decoratedPromotionActionFactoryDefinition);
    }
```

Is this fixed in `v1.0.0-alpha`? Otherwise we'll upgrade to that version instead of filing a PR.

**Comment by rvanlaak** [comment]
After thinking about this, adding Rules still works correct for us. But, the `SyliusPromotionExtension` does not have a `overwriteRuleFactory`, it only has `overwriteActionFactory`. So, does this mean the `RuleFactory` can't be overwritten?

**Comment by rvanlaak** [comment]
FYI: Commenting out the functionality in the `overwriteActionFactory` function, and rebuilding the container for now resolved this issue for us. I know it's a crappy fix ;)

**Comment by pamil** [comment]
There's some weird magic going on, I've sent a #6628 which may help :)

**Comment by rvanlaak** [comment]
@pamil probably some old decoration code that was left behind right? :-) We'll upgrade to `1.0.0-alpha2` once it's released, any ETA for that?
