### ISSUE TITLE
[RFC] (root) Taxon with children taxons behavior in listing

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#6604]
⚠️ 🛣 **This issue is a part of the** [Sylius Public Roadmap](https://github.com/orgs/Sylius/projects/2) 🛣 ⚠️

Preconditions:
 - I have 3 taxons like this:
   - TShirts
       - Men
       - Women
 - I have 4 products where Men taxon is assigned
 - I have 8 products where Women taxon is assigned

Steps to reproduce:
 - go to http://sylius.localhost/taxons/category/t-shirts/men and observe the 4 products 
 - go to http://sylius.localhost/taxons/category/t-shirts/women and observe 8 products
 - go to http://sylius.localhost/taxons/category/t-shirts

What happens: 
 - there is no product

What I think it should happen:
 - see all the 12 products assigned to the children taxons of T-Shirts

----

![image](https://cloud.githubusercontent.com/assets/5156054/19903052/d5ac9378-a075-11e6-81d9-d8e433d9cc66.png)

![image](https://cloud.githubusercontent.com/assets/5156054/19903072/e3893fb4-a075-11e6-9e48-f25d399c464a.png)

----

We have implemented such a behavior here, based on ElasticSearch: 
 - https://bestvalue.eu/listing/parfumuri 
 - https://bestvalue.eu/listing/parfumuri/apa-de-parfum
 - https://bestvalue.eu/listing/parfumuri/apa-de-toaleta

**Comment by gabiudrescu** [comment]
@pjedrzejewski isn't this supposed to be already available for testing on http://demo.sylius.org/ ? how often do you deploy?

**Comment by michalmarcinkowski** [comment]
The demo will be updated tomorrow to the 1.0.0-beta release 🎉 . After that we will deploy on each release.

**Comment by teohhanhui** [comment]
I believe this was not fixed the right way. Any product listing of a parent taxon must automatically include products from all its children. It is counter-intuitive and error prone for the user to have to manually add products from child taxons directly to the parent taxon. And it's especially problematic when you have a more nested hierarchy.

**Comment by teohhanhui** [comment]
And putting the `/` in the taxon slug is a ugly hack that is again very error prone. Imagine you have tens or hundreds of child taxons, and if you rename or change the slug of the parent taxon, you'll have to then make sure to update the slug for each child taxon?

**Comment by pamil** [comment]
I agree with @teohhanhui as the current behaviour has always been counterintuitive to me and AFAIK all Sylius' ElasticSearch plugins on the market solve this problem. 

I'm reopening this issue and tagging it as a feature, because the current behaviour has existed for so long that fixing it to show nested products could be a BC break for some.

As for the second comment, could you make a separate issue for that?

**Comment by teohhanhui** [comment]
To me, the two comments are about the same issue.

**Comment by gabiudrescu** [comment]
@pamil yes, I agree https://github.com/Sylius/Sylius/issues/9229 :+1:

**Comment by lchrusciel** [comment]
Brace yourself, @bartoszpietrzak1994 save the day with a PR to our demo :D https://github.com/Sylius/SyliusDemo/pull/49

**Comment by lchrusciel** [comment]
And it is done :)
