### ISSUE TITLE
Cant change field label or field type in the grid

### ISSUE THREAD

**Issue by yosriMekni** [Sylius/Sylius#6610]
i'm using sylius alpha version 
i posted my issue on [stackoverflow](http://stackoverflow.com/q/40379855/5092143) , knowing that i followed this [docs](http://docs.sylius.org/en/latest/cookbook/custom-model.html)

**Comment by yosriMekni** [comment]
Actually the changes appeared only  with action or index actions but not with create ?!

**Comment by pjedrzejewski** [comment]
@yosriMekni Grid is only used for index. In create/update actions form labels are used. Have a look at translations customization guide to learn how to tweak them. :)

**Comment by pjedrzejewski** [comment]
Please reopen if still in doubt. :)

**Comment by yosriMekni** [comment]
thank you

**Comment by yosriMekni** [comment]
how can i upload files related to some model with sylius plz

**Comment by Zales0123** [comment]
@yosriMekni please, ask such questions on [stackoverflow](http://stackoverflow.com/questions/tagged/sylius) - I know that it's necessary to wait sometimes a bit for answer, but **Issues** on github should be used only to report potential bugs, improvements, ideas for future etc.
