### ISSUE TITLE
Handling abandoned orders

### ISSUE THREAD

**Issue by Frosthaven** [Sylius/Sylius#6616]
Checkout workflow:
After clicking "place order", if the user changes their mind and closes the browser or leaves to another site a few things happen:

- The order is placed in their order history
- The order in the admin panel is listed as "awaiting payment"

I can't find a way for the user to pay for the unpaid item via the UI if they return to the site at a later date. The order appears to be stuck in "awaiting payment" limbo with no way out aside from having an admin either cancel or manually process it.

Question:

1. Is it possible to only have orders that have been paid for added to the order history? (state machine settings?)
2. Optional: Is it possible for the order history to include a "pay now" button on incomplete orders? (template override that links to order summary screen with "pay now"?)

**Comment by pjedrzejewski** [comment]
I think we should add a button in the order history, we have everything for that already, so we just need to add a link to ``sylius_shop_order_show`` page, which allows changing payment method or paying. Could you open a PR? That would be awesome! :)

**Comment by inssein** [comment]
There are two commands I run(`sylius:cancel-unpaid-orders` and `sylius:remove-expired-carts`) that help with the cleanup.

**Comment by michalmarcinkowski** [comment]
Fixed in https://github.com/Sylius/Sylius/pull/6718.
