### ISSUE TITLE
Extend a product and its fixtures (v1.0.0-alpha)

### ISSUE THREAD

**Issue by leogout** [Sylius/Sylius#6617]
Hi, I am currently trying to create some fixtures for a product that I extended. My product have some custom required options, but it's basically the same as the Sylius one.

I was wondering if there is a way to extend the fixtures as well, keeping in mind that they are final.

After some digging, I saw that I needed to code a whole new fixture with a new `CustomProductFixture`, a new `Factory\CustomProductExampleFactory` and a new `TShirtCustomProductFixture` on top of that with their own config files and their own suite which is not ideal. Do you have any better solution ?

By the way, thank you for this amazing project, I've learned a lot about symfony and php in general just by exploring your code.

**Comment by michalmarcinkowski** [comment]
Now after #6907 you can extend fixtures, we will add docs soon.
