### ISSUE TITLE
[Documentation] about Behat

### ISSUE THREAD

**Issue by crevillo** [Sylius/Sylius#6619]
Hi there. I'm asking for support here. No issue at all :). 

I'm a bit new to behat also. Anyway, the main question i have is how can i add tests from my own bundle. i'm looking to the [doc](http://docs.sylius.org/en/latest/behat/) and there i see
`To add a new context to Behat container it is needed to add a service in to one of a following files cli.xml/domain.xml/hook.xml/setup.xml/transform.xml/ui.xml in src/Sylius/Behat/Resources/config/services/contexts/ folder:`

So, first question: Does this mean i can only add contexts from here? is there any way to add them from my own bundle? 

Thank you.

**Comment by lchrusciel** [comment]
As you have asked for support, please go to [stackoverflow](http://stackoverflow.com/questions/tagged/sylius).

**Comment by crevillo** [comment]
sure, sorry, i added here as i saw this https://github.com/Sylius/Sylius/labels/Support%20Request

**Comment by lchrusciel** [comment]
We just try to move all this question there, to clean issues on a main repo. Thanks for understanding!
