### ISSUE TITLE
"$condition" attribute generated via doctrine:generate:entities (v1.0.0-alpha)

### ISSUE THREAD

**Issue by leogout** [Sylius/Sylius#6627]
Hi, I don't know if it comes from Symfony itself or from the sylius project but I didn't found any issue on this at Symfony/Symfony or doctrine/doctrine2.

Every time I run `php app/console doctrine:generate:entities AppBundle:Whatever`, in my `Whatever` entity I get an extra attribute and its getters / setters :
```php
/**
 * @var string
 */
private $condition;

/**
 * Set condition
 *
 * @param string $condition
 * @return Product
 */
public function setCondition($condition)
{
    $this->condition = $condition;

    return $this;
}

/**
 * Get condition
 *
 * @return string 
 */
public function getCondition()
{
    return $this->condition;
}
```
I've installed the full stack project (v1.0.0-alpha1) from composer. Tell me if you want more info.

Cheers.

**Comment by tchapi** [comment]
See https://github.com/Sylius/Sylius/issues/5502

**Comment by leogout** [comment]
Thanks for taking the time to answer and sorry for this.
