### ISSUE TITLE
Problem installing Sylius when using sylius:install

### ISSUE THREAD

**Issue by loicGR** [Sylius/Sylius#6638]
I installed Sylius as explained in http://docs.sylius.org/en/latest/book/installation.html. 
No problem when using : composer create-project
Problem occur when i type : app/console sylius:install

`C:\Data\OneDrive\PhpstormProjects\Dev\nec001>php app/console sylius:install
Installing Sylius...

Step 1 of 4. Checking system requirements.
+-------------------------------+---------------------------------------------------------------------+
| Issue                         | Recommendation                                                      |
+-------------------------------+---------------------------------------------------------------------+
| short_open_tag                |                                                                     |
| session.auto_start            |                                                                     |
| sylius.extensions.accelerator | Install and enable a PHP accelerator like APC (highly recommended). |
+-------------------------------+---------------------------------------------------------------------+
Success! Your system can run Sylius properly.

Step 2 of 4. Setting up the database.
Creating Sylius database for environment dev.
It appears that your database already exists. Would you like to reset it? (y/N) n
Seems like your database contains schema. Do you want to reset it? (y/N) n
 0/5 [|                           ]   0%

  **[Symfony\Component\Filesystem\Exception\IOException]
  Cannot rename "C:\Data\OneDrive\PhpstormProjects\Dev\nec001\app\cache\de_" to "C:\Data\OneDrive\PhpstormProjects\Dev\nec001\app\cache\dev".**`

Does anyone has a solution ?
I'am on Window system and using Wamp3.06 with Apache 2.4.9, PHP 7, MySql 5.6.
Sylius version is 0.18-dev

**Comment by yukoff** [comment]
Hi @loicGR, I've seen this several times - not sure about what causing it (maybe some locking issues?), usually re-running the command goes without a problem - to avoid running a complete installation you may check it with `cache:clear`. However on windows there's much more unpleasant issue - sass|scss|css sources are meant to be bult by gulp using node-sass, which I haven't manage to get working :( [here](/sass/node-sass/issues/1790)
```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\Apps\\node-v6.9.1-win-x64\\node.exe" "D:\\Apps\\node-v6.9.1-win-x64\\node_modules\\npm\\bin\\npm-cli.js" "run" "gulp"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! @ gulp: `gulp`
npm ERR! Exit status 1
```

**Comment by yukoff** [comment]
@loicGR, just realized your project is in OneDrive folder - so maybe it could be really related to locking - syncronization done by OneDrive's service.

**Comment by loicGR** [comment]
@yukoff, it works now. I don't know why. Maybe it's OneDrive.
