### ISSUE TITLE
[supportRequest] Credit Card Details Form.

### ISSUE THREAD

**Issue by whitebook** [Sylius/Sylius#6650]
Can someone point me to the docs where I can enable the credit card details form to the checkout process. I am trying to figure out how to disable the "select-payment" screen in the DEMO app and replace it with the enter credit card details screen.

Not clear on how to do this. 

Thanks in advance for your guidance.

**Comment by michalmarcinkowski** [comment]
Please post such questions on stackoverflow under "sylius" tag, it's the official support channel, maybe someone will be able to help you there.

**Comment by nietzcheson** [comment]
@michalmarcinkowski please reopen the issue and report it as part of the documentation. There is no clear information on how to implement the CreditCardType.
