### ISSUE TITLE
[supportRequest] storing menu items in database/ integrate KtwDatabaseMenuBundle  with Resources items

### ISSUE THREAD

**Issue by Mr-Negative** [Sylius/Sylius#6652]
I'm stuck completly.
Has anybody maybe have used https://github.com/kevintweber/KtwDatabaseMenuBundle or any other way to store menu items in database? i can extend menu via usuall way, but client want to store them in database and have option to edit them. 

If i add manually to database items, i can display it, but it's not well integrated.
Anybody has working example?

**Comment by michalmarcinkowski** [comment]
Please post such questions on StackOverflow under "sylius" tag, it's the official support channel, maybe someone will be able to help you there.
