### ISSUE TITLE
issue with Many-to-Many association mapping , help plz

### ISSUE THREAD

**Issue by yosriMekni** [Sylius/Sylius#6655]
this my post on [stackoverflow](http://stackoverflow.com/q/40483173/5092143)

**Comment by michalmarcinkowski** [comment]
I know that there are more people on Github than on StackOverflow, but Github issues should not be used as support requests. Creating an issue with reference to StackOverflow is a bad idea. Github issues should address bugs, improvements and feature requests. Definitely shouldn't be used to resolve your technical issues during custom development. We will do our best to encourage more people to regularly visit StackOverflow and help resolving such issues. Thanks for understanding!
