### ISSUE TITLE
[BUG] DefaultCalculator - Tax calculator.

### ISSUE THREAD

**Issue by liverbool** [Sylius/Sylius#6664]
This's should be bug. Why difference calculation between `isIncludedInPrice` and `none isIncludedInPrice`?

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Taxation/Calculator/DefaultCalculator.php#L28

**Comment by michalmarcinkowski** [comment]
It is not a bug. See the examples:

**Tax included in price:**
```
Given the store has included in price "VAT" tax rate of 23%
And the store has a product "T-Shirt" priced at "$10.00"
When I add product "T-Shirt" to my cart
Then my cart total should be "$10.00"
And my cart taxes should be "$1.87"
```

**Tax excluded from price:**
```
Given the store has excluded from price "VAT" tax rate of 23%
And the store has a product "T-Shirt" priced at "$10.00"
When I add product "T-Shirt" to my cart
Then my cart total should be "$12.30"
And my cart taxes should be "$2.30"
```

**Comment by michalmarcinkowski** [comment]
@TheMadeleine it's not the first question about that, I think we need to put these examples in the docs.

**Comment by liverbool** [comment]
Oh my mistake , sorry 🤗

**Comment by liverbool** [comment]
@michalmarcinkowski I have a question, in front-end how i we know that this product contains  included or not included in price vat?

In the end how i can display user friendly tax label in my store?
