### ISSUE TITLE
[AttributeBundle] error with boolean storage type (v0.19)

### ISSUE THREAD

**Issue by loic425** [Sylius/Sylius#6669]
I've an error when an attribute has a boolean storage with form type.
`Could not load type "sylius_attribute_type_boolean"`

This seems to be fixed on sylius1.0.0-alpha (i've tried on sylius demo) but i don't find the fix on pull-requests or issues.

**Comment by michalmarcinkowski** [comment]
Fixed already, but I couldn't find the fix also 😞
