### ISSUE TITLE
Why doesn't Core/Model/Image use TimestampableTrait ?

### ISSUE THREAD

**Issue by leogout** [Sylius/Sylius#6681]
Hi,
Shouldn't [Core/Model/Image](https://github.com/Sylius/Sylius/blob/v1.0.0-alpha.1/src/Sylius/Component/Core/Model/Image.php) use the TimestampableTrait ?
For now, `$createdAt` is declared dynamically in its [constructor](https://github.com/Sylius/Sylius/blob/v1.0.0-alpha.1/src/Sylius/Component/Core/Model/Image.php#L46).

If it isn't done on purpose, I can create a PR to fix this.

Cheers.

**Comment by pjedrzejewski** [comment]
I am 👍 !

**Comment by pamil** [comment]
Shouldn't we remove `createdAt` instead? I don't think it's needed for an image.

**Comment by michalmarcinkowski** [comment]
Agree with @pamil. Fields like `createdAt` and `updatedAt` on image are not used in Core and should not be required for all images. If someone find such fields useful, he will need some customization anyway so he can also add them as it's super easily.

**Comment by pjedrzejewski** [comment]
On the other hand, cost of maintaining this feature in the core is low (pretty much none) - customizing it is easy, although will be repetitive for many. I can see a use-case for knowing when product image was added or edited.
