### ISSUE TITLE
[BUG][DOC] - Repair doc in doc.sylius.org

### ISSUE THREAD

**Issue by nietzcheson** [Sylius/Sylius#6693]
Could you please repair this documentation: http://docs.sylius.org/provisioning/index.php

Regards

**Comment by okwinza** [comment]
What about http://docs.sylius.org/en/latest/ ?

**Comment by nietzcheson** [comment]
Sorry. The link that fails is SyliusResourceBundle

**Comment by michalmarcinkowski** [comment]
`ResourceBundle` docs are working (see http://docs.sylius.org/en/latest/bundles/SyliusResourceBundle/index.html). Could you point to the issue?

**Comment by nietzcheson** [comment]
The issue consisted of a redirect I wanted to enter @ResourceBundle. I deleted all caches and it worked again.
