### ISSUE TITLE
[Admin][CSS] Css issue in admin in /orders/edit

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#6696]
When a product name is too long, the containing UI element overflows to the right and breaks the page. See on the right sidebar of the below screenshot

![screen shot 2016-11-11 at 12 11 43](https://cloud.githubusercontent.com/assets/1944007/20213275/1c7d317e-a808-11e6-806b-e1f4726e99d7.png)

**Comment by davidangel** [comment]
I would like to take a shot at addressing this issue. Do we think truncating the product title with an ellipsis?

While we're on the topic, I kind of expected the product title to link to the product admin page, instead of the storefront's detail page. Should this behavior be changed?

**Comment by pjedrzejewski** [comment]
@davidangel +1 for truncating it and displaying a full name in title of the link. Regarding the link itself, it should point to the admin page, especially that our admin should be decoupled from shop, so its a bug if that's the case. :)
