### ISSUE TITLE
Mark SyliusCartBundle as deprecated

### ISSUE THREAD

**Issue by davalb** [Sylius/Sylius#6701]
After reading about the 1.0-branch, I get the impression that the [SyliusCartBundle](https://github.com/Sylius/SyliusCartBundle) is no longer really part of the Sylius-framework.
If this is the case, please mark it as deprecated in the bundles README file. This can prevent future users of Sylius to waste a lot of time, by digging into the code of the CartBundle.
I can do this too, but I am not sure where to submit the PR since the SyliusCartBundle is READ-ONLY

**Comment by michalmarcinkowski** [comment]
@pjedrzejewski are you able to do it?

**Comment by pjedrzejewski** [comment]
Done, thanks for the heads up David!
