### ISSUE TITLE
release SyliusShopBundle separately on packagist

### ISSUE THREAD

**Issue by davalb** [Sylius/Sylius#6702]
I would like to require the ShopBundle into my application (since it seems to have all the cart-functionality if I am not mistaken). Is it possible to release it as a seperate bundle?

**Comment by okwinza** [comment]
ShopBundle is basically frontend templates, routes, and stuff, it doesn't contain any business logic/features by itself.

Therefore there is no point using it standalone.

**Comment by michalmarcinkowski** [comment]
If you want to use AdminBundle and/or ShopBundle, you should require `sylius/sylius` and simply put into the Kernel only these bundles that you need.

**Comment by davalb** [comment]
ok, I understand. It is kinda inconsistent though, that the AdminBundle is independently available but the ShopBundle is not.

**Comment by pjedrzejewski** [comment]
I just marked both Api & Admin bundles as abandoned. We will remove the composer.json's from them soon. (most likely, I need to give it a bit more thought)

**Comment by jordisala1991** [comment]
Is there a possibility to keep updating the Api and the Admin atleast? It is easy to understand that someone might not want the full shopBundle, but it is normal to expect a backoffice working out of the box, and being able to install it without using `sylius/sylius` would be nice.

Atm the package is abandoned on packagist, but it is still updated on the master branch (the tags are not being created though).

@pjedrzejewski @pamil
