### ISSUE TITLE
Wrong interface given for FlashHelper 

### ISSUE THREAD

**Issue by kurakin-oleksandr** [Sylius/Sylius#6704]
After installation I got an error:
`Sylius\Bundle\ResourceBundle\Controller\FlashHelper::__construct() must be an instance of Symfony\Component\Translation\TranslatorBagInterface, instance of Symfony\Component\Translation\IdentityTranslator given`

I've to override service like this:
```
  translator:
    class: "%translator.class%"
    arguments:
      - "@service_container"
      - "@translator.selector"
      - []
      - { cache_dir: "%kernel.cache_dir%/translations", debug: "%kernel.debug%" }
    calls:
      - [setConfigCacheFactory, ['@config_cache_factory']]```

**Comment by NeverResponse** [comment]
Just installed sylius/sylius and sylius/sylius-standard and in both cases FlashHelper works.
My guess is something went wrong with your config file.

Please check if you have the default sylius config.yml, the part concerning translation should look something like:
``` yaml
framework:
    translator: { fallbacks: ["%locale%"] }
```

And if you'd prefer not having fallbacks go:
``` yaml
framework:
    translator: { enabled: true }
```
or:
``` yaml
framework:
    translator:
        enabled: true
```
Whichever of those will overwrite the `translator` service id  with the [symfony's default translator](https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Translation/Translator.php), and the flash helper will work anew.

**Comment by kurakin-oleksandr** [comment]
@NeverResponse, thanks, it helps. I was blind enough to miss that `framework: translator` was commented out
