### ISSUE TITLE
Wrong xml_root_name in CoreBundle/.../Model.OrderItem.xml

### ISSUE THREAD

**Issue by leogout** [Sylius/Sylius#6706]
Hi, shouldn't [this line](https://github.com/Sylius/Sylius/blob/v1.0.0-alpha.1/src/Sylius/Bundle/CoreBundle/Resources/config/serializer/Model.OrderItem.yml#L3) be `xml_root_name: order-item` instead of `xml_root_name: order` ?

**Comment by pjedrzejewski** [comment]
Yes, PR would be great if you have a moment, thanks! :)

**Comment by leogout** [comment]
As soon as I finish work,

Cheers.

**Comment by tcaron** [comment]
Hi, i work on it :)

**Comment by leogout** [comment]
Thank you for that, didn't got the time yesterday !

**Comment by pjedrzejewski** [comment]
👍
