### ISSUE TITLE
[Admin][Product] Product->getSlug() tries to load non-existing translation class

### ISSUE THREAD

**Issue by sweoggy** [Sylius/Sylius#6739]
I have a custom product model, extending the Product model from the CoreBundle, following the guidelines provided by the docs, http://docs.sylius.org/en/latest/customization/model.html.

It was working just fine until one of the slug related commits to the Product model was pushed. Now I am no longer able to create new products (editing existing works just fine), instead the following error is thrown:

![stacktrace product model](https://cloud.githubusercontent.com/assets/5914253/20315012/9174cdaa-ab5c-11e6-8b73-3d8d88949032.PNG)

I have not extended the ProductTranslation class, since I didn't need to, so I am not surprised it can't find that class...

As a workaround I have changed TranslatableTrait's row 163 from get_called_class() to get_class(), but I don't think that is a proper fix.

**Comment by michalmarcinkowski** [comment]
Unfortunately the translation class is specified in a poor way, so you need to override `getTransaltionClass` method in your custom Product model and specify the translation class directly:
```
    /**
     * {@inheritdoc}
     */
    public static function getTranslationClass()
    {
        return Sylius\Component\Core\Model\ProductTranslation::class;
    }
```

This should be added to docs.

**Comment by sweoggy** [comment]
That worked thanks, not sure I like that coupling though 😓
