### ISSUE TITLE
new installation - standard edition alpha doesn't pull project git files

### ISSUE THREAD

**Issue by Mr-Negative** [Sylius/Sylius#6740]
Older version of standard edition had .git folder and files, co it was possible to update to current git version by git pull in vendor/sylius catalog. Now it doesn't have it after 
`$ composer create-project -s alpha sylius/sylius-standard acme`

How to make it possible to update to current [with all merged pull requests]?

**Comment by sweoggy** [comment]
Change the Sylius requirement (sylius/sylius) to use the master branch in composer.json:

```
"require": {
        ...

        "sylius/sylius": "dev-master",

        ...
},
```

Then run (may take a while):
`$ composer update`

**Comment by Mr-Negative** [comment]
doh! good idea (git pull was faster but still). Thanks
