### ISSUE TITLE
[UiBundle] display overflow on paginator with too many pages (v1.0.0-alpha1)

### ISSUE THREAD

**Issue by loic425** [Sylius/Sylius#6747]
I have a display problem on a paginator with too many pages.

Have you plan to improve it ?

![capture d ecran 2016-11-16 a 14 05 54](https://cloud.githubusercontent.com/assets/8329789/20348463/d49d2dee-ac05-11e6-84f1-aeec9bfe9274.png)

**Comment by loic425** [comment]
I think it could be great to contribute on pagerfanta to purpose a SemanticUiTemplate extending Pagerfanta\View\Template.

Maybe, I'll work on it soon...

**Comment by loic425** [comment]
@pjedrzejewski @michalmarcinkowski 
I started working on SemanticUiTemplate

The second step is to submit a pull-request on pagerfanta and whiteoctober pagerfanta. So tell me if this could be ok for you.

![capture d ecran 2016-11-16 a 17 47 34](https://cloud.githubusercontent.com/assets/8329789/20356536/16cf3184-ac25-11e6-9ad3-1affeafa974e.png)

**Comment by michalmarcinkowski** [comment]
Looks good to me!

**Comment by pjedrzejewski** [comment]
Looks great, @loic425 Please submit the PR, hopefully it will get merged in time to use it in Sylius, nice work! :)

**Comment by loic425** [comment]
@michalmarcinkowski @pjedrzejewski 
Ok, i'll do that today. If the pagerfanta merge is too long, it's possible to add SemanticUiTemplate and SemanticUiView in sylius Ui component and SemanticUiTranslatedView in SyliusUiBundle in waiting for pagerfanta merge and remove them later.

**Comment by pjedrzejewski** [comment]
@loic425 Agreed, please post the PR here when it is open - I will help with speeding up the merge (by being a bit annoying, as we are short on time :D).

**Comment by loic425** [comment]
@pjedrzejewski 
[PR on Pagerfanta](https://github.com/whiteoctober/Pagerfanta/pull/216)
[PR on PagerfantaBundle](https://github.com/whiteoctober/WhiteOctoberPagerfantaBundle/pull/150)

**Comment by loic425** [comment]
@pjedrzejewski 
@michalmarcinkowski 
We have no news from White October team... Do you want to wait a little or make a copy into Sylius Ui Component and SyliusUiBundle ?

**Comment by pjedrzejewski** [comment]
@loic425 I tweeted - https://twitter.com/pjedrzejewski/status/800664021938606080. Let's wait 1-2 days and if still nothing, then we should add it to SyliusUiBundle. :)

**Comment by loic425** [comment]
@pjedrzejewski 
No news, so i'm gonna do a sylius pull-request :)

**Comment by loic425** [comment]
@pjedrzejewski 
There's an answer from whiteoctober :) yes !

**Comment by michalmarcinkowski** [comment]
@loic425 do you think it will be possible to get it merged tomorrow?

**Comment by loic425** [comment]
@michalmarcinkowski 
Yep, i think it's possible if i copy all the files on sylius in waiting for pagerfanta new release.
