### ISSUE TITLE
Static content removed in alpha?

### ISSUE THREAD

**Issue by Mr-Negative** [Sylius/Sylius#6751]
I'm updating v0.19 tu dev-master, and i don't see Static content in admin in new dev-master from today, but its visible in demo. 
Should there be static content or it is removed?

**Comment by okwinza** [comment]
It was recently removed. yep.

**Comment by okwinza** [comment]
By the way, why are you upgrading so often? With all these BC breaks the best strat would be to lock on some version and iterate your app on it. Afterwards you could update the core pretty easily. 

IMO. of course.

**Comment by Mr-Negative** [comment]
Yeah, normally i would do as you said, but i needed to update some library dependencies, and wa in need of few pull requests from alpha and it just made a sense to update it now.

IMO Weird decision to remove it.

**Comment by okwinza** [comment]
@Mr-Negative it was a brick on the road to SF3 support so IMO it is good decision.
And it will be back eventually.

**Comment by okwinza** [comment]
@Mr-Negative and don't forget you can always backport things to your app.

**Comment by michalmarcinkowski** [comment]
@Mr-Negative static content will be provided as an extension (see [this comment](https://github.com/Sylius/Sylius/pull/6717#issuecomment-260636697)).
