### ISSUE TITLE
[Admin] Product / Media file upload

### ISSUE THREAD

**Issue by psihius** [Sylius/Sylius#6771]
Because the default input of type "file" is hidden and a custom button is used, right now when you select a file, you can't see that you did that.
It appears as if the functionality is not working, but in fact it does work. This is a major "WTF" moment for everyone involved, especially the people who are going to work with it.

**Comment by ascameron1** [comment]
Has this been fixed yet?

**Comment by juice77** [comment]
Any news?

**Comment by liverbool** [comment]
Bad UX and easy pick, v1.0.0 please.
