### ISSUE TITLE
Validation for negative value of on hand product variants

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#6778]
During my work on #6768 I have realized that even if there is constraint defined on `on hand` property it doesn't work. I have to focus on some other part of Sylius, so if anyone can investigate it further, please resolve it :)

**Comment by zerho** [comment]
have the same issue since 0.19

**Comment by michalmarcinkowski** [comment]
The logic is hardcoded in method. It doesn't allow to set value lower than 0, so we won't have a negative `onHand` ever.
