### ISSUE TITLE
[Admin] Product variant is lost after editing the variant

### ISSUE THREAD

**Issue by crevillo** [Sylius/Sylius#6786]
In our project we are working in a import script that creates variant. Each variant has it's own name. 

But after, when you try to update the variant from the admin interface, name fields is not being showed in the form. Submitting the form updates the variant setting its name to empty... 

this implies that you can't identify the variant in the product page. see attached pic. 
![captura de pantalla de 2016-11-20 13-04-00](https://cloud.githubusercontent.com/assets/306215/20462582/f01a0c94-af21-11e6-9040-37266cd0d482.png)

**Comment by pjedrzejewski** [comment]
Thank you for reporting and fix!
