### ISSUE TITLE
Adding a product to cart fails after https://github.com/Sylius/Sylius/pull/6712

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#6800]
After https://github.com/Sylius/Sylius/pull/6712, when adding a product to the cart, I now have a 500 :  

`Unable to find template "/add.html.twig" (looked into: [....]/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form, [....]/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views).`

It was working correctly just before

**Comment by michalmarcinkowski** [comment]
I don't see any changes in this PR that could result in such exception, are you sure it is caused by that changes? Maybe you could provide more details about the issue?

**Comment by tchapi** [comment]
I guess that now the add to cart form is not valid anymore since some form elements changed names : https://github.com/Sylius/Sylius/pull/6712/files#diff-9d5b70e08529570f3a50b320100ed508R15

But my form doesn't have any `cartItem` element in it. 

The question is, now, how do we construct the add_to_cart form programmatically and pass it on to our templates ? I was using CartHelper's `getItemFormView()` but now it's broken ...

**Comment by michalmarcinkowski** [comment]
You should use `sylius_add_to_cart` form type (https://github.com/Sylius/Sylius/pull/6712/files#diff-9ba956790fd44c9622c2f90d6072a87cR48).

**Comment by tchapi** [comment]
Changed that already, but it's the CartHelper that is still broken.

**Comment by tchapi** [comment]
I guess the CartHelper should be changed to reflect the PR :

```
    public function getItemFormView(array $options = [])
    {
        $cartItem = $this->orderItemFactory->createNew();

        $form = $this->formFactory->create(
            'sylius_add_to_cart',
            $this->addToCartCommandFactory->createForCartAndCartItem($this->cartContext->getCart(), $cartItem),
            $options
        );

        return $form->createView();
    }
```

**Comment by lchrusciel** [comment]
I'm pretty sure, you are not displaying a regular form, just submitting data to this endpoint. 

Because of `AddToCartType` the required parameters have changed the form is not valid anymore. Unfortunately, with our current solution if request is wrong we are only checking if request was a regular html request or an api one. Because it is an html one we are going straight to [this line](https://github.com/Arminek/Sylius/blob/bb2a8710cbd65689ebade08c2036f61b0131abcb/src/Sylius/Bundle/OrderBundle/Controller/OrderItemController.php#L97) which cause an error, because you don't have `add.html.twig` file.

**Comment by tchapi** [comment]
Trust me I'm displaying a regular form that emanates from CartHelper's `getItemFormView()` in **Sylius\Bundle\OrderBundle\Templating\Helper**. But this helper does not produce valid forms anymore, hence the solution I have given two comments above with a modified CartHelper method.

**Comment by tchapi** [comment]
**CartHelper** is removed in https://github.com/Sylius/Sylius/pull/6843 so I guess this is now N/A. For the sake of documentation here is how I have implemented my own cart helper :  

```php
<?php

namespace My\WebBundle\Form;

use Symfony\Component\Form\FormFactoryInterface;
use Sylius\Component\Order\Context\CartContextInterface;
use Sylius\Component\Resource\Factory\FactoryInterface;
use Sylius\Bundle\OrderBundle\Factory\AddToCartCommandFactory;
use Sylius\Bundle\CoreBundle\Form\Type\Order\AddToCartType;

/**
 * Create an ad hoc form view for a product
 *
 * @author tchapi
 */
class MyOwnCartFormHelper
{
    /**
     * @param CartContextInterface $cartContext,
     * @param FactoryInterface $orderItemFactory,
     * @param FormFactoryInterface $formFactory,
     * @param AddToCartCommandFactory $addToCartCommandFactory
     */
    public function __construct(
        CartContextInterface $cartContext,
        FactoryInterface $orderItemFactory,
        FormFactoryInterface $formFactory,
        AddToCartCommandFactory $addToCartCommandFactory
    ) {
        $this->orderItemFactory = $orderItemFactory;
        $this->addToCartCommandFactory = $addToCartCommandFactory;
        $this->formFactory = $formFactory;
        $this->cartContext = $cartContext;
    }
    
    /**
     * @param array $options
     *
     * @return FormView
     */
    public function getItemFormView(array $options = [])
    {
        $cartItem = $this->orderItemFactory->createNew();

        $form = $this->formFactory->create(
            AddToCartType::class,
            $this->addToCartCommandFactory->createForCartAndCartItem($this->cartContext->getCart(), $cartItem),
            $options
        );

        return $form->createView();
    }
}
```
