### ISSUE TITLE
How to override CartItemType Class?

### ISSUE THREAD

**Issue by castwayalldc** [Sylius/Sylius#6836]
Please i need to add some custom fields to this form and i havent found a clear way to override this form, tried to override in the sylius_order resource, by adding cart_item, but it does not exist.

Thank you in advance.

**Comment by michalmarcinkowski** [comment]
Closing as it's a duplicate of https://github.com/Sylius/Sylius/issues/6635. Working on making this form type configurable, should be implemented really soon.
