### ISSUE TITLE
I can't update Sylius Project

### ISSUE THREAD

**Issue by alanrivetta** [Sylius/Sylius#6854]
Hello! 

I have a problem with Sylius and Composer:

When run `composer create-project -s alpha sylius/sylius-standard acme` , OK

When run `composer require knplabs/knp-menu:^2.1` :
```
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 58720256 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/RuleSet.php on line 73

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.
```

System:
Windows 7 x64
RAM: 4gb
Composer 1.2.2
PHP 7 (Memory limit 1G) (too -1 and same results)

In other project without Sylius i dont have problems

**Comment by michalmarcinkowski** [comment]
It indicates memory limit, composer with Sylius uses over 1G. Please post such questions on stackoverflow under "sylius" tag, it's the official support channel, maybe someone will be able to help you there.
