### ISSUE TITLE
[Migrations] Error executing new migrations from v1.0.0-alpha.2

### ISSUE THREAD

**Issue by crevillo** [Sylius/Sylius#6858]
Hello, We have updated our project to v1.0.0-alpha.2

Trying to execute `php app/console doctrine:migrations:migrate` we get a crash saying
```shell
Migration 20161102145826 failed during Post-Checks. Error An exception occurred while executing 'SELECT t0.code AS code1, t0.name AS name2, t0.color AS color3, t0.description AS description4, t0.enabled AS enabled5, t0.hostname AS hostname6, t0.created_at AS created_at7, t0.updated_at AS updated_at8, t0.id AS id9, t0.theme_name AS theme_name10, t0.tax_calculation_strategy AS tax_calculation_strategy11, t0.default_locale_id AS default_locale_id12, t0.base_currency_id AS base_currency_id13, t0.default_tax_zone_id AS default_tax_zone_id14 FROM sylius_channel t0':

SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.base_currency_id' in 'field list'
```

Afaik, there has been a change in the name of a column, but that change is done in a migration that has not been executed yet, because is newer than the one failing... 

I mean, migration failing is `20161102145826` and migration that change that column name is `20161117163856`  https://github.com/Sylius/Sylius/blob/v1.0.0-alpha.2/app/migrations/Version20161117163856.php

Is this a bug or is there any workaround to execute?

Thank you!.

**Comment by michalmarcinkowski** [comment]
That's strage, because it works on Travis...

**Comment by crevillo** [comment]
@michalmarcinkowski , can it be because in travis the database is recreated? i already have some data in my db that i would like to keep. thinking in channel definitions or something like that. doing `sylius:install` seems to work fine.
