### ISSUE TITLE
When creating a new product, mainTaxon is set to 1

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#6859]
When creating a new product ion the backend, the `mainTaxon` field is automatically populated with the value `1`.

Moreover, we cannot remove the `mainTaxon` (i.e. set it to `null`)

I'm on the latest master.

**Comment by michalmarcinkowski** [comment]
Probably we should add `required => false` to the form type.

**Comment by tchapi** [comment]
And somewhere in **TaxonChoiceType** there should be an option to set it to `null` I guess — I didn't really dive into the code but adding a choice `=> null` should do the trick

**Comment by michalmarcinkowski** [comment]
@pamil please you make sure your changes in forms will include this fix 😉

**Comment by pjedrzejewski** [comment]
This is more of an UI issue, I will fix it. (choices are not loaded, so it is using 1, 95% sure that's the problem) :D

**Comment by michalmarcinkowski** [comment]
Fixed.

**Comment by tchapi** [comment]
It's fixed when we create a new product but I just tested on latest master and when you have selected a main taxon, you cannot remove it afterwards (no "null" option in the choice list) — or am I missing something ?

**Comment by michalmarcinkowski** [comment]
You're right.
