### ISSUE TITLE
Error during checkout if restricted product is the only product in the cart

### ISSUE THREAD

**Issue by umpirsky** [Sylius/Sylius#686]
This issue is related to https://github.com/Sylius/Sylius/pull/665.

Scenario is following: non authenticated user adds restricted product to cart, during the checkout he enters address with country matching restricted zone. `RestrictedZoneListener` removes item from cart, so cart is empty. `HttpException` is thrown in https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/FlowBundle/Validator/ProcessValidator.php#L105

@pjedrzejewski Can we improve cart validation handling so it sends user back to cart? Any other ideas?

**Comment by Sp0ng3b0b** [comment]
What would be the quickest way to hide that exeption from the user and show a nice message?

**Comment by michalmarcinkowski** [comment]
This feature was removed, so the issue is no longer valid
