### ISSUE TITLE
The AddressBundle should support four level cascade selection

### ISSUE THREAD

**Issue by videni** [Sylius/Sylius#6862]
```
Country - > Province -> City -> District 
```
Just like the relationship between country and province , I think the other two should also  have a similar relation.   

1. Create  Address 
that is when a province is selected , those cities under that province shows up, the behavior for district is also the same.

2. Edit Address
    the selected province , city , district should be selected 

This  use case is used very widely , I don't understand why the AddressBundle doesn't cover the common case.

**Comment by pjedrzejewski** [comment]
I know that this is quite easy to customize already, we had some developers doing that. I am not sure it is popular enough use-case. We definitely won't introduce this to 1.0. This can be a plugin perhaps.
