### ISSUE TITLE
[1.0.0-alpha.1] [Cart] JavaScript cart success handler does not respect DEV mode

### ISSUE THREAD

**Issue by psihius** [Sylius/Sylius#6872]
When adding a product to the card in dev mode through "app_dev.php", the JS forwards us to /cart without any regard for the mode the shop is running in.
This results in unknown database error, because usually on dev machine you do not have the production database setup.
app.js at line 778 defines the URL and 852 does the redirect. 

> Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1049] Unknown database 'xxxxxxxxxx'

**Comment by michalmarcinkowski** [comment]
Should be fixed on master. Please reopen if still relevant.
