### ISSUE TITLE
Version in CoreBundle Kernel was not updated after alpha2 release 

### ISSUE THREAD

**Issue by gorkalaucirica** [Sylius/Sylius#6874]
It's not critical at all but may create confusion that still [Kernel shows alpha1 release in profiler](https://github.com/Sylius/Sylius/blob/e9a7f64de2a844aaca4b0ebaa665c8f0c0c983d6/src/Sylius/Bundle/CoreBundle/Application/Kernel.php#L24), I guess now it's late to update it

**Comment by pjedrzejewski** [comment]
Yes... I noticed that too, after merging some PRs. So yeah, it is too late. Luckily we have next tag coming soon. Thanks for the heads up! :)
