### ISSUE TITLE
Hijacking an account

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#6883]
Sylius version: dev-master (https://github.com/Sylius/Sylius/commit/dc31f7c9ccf596fd1c6c59ec88c66858059d9543)

Steps to reproduce:
 - place an order using test@test.com
 - try to register with the email test@test.com

What happens:
 - you get full access to change the payment method of an order for any email address - without confirming the address first

What should happen:
 - you should not be able to access any restricted resources before confirming access to an email address

by restricted resources I mean:
 - orders
 - addresses

**Comment by michalmarcinkowski** [comment]
A see the following solutions for this:

1. Not allow for guest orders
    a.) Enforce registration before placing an order
    b.) Always create account for "guest" customer (on checkout complete) and sent the generated password through email
2. Confirm account before being able to login (https://github.com/Sylius/Sylius/issues/3444) - IMO poor UX
3. Hide orders history and addresses (this can be tricky since we display address book and prefill address during checkout) for accounts which didn't confirm email address

WDYT?

**Comment by patrick-mcdougle** [comment]
I vote for 1b. Create an account for the person, but send temp password in "welcome email". If that is lost, then force "forgot password" on re-use of that account.

**Comment by okwinza** [comment]
+1 on 1b

**Comment by michalmarcinkowski** [comment]
The drawback of 1b is that when you place a guest order and you would like to place order again as guest, you will have to login.

There is also another, not so good option, but maybe will help with coming up with more solutions:

 4. Mark guest orders as "guest" and filter them out in my account section (do not show for user), but with this solution we would still need to hide addresses...

**Comment by patrick-mcdougle** [comment]
@michalmarcinkowski Why not just allow a guest order (but no account access)? Treat subsequent guest orders the same way you treat the first.

**Comment by michalmarcinkowski** [comment]
@patrick-mcdougle allowing for guest orders for registered accounts will allow me to place order on email address of different person that will show up in his orders history...

How about a mix of these ideas:

1. Do not save addresses for guest customers (when we register there will be no addresses saved)
2. If email is not verified do not display orders history (on "orders history" page display information that you need to confirm your email address to view orders history)

**Comment by gabiudrescu** [comment]
The behavior I would expect is: 
 - allow me to guest checkout whenever I want to; if I want to use previously saved email, tough luck - I need to login / register
 - when registering with an email address that has been used for guest checkouts, do not automatically log me in if the account is not confirmed (eg. customer isConfirmed = false)
 - send me an email to confirm my account
 - only after I press "confirm" in that email I should be able to login, view my account, my addresses and so on

When trying to login with an account that has not yet been confirmed, I should receive a flash notification that I should confirm my email first.

----

Pretty much this is the behavior we have implemented at bestvalue.eu, just that we don't allow (yet) guest checkout :grin: 

----

@michalmarcinkowski regarding 1b - I am never-ever comfortable with the idea of auto-generated passwords sent through email. 

ok, one-time-only passwords maybe, but I'd rather go for a flow that does not imply any sensitive information sent via email.

**Comment by michalmarcinkowski** [comment]
@gabiudrescu how about the idea I mentioned [above](https://github.com/Sylius/Sylius/issues/6883#issuecomment-263207481)?

1. Allow to guest checkout as many times as you want until you register your account
2. Not being able to login before confirming email is questionable, not everyone wants that. It will probably be shipped as an extension ([feature request here])(https://github.com/Sylius/Sylius/issues/3444))
3. Confirming email works now
4. Same as 2., so my proposed idea is to hide orders history for not verified accounts

@gabiudrescu wdyt?

**Comment by crevillo** [comment]
sorry, 1b means we will be sending plain passwords by email?

**Comment by psihius** [comment]
I would go with @gabiudrescu - this is exactly the processes I worked out with a client for an upcoming project. This makes a lot of sense, gives ability to give user all the bonuses when he finally becomes a full fledged user, and we can do some marketing targeting users that are not yet officially registered.

But no password sending - if user wants to confirm his account - send an email and a password creating/restoration link. I think this is pretty much standard these days. Don't send passwords in emails.
Also, when you restore a password, and if the form has also an e-mail field, a password manager will pick it up and save it. That is very very very convenient.

**Comment by michalmarcinkowski** [comment]
These were just loose ideas. We're not going to do 1a or 1b. Regarding 2. I already expressed my opinion (ok, but not as default Core behaviour).

Do you see any drawbacks of hiding order history for not verified accounts ([mentioned here](https://github.com/Sylius/Sylius/issues/6883#issuecomment-263218768))? We're going to implement this today, so if anyone see any issue with that please let us know.

**Comment by psihius** [comment]
@michalmarcinkowski well, if you force user to register, then you should send confirmation e-mail right away and don't either allow to login, or after login ask for user to confirm his e-mail to continue further.
If you just hide orders, it opens a can of works with access to other data in the stores, that are heavily modified and extended. This also will need to be accounted for by every plugin. So, just hiding information is not a good idea.

**Comment by michalmarcinkowski** [comment]
@psihius you're probably right, but on the other hand introducing such limitation to Core just to protect future extensions developers from potential bugs is not a good idea.

E.g. If someone will allow for placing orders only for registered users and there will be registration page before starting the checkout, as a customer I would expect to fill in my data, submit form and continue to the checkout instead of being forced to first go to my email inbox, confirm my account and then go back to the site and only then proceed with checkout. I'm not an eCommerce expert but that I assume this will probably affect the conversion.

I understand your point of view, but I don't think restricting access to orders history for users with not confirmed email will cause any troubles. It's not hard to prevent from viewing these data and there are many worse issues that can be introduced by badly written extensions.

Any other drawbacks?

**Comment by psihius** [comment]
@michalmarcinkowski regarding the order - no, don't make the user to confirm account to finish the order, let him go through. What I meant is when user actually tries to log in, then don't allow to go further until he confirms his e-mail. I'm in favour making silently a user, just make it unconfirmed and don't restrict using the same e-mail in the future for new orders. Just silently add new orders to the same user when e-mails match. When user decides to make an account - he will get all his history. But don't allow to go through login without  a confirmation to protect any data that is saved there. That way you just restrict access globally and don't have to care if orders are hidden or not. There is also address data that needs hiding, and whatever other data will get stored in the future.
And just make a setting: allow anonymous orders or not for those, who want to restrict to registered users only.

**Comment by michalmarcinkowski** [comment]
I was talking about the example when you don't allow guest orders. Anyway the behaviour can vary between shops, so we can't assume anything in Core. We would go with the solution I described since it doesn't introduce any limitation and allows for both strategies.

If you want to restrict access to only confirmed accounts you can still easily customize that, later there can be an extension that introduces this behaviour.

**Comment by psihius** [comment]
Ah, okay. So just to confirm, you are going to make it so Core creates a user and assigns that order to that user? Then we can choose what we want to do with that when customizing the shop?

**Comment by gabiudrescu** [comment]
@michalmarcinkowski I think @psihius covered pretty much everything I have though about.

another scenario I have in mind regarding how one might benefit from hijacking an account like this is being able to erase any trace of the initial email address.

for example:
 - John places an order using test@test.com (order no. 1)
 - Bill registers an account using test@test.com
 - Bill changes test@test.com to evil@evil.com
 - order no. 1 that was initially placed by John is now assigned to Bill with a confirmed email address evil@evil.com

then, hiding the orders is no longer a blocker for evil Bill, but more a minor setback. 

it becomes very cumbersome for customer care representative to trace all this kind of account changes - especially if you don't have very verbose logs.

I think that Core implementation should assume the worst and allow with little modification more loose implementation - if someone really wants something like that.

----

My vote is on option no. 2 - do not allow login of a customer unless that customer has confirmed his email; allow him to place orders, because you don't want to hurt your business.

If someone is well aware of the risks, then it should disable some config / rewrite a class and allow customers to login even if they haven't confirmed their account - yet.

**Comment by patrick-mcdougle** [comment]
@gabiudrescu @crevillo 
>I am never-ever comfortable with the idea of auto-generated passwords sent through email.

I want to be clear, me neither. I meant sending a similar email to the one you send when users click forgot password.

As for the John/Bill example, that shouldn't be possible because an email change would require a login, which requires verification first. And in that case everything breaks down because Bill would need access to John's email.

I'm +1 for everything outlined by @psihius

**Comment by michalmarcinkowski** [comment]
Implemented 2. "Confirm account before being able to login". Thanks guys for the input! 👍
