### ISSUE TITLE
Missing changelog v1.0.0-alpha.2

### ISSUE THREAD

**Issue by piwi91** [Sylius/Sylius#6891]
I want to update the project to the next alpha version but the changelog is missing. Possible to update this?

**Comment by psihius** [comment]
Would be good to know what changed under the hood, yes.
Had to sit down and compare data reading in templates between bundle originals and my override templates.

**Comment by pjedrzejewski** [comment]
Apologies for that, alpha.2 was a quick release to add extra step in migration to beta and I forgot to generate the changelog. I suggest upgrading to beta directly, it is less effort than 2 steps (now, back then it was not.

**Comment by szilagyikinga** [comment]
I am currently trying to update a sylius v1.0.0-alpha.1 project. Is the changelog to v1.0.0-alpha.2 available since?
