### ISSUE TITLE
sylius.order.allow_guest_order doesn't seem to be used.

### ISSUE THREAD

**Issue by crevillo** [Sylius/Sylius#6897]
Hello. While looking at the config_test.yml provided i can see this line
https://github.com/Sylius/Sylius/blob/master/app/config/config_test.yml#L11

But is this param used anywhere in the code? Please let me know and i'all add pull request to avoid confussion or close this if the oaram is used somehwere. 

Thank you.

**Comment by michalmarcinkowski** [comment]
This parameter is not used any more and should be removed. Together with `sylius.order.pending.duration` and `sylius.inventory.holding.duration`.

**Comment by crevillo** [comment]
cool. i'll add a pr.
