### ISSUE TITLE
checkoutCompletedAt not filled anymore ?

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#6903]
After the last few PR's, I have a feeling that **Order**'s `checkoutCompletedAt` is not filled after an order has indeed completed checkout.

I have checked for usage of `completeCheckout()` and it's actually not used (except in specs & Behat). Is this field supposed to be removed in a very near future or is it not normal ?

Thanks !

**Comment by michalmarcinkowski** [comment]
It works well, it's been moved to state machine callback [here](https://github.com/michalmarcinkowski/Sylius/blob/57f544cc067eedb68d058b5992e25d60dd79cd34/src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_order_checkout.yml#L36).

**Comment by tchapi** [comment]
Oh, alright. I must add priorities to callbacks then, so the order is _checkout-completed_ before my callbacks fire. Thanks for the tip !
