### ISSUE TITLE
Sylius Install does not require php-mysql extension

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#6989]
Preconditions: 
 - you just bought a brand new laptop that ships with Ubuntu vanilla
 - you ran `sudo apt-get install php` without thinking about other dependencies
 - php mysql extension is not available

Steps to reproduce:
 - run `git clone git@github.com:Sylius/Sylius.git syliusMaster`
 - run `composer install` in syliusMaster folder
 - run bin/console sylius:install

What happens:
 - observe a nasty exception complaining about missing PDO MySQL extension. see below:

```
php bin/console sylius:install
Installing Sylius...
 
Step 1 of 4. Checking system requirements.
Success! Your system can run Sylius properly.
 
Step 2 of 4. Setting up the database.
Creating Sylius database for environment dev.
 
                                                         
  [Doctrine\DBAL\Exception\DriverException]              
  An exception occured in driver: could not find driver  
                                                         
 
                                       
  [Doctrine\DBAL\Driver\PDOException]  
  could not find driver                
                                       
 
                         
  [PDOException]        
  could not find driver  
                         
 
sylius:install:database [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

What should happen:
 - composer install should require mysql PHP extension
 - or gracefully handle this in sylius:install

----
bug discovered by @mihaichitic

**Comment by Niiko** [comment]
:+1: to handle this gracefully, i'm using Postgresql and don't need mysql extension.

I think i'm not the only one in this situation.

**Comment by pjedrzejewski** [comment]
Thanks for reporting, we did not make it required because you can use other drivers, but we should definitely make it more clear during the installation, without adding it to the composer.json.

**Comment by gabiudrescu** [comment]
It's my bias regarding mysql, apologize for that. Any SQL though should be required in sylius:install
