### ISSUE TITLE
Problem generate new bundle

### ISSUE THREAD

**Issue by romain0801** [Sylius/Sylius#6990]
Hello

i try to create a new bundle but i got this error : 

 [Symfony\Component\Config\Exception\FileLoaderLoadException]
  Cannot load resource "@FrontBundle/Controller/". Make sure the "FrontBundle" bundle is correctly registered and loaded in the application kernel class. If the bundle is registered, make sure the bundle path "@FrontBundle/Controller/" is not empty.

anyone can help me ? I think problem is in appkernel.php but i dont know how to solve this and solutions i found dont work.

thanks for help

**Comment by tchapi** [comment]
Have you registered the bundle in your `AppKernel.php` ? If you're not familiar with Symfony 3, you should first try some tutorial on how to create a bundle (see http://symfony.com/doc/3.1/index.html for the full doc)

**Comment by LaKrue** [comment]
If you are using the sylius-standart edition and put your FrontBundle into the /src directory, you have to change the autoload config in composer.json.

Change
`   "autoload": {
        "psr-4": {
            "AppBundle\\": "src/AppBundle/"
        },
...`
to
`    "autoload": {
        "psr-4": {
            "": "src/"
        },
...`
and you will have the same autoload behaviour like with symfony-standart.

You might have to run `composer dumpautoload` after that.

**Comment by romain0801** [comment]
@LaKrue thanks for your answer.

I did what you said but i always got this error when i try "php app/console cache:clear"

` [Symfony\Component\Config\Exception\FileLoaderLoadException]
  Cannot load resource "@FrontBundle/Controller/". Make sure the "FrontBundle" bundle is correctly registered and loaded in the application kernel class. If the bundle is registered, mak
  e sure the bundle path "@FrontBundle/Controller/" is not empty.
`

There is my "registerBundles" function from AppKernel.php (i tried without \ on new \Front too) : 
public function registerBundles()
    {
        $bundles = [
            new \Sylius\Bundle\AdminBundle\SyliusAdminBundle(),
            new \Sylius\Bundle\ApiBundle\SyliusApiBundle(),
            new \Sylius\Bundle\ShopBundle\SyliusShopBundle(),
            new Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle(),
            new \FOS\OAuthServerBundle\FOSOAuthServerBundle(),
            new Vich\UploaderBundle\VichUploaderBundle(),
            new \FrontBundle\FrontBundle(), 
        ];

        return array_merge(parent::registerBundles(), $bundles);
    }

My config.yml  contains this : 
- { resource: "@FrontBundle/Resources/config/services.yml" }

And my routing.yml : 
front:
    resource: "@FrontBundle/Controller/"
    prefix:   /

i dont know why it cant load my bundle resource.

**Comment by pjedrzejewski** [comment]
Are you using annotations for controllers? This is not supported out of the box, you should look at http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/index.html probably although I am not entirely sure, we do not use annotations.

**Comment by romain0801** [comment]
@pjedrzejewski Thanks you a lot, it works with sensioextrabundle add !
