### ISSUE TITLE
Flysystem for cloud storage

### ISSUE THREAD

**Issue by guestisp** [Sylius/Sylius#6995]
Please abstract all "uploadable assests" like product images and so on with Flysystem, allowing users to use an external Cloud Storage.

This allows an horizontal scaling

**Comment by gabiudrescu** [comment]
or Gaufrette, if that matters - that's what we have implemented with success - both for product images and other entities with media (like promotions).

**Comment by guestisp** [comment]
Flysystem or Gaufrette doesn't matter.
Is Gaufrette supported out of the box ?

**Comment by gabiudrescu** [comment]
not from my knowledge. but we were able to integrate it quite easily in our shop.

**Comment by pjedrzejewski** [comment]
We already use Gaufrette for uploads, see https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/Uploader/ImageUploader.php#L27. It configured to local system by default, but you can change that. That being said, we probably need to work a bit more on the image url resolution logic (add abstraction) so that it can be customized a bit easier. (That being said, it is really straightforward in templates already)

**Comment by guestisp** [comment]
Great. Having this feature fully supported could be a booster for Sylius adoption. AFAIK no other ecommerce platform support storage abstraction making the horizontal scaling a mess.

**Comment by gruberro** [comment]
We've a working solution in our project build on top on Gaufrette's uploader and LiipImagine's image handler storing product images in MongoDBs GridFS. If it's useful for you and the project I could contribute some documentation of how to configure an alternative image handling. If so, what would be a desirable docs location for it?

**Comment by guestisp** [comment]
This require the use of mongodb and doesn't solve the scaling issue as you have to also scale mongodb

What I'm talking about is to use an external object storage like Amazon s3 or Google cloud storage.
In this case you don't need to scale anything as both are managed by Amazon or Google

**Comment by gruberro** [comment]
You're right. But the way it's configured for MongoDB GridFS will be quite the same as if you're going to use an external service 😄 . It'd be a reference documentation only...

**Comment by pjedrzejewski** [comment]
@gruberro Definitely good idea for the docs! That would be part of the Coobook I think: "How to store images in MongoDB GridFS?" would be a good title. Appreciate your help!

**Comment by michalmarcinkowski** [comment]
@guestisp have a look at http://stackoverflow.com/questions/40689042/configure-s3-gaufrette-sylius
