### ISSUE TITLE
How to translate strings in javascript files?

### ISSUE THREAD

**Issue by alexdrupal** [Sylius/Sylius#7001]
Hello

I have a custom form in sylius admin with js script attached. How to translate strings in my js using Sylius translation rules. I can't seem to find this in documentation.

Thanks!

**Comment by pjedrzejewski** [comment]
Hi Alex!

There is https://github.com/willdurand/BazingaJsTranslationBundle, but I have never used it. What we do now is use ``data-`` attributes to store some messages, but we do it only in couple of places so I did not give it too much thought. We still need to define the best practice. If you give this bundle a try, please let us know how it worked! Thanks!
