### ISSUE TITLE
"Create" transition is never triggered in sylius_payment state_machine

### ISSUE THREAD

**Issue by gorkalaucirica** [Sylius/Sylius#7003]
I want to listen to payment creations using [sylius_payment state machine](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/PaymentBundle/Resources/config/app/state_machine.yml) but "create" transition is never triggered. 

Currently the state machine also has a "cart" state that a payment never has, [payments are created with "new" state by default](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Payment/Model/Payment.php#L48) and no transition new -> cart is available.

What is the expected behavior here?

**Comment by gorkalaucirica** [comment]
I found that create is called in [sylius_order state maching on order create](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_order.yml#L45).

The issue now is that in case a payment is cancelled and a user retries the payment, no "create" is triggered

**Comment by pjedrzejewski** [comment]
Default payment state should be "cart", then the transition shall be executed. Thanks for reporting!

**Comment by pjedrzejewski** [comment]
Thanks for reporting Gorka, let us know if it is fixed now. :)
