### ISSUE TITLE
[Bug][Admin][Product] Unique code validation error for simple product 

### ISSUE THREAD

**Issue by tuka217** [Sylius/Sylius#7005]
When we create new simple product there is also create one variant for this product. Unfortunately they have the same variant and there is an constraint which says that code of product must be unique among products and variants defined in Sylius. 
We don't get information about this error during creating a product, but only when we make different mistake during editing simple product. 
![screen shot 2016-12-05 at 11 59 40](https://cloud.githubusercontent.com/assets/8963048/20882676/586dfbcc-bae2-11e6-9c98-b53b993f0447.png)

**Comment by jbator** [comment]
Any tips how to fix this in beta?

**Comment by lchrusciel** [comment]
We have [scenarios](https://github.com/Sylius/Sylius/blob/master/features/product/managing_products/product_validation.feature#L20-L41) for that and they are green. I also tried it on sylius demo and it works as expected. Can be closed. /cc @pjedrzejewski

**Comment by jbator** [comment]
This error is still visible on demo - try to add simple product, save it, then edit again and leave any required field blank. You will see 2 errors - for code unique and field which was left blank.

**Comment by lchrusciel** [comment]
@jbator didn't check this configuration 👍

**Comment by lchrusciel** [comment]
@jbator PR with fix is ready! :)

**Comment by jbator** [comment]
@lchrusciel Thanks :)
