### ISSUE TITLE
Beta tags not distributed to bundles

### ISSUE THREAD

**Issue by rvanlaak** [Sylius/Sylius#7009]
Once again, congrats on `beta.1` 🎉 

The tags are not distributed to the bundles yet, so I can't start testing with the [`PromotionBundle`](https://github.com/Sylius/SyliusPromotionBundle/releases).

**Comment by pjedrzejewski** [comment]
Working on it as we speak. :)

**Comment by pjedrzejewski** [comment]
Done! :)
