### ISSUE TITLE
Can't create session

### ISSUE THREAD

**Issue by zhiephie** [Sylius/Sylius#7016]
I following installation in [here](http://docs.sylius.org/en/latest/book/installation/installation.html)

Work normaly, but I can't login admin/customer, not flash message or if success not redirect to dashboard admin. 

What's wrong?

**Comment by pjedrzejewski** [comment]
@zhiephie Could you tell us more about your environment? Did you try clearing the app cache?

**Comment by zhiephie** [comment]
This video more Information [here](https://youtu.be/JBsuyDgWI9A), Yeah, I've deleted the cache

**Comment by zhiephie** [comment]
Sorry missing answer, my environment is development.
