### ISSUE TITLE
 Allow customer to manage cart

### ISSUE THREAD

**Issue by videni** [Sylius/Sylius#7027]
We need to  allow customer to manage their own cart, Lets assume there are 3 products in cart. we need to fulfill these use cases.

1.  A customer checks out 2 products in cart , the left one  should be in cart.

2.  A customer checks out 2 products in cart, but doesn't confirm,  then he goes back to cart again, it should be 3 products there.

3.  A customer checks out 3 products in cart and confirmed, the cart should be empty

4. The cart total is only calculated by products, it shouldn't be adjusted by shipping method, promotions, etc,  because we will show these info in checkout  flow.

**Comment by gabiudrescu** [comment]
@videni could you be more explicit about your request? I'm not sure what you aim to get with this issue. a RFC? an opinion? an advice?

**Comment by videni** [comment]
@gabiudrescu , What I mean is making  the cart  editable, almost every e-commence site in China , such as taobao.com, JD.com,   customer can edit their cart, he can choose  2 of 3 products in cart  to pay like I described in question.
