### ISSUE TITLE
Optional account creation at checkout - unable to find how to do it

### ISSUE THREAD

**Issue by psihius** [Sylius/Sylius#7030]
Hello!

I'm trying to enable the optional registration in the checkout process (I know it was there before the Alpha releases), but as I'm pretty new to Sylius, I can't find how to do it. It seems that the option to enable this was ripped out with all the guts, including the templates.

Can you please put me in the right direction?

**Comment by psihius** [comment]
@pjedrzejewski right now the account is created automatically, based on the e-mail. Is there a way to force the sending of the e-mail confirmation e-mail (and password resetting)?

**Comment by michalmarcinkowski** [comment]
@psihius the customer is saved in the database, but the user account is not created automatically. If you want to have an optional registration in the checkout process you can create a controller action that will display registration form or if user is logged in, redirect to the addressing step and change the url of the "checkout" button on cart summary page to the url of newly created action.

**Comment by pjedrzejewski** [comment]
If you want to automatically register account for customer, I'd suggest a state machine callback for ``complete`` transition of ``sylius_order_checkout`` graph, that creates an account for the customer (new ShopUser, add it to the customer of order) and sends the "reset" password link. This way guest customers will always get an account and link to setup the password.

**Comment by psihius** [comment]
@pjedrzejewski well, I actually need an optional registration, so I need to add a checkbox field to the address form and based of it's state either create an account, or business as usual. I think I know how to modify the state machine callback - there is a doc section for that, so that question probably is solved. I would appreciate a suggestion on how to override or modify the address form to add the field I need. I know the template and form type for the address, but it does not include the e-mail field and I can't find in code where it is added to the output and processed, so I can override the relevant files.

Thanks in advance.

Btw, this could be a good case for the docs.
