### ISSUE TITLE
Failed to set cookie on Behat tests

### ISSUE THREAD

**Issue by paullla** [Sylius/Sylius#7032]
When I run Behat javascript tests using selenium2, I get an error when test "And I am logged in as an administrator" is executed:

Failed to set the 'cookie' property on 'Document': Cookies are disabled inside 'data:' URLs.

Did anyone had this problem?

**Comment by antonioperic** [comment]
cc @dantleech @pjedrzejewski ?

**Comment by pjedrzejewski** [comment]
You run it on Sylius/Sylius for contributing or a project?

**Comment by paullla** [comment]
I run it on Sylius Standard

**Comment by paullla** [comment]
I managed to find the problem, chromedriver was not running on default 8080 port, so I had to change base_url port in behat.yml to match chromedriver one.

**Comment by pjedrzejewski** [comment]
Can we close the issue then? :)

**Comment by paullla** [comment]
yes, thank you :)
