### ISSUE TITLE
Please adopt SEMVER for all releases > 1.0.0 beta

### ISSUE THREAD

**Issue by Richard87** [Sylius/Sylius#7040]
Hi!

Please adopt semantic versioning for all new releases, it will make `composer update` work as its designed to, and help manage expectations for developers!

**Comment by pjedrzejewski** [comment]
There will be at least 1 more BETA release. 1.0.0 stable will follow semver. :)

**Comment by Richard87** [comment]
Alright, you might want to specify that in your blog post, because it seems like you wouldnt care about semver at all ;)

> # BC Policy and Upgrades
> If you have been using or following Sylius since early days (~2011), you know that very often the upgrade required more effort than expected. We are innovating at many areas (Symfony, Doctrine ORM, BDD with Behat, phpspec) and this required various experiments and evolutionary process. That being said, we are setting a much better BC Policy since this BETA Release:
> 
> Breaking changes will be only done when necessary (critical bugs, security issues, major DX issues, performance)
> All breaking changes will be properly documented in the UPGRADE file, with clear instructions
> Database structure shall not be altered in any major way. That being said, if it is needed, a migration preserving data shall be included
> We are still experimenting with reusing Behat scenarios in projects, therefore the code related to them is not considered stable at least until the next release
> REST API still requires some polishing and there will be breaking changes
> We really appreciate our early-adopters, there have been great projects built on top of Sylius and we are looking forward to see more. Hopefully this BC policy will ease the migration to further releases.

**Comment by pjedrzejewski** [comment]
Good point, I will update the blog post to clarify that this BC policy is only for the BETA period. :)
