### ISSUE TITLE
Session data file is not created by your uid

### ISSUE THREAD

**Issue by dulumao** [Sylius/Sylius#7047]
i installed project.
with 
```
git clone https://github.com/Sylius/Sylius/
composer update
bin/console sylius:install
npm install && gulp
bin/console server:run 0.0.0.0:8000 in my linode server
```

and open http://xxx.xxx.xxx.xxx:8000/app_dev.php, Sylius show errors

Warning: SessionHandler::read(): Session data file is not created by your uid
500 Internal Server Error - ContextErrorException

**Comment by pjedrzejewski** [comment]
You should follow the guide from http://sylius.org/download. Could you tell us more about your system config?

**Comment by dulumao** [comment]
@pjedrzejewski ,i try to change app.php,no errors.

PHP Version => 5.6.27

System => Linux iZj6c66hn1pkontv7grfctZ 3.10.0-327.22.2.el7.x86_64 #1 SMP Thu Jun 23 17:05:11 UTC 2016 x86_64

Configure Command =>  './configure'  '--prefix=/Servdata/server/php' '--with-config-file-path=/Servdata/server/php/etc' '--enable-inline-optimization' '--disable-debug' '--disable-rpath' '--enable-shared' '--enable-fpm' '--with-fpm-user=www' '--with-fpm-group=www' '--with-mysql=mysqlnd' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--with-gettext' '--enable-mbstring' '--with-iconv' '--with-mcrypt' '--with-mhash' '--with-openssl' '--enable-bcmath' '--enable-soap' '--with-libxml-dir' '--enable-pcntl' '--enable-shmop' '--enable-sysvmsg' '--enable-sysvsem' '--enable-sysvshm' '--enable-sockets' '--with-curl' '--with-zlib' '--enable-zip' '--with-bz2' '--with-readline' '--enable-exif' '--enable-intl' '--enable-opcache=no' '--with-gd'

centos 7.2
