### ISSUE TITLE
How to able readdress one order?

### ISSUE THREAD

**Issue by bnd170** [Sylius/Sylius#7052]
Hi guys!

I need some help about the checkout process.

I read about the state machine in docs but i don't understand why, by default you disable the option about one customer can't modify the shipment address or shipment method or payment method... how I can config Sylius to able that?

Thanks guys!

**Comment by pjedrzejewski** [comment]
It is possible, try it on the online demo. You can go back to any step and modify the address, payment/shipping method. Unless I misunderstood your question?

**Comment by bnd170** [comment]
Oh thats true, in demo works perfectly.

Then i think the error must be on my version on sylius, when i try to save the address shipment data when i already added one, i get this error:

> Transition "address" cannot be applied on state "addressed" of object "Dinamic\Bundle\SyliusRibBundle\Entity\Order" with graph "sylius_order_checkout"

**Comment by michalmarcinkowski** [comment]
Adding "addressed" to `from:` under `address` transition in the checkout state machine should resolve this issue. Closing since it's not an issue on Sylius anymore.
