### ISSUE TITLE
package.json and gulpfile.js are missing from v1.0.0 BETA1 install

### ISSUE THREAD

**Issue by EricGrivilers** [Sylius/Sylius#7059]
when running `composer create-project -s beta sylius/sylius-standard projectname`

**Comment by pjedrzejewski** [comment]
Are you sure? https://github.com/Sylius/Sylius-Standard/blob/v1.0.0-beta.1/package.json

**Comment by EricGrivilers** [comment]
just tried twice: no package.jon nor gulpfile.js
Running on OS X
 

Eric Grivilers l Caravane média

**Comment by EricGrivilers** [comment]
And differents files in the bin directory (i.e. no console)

`MacBook-Pro-de-Eric:eshop ericgrivilers$ cd bin/
MacBook-Pro-de-Eric:bin ericgrivilers$ ls -la
total 120
drwxr-xr-x+ 17 ericgrivilers  staff  578 10 déc 10:52 .
drwxr-xr-x+ 20 ericgrivilers  staff  680 10 déc 11:12 ..
lrwxr-xr-x   1 ericgrivilers  staff   31 10 déc 10:50 behat -> ../vendor/behat/behat/bin/behat
lrwxr-xr-x   1 ericgrivilers  staff   35 10 déc 10:50 doctrine -> ../vendor/doctrine/orm/bin/doctrine
lrwxr-xr-x   1 ericgrivilers  staff   41 10 déc 10:47 doctrine-dbal -> ../vendor/doctrine/dbal/bin/doctrine-dbal
lrwxr-xr-x   1 ericgrivilers  staff   53 10 déc 10:47 doctrine-migrations -> ../vendor/doctrine/migrations/bin/doctrine-migrations
lrwxr-xr-x   1 ericgrivilers  staff   39 10 déc 10:50 doctrine.php -> ../vendor/doctrine/orm/bin/doctrine.php
lrwxr-xr-x   1 ericgrivilers  staff   57 10 déc 10:49 jackalope -> ../vendor/jackalope/jackalope-doctrine-dbal/bin/jackalope
lrwxr-xr-x   1 ericgrivilers  staff   51 10 déc 10:47 parse -> ../vendor/jeremykendall/php-domain-parser/bin/parse
lrwxr-xr-x   1 ericgrivilers  staff   40 10 déc 10:47 php-parse -> ../vendor/nikic/php-parser/bin/php-parse
lrwxr-xr-x   1 ericgrivilers  staff   37 10 déc 10:48 phpcr -> ../vendor/phpcr/phpcr-utils/bin/phpcr
lrwxr-xr-x   1 ericgrivilers  staff   41 10 déc 10:49 phpcrodm -> ../vendor/doctrine/phpcr-odm/bin/phpcrodm
lrwxr-xr-x   1 ericgrivilers  staff   45 10 déc 10:49 phpcrodm.php -> ../vendor/doctrine/phpcr-odm/bin/phpcrodm.php
lrwxr-xr-x   1 ericgrivilers  staff   37 10 déc 10:52 phpspec -> ../vendor/phpspec/phpspec/bin/phpspec
lrwxr-xr-x   1 ericgrivilers  staff   33 10 déc 10:52 phpunit -> ../vendor/phpunit/phpunit/phpunit
lrwxr-xr-x   1 ericgrivilers  staff   54 10 déc 10:48 security-checker -> ../vendor/sensiolabs/security-checker/security-checker
lrwxr-xr-x   1 ericgrivilers  staff   56 10 déc 10:47 update-psl -> ../vendor/jeremykendall/php-domain-parser/bin/update-psl`

**Comment by EricGrivilers** [comment]
Even composer.json is different (probably an old one)


{
    "name":        "sylius/sylius-standard",
    "description": "Starting point for projects powered by Sylius eCommerce.",
    "keywords":    ["symfony", "symfony2", "sylius", "distribution", "ecommerce", "cart", "shopping"],
    "type":        "project",
    "license":     "MIT",
    "homepage":    "http://sylius.org",
    "authors": [
        {
            "name":     "Paweł Jędrzejewski",
            "homepage": "http://pjedrzejewski.com"
        },
        {
            "name":     "Sylius project",
            "homepage": "http://sylius.org"
        },
        {
            "name":     "Community contributions",
            "homepage": "http://github.com/Sylius/Sylius/contributors"
        }
    ],
    "require": {
        "php": ">=5.5.9",

        "sylius/sylius": "^0.18@dev",
        "sensio/generator-bundle": "^2.3",
        "sensio/distribution-bundle": "^3.0"
    },

**Comment by EricGrivilers** [comment]
OK seems it was a matter of PHP version.
Just upgraded from 5.5 to 5.6, re-run `composer create-project -s beta sylius/sylius-standard project ` and everything is fine.
Sorry.
