### ISSUE TITLE
Locale Switcher not working?

### ISSUE THREAD

**Issue by davidangel** [Sylius/Sylius#7069]
I have a store set up with three different locales set to 'Enabled'. However, the default theme isn't rendering the locale switcher. Also, when I try to hit the `/switch-locale/{existing_locale_code}` route, it gives me the following error: `The locale code "{existing_locale_code}" is invalid.`

**Comment by davidangel** [comment]
Of course I figure this out right after opening the issue... :-|

Answer: Locales must be associated to each individual `channel` in the channel settings.

**Comment by pjedrzejewski** [comment]
Hi David! Thanks for closing the issue, that helps a lot! That being said, I think we could clearly mention this in the docs, what do you think @TheMadeleine? http://docs.sylius.org/en/latest/book/architecture/locales.html seems to be appropriate place.
