### ISSUE TITLE
[SyliusUserBundle] Promoting / Demoting only work on "shop" users

### ISSUE THREAD

**Issue by bpolaszek** [Sylius/Sylius#7094]
After fixing #7093 on my side, I wanted to promote a `ROLE_API_ACCESS` to my user account, in order to use the API.

Then the console told me there was no account registered with the email address I entered.

This is because the promote / demote actions only rely on `sylius.repository.shop_user`, although my account is an admin account.

I suggest asking the human to specify which type of account it should retrieve before applying any modification.

**Comment by venyii** [comment]
Related to #5800
