### ISSUE TITLE
[UX] Time not showing in order summary page

### ISSUE THREAD

**Issue by gorkalaucirica** [Sylius/Sylius#7100]
A tiny UX improvement proposal.

Instead of showing only the date, it can help to the admin to see also the time when the checkout has been completed. 

<img width="368" alt="captura de pantalla 2016-12-15 a las 11 01 29" src="https://cloud.githubusercontent.com/assets/1749891/21219847/b327d174-c2b6-11e6-99f3-1a7c055bdd81.png">

Dec 15, 2016 11:30 instead Dec 15, 2016

Can send a PR, WDYT?

**Comment by pjedrzejewski** [comment]
Absolutely! 👍  Thank you Gorka!
