### ISSUE TITLE
ChannelPricing model is final an cannot be extended

### ISSUE THREAD

**Issue by gorkalaucirica** [Sylius/Sylius#7103]
According to [model customization guide](http://docs.sylius.org/en/latest/customization/model.html) extending a model is allowed in Sylius but it's not true for ChannelPricing.

Is there any reason for this class to be different from others?

**Comment by pamil** [comment]
I guess @Zales0123 just forgot to remove that keyword from default class template 🌮

**Comment by pjedrzejewski** [comment]
Fixed, thanks for reporting Gorka!
