### ISSUE TITLE
theme problem. T_T

### ISSUE THREAD

**Issue by dulumao** [Sylius/Sylius#7120]
i created theme into app/themes/

like:
      
![image](https://cloud.githubusercontent.com/assets/2610297/21289122/b25aac92-c4cf-11e6-9af8-3b9e40e6c491.png)

admin channel enabled theme,but frond end not change.

**Comment by sudomabider** [comment]
Try changing `ShopBundle` to `SyliusShopBundle`. That should do the trick.

**Comment by dulumao** [comment]
@sudomabider wow, it's working! tks
