### ISSUE TITLE
Error when using coupon with a per customer usage limit as a anonymous customer

### ISSUE THREAD

**Issue by gorkalaucirica** [Sylius/Sylius#7126]
This bug seems quite critical, and the error is quite strange, we spent a long time to figure it out what was going on.

**Steps to reproduce**
- As an admin create a promotion
- Add a coupon with a "Per customer usage limit" to 1 (any number can be used)
- As a anonymous customer try to apply the coupon
- Go to the addressing page, fill the form and click continue
- Error 500 shows up saying that "Binding entities to query parameters only allowed for entities that have an identifier"

**Some research**
What seems to happen is that `PromotionCouponPerCustomerUsageLimitEligibilityChecker` uses `countByCustomerAndCoupon()` from `OrderRepository` passing an not persisted customer, an therefore it does not have an ID showing the error mentioned above.

**Comment by pamil** [comment]
Thanks! This issue duplicates #7122 will be fixed by #7123.

**Comment by gorkalaucirica** [comment]
Sorry, I posted without searching, my fault

**Comment by pjedrzejewski** [comment]
Thanks for the research @gorkalaucirica, I just merged #7113, which should fix this issue.
