### ISSUE TITLE
[Shop] How to display both net and gross prices on product page?

### ISSUE THREAD

**Issue by jbator** [Sylius/Sylius#7128]
I need to display both net and gross prices on product page. Is there any way to do this on shop product page? 
Currently price can be net or gross depends on tax configuration.

**Comment by czende** [comment]
Any update on this?

**Comment by lchrusciel** [comment]
@jbator @czende you can calculate the price based on taxation adjustment.

**Comment by czende** [comment]
Please can you provide some simple example? I'm little bit lost in taxation concept for two weeks. I understand that Sylius use taxes in cart/totals/order, but I have to have prices in relation with product to print both prices with and without taxes in details, _box, grids etc. 

What I'm trying to do:
1. Print product price and original price with AND without tax.
1. IF product has tax category, THAN use it
1. IF product hasn't tax category, THAN print price based on default channel tax

Please how to achieve it for example in the _box.html.twig template?
```
{% if not product.variants.empty() %}
{{ money.calculatePrice(product|sylius_resolve_variant) }}
{% endif %}
```

**Comment by lchrusciel** [comment]
Sorry, I didn't get the question correctly. I have thought about order items instead. 

And your problem will not be simple, so I cannot provide you just a code sample.

What you need to do is to create a new twig helper which will allow you to access `DelegatingCalculator`. This class requires two arguments, `base` which is taxation base value and a tax rate. The base can be gather based on variant and channel(`variant|sylius_calculate_price({'channel': sylius.channel})`). The problem will be with the tax rate. You need to provide custom resolving logic based on a product tax category and default tax zone from a channel. Based on this information you can choose proper tax rate and calculate product price with taxes. It is also pretty nice idea for a plugin.

Of course, the price can be determined only if at least one variant exist and taxation only if tax category has been chosen. Just remember, that the channel doesn't have a default tax category.

Hope, that it will help you.
