### ISSUE TITLE
[Core][DX] Make private properties and methods in StateResolvers protected

### ISSUE THREAD

**Issue by crevillo** [Sylius/Sylius#7137]
Hello,
The provided StateResolvers like https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/StateResolver/OrderPaymentStateResolver.php have only private and public properties and methods. 

This make more difficult to extend them as you almost need to duplicate all code in the classes. And  extending this is probably needed if you add more states in place. 

I suggest to change those private to protected. ¿Thoughts?

**Comment by pjedrzejewski** [comment]
The class is quite small and if you customize the logic here, I think it is reasonable to simply implement your own state resolver. This way the logic is visible and not hidden in some protected methods, etc. Let's see what others say.

**Comment by lchrusciel** [comment]
We can also make this class final. It would be an easier :)

**Comment by crevillo** [comment]
well, as @pjedrzejewski is easy to add my own and override service to use my class instead. Ok to the final proposal then too :)

**Comment by gorkalaucirica** [comment]
I copy from the Slack channel:

It seems is that `OrderPaymentStateResolver` also implicitly does a lot of logic to resolve the target transition that cannot be reused / replaced at all,  better than making those methods protected I would inject a colaborator that implements an interface. That way you can reuse the target transition resolver in other places or you can override the resolution with your  custom implementation

**Comment by gorkalaucirica** [comment]
@pjedrzejewski @lchrusciel WDYT if apart from making the class final we inject a `PaymentTargetTransitionResolverInterface` to the class and we remove the protected methods, easier to test, easier to mantain, easier to reuse

**Comment by lchrusciel** [comment]
@gorkalaucirica IMHO we should make state resolvers private anyway. But extracting this logic is also a good idea :)

**Comment by gorkalaucirica** [comment]
@lchrusciel Yes, I aggree in making them final
