### ISSUE TITLE
Invoice generation

### ISSUE THREAD

**Issue by rcsofttech85** [Sylius/Sylius#7163]
invoice not generating after placing an order or item shipped.

**Comment by psihius** [comment]
It's say give us a template structure that we can override and ability to override the invoice sending code to do additional stuff on invoice generation and sending - in my case we will convert the invoice to PDF with khtml2pdf and attach it to the e-mail we send to user when he completed his checkout.

**Comment by gabiudrescu** [comment]
I highly recommend you use a dedicated accounting software for invoices. I don't think Sylius is meant for that.

if by invoice you mean order paper slip, then you can create a twig template - as you suggested above - and use khtml2pdf for it.

**Comment by davidromani** [comment]
@psihius totally agree, I think that an eCommerce must implement a minimum feature related with invoice generation (order paper slip)

**Comment by stefandoorn** [comment]
I agree with @gabiudrescu. I think this is something that should be handled differently, but if needed for a project it makes perfect sense to me to have it as a separate plugin which can be activated/deactivated on wish. Including it in the core seems overkill to me, as often an online platform will solely serve as buying gateway and handling/administration will be done in a dedicated system. 

Keeping it as a separate plugin (maybe even supported by Sylius core team) adds less to core than strictly necessary imo.

**Comment by stefandoorn** [comment]
@davidromani The PluginSkeleton might be a good start: https://github.com/Sylius/PluginSkeleton. I'm currently working on something similar in my current project, but it's not finished yet and not that ready for OS out of the box directly - so it might need a bit of time to get going. But might be able to port is to a plugin and then contributors can step in e.g.

**Comment by davidromani** [comment]
@stefandoorn great, for now I can wait. Please, tell me something if you decide to publish this plugin and I will try to help you.

**Comment by Roshyo** [comment]
@stefandoorn @davidromani Hi guys, I also need this feature in a project, so we developped a simple plugin for Sylius. I know this is not what most might expect from an InvoicePlugin, but since we are also waiting for an official release, it might help a bit. Have a look at https://github.com/BeHappyCommunication/sylius-invoice/tree/v0.0.1

And feel free to ask for more features for it.
