### ISSUE TITLE
SyliusSettingsBundle has no 1.0.0 beta release

### ISSUE THREAD

**Issue by jrobeson** [Sylius/Sylius#7169]
You can see it here: https://github.com/Sylius/SyliusSettingsBundle/releases

**Comment by jrobeson** [comment]
ah, I wouldn't be able to install it with 3.x anyways, because it still has dependencies on symfony 2.8 components.

**Comment by jrobeson** [comment]
so what should one do with the `OptionsResolverInterface` usage? `OptionsResolver` no longer provides said interface.

**Comment by jrobeson** [comment]
and now I see that it got removed from Sylius/Sylius also last month!   It's still marked as a subtree split bundle, so no issues can be submitted to it.   I saw mention that somebody else might maintain it, but I'm not sure who.  @steffenbrem do you still wanna maintain it? I didn't see a fork in your list of repos.

**Comment by jrobeson** [comment]
Also in that case, the docs should be moved to the bundle as well.

**Comment by steffenbrem** [comment]
@jrobeson I am willing to maintain the bundle but it is not yet clear if it will go under the official `Sylius` organisation or not. See https://github.com/Sylius/Sylius/pull/6673#issuecomment-260929536.
