### ISSUE TITLE
Can not create new bundle by command in Sylius beta

### ISSUE THREAD

**Issue by ducbin** [Sylius/Sylius#7175]
I install the version Sylius beta

I want to create new bundle in Sylius, I tried:
**php bin/console generate:bundle**

But it displays an error msg: **Command "generate:bundle" is not defined**
Although sensio/generator-bundle is in file composer.json

Anyone can tell me the reason ?  Thank you

**Comment by praswicaksono** [comment]
you should install `generator-bundle`

`composer require --dev sensio/generator-bundle`

and register them in `AppKernel`

**Comment by ducbin** [comment]
Thank you for your help
