### ISSUE TITLE
Automatically generated slug: issue with pasted value

### ISSUE THREAD

**Issue by krisElphenor** [Sylius/Sylius#7188]
When editing a product, if you **paste** a value in the name field, the generated slug begins with a slash (/), which isn't recognize for the route to the product.

For instance, if you paste hello world, you'll get '/hello-world' automatically as the slug, but when you go to the page /taxons/hello-world, you got no result.

But, if you **type** hello world in the name field, the slug will be 'hello-world' (without the slash), which works perfectly when you go to the taxons listing page - /taxons/hello-world.

**Comment by davidangel** [comment]
@krisElphenor – I'm unable to reproduce this problem. Is it still an issue? If so, can tell me what OS/Browser versions you've experienced this on?

**Comment by pamil** [comment]
Couldn't reproduce it as well.
