### ISSUE TITLE
Miscalculated discount with product with cost 0€

### ISSUE THREAD

**Issue by bnd170** [Sylius/Sylius#7191]
Hi guys,

I'm testing Discount Coupons with products as souvenirs (One paid and two products with 0€ as cost) and the discount is miscalculating.

The coupon is configured for percentage to all order.

Here is an example about an Order i did for test it.

![captura de pantalla 2017-01-04 a las 16 09 52](https://cloud.githubusercontent.com/assets/5690663/21647255/cab8682e-d299-11e6-87a4-ddb5f4ff0adf.png)

**Comment by michalmarcinkowski** [comment]
The promotion is distributed on items based their contribution to total, the discount should be calculated properly in this case. Looks like you've made some customizations (we don't allow for 0$ price), have you tried to reproduce it on clean install of Sylius with e.g. 0.01$ as price?

**Comment by bnd170** [comment]
I can't try it for now, but i'll do on this week.

Btw, i didn't made any customizations in the promotion discount calculation.

I'll be back with the test that you prupose and i'll paste here the result, thank you for your time.
