### ISSUE TITLE
Error on creating new currencies

### ISSUE THREAD

**Issue by krisElphenor** [Sylius/Sylius#7192]
When trying to add a new currency (through the admin panel), there is an error on submit as the value field is expected (see screenshot below), but not set.

![image](https://cloud.githubusercontent.com/assets/18109539/21649530/59bbcb12-d2a2-11e6-9c5f-aa5335457b38.png)

Maybe this field could be mapped as nullable or with a default value ?!

**Comment by pjedrzejewski** [comment]
@krisElphenor This does not look like Sylius database structure. You are using a customized version perhaps, we do not have these fields on the default entity.

**Comment by krisElphenor** [comment]
@pjedrzejewski You're right, I'm really sorry. We have a custom model for currencies and I just realised this field belongs to that model. Sorry again.

**Comment by pjedrzejewski** [comment]
@krisElphenor No worries! Your issue actually gave me couple ideas for future improvements, so I should thank you! :)
