### ISSUE TITLE
CustomerChoiceType uses non existing field

### ISSUE THREAD

**Issue by GrandLTU** [Sylius/Sylius#7194]
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CustomerBundle/Form/Type/CustomerChoiceType.php#L59
Form type uses code as value but customer does not have code.

**Comment by lchrusciel** [comment]
It seems to not be used or tested at all.

**Comment by GrandLTU** [comment]
It is used in for Api

**Comment by lchrusciel** [comment]
@GrandLTU I will look for that, thanks

**Comment by lchrusciel** [comment]
@GrandLTU You are right. I had to have narrowed scope when I have looked for it. I will cover it with test and fix than.

**Comment by pjedrzejewski** [comment]
@lchrusciel It should use e-mail instead of code and should be fine, I guess.

**Comment by lchrusciel** [comment]
@pjedrzejewski @GrandLTU it required a few more fixes, but it should work now.
