### ISSUE TITLE
Bad request when trying to add a product to the cart

### ISSUE THREAD

**Issue by crevillo** [Sylius/Sylius#7208]
In some circustances, adding a product to the cart makes the chrome console scream telling there is a bad request. 

Steps to reproduce: 
 - Do fresh install of beta1
 - Go to the admin and edit the first variant for `T-Shirt "praesentium"` product (product_id = 52)
 - Set current stock 0 and mark that variant as `tracked`
 - Now try to add this product to the cart in the frontend and that bad request message is appearing. 
![t-shirt-praesentium](https://cloud.githubusercontent.com/assets/306215/21740669/e637940c-d4c0-11e6-9479-6a2868a5b36e.png)

**Comment by gorkalaucirica** [comment]
I guess it's expected behavior. 

You don't have stock for that variant, and when you try to add it to cart the API returns 400 status code.

Chrome shows error messages for ajax calls returning 4xx and 5xx but does not mean that your app is not working properly.

**Comment by crevillo** [comment]
ok then :). if this is the expected behaviour we can close this. 
thanks.
