### ISSUE TITLE
You can delete a payment option used for orders

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#7211]
Initially reported in #7167:

a shipment method cannot be deleted if it is used in an order, but a payment order can be. then, an order remains without any method for the payment:

![image](https://cloud.githubusercontent.com/assets/5156054/21751400/2bea251e-d5cf-11e6-9047-f7fa0d04c507.png)

vs

![image](https://cloud.githubusercontent.com/assets/5156054/21751403/3136e7e6-d5cf-11e6-81e2-42244da4e757.png)

**Comment by David-Guillot** [comment]
Hi @gabiudrescu ,

Actually [the ORM config](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/PaymentBundle/Resources/config/doctrine/model/Payment.orm.xml#L23) explicitly tells the DBMS to set the `method` field to NULL in the `Payment` entity after deleting a `PaymentMethod`. I don't know if it was intended, but:
* If it was, maybe the intention was to allow deleting a PaymentMethod only if all Orders using it are in a final state ; in this case fixing this will require a bit of work
* If it wasn't, fixing this will be very easy (removing the `on-delete="SET NULL"` config and adding the Behat test to ensure the behavior will not be accidentally changed ; I'm actually working on that already)

**Comment by gabiudrescu** [comment]
@David-Guillot I see no reason for a user to be able to delete a used payment method. even if it is for orders with a final state.

it becomes a mess from the accounting point of view to reconcile payments if you don't know the payment method.

**Comment by pjedrzejewski** [comment]
This is a bug, behavior should be the same as with shipping methods. :)
