### ISSUE TITLE
[RFC] Skipping the shipping checkout step (virtual products)

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#7215]
Hey folks!

While handling virtual/downloadable products is definitely out of scope for the core of Sylius (at least in v1), I think we could make our life (and life of the awesome guys that will implement virtual products bundle for Sylius) a bit easier, by introducing a very basic foundation for such feature.

I have did some research on other eCommerce platforms and most have a simple checkbox on the product, which indicates whether it is a virtual product or not.

As we can see, there is some interest in that already:

* https://github.com/Sylius/Sylius/issues/7180
* https://github.com/Sylius/Sylius/issues/7017
* https://github.com/Sylius/Sylius/issues/2150
* https://github.com/Sylius/Sylius/issues/1272

We have already figured out how to skip the payment step if payment is not required: #7031. Doing so for the shipping step would be very similar:

* We add ``protected $requiresShipping = true`` to the ProductVariant (so that we can have physical and audio book on a single product)
* We create a shipment only for products that require shipping
* We skip the shipping selection step if there are no shipments (just like for payment)
* We display an indication on the order summary that product is "virtual" or does not require shipping

That's it. BETA2, which is coming very soon will be an absolute feature freeze, so this is the last chance to squeeze this in and I believe it would be a huge improvement for the future, achieved at low cost. Otherwise people will need to make their ways around skipping the shipping step, for whatever reason.

Concerns:

* Our "default" address in the checkout address screen is "shipping", looks like we would need to make a switch, because the billing address is always required and needs to be filled, shipping can be the same or non existent. This change would make sense regardless of the changes described above.

Let me hear your thoughts about this! :)

**Comment by FatalError404** [comment]
Hello pjedrzejewski,

did you check the state machine configuration : http://docs.sylius.org/en/latest/customization/state_machine.html ?

Carefull about some process, in shipping step, there are some adjustments, (shipping method is updated according to selected country/province, played thanks to sylius ajax request; AND shipping method is part of the final object which defines the final price).

I guess shipping is part of the model, and currently, it seems to be difficult to disable it (not impossible ;)).

Regards,

JMO.

**Comment by starspire** [comment]
Hello pjedrzejewski,
I'd also dealt with it. In my case I created "Shipment via internet" method and after successful payment in event listener updated shipment status. Because I used API (I used 0.18,where the API was really poor, so I writen some own methods) I didn't have to fill the step with shipment address. 
Not setting any shipment method has one disadvantage, which is a case, when we don't want to give customers some downloadables goods immediately. For example in my situation I sold events, which take place on particular dates,  and sending people tickets x days before (the tickets was highly personalized and they had much information, which had to be actual). But in general I think that most of cases aren't so specific and your proposition should deal with them fine :)

**Comment by pjedrzejewski** [comment]
@starspire Thank you for your input! I agree, I was thinking about keeping the shipment and introducing concept of "shipping handlers" of something like that, which would handle exactly that, apply transition to proper state after the checkout if necessary and handle API calls if needed too. Although I want to keep things simple as possible and what I described above can be easily introduced as a plugin.

**Comment by okwinza** [comment]
Beside skipping shipping step there are also cases when you need to skip the addressing step aswell, i.e. when customer chooses to pickup items at your store or if the product is virtual.

Since all other steps are skippable, why not make addressing skippable too?

Should we squeeze this feature in aswell @pjedrzejewski ?

**Comment by pjedrzejewski** [comment]
@okwinza But you still need the billing address, no?

**Comment by okwinza** [comment]
The billing address is required when you're dealing with AVS(address
verification system) which is the case for US and some other countries
AFAIK.

For example, in Russian ecommerce address is not required to authorize the
payment. So there is no such term as billing address.

Also, it is only useful when customer pays online with card. When customer
chooses to pay with cash(or with any other method) and decides to pick up
stuff at your location there is no need neither for billing address nor
shipping address.

Anyway, i think it is worth discussing so I will open an RFC and share my
experience on the matter.

**Comment by brunocombodo** [comment]
@pjedrzejewski : I agree with you when you say this : 
> @starspire Thank you for your input! I agree, I was thinking about keeping the shipment and introducing concept of "shipping handlers" of something like that, which would handle exactly that, apply transition to proper state after the checkout if necessary and handle API calls if needed too. Although I want to keep things simple as possible and what I described above can be easily introduced as a plugin.

I have a complex need for this (several different dematerialised services), and I know I have a tendency to produce over complicated things, but I think it would be great, on the product page, to choose the "shipping handler" in a list (or reversely if you don't want to do this, the product would have to provide extra informations so that the unique "shipping handler" will choose what rule to apply between manys)

**Comment by blacknoir** [comment]
@pjedrzejewski For me the `requiresShipping ` is rather a product flag, not product variant. I can be wrong, but what real-life business case can be for having some of product variants shippable, while others are not? The TV is one kind of product, while game or music album is completely another one and they are reflected as a Product entity itself, not variant (as being just same product by nature but with some minor difference in characteristics of real product).

**Comment by michalmarcinkowski** [comment]
@blacknoir for me a real-life example will be a book. You can have a single book available in different variants e.g. hardcover, softcover, pdf. Therefore you would like to skip shipping for PDF (virtual product), but leave it for hardcover and softcover. Don't you agree on that one?

**Comment by c-revillo** [comment]
what @michalmarcinkowski says is indeed popular specially in site for editorials. we developed one site (not with sylius) that was selling physical and epub and/or pdf versions of those books. 
and yes, for those cases we had to add a shipping cost for the physical ones and due how laws are here in Spain, also different taxes per variant.

**Comment by gabiudrescu** [comment]
@michalmarcinkowski and @c-revillo  we had that also at elefant.ro, but we solved it in another manner: two different products (not variants, but full parent products) tied together by an table similar to Product Associations. you can see it here:
 - http://www.elefant.ro/carti/fictiune/literatura-de-divertisment/chick-lit-romance/inainte-sa-te-cunosc-338142.html
 - http://www.elefant.ro/ebooks/fictiune/literatura-de-divertisment/chick-lit-romance/inainte-sa-te-cunosc-339161.html

basically, although sold under the same title, the products were entirely different:
 - different VAT
 - different shipping method (one was sent through courier, another via email)
 - different payment restrictions (if you had both in your cart, you were restricted to pay only by credit card - to make sure you get the book before the shipping package arrives at your house)

I don't know if this makes your decision easier, but I hope it gives you an insight from a real life business case.

----

I also think @starspire idea to use a shipping method called "shipping via internet" fits the model and although it requires customization, it keeps the core clean and without boolean flags, which if I personally find as toxic as softdelete and ELSE.

**Comment by Zales0123** [comment]
@gabiudrescu I don't like having too much boolean flags on model as well. However, in this case it's the simplest and most accurate way to provide built-in *virtual products* functionality. Things like **separate shipping method** or **different product variants** are for sure much more manageable, but we could not provide such a functionality as default in Sylius 😕  In this case a boolean flag is lesser evil, you could easily don't worry about it (by template/model customization), as it would be `true` as default, and it's just a good point where you can hook some logic. I just think it would be the most pragmatic way to handle this ;)

**Comment by tisjames** [comment]
Hello, I was just wondering if this feature will be part of Beta 2? 

Some nice ideas in the discussion on alternate ways of approaching shipping for virtual products!

**Comment by bruno-ds** [comment]
Hello, I'm trying to use this on my sylius installation, but I can't.
Here are my steps : 

1. The channel has 
  - skipping_shipping_step_allowed : 1
  -  skipping_payment_step_allowed : 1
2. The variant has `$variant->setShippingRequired(false);`
3. on the checkout step, the `/checkout/address` appear.

What did I miss?

**Comment by bruno-ds** [comment]
Hello, I'm trying to use this (great) feature, 
Here are my feedbacks : 
- if the shipping is skipped, the address step still ask for the shipping address, it should only ask for the billing address. (it could be simpler for you to invert the two steps)
- if either the shipping and the payement steps are going to be skipped, no address at all should be asked (this is subject to discussion, but in our shop, we decided to go that way)


PS : thanks @Zales0123 \o/

**Comment by psihius** [comment]
@bruno-ds you missed the point of that feature - it is hiding the steps only if there is a single shipping and/or payment method available. This is not a "skip shipping step because I don't need it".

**Comment by bruno-ds** [comment]
@psihius when I read the doc related to this issue : https://github.com/Sylius/Sylius/pull/7495 that is not was is explained : 
> What if in the order you have only products that do not require shipping (they are downloadable for example)? [source](https://github.com/Sylius/Sylius/pull/7495/commits/ea337dd7bf62f82b0563817ef89d7bc1bd582d6d)

plus wee had a training with @Zales0123 and agreed that this feature was right in our use case, so I'm pretty sure of myself.

But I agree that in the admin interface, in the channel admin form, that is not what is told to the admin user.
