### ISSUE TITLE
 Changing the “Max Per Page” Option of Paginator not working on SyliusShopBundle

### ISSUE THREAD

**Issue by thailandjerry** [Sylius/Sylius#7229]
I am a newbee for sylius. 
According to official Docs, I changed taxons list number by setting paginate.

sylius_shop_product_index:
    path: /taxons/{slug}
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            **paginate: 30**
            template: "@SyliusShop/Product/index.html.twig"
            grid: sylius_shop_product
    requirements:
        slug: .+

But products always display default number 10, So I don't understand.
Thus is my debug info on front-end.

ResourceGridView {#2720 ▼
  -metadata: Metadata {#1800 ▶}
  -requestConfiguration: RequestConfiguration {#2717 ▼
    -request: Request {#9 ▶}
    -metadata: Metadata {#1800 ▶}
    -parameters: Parameters {#2718 ▼
      #parameters: array:10 [▼
        **"paginate" => 30**
        "limit" => null
        "allowed_paginate" => array:3 [▶]
        "default_page_size" => 10
        "sortable" => false
        "sorting" => null
        "filterable" => false
        "criteria" => null
        "template" => "@SyliusShop/Product/index.html.twig"
        "grid" => "sylius_shop_product"
      ]
    }
  }
  -data: Pagerfanta {#2759 ▼
    -adapter: DoctrineORMAdapter {#2760 ▶}
    -allowOutOfRangePages: false
    -normalizeOutOfRangePages: true
    **-maxPerPage: 10**
    -currentPage: 1
    -nbResults: 11
    -currentPageResults: null
  }
  -definition: Grid {#2663 ▶}
  -parameters: Parameters {#2719 ▶}
}

Who can help me explain this , thanks very much.

**Comment by yosriMekni** [comment]
i have the same problem too

**Comment by thailandjerry** [comment]
I pulled latest code from github, find the problem is resolved already. Thanks Sylius team.

Jerry
