### ISSUE TITLE
Can't add a product to cart after removing shipping step and creating an other channel

### ISSUE THREAD

**Issue by yosriMekni** [Sylius/Sylius#7231]
after removing the shipping step ,i've created an other channel with no shipping methods ,  with code 'tn_store' and i've added a product to it , and when i try to add the product to the cart and exception appears in the ajax call :
the url : web/app_dev.php/ajax/cart/add?productId=62
the exeption : Notice: Undefined index: tn_store / 500 Internal Server Error - ContextErrorException
stack trace : 
![capture](https://cloud.githubusercontent.com/assets/13231156/21843163/43bcc9cc-d7ea-11e6-8c57-49e32169c415.PNG)

**Comment by pjedrzejewski** [comment]
This is a bug in the calculator. It does not check if the configuration for this channel exists in the serialized array. Simple to fix, but question is ... what should be the behavior here? When price of shipping is not defined. We have validation for that in the UI, so I assume you added this shipping method programmatically?

**Comment by yosriMekni** [comment]
Nope , i've never added a shipping method for the new channel coded 'tn_store'

**Comment by yosriMekni** [comment]
can i skip this problem adding a shipping  method to the channel with price zero temporarily , until it fixed ?

**Comment by yosriMekni** [comment]
i've tryied it, no chance 😞

**Comment by yosriMekni** [comment]
@pjedrzejewski can you explain more , please ? and if its simple to fix ,why can be fixed ?
