### ISSUE TITLE
[Payment] Stripe custom form

### ISSUE THREAD

**Issue by bocasaysetra** [Sylius/Sylius#7240]
I use Stripe custom form ([Creating a Custom Payment Form with Stripe.js](https://stripe.com/docs/custom-form)) :
the payment works well in Stripe and the state of the sylius_payment is completed, but the payment_state of sylius_order remains in awaiting_payment (I want to have the order object in the view but I don't know how to get it)

**Comment by lchrusciel** [comment]
It seems, that you didn't make a state machine transition on payment. Did you just update a state? 

Anyway, it is more a stackoverflow question. And without any snippet it will be hard to detect what went wrong.

**Comment by bocasaysetra** [comment]
Thank you for replying, yes I already posted on stackoverflow

I followed the configuration of the official [documentation](http://docs.sylius.org/en/latest/cookbook/stripe.html) with the default Sylius [state machine](https://github.com/Sylius/Sylius/tree/master/src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine) configuration. I just modified the stripe checkout in stripe custom form

**Comment by GSadee** [comment]
Hi @bocasaysetra, I was trying to recreate this issue, but without success. Please, reopen an issue if you still have problem with it.
