### ISSUE TITLE
[Admin][Product] Integrity constraint violation while adding a new product

### ISSUE THREAD

**Issue by tuka217** [Sylius/Sylius#7245]
1. In system there is a product  name:Vodka, code:vodka, slug:vodka
2. When we create a new product name:Vodka, code:122_vodka, slug:vodka then we get constraint violation

![screen shot 2017-01-12 at 11 19 49](https://cloud.githubusercontent.com/assets/8963048/21885693/108ab42c-d8b9-11e6-9f52-f63243a35e71.png)

**Comment by pjedrzejewski** [comment]
@tuka217 Can you quickly write a Behat scenario that reproduces it? (no need to fix it right away, just to confirm the issue)
