### ISSUE TITLE
Resource Bundle bump up friendsofsymfony/rest-bundle to version 2.x

### ISSUE THREAD

**Issue by Mrkisha** [Sylius/Sylius#7260]
I can't use Resource Bundle 1.0 Beta since it uses friendsofsymfony/rest-bundle 1.8 version, but rest-bundle has requirement for symfony 3.0 (and not 3.2)

**Comment by jrobeson** [comment]
I think that was done just a few days ago.

**Comment by michalmarcinkowski** [comment]
Fixed in https://github.com/Sylius/Sylius/pull/7349
