### ISSUE TITLE
Duplicate database execute when using grid.

### ISSUE THREAD

**Issue by liverbool** [Sylius/Sylius#7262]
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/GridBundle/Doctrine/ORM/DataSource.php#L79
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Controller/ResourcesCollectionProvider.php#L60

PS. Seem no need `$paginator->getCurrentPageResults()` in grid-bundle `$paginator->setMaxPerPage()` on resource-bundle will reset cached result.

**Comment by michalmarcinkowski** [comment]
Should be fixed by https://github.com/Sylius/Sylius/pull/7319.
