### ISSUE TITLE
Sylius Install issue: "Your requirements could not be resolved to an installable set of packages"

### ISSUE THREAD

**Issue by sepehr3point** [Sylius/Sylius#7263]
Hi folks

I am getting this error message when trying to create a new Sylius project.
Would you please help me get this fixed?...
Here are the commands that I have tried so far and both comes up with same results:

composer create-project sylius/sylius-standard -s dev
composer create-project -s beta sylius/sylius-standard

result:

Installing sylius/sylius-standard (dev-master 279ba1c472373773033c59d63485dbc1e7c0575b)
  - Installing sylius/sylius-standard (dev-master master)'/c/Users/Public/Desktop/Git Bash.lnk' Cloning master from cache
Created project in C:\Users\TOSHIBAPC\sylius-standard
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for league/uri 4.2.1 -> satisfiable by league/uri[4.2.1].
    - league/uri 4.2.1 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
  Problem 2
    - Installation request for sylius/sylius 1.0.x-dev -> satisfiable by sylius/sylius[1.0.x-dev].
    - sylius/sylius 1.0.x-dev requires ext-exif * -> the requested PHP extension exif is missing from your system.
  Problem 3
    - Installation request for sylius/sylius dev-master -> satisfiable by sylius/sylius[dev-master].
    - sylius/sylius dev-master requires ext-exif * -> the requested PHP extension exif is missing from your system.
  Problem 4
    - league/uri 4.2.1 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - payum/payum 1.3.8 requires league/uri ~4.0 -> satisfiable by league/uri[4.2.1].
    - Installation request for payum/payum 1.3.8 -> satisfiable by payum/payum[1.3.8].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\Bitnami\wampstack-5.6.29-0\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by venyii** [comment]
`league/uri 4.2.1 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.`

Looks like you're missing an extension.

```
To enable extensions, verify that they are enabled in your .ini files:
- C:\Bitnami\wampstack-5.6.29-0\php\php.ini
You can also run php --ini inside terminal to see which files are used by PHP in CLI mode.
```

**Comment by michalmarcinkowski** [comment]
Solution from @venyii should help. For future support requests please use StackOverflow or Slack (read more about community support [here](http://sylius.org/blog/get-support-from-sylius-community)).
