### ISSUE TITLE
[API] [RFC] Code instead of ids for api calls

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#7266]
During my research for our api changes I have notice that Magento uses sku to show specific product. With our concept of immutable codes we can use them for almost all of our entities. For customers we could use an email as unique identifier. This will increase cohesion between different applications and probably it will make life easier. Should we go this way?

Check `catalogProductRepositoryV1` in [Magento docs](http://devdocs.magento.com/swagger/index_20.html).

**Comment by steffenbrem** [comment]
It should be noted that this would introduce a bit more database overhead but I think it is worth it. Feels a lot better + safer to use UUIDs (or whatever you use for the code) to be used externally and auto incremented ids internally. 👍

**Comment by pjedrzejewski** [comment]
Ref. #6560 #6801.

**Comment by lchrusciel** [comment]
@steffenbrem absolutely. But without making any benchmarks its hard to say anything particular about performance. Index on code should also help. But I guess we will probably go this way. Let just wait for some more feedback.
