### ISSUE TITLE
[ API ] Unit tests

### ISSUE THREAD

**Issue by jvahldick** [Sylius/Sylius#7283]
The PHPUnit test is breaking on:
1) Sylius\Tests\Controller\CustomerApiTest::it_allows_to_get_customers_list

**Comment by lchrusciel** [comment]
Master seems to be fine... It is probably something wrong with your installation. If you need any help with you app, please ask question on stackoverflow or join us at Slack.

Probably can be [closed](https://travis-ci.org/Sylius/Sylius/branches) /cc @pjedrzejewski @michalmarcinkowski

**Comment by jvahldick** [comment]
Yes, my bad.
The unit tests breaks after #6017

**Comment by lchrusciel** [comment]
I will take a look in a minute and try to help you.

**Comment by michalmarcinkowski** [comment]
Your fix discovered bad test, let's work on that in #6017.
