### ISSUE TITLE
Menu override

### ISSUE THREAD

**Issue by PyRowMan** [Sylius/Sylius#7285]
Hey guys, i'm posting a topic here because i need a bit of help : 

I'm overriding the admin menu (to add some dropdown option) into the main topics by creating a 

app/SyliusUiBundle/views/Layout/sidebar.html.twig

Here i wanted to get bas the menu's stuff.

But it seems that somehow the parameters of the menu are not going into my extended view : 

Here is the file : 

> app/SyliusUiBundle/views/Layout/sidebar.html.twig

```
{% extends 'knp_menu.html.twig' %}

{% block list %}
LOLOLOLO
{% endblock %}
```

And here is the screenshot of the error : 

![capture](https://cloud.githubusercontent.com/assets/6388129/22092705/31776742-de00-11e6-8ff6-f8b902686b61.PNG)

 #Thanks.

**Comment by pjedrzejewski** [comment]
You are using "Layout/sidebar", while you should use "Menu/sidebar". :)

**Comment by pjedrzejewski** [comment]
Please use our Slack to post such questions: https://slackinvite.me/to/sylius-devs. Please re-open if you find a bug and my solution is not working. Thanks! :)
