### ISSUE TITLE
[Feature Request][Admin] Add ability to resend registration confirmation e-mail from customer management

### ISSUE THREAD

**Issue by psihius** [Sylius/Sylius#7291]
Title says it all - I have something wrong with my SMTP settings, so e-mail didn't go though, and I didn't get an error. But now I have to either delete the user and register again, or create a new registration with a different e-mail.

But in the big picture - there are instances when an e-mail just didn't go though for some reason and the administrative personal needs ability to re-send that confirmation.

**Comment by gabiudrescu** [comment]
from what I can see, the confirmation email is sent through this service: 

```
        <service id="sylius.listener.user_mailer_listener" class="Sylius\Bundle\UserBundle\EventListener\MailerListener">
            <argument type="service" id="sylius.email_sender" />
            <tag name="kernel.event_listener" event="sylius.user.password_reset.request.pin" method="sendResetPasswordPinEmail" />
            <tag name="kernel.event_listener" event="sylius.user.password_reset.request.token" method="sendResetPasswordTokenEmail" />
            <tag name="kernel.event_listener" event="sylius.user.email_verification.token" method="sendVerificationTokenEmail" />
        </service>
```

this code is being called:

```
    /**
     * @param GenericEvent $event
     */
    public function sendVerificationTokenEmail(GenericEvent $event)
    {
        $this->sendEmail($event->getSubject(), Emails::EMAIL_VERIFICATION_TOKEN);
    }
```

So, if you generate a new `sylius.user.email_verification.token` event, you'll receive the email again. then you'll have to create a button, a route, a controller and modify a template - and you're done :grin: 

right?

**Comment by psihius** [comment]
Probably, this is meant more as a feature that should be there in the base installation - this is a common thing that just makes sense :)

**Comment by pjedrzejewski** [comment]
Yeah, I agree it makes sense to have it in the core. Had this on my list as well, just added it to our JIRA. I have noted that reason why it is not implemented yet is the following: We do not know which channel to use in the e-mail. ;) We could make it a dropdown with all channels (unless there is only 1) and pass the channel code to the controller.

**Comment by psihius** [comment]
@pjedrzejewski or write down the channel user registered from in his profile data. This, actually, can be very useful for marketing people, knowing what channel user came in through.
