### ISSUE TITLE
[RFC] [Order] Order item quantity lower than 1

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#7301]
We are using a data mapper to convert quantity value into order item units. But symfony forms handles validation after mapping data to fields. In current implementation, quantity will never be lower than 1, because if value is negative, `OrderItemQuantityModifier` skips mapping. 
The good news: We will never have order item quantity lower than 0
The bad news: If somebody will try to set the quantity to value lower than 0 it will just be ignored. No flash/error message will be displayed. In API it will just result with HTTP NO_CONTENT response, which can be quite confusing... 

If you know how should it be handled I'am open for solutions. It would be nice to decide if we are staying with current behaviour or change it before beta2.

**Comment by stefandoorn** [comment]
Stumbled into the same when I was trying to add validation on extra properties for the OrderItem entity.

**Comment by stefandoorn** [comment]
Still relevant.

**Comment by psren** [comment]
...

**Comment by CoderMaggie** [comment]
It seems that the described behavior stayed with us until today, thus I'm closing the issue 😅 . Please reopen if needed.
