### ISSUE TITLE
[RFC] Non Toggleable Locales

### ISSUE THREAD

**Issue by NeverResponse** [Sylius/Sylius#7309]
It seems there's a problem with the `Locale`s resolving that no one saw coming,
and now it bites our butts.

Issue:
=====
If you set a disabled locale as default in a channel, you'll break the whole shop.
Doesn't matter which locale is the customer using atm.

Possible solutions:
==============
Another resolver
-----------------
Which sole purpose of existence will be to fallback to the locale configured in config.yml

Pros:
- The site won't blow up

Cons:
 - You might not know the users are seeing everything in chinese

Restricting Locales used by channels
-------------------------------------
Blocking toggleability of default locales, and removing disabled locales from channel's edit select

Pros:
 - Site will stay up (probably)

Cons:
- Complexity goes up (esp. in forms, which we all love wholeheartedly);
- It will probably lead to way more bugs than it'll resolve;
- Crappy UX

Removing Locales' toggleability altogether
-------------------------------------------
Deleting the `enabled` field and all logic using it.

Pros:
- No bugs with disabling (obviously)
- Somewhat simplifies things

Cons:
- Another thing goes in the gutter (it would be a BC break, and will probably annoy some people heavily depending on it)

Personally I'm for the last one (hence the title), as it provides simplicity, and doesn't really have a downside since You'll still be able to "disable" a locale, by simply not adding it to the channel.

Either way those are my thoughts on the matter, and if anyone want to interject, provide more ups/downs or suggest another possible solution, please do so.

Cheers

**Comment by okwinza** [comment]
+1 for last one.
