### ISSUE TITLE
[Cart] All items is cleared when logging in with facebook

### ISSUE THREAD

**Issue by oatto** [Sylius/Sylius#7336]
_Step to produce:_

1. Guest add products to cart.
2. Guest logins with Facebook.
3. All Items in the cart has gone.

**Comment by michalmarcinkowski** [comment]
The eternal question: a bug or a missing feature? 😄 

It's a known behavior. After login the cart is resolved by user and the cart from session is abandoned. To provide a better UX we would need to implement a mechanism to attach cart from session to a currently logged in user under the condition there is no cart already attached.

**Comment by nbjohan** [comment]
I think this is also the case with the regular login. 
1. Add product to cart.
2. Go to checkout
3. Login during checkout
4. Cart is empty

We probably will need to fix this in our current project.

**Comment by lchrusciel** [comment]
You can just adjust this logic inside `CartBlamerListener`

**Comment by Zales0123** [comment]
Cart flow has been documented recently (https://github.com/Sylius/Sylius/pull/10167) and we already know we need a cookbook for the cart flow customization (https://github.com/Sylius/Sylius/issues/10181). Can be closed then, I suppose 🖖
