### ISSUE TITLE
When adding mainTaxon to product, an error appears

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#7343]
Via the admin, when I add a mainTaxon to a product (I select it in the list), it fails 'This value is not valid' :

![screen shot 2017-01-25 at 14 04 07](https://cloud.githubusercontent.com/assets/1944007/22291533/2c575004-e307-11e6-97d6-415b4cd62363.png)

I'm on PHP 7.0, latest master.
Any ideas ?

**Comment by smashou** [comment]
I just tried it, with the last master, PHP 7.0 and it's working. Do you have more data to test ?

**Comment by tchapi** [comment]
I'll test it again asap and keep this issue up to date

**Comment by tchapi** [comment]
Still an error on my side and on a coworker side, in various virgin browsers, on the latest master. I don't know how it can work on your side.

The problem is only on the `mainTaxon` field, not on the `productTaxons` field. I've traced down the problem, and I think it is a bug in Sylius in `ProductTypeExtension.php` : the `choice_value` parameter on `mainTaxon` should be `id`, and not `code`, since it's the `id` that is sent in the POST request by the admin : 

```
------WebKitFormBoundaryVklrPNdPcoyS5nOG
Content-Disposition: form-data; name="sylius_product[mainTaxon]"

17
```

So the transformer expects a `code`, gets an `id`, fails, and doesn't save the taxon. Same goes for when you display the page on reload : the mainTaxon is not displayed.

Just changing `code` to `id` in this file fixes the issue for me.

What do you think ?

**Comment by tchapi** [comment]
This was introduced here I think : https://github.com/Sylius/Sylius/commit/4df87c99527968df5635ad08a1d6b2892e5a8730#diff-849c08d76f6f2e39a0eb0f5bd21b938aR48

**Comment by tchapi** [comment]
Up ?

**Comment by pjedrzejewski** [comment]
@Arminek This and #6859 are fixed, right?

**Comment by Arminek** [comment]
yes, it is fixed.
