### ISSUE TITLE
Errors when adding attributes to products

### ISSUE THREAD

**Issue by michaelzangerle** [Sylius/Sylius#7361]
I was just playing around a bit with the latest version of Sylius (1.0.0-beta.1) and I discovered two (probably minor) issues when clicking the "add attributes"-button on while editing a product.

**Case 1**
Edit a product that has one or more attributes assigned and select the attributes tab. There just click on the add attributes button and it will produce following error message:

```
[2017-01-27 13:00:47] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Warning: Invalid argument supplied for foreach()" at /.../sylius/vendor/sylius/sylius/src/Sylius/Bundle/ProductBundle/Controller/ProductAttributeController.php line 78 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Warning: Invalid argument supplied for foreach() at /.../sylius/vendor/sylius/sylius/src/Sylius/Bundle/ProductBundle/Controller/ProductAttributeController.php:78)"} []
```

**Case 2**
Edit a product that has **no** attributes assigned and select the attributes tab. There just click on the add attributes button again and it will produce following error message:

![selection_008](https://cloud.githubusercontent.com/assets/1465587/22370415/9d3d18b8-e491-11e6-87b2-24bad0d412c5.png)

Same issue occurs when removing an attribute and hitting the "add attributes"-button.

I know I kind of misused the form but it was not clear to me how to use it at first sight. Maybe the button should be disabled until the selection of attributes changes?

**Comment by devozanges** [comment]
Idem for me, when I click on the add attributes button, loader turns ...and nothing happen.

**Comment by Zales0123** [comment]
Both of this bugs should be already fix, check out [this PR](https://github.com/Sylius/Sylius/pull/7012) - now the `BadRequestHttpException` is throw if there is no new attributes passed to ajax action (and therefore no action is performed).

**Comment by michaelzangerle** [comment]
I just updated my Sylius test project again but still the same error. You can also check it out in the demo project [http://demo.sylius.org/admin](http://demo.sylius.org/admin). It looks a bit different there but still errors ...

First click on the button:
![selection_009](https://cloud.githubusercontent.com/assets/1465587/22418209/49bb82c6-e6d8-11e6-8518-564be2242cca.png)

Second click on the button:
![selection_010](https://cloud.githubusercontent.com/assets/1465587/22418206/47ec0498-e6d8-11e6-8f1f-6e60bc80f8c1.png)

**Comment by Zales0123** [comment]
@michaelzangerle can you confirm it's still an issue on `dev-master`? I've just checked it on the newest version and it works well for me. On each call it just throws `400 Bad Request`, which is a desired behaviour (as we handle this exception and stop js function).

First call:
![zrzut ekranu 2017-02-20 o 11 29 07](https://cloud.githubusercontent.com/assets/6212718/23121301/23e55d04-f760-11e6-83c1-b60d6334e6cb.png)

Second and third call:
![zrzut ekranu 2017-02-20 o 11 29 54](https://cloud.githubusercontent.com/assets/6212718/23121302/23e984c4-f760-11e6-885a-b84fc60a3d9b.png)

**Comment by michaelzangerle** [comment]
@Zales0123 Yes I still get the same error on dev-master for this request

```
GET http://sylius.lo/app_dev.php/admin/attribute-forms?count=4 500 (Internal Server Error)
```

Stack trace:

```
<h1>Whoops, looks like something went wrong.</h1>
<h2 class="block_exception clear_fix">
   <span class="exception_counter">1/1</span>
   <span class="exception_title"><abbr title="Symfony\Component\Debug\Exception\FatalThrowableError">FatalThrowableError</abbr> in <a href="http://sylius.lo/app_dev.php/_profiler/open?file=vendor/friendsofsymfony/rest-bundle/Controller/ExceptionController.php&amp;line=43#line43" title="Go to source">ExceptionController.php line 43</a>:</span>
   <span class="exception_message">Type error: Argument 1 passed to FOS\RestBundle\Controller\ExceptionController::__construct() must implement interface FOS\RestBundle\View\ViewHandlerInterface, none given, called in /home/mzangerle/sandbox/sylius/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php on line 202</span>
</h2>
<div class="block">
<ol class="traces list_exception">
<li> in <a href="http://sylius.lo/app_dev.php/_profiler/open?file=vendor/friendsofsymfony/rest-bundle/Controller/ExceptionController.php&amp;line=43#line43" title="Go to source">ExceptionController.php line 43</a></li>
<li>at <abbr title="FOS\RestBundle\Controller\ExceptionController">ExceptionController</abbr>->__construct() in <a href="http://sylius.lo/app_dev.php/_profiler/open?file=vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php&amp;line=202#line202" title="Go to source">ControllerResolver.php line 202</a></li>
<li>at <abbr title="Symfony\Component\HttpKernel\Controller\ControllerResolver">ControllerResolver</abbr>->instantiateController('FOS\\RestBundle\\Controller\\ExceptionController') in <a href="http://sylius.lo/app_dev.php/_profiler/open?file=vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerResolver.php&amp;line=85#line85" title="Go to source">ControllerResolver.php line 85</a></li>
<li>at <abbr title="Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver">ControllerResolver</abbr>->instantiateController('FOS\\RestBundle\\Controller\\ExceptionController') in <a href="http://sylius.lo/app_dev.php/_profiler/open?file=vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php&amp;line=190#line190" title="Go to source">ControllerResolver.php line 190</a></li>
...
```

I just saw that you have another symfony version in you screenshots than me so here are my composer dependencies.

```
    "require": {
        "php": "^5.6|^7.0",
        "sylius/sylius": "dev-master"
    },
    "require-dev": {
        "behat/behat": "^3.2",
        "behat/mink": "^1.7",
        "behat/mink-browserkit-driver": "^1.3",
        "behat/mink-extension": "^2.2",
        "behat/mink-selenium2-driver": "^1.3",
        "bossa/phpspec2-expect": "^1.0",
        "coduo/php-matcher": "^2.1",
        "friends-of-behat/context-service-extension": "^0.3",
        "friends-of-behat/cross-container-extension": "^0.2",
        "friends-of-behat/performance-extension": "^1.0",
        "friends-of-behat/service-container-extension": "^0.3",
        "friends-of-behat/suite-settings-extension": "^1.0",
        "friends-of-behat/symfony-extension": "^0.2.1",
        "friends-of-behat/variadic-extension": "^0.1",
        "lakion/api-test-case": "^1.0",
        "lakion/mink-debug-extension": "^1.2.3",
        "phpspec/phpspec": "^3.2",
        "phpunit/phpunit": "^5.6",
        "se/selenium-server-standalone": "^2.52",
        "sensio/generator-bundle": "^3.1",
        "stripe/stripe-php": "^4.1"
    },
```

**Comment by GSadee** [comment]
I've also just checked it on the newest master and it works well for me.

**Comment by pjedrzejewski** [comment]
Please reopen if still an issue.

**Comment by mrjingles** [comment]
For me the solution was to rebuild/reinstall assets via gulp/yarn.

**Comment by shaunroot** [comment]
I am trying to upgrade to the new beta and I am getting the same error:

FatalThrowableError in ExceptionController.php line 43:
Type error: Argument 1 passed to FOS\RestBundle\Controller\ExceptionController::__construct() must be an instance of FOS\RestBundle\View\ViewHandlerInterface, none given, called in /mnt/hgfs/www/tenderbones.com/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php on line 202

This only happens in my shop pages and not my admin pages.

This item was closed, but I don't see any resolution. I'm trying to figure out if some of my code is incompatible with the new version or if there is a bug in Sylius.

**Comment by lchrusciel** [comment]
This error is common when upgrading a FOSRest bundle. Solution is available in our UPGRADE file. Please, apply #7662
