### ISSUE TITLE
Error when updating cart from different browser windows

### ISSUE THREAD

**Issue by gonzalovilaseca** [Sylius/Sylius#7373]
It's not a common case, but we've had a few, the way to reproduce it in http://demo.sylius.org is:
1) Add any 3 items to cart (`window1`)
2) Open a new browser window and navigate to cart page (`window2`).
3) Go back to `window1`, remove 2 items from cart.
4) Goto `window2`, change any item quantity and save cart, you should get "500 Internal Server Error".

Somehow symfony form transformation gets messed up.

**Comment by michalmarcinkowski** [comment]
Fixed in #7406.
