### ISSUE TITLE
[ReportBundle] Make it works with Sylius beta version

### ISSUE THREAD

**Issue by Pitoune** [Sylius/Sylius#7379]
I have forked [SyliusReportBundle](https://github.com/Pitoune/SyliusReportBundle) to make it works with Sylius beta version.  
I did it quickly so the code is not the cleanest but it works.  
Just let me know what you plan to do with this repository and I will be glad to help.

**Comment by bendavies** [comment]
same question for the settings bundle, really.

**Comment by lchrusciel** [comment]
Probably [BundleSkeleton](https://github.com/Sylius/BundleSkeleton) and stand alone plugin will be best choice. Do you need any help with that? Probably together with @Zales0123 we would be glad to help.

Anyway, these bundles could be part of https://github.com/friendsofsylius

**Comment by Pitoune** [comment]
I have seen that report bundle and report component are already part of https://github.com/friendsofsylius  
I am totally OK to make my PR on these repositories. I am just wondering who is gonna read it as the group does not seem very active.

**Comment by Zales0123** [comment]
As @lchrusciel said, it would be wonderful to introduce _ReportBundle_ again (probably as a standalone Sylius plugin, as it definitely won't be implemented back to Core). I've seen that Fosyl organization already has Report component and bundle. Anyway, you can be 100% that wherever you're going to do some effort to make _ReportBundle_ compatible with Sylius, me and @lchrusciel would be glad to help (at least with code review, probably with some problems and brainstorming too 😉 ).

**Comment by Pitoune** [comment]
Sounds great !  
Thanks guys

**Comment by odiseoteam** [comment]
Hi guys, i want to share a SyliusReportBundle fork we made in Odiseo https://github.com/odiseoteam/SyliusReportBundle. We will do some modifications in this days. Let us know your feedback. 
Thanks.

**Comment by lchrusciel** [comment]
It is not a concern of the main repository anyway.
