### ISSUE TITLE
Shop Register Form with Recaptcha

### ISSUE THREAD

**Issue by FatalError404** [Sylius/Sylius#7380]
Hello,

I follow the documentation to override the customer form type and the customer entity in order to add a recaptcha field.

The recaptcha is based on this bundle https://github.com/excelwebzone/EWZRecaptchaBundle

If we stricly follow the documentation we get a corrupted database, notally during the step 4 here : http://docs.sylius.org/en/latest/customization/model.html

You recommend to use migration:
* this removes datas
* this modifies foreign key
* this raises doctrine exception as Integrity constraint violation
* this generates version file into vendor directory (if we update vendor wtih composer, I guess the generated file will be deleted)

I dont know if it is the best way to update database (keeping datas).

Anyway, do you know the best practice to add recaptcha field in the shop register form ?

Thanks!

**Comment by TheMadeleine** [comment]
Migrations do not remove data. They reorganize the database structure to meet the new requirements, you have designed. If you modify models, you need to write your own migration, that actually does not touch the existing data.

**Comment by FatalError404** [comment]
Hello TheMadeleine,

here is what we get executing migration:

➜  ann_mon_syl git:(develop) ✗ app/console doctrine:migrations:diff
Generated new migration class to "/data/users/jmo/ann_mon_syl/app/../vendor/sylius/sylius/app/migrations/Version20170131105225.php" from schema differences.
➜  ann_mon_syl git:(develop) ✗ app/console doctrine:migrations:migrate

                    Sylius Migrations


WARNING! You are about to execute a database migration that could result in schema changes and data lost. Are you sure you wish to continue? (y/n)y
Migrating up to 20170131105225 from 20161003133743

  ++ migrating 20170131105225

     -> ALTER TABLE sylius_address DROP FOREIGN KEY FK_B97FF0589395C3F3
     -> ALTER TABLE sylius_customer_group DROP FOREIGN KEY FK_7FCF9B059395C3F3
     -> ALTER TABLE sylius_order DROP FOREIGN KEY FK_6196A1F99395C3F3
     -> ALTER TABLE sylius_product_review DROP FOREIGN KEY FK_C7056A99F675F31B
     -> ALTER TABLE sylius_shop_user DROP FOREIGN KEY FK_7C2B74809395C3F3
     -> CREATE TABLE sylius_recaptcha (id INT AUTO_INCREMENT NOT NULL, billing_address_id INT DEFAULT NULL, shipping_address_id INT DEFAULT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, birthday DATETIME DEFAULT NULL, gender VARCHAR(1) DEFAULT 'u' NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, phone_number VARCHAR(255) DEFAULT NULL, subscribed_to_newsletter TINYINT(1) NOT NULL, recaptcha LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_29648D0BE7927C74 (email), UNIQUE INDEX UNIQ_29648D0BA0D96FBF (email_canonical), UNIQUE INDEX UNIQ_29648D0B79D0C0E4 (billing_address_id), UNIQUE INDEX UNIQ_29648D0B4D4CFF2B (shipping_address_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
     -> ALTER TABLE sylius_recaptcha ADD CONSTRAINT FK_29648D0B79D0C0E4 FOREIGN KEY (billing_address_id) REFERENCES sylius_address (id) ON DELETE SET NULL
     -> ALTER TABLE sylius_recaptcha ADD CONSTRAINT FK_29648D0B4D4CFF2B FOREIGN KEY (shipping_address_id) REFERENCES sylius_address (id) ON DELETE SET NULL
     -> DROP TABLE ezapprove_items
     -> DROP TABLE ezbasket
     -> DROP TABLE ezbinaryfile
     -> DROP TABLE ezcobj_state
     -> DROP TABLE ezcobj_state_group
     -> DROP TABLE ezcobj_state_group_language
     -> DROP TABLE ezcobj_state_language
     -> DROP TABLE ezcobj_state_link
     -> DROP TABLE ezcollab_group
     -> DROP TABLE ezcollab_item
     -> DROP TABLE ezcollab_item_group_link
     -> DROP TABLE ezcollab_item_message_link
     -> DROP TABLE ezcollab_item_participant_link
     -> DROP TABLE ezcollab_item_status
     -> DROP TABLE ezcollab_notification_rule
     -> DROP TABLE ezcollab_profile
     -> DROP TABLE ezcollab_simple_message
     -> DROP TABLE ezcomment
     -> DROP TABLE ezcomment_notification
     -> DROP TABLE ezcomment_subscriber
     -> DROP TABLE ezcomment_subscription
     -> DROP TABLE ezcontent_language
     -> DROP TABLE ezcontentbrowsebookmark
     -> DROP TABLE ezcontentbrowserecent
     -> DROP TABLE ezcontentclass
     -> DROP TABLE ezcontentclass_attribute
     -> DROP TABLE ezcontentclass_classgroup
     -> DROP TABLE ezcontentclass_name
     -> DROP TABLE ezcontentclassgroup
     -> DROP TABLE ezcontentobject
     -> DROP TABLE ezcontentobject_attribute
     -> DROP TABLE ezcontentobject_link
     -> DROP TABLE ezcontentobject_name
     -> DROP TABLE ezcontentobject_trash
     -> DROP TABLE ezcontentobject_tree
     -> DROP TABLE ezcontentobject_version
     -> DROP TABLE ezcurrencydata
     -> DROP TABLE ezdiscountrule
     -> DROP TABLE ezdiscountsubrule
     -> DROP TABLE ezdiscountsubrule_value
     -> DROP TABLE ezenumobjectvalue
     -> DROP TABLE ezenumvalue
     -> DROP TABLE ezforgot_password
     -> DROP TABLE ezgeneral_digest_user_settings
     -> DROP TABLE ezgmaplocation
     -> DROP TABLE ezimagefile
     -> DROP TABLE ezinfocollection
     -> DROP TABLE ezinfocollection_attribute
     -> DROP TABLE ezisbn_group
     -> DROP TABLE ezisbn_group_range
     -> DROP TABLE ezisbn_registrant_range
     -> DROP TABLE ezkeyword
     -> DROP TABLE ezkeyword_attribute_link
     -> DROP TABLE ezm_block
     -> DROP TABLE ezm_pool
     -> DROP TABLE ezmedia
     -> DROP TABLE ezmessage
     -> DROP TABLE ezmodule_run
     -> DROP TABLE ezmultipricedata
     -> DROP TABLE eznode_assignment
     -> DROP TABLE eznotificationcollection
     -> DROP TABLE eznotificationcollection_item
     -> DROP TABLE eznotificationevent
     -> DROP TABLE ezoperation_memento
     -> DROP TABLE ezorder
     -> DROP TABLE ezorder_item
     -> DROP TABLE ezorder_nr_incr
     -> DROP TABLE ezorder_status
     -> DROP TABLE ezorder_status_history
     -> DROP TABLE ezpackage
     -> DROP TABLE ezpaymentobject
     -> DROP TABLE ezpdf_export
     -> DROP TABLE ezpending_actions
     -> DROP TABLE ezpolicy
     -> DROP TABLE ezpolicy_limitation
     -> DROP TABLE ezpolicy_limitation_value
     -> DROP TABLE ezpreferences
     -> DROP TABLE ezprest_authcode
     -> DROP TABLE ezprest_authorized_clients
     -> DROP TABLE ezprest_clients
     -> DROP TABLE ezprest_token
     -> DROP TABLE ezproductcategory
     -> DROP TABLE ezproductcollection
     -> DROP TABLE ezproductcollection_item
     -> DROP TABLE ezproductcollection_item_opt
     -> DROP TABLE ezpublishingqueueprocesses
     -> DROP TABLE ezrole
     -> DROP TABLE ezrss_export
     -> DROP TABLE ezrss_export_item
     -> DROP TABLE ezrss_import
     -> DROP TABLE ezscheduled_script
     -> DROP TABLE ezsearch_object_word_link
     -> DROP TABLE ezsearch_return_count
     -> DROP TABLE ezsearch_search_phrase
     -> DROP TABLE ezsearch_word
     -> DROP TABLE ezsection
     -> DROP TABLE ezsession
     -> DROP TABLE ezsite_data
     -> DROP TABLE ezstarrating
     -> DROP TABLE ezstarrating_data
     -> DROP TABLE ezsubtree_notification_rule
     -> DROP TABLE eztipafriend_counter
     -> DROP TABLE eztipafriend_request
     -> DROP TABLE eztrigger
     -> DROP TABLE ezurl
     -> DROP TABLE ezurl_object_link
     -> DROP TABLE ezurlalias
     -> DROP TABLE ezurlalias_ml
     -> DROP TABLE ezurlalias_ml_incr
     -> DROP TABLE ezurlwildcard
     -> DROP TABLE ezuser
     -> DROP TABLE ezuser_accountkey
     -> DROP TABLE ezuser_discountrule
     -> DROP TABLE ezuser_role
     -> DROP TABLE ezuser_setting
     -> DROP TABLE ezuservisit
     -> DROP TABLE ezvatrule
     -> DROP TABLE ezvatrule_product_category
     -> DROP TABLE ezvattype
     -> DROP TABLE ezview_counter
     -> DROP TABLE ezwaituntildatevalue
     -> DROP TABLE ezwishlist
     -> DROP TABLE ezworkflow
     -> DROP TABLE ezworkflow_assign
     -> DROP TABLE ezworkflow_event
     -> DROP TABLE ezworkflow_group
     -> DROP TABLE ezworkflow_group_link
     -> DROP TABLE ezworkflow_process
     -> DROP TABLE sylius_customer
     -> DROP TABLE sylius_order_comment
     -> DROP TABLE sylius_product_variant_image
     -> ALTER TABLE sylius_shop_user DROP FOREIGN KEY FK_7C2B74809395C3F3
Migration 20170131105225 failed during Execution. Error An exception occurred while executing 'ALTER TABLE sylius_shop_user DROP FOREIGN KEY FK_7C2B74809395C3F3':

SQLSTATE[HY000]: General error: 1025 Error on rename of './ann_ezp_dev/sylius_shop_user' to './ann_ezp_dev/#sql2-53b-6e60' (errno: 152)


  [Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'ALTER TABLE sylius_shop_user DROP FOREIGN KEY FK_7C2B74809395C3F3':
  SQLSTATE[HY000]: General error: 1025 Error on rename of './ann_ezp_dev/sylius_shop_user' to './ann_ezp_dev/#sql2-53b-6e60' (errno: 152)

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[HY000]: General error: 1025 Error on rename of './ann_ezp_dev/sylius_shop_user' to './ann_ezp_dev/#sql2-53b-6e60' (errno: 152)


  [PDOException]
  SQLSTATE[HY000]: General error: 1025 Error on rename of './ann_ezp_dev/sylius_shop_user' to './ann_ezp_dev/#sql2-53b-6e60' (errno: 152)

I guess migration impacts not only sylius models but other too, that's why I guess it is not really recommendable.

Anyway, did you deal with the recaptcha field into shop register form ?

Thanks.

**Comment by TheMadeleine** [comment]
Okay, We see the problem. The migration you are trying to execute is your own migration you've done with `doctrine:migrations:diff`, true?

Then you need to know that `diff` compares the database with the metadata, in your project it does not have the metadata of **ez** ;) 
Therefore to migrate data successfully on production, you need to write your own, custom migration, that will not touch the ez tables. So you can either modify the generated migration not to drop these ez tables, or write your own :)

**Comment by FatalError404** [comment]
TheMadeleine,

What about this ?

 -> DROP TABLE sylius_customer
 -> DROP TABLE sylius_order_comment
 -> DROP TABLE sylius_product_variant_image

Actually, I have already users and orders, this migration impacts sylius model too, and drop customer table!

Anyway, this is not the topic here, the migration issue can be reverted (just recommend to dump database before ;)), the real topic of this issue is about recaptcha, did you deal with this use case, and if yes do you have any examples of implementation which works with this bundle https://github.com/excelwebzone/EWZRecaptchaBundle ?

Many thanks!

**Comment by FatalError404** [comment]
TheMadeleine,

About asking on Stackoverflow, this issue may have impact on sylius core, adding recaptcha property into customer model, in order to "externally" securize customer forms. I guess there are some optimizations to do here:
* select appropriate recaptcha bundle (is EWZRecaptchaBundle  ok for you ?)
* check dependancies through composer processes (define compatible versions and update packagist)
* enable/disable recaptcha field via sylius configuration
* deal with recaptcha doctrine type
* ...

Recaptcha is important for most web applications, it becomes a "standard" of the web, I guess it should have a place into your solution.

Regards,

JMO.
