### ISSUE TITLE
ResourceBundle's ResourceDeleteSubscriber seems a little over-eager

### ISSUE THREAD

**Issue by mbabker** [Sylius/Sylius#7383]
Today in one of my projects I was dealing with an error removing an old entity to add a new one and found that the Exception was getting handled by the `ResourceDeleteSubscriber`.  This entity (actually, the entire bundle this code is in) isn't a Sylius resource type so it caught me a little off guard that this event subscriber was handling the event.  Could this subscriber be updated in a way that doesn't handle errors for non-resource types?

**Comment by pjedrzejewski** [comment]
See #7351. Are you on dev-master or beta1 tag? :) It is solved on master.

**Comment by mbabker** [comment]
Should be good then.  I was on master but hadn't updated in a few days and hit that issue before updating.  Thanks!
