### ISSUE TITLE
ImageUploader is using wrong method according to ImageInterface

### ISSUE THREAD

**Issue by Pitoune** [Sylius/Sylius#7391]
According to [ImageInterface](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/Model/ImageInterface.php#L25) the method `getFile()` returns a `\SplFileInfo`.  
But [ImageUploader](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Core/Uploader/ImageUploader.php#L47) is calling method `guessExtension` which does not exist in `\SplFileInfo`.  
I guess that what ImageInterface is returning is actually a `Symfony\Component\HttpFoundation\File\File`.  
  
I see two options:
- do not change ImageInterface and use `getExtension()`instead of `guessExtension()`  
- change ImageInterface to return a `Symfony\Component\HttpFoundation\File\File`  

Let me know which option seems the best to you and I will do the PR.

**Comment by Pitoune** [comment]
any advice on this ?

**Comment by michalmarcinkowski** [comment]
@Pitoune is there any drawback of simply using `getExtension()` on `\SplFileInfo`? What is the benefit of `guessExtension()`?

**Comment by Pitoune** [comment]
According to documentation the method `guessExtension()` determines it thanks to the file MIME type.  
I had some issues by simply using `getExtension()` but I did not really figured out why.

**Comment by pjedrzejewski** [comment]
@Pitoune My first thought was to change the interface, but this couples Core with HttpFoundation from Symfony... So we would need to move the image uploader to CoreBundle, which is ok IMO, wdyt?

**Comment by Pitoune** [comment]
@pjedrzejewski it sounds good to me. I am going to work on it to make a pull request.

**Comment by pamil** [comment]
Fixed by #9776, `symfony/http-foundation` has been already a transient dependency + an instanceof assertio has been added in the meantime.
