### ISSUE TITLE
Grid option "position" unrecognized

### ISSUE THREAD

**Issue by michaelzangerle** [Sylius/Sylius#7393]
I just copy and pasted the configuration related to the position of a column in a grid from here http://docs.sylius.org/en/latest/customization/grid.html#how-to-modify-positions-of-fields-filters-and-actions-in-grid but then I get the following error:

```
InvalidConfigurationException in ArrayNode.php line 317:
Unrecognized option "position" under "sylius_grid.grids.sylius_admin_product_review.fields.date"
```

It's also not defined in the configuration tree in GridBundle/DependencyInjection/Configuration.php.

```
....
->arrayNode('fields')
    ->useAttributeAsKey('name')
    ->prototype('array')
        ->children()
            ->scalarNode('type')->isRequired()->cannotBeEmpty()->end()
            ->scalarNode('label')->cannotBeEmpty()->end()
            ->scalarNode('path')->cannotBeEmpty()->end()
            ->scalarNode('sortable')->end()
            ->scalarNode('enabled')->defaultTrue()->end()
            ->arrayNode('options')
                ->prototype('variable')->end()
            ->end()
        ->end()
    ->end()
->end()
...
```

Did I miss something?

**Comment by TheMadeleine** [comment]
Hi @michaelzangerle, what Sylius version are you on?
This feature is not available in beta-1. Update to `dev-master` :)
