### ISSUE TITLE
No mapping file found named 'Order.orm.xml'

### ISSUE THREAD

**Issue by petrkostelka** [Sylius/Sylius#7395]
Hello,
I transfer my project in Sylius from localhost (on localhost work properly) to shared hosting and now on open /web/ show this error. 

Any ideas what to do?

Thank you!

`Fatal error: Uncaught Doctrine\Common\Persistence\Mapping\MappingException: No mapping file found named 'Order.orm.xml' for class 'Sylius\Component\Core\Model\Order'. in /data/web/virtuals/153026/virtual/www/concept/sf7prowear/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:75 Stack trace: #0 /data/web/virtuals/153026/virtual/www/concept/sf7prowear/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/SymfonyFileLocator.php(237): Doctrine\Common\Persistence\Mapping\MappingException::mappingFileNotFound('Sylius\\Componen...', 'Order.orm.xml') #1 /data/web/virtuals/153026/virtual/www/concept/sf7prowear/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/Driver/FileDriver.php(115): Doctrine\Common\Persistence\Mapping\Driver\SymfonyFileLocator->findMappingFile('Sylius\\Componen...') #2 /data/web/virtuals/153026/virtual/www/concept/sf7prowear/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/Driver/XmlDriver.php(58): Doctrine\Common\Persistence\Mapping\Driver\FileDriver in /data/web/virtuals/153026/virtual/www/concept/sf7prowear/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/MappingException.php on line 75`

**Comment by pjedrzejewski** [comment]
Hey @petrkostelka! Sylius is not meant to run on a shared hosting, you should use a vps/dedicated server. Can you tell us more about your env tho, maybe it is something simple we can fix.

**Comment by muhammadhafeez** [comment]
@pjedrzejewski I'm getting the same error and didn't found any solution over the internet. Please help
