### ISSUE TITLE
(UIBundle) Missing translations

### ISSUE THREAD

**Issue by RomainSanchez** [Sylius/Sylius#7411]
Hi there, i have noticed missing `sylius.ui` translation messages here and there like `sylius.ui.set_as_default`.
I was about to make a PR with those but i noticed it is not only missing in french but in other languages as well.

So is there a file where the messages should be added for crowdin to update all languages or something or should i just add translations that i am missing in the messages.fr file?

**Comment by TheMadeleine** [comment]
I'm not sure what's the case here, but see https://crowdin.com/translate/sylius/352/en-fr#q=set_as_default the key you are missing exists. Also in french :)

Probably you are on the beta-1 varsion of Sylius, where that translation was still missing. It's already translated on `dev-master`. :)

Solution: Upgrade ⬆️  :)
