### ISSUE TITLE
Checkout-Layout duplicates normal layout instead of extending

### ISSUE THREAD

**Issue by psren** [Sylius/Sylius#7418]
Hey there,

i adjusted some meta tags and noticed that it didn't work in the checkout.
```ShopBundle\Checkout\layout.html.twig``` is not extending ```ShopBundle\layout.html.twig``` which leads to duplication.

I'd suggest to use Twigs ```extend``` and override the unnecessary ```block``` tags.
This needs some adjustments in ```ShopBundle\layout.html.twig``` e.g. the topbar and the header are not in a ```block```.

If you agree I'm happy to provide a PR.

**Comment by pjedrzejewski** [comment]
@psren 👍
