### ISSUE TITLE
[API] No oauth route

### ISSUE THREAD

**Issue by starspire** [Sylius/Sylius#7421]
Hello, there is probably a bug (or I miss something), because the ouath route dissapeared.
```
http://localhost:8000/api/oauth/v2/token
```
Response:
```
{
  "code": 404,
  "message": "No route found for \"GET /api/oauth/v2/token\""
}
```

Why has it happened? Is there a posibility to fix that quickly? Because now I cannot use API at all due to lack of authorization.

**Comment by lchrusciel** [comment]
It is working for me. And we have tests for it also. Did you import `src/Sylius/Bundle/ApiBundle/Resources/config/routing.yml`?

**Comment by starspire** [comment]
OK, I found the difference. I had got in `routing.yml` following code:
```
sylius_api:
    resource: "@SyliusApiBundle/Resources/config/routing/main.yml"
    prefix: /api
```

So I was importing `routing/main.yml` instead of `routing.yml`. But it was working on beta1 and was broken when I switched to dev-master. And there is nothing about it in `Upgrade.md `. Maybe we should add info about routing imports changes (if I'm right ofc)?

**Comment by lchrusciel** [comment]
You are right. I have missed it in `UPGRADE.md`. Let's keep it open until someone will update upgrade
