### ISSUE TITLE
Use DataTransformer in filter (v1.0.0-alpha.1)

### ISSUE THREAD

**Issue by leogout** [Sylius/Sylius#7432]
Hi, I am using a custom form type to filter products between a given price range. This form returns a string like `min-max`.
I have a `DoubleRangeToStringTransformer` which, when given `20-200`, returns a DoubleRange object with `$min = 20` and `$max = 200`.
However, this transformer isn't applied when I am in the [apply](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Grid/Filtering/FilterInterface.php#L27) method of my `PriceRangeFilter` : `$data = "20-200"`.

Am I missing something ? Perhaps it have been added in beta ?

Thanks for your time !

**Comment by pjedrzejewski** [comment]
@leogout Please ask such questions on StackOverflow (remember to show the code of the filter, otherwise we can only guess) or join our Slack: https://slackinvite.me/to/sylius-devs. ;)
