### ISSUE TITLE
Classes for KnpMenu root node should not be hardcoded.

### ISSUE THREAD

**Issue by Im0rtality** [Sylius/Sylius#745]
see: https://github.com/Sylius/SyliusWebBundle/blob/4981b73087fdc62ca7c8e043d09ad00136f464c7/Menu/FrontendMenuBuilder.php#L100

There are multiple places like this. Class parameter should be configurable so it is possible to override it. 

As of now, it is only possible to override items template, but root element remains same.

**Comment by michalmarcinkowski** [comment]
WebBundle is removed now.
