### ISSUE TITLE
OAuth tokens aren't updated on reconnection

### ISSUE THREAD

**Issue by bruno-ds** [Sylius/Sylius#7463]
Hello,

OAuth tokens aren't updated on reconnexion, 
I've debugged it and will post soon a pull request.

**Comment by Zales0123** [comment]
Can anyone confirm it's still an issue? cc @pamil @lchrusciel

**Comment by bruno-ds** [comment]
The bugged part described in this PR :
https://github.com/Sylius/Sylius/issues/7464

Is still here, so yes, this is still an issue.
I think this PR contain everything needed to understand the bug and why it is not so urgent to solve it.
(Our store "iTop Hub" rely only on SSO and have quite a lot of REST API so it was really annoying, but I think most store won't even use SSO)
