### ISSUE TITLE
createReviewerMapping: wrong array key

### ISSUE THREAD

**Issue by krisElphenor** [Sylius/Sylius#7471]
When overriding the customer entity mapping, especially the id field. The new value isn't 'seen' by the mapping of the review entity.

For example, let's say, we override the mapping of customer entity and we change 'id' to 'customer_id', we then expect the author_id of the review entity, which references the customer id, to reference the new field 'customer_id'. Unfortunately, that's not the case and author_id still point at customer.id (which doesn't exist anymore) which result in an exception.

The problem seems to be in the file [Sylius/Bundle/ReviewBundle/Doctrine/ORM/Subscriber/LoadMetadataSubscriber.php](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ReviewBundle/Doctrine/ORM/Subscriber/LoadMetadataSubscriber.php)

... in the createReviewerMapping method, in the returned array, I believe the key 'joinColum' should be 'joinColumns' and the expected value should be an array of array, so...

...instead of

```
private function createReviewerMapping($reviewerEntity, ClassMetadata $reviewerEntityMetadata)
    {
        return [
            'fieldName' => 'author',
            'targetEntity' => $reviewerEntity,
            'joinColumn' => [
                'name' => 'author_id',
                'referencedColumnName' => $reviewerEntityMetadata->fieldMappings['id']['columnName'],
                'nullable' => false,
                'onDelete' => 'CASCADE',
            ],
            'cascade' => ['persist'],
        ];
    }
```

...we should have...

```
private function createReviewerMapping($reviewerEntity, ClassMetadata $reviewerEntityMetadata)
    {
        return [
            'fieldName' => 'author',
            'targetEntity' => $reviewerEntity,
            'joinColumns' => [
                [
                    'name' => 'author_id',
                    'referencedColumnName' => $reviewerEntityMetadata->fieldMappings['id']['columnName'],
                    'nullable' => false,
                    'onDelete' => 'CASCADE',
                ]
            ],
            'cascade' => ['persist'],
        ];
    }
```

Doing so, allows the field to be properly overwritten by Doctrine

**Comment by pjedrzejewski** [comment]
@krisElphenor Could you submit a PR with the fix, please? That would be super helpful! :)

**Comment by krisElphenor** [comment]
@pjedrzejewski Yes, of course !

https://github.com/Sylius/Sylius/pull/7490
