### ISSUE TITLE
private $channels field in ShippingMethod model

### ISSUE THREAD

**Issue by pearlwithbanana** [Sylius/Sylius#7538]
I was trying to override the ShippingMethod model to add cashOnDelivery flag but for some reason the $channels field is private and while updating the database I am getting the 

> Property AppBundle\Entity\ShippingMethod::$channels does not exist

error. Am I doing something wrong while overriding the entity? 

My new ShippingMethod entity class looks quite simple:

```
namespace AppBundle\Entity;


use Sylius\Component\Core\Model\ShippingMethod as BaseShippingMethod;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 */
class ShippingMethod extends BaseShippingMethod
{
    /**
     * @ORM\Column(type="boolean")
     */
    private $cashOnDelivery = false;

 ..some getters and setters
}
```

**Comment by Zales0123** [comment]
What version of **Sylius** do you use? It was fixed in https://github.com/Sylius/Sylius/pull/7109.

**Comment by pearlwithbanana** [comment]
The v1.0.0-beta.1 one.

**Comment by michalmarcinkowski** [comment]
It's already fixed on master.
