### ISSUE TITLE
[ResourceBundle] Pagination override does not work as stated in the docs

### ISSUE THREAD

**Issue by psihius** [Sylius/Sylius#7557]
So I was battling the issue that I saw only 10 taxons in the product Taxonomy form in the admin panel and noticed that it paginates it 10 items at a time and ignores the limit=1000 in the URL.
So, I went in to try to override it, and after reading http://docs.sylius.org/en/latest/bundles/SyliusResourceBundle/index_resources.html I set
```
paginate: false
limit: 1000
```

And got a 404.
Then I just left the limit: 1000 - still got 10 items only.

Then I set paginate: 1000 - worked.

So, either the docs are wrong or there is a bug.

**Comment by CoderMaggie** [comment]
Hi! I've tested it in shop on some random index.
And both:
```
paginate: 5
```
and
```
paginate: false
limit: 5
```
work correctly.

Do you remember where were you exactly changing that one? Currently the Taxons choice in the form you've mentioned is handled by autocomplete so this might be irrelevant now, tht is why I will close it.
