### ISSUE TITLE
Payment method issue

### ISSUE THREAD

**Issue by kurakin-oleksandr** [Sylius/Sylius#7570]
I have an issue with payment method (admin page is broken). Looks like table `sylius_gateway_config` should be filled in with some data and it does not. What should be there?
It happened after merging PR https://github.com/Sylius/Sylius/pull/7237

**Comment by mbabker** [comment]
If you create a stub record with at least the `factory_name` (looks like it should match the Payum factory name, i.e. `paypal_express_checkout`) and the `gateway_name` (this can be anything I think, I didn't see any validation it has to match a pattern but the code makes it a "code" version of the method's translated name) that'll get you in and you'll just have to configure the gateway fresh through the UI.

I literally just finished this process 10 minutes ago.  It'd be nice if there were some kind of upgrade steps for this; it will bring down a shop upgrading to beta 2.

**Comment by tchapi** [comment]
It still needs to make its way into the UPGRADE file to avoid frustration ....

**Comment by Zales0123** [comment]
It for sure should be in `UPGRADE.md` file 👍  @mbabker are you willing to open a pull request about it? Or should I do it?

**Comment by mbabker** [comment]
If there's a better upgrade path than "go into the database and add these stubs then edit your existing methods to reintegrate the data" then someone else should probably write it, that was the working solution I came up with for myself yesterday 😄

**Comment by mrgrt** [comment]
@mbabker  I attempted to add a new payment method  (through the UI and directly in the database) but when I went to /admin/payment-methods I'm still getting an error. Was there anything
