### ISSUE TITLE
Semantic.min.js missing from semantic-ui-css:2.2.8

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#7571]
Today we ran into some issues with the Semantic JS minified file not loading and therefore breaking JS functionality on the basic shop. It seems that in the last release of Semantic UI CSS ('css only' split) (2.2.8) the minified file got left out, which is breaking things:

https://github.com/Semantic-Org/Semantic-UI-CSS/commit/b6e97c923ab35886b93af0b2d65f93aea3bcc57f

Either we can limit it currently at version 2.2.7, because in there the minified file seems available, or we should include the non-minified version & minify it ourselves.

**Comment by stefandoorn** [comment]
From their repository: https://github.com/Semantic-Org/Semantic-UI-CSS/issues/29

**Comment by jlukic** [comment]
I'll fix this later tonight

**Comment by stefandoorn** [comment]
Works again!
