### ISSUE TITLE
Combined buttons look strange with translations

### ISSUE THREAD

**Issue by psren** [Sylius/Sylius#7580]
Some languages have longer words for "or", for example the german "oder" looks strange in the buttons in the Admin-UI.

Possibly there are other languages with even longer words.

![bildschirmfoto 2017-02-22 um 21 13 49](https://cloud.githubusercontent.com/assets/1016798/23230411/1992009c-f944-11e6-9a72-db8c0215ed0c.png)

**Comment by psren** [comment]
Maybe we can remove the ```{{ 'sylius.ui.or'|trans }}``` completely?
IMO it does not provide any value.

Alternatively I could also place the word between the two buttons (not in a circle)
and improve the handling of foreign languages with longer translations for "or".

WDYT? I would provide a PR if you comment on that issue.

**Comment by pjedrzejewski** [comment]
@psren +1 for removing it, not much value and I'd rather not waste time on trying to make it look pretty with so many locales. :)
