### ISSUE TITLE
Unable to display the list of root taxons

### ISSUE THREAD

**Issue by rmNyro** [Sylius/Sylius#7597]
Hi everyone,

I need to display the list of taxons ([or is it taxonomies ?](http://guides.spreecommerce.org/user/configuring_taxonomies.html)) on the site's homepage we're building.

[According to the doc](http://docs.sylius.org/en/latest/cookbook/taxons-menu.html) : "The findChildrenAsTreeByRootCode method of TaxonRepository takes either a code or null. If the code is null it returns the whole tree of taxons configured in the database."

But I'm unable to send null as a code, I thought it was something like:
`{{ render(url('sylius_shop_partial_taxon_index_by_code', {'code': 'null', 'template': '@SyliusShop/Components/Taxon/_horizontalMenu.html.twig'})) }}`
In that case null is interpreted as an actual taxon (and it's not found). Also the "code" parameters is checked through the regex `[^/]++` so an empty string (or null as value, without quotes) throws an error.

So either I'm wrong or there's a bug or the doc is not up to date.

Thank you.

P.S.: I'm using Sylius 1.0.0-beta.1 fetched and install via composer a week ago following the download instructions. It's not a custom install using bundles or anything.

**Comment by rmNyro** [comment]
up

**Comment by pjedrzejewski** [comment]
I think we should have separate routing for displaying the whole category tree then. Like ``sylius_shop_partial_taxon_index`` and that's it. Would you find a moment to submit a PR?

**Comment by rmNyro** [comment]
I'll submit a PR. I just need to wrap my head around your PR process (if you have any tip).
Btw, I was wondering why you designed the url generator with this regex (even numbers are filtered through `[^/]++` expr). And I was wondering if you have some diagram or some representation showing the logic and interactions between objects.
Keep up the great work, thank you.

**Comment by pjedrzejewski** [comment]
@rmNyro Have a look here: http://docs.sylius.org/en/latest/contributing/index.html.
