### ISSUE TITLE
[Sylius/Sylius-Standard] autoload psr-4 in composer.json 

### ISSUE THREAD

**Issue by brunocombodo** [Sylius/Sylius#7605]
Hello,

I'm using `Sylius/Sylius-Standard`,

I'm new to symfony & composer, so I spent a lot of time figuring out why my custom bundles wasn't autoloaded, this reason is because in the [composer.json](https://github.com/Sylius/Sylius-Standard/blob/master/composer.json) of `Sylius/Sylius-Standard`, the autoload section is : 
```javascript
    "autoload": {
        "psr-4": {
            "AppBundle\\": "src/AppBundle/"
        },
        "classmap": ["app/AppKernel.php", "app/AppCache.php"]
    },
```
I think it should have a `"": "src/"` like this : 
```javascript
    "autoload": {
        "psr-4": {
            "AppBundle\\": "src/AppBundle/",
            "": "src/"
        },
        "classmap": [
            "app/AppKernel.php", "app/AppCache.php"
        ]
    },
```

or even : 
```javascript
    "autoload": {
        "psr-4": {
            "": "src/"
        },
        "classmap": [
            "app/AppKernel.php", "app/AppCache.php"
        ]
    },
```

**Comment by pjedrzejewski** [comment]
@brunocombodo Can you open this issue on Sylius-Standard, please? Thanks!

**Comment by pamil** [comment]
It will affect the Composer autoloader performance (without dumped classmap) - looking for class `Symfony\Foo` it would check `src/Symfony/Foo.php` first and then `vendor/symfony/symfony/src/Symfony/Foo.php`.

However it is the way Symfony-Standard handles it, so we might want to do the same in order to be more similar to them.

**Comment by brunocombodo** [comment]
@pjedrzejewski : done => https://github.com/Sylius/Sylius-Standard/issues/163
