### ISSUE TITLE
Create administrator in command line would lost username field

### ISSUE THREAD

**Issue by thailandjerry** [Sylius/Sylius#7623]
When I have created database in production env. I should create administraor in command line.

input:

`$ php bin/console sylius:install:setup `

output:

```
$ php bin/console sylius:install:setup
Currency (press enter to use USD): 
Adding US Dollar currency.
Adding American English locale.
Create your administrator account.
E-mail:admin@modain.com
Choose password:
Confirm password:
Administrator account successfully registered.
```

The username field lost, so I cannot log into backend dashboard.

Please confirm. Thanks a lot.

Jerry Song from KL Malaysia.

**Comment by Zales0123** [comment]
Have you tried to log in with your email (admin@modain.com) as it's used as username?

**Comment by thailandjerry** [comment]
Yes, I tried it. But failure also.

**Comment by TheMadeleine** [comment]
But why?

While installing Sylius, when you do not provide your administrator data, the default account will be created. 

And what do you mean by failure?

**Comment by thailandjerry** [comment]
I means that is failure if I login with admin email and password.

**Comment by Zales0123** [comment]
Could you please provide any more information? Maybe some stack trace or screenshoots?

**Comment by thailandjerry** [comment]
`jerry@jerry-Latitude-E6510 ~/Code/BvShop $ php bin/console sylius:install --env=prod
Installing Sylius...

Step 1 of 4. Checking system requirements.
Success! Your system can run Sylius properly.

Step 2 of 4. Setting up the database.
Creating Sylius database for environment prod.
It appears that your database already exists. Would you like to reset it? (y/N) y
 5/5 [||||||||||||||||||||||||||||] 100%
Warning! This will erase your database. Your current environment is prod.
Load sample data? (y/N) N
Cancelled loading sample data.

Step 3 of 4. Shop configuration.
Currency (press enter to use USD): 
Adding US Dollar currency.
Adding American English locale.
Create your administrator account.
E-mail:admin@bvshop.com
Choose password:
Confirm password:
Administrator account successfully registered.

Step 4 of 4. Installing assets.
Installing Sylius assets for environment prod.
 1/1 [||||||||||||||||||||||||||||] 100%
Sylius has been successfully installed.
You can now open your store at the following path under the website root: /.
`

Next step, access mySQL database table sylius_admin_user , find the "username"field is null.

But, this time, I can login successfully with username "admin@bvshop.com" and password "admin".

So, The problem is not so serious.

Thank you very much for suggesting try again.

**Comment by TheMadeleine** [comment]
I think we can close this @pjedrzejewski, @michalmarcinkowski :)
