### ISSUE TITLE
[ResourceBundle] Events

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#7631]
Just opening up this issue to keep track of this feature request which was initially proposed in the sylius-dev slack channel.

Currently there is no way to hook into the ResourceBundle to keep track of certain things. For example, lets say I wanted to keep track of abandoned carts that were cleared up through the `ExpiredCartRemover`. There is currently no way of doing it.

The discussion on slack lead to a solution based on events from the ResourceBundle.

**Comment by pjedrzejewski** [comment]
We have added events to the expired cart remover. These events are used for UI/API operations performed by user/client. If you want to be certain that things happen on delete/persist/update, you should use doctrine orm events. There is no other way. :)
