### ISSUE TITLE
Language switching inconsistency

### ISSUE THREAD

**Issue by Im0rtality** [Sylius/Sylius#764]
When language is changed via dashboard, some parts part of website loads other language.

Right after language change (Polish -> Russian):
![capture](https://f.cloud.github.com/assets/1804210/1818671/b6702d60-7019-11e3-832d-7092f0d38fa9.PNG)

Changed currency to quickly get another alert:
![capture2 2](https://f.cloud.github.com/assets/1804210/1818674/110aa70a-701a-11e3-80c3-5c82fd6ea621.PNG)

After further changes alert stays English. Behavior is same when changing other languages as well.

**Comment by antonioperic** [comment]
ping @pjedrzejewski

**Comment by pjedrzejewski** [comment]
Not relevant anymore.
