### ISSUE TITLE
Change local in shop don't work

### ISSUE THREAD

**Issue by lasotaartur** [Sylius/Sylius#7655]
Steps to reproduce

1. Add locale in Configuration -> Locales in admin
2. Select old and new locale in channel in Configuration -> Channels -> Edit (first one) -> Locales in admin
3. Change default locale to new locale in shop - default locale is still selected

I tested it on dev-master

**Comment by pjedrzejewski** [comment]
I swear I was playing with the app today and it worked just fine. :/

**Comment by pamil** [comment]
I just have checked it out and I couldn't reproduce it.

**Comment by lasotaartur** [comment]
It works. :)

**Comment by michalmarcinkowski** [comment]
Closing then 😉
