### ISSUE TITLE
How to get inventory from API

### ISSUE THREAD

**Issue by anned20** [Sylius/Sylius#7671]
Our use case is very specific. We need to get the data from a live API called TecDoc.

This API sends us data about car parts and fitments. We then need to order that part via TecCom.

So the inventory has to be from TecDoc and all orders have to be send to TecCom.

Now we kinda figured out how to get our orders to TecCom but have no clue on how to get the data from TecDoc in our inventory.

The flow of the customer will be something like: Customer inputs vehicle registration -> data is pulled from TecDoc -> customer sees data -> customer selects a part and orders it -> order shows up in sylius admin and goes to TecCom -> TecCom sends the part to the customer.

Any input on this?

Thanks!

**Comment by pjedrzejewski** [comment]
Hi Anne!

So, you basically need to load products from external system into Sylius? You can do that in many ways, use Sylius API to create them from a separate app, which consumes TecCom API. Or you can create some Symfony commands, that will load data from TecCom API and create products programmatically. (have a look at docs and fixture's code)

**Comment by anned20** [comment]
Well the problem is not loading the data in the database. It's way too much data to store. They have to be fetched in realtime.

**Comment by okwinza** [comment]
The Sylius core won't suit for that usecase you've decribed. I advice you to come up with your own solution based on standalone Sylius Bundles.
