### ISSUE TITLE
AddressChoiceType hardcoded 'customer'

### ISSUE THREAD

**Issue by RomainSanchez** [Sylius/Sylius#7672]
In `AddressChoiceType.php` the call to retrieve addresses is made with `$this->addressRepository->findBy(['customer' => $options['customer']]);`

This hardcoded 'customer' relation prevents from replacing Sylius' Customer and address entities as the relationship is forced to be called customer.

If it was `$this->addressRepository->findByCustomer($options['customer']);`   we could easily replace the repository class and make our own  `findByCustomer` method.

I am willing to make a PR if needed

**Comment by pjedrzejewski** [comment]
@RomainSanchez Makes sense to me, I will be happy to merge such PR! 👍
