### ISSUE TITLE
Sylius install 

### ISSUE THREAD

**Issue by Cathmor** [Sylius/Sylius#7674]
Hi! Really excited to use Sylius!
I'm running through the sylius-standard install just like in download page on the site and I ran into a db error. 

It is not creating all of the columns for table sylius_channel. When I look at the xml in the channel bundle it's columns that it's trying to find are missing. Am I missing some xml or is doctrine not combining xml files?

One thing of note, I'm on mssql so I'm using pdo_sqlsrv as my driver.

Thanks

**Comment by pjedrzejewski** [comment]
Hi @Cathmor! We never tested Sylius with mssql. Can you maybe post here part of the sql that ``doctrine:schema:create --dump-sql`` generates? (part with sylius_channel table) That would give us some hint perhaps, thanks!

**Comment by Cathmor** [comment]
I can when I get a chance to run an new install in a day or two. I think I hacked and edited too many xml files to be able to give you accurate troubleshooting info. 

But after some editing I was able to get the shop and admin up and running and there is 1 MAJOR issue with mssql compatibility. There are several cascade on delete that may cause cycles or multiple cascade paths in mssql and will not be created but are allowed in mysql. I may try setting up some triggers to compensate for removing those.

Again I'll try all of this in a day or two and keep you guys posted.

**Comment by Cathmor** [comment]
Hi, after a couple of installs from composer and running `sylius:install` a couple times (on empty dbs) and `doctrine:schema:create --dump-sql` to look at what was running I was unable to recreate my original issue of missing columns. Must have been something I've done or and issue with my db. Sorry for the false alarm.

**Comment by pjedrzejewski** [comment]
@Cathmor Thanks for closing the issue!
