### ISSUE TITLE
ProductBundle Installation Problem

### ISSUE THREAD

**Issue by maxthev** [Sylius/Sylius#7684]
Hi !

I'm trying to use Sylius OrderBundle and ProductBundle in a project and I encounter a problem when  I install ProductBundle :

```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  The service "sylius.form.type.product_attribute_value" has a dependency on a non-exis
  tent service "sylius.repository.locale".
```

I tried adding LocaleBundle in AppKernel.php like this:

```php
public function registerBundles()
    {
        $bundles = [

            //Sylius Dependencies
            new winzou\Bundle\StateMachineBundle\winzouStateMachineBundle(),
            new FOS\RestBundle\FOSRestBundle(),
            new JMS\SerializerBundle\JMSSerializerBundle($this),
            new Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle(),
            new WhiteOctober\PagerfantaBundle\WhiteOctoberPagerfantaBundle(),

            //Sylius
            new Sylius\Bundle\LocaleBundle\SyliusLocaleBundle(),
            new Sylius\Bundle\MoneyBundle\SyliusMoneyBundle(),
            new Sylius\Bundle\OrderBundle\SyliusOrderBundle(),
            new Sylius\Bundle\ResourceBundle\SyliusResourceBundle(),
            new Sylius\Bundle\ProductBundle\SyliusProductBundle(),
            new Sylius\Bundle\AttributeBundle\SyliusAttributeBundle(),

             //Symfony
            new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
[...]
```

And i got :

```
LocaleNotFoundException in CompositeLocaleContext.php line 56:
Locale could not be found!
```

So i tried adding the parameter in config.yml:

```yml
parameters:
    locale: fr
    sylius.locale: %sylius.locale%

framework:
    #esi:             ~
    secret:          "%secret%"
```

and this time i got :

```
ParameterCircularReferenceException in ParameterBag.php line 212:
Circular reference detected for parameter "sylius.locale" ("sylius.locale" > "sylius.locale").
```

Here I am, i really don't know what to do to resolve this problem. Thank you in advance !

**Comment by TheMadeleine** [comment]
What versions of these bundles are you using? :)

**Comment by maxthev** [comment]
I use dev-master versions (the last stable versions 0.19.0 are for Symfony 2.8 ...)

```
        "sylius/order-bundle":"dev-master",
        "sylius/order":"@dev",
        "sylius/money-bundle":"@dev",
        "sylius/resource-bundle":"@dev",
        "sylius/resource":"@dev",
        "sylius/product-bundle":"dev-master",
        "sylius/product":"dev-master",
        "sylius/attribute-bundle":"@dev",
        "sylius/attribute":"@dev",
        "sylius/locale-bundle":"@dev",
        "sylius/locale":"@dev",
        "sylius/registry":"@dev"
```

**Comment by TheMadeleine** [comment]
First of all, I am pretty sure you do not need this part:

```
sylius.locale: %sylius.locale%
```
in your config. 

But you can try adding:

```
framework:
    translator: { fallbacks: ["%locale%"] }
    default_locale: "%locale%"
```

**Comment by maxthev** [comment]
Same issue :

```
LocaleNotFoundException in CompositeLocaleContext.php line 56:
Locale could not be found!
```

I also found this thread but it didn't help me:

https://github.com/Sylius/Sylius/issues/6125

**Comment by maxthev** [comment]
Still no solution for this problem, does someone have an idea ?

**Comment by lchrusciel** [comment]
@maxthev the last version with support for Symfony 2.8 is [alpha2](https://github.com/Sylius/Sylius/releases/tag/v1.0.0-alpha.2) release. Can you check which one do you use? 
Can you try with locale 'fr_FR'?
```yml
parameters:
    locale: fr_FR
```

But probably without XDebug you won't be able to resolve this issue. We need to know which contexts are available and why they are failing.

**Comment by maxthev** [comment]
@lchrusciel Hi, i'm using Symfony 3.2 with ProductBundle dev-master/1.0.x-dev.

The parameter change nothing.

For the rest, it's juste a fresh 3.2 Symfony with Sylius OrderBundle and ProductBundle installation, nothing more. It's a new "from scratch" project.

**Comment by maxthev** [comment]
Ok I think it work now. I reinstalled all Sylius bundles with "^1.0@beta" instead of "dev-master".
After this, i had to remove 

```PHP
new Sylius\Bundle\LocaleBundle\SyliusLocaleBundle(),
```

from the AppKernel.php
