### ISSUE TITLE
No Symfony 2.8 support 

### ISSUE THREAD

**Issue by RomainSanchez** [Sylius/Sylius#7687]
Hi again, i was trying to update sylius to dev-master to take advantage of the changes of #7683 but composer says sylius requires Symfony 3.2.
Sylius doesn't support 2.8 anymore?

**Comment by okwinza** [comment]
AFAIK Sylius moved to symfony 3.x since beta. 
Could you link the commit hash from which you're trying to update?

**Comment by RomainSanchez** [comment]
https://github.com/Sylius/Sylius/commit/983966a6b7fa491ccf218477c6fba8e654ade3d1

**Comment by okwinza** [comment]
Well, the thing is that composer.json was updated in november in https://github.com/Sylius/Sylius/commit/eaeaf3d3b8ad7271f4e89e2c35d472bf34ad5714 so if you are trying to do a rebase in a project with earlier revision of sylius' master branch - it will fail.

Otherwise it wouldn't be an issue.

**Comment by okwinza** [comment]
So you have to be compatible with that composer version restriction somehow.

**Comment by RomainSanchez** [comment]
Couldn't you make a tag of the last commit alowing 2.8 ?

**Comment by okwinza** [comment]
You're looking for this one: https://github.com/Sylius/Sylius/releases/tag/v1.0.0-alpha.2

**Comment by RomainSanchez** [comment]
Thanks

**Comment by RomainSanchez** [comment]
And would it be possible to cherry-pick https://github.com/Sylius/Sylius/commit/983966a6b7fa491ccf218477c6fba8e654ade3d1 into alpha 2 ?

**Comment by okwinza** [comment]
IMO i don't think it makes sense to support both 2.8 and 3.x at this point.
/cc @michalmarcinkowski

**Comment by pamil** [comment]
We already use features introduced in Symfony 3.1 & 3.2, so it won't be easy.

**Comment by okwinza** [comment]
@pamil in theory, we could maintain a second branch based on that alpha2 tag and backport  things from master from time to time but it would really weird.

**Comment by lchrusciel** [comment]
@okwinza @pamil eZ community wants to maintain a version of Sylius with Symfony2.8 compatibility, but I don't know what is the state of that.

**Comment by RomainSanchez** [comment]
@okwinza that's what i had in mind

**Comment by pjedrzejewski** [comment]
Let's continue discussions here: https://github.com/pjedrzejewski/SyliusSymfony28. We do not officially support it, so it's up to the community.
