### ISSUE TITLE
[Shipping methods] [Discussion] Introducing "Shipping Provider"

### ISSUE THREAD

**Issue by psihius** [Sylius/Sylius#7689]
Moving discussion here because Slack is not the best medium for a thoughtful discussion including lots of people and long reads 👍 

Basic idea: Introduce a "Carrier" or "Shipping Provider".
Reason: Many shipping providers are international and you can use a single shipping provider to ship across half of the world (or in my case - across the whole EU).
Problem: Because for each shipping method added based on the zoned costs you have to define "code" - you end up with a bunch of shipping methods that are using the same "shipping provider", but have different "code" values (basically, keywords). Chances are you are going to use the same API for all those shipping methods for same shipping provider, but because of different codes for each "shipping method - zone" pair, you need to maintain a map of what code to what shipping provider is related to use the same integration code.

In my specific case, there is also an issue of self-pickup boxes - I have 2 providers with that option and they cover all 3 Baltic state countries, and we ship to all 3 countries. Prices are different for each country, so that means I have to add 3 shipping methods for each country for each shipping provider - meaning 6 shipping methods (having 6 shipping methods is not the problem here). But my self-pickup boxes are related to the shipping carrier, not shipping methods. Ideally I would like to just filter the pickup boxes by country the user has selected and not tailor my integration for importing/updating the list of boxes so that they link to each specific shipping method "code" value.

In my case it looks like this:
omniva-lv
omniva-lt
omniva-ee
dpd-lv
dpd-lt
dpd-ee

Both shipping method "code" field values and self-pickup box "shipping method" field values have to use these exact values to have the link between them. If a new country is added - I have to modify my import/update code and make sure the "shipping method" added has a proper keyword entered (meaning if manager adds it and then says "It does not work" - I have to go into the database and edit it via SQL query as this cannot be done in the admin panel).
And this will work only for zones that contain a single country. If the scope for the zone is multiple countries - this hack brakes, and this is pretty much a guarantee for anyone who is working in the EU market - you split it into a few zones and set the prices - I don't think you ever going to add all EU countries separately.

**Comment by zdenektopic** [comment]
👍 I second this, same issue here

**Comment by wadjeroudi** [comment]
linked to #3281
