### ISSUE TITLE
Removed images aren't deleted from the filesystem

### ISSUE THREAD

**Issue by DmitriyTrt** [Sylius/Sylius#7699]
How to reproduce:
- Upload an image to taxon or product
- Delete it through admin UI without adding any replacement

The file will still be there, while the DB record is deleted properly. It's important to not upload a replacement, because otherwise the file is removed properly. There is a chance we broke something with customizations, but I can't see the code in Sylius responsible for such a file deletion.

**Comment by Zales0123** [comment]
It's almost two years, I've just checked it on the newest Sylius 1.3 and it seems to be resolved. I'm closing it, feel free to reopen if any clarification is needed :) 🖖
