### ISSUE TITLE
[PromotionBundle] Coupon validation is too dummy

### ISSUE THREAD

**Issue by stloyd** [Sylius/Sylius#770]
Right now coupon validation is not a real thing, in theory you can depend on events in model transformer, but it complicates life more than it solves.

As a developer I want to show the end user message that coupon:
- not exists,
- is expired,
- was already used,
- he didn't pass the rules on assigned promotion,
- maybe something more =)

And the problem with current implementation is that, I'm able to do only two things:
- coupon not exists,
- or coupon is "invalid", but I have no real idea [why it's invalid](http://www.ludumdare.com/compo/wp-content/uploads/2013/04/i-have-no-idea-what-im-doing-dog.jpg).

Simplest solution I guess would be replace of the form transforming (don't check validation there, do it in correct place, just transform the value etc.), with real validation and removal of dummy check done at coupon model in advance of real validation.

**Comment by michalmarcinkowski** [comment]
Fixed in #6273.
