### ISSUE TITLE
Default order confirmation e-mail is coupled with the Shop bundle

### ISSUE THREAD

**Issue by DmitriyTrt** [Sylius/Sylius#7700]
Turning off the Shop bundle makes the "create" order transition to fail with an exception:

> An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "sylius_shop_order_show" as such route does not exist.") in "SyliusCoreBundle:Email:orderConfirmation.html.twig" at line 6.

I guess Core template shouldn't use the route from the Shop bundle.

**Comment by pjedrzejewski** [comment]
Yes, the template should be in ShopBundle, and seems like the listener and everything related too.
