### ISSUE TITLE
Cannot retry payment due to out of stock due to my own order

### ISSUE THREAD

**Issue by gorkalaucirica** [Sylius/Sylius#7707]
**Steps to reproduce**

1. Add to cart a product variant with 1 unit left on stock
2. Proceed to checkout and select Paypal for example, as a payment method
3. Cancel paypal payment and return to order show page
4. Retry with paypal.
5. Get "Product does not have sufficient stock" error

**Investigation**

We see that after checkout is completed that product is marked as "onHold" and therefore is out of stock as we have 1 on hand and 1 on hold.

Somehow the InStockValidator needs to check if the products we are trying to pay is on hold in the same order

**Comment by psihius** [comment]
Second this, it would be great if this could be handled, as I have this exact requirement from a client :) We planned just to cancel the previous orders, but this would make it way easier and more appropriate.

**Comment by zdenektopic** [comment]
Wouldnt it be better to put stock unit onHold right when order status changes to "new"? You dont need to worry about stock units after that - its doesnt matter how user is going to pay, you are sure and the user is sure that the product is reserved for him.

**Comment by pamil** [comment]
Solution proposed by @zdenektopic looks good, does anyone know any disadvantages of this approach?

**Comment by pamil** [comment]
I'm on it! :)
