### ISSUE TITLE
Inventory - suppliers stock

### ISSUE THREAD

**Issue by zdenektopic** [Sylius/Sylius#7712]
It would be nice if Inventory component would also support supplier stock keeping information so we can show information to the user that the product can be shipped in 3 days or something like that.

**Comment by pjedrzejewski** [comment]
Sounds like a good idea, although it will need to wait for 1.1. :)

**Comment by zdenektopic** [comment]
Great, also this would have effect in orders as orders would have shipping state of something like "waiting for stock/product/supplier"
