### ISSUE TITLE
SyliusThemeBundle - setting theme per request, not for whole application

### ISSUE THREAD

**Issue by zdenektopic** [Sylius/Sylius#7714]
Hello guys,

I was thinking of running Sylius under reactphp webserver for performance, I already know it is possible with plain Symfony SE (https://gnugat.github.io/2016/04/13/super-speed-sf-react-php.html).

However I need to implement ThemeContextInterface service in a way that returns the Theme based on request which I am not sure how to do since it has just simple getter method. Setting request info to the service with listener is same as setting the Theme so its not the solution.

**Comment by pamil** [comment]
I don't know if I understood correctly, but you can inject Symfony's `RequestStack` to your custom `ThemeContextInterface` implementation and then resolve the theme based on request retrieved by `$this->requestStack->getMasterRequest()`.

**Comment by zdenektopic** [comment]
Well `RequestStack` is also service isnt it? It means it is stateful, if i have more master requests processing concurrently it will mess with it, probably.
