### ISSUE TITLE
PayPap express checkout working out of the box

### ISSUE THREAD

**Issue by ascameron1** [Sylius/Sylius#7728]
Ive done a new installation of the project using the documentation provided. 

I am trying to set a new PayPal payment method using the cookbook documentation [Here](http://docs.sylius.org/en/latest/cookbook/paypal.html). 

When trying to access the route provided, i am getting the error:

No route found for "GET /admin/payment-methods/new/paypal_express_checkout"

Also, there is no PayPal gateway which is selectable when adding a new payment method. Is there a step I'm missing or is there a part of the documentation which I have missed? I have looked around to try and sort this issue and have seen various settings in config.yml such as :

`payum:
    gateways:
        yourgateway:
            factory: yourgateway`

But my understanding was that Sylius now takes care of this and PayPal was to work "out of the box".

Thanks in advance.

**Comment by TheMadeleine** [comment]
What version of Sylius are you using @ascameron1 ?

**Comment by ascameron1** [comment]
Hi @TheMadeleine 

sylius/sylius-standard (v1.0.0-beta.1)

**Comment by TheMadeleine** [comment]
Is it possible for you to upgrade to `dev-master`?

**Comment by ascameron1** [comment]
I could try yes. I do that by updating my composer.json file? Currently I'm set to;

`"require": {
        "php": ">=5.5.9",
        "sylius/sylius": "^0.18@dev",
        "sensio/generator-bundle": "^2.3",
        "sensio/distribution-bundle": "^3.0"
}`

Thank you

**Comment by TheMadeleine** [comment]
Yes, exactly. you need to change the `"sylius/sylius": "^0.18@dev"` to `"sylius/sylius": "dev-master"`, make sure your min stablility is dev `"minimum-stability": "dev"`,
an then run `composer update sylius/sylius --with-dependencies` :)

**Comment by ascameron1** [comment]
Hey,

Sorry for the delay, run into a couple of issue during update but sorted them now.... and it has worked. Thank you for taking time to answer my questions. I really appreciate it 👍 .

**Comment by TheMadeleine** [comment]
@ascameron1 Is it working then? Can we close the issue? :)

**Comment by psihius** [comment]
I updated recently to the new gateway management and it worked flawlessly for PayPal for me without any issues 👍

**Comment by ascameron1** [comment]
@TheMadeleine Yes this is working... thank you for all your help.
