### ISSUE TITLE
Checkout Form Extensions: constraints/validation looks like is not fired / ignored

### ISSUE THREAD

**Issue by psihius** [Sylius/Sylius#7732]
Here is a minimal use-case that shows that it does not work.

- Get a fresh sylius install with dev-master or apply to existing project that does not have any modification to Address components
- Create file `src/AppBundle/Form/Extension/AddressTypeExtension.php` and copy contents bellow into it

```php
<?php

namespace AppBundle\Form\Extension;

use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Sylius\Bundle\AddressingBundle\Form\Type\AddressType;

class AddressTypeExtension extends AbstractTypeExtension
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('phoneNumber', TextType::class, [
            'required' => true,
            'label' => 'sylius.form.address.phone_number',
        ]);
    }


    public function getExtendedType()
    {
        return AddressType::class;
    }
}
```
- Add to `src/AppBundle/Resources/config/services.yml` configuration
```yaml
    app.form.extension.type.address:
        class: AppBundle\Form\Extension\AddressTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\AddressingBundle\Form\Type\AddressType }
```
- Place a product into the card and go to the checkout to the Address filling step
- Fill everything except the phone number - after submit there is no validation error and you are allowed to proceed to the "Select shipping" stage

P.S. Adding a `'constraints' => [new NotBlank()]` to the field in the form extension makes no difference.

I have seen same behaviour on various projects now for various checkout stages.

**Comment by pjedrzejewski** [comment]
Well, that's because:

1. required => true is merely an indication for the html rendered.
2. We use ``sylius`` validation group, so that ``NotBlank`` from your second example would work only if you add it with ``validation_groups => ['sylius']``.

**Comment by psihius** [comment]
@pjedrzejewski adding the validation_group does not help, I forgot to add this to the initial report.
It still does not validate and allows to go through.

```php
<?php

namespace AppBundle\Form\Extension;

use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Sylius\Bundle\AddressingBundle\Form\Type\AddressType;
use Symfony\Component\Validator\Constraints\NotBlank;

class AddressTypeExtension extends AbstractTypeExtension
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('phoneNumber', TextType::class, [
            'required' => true,
            'label' => 'sylius.form.address.phone_number',
            'constraints' => [new NotBlank()],
            'validation_groups' => ['sylius']
        ]);
    }


    public function getExtendedType()
    {
        return AddressType::class;
    }
}
```

**Comment by psihius** [comment]
Okay, I think I figured it out. It's a bit more complex than just making a new form - you actually have to combine the http://docs.sylius.org/en/latest/customization/form.html and http://docs.sylius.org/en/latest/customization/validation.html - I think you can't even define constraints in the form extension - you have to go the config file way, and that's kind'a a blocker for dynamic validation when validation is dependent on some condition.
I saw the idea of modifying the validation group - is that the prefered way of doing custom conditional validation constraints?

**Comment by pamil** [comment]
@psihius have you tried something like:

```php
<?php

namespace AppBundle\Form\Extension;

use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Sylius\Bundle\AddressingBundle\Form\Type\AddressType;
use Symfony\Component\Validator\Constraints\NotBlank;

class AddressTypeExtension extends AbstractTypeExtension
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('phoneNumber', TextType::class, [
            'required' => true,
            'label' => 'sylius.form.address.phone_number',
            'constraints' => [new NotBlank(['groups' => ['sylius']])]
        ]);
    }

    public function getExtendedType()
    {
        return AddressType::class;
    }
}
```

**Comment by psihius** [comment]
@pamil I will try and report tomorrow. Thanks!

**Comment by padalec** [comment]
Hi there,
I have similar problem but nothing of suggested solution what works for me. This is my scenerio. I created a extended type from Sylius\Bundle\AddressingBundle\Form\Type\AddressType.
```php
<?php
declare(strict_types=1);
namespace App\AddressingBundle\Form\Extension;
use Sylius\Bundle\AddressingBundle\Form\Type\AddressType as BaseAddressType;
use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

final class AddressType extends AbstractTypeExtension
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add(
                'title',
                ChoiceType::class,
                [
                    'choices'     => [
                        'app.form.addressing.mrs' => 'mrs',
                        'app.form.addressing.mr'  => 'mr',
                    ],
                    'placeholder' => 'form.addressing.title',
                ]
            )
            ->add(
                'phoneNumber',
                TextType::class,
                [
                    'required' => true,
                    'label'    => 'sylius.form.address.phone_number',
                ]
            )
        ;
    }

    public function getExtendedType(): string
    {
        return BaseAddressType::class;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'validation_groups' => ['sylius'],
            ]
        );
    }
}
```
And all of this field have to be required and NotBlank so I created a xml file:
`src/App/AddressingBundle/Resources/config/validation/Address.xml`
with this configuration:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<constraint-mapping
        xmlns="http://symfony.com/schema/dic/constraint-mapping"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://symfony.com/schema/dic/constraint-mapping http://symfony.com/schema/dic/services/constraint-mapping-1.0.xsd">

    <class name="App\AddressingBundle\Entity\Address">
        <property name="title">
            <constraint name="NotBlank">
                <option name="message">app.user.title.not_blank</option>
                <option name="groups">
                    <value>sylius</value>
                </option>
            </constraint>
        </property>
        <property name="phoneNumber">
            <constraint name="NotBlank">
                <option name="message">app.user.phoneNumber.not_blank</option>
                <option name="groups">
                    <value>sylius</value>
                </option>
            </constraint>
        </property>
        <property name="firstName">
            <constraint name="NotBlank">
                <option name="message">app.user.firstName.not_blank</option>
                <option name="groups">
                    <value>sylius</value>
                </option>
            </constraint>
        </property>
        <property name="lastName">
            <constraint name="NotBlank">
                <option name="message">app.user.lastName.not_blank</option>
                <option name="groups">
                    <value>sylius</value>
                </option>
            </constraint>
        </property>
    </class>
</constraint-mapping>
```
and in my registration form I add the base sylius type: Sylius\Bundle\AddressingBundle\Form\Type\AddressType 
```php

declare(strict_types=1);

namespace App\CustomerBundle\Form\Extension;

use Sylius\Bundle\AddressingBundle\Form\Type\AddressType;
use Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerRegistrationType as BaseCustomerRegistrationType;
use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

final class CustomerRegistrationType extends AbstractTypeExtension
{

    public function getExtendedType()
    {
        return BaseCustomerRegistrationType::class;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'defaultLanguage',
                ChoiceType::class,
                [
                    'label'       => 'app.form.register.language.label',
                    'placeholder' => 'app.form.register.language.label',
                    'choices'     => [
                        'app.form.register.language.en' => 'en',
                        'app.form.register.language.de' => 'de',
                    ],
                    'mapped'      => false,
                ]
            )
            ->add(
                'birthday',
                BirthdayType::class,
                [
                    'label'       => 'app.form.register.birth_date',
                    'placeholder' => 'app.form.register.birth_date',
                    'widget'      => 'single_text',
                ]
            )
            ->add(
                'defaultAddress',
                AddressType::class
            )
            ->add('submit', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'startHour'         => null,
                'endHour'           => null,
                'validation_groups' => ['sylius'],
            ]
        );
    }
}
```
and XML file with configuration of validation: `/src/App/CustomerBundle/Resources/config/validation/Customer.xml`

```XML
<?xml version="1.0" encoding="UTF-8"?>
<constraint-mapping
        xmlns="http://symfony.com/schema/dic/constraint-mapping"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://symfony.com/schema/dic/constraint-mapping http://symfony.com/schema/dic/services/constraint-mapping-1.0.xsd">

    <class name="App\CustomerBundle\Entity\Customer">
        <property name="firstName">
            <constraint name="NotBlank">
                <option name="message">app.user.firstName.not_blank</option>
                <option name="groups">
                    <value>sylius</value>
                </option>
            </constraint>
        </property>
        <property name="lastName">
            <constraint name="NotBlank">
                <option name="message">app.user.lastName.not_blank</option>
                <option name="groups">
                    <value>sylius</value>
                </option>
            </constraint>
        </property>
        <property name="defaultLanguage">
            <constraint name="NotBlank">
                <option name="message">app.user.defaultLanguage.not_blank</option>
                <option name="groups">
                    <value>sylius</value>
                </option>
            </constraint>
        </property>
    </class>
</constraint-mapping>
```
validation only works on fields placed in base customer type `Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerRegistrationType`
other fields are omitted
Regards

**Comment by aario-sitewards** [comment]
> Hi there,
> I have similar problem but nothing of suggested solution what works for me. This is my scenerio. I created a extended type from Sylius\Bundle\AddressingBundle\Form\Type\AddressType.
> 
> ```
> <?php
> declare(strict_types=1);
> namespace App\AddressingBundle\Form\Extension;
> use Sylius\Bundle\AddressingBundle\Form\Type\AddressType as BaseAddressType;
> use Symfony\Component\Form\AbstractTypeExtension;
> use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
> use Symfony\Component\Form\Extension\Core\Type\TextType;
> use Symfony\Component\Form\FormBuilderInterface;
> use Symfony\Component\OptionsResolver\OptionsResolver;
> 
> final class AddressType extends AbstractTypeExtension
> {
>     public function buildForm(FormBuilderInterface $builder, array $options): void
>     {
>         $builder
>             ->add(
>                 'title',
>                 ChoiceType::class,
>                 [
>                     'choices'     => [
>                         'app.form.addressing.mrs' => 'mrs',
>                         'app.form.addressing.mr'  => 'mr',
>                     ],
>                     'placeholder' => 'form.addressing.title',
>                 ]
>             )
>             ->add(
>                 'phoneNumber',
>                 TextType::class,
>                 [
>                     'required' => true,
>                     'label'    => 'sylius.form.address.phone_number',
>                 ]
>             )
>         ;
>     }
> 
>     public function getExtendedType(): string
>     {
>         return BaseAddressType::class;
>     }
> 
>     public function configureOptions(OptionsResolver $resolver)
>     {
>         $resolver->setDefaults(
>             [
>                 'validation_groups' => ['sylius'],
>             ]
>         );
>     }
> }
> ```
> 
> And all of this field have to be required and NotBlank so I created a xml file:
> `src/App/AddressingBundle/Resources/config/validation/Address.xml`
> with this configuration:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <constraint-mapping
>         xmlns="http://symfony.com/schema/dic/constraint-mapping"
>         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>         xsi:schemaLocation="http://symfony.com/schema/dic/constraint-mapping http://symfony.com/schema/dic/services/constraint-mapping-1.0.xsd">
> 
>     <class name="App\AddressingBundle\Entity\Address">
>         <property name="title">
>             <constraint name="NotBlank">
>                 <option name="message">app.user.title.not_blank</option>
>                 <option name="groups">
>                     <value>sylius</value>
>                 </option>
>             </constraint>
>         </property>
>         <property name="phoneNumber">
>             <constraint name="NotBlank">
>                 <option name="message">app.user.phoneNumber.not_blank</option>
>                 <option name="groups">
>                     <value>sylius</value>
>                 </option>
>             </constraint>
>         </property>
>         <property name="firstName">
>             <constraint name="NotBlank">
>                 <option name="message">app.user.firstName.not_blank</option>
>                 <option name="groups">
>                     <value>sylius</value>
>                 </option>
>             </constraint>
>         </property>
>         <property name="lastName">
>             <constraint name="NotBlank">
>                 <option name="message">app.user.lastName.not_blank</option>
>                 <option name="groups">
>                     <value>sylius</value>
>                 </option>
>             </constraint>
>         </property>
>     </class>
> </constraint-mapping>
> ```
> 
> and in my registration form I add the base sylius type: Sylius\Bundle\AddressingBundle\Form\Type\AddressType
> 
> ```
> 
> declare(strict_types=1);
> 
> namespace App\CustomerBundle\Form\Extension;
> 
> use Sylius\Bundle\AddressingBundle\Form\Type\AddressType;
> use Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerRegistrationType as BaseCustomerRegistrationType;
> use Symfony\Component\Form\AbstractTypeExtension;
> use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
> use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
> use Symfony\Component\Form\Extension\Core\Type\SubmitType;
> use Symfony\Component\Form\FormBuilderInterface;
> use Symfony\Component\OptionsResolver\OptionsResolver;
> 
> final class CustomerRegistrationType extends AbstractTypeExtension
> {
> 
>     public function getExtendedType()
>     {
>         return BaseCustomerRegistrationType::class;
>     }
> 
>     public function buildForm(FormBuilderInterface $builder, array $options)
>     {
>         $builder
>             ->add(
>                 'defaultLanguage',
>                 ChoiceType::class,
>                 [
>                     'label'       => 'app.form.register.language.label',
>                     'placeholder' => 'app.form.register.language.label',
>                     'choices'     => [
>                         'app.form.register.language.en' => 'en',
>                         'app.form.register.language.de' => 'de',
>                     ],
>                     'mapped'      => false,
>                 ]
>             )
>             ->add(
>                 'birthday',
>                 BirthdayType::class,
>                 [
>                     'label'       => 'app.form.register.birth_date',
>                     'placeholder' => 'app.form.register.birth_date',
>                     'widget'      => 'single_text',
>                 ]
>             )
>             ->add(
>                 'defaultAddress',
>                 AddressType::class
>             )
>             ->add('submit', SubmitType::class);
>     }
> 
>     public function configureOptions(OptionsResolver $resolver)
>     {
>         $resolver->setDefaults(
>             [
>                 'startHour'         => null,
>                 'endHour'           => null,
>                 'validation_groups' => ['sylius'],
>             ]
>         );
>     }
> }
> ```
> 
> and XML file with configuration of validation: `/src/App/CustomerBundle/Resources/config/validation/Customer.xml`
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <constraint-mapping
>         xmlns="http://symfony.com/schema/dic/constraint-mapping"
>         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>         xsi:schemaLocation="http://symfony.com/schema/dic/constraint-mapping http://symfony.com/schema/dic/services/constraint-mapping-1.0.xsd">
> 
>     <class name="App\CustomerBundle\Entity\Customer">
>         <property name="firstName">
>             <constraint name="NotBlank">
>                 <option name="message">app.user.firstName.not_blank</option>
>                 <option name="groups">
>                     <value>sylius</value>
>                 </option>
>             </constraint>
>         </property>
>         <property name="lastName">
>             <constraint name="NotBlank">
>                 <option name="message">app.user.lastName.not_blank</option>
>                 <option name="groups">
>                     <value>sylius</value>
>                 </option>
>             </constraint>
>         </property>
>         <property name="defaultLanguage">
>             <constraint name="NotBlank">
>                 <option name="message">app.user.defaultLanguage.not_blank</option>
>                 <option name="groups">
>                     <value>sylius</value>
>                 </option>
>             </constraint>
>         </property>
>     </class>
> </constraint-mapping>
> ```
> 
> validation only works on fields placed in base customer type `Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerRegistrationType`
> other fields are omitted
> Regards

Same here.

**Comment by aario-sitewards** [comment]
So correct path of the file validation.yml is:
```
config/validator/validation.yml
```
While the documentation:
https://docs.sylius.com/en/1.3/customization/validation.html
Says otherwise:
```
src/Resources/config/validation.yml
```
This must be corrected. If you are customizing validation of an extended property (A property you added by extending an entity), you must mention its own class name on top of validation.yml file instead of the base class name.
Now the bottom toolbar shows me the validation error which means everything works except the error bubbles that don't appear. The bubble appears for other fields in the same form but not the added field.
setting error bubbling to true didn't work.
Setting error mapping didn't work.
setting validation groups didn't work.
Trying to debug the core code to reverse engineer how it works,
vendor/symfony/form/Extension/Validator/ViolationMapper/ViolationMapper.php:mapViolation
Finds a match and returns the correct validation error within its results. Still the bubble doesn't appear in rendered html.

**Comment by jcgdjob** [comment]
Not working on ProductVariant

**Comment by itinance** [comment]
This document helped me:

https://docs.sylius.com/en/1.2/customization/validation.html?highlight=validation

In my case i just added a `AppBundle\Resources\config\validation.yml` with the following content:

```
AppBundle\Entity\Artist:
  properties:
    name:
      - NotBlank:
          message: sylius.product.name.not_blank
          groups: [artist, sylius]
      - Length:
          min: 10
          minMessage: sylius.product.name.min_length
          max: 255
          maxMessage: sylius.product.name.max_length
          groups: [artist, sylius]
```

ArtistType.php:

```
        $builder
            ->add('name', TextType::class, [
                'required' => true,
                'validation_groups' => ['artist']
            ])

```

However, the NotBlank-Constraint is not working as expected. Submitting an empty Textfield will call "setName" with null, which gives an exception as null-values aren't allowed in my setName-method.

**Comment by sasa-b** [comment]
This is what made it work for me but only in the Form Builder, when I follow the steps from Customize Validation guide it does not work, I'm using Sylius 1.9:

```
 $builder->add('phoneNumber', TextType::class, [
            'required' => true,
            'label' => 'sylius.form.address.phone_number',
            'constraints' => [new NotBlank(['groups' => ['sylius', 'sylius_shipping_address_update']])],
            'validation_groups' => ['sylius', 'sylius_shipping_address_update']
        ]);
```
