### ISSUE TITLE
Variant name lost when editing the product

### ISSUE THREAD

**Issue by crevillo** [Sylius/Sylius#7735]
Hi. Strange thing when editing a product with only one variant. Here are the steps to reproduce this issue.
 - Do a fresh sylius install
 - go to admin and go the product list
 - find a product with only one variant
 - list variants of that product, take note of the name of the variant
 - edit and save the product
 - go to the list of variants of the product

You'll see the variant name has changed. Further more, when you edit the variant, name fields appears blank. 

This only seem to happen when product has only one variant. 

Anyone experiencing this?

**Comment by plozmun** [comment]
Name variant is not mandatory. It takes from product name if it not set. Maybe a placeholder with product name in blank field could be a good solution

**Comment by crevillo** [comment]
hola :). Yeah, is not mandatory, but question is why it gets lost once you edit the product. it should be maintained i think. it's maintained when you have more than one variant.

**Comment by plozmun** [comment]
It's true, if there is one variant the name change

**Comment by plozmun** [comment]
This is cause because it is a Simple Product. You can prevent this adding 
`$form->get('variant')->remove('name');`
after this https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ProductBundle/Form/EventSubscriber/SimpleProductSubscriber.php#L51-L56

**Comment by crevillo** [comment]
great!.

**Comment by pamil** [comment]
Same happens with **available on** and **available after**.
