### ISSUE TITLE
[ResourceBundle] (beta.1) Class "form" is not configured for resource "my.resource".

### ISSUE THREAD

**Issue by leogout** [Sylius/Sylius#7736]
Hi, I got this error on a fresh install of ResourceBundle beta.1 with a resource configured like the following :
```yml
sylius_resource:
    resources:
        app.book:
            classes:
                model: AppBundle\Entity\Book
```
As you can see, I didn't configured the form:default field, as in Alpha.1 the [DefaultFormbuilder](https://github.com/Sylius/Sylius/blob/v1.0.0-alpha.2/src/Sylius/Bundle/ResourceBundle/Doctrine/ORM/Form/Builder/DefaultFormBuilder.php) should have guessed what to do. I can't see this builder anymore, neither the [DefaultResourceType](https://github.com/Sylius/Sylius/blob/v1.0.0-alpha.2/src/Sylius/Bundle/ResourceBundle/Form/Type/DefaultResourceType.php) class. They've been removed in [this](https://github.com/Sylius/Sylius/commit/2b2cfbe6ed217db8bdf752ca8aa9c8d662d3b351) commit.

When I do a container:debug, I (obviously) don't get the DefaultResourceType:
```
php bin/console debug:container | grep book                                                                        
  app.controller.book                                                         Sylius\Bundle\ResourceBundle\Controller\ResourceController                                  
  app.factory.book                                                            Sylius\Component\Resource\Factory\Factory                                                   
  app.manager.book                                                            alias for "doctrine.orm.default_entity_manager"                                             
  app.repository.book                                                         Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
```

I guess you guys did that on purpose, if so, this is more a documentation problem. Should I update [the docs](http://docs.sylius.org/en/latest/cookbook/custom-model.html) ?

Cheers !

**Comment by lchrusciel** [comment]
We had to remove this class to bring Symfony3 support in Beta1, but it has been brought back in #7185. You can use current dev-master to use it or wait for Beta2 which should be released in a few days. The docs are up-to-date.

**Comment by leogout** [comment]
Okay, my bad... Thanks for your time !
