### ISSUE TITLE
Product info template of the Admin bundle is coupled wih the Shop bundle

### ISSUE THREAD

**Issue by DmitriyTrt** [Sylius/Sylius#7739]
The `AdminBundle/Resources/views/Product/_info.html.twig` template references `sylius_shop_product_show` route, which breaks the order administration page while Shop bundle is disabled.

**Comment by Zales0123** [comment]
Which version of *Sylius* do you use? I believe it's fixed after https://github.com/Sylius/Sylius/commit/0334d78c05721799dcc24f2bac8cbe5b1f6ca5a0

**Comment by DmitriyTrt** [comment]
Sorry, haven't checked the latest code. You're right, should be fixed already.
