### ISSUE TITLE
CompositeCartContext : cart is empty after login

### ISSUE THREAD

**Issue by bruno-ds** [Sylius/Sylius#7741]
Hello,

the ̀Sylius\Component\Order\Context\CompositeCartContext ̀ handles the fact that multiple cart candidate may exists.
If 
- you are not logued in and have a cart with items
- have an empty cart in the database associated with your login

once you log in, the (empty) cart stored in the database  has a priority higher and you loss your cart.
I see two solutions : 
- change the priorities => I'd rather use this solution but I don't see how I can modify the existing priorities (defined as follow : `<tag name="sylius.context.cart" priority="-555" />`in the `vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Resources/config/services/context.xml` (maybe the priorities should be overwritable variables)
- if the cart is empty go the the next candidate in the loop of  ̀Sylius\Component\Order\Context\CompositeCartContext::getCart() ̀

a pseudo code would be : 
```php
    public function getCart()
    {
        $cartCandidate = [];
        foreach ($this->cartContexts as $cartIndex => $cartContext) {
            try {
                $cartCandidate[$cartIndex] =  $cartContext->getCart();
                if ($cartCandidate[$cartIndex]->countItems() == 0) { 
                    continue;
                }
            } catch (CartNotFoundException $exception) {
                continue;
            }
        }
        if (count($cartCandidate) > 0) {
             return reset($cartCandidate);//apply the rule only if there is no less prioritized cart with items
        }
        throw new CartNotFoundException();
    }
```

**Comment by bruno-ds** [comment]
Or maybe it could merge the two carts (the current one and the one stored in the database).

If the cart is merged or replaced, it would be appréciable to display a message to the customer.

**Comment by bruno-ds** [comment]
I just saw that you did not tagged this issue as a tag.
since it is your expected behavior, I think it is perceived but the end user as a bug.

+ as I force the user to log in once in the checkout process, his cart is silently altered, IMHO it result in a really weird comportment.

**Comment by veloxy** [comment]
@bruno-ds I've just noticed this issue too, after logging in in the checkout process the cart is replaced. It's very weird behavior, how did you end up solving this?

Merging the cart without any notice would still be very weird to a customer who was on their way to check out their cart, only valid option I see from a usability standpoint would be to keep the cart and throw the database cart away when logged in from the checkout process. When logging in through the login page, the customer could have a choice to merge the two carts of pick one or the other

**Comment by bruno-ds** [comment]
Our sale team weirdly asked us to remove the cart and to force the user to make a purchase per product.
As a side effect, we did not suffer from this probleme ever since.

PS: the issue is closed, I'm not sure it will be reopened, maybe you should create a new issue (and link to this one is you want to give a little more context).

**Comment by veloxy** [comment]
@bruno-ds thank you for the response, even though it's an old issue! I did notice after my comment that there already a host of other similar tickets, I don't think the behavior will be changed. Though I found a comment somewhere where it said it was possible to change priority on the carts - will probably go with that route.
