### ISSUE TITLE
Missing Attribute on Products API list

### ISSUE THREAD

**Issue by ardani** [Sylius/Sylius#7752]
i try sylius product API but i see missing object on list API 
but when i call Product API details attribute fine
![screenshot at mar 14 12-04-53](https://cloud.githubusercontent.com/assets/2499777/23886661/332e211e-08af-11e7-8e4b-8ec6c3f3170c.png)

any solution for that
thanks

**Comment by lchrusciel** [comment]
It seems that you are missing the serialization for attributes. AFAIK it has been resolved in the newest master, so you can either update to dev-maser or declare attributes serialization by your own.
