### ISSUE TITLE
Disabling order confirmation email

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#7763]
On beta1, emails were sent using the state machine, which wasn't perfect, but it allowed me to disable the order confirmation email, and send out my own payment confirmation email.

Currently there are a few issues:

- I initially thought it was the event `sylius.order.post_payment`, but its not. It should be renamed `sylius.order.post_select_payment`
- The event that it is supposed to be (`sylius.payment.post_complete`) doesn't fire, but there is already a ticket open.
- I can't seem to easily disable the current email sent via listening to `sylius.order.post_complete`.

Finally, I just wanted to ask, why does Sylius send order confirmation emails before payment anyways? I would think that most people would want an order confirmation email once something has been paid for.

**Comment by crevillo** [comment]
while i see the point on not sending emails until the payment is complete, i doubt how we should proceed then in case payment method is somehting like `cash on delivery` or `bank transfer`...  you don't receive the payment at that time there but still you need to notify the user and maybe the shop about the order.

**Comment by pamil** [comment]
When I buy something online I often get two messages:
 - one that I have placed an order
 - another one that the order has been paid

Isn't it the most flexible solution?

**Comment by c-revillo** [comment]
well, same here, but normally that second one is sent by the payment gatewy. for instnace, if i buy something for dinner tonight and pay with paypal i normally get an email from the commerce and another one from paypal...

About receiving an email when placing order i still have my doubts. if should be carefully thinking what we tell the customer there to avoid missunderstandings.

**Comment by inssein** [comment]
@pamil that has not been my experience, but I do see the value. That said, if a payment framework had one of them, I'd imagine it would be payment confirmation.

Like @c-revillo mentioned above, I have a hard time understanding what an order confirmation email would have for most online stores. I do understand Cash on Delivery and Pay in store, but those seem like special cases to me.

**Comment by c-revillo** [comment]
well, maybe we can add a new level of complication :). depending on payment mode you could send the email once the order is placed or once the order is paid...

**Comment by zdenektopic** [comment]
why would you disable order confirmation email? for unregistered user it doesnt make sense, you want to get email with information about your order and also email that order status has changed - eg. payment received and some others

**Comment by inssein** [comment]
@zdenektopic because we prefer to send the order confirmation email after payment has been made. No point sending two emails, and especially in our case, the order confirmation is quite meaningless until it has been paid for.

**Comment by zdenektopic** [comment]
I see, this should be allowed in sylius for easy customization

**Comment by pamil** [comment]
It's quite similar to #7707.

What about having two emails configured to be sent (one after placing order, one after successful payment) and allowing them to be disabled by some configuration (at what level? channel? application? any ideas?)?

**Comment by pjedrzejewski** [comment]
We will either make it configurable or write a cookbook how to disable certain e-mails. Not a blocker for the release.

**Comment by inssein** [comment]
@pjedrzejewski I thought it was a blocker because there was no trivial way to disable certain emails. Am I missing something simple?

**Comment by pjedrzejewski** [comment]
Remove listener services/their tags? :) @TheMadeleine We need a coobook that will describe this, can be the confirmation e-mail.

**Comment by dbalabka** [comment]
@pjedrzejewski IMO most of the stores follow two scenarios of sending confirmation emails:
1. When customers use **offline payment** (Bank transfer or cash on delivery) then order confirmation is sent right after order has been placed.
2. When customers use **online payment** (e.g. PayPal) then order confirmation should be sent right after the payment is successfully done.

It is not trivial to adjust Sylius logic to implement the above-described logic:
1. You have to decorate `\Sylius\Bundle\ShopBundle\EmailManager\OrderEmailManager::sendConfirmationEmail` to send confirmation email always for offline payments and only for paid orders in case of online payment.
2. Send an order confirmation email when the order has been paid using a state machine callback.

This issue was already discussed in #6261. I advise changing the default behavior of confirmation emails or at least describe the step-by-step configuration in the documentation.
