### ISSUE TITLE
Error when going back to address step in checkout

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#7774]
What I did:

* Add item to cart
* Go to checkout
* Enter information and go to next step (I have skipping shipping step enabled, so I go directly to the payment step)
* Click on the 'Address' block (from the checkout steps) to go back to address information page
* Get error

Checked it also in another browser with a fresh cookie, same behavior. 

Sylius version: dev-master d33ce31 

Beginning of the stack trace:

```
[1] Twig_Error_Runtime: Impossible to access an attribute ("customer") on a null variable.
    at n/a
        in /var/www/webshop/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/Address/_addressBookSelect.html.twig line 6

    at Twig_Template->getAttribute(null, 'customer', array())
        in /dev/shm/sylius/cache/dev/twig/5a/5ab68d9dfb5518a6bb57328e03a4448fc101f1e3810cc7f44dbd2df67a20e29b.php line 37
```

**Comment by pamil** [comment]
I can't reproduce it on the newest master, can you provide a failing Behat scenario?

**Comment by stefandoorn** [comment]
I will try to upgrade to dev-master later this week and see if it's still reproducible.
