### ISSUE TITLE
Deleting a taxon breaks admin edit and product view

### ISSUE THREAD

**Issue by shaunroot** [Sylius/Sylius#7786]
To reproduce, open a Sylius demo installation and delete a taxon through the admin interface. Then, browse to a product that had that taxon in the admin section or user front end.

**admin/products/[id]/edit**
`An exception has been thrown during the rendering of a template ("Entity of type 'Sylius\Component\Core\Model\Taxon' for IDs id(2) was not found") in @SyliusAdmin/Product/Tab/_taxonomy.html.twig at line 11.`

**products/[id]**
`An exception has been thrown during the rendering of a template ("Entity of type 'Sylius\Component\Core\Model\Taxon' for IDs id(6) was not found") in @SyliusShop/Product/Show/_breadcrumb.html.twig at line 6.`

When a taxon is deleted, all products with the equivalent product.main_taxon_id should should have their values set to null and related entries should be removed from sylius_product_taxon.

**Comment by Cathmor** [comment]
What do you mean by Sylius demo installation? I was unable to reproduce this issue.

I went through `composer create-project -s dev sylius/sylius`  and `composer create-project -s beta sylius/sylius-standard acme`and installed sample data and tried deleting the mens t-shirt taxon and I got an error flash message. It wouldn't let me delete it.

Should there be a `on-delete="SET NULL"` in the Product xml in the CoreBundle to accommodate this?

**Comment by shaunroot** [comment]
I am also unable to reproduce from a fresh DB with sample data. I will continue testing and start a new ticket when I have more information.
