### ISSUE TITLE
Images on Entity - adding one item

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#7795]
The docs describe 'It needs to have the images field as a CollectionType. If you want to give the possibility to add more than one image to the entity set the allow_add option to true.' at http://docs.sylius.org/en/latest/cookbook/images-on-entity.html.

Unfortunately setting this `allow_add` to `false` means users can add zero images, so there is no option to just add a single image.

I'm using dev-master@d33ce31 to test this.

**Comment by pjedrzejewski** [comment]
Related to #7790. Let's continue discussion there.
