### ISSUE TITLE
Sylius/product-bundle : You have requested a non-existent service "sylius.factory.product_variant"

### ISSUE THREAD

**Issue by tvequaud** [Sylius/Sylius#7803]
Hi there,

New retry to install with composer sylius/product-bundle 0.19 into an existing project downgraded to Symfony 2.8 with this guideline : http://docs.sylius.org/en/latest/bundles/SyliusProductBundle/installation.html

Composer step is OK.
AppKernel step is OK.
But the doctrine:schema:update command triggers an exception :
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException] You have requested a non-existent service "sylius.factory.product_variant".

**I suppose the guideline is incomplete**... In addition, I tried to install sylius/order-bundle + sylius/taxation-bundle and both are installed.

in app/AppKernel.php :

	public function registerBundles()
	{
		$bundles = [
			// Sylius
			new FOS\RestBundle\FOSRestBundle(),
			new JMS\SerializerBundle\JMSSerializerBundle($this),
			new Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle(),
			new WhiteOctober\PagerfantaBundle\WhiteOctoberPagerfantaBundle(),
			new winzou\Bundle\StateMachineBundle\winzouStateMachineBundle(),
			new Sylius\Bundle\ProductBundle\SyliusProductBundle(),
			new Sylius\Bundle\AttributeBundle\SyliusAttributeBundle(),
			new Sylius\Bundle\ResourceBundle\SyliusResourceBundle(),

			// My Bundles
			new AppBundle\AppBundle(),

			// Doctrine
			new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
			new Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle(),
		];

**Comment by pjedrzejewski** [comment]
0.19 is no longer supported, please use ``stability`` flag set to ``dev`` when using Composer and it will install latest version for you.

**Comment by tvequaud** [comment]
`[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]   
  The service "sylius.controller.product" has a dependency on a non-existent   
  service "sylius.resource_registry".̀  `

...

**Comment by tvequaud** [comment]
@pjedrzejewski I finally fixed it by installing sylius/sylius. You should seriously think about updating the documentation.

Here is my final composer.json, with flag `minimum-stability` set to `dev` - I really don't like it - so I added a flag `prefere-stable`  :
`
[...]
{
	"minimum-stability" : "dev",
	"prefer-stable" : true,
	"require" : {
		"php" : "^7.0",
		"sylius/sylius" : "^1.0@beta",
		"friendsofsymfony/user-bundle" : "~2.0@dev",
		"symfony/assetic-bundle" : "^2.8",
		"knplabs/knp-paginator-bundle" : "^2.5",
		"vakata/jstree" : "^3.3",
		"liip/imagine-bundle" : "^1.7",
		"liuggio/excelbundle" : "^2.1",
		"ensepar/html2pdf-bundle" : "^3.0",
		"tetranz/select2entity-bundle" : "^2.9",
		"ezyang/htmlpurifier" : "^4.9"
	},
	"require-dev" : {
		"behat/behat" : "^3.2",
		"behat/mink" : "^1.7",
		"behat/mink-browserkit-driver" : "^1.3",
		"behat/mink-extension" : "^2.2",
		"behat/mink-selenium2-driver" : "^1.3",
		"bossa/phpspec2-expect" : "^1.0",
		"coduo/php-matcher" : "^2.1",
		"friends-of-behat/context-service-extension" : "^0.3",
		"friends-of-behat/cross-container-extension" : "^0.2",
		"friends-of-behat/performance-extension" : "^1.0",
		"friends-of-behat/service-container-extension" : "^0.3",
		"friends-of-behat/suite-settings-extension" : "^1.0",
		"friends-of-behat/symfony-extension" : "^0.2.1",
		"friends-of-behat/variadic-extension" : "^0.1",
		"lakion/api-test-case" : "^1.0",
		"lakion/mink-debug-extension" : "^1.2.3",
		"phpspec/phpspec" : "^3.2",
		"phpunit/phpunit" : "^5.6",
		"se/selenium-server-standalone" : "^2.52",
		"sensio/generator-bundle" : "^3.1",
		"stripe/stripe-php" : "^4.1"
	},
[...]
}`
