### ISSUE TITLE
[ResourceBundle] Unable to customize the data passed to the view

### ISSUE THREAD

**Issue by ste93cry** [Sylius/Sylius#7804]
There seems to be no easy way to customize the data passed to the view from the actions of the `ResourceController` class. The `$view` variable is populated and then just returned to the view handler. If a user wants to pass additional data to the view he has to override the whole method. There should be at least an event dispatched after the view is populated with data, or, feeling this overkill, the actions should maybe be semplified by moving common parts to a service so that overriding the method is easier.

**Comment by isometriks** [comment]
Could return the view directly so you can get it from the parent method and then use the `kernel.view` event to use the ViewHandler to transform the view into a response.

**Comment by ste93cry** [comment]
>use the kernel.view event

This would be indeed a good solution to fix the problem, although we would lose the ability to create a custom response

>I was also thinking about using Argument Resolvers

Nice idea, but if I'm not wrong this feature is available only on Symfony 3+ while the bundle supports Symfony 2.8

**Comment by isometriks** [comment]
You could still use a custom response, the kernel.view event would only check to see if the controllers return value is an instance of View, if it's not then the response would just get sent as is, similar to using the @Template annotation and returning an array.

**Comment by ste93cry** [comment]
Sure, it's just that creating a listener, checking for the controller, see if that controller is what you want, etc just to maybe customize a header of a certain route seems overcomplicated.
