### ISSUE TITLE
No translation in flash admin message

### ISSUE THREAD

**Issue by lasotaartur** [Sylius/Sylius#7805]
After updating the record in any admin module it appears success flash message ie. in polish "Customer został pomyślnie uaktualniony.". Should be "Klient został pomyślnie uaktualniony.".

**Comment by pjedrzejewski** [comment]
Flash messages need to be translated manually, they are automatically generated for English, because we have the resource name already. For other languages, keys need to be translated. I am not sure if it is possible now on Crowdin to add keys without their English counterparts, I will check.
