### ISSUE TITLE
Users can not see what items are in a category in order to delete it

### ISSUE THREAD

**Issue by hdwebpros** [Sylius/Sylius#7815]
We've built a shop and imported over from Magento.

The client wants to delete a category. It shows as empty, but says the taxon is in use.

The category page does not display items which have a category set in the main category spot but not in the tree.

How is this alleviated without having to dig into the DB?

**Comment by pjedrzejewski** [comment]
Ouch, this one is tough as I don't see a clean solution. Possibly a listener that removes it from all products, just before deletion. (finds all products which have this taxon as main taxon, set to null, then should work)

Far from perfect but I am pretty sure it will resolve the issue. WDYT?

**Comment by hdwebpros** [comment]
My $0.02, it's confusing that there's a main taxon tree and a completely separate main taxon. But, let's move on and get a good solution here.

Why isn't it recommended to show items that have the main taxon as the taxon you are viewing? Is there a good reason for not showing those items? By simply showing those items, you'd alleviate this issue.

Your solution works too, but it changes taxons of items without people knowing and it could cause a bunch of items with no taxons or at least no main taxons. That's my fear with that.

**Comment by mbabker** [comment]
Something that could possibly help short term would be to at least show the main taxon in the grid list view instead of hiding it completely.  Even if the `sylius_admin_product_per_taxon_index` route can't include that field in the query to fetch the items, at least showing it (and possibly adding it as a filter option) would let folks find those items from the `sylius_admin_product_index` route.

**Comment by pjedrzejewski** [comment]
Yeah, this mainTaxon is a bit pain in the a** now... Because for the ``taxons`` relation we have a separate entity ProductTaxon and sorting. For mainTaxon there is none, so not sure where to display these products... At the end/beginning? Generally it is a bit weird...

**Comment by mbabker** [comment]
#7921 will at least show the main taxon in the admin grid view, so there's a starting point.

Now the "tough" question.  Is there a valid use case for a product being assigned to a taxon through the `mainTaxon` relation but not being assigned to the `taxons` relation as well?  One possible way out of this without wreaking too much havoc is to make `Product::setMainTaxon()` also call `Product::addProductTaxon()`, but this would require a B/C break by changing the `mainTaxon` property to a `ProductTaxonInterface` implementation versus `TaxonInterface`.
