### ISSUE TITLE
UX Issue with "Main Taxon" in Admin Bundle

### ISSUE THREAD

**Issue by mbabker** [Sylius/Sylius#7817]
Navigating to the `sylius_admin_product_per_taxon_index` route, you get a list of all items assigned to a taxon.  This works pretty well, but it doesn't include items where an item is assigned to a taxon with the "Main taxon" field but not in the overall tree selection area below.  Which makes sense once you grasp the difference between these two fields.

However, it does present a mild usability issue.  This morning our client was trying to clean up some of the data imported from another platform and trying to remove what they thought was an empty taxon, however Sylius was telling them that the taxon was still in use.  Since they had moved all items out of that taxon and nothing was showing on the filtered product listing, they were confused (it wasn't until I checked the database that I grasped what was happening here).

I'm not quite sure on what a good approach to addressing this issue is, but IMO there is a need to be able to filter products based on the assigned main taxon.

**Comment by pamil** [comment]
Looks to be the same issue as #7815.

**Comment by mbabker** [comment]
Yep.  We were talking about it before I drove to the office, didn't realize he put one in before I got here.
