### ISSUE TITLE
Customizing model "Product" => The table with name 'sylius.sylius_product_options' already exists.

### ISSUE THREAD

**Issue by tvequaud** [Sylius/Sylius#7818]
Hi there,

I was trying to integrate the Sylius product approach within my Product entity following this guideline : http://docs.sylius.org/en/latest/customization/model.html

This guideline explains that I have to extend either the Component or Core model and that I have to check this state with the commande `php bin/console debug:container --parameter=sylius.model.product.class`

Here is the result I got :
```console
 ---------------------------- ---------------------------------------- 
  Parameter                    Value                                   
 ---------------------------- ---------------------------------------- 
  sylius.model.product.class   Sylius\Component\Product\Model\Product  
 ---------------------------- ---------------------------------------- 
```

Actually, it's wrong. I got the CoreBundle installed and the Product model is inherited in Sylius\Component\Core\Model\Product.

And I still have the exception 
`[Doctrine\DBAL\Schema\SchemaException] The table with name 'sylius.sylius_product_options' already exists.`

Any suggestion ?

**Comment by tvequaud** [comment]
The same when I try with the Country Entity in AppBundle just like in the guideline... Same result : `The table with name 'dynaweb.sylius_country' already exists.̀`

**Comment by pamil** [comment]
CoreBundle needs to have its configuration imported using:

```yaml
imports:
    - { resource: "@SyliusCoreBundle/Resources/config/app/config.yml" }
```

Like Sylius have in `app/config/config.yml`.

**Comment by tvequaud** [comment]
Just figured it out that I commented the line importing my Sylius config... I changed so any things to make it working that I forgot that... Damn ! :/

**Comment by tvequaud** [comment]
It seems to work like that without including the Core config... I keep that in mind... Thanks pamil for your help.
