### ISSUE TITLE
Limiting Countries

### ISSUE THREAD

**Issue by Richtermeister** [Sylius/Sylius#782]
I have the use-case to only sell in the USA, so I'm playing with the idea to add an "enabled" flag to the country table (on the core level, not the addressing bundle) and limit the country choices during checkout accordingly.

In addition we could also have a "preference" or "rank" field which could be used for the "preferred choices" part of the widget..

Does this sound like a good idea for Sylius or should I just hack this into my own project?

**Comment by pjedrzejewski** [comment]
Implemented.
