### ISSUE TITLE
Price on product page is first one not selected one

### ISSUE THREAD

**Issue by mrjingles** [Sylius/Sylius#7820]
If I enter the product page, the shown price is not the one of the selected variant (combination) but the first one from the hidden price list.

**Comment by tuka217** [comment]
Hello,
I created a product with variants with options like this: color[red, yellow, green], size[s,m,l] and set them prices. When I went to show page of this product I could see the current price of the variant for selected options combination (for example Red S). So, could you check if this issue will have still happened after you'll update to the current Sylius master? (Or maybe you have already the newest version)?
Unless you expected that the product variant with first (0) position will be shown as the default one on the product show page in the shop?

**Comment by mrjingles** [comment]
Situation was the following. The first variant I created wasn't the first combination of options. In your example red/s. I created for example yellow/m at first variant. When I visit product show page it shows selected red/s as default but the price was from the variant (yellow/m). As I remember it was fixed in latest master, I cannot reproduce right now.
