### ISSUE TITLE
different locale in admin and shop

### ISSUE THREAD

**Issue by samanmohamadi** [Sylius/Sylius#7822]
I use different locale in admin(EN) and shop(fa_IR), So all taxons needs to be  created in fa_IR locale .
the problem is when I want to choose a taxon for a product it search and shows me only taxons in EN locale, because the locale of sylius context in admin is EN.
I think locale should not be involved in searching for resources in admin.

**Comment by aistis-** [comment]
Hi @samanmohamadi how do you set a different locale for the admin? Thanks

**Comment by pjedrzejewski** [comment]
Duplicate of #8225.
