### ISSUE TITLE
ORM mapping option

### ISSUE THREAD

**Issue by tvequaud** [Sylius/Sylius#7827]
The model customization needs to put some Doctrine mapping configuration.
=> http://docs.sylius.org/en/latest/customization/model.html

But my Symfony project is entirely base on Doctrine annotations... Is there a way to use my annotations instead of refactoring my entire project models ????

**Comment by pjedrzejewski** [comment]
I am pretty sure you can use annotations. Did you try it? We recommend YML/XML though. Please reopen if still a problem.

**Comment by tvequaud** [comment]
@pjedrzejewski I tried yesterday... Just cleaned the cache and renamed the Yml file and... It works without the mapping... Damn ! Thank you for your quick answer.
