### ISSUE TITLE
Taxons broken

### ISSUE THREAD

**Issue by zdenektopic** [Sylius/Sylius#7841]
Hi, I found issue where I cant move some sub-taxon to another parent.
heres screenshot from admin.
<img width="1146" alt="snimek obrazovky 2017-03-28 v 0 32 19" src="https://cloud.githubusercontent.com/assets/2551911/24380948/1e47af00-134e-11e7-883f-c14e2e377b6e.png">

**Comment by pamil** [comment]
Looks to be working correctly for me: https://youtu.be/z2e6xOqwJ4w

**Comment by wodor** [comment]
@zdenektopic  It looks like `Parent` list is loaded with ajax call like this `admin/ajax/taxons/search?phrase=&_=1490716168562`, can you check if it is successful in browser inspection ? 
I must admin that it loads for me after 1-2s delay sometimes, after I click it. So this might be js related issue.
