### ISSUE TITLE
new product/Variant : use a transaction and commit after the state_machine execution

### ISSUE THREAD

**Issue by bruno-ds** [Sylius/Sylius#7844]
Hello,

I've put some logic in the state machine : when a product and an extension are added, it create some additional tables.
But sometimes, my process fail and the tables are not created, but the product/variant are created eitehr way. 
So thoses products are bugged and cannot be correctly processed when sold.

Would it be possible to add a transaction who cover from the product/variant creation until the execution of the state_machine's callback.

I realize that it is not an universal need, so maybe if it is configurable by resource, it would be acceptable for you?

________
Beginner's Technical hint : I suppose that the code should be in `ResourceController` on `createAction`, `updateAction`, `deleteAction`. But I don't understand how it should read an additional parameter set to the resource, maybe with an additional treatment in the `MetadataInterface`?

**Comment by pjedrzejewski** [comment]
Why do you need to create these tables? That is my first thought. :) Because maybe there is a simpler solution to the problem, which does not involve the transaction.
