### ISSUE TITLE
Docs about 'SyliusPluginTrait'

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#7851]
The current docs do not describe anything about using the `SyliusPluginTrait` yet, also the Sylius skeleton bundle doesn't use it. I would write them myself, but I'm not 100% sure yet how it is intended to be used. Besides that, I think there was also some discussion whether it should be Plugin or Bundle suffix, which is probably decided upon using this trait.

Related commit: https://github.com/Sylius/Sylius/commit/0010f551b831f3df5ec57a561b4c6ba8916f2af0

**Comment by pjedrzejewski** [comment]
@TheMadeleine @lchrusciel Can you have a look, please? We definitely need that. :)

**Comment by lchrusciel** [comment]
Plugin update should wait for beta2 release probably, but as soon as #7858 will be merged issue can be closed probably. 

@stefandoorn thanks for reporting :)

**Comment by stefandoorn** [comment]
Yw :) 

One thing I'm a bit in doubt about is not having the 'Sylius' name prefix the plugin, e.g. not `SyliusPdfInvoicePlugin` but `PdfInvoicePlugin`. Problem is that just based on the name nobody can distinguish that it's a specific plugin to Sylius. 

It can only be recognised based on the type in the composer.json file and I think naming the repository could still have `sylius` in it (e.g. sylius-pdf-invoice-plugin), am I right?

**Comment by stefandoorn** [comment]
@pjedrzejewski What about the last question regarding naming repositories when open-sourcing things?
