### ISSUE TITLE
Feedback doc ProductBundle

### ISSUE THREAD

**Issue by tvequaud** [Sylius/Sylius#7853]
Just installed a fresh brand new Symfony 3.2 to test the ProductBundle installation guide : http://docs.sylius.org/en/latest/bundles/SyliusProductBundle/installation.html
Here is my feedback.

1. You should update the documentation to advice developers to use the dev-master branch with composer by this way
`composer require sylius/produc-bundle dev-master`
or in composer.json, add or update the 2 fields in bold :
```
{
	"name" : "thomas/ecommerce",
	"license" : "proprietary",
	"type" : "project",
	**"minimum-stability" : "dev",
	"prefer-stable" : true,**
```
Otherwise the stable version 0.19 is installed instead, unusable and not supported anymore.

2. Then, exception during `doctrine:schema:update` :
```
thomas@debian /var/www/ecommerce $ php bin/console doctrine:schema:update --force

                                                                                                                                      
  [Symfony\Component\Debug\Exception\ContextErrorException]                                                                           
  Warning: class_implements(): Class Sylius\Component\Product\Model\ProductVariantTranslation does not exist and could not be loaded
```

**Comment by TheMadeleine** [comment]
Hi @tvequaud :) Thanks for your feedback, although... it is not an issue. 

Since the docs are prepared and written (kind of upfront) for the oncoming stable release, then they assume that you are using the latest version available. Which is `dev-master` indeed.

**Comment by tvequaud** [comment]
@TheMadeleine : I knew you'll answer that :p  it's not obvious for a beginner. And symfony is delivered in stable so by default newcomers will have a bad first impression (like I had). Even if it's only for few days/weeks.

Anyway I'm using the dev-master branch and got the exception in the second point.

**Comment by TheMadeleine** [comment]
We'll discuss the version mentioning problem at Sylius today, I promise :)

Regarding the exception you've got - did you check if the class exists in the project? Cleared the cache? If your project is clear, maybe recreating the database will help.

**Comment by tvequaud** [comment]
Actually the error in console says that some astract methods are not implemented...

I opened the `/vendor/sylius/product/Model/Product.php` class and, indeed, 5 methods implemented in `Component\Product\Model\ProductInterface` are missing :

```
    /**
     * {@inheritDoc}
     * @see \Sylius\Component\Product\Model\ProductInterface::isAvailable()
     */
    public function isAvailable() {
    	// TODO: Auto-generated method stub

    }

    /**
     * {@inheritDoc}
     * @see \Sylius\Component\Product\Model\ProductInterface::getAvailableOn()
     */
    public function getAvailableOn() {
    	// TODO: Auto-generated method stub

    }

    /**
     * {@inheritDoc}
     * @see \Sylius\Component\Product\Model\ProductInterface::setAvailableOn($availableOn)
     */
    public function setAvailableOn(DateTime $availableOn = null) {
    	// TODO: Auto-generated method stub

    }

    /**
     * {@inheritDoc}
     * @see \Sylius\Component\Product\Model\ProductInterface::getAvailableUntil()
     */
    public function getAvailableUntil() {
    	// TODO: Auto-generated method stub

    }

    /**
     * {@inheritDoc}
     * @see \Sylius\Component\Product\Model\ProductInterface::setAvailableUntil($availableUntil)
     */
    public function setAvailableUntil(DateTime $availableUntil = null) {
    	// TODO: Auto-generated method stub

    }
```

**Comment by tvequaud** [comment]
I finally had to force the update of all sylius/* packages in dev-master too : `composer update sylius/*`

but got another issue : 
```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                     
  The service "sylius.form.type.product_attribute_value" has a dependency on a non-existent service "sylius.repository.locale"
```

I fixed this issue by installing LocaleBundle : 
`thomas@debian> composer require sylius/locale-bundle dev-master`

and in AppKernel.php, I added the line in bold : 
```
new FOS\RestBundle\FOSRestBundle(),
new JMS\SerializerBundle\JMSSerializerBundle($this),
new Stof\DoctrineExtensionsBundle\StofDoctrineExtensionsBundle(),
new WhiteOctober\PagerfantaBundle\WhiteOctoberPagerfantaBundle(),
new winzou\Bundle\StateMachineBundle\winzouStateMachineBundle(),
**new Sylius\Bundle\LocaleBundle\SyliusLocaleBundle(),**
new Sylius\Bundle\ProductBundle\SyliusProductBundle(),
new Sylius\Bundle\AttributeBundle\SyliusAttributeBundle(),
new Sylius\Bundle\ResourceBundle\SyliusResourceBundle(),
```

**Comment by loic425** [comment]
@TheMadeleine @pjedrzejewski 
I have exactly the same error while upgrading a project which uses several sylius bundles into sylius beta 1.
`LocaleNotFoundException in CompositeLocaleContext.php line 52:

There is an empty array on "$this->localeContexts" on CompositeLocaleContext. How to add a localeContext into this service ?

**Comment by chamss19** [comment]
```php
<?php
namespace AppBundle\DependencyInjection\Compiler;


use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;

class OverrideServiceCompilerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        $definition = $container->getDefinition("sylius.context.locale.composite");
        $definition->setDecoratedService(null);
    }
}
```

```php
<?php
namespace AppBundle;

use AppBundle\DependencyInjection\Compiler\OverrideServiceCompilerPass;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class AppBundle extends Bundle
{
    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub
        $container->addCompilerPass(new OverrideServiceCompilerPass());
    }

```

**Comment by loic425** [comment]
@chamss19 it works and it's far better than my "temporary" fix.
