### ISSUE TITLE
Gateway configuration needs more extensability

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#7860]
I know Sylius is in a crunch to get beta2 out, but there are currently a few problems with payment gateway configuration that need to be addressed first (IMO).

1. `PaypalGatewayConfigurationType` is missing the  `sandbox` parameter
2. `StripeGatewayConfigurationType` is missing the `test_mode` parameter
3. There needs to be an easy way to override not only template, but other gateway configurations (for example `payum.action.convert_payment`) via code. 

I've brought up the last item a few items (in past tickets, slack) but none of the solutions seem like a good idea. Is the solution extending each of the gateway factories?

**Comment by pjedrzejewski** [comment]
First 2 should be added to the form types IMO. We could consider the template and other settings too, and populate choices via parameter. WDYT?

**Comment by makasim** [comment]
> There needs to be an easy way to override not only template, but other gateway configurations (for example payum.action.convert_payment) via code.

those could be set as a string `@servic_id` later it will be resolved by core gateway factory to a service. If it failed to resolve it leaves a string value.

Some thoughts on how dynamic gateways could be extended: https://github.com/Payum/Core/pull/4

**Comment by inssein** [comment]
I like the second option (PayumBuilder::addGatewayFactoryConfig). Maybe it is sufficient to write up a cookbook entry on how to do that. I can try and get to that this weekend.

@pjedrzejewski not a fan of template strings / populating choices via parameter, because they can't be changed with simple code deploys. Having to write a migration for a change is the template path doesn't seem like a great option. A similar option was discussed in slack but the downside was the same.

**Comment by makasim** [comment]
> Maybe it is sufficient to write up a cookbook entry on how to do that. I can try and get to that this weekend.

@inssein basically you have to add a method call to `payum.builder` service definition via compiler pass or "by decoration".
