### ISSUE TITLE
Form extension dynamic constraints get ignored

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#7862]
I'm trying to add dynamic constraints to a form extension, using an event subscriber (preSetData). It seems that the 'constraints' option is totally ignored. The 'attr' etc. are added to the form:

```
$form->add('length', IntegerType::class, [
            'scale' => 0,
            'required' => true,
            'attr' => [
                'step' => 1,
            ],
            'constraints' => [
                new Range([
                    'min' => $resource->getProduct()->getMinimumLength(),
                    'max' => $resource->getProduct()->getMaximumLength(),
                ]),
            ]]
        );
```

Submitting the form and looking into the profiler, under the 'constraints' key none are registered. The 'step' of 1 and 'required' are visible though on the form.

The validation groups look to be correct in my case: [sylius, app_order_item]. In this case I'm adjusting the add to cart form.

I'm using dev-master@a7ce677.

**Comment by pamil** [comment]
@stefandoorn add `'groups' => ['sylius']` to `Range` configuration array :)

**Comment by stefandoorn** [comment]
Great, does the job :) Shall I submit a PR to add this to the docs? It's a powerful feature I think to be used.

**Comment by pamil** [comment]
Yeah, I think it may be quite a common case, wdyt @TheMadeleine? :)

**Comment by psihius** [comment]
This is relevant #7732 - I might be not entirely correct there, but I did find that even groups may not work.

**Comment by stefandoorn** [comment]
I think this is still relevant for the documentation.

**Comment by lchrusciel** [comment]
@stefandoorn can you open a PR?
