### ISSUE TITLE
Asset install commands naming inconsistent

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#7867]
```
$ bin/console | grep assets
...
125:  sylius:install:assets                   Installs all Sylius assets.
132:  sylius:theme:assets:install             Installs themes web assets under a public web directory
```

One is called `install:assets` and the other one `assets:install`.

**Comment by stefandoorn** [comment]
@pjedrzejewski What about using sylius:theme:install:assets?

**Comment by stefandoorn** [comment]
What about this one @pjedrzejewski? It's still the case.

**Comment by pamil** [comment]
I'd mark these `sylius:install:*` commands as deprecated and support only the `sylius:install` one.
