### ISSUE TITLE
[UI] Mapping violation on attributeValue

### ISSUE THREAD

**Issue by tuka217** [Sylius/Sylius#7879]
Currently, when we have more than one attribute with values the violations are not attached to a proper value field.  For example here:
![screen shot 2017-04-03 at 10 03 27](https://cloud.githubusercontent.com/assets/8963048/24600462/165ec682-1855-11e7-8ad3-f7ee7c43da72.png)
![screen shot 2017-04-03 at 10 03 38](https://cloud.githubusercontent.com/assets/8963048/24600464/1937fd10-1855-11e7-948f-4c861cf01d91.png)
we expected that `this value should not be blank` will show only in English section (for integer and percent value) and `this collection should contain 1 element or more` should show both in English and Polish section, but only for collection element.

**Comment by Zales0123** [comment]
Btw, `datetime` attribute looks like sadness and wasted dreams 😢

**Comment by Zales0123** [comment]
I've just checked it on the newest Sylius 1.3 and it seems to work:

<img width="863" alt="zrzut ekranu 2019-03-1 o 11 57 18" src="https://user-images.githubusercontent.com/6212718/53633990-4b7f6580-3c19-11e9-90ba-7406fa7cd13e.png">

Closing then.

PS. Datetime attribute value after validation failed is still as ugly as hell 👹 😢
