### ISSUE TITLE
[Checkout] Doubled email validation error on addressing

### ISSUE THREAD

**Issue by NoResponseMate** [Sylius/Sylius#7880]
![screen shot 2017-04-03 at 11 33 25](https://cloud.githubusercontent.com/assets/9448101/24603556/92a4ae44-1861-11e7-8c2b-e9b998ee351c.png)
![screen shot 2017-04-03 at 11 33 46](https://cloud.githubusercontent.com/assets/9448101/24603561/96d93e76-1861-11e7-8f0e-a911df195e2f.png)

Only validation for the email gets duplicated, everything else is fine.

**Comment by c-revillo** [comment]
it looks same is happening to me on register account form, but only if a use an email that i already have in my db...

**Comment by c-revillo** [comment]
it also happens in dev env if you disable debug in the kernel initialization. I mean, 
`$kernel = new AppKernel('dev', false);`

**Comment by pamil** [comment]
Not reproducible on Sylius Demo, I think we have fixed it in the meantime.
