### ISSUE TITLE
Inconsistency in the API doc between Orders, Checkouts and Product Variants

### ISSUE THREAD

**Issue by betaglop** [Sylius/Sylius#7886]
Orders and Checkouts docs present the Variants structure with ``on_hold`` and ``on_hand`` properties, as the Product Variants doc refers to ``onHold`` and ``onHand``. As I am only a reader of the Sylius API Documentation, I cannot propose a pull request, because I cannot know which one is the good representation (even if I can imagine the ``onHold`` and ``onHand`` are the straighter denomination compared to the rest).

**Comment by pjedrzejewski** [comment]
Hey @betaglop! Thanks for reporting this, it's a small bug in the docs, the correct is camelCased one: ``onHold`` & ``onHand``.

**Comment by betaglop** [comment]
Ok thanks for the advise ... I'll propose a pull request then.
