### ISSUE TITLE
Not truly random token generator

### ISSUE THREAD

**Issue by DmitriyTrt** [Sylius/Sylius#7890]
The [token generator](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/User/Security/Generator/UniqueTokenGenerator.php#L73) used for password reset and e-mail verification doesn't look secure to me.

It's enough to know the time of the request and you get more than 1/(40*1000) chance to guess the token. The configuration seems to provide a way to use longer tokens, but due to the way they are generated you actually get less combinations with longer token. 1 in 40k combinations is possible to brute force within default 24 hours (1 attempt per second gives 86400 attempts). And for the e-mail verification there is no time limit at all.

Are there any reasons Sylius doesn't use `random_bytes()` function, as [Symfony CSRF generator](https://github.com/symfony/security/blob/master/Csrf/TokenGenerator/UriSafeTokenGenerator.php) does?

**Comment by pjedrzejewski** [comment]
@NeverResponse Can you have a look at this?
