### ISSUE TITLE
TaxRateResolverInterface only allows returning one tax

### ISSUE THREAD

**Issue by gorkalaucirica** [Sylius/Sylius#7891]
It's kind of RFC to talk about one of the issues we have faced. We have a workaround but we had to extend multiple clases.

By definition TaxRateResolverInterface returns `null|TaxRateInterface`. Due to some business requirements in one of our B2B shops we need to have multiple taxes applied to some of our products.

If `TaxRateResolver` could return multiple taxes we could easily code a custom `TaxRateResolver`, but the classes implementing `OrderTaxesApplicatorInterface` only allow returning `null|TaxRateInterface` from a tax resolver.

The workaround for us was to rewrite all tax applicators to allow using TaxRateResolvers returning an array of `TaxRateInterface`.

Don't know if our use case is common or not and depending on if it is or not maybe we can consider allowing array returns from `TaxRateResolver`.

WDYT?

**Comment by ima-tech** [comment]
I think this is a must. Supporting multiple taxes is extremely important.

**Comment by gorkalaucirica** [comment]
Can we reopen this for 2.0?

**Comment by SteadEXE** [comment]
I agree, in France, for example, we got eco-tax and VAT for the same product, it's 2 differents taxes. (one is a % and the other one is a fixed amount).
