### ISSUE TITLE
Locale code not in available locales

### ISSUE THREAD

**Issue by tchapi** [Sylius/Sylius#7895]
Hi all - I have a very weird behaviour with locales.

I have defined a service that takes the container as an argument.

```php
my_web.product_from_entity_creator:
    class: My\WebBundle\Service\ProductFromEntityCreator
    arguments:
         - "@service_container"
```
In this service, if I do :  

```php
$localeCode = $this->container->get('sylius.context.locale')->getLocaleCode();
$allLocales = $this->container->get('sylius.locale_provider')->getAvailableLocalesCodes();
error_log("Locale is " . $localeCode);
error_log("All locales : " . implode(', ',$allLocales));
```

I have the following result : 

    Locale is fr
    All locales : fr_FR

I don't understand how this works.. The underlying problem is that I don't have a correct locale (I've asked a question on SO about that [here](https://stackoverflow.com/questions/43200617/sylius-locale-code-not-correct)) but to my understanding, the current locale must be one of the available locales, no ?

I would expect the **LocaleContext** to throw an error at some point when trying to resolve the locale since `fr` is not in the array of available locales `['fr_FR']`, but apparently it doesn't.

Is this expected ? I'm trying to debug my code and see where that `fr` comes from but I don't really get how locales are resolved when I see this.

Any hints appreciated,
Thanks a lot !
Best

**Comment by cv65kr** [comment]
Hi,
What you see in sylius profiler ( http://docs.sylius.org/en/latest/_images/toolbar.png ).
I guess in admin panel, locale section you choice from the list language "French" who is assigned to only "fr" code. On list you have more options of languages who have correctly format for You, just look  on this screenshot http://screenshot.sh/m7XZxanvwPVQg

**Comment by tchapi** [comment]
No no, I only have one locale in the backend, and it's `fr_FR`, as per what `getAvailableLocalesCodes();` correctly returns...
