### ISSUE TITLE
[Features request] API Product : filter enabled products within the collection

### ISSUE THREAD

**Issue by tvequaud** [Sylius/Sylius#7901]
My goal is to list enabled products on the front office of my ecommerce website.

Following the doc http://docs.sylius.org/en/latest/api/products.html, the GET method (collections of products) does not permit to filter by "enabled" state

**Comment by tvequaud** [comment]
Finally found how to do this by crawling source code of the AdminBundle...

We have to call  GET /api/v1/products/?criteria[enabled]=true|false
Should be documented in the Product API.

**Comment by venyii** [comment]
FYI this is the case for (most?) of the APIs, it also has its own doc page: http://docs.sylius.org/en/latest/api/sorting_and_filtration.html (last page in The REST API Reference)

**Comment by tvequaud** [comment]
Actually they indicate to use the format GET /api/v1/products/?criteria[enabled][type]=equal|contains&criteria[enabled][value]=true which doesn't work

**Comment by lchrusciel** [comment]
I will try to check it and resolve later today.
