### ISSUE TITLE
[Feature request] API Product : filter products collection by channel

### ISSUE THREAD

**Issue by tvequaud** [Sylius/Sylius#7902]
My goal is to list products from a specific channel onto different ecommerce websites.

Following the doc http://docs.sylius.org/en/latest/api/products.html, the GET method (collections of products) does not permit to filter by "channel".

Tried to call GET /api/v1/products/?criteria[enabled]=true&criteria[channel]=default&criteria[taxon]=parcs_de_loisirs but no filtering...

**Comment by l754640309** [comment]
see https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminApiBundle/Resources/config/grids/product.yml,add channel option.
 example：
           channel:
                    type: entities
                    form_options:
                        class: "%sylius.model.channel.class%"
                    options:
                        field: "channels.code"
