### ISSUE TITLE
[Feature request] Automatically select shipping/payment when possible

### ISSUE THREAD

**Issue by shaunroot** [Sylius/Sylius#7913]
If there is only 1 shipping or payment option, it should automatically be selected in the back end and the user be taken directly to the next page. The user should not need to hit the "Next" button on a page that has no options to select.

<img width="933" alt="sylius-feature-request-001" src="https://cloud.githubusercontent.com/assets/3654817/24782442/4a2100e0-1b14-11e7-8862-c8c803ba8aa2.png">

**Comment by stefandoorn** [comment]
Hi @shaunroot, this feature is already included in dev-master (and will be included in beta-2). You can activate/deactivate this per channel and it will only kick in in there is just one method available.
