### ISSUE TITLE
[Behat] Some scenarios for product variants and checkout fail after update of packages by composer

### ISSUE THREAD

**Issue by Tykzz** [Sylius/Sylius#7915]
Installing a package I've got automatic update of the following:

- twig/twig (to v1.33.0)
- symfony/symfony (to v3.2.7)
- phpunit/php-code-coverage (to 4.0.8)
- guzzlehttp/psr7 (to 1.4.2)

That caused 5 scenarios to fail:

- _Getting a hint when looking for product variants_ (4 scenarios) from `@managing_product_variants`
- _Successfully placing an order using custom locale_ from `@paying_for_order`

I'm not sure what these packages have to do with the errors but here is what I found while debugging:

In the tests for product variants the error concerns LS characters (U+2028) at the end of a few lines in the `Model.ProductVariant.yml` file.

As to the checkout scenario, it seems that e-mail address should be specified along with the address in `CheckoutAddressingContext`, method `iProceedSelectingShippingCountry` which is used by the step `I proceed through checkout process in the "French (France)" locale`.

**Comment by TheMadeleine** [comment]
#7916 solves the "weird chars" problem.
