### ISSUE TITLE
How to update product qty programmatically

### ISSUE THREAD

**Issue by alexdrupal** [Sylius/Sylius#7917]
Hello,

I'm doing QuickBooks integration. How do I update an available product qty. For example I receive from QB that we have 50 products I want to use something like `$product->setQty(50)`
Please, help.
Thanks!

**Comment by TheMadeleine** [comment]
What you need here is probably the `onHand` value of the `ProductVariant`, that is tracked in the inventory. 

Read more on inventory in Sylius [here](http://docs.sylius.org/en/latest/book/products/inventory.html).

**Comment by alexdrupal** [comment]
So the only thing I need to do is `$productVariant->setOnHand(50)`?

**Comment by pjedrzejewski** [comment]
@alexdrupal Yes! And flush the manager of course.

**Comment by pjedrzejewski** [comment]
Please reopen if still an issue. @TheMadeleine Maybe we should add this to http://docs.sylius.org/en/latest/book/products/inventory.html? Just example of setting the onHand.
