### ISSUE TITLE
Problem installing Sylius when using yarn run gulp

### ISSUE THREAD

**Issue by 4oXdev** [Sylius/Sylius#7919]
When i installing Sylius i had problem

$ yarn run gulp
yarn run v0.22.0
$ gulp 
[11:40:10] Using gulpfile /var/www/demo/www/sylius.demo.local/Gulpfile.js
[11:40:10] Starting 'admin'...
[11:40:10] Finished 'admin' after 12 ms
[11:40:10] Starting 'shop'...
[11:40:10] Finished 'shop' after 2.96 ms
[11:40:10] Starting 'default'...
[11:40:10] Finished 'default' after 8.07 μs
[gulp-chug] Gulpfile, Gulpfile.js, contents is empty. Reading directly from disk...
[gulp-chug] Spawning process /var/www/demo/www/sylius.demo.local/node_modules/gulp/bin/gulp.js with args /var/www/demo/www/sylius.demo.local/node_modules/gulp/bin/gulp.js --gulpfile Gulpfile.js default --rootPath ../../../../web/assets/ --nodeModulesPath ../../../../node_modules/ from directory /var/www/demo/www/sylius.demo.local/src/Sylius/Bundle/AdminBundle...
[gulp-chug] Gulpfile, Gulpfile.js, contents is empty. Reading directly from disk...
[gulp-chug] Spawning process /var/www/demo/www/sylius.demo.local/node_modules/gulp/bin/gulp.js with args /var/www/demo/www/sylius.demo.local/node_modules/gulp/bin/gulp.js --gulpfile Gulpfile.js default --rootPath ../../../../web/assets/ --nodeModulesPath ../../../../node_modules/ from directory /var/www/demo/www/sylius.demo.local/src/Sylius/Bundle/ShopBundle...
[gulp-chug] (src/Sylius/Bundle/AdminBundle/Gulpfile.js) fs.js:808
  return binding.readdir(pathModule._makeLong(path));
                 ^
Error: ENOENT: no such file or directory, scandir '/var/www/demo/www/sylius.demo.local/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:808:18)
    at Object.getInstalledBinaries (/var/www/demo/www/sylius.demo.local/node_modules/node-sass/lib/extensions.js:121:13)
    at foundBinariesList (/var/www/demo/www/sylius.demo.local/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/var/www/demo/www/sylius.demo.local/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/var/www/demo/www/sylius.demo.local/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/var/www/demo/www/sylius.demo.local/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/var/www/demo/www/sylius.demo.local/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Gulpfile /var/www/demo/www/sylius.demo.local/src/Sylius/Bundle/AdminBundle/Gulpfile.js exited with an error :(
error Command failed with exit code 1.

To resolve it i installed
yarn add node-sass

Perhaps need to change the dependencies?

**Comment by pjedrzejewski** [comment]
@4oXdev What is your node.js version?

**Comment by 4oXdev** [comment]
nodejs -v
v4.2.6
It's by default in ubuntu 16.04 LTS

**Comment by psren** [comment]
I had the same problem #8322 in a travis-run. I was not able to reproduce it on my box, but I used a workaround. I linked some more information on this issue as well.

**Comment by pjedrzejewski** [comment]
Please try with beta3 and reopen if still an issue, thanks!

**Comment by johnkrovitch** [comment]
Hi,

i just create a project with sylius, and I encounter the same problem. I have nodejs 4.2.6 and yarn 1.0.1 too.

yarn add node-sass did not solve the problem.

Any news on this ?


Thanks

**Comment by psihius** [comment]
@johnkrovitch you need nodejs 4.8.0+, sadly it's something like 4.6.x in Ubuntu 17.04, so you have to add and install from nodejs repository, it installs 6.x.x and yarn then works fine.

**Comment by johnkrovitch** [comment]
@psihius I had to run "yarn add node-sass" too, and it works, thanks.

**Comment by mtamazlicaru** [comment]
Hi guys, i have the same problem now, i am on sylius version 1.0.8, yarn version 1.3.2, node 6.10.3, i installed the node-sass too, but anyway, stuck with the error:
```php
...
[gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Gulpfile.js) [15:48:21] [gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Gulpfile.js) Starting 'shop-css'...
[gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js) [15:48:21] Starting 'admin-css'...
[gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Gulpfile.js) [15:48:21] [gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Gulpfile.js) Starting 'shop-img'...
[gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js) [15:48:21] [gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js) Starting 'admin-img'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Gulpfile /var/www/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js exited with an error :(
error Command failed with exit code 1.
...
```

**Comment by haalmaguer** [comment]
Node 9 same issue

**Comment by mtamazlicaru** [comment]
@haalmaguer i managed to solve the issue from my docker container, i installed also yarn 1.3.2 but everything works. Sylius version 1.0.8
