### ISSUE TITLE
Sylius Slack invitation link no longer works

### ISSUE THREAD

**Issue by javiereguiluz** [Sylius/Sylius#7922]
I know this is probably not the right place to report this, but I don't know where else I can report it.

---

On Symfony Slack, a user told us that `slackinvite.me/to/sylius-devs` is down. Indeed, `slackinvite.me` seems to be down, that's why we removed it for the Symfony Slack.

A simple alternative solution is to self-host an application like https://github.com/rauchg/slackin  but at the end we decided to use a "shared invite" which is a link with auto sign-up. The number of people it can use it is limited, but you can renew it. It should be available at `https://sylius-devs.slack.com/admin/shared_invites`

**Comment by pjedrzejewski** [comment]
Thank you Javier, I had some trouble setting up Slackin but I will try again soon. If it does not work out, I will check the shared invites.

Thanks for the tips, I will keep this open until it's resolved.

**Comment by javiereguiluz** [comment]
In case it helps you, these were the steps that I followed to setup Slackin on my personal Heroku account:

1) Visit https://heroku.com/deploy?template=https://github.com/rauchg/slackin/tree/master
2) Visit https://api.slack.com/custom-integrations/legacy-tokens and click the button to generate a token. (this URL is called "legacy tokens" ... but it's the "good token")
3) In the Heroku deployment, set these two variables:
   * SLACK_API_TOKEN is the token you generated in 2)
   * SLACK_SUBDOMAIN is `sylius-devs`

**Comment by pjedrzejewski** [comment]
Awesome, thank you so much Javier, I couldn't find the right token before. :D 🍺 

It's now available here: http://sylius.org/slack.
