### ISSUE TITLE
Wrong package name on 'How to create a plugin for Sylius?' page so instructions cannot be followed

### ISSUE THREAD

**Issue by nicanaca0** [Sylius/Sylius#7925]
On http://docs.sylius.org/en/latest/plugins/creating-plugin.html#create-project-using-composer the `composer create-project` fails due to the package not existing.

`composer create-project sylius/plugin-skeleton MyPlugin` gives the error `Could not find package sylius/plugin-skeleton with stability stable.`

I found this: https://github.com/Sylius/PluginSkeleton which has the correct command: `composer create-project sylius/bundle-skeleton -s dev MyPlugin`

**Comment by pjedrzejewski** [comment]
Should work now. :)

**Comment by pjedrzejewski** [comment]
Please reopen if still an issue.

**Comment by pjurasek** [comment]
I am not sure, but I got similar error on `composer create-project sylius/plugin-skeleton SyliusMyFirstPlugin`:
```bash
[InvalidArgumentException]                                                                                                                                 
Could not find package sylius/plugin-skeleton with stability stable in a version installable using your PHP version, PHP extensions and Composer version.
```

**Comment by olimination** [comment]
I'm facing the same issue and have opened a new issue in the appropriate Sylius/PluginSkeleton project: https://github.com/Sylius/PluginSkeleton/issues/297
