### ISSUE TITLE
Make BuildProductVariantFormSubscriber a service?

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#7932]
`BuildProductVariantFormSubscriber` is used on several locations in the admin around creating variants. It's rather hard to adjust things if you need to adjust a small thing in that subscriber. 

Basically it comes down to extending the form type loading it (or overwriting it), removing the previous subscriber, and adding your own subscriber in there. That's extending lots of things while injecting would make this more cleaner. 

Is there any reason not the make this subscriber injected into the constructor and therefor easier to inject another implementation? If so, I could file a PR. But first wanting to check it's not for a good reason this way.

**Comment by pjedrzejewski** [comment]
We wanted to avoid form event subscribers as services. Can you give an example of customization you need? Maybe there is another way.

**Comment by stefandoorn** [comment]
Yes. In my case I'm trying to mark an ProductOption as optional, and therefore I adjusted the variant generator to generate the following strategy:

Colors: 10 items, Sizes: 3 items, Materials (optional): 3 items.

Normal variant generator would generate 10 * 3 * 3 = 90 variants. 

Because I have one optional, this becomes: 10 * 3 * 3 + 10 * 3 = 120 variants.

The variant generator editing is quite easy. Afterwards I want to change all the forms in the admin to make sure it can handle optional items and leave out the ProductOption that was optional if it was also not set on the variant, e.g. by doing something like this:

```
<?php

namespace AppBundle\Form\EventSubscriber;

use AppBundle\Entity\Interfaces\ProductInterface;
use Sylius\Bundle\ProductBundle\Form\Type\ProductOptionValueCollectionType;
use Sylius\Component\Product\Model\ProductVariantInterface;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormFactoryInterface;

/**
 * @author Paweł Jędrzejewski <pawel@sylius.org>
 * @author Łukasz Chruściel <lukasz.chrusciel@lakion.com>
 */
final class BuildProductVariantFormSubscriber implements EventSubscriberInterface
{
    /**
     * @var FormFactoryInterface
     */
    private $factory;

    /**
     * @var bool
     */
    private $disabled;

    /**
     * @param FormFactoryInterface $factory
     * @param bool $disabled
     */
    public function __construct(FormFactoryInterface $factory, $disabled = false)
    {
        $this->factory = $factory;
        $this->disabled = $disabled;
    }

    /**
     * {@inheritdoc}
     */
    public static function getSubscribedEvents()
    {
        return [
            FormEvents::PRE_SET_DATA => 'preSetData',
        ];
    }

    /**
     * @param FormEvent $event
     */
    public function preSetData(FormEvent $event)
    {
        /** @var ProductVariantInterface $productVariant */
        $productVariant = $event->getData();
        $form = $event->getForm();

        if (null === $productVariant) {
            return;
        }

        /** @var ProductInterface $product */
        $product = $productVariant->getProduct();

        if (!$product->hasOptions()) {
            return;
        }

        $countOptionValues = count($productVariant->getOptionValues());
        $countOptions = count($product->getOptions());

        $optionsToSubmit = $countOptions !== $countOptionValues ? $product->getRequiredOptions() : $product->getOptions();

        $form->add($this->factory->createNamed(
            'optionValues',
            ProductOptionValueCollectionType::class,
            $productVariant->getOptionValues(),
            [
                'disabled' => $this->disabled,
                'options' => $optionsToSubmit,
                'auto_initialize' => false,
            ]
        ));
    }
}
```

So basically the change is in in here:

```
        $countOptionValues = count($productVariant->getOptionValues());
        $countOptions = count($product->getOptions());

        $optionsToSubmit = $countOptions !== $countOptionValues ? $product->getRequiredOptions() : $product->getOptions();

        $form->add($this->factory->createNamed(
            'optionValues',
            ProductOptionValueCollectionType::class,
            $productVariant->getOptionValues(),
            [
                'disabled' => $this->disabled,
                'options' => $optionsToSubmit,
                'auto_initialize' => false,
            ]
        ));
```

To make sure this Subscriber is used, I need to extend the form type, remove the original subscriber from it, and adding my own subscriber to it. Quite a lot of customisations for simply replacing a subscriber, but maybe I'm doing it not in an efficient way of course :)

**Comment by Beaudinn** [comment]
Exactly the same problem here..
