### ISSUE TITLE
Sylius blog text contrast too low

### ISSUE THREAD

**Issue by mestaritonttu** [Sylius/Sylius#7933]
http://sylius.org/blog/sylius-v1-0-0-beta2-now-available
Painfully low contrast.

See http://contrastrebellion.com/ if you don't understand the problem.

**Comment by psihius** [comment]
Have to agree. Reading it on any kind of mobile device is impossible without making your eyes go out of their eye sockets.

**Comment by pjedrzejewski** [comment]
Agree, we will be iterating on the website soon, so I will include this. Thanks for reporting!
