### ISSUE TITLE
[Sylius Beta.2] Problem accent in select attribute & email user check

### ISSUE THREAD

**Issue by lucassimonin** [Sylius/Sylius#7936]
hi,
If I put an accent in select attribute value I got this error & the error in the checkout/address : 

`Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to FOS\RestBundle\Controller\ExceptionController::__construct() must implement interface FOS\RestBundle\View\ViewHandlerInterface, none given, called in /app/var/cache/prod/classes.php on line 4218 in /app/vendor/friendsofsymfony/rest-bundle/Controller/ExceptionController.php:43 Stack trace: #0 /app/var/cache/prod/classes.php(4218): FOS\RestBundle\Controller\ExceptionController->__construct() #1 /app/var/cache/prod/classes.php(4908): Symfony\Component\HttpKernel\Controller\ControllerResolver->instantiateController('FOS\\RestBundle\\...') #2 /app/var/cache/prod/classes.php(4214): Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver->instantiateController('FOS\\RestBundle\\...') #3 /app/var/cache/prod/classes.php(4901): Symfony\Component\HttpKernel\Controller\ControllerResolver->createController('FOS\\RestBundle\\...') #4 /app/var/cache/prod/classes.php(4155): Symfony\Bundle\FrameworkBundle\Controller\Controlle in /app/vendor/friendsofsymfony/rest-bundle/Controller/ExceptionController.php on line 43`

(tested on my develop and your demo website)

**Comment by pjedrzejewski** [comment]
Thanks for reporting!

**Comment by lucassimonin** [comment]
No problem :)

**Comment by lucassimonin** [comment]
It's possible to authorize apostrophe too ?
Because I have some brand like this : **O'C**lock Brewing
And it isn't accepted.

Thanks

**Comment by pamil** [comment]
More info in #8111, @stefandoorn's trying to fix this one in #8134 :)
