### ISSUE TITLE
How to add a custom promotion action?

### ISSUE THREAD

**Issue by ascameron1** [Sylius/Sylius#7937]
Hi,

I have followed the documentation exactly to add custom promotion action.

I am getting this error:

`Promotion action needs to implement "Sylius\Component\Promotion\Action\PromotionActionCommandInterface", "AppBundle\Promotion\Action\CheapestProductDiscountPromotionActionCommand" given.`

in vendor/sylius/sylius/src/Sylius/Component/Registry/ServiceRegistry.php at line 72:

`        }
        if (!in_array($this->interface, class_implements($service), true)) {
            throw new \InvalidArgumentException(
                sprintf('%s needs to implement "%s", "%s" given.', ucfirst($this->context), $this->interface, get_class($service))
            );
        }`

The documentation makes no mention of implementing this class. If i do indeed implement this class, i get this error?

`Could not load type "AppBundle\Promotion\Action\CheapestProductDiscountPromotionActionCommand"`

Is the documentation outdated? I have not changed anything outlined in the cookbook guide [here](http://docs.sylius.org/en/latest/cookbook/custom-promotion-action.html).

Kind regards

**Comment by ascameron1** [comment]
Has anyone managed to look at this issue yet? The promotion I'm trying to create is a 5 for 4 offer. So for every 5 products bought, a discount of one product will be applied. Ive tried to implement this with the promotion rules and actions provided but have had no luck.

Kind regards

**Comment by lchrusciel** [comment]
It depends. Docs don't mention about this interface, but as was written, you should extend `DiscountPromotionActionCommand` which implements this interface. Maybe we should add this information also as a warning. 

According to your problem, `CheapestProductDiscountPromotionActionCommand` could be a good solution for you. But the `Cart quantity` rule should be a good choice. A little bit harder it would be if you want to have this promotion repeatable(for each 4 items 5th should be discounted).

**Comment by ascameron1** [comment]
Hi,

My class implements `ChannelBasedPromotionActionCommandInterface` which implements `PromotionActionCommandInterface`. I got this from looking at `FixedDiscountPromotionActionCommand.php`.

Yea this promotion would need to be repeated which is why I opted for a custom promotion action. 

When I implement `ChannelBasedPromotionActionCommandInterface`, the error I'm getting is in FormRegistry. 

     if (class_exists($name) && in_array('Symfony\Component\Form\FormTypeInterface', class_implements($name))) {
        $type = new $name();
     } else {
        throw new InvalidArgumentException(sprintf('Could not load type "%s"', $name));
     }

From what i can gather, it is checking if `CheapestProductDiscountPromotionActionCommand.php` implements `FormTypeInterface` but Im not entirely sure why? I thought `CheapestProductDiscountConfigurationType` extends `AbstractType` which `implements FormTypeInterface`? Maybe Im wrong but i would of thought that `CheapestProductDiscountPromotionActionCommand.php` should no be going through the above code block?

**Comment by lchrusciel** [comment]
Did you use follow [this step](http://docs.sylius.org/en/latest/cookbook/custom-promotion-action.html#register-the-action-as-a-service) exactly? The tag has a key `form-type` -> `form-type: AppBundle\Form\Type\Action\CheapestProductDiscountConfigurationType`. Did you specify this type there? 

Anyway, it seems, that its some problem with your configuration rather than Sylius implementation. Can we move with resolving this solution to StackOverflow to keep this thread clean?

@ascameron1 will you open a PR with warning about this class?

**Comment by ascameron1** [comment]
@lchrusciel 

Yes i followed the example exactly... i even copied and pasted the code direct from the documentation. Here is a my code from services.yml:

    app.form.type.promotion_action.cheapest_product_discount_configuration:
        class: AppBundle\Form\Type\Action\CheapestProductDiscountConfigurationType
        tags:
            - { name: form.type }

    app.promotion_action.cheapest_product_discount:
        class: AppBundle\Promotion\Action\CheapestProductDiscountPromotionActionCommand
        arguments: ['@sylius.proportional_integer_distributor', '@sylius.promotion.units_promotion_adjustments_applicator']
        tags:
            - { name: sylius.promotion_action, type: cheapest_product_discount, label: Cheapest product discount }

And yes I can open a PR :)

**Comment by lchrusciel** [comment]
Can you provide exact error with stack trace but on SO, please?

**Comment by ascameron1** [comment]
@lchrusciel 

I have put my stack trace [here](http://stackoverflow.com/questions/43516523/sylius-how-to-add-a-custom-promotion-action).

Kind regards

**Comment by ascameron1** [comment]
@lchrusciel 

I added to this SO, did you manage to take a look at it?

**Comment by lchrusciel** [comment]
The docs are outdated for sure, but I don't have time to look deeper into your code. I will leave this issue open to not forget about it, but you have to wait for somebody to help you or handle it by your own. 

Nevertheless, it seems that something is wrong with your config. There are a few working promotions in Sylius by default.

**Comment by ascameron1** [comment]
@lchrusciel Ok buddy, no problem. 

Thank you for your help 😄

**Comment by ascameron1** [comment]
I found the issue in `CheapestProductDiscountPromotionActionCommand`. 

In the documentation:

    /**
        * {@inheritdoc}
    */
    public function getConfigurationFormType()
    {
        return CheapestProductDiscountPromotionActionCommand::class;
    }

However this should be:

     /**
        * {@inheritdoc}
    */
    public function getConfigurationFormType()
    {
        return CheapestProductDiscountConfigurationType::class;
    }

This is why the code checked that `CheapestProductDiscountPromotionActionCommand.php` implements `FormTypeInterface`.

Ive managed to add my custom action and its working perfectly. There is a couple of issues with documentation but the implementation works :).

**Comment by lchrusciel** [comment]
THB this function should not be needed at all. The information about form type is handled on the promotion tag. The documentation is outdated for sure. Are you willing to open a PR with fixes to documentation?
