### ISSUE TITLE
Cannot edit taxons

### ISSUE THREAD

**Issue by shaunroot** [Sylius/Sylius#7940]
This is a fresh install.  

http://localhost/app_dev.php/admin/taxons/1/edit

    Variable "remote_url" does not exist.
    500 Internal Server Error - Twig_Error_Runtime in vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig at line 200

I also cannot create a new product. I'm not sure if this is related, so I will wait to open a new issue.

http://localhost/app_dev.php/admin/products/new/simple

    An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "sylius_admin_ajax_taxon_index" as such route does not exist.").

**Comment by shaunroot** [comment]
This happens when you override views using values in beta1 that are not in beta2. Recreating my view from the new view in vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Resources/views fixed the problem.

**Comment by smanezItec** [comment]
I have the same problem. I have a Model with new fields for Taxon and a view _form.html.twig with these fields added. Please help.
