### ISSUE TITLE
[beta2] post migration feedback

### ISSUE THREAD

**Issue by bruno-ds** [Sylius/Sylius#7942]
Hello,

I'm in the process of migrating to the beta2 so I write here every feedback that I may have, mostly because their are small detail not documented in the (great) upgrade.md, please tell me if you don't want them or if you prefer another way of giving them to you.

# payment-methods
on the display of : `/app_dev.php/admin/payment-methods/`

> “
> An exception has been thrown during the rendering of a template ("PropertyAccessor requires a graph of objects or arrays to operate on, but it found type "NULL" while trying to traverse path "gatewayConfig.gatewayName" at property "gatewayName".").
> 500 Internal Server Error - Twig_Error_Runtime
> 1 linked Exception: UnexpectedTypeException »
> ”
> [2/2] Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("PropertyAccessor requires a graph of objects or arrays to operate on, but it found type "NULL" while trying to traverse path "gatewayConfig.gatewayName" at property "gatewayName".").   +
> [1/2] UnexpectedTypeException: PropertyAccessor requires a graph of objects or arrays to operate on, but it found type "NULL" while trying to traverse path "gatewayConfig.gatewayName" at property "gatewayName".   

=> you need to clear the payment table and add it all by hand, this is not in the upgrade.md.

# resource variable in admin templates
in the admin templates,  the variable  `resource` do not exist anymore, it is replaced either by `options.foo_bar`or `foo_bar`, `foo_bar` beeing the name of the entity, snake_cased.

# extending menu in admin
you do no more generate the HTML of the menu by hand, so instead of ovewriting `*/_menu.html.twig` and `*/_tabs.html.twig`, you have to create a a service who alter a knpMenu, for example 
```yaml
  app.listener.admin.product_variant.form.menu_builder:
      class: AppBundle\Menu\AdminProductVariantFormMenuListener
      tags:
          - { name: kernel.event_listener, event: sylius.menu.admin.product_variant.form, method: addItems }
```

# change in route name
`sylius_shop_cart_item_remove` as been renamed to `sylius_shop_ajax_cart_item_remove`, this is not the only one.

# product images
instead of a code, they have a Type, and they can be associated to a vriant (not working on my installation : in the product's admin panel the list of variant is empty, I will look a it later)

# in the cart, the removal of a product do not work 
a loader is shown bu no http query is done, I do not find any hint on this 
suspecting a missing JS, I tried without success : 
```
bin/console assets:install --symlink
bin/console sylius:install:assets
gulp
```
I'm pretty sure that I missed an update of a javascript, but can't figure out how to update it 
My bad : varnish was the ultimate problem : it did not cleared the cache. But I'm pretty sure that a `gulp` was needed in order to have a correct file, you should mention it.

# taxon list is empty in the product admin panel
on the Taxonomy panel of the product's admin, the main taxon dropdown is empty, and there is no list of taxon in the "Product taxon" section.
I'm pretty sure that I missed an update of a javascript, but can't figure out how to update it bis
after comparing with the sylius demo, I see that this part is now rendered using javascript, so I guess that I miss some new JS introduced in the beta 2.

Edit : when I launched `gulp` for the third time, it worked. I can't understand why it didn't worked.... If I'm correct and wee should launch gulp, you should add this step in the UPGRADE.md file

# admin's zone edition take a lot of ram
I sell worldwide, rendering `/admin/zones/1/edit` use more than 128Mo, (so I can't use the admin panel for zone editing)

> Whoops, looks like something went wrong.
> 
> 1/1
> OutOfMemoryException in FormDataCollector.php line 272:
> Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 2097152 bytes)
> in FormDataCollector.php line 272

# OptimisticLock on the variant
it seem that you've added an optimistic lock on the product variant, in order to have it working, `/var/www/sylius/app/Resources/SyliusAdminBundle/views/ProductVariant/Tab/_details.html.twig` have to contain this : `{{ form_row(form.version) }}` 
(this one got me for a long time since I supposed that it was my WIP that was in fault)

**Comment by bruno-ds** [comment]
I just added "OptimisticLock on the variant" in the above listing

**Comment by pjedrzejewski** [comment]
Thanks @bruno-ds! We will need to split that issue into separate tickets, otherwise it will be hard to work on them. If you can submit some PRs to fix smaller issues or update the upgrade file, that would be much appreciated!
