### ISSUE TITLE
[Address] The province selection never shows a validation error

### ISSUE THREAD

**Issue by inssein** [Sylius/Sylius#7944]
I tried to look into this briefly, and I'm not sure where this is breaking.

If you fill out the shipping address form, and don't enter a province (easy to miss since it is dynamically loaded), you come back to the same page with no validation errors visible.

Edit: To re-iterate, the validation constraint does fail, its just the display of the form errors.

**Comment by Zales0123** [comment]
I've just checked it out and it seems to work - not perfectly, but the validation error is displayed :)

<img width="785" alt="zrzut ekranu 2019-03-1 o 12 21 15" src="https://user-images.githubusercontent.com/6212718/53635157-86cf6380-3c1c-11e9-9094-c6270f4d641c.png">
