### ISSUE TITLE
Stripe bug in beta2, completed payment is redirected and asks for payment again

### ISSUE THREAD

**Issue by Richard87** [Sylius/Sylius#7946]
Hi,

I just installed Sylius beta2 and testing out Stripe (set up with test credentials)

When I come to the payment site, I get the payment form, and on a successful payment, I get  redirected to the same place, with a new popup asking for the payment over again...

Video showing the bug:
https://drive.google.com/file/d/0BzvHB2I-HikSUmRfWlBtOURvSkE/view

Richard

**Comment by GSadee** [comment]
Hi @Richard87, I was trying to recreate this issue on current master, but without success. Please, reopen an issue if you still have problem with it.
