### ISSUE TITLE
I don't want permit users anonymous pay products

### ISSUE THREAD

**Issue by Chrysweel** [Sylius/Sylius#7947]
I am upgrading to Sylius version v1.0.0-alpha.2 and the anonymous users can pay for the products. 
My project is a suscriptions model , and I need to sign in to complete the payment process. Also I need remove the product address and delivery steps. I dont send prodycts, I sell virtual products.

In Sylius version 0.18, the user must log in to the second step and Sylius auto-redirect to cart again.

Now is it possible configure this functionality ? Is it mandatory the deliver step? Can I include login in some step of pay and redirect to cart ?

Thanks in advance

**Comment by pjedrzejewski** [comment]
@TheMadeleine I think we need a cookbook article: "How to disable guest checkout?". The solution is simple, reconfigure ACL in security.yml, to require login for path ``/checkout`` and that should do the trick. :)

**Comment by Chrysweel** [comment]
Hello @pjedrzejewski thanks for reply.

With this solution, the login works correctly, and sylius redirect to cart steps .. but the problem is with register ... the user lost in the process ...

Are there any solution?

Thanks!

**Comment by lchrusciel** [comment]
Do you mean that the cart is lost when the user logs in? 

Anyway, this question is probably more suitable for StackOverflow.

**Comment by Chrysweel** [comment]
Hello @lchrusciel.

I did not say the cart is lost when the user logs in, sorry for my english.

With login, all process work correctly, (the user is redirected to login, login success, and redirect to cart steps) the problem is the following:

The user anonymous init car steps, to continue the user anonymous is necesary register to finish proccess, the user to register in the project, but dont redirect to continue cart steps ... so user is lost in the process, is necesary click in button of cart to continue process.

I remember that in sylius 0.18, the user can login and register in medium of car steps and continue the process transparently

**Comment by lchrusciel** [comment]
Adding this line `- { path: "%sylius.security.shop_regex%/checkout", role: ROLE_USER }` to your access control section in `security.yml` will resolve your problem. Customer cannot access checkout without login and he is redirected to cart if successful.
```yml
# app/config/security.yml

security:
    # ....
    access_control:
        # ...
        - { path: "%sylius.security.shop_regex%/checkout", role: ROLE_USER }
```

**Comment by TheMadeleine** [comment]
@lchrusciel why closing? Should stay as a docs request issue.

**Comment by lchrusciel** [comment]
Of course. my fault.

**Comment by Chrysweel** [comment]
@lchrusciel 
Does your solution work when the user must register to pay? This solution work with login, but and with register ?

I do not think we understand each other.
The situation is:
- User anonymous want pay.
- The user must login or **register**
- When user **registered success**, the project must redirect to process of payment to finish payment.

**Comment by TheMadeleine** [comment]
Hi @Chrysweel!

To achieve what you are requesting here, you would need to turn off the email verification feature. 

It is currently impossible to redirect user to checkout after registration, since he has to verify his account (click a link sent via email) and then log in. 

It was probably possible before in 0.18 because there was not email verification.

**Comment by Chrysweel** [comment]
Correct @TheMadeleine the redirect only from /checkout.  :)

Yes in Sylius 0.18 this funcionality was possible. Futhermore because the register form was incrusted in cart steps. i.e there was two register, the main register and one page with register and login embeded into cart steps..

I would like to keep the same logic, so as not to take out the user out of the buying process.

Thanks for reply.
