### ISSUE TITLE
[ResourceBundle] Exceptions handling during deletion of resources

### ISSUE THREAD

**Issue by ste93cry** [Sylius/Sylius#7948]
PR #7425 added a `UpdateHandlingException` exception class to handle all errors during the update of a resource and this prevents error 500 to be shown if something goes wrong. The same should be done for deletion of resources: for example, if there is a constraint on a foreign key and you try to delete something an error page is displayed. Are you willing to accept a PR to fix the issue?

**Comment by pjedrzejewski** [comment]
@ste93cry Absolutely, we will be happy to review & merge such PR. 👍

**Comment by pjedrzejewski** [comment]
@ste93cry Hi, will you have some time to implement this? Would be great to have it before the stable release.

**Comment by ste93cry** [comment]
Sorry I forgot about this issue. I prepared a PR, I never used PHPSpec so I'm not sure about the tests
