### ISSUE TITLE
Double translations for button in taxonomy tree

### ISSUE THREAD

**Issue by damian-kociuba** [Sylius/Sylius#7949]
In the file `Sylius/Bundle/AdminBundle/Resources/views/Taxon/_treeWithButtons.html.twig`, line 18:

```
{{ buttons.create(path('sylius_admin_taxon_create_for_parent', { 'id': taxon.id }), 'sylius.ui.add'|trans) }}
```
there are twice translated messages. Firstly message is translated in mentioned file, secondly in default button macro (`Sylius/Bundle/UiBundle/Resources/views/Macro/buttons.html.twig`). The result of this issue is a warning that cannot find translation for `Add` (or `Dodaj` in Polish).

**Comment by lchrusciel** [comment]
Are you willing to open a PR with a fix?
