### ISSUE TITLE
Data loss and tree corruption on taxon deletion

### ISSUE THREAD

**Issue by DmitriyTrt** [Sylius/Sylius#7950]
It may be related to #3855. Nobody reacted to [the comment](https://github.com/Sylius/Sylius/issues/3855#issuecomment-285463595) in more than a month, so let's make it a separate task.

Steps to reproduce:
- Make a new root taxon.
- Add root child 1
- Add root child 2
- Add child of the child 1
- Delete child 1

Child 2 is also deleted.

After some taxons deletions we also got a corrupted tree with taxons having `left`, `right` and `level` properties messed up, but I can't reliably reproduce it yet. This is a quite critical issue, as it results in unexpected data loss. Reproducible on a fresh installation of Sylius v1.0.0-beta.2, as well as on beta.1

**Comment by lchrusciel** [comment]
Thanks for reporting this in the new issue. 
Can you open a PR with behat scenario for that? It will be a good starting point for others to fix this.

**Comment by bitbager** [comment]
@pamil, Could it be related to the cascade options in https://github.com/Sylius/Sylius/blob/ded40eb651bee57a1683cd5ad7fdb4a75c510ee7/src/Sylius/Bundle/TaxonomyBundle/Resources/config/doctrine/model/Taxon.orm.xml#L29?

I think that this issue may also appear for both neighbor taxons (left, right).

**Comment by pamil** [comment]
@bitbager close, in fact it was related to Doctrine's cascade delete on children.

**Comment by bitbager** [comment]
@pamil, sorry for not closing the issue myself, but suggesting the solution was the only thing I could have done yesterday 😢 . Hope it helped a little bit.

**Comment by stefandoorn** [comment]
I'm experiencing this same issue on a site currently, not sure what caused it (Sylius 1.x) where the tree got corrupted. Is there a way to restore it somehow?
