### ISSUE TITLE
[beta2] Locale system broken

### ISSUE THREAD

**Issue by mikelros** [Sylius/Sylius#7956]
After updating my Sylius test project to beta2, I have found that the internationalization isn't working anymore. I'm not 100% sure if beta2 broke it or it was just me so I'd appreciate if someone else checks it.
Repro:
Having two languages available in a channel and one as the default isn't letting users in the shop to swap to the non-default language. The URL adds the "?_locale=en_US", but does nothing after.

**Comment by lchrusciel** [comment]
Shop routes should be prefixed with the locale. There is information about it in [UPGRADE file](https://github.com/Sylius/Sylius/blob/master/UPGRADE.md#application).

**Comment by mikelros** [comment]
Oh I see, thank you. I didn't know about that.
