### ISSUE TITLE
[PromotionBundle] Unable to have a promotion with multiple shipping countries

### ISSUE THREAD

**Issue by psihius** [Sylius/Sylius#7962]
The rule checker `Sylius\Component\Promotion\Checker\Eligibility\PromotionRulesEligibilityChecker` when checking for the eligibility, is not able to check for multiple countries to apply the promotion.
This is due to the fact, that a single "not eligible" for the list of rules completely fails promotion eligibility. 

To make it work for me, I've took the easier road of just overriding the class (code below), but I think in this case the ShippingCountryRuleChecker should be updated so it can contain the list of rules and in admin panel the selector should be "multiple items". I would also add a validation rule when creating promotions so it warns people when they add multiple entries of the same rule, because right now if any single rule is "failing" the eligibility, it all fails and this has quite a "wtf?!" on the people who administrate the stuff.
```php
public function isEligible(PromotionSubjectInterface $promotionSubject, PromotionInterface $promotion)
    {
        if (!$promotion->hasRules()) {
            return true;
        }

        $shippingCountry = null;
        foreach ($promotion->getRules() as $rule) {
            if ($rule->getType() === ShippingCountryRuleChecker::TYPE) {
                if ($shippingCountry !== true) {
                    if ($this->isEligibleToRule($promotionSubject, $rule)) {
                        $shippingCountry = true;
                    } else {
                        $shippingCountry = false;
                    }
                }
            } else {
                if (!$this->isEligibleToRule($promotionSubject, $rule)) {
                    return false;
                }
            }
        }

        if (!is_null($shippingCountry)) {
            return $shippingCountry & true;
        } else {
            return true;
        }

    }
```

**Comment by psihius** [comment]
Updated my solution as it had a bug. But all in all this is running in production since april and the logic is sound and works as expected.

**Comment by lchrusciel** [comment]
It's a pretty old issue, but still, I can give a little comment on it. The thing is, that our rule checkers is using `AND` logic operand for all rules. And we did it on purpose because handling `OR` and `AND` would be problematic. So the good solution for that would be to create a new promotion rule `OneOfShippingCountries` and implement a custom `isEligible` rule there. 

Probably we should put more stress on this in our documentation.
