### ISSUE TITLE
PayPal Express Checkout relies on deprecated NVP API

### ISSUE THREAD

**Issue by mbabker** [Sylius/Sylius#7967]
As of January 1, 2017, PayPal has deprecated the NVP/SOAP APIs for PayPal Express and recommends an integration based on the REST API instead.

It would possibly be good to add a second PayPal Express Checkout option using the newer architecture.  Since this uses the REST API, Payum should already support the required server setup, so this probably would only involve setting up a new form type for the payment gateway config and creating Payum Action classes as needed.

**Comment by Takeno** [comment]
If anybody needs, here is the guide to request API credentials for Paypal Express Checkout:
https://developer.paypal.com/docs/classic/api/apiCredentials/#create-an-api-signature

**Comment by WaleedaliAjeebi** [comment]
W506101w@gmail.com
