### ISSUE TITLE
[ProductBundle] No way to make ProductImage translatable

### ISSUE THREAD

**Issue by mrjingles** [Sylius/Sylius#7968]
For me there is no way to extend the ProductImage. I tried to overwrite it for adding translatable name an slug. But when I want to overwrite the models class, it's not part of `sylius_product configuration`. Instead I have to overwrite the parameter `sylius.model.product_image.class` which results in "The table with name 'my_app.sylius_product_image' already exists." on doctrine migration.

I am not sure if it is a bug, but it seems to me like a design failure. ^^

Thanx in advance for your feedback.

**Comment by mrjingles** [comment]
`ProductImage.orm.yml` with:
```AppBundle\Entity\ProductImage:
    type: mappedSuperclass
    table: sylius_product_image
```

works for me.

But I ran into another error. Seems that the translation table is not joined correctly.

`An exception occurred while executing 'SELECT t1.type AS type_2, t1.path AS path_3, t1.id AS id_4, t1.owner_id AS owner_id_5 FROM sylius_product_image t1 WHERE t0.owner_id = ?' with params [22]:`

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.owner_id' in 'where clause'`

**Comment by mrjingles** [comment]
I created a more detailed description on [stackoverflow](http://stackoverflow.com/questions/43615182/making-sylius-productimage-translatable).

**Comment by pamil** [comment]
@mrjingles can you try replacing `type: entity` with `type: mappedSuperclass` in your mapping?

**Comment by mrjingles** [comment]
Hi @pamil, I tried that, cleared cache - but still the same error.

**Comment by ylastapis** [comment]
@mrjingles To have your own ProductImage class, you need to extend sylius_core config point like:

```
sylius_core:
    resources:
        product_image:
            classes:
                model: AppBundle\Entity\ProductImage
```
But to make it translatable, I can't tell. I completed to StackOverflow ticket about that.

**Comment by mrjingles** [comment]
@ylastapis Thx for your help. Error is gone, but got next one. See [stackoverflow](http://stackoverflow.com/questions/43615182/making-sylius-productimage-translatable) for details.
