### ISSUE TITLE
Where to find Documentation for 0.17

### ISSUE THREAD

**Issue by BNEP** [Sylius/Sylius#7969]
Hello,
because of the massive changes we where not able to redesign our whole project, so unfortunately we have to stay with 0.17. Now i cannot find the Docs for 0.17! Where is it?
Regards

**Comment by pjedrzejewski** [comment]
0.17 was pre-alpha version and is no longer supported. For such old projects we recommend migrating to beta2 by migrating the custom functionality to plugins (or using existing plugins). There is no other way unfortunately, there were a lot of changes since 0.17.
