### ISSUE TITLE
[ResourceBundle] Missing doc configuration for getting started with an API

### ISSUE THREAD

**Issue by bpolaszek** [Sylius/Sylius#7987]
Hi there,

When using **SyliusResourceBundle** as a standalone and trying to expose a REST API:
* **FOSRestBundle** is not configured by default. This prevents enabling content-negotiation and leads to a "template not found" exception when calling a resource endpoint with `Accept: application/json` header.
* No documentation is provided to get an accurate out-of-the-box working application. So I tried to configure **FOSRestBundle** by myself, but the returned JSON does not show my entities (only the pager).

Example response:
```json
# http://localhost:8000/authors
{
  "page": 1,
  "limit": 10,
  "pages": 1,
  "total": 2
}
```

instead of:

```json
# http://localhost:8000/authors
{
  "page": 1,
  "limit": 10,
  "pages": 1,
  "total": 2,
  "_links": {
    "self": {
      "href": "/authors?page=1&limit=10"
    },
    "first": {
      "href": "/authors?page=1&limit=10"
    },
    "last": {
      "href": "/authors?page=1&limit=10"
    }
  },
  "_embedded": {
    "items": [
      {
        "id": 1,
        "name": "Stephen King"
      },
      {
        "id": 1,
        "name": "J.K. Rowling"
      }
    ]
  }
}
```

Try my [sample app](https://github.com/bpolaszek/SyliusResourceBundleExample) to reproduce the bug.

**Comment by bendavies** [comment]
I run ResourceBundle standalone so thought id take a look. good job with the sample app.

1. you've not loaded `BazingaHateoasBundle` in `AppKernel`
2. you have no serialization setup config setup for your entities

**Comment by lchrusciel** [comment]
@bpolaszek you can take a look into [Lakion/Lionframe](https://github.com/Lakion/Lionframe/tree/master/src/DemoBundle) project to see a demo app of stand-alone resource bundle usage. 
But feel free to post here any problems with API documentation. I will try to take a look into these problems in nearest days. Together with #7976 #7951 and your previous issue #7986
