### ISSUE TITLE
Disabling API cookbook instructions results in error

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#7991]
I'm following very strict the following guide: http://docs.sylius.org/en/latest/cookbook/disabling-shop-admin-api.html#how-to-disable-sylius-api (on beta-2).

It results in an array: 

```
InvalidConfigurationException in SecurityExtension.php line 481:
No authentication listener registered for firewall "api".
```

Then I removed that `api:` line, as it seems obsolete to me in `security.yml`.

Results in another error:

```
InvalidConfigurationException in ArrayNode.php line 240:
The child node "db_driver" at path "fos_oauth_server" must be configured.
```

**Comment by Cathmor** [comment]
I ran into this error too. I did not dig or try to figure out the issue or why it's it's happening but was able to fix by commenting out the FOSOAuthServerBundle().

    new \Sylius\Bundle\AdminBundle\SyliusAdminBundle(),
    new \Sylius\Bundle\ShopBundle\SyliusShopBundle(),
    // new \FOS\OAuthServerBundle\FOSOAuthServerBundle(), // Required by SyliusApiBundle
    // new \Sylius\Bundle\AdminApiBundle\SyliusAdminApiBundle(),
    new \AppBundle\AppBundle(),

I'm working on other things and didn't need the api and have yet to find an issue with disabling that bundle and using the admin and shop bundle.

**Comment by stefandoorn** [comment]
Can confirm @Cathmor's solution works :)
