### ISSUE TITLE
Extended product, pass repository to resourcesCollectionProvider

### ISSUE THREAD

**Issue by craphunter** [Sylius/Sylius#7994]
I extended the Product.php from the core of sylius. I added a field 'deallerId'. I also extended a repository. 

From the docs I can now do a query that is working. I know sylius is doing everything with grid. I don't want to customize the twig/grid. So how can I render the Product/index.twig.html of sylius with the extended repository (new query) with the resourcesCollectionProvider().

        $configuration = $this->requestConfigurationFactory->create($this->metadata, $request);

        $this->isGrantedOr403($configuration, ResourceActions::INDEX);

        $productRepository = $this->container->get('sylius.repository.product');

        $product = $productRepository->findByOnHand($dealerId);
        //IMPORT!!!
        //put $product in $resources as product!!!
        //IMPORT!!!
        $resources = $this->resourcesCollectionProvider->get($configuration, $this->repository);

        $view = View::create($resources);

        if ($configuration->isHtmlRequest()) {
            .....

I miss this in the docs? Or you can not do this?

**Comment by pjedrzejewski** [comment]
Please join our Slack and describe your use-case, because we should start from the problem you are trying to solve, what you pasted is not a good way.
