### ISSUE TITLE
Sylius:install hanged

### ISSUE THREAD

**Issue by Alcondez** [Sylius/Sylius#8005]
I am trying to set up a new sylius project following these steps:

$ composer create-project -s beta sylius/sylius-standard project 
$ cd project 
$ yarn install
$ yarn run gulp
$ bin/console sylius:install
$ bin/console server:start
$ open http://127.0.0.1:8000

It all goes well until the bin/console sylius:install, it just hangs, no error message, prompt just keep blinking.  Tried leaving it for a while and nothing happened. Any ideas of what may be causing this?

Some details about my setup:

Ubuntu 16.04 (Pretty much fresh install)
PHP 5.6.30-10
Postgres 9.5

As a side note, I do have an older version of sylius running locally with no problems.
![screenshot](https://cloud.githubusercontent.com/assets/8955829/25551917/00ab426a-2c5b-11e7-98e8-ef87f75bfd39.png)

**Comment by maxpaynestory** [comment]
Does it also stuck if you try

bin/console sylius:install:check-requirements

**Comment by Alcondez** [comment]
Yes, I also tried running the commands separately.  Same result.

**Comment by maxpaynestory** [comment]
Could you please remove vendor folder and then run composer install
Check if all dependencies are properly downloaded by composer

**Comment by Alcondez** [comment]
Deleted vendor folder and composer install ran without errros but the problem persists.

**Comment by pjedrzejewski** [comment]
Is it still an issue? Please reopen then. Thanks!
