### ISSUE TITLE
irritating order count message if customer has cancelled orders

### ISSUE THREAD

**Issue by elmariachi111** [Sylius/Sylius#8008]
If a customer cancels an order the backend (sylius_admin_customer_show) says: "This customer has not placed any orders yet" which is not exactly true: the customer placed an order but it's cancelled :) #xberghackathon

**Comment by bricelalu** [comment]
Hi,

I really want to fix this one for my first contribution.

After investigating I found this in CoreBundle\Doctrine\ORM\OrderRepository:
`/**
     * {@inheritdoc}
     */
    public function findForCustomerStatistics(CustomerInterface $customer)
    {
        return $this->createByCustomerIdQueryBuilder($customer->getId())
            ->andWhere('o.state NOT IN (:states)')
            ->setParameter('states', [OrderInterface::STATE_CART, OrderInterface::STATE_CANCELLED])
            ->getQuery()
            ->getResult()
        ;
    }`

findForCustomerStatistics returns empty in case order has been canceled. Is it ok if I change the where condition?

**Comment by bricelalu** [comment]
@elmariachi111 Maybe I can only change the message? and don't change the findForCustomerStatistics behavior?

**Comment by elmariachi111** [comment]
Hey @bricelalu, good that you stumbled upon that issue. I'm currently not working on this project, please mention another contributor :) Cheers
