### ISSUE TITLE
cannot run gulp during standard installation from installation page

### ISSUE THREAD

**Issue by ravjanisz** [Sylius/Sylius#8009]
yarn run v0.22.0
$ gulp
[20:29:03] Using gulpfile /public_html/shop/Gulpfile.js
[20:29:03] Starting 'admin'...
[20:29:03] Finished 'admin' after 7.79 ms
[20:29:03] Starting 'shop'...
[20:29:03] Finished 'shop' after 1.52 ms
[20:29:03] Starting 'default'...
[20:29:03] Finished 'default' after 10 μs
[gulp-chug] Gulpfile, Gulpfile.js, contents is empty. Reading directly from disk...
[gulp-chug] Spawning process /public_html/shop/node_modules/gulp/bin/gulp.js with args /public_html/shop/node_modules/gulp/bin/gulp.js --gulpfile Gulpfile.js default --rootPath ../../../../../../../web/assets/ --nodeModulesPath ../../../../../../../node_modules/ from directory /public_html/shop/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle...
[gulp-chug] Gulpfile, Gulpfile.js, contents is empty. Reading directly from disk...
[gulp-chug] Spawning process /public_html/shop/node_modules/gulp/bin/gulp.js with args /public_html/shop/node_modules/gulp/bin/gulp.js --gulpfile Gulpfile.js default --rootPath ../../../../../../../web/assets/ --nodeModulesPath ../../../../../../../node_modules/ from directory /public_html/shop/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle...
[gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js) [20:29:03] [gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js) Using gulpfile /public_html/shop/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js
[gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js) [20:29:03] [gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js) Starting 'admin-js'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Gulpfile /public_html/shop/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js exited with an error :(
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

it's doesn't matter is this yarn or gulp and is this prod or dev environment

i found similar problems on stackoverflow, but no resolution:
http://stackoverflow.com/questions/39019290/sylius-standard-admin-panel-no-css-js
http://stackoverflow.com/questions/40288101/sylius-no-css-and-images-nothing-in-web-assets-directory

it can be server problem, but i don know too much yarn and gulp and can't handle with this alone

**Comment by maxpaynestory** [comment]
What is the version of Nodejs on your server?

**Comment by ravjanisz** [comment]
node --version
v6.10.2

**Comment by maxpaynestory** [comment]
Have you tried with npm?

**Comment by ravjanisz** [comment]
yes, same effect

**Comment by maxpaynestory** [comment]
remove node_modules folder and then try

**Comment by ravjanisz** [comment]
nope, when i do as you say, and remove this folder, error changed a little bit:
now throws in:

[gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Gulpfile.js) [12:53:45] Starting 'shop-css'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Gulpfile /public_html/shop/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js exited with an error :(

npm ERR! Linux 4.4.28-grsec
npm ERR! argv "/usr/local/node/bin/node" "/usr/local/bin/npm" "run" "gulp"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ gulp: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ gulp script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /public_html/shop/npm-debug.log

**Comment by maxpaynestory** [comment]
My nodejs version is v4.8.2

Your version is really new, maybe you could try with the above version. Make sure to remove node_modules folder before downloading dependencies.

**Comment by ravjanisz** [comment]
ok, i try with older version, but it can take a little bit. I write, if it help,

**Comment by ravjanisz** [comment]
sorry for late with answer, but it's not depend on me.
i install node 4.8.2 and have npm version 4.5.0
i deleted node_modules folder and run command npm install without errors
but error still occurs when i want to generate assets.
perhaps it is samething with code
i don't know what else from environment can generate problem with executing this command:

npm run gulp

> @ gulp /public_html/shop
> gulp

[18:40:15] Using gulpfile /public_html/shop/Gulpfile.js
[18:40:15] Starting 'admin'...
[18:40:15] Finished 'admin' after 6.88 ms
[18:40:15] Starting 'shop'...
[18:40:15] Finished 'shop' after 1.71 ms
[18:40:15] Starting 'default'...
[18:40:15] Finished 'default' after 5.51 μs
[gulp-chug] Gulpfile, Gulpfile.js, contents is empty. Reading directly from disk...
[gulp-chug] Spawning process /public_html/shop/node_modules/gulp/bin/gulp.js with args /public_html/shop/node_modules/gulp/bin/gulp.js --gulpfile Gulpfile.js default --rootPath ../../../../../../../web/assets/ --nodeModulesPath ../../../../../../../node_modules/ from directory /public_html/shop/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle...
[gulp-chug] Gulpfile, Gulpfile.js, contents is empty. Reading directly from disk...
[gulp-chug] Spawning process /public_html/shop/node_modules/gulp/bin/gulp.js with args /public_html/shop/node_modules/gulp/bin/gulp.js --gulpfile Gulpfile.js default --rootPath ../../../../../../../web/assets/ --nodeModulesPath ../../../../../../../node_modules/ from directory /public_html/shop/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle...
[gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js) [18:40:15] [gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js) Using gulpfile /public_html/shop/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js
[gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js) [18:40:15] [gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js) Starting 'admin-js'...
[gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Gulpfile.js) [18:40:15] [gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Gulpfile.js) Using gulpfile /public_html/shop/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Gulpfile.js
[gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Gulpfile.js) [18:40:15] [gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Gulpfile.js) Starting 'shop-js'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Gulpfile /public_html/shop/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js exited with an error :(
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ gulp: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ gulp script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!    /.npm/_logs/2017-05-07T16_40_16_015Z-debug.log

**Comment by pjedrzejewski** [comment]
We have switched to yarn, could you try with that?

**Comment by pjedrzejewski** [comment]
I have updated the installation guide on Sylius.org.

**Comment by ravjanisz** [comment]
nope, i won;t help. i used same configuration like upper and yarn:

yarn run gulp
yarn run v0.23.4
$ gulp
[09:39:24] Using gulpfile /public_html/shop/Gulpfile.js
[09:39:24] Starting 'admin'...
[09:39:24] Finished 'admin' after 7.04 ms
[09:39:24] Starting 'shop'...
[09:39:24] Finished 'shop' after 1.57 ms
[09:39:24] Starting 'default'...
[09:39:24] Finished 'default' after 5.19 μs
[gulp-chug] Gulpfile, Gulpfile.js, contents is empty. Reading directly from disk...
[gulp-chug] Spawning process /public_html/shop/node_modules/gulp/bin/gulp.js with args /public_html/shop/node_modules/gulp/bin/gulp.js --gulpfile Gulpfile.js default --rootPath ../../../../../../../web/assets/ --nodeModulesPath ../../../../../../../node_modules/ from directory /public_html/shop/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle...
[gulp-chug] Gulpfile, Gulpfile.js, contents is empty. Reading directly from disk...
[gulp-chug] Spawning process /public_html/shop/node_modules/gulp/bin/gulp.js with args /public_html/shop/node_modules/gulp/bin/gulp.js --gulpfile Gulpfile.js default --rootPath ../../../../../../../web/assets/ --nodeModulesPath ../../../../../../../node_modules/ from directory /public_html/shop/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle...
[gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js) [09:39:25] [gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js) Using gulpfile /public_html/shop/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js
[gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Gulpfile.js) [09:39:25] [gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Gulpfile.js) Using gulpfile /public_html/shop/vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Gulpfile.js
[gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js) [09:39:25] [gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js) Starting 'admin-js'...
[gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Gulpfile.js) [09:39:25] [gulp-chug] (vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Gulpfile.js) Starting 'shop-js'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Gulpfile /public_html/shop/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js exited with an error :(
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by maxpaynestory** [comment]
Could you please verify inside your composer.json

"sylius/sylius": "^1.0@beta"

if that is the sylius version?

**Comment by Mipme** [comment]
I had the same problem. Seems like node-sass is missing from package.json. After installing node-sass (npm install node-sass) it worked like charm!

**Comment by pjedrzejewski** [comment]
Fixed in https://github.com/Sylius/Sylius/commit/8f41da482c604d600cebc834bd84070145ac5737#diff-b9cfc7f2cdf78a7f4b91a753d10865a2.

**Comment by adsazad** [comment]
> I had the same problem. Seems like node-sass is missing from package.json. After installing node-sass (npm install node-sass) it worked like charm!

adding node-sass didnt work
