### ISSUE TITLE
Integrate Sylius Bundles to my existing app Symfony 2.8

### ISSUE THREAD

**Issue by AdelProDev** [Sylius/Sylius#8014]
Hello everybody,
i wanna add a basket to my plateforme which i have placed 3 types of different services ( Hotels, Transports, Hostesses) , i had already code the whole project without REST API, now i need to integrate step of **making orders** ( differents products (services ) ) , registration customs and payment with different cards.

please help me i have already tried to work and integrate SyliusOrderBundle + SyliusProductBundle i have found many problems with, if someone here have already do this job, please help  me.

Thank you All.

**Comment by lchrusciel** [comment]
Please, ask these questions on our official slack channel or StackOverflow. Somebody should help you there.
