### ISSUE TITLE
[ResourceBundle] EntityRepository::applyCriteria and applySorting no longer support table prefixes

### ISSUE THREAD

**Issue by peteward** [Sylius/Sylius#8019]
After a recent update, using either of these methods where you have joins and explicit table prefixes in your criteria/sorting no longer work. e.g.:

```
        $criteria = [
            'product.enabled' => true,
            'product.state' => Product::STATE_PUBLISHED,
        ];
```

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Doctrine/ORM/EntityRepository.php#L88

dot notation should be considered on `$property` (it's considered further down on line 99 and also in `getPropertyName()`).

I'm not really sure what this guard is achieving anyway. Currently it's a silent failure to apply your criteria - which isn't great. Surely an Exception would be better so you actually know what you've provided is wrong? Although changes were made here to make it 'softer' so maybe there's a good reason that I'm unaware of.

Otherwise shouldn't it just be removed? If you provide invalid criteria then you're query is going to blow up anyway, so why be heavy-handed in trying to silence it?

**Comment by gonzalovilaseca** [comment]
I came across this issue whith Godzilla, need to remember out how I solved it.
