### ISSUE TITLE
_toString() on many component's models

### ISSUE THREAD

**Issue by PapsOu** [Sylius/Sylius#8020]
Related to these closed issues, I got pretty same problem with Zone model (Adressing component)

Is it possible to cast as string all returned values of _toString() methods for each models ?

Here the list of models :

- Sylius/Component/Locale/Model/Locale.php
- Sylius/Component/Addressing/Model/Zone.php
- Sylius/Component/Addressing/Model/Province.php
- Sylius/Component/Addressing/Model/Country.php
- Sylius/Component/Attribute/Model/Attribute.php
- Sylius/Component/Taxonomy/Model/TaxonTranslation.php
- Sylius/Component/Channel/Model/Channel.php
- Sylius/Component/Product/Model/ProductOption.php
- Sylius/Component/Product/Model/Product.php
- Sylius/Component/Product/Model/ProductOptionValue.php
- Sylius/Component/Product/Model/ProductAssociationType.php
- Sylius/Component/Currency/Model/Currency.php
- Sylius/Component/Customer/Model/Customer.php
- Sylius/Component/Customer/Model/CustomerGroup.php
- Sylius/Component/Payment/Model/PaymentMethodTranslation.php
- Sylius/Component/Payment/Model/PaymentMethod.php
- Sylius/Component/Shipping/Model/ShippingCategory.php
- Sylius/Component/Shipping/Model/ShippingMethod.php
- Sylius/Component/Shipping/Model/ShippingMethodTranslation.php
- Sylius/Component/Taxation/Model/TaxCategory.php

Do you need a PR for that change ?

**Comment by PapsOu** [comment]
Related to these closed issues :
#3562, #2561, #4816

**Comment by mvar** [comment]
Another solution for this problem is to remove magic methods :) They are not part of interface anyway.

**Comment by GSadee** [comment]
It has been already fixed for the most part while introducing scalar types: 
https://github.com/Sylius/Sylius/pull/8421, https://github.com/Sylius/Sylius/pull/8325, https://github.com/Sylius/Sylius/pull/8428, https://github.com/Sylius/Sylius/pull/8430, https://github.com/Sylius/Sylius/pull/8432, https://github.com/Sylius/Sylius/pull/8435, https://github.com/Sylius/Sylius/pull/8440, https://github.com/Sylius/Sylius/pull/8447, https://github.com/Sylius/Sylius/pull/8451, https://github.com/Sylius/Sylius/pull/8466
