### ISSUE TITLE
[Docs] Building docs requires fabpot/sphinx-php

### ISSUE THREAD

**Issue by emodric** [Sylius/Sylius#8021]
It is not mentioned anywhere in documentation `README.md`, but building docs requires https://github.com/fabpot/sphinx-php.git to be installed with:

```
pip install git+https://github.com/fabpot/sphinx-php.git
```

Otherwise, running `sphinx-build -b html . build` will result in the following error:

```
Extension error:
Could not import extension sensio.sphinx.configurationblock (exception: cannot import name 'upper')
```

**Comment by lchrusciel** [comment]
Are you willing to open a pr? /cc @CoderMaggie

**Comment by CoderMaggie** [comment]
It is mentioned in the docs :)
http://docs.sylius.org/en/latest/contributing/documentation/overview.html#testing-documentation

**Comment by emodric** [comment]
@CoderMaggie I must be blind :)

Docs only state that we need to run `pip install -r requirements.txt`, but the `requirements.txt` file does not specify `fabpot/sphinx-php` requirement.

I only managed to build the docs once I installed that manually.

**Comment by CoderMaggie** [comment]
![image](https://cloud.githubusercontent.com/assets/13198869/25743723/1c63011a-3196-11e7-93e1-8f6bf5e4720b.png)
 @emodric, did you see this one? :)

**Comment by emodric** [comment]
@CoderMaggie I'm talking about https://github.com/fabpot/sphinx-php, which is installed via `pip install git+https://github.com/fabpot/sphinx-php.git` :)

That repo provides `sensio.sphinx.configurationblock` extension which you import in your `conf.py`.

**Comment by CoderMaggie** [comment]
Okay @emodric. I'll check that when I will have a moment, because I did not install it, and I can build docs without any issues.
