### ISSUE TITLE
Is there any direct way to install wtihout composer?

### ISSUE THREAD

**Issue by maplewang** [Sylius/Sylius#8027]
Since many VPS provide old version Ubuntu and php 5.x, so we prefer to install a xampp on it, install a composer on xampp is not easy , can Sylius be downloaded and installed via a web browser?
prestashop is based on symphony now, it can be downloaded and installed.
and can it support SQLite? I just want to run a small site.
Thanks.

**Comment by lchrusciel** [comment]
SQLLite support should not be a problem (our [PluginSkeleton is preconfigured to use it](https://github.com/Sylius/PluginSkeleton/blob/master/tests/Application/app/config/config.yml#L36-L40)), but the only possible way of installation is a composer at the moment, sorry. And I don't see any other possible solution in a near future. 
Closing then.
