### ISSUE TITLE
translations collections from custom model empty in twig template

### ISSUE THREAD

**Issue by gaetan-puleo** [Sylius/Sylius#8028]
Hello,

I created a custom entity "Faq" with their routes .
When I make a dump of "faqs" in my index.html.twig  Faq#translations#collection is empty.

I need a "question"and a "response" in the collection.
In my database all fields are present in FaqTranslation.

What I've could missed?

Sorry for my poor English.

Thanks .

result dump : 
Faq {#3359 ▼
  -id: 2
  #translations: PersistentCollection {#3369 ▼
    -snapshot: []
    -owner: Faq {#3359}
    -association: array:16 [ …16]
    -em: EntityManager {#2123 …11}
    -backRefFieldName: "translatable"
    -typeClass: ClassMetadata {#3361 …}
    -isDirty: false
    #collection: ArrayCollection {#3371 ▼
      -elements: []
    }
    #initialized: false
  }
  #translationsCache: []
  #currentLocale: "fr_FR"
  #currentTranslation: null
  #fallbackLocale: "en_US"
}

**Comment by pjedrzejewski** [comment]
@gaetan-puleo We use GitHub to report bugs/feature requests and to manage the development of the whole platform. For support, please use our Slack or StackOverflow and tag your question with "sylius". From I see, it must be something wrong with your entity mappings, but not sure.
