### ISSUE TITLE
Support for Twig 2.x

### ISSUE THREAD

**Issue by emodric** [Sylius/Sylius#8029]
It would be awesome to have support for Twig 2.x before the final is released.

Sylius already requires Twig `^1.28` and as far as I can tell, upgrade from 1.28 to 2.x is pretty straightforward.

**Comment by mbabker** [comment]
I need to find a little bit of time to go through it all again but https://github.com/Sylius/Sylius/pull/7629 is the PR working on that.

**Comment by pjedrzejewski** [comment]
We had some discussions and we would need to figure out how to test it on both versions, so we decided that it is not worth the effort at this point. That being said, let's keep that discussion open and continue in #7629.

**Comment by emodric** [comment]
@mbabker @pjedrzejewski Thanks for pointing me to the right PR and sorry for the duplicate :)
