### ISSUE TITLE
Model setters

### ISSUE THREAD

**Issue by PapsOu** [Sylius/Sylius#8030]
It would be very handy to change all setters of Sylius models, adding self return in order to allow setter chaining.

Example : 

class Sylius\Component\Core\Model\Image::setFile

```php
/**
     * {@inheritdoc}
     */
    public function setFile(\SplFileInfo $file)
    {
        $this->file = $file;
    }
```

Should be 

```php
/**
     * {@inheritdoc}
     */
    public function setFile(\SplFileInfo $file)
    {
        $this->file = $file;
        return $this;
    }
```

Allowing that kind of custom code : 

```php
$productImage = new ProductImage();
$productImage
    ->setRealFile($file)
    ->setOwner($object)
    ->setType('main');
```

I know that regenerating all model's setters is an long task, but it would be a great feature / coding standard for developers that will extends Sylius models.

**Comment by Arminek** [comment]
Imo fluent interfaces are not a good idea. Here is blog post about this approach https://ocramius.github.io/blog/fluent-interfaces-are-evil/

**Comment by Zales0123** [comment]
I totally agree with @Arminek, in fact, almost every model in Sylius had fluent interfaces in the past and they was removed, according to all the reasons posted in linked article. I know they look encouragingly at the first sight, but it's just a bad design, we should not return to that nightmare 👹  ;)

**Comment by PapsOu** [comment]
@Arminek : I think for plain old PHP object (or POJO for Java developers) the « bad points » described in this blog article are not important for so simple objects.

Using fluent accessors for simple object (models in that case) wouldn't add much more problems than other « complex » objects.

@Zales0123 : With PHP7 you can type explicitly the returned type of any method.

If Sylius's team don't want to go back with a « bad » design pattern, I would understand that choice because I don't know all implied things of that kind of decision.
