### ISSUE TITLE
[FR][API] Support for API documentation generator

### ISSUE THREAD

**Issue by mvar** [Sylius/Sylius#8032]
Any plans to support NelmioApiDocBundle or other existing solution for API docs?

**Comment by pjedrzejewski** [comment]
We wanted to use Nelmio's bundle, but at the time it only supported annotations and this does not work with our controllers. :/ Anything has changed? We would need YAML format support.

**Comment by mvar** [comment]
From what I see it still supports only annotations. But it also supports [custom annotation providers](https://github.com/nelmio/NelmioApiDocBundle/blob/master/Extractor/AnnotationsProvider/DunglasApiProvider.php). Maybe Sylius could have annotation provider which takes serialisation configuration and builds virtual annotations.

**Comment by kochen** [comment]
@pjedrzejewski @mvar it (should) support other method/handlers/extractors: https://github.com/nelmio/NelmioApiDocBundle/tree/master/Extractor
https://symfony.com/doc/current/bundles/NelmioApiDocBundle/other-bundle-annotations.html#using-your-own-annotations
