### ISSUE TITLE
PayPal on production

### ISSUE THREAD

**Issue by ascameron1** [Sylius/Sylius#8036]
I have been using sandbox credentials for PayPal using the paypal_express_checkout feature built into Sylius with no issue.

However, since changing the credentials to a live account, I am getting a `Security header is not valid` error.

This suggests that either the endpoint or credentials are wrong. Im pretty certain my credentials are right so is there something im missing with the endpoint and thats why it was working on sandbox? 

Kind regards

**Comment by makasim** [comment]
A lot of people use Payum Paypal on production. If there was a problem with the endpoint we would notice it a long time ago. The endpoint is defined in [Api::getEndpointUrl](https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/ExpressCheckout/Nvp/Api.php#L604) method, you could check them yourself. 

Please check the credentials one more time. Make sure (If you configured it in  YAML) that the parameters in '', there is entry white spaces or other symbols.

**Comment by ascameron1** [comment]
Hi,

Ok this is a strange one and im stuck with it.

Using the sandbox credentials works fine and looking into the network tab... this request can be seen.

![screen shot 2017-05-10 at 09 08 37](https://cloud.githubusercontent.com/assets/9931913/25889024/5193cd7e-3560-11e7-812f-8f4f493c3bcd.png)

When i change the credentials to real credentials for a real account... this can be seen.

![screen shot 2017-05-10 at 09 05 32](https://cloud.githubusercontent.com/assets/9931913/25889074/7a27fba2-3560-11e7-8c41-8d9465a621ef.png)

The location is different in the response headers.

**Comment by ascameron1** [comment]
When i set the URL to not use the sandbox url in [Api::getEndpointUrl](https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/ExpressCheckout/Nvp/Api.php#L604), the headers are still in sandbox mode apparently. Is there away to disable sandbox mode? 

Ive tried in config.yml:

    payum:
        gateways:
            paypal_express_checkout:
                factory: paypal_express_checkout
                payum.http_client: "@sylius.payum.http_client"
                username: 'xxxxx'
                password: 'xxxxx'
                signature: 'xxxxx'
                sandbox: false

But this did not work.

**Comment by psihius** [comment]
@ascameron1 

What version of Sylius are you using?
The Beta 2 and master are not using configuration through the files anymore for gateways.

**Comment by ascameron1** [comment]
Hi @psihius 

Im using master and have set up my gateway through the admin panel. The configuration i shown was a last ditch attempt to try and disable sandbox mode.

Test credentials work fine but when i use live credentials, sandbox headers in the request are still being used as far as i am aware.

Kind regards

**Comment by psihius** [comment]
@ascameron1  Did you change the sandbox mode and credentials in the admin panel?

**Comment by ascameron1** [comment]
@psihius I have changed the credentials yes. Ive not changed sandbox mode as i cannot see where that is done?

Here is a ss of my admin panel:

![screen shot 2017-05-10 at 11 22 03](https://cloud.githubusercontent.com/assets/9931913/25894223/ee769880-3572-11e7-95db-19fecbb74392.png)

Kind regards

**Comment by psihius** [comment]
Hm, your form looks a bit weird - fields are in the wrong places and you miss at least one of them. Should be like this:
https://i.imgur.com/zma2V1F.png

**Comment by ascameron1** [comment]
@psihius 

Ok... is that something thats been done recently? I checked out the project in March.

**Comment by psihius** [comment]
Beta 2 was released on April 11th 2017, so yes, you are using an incomplete dev version. You should really update at least to BETA 2 or catch up to current master.

**Comment by ascameron1** [comment]
Ahhh ok. No worries. Ill try that and see if it works. 

Kind regards

**Comment by psihius** [comment]
@ascameron1 please close the issue, you should be able to as the creator so it does not dangle in the issue tracker :)

**Comment by mbabker** [comment]
IIRC PayPal requires you have SSL enabled on your site, the screenshot of your headers from the browser show the site's not using SSL.

**Comment by makasim** [comment]
It is widly suggested to have SSL enabled, but there is no such restriction from Paypal side.
The site could be pure HTTP, the site to PayPal communication is done over secured connection.

**Comment by ascameron1** [comment]
Hi guys, i updated to the beta2 release (big pain haha) and paypal is now working. I was indeed missing the disable sandbox action in the form.

Thank you all for you help :).
