### ISSUE TITLE
Improve admin sidebar

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#8043]
Since #7603 the sidebar is always opened in the Admin. On an 13 inch screen with a default resolution, this conflicts on a lot of places with proper showing information, e.g. on the order overview & on the new taxons URL. I would really like the feature again to be able to keep the sidebar by default closed, or remember last state e.g. (cookie?).

**Comment by sweoggy** [comment]
It should definitely be possible to lock it so it stays open (very useful on desktop), but when unlocked it should automatically be closed. I think I might have a go at this.

**Comment by Arminek** [comment]
#7603 this should be reverted to bring back this functionality, but still this animation won't work.

**Comment by lchrusciel** [comment]
yep, it is resolved.
