### ISSUE TITLE
Taxation model doesn't seem to work for EU B2B/B2C sales

### ISSUE THREAD

**Issue by ioweb-gr** [Sylius/Sylius#8047]
Hi,

Sorry for the newbie question, but we only recently decided to try out Sylius for our company and noticed something that I don't see a way to fix other than customizing the taxation logic but most ecommerce alternatives support out of the box e.g. Magento, Prestashop, Woocommerce. 

The problem comes with calculating VAT Tax in European Union countries. 

Let's say we have 4 types of customers, 

Local Retail Customers (LRC) 
Foreign Retail Customers (FRC)
Local Businesses (LBC)
Foreign Business (FBC)

For retail customers there are two cases I've encountered so far based on individual country's law
1. add the same VAT Tax % for every sale to any LRC  or FRC
2. add the VAT tax % of the recipient's country for FRCs (for example 20% if the person purchasing is residing in Germany, 24% if the person is in Greece).  

For business customers I see two different cases as well
1. put VAT Tax to every sale to any LBC
2. don't put any VAT Tax (0% VAT) for FBC

I thought of setting up Zones first with scope for taxes but I can't see how to set it up the way the system  currently works. I can't see any association between "Customer Group and Tax" or  between "Zones and Customer Group" that would enable this sort of association I'm describing. Also there's not a way to automatically check during checkout if the guest is a company or an individual. 

One common implementation I see for this in checkout when purchasing from abroad is the following:
1a. when the guest fills in a company name, he is considered a BC 
1b. the guest selects if he's buying as individual or company
2. If the country he selected is within the EU, a VAT Identification Number field shows up to be filled. 
3. The tax is calculated based on the type of customer and country selected. 

Am I missing something simple here maybe because it looks to me like a serious flaw. I appreciate any advice. Thank you in advance

**Comment by ioweb-gr** [comment]
After checking around  abit more I still can't find a solution to this within sylius. There's no relation between tax rate and customer tax class. 

Here's an example in Magento where we have tax rates, product tax class and customer tax class to define taxation for products. 

![image](https://cloud.githubusercontent.com/assets/20220341/26094242/d3872b4e-3a21-11e7-9dba-2c49bada819d.png)

Here's an example from virtuemart 

![image](https://cloud.githubusercontent.com/assets/20220341/26094454/bfeeba56-3a22-11e7-8f14-78c9f4856709.png)

**Comment by pjedrzejewski** [comment]
We would like to introduce customer tax category concept in 1.1, right now it is a bit too late but thank you for research & explanation of the issue - makes sense. :) 👍

**Comment by ioweb-gr** [comment]
Hi @pjedrzejewski it's very nice to see that this will be addressed because for me it wasn't possible to use Sylius at all with this issue. It will be nice to revisit.

**Comment by mrjingles** [comment]
+1 Actually a showstopper for me to.

**Comment by GSadee** [comment]
@ioweb-gr as for the creator of this issue, it would be really appreciate if you look at the proposed solution in #8676. Thank you very much for your time!

**Comment by psren** [comment]
this is not stale

**Comment by mrjingles** [comment]
Are there any news about that? @pjedrzejewski

**Comment by michaelKaefer** [comment]
@pjedrzejewski As long as the "customer tax category concept" is not introduced is this a valid solution in your opinion? Create a channel `B2B` and a channel `B2C`. For every product/variant enter a gross price for channel `B2C` and a net price for `B2B` (add taxes as usual, just make sure that the tax is 0% in every case fpr channel `B2B`). Redirect "Foreign Business (FBC)" who have a valid VATIN to the channel `B2B` (this can be done in a modal on the first visit where they have to choose that they are a foreign business and enter a valid VATIN; and also you can add links in the `B2C`channel which lead to the `B2B` channel). - Or: as there are already a lot of B2B and B2C shops made with Sylius how is this done usually? Is there y better way?
