### ISSUE TITLE
Zones with multiple countries slow performance

### ISSUE THREAD

**Issue by ioweb-gr** [Sylius/Sylius#8048]
Hi, 

I tried creating a few zones programmatically by loading some fixtures, for EU and Rest of the world. The zones got created correctly however trying to edit them is near impossible via the admin interface. It takes over 40seconds to load and about as much to save a change for the EU zone with 28 countries. 
The rest of the world will just load forever and then timeout. 

![image](https://cloud.githubusercontent.com/assets/20220341/26033436/14ac1148-38b5-11e7-871b-5a77980ae82d.png)

From the profiler in dev mode
![image](https://cloud.githubusercontent.com/assets/20220341/26033484/27d8a4ba-38b6-11e7-9874-34516f3299ff.png)

Here are the specs of the server I tested it on using 

```
php 7.0.14
mysql  Ver 15.1 Distrib 10.0.30-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
model name      : Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz on load average: 0.34
ram: 16GB DDR3
hdd: SATA III 

hdparm -t /dev/md3
/dev/md3:
 Timing buffered disk reads: 364 MB in  3.00 seconds = 121.19 MB/sec
```

Here is the code I used to load the fixtures on the db

```

        $countries = Intl::getRegionBundle()->getCountryNames();
        foreach ($countries as $code => $name) {
            $zoneMember = new ZoneMember();
            $zoneMember->setCode($code);
            if (empty($this->zoneMemberManager->getRepository(ZoneMember::class)->findOneBy(['code' => $code]))) {
                $this->zoneMemberManager->persist($zoneMember);
            }
        }


        $zones = ['GR' => 'Greece', 'EU' => 'European Union', 'ROW' => 'Rest of the world'];
        foreach ($zones as $code => $name) {
            $zone = new Zone();
            $zone->setCode($code);
            $zone->setName($name);
            $zone->setScope(Scope::ALL);
            $zone->setType(Zone::TYPE_COUNTRY);
            if (empty($this->zoneManager->getRepository(Zone::class)->findOneBy(['code' => $code]))) {
                $this->zoneManager->persist($zone);
            }
        }

        $zoneMembers = array();
        $zoneMembers['GR'] = ['GR'];
        $zoneMembers['EU'] = [
            'BE',
            'BG',
            'CZ',
            'DK',
            'DE',
            'EE',
            'IE',
            'GR',
            'ES',
            'FR',
            'HR',
            'IT',
            'CY',
            'LV',
            'LT',
            'LU',
            'HU',
            'MT',
            'NL',
            'AT',
            'PL',
            'PT',
            'RO',
            'SI',
            'SK',
            'FI',
            'SE',
            'GB',
        ];

        $zoneMembers['ROW'] = array();
        foreach($countries as $code => $name) {
            array_push($zoneMembers['ROW'], $code);
        }

        $this->zoneMemberManager->flush();
        $this->zoneManager->flush();

        $zoneROW = $this->zoneManager->getRepository(Zone::class)->findOneBy(['code' => 'ROW']);
        $zoneEU = $this->zoneManager->getRepository(Zone::class)->findOneBy(['code' => 'EU']);
        $zoneGr =  $this->zoneManager->getRepository(Zone::class)->findOneBy(['code' => 'GR']);

        foreach($zoneMembers['ROW'] as $code){
            $zoneMember = $this->zoneMemberManager->getRepository(ZoneMember::class)->findOneBy(['code' => $code]);
            $zoneROW->addMember($zoneMember);
        }

        foreach($zoneMembers['EU'] as $code){
            $zoneMember = $this->zoneMemberManager->getRepository(ZoneMember::class)->findOneBy(['code' => $code]);
            $zoneEU->addMember($zoneMember);
        }

        $zoneGr->addMember($this->zoneMemberManager->getRepository(ZoneMember::class)->findOneBy(['code' => 'GR']));

        $this->zoneManager->flush();
        $this->zoneMemberManager->flush();
```

And I also followed the docs to add all countries via fixtures:load

**Comment by psihius** [comment]
Is this being run under Vagrant?
Is Opcache enabled?
Is that an SSD?

**Comment by ioweb-gr** [comment]
Hi, 
it's a SATA III (not SSD) disk on a dedicated server. It provides about 130-150mb/sec read/write speed on most tests

I just checked php version and Opcache was disabled. I enabled it and the results improved a lot on the second time I open the same zone. It went down to 14seconds from 47. However after browsing around and revesiting the same zone a bit later it went back up to 43.

![image](https://cloud.githubusercontent.com/assets/20220341/26034180/532817bc-38c1-11e7-94b1-a9a6bf607eea.png)

![image](https://cloud.githubusercontent.com/assets/20220341/26034184/66baf178-38c1-11e7-830f-ab8b9abdc416.png)

The second zone for Rest of the world, with 225 counttries resulted in 99 seconds load time with opcache enabled consistently. It used up 300MB of memory though. It seems a bit much

![image](https://cloud.githubusercontent.com/assets/20220341/26034226/280a9e8c-38c2-11e7-9e21-f5d8dcea0f54.png)

**Comment by psihius** [comment]
Well, first, HDD is, sadly, are slow and Symfony has a lot of small files and in debug mode writes a lot to logs and profiler has tons of data to write to disk too - I guess that is what slows down a lot.

Second, I'd recommend adjusting opcache settings a bit:
```zend_extension=opcache.so
opcache.revalidate_freq=0
;opcache.validate_timestamps=0
opcache.max_accelerated_files=40000
opcache.memory_consumption=192
opcache.interned_strings_buffer=16
opcache.fast_shutdown=1```

Tweak `opcache.revalidate_freq=0` and `opcache.validate_timestamps=0` according to your environment. My are for a developer machine - it checks if code has changed every request. See http://php.net/manual/en/opcache.configuration.php for those two.

Third - adjust realpath cache, I used recommended settings for Symfony.
```
realpath_cache_size = 4096k
realpath_cache_ttl = 600
```

This is what can be done for a developer machine. For production there are more optimizations that can be done. Also, try running in production mode (just don't use app_dev.php) and see how fast that will be.

**Comment by ioweb-gr** [comment]
Thanks for the suggestions. I really appreciate any advice. Speed has improved but it wasn't significant difference. I tried with the above recommendations, I also tweaked revalidate_freq, timestamp to see the effects and also enabled prod mode and from 99secs it dropped to 91secs for 230countries. That's less than 10% improvement. 
![image](https://cloud.githubusercontent.com/assets/20220341/26034705/41a83d7a-38c9-11e7-811c-1d2f1d5b2a2e.png)

It seems to me that even if I used an ssd that's 4 times faster (520mb/sec - 600mb/sec), doesn't it mean it would drop at best to 91s/4 = 25s ? It still feels slow for the amount of data this page has. 

Sorry if I ask a lot of questions since I'm new at trying Sylius as an alternative to common ecommerce platforms but, does this mean that Sylius doesn't scale well and can only be used on high-end dedicated hardware?

**Comment by psihius** [comment]
Well, at this point either someone from Sylius team may have an idea why this happens or it needs some debugging to figure out what happens there that makes this kind of slowdown, it should not be that bad...

**Comment by ioweb-gr** [comment]
Yeah I see. But obviously that's assuming you have ideal disk usage and can use it at full capacity. In a real scenario this would rarely be possible.  

In any case I can see it's pretty much taking it's time in 

`vendor/sylius/sylius/src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php`
line 309: `$form = $this->resourceFormFactory->create($configuration, $resource);`

From there I can see it's trying to recursively build the forms for each associated entity too but it's getting too complex for me to understand. 

I'm thinking it might be trying to build the form 1 time for each ZoneMember that belongs to the zone with the full amount of countries causing 28 x 255 (countries) to be needed in 1st case or 230x255 entries in second case to actually render the select form elements. That would explain the long time. 

I've actually had a similar issue while trying to integrate the geonames database to a project and the sheer amount of provinces (32500 for my country) was making every form sluggish to load so I had to make sure to limit the results or ask for the input to be loaded via ajax in a hierarchy country -> region -> province -> city  and only when a select box was picked.

**Comment by psihius** [comment]
Yeah, that's probably the issue here. That explains the 2.25 MB document size and the 200MB memory usage.

Well, this probably calls for the form override to make it more sensible, but in general this looks like a problem that needs solving overall.
From the top of my head I think this does not need to provide select options for already added members - if you need to change one - just remove it and add a new one - editing here may be dropped. The only dropdown needs to be the "Add" one I think. This is easiest solution. Also can go custom route, involve AJAX and convert to a select box when clicked. Anyway, this is not for me to decide.
