### ISSUE TITLE
Container error

### ISSUE THREAD

**Issue by dimonise** [Sylius/Sylius#8049]
I'm learning Sylius and I'm following the documentation. I'm trying to get a list of products on the main page. Here is my controller code:
`<?php

namespace AppBundle\Controller\Shop;

use Symfony\Bundle\FrameworkBundle\Templating\EngineInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

final class HomepageController
{
    /**
     * @var EngineInterface
     */
    private $templatingEngine;
    /**
     * @param EngineInterface $templatingEngine
     */
    public function __construct(EngineInterface $templatingEngine)
    {
        $this->templatingEngine = $templatingEngine;

    }

    /**
     * @param Request $request
     *
     * @return Response
     */
    public function indexAction(Request $request)
    {

        $productRepository = $this->container->get('sylius.repository.product');

        $first = $productRepository->findAll();

        return $this->templatingEngine->renderResponse('@SyliusShop/Homepage/index.html.twig', array('first'=>$first));
    }

}
`
But I'm constantly getting an error with this line:

`$productRepository = $this->container->get('sylius.repository.product');`

> Notice: Undefined property: AppBundle \ Controller \ Shop \ HomepageController :: $ container

**Comment by Zales0123** [comment]
Hi @dimonise. The reason you're getting this error is that you don't extend basic `Controller` class from *Symfony* or not inject container to your `HomepageController`.
I'm closing this, as it's not a Sylius issue. In the future, please use our **Slack** or [stackoverflow](http://stackoverflow.com/questions/tagged/sylius) to ask such questions :)
