### ISSUE TITLE
Yarn install - No such file or directory

### ISSUE THREAD

**Issue by hakabe** [Sylius/Sylius#8063]
Couldn't find versions required for yarn in the manual. Which yarn version is supported in your project?
```
[OK] Sylius has been successfully installed.

You can now open your store at the following path under the website root: /app_dev.php.
root@bitsnpcs:~/acme# yarn install
ERROR: [Errno 2] No such file or directory: 'install'
root@bitsnpcs:~/acme# yarn --version
0.22
```

**Comment by lchrusciel** [comment]
Somebody could add this to docs. @hakabe according to your problem, I have v0.23.4 and it is working.

**Comment by aeoris** [comment]
For future reference, this may be related: https://github.com/yarnpkg/yarn/issues/3189

**Comment by cbka** [comment]
still an issue today... with debian you have to do the following: 

sudo apt remove cmdtest
sudo apt remove yarn
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update
sudo apt-get install yarn -y

after that yarn install runs fine... 

maybe doc ?
