### ISSUE TITLE
[Cookbook] Configure Mandrill (etc.) for transactional e-mails

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#8065]
A lot of people asking how to use Mailjet, Mandrill to send transactional e-mail. A cookbook would be great. My solution so far was just to configure Swiftmailer and it worked like a charm. I recall also a bundle, which allowed to use Mandrill API. (Useful when hosting on Google Cloud)

**Comment by stefandoorn** [comment]
Mandrill recently got pretty expansive, so lots of people are moving to SparkPost, MailGun, etc. I'm not sure if there is a package available somewhere that easily connects with all this kinds of API's instead over SMTP (it does work easy indeed as I have with SparkPost), that would be great to implement :)
