### ISSUE TITLE
[Products][Admin] Main taxon is not giving any taxons to select

### ISSUE THREAD

**Issue by psihius** [Sylius/Sylius#8068]
The issue is that for me and @gabiudrescu on our projects the taxon list for selection is not being shown. Though my debug attempts I came to the fact that "search" request is not being made at all, hence we get no taxons at all. If the taxon is already set, then the `load-edit-url` works no problem.
The more weird part is that on current demo (whatever version that is) it works just fine. I have double checked - I have no overrides in the admin side, I cleared all caches, generated JS files, re-installed all the JS packages. I have compared the code between the demo and my project - it's identical.

I'm on master, updated it today to make sure i'm on the most fresh version there is. Poke me in Slack under same username - I will provide info and show what exactly is happening if reproduction is problematic.

**Comment by gabiudrescu** [comment]
I'll be damned.. i just tried it on a fresh new install on my machine and it works.

although on another server, it doesn't. I can provide access to that server on request to anyone interested in debugging.

**Comment by pcmdev** [comment]
I've a similar issue on my site. I have a tree of taxonomies like this:

- Categories: including Category 1, Category 2, Category 3, etc.
- Test: including Test 1.

When I try to assign the product to Category 1 it's impossible, Sylius is not displaying the tree of categories and the search is not returning any results either.

![screenshot from 2017-06-01 16-52-32](https://cloud.githubusercontent.com/assets/27411883/26688529/c6b47298-46ea-11e7-904b-f1551521a252.png)

**Comment by pjedrzejewski** [comment]
@psihius @gabiudrescu Is it still the case?

**Comment by psihius** [comment]
@pjedrzejewski on my current project - works, I can do everything no problem. I'm on the master, just updated today.

**Comment by gabiudrescu** [comment]
works on dev-master. I think it can be closed.

**Comment by pjedrzejewski** [comment]
👍 👍 👍

**Comment by nithiz** [comment]
Hey @pjedrzejewski , it seems that this issue is back again. I can't select any mainTaxon. The only time a value is present in the dropdown is when it already is the mainTaxon (for example if you run fixtures where mainTaxons are applied).

It also seems that there is no way this could work with the current code. In Tab/_taxonomy.html.twig i see `{{ form_row(form.mainTaxon) }}` but form.mainTaxon is null when nog mainTaxon has been chosen yet..
