### ISSUE TITLE
Multistore

### ISSUE THREAD

**Issue by HRvojeIT** [Sylius/Sylius#8082]
Hello,
I find different answers for this question: is it possibile to make a sort of marketplace?
I need to:
 - permit to multiple different admins to see and load only their products
 - the marketplace user (and it's only one user for all "admins") shoud see all products and follow the same cart experience
 - after buying the superuser can see all markets but the relative admin should see only it's own

Thank you

**Comment by pjedrzejewski** [comment]
Hello @HRvojeIT! Yes it is possible, but requires custom development. We see high demand for such functionality, so it is a good idea for Sylius plugin/marketplace edition. Join our Slack via sylius.org/slack, I am sure there are more people interested in the idea. :)
