### ISSUE TITLE
Minimum Sylius install

### ISSUE THREAD

**Issue by andrewpros** [Sylius/Sylius#8083]
Hi.

It is more like question than issue, but i can't find this in docs, but they do state that you can use only a fraction of components, the default project sylius standard is installing a lot of libs, so my question is, what is the absolute minimum install of sylius to be functional?

**Comment by pjedrzejewski** [comment]
Hello @andrewpros! Well, you can use the individual components, but to use the platform (ui/api with core ecommerce logic), Sylius/Sylius is the minimum, although you can disable admin/shop UI & API individually. I suggest to join our slack via sylius.org/slack to discuss your use-case. :) GitHub issues are for bug reports/feature requests, etc. Thanks and welcome!

**Comment by andrewpros** [comment]
Ok, so the sylius/core can't be used as a base?

**Comment by CoderMaggie** [comment]
@andrewpros SyliusCore is basically the Sylius/Sylius as a whole, it is just a bundle that integrates all the other bundles into a whole platform. What is more, Sylius/Sylius is the minimum installation as @pjedrzejewski has stated above.

**Comment by andrewpros** [comment]
Ok, got it.

**Comment by Bonobomagno** [comment]
The only way to install sylius/sylius is with the create-project? no way to install sylius on old project? Maybe symfony one?

**Comment by lchrusciel** [comment]
You can always do it standard Symfony way `composer require sylius/sylius` and then add needed things to kernel and config file
