### ISSUE TITLE
Not able to get it to work on heroku

### ISSUE THREAD

**Issue by shairyar** [Sylius/Sylius#8088]
Please provide detailed instructions on how to deploy Sylius on heroku.

This is not my first symfony deployment but for some reason i am having a really hard time deploying sylius on heroku

I have the procfile and database all setup.

When i run the command `heroku run bin/console sylius:install`

The first step asks 

```
Creating Sylius database for environment prod.
It appears that your database already exists.
Warning! This action will erase your database.
Would you like to reset it? (y/N) y
```

the process goes on and the second step asks

```
Loading sample data for environment prod.
Warning! This action will erase your database.
Continue? (y/N) y
```

after entering y i get the error

```

>   [Symfony\Component\Debug\Exception\FatalThrowableError]
>   Call to a member function getCode() on null

```

In another try i entered n in second step and got through rest of the questions .

but on running the app i get 403

Inside my procfile i have

`web: vendor/bin/heroku-php-apache2 public/`, right now this gives 403 but i can access the site using domain.com/web/app.php so i have a feeling maybe .htaccess file is not uploaded or something

I also tried replacing this with 
`web: $(composer config bin-dir)/heroku-php-apache2 web/` but this crashes the app and gives error code code=H10 

I will really appreciate if you can point me to some details installation guide or let me know what ami missing here as this is driving me crazy :)

**Comment by tchapi** [comment]
Might be linked to https://github.com/Sylius/Sylius/issues/5762
