### ISSUE TITLE
Meta keywords & description for taxons

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#8091]
It's currently missing. Would it be something to add? I can submit a PR if interested.

**Comment by kochen** [comment]
@stefandoorn I'd submit a pool request anyway - worst case it's not accepted/merge but the code is available for everyone ;)

**Comment by psihius** [comment]
Maybe we can even make those a "per channel" based? You might want different SEO texts for different channels, and maybe even descriptions/names? :)

**Comment by stefandoorn** [comment]
Hehe, let's keep it easy in the beginning. @lchrusciel Shall I submit a PR?

**Comment by pjedrzejewski** [comment]
@stefandoorn Makes sense to me, especially we do have them on the product translation. Let's do the same for taxon translations. 👍

**Comment by psihius** [comment]
@pjedrzejewski @stefandoorn this was suggested by clients SEO people - do not use the product name for the SEO - make a separate SEO field for title tag. I ended up doing just that - product has a name that is displayed on the page and page title has it's own value taken from that SEO field.
You could probably copy it by default from name when it is entered and SEO people can change it when needed to make life easier for the regular joe.

**Comment by stefandoorn** [comment]
Let's keep this one open, still need to PR it.
