### ISSUE TITLE
Group By error on Sylius taxon routes

### ISSUE THREAD

**Issue by Cathmor** [Sylius/Sylius#8099]
So I have an error pooping up when I go to look at the taxon/{slug} routes on the shop page. This error pops up on every taxon. 

    An exception occurred while executing 'SELECT s0_.code AS code_0, s0_.created_at AS created_at_1, s0_.updated_at AS updated_at_2, s0_.enabled AS enabled_3, 
    s0_.id AS id_4, s0_.variant_selection_method AS variant_selection_method_5, s0_.average_rating AS average_rating_6, s1_.name AS name_7, s1_.slug AS slug_8, s1_.description AS description_9, 
    s1_.meta_keywords AS meta_keywords_10, s1_.meta_description AS meta_description_11, s1_.id AS id_12, s1_.short_description AS short_description_13, s1_.locale AS locale_14, s0_.main_taxon_id AS 
    main_taxon_id_15, s1_.translatable_id AS translatable_id_16 FROM sylius_product s0_ INNER JOIN sylius_product_translation s1_ ON s0_.id = s1_.translatable_id AND (s1_.locale = ?) INNER JOIN
    sylius_product_taxon s2_ ON s0_.id = s2_.product_id WHERE s2_.taxon_id = ? AND EXISTS (SELECT 1 FROM sylius_product_channels s3_ INNER JOIN sylius_channel s4_ ON s3_.channel_id = s4_.id WHERE
    s3_.product_id = s0_.id AND s4_.id IN (?)) AND s0_.enabled = 1 GROUP BY s0_.id ORDER BY s2_.position
    ASC OFFSET 0 ROWS FETCH NEXT 9 ROWS ONLY' with params ["en_US", 3, 1]:

    SQLSTATE[42000]: [Microsoft][SQL Server Native Client 11.0][SQL Server]Column 'sylius_product.code' is invalid in the select list because it is not contained in either an aggregate function or the 
    GROUP BY clause`

The only product field that is in the group by query is the id but code and dates are in there as well. 

Has anyone else ran into this issue?

Thanks,
Cathmor

**Comment by mbabker** [comment]
Just looking at your error message, I'm going to make a bet that SQL Server support isn't very strong in Sylius right now.

**Comment by Raptek** [comment]
MySQL 5.7+ use `ONLY_FULL_GROUP_BY` as one of default sql modes. I use this workaround:

```php
use Doctrine\Common\EventSubscriber;
use Doctrine\DBAL\Event\ConnectionEventArgs;
use Doctrine\DBAL\Events;

class MySQLModeListener implements EventSubscriber
{
    public function getSubscribedEvents()
    {
        return [Events::postConnect];
    }

    public function postConnect(ConnectionEventArgs $args)
    {
        $args->getConnection()->exec("SET sql_mode=(SELECT REPLACE(@@sql_mode, 'ONLY_FULL_GROUP_BY', ''));");
    }
}
```

It's a bit dirty solution, but it works.

**Comment by Cathmor** [comment]
Thanks for the fast response guys!

Yep, I am using MS SQL Server so the MySQLModeListener didn't make a difference. 

The GROUP BY clause is specified in the createShopListQueryBuilder so I was able to at least fix my error with by making a custom repository and over riding the function with one without the group by.

But now a new question, is that GROUP BY necessary? There are no aggregates so it;s not like it's getting a sum with all the unique id constraints on the tables there would be any duplicate information. Just my thought.
