### ISSUE TITLE
[Admin] Prevent error bubbling in CollectionTypes

### ISSUE THREAD

**Issue by Niiko** [Sylius/Sylius#8100]
In fact, in admin forms, if you add any validation on a collectionType, errors are displayed at the beginning of form, despite if error belongs to a sub menu form.

My case is, i had a count validator on product images with a minimum of one value.

Error is displayed in details sub menu form menu, not in media menu.

I know it's pure cosmetic and i managed that by a form extension.

[Edited]
As a side effect, error is displayed twice in collection_widget because of " {{ error(form.vars.errors) }}"

```twig
{% block collection_widget -%}
    {% from 'SyliusResourceBundle:Macros:notification.html.twig' import error %}
    {% set attr = attr|merge({'class': attr.class|default ~ ' controls collection-widget'}) %}

    {% spaceless %}
        <div data-form-type="collection" {{ block('widget_container_attributes') }}
                {% if prototype is defined and allow_add %}
                    data-prototype='{{ _self.collection_item(prototype, allow_delete, button_delete_label, '__name__')|e }}'
                {%- endif -%}
        >
            {{ error(form.vars.errors) }}

            {% if prototypes|default is iterable %}
                {% for key, subPrototype in prototypes %}
                    <input type="hidden" data-form-prototype="{{ key }}" value="{{ _self.collection_item(subPrototype, allow_delete, button_delete_label, '__name__')|e }}" />
                {% endfor %}
            {% endif %}

            <div data-form-collection="list" class="ui three column stackable grid">
                {% for child in form %}
                    {{ _self.collection_item(child, allow_delete, button_delete_label, loop.index0) }}
                {% endfor %}
            </div>

            {% if prototype is defined and allow_add %}
                <a href="#" class="ui labeled icon button" data-form-collection="add">
                    <i class="plus square outline icon"></i>
                    {{ button_add_label|trans }}
                </a>
            {% endif %}
        </div>
    {% endspaceless %}
{%- endblock collection_widget %}
```

**Comment by tautelis** [comment]
I second @Niiko's request. There are two reasons why `{{ error(form.vars.errors) }}` shouldn't be there:
1. It is a widget block (not row)
2. Errors on collection appears twice

I hope this gets removed in upcoming versions.

![screen shot 2018-12-07 at 14 00 33](https://user-images.githubusercontent.com/6945396/49646709-962d7f00-fa28-11e8-816e-0750a1a263b7.png)

**Comment by tautelis** [comment]
Still there. https://github.com/Sylius/Sylius/blob/831cab3e2c961df4285a5932dcd0054ba2b374a8/src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig#L92
