### ISSUE TITLE
[DOC] Add promotionCoupon to Order through API

### ISSUE THREAD

**Issue by Adraesh** [Sylius/Sylius#8101]
> PATCH /api/v1/carts/{id}

id - url attribute - id of the cart

**Example**
```
$ curl http://demo.sylius.org/api/v1/carts/21 \
    -H "Authorization: Bearer SampleToken" \
    -H "Content-Type: application/json" \
    -X PATCH \
    --data '
        {
            "promotionCoupon": "BANANA"
        }
    '
```

**Exemplary Response**

`STATUS: 204 No Content`

Important note: To be performed after the Addressing step!

**Comment by pjedrzejewski** [comment]
Hi @Adraesh! Does it work for you? If yes, could you submit a PR to our documentation? :)

**Comment by Adraesh** [comment]
Hi @pjedrzejewski! Yes of course it worked for me.

To be honest, me and the PR.... :D More seriously I am not used to create PR ;)
