### ISSUE TITLE
[admin][product-reviews] 500 Internal Server Error - Twig_Error_Runtime

### ISSUE THREAD

**Issue by jarekkowol** [Sylius/Sylius#8105]
Hello, i found error when i enter to my.shop/app_dev.php/admin/product-reviews/

`CRITICAL - Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Method Proxies\__CG__\Sylius\Component\Core\Model\Product::__toString() must return a string value")." at /var/www/ex-dev/vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig line 61 `

Debian 8.8,
PHP 7.1.5

**Comment by pjedrzejewski** [comment]
@jarekkowol What is you locales configuration (both in admin and parameters.yml)?

**Comment by jarekkowol** [comment]
@pjedrzejewski 
First of all, I changed some configurations according to http://docs.sylius.org/en/latest/cookbook/disabling-localised-urls.html
This change worked correctly for me, locales was removed from url.

parameters.yml:
```
parameters:
    locale: pl_PL
```

**Comment by pjedrzejewski** [comment]
I could not reproduce this issue. Please reopen if still a problem.
