### ISSUE TITLE
Sylius/GUS broken comparison logic.

### ISSUE THREAD

**Issue by Arminek** [Sylius/Sylius#8108]
There is no comparison logic on Sylius side so actually notification widget will always display that new version of sylius is available.

**Comment by pjedrzejewski** [comment]
We should also record environment of the app.

**Comment by bitbager** [comment]
Could you please tell me what is the reason you want the environment to be recorded in notification context?

**Comment by lchrusciel** [comment]
We still want to fetch environment of an app, so the issue should stay open. 

@bitbager just for statistic reasons. We just would like to know how many production sites are online and how many are under development.

**Comment by bitbager** [comment]
How would you like to achieve it?

**Comment by pamil** [comment]
@bitbager #8267 :)
