### ISSUE TITLE
Dropping support for PHP 5.6 / 7.0

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#8114]
Hi folks!

After recent comments seen in issues (like #8107), core team discussions and many open-source projects requiring PHP 7+ in their next major releases, we came to the conclusions that it might be worth to consider dropping support for PHP 5.6 / 7.0.

Facts:
 - **PHP 5.6**: no active support, security support ends on December 2018
 - **PHP 7.0**: active support ends on December 2017, security support ends on December 2018
 - **PHP 7.1**: active support ends on December 2018, security support ends on December 2019
 - **Symfony 4.0**: to be released on November this year, meant to support PHP 7.1
 - **Doctrine 3.0**: meant to support PHP 7.2
 - **Sylius 1.0**: to be released this year, next major release in 2019, LTS versions with 4 years of security support (as #8107 mentions).

In addition to these, PHP 5.6 is a lot slower and makes quite a bit of weird false-positives on Travis CI. By introducing PHP 7.1 we could not only make use of new features (like `iterable` typehint, return typehints, scalar typehints) but also align Sylius with other open-source projects and libraries, while having active support for PHP issues.

After this RFC is settled we should also consider introducing some kind of process for adapting the new PHP releases.

We can vote using reactions on this message, 👍  for supporting PHP 7.1 only, 😆  for supporting PHP 7.0+, 👎  for supporting PHP 5.6+. Comments are appreciated for sharing your own experiences and thoughts! :)

**Comment by pamil** [comment]
As for security issues in PHP itself:
 - [Recorded PHP vulnerabilities by year](https://www.cvedetails.com/vendor/74/PHP.html)
 - [List of severe PHP vulnerabilities (CVE score >= 9)](https://www.cvedetails.com/vulnerability-list.php?vendor_id=74&product_id=&version_id=&page=1&hasexp=0&opdos=0&opec=0&opov=0&opcsrf=0&opgpriv=0&opsqli=0&opxss=0&opdirt=0&opmemc=0&ophttprs=0&opbyp=0&opfileinc=0&opginf=0&cvssscoremin=9&cvssscoremax=0&year=0&month=0&cweid=0&order=1&trc=495&sha=3a14a3e67be8aa88a16a1018e06ffe4e0d940af5)

**Comment by kochen** [comment]
Regardless of the code/performance benefits of PHP 7 over 5.6, I think @stefandoorn summarised well the effort required in a short time when a stable release is expected: https://github.com/Sylius/Sylius/issues/8106#issuecomment-304531821

**Comment by psihius** [comment]
Go for 7.1, it's a new software and 7.1 adoption looks good + 7.1 has some very important improvement followups over 7.0 branch that make developers life so much easier. And 7.0 is going to go into security maintenance mode at the end of the year already, so it's time to move on if there are no big obstacles.

**Comment by bruno-ds** [comment]
hello, back from holiday I discovered your announcement of Sylius v1.0.0-beta.3 (yay!) and your intention of dropping support for PHP 7.0.
I know that I react lately and I'm sorry for that, but here is my two cents about this : I use ubuntu 16.04 because this is the LTS, and for production I search stability. This version ship PHP 7.0. I searched and it seem te be a widely used solution ([Ondřej Surý's PPA](https://launchpad.net/~ondrej/+archive/ubuntu/php) but this is a PPA, I'd rather not use it in production (especially since my VM are "backed" by an AWS autoscalling group) because it is not maintained by canonical and I have trust issue and stability anxiety.

**Comment by psihius** [comment]
@bruno-ds sadly for you, it's too late. As you can see, this vote was taken at the end of May and was heavily discussed in Slack - almost unanimously has been decided that forward compatibility should be in line with next upcoming versions of Symfony and Doctrine being 7.1+ only too.

**Comment by TomasVotruba** [comment]
:+1: Good job!

I've added the project to https://gophp71.org/
