### ISSUE TITLE
Wrong 'order item percentage discount' promotions in cart

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#8118]
I have a weird situation currently regarding promotions. The shop I'm working on has about 10 products. 9 out of 10 products have each a single unique promotion rule assigned with the following settings (because they need to be switched on/off regularly):

* Exclusive = false
* Coupon based = 0
* Channel: only channel I have

Rules:
* Contains product: only selected the one single product it applies on

Actions:
* Item percentage discount
* Percentage: 25 (some have different percentages, but for this example I took 25)

Now I add one of these products to the cart (let's call it Product A), the normal price and the discounted price show perfect.

Then I add this single product to the cart that does not have promotions (let's call it Product B). The same 25% discount is also applied on this product (B). Which is not what I expected, as I expected 'order percentage discount' to do this, and not 'order item percentage'. I expected only discount on A.

Then I edit the promotion rule (connected to A) to exclude this product that has no promotions (so I exclude the product B). Then I update the cart, and only the product WITHOUT promotions (B) has 25% discount, but the product (A) that originally should have 25% discount does NOT have discount.

Behavior stays like this adding more products. A single product in the cart (regardless quantity) doesn't give problems. Quantities are never the problem.

I have the impression this is a bug, as I expected the action 'order item percentage' to only apply that discount to that single order line item and not to other order line items in the cart.

**Comment by gabiudrescu** [comment]
I had the same misunderstanding a few months ago. That's how I learned about the filter concept.

It makes sense somehow because actions apply on the entire cart, if the rules are true.

If you have that specific item in cart, then cart receives 25% discount.

If you want to give 25% discount on only one item in cart, then you also need to setup a filter for that promotion.

**Comment by stefandoorn** [comment]
Hm, that sounds a bit weird to me as then 'Item percentage discount' & 'Cart percentage discount' are nearly the same, plus no easy method to just give a single product discount. This shop only has 10 products, but imagine a shop with 4.000 in which you want to give 10 of them a discount. You then need to exclude 3.990 products on each of them?

Did some more testing. On Product A rule (25%) I excluded Product B. Product B does not have a promotion. Updated quantities in cart for both. Now Product A does NOT get discount, Product B get's the discount that Product A should have had..

**Comment by stefandoorn** [comment]
Maybe I'm misreading things. So I have to add the same product to the product filter probably to only apply it on this single product. The terms are a bit misleading, but that seems to do the job.

**Comment by gabiudrescu** [comment]
maybe this helps: https://github.com/Sylius/Sylius/issues/5772

**Comment by stefandoorn** [comment]
Ok, it was misunderstanding indeed. I'm afraid more people are going to run into this. It might be beneficial to have some help / help links to explanations in the admin, but for now this can be closed.
