### ISSUE TITLE
[SEO] [Product] SEO related fields in product forms are not used

### ISSUE THREAD

**Issue by Tykzz** [Sylius/Sylius#8126]
Are these fields planned to be removed?

**Comment by lchrusciel** [comment]
I haven't heard anything about that. But let's ask @pamil and @pjedrzejewski

**Comment by pjedrzejewski** [comment]
Not really, they are useful for small stores and do not do much harm to devs who handle SEO their own way.

**Comment by Tykzz** [comment]
How are they useful if not rendered in the product page?

**Comment by psihius** [comment]
The fact that they are not rendered by default does not mean you can't add those to render in like 1 minute :)
