### ISSUE TITLE
Installation: run gulp

### ISSUE THREAD

**Issue by adamostrogorski** [Sylius/Sylius#8129]
I install Sylius. I dont' have design. 

I can't run gulp.

If I follow instruction and run in acme directory:
`$ yarn run gulp`
I received ERROR: [Errno 2] No such file or directory: 'run'
(I have yarn in version 0.22 )

So I do this:
```
$ sudo apt-get install nodejs
$ sudo apt-get install npm
$ npm install gulp -g
$ npm install gulp
```

And if I run in acme directory:
`$ gulp`
I receive:
/usr/bin/env: „node”: There is no such file or directory

And if I run in acme directory:
`$ npm run gulp`
I receive:
> @ gulp /home/main/acme
> gulp

/usr/bin/env: „node”: There is no such file or directory

npm ERR! Linux 4.8.0-52-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "gulp"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @ gulp: `gulp`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @ gulp script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/main/acme/npm-debug.log

Can anyone help? What should I do?

[Ubuntu 16.04, nodejs v4.2.6, npm 3.5.2]

**Comment by Czende** [comment]
Maybe problem with node itself. Try to create symlink: 

```sudo ln -fs /usr/bin/nodejs /usr/local/bin/node```

**Comment by adamostrogorski** [comment]
Now I have gulp, but still not working design from sylius.

I have gup version:
CLI version 3.9.1
Local version 3.9.1

And if I run in acme dir:
`$ gulp`
I receive:
module.js:328
    throw err;
    ^
Error: Cannot find module 'gulp-chug'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/main/acme/Gulpfile.js:2:12)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

Why I don't get 'gulp-chug' during installation and how can I install this module (if this is a problem)?

In my acme dir I have file of gulp:
Gulpfile.js and package.json.

In Gulpfile I change from false on true and have:
```
var gulp = require('gulp');
var chug = require('gulp-chug');
var argv = require('yargs').argv;

config = [
    '--rootPath',
    argv.rootPath || '../../../../../../../web/assets/',
    '--nodeModulesPath',
    argv.nodeModulesPath || '../../../../../../../node_modules/'
];

gulp.task('admin', function() {
    gulp.src('vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Gulpfile.js', { read: true })
        .pipe(chug({ args: config }))
    ;
});

gulp.task('shop', function() {
    gulp.src('vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Gulpfile.js', { read: true })
        .pipe(chug({ args: config }))
    ;
});

gulp.task('default', ['admin', 'shop']);
```

and in package.json:
```
{
  "dependencies": {
    "jquery": "^2.2.0",
    "lightbox2": "^2.9.0",
    "semantic-ui-css": "^2.2.0"
  },
  "devDependencies": {
    "gulp": "^3.9.0",
    "gulp-chug": "^0.5",
    "gulp-concat": "^2.6.0",
    "gulp-debug": "^2.1.2",
    "gulp-if": "^2.0.0",
    "gulp-livereload": "^3.8.1",
    "gulp-order": "^1.1.1",
    "gulp-sass": "^2.3.0",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-uglify": "^1.5.1",
    "gulp-uglifycss": "^1.0.5",
    "merge-stream": "^1.0.0",
    "yargs": "^6.4.0"
  },
  "scripts": {
    "gulp": "gulp"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Sylius/Sylius.git"
  },
  "author": "Paweł Jędrzejewski",
  "license": "MIT"
}
```
Thanks for every support.

**Comment by Czende** [comment]
It seems you don't have other packages. Did you run `yarn install`? Have you in the root directory node_modules folder?

**Comment by adamostrogorski** [comment]
Yes, I have in root directory node_modules folder. 

Yes, I try run `yarn install` but I receive:` ERROR: [Errno 2] No such file or directory: 'install'.` But I check (`yarn --version`) and is seems, that I have yarn version 0.22. 

How can I install these other packages?

**Comment by adamostrogorski** [comment]
Solution:
`npm install`

**Comment by Czende** [comment]
Yes, npm as another package manager is solution, but it is strange that yarn doesn't work for you.

**Comment by lchrusciel** [comment]
Probably something related to @adamostrogorski environment. Please re-open if the problem will occur again. Also, support channel or StackOverflow will be a better place for such a questions.
