### ISSUE TITLE
Can't filter the items in the grid by a related entity property

### ISSUE THREAD

**Issue by DPvic** [Sylius/Sylius#8132]
I can not call deliveyDate, datetimepicker is a type created, and when I try to perform the filter, it gives this error:
![captura de pantalla 2017-06-05 a las 16 01 49](https://cloud.githubusercontent.com/assets/28042832/26786900/5f14c892-4a08-11e7-9378-38cfbfddd094.png)

fields:
 deliveryDate:
                    type: datetime
                    label: Fecha de entrega
                    path: shippingAddress.deliveryDate
                    options:
                        format: d-m-Y
....
filters:
                deliveryDate:
                    type: datetimepicker
                    label: Fecha desde hasta

**Comment by pjedrzejewski** [comment]
Please use sylius.org/slack or StackOverflow for support. It will be easier to understand your problem there.
