### ISSUE TITLE
[#TaxationBundle] - Class 'Sylius\Component\Taxation\Model\TaxRateInterface' does not exist

### ISSUE THREAD

**Issue by nietzscheson** [Sylius/Sylius#8133]
I’m tryng use the taxation-bundle in other project, outside the Sylius. I’m use the versión ^1.0@beta; throw me this error:
```console
[Doctrine\Common\Persistence\Mapping\MappingException]
  Class ‘Sylius\Component\Taxation\Model\TaxRateInterface’ does not exist
```
When doing *doctrine:schema:validate* shows me:
```console
[Mapping]  FAIL - The entity-class ‘Sylius\Component\Taxation\Model\TaxCategory’ mapping is invalid:
* The target entity ‘Sylius\Component\Taxation\Model\TaxRateInterface’ specified on Sylius\Component\Taxation\Model\TaxCategory#rates is unknown or not an entity.

[Mapping]  FAIL - The entity-class ‘Sylius\Component\Taxation\Model\TaxRate’ mapping is invalid:
* The target entity ‘Sylius\Component\Taxation\Model\TaxCategoryInterface’ specified on Sylius\Component\Taxation\Model\TaxRate#category is unknown or not an entity.
```
In the AppKernel:
```php
public function registerBundles()
{
        $bundles = [
             ...,
            new Sylius\Bundle\TaxationBundle\SyliusTaxationBundle(),
        }
}
```

Am I forgetting something? Can I use this bundle outside Sylius?

**Comment by lchrusciel** [comment]
@nietzscheson did you resolved your problem?

**Comment by pamil** [comment]
@nietzscheson have you fulfilled all steps listed in http://docs.sylius.org/en/latest/bundles/SyliusTaxationBundle/installation.html#adding-required-bundles-to-the-kernel?

**Comment by nietzscheson** [comment]
The problem persists. It is solved if I modify in this file the relation 

- https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/TaxationBundle/Resources/config/doctrine/model/TaxRate.orm.xml#L28[https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/TaxationBundle/Resources/config/doctrine/model/TaxRate.orm.xml#L28]

- TaxCategoryInterface

 by ---

TaxCategory

My project does not use interfaces for the relationship; I do not have it configured as configured by Sylius. I would believe when using interfaces by entities, it would work ...
