### ISSUE TITLE
sylius.form.type.checkout_complete.validation_groups not working

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#8135]
I'm using Sylius version dev-master@b3d47c5.

Setting the 'sylius.form.type.checkout_complete.validation_groups' to [sylius, app_checkout_complete] doesn't seem to do anything. 

When I open the profiler to see what the `Sylius\Bundle\CoreBundle\Form\Type\Checkout\CompleteType` gets injected on the last step of checkout, it seems 'sylius_checkout_complete'.

It's not an huge issue, as I can also add my validation to 'sylius_checkout_complete', but it seems odd looking at the documentation about how to add custom validation rules.

**Comment by lchrusciel** [comment]
`sylius_checkout_complete` is [hard coded](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ShopBundle/Resources/config/routing/checkout.yml#L88-L91) in routeing. Can you check what will happen if you will override the routeing?

**Comment by lchrusciel** [comment]
Similar problem will be with API

**Comment by stefandoorn** [comment]
Haven't been able to test it yet, but I think it's still an issue as it doesn't relate with the docs.
