### ISSUE TITLE
SyliusSettingsBundle deprecated?

### ISSUE THREAD

**Issue by jmontoyaa** [Sylius/Sylius#8136]
Is the SyliusSettingsBundle going to be deprecated from the https://github.com/Sylius/Sylius package?
I have seen that it has not been updated since a year ago. If yes, then how you manage settings in the current Sylius/Sylius package? Via only Resources?

**Comment by pjedrzejewski** [comment]
@jmontoyaa It has been already removed from the core, as we do not use it. Most of configurations have moved to Channel resources. That being said, the bundle is usable as standalone and if you would like to develop it further - we will be happy to "donate" it to another organization/dev.

**Comment by jmontoyaa** [comment]
That sounds good, I'm using it for https://github.com/chamilo/chamilo-lms/ (version 2).
But I found some composer issues. I just fork it here:

https://github.com/chamilo/SyliusSettingsBundle

**Comment by mbabker** [comment]
@pjedrzejewski It might be a good idea for someone to update Packagist to mark which packages are abandoned, there's still a lot of stuff like the metadata bundle listed there and that would be good to mark what's not in core anymore.

**Comment by jmontoyaa** [comment]
I agree with @mbabker. The same with the https://github.com/Sylius/SyliusFlowBundle I used to use it but now it seems abandoned.
