### ISSUE TITLE
[ResourceBundle] Mass update - how to?

### ISSUE THREAD

**Issue by psihius** [Sylius/Sylius#8141]
So, I'm required to make front-end mass-edit functionality for a specific place (billing/shipping address editing - don't ask why, just has to be done and I can't change it). I don't really want to do a complete custom action that circumvents the ResourceBundle logic and standard way of doing things (future proofing).

I tried to implement it based on the updateAction, but I ended up with Factory raising errors because it expects a single entity, not an array. After looking at it for a while, I just don't know how to adjust stuff, hence I would like to request some help here. For the time being I don't ask it to be in the core - I completly happy with just overriding the controller and adding my custom action.
There were a few questions regarding this functionality on the Slack too, so i'm not the only one.  Maybe this can be a good start for an initial PR that may evolve into a proper support for this feature.

**Comment by 4oXdev** [comment]
It can be a good feature!

**Comment by pjedrzejewski** [comment]
Duplicate of #93. :) I think we need to finally do it. :D
