### ISSUE TITLE
[ResourceBundle] Disabling Pagination doesn't work

### ISSUE THREAD

**Issue by 4oXdev** [Sylius/Sylius#8142]
I tried disabling pagination by route configuration. It doesn't work.
    defaults:
        _sylius:
            paginate: false

ResourceGridView {▼
  -metadata: Metadata {▶}
  -requestConfiguration: RequestConfiguration {▶}
  -data: Pagerfanta {▼
    -adapter: DoctrineORMAdapter {▶}
    -allowOutOfRangePages: false
    -normalizeOutOfRangePages: true
    -maxPerPage: 10
    -currentPage: 1
    -nbResults: 14
    -currentPageResults: ArrayIterator {▶}
  }

**Comment by Mipme** [comment]
Hm, i have some routes where it is actually working. Can you post the whole route definition?

**Comment by pjedrzejewski** [comment]
@4oXdev You can't disable pagination on grids atm. It works with non-grid indexActions.

**Comment by Mipme** [comment]
Was just running into the same problem again and the machines seem to work this way:

1. Route + Grid;
2. On Grid i had limits: ~
3. Then on Route setting paginate: false --> Pagerfanta ERROR/Exception

2b. On Grid setting limits: [10000]
3. Route->paginate: false --> No Error

Setting the limit to 10.000 should be equivalent to no limit and no pagination in most cases.
For the moment its a workaround, but definitely not a nice thing to do.
