### ISSUE TITLE
When editing variant, the connected product option values are not preselected in form

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#8144]
On the product variant edit page in CMS (`admin/products/229/variants/61249/edit`), there is a list of options with select inputs. In the database the links are set correct, but the form choices show 'Select an option'.

**Comment by pjedrzejewski** [comment]
Can you reproduce this on clean Sylius-Standard install?

**Comment by pjedrzejewski** [comment]
Could not reproduce on latest Sylius. Please reopen if still an issue.

**Comment by stefandoorn** [comment]
I can confirm this still exists on a v1.2.x installation. I unfortunately have no clue why it occurs though. It seems the same as issue as #8999. Weird thing is that client created product on staging and had the options available, now did it at production and no options shown. I will try to figure out what they've done differently this time (e.g. order of adding things).

**Comment by nbjohan** [comment]
@stefandoorn There was a PR some time back, which has not been merged (afaik). Maybe this is useful to you: https://github.com/Sylius/Sylius/pull/9223
