### ISSUE TITLE
[FixturesBundle] How can I uninstall default fixtures?

### ISSUE THREAD

**Issue by adamostrogorski** [Sylius/Sylius#8148]
How can I uninstall default fixtures? Manual deleting is inconvenient. Is there a better way?

**Comment by gabiudrescu** [comment]
redo a sylius install and be careful to opt for "no" when you are asked if you want to install demo data?

**Comment by pjedrzejewski** [comment]
@adamostrogorski Please use Slack (sylius.org/slack) for such questions and what @gabiudrescu said is correct. :) Thanks!
