### ISSUE TITLE
[ResourceBundle] Symfony Flex compatibility.

### ISSUE THREAD

**Issue by adamelso** [Sylius/Sylius#8150]
Symfony Flex is great, but as I expected I am having issues making it work with the Sylius ResourceBundle.

Some of them were quite easy to solve - Whereas the Symfony Standard Edition installs all Symfony libraries, Symfony Flex works by only installing what is needed. So I had to explicitly install Symfony OrmPack and Symfony Asset, and enable framework.session and framework.templating.engines.

However once I did that, I found making JSON requests would attempt to return an HTML response. Command used to test this was the one provided by the docs:

    curl -i -X GET -H "Accept: application/json" http://localhost:8000/books/

Response

    Unable to find template "/index.html.twig"

**Comment by jrobeson** [comment]
what's your resource bundle configuration?
