### ISSUE TITLE
Register when you put always_authenticate_before_granting to true in security.yml fails

### ISSUE THREAD

**Issue by jdeveloper** [Sylius/Sylius#8151]
The registering works but then when sylius tries to authenticate, it is not able to do it so it is redirecting continuously to login page.

If I put a a die to get the exception message in Symfony\Component\Security\Http\Firewall\ExceptionListener::onKernelException I got the following messages:

No Authentication Provider found for token of class "Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken".

I also tried it with the exact config of security.yml of the sylius project and with just setting ```always_authenticate_before_granting: true``` the register process fails.

**Comment by jdeveloper** [comment]
The problem was that in security.yml a named the firewal for sylius different. I named it main instead of shop.

Would it be possible to configure the name of the shop firewall and set it by default to shop?

**Comment by pjedrzejewski** [comment]
👍  @jdeveloper Could you submit a PR?

**Comment by jdeveloper** [comment]
@pjedrzejewski I'm sorry for the delay, I hope that it is well the way I implemented it

**Comment by pjedrzejewski** [comment]
@jdeveloper Everything fine, thanks!
