### ISSUE TITLE
Add product attribute not works

### ISSUE THREAD

**Issue by ginodm** [Sylius/Sylius#8157]
Hi all,
I'm a new on sylius, I have installed the version 1 beta2.
I have a bit problems when i try to add a new product attribute.

When I select a new attribute and I click on the button add attributes product page is reloaded but the new attribute is not loaded.

Thanks

**Comment by tchapi** [comment]
Hi - have you built the backend assets ? (You might be missing some JS especially)

    $ yarn install
    $ yarn run gulp

**Comment by ginodm** [comment]
Hi @tchapi  
thanks. The installation procedure was not completed sucessyful and the assets non instal correctly.

Now works.

**Comment by tchapi** [comment]
Perfect, you can close this issue then
