### ISSUE TITLE
[Documentation][Theme] Remove the asset override feature from the doc

### ISSUE THREAD

**Issue by Colmea** [Sylius/Sylius#8161]
Hello Sylius team,

When creating a theme, override template works really well, but not static files (images, css, js, ...).
After a discussion on Slack, it appears this feature doesn't work/exist in Sylius.

If it's the case, we should remove it from the doc (in the Theme Book):
http://docs.sylius.org/en/latest/book/themes/themes.html#how-to-create-themes  (last note at the end of the page)

![image](https://user-images.githubusercontent.com/974918/27081617-8813b868-5041-11e7-93ae-68250fb575e0.png)

 Or even add a specific note to explain how to add custom CSS/JS (import a new CSS/JS file in the layout).

I can send a PR if wanted

**Comment by pjedrzejewski** [comment]
@Colmea Would be awesome to get a PR for this, thanks Arthur!

**Comment by Mipme** [comment]
Since i am using node-sass and other npm functions to build the theme assets, i simply added a copy-my-assets-script. I can contribute that to the docs if interested...

**Comment by Colmea** [comment]
@pjedrzejewski What do you think about adding a custom Gulpfile into Sylius Demo project ? 
This implies to have a built-in custom theme in the repository, but this way users have a custom theme + override assets "out of the box".

I can make a PR if you find this interesting

**Comment by lchrusciel** [comment]
I think simple cookbook will be easier to maintain, so I would vote tor @Mipme proposal. /cc @pjedrzejewski @pamil

**Comment by pjedrzejewski** [comment]
@Colmea I would say let's have both base file & coobook? That would be huge help!

**Comment by pjedrzejewski** [comment]
@Colmea Hi Arthur! Will you find a moment to push a PR for this? Would be huge help before 1.0.0. :)
