### ISSUE TITLE
Cannot delete address used in an order

### ISSUE THREAD

**Issue by silverbackdan** [Sylius/Sylius#8168]
When a shop user attempts to delete one of their addresses that has been previously used in an order, they cannot due to a foreign key constraint. Possibly this exception could be caught and archive the address when a user attempts to delete it instead (just hide it from the user). I'm not sure the best way to go about implementing this as it'll probably involve adding functionality to the resources bundle to allow for archiving.

**Comment by silverbackdan** [comment]
Is a potential solution to disassociate the address with the Shop User's account so it won't appear in their list? Perhaps that'd be a way that involves less complications...

**Comment by pjedrzejewski** [comment]
This should not be the case, as the addresses are cloned, never used directly from address book. Could you provide a scenario to reproduce this issue on clean sylius-standard?

**Comment by silverbackdan** [comment]
I can't replicate on your demo website, it may have been an issue in the Beta 2 release or something in my website somewhere. Sorry about that. Closing now.

**Comment by silverbackdan** [comment]
Sorry, it is a bug.
1. Make sure no items in cart
2. Login as user and set a default shipping method
3. Add an item to basket
4. Check the cloned address in database, it has a customer ID

Fix proposed by @michalmarcinkowski 
ShopBasedCartContext::setCustomerAndAddressOnCart
```php
if (null !== $defaultAddress) {
    $cart->setShippingAddress(clone $defaultAddress);
}
```
should change to
```php
if (null !== $defaultAddress) {
    $clonnedAddress = clone $defaultAddress;
    $clonnedAddress->setCustomer(null);
    $cart->setShippingAddress($clonnedAddress);
}
```

**Comment by lchrusciel** [comment]
@silverbackdan are you willing to open a PR? Could you also add a behat scenario for that to avoid regression in the future?

**Comment by silverbackdan** [comment]
I'm not as familiar with behat but will make a PR with all issues that you've requested me to create a PR for in one and will look at behat. Cheers.
