### ISSUE TITLE
AddressingBundle depends on AdminApiBundle

### ISSUE THREAD

**Issue by MichaelKubovic** [Sylius/Sylius#8171]
In our custom installation we only extend CoreBundle, having all frontend bundles custom (admin, shop). Default serializer tries to serialize Order resource, which boils down to serializing Zone model, which has hardcoded route sylius_admin_api_zone_show for Hateoas relation.

I propose moving relations section of serializer configuration from core bundles to bundle which defines the route, in this case AdminApiBundle. I'd be glad to submit PR upon approval.

**Comment by pjedrzejewski** [comment]
@MichaelKubovic What version are you using? I believe we fixed this in #8115?

**Comment by MichaelKubovic** [comment]
Using dev-master. Unfortunatelly some bundles still have hardcoded routes, ie., https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AddressingBundle/Resources/config/serializer/Model.Zone.yml which results into 'None of the chained routers were able to generate route: Route 'sylius_admin_api_zone_show' not found'

**Comment by MichaelKubovic** [comment]
Shall I move them all to AdminApiBundle like in #8115?

**Comment by MichaelKubovic** [comment]
please have a look at PR, if you are ok with it I'll browse other components before it's merged.

**Comment by pjedrzejewski** [comment]
Currently not possible, I will leave the PR open but close this issue.
