### ISSUE TITLE
[Review] Why title is required ?

### ISSUE THREAD

**Issue by loic425** [Sylius/Sylius#8172]
On many websites, you can rate something without comment it.
On Review model, comment is nullable but title is not, it's weird. On few projects, I use review bundle in this use case and I needed to work around.

What do you think ?

**Comment by pjedrzejewski** [comment]
I think we could make it nullable, it is always easier to add NotBlank, than to remove it. :)

**Comment by pjedrzejewski** [comment]
@Sylius/core-team Thoughts? @Zales0123.

**Comment by Zales0123** [comment]
Totally agreed 👍  After all, even a lonely rating is a valid review for the product and it's the only field that should be required.

**Comment by loic425** [comment]
@pjedrzejewski @Zales0123 
I think i can work on it soon.

**Comment by loic425** [comment]
@pjedrzejewski @pamil Now I think I could work on this soon :) sorry for the delay.

**Comment by pamil** [comment]
Awesome, thanks! No worries :)
