### ISSUE TITLE
Can't clear cache after update

### ISSUE THREAD

**Issue by padalec** [Sylius/Sylius#8174]
Hi,
after update to beta 2 I had this error:
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception

                                                                                                                      
  [RuntimeException]                                                                                                  
  An error occurred when executing the "'cache:clear --no-warmup'" command:                                           
  PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: Tag "<argumen  
  t>" with type="service" has no or empty "id" attribute in "/home/vagrant/sites/earlybird/vendor/sylius/sylius/src/  
  Sylius/Bundle/ThemeBundle/DependencyInjection/../Resources/config/services/integrations/assets.xml". in /home/vagr  
  ant/sites/earlybird/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php:484   
  Stack trace:                                                                                                        
  #0 /home/vagrant/sites/earlybird/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLo  
  ader.php(279): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->getArgumentsAsPhp(Object(DOMElement), '  
  argument', '/home/vagrant/s...', false, false)                                                                      
  #1 /home/vagrant/sites/earlybird/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLo  
  ader.php(143): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseDefinition(Object(DOMElement), '/h  
  ome/vagrant/s...', Array)                                                                                           
  #2 /home/vagrant/sites/earlybird/vendor/symf in /home/vagrant/sites/earlybird/vendor/symfony/symfony/src/Symfony/C  
  omponent/DependencyInjection/Loader/XmlFileLoader.php on line 484

**Comment by tchapi** [comment]
This was fixed in #8031 (current master)

**Comment by padalec** [comment]
Thanks this error disappear but I have  another one:
```
The file "alias: sylius.order
path: '" does not exist in /home/vagrant/sites/ch.earlybird/vendor/sylius/sylius/src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/cart.yml (which is being imported from "/home/vagrant/sites/ch.earlybird/vendor/sylius/sylius/src/Sylius/Bundle/AdminApiBundle/Resources/config/routing/main.yml").
```

**Comment by tchapi** [comment]
See https://github.com/Sylius/Sylius/issues/8165

**Comment by lchrusciel** [comment]
Closing as a duplication of #8178 

Thanks, @tchapi.
