### ISSUE TITLE
Symfony 3.3 and the CoreBundle Kernel

### ISSUE THREAD

**Issue by mbabker** [Sylius/Sylius#8181]
Symfony 3.3 deprecates the `getRootDir()` method in the Kernel class and the `%kernel.root_dir%` container parameter in favor of `getProjectDir()` and `%kernel.project_dir%`.  These new params are designed to resolve to your project root instead of the `app/` dir.  This creates a bit of a quirk with the `Sylius\Bundle\CoreBundle\Application\Kernel` class because `getProjectDir()` by default works by traversing up the directory chain until it finds a `composer.json` file, which will be found in the core bundle's root.  Since this class is not abstract, it's entirely possible (but you're borderline crazy if you're doing so) for someone to set up an app and just use that kernel without subclassing it any further, this could theoretically cause `getProjectDir()` to resolve to the wrong directory.

Just shooting from the hip, there are a couple ways to deal with this:

- Remove the core bundle's `composer.json`, it's been said already that this bundle isn't usable in a standalone manner similar to other Sylius packages, this will also mean at least unregistering it from Packagist (maybe the subsplit can be killed too)
- Make the class abstract and require an `AppKernel` class, which is already happening anyway in this repo and the Sylius Standard repo to load the admin, shop, and admin API resources; but, this comes with a B/C break for anyone who might have set up an app just using the core bundle's Kernel class without a subclass

**Comment by pjedrzejewski** [comment]
I'd go ahead and remove the composer.json file from CoreBundle. @Sylius/core-team wdyt?
