### ISSUE TITLE
Shipping Calculators w/ Item Count Dependency Bug

### ISSUE THREAD

**Issue by silverbackdan** [Sylius/Sylius#8183]
In the shipping calculators (the main one affected being the flat rate per item) they use this to find out number of items:
```php
$totalItems = $subject->getShippingUnitCount();
```
When in the basket, if you increase a product quantity from 1 to 2, the shipping updates correctly. Then decrease from 2 back to 1 and you have to press update/save cart twice to get the correct shipping calculation.

A quick workaround:
```php
$totalItems = 0;
foreach( $subject->getOrder()->getItems() as $item )
{
    if( $item->getVariant()->isShippingRequired() )
    {
        $totalItems+=$item->getQuantity();
    }
}
```
Not sure if that's the best approach or not, but it works for me at the moment.

**Comment by silverbackdan** [comment]
That was a bad workaround. This works as suggested to me by @michalmarcinkowski 
```php
public function process(BaseOrderInterface $order)
    {
        /** @var OrderInterface $order */
        Assert::isInstanceOf($order, OrderInterface::class);

        if ($order->isEmpty()) {
            $order->removeShipments();

            return;
        }

        $shipment = $this->getOrderShipment($order);

        if (null === $shipment) {
            return;
        }

        foreach ($order->getItemUnits() as $itemUnit) {
            if (null === $itemUnit->getShipment()) {
                $shipment->addUnit($itemUnit);
            }
        }
// ADD THIS LOOP
        foreach ($shipment->getUnits() as $itemUnit) {
            if (null === $itemUnit->getOrderItem()->getOrder()) {
                $shipment->removeUnit($itemUnit);
            }
        }

        if (!$this->orderShippingMethodSelectionRequirementChecker->isShippingMethodSelectionRequired($order)) {
            $shipment->setMethod($this->defaultShippingMethodResolver->getDefaultShippingMethod($shipment));
        }
    }
```

I do a PR when I get a chance along with other issues I've raised unless someone else beats me to it.

**Comment by michalmarcinkowski** [comment]
Unfortunately the above snippet is only a quickfix. This issue just uncovered a bigger issue -incorrect state of objects. It's probably not the only place affected by this core issue. It needs deeper investigation and a proper fix.

**Comment by lchrusciel** [comment]
Maybe a good start point would be to add a shipment cleaner as one of the first processors in order to always have "a clean" start in resolving. Anyway, this logic should be reconsidered one way or another.

**Comment by Zales0123** [comment]
I'm pretty should it was fixed by https://github.com/Sylius/Sylius/pull/8352. Just checked it looking into database and everything works fine. @silverbackdan Please, reopen if you find it unresolved ;)
