### ISSUE TITLE
Upgrade JMS Serializer Bundle to 2.0

### ISSUE THREAD

**Issue by emodric** [Sylius/Sylius#8193]
#8186 disabled aliasing `@serializer` service to `@jms_serializer.serializer` to increase compatibility with 3rd party addons for Sylius.

JMS Serializer Bundle in v2 disabled aliasing altogether, so probably the best course of action would be to upgrade the bundle to 2.0 instead of disabling the alias. However, it appears that Serializer Bundle 2.0 currently breaks Sylius, so this issue is opened as per @lchrusciel's instructions to track the progress.

**Comment by pamil** [comment]
I'm all for it after #8117 is merged, it seems like the only issue Serializer 1.7 causes is the one with taxons' root / parent serialization, we should figure it out on its own how much data should we show for these endpoints.

**Comment by emodric** [comment]
<3
