### ISSUE TITLE
Disable InventoryBundle

### ISSUE THREAD

**Issue by davidromani** [Sylius/Sylius#8194]
Hello.

It's possible to disable all the stock management layers?

Thx.

**Comment by lchrusciel** [comment]
No - if you are using core bundle.
Yes - if you will create your own solution on a top of most bundles(without Admin, AdminApi, Shop and Core).

It should not get in your way too much if you just won't trace items

**Comment by pjedrzejewski** [comment]
@davidromani You can set "tracked" to false on the ProductVariant, which will assume that there is always enough stock.

**Comment by davidromani** [comment]
thx @pjedrzejewski 

I saw this setting after open this issue, my apologies.

**Comment by pjedrzejewski** [comment]
@davidromani No worries, glad I could help!
