### ISSUE TITLE
Adding Search Box to homepage

### ISSUE THREAD

**Issue by KirbyFox** [Sylius/Sylius#8204]
Could someone please explain how to add a search box to the homepage of my Sylius website?

I've tried using Sylius Search Bundle but that seems to be buggy and the config sample seems to be out of data.

I noticed that http://demo.sylius.org doesn't include a search box on the homepage, so maybe this is not possible.

I'd be grateful for any help please.

**Comment by lchrusciel** [comment]
@KirbyFox such a support request should be asked on our slack channel or on Stackoverflow. Somebody will be willing to help you for sure.

According to your problem, a possible solution is to add ElastichSearchPlugin to your instance, build search indexes and just embed controller to your shop.

Anyway, closing as it is not a Sylius issue.
