### ISSUE TITLE
Different gatway configurations depending app environment

### ISSUE THREAD

**Issue by jdeveloper** [Sylius/Sylius#8209]
Hi

I want to configure different configurations for the same gateway on database depending on the app environment. I create different entries on ```sylius_payment_method``` with different environments pointing to different gateway configs of the same gateway factory method. But when I go to checkout page to select payment method, all payment methods of all environmets appear.

Is it currently possible to have different configurations depending on the environment?

**Comment by lchrusciel** [comment]
If you understand `environment` as a `channel` then yes. Just provide different channels for different environments and you could configure not only different payments but product pricing and available shipping methods as well. 

Please, ask such a question on our slack :)
