### ISSUE TITLE
Compatibility with doctrine/orm >2.5

### ISSUE THREAD

**Issue by Chrysweel** [Sylius/Sylius#8211]
Hello.

I see that with
```
            "name": "doctrine/orm",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "https://github.com/doctrine/doctrine2.git",
                "reference": "388afb46d0cb3ed0c51332e8df0de9e942c2690b"
            },
```

There are one conflict in declaration function count.

>https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/EntityRepository.php#L208

Sylius have error:
> Warning: Declaration of Sylius\Bundle\OrderBundle\Doctrine\ORM\OrderRepository::count() should be compatible with Doctrine\ORM\EntityRepository::count(array $criteria)

Same problem in 
>Warning: Declaration of Sylius\Bundle\CoreBundle\Doctrine\ORM\CustomerRepository::count() should be compatible with Doctrine\ORM\EntityRepository::count(array $criteria)

This problem is easy. Include in OrderRepository and OrderRepositoryInterface function count the parameter array $criteria.

Do you want a pull request ?

**Comment by pamil** [comment]
`dev-master` points to branch for future Doctrine 3.0 release, which can still introduce new BC breaks so there is no sense to support it in Sylius now.

**Comment by Chrysweel** [comment]
Ok.

**Comment by koemeet** [comment]
Now that doctrine v2.6.0 (https://github.com/doctrine/doctrine2/releases/tag/v2.6.0) is released, it may be a good idea to revisit this.
