### ISSUE TITLE
[Documentation] How to embed a list of products into a view

### ISSUE THREAD

**Issue by KirbyFox** [Sylius/Sylius#8212]
https://github.com/Sylius/Sylius/blob/master/docs/cookbook/embedding-products.rst

The code throws the following error:

An exception has been thrown during the rendering of a template ("[Semantical Error] line 0, col 142 near 'taxon WHERE o.enabled': Error: Class Sylius\Component\Core\Model\Product has no association named taxons”).

**Comment by lchrusciel** [comment]
A product does not have relation to Taxon anymore. We have introduced a new concept of productTaxon. Docs are just outdated. Thank for reporting! :)

**Comment by mrbase** [comment]
@KirbyFox just fell over this as well - this works, don't know if its 100% correct tho :)

```php
public function findLatestByChannelAndTaxonCode(ChannelInterface $channel, $code, $count)
{
    return $this->createQueryBuilder('o')
        ->innerJoin('o.channels', 'channel')
        ->andWhere('o.enabled = true')
        ->andWhere('channel = :channel')
        ->innerJoin('o.productTaxons', 'productTaxons')
        ->addOrderBy('productTaxons.position', 'asc')
        ->innerJoin('productTaxons.taxon', 'taxon')
        ->andWhere('taxon.code = :code')
        ->setParameter('code', $code)
        ->setParameter('channel', $channel)
        ->setMaxResults($count)
        ->getQuery()
        ->getResult();
}
```

**Comment by Mipme** [comment]
Maybe we could also explain why there is a `mainTaxon` and a `productTaxon`... I am still puzzled by that my self!

**Comment by hamad251** [comment]
Its bring products from all locales ! , How can Limit it to current locale ?
