### ISSUE TITLE
Problem installing on server.

### ISSUE THREAD

**Issue by juanitourquiza** [Sylius/Sylius#8216]
I am in digitalocean inside my droplet and I use this code:
`composer create-project -s beta sylius / sylius-standard acme`

It downloads everything perfect but when using this:
`php bin / console sylius: install`

It shows me the error:

> Could not open input file: bin / console

There are several files that are not downloaded inside folder bin

Try using git by making a clone and then use the same statement but it gives me an error in autoload.php

Any solution??

Regards

**Comment by lchrusciel** [comment]
It seems, that you can have a problem with permissions or something for related to your server. Please, ask such a question on our support channel at Slack on Stackoverflow.
