### ISSUE TITLE
[QA] How to change locale code to ISO 639-1?

### ISSUE THREAD

**Issue by liverbool** [Sylius/Sylius#8229]
Hi All,

How i can change my route to ISO 639-1 code? 

for example: `/en_US/` change to `/en/`

Thanks.

**Comment by lchrusciel** [comment]
It should be possible out-of-the-box. Do you have any exception when defining it like this?

**Comment by liverbool** [comment]
Oops!

I got this message `The "en" locale is unavailable in this channel.`
We've store `en_US` to our `sylius_locale` right?

**Comment by lchrusciel** [comment]
Try to add a regular English locale(en) to locales, then go to the channel configuration and change a default locale together with choosing appropriate English from the multi-select checkbox. I just have created a sample configuration on our demo if you would like to take a look.

Just as a reminder, the products could disappear from shop, cuz they would need a fallback in default locale and something is not playing well with our fallback system

**Comment by liverbool** [comment]
I thinks that we have to decorate `LocaleType` to have new locale code and must to migrate data to change locale code if we have already exists data, right @lchrusciel ?

**Comment by lchrusciel** [comment]
I think only migration will be required. The `en` locale code should be available.

**Comment by liverbool** [comment]
👍 @lchrusciel I see that Symfony Locale contains both ISO `639-1`, `3166-1`.

https://symfony.com/doc/current/reference/constraints/Locale.html

>Validates that a value is a valid locale.
>The "value" for each locale is either the two letter ISO 639-1 language code (e.g. fr), or the language code followed by an underscore (_), then the ISO 3166-1 alpha-2 country code (e.g. fr_FR for French/France).

My country is no difference between language code `th_TH` and local code `th`. I have a bit confused

Thanks you so much @lchrusciel 😃  and feel free to close this issue.

**Comment by lchrusciel** [comment]
Perfect 👍
