### ISSUE TITLE
Assets strange behavior

### ISSUE THREAD

**Issue by roberto910907** [Sylius/Sylius#8232]
I've created a new theme in **app/themes** and i want to override some SyliusShopBundle templates, so what I've done is to copy a css file **style.css** in app/themes/MyTheme/SyliusShopBundle/public/css/style.css, after that, I have executed `php bin/console sylius:theme:assets:install --symlink` but when my page loads I'm getting 404 Not Found for the css file. I open the browser profile and the url generated is "http://sylius.local/bundles/_themes/proveedor/my-theme/_themes/proveedor/my-theme/syliusshop/css/style.css". It seems the asset component is generating twice this part "_themes/proveedor/my-theme". I tested the commando without "--symlink" option, I cleared the cache with command and manually but its not working.

I really dont understand what its happening here. Could someone help me to solve this issue?

**Comment by lchrusciel** [comment]
Can you join our Slack and ask this question on support channel?
