### ISSUE TITLE
Page show order in device mobile

### ISSUE THREAD

**Issue by Chrysweel** [Sylius/Sylius#8233]
Hello.

The page to visualize an order in a small resolution has a table which is not useful.

It show all headers first, and after show all data...

Here a capture screen

![page-show-order-top](https://user-images.githubusercontent.com/1416870/27782637-95991c34-5fd3-11e7-88db-73674a4b3f26.png)

And when you doing scroll you see....

![page-show-order-botton](https://user-images.githubusercontent.com/1416870/27782638-959b8e4c-5fd3-11e7-9c93-024313b6ff18.png)
It could to be an error to fix ?

**Comment by lchrusciel** [comment]
Feel free to help us with this :)
