### ISSUE TITLE
[Sylius demo] Error reporting is enabled on the server

### ISSUE THREAD

**Issue by bitbager** [Sylius/Sylius#8234]
Accessing http://demo.sylius.org/en_US/admin throws `Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to FOS\RestBundle\Controller\ExceptionController::__construct() must be an instance of FOS\RestBundle\View\ViewHandlerInterface, none given, called in /app/var/cache/prod/classes.php on line 4218 in /app/vendor/friendsofsymfony/rest-bundle/Controller/ExceptionController.php:43 Stack trace: #0 /app/var/cache/prod/classes.php(4218): FOS\RestBundle\Controller\ExceptionController->__construct() #1 /app/var/cache/prod/classes.php(4908): Symfony\Component\HttpKernel\Controller\ControllerResolver->instantiateController('FOS\\RestBundle\\...') #2 /app/var/cache/prod/classes.php(4214): Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver->instantiateController('FOS\\RestBundle\\...') #3 /app/var/cache/prod/classes.php(4901): Symfony\Component\HttpKernel\Controller\ControllerResolver->createController('FOS\\RestBundle\\...') #4 /app/var/cache/prod/classes.php(4155): Symfony\Bundle\FrameworkBundle\Controller\ControllerR in /app/vendor/friendsofsymfony/rest-bundle/Controller/ExceptionController.php on line 43` error. 

Enabled error reporting on the production server is something that may scare a little bit new Sylius users. The other thing is that this error should not appear and it doesn't as far as I am concerned with the beta2 version.

**Comment by lchrusciel** [comment]
The problem will be solved with the newest release.
