### ISSUE TITLE
Display promo price on product page

### ISSUE THREAD

**Issue by akorchaginn** [Sylius/Sylius#8249]
Hi!
How to calculate the price of product promotion on the product page?
For example, I create an advertising campaign with the "Contains product" type and select several products. The price for selected products is displayed in the cart, but not is displayed on homepage or product page.

**Comment by lchrusciel** [comment]
Sylius doesn't support this kind of promotion by default. Current implementation allows for cart promotions only, so something like `10% discount for your cart`. If you would like to have catalog promotions(so the one presented in a product catalog) try [UrbanaraCatalogPromotionPlugin](https://github.com/URBANARA/UrbanaraCatalogPromotionPlugin).
