### ISSUE TITLE
Missing Translations

### ISSUE THREAD

**Issue by Cathmor** [Sylius/Sylius#8252]
Not sure if this is a Sylius or if it's a Symfony issue but I had a mostly functioning (still under construction) site and then had to install something with composer. Since I was at it I also thought I would run a composer update for Symfony so I am currently as 3.3.3. Most things seem to be working fine but now my translations aren't loading. So my links in the footer show the sylius.ui.about format instead of the "About" translation. And this is for all translations that I see. I changed nothing about the local or had overridden or custom translations so everything should have been coming from the sylius package in the vendor folder. I ran debug:translation and showed no translations. So I tried adding some a translations/messages.en.yml in app/Resources/ to see if it wasn't loading properly and they're still missing on the site. BUT, if I run debug:translation in the console, all the translation show up as unused. 

Anyone else run into this?

**Comment by tchapi** [comment]
Are you on the latest master ? Seems to be related to https://github.com/Sylius/Sylius/pull/8159

**Comment by Cathmor** [comment]
No, I'm on beta2 and I seem to be missing the changes in that PR so I guess that is the issue.  I should check the PRs more often. Thanks!
