### ISSUE TITLE
Impersonate user from admin authenticate previously in shop, fails assignin customer shopping

### ISSUE THREAD

**Issue by jdeveloper** [Sylius/Sylius#8254]
Scenario:

I login as a normal user in the shop and begin to add items to the cart.

If now I authenticate in the admin, pick a customer and press impersonate and go back to the shop area, the user authenticated is in fact the impersonated user. But the impersonated user has now the cart of the previous user so, when the user end with checkout, the associated user is the one of the beginning.

Related issue: #8127 

See comments in the related issue where it is discussed a possible solution-

**Comment by pjedrzejewski** [comment]
Fixed, thanks for reporting!
