### ISSUE TITLE
Remove Variant and chanel

### ISSUE THREAD

**Issue by padalec** [Sylius/Sylius#8255]
Hi there,
there is the way to completely remove product variants and shop channels? 
Regards

**Comment by gabiudrescu** [comment]
I think it will bring more issues than it solves doing so. why do you want to do that?

**Comment by padalec** [comment]
Because in shop what just creating I don't need this functionality. This is very simple shop have only one price for products.

**Comment by gabiudrescu** [comment]
then create one channel and use "new simple product". you'll have everything in one page when editing a product, just more labels, like e.g: Channel price. 

the system does not force you to create multiple channels if you only need one.

**Comment by lchrusciel** [comment]
It is not possible and we do not plan to have such a functionality. But what @gabiudrescu said is correct. So, just ignore this functionality. Maybe one day they become useful.

**Comment by padalec** [comment]
I don't like to gives inexperienced users functionality which they do not need. From my experience always is associated with problems when user have more then they necessary.

**Comment by lchrusciel** [comment]
When creating simple products you don't need to care about variants at all. And shop needs its configuration so one channel is required. You can always remove this parts from the admin panel if you don't want end-user to have access to this. If the shop is simpler than that, maybe a good solution will be to take just some of the components?

**Comment by gabiudrescu** [comment]
@padalec then rework the templates to hide the buttons you don't need. but I have the feeling your fears will never come true and waste time solving a problem you think you have.
