### ISSUE TITLE
User impersonator couples core with shop bundle

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#8257]
This service is defined in core, used by admin and coupled with shop... We need some neat solution for this. Reported in https://github.com/Sylius/Sylius/pull/8253#discussion_r125844284.

**Comment by pamil** [comment]
The most decoupled approach would be probably:
  - moving `sylius.security.user_impersonator` to `ShopBundle`
  - introducing an optional integration layer with `ShopBundle` in `AdminBundle` (loading impersonator controller, showing impersonate button etc.)

As of beta.3 let's only care about the first point, wdyt?
