### ISSUE TITLE
Original price not displayed in product listing

### ISSUE THREAD

**Issue by Snake-Tn** [Sylius/Sylius#8258]
Create a product variant with price and original price.
On product listing only the price is being displayed, original price should also be displayed crossed out.

I'm ready to contribute if you see it's importance.

**Comment by lchrusciel** [comment]
Please, feel free to open a PR :)

**Comment by kochen** [comment]
@Snake-Tn, try this:
```{% set prices = product.variants|first.channelPricings|first %}
{{ prices.originalPrice }}
```

**Comment by Snake-Tn** [comment]
@kochen , original price should not be taken directly from entity, it should be calculated through a service, so I give the possibility for plugins to overwrite it(like catalog promotion plugin) , currently this is the case for the price.

**Comment by nacholibre** [comment]
If the price is calculated through service how can you sort be price?

**Comment by Snake-Tn** [comment]
@nacholibre , what you mean by "sort" the price ?

**Comment by nacholibre** [comment]
For example when you list products and you want to sort them by price asc/desc (including promotions etc). One solution is to fetch all products and sort them in memory, but this is not good idea.
