### ISSUE TITLE
[ReviewBundle] events

### ISSUE THREAD

**Issue by davidromani** [Sylius/Sylius#8259]
Hi.

I need to send an email on every new product review. How can I do it? There is some event to catch?

Thanks.

**Comment by lchrusciel** [comment]
You can hook to `sylius.product_review.post_create`. That should resolve your problem. You can find docs about [mailing](http://docs.sylius.org/en/latest/bundles/SyliusMailerBundle/your_first_email.html) and [Sylius events](http://docs.sylius.org/en/latest/book/architecture/events.html) pretty helpful :)
