### ISSUE TITLE
Is possible add custom GRID in dashboard?

### ISSUE THREAD

**Issue by piterssson** [Sylius/Sylius#8263]
Is possible add custom GRID (and filters) in dashboard?
Look on the screen:

![screencapture-localhost-html-sylius-web-app_dev-php-admin-1499635895962](https://user-images.githubusercontent.com/16086241/27997860-3675e754-6501-11e7-965c-d46e96d3479c.png)

**Comment by Zales0123** [comment]
Hello @piterssson! As you can see, Admin dashboard layout is defined in [this file](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AdminBundle/Resources/views/Dashboard/index.html.twig). To learn more about customizing templates, take a look at proper [Sylius docs page](http://docs.sylius.org/en/latest/customization/template.html).

**Comment by Zales0123** [comment]
I think it can be even closed, no need to keep it open.
