### ISSUE TITLE
Skipping shipping method selection, does not force available one if already selected

### ISSUE THREAD

**Issue by mrjingles** [Sylius/Sylius#8265]
If skipping shipping method when only one is available is enabled, it does not force to select the only available one if there was already selected another before.

For example you have 2 shipping methods available and you select the method B. After that you go back and change anything that makes only method A available, it will not be overwritten. Shipping method selection is skipped, but there is still B active - even if only A ist available.

**Comment by pjedrzejewski** [comment]
Thanks for reporting this issue Benjamin! Do you think you would be able to provide us with failing Behat scenario as PR? I think we have enough steps to just write a scenario.

**Comment by mrjingles** [comment]
Never did that before. Do you have link for an example or a tutorial?

**Comment by psihius** [comment]
#7965 subset of the current issue and actually provides a perfect way to replicate the issue.

**Comment by mrjingles** [comment]
@psihius @pjedrzejewski That's the same problem, so you can close my issue as duplicate. Thanks for linking.
