### ISSUE TITLE
[Payum][Sofort] Can't try to pay again after cancellation

### ISSUE THREAD

**Issue by zelton** [Sylius/Sylius#8269]
After placing an order I attempt to pay with Sofort payments. I cancel the process on their page and get redirected to the payment choice. Then I can't go to Sofort again and get 

> There was an unknown problem with payment.

**Comment by Colmea** [comment]
+1 same issue in production/dev

**Comment by Zales0123** [comment]
I believe it's an issue related to Sofort itself, which is not supported in Sylius out-of-the-box. Feel free to reopen and/or restart the discussion if it's still relevant in your opinion 🚀
