### ISSUE TITLE
framework.assets.base_urls conflicts with theme asset path resolving (breaks CDN support)

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#8278]
URL without `framework.assets.base_urls` defined: http://example.com/bundles/_themes/themename/base-theme/theme/svg/tj-logo.svg

URL with `framework.assets.base_urls` defined to ['http://example.com/']: http://example.com/bundles/theme/svg/tj-logo.svg

```yml
framework:
    assets:
        base_urls: ['http://example.com/']
```

According to https://symfony.com/doc/current/reference/configuration/framework.html#base-urls.

Use case is that I want to load my assets over a CDN. Most assets are going well, but the ones connected to a theme are now given a wrong URL.

The theme path resolver doesn't get the path supplied at all, so it seems to bypass these things. I'm not sure it hits the PathPackage::getUrl() though, but I have the impression that it also skips that one.

**Comment by pamil** [comment]
To solve this issue it's needed to overwrite Symfony's `UrlPackage` with added theming-related logic, mostly just cloning what was done to `PathPackage` before.
