### ISSUE TITLE
Select attribute values get lost on attribute value rename

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#8308]
### Steps to reproduce:
1. create a select attribute with the following configuration: name "Mug material" - values: "Banana skin" and "Prcelan"
2. create a product and assign the attribute "Mug material" with the value "Prcelan"
3. realize you have a typo in the product attribute value: it is "Prcelan" instead of "Porcelain" 
![image](https://user-images.githubusercontent.com/5156054/28501002-4c899574-6fdb-11e7-9f67-ce2b0f4991da.png)
4. modify the attribute value from "Prcelan" to "Porcelain"
![image](https://user-images.githubusercontent.com/5156054/28501013-6af222b0-6fdb-11e7-8c92-3ca765fa37ba.png)
5. observe the product attributes
![image](https://user-images.githubusercontent.com/5156054/28501016-77fd54ac-6fdb-11e7-84b9-7e106fbd1c67.png)

### What happens:
The product attribute value gets lost

### What should happen:
"Prcelan" should be linked to the product through a reference, otherwise, whenever the attribute value gets changed, the products get obsolete references.

Based on the feedback from @pamil on #8220

**Comment by pamil** [comment]
What about not relying on value for generating options codes but using UUID instead? This will make it resistant for value changes (but there still will be an issue with removing an option entirely).

**Comment by gabiudrescu** [comment]
why UUID and not plain IDs? just wondering.

regarding the removal of the option entirely, I am thinking about the following approaches:
 - similar to order items and products: if the option is used, prevent the user to delete it to avoid situations when you delete by mistake an option used by hundred of products
 - allow the delete of a select attribute value and cascade the deletion to all references from products, removing the attribute from the products too
 - same as no. 2, but instead of deleting the attribute from the product, only make the value null and allow the operator to choose another one

all options above have advantages and disadvantages. let's hear others opinion on this matter too.

**Comment by pjedrzejewski** [comment]
We decided to add translatable attribute values (select type) in 1.1 because it requires too many risky changes and not worth delaying the 1.0.0 release. It will be one of the first things we look at after the release.
