### ISSUE TITLE
[Admin] Taxon UI is not very user-friendly

### ISSUE THREAD

**Issue by psren** [Sylius/Sylius#8311]
IMO there are some usability-quirks in the Admin-UI of the Taxons.

1. The "Create" Button just reloads the page
1. The Breadcrumb is in an unusual place (compare with other screenshot)
1. Reordering of items is unintuitive (is it even possible to move "T-Shirts" as a child of "Books" (I know, stupid example, but should be possible.)) Maybe we can split the complete view into two routes. And maybe we can use a view better than "tree" for the taxons. In big taxon structures the tree gets unintuitive somehow. I really like the "finder"-Like approach of Sulu CMF (see screenshot)
1. If i klick on "Mugs" the Admin-Panel switches to ```/admin/products/taxon/17529```  i think we should "edit" the taxon instead (same as pencil-icon). Maybe we can add an "eye" icon next to the buttons to switch to ```/admin/products/taxon/17529``` instead.

![bildschirmfoto 2017-07-24 um 10 07 10](https://user-images.githubusercontent.com/1016798/28515199-04559654-705d-11e7-98d1-945da9b6612e.png)

![bildschirmfoto 2017-07-24 um 10 36 21](https://user-images.githubusercontent.com/1016798/28515029-6ed22e30-705c-11e7-8ae0-ecf7aa899a18.png)

![bildschirmfoto 2017-07-24 um 10 49 42](https://user-images.githubusercontent.com/1016798/28515443-ea25c096-705d-11e7-8ad8-5f2dfc829cf6.png)

What do you think?
I'd like to help out on that if you agree with one or more of my points here.

**Comment by blacknoir** [comment]
Currently we have in-dev shop with over 900! taxon. Would someone like to see how the UI looks like ? :) I know, the case is quite specific, but the current solution is not suitable even for few dozens of taxons in tree. And if thinking to use Taxonomy for categorizing articles or other CMS related stuff, the tree will grow a lot.

**Comment by psren** [comment]
@blacknoir your issue would be solved with my proposal? Or can you think of a more user-friendly version?

**Comment by blacknoir** [comment]
@psren yes, i think your proposal is good enough. Alternative could be some js tree component which collapses all nodes by default. imho

**Comment by psren** [comment]
@blacknoir i had problems with collapsible trees in huge cms project so far. Think of 10 Levels and the UI. Let's wait for the opinion of the core team

**Comment by serieznyi** [comment]
Up

**Comment by psren** [comment]
up

**Comment by psren** [comment]
...

**Comment by cv65kr** [comment]
Something moved?

**Comment by pamil** [comment]
I'll be happy to review a PR that improves that UI.

**Comment by Zales0123** [comment]
Agreed - I think right now in @Sylius/core-team we have no enough power and knowledge to handle this issue, but for sure it's important. PR with improvements would be more than welcomed 😄

**Comment by CoderMaggie** [comment]
Fixed by #10228
