### ISSUE TITLE
[ShopBundle][Checkout] Checkout-Templates, small refactoring

### ISSUE THREAD

**Issue by psren** [Sylius/Sylius#8313]
Hey there,

in the checkout there is the support-box in the right column.

![bildschirmfoto 2017-07-24 um 14 38 43](https://user-images.githubusercontent.com/1016798/28523797-35b9b3d0-707e-11e7-81cc-c9ad55977e8a.png)

The Phone-Number is hard-coded.
Maybe we can remove the code completely (I know the default template just acts as an example application).

Also the code (and template events) for the right column are duplicated:
[here](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/selectPayment.html.twig#L28-L38), [here](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/selectShipping.html.twig#L29-L38), and [here](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/address.html.twig#L29-L39)

## Proposal

I propose the following changes:

- [x] Remove right column from ```selectPayment.html.twig```, ```selectShipping.html.twig``` and ```address.html.twig``` and add it to ```layout.html.twig``` instead (```content```-Block)
Then override the ```content``` block in ```complete.html.twig```
- [x] Adjust the names of the Template-Events (the ```address``` namespace is wrong, because it's in ```Checkout/layout.html.twig``` wich is used by ```selectPayment|selectShipping|complete```, too.
- [x] Remove the ```_support.html.twig``` Events [here](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ShopBundle/Resources/views/Checkout/selectPayment.html.twig#L33-L37)
- [x] Add missing ```after_summary``` Event (or remove the summary-events at all. (We could introduce a ```sylius.shop.checkout.additional```  or ```sylius.shop.checkout.aside```  Event and then register a Plugin/Bundle which adds elements like support/summary to the sidebar (we know about the request context there, too, so using it for only one of the checkout-steps should be fairly easy)
- [x] remove the ```_support.html.twig``` completely (can be added with template-events by a plugin). The number is also hardcoded at the moment.

What do you think to the proposals? Are there some u like?

**Comment by mheki** [comment]
How about adding a phone number to the channel? We have already a `contact email` field there.

**Comment by psren** [comment]
Would be possible, but I'm not sure if this is in the scope of the core or if new features like that should be introduces in beta-phase. I'm 👍 for removing the module entirely.

What about the other points i made in my list?
Removing/Renaming of template-events is a BC-Break (i'm not sure if anybody uses them atm).
Should we do that before 1.0-RC/stable?

**Comment by gabiudrescu** [comment]
@psren I find your requests pertinent, but I'm still wondering why do you want to remove entirely that area? I think it fits the default look and allows people to customize if it they want. 

also, having the phone number handy in checkout seems to be a good practice, from customer care point of view.

**Comment by psren** [comment]
I'm sure ist's handy for the customer.

But i'd remove it or make ist configurable somehow. Each of those choices Seemann better to me than hardcoding it.

I'd love to provide a PR, but wanted to gather some feedback first.

**Comment by pjedrzejewski** [comment]
I agree with all the changes, one thing is I'd like keep the _support in demo site. So maybe we add it there via event? On SyliusDemo repository, wdyt @psren?

**Comment by psren** [comment]
@pjedrzejewski IMO the correct place for the support-box is ```AppBundle```  in Sylius-Standard and attach it via event (I'm 👍 *100 to attach it via event)? Or even a completely seperated bundle (but i don't think anyone will ever use it). Whats your opionion on that?

Do you consider the BC-Breaks (removing the support-events) critical or should we do that before 1.0, too?

I will give this a try as soon as I have your answer :-)

**Comment by psren** [comment]
Oh, stupid me. You already answered all my questions except the BC-Question
