### ISSUE TITLE
sylius demo not search bundle work?

### ISSUE THREAD

**Issue by benyang2015** [Sylius/Sylius#8329]

**Comment by lchrusciel** [comment]
The demo is just a vanilla version of Sylius without any plugin. Search bundle has been removed from Syluus itself a long time ago and the closest plugin to it would be SyliusElasticSearchPlugin. Which is, as I mentioned before, not a part of the demo.

**Comment by mheki** [comment]
@benyang2015 I've created a demo with search form here: https://github.com/mheki/sylius-search-demo (currently based on LakionElasticSearchBundle, but if I have some time can update it to work with Sylius plugin).
