### ISSUE TITLE
[Checkout][Address] Province cannot be selected using address book

### ISSUE THREAD

**Issue by PetrHeinz** [Sylius/Sylius#8330]
Issue found on *Sylius standard 1.0.0-beta.3*.

**How to reproduce:**

1. Define provinces for a country in administration
2. Log in as an customer
3. Create an address with a defined province selected
4. Go to checkout
5. Select the address from the address book

**Current state:**

When the address is selected, province is selected only if the same country was already selected.

Even if the province was selected, the province selection is reloaded and the province is unselected.

The #7944 makes it even worse as no validation error is shown.

**Expected state:**

When the address is selected, province should be selected as well

**Comment by Zales0123** [comment]
Should be fixed by https://github.com/Sylius/Sylius/pull/9237 🖖

**Comment by PetrHeinz** [comment]
Cool, thx :+1:
