### ISSUE TITLE
is void the good return type for interface setter ?

### ISSUE THREAD

**Issue by FanchTheSystem** [Sylius/Sylius#8345]
From: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Addressing/Model/AddressInterface.php
```php
interface AddressInterface extends TimestampableInterface, ResourceInterface
{
    /**
     * @return string|null
     */
    public function getFirstName(): ?string;
    /**
     * @param string|null $firstName
     */
    public function setFirstName(?string $firstName): void;
```

If I "implements" it like this:
 ```php
  public function setFirstName($firstName)
    {
        $this->firstName = $firstName;

        return $this;
    }
```

I will be able to do something like this:
 ```php
$address->setFirstName('MyName')->getFirstName();
 ```

With void type, I can't do this ... :(

Related commit:
https://github.com/Sylius/Sylius/commit/9c77c69437d75d6038ad2b42dfea0999fb8537e3

**Comment by Zales0123** [comment]
We got rid of fluent interfaces a long time ago, as there are plenty of good reasons not to use them. I recommend to read this article https://ocramius.github.io/blog/fluent-interfaces-are-evil/ to find out about the purposes of this decision ;)

**Comment by FanchTheSystem** [comment]
@Zales0123 : thank for the link ;)
