### ISSUE TITLE
[Bug]: Impossible to remove all elements from collection type

### ISSUE THREAD

**Issue by nenadalm** [Sylius/Sylius#8346]
preconditions:
- create extension for type `Sylius\Bundle\OrderBundle\Form\Type\OrderType` which adds `CollectionType` field with possibility to add and remove items
- update the twig template so that the field is shown in the admin

steps to reproduce:
- go to `/admin/orders/{id}/edit`, add a few items into the collection field
- save
- go to the edit page again, remove all of the fields
- save

expected result:
- all items from the collection were removed

actual result:
- items weren't removed, because the collection field is not in request data and there is `_method:PATCH` which causes missing fields to be ignored

environment:
```
sylius/sylius v1.0.0-beta.3
```

**Comment by pjedrzejewski** [comment]
Should work if we change it to PUT, not sure why PATCH was configured there. We should use PUT for all update forms in the UI. PATCH is only used for API.
