### ISSUE TITLE
Translations of category requirements in shipping method

### ISSUE THREAD

**Issue by lasotaartur** [Sylius/Sylius#8360]
How to add translations to category requirements in shipping method i.e. "At least 1 unit has to match the method category". This description exists in Sylius/Component/Shipping so there is a problem to use symfony translation.

**Comment by Zales0123** [comment]
For sure there should be translations keys used for these messages, to allow the multi-language translation 👍  are you willing to open a PR with such a fix?

**Comment by lasotaartur** [comment]
But I don't know how to fix it because in Sylius/Component we can't use symfony translations I think.
In Bundle yes, but in component no.

**Comment by Zales0123** [comment]
Well, `getCategoryRequirementLabels()` method from `ShippingMethod` entity is used only on `ShippingMethodType`. I think we can remove these method and replace it with `const`->`translation key` array in form type itself. /cc @pjedrzejewski

**Comment by lasotaartur** [comment]
@pjedrzejewski  ?

**Comment by pjedrzejewski** [comment]
I agree with @Zales0123. Let's add these in the form type.
