### ISSUE TITLE
Minimum length validation on email from 2 to 3 for customers

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#8363]
As discussed in #8344, it would make sense for email fields to validate as minimum length of 3 characters. Currently, in e.g. `src/Sylius/Bundle/CustomerBundle/Resources/config/validation/Customer.xml` the minimum length is defined as 2 characters. 

WDYT? If agreed, I can submit a PR if welcomed.

**Comment by pjedrzejewski** [comment]
Makes sense, would be happy to merge a PR! :)

**Comment by stefandoorn** [comment]
@pawel Alternative could be to remove the minimum length check and only rely on the Email check. Email is a regexp (according to @pamil) which already checks for a certain length.. WDYT?

**Comment by pamil** [comment]
IMO max length will do just fine :)
