### ISSUE TITLE
Symfony2 phpunit can't access Sylius Cart

### ISSUE THREAD

**Issue by ludovicpages** [Sylius/Sylius#8366]
I'm writing functional tests for a checkout process. I'm using Sf2, PhpUnit 5.1 and SyliusCartBundle 0.15

I have some services that gets the current order doing :
`$order = $this->container->get('sylius.cart_provider')->getCart();`
Problem is that when I call one of this services from inside a functional Test, the returned Object properties are empty.

Weird thing is that some property like "state" or "createdAt" are correctly sets.

Same is a call the sylius_cart service directly from inside a functional test doing :
`self::$container->get('sylius.cart_provider')->getCart()`
Here is the setUpBeforeClass method (in case it helps):
`public static function setUpBeforeClass() 
    {
 parent::setUpBeforeClass();
    static::bootKernel();
    self::$container = self::$kernel->getContainer();
    self::$entityManager = self::$container->get('doctrine')->getManager();
}`
And the object I receive :

`object(stdClass)[6001]
public '__CLASS__' => string 'Lp\AppBundle\Entity\Order' (length=25)
public 'items' => 
  array (size=0)
    empty
public 'adjustments' => 
  array (size=0)
    empty
public 'expiresAt' => 
  object(stdClass)[6027]
    public '__CLASS__' => string 'DateTime' (length=8)
    public 'date' => string '2017-08-03T17:55:09+00:00' (length=25)
    public 'timezone' => string 'UTC' (length=3)
public 'user' => null
public 'promotionCoupon' => null
public 'promotions' => 
  array (size=0)
    empty
public 'shippingAddress' => null
public 'billingAddress' => null
public 'comment' => null
public 'phone' => null
public 'id' => null
public 'completedAt' => null
public 'number' => null
public 'itemsTotal' => int 0
public 'comments' => 
  array (size=0)
    empty
public 'identities' => 
  array (size=0)
    empty
public 'adjustmentsTotal' => int 0
public 'total' => int 0
public 'createdAt' => 
object(stdClass)[6028]
  public '__CLASS__' => string 'DateTime' (length=8)
  public 'date' => string '2017-08-03T14:55:09+00:00' (length=25)
  public 'timezone' => string 'UTC' (length=3)
public 'updatedAt' => null
public 'deletedAt' => null
public 'state' => string 'cart' (length=4)`
Any help, idea, input are welcome :) Ludo

**Comment by CoderMaggie** [comment]
**SyliusCartBundle 0.15**? Do you know we are at beta.3 now? 0.15 is no longer maintained.
