### ISSUE TITLE
Variant option as string

### ISSUE THREAD

**Issue by lasotaartur** [Sylius/Sylius#8367]
How can I add a variant option on product cart with field input? 
Now we can choose a value from a select list. I would like type string to an input field. Value from this field doesn't change the price of the product.

**Comment by CoderMaggie** [comment]
I am just curious, what is your use case exactly? It seems like you ned rather a new field, like "comment/notes", on the ProductVariant entity, rather than the modification of input.

**Comment by lasotaartur** [comment]
Exactly, something just like this.

**Comment by lasotaartur** [comment]
Anybody?

**Comment by pjedrzejewski** [comment]
@lasotaartur I'd suggest extending OrderItem entity to add new field. Please use Slack or StackOverflow for support, here we report bugs, discuss features, etc. Thanks!
