### ISSUE TITLE
[Bug][ShopBundle] Fatal error for 404 pages

### ISSUE THREAD

**Issue by Takeno** [Sylius/Sylius#8369]
Hi guys!

When a resource can't be found, system is going in fatal error:
> Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError:
Type error: Argument 1 passed to FOS\RestBundle\Controller\ExceptionController::__construct() must implement interface FOS\RestBundle\View\ViewHandlerInterface, none given,
called in /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php on line 202 in /app/vendor/friendsofsymfony/rest-bundle/Controller/ExceptionController.php:43 Stack trace: #0 /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php(202): FOS\RestBundle\Controller\ExceptionController->__construct() #1 /app/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ContainerControllerResolver.php(74): Symfony\Component\HttpKernel\Controller\ControllerResolver->instantiateController('FOS\\RestBundle\\...') #2 /app/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerResolver.php(72): Symfony\Component\HttpKernel\Controller\ContainerControllerResolver->instantiateControl in /app/vendor/friendsofsymfony/rest-bundle/Controller/ExceptionController.php on line 43

It happens with non-existing resources (like `/taxons/blablabla`) and with not defined routes (like `/blablabla`).

Examples: 
- [http://demo.sylius.org/en_US/taxons/stickers2](http://demo.sylius.org/en_US/taxons/stickers2)
- [http://demo.sylius.org/en_US/stickers2](http://demo.sylius.org/en_US/stickers2)

In app_dev.php, `NotFoundException` is catched by Symfony profiler which show stacktrace. In `app` env, it goes in error.

**Comment by pjedrzejewski** [comment]
This is because of missing config for fos_rest bundle. See the upgrade file.

```
fos_rest:
    exception: ~
```

I just fixed it on the demo edition and deployed. :) Thanks for reporting!
