### ISSUE TITLE
[Contact] Add reply-to email when sending contact request mail

### ISSUE THREAD

**Issue by Niiko** [Sylius/Sylius#8371]
In fact,

We have the customer email in the mail template, but not in the reply-to field of the received email.

We have to copy paste each time we receive a mail to answer.

**Comment by kochen** [comment]
@Niiko this was discuss in Slack Support channel.
have you tried this (`config.yml`)?
```sylius_mailer:
    sender:
        name: Store Name
        address: noreply@store.com```

**Comment by Niiko** [comment]
The problem is, that address depend on user which send a contact request, not a support one.

In the config you submit, this is always that address that will be used.

I have plenty of requests, and each time i had to copy/paste the one of the user inside the email template

**Comment by kochen** [comment]
How about simply creating your own: `ContactEmailManager`?
```
        <service id="sylius.email_manager.contact" class="Sylius\Bundle\ShopBundle\EmailManager\ContactEmailManager">
            <argument type="service" id="sylius.email_sender" />
        </service>
```

**Comment by Niiko** [comment]
I think it has to be in core, it's standard behaviour for requests.

In fact, you could see it in requestAction from ContactController 
```php
$this->contactEmailManager->sendContactRequest($data, [$contactEmail]);
```

Of course, i can override it, that's not the problem here ;-)

I certainly will PR that one when i will fix it for my project.

**Comment by pjedrzejewski** [comment]
Implemented, thanks @loic425 & @Niiko for reporting. :)
