### ISSUE TITLE
Order status have to be more customizable

### ISSUE THREAD

**Issue by benyang2015** [Sylius/Sylius#8375]
Administrator should be able to

create custom order status
define how the status influence products' stocks
define how the status influence sales ("refund" status decrease overall sales)

**Comment by pjedrzejewski** [comment]
Currently, this is configured by the developer in state machine. Sylius is not WooCommerce or Shopify, so we will most likely not provide this kind of generic configuration in admin. For most Sylius use-cases, it is a bit too advanced to configure it with a couple of clicks.

**Comment by pjedrzejewski** [comment]
I will keep it open for discussion though.
