### ISSUE TITLE
Ability to select catalog base category per channel level

### ISSUE THREAD

**Issue by blacknoir** [Sylius/Sylius#8387]
By this suggested to add ability to set catalog main  taxon on channel level. This is obviously to be done at Admin panel channel editing page.

Business purpose: there are real cases (from my old Magento experience) when business wants to support more than one shop on single engine / app instance. This usually means another design, another catalog and scope of products , probably another taxation settings, other. To make this completely possible Sylius really misses such important feature as assignation of some root category where the shopping catalog starts from.

**Comment by pjedrzejewski** [comment]
I was thinking about that, but in most Sylius mulit-store cases every channel uses different theme. So in templates people have been using a different taxon code to get the tree and that's it. But then it is possible to view a category (it will have no products), from another store. And while typing this I realized it has a couple of extra logic checks needed if we introduce this feature. I'd suggest we start with some scenarios for this feature and see how complex/important it is. WDYT?

**Comment by pamil** [comment]
This will be an another BC break for everyone using main taxon, I'm not sure about that.

**Comment by psren** [comment]
Maybe the Taxon can be kept as is and each channel can set a "Taxon Entry Point" in the Channel-Settings?

**Comment by blacknoir** [comment]
@pamil @psren hi, feature proposal is right about what you said. Imho this is minimal what can be done. As for restrictions on category pages access, it is not that critical imho (since products are also filtered by channel). Here it's important to think that restriction should only consider the categories under the catalog  `entry point` channel taxon, other taxon trees (e.g. completely independent article pages taxon hierarchy) should be accessible and not restricted. So such cases make the implementation not that trivial :)
