### ISSUE TITLE
Mail is not delivered in sylius.

### ISSUE THREAD

**Issue by lovepreetsingh03** [Sylius/Sylius#8388]
Mail is not delivered in sylius.
Parameter.yml
 database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: sylius
    database_user: root
    database_password: root
    mailer_transport: smtp
    mailer_host: mail.exclusivehosting.net
    mailer_user: noreply@drivekool.com
    mailer_password: ****
    secret: EDITME
    locale: en_US

In controller 
	
	 $message = \Swift_Message::newInstance()
        ->setSubject('Email')
        ->setFrom('noreply@drivekool.com')
        ->setTo('example@gmail.com')
	
        ->setBody(
            $this->renderView(
                'CommunicationBundle:Default:movieAddedNotification.html.twig',
               array('name' => 'Ajay')
            )
       )
    ;
    $this->get('mailer')->send($message);

Please help me out to get Solution

**Comment by psren** [comment]
Are you in dev environment?

Maybe see this in ```config_dev.yml```

https://github.com/Sylius/Sylius/blob/master/app/config/config_dev.yml#L25-L26

**Comment by lovepreetsingh03** [comment]
yes, 
I am working in dev environment
this is my config_dev.yml file

imports:
    - { resource: "config.yml" }

framework:
    router: { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }

doctrine:
    dbal:
        dbname: "%database_name%_dev"

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        firephp:
            type: firephp
            level: info

swiftmailer:
    disable_delivery: true

web_profiler:
    toolbar: true
    intercept_redirects: false

**Comment by Zales0123** [comment]
Hi @lovepreetsingh03! If you're using `dev` environment sending emails is disabled by default with `swiftmailer.disable_delivery: true`. To send emails you should either change it to `false` or remove these two lines.
Moreover, I see you don't use *MailerBundle* to send your emails. It's much more easier when you use it, please, check out [this blog post](http://sylius.org/blog/sending-configurable-e-mails-in-symfony) or [related documentation section](http://docs.sylius.org/en/latest/bundles/SyliusMailerBundle/index.html).

**Comment by lovepreetsingh03** [comment]
thank you Sir.
Now it's working fine for me

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

On Fri, Aug 11, 2017 at 11:59 AM, Mateusz Zalewski <notifications@github.com

**Comment by Zales0123** [comment]
Great, you're welcome! 👍
