### ISSUE TITLE
open existing sylius project in windows 7

### ISSUE THREAD

**Issue by lovepreetsingh03** [Sylius/Sylius#8407]
Is it Possible to Open a existing sylius Project in Windows ?
If it is Possible then Please help me out to get solution.

**Comment by Cathmor** [comment]
I run sylius in a windows environment and have no issues with the php. I was missing some extensions in the ini file when I initially started a new sylius project but once I got everything installed, it worked just fine. 

The only issue with windows is if you are using ms sql server, which we are. There are some foreign keys that cause issues when cascade is set to delete that we had to remove. But doctrine doesnt seem to care that these keys are missing so it works out fine.
