### ISSUE TITLE
No route found exception when uploading media bigger than upload_max_filesize / post_max_size

### ISSUE THREAD

**Issue by pyrorules** [Sylius/Sylius#8408]
I noticed (on a fresh installation of Sylius) that when you upload a file in Media bigger than `upload_max_filesize` / `post_max_size` then you get an exception:

`No route found for "POST /admin/products/73/edit": Method Not Allowed (Allow: GET, PUT, PATCH, HEAD)`

Please note that this does NOT happen when you create a product. It happens only when you update one (like it's ignoring `_method`, which is sent).

My config:

```
upload_max_filesize => 200M => 200M
post_max_size => 200M => 200M

PHP 7.1.8-2+ubuntu16.04.1+deb.sury.org+4 (cli) (built: Aug  4 2017 13:04:12) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.8-2+ubuntu16.04.1+deb.sury.org+4, Copyright (c) 1999-2017, by Zend Technologies

Sylius v1.0.0-beta.2
```

Please note than when I upload any file smaller than the values above (for example: 150mb), everything works just fine.

**Comment by loic425** [comment]
I've already seen this error. I think the hidden type "PUT" is lost cause of the media bigger than upload_max_filesize.
