### ISSUE TITLE
sylius:install does not run in non-interactive mode

### ISSUE THREAD

**Issue by Im0rtality** [Sylius/Sylius#841]
Use-case: load fixtures and run behat tests on travis. 

Right now `--no-interaction` only prevents `Careful, database will be purged. Do you want to continue Y/N ?` (defaults to Y), however `Load fixtures (Y/N)?` still blocks execution.

**Comment by stloyd** [comment]
@pjedrzejewski @aRn0D After merge of #2599 this can be closed.
