### ISSUE TITLE
Why not load the template?

### ISSUE THREAD

**Issue by puning** [Sylius/Sylius#8411]
Why not load the template after windows7 is installed through the DOS?,
![sylius](https://user-images.githubusercontent.com/15931200/29404040-9b7282fa-836c-11e7-913e-80428559203a.png)

**Comment by mbabker** [comment]
You ran the yarn commands to compile the CSS/JS, right?

```sh
yarn install
yarn run gulp
```

**Comment by lchrusciel** [comment]
@puning Did it help?

Anyway, closing, as our official support channels are stackoverflow and slack

**Comment by puning** [comment]
谢谢，成功了。
通过下面的方式：


Thank you. It's a success.

Through the following way:
yarn install
yarn run gulp
