### ISSUE TITLE
[Grids] Per page has to keep filters informations

### ISSUE THREAD

**Issue by Niiko** [Sylius/Sylius#8412]
In fact, when you change pagination in grid, you loose your filters

Has to change 
```twig
{% set path = path(app.request.attributes.get('_route'), app.request.attributes.get('_route_params')|merge({'limit': limit})) %}
```
To
```twig
{% set path = path(app.request.attributes.get('_route'), app.request.attributes.get('_route_params')|merge(app.request.query)|merge({'limit': limit})) %}
```

Let me know if you want a PR, i could add that quickly

**Comment by pjedrzejewski** [comment]
@Niiko Sure thing!

**Comment by lex111** [comment]
@pjedrzejewski Strange, I do not notice this behavior. Can this be fixed already?

**Comment by Zales0123** [comment]
I've just checked it and it seems to work, should've been fixed in the meantime. Closing then 🚀
