### ISSUE TITLE
Problem with installation via composer

### ISSUE THREAD

**Issue by pietrek777** [Sylius/Sylius#8418]
Hello,
I'm trying to install Sylius via composer. But after executing command `composer create-project -s beta sylius/sylius-standard acme ` composer is throwing an error `Your requirements could not be resolved to an installable set of  packages. `

**Comment by Zales0123** [comment]
Hello Piotr!
1. Which version of PHP do you use? *Sylius* in beta version requires at least PHP5.6.
2. Issues should be used to report bugs inside *Sylius* or propose new features. For such a help, please, use our official Slack channel (probably the quickest way for simple questions) or post question on stackoverflow with #sylius tag.
;)
