### ISSUE TITLE
[Question] fractional amount of CartItem possible?

### ISSUE THREAD

**Issue by psren** [Sylius/Sylius#8431]
Hey there,

is it somehow possible (*possible meant as without hacking sylius unmaintainable*) to add a fractional amount of items to an order?

I found different places where this must be adjusted.

- IntegerDistributor (what is that?!)
- CartItemType (min-value can be smaller that 1 und IntegerType is not usable for that)
- OrderItem-Mapping

Or is it better to store the price as an integer and the quantity as an integer.
If the product has some kind of attribute "allow fractional oders" only the form-validation is changed.

Could you give me some hints on that? Where do i start?

**Comment by psihius** [comment]
To keep money calculations iron-clad - you have to stick to integers. Float calculations and money always result in nuclear explosion type of problems. Never ever use float's for that.

**Comment by psren** [comment]
okay, so i'll stick with option 2.
Use integer quantity and multiply it on form-input with some "factor" thanks for your help, i'll give it a try :-)
