### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by lellebebbl** [Sylius/Sylius#8437]
Hello,

I'm implementing some SyliusBundles in our existing symfony project. But some of the bundles use older bundles, for example the fos/rest-bundle is required at ver ~1.5 but we are using ^2.2
Or the association bundle requires the doctrine orm at <2.5, but it is essential for us to use >2.5.

Is there some way to ignore this, or would lead this to some essential errors?

**Comment by kochen** [comment]
@lellebebbl Sylius was recently updated to use ORM 2.5.
