### ISSUE TITLE
Introduce "staging" environment

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#8455]
We add it almost to every project so I think it makes sense to have it in both Sylius & Sylius-Standard.

Staging is just like production but has e-mails redirected to a test address, etc.

* [x] Sylius
* [x] Sylius-Standard

**Comment by gabiudrescu** [comment]
We use https://mailcatcher.me/ for catching emails on non-prod environment. and it plays nice with Behat: https://github.com/alexandresalome/mailcatcher
