### ISSUE TITLE
[Question] Best selling products

### ISSUE THREAD

**Issue by czende** [Sylius/Sylius#8460]
Hi, 
I've followed this guide http://docs.sylius.org/en/latest/customization/controller.html and just want to exactly same functionality as described - show best selling products.
I've prepared my own ProductController with some actions and custom ProductRepository class, but I'm stuck at `findBestSellingByChannel(ChannelInterface $channel, $locale, $count)` method in ProductRepository. I cannot find any examples for this and already asked twice on slack.

Can anyone help me how to create this method please? I'm pretty new to DQL and not sure how to construct query with joining `sylius_order_item` table.

Thank you very much!

**Comment by tuanminhgp** [comment]
i have the same issue. Can you help me if you have solution.
