### ISSUE TITLE
image not display in sylius 

### ISSUE THREAD

**Issue by lovepreetsingh03** [Sylius/Sylius#8475]
hi,
I install a sylius in centos than product images is not display.
I give permission to web/media folder .

it's showing following error in console
GET http://18.221.8.245/ecommerce/web/app_dev.php/en_US/media/cache/resolve/sylius_shop_product_thumbnail/76/81/a1ca42ed2026c75cb96e76893340.jpeg 500 (Internal Server Error)

when i open a  above link then give following error
Failed to create "/var/www/html/ecommerce/app/../web/media/cache/sylius_shop_product_thumbnail/d2/2a": The Symfony\Component\ClassLoader\ClassCollectionLoader class is deprecated since version 3.3 and will be removed in 4.0..

Please help me out to get Solution

**Comment by pjedrzejewski** [comment]
@lovepreetsingh03 Can you gist full stack trace? And run in with --verbose? Seems like this is just a deprecation warning and error is somewhere else.
