### ISSUE TITLE
[PostgreSQL] sylius_shop_product grid fails with SQL error

### ISSUE THREAD

**Issue by kokoon** [Sylius/Sylius#8477]
Installed the standard distribution on PostgreSQL 9.6.4.

Shop crashes when trying to browse by any taxon:

> An exception occurred while executing 'SELECT s0_.code AS code_0, s0_.created_at AS created_at_1, s0_.updated_at AS updated_at_2, s0_.enabled AS enabled_3, s0_.id AS id_4, s0_.variant_selection_method AS variant_selection_method_5, s0_.average_rating AS average_rating_6, s1_.name AS name_7, s1_.slug AS slug_8, s1_.description AS description_9, s1_.meta_keywords AS meta_keywords_10, s1_.meta_description AS meta_description_11, s1_.id AS id_12, s1_.short_description AS short_description_13, s1_.locale AS locale_14, s0_.main_taxon_id AS main_taxon_id_15, s1_.translatable_id AS translatable_id_16 FROM sylius_product s0_ INNER JOIN sylius_product_translation s1_ ON s0_.id = s1_.translatable_id AND (s1_.locale = ?) INNER JOIN sylius_product_taxon s2_ ON s0_.id = s2_.product_id WHERE s2_.taxon_id = ? AND EXISTS (SELECT 1 FROM sylius_product_channels s3_ INNER JOIN sylius_channel s4_ ON s3_.channel_id = s4_.id WHERE s3_.product_id = s0_.id AND s4_.id IN (?)) AND s0_.enabled = true GROUP BY s0_.id ORDER BY s2_.position ASC LIMIT 9 OFFSET 0' with params ["en_US", 2, 1]:
>
>SQLSTATE[42803]: Grouping error: 7 ERROR: column "s1_.name" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...method_5, s0_.average_rating AS average_rating_6, s1_.name A...
^

Looks like the query could work on MySQL, but it does not work on PostgreSQL - group by should also include s1_.id and s2_.id fields.

**Comment by PapsOu** [comment]
Related to this PR https://github.com/Sylius/Sylius/pull/7978

Any news ?

**Comment by kokoon** [comment]
Probably related, but not sure how closely. I'm not entirely sure why the query looks like it does, but this patch fixes the error: https://github.com/Sylius/Sylius/compare/master...kokoon:master

**Comment by pamil** [comment]
Seems fixed on Sylius `1.3.0` with PostgreSQL `10.5`, please open an issue if that's still the case on your environment.
