### ISSUE TITLE
On grids with 'state machine' a state filter

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#8479]
I think it would be great to have on e.g. the order overview a default filter to filter on the state machine values (translated). It can be created myself ofcourse, but might be something useful for anyone. 

Parking it here for now, don't directly have the time to PR it myself.

**Comment by kochen** [comment]
@stefandoorn isn't this already possible?
i.e for Orders:
```            criteria:
                state: ["new", "fulfilled", "cancelled"]```

**Comment by stefandoorn** [comment]
Yes - that's the default filtering on the query isn't it?

But I mean a filter on top of the page so the administrator can choose a certain 'state' themselves and filter the grid based on that. It's possible to add a select I think manually now - but I think it should go into core + there should be support for proper labels on it instead of the internal names.

**Comment by kochen** [comment]
the above code is a `criteria` in the routing, thus a constant (not adjustable) filter.

but you are talking about a grid filter, right?
something like this:
```
                state:
                    type: state
                    options:
                        fields: state
```

**Comment by kochen** [comment]
I just saw that we already have something like this:
```
            filters:
                state:
                    type: string
```
`sylius_admin_api_shipment` & `sylius_admin_api_payment`
