### ISSUE TITLE
Main Taxon Hard to Use With "Duplicate" Names

### ISSUE THREAD

**Issue by mbabker** [Sylius/Sylius#8485]
Example taxonomy structure (partial from a build we're finishing)

```
- Category
|- Automotive
|-|- Interior
|-|-|- Vinyl
|-|- Exterior
|-|-|- Vinyl
```

When using the Main taxon field in the product's edit page, the search will only show the taxon name, so when searching "Vinyl" you don't know which parent you're choosing.  It would be good if the display could be expanded to either show the entire tree down to that item or at least show the parent.

**Comment by teohhanhui** [comment]
@pamil This is still an issue.

**Comment by pamil** [comment]
Needs #9669.

**Comment by igormukhingmailcom** [comment]
This was fixed at https://github.com/Sylius/Sylius/pull/9983

**Comment by lchrusciel** [comment]
@teohhanhui would you like to give it a try and see if this solution works fine?

**Comment by teohhanhui** [comment]
@lchrusciel #9983 looks good! I won't get a chance to give this a try as I'm not working on a Sylius project at the moment. :)

**Comment by lchrusciel** [comment]
Awesome!
