### ISSUE TITLE
Fatal error when save product with integer attribute

### ISSUE THREAD

**Issue by ping86** [Sylius/Sylius#8486]
When I save a product with integuer attribute in the master branch i see this issue:

``
Type error: Argument 2 passed to Sylius\Component\Attribute\AttributeType\IntegerAttributeType::getValidationErrors() must be of the type string or null, integer given, called in /home/proyects/Sylius/src/Sylius/Component/Attribute/AttributeType/IntegerAttributeType.php on line 58
``

Thanks.

**Comment by ping86** [comment]
I want create a pull request for this issue.

How can I solve this problem?

I will try change value to integer https://github.com/Sylius/Sylius/commit/c1e6aae6aa89c9baf972e3ebe52c5a6013e8f5c0#diff-cf06aea427c039c2341d0aaea1f8fbf5R75  but I dont know if you another solution.

Thanks.

**Comment by Arminek** [comment]
Hey, @ping86 I have reproduced your issue but I did not get any errors. Are you sure that this issue still exists?

**Comment by ping86** [comment]
@Arminek yes, I try now with sylius master, commit 41b0971870bfd5b44af7664987f83950c5043858

If you want reproduce this issue follow the next steps:

1) Login in te sylius admin
2) Select product with id 32 and go to edit page "http://127.0.0.1:8000/admin/products/32/edit"
3) Edit the attribute "Book pages" and save.

And now you see the error in the next page.

The product must have an attribute with integer value.


Thanks.
