### ISSUE TITLE
Customer::Gender is required but might be empty if removed from form

### ISSUE THREAD

**Issue by kochen** [Sylius/Sylius#8493]
Customer::Gender is a required field:
```        <field name="gender" column="gender" type="string" length="1">
            <options>
                <option name="default">u</option>
            </options>
        </field>
```
which has a default value `u`.

but when being removed (i.e not needed for the shop) from `.../vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views/Account/profileUpdate.html.twig`:
```<div class="field">{{ form_row(form.gender) }}</div>```
you get an error saying:
![image](https://user-images.githubusercontent.com/106042/30017837-f559a9fa-915a-11e7-82e8-7437a7275cd3.png)

This issue seem to occur as well from the API - @psihius could you confirm/elaborate?

**Comment by pjedrzejewski** [comment]
@kochen this behavior is actually correct. If you remove this field from template, you should also remove it from the form. (using form type extension)

**Comment by kochen** [comment]
@pjedrzejewski that's true, but it'd also require you to remove the attribute from the DB.
what I'm trying to do here is properly set the default value of `u` for the case where not value is provided.

**Comment by pjedrzejewski** [comment]
@kochen but this should happen on the Customer object already in the constructor here: https://github.com/Sylius/Sylius/blob/12ce073e341a8876ffd4696d8473a13ae9ce013d/src/Sylius/Component/Customer/Model/Customer.php#L58-L58

**Comment by kochen** [comment]
@pjedrzejewski yes, but it doesn't happen :)

**Comment by itinance** [comment]
I don't now why this issue was closed although the provided PR is still unmerged. 

However, i've found the following fixes:

a) write an own GenderType according to the draft of @kochen (https://github.com/kochen/Sylius/blob/36099fbbc6f70484595b1e0a082031b548fafc6b/src/Sylius/Bundle/CustomerBundle/Form/Type/GenderType.php#L37)

b) override the "gender"-type like this:

```
->add('gender', HiddenType::class, array(
                'data' => CustomerInterface::UNKNOWN_GENDER,
            ))

```
