### ISSUE TITLE
"View your store" link is wrong

### ISSUE THREAD

**Issue by jeroendesloovere** [Sylius/Sylius#8495]
## Type

Bug

## Problem description

In the `admin` section (of the demo), the `View your store` button has a wrong link.
It isn't the link from the store, but it is always `localhost`, even when installed locally.

## Steps to reproduce

* Visit the [Demo site](http://demo.sylius.org/admin/)
* Log in to `admin/login`
* Click the "View your store" button in the main navigation
=> You are now seeing 404 page, because `localhost` doesn't exist.

**Comment by pjedrzejewski** [comment]
To generate this link we use hostname from channel. So it is not a bug. :)

**Comment by jeroendesloovere** [comment]
Well, that isn't proper behavior.
Using `<a href="localhost">` instead of `<a href="http://demo.sylius.org/">` seems like a bug to me. Since clicking the first (localhost) link gives you a 404...

Wouldn't it be a solution to use the Symfony Request `request. getScheme()`+ `request.getBaseUrl()` instead?

**Comment by kochen** [comment]
@jeroendesloovere to elaborate on what @pjedrzejewski tied to explain, the Hostname of the channel comes from a setting and not a fixed value.
If you take a look in the admin (of the demo) you'll see this:
![image](https://user-images.githubusercontent.com/106042/30368681-35592ad0-9872-11e7-8256-b9e0197c9add.png)

This is done to allow multiple channels having different `Hostnames`.
