### ISSUE TITLE
Sylius Taxonomy bundle and component not compatible with Symfony 3.3.8

### ISSUE THREAD

**Issue by apoorva-shah** [Sylius/Sylius#8504]
I install Symofny 3.3.8 and try to install 
composer require sylius/taxonomy-bundle and
composer require sylius/resource-bundle

I got error.

Problem 1
    - sylius/taxonomy-bundle v0.18.0 requires sylius/resource-bundle ^0.18 -> satisfiable by sylius/resource-bundle[v0.18.0].
    - Installation request for sylius/taxonomy-bundle ^0.18.0 -> satisfiable by sylius/taxonomy-bundle[v0.18.0].
    - Conclusion: remove symfony/symfony v3.3.8
    - Conclusion: don't install symfony/symfony v3.3.8
    - sylius/resource-bundle v0.18.0 requires symfony/validator ^2.7 -> satisfiable by symfony/validator[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.34, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - don't install symfony/validator v2.7.0|don't install symfony/symfony v3.3.8

![taxonomy-component](https://user-images.githubusercontent.com/24920542/30054207-f6fa383a-9248-11e7-85d3-5466c630b447.png)
![sylius-taxonomy](https://user-images.githubusercontent.com/24920542/30054200-f14bf45a-9248-11e7-9627-89323d4e5a5f.png)

**Comment by pjedrzejewski** [comment]
Please use stability beta when using composer. Otherwise it installs 0.19.0, which is pre-alpha version.

**Comment by apoorva-shah** [comment]
Can you please write command for stabily beta using composer?

**Comment by lchrusciel** [comment]
https://github.com/Sylius/Sylius#installation

**Comment by apoorva-shah** [comment]
@lchrusciel 
My requirement is:
I will install symfony 3.
And then i will use just taxonomy bundle or taxonomy component. I do not want to install full sylius. 
So your link is about full sylius installation.
Thanks in advance!

**Comment by lchrusciel** [comment]
It is all about the details
```bash
$ php composer.phar create-project -s beta sylius/sylius-standard project
```
What you need are `-s beta` flag

**Comment by apoorva-shah** [comment]
@lchrusciel

hi let i have installed symfony and

now i want to just install just sylius taxonomy bundle **not full sylius**.

So please tell command to install **just taxonomy bundle in symfony app**.

**Comment by lchrusciel** [comment]
It is all about **the details**

I meant that the library needs the stability of beta, [here it is explained.](http://lmgtfy.com/?iie=1&q=composer+require+beta)

I recommend the first link. 
```bash
$ composer require sylius/taxonomy-bundle:1.0-beta
```
