### ISSUE TITLE
[Resource] UpdateHandlingException flash message 

### ISSUE THREAD

**Issue by dannyvw** [Sylius/Sylius#8542]
When define a custom flash message in the routing configuration the exception flash message is also overwritten with the new translation.

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Controller/ResourceController.php#L343

**Comment by Arminek** [comment]
Hi @dannyvw, We should probably configure flashes for success and error.
```yaml
   flash:
      error: app.ui.resource.error_message
      success: app.ui.resource.success_message
```
We can add this feature without bc breaks later on.

**Comment by dannyvw** [comment]
@Arminek I think it's better to not overwrite the exception flash message. But your solution is good also.
