### ISSUE TITLE
TaxRateInterface & TaxRateExampleFactory.php

### ISSUE THREAD

**Issue by FanchTheSystem** [Sylius/Sylius#8555]
In file:

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Fixture/Factory/TaxRateExampleFactory.php

I think this :

`use Sylius\Component\Core\Model\TaxRateInterface;`

Should be replaced by : 

`use Sylius\Component\Taxation\Model\TaxRateInterface;`

For information, here is the error I get with the current code 

` Type error: Return value of Sylius\Bundle\CoreBundle\Fixture\Factory\TaxRateExampleFactory::create() must implement interface Sylius\Component\Core\Model\TaxRateInterface  instance of MyOwnTaxRateWhichExtendTaxRate returned`

Maybe you should not use the exact same name for interface in Core and Other component, as it is confusing ...

**Comment by lchrusciel** [comment]
This class sets Zones as well, so we need to use a core typehint. If you are using core you should mostly use core class to base on unless you are 100% sure you don't want to. Anyway, yes it can be confusing. 

Not sure, how we can help further. Probably can be closed. /cc @Sylius/core-team
