### ISSUE TITLE
Upgrade Feedback: OrderController being final makes upgrade hard

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#8563]
Have already talked to several people about it on Slack, but might need to have a central place for the discussion. 

In recent commits, some Controllers that extend ResourceController have been made final. Although I like the idea of final classes, around the extensibility of the ResourceController it makes developers lives harder. This guide doesn't apply anymore for e.g. the OrderController: http://docs.sylius.org/en/latest/customization/controller.html#how-to-customize-a-resource-controller.

The use case I'm running in is that I have a PDF download connected to the OrderController, in method 'downloadAction'. It simply accepts an Order ID, fetches the file from file system and returns it as a download to the user (from inside the admin). 

Decorating the default OrderController is do-able, but there are some big downsides:

- The original controller can be injected as dependency, which is great. Unfortunately very useful helper methods as 'findOr404' and 'isGrantedOr403' are protected so therefore not callable from the decorator. This results in copy / pasting, which in the case of 'isGrantedOr403' might lead to security issues (it's harder to stay updated with Sylius updates).
- The original dependencies are hard to trace. There is no 'sylius.controller.order' service definition in a XML file, it looks to me that is done rather dynamic based on configuration inside the ResourceBundle. To mimic the correct dependencies, it's going to be a hard time I'm afraid. If copying a method like 'isGrantedOr403' I also need to make sure the correct dependencies are inside my decorator.

Some possibilities I see:

- Revert Controllers extending ResourceController being final
- Have the helper methods inside the ResourceController being public (e.g. 'findOr404') & allow to get the dependencies from the original Controller (so you don't have to declare them again)
- Allow the dependencies from the original Controller to be fetched (as above) and have the methods being shared as traits, so they can easily be implemented but still being safe during upgrades of core Sylius.

Example code of my method:

```
/**
     * @param Request $request
     *
     * @return Response
     */
    public function downloadAction(Request $request)
    {
        $configuration = $this->requestConfigurationFactory->create($this->metadata, $request);

        $this->isGrantedOr403($configuration, ResourceActions::SHOW);
        $order = $this->findOr404($configuration);

        // Find file & return
        .... // Project specific

        $disposition = $response->headers->makeDisposition(
            ResponseHeaderBag::DISPOSITION_ATTACHMENT,
            $filename
        );

        $response->headers->set('Content-Disposition', $disposition);

        return $response;
    }
```

Thinking about how to implement this in the final controller structure, is according to me quite tedious and limits extending the framework - which Sylius is great at normally. Upgrading from beta-3 to dev-master (trying it by request of @pjedrzejewski) became tremendously harder than expected :(

**Comment by stefandoorn** [comment]
P.S. If this is the way to go, then it would be great to have proper documentation on how best to do the decorating in the context of the ResourceController. It's one of the hardest classes in Sylius to understand :-)

**Comment by zbigp** [comment]
I also thinking that `final` keyword should be removed from controllers. Changing of visibility or creating a lot of traits that is not solution in my opinion. There will be always situations when someone will need to overwrite original controller class.

**Comment by psihius** [comment]
For me it's even worse - this is just the OrderController overridden and added stuff. I have extensive checkout workflow modifications and additions, and I just require to override and/or adjust the base methods, there is also some copy-pasting involved because there is no way I can modify the behaviour with events or calling parent::whateverAction before or after my code - I had to modify the body of an action or two.
final on controllers does not look as a great idea.
https://i.imgur.com/Brc8Vu8.png

**Comment by zbigp** [comment]
@psihius As short solution at this moment you can use this approach http://mnapoli.fr/overriding-dependencies-with-composer/ . In your copy of Sylius you will be able to remove `final` keyword.

**Comment by inspiran** [comment]
+1 for removing final for the resource controller.

**Comment by pjedrzejewski** [comment]
I think this change sneaked in during introduction of strict types. We will remove it for controllers. /cc @pamil @Zales0123

**Comment by stefandoorn** [comment]
Alright, great :-) PR is submitted already.
