### ISSUE TITLE
Incompatible CustomerRepository count() method declaration

### ISSUE THREAD

**Issue by bitbager** [Sylius/Sylius#8566]
Looks like the count method of CustomerRepository overrides the `Doctrine\ORM\EntityRepository::count(array $criteria)` which throws below error while trying to use the repository:

`Warning: Declaration of Sylius\Bundle\CoreBundle\Doctrine\ORM\CustomerRepository::count(): int should be compatible with Doctrine\ORM\EntityRepository::count(array $criteria)`

Renaming the method to `countCustomers()` should fix the problem.

**Comment by Zales0123** [comment]
Which version of Doctrine do you use? Current version in our `composer.lock` is `2.5.6` and there is not such method in `Doctrine\ORM\EntityRepository` for this version 😄

**Comment by mbabker** [comment]
See https://github.com/doctrine/doctrine2/pull/6003 - it'll be part of ORM 2.6

**Comment by Zales0123** [comment]
👍  the question is - should we fix something (with BC break, btw) what is not bug **yet**. I think we can leave it as it is and take care about it when we'll upgrade to doctrine 2.6. /cc @Sylius/core-team

**Comment by mbabker** [comment]
Personally I'd do it now otherwise dependent on how strict you are on B/C you possibly lock to ORM 2.5 until Sylius 2.0.

**Comment by stefandoorn** [comment]
I would say the more you can upgrade before 1.0, the better. Saves BC issues afterwards. The upgrade from beta.3 to 1.0 is already full of BC, so a bit more won't harm anyone ;-)

**Comment by pamil** [comment]
We could also try not to extend `EntityRepository` in our own repositories :)
