### ISSUE TITLE
Invalid cookie name in Behat scenarios

### ISSUE THREAD

**Issue by bitbager** [Sylius/Sylius#8583]
Running background steps like `Given the store operates on a channel named "United States" in "USD" currency` causes below issue in test.log. It's because the channel identifier `United States` is passed as a code to the factory method.

`[2017-09-11 13:04:59] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The cookie name "_currency_United States" contains invalid characters." at vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Cookie.php line 53 {"exception":"[object] (InvalidArgumentException(code: 0): The cookie name \"_currency_United States\" contains invalid characters. at vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Cookie.php:53)"} []`

**Comment by lchrusciel** [comment]
I guess its fixed
