### ISSUE TITLE
how to install rc1 version

### ISSUE THREAD

**Issue by benyang2015** [Sylius/Sylius#8610]

**Comment by CoderMaggie** [comment]
Hi @benyang2015!

There are two ways to do it:

1. Install Sylius Standard with beta3 `composer create-project -s beta sylius/sylius-standard acme`
And then in `composer.json` change Sylius version to `"^1.0.0-rc.1"` and run `composer update`.

2. Wait a bit more until an updating PR to the Sylius-Standard repository is merged. It is this one: https://github.com/Sylius/Sylius-Standard/pull/187

Thanks for asking! 🎉

**Comment by CoderMaggie** [comment]
If you will have any more questions please reopen @benyang2015 :)

**Comment by benyang2015** [comment]
use php composer.phar create-project -s beta sylius/sylius-standard project  can't install rc1 version also the beta3

**Comment by lchrusciel** [comment]
As was written you need either to 

1. Install Sylius Standard with beta3 `composer create-project -s beta sylius/sylius-standard acme`
And then in `composer.json` change Sylius version to `"^1.0@rc"` and run `composer update`.

2. Wait a bit more until an updating PR to the Sylius-Standard repository is merged. It is this one: https://github.com/Sylius/Sylius-Standard/pull/187

or


1. Install Sylius Standard with rc1 `composer create-project -s rc1 sylius/sylius-standard acme` as it was tagged a few minutes ago
