### ISSUE TITLE
the channel changer is not working properly for 2 channels with different urls

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#8615]
steps to reproduce:
- install a fresh new copy of sylius
- setup /etc/hosts to point example.com and localhost to 127.0.0.1
- setup 2 channels on your sylius instance, for the two domains
- click on admin on the link "view channel" for any of the channels or open one of the URLs in incognito
- try to access any of the channels by url (preferably in incognito)

what happens:
- you end up seeing an error:
![image](https://user-images.githubusercontent.com/5156054/30313773-2425886a-97a7-11e7-8261-2df6193e8732.png)
- going on localhost or on example.com there current channel is not changed according to the url
![image](https://user-images.githubusercontent.com/5156054/30313790-3e72e80c-97a7-11e7-9b23-37040cef3774.png)
(notice the url is localhost while the selected channel is mobile - imho, the behavior should be ```redirect me to example.com when I change the channel to mobile```)

what should happen:
- you should be able to change the channel by the URL you are using to access the sylius instance

**Comment by pjedrzejewski** [comment]
Thanks for report, we are on it!

**Comment by Arminek** [comment]
Hi @gabiudrescu, you have configured the domain with ports and unfortunately, right now we do not support channel resolving with the port number.

**Comment by gabiudrescu** [comment]
I confirm, using the url in channel without port is working as advertised. 

I wouldn't keep this ticket as a feature request, because I'm (personally) not requesting this to be implemented nor believe it's a priority. So, with your approval, I would:
 - close this ticket with the resolution "won't fix" OR
 - implement a validator for the channel url to prevent users from using urls with port

what do you think?

**Comment by pjedrzejewski** [comment]
Let's keep it as feature request for now as we will go through all of them soon. We could consider this functionality for future versions. :)
