### ISSUE TITLE
can't install sylius 1.0 use composer create-project sylius/sylius-standard sylius-shop

### ISSUE THREAD

**Issue by benyang2015** [Sylius/Sylius#8666]
composer version: 1.5.2
php:7.1.7
use composer create-project sylius/sylius-standard sylius-shop,
the project install sylius 0.18.0

**Comment by stefandoorn** [comment]
Can you copy paste the whole input / output you are entering and/or seeing?

**Comment by benyang2015** [comment]
nothing error
it's display download sylius(0.18.0)

**Comment by benyang2015** [comment]
use composer create-project sylius/sylius-standard sylius-shop "1.0.0"   alse can't install.
the error like this:   Could not find package sylius/sylius-standard with version 1.0.0.

**Comment by stefandoorn** [comment]
And what about 'v1.0.0'?

**Comment by benyang2015** [comment]
Could not parse version constraint 'v1.0.0': Invalid version string "'v1.0.0'"

**Comment by benyang2015** [comment]
what can I do can download the sylius 1.0.0

**Comment by stefandoorn** [comment]
Without the ', so just: `v1.0.0`.

**Comment by stefandoorn** [comment]
Might be better to join the Slack channel, it's easier to get help on such issues in there.

**Comment by Koronos** [comment]
I had the same problem and the solution was reinstall composer, because it takes an old php version from my computer (I use wampserver in Windows).
