### ISSUE TITLE
OrderSequence::getIndex() must be of the type integer, string returned

### ISSUE THREAD

**Issue by gomcodoctor** [Sylius/Sylius#8674]
look like some typo error?

`Type error: Return value of Sylius\Component\Order\Model\OrderSequence::getIndex() must be of the type integer, string returned`

**Comment by gomcodoctor** [comment]
I debugged it - this issue occurring because I changed idx of sylius_order_sequence  to bigint, and look like bigint is converted to string by doctrine / php, I reverted it back to integer, issue resolved

**Comment by pjedrzejewski** [comment]
@gomcodoctor Thanks for quick feedback!

**Comment by gomcodoctor** [comment]
Here is more reference 

https://github.com/unreal4u/telegram-bots/commit/ee83b6826212cd36a424ae71ff5bc794774e3497

I need bigint because I am adding more than 60 million products, so I had changed integer to bigint everywhere.

**Comment by pjedrzejewski** [comment]
@gomcodoctor 60 million products is a lot, can you tell us more about your project? :D

**Comment by gomcodoctor** [comment]
@pjedrzejewski I am trying to build marketplace like amazon, walmart etc, so I am trying to load all products which have UPC/EAN/ISBN code so that seller can load inventory using these number in one go.

I have already added following this

1. Multiple sellers can signup on store and start selling products ( seller dashboard is in development stage )
2. Multiple offers on one product variant from different sellers.

3. Ticket system - where anyone can communicate to each other ( buyer -> seller or vica versa)

Following in development 
Return system
Refund system - both are very crucial but lacking in sylius yet :(

**Comment by gomcodoctor** [comment]
right now I have loaded 15 million products, approx 20 million offers, page load time is hardly 1 sec
I am using memcached for cache for doctrine query and metadata. I have to do testing with huge traffic.
