### ISSUE TITLE
Adding the Sylius version in admin

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#8679]
I was curious to see which Sylius version is running on demo.sylius.org and there is no mention in admin or web.

What do you think about adding it to the footer of the admin? Like wordpress does.

**Comment by pjedrzejewski** [comment]
It is a feature, but hmmm, do we really need to wait till 1.1? :D /cc @pamil WDYT?

**Comment by pamil** [comment]
I'd rather not make any exceptions, we can speed up 1.1 release though :)
