### ISSUE TITLE
ProductOptionValue should have unique constraint on option_id and code

### ISSUE THREAD

**Issue by krafas** [Sylius/Sylius#8691]
Now ProductOptionValue has unique constraint only on `code` field:

```<field name="code" column="code" type="string" unique="true" />```

The problem is that codes of option value can be similar on different options. Option value should have unique constraint on `option_id` and `code` fields.

```
     <mapped-superclass name="Sylius\Component\Product\Model\ProductOptionValue" table="sylius_product_option_value">
+        <unique-constraints>
+            <unique-constraint columns="option_id,code" />
+        </unique-constraints>
+     
         <id name="id" column="id" type="integer">
             <generator strategy="AUTO" />
         </id>
 
-        <field name="code" column="code" type="string" unique="true" />
+        <field name="code" column="code" type="string" />
```

**Comment by pjedrzejewski** [comment]
I think these codes should follow the same logic as any other code in Sylius. We solve it by having tshirt_color_red, iphone_case_color_red as codes instead of just two "red" option values. Would that solve your problem?

**Comment by mlelong** [comment]
I just made Product_Option_Value overriding, in order to add the code/option_id index.
It's more logic to me, than force a prefix in production_option_value.code.

``
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping">

    <mapped-superclass name="AppBundle\Entity\ProductOptionValue" table="sylius_product_option_value">
        <unique-constraints>
            <unique-constraint columns="option_id,code" />
        </unique-constraints>
        <attribute-overrides>
            <attribute-override name="code">
                <field unique="false" />
            </attribute-override>
        </attribute-overrides>
    </mapped-superclass>
``
