### ISSUE TITLE
Add branching strategy to contribution guide

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#8693]
While reviewing the Platform.sh PR today, I noticed that target branch was adjusted from `master` to `1.0`. I think it would be good to make clear to contributors how to setup their PR's, to point it to which branch. Also makes it more clear on which branch to branch from, when willing to submit a change.

**Comment by pamil** [comment]
Yeah, we're working on that (and learning how to manage these branches on other, less significant repos :tada:).

**Comment by stefandoorn** [comment]
Over the last weeks I've seen multiple contributors opening PR's against master - which seems to become 1.1. The 1.0 branch is to be used for bug fixes. Afterwards they need to rebase it to the proper branch, which seems not that easy for many people.

Wouldn't it make more sense to use master as bugfixes on 1.0 and features that should go to 1.1 to point them to a specific release branch (and treat 1.1 as the dev version in Composer)? It will make it way easier for contributors as it's the no-brainer way to do it (create branch, commit code, push, open PR). Most people outside the core team mainly submit small patches, not often an huge feature that should go to 1.1 and these users are often skilled enough to do proper rebases etc. 

I'm not sure it has other downsides, but I have the impression it would life for contributors way easier and for the core team it shouldn't make a lot difference I think. But, not sure about other implications.

**Comment by lchrusciel** [comment]
#8934 closed it I suppose.
