### ISSUE TITLE
[Order] Creating order via custom checkout without customer leads to error

### ISSUE THREAD

**Issue by kate-kate** [Sylius/Sylius#8698]
Hi guys! 
I've created one-page-checkout following instructions from this [article](http://docs.sylius.org/en/latest/cookbook/checkout.html)

And I've found a few problems:
### 1. There is a fake action used in example  #8697 
And it was said, that we take config from ```ShopBundle/Resources/config/routing/checkout.yml``` and only remove routing connected with ```sylius_shop_checkout_select_shipping```, so this is an error

### 2. Fatal error at complete step
Even if I change route of complete step to ```sylius.controller.order:updateAction```, I get Fatal error when trying to save order after being completed
<img width="1124" alt="2017-09-19 16 37 33" src="https://user-images.githubusercontent.com/4061805/30595137-0107e14a-9d59-11e7-98b3-b78424757b8b.png">

It is thrown because there is no check, if I have set customer (and I haven't)

**Comment by kate-kate** [comment]
Also error may be raised in [email manager](https://github.com/Sylius/Sylius/blob/88dfec13f9f07fb252fa7e51190aa0fa59cf7cc4/src/Sylius/Bundle/ShopBundle/EmailManager/OrderEmailManager.php#L43)
Except this two places everything will work even without customer

**Comment by gustawdaniel** [comment]
Article linked in this issue give 404.

```
        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
           ]                     [   /  |
           ]___               ___[ ,'   |
           ]  ]\             /[  [ |:   |
           ]  ] \           / [  [ |:   |
           ]  ]  ]         [  [  [ |:   |
           ]  ]  ]__     __[  [  [ |:   |
           ]  ]  ] ]\ _ /[ [  [  [ |:   |
           ]  ]  ] ] (#) [ [  [  [ :===='
           ]  ]  ]_].nHn.[_[  [  [
           ]  ]  ]  HHHHH. [  [  [
           ]  ] /   `HH("N  \ [  [
           ]__]/     HHH  "  \[__[
           ]         NNN         [
           ]         N/"         [
           ]         N H         [
          /          N            \
         /           q,            \
        /                           \
```

Anyway I have the same error:

    Call to a member function getUser() on null

When I removed address state from state machine `sylius_order_checkout`. How to fix this error?
