### ISSUE TITLE
Problem with coupons expired and older orders.

### ISSUE THREAD

**Issue by ping86** [Sylius/Sylius#8699]
This is the scenario in sylius 1.0.0:

I create a coupon based promotion. I go to cart page and apply the coupon. Next I remove the item (I only have one item in the cart), not all order (dont use clear cart button). With this remove the order is not removed and promotion_coupon_id  relation is present in the database. The coupon expire, and i return to the shop the next day. I buy a newo product and Sylius reutilize de older order. The new order have a relation with expired coupon_id but the promotion rules arent apllyed.

I think in this case the promotion relation in the new order will be removed. 

Thanks.

**Comment by pjedrzejewski** [comment]
@ping86 Thanks for report, we will look into it. If you have some time, you could write a Behat scenario which reproduces this issue. This would help fixing it a lot!

**Comment by pamil** [comment]
Thanks for reporting this bug, I'll consolidate it into one issue, #9361, to keep the discussion there.
