### ISSUE TITLE
[BUG] ProductVariant::shippingRequired is NOT true as default suggests

### ISSUE THREAD

**Issue by kochen** [Sylius/Sylius#8700]
```
class ProductVariant extends BaseVariant implements ProductVariantInterface
{
...
    /**
     * @var bool
     */
    protected $shippingRequired = true;
...
}
```
Setting the default value on the DB/Table level doesn't help, because when creating a simple product the Form is submitted with the value FALSE:
![image](https://user-images.githubusercontent.com/106042/30597699-12a6bfb2-9d58-11e7-97f9-20531339cab5.png)
```
final class ProductVariantTypeExtension extends AbstractTypeExtension
{
...
            ->add('shippingRequired', CheckboxType::class, [
                'label' => 'sylius.form.variant.shipping_required',
            ])
...
}
```

**Comment by kochen** [comment]
@lchrusciel I also think that the scenario for this case is incorrect:
```
        And I do not want to have shipping required for this product
```
because:
1. the `Shipping Required` is not part of the `Simple Product` form.
2. it is forcing a value FALSE instead of expecting it to be set by default (possible separate scenario).

**Comment by GSadee** [comment]
I am not sure if this bug exists or maybe I misunderstood the issue, but there is a `shipping required` checkbox in a simple product form:
![zrzut ekranu 2017-09-22 o 10 06 17](https://user-images.githubusercontent.com/6140884/30735135-2e0697a0-9f7e-11e7-8db6-cd63b06d0c52.png)

**Comment by kochen** [comment]
@GSadee OK, thanks.
Now we can pin point it a bit deeper, because `{{ form_row(form.variant.shippingRequired) }}` is in the simple Product `SyliusAdminBundle::Tab::_detail.html.twig`.
In my case it isn't so the form gets the default value from the Transformer which is FALSE, instead of the `ProductVariant` class which is TRUE.


So I created a new product through the API:
```
{
	"code": "SHIPPABLE",
    "translations": {
    	"en_US": {
        	"name": "Shippable",
        	"slug": "shippable"
		}
	}
}
```

and this is the response:
```
{
    "name": "Shippable",
    "id": 237569,
    "code": "SHIPPABLE",
    "attributes": [],
    "options": [],
    "associations": [],
    "translations": {
        "en_US": {
            "locale": "en_US",
            "id": 237602,
            "name": "Shippable",
            "slug": "shippable"
        }
    },
    "productTaxons": [],
    "channels": [],
    "reviews": [],
    "averageRating": 0,
    "images": [],
    "_links": {
        "self": {
            "href": "/api/v1/products/SHIPPABLE"
        },
        "variants": {
            "href": "/api/v1/products/SHIPPABLE/variants/"
        }
    }
}
```
product is not a simple product (therefor has no ShippingRequired field in the edit form), but also  has no Variant:
![image](https://user-images.githubusercontent.com/106042/30772776-f70284e0-a062-11e7-9fc2-ac9473832e38.png)
![image](https://user-images.githubusercontent.com/106042/30772779-010a5b7a-a063-11e7-926d-adadc9b4f4ed.png)
