### ISSUE TITLE
Facebook login routing and disabled localised URLs

### ISSUE THREAD

**Issue by czende** [Sylius/Sylius#8702]
Hi, I've added facebook login based on this [cookbook](http://docs.sylius.org/en/latest/cookbook/facebook-login.html) 
and everything worked fine, but when I disable localised URLs based on this [guide](http://docs.sylius.org/en/latest/cookbook/disabling-localised-urls.html) and go to the default login page, somehow I'm always redirected to facebook login oauth. 

I'm I missing something? Thank you!

**Comment by chokrijobs** [comment]
when you have disabled localised URLs you will have the same routing prefix of hwi_oauth_login and sylius_shop_login:

`hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login`
`sylius_shop_login:
    path: /login
    ...`
you can set for example:
`hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /hwi-login`

**Comment by chokrijobs** [comment]
Hi @czende , you can change the routing prefix of `hwi_oauth_login` to avoid confilict with `sylius_shop_login`
```
hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
```
To 
```
hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /hwi-login
```

**Comment by czende** [comment]
Thx @chokrijobs but without change. I still have on `http://localhost/sylius/web/app_dev.php/login/` same error `No route found for "GET /login/"`

**Comment by chokrijobs** [comment]
@czende because route is not `/login/` but is `/login` browser redirect automatically to `/login/` from it's cache, try to change browser and type `http://localhost/sylius/web/app_dev.php/login`

**Comment by czende** [comment]
Damn! My bad. Thank you!

**Comment by chokrijobs** [comment]
It works for you ? thank you too :)

**Comment by czende** [comment]
Yes, now it is fixed. Thx. This can be closed.

**Comment by chokrijobs** [comment]
Thank you
