### ISSUE TITLE
Placing order as Guest throws 'shop_user' not found exception after payment.

### ISSUE THREAD

**Issue by KirbyFox** [Sylius/Sylius#8711]
When placing an order as a Guest customer, it throws an exception 'shop_user' not found, after the payment has been taken (captureAction).

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ShopBundle/Resources/config/routing/ajax/user.yml

https://github.com/Sylius/Sylius/blob/0a485dad6e6317ebfd88af9f95387b1c408b0ded/src/Sylius/Bundle/CoreBundle/Doctrine/ORM/UserRepository.php

This does not occur when placing an order as a customer who is logged into the system.

**Comment by benyang2015** [comment]
@KirbyFox how to solve this problem
