### ISSUE TITLE
How can I translate the routes?

### ISSUE THREAD

**Issue by Chrysweel** [Sylius/Sylius#8724]
Can I translate routes without override all configuration of yaml ?

I can translate routes using the bundle JMS\I18nRoutingBundle\JMSI18nRoutingBundle but I want to know if there is another possibility...

For example translate the route:

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ShopBundle/Resources/config/routing/checkout.yml#L11

```
sylius_shop_checkout_address:
    path: /address
```
I need override in my project from line 11 to line 30 of yml ?

thanks in advance.

PD: I ask here, because in documentation I dont find it

**Comment by Zales0123** [comment]
Unfortunately, I think there is no such feature in **Sylius**, you need to override the route definition.

**Comment by Chrysweel** [comment]
Bad news... thanks for reply @Zales0123 !

**Comment by teohhanhui** [comment]
https://github.com/symfony/symfony/pull/26143 might help.
