### ISSUE TITLE
Admin product image upload artifacts

### ISSUE THREAD

**Issue by ecornelisse** [Sylius/Sylius#8726]
When i upload a png image in the admin for a product some parts of the original image gets converted to black. See below for an example. The black square is just a removal of the company brand. The drop shadow below the device gets converted to full black as is seen:
![png upload sylius](https://user-images.githubusercontent.com/11006071/30749527-f7e0edde-9fb3-11e7-9064-53342c2ff025.png)

How can i fix this? Or is this a possible bug? This is on sylius 1.0

**Comment by pjedrzejewski** [comment]
I guess this can be related to some of liip_imagine settings. Did you try setting quality to 100?

**Comment by ecornelisse** [comment]
I tried the following settings but it doesn't seem to do anything

> quality: 100
            png_compression_level: 0
            png_compression_filter: 0
            filters:
                thumbnail: { size: [382, 255], mode: outbound}

**Comment by pjedrzejewski** [comment]
@ecornelisse Is it possible for you to share this one sample image? We could give it a try and see if we can reproduce. :)

**Comment by pamil** [comment]
It might be helpful to ask at https://github.com/liip/LiipImagineBundle

**Comment by ecornelisse** [comment]
@pjedrzejewski Here is an example image with the drop shadow that is causing the problem.
![scan 3x](https://user-images.githubusercontent.com/11006071/30954580-090f2838-a431-11e7-9861-66ac84172137.png)

**Comment by pamil** [comment]
Reproduced here: http://demo.sylius.org/en_US/products/book-reiciendis-by-deanna-anderson

**Comment by pjedrzejewski** [comment]
@pamil demo is restarted every hour so it is gone now. :)

**Comment by pamil** [comment]
But it's real!

**Comment by anolek** [comment]
I just hit the same issue, but i found a workaround, maybe it could help. If you export a PNG with transparency in Photoshop (File > Export > Export in...) without checking "Small file (8 bits)", and then try to import it in Sylius, it doesn't work (you got the weird black shadow and no transparency). But when you check "Small file (8 bits)", it does work.


Anyway i don't think it is related to Sylius, but more to GD (and maybe Imagick, i didn't try with Imagick), or maybe LiipImagineBundle.

**Comment by pamil** [comment]
It's still reproducible, but I believe we can't solve it in Sylius.
