### ISSUE TITLE
updatedAt column not updated

### ISSUE THREAD

**Issue by dannyvw** [Sylius/Sylius#8727]
updatedAt column (product) will not be updated if you only change a translation. This is probably a problem with all associations.

Possible solution: Can be fixed by adding this to the `ResourceUpdateHandler` class.

```
if ($resource instanceof TimestampableInterface) {
    $resource->setUpdatedAt(new \DateTime);
}
```

**Comment by pamil** [comment]
Related to #8522.

**Comment by pamil** [comment]
Sorry for such a delayed response, I'm trying to get through all the issues that have been there unsolved. In my opinion, changing this behaviour could break existing applications and it's a tough job to decide which models should trigger an update in associated models. I would leave it as is until we work out some solution for it.
