### ISSUE TITLE
Macros, Twig2 and SyliusResourceBundle::form.html.twig

### ISSUE THREAD

**Issue by winzou** [Sylius/Sylius#8728]
In Twig > 2.0, the variable `_self` returns the current template name. It is a `string`. cf https://github.com/twigphp/Twig/pull/1965

Hence it is not possible to use it like this: https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ResourceBundle/Resources/views/forms.html.twig#L9

    {{ _self.collectionItem(prototype, allow_delete, button_delete_label, '__name__')|e }}

If you try to do this, you get the following `Twig_Error_Runtime` exception:

    "Impossible to invoke a method ("collectionItem") on a string variable ("SyliusResourceBundle::forms.html.twig")." at ./vendor/sylius/resource-bundle/Resources/views/forms.html.twig line 9

You have to import it first:

    {% import _self as this %}
    {{ this.collectionItem(....) }}

I just don't get it as Sylius is using twig/twig v2.4.3. How are the collection forms working? Is `{% block collection_widget -%}` used at all?

I am using only the ResourceBundle v1.0 with Twig 2.4.3 and Symfony 3.3.9.

**Comment by pamil** [comment]
This could be closed, as Sylius now uses Twig 2.0 and it has been solved in the meantime.
