### ISSUE TITLE
Get the right repositories with EntityManager->getRepository()

### ISSUE THREAD

**Issue by winzou** [Sylius/Sylius#873]
Hi,

We once said:

_Using listener to change the entity repository classes dynamically. We use repositories as services, which is my preferred method. But, we construct them manually (not via getRepository() method of ObjectManager). This allows us to easily override the repository class, from container, from configuration etc. But if someone uses the casual way, the getRepository method, he'll get the default repository class. What we can do is use a listener to change the class inside mapping. ("load metadata" event) and in service definition, use the factory method, to get the repository via object manager._

Currently, you get 2 different objects by doing `$container->get('sylius.repository.order')`  and `$entityManager->getRepository('Order')`.

Is this something we want to fix? Unless I'm wrong, yes we should fix this.

This issue is a reminder for this point.

**Comment by lsmith77** [comment]
just to confirm .. we should therefore be safe to using `$em->getRepository()` instead of `$container->get()`?

relates to https://github.com/FriendsOfSylius/SyliusImportExportPlugin/pull/173#discussion_r264571725
