### ISSUE TITLE
sylius_shop_ajax_user_check_action throws "shop user" has not been found" exception

### ISSUE THREAD

**Issue by KirbyFox** [Sylius/Sylius#8730]
The following file causes a "shop user" has not been found" exception to be thrown when a guest user is going through checkout/

vendor/sylius/sylius/src/Sylius/Bundle/ShopBundle/Resources/views/Common/Form/_login.html.twig

https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/ShopBundle/Resources/views/Common/Form/_login.html.twig

**Comment by GSadee** [comment]
This is the normal behaviour of checking out as a guest. When you specify email in an address form, the ajax call try to find out if there is a user with given email.

**Comment by KirbyFox** [comment]
OK thanks, but every time a guest visits the checkout address page, it results in this exception being thrown, which causes a log to be written to the log file. Would it not be better if the system could simply return the required data to the AJAX call (JSON?), without having to resort to throwing an exception?

**Comment by reyostallenberg** [comment]
Same problem of 'incorrect' logs here because of this behaviour
