### ISSUE TITLE
Installation Guide Composer Command Installing version 0.18.0 instead version 1.0.0 ? And not installing bin/console

### ISSUE THREAD

**Issue by dmidz** [Sylius/Sylius#8747]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 0.18.0 ?

Installation guide composer command seem Installing v0.18.0 ?
But it tells about "v1.0.0 released !"
```
composer create-project sylius/sylius-standard Sylius
Installing sylius/sylius-standard (v0.18.0)
  - Installing sylius/sylius-standard (v0.18.0): Downloading (100%)
Created project in Sylius
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 180 installs, 0 updates, 0 removals
...
  - Installing sylius/sylius (v0.18.0): Downloading (100%)
...
```
Then bin/console is not installed (I had a previous version which had console installed), so further commands are not available as is, following installation guide.

**Comment by pamil** [comment]
Make sure you're using PHP 7.1

**Comment by dmidz** [comment]
Ah ok, so I am installing env for x64 in order to get PHP 7.1, and then retry the install, I close for the moment.
Thank you.
