### ISSUE TITLE
Product Reviews API

### ISSUE THREAD

**Issue by paulstoica** [Sylius/Sylius#8753]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.0

Hi all,

I am using just released Sylius version but only the API, thank you for it.
I am using Sylius API for one of my projects and I think I found that there are not an REST API for creating a product review. Or a product review can be created with a product update?

Can you please clarify it?
If it does not exists will be implemented in the feature?

Thank you.
Have a good day,
Paul

**Comment by pjedrzejewski** [comment]
Hi Paul!

Would be great to have it for 1.1, although it is not planned yet. If you are able to work on it, then we would be definitely happy to merge it. :) Otherwise, we will probably implement it although a bit later. (We hope to release 1.1 within the next 2-3 months.)

**Comment by paulstoica** [comment]
Hi,
I see, thank you for the answer.
I think I will going to work on it, because I need this feature. And after if can submit this feature to be merged.

**Comment by pamil** [comment]
#8772 has just been merged and product reviews API will be released with 1.1.0 in the late January.
