### ISSUE TITLE
How to customize ProductVariantImage entity in Sylius v0.19?

### ISSUE THREAD

**Issue by barik94** [Sylius/Sylius#8754]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 0.19

https://stackoverflow.com/questions/46493370/how-to-customize-productvariantimage-entity-in-sylius-v0-19

**Comment by pjedrzejewski** [comment]
Hello Den. 0.19 is no longer supported, you should start your project on v1.0.0 or upgrade if that's in-dev project.

That being said, IIRC in 0.19 there was no simple way to do it via config in YAML. You could try customizing the ``sylius.model.product_variant_image.class`` parameter if it exists, but I am not 100% sure if it was already there. Hope it helps, cheers.

**Comment by barik94** [comment]
@pjedrzejewski I need to fast update project from v0.11 to newest. 
Updating to v1.0 isn't fast. 
Thats why I tries to update my proj to most loyal version.
I understood you.
Thanks.
