### ISSUE TITLE
Ability to specify fixture suite during sylius:install

### ISSUE THREAD

**Issue by igormukhingmailcom** [Sylius/Sylius#8759]
When we have some custom fixture suite - steps to install Sylius become not user-friendly. 
We should:

1. Run `php bin/console sylius:install`
2. Answer 'Y' for 'Would you like to reset it?
3. Answer 'N' for 'Loading sample data for environment dev. Continue?
4. Type dummy E-mail and password (they will be rewrited during loading fixtures - next step)
5. Load our custom fixture suite (`php bin/console sylius:fixtures:load CUSTOM_SUITE_NAME --no-interaction`)

Note, that we can't use `--no-interaction` at first step as far as in that case `default` fixture suite will be executed and (in case we have some entities customized) it will fail (like `Some custom fields can't be null`) during creation. Thats why we should perform so many steps and its not good.

May I perform pull request?

**Comment by pjedrzejewski** [comment]
Great idea. 👍
