### ISSUE TITLE
Can't disable ShopBundle

### ISSUE THREAD

**Issue by TomPradat** [Sylius/Sylius#8764]
sylius.storage.cart_session is defined in the ShopBundle but used in the CoreBundle. Therefore i can't disable ShopBundle.

I just updated to 1.0.0

https://github.com/Sylius/Sylius/blob/127382f6eeaf2a2bc2010d89c897f479ffbb72fa/src/Sylius/Bundle/ShopBundle/Resources/config/services.xml#L34

**Comment by pjedrzejewski** [comment]
@TomPradat Thanks for reporting, we will have a look.
