### ISSUE TITLE
Mention PHP 7.1 requirement in installation guide

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#8765]
Would this make sense to add to README? I've seen multiple people installing 0.18 or smth due to wrong PHP version and not knowing how to get past that issue.

**Comment by baskan** [comment]
+1 just now installed with 7.0 and got confused somehow

**Comment by stefandoorn** [comment]
@GSadee I can submit a PR. Should that be pointed to `1.0` or to `master`. We want it visible on the main README.md I assume (when users visit the repo) + on the latest version of the docs. So I guess it will be `master`.

**Comment by GSadee** [comment]
IMO this PR should be pointed to `1.0`, so it will be visible on both branches because `master` is up-to-date with `1.0`

**Comment by stefandoorn** [comment]
Can be closed, #8800 is merged.
