### ISSUE TITLE
Extend Channels REST API - Create, Update, Delete

### ISSUE THREAD

**Issue by ce-bo** [Sylius/Sylius#8768]
We need the possibilities to create, update and delete channels by your REST API.
Thank you!

| Q                | A
| ---------------- | -----
| Feature request? | yes
| Sylius version   | 1.0.0

**Comment by nerdyninja** [comment]
I think no one is assigned, can I take this issue?

**Comment by pjedrzejewski** [comment]
@nerdyninja Absolutely!
