### ISSUE TITLE
Creating cart via REST API takes long time

### ISSUE THREAD

**Issue by jdeveloper** [Sylius/Sylius#8776]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.0

It occurs when you have a lot of customers in your database. 

The proble is due that the ```Sylius\Bundle\AdminApiBundle\Form\Type\OrderType``` uses for customer the ```Sylius\Bundle\CustomerBundle\Form\Type\CustomerChoiceType``` type and therefore it loads all customers leading to out of memory problem.

To clarify I'm speaking form the API call explained in the docs http://docs.sylius.org/en/latest/api/carts.html#creating-a-cart

```
curl http://demo.sylius.org/api/v1/carts/ \
    -H "Authorization: Bearer SampleToken" \
    -H "Content-Type: application/json" \
    -X POST \
    --data '
        {
            "customer": "shop@example.com",
            "channel": "US_WEB",
            "localeCode": "en_US"
        }
```

**Comment by pjedrzejewski** [comment]
Fix: The ChoiceType should be replaced with a transformer form type (from e-mail to Customer or ResourceToIdentifierTransformer).

**Comment by jdeveloper** [comment]
Thanks, I'll try a pull request

**Comment by gabiudrescu** [comment]
we experienced a lot of headaches with customers on Sylius 0.19 because of missing indexes on the right columns. 

missing indexes + output walkers almost made our website crash due to high load. might wanna check the slow query log of MySQL.

**Comment by GSadee** [comment]
I guess that this issue can be closed after https://github.com/Sylius/Sylius/pull/8778 was merged
