### ISSUE TITLE
Setting Locale from 'sylius.context.locale'

### ISSUE THREAD

**Issue by TomPradat** [Sylius/Sylius#8780]
On the documentation (here: http://sylius-older.readthedocs.io/en/latest/book/locales.html), it is said that i can set the locale by fetching the service 'sylius.context.locale'. But when i do so i get an instance of Sylius\Component\Locale\Context\CompositeLocaleContext which doesn't have setLocale method.

Not sure if the documentation should be updated or so.

I'm trying to set the Locale in a kernelRequest event listener (with a get parameter), how should i do ?

https://github.com/Sylius/Sylius/blob/127382f6eeaf2a2bc2010d89c897f479ffbb72fa/src/Sylius/Bundle/LocaleBundle/Resources/config/services.xml#L37

**Comment by GSadee** [comment]
Hi @TomPradat, first of all, you are using strange version of docs, the official documentation is here: http://docs.sylius.org/en/latest/book/configuration/locales.html
However, you are unfortunately right that this section of documentation is not up-to-date, because there is only `getLocaleCode` method on `LocaleContextInterface` https://github.com/Sylius/Sylius/blob/127382f6eeaf2a2bc2010d89c897f479ffbb72fa/src/Sylius/Component/Locale/Context/LocaleContextInterface.php#L19-L26

Could you tell me, what exactly do you want to achieve?

**Comment by TomPradat** [comment]
Hi ! Well i have a front application fetching data from a sylius app through some routes. I want to be able to set the locale for the request to get the right translation for my entities with a get parameter (/foo?locale=en_US). What i did so far was to listen to the kernel request and change the symfony request locale but this is not enough. If i understand well, sylius doesn't use symfony locale system.

I hope this is clear.

**Comment by GSadee** [comment]
Look at `LocaleSwitcherInterface` and its implementation: https://github.com/Sylius/Sylius/tree/1.0/src/Sylius/Bundle/ShopBundle/Locale
I'm not sure, but maybe it could help.

**Comment by TomPradat** [comment]
What seems to work is adding a new context to the CompositeLocaleContext instance with higher priority.

I created a custom LocaleContext class implementing the LocaleContextInterface : 
```
use Sylius\Component\Locale\Context\LocaleContextInterface;

class MyLocaleContext implements LocaleContextInterface
{
    private $locale;

    public function __construct(string $locale)
    {
        $this->locale = $locale;
    }

    public function getLocaleCode(): string
    {
        return $this->locale;
    }
}
```

Then i listen to the request (i injected the 'sylius.context.locale' service) and add this context:

```
public function onRequest(GetResponseEvent $event)
    {
        $request = $event->getRequest();

        $locale = $request->query->get('locale');
        if (null !== $locale && $this->isLocaleValid($locale)) {
            $request->setLocale($locale);
            $this->localContext->addContext(new MyLocaleContext($locale), '500');
        }
    }
```
PS:  i struggled finding where the admin local was set from. Apparently from the adminuser locale. Might be usefull to explain in the documentation.
