### ISSUE TITLE
switch channel by prefix uri

### ISSUE THREAD

**Issue by Bonobomagno** [Sylius/Sylius#8781]
| Q                | A
| ---------------- | -----
| Bug report?      | no/
| Feature request? | yes
| BC Break report? | no/yes
| RFC?             | no/yes
| Sylius version   | 1.0.0

Any solution for global channel like _locale?
The RequestBased is not enought for who want to use a simple /channel(country)/locale(lang) path.
I found someone doing it here, but that solution is not working for me.
My first try was using che BasedRequestResolver, but no way to make it work.
any idea ?

**Comment by Bonobomagno** [comment]
Ok, now something is working. Idk why becouse i didnt change nothing.
On first moment i used a CustomeResolver, that implements requestResovlerInterface on tag sylius.context.channel.request_based.resolver
But, this didnt work. Also, dump() didnt work, till now.

When it work: only on  bin/console server:start host mode.
If i use my webserver istead with true hostname, he throw "the "xx" locale is unavailable in this channel".
NonChannelLocaleListener.php is throwing the error.

My dump is not shown. This mean that on server:start the CustomResolver start before LocaleListener, instead on true webserver, it start after. This is pretty awful!

**Comment by Bonobomagno** [comment]
Ok. i found a way, and i think that would be nice to integrate it.
part1:
Must copy LocalListener as CustomListener and use parameterBag of request to handle a new prefix: {channel}
tags it as kernel.event_subscribe and inject @request_stack @route 

Part2:
Implement own CustomBasedRequestResolver (implements RequestResolverInterface)

on findchannel you can use findOneByCode ($requestRule); where $requestRule is _prefix attribute of $request. (remember: admin route dont have prefix)

part3:
Now you have a domain/prefix/locale route based shop, but still something dont work as wanted.
For example if all channel dont have the same shared lang, error will be thrown.
Is just a redirect, but still not nice to have.

I'm open to different solution, but for now i will not PR. Sorry, i still dont use Behat :/
PS.
I think that feature request would be a better tag.

**Comment by Bonobomagno** [comment]
remove from stale plz.
any future plan about custom url structure? 
It is mandatary for seo purpose.

**Comment by NoResponseMate** [comment]
> bump

related #5846

**Comment by pamil** [comment]
Let's continue the discussion in #5846.
