### ISSUE TITLE
Admin manage customers  display error

### ISSUE THREAD

**Issue by benyang2015** [Sylius/Sylius#8784]
on product env, customer grid not display,
![customer-not-display](https://user-images.githubusercontent.com/15188607/31273050-b0d321de-aabf-11e7-938d-37d418e4f719.jpg)

on dev env, customer grid display all customer
![dev-display](https://user-images.githubusercontent.com/15188607/31273060-b791c98a-aabf-11e7-81c4-d60440eecde0.jpg)

**Comment by CoderMaggie** [comment]
@benyang2015 all environments have separate databases, that is why you see different data. You probably do not have any customers on the production environment.
