### ISSUE TITLE
Javascript (or maybe just backend bundles?) not cascading back to default theme

### ISSUE THREAD

**Issue by johnrisby** [Sylius/Sylius#8789]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.0

When creating a new theme, any templates not in your own theme are taken from the default SyliusShopBundle views - correctly, otherwise you'd need to copy all the files - but javascript resources don't seem to be - at least in backend bundles.

I installed CKEditor for use on the backend to edit product descriptions. I installed it from https://github.com/egeloen/IvoryCKEditorBundle

Under the default ('no theme') theme, it was loading the ckeditor js file from

` <script type="text/javascript" src="/bundles/ivoryckeditor/ckeditor.js"></script>`

and worked perfectly. I just needed a small change to the frontend twig templates to change the filter to raw for the html to display correctly. All good.

but when the theme is turned on, it tries to load it from 

`<script type="text/javascript" src="/bundles/_themes/MyThemes/mytheme-theme/ivoryckeditor/ckeditor.js"></script>`

(theme name/folders changed to protect the innocent... ;) )

When I changed the theme on the channel I expected it to change the frontend only but now I realise that changing themes for a channel - obviously - also changes the theme for the backend if the admin is just accessed via /admin/ off that channel's url. Of course, a different channel just for admin could be set up to avoid this problem.

When CKEditor stopped working in the backend I was confused as it was several hours after adding the theme so I didn't realise the connection. Eventually I spotted it in the javascript console.

I solved it with a symbolic link, but this could cause a lot of confusion for people.

How far this problem extends, I don't know. Is it just backend bundles that don't fallback? I've not had chance to test any further.

Whether it's a 'bug' or something that could just be pointed out in the documents, I'm not sure. But maybe this issue will save some people some head scratching.

**Comment by stefandoorn** [comment]
I think you are missing the usage of 'sylius:theme:assets:install' command to copy the CKEditor assets to the theme folder. Might be nice to mention something like this on http://docs.sylius.org/en/latest/components_and_bundles/bundles/SyliusThemeBundle/your_first_theme.html e.g. I cannot find in the current docs mentions to this command anymore, while it's rather crucial imo.

**Comment by stefandoorn** [comment]
https://github.com/Sylius/Sylius/issues/8641

**Comment by stefandoorn** [comment]
This information might be suitable to make more prominent also on the 'Your First Theme' page: http://docs.sylius.org/en/latest/components_and_bundles/bundles/SyliusThemeBundle/important_changes.html#assets.

**Comment by johnrisby** [comment]
Yes, that is the issue. So this is a documentation issue and needs to be added to the documentation at http://docs.sylius.org/en/latest/book/themes/themes.html

It's mentioned here - http://docs.sylius.org/en/latest/components_and_bundles/bundles/SyliusThemeBundle/important_changes.html#assets

But it should imo be on the first page as it's crucial and documentation should be as simple as possible to follow rather than having to hunt around.

**Comment by johnrisby** [comment]
Issue now resolved. It was an oversight on my part due to the documentation not being as clear as it could have been (that's my excuse anyway ;) Documentation PR submitted and approved so I'm closing this. Thanks.
