### ISSUE TITLE
mutil chanel on backend, the frontend error

### ISSUE THREAD

**Issue by benyang2015** [Sylius/Sylius#8792]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.0

Uncaught PHP Exception Sylius\Component\Channel\Context\ChannelNotFoundException: "Channel could not be found! Tip: You can use the Web Debug Toolbar to switch between channels in development.

**Comment by Koc** [comment]
Possible duplicate of #981

**Comment by gabiudrescu** [comment]
have you followed the installation instructions correctly?

**Comment by benyang2015** [comment]
yes, followed the installation
$ composer create-project sylius/sylius-standard my-sylius-shop && cd my-sylius-shop
$ php bin/console sylius:install
$ yarn install && yarn run gulp
$ php bin/console server:start

**Comment by gabiudrescu** [comment]
have you opted for using dummy data? or have you played around with Channels configuration?

**Comment by benyang2015** [comment]
how to config channel？where the doc

**Comment by GSadee** [comment]
@benyang2015 please use issues to report bugs, propose new features or discuss new functionalities. However, when you are creating an issue, describe it as good as you can.

**Comment by lchrusciel** [comment]
Probably misconfiguration of channels. Closing.
