### ISSUE TITLE
Sylius under scrutiny

### ISSUE THREAD

**Issue by gabiudrescu** [Sylius/Sylius#8794]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.0

Symfony published today's blogpost with a link to an article where eCommerce platforms built using this framework get under the scrutiny of various code analysis tools. Sylius being one of the platforms.

Go check it out: https://www.tomasvotruba.cz/blog/2017/10/02/easy-coding-standard-and-phpstan-meet-3-symfony-ecommerce-projects/

Should this be worrying in some way?

**Comment by pjedrzejewski** [comment]
Well, these analyses seem to me part of the marketing strategy from ShopSys (as far as I know, Tomas is working for them as a contractor) to say "Hi, we are here too!", which is totally fine with me. That being said, comparing coding standards and static analysis is I believe one of the least important comparisons you can do, especially without presenting the actual functionality of the platforms etc. Nonetheless, we should fix some of these issues, we have them reported on ScrutinizerCI too.
