### ISSUE TITLE
how to add image or media to product description

### ISSUE THREAD

**Issue by benyang2015** [Sylius/Sylius#8795]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.0

**Comment by GSadee** [comment]
**Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our Slack or [stackoverflow](https://stackoverflow.com/questions/tagged/sylius)
