### ISSUE TITLE
Wrong method in example on documentation of attributes

### ISSUE THREAD

**Issue by reyostallenberg** [Sylius/Sylius#8799]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.0

`$attributeFactory->createWithType($type)` should be `$attributeFactory->createTyped($type)`

See: 
https://github.com/Sylius/Sylius/blob/362ef04e123b36c11bdb891bbf83d9b67a81c99c/docs/book/products/attributes.rst#L41
https://github.com/Sylius/Sylius/blob/362ef04e123b36c11bdb891bbf83d9b67a81c99c/docs/book/products/attributes.rst#L51

**Comment by GSadee** [comment]
@reyostallenberg thank you for reporting this. Could you open a PR with this change?

**Comment by garbetjie** [comment]
I hope you don't mind, I took the liberty of creating a pull request for this?

**Comment by reyostallenberg** [comment]
Great!
