### ISSUE TITLE
error on frontend user creation

### ISSUE THREAD

**Issue by Bonobomagno** [Sylius/Sylius#8801]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | master

i have this erro:
 **The identifier id is missing for a query of Sylius\Component\Core\Model\Customer**

basically my uri is /en_US/account/dashboard?id=number
Istead it must be just home ( /en_US) on first redirect.

how to fix it?
#ShopBundle/Rerouces/config/routing/security.yml
from 
`sylius_shop_register:
    path: /register
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.customer:createAction
        _sylius:
            template: "@SyliusShop/register.html.twig"
            form: Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerRegistrationType
            event: register
            redirect:
                route: sylius_shop_account_dashboard
`

to
`sylius_shop_register:
    path: /register
    methods: [GET, POST]
    defaults:
        _controller: sylius.controller.customer:createAction
        _sylius:
            template: "@SyliusShop/register.html.twig"
            form: Sylius\Bundle\CoreBundle\Form\Type\Customer\CustomerRegistrationType
            event: register
            redirect:
                route: sylius_shop_homepage
`

**Comment by Bonobomagno** [comment]
same error on verify. 
Same type of fix.

**Comment by nickvanderzwet** [comment]
It seems like https://github.com/Sylius/Sylius/blob/master/app/config/security.yml#L102 doesn't work?

**Comment by PapsOu** [comment]
I can confirm this bug with Sylius 1.0.4

The customer is not authenticated, so the service sylius.context.customer cannot find the newly registred customer.

**Comment by alexrowesoap** [comment]
This is still happening on 1.2.3 fresh install

**Comment by alexrowesoap** [comment]
I've been debugging this this morning.
I could be wrong, but would appricate a logic check.
After creating a user, you get directed to https://storename.com/account/dashboard?id=2
One of the first points outside the kernel is showAction in vendor\sylius\sylius\src\Sylius\Bundle\ResourceBundle\Controller\ResourceController.php. It tries to generate the configuration via a configuration factory. At this point in execution metadata is a properly instanciated object:
![temp_metadata](https://user-images.githubusercontent.com/29568210/43254011-4ae790a4-90be-11e8-81fe-dee1e7d17135.JPG)
and request is a Symfony\Component\HttpFoundation\Request class wherein query->parameters is an array where the only element is `id = 2`. Thus, in theory, the factory should have everything it needs.
Going into vendor\sylius\sylius\src\Sylius\Bundle\ResourceBundle\Controller\RequestConfigurationFactory.php in the create method it merges the default params (which id is not in (these values come from vendor\sylius\sylius\src\Sylius\Bundle\ResourceBundle\DependencyInjection\Configuration.php)) and any api params, which are not present in this instance. Thus id is never injected into $parameters, which means it isn't in the generated configuration object, which in turn (inside findOr404 back in the resource controller, which then loads get in the SingleResourceProvider) eventually tries to run `return $repository->$method(...$arguments)` where $repository is the correct CustomerRepository, $method is the correct string of "find" but $arguments is null from the above.
![sylius_user_end_result](https://user-images.githubusercontent.com/29568210/43255258-431d2d0e-90c1-11e8-97e2-5639d1327623.jpg)
<sup>Small note: I shopped in the watch as it was obscured, hence it being in an odd spot</sup>

so the question is, is the configuration factory wrong to not look in the request query params, or is this really a security config issue?

**Comment by unicolored** [comment]
> Short term fix is to redirect the user to the login rather than the dashboard:
> Insert the follwoing into app/config/routing.yml

Works for me, i confirm that the problem was the redirection in the dashboard.
Sylius 1.3.1

**Comment by Zortor58** [comment]
Nice fix, problem is still occurring with current version of sylius

**Comment by atapatel** [comment]
The identifier id is missing for a query of App\Entity\Customer\Customer
For sylius 1.8.1
