### ISSUE TITLE
Shipping cost in purchase flow are wrongly calculated when you change country

### ISSUE THREAD

**Issue by dimitrizetzsche** [Sylius/Sylius#8805]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | v1.0.0-beta.1

In our Sylius configuration we have different shipping cost per country. Eg: Germany 10€ and Belgium 5€.
We ran into the problem where the total cost where wrongly calculated/shown when a customer changes his country.

**Use case:**
- Customer buys a product of 500€ and selects Germany as his shipping country. The shipping cost for Germany is 10€. Total cost = 510€
- The customer sees his total cost on the summary page: 510€
- The customer uses the back button which is available in the flow (not the browser button) and goes back to the point where he can chose his shipping address --> the customer changes his country to Belgium (shipping cost = 5€)
- The customer goes forward into the flow and there is no shipping cost shown on the order summary page, the total cost on this page is 500€, which is incorrect. However on the last step, right before when you are send to a payment provider (where all the details are show and where you can add a comment), the shipping cost for Belgium is shown. The total cost here is 505€ which is correct

**Comment by GSadee** [comment]
I've been trying to reproduce that on a current version, but without success.

**Comment by pjedrzejewski** [comment]
I think it is because we show only items total on the small summary during the checkout steps. May be misleading indeed. Perhaps we change it to total? WDYT?

**Comment by GSadee** [comment]
Ok, maybe I misunderstood the issue 😃  We are displaying on this small summary only subtotals of items. If we display there a total, it is changing after the select shipping method step, not after the addressing step when the country is changed. So I guess that this is an issue 😃
