### ISSUE TITLE
[Documentation] Locale component missing docs

### ISSUE THREAD

**Issue by CoderMaggie** [Sylius/Sylius#8811]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Docs request? | yes
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0

* title should be `Locale` instead of `Locales`
* at least the `CompositeLocaleContext` should be described here in place of the empty `LocaleContext` paragraph - we should add that it has the `getLocaleCode` method, and that it is a composite of different contexts which are prioritized in it (the one with highest priority is used if it exists)

* we can also mention that the following contexts reside in the Locale component: `ImmutableLocaleContext` and `ProviderBasedLocaleContext`

**Comment by nightrainlily** [comment]
I'll work on this!
