### ISSUE TITLE
[ProductAttribute] Horizontal attribute

### ISSUE THREAD

**Issue by Bonobomagno** [Sylius/Sylius#8818]
| Q                | A
| ---------------- | -----
| Bug report?      | no/yes
| Feature request? | yes
| BC Break report? | no/yes
| RFC?             | no/yes
| Sylius version   | 1.x.y

Any plan for making horizontal attribute? I'm talking about common shared attribute (aka tags). Something like "brand" or "author". Make no sense rewrite them every time. And of course this would make filtering by attribute (orizzontal) easer.

thanks

**Comment by gabiudrescu** [comment]
we created brands like a dedicated entity. the reasons were:
 - brands have logos
 - brands have a priority field - an based on that priority we decide to sort them in our filters

but brands can also be attributes or taxons. I think this depends on the implementation of the website.

**Comment by Bonobomagno** [comment]
I didn't found the brands, but this is not important.  horizontal taxonomy
is a basic features as vertical (classic category) one.

Il 12 ott 2017 17:07, "Gabi Udrescu" <notifications@github.com> ha scritto:

**Comment by Bonobomagno** [comment]
I'm talking about predefined chose attribute. 
So i can create an author attribute_taxon and set a list of author. When i create a product that use attribute_taxon author, i can just pick the right author, without typing. So reference it, instead of using a string.
This make filtering by author easer, ofc.

Did you think you can tag this as FR?

**Comment by Bonobomagno** [comment]
I see a lot of features request or PR about this type of feature, any plan about it?
Any news?
