### ISSUE TITLE
Problem to extend form

### ISSUE THREAD

**Issue by TELLO0815** [Sylius/Sylius#8822]
| Q                | A
| ---------------- | -----
| Bug report?      | no/
| Feature request? | no/
| BC Break report? | no/
| RFC?             | no/
| Sylius version   | 1.0.0

I have a problem to extend the form. I just want to change the birthday format in EU style (dd.MM.yyyy). So i create the src/AppBundle/Form/Extension/CustomerProfileTypeExtension.php 

```
<?php

namespace AppBundle\Form\Extension;

use Sylius\Bundle\CustomerBundle\Form\Type\CustomerProfileType;
use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

final class CustomerProfileTypeExtension extends AbstractTypeExtension
{
/**
* {@inheritdoc}
*/
public function buildForm(FormBuilderInterface $builder, array $options)
{

// Change to EU Style dd.MM.yyyy
$builder->add('birthday', BirthdayType::class, [
'format' => 'dd.MM.yyyy',
]);
}

/**
* {@inheritdoc}
*/
public function getExtendedType()
{
return CustomerProfileType::class;
}
}
```

 and i changed the AppBundle/Resources/config/services.yml to 

```
services:
app.form.extension.type.customer_profile:
class: AppBundle\Form\Extension\CustomerProfileTypeExtension
tags:
- { name: form.type_extension, extended_type: Sylius\Bundle\CustomerBundle\Form\Type\CustomerProfileType } 

```

BUT NO CHANGE. Cache clear not helping me!

**Comment by Zales0123** [comment]
**Sylius** issues should used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our Slack or [stackoverflow](https://stackoverflow.com/questions/tagged/sylius) ;)
