### ISSUE TITLE
Customising action of existing resource controller needs return type declaration

### ISSUE THREAD

**Issue by othbert** [Sylius/Sylius#8834]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.0

The example in the docs shows overriding the showAction on the product controller, without specifying the return type. PHP 7.1(+?) requires specifying :Response as the return type or there is an error at compile time.

```[Symfony\Component\Debug\Exception\FatalErrorException]
  Compile Error: Declaration of AppBundle\Controller\ProductController::showAction(Symfony\Component\HttpFoundation\Request $request) must be compatible with Sylius\Bundle\ResourceBundle\Controller\ResourceController::showAction(Symfony\Component\HttpFoundation  
  \Request $request): Symfony\Component\HttpFoundation\Response

**Comment by GSadee** [comment]
Hi @othbert! Thanks for reporting this, would you like to open a PR with this fix?
