### ISSUE TITLE
[Documentation] Payment channel association

### ISSUE THREAD

**Issue by PapsOu** [Sylius/Sylius#8849]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.1

Found a wrong usage description about associating payment methods and channels

http://docs.sylius.org/en/latest/book/orders/payments.html

```
In order to have your new payment method available in the checkout remember to add it to your desired channels:

$channel->addPaymentMethod($paymentMethod);
```

Channel entity does not have method `addPaymentMethod(PaymentMethodInterface $paymentMethod)`. But PaymentMethod entity have method `addChannel(ChannelInterface $channel)`

Maybe replacing `$channel->addPaymentMethod($paymentMethod);` by `$paymentMethod->addChannel($channel)` will avoid problems.

**Comment by GSadee** [comment]
@PapsOu could you create a PR with this fix?

**Comment by PapsOu** [comment]
Done : https://github.com/Sylius/Sylius/pull/8877
