### ISSUE TITLE
[ProductAttribute] Creation "select" type attribute from the Admin UI

### ISSUE THREAD

**Issue by rudestan** [Sylius/Sylius#8852]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.1

1) In the Admin UI during the creation of "Select" type Attribute there is no possibility to specify the name of the items in the choice array. As a result automatically generated choice key names will be given in format "9c75a866-b01d-11e7-a44b-791088f6a089". It might be good to provide the ability to give custom names per choice, for example if we would like to use the choice names to create a search request.

The auto-inserted demo fixtures have proper human-readable choice item keys.

From fixtures:

`a:4:{s:8:"multiple";b:0;s:7:"choices";a:4:{s:19:"invisible_porcelain";s:21:"Invisible porcelain 1";s:11:"banana_skin";s:11:"Banana skin";s:9:"porcelain";s:9:"Porcelain";s:9:"centipede";s:9:"Centipede";}s:3:"min";N;s:3:"max";N;}`

Created from the Admin UI:

`a:4:{s:7:"choices";a:1:{s:36:"6c84a1f6-b01e-11e7-a64a-5db6175fa47a";s:13:"Intel Core i3";}s:8:"multiple";b:0;s:3:"min";N;s:3:"max";N;}`

2) Small suggestion:

It is a bit confusing that the `storage_type` of "select" attribute is "json" however, in fact, it is a PHP serialized array. I know this is how the Doctrine handles the array type fields. However, would not it make more sense either to rename the `storage_type` from json to something like `serialized_collection` (or something similar that will corresponds to the real type) or change the type of `configuration` field from `array` to `json` so the Doctrine will store the real json?

**Comment by pjedrzejewski** [comment]
We switched to UUID to avoid bugs with renaming the values, etc. Also, you are right about the column type... it should be JSON. We need a PR with a migration for that, would you find some time to contribute this? Thanks for reporting anyway!

**Comment by rudestan** [comment]
@pjedrzejewski Regarding the JSON type, sure i would love to help and contribute and will do it in the nearest future. 
The UUID, of course, definitely helps to avoid naming collisions, but i was trying to implement filters that mapped to attributes. During rendering of the form i am taking into account the type of the corresponding attribute and it's configuration. Everything working fine, except that when you submit the form via get, the URL with such values looks ugly, e.g.: `processor[]=6c84a1f6-b01e-11e7-a64a-5db6175fa47a&processor[]=9c7631b4-b01d-11e7-8bfa-5750f90e01ad ...` etc. So if you have a lot of filters with choices the URL will become too long and fully unreadable. I would say of course it is a minor issue and i'll do some workaround, but was thinking maybe it still makes sense to think about this functionality out of the box.
Thanks for the reply.
