### ISSUE TITLE
AbortMigrationException on fresh install with postgres

### ISSUE THREAD

**Issue by programaths** [Sylius/Sylius#8853]
| Q                | A
| ---------------- | -----
| Bug report?      |  yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.0
| Posgres verison | 9.6.5
| Host | Distributor ID: Ubuntu <br> Description:    Ubuntu 17.04 <br>  Release:        17.04 <br> Codename:       zesty <br> Station : HPDV7 (646 bits)
| PHP Version | PHP 7.1.10

# How to reproduce

## Setup postgres :

```
$ su postgres
$ psql
# create user sylius LOGIN PASSWORD '1234';
# create database sylius OWNER sylius;
# create database sylius_dev OWNER sylius;
```

In `app/config/parameters.yml`:

```
parameters:
    database_driver: pdo_pgsql
    database_host: 127.0.0.1
    database_port: 5432
    database_name: sylius
    database_user: sylius
    database_password: 1234
   ...
```

## Setup sylius

Follow the standard installation procedure :

```bash
$ wget http://getcomposer.org/composer.phar
$ php composer.phar create-project sylius/sylius-standard project
$ cd project
$ yarn install
$ yarn run gulp
$ php bin/console sylius:install
```
# Result

>  [Doctrine\DBAL\Migrations\AbortMigrationException]  
  Migration can only be executed safely on 'mysql'.

**Comment by nicholasruunu** [comment]
Any information on this issue? 1.0 milestone failed?

**Comment by it-all** [comment]
I am getting this error too. Does this mean that Sylius isn't compatible with PostgreSQL?

**Comment by teohhanhui** [comment]
This is the workaround I used in a fresh Sylius-Standard project:

1. Remove all migrations from `app/migrations`
2. `bin/console doctrine:migrations:diff`
3. `bin/console doctrine:migrations:migrate`
3. Profit(?)

**Comment by pamil** [comment]
@teohhanhui this way works only for a fresh installation, migrations often include more complicated, hand-made transformations to make upgrades effortless.

**Comment by pamil** [comment]
Overall, to properly support PostgreSQL we would need to run tests on both databases and provide additional fixtures, which is something we don't have enough resources to do right now. The solution here might be to start up a community project providing support for PostgreSQL-based migrations made by people who actually use it.

**Comment by teohhanhui** [comment]
As long as Sylius doesn't use any MySQL-specific features or depend on any quirks of MySQL, things should work fine on PostgreSQL. Migrations could be adapted by the users themselves. :laughing:

I think it's worth having a section in the docs about using a different DBMS, because currently it's claimed that you could use something else like PostgreSQL, but the user is left hanging.

**Comment by it-all** [comment]
@teohhanhui it looks like there's an incompatibility referenced in #7978.

**Comment by teohhanhui** [comment]
@it-all Thanks for the heads up.

**Comment by Codealist** [comment]
Having the same issue :(

**Comment by teohhanhui** [comment]
@Codealist Please try the workaround above: https://github.com/Sylius/Sylius/issues/8853#issuecomment-379024893

**Comment by andriusdj** [comment]
Hello,

I am a Symfony developer and I am in love with the project :heart_eyes_cat: already..

The Migrations scripts are just a bunch of lazy dumps of Mysql database statements and the $schema argument of the component is not in use which would allow installation on any Doctrine-supporting infrastructure.

I would like to fix this and make a pull request to merge it for the future generations. 

Would you be OK with this?

I would just need information on how we should do this. I am think to simply edit the Migrations/VersionXXX.php and use DBAL for creating tables and all that is needed.

**Comment by omarbg** [comment]
i'm a symfony developer  for many years ago 
i get same issue 
here is how i resolve it 
1-go to migration directory in the project under **src**  remove all  migration files
2-generate new migration file using "**php bin/console make:migration**"
3-finaly do this "**php bin/console doctrine:migration:migrate**"

this works for me :)

![image](https://user-images.githubusercontent.com/6241826/59276340-0629f580-8c56-11e9-9d74-d571e2122313.png)

**Comment by storm1er** [comment]
Issue to be reopen, as version 1.8.0 include migrations for mysql only from the packages, so the workaround here is not applicable :/

**Comment by 3kynox** [comment]
I confirm, switching to mysql in the meantime

**Comment by lchrusciel** [comment]
Hey @storm1er and @3kynox. Can you try fix provided here: https://github.com/Sylius/Sylius/issues/11851#issuecomment-764952143?
