### ISSUE TITLE
ProductVariants REST API - Updating variants without version not working

### ISSUE THREAD

**Issue by ce-bo** [Sylius/Sylius#8859]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.1

Hi there! I try to update product variants without the version. Unfortunately it doesn't work because of the missing version number. The version handling should be done by Sylius automatically.

Maybe it's a bug?!
Even if I send a new version number for each update request, it will only be working if any data has changed. Otherwise it will also crash with a 409 Conflicted response.

Thank you in advance!

**Comment by GSadee** [comment]
Hi @ce-bo! This feature has been added to `ProductVariant` entity to resolve race conditions on inventory. The `version` field is necessary while sending a request with updating a product variant, so, there is no way to handling that automatically by Sylius. 

When you are sending a request to update product variant, you should send a current version from given product variant (not a new one), version increments automatically after each change in database.

**Comment by ce-bo** [comment]
Ok, i will try it this way. I keep you up to date.

**Comment by ce-bo** [comment]
Okay ... I can confirm the behavior.
We have found a good soultion for us to handle the versions. I think this issue can be closed.

But maybe it would be a good option to configure wether the version is required or not.

**Comment by GSadee** [comment]
That could be a good idea, however I am not sure if there is a possibility to do that with doctrine.
