### ISSUE TITLE
Fatal Error when deleting product variants via the admin interface

### ISSUE THREAD

**Issue by ce-bo** [Sylius/Sylius#8861]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.1

I try to delete a product variant via the admin interface and it crashes:
Type error: Argument 2 passed to Sylius\Bundle\ResourceBundle\Controller\RedirectHandler::redirect() must be of the type string, null given, called in vendor\sylius\sylius\src\Sylius\Bundle\ResourceBundle\Controller\RedirectHandler.php on line 104

PHP 7.1.8
Windows
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0
Apache/2.4.27 (Xampp Windows)

**Comment by GSadee** [comment]
I've been trying to reproduce this bug, but without success, everything works fine in the current version. Did you make any customizations? Could you give us more details?

**Comment by ce-bo** [comment]
Hi @GSadee, thank's for your reply!

Please have a look at Sylius/Bundle/ResourceBundle/Controller/RequestConfiguration.php:222
$referer = $this->request->headers->get('referer');

In my case there is no 'referer' header. So I guess, this could be the reason why the funciton Sylius\Bundle\ResourceBundle\Controller\RequestConfiguration::getRedirectReferer() will return null and therefor crashes.

**Comment by GSadee** [comment]
I see where is the problem, but I have no idea why, probably I don't have enough information to help you. Are you using clear instance of Sylius or you customized sth?

**Comment by ce-bo** [comment]
I use a clear instance of Sylius installed by using the composer create-project command.
No customizations.

**Comment by ce-bo** [comment]
Let me know, if you need more information.
