### ISSUE TITLE
Found entity of type Sylius\Bundle\CoreBundle\Model\Taxon on association Project\CoreBundle\Entity\Product#taxons, but expecting Project\CoreBundle\Entity\Taxon

### ISSUE THREAD

**Issue by luigimassa** [Sylius/Sylius#888]
Hi, 
I override Taxon and Taxonomy for my business process. This is necessary to extend the model with my fields
Now when I create a new product I have the error in subject.
I investigate: in TaxonSelectionType  there is this code

```php
  public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $taxonomies = $this->repository->findAll();

        $builder->addModelTransformer(new TaxonSelectionToCollectionTransformer($taxonomies));

        foreach ($taxonomies as $taxonomy) {
            /* @var $taxonomy Taxonomy*/
            $builder->add($taxonomy->getId(), 'choice', array(
                'choice_list' => new ObjectChoiceList($taxonomy->getTaxonsAsList()),
                'multiple'    => $options['multiple'],
                'label'       => /** @Ignore */ $taxonomy->getName()
            ));
        }
    }
```

Method  **... $taxonomy->getTaxonsAsList() ...** create an array **$taxon[] = child;** but child are Sylius\Bundle\CoreBundle\Model\Taxon and not  Project\CoreBundle\Entity\Taxon

It's a bug or error in my configuration/override?

Thanks in advance

**Comment by geoffrey-brier** [comment]
@pjedrzejewski :+1:  Had the same problem and your solution works
