### ISSUE TITLE
OrderBundle Twig - Cannot instantiate abstract class

### ISSUE THREAD

**Issue by aarsla** [Sylius/Sylius#8886]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| OrderBundle version   | 1.0

- AggregateAdjustmentsExtension
```
new \Twig_Function('sylius_aggregate_adjustments', [$this->adjustmentsHelper, 'getAggregatedAdjustments']),
```
should be
```
new \Twig_SimpleFunction('sylius_aggregate_adjustments', [$this->adjustmentsHelper, 'getAggregatedAdjustments']),

```

Also present in MoneyBundle:
- FormatMoneyExtension
```
new \Twig_Filter('sylius_format_money', [$this->helper, 'formatAmount']),
```
should be
```
new \Twig_SimpleFilter('sylius_format_money', [$this->helper, 'formatAmount']),

```

**Comment by pamil** [comment]
Both `\Twig_SimpleFilter` and `\Twig_SimpleFunction` are deprecated and points to `\Twig_Filter` and `\Twig_Function` respectively - https://github.com/twigphp/Twig/blob/2.x/lib/Twig/Filter.php#L140.

Please make sure that you're using latest release of Twig (2.x) and if the error still exist, include an error message.

**Comment by mbabker** [comment]
`MoneyBundle` only has a Twig dependency in `require-dev` and `OrderBundle` doesn't declare one at all.  So perhaps this should be added to the `require` block in those bundles, or if the intent is to keep Twig optional add a `suggest` block and a note on the requirements.

**Comment by pamil** [comment]
Yeah, I guess `suggest` block might clarify it.
