### ISSUE TITLE
product select attribute translation can't work

### ISSUE THREAD

**Issue by benyang2015** [Sylius/Sylius#8898]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no/yes
| BC Break report? | no/yes
| RFC?             | no/yes
| Sylius version   | 1.0.1

on select attribute create page,can't click the multile locale

**Comment by GSadee** [comment]
I've checked that on the current master and I cannot reproduce that.
Probably you didn't do `yarn run gulp`.
