### ISSUE TITLE
product select attribute translation error

### ISSUE THREAD

**Issue by benyang2015** [Sylius/Sylius#8900]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.1.0

<img width="951" alt="attribute-error" src="https://user-images.githubusercontent.com/15188607/31993214-1c39038c-b9af-11e7-9070-e3d4b2f0d3b3.png">

**Comment by GSadee** [comment]
Did you do `yarn run gulp`?

**Comment by benyang2015** [comment]
yarn run gulp and clear cache，also get the error

**Comment by benyang2015** [comment]
@GSadee some js error?

**Comment by GSadee** [comment]
I have no idea for now, as I said before, I was trying to reproduce that, but everything works fine for me.

**Comment by benyang2015** [comment]
I update the code from your mege Again， also can't click the second language

**Comment by pamil** [comment]
Can you provide all the changes made before? Your channels configurations, your locales, your base locale etc.

**Comment by benyang2015** [comment]
![image](https://user-images.githubusercontent.com/15188607/32499496-b1b9efda-c40d-11e7-85b5-c5b539245a9d.png)
![image](https://user-images.githubusercontent.com/15188607/32499543-ca493268-c40d-11e7-9c0c-6d8fde8e0831.png)

**Comment by Zales0123** [comment]
I think I've managed to reproduce it 😄 there is a fix PR already opened
