### ISSUE TITLE
Applying taxes as order adjustment instead of orderItem adjustment

### ISSUE THREAD

**Issue by TomPradat** [Sylius/Sylius#8902]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.0

https://github.com/Sylius/Sylius/blob/8e33ffdd85c899cacbc9ef9ee81e00e202eaae14/src/Sylius/Component/Core/Taxation/Applicator/OrderItemsTaxesApplicator.php#L73

What are the reasons for having adjustment on each item for taxation ?

I have 3 items, 70 € each. I also have a coupon giving me a reduction of 5 €.
My taxe rate is 20%.

My order total price without taxes is then 210 - 5 = 205 €. Then my taxes should be 20%*205 = 41 €.

Instead i have (205 / 3) *20% = 13,6666667 (rounded to 13,67) taxes on each item. At then end i get 41,01 € of taxes.

Why don't we apply taxes as an order adjustment instead ?

How should i solve this ?

**Comment by Zales0123** [comment]
Hello @TomPradat! Answering your questions:
1. Taxes are distributed over order items (_de facto_ over order item units) to make returns easier and to allow us to handle each order item unit as a separate object. It means, we need taxes and promotions applied on order unit, to know exactly what's price of **each single** unit in order.
2. About taxes distribution it does not work like this in fact. Take a look at [this line](https://github.com/Sylius/Sylius/blob/8e33ffdd85c899cacbc9ef9ee81e00e202eaae14/src/Sylius/Component/Core/Taxation/Applicator/OrderItemsTaxesApplicator.php#L83) in a service you've mentioned. Total tax is calculated on order item, not on the whole order. And don't be afraid about rounding taxes for item units! 😄  In the [next line](https://github.com/Sylius/Sylius/blob/8e33ffdd85c899cacbc9ef9ee81e00e202eaae14/src/Sylius/Component/Core/Taxation/Applicator/OrderItemsTaxesApplicator.php#L84) there is an integer distributor used, which means that event if tax calculated for your **order item** would not be evenly divided between its units, each of them would get an absolute tax, without rounding. In your case, €41 for 3 units, will be distributed as €14, €14 and €13 :)

I hope that it made you a bit clearer, please as if you have some more questions ;)

**Comment by TomPradat** [comment]
Hi @Zales0123, Thank you for your answer.

Well For the coupon reduction i do have the behavior you're describing.

The 5 euro coupon produces the following adjustment on my order_item_units

-166 for the first one, -167 for the second one and -167 for the third one.

But for the taxes i have 1367 for each.

I did debug the process. My order_item_units are 7000 each.

Then the coupon produces the -166, -167 and -167 adjustments.

Then the taxes are applied on each order_item_unit including adjustment from the coupon (ie 6834, 6833, 6833).

So with the 20% taxes, i have : (6834 * 20% = 1366,8 rounded to 1367, 6833 * 20% = 1366,6 also rounded to 1367). But at the end i have 1367 * 3 = 4101 instead of 4100 as taxes.

Hope this is clear enough, tell me otherwise.
