### ISSUE TITLE
States not updated accordingly if user navigates away during payment processing

### ISSUE THREAD

**Issue by blankcheck** [Sylius/Sylius#8913]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.0beta2 (didn't check other versions)

Order/payment/shipment states are not updated accordingly if user navigates away/clicks browser's stop btn/closes browser during payment processing (with payment gateways which don't call your site back on some url).

**Steps to reporoduce:**

Implement i.e. authrozie.net (existing in payum). Get to payment screen. Click pay. Click browser's stop btn/navigate away. Credit card is charged but order/payment/shipment states are not updated.

**Why is this happening:**

States are updated during execution of Sylius\Bundle\PayumBundle\Controller:afterCaptureAction, specifically in extension for Payum Sylius\Bundle\PayumBundle\Extension:UpdatePaymentStateExtension. Problem is that afterCaptureAction is executed after redirect from Payum\Bundle\PayumBundle\Controller:doAction, basically meaning that we are relying on successful redirect to keep our data consistent - and of course, by i.e. navigating away, redirect can't happen.

**Resolution (quick fix):**

To quick fix it, I overrode route for Payum\Bundle\PayumBundle\Controller:doAction and replaced  Payum\Bundle\PayumBundle\Controller:doAction with my doAction in a way that states are updated there by adding         

```
$status = new GetStatus($token);
$gateway->execute($status);
```
before redirection.
_For anyone using this approach, don't forget use statement for GetStatus_

This is not ideal for sure and if we really want to treat this as a bug we should come up with more elegant solution.

**Comment by kortwotze** [comment]
I like this. This makes the payment capturing one step with clicking the button - and thus order data will stay up-to-date instead of getting old.
This case in general is a race-condition though, but this makes a good first aid patch. :)
