### ISSUE TITLE
Cancelled orders can be paid - inconsistent states

### ISSUE THREAD

**Issue by blankcheck** [Sylius/Sylius#8928]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.0beta2 (didn't check others)

Payment can be done even on canceled orders, leading to inconsistent states: order is paid for but still remains cancelled. This is particulary dangerous in combination with cron which cancels orders: Client is on payment screen (still didn't click pay), cron hits and cancells order, client hits pay - credit card is charged, order remains cancelled.

**Steps to reproduce**

Complete an order. Be on payment screen. Cancel order. Pay for order.

**Comment by Zales0123** [comment]
Seems to be fixed:

<img width="1200" alt="zrzut ekranu 2019-03-1 o 12 34 17" src="https://user-images.githubusercontent.com/6212718/53635890-d020b280-3c1e-11e9-8146-25a1a8ed7825.png">
<img width="1147" alt="zrzut ekranu 2019-03-1 o 12 45 35" src="https://user-images.githubusercontent.com/6212718/53636295-ef6c0f80-3c1f-11e9-9853-a0a49df1d80e.png">

Please, reopen if something is still not working (I've not checked it on PayPal, but I really think the result should be identical). 

🖖 🚀
