### ISSUE TITLE
Taxon per channel

### ISSUE THREAD

**Issue by Toumm** [Sylius/Sylius#8932]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.0

I am trying to customize Sylius to make the taxons specific per Channel. It means:
- Having a channel selector in the taxon creation/edition form;
- Edit how the taxon menu is rendered.
I am very new with Sylius so I am not sure where to start.

**Comment by Zales0123** [comment]
Hello @Toumm and welcome to the community! **Sylius** issues should used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our Slack (preffered) or [stackoverflow](https://stackoverflow.com/questions/tagged/sylius) ;) Also, take a look at our documentation, especially at the [Customization Guide](http://docs.sylius.org/en/latest/customization/index.html) which is very useful if you're just starting and adventure with **Sylius**. Good luck :)

**Comment by Chrysweel** [comment]
I found this issue searching on this topic on the internet, although it is already closed and it is old, it can be useful in case someone comes here today with this same question.

You can have different taxonomies by channels, in the channels section you can specify the taxon to use.

Create a new taxonomy.
Edit the channel and select that taxonomy.
The channel will only show the child taxonomies of that taxonomy.

**Comment by lchrusciel** [comment]
Hey @Chrysweel. Thanks for pointing this out. You are absolutely correct about it. We are about to create some doc page about it. 

Just for the record, this is a relatively new feature, part of 1.7 release, for anyone who will be looking for it ;) Introduced in #11012

**Comment by lchrusciel** [comment]
Described in: #11354
