### ISSUE TITLE
Tag/release 1.0.2 version of the various bundles

### ISSUE THREAD

**Issue by sweoggy** [Sylius/Sylius#8935]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | Kind of
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.2

Aren't the bundles supposed to be tagged at the same rate as the main sylius/sylius package?

**Comment by dragosprotung** [comment]
Any update on this ? It seems that not even the commits are showing up in the split repositories.
This is critical because of #8968

**Comment by loic425** [comment]
@pamil @pjedrzejewski same problem for me. It's critical.

**Comment by cezarystepkowski** [comment]
Waiting for it as well...

**Comment by sweoggy** [comment]
This issue is now preventing upgrading to Symfony 3.4 RC1 as well

**Comment by pjedrzejewski** [comment]
Sorry for the inconvenience, we are working on adjusting our git subtree split scripts to handle multiple branches. Hope to release these soon.

**Comment by loic425** [comment]
@pjedrzejewski is it ok ? cause I see 1.4 on packagist for resource bundle.
https://packagist.org/packages/sylius/resource-bundle

**Comment by pamil** [comment]
@loic425 it's ready, all packages are now tagged for 1.0.1-1.0.4 releases.

**Comment by loic425** [comment]
@pamil great great news :)
