### ISSUE TITLE
adminbundle : invalid csrf token , when trying to delete a customer

### ISSUE THREAD

**Issue by ecornelisse** [Sylius/Sylius#8936]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.1

I am using the default templates and no custom code here , yet i still get this csrf token error.

![screenshot from 2017-11-06 14-28-49](https://user-images.githubusercontent.com/11006071/32443368-0b6cf352-c2ff-11e7-9494-dbefa06bccd1.png)

**Comment by ecornelisse** [comment]
A bit offtopic but since 1.0 has been released now, theoretically nothing should be added to the 1.0 milestone as it's history now and there should be a new release milestone? Like 1.1? Depending on the roadmap of new features ofcourse.

**Comment by pamil** [comment]
1.0 milestone is added to mention that a specific issue or PR should be resolved in 1.0.x release. 1.0.x is still supported with bugfixes, whereas new features go directly to 1.1 milestone.

**Comment by pamil** [comment]
Cannot reproduce on 1.0.3-debv

**Comment by anolek** [comment]
I also have this issue in 1.0.4. I tried on demo.sylius.org and i got "Unexpected error occurred." when i try to delete one customer :( 

![image](https://user-images.githubusercontent.com/1519946/33239290-16f44d42-d29f-11e7-94c3-9f8cec7e4ba6.png)

**Comment by dev-ish** [comment]
Have the same issue, but for me it works on my development machine while in production i get the same error as above

**Comment by czende** [comment]
Still not able to delete shop user. Only in production 😞

**Comment by pamil** [comment]
Could you provide a failing Behat scenario?

**Comment by czende** [comment]
Up!

**Comment by pamil** [comment]
A failing Behat scenario still would be a great help :)

**Comment by pamil** [comment]
#9618 should reproduce this error.

**Comment by pamil** [comment]
Fixed in #9618.
