### ISSUE TITLE
sylius:install throws sylius_promotion 'created_at' cannot be null                                                 

### ISSUE THREAD

**Issue by pfwd** [Sylius/Sylius#894]
Running

```
php app/console sylius:install
```

whilst having the the fixes from https://github.com/Sylius/Sylius/pull/892

throws this different and unrelated error:

```
[Doctrine\DBA\DBALException]                                                
An exception occurred while executing 'INSERT INTO sylius_promotion (name,description, usage_limit, used, coupon_based, starts_at, ends_at, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)' with params 
["New Year","New Year Sale for 3 and more items.", null, 0, 0, null, null, null, null]  
: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'created_at' cannot be null 
```

**Comment by patrick-mcdougle** [comment]
@pfwd We shouldn't need to set createdAt explicitly. Were you using a doctrine metadata cache? I'm trying to understand it, but I think there might be a bug in gedmo for mapped superclasses when using a metadata cache. If you were using a metadata cache at the time, I'd like to know to further support my hypothesis.

Thanks,
Patrick

**Comment by pfwd** [comment]
@patrick-mcdougle I can't be 100% sure if I was as it was sometime ago. It was definitely based on a extended entity if that helps.
