### ISSUE TITLE
Taxt rate

### ISSUE THREAD

**Issue by darkiron** [Sylius/Sylius#8944]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.0

How to select for product a taxe rate or a taxon ? Have only Taxe Categorie on product

**Comment by GSadee** [comment]
Hi @darkiron! Sylius issues should used to report bugs, propose new features or discuss new functionalities. For everything else, please, use our Slack or stackoverflow ;) Also, take a look at our documentation if you're just starting an adventure with Sylius. Good luck :)
