### ISSUE TITLE
cart total ajax not work

### ISSUE THREAD

**Issue by benyang2015** [Sylius/Sylius#8947]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.2

![image](https://user-images.githubusercontent.com/15188607/32549517-c2872d8e-c4c4-11e7-950a-589e3a261c0d.png)

**Comment by pamil** [comment]
You need to click "Update cart" when you modify the quantity of a product, there's no AJAX calculation there.
