### ISSUE TITLE
[PayumBundle] PayPal Express Checkout: sum of payment request item lines isn't order amount

### ISSUE THREAD

**Issue by jolicht** [Sylius/Sylius#8950]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.2

# Description of potential bug

order with € 100 product costs and € 10 shipping costs (both excluding vat) results in paypal payment request with amount and item amount of **132** but summed up amount of request items is **134**, see [payment_request_params.txt](https://github.com/Sylius/Sylius/files/1457635/payment_request_params.txt), captured in [PayumBundle/Action/CapturePaymentAction.php Line 78](https://github.com/Sylius/Sylius/blob/c025bb584064b6cf3c53f110123444f104074f37/src/Sylius/Bundle/PayumBundle/Action/CapturePaymentAction.php#L78) ($details)

Payment Request items:
- amount: 132 
- item amount: 132
- product item amount: 100 
- tax total: 22
- shipping total: **12**

i think *shipping total* should be 10, if *total tax* includes both tax of products and shipping.

# Settings to reproduce
## Order Example

Order contains single product (€100 excluding VAT) and shipping (€10 exluding VAT), so order summary (/de_AT/checkout/complete) has following values:
- Product line: 
  - price: € 100.00
  - quantity: 1
  - sub-total: € 100.00
-  Summary:
  - subtotal: € 120.00
  - shipping-total: € 12.00
  - tax-total: € 22.00
  - promotion-total: € 0.00
  - total: € 132.00

### Channel
- code: default
- default tax zone: Default, Austria
- Tax calculation strategy: Order items based

### Shipping method
- code: domestic_default
- Tax category: **Default 20%**
- Austria/Amount: 10.00

### Tax category
- code: default_tax
- Name: Default 20%

### Tax rate
- code: tax_20_percent
- Amount: 20.00
- Included in price: **no**

### Example Product
- Price: 100.00
- Tax category: Default 20%

**Comment by h3llr4iser** [comment]
I have this problem: The totals of the cart item amounts do not match order amounts

**Comment by pcmdev** [comment]
I have the same problem. I'm using Sylius 1.1.0, "Included in price?" disabled and 20% tax rate applied to both products and shipping costs. In the cart everything look OK, but Paypal returns this error:

"The totals of the cart item amounts do not match order amounts."

**Comment by piermont** [comment]
As a temporary fix I've removed line 526 from `Sylius\Component\Core\Model\Order`.

**Comment by pamil** [comment]
Hmm, I don't get why are we adding the total `TAX_ADJUSTMENT` there, can someone else shed some light on this? /cc @Sylius/core-team

**Comment by piermont** [comment]
I think it would be also interesting being able to get totals including and excluding taxes. The order or cart subtotal should not include taxes when presented to the user (if "Included in price?" is not enabled), but they should be added in the total.

**Comment by andreasschacht** [comment]
Issue is still existing, so can we re-open this?

If shipping contains taxes, this taxes will be includes 2 times, here:
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/PayumBundle/Action/Paypal/ExpressCheckout/ConvertPaymentAction.php#L63

and here:
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/PayumBundle/Action/Paypal/ExpressCheckout/ConvertPaymentAction.php#L79

This results in `The totals of the cart item amounts do not match order amounts.` from the Paypal-API.

**Comment by fntneves** [comment]
I'm experiencing the same issue.

Shipping Taxes are included both in TaxTotal and ShippingTotal.

**Comment by lchrusciel** [comment]
Hello folks!

The bug probably still exists in the codebase, however we need to cover these cases with tests to start working on them. Are you able to add them to help us resolve this issue?

**Comment by vvasiloi** [comment]
It's probably related to https://github.com/Sylius/Sylius/issues/11279

**Comment by Zales0123** [comment]
Hi guys! To be honest, the best thing I can recommend is to move to [PayPalPlugin](https://github.com/Sylius/PayPalPlugin) as our official PayPal integration. The Express Checkout is deprecated and we will probably not invest in it... Let me know if it's a way to process this issue for you :) 🖖
