### ISSUE TITLE
[Documentation] Channel docs are wrong/misleading

### ISSUE THREAD

**Issue by othbert** [Sylius/Sylius#8953]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no/yes
| RFC?             | no/yes
| Sylius version   | 1.x.y

http://docs.sylius.org/en/latest/components_and_bundles/components/Channel/basic_usage.html

Shows `setChannel` method on a `ChannelContext` but the method doesn't exist. 
`use Sylius\Component\Channel\Context\ChannelContext;` The ChannelContext class doesn't exist here either.

Coincidentally, any pointers on how to set channel on a context (the current channel context) to switch between channels when the channel strategy is not known (request / hostname / single etc.)?

Thanks!

**Comment by Bonobomagno** [comment]
the file exist, but the setChannel no. No implementation of it.
And yes, no  way to set che channel. 
And you cant either enable/disable the strategy.

**Comment by othbert** [comment]
For me the file doesn't exist there either. There is a ChannelContext class but it is found in:
```...\Sylius\Component\Channel\Context\RequestBased\ChannelContext.php```

**Comment by pamil** [comment]
Fixed by #10205.
