### ISSUE TITLE
Type error: Return value of Sylius\Component\Core\Model\Channel::getLocales() must implement interface Doctrine\Common\Collections\Collection, null returned

### ISSUE THREAD

**Issue by itma** [Sylius/Sylius#8963]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.3

Hello

I have installed a fresh version of Sylius 1.0.3 and I am getting an exception like below:

`(1/1) FatalThrowableError
Type error: Return value of Sylius\Component\Core\Model\Channel::getLocales() must implement interface Doctrine\Common\Collections\Collection, null returned`

PHP version is 7.1.11-1

All the requirements passed the test during the installation process. I thought it has something to do with default_locale for intl extension, so I set the value to PL and still getting the exception.

**Comment by itma** [comment]
Update: I've reinstalled Sylius. For this particular installation I didn't put an example data for the shop. **It has been working for now.** I am not sure if the error is referring to the example data or maybe to the wizard (via console) where a user can input any data, for example a bad locale info (then he will get information about wrong locale, nevertheless maybe the bad value is being saved somewhere...? I don't know.). If I find a while I will investigate it more.

**Comment by damonsson** [comment]
Probably you open the site before data was added to database and cache catch this status (missing locales). Clear cache should be enough to fix it.

**Comment by itma** [comment]
@damonsson I opened the site after the console wizard told that everything had been established.

**Comment by atamaniuc** [comment]
I had this when moved cache and logs to` /dev/shm/` via setting environment variable `VAGRANT=VAGRANT`. This error occasionally appears after some requests on home page.
