### ISSUE TITLE
yarn install

### ISSUE THREAD

**Issue by hazasaad** [Sylius/Sylius#8964]
| Q                | A
| ---------------- | -----
| Bug report?      | no/yes
| Feature request? | no/yes
| BC Break report? | no/yes
| RFC?             | no/yes
| Sylius version   | 1.x.y

**Comment by Zales0123** [comment]
**Sylius** issues should used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our Slack or [stackoverflow](https://stackoverflow.com/questions/tagged/sylius) ;)
