### ISSUE TITLE
migration:diff problem - scheme always need in sync

### ISSUE THREAD

**Issue by mitalcoi** [Sylius/Sylius#8965]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Sylius version   | 1.1

Step to reproduce:
1)Install fresh Sylius app
2)apply migrations (or run sylius:install)
3)try to update scheme: bin/console do:sche:update --dump-sql
Output always be:
```
ALTER TABLE sylius_payment CHANGE details details JSON NOT NULL;
ALTER TABLE sylius_product_attribute_value CHANGE json_value json_value JSON DEFAULT NULL;
ALTER TABLE sylius_gateway_config CHANGE config config JSON NOT NULL;
```

System info:
php71
mysql 5.7.19

**Comment by Tetragramat** [comment]
It might be because migration was created for mysql version lower than 5.7.8.
The JSON data type was added into mysql in version 5.7.8.
Could be solved by adding condition into migration, if version > 5.7.8 then use differend sql.

https://dev.mysql.com/doc/refman/5.7/en/json.html

**Comment by kochen** [comment]
@mitalcoi are you using MariaDB v10.2.x?
https://github.com/doctrine/doctrine2/issues/6565

The pull request was already merged and pending release on the (hopefully) upcoming `v2.7`...

**Comment by mitalcoi** [comment]
@kochen previously we used it (and problem existsed also on mariadb), but now we've switched to mysql

**Comment by PapsOu** [comment]
@mitalcoi : Your problem was due tu doctrine migration bundle. see this closed issue for more information. https://github.com/doctrine/dbal/issues/2880

**Comment by pamil** [comment]
I guess this issue could be closed, please open a new one if that's not the case.
