### ISSUE TITLE
HttpFoundationRequestHandler

### ISSUE THREAD

**Issue by pdias** [Sylius/Sylius#8966]
With Symfony v3.3.13 i have this error:

_Fatal error: Class Sylius\Bundle\ResourceBundle\Form\Extension\HttpFoundati
  on\HttpFoundationRequestHandler contains 1 abstract method and must therefo
  re be declared abstract or implement the remaining methods (Symfony\Compone
  nt\Form\RequestHandlerInterface::isFileUpload_

Thanks,

Paulo

**Comment by onusgit** [comment]
Hello,
Also i am facing same issue on my server http://sylius.http5000.com/app_dev.php/admin/login
It's working fine in local.

There is PHP 7.1.11, FastCGI application served by Apache

**Comment by pamil** [comment]
What Sylius versions are you using?

**Comment by onusgit** [comment]
Its Sylius 1.0.3

**Comment by pamil** [comment]
It's related to http://symfony.com/blog/symfony-3-3-13-released, Sylius v1.0.4 fixing these coming in a few hours.

**Comment by onusgit** [comment]
Thanks Kamil

**Comment by pamil** [comment]
Sylius v1.0.4 released! 🎉

**Comment by pdias** [comment]
Hello Pamil,

Can you also update/fix the SyliusResourceBundle?

Thanks,

Paulo
