### ISSUE TITLE
Improvements to the bulk actions

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#8969]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.1.y

I suggest the following improvements for the bulk actions:

* [ ] Add confirmation modal (!), this is a matter of adding an appropriate "data-requires-confirmation" (IIRC), just like for the single delete button.
* [ ] When you select an entity that is in use (is referenced in an order), it is not deleted, although there is no flash message informing about the problem.

**Comment by GSadee** [comment]
@pjedrzejewski I've just checked that on the current `master` to be 100% sure, but all of these improvements are already implemented with the bulk actions 😃 
![zrzut ekranu 2017-11-21 o 08 20 39](https://user-images.githubusercontent.com/6140884/33059578-1f3a1c74-ce95-11e7-8d9f-bf5ef5cf159f.png)
![zrzut ekranu 2017-11-21 o 08 21 01](https://user-images.githubusercontent.com/6140884/33059579-2146c422-ce95-11e7-96e2-5fac839443f9.png)

**Comment by lchrusciel** [comment]
So let's close it :)
