### ISSUE TITLE
Problem installing Sylius when using yarn install

### ISSUE THREAD

**Issue by hazasaad** [Sylius/Sylius#8972]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.3

**Comment by Zales0123** [comment]
Could you please provide any more information about your problem? What is your environment? What kind of error do you get?
Btw - **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our Slack ;)

**Comment by hazasaad** [comment]
`C:\xampp\htdocs\project>yarn install
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ? node-sass: check python checking for Python executable "python"
[-/1] ? waiting...
[-/1] ? waiting...
[-/1] ? waiting...
error C:\xampp\htdocs\project\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\xampp\htdocs\project\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\xampp\htdocs\project\node_modules
node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --li
bsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\Program Files\nodejs\node.exe',
gyp verb cli 'C:\xampp\htdocs\project\node_modules\node-gyp\bin\node-gy
p.js',
gyp verb cli 'rebuild',
gyp verb cli '--verbose',
gyp verb cli '--libsass_ext=',
gyp verb cli '--libsass_cflags=',
gyp verb cli '--libsass_ldflags=',
gyp verb cli '--libsass_library=' ]
gyp info using node-gyp@3.6.0
gyp info using node@8.9.1 | win32 | ia32
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb which failed Error: not found: python2
gyp verb which failed at getNotFoundError (C:\xampp\htdocs\project\node_mo
dules\which\which.js:13:12)
gyp verb which failed at F (C:\xampp\htdocs\project\node_modules\which\whi
ch.js:68:19)
gyp verb which failed at E (C:\xampp\htdocs\project\node_modules\which\whi
ch.js:80:29)
gyp verb which failed at C:\xampp\htdocs\project\node_modules\which\which.
js:89:16
gyp verb which failed at C:\xampp\htdocs\project\node_modules\isexe\index.
js:42:5
gyp verb which failed at C:\xampp\htdocs\project\node_modules\isexe\window
s.js:36:5
gyp verb which failed at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb which failed python2 { Error: not found: python2
gyp verb which failed at getNotFoundError (C:\xampp\htdocs\project\node_mo
dules\which\which.js:13:12)
gyp verb which failed at F (C:\xampp\htdocs\project\node_modules\which\whiv`

**Comment by hazasaad** [comment]
IIn slack noone respond for my question

**Comment by hazasaad** [comment]
[yarn-error.log](https://github.com/Sylius/Sylius/files/1486765/yarn-error.log)

**Comment by hazasaad** [comment]
`C:\xampp\htdocs\sylius>yarn install
yarn install v1.3.2
[1/4] Resolving packages...
error An unexpected error occurred: "write EIO".
info If you think this is a bug, please open a bug report with the information p
rovided in "C:\\xampp\\htdocs\\sylius\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this
command.`

**Comment by Zales0123** [comment]
@hazasaad you must be aware, that **Sylius** does not officially support Windows environment now. Moreover, I think this is a bug connected with yarn itself on Windows os, not with **Sylius**. You should for sure check do you use the latest version of Yarn and maybe look for some help in Yarn community.

**Comment by hazasaad** [comment]
yarn 1.3.2 
sylius doestsupport windows environment?

**Comment by PastisD** [comment]
@hazasaad I had to install this : https://github.com/nodejs/node-gyp#on-windows

**Comment by hazasaad** [comment]
npm install -g node-gyp
this command also gives error to me

**Comment by PastisD** [comment]
@hazasaad I meant to follow instructions :P
For me i followed "Option 1"

**Comment by hazasaad** [comment]
npm install --global --production windows-build-tools gives error 
C:\>npm install --global --production windows-build-tools
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Win7\\AppData\\R
oaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "--product
ion" "windows-build-tools"
npm ERR! node v5.12.0
npm ERR! npm  v4.1.2

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Win7\\AppData\\R
oaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "--product
ion" "windows-build-tools"
npm ERR! node v5.12.0
npm ERR! npm  v4.1.2
npm ERR! code ECONNRESET

npm ERR! network socket hang up
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Win7\\AppData\\R
oaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global" "--product
ion" "windows-build-tools"
npm ERR! node v5.12.0
npm ERR! npm  v4.1.2
npm ERR! path C:\npm-debug.log.2818685483
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'C:\npm-debug.log.281868548
3'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, open 'C:\npm-debug.log.28186
85483']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\npm-debug.log.2818685483' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log``

**Comment by PastisD** [comment]
Did you install it via a cmd **run a administrator** ?

**Comment by hazasaad** [comment]
yeah

**Comment by PastisD** [comment]
@hazasaad have you tried with powershell ? If yes, so i've no idea :s

**Comment by Shiro94** [comment]
Try to run yarn global add windows-build-tools as administrator

**Comment by hazasaad** [comment]
@Shiro94  STILL GIVES ERROR `
C:\Windows\system32>yarn global add windows-build-tools
yarn global v1.3.2
[1/4] Resolving packages...
warning windows-build-tools > nugget > progress-stream > through2 > xtend > obje
ct-keys@0.4.0:
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning "windows-build-tools@1.3.2" has no binaries
Done in 40.35s.

C:\Windows\system32>cd C:\xampp\htdocs\sylius

C:\xampp\htdocs\sylius>yarn install
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ? node-sass: Build failed with error code: 1
[-/1] ? waiting...
[-/1] ? waiting...
[-/1] ? waiting...
error C:\xampp\htdocs\sylius\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\xampp\htdocs\sylius\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\xampp\htdocs\sylius\node_modules\n
ode-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --lib
sass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\xampp\\htdocs\\sylius\\node_modules\\node-gyp\\bin\\node-gyp
.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.0
gyp info using node@5.12.0 | win32 | ia32
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\xampp\htdocs\sylius\node_mod
ules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\xampp\htdocs\sylius\node_modules\which\whic
h.js:68:19)
gyp verb `which` failed     at E (C:\xampp\htdocs\sylius\node_modules\which\whic
h.js:80:29)
gyp verb `which` failed     at C:\xampp\htdocs\sylius\node_modules\which\which.j
s:89:16
gyp verb `which` failed     at C:\xampp\htdocs\sylius\node_modules\isexe\index.j
s:42:5
gyp verb `which` failed     at C:\xampp\htdocs\sylius\node_modules\isexe\windows
.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:82:15)
gyp verb `which` failed  python2 { [Error: not found: python2] code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (C:\xampp\htdocs\sylius\node_mod
ules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\xampp\htdocs\sylius\node_modules\which\whic
h.js:68:19)
gyp verb `which` failed     at E (C:\xampp\htdocs\sylius\node_modules\which\whic
h.js:80:29)
gyp verb `which` failed     at C:\xampp\htdocs\sylius\node_modules\which\which.j
s:89:16
gyp verb `which` failed     at C:\xampp\htdocs\sylius\node_modules\isexe\index.j
s:42:5
gyp verb `which` failed     at C:\xampp\htdocs\sylius\node_modules\isexe\windows
.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:82:15)
gyp verb `which` failed  python { [Error: not found: python] code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb check python launcher python executable found: "C:\\Python27\\python.ex
e"
gyp verb check python version `C:\Python27\python.exe -c "import platform; print
(platform.python_version());"` returned: "2.7.14\r\n"
gyp verb get node dir no --target version specified, falling back to host node v
ersion: 5.12.0
gyp verb command install [ '5.12.0' ]
gyp verb install input version string "5.12.0"
gyp verb install installing version: 5.12.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 5.12.0
gyp verb ensuring nodedir is created C:\Users\Win7\.node-gyp\5.12.0
gyp verb created nodedir C:\Users\Win7\.node-gyp\5.12.0
gyp http GET https://nodejs.org/download/release/v5.12.0/node-v5.12.0-headers.ta
r.gz
gyp WARN download ignoring invalid "proxy" config setting: "localhost"
gyp WARN install got an error, rolling back install
gyp verb command remove [ '5.12.0' ]
gyp verb remove using node-gyp dir: C:\Users\Win7\.node-gyp
gyp verb remove removing target version: 5.12.0
gyp verb remove removing development files for version: 5.12.0
gyp ERR! configure error
gyp ERR! stack Error: tunneling socket could not be established, cause=connect E
CONNREFUSED 127.0.0.1:80
gyp ERR! stack     at ClientRequest.onError (C:\xampp\htdocs\sylius\node_modules
\tunnel-agent\index.js:177:17)
gyp ERR! stack     at ClientRequest.g (events.js:273:16)
gyp ERR! stack     at emitOne (events.js:90:13)
gyp ERR! stack     at ClientRequest.emit (events.js:182:7)
gyp ERR! stack     at Socket.socketErrorListener (_http_client.js:306:9)
gyp ERR! stack     at emitOne (events.js:90:13)
gyp ERR! stack     at Socket.emit (events.js:182:7)
gyp ERR! stack     at emitErrorNT (net.js:1265:8)
gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:74:11
)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:98:9)

gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\xampp\\htdocs\\syliu
s\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ex
t=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\xampp\htdocs\sylius\node_modules\node-sass
gyp ERR! node -v v5.12.0
gyp ERR! node-gyp -v v3.6.0
`

**Comment by hazasaad** [comment]
@Shiro94 
C:\>yarn global add windows-build-tools
yarn global v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning "windows-build-tools@1.3.2" has no binaries
Done in 20.43s.

**Comment by Shiro94** [comment]
Did you add python to your PATH Environment Variable?

**Comment by hazasaad** [comment]
@Shiro94  i added
