### ISSUE TITLE
Contact form error if contact email not set in channel settings

### ISSUE THREAD

**Issue by chaenu** [Sylius/Sylius#8973]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.3

The default contact form https://demo.sylius.org/en_US/contact/ displays always an error message to the user, if there's no contact email configured in the active channel: https://demo.sylius.org/admin/channels/5323/edit This happens in the demo as well, just try to submit the form.

It seems that this is how it should work, which I think is reasonable: https://github.com/Sylius/Sylius/blob/1ad4e19ac3a1cdb5f7a8641fa094b6eda120a194/src/Sylius/Bundle/ShopBundle/Controller/ContactController.php#L95-L107

But if you're not aware of it, you loose some time debugging... Can we mark the form field `contact email` in the edit channel form as required? Or show a specific error message to the user? Or somehow disable the whole contact form, if there's no contact email configured...? What do you think? :)

**Comment by CoderMaggie** [comment]
![image](https://user-images.githubusercontent.com/13198869/33007386-da677284-cdce-11e7-9387-81a8b52c6084.png)

This is the flash message that appears, at least to me it is correct.

**Comment by chaenu** [comment]
Yes, the flash message is fine, it would probably be too much if the message says something like "You cannot use this form because the site administrator didn't configure the channel properly." ;)

But how do I know as an administrator, that if I want to have all basic Sylius shop functionality, I need to provide a contact email in the channel setting if this field is not mandatory?
