### ISSUE TITLE
Error when deleting variants in generator used in order

### ISSUE THREAD

**Issue by czende** [Sylius/Sylius#8974]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.4

Steps to reproduce on [demoshop](http://demo.sylius.org/admin):
1. Search for example T-Shirt "veniam" that has been used in some order.
1. Go to variants generator
1. Remove some variants that have been used as order item
1. Save form by clicking on "Generate"

**Comment by wadjeroudi** [comment]
For this use case, we enabled the soft deletable extension on variant entity.

**Comment by olia-bn** [comment]
This bug is still present in 1.6.2
