### ISSUE TITLE
Error "LocaleNotFoundException"

### ISSUE THREAD

**Issue by onusgit** [Sylius/Sylius#8976]
Hello,

I was face locale issue
"Whoops, looks like something went wrong.
(3/3) LocaleNotFoundException
Locale could not be found!
"
I debug and found issue "locale for French saved "fr" instead of "fr_FR"
can you please update option value for the French?
option value="fr">French /option> to option value="fr_FR">French</option

Bug report? yes
Feature request?yes
Sylius version   | 1.0.4

Thanks

**Comment by pamil** [comment]
Please provide more details how to reproduce this bug.

**Comment by onusgit** [comment]
![image](https://user-images.githubusercontent.com/15248145/33478218-898784d8-d6ae-11e7-87f2-f6a382e0e00a.png)
Add language French, you will see

**Comment by pamil** [comment]
Still, no idea how to reproduce this error, where it happens and what is the current shop setup. French is `fr`, French (France) is `fr_FR`.

**Comment by xiranst** [comment]
@pamil hi, i have the same error in my project. I only use the product-bundle of sylius without the whole project of sylius into symfony 4 project and then got this error.

Symfony version is 4.2.
SyliusProductBundle Version is 1.4.

LocaleNotFoundException

i have insert the locale data into database about sylius_locale. but it is still.
So, could you know how to solve it?

**Comment by onusgit** [comment]
I face this issue for French language, to fix this, I update language fr to fr_Fr directly in database

**Comment by xiranst** [comment]
@onusgit Could you show me your database about it? Thanks.
![1551285770559](https://user-images.githubusercontent.com/9444008/53643589-667cc480-3c6f-11e9-8b86-3f036b6d9fe2.jpg)
This is sylius_locale table in my database.

**Comment by IvanScotto** [comment]
@xiranst  same issue. Did you solve it ?

**Comment by binarious** [comment]
@xiranst @IvanScotto and for people stumbling over this issue. The locale has to be added to the channel. Make sure to add it in the fixtures or manually in `sylius_channel_locales`.
