### ISSUE TITLE
Latest versions of ResourceBundle bundle not published on Packagist

### ISSUE THREAD

**Issue by ste93cry** [Sylius/Sylius#8983]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.4

Since version 1.0 the ResourceBundle versions are not published on Packagist leading to users not being able to install the latest version of the bundle. For example, `version >= 1.0.1 and <= 1.0.4` are tagged on GitHub but are not available on Packagist

**Comment by pjedrzejewski** [comment]
Tagging is in progress, should be finished today. :) Sorry for the trouble!
