### ISSUE TITLE
Corrupted shipping methods

### ISSUE THREAD

**Issue by poolerMF** [Sylius/Sylius#8985]
hello

I opened those entities 
http://demo.sylius.org/admin/shipping-methods/16339/edit
http://demo.sylius.org/admin/shipping-methods/16337/edit
remove "calculator" from HTML and save it

result is **Server has encountered some errors**. ... and it's not possible to edit this entity anymore

sorry :)

**Comment by Zales0123** [comment]
I think it just indicate that we're missing `NotBlank` validation on `ShippingMethod::$calculator` ;)

**Comment by pamil** [comment]
Should be solved by #9764.

**Comment by Zales0123** [comment]
Should be fixed now, thank you, @poolerMF for reporting this issue :)
