### ISSUE TITLE
Tax value with begin dates

### ISSUE THREAD

**Issue by soullivaneuh** [Sylius/Sylius#8991]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no (I guess)
| Sylius version   | 1.x.y

This concern the taxation component and bundle.

Generally, when a tax is changed by a government, it is warned long time ago with a specific date when to change the tax on our new invoices.

With the current state of Sylius, we can't make this automatic. We have to be sure to make the change manually at the **needed date**.

It would be great to make it programmable.

This can be done like this:

- `TaxRate`: Same as acutal, without the amount properties.
- `TaxRateValue`: A model having the amount and a `begin` date.

The `TaxRate` will have multiple `TaxRateValue` object and we may add a `getCurrentValue` to return the object and `getCurrentAmount` to directly have the amount. Those method will select the closest amount to return according to the `begin` properties.

Example with current (2017-11-28) date:

Here is a value list with value/begin date:

- 20% / 2014-01-01
- 22% / 2016-05-01
- 18% / 2019-01-01

The current value will be `22%`.

I think it would worth it to make it automatic and prevent errors, especially for large e-commerce.

If you have simpler way for the same goal, I'm hearing! :+1: 

WDYT?

**Comment by pamil** [comment]
That's still relevant 🎉

**Comment by pamil** [comment]
Ping 🏓

**Comment by Soullivaneuh** [comment]
I here,

I'm currently testing the integration of the TaxationBundle inside our company project.

If the integration is validated, I'll certainly work on this feature. :+1:

**Comment by NoResponseMate** [comment]
Hi @soullivaneuh 

It took a while, but the date ranges have come into play in 1.12 via #14338 
Cheers :beers:
