### ISSUE TITLE
Bug in Calculator Pass

### ISSUE THREAD

**Issue by igorjacon** [Sylius/Sylius#9004]
There seems to be a bug in the Calculator Pass [here](https://github.com/Sylius/Sylius/blob/1.0/src/Sylius/Bundle/ShippingBundle/DependencyInjection/Compiler/RegisterCalculatorsPass.php)
The Calculator Pass searches for an attribute "form_type" in "sylius.shipping_calculator" service

> isset($attributes[0]['form_type']

However if you look at the services tagged by "sylius.shipping_calculator" [here](https://github.com/Sylius/Sylius/blob/1.0/src/Sylius/Bundle/ShippingBundle/Resources/config/services.xml) you will notice that the attributes are: calculator, **form-type**, and label. 
So it never adds those calculators to the form type registry.
The following line will never run:

> $formTypeRegistry->addMethodCall('add', [$name, 'default', $attributes[0]['form_type']]);

**Comment by pamil** [comment]
When using XML for services, `-` are transformed to `_` automatically.

For example, [`RegisterAttributeTypePass`](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AttributeBundle/DependencyInjection/Compiler/RegisterAttributeTypePass.php#L37) requires `form_type`, and [XML definitions](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/AttributeBundle/Resources/config/services/attribute_types.xml#L18) use `form-type` and it works correctly.
