### ISSUE TITLE
PHP 7.2 support

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#9009]
PHP 7.2 build on Travis is already enabled and running, the very last issue we need to solve is https://github.com/jeremykendall/php-domain-parser/issues/205. After the stable package is released (or we find another way around it), a patch release will be tagged.

If you do need PHP 7.2 support right now, just require this package in `4.0.3-alpha` version and everything should work just fine 🎉

**Comment by stefandoorn** [comment]
PR for the stable 4.0 release of the mentioned package: https://github.com/jeremykendall/php-domain-parser/issues/205.

**Comment by pamil** [comment]
Done by #9096, will be included in 1.0.8 and 1.1.0 releases 🎉
