### ISSUE TITLE
add addon type in product mode

### ISSUE THREAD

**Issue by renothing** [Sylius/Sylius#9030]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Sylius version   | 1.x.y

thanks guys for great jood in sylius. and I found there is a common scenario missing in sylius.
    when you sell something with service support , or Electronic products with plugin addons.  you need add serfice package or plugin addons as another product, but them can only be purchased with primary product, it can not be purchased dedicated alone. that's mean we need new product type as simple and configuable.
   for example you sell Electronic products with additional After-sales service.  people can only purchase service with product together. 

   pepole should add addon type product first, then when he add normal product, he can choose addon product as configuable options for sale.

**Comment by Zales0123** [comment]
Hello @renothing and thank you for your kind feedback :) Thing you're writing about is for sure something useful and interesting, but I don't know will we want to implement this in core of Sylius, at least in the nearest future. But I see here a great potential for the awesome plugin :) Check out our [Plugins section](http://docs.sylius.org/en/latest/plugins/) on docs, or maybe anybody is working on something like this right now?

**Comment by Zales0123** [comment]
I think it can be closed, please, reopen if any further discussion is required
