### ISSUE TITLE
set the default local not the en_US,add the product language error

### ISSUE THREAD

**Issue by benyang2015** [Sylius/Sylius#9031]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no/yes
| BC Break report? | no/yes
| RFC?             | no/yes
| Sylius version   | 1.0.5
![image](https://user-images.githubusercontent.com/15188607/34077323-35f0d60e-e33c-11e7-88ac-703952bc4e78.png)
![image](https://user-images.githubusercontent.com/15188607/34077326-4117fbfc-e33c-11e7-9773-5945a5838f29.png)
![image](https://user-images.githubusercontent.com/15188607/34077333-8e20fe08-e33c-11e7-8b77-6b2618ab3123.png)
why the en_US is require?

**Comment by pamil** [comment]
It could be solved by changing the value of locale parameter in `app/config/config.yml` and reinstalling Sylius.

**Comment by benyang2015** [comment]
reinstalling sylius？ use php bin/console sylius:install --env=prod

**Comment by pamil** [comment]
Yeah :)

**Comment by Zales0123** [comment]
I think it can be closed, feel free to open if any new info will be needed ;)
