### ISSUE TITLE
Different template for flash messages in ShopBundle and AdminBundle

### ISSUE THREAD

**Issue by Takeno** [Sylius/Sylius#9032]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no/yes
| Sylius version   | 1.0.5

Actually there is only one file containing flash messages layout:
[Sylius/src/Sylius/Bundle/UiBundle/Resources/views/_flashes.html.twig](https://github.com/Sylius/Sylius/blob/v1.0.5/src/Sylius/Bundle/UiBundle/Resources/views/_flashes.html.twig)

It is used for ShopBundle (frontend) as for AdminBundle (administration). This makes customization really hard.

IMHO we can create two different files for Shop and Admin, which contain a single include:
```
{% include 'SyliusUiBundle::_flashes.html.twig' %}
```

In this way, you can customize your frontend flashes overriding `ShopBundle::_flashes.html.twig` and keep admin messages untouched.

What do you think about this? I'll make the PR if solution is acceptable

**Comment by pamil** [comment]
It's a good idea, I'd be happy to help and merge it :)
