### ISSUE TITLE
Docs about Stripe behind loadbalancer

### ISSUE THREAD

**Issue by reyostallenberg** [Sylius/Sylius#9035]
| Q                | A
| ---------------- | -----
| Bug report?      | no/yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.4

I was implementing the Stripe payment method and all worked fine on my development environment.
On production payments didn't succeed and then they looped back to the payment page. I found out it  was because of being behind a load-balancer and therefor the payment form posted to 'http' and not httpS.

This (risk) should be documented.

**Comment by Zales0123** [comment]
@reyostallenberg thank you for that issue, will you be able to contribute to docs and explain this potential issue there?
