### ISSUE TITLE
Order confirmation email is not send in API

### ISSUE THREAD

**Issue by Tetragramat** [Sylius/Sylius#9039]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.y

Reason is missing `_sylius.event` parameter in `sylius_admin_api_checkout_complete` route.
This parameter needs to be set to `complete`. 

If it is not set `sylius.order.post_update` event listeners are called instead of `sylius.order.post_complete`, which should be the correct behavior.

**Comment by mamazu** [comment]
This is an issue in the API. See [issue 250](https://github.com/Sylius/ShopApiPlugin/issues/250)
