### ISSUE TITLE
Debug toolbar brokes due to HTTP cache

### ISSUE THREAD

**Issue by HerveEmagma** [Sylius/Sylius#9044]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Sylius version   | 1.0.5

Hello,

The debug toolbar brokes when I enable the HTTP cache in app.php with 
`if (getenv('SYLIUS_HTTP_CACHE_ENABLED') == '1') {
    $kernel = new AppCache($kernel);
}
`

I get this error
![image](https://user-images.githubusercontent.com/25428513/34199384-e0d975f2-e56d-11e7-850a-62086f147fbc.png)

collector.channel return a strange array of array
![image](https://user-images.githubusercontent.com/25428513/34199524-593fef30-e56e-11e7-8077-f20abef2b1a7.png)

Any idea ?

Thanks

**Comment by Cathmor** [comment]
Why do you have your debug bar enabled in app.php? Isn't your app.php set up for production, in which case, you shouldn't have the debug bar there anyway?
