### ISSUE TITLE
Translating Sylius - looking for proofreaders

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#9057]
Hi folks!

I've just changed CrowdIn settings to only extract approved translations, so that suggesting changes there isn't enough right now (so no one can troll us by changing translations). All of the current translations have been already marked as approved, so the existing ones are not affected.

This makes us looking for proofreaders on CrowdIn - if you would like to help us approving translations or translate Sylius to a language which isn't available on CrowdIn yet, write a message here or DM me on Slack / Twitter.

**Comment by Zales0123** [comment]
Sorry Mr. Stale, not today 🔥
