### ISSUE TITLE
Change database name in app_dev?

### ISSUE THREAD

**Issue by landsman** [Sylius/Sylius#9086]
Hi,

why is suffix here?
https://github.com/Sylius/Sylius/blob/de87652ef8b32348bd1a10f0759865139a79ffc2/app/config/config_dev.yml#L13

I don't want changing database name for app_dev.php, in not making sense.

**Comment by lchrusciel** [comment]
It is rather typical that you have different databases for prod, dev and test. It would say that it is even standard. This repo is for Sylius development only. Feel free to customize it in your project in app/config.
