### ISSUE TITLE
errors during running behat tests - payment with paypal test 

### ISSUE THREAD

**Issue by kuzmamar** [Sylius/Sylius#9092]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Sylius version   | 1.0.0

There is a feature test for paypal payment in vendor/sylius/sylius/features/checkout/paying_for_order/paying_with_paypal_during_checkout.feature

When I run the tests with: ./bin/behat vendor/sylius/sylius/features/checkout/paying_for_order/paying_with_paypal_during_checkout.feature 
then the result is as follows:
![payment-security-token-error](https://user-images.githubusercontent.com/8044284/34652809-709b1bd6-f3e3-11e7-8754-4a7f7b94b518.png)

Is there some required step to create the token before running the tests?

**Comment by pamil** [comment]
Could you please retry running those Behat tests on the fresh Sylius installation?
