### ISSUE TITLE
Image lightbox2 'Image X of Y' text is not translated

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#9099]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.6

Example: http://demo.sylius.org/en_US/products/mug-et. Click on main image, see text 'Image 1 of 3'. This text is not translated. There is way to do this: http://lokeshdhakar.com/projects/lightbox2/ (search for 'albumLabel').

The issue is now, how to get a translation from the translation files into JS, in case we want to fix this. I'm willing to make a PR, but would like to hear what is the preferred way of solving this. There are bundles to help in this (e.g. https://github.com/willdurand/BazingaJsTranslationBundle), but that adds some dependencies to Sylius which might be a bit overkill.

**Comment by Zales0123** [comment]
Although it would be nice to have this label translated, I think it would be good to solve it without adding any new dependencies, as it's not-so-high-level bug :) anyway, PR would be welcomed 👍

**Comment by pamil** [comment]
Fixed by #9125.
