### ISSUE TITLE
[Urgent] An error appear in the Payum capture action when checking out an order

### ISSUE THREAD

**Issue by songecko** [Sylius/Sylius#9105]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0

This issue appear after a composer update. It updates the Payum bundle to the 1.5.0 tag and subsequently it updates the League Uri library to 5.x. 

Steps to reproduce:

1- Do a composer update.
2- Do a checkout and the error appear when click in the "Place Order" button on the checkout last step.

After a research i did, i found that the League URI need to write a cache file in **/vendor** directory instead **/var/cache**. And of course the /vendor directory is not writable.

Here an screenshot showing the stack trace. URL: /payment/capture/{token}

![2018-01-13](https://user-images.githubusercontent.com/429512/34950833-f781d146-fa1c-11e7-9217-d270d964b994.png)

**Comment by stefandoorn** [comment]
This would also be problematic on hosting environments like Platform.sh, where by default folders are read-only unless specifically marked as a persistent volume between deployments.

**Comment by Tetragramat** [comment]
related issue in payum https://github.com/Payum/Payum/issues/734

**Comment by pamil** [comment]
Tracked it downstream to thephpleague/uri-hostname-parser#2.

**Comment by Takeno** [comment]
It should be a permission error for cache folder: `vendor/league/uri-hostname-parser/data/`.

Easy fix: chmod on that directory.

**Comment by Tetragramat** [comment]
Wasn't that was already fixed in league/uri-components:^1.7.1 ?

**Comment by Zales0123** [comment]
It should be :)

**Comment by Takeno** [comment]
Yeah, it should be fixed with new version of `league/uri-components` but if you can't upgrade for some reason, chmod is a way.

**Comment by Zales0123** [comment]
Nice, thank you @Takeno for useful information, thank you @Tetragramat for clarification, I think it could be closed then :)
