### ISSUE TITLE
Updating product position does not work

### ISSUE THREAD

**Issue by bitbager** [Sylius/Sylius#9107]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.5

```
Given I have a product with position set to 1
When I go to the product list page that contains this product
And I set the position to 2
And I press the "Save positions" button
Then I am not notified that the position has been updated
And the position is still 1 😢 
```

Also happens on Sylius demo, take book taxonomy as an example.

**Comment by pamil** [comment]
Could you provide a PR with failing Behat scenario for that?

**Comment by bitbager** [comment]
How should I tag it?

**Comment by pamil** [comment]
No, let it fail (just like #9145).

**Comment by bitbager** [comment]
Done 🎉

**Comment by pamil** [comment]
It's not reproducible on the last releases of `1.1.x` / `1.2.x` and `1.3.x`.
