### ISSUE TITLE
"Too few arguments to function" error when overriding Product controller

### ISSUE THREAD

**Issue by Toumm** [Sylius/Sylius#9112]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.3

I am trying to override the Product controller as it is indicated in the `[customization guide](http://docs.sylius.org/en/latest/customization/controller.html)`.
I have created my controller in the AppBundle namespace, register it as a service and added a route to the only one action in it.
Here is the error I got:
Too few arguments to function Sylius\Bundle\ResourceBundle\Controller\ResourceController::__construct(), 0 passed

**Comment by lchrusciel** [comment]
Please ask such questions on StackOverflow or our slack channel.
