### ISSUE TITLE
Adding N products to Taxon create/update form

### ISSUE THREAD

**Issue by floriancourgey** [Sylius/Sylius#9114]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no/yes
| Sylius version   | 1.0.8

Hi,

I would like to know how I can add products to a Taxon on the creating/editing Taxon Form.

In our system, each customer is linked to a Taxon, and has only access to products linked to this Taxon with product.mainTaxon.

Here's a quick preview of what I'm aiming at:
![image 1](https://user-images.githubusercontent.com/9380369/35225559-bbd0eb7a-ff56-11e7-8d58-6298e066522a.png)

I didn't find any lead in the docs, is it done via a grid, a form extension, a template override?

Thanks!
Florian

PS: I've already overriden Taxon (and its orm.yml) with $products, and Product (with its orm.yml) with mainTaxon

PS2: ideally, each new product would be pre-filled with a predefined set of attributes that we always use in our system, and we would hide the 'delete attribute' button via CSS, but that's only when the work above would be done

**Comment by pamil** [comment]
It could be done by a form extension and overriding the form template. Anyway, it would be the valid  solution only if you're having rather a small amount of products in a taxon, as downloading and showing when counted in hundreds might be cumbersome.

As for PS2, what you're looking for is https://github.com/FriendsOfSylius/archetype-bundle, but it seems abandoned /cc @bitbager

**Comment by floriancourgey** [comment]
I finally managed to resolve this using Sonata Admin

We're already using Sonata for different entities, and it's working as expected when used with Sylius entities!

see https://github.com/sonata-project/SonataAdminBundle/issues/4904 for details on implementation

Thanks
