### ISSUE TITLE
User registration-Email validation failure 

### ISSUE THREAD

**Issue by DesignJobs** [Sylius/Sylius#9116]
Failed email validation on User registration.

Tried to enter an invalid email like test@test.;conm

And got the following
Address in mailbox given [test@test.;conm] does not comply with RFC 2822, 3.6.2.

| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0

**Comment by lchrusciel** [comment]
Thanks for reporting. 

Could you try to write a reproducing scenario for that? Or even better fix it? 

Check our feature file to see how we try to describe features and bugs :)

**Comment by lex111** [comment]
The email is checked via Symfony Validator, which by default does not check the correspondence of the email to the RFC. But we can do this by setting the [strict parameter](http://symfony.com/doc/current/reference/constraints/Email.html#strict). But this can lead to unexpected behavior: strange addresses like `example@mail` will be valid, there is even an [article](http://girders.org/blog/2013/01/31/dont-rfc-validate-email-addresses/) on this matter.

On the other hand, we can check the mail with a standard PHP function - `filter_var` with a flag `FILTER_VALIDATE_EMAIL`, it does not allow an e-mail with semicolon, but does not allow such e-mail addresses as `example@mail`, it is a reasonable compromise.  I can do PR, implementations custom email validator.

**Comment by pamil** [comment]
Setting the strict parameter seems like a correct solution, as `example@mail` is in fact a correct email address :)

**Comment by lex111** [comment]
Perhaps, on this occasion, I just added a link to the article, why it is not necessary to do so :/

**Comment by stefandoorn** [comment]
Having the same issue here with an email that looks like: 'b@example@bla.com'. Probably by accident entered by the customer, but was possible.

**Comment by LegendOfGIT** [comment]
So. Using the strict parameter would make everybody happy?
If this was the case, i would prepare a Pull-Request today evening.

**Comment by stefandoorn** [comment]
I would be happy with it ;-)
