### ISSUE TITLE
Postcode ranges supported for zone matching

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#9120]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Sylius version   | 1.2

Would be great if we can also specify a Postcode range for every zone. Right now Zones can be defined as:

* Zone of countries ("European Union")
* Zone of provinces (lands, cantons, etc.)
* Zone of other Zones (like "US + EU")

Zones are used for shipping & tax calculation purposes. The responsible class is https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Addressing/Matcher/ZoneMatcher.php

More about zones: http://docs.sylius.org/en/latest/book/customers/addresses/zones.html

Definition of Done:

* Behat scenarios implemented
* Postcode range configurable on the Zone entity (?)
* ZoneMatcher taking this into account

**Comment by mamazu** [comment]
Well contrary to names of countries and Provinces, [zip codes aren't unique so the same zip code in America could mean a totally different region in Israel](https://www.quora.com/Are-postal-zip-codes-unique-globally-What-tells-us-to-which-country-they-belong).

So how would I go about that? Would I just make it so you have to also select a country and then store the code of this region as for example Germany_26122 with type zip code or do I create an Entity (which would require some refactoring of the old system).

**Comment by stefandoorn** [comment]
What's the status of this 'Easy Pick Feature'? :-)

**Comment by mamazu** [comment]
The merge request of the implementation is still waiting for review.

**Comment by pamil** [comment]
If that's an easy pick then half of our issues are easy picks 🎉

**Comment by mamazu** [comment]
Still waiting for feedback

**Comment by CoderMaggie** [comment]
Well, it is indeed a great idea but it is not on our current (nor foreseeable) roadmap 😢  I encourage you to create something on your own, especially in a plugin 🖖🏻
