### ISSUE TITLE
URL rewrites made configurable via Admin UI

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#9121]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Sylius version   | 1.2

Currently, any URL rewrites need to be handled by a developer. It would save a lot of work to have a simple engine for defining redirects from the admin UI. Next step would be to generate these automatically on certain events, like the product's "slug" change.

My idea would be to add a simple resource [(docs](http://docs.sylius.org/en/latest/cookbook/entities/custom-model.html) that has the redirect configuration + a listener (kernel.request) that would perform a redirect if needed.

**Comment by stefandoorn** [comment]
Might also be a good idea for something like a Redirect plugin? Not necessarily core maybe.

**Comment by pamil** [comment]
I'm 👍  for a plugin, if it is good enough we can make it required in core itself.

**Comment by mamazu** [comment]
What kind of redirects where you thinking about (a normal redirect as in Symfony) or should the route deliver the content of it's redirected route?

**Comment by mamazu** [comment]
Waiting for feedback

**Comment by mamazu** [comment]
As discussed, we will maintain this in a plugin that might be merged into the core later on [SyliusRedirectPlugin](https://github.com/Setono/SyliusRedirectPlugin)

**Comment by mamazu** [comment]
So I would suggest to close this issue. @pjedrzejewski

**Comment by Zales0123** [comment]
Can be close, especially as `SyliusRedirectPlugin` has been officially approved by Sylius :)
