### ISSUE TITLE
Countries available in the checkout made configurable per channel

### ISSUE THREAD

**Issue by pjedrzejewski** [Sylius/Sylius#9122]
⚠️ 🛣 **This issue is a part of the** [Sylius Public Roadmap](https://github.com/orgs/Sylius/projects/2) 🛣 ⚠️

| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.2

Currently, if we have 2 channels "US Webstore" and "EU Webstore", during the checkout, all countries are available. An improvement would be to add a relation between every Channel and many Countries. And if Channel has like 2 out of 5 countries selected, these are available during checkout. If no countries are selected - all are available. So we retain the current behavior (no BC break) but add new, useful feature.

To achieve this, I would suggest to modify the AddressType form type. In the CheckoutAddressType form type we could identify the channel of the order and use appropriate countries as options to choose from.

**Comment by pamil** [comment]
It's going to be part of Sylius 1.7.
