### ISSUE TITLE
[Channel] Use color input type for color

### ISSUE THREAD

**Issue by Tetragramat** [Sylius/Sylius#9146]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.x.y

Currently is used text as color input, but it is not user friendly.

**Comment by czende** [comment]
You can use for example this [ColorPickerBundle](https://github.com/kunicmarko20/ColorPickerBundle) and extend ChannelFormType. I'm not sure if it is so important for just one single input in whole Sylius.

**Comment by Tetragramat** [comment]
I would like html5 color input type rather than some custom js.
http://symfony.com/doc/3.4/reference/forms/types/color.html

If I'll find the time then I'll make PR, but I want confirmation from the maintainers before that.

**Comment by Zales0123** [comment]
I think that if we can use the dedicated solution for something (especially if it does not provide any new dependencies) we should do that 👍
