### ISSUE TITLE
Return types incompatible for Timestampables

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#9148]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | yes
| RFC?             | no
| Sylius version   | 1.0.x

TimestampableTrait: https://github.com/Sylius/Sylius/blob/190a314d7e84d36093ec2736111dabc713c6b7bf/src/Sylius/Component/Resource/Model/TimestampableTrait.php

TimestampableInterface: https://github.com/Sylius/Sylius/blob/190a314d7e84d36093ec2736111dabc713c6b7bf/src/Sylius/Component/Resource/Model/TimestampableInterface.php

It seems the return types of the setters in the trait seem not to match the ones in the interface. Not sure if it's a big issue, but just noticed it while scrolling through code. It seems functional that it's no issue, as it doesn't result in errors.

**Comment by pamil** [comment]
Yeah, looks like we've forgotten about `void` return typehints for the `TimestampableInterface`. The trait implementation does not break anything as adding a return typehint in an implementation is perfectly valid. 

That being said, we can't add a return typehint to these methods without causing a BC break, so I'm tagging it as a bug under 2.0 milestone and we'll get back to this issue in the future, when we will be working on the next major version.
