### ISSUE TITLE
Tax Categories not set in product variant fixtures

### ISSUE THREAD

**Issue by mamazu** [Sylius/Sylius#9156]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.2.0

Currently if you install the Sylius database with the test data you get some products with variants and some tax categories. However no product variant has a tax category set by default. It would make sense to set the default tax category for t-shirts to clothing and for books as well. As stickers fit none of the existing categories I would suggest to leave it blank.

**Comment by teohhanhui** [comment]
This is still an issue.

**Comment by pamil** [comment]
Same for shipping categories probably.

**Comment by devdrops** [comment]
Working on it! :D
