### ISSUE TITLE
Adding a select attribute to a product doesnt work in PHP >= 7.2.0

### ISSUE THREAD

**Issue by alexrowesoap** [Sylius/Sylius#9159]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.8

I'm experiencing unusual behaviour with select attributes. I've checked the issues on github and nothing matches currently. I've created a new select attribute, which has two options. On the product page, it's visible in the dropdown of attributes, yet when I select it and press "Add attributes", it doesn't add it to the list of attributes. The select does have an en_us translation. The ajax request is returning a 500, with an error of "Warning: count(): Parameter must be an array or an object that implements Countable" in  src\Sylius\Bundle\AttributeBundle\Form\Type\AttributeType\SelectAttributeType.php (line 43).
This relates to a change in the count() function where from PHP 7.2.0 onwards, passing anything that doesnt implement a countable interface raises a warning.
WAMP stack, php 7.2.1 32bit.

**Comment by pamil** [comment]
Could you tell what value does `$array` have when `count($array)` is called?

**Comment by alexrowesoap** [comment]
At the time of debugging, it was null.
The quick fix for me was to replace 
if  count($array) > 0) { 
with 
if ((is_array($array) || is_object($array)) && count($array) > 0) {
but I feel testing for an instance of countable would be more elagant.

**Comment by pamil** [comment]
#9204 merged, the fix will be included in the next patch releases :)

**Comment by alexrowesoap** [comment]
thanks @pamil :)
