### ISSUE TITLE
Don't show variants which don't exist

### ISSUE THREAD

**Issue by patkar** [Sylius/Sylius#917]
Example: I have boots with option size UK 4 to 13. But the boots are only on stock for size 5 to 10 (also the variants are created only for size 5 to 10). But the frontend shows all options values for selection and raises an error if I want to buy a non existing variant.

At the moment I have to create different options for a product which is only in stock from size 5 to 10, size 4 to 9, size 5 to 13 and so on. And I can't switch between them, when a product should get a new variant.

**Comment by baublet** [comment]
Bumping this. It would be great if this were supported out of the box.

**Comment by smashou** [comment]
We have the same problem in our projects but with another constraint which is not loading all variants as there are almost 15000 variants per product. 
Do you have any idea of how to do it ? maybe @jurv could git it a try ?

**Comment by pjedrzejewski** [comment]
@smashou Could you tell us more about the product? 15K variants sounds like a lot. Maybe there is a simpler design. :)

**Comment by jurv** [comment]
@pjedrzejewski the products are pieces of furniture that can have different decoration patterns, colors (main color and pattern color, 16 choices for each color), finitions (shiny / matte), positions (against the wall / island), ... 

We created these as options for the pieces of furnitures. As there are a lot of options and values for each option, there is a lot of variants... Some products have more options than others, but we always are between 10K and 15K variants.

Now our issue is that even if a furniture doesn't have a variant with one of these option value (eg one of the furniture doesn't exist in red), the value is still present in the list of options.

**Comment by pjedrzejewski** [comment]
Product Variants should usually represent what do you have physically in stock, I assume that the furniture is handmade according to the options selected. So you actually need something like https://github.com/Sylius/Sylius/issues/362, which we unfortunately do not support at the moment. That being said, I think you could customize it relatively easily. Let me know what do you think. If you have 15k variations per product, it can get tricky. :)
