### ISSUE TITLE
[Locale] Flags does not work properly

### ISSUE THREAD

**Issue by shadypierre** [Sylius/Sylius#9184]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.1.0

When you create a new locale, for some countries the form return two letters as code (example : France => "fr"), and five for the others one (example : United States => en_US).
The problem is that in the template, when the application try to display flag that doesn't work for the locale with only two letters : 

![capture d ecran 2018-02-14 a 04 55 01](https://user-images.githubusercontent.com/1146998/36187089-4433c2b4-1143-11e8-9243-5cb767014d29.jpg)

**Comment by shadypierre** [comment]
Current code is : 
`<i class="{{ data.code|slice(3, 2)|lower }} flag"></i>`

Maybe we could just replace by this : 
`<i class="{{ data.code|length > 2 ? data.code|slice(3, 2)|lower : data.code|lower }} flag"></i>`

**Comment by pamil** [comment]
@shadypierre `{{ data.code|slice(-2)|lower }}` should do the work, can you open a PR against `1.0` branch with that?

**Comment by pamil** [comment]
The another thing to consider is that the first two characters describe the language code which might not be the same as a country from which it originates.
