### ISSUE TITLE
Allow users to change interface language in Sylius

### ISSUE THREAD

**Issue by Ghani2018** [Sylius/Sylius#9197]
I use Sylius Standard (version: 1.0.5) and I would like to know how to allow users to change the interface language, because I did not find anything about this in the official documentation ( here: http://docs.sylius.com/en/latest/book/configuration/locales.html ) ?

**Comment by vvasiloi** [comment]
@Ghani2018 If you use the default theme, then the language select box will automatically appear in the top-left corner of your storefront as soos as you will have more than 1 locales available.
So, in the admin panel, create the locales you need in the `Configuration -> Locales` page and add then to the channel you need in the `Configuration -> Channels` page.

**Comment by Ghani2018** [comment]
@vvasiloi Thanks ! actually in the admin panel, if I change the locale of the channel, the language interface change, but I want to allow users to change the language interface by themselves (with a customized select box for example). Furthermore, I do not see the language select box in the top-left, even in the demo ( https://demo.sylius.com/en_US/ )  !

**Comment by Ghani2018** [comment]
@vvasiloi Thanks ! I added several locales to my Channel as you can see in the screenshot
but I still have not the select box language  (it considers that there is only one locale because when I change the condition "{% if locales|length > 1 %}" into "{% if locales|length > 0 %}" I have this select box language but only with one language, which is the default language) ! 
![channel sylius](https://user-images.githubusercontent.com/36482563/36270708-b010198a-127c-11e8-82fd-21f30bbadef5.png)

**Comment by vvasiloi** [comment]
@Ghani2018 in your screenshot, the `Locales` is a multiple select box, but there is only one value selected.
In order to select multiple values, hold `Shift` and click the locales you want to enable in that channel, then save the changes and refresh the storefront page.

**Comment by Ghani2018** [comment]
@vvasiloi it works perfectly ! Thank you !
