### ISSUE TITLE
QueryBuilder getters in many Repository interfaces

### ISSUE THREAD

**Issue by DerRidda** [Sylius/Sylius#9198]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | kinda
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.1.0

Hello,

First of: Very thrilling project you have going on here, Sylius seems insanely flexible and well engineered and if the opportunity arises, I will certainly throw a real project at Sylius.

One thing I have noticed is, that many of the repository interfaces seem to contain getters for Doctrine's QueryBuilder, which to me seems like an implementation detail of the default Doctrine repository classes that doesn't belong there.

Searching for usages of these methods there never don't seem to be any except in some yaml files of specific bundles, at which point they always seem to appear next to an implementation of that interface.

What's the stopper here from abstracting these away?
It seems to me like Sylius was designed with a level of abstraction in mind that specifically states "We don't care where the data comes from" and having Doctrine pop it's head out here and there within interfaces contradicts that.

**Comment by pamil** [comment]
Sorry to keep you waiting, basically it's a design flaw we've intended not to do, but given the time constraints for stable release haven't been able to remove that.

The stopper here is probably the current usage of them in YAML routing files which contents are then handled by ResourceBundle / GridBundle (and the BC policy right now, but we can deprecate them and provide alternative implementation in `1.x` and remove them in `2.0`).
