### ISSUE TITLE
Bulk remove action does not work

### ISSUE THREAD

**Issue by bitbager** [Sylius/Sylius#9201]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.1.0

On the demo page, the bulk remove on the product list causes a 500 error. That being said, I think it's worth considering to disable the error reporting on the demo app.

![screen shot 2018-02-17 at 15 44 46](https://user-images.githubusercontent.com/28542010/36342119-d48a53ba-13f9-11e8-81c5-5e1443614c0f.jpg)

**Comment by Zales0123** [comment]
@bitbager could you please check if it still happens? I've just checked it out and everything works fine for me :)
![zrzut ekranu 2018-03-22 o 13 46 19](https://user-images.githubusercontent.com/6212718/37771328-88beb244-2dd7-11e8-9177-2f419108a470.png)

**Comment by bitbager** [comment]
Yes, it works now. Dunno what it was caused by, but seems like fixed 🙂

**Comment by Zales0123** [comment]
🎉
