### ISSUE TITLE
Missing UserBundle french translations since last 1.1.1 release

### ISSUE THREAD

**Issue by michelcourtade** [Sylius/Sylius#9213]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.1.1

Hi,
I recently upgraded to 1.1.1 and I found a problem with, I think, a missing french translation for UserBundle.

On file Sylius\Bundle\UiBundle\Form\Type\SecurityLoginType on line 32 and 35, labels 'sylius.form.login.username' and 'sylius.form.login.password' are used but are no longer present in french translation file in : vendor\sylius\sylius\src\Sylius\Bundle\UserBundle\Resources\translations\messages.fr.yml.

The result is a fallback message when you have the english translation enabled or simply a 'sylius.form.login.username' displayed on login form.

Thanks for the fix !

**Comment by shadypierre** [comment]
The admin menu is missing too

**Comment by shadypierre** [comment]
The admin menu is missing too
![capture d ecran 2018-02-27 a 16 25 45](https://user-images.githubusercontent.com/1146998/36737254-eb59a3d2-1bda-11e8-9593-a641c138d3bb.jpg)

**Comment by ambroisemaupate** [comment]
It seems to be an issue with your translation bot from *Crowdin*. 

This commit show many many removed lines in French translations
https://github.com/Sylius/Sylius/commit/e9253064048dd58c646f2a9c9f12addeb0e1ddf8

**Comment by michelcourtade** [comment]
Yes, it seems more impactful than I thought ... can someone from core devs please fix that ? not very cool to have a new release that breaks existing translations ...

**Comment by pamil** [comment]
It seems like our CrowdIn synchronisation application change together with introducing branches on CrowdIn caused that. I'll pull the most recent translations in a few minutes, French is right now at 99% so it should fix that (you can translate the missing 1% here: http://translate.sylius.com/translate/sylius/all/en-fr). Right now the best solution would be to revert from v1.1.1 to v1.1.0 / from v1.0.11 to v1.0.10 and wait to the next week's release.

**Comment by michelcourtade** [comment]
Thanks for the response and the fix. I'll revert to v1.1.0 and wait next release.

**Comment by pamil** [comment]
Will be fixed by #9215.

**Comment by pamil** [comment]
Okay, I guess it has been solved :)
