### ISSUE TITLE
[Fixtures] Zone scope ignored in GeographicalFixture

### ISSUE THREAD

**Issue by vvasiloi** [Sylius/Sylius#9221]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.1.0

The Zone configuration accepts a `scope` property:
https://github.com/Sylius/Sylius/blob/723c19834562f61167a51a155e575fe3a8d6ae8f/src/Sylius/Bundle/CoreBundle/Fixture/GeographicalFixture.php#L140-L150
but it's ignored on object creation:
https://github.com/Sylius/Sylius/blob/723c19834562f61167a51a155e575fe3a8d6ae8f/src/Sylius/Bundle/CoreBundle/Fixture/GeographicalFixture.php#L204-L210

**Comment by pamil** [comment]
Could you open a PR against `1.0` branch which adds setting zone to the fixture?

**Comment by vvasiloi** [comment]
@pamil Sure, I will.

**Comment by pamil** [comment]
Fixed by #9687.
