### ISSUE TITLE
Access Denied issue

### ISSUE THREAD

**Issue by ObadaAbdelkareem** [Sylius/Sylius#9228]
i follow the link documentation below : 
http://docs.sylius.com/en/1.1/api/authorization.html

but it still give me the error below, i put the access token and header ( Authorization : Bearer accesstoken , Accept : application/json )  but still not work with me, please advise
{
    "error": "access_denied",
    "error_description": "OAuth2 authentication required"
}

**Comment by Zales0123** [comment]
Hello @ObadaAbdelkareem and welcome to the community! First of all, what version of Sylius do you use? Are you sure you've completed each step correctly? I've just tried it on **Sylius**1.1 and everything worked fine.
And at the end - **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our [Slack](http://sylius.org/slack) or [stackoverflow](https://stackoverflow.com/questions/tagged/sylius) ;)

**Comment by ObadaAbdelkareem** [comment]
thank you @Zales0123  my sylius version 1.1.0, and i have asked the question on stackoverflow and i will use it for the issues like this :)
