### ISSUE TITLE
[ThemeBundle] Themes path cached

### ISSUE THREAD

**Issue by slince** [Sylius/Sylius#9250]
| Q                | A
| ---------------- | -----
| Bug report?      | n
| Feature request? | no
| BC Break report? | n0
| RFC?             | no
| Sylius version   | 1.x.y

Hi

I m using [http://docs.sylius.com/en/1.1/components_and_bundles/bundles/SyliusThemeBundle/index.html](http://docs.sylius.com/en/1.1/components_and_bundles/bundles/SyliusThemeBundle/index.html) in an another project.  I see service `sylius.repository.theme` is `InMemoryThemeRepository`, Does these mean that this bundle will collect all theme paths every time?

**Comment by slince** [comment]
When I enable the theme, the service will becomes very slow. I think it may be because of collecting the theme path every time.

**Comment by stefandoorn** [comment]
@slince Have you tried the `scan_depth` as mentioned here: http://docs.sylius.com/en/1.1/components_and_bundles/bundles/SyliusThemeBundle/configuration_sources/filesystem.html?highlight=scan_depth? Maybe you have some big folders inside the theme, e.g. a `node_modules` folder? 

Maybe similar to this: https://github.com/Sylius/Sylius/pull/9008?

**Comment by slince** [comment]
@stefandoorn 

> Maybe you have some big folders inside the theme, e.g. a node_modules folder?

Hi , there just a little test file. 

Themebundle will caches all themes? Or say that will find the theme again every time process an http request.

**Comment by stefandoorn** [comment]
IIRC it will define all these things when building the cache / compiling, but @pamil knows this better than me.

**Comment by slince** [comment]
@pamil  Hi, can you solve my doubts?

**Comment by pamil** [comment]
IIRC it is trying to find the configuration file every request right now.
