### ISSUE TITLE
PHP timezone Installation Problem

### ISSUE THREAD

**Issue by it-all** [Sylius/Sylius#9251]
`php bin/console sylius:install`

Produces: 
timezone Error!

| Issue    | Recommendation |
+----------+----------------+
| timezone |                |
+----------+----------------+

In CheckRequirementsCommand.php line 45:
                                                                                          
  [RuntimeException]                                                                      
  Some system requirements are not fulfilled. Please check output messages and fix them.  

Upon first getting this, I updated my php.ini date.timezone to America/New_York and restarted Apache. The date.timezone in phpinfo() output now shows America/New_York for both local and master values (they were blank prior to this). But the Sylius installation error remains.

Is there some sort of cache I need to clear before it will work? Or do you have other ideas of the cause?
                                                                                          

| Q                | A
| ---------------- | -----
| Bug report?  (possibly - if only because the Recommendation is blank for the Issue)     | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.1.1

**Comment by pamil** [comment]
Check if your CLI config has also `date.timezone` set up (`php -i | grep timezone`).

**Comment by it-all** [comment]
That was it. Thanks a lot!
