### ISSUE TITLE
[Fixtures] False as boolean value for product attributes is ignored

### ISSUE THREAD

**Issue by twojtylak** [Sylius/Sylius#9252]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.1.1

If you define `false` as attribute value for a checkbox attribute, this value will be ignored and a random value will be used instead.

In [ProductExampleFactory](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Fixture/Factory/ProductExampleFactory.php#L252) no distinction between `null` and `false`  is made

**Comment by Zales0123** [comment]
Should be fixed by https://github.com/Sylius/Sylius/pull/10165
