### ISSUE TITLE
[Taxation][RFC] Multiple tax rates in one tax category

### ISSUE THREAD

**Issue by czende** [Sylius/Sylius#9257]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Sylius version   | 1.1.1

Hi, I would like to open discussion about tax rates and their relations to tax category. For now there is a possibility to have multiple tax rates related to single tax category. But then in `Sylius/Component/Taxation/Resolver/TaxRateResolver.php` it's called `$this->taxRateRepository->findOneBy(['category' => $category])` and first found tax rate is returned. It's just no make sense.

So I think tax category FK in tax rates should be unique, what do you think?

**Comment by vvasiloi** [comment]
@czende if it will be unique, it won't be possible to have a many-to-one relationship neither with `TaxCategory` nor `Zone`.
Look at `\Sylius\Component\Taxation\Resolver\TaxRateResolverInterface::resolve` method, it accepts an array of criteria wich is merged with the tax category.
For example in `\Sylius\Component\Core\Taxation\Applicator\OrderItemsTaxesApplicator::apply` the zone is also added to the criteria.

**Comment by czende** [comment]
@vvasiloi Yes, you are right, but still its confusing and user cannot know what tax rate is used at the end.

**Comment by vvasiloi** [comment]
@czende by user you mean customer or admin user?

**Comment by czende** [comment]
@vvasiloi I mean admin/client user. Moreover when you have two categories with same name, in product edit there will be two "same" options in tax category select.

**Comment by czende** [comment]
Discussion moved to slack :-)
