### ISSUE TITLE
Complete checkout callback service should be removed from SyliusOrderBundle

### ISSUE THREAD

**Issue by alexsegura** [Sylius/Sylius#9258]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.1.x

Hello, 

I'm using `SyliusOrderBundle` as a "standalone" bundle (without the whole distribution), and the state machine configuration shipped with the bundle calls a non-existent `@sylius.complete_checkout_callback` service. 

This was changed in `SyliusCoreBundle` in 57f544cc067eedb68d058b5992e25d60dd79cd34, but it is still there in `SyliusOrderBundle`. 

I can make a PR if you agree.

**Comment by Zales0123** [comment]
@alexsegura this is for sure a bug, feel free to open a PR :)
