### ISSUE TITLE
Lot of classes are final

### ISSUE THREAD

**Issue by arnaudroulee** [Sylius/Sylius#9263]
Why lot of classes are final ?

If we need to override them, we have to copy the entire class, add our logic and redefine service.

if there is bug fix in this class, it's very difficult to maintain our code.

Thank

**Comment by Zales0123** [comment]
Hello @arnaudroulee and welcome to the community! **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our Slack (preffered) or [stackoverflow](https://stackoverflow.com/questions/tagged/sylius) ;) Regarding you question - I recommend reading something about concept called "composition over inheritance". It should nicely explain why you should depend more on oop structures like decoration than just extending classes. Good luck :)

**Comment by pamil** [comment]
https://ocramius.github.io/blog/when-to-declare-classes-final/
