### ISSUE TITLE
Unable to override roles feature 

### ISSUE THREAD

**Issue by smtlab** [Sylius/Sylius#9270]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Sylius version   | 1.x.y

Hi,

I am trying to override roles feature and add custom roles for ShopUser but unable to do it as the 
`Sylius\Component\User\Model\UserInterface` has type hint string for add role and other role related methods.

```
    /**
     * @param string $role
     */
    public function addRole(string $role): void;
```

**Comment by Zales0123** [comment]
Hello Sumeet :) **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our Slack (preferred) or [stackoverflow](https://stackoverflow.com/questions/tagged/sylius). I'm sure somebody would find some time to help you with your problem :)
