### ISSUE TITLE
[documentation] how to override private assets?

### ISSUE THREAD

**Issue by Bonobomagno** [Sylius/Sylius#9274]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no/yes
| BC Break report? | no/yes
| RFC?             | no/yes
| Sylius version   | 1.1.1

On doc there is no explain about this.
You can ADD file(with new paths), but no way to substitute/override actual js/css/img.
If i dont want to use them i must rewrite the gulpjs or rewrite the view without including default assets, but still my /web directory will have all the default files, they will be just not in use.

Any alternative solution?
If you create a theme skeleton WITH  overriding css/js/img, would be nice.
For eg, i still didn't found a way to remove sylius logo from the web directory (without changing gulpfile, or vendor, ofc)

Thanks

**Comment by Bonobomagno** [comment]
I'm start to think that using gulpfile is the only quick solution.
So, i suggest to include a default one inside sylius-standard and/or theme skeleton.

bwt.
On theme skeleton there is a composer inside che specific theme, instead on docs the composer.json is on the themes root (./themes/composer.json instead of ./themes/MyTheme/composer.json)


An other question about theming. Suggested way to bundle all in few files?

**Comment by stefandoorn** [comment]
@Bonobomagno What I did is in the base Gulpfile add my own stuff. You can define the same function in your code as in Sylius JS and if you load it after the Sylius defaults, you can override it. That's at least what's working for me. There is no 'best practice' or clear path in this I think unfortunately.

**Comment by Bonobomagno** [comment]
The ugly thing is that you have to override the default, or you will have
sylius default file inside the web dir.

I made my custom gulp file too.  fortunately I have gulp on an other
project, so was easy to integrate imagemin and other things.

Ofc webpack is better, but I don't want to split too much the theming.

I think that a better documentation explaining this would be nice to have.

Il 19 mar 2018 19:34, "Stefan Doorn" <notifications@github.com> ha scritto:

**Comment by Bonobomagno** [comment]
I think that the way asset:install work, it is a bad RFC.
Too much decoupling of the web dir, hard to optimize and too many files to include

Usually i'm used to split js/css in app/main/bundle + vendor, both versioned.
here instead all files inside bundles are not touched, so every one for himself on source mode.
Any idea on how to bundle them?

**Comment by Bonobomagno** [comment]
Now that you started using babel, any update on asset handling for customizing?
