### ISSUE TITLE
Sylius bundles are currently in 1.1.0 version on packagist instead of 1.1.2

### ISSUE THREAD

**Issue by loic425** [Sylius/Sylius#9275]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.1.2

Like previously on #9077, sylius packages still in 1.1.0 instead of 1.1.2

**Comment by lchrusciel** [comment]
Loic, sorry, but I'm afraid you will have to wait until next release for this update :( Something about 10th of April.

**Comment by loic425** [comment]
@lchrusciel Ok, thank you, no problem.
