### ISSUE TITLE
[Promotion] Checkers need to be better organized

### ISSUE THREAD

**Issue by winzou** [Sylius/Sylius#928]
Ref: #920 

A few things to do:
* We could use a voter-like mechanism for promotion checkers. In that way it's super simple to add or remove checkers. Each checker return `eligible` or `not_eligible` or `abstain`
* This enable to fix some logic like the trick of returning true whereas the method is actually abstaining
* We must get rid of event dispatching in such methods. Checkers are here to check, not to dispatch events

@mykehsd please tell us if you can do it or if anyone can take this issue.

Thanks

**Comment by michalmarcinkowski** [comment]
Reworked in #6273, I suppose this can be closed.
