### ISSUE TITLE
[RFC] Switch to Symfony Serializer

### ISSUE THREAD

**Issue by teohhanhui** [Sylius/Sylius#9288]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Sylius version   | 1.x

JMS Serializer is a pain to deal with, and it just doesn't do the sensible thing out of the box. For example:

https://stackoverflow.com/questions/31948118/jms-serializer-why-are-new-objects-not-being-instantiated-through-constructor

https://github.com/schmittjoh/JMSSerializerBundle/issues/639

In contrast, Symfony's [ObjectNormalizer](https://symfony.com/doc/current/components/serializer.html#normalizers) through the [instantiateObject method](https://github.com/symfony/symfony/blob/v4.0.6/src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php#L312) even supports matching properties to constructor parameters.

Testimony: At [API Platform](https://github.com/api-platform/core), we use the Symfony Serializer.

Full disclosure: @dunglas who created API Platform is a member on the Symfony core team. He was the main person who made Symfony Serializer awesome.

**Comment by loic425** [comment]
@pamil I'd like to try doing this one. I may start today.

**Comment by pamil** [comment]
It's a great idea and I'm personally all for it, but for the project, it would probably result in either:
a) need to support both JMS and Symfony serializers
b) dropping support for JMS serializer which is possibly a BC break indeed

Do you have some ideas how we can tackle it without breaking existing applications (they might extend JMS mappings or define new ones) and too much maintenance effort?

**Comment by teohhanhui** [comment]
To provide an upgrade path, we could keep the JMS Serializer mappings around but deprecate its use in Sylius. We could provide Symfony Serializer mappings, it shouldn't cause any issues.

Yes, for the transition period, we must support both JMS Serializer and Symfony Serializer. And in the next major version, we could drop support for JMS Serializer and remove the mapping files.

**Comment by loic425** [comment]
@teohhanhui @pamil 
I totally agree with this solution to deprecate jms serialization.

**Comment by teohhanhui** [comment]
@pamil We need a do-not-stale here.

**Comment by pamil** [comment]
Fully agreed.

**Comment by mitalcoi** [comment]
totally agree. JMS is very bad solution, we faced with trouble every time when need to override serialization

**Comment by Roshyo** [comment]
Bump on this one.
I can help if needed.
No, I want to help !! JMS is such a pain to use...

**Comment by wendel841** [comment]
+1, also ur team can take look at https://github.com/liip/serializer, i hope in near future it can become drop-in replace for jms.

**Comment by Roshyo** [comment]
IMO it's more relevant to use native serializer. I've never used Liip, but I think that using Symfony core components is a better choice for LTS and compatibility.

**Comment by CoderMaggie** [comment]
With the API v2 we have moved to Symfony Serializer, therefore I'm closing this issue. ✌🏻

**Comment by Roshyo** [comment]
@CoderMaggie that is not completely true. As in the admin, for ResourceAutocomplete, we still use JMS Serializer. Should we create a new issue ? Or reopen this one ?
