### ISSUE TITLE
[RFC] Update ChannelNotFoundException to LocaleNotFoundException format

### ISSUE THREAD

**Issue by diimpp** [Sylius/Sylius#9294]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Sylius version   | 1.x.y

[`ChannelNotFoundException`](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Channel/Context/ChannelNotFoundException.php) accepts as constructor only another exception, while [`LocaleNotFoundException`](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Locale/Context/LocaleNotFoundException.php), [`CurrencyNotFoundException`](https://github.com/Sylius/Sylius/blob/master/src/Sylius/Component/Currency/Context/CurrencyNotFoundException.php) allows for custom message. 

Would be cool to upgrade `ChannelNotFoundException` to same format. For example, I've a custom shop-api, which have channel defined in URL and there're multiple cases why this exception could be thrown.

**Comment by pamil** [comment]
Could you provide a PR for 1.2 (master)?
