### ISSUE TITLE
Autocomplete choice cannot be set to null

### ISSUE THREAD

**Issue by teohhanhui** [Sylius/Sylius#9297]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.x

Say, I have a `brand` field on the `Product`, but once I select a brand it's no longer possible to clear it.

**Comment by mikemix** [comment]
Is this ever going to be resolved? This is a major flaw.

**Comment by mikemix** [comment]
Omg

**Comment by mikemix** [comment]
Thanks :)

**Comment by pguetschow** [comment]
This is my quick and dirty workaround for this. It is hacky AF but does the job with minimal effort. I just added a clickable thingy next to all autocomplete fields in the global theming file and it erases the current content of the closest autocomplete field.

I modified the SyliusUiBundle/Form/theme.html.twig like this:

``` 
{% block sylius_resource_autocomplete_choice_row %}
    <div class="{% if required %}required {% endif %}field{% if (not compound or force_error|default(false)) and not valid %} error{% endif %}" style="display: flex;">
        {{- form_label(form) -}}
        <div
            class="sylius-autocomplete ui fluid search selection dropdown {% if multiple %}multiple{% endif %}"
            data-url="{{ remote_url }}"
            data-choice-name="{{ choice_name }}"
            data-choice-value="{{ choice_value }}"
            data-criteria-type="{{ remote_criteria_type }}"
            data-criteria-name="{{ remote_criteria_name }}"
            data-load-edit-url="{{ load_edit_url }}"
        >
            {{- form_widget(form, {'attr': {'class' : 'autocomplete'}}) -}}
            <i class="dropdown icon"></i>
            <div class="default text">{% if placeholder is defined %} {{ placeholder|trans }} {% endif %}</div>
            <div class="menu"></div>
        </div>
        {# THIS PART IS NEW#}
        <div class="ui fluid autocomplete-reset">
            <i class="icon times circle" style="margin-top: .5em;margin-left: .5em;cursor: pointer;font-size: 1.5em;"></i>
        </div>
        {{- form_errors(form) -}}
    </div>
{% endblock %}
```
And added some hacky JS to the/assets/admin/entry.js

```
$(document).ready(function() {
  $('.autocomplete-reset').on('click', function () {
    $(this).siblings('.sylius-autocomplete').find('.autocomplete').val(null);
    $(this).siblings('.sylius-autocomplete').find('.text').html('');
  });
});
```

Maybe this workaround can help someone in the future

**Comment by lchrusciel** [comment]
Hey folks! 

I can confirm, that bug exists. The solution is as simple, as adding empty field to the list of possible choices, however we would need scenario for that. In addition, we should probably add some possibility to declare on the form level, if empty field should be possible(but can be skipped for the first iteration)

**Comment by Geolim4** [comment]
Hello, anyone working on this, I can confirm that it is a major flaw that needs to be patched at the root form type  `ResourceAutocompleteChoiceType` itself :(

**Comment by coldic3** [comment]
Hi everyone, I hope it's fixed in https://github.com/Sylius/Sylius/pull/13805. If the issue still exists feel free to open a new one 💃
