### ISSUE TITLE
v1.1.4 still require NelmioAliceBundle

### ISSUE THREAD

**Issue by shadypierre** [Sylius/Sylius#9304]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.1.3 & 1.1.4

1.1.3 & 1.1.4 release still require NelmioAliceBundle (see : https://github.com/Sylius/Sylius/blob/v1.1.4/src/Sylius/Bundle/CoreBundle/Application/Kernel.php#L103).
That leads to an error :
`PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "NelmioAliceBundle" from namespace "Nelmio\Alice\Bridge\Symfony".
Did you forget a "use" statement for another namespace`

**Comment by pamil** [comment]
@shadypierre I'll try to fix it with v1.1.5 today, things went out of hand this week

**Comment by pamil** [comment]
@teohhanhui we're open for better solutions :)

**Comment by shadypierre** [comment]
Fixed by #9303
