### ISSUE TITLE
[RFC] Cleaner separation between Sylius and Sylius-Standard

### ISSUE THREAD

**Issue by teohhanhui** [Sylius/Sylius#9305]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Sylius version   | future major

Currently, many files exist in the Sylius repository that are only useful for the Sylius-Standard repository. This means the two projects are tightly coupled in a convoluted way. Issues like #9301 and #9304 cannot be properly fixed, because of the lack of a clean separation. Of course, this also makes it almost impossible to move to Symfony Flex (correct me if I'm wrong).

**Comment by pamil** [comment]
Apart of them being useful in Sylius-Standard, we also need them to test the whole application using Behat. I'm not sure if I understand Symfony Flex issue correctly, but it's mostly connected to single bundles, not the whole application, so this should be possible just by customising them.

**Comment by teohhanhui** [comment]
@pamil Continuing the discussion here.

We could start by getting rid of the shared `Kernel`, or if there's a need for some extended functionality, making sure that whatever is in it is not related to the "app" / distribution.

**Comment by teohhanhui** [comment]
> Apart of them being useful in Sylius-Standard, we also need them to test the whole application using Behat.

The test app should have its own `AppKernel`. Yes, there will be some duplication, but it's necessary. :)

**Comment by teohhanhui** [comment]
Also, all the `XXXBundle/Resources/app/config.yml` and such should definitely be moved to Sylius-Standard.

Say, normally something like #9330 would be fixed in Sylius-Standard, not Sylius.

**Comment by pamil** [comment]
It's still a pain point from maintainer/contributor perspective.

**Comment by Zales0123** [comment]
Event though we will probably be thinking what we should do with Sylius-Standard in the future, I believe this issue can be closed 🖖
