### ISSUE TITLE
[Channel] Changing channel does not work, if the expected channel does not have a current locale

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#9307]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | master

<img width="1316" alt="screen shot 2018-04-06 at 12 08 36" src="https://user-images.githubusercontent.com/6213903/38415917-44031d62-3993-11e8-8572-d1cf3a336762.png">

**Comment by vvasiloi** [comment]
@lchrusciel What would you expect to happen? Also switch to channel's default locale if the requested one isn't available?
