### ISSUE TITLE
Wrong type hint when returning collections

### ISSUE THREAD

**Issue by teohhanhui** [Sylius/Sylius#9309]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.x

The type hint should be `iterable` instead of `Doctrine\Common\Collections\Collection`. It even contradicts with our own PHPDoc. Fixing this will be a BC break, unfortunately.

**Comment by pamil** [comment]
Where?

**Comment by teohhanhui** [comment]
Everywhere. But just an example: https://github.com/Sylius/Sylius/blob/v1.1.4/src/Sylius/Component/Core/Model/ImagesAwareInterface.php#L20-L23

**Comment by teohhanhui** [comment]
That should be:

```php
    /**
     * @return Collection|ImageInterface[]
     */
    public function getImages(): iterable;
```

**Comment by pamil** [comment]
Can't see what's wrong there, it's an interface which returns a `Collection` object.

**Comment by pamil** [comment]
It does not contradict with any PHPDoc, at least the example you have provided.

**Comment by teohhanhui** [comment]
The PHPDoc says it'd return a `Collection` **or** an array of `ImageInterface`.

**Comment by teohhanhui** [comment]
Or should we change the PHPDoc to `Collection<ImageInterface>`?

**Comment by pamil** [comment]
The `|` part is mostly due to incomplete support in IDEs. It should be something like `Collection&iterable<ImageInterface>`, but that makes PHPStorm and probably any other IDE stop providing autocompletion. The return typehint itself is correct.

**Comment by teohhanhui** [comment]
Yeah, that's why we need PSR-5: https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc.md#collections
