### ISSUE TITLE
UserInterface has setLocked but no isLocked

### ISSUE THREAD

**Issue by teohhanhui** [Sylius/Sylius#9311]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.x

https://github.com/Sylius/Sylius/blob/v1.1.4/src/Sylius/Component/User/Model/UserInterface.php#L71-L74

**Comment by vvasiloi** [comment]
It's in the `AdvancedUserInterface` it extends: `\Symfony\Component\Security\Core\User\AdvancedUserInterface::isAccountNonLocked`

**Comment by teohhanhui** [comment]
Uhh, my bad.
