### ISSUE TITLE
[UiBundle] French miss spelling

### ISSUE THREAD

**Issue by Dean79000** [Sylius/Sylius#9313]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.1.4

In File : `UiBundle/Resources/translations/messages.fr.yml`

Current :
`sign_in: 'Connection'`

Expected :
`sign_in: 'Connexion'`

**Comment by czende** [comment]
@Dean79000 You can fix it by yourself on [crowdin](https://crowdin.com/translate/sylius/934/en-fr#q=sign) and I will approve it, if you want :-) Correct translation will be automatically merged in the next release.
