### ISSUE TITLE
Cannot delete or update a parent row: a foreign key constraint fails

### ISSUE THREAD

**Issue by czende** [Sylius/Sylius#9320]
| Q                | A
| ---------------- | -----
| Bug report?      | maybe
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Sylius version   | 1.1.*

Hi, when I want to delete used resource (product, promotion, etc) there is a proper flash message that resource is in use. But in production environment I'm using sentry as logger, and sentry always give me exception above. So flash message is triggered, in admin UI nothing abnormal happened, but sentry fired this exception. Is it appropriate behaviour or just sentry thing?

**Comment by pamil** [comment]
I guess stopping event propagation would prevent Sentry from catching it (and it makes sense since we're passing our own response in `ResourceDeleteSubscriber`).

**Comment by pamil** [comment]
@czende the solution here is to lower the priority of `kernel_exception` listener in Sentry (https://github.com/getsentry/sentry-symfony#listeners-priority).

**Comment by czende** [comment]
Thanks @pamil I'll try that.
