### ISSUE TITLE
Deprecation: logout_on_user_change must be set to true on firewall config

### ISSUE THREAD

**Issue by teohhanhui** [Sylius/Sylius#9327]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.x

We need to make `User` implement [`EquatableInterface`](https://github.com/symfony/symfony/blob/v3.4.8/src/Symfony/Component/Security/Core/User/EquatableInterface.php) to fix a Symfony deprecation message safely. See https://github.com/symfony/symfony/pull/23882 and https://github.com/symfony/symfony-docs/issues/8428

**Comment by pamil** [comment]
Our test suite passes with Symfony 4, so it's either not tested now (but I'm almost sure we do change the user data in some tests) or it's not an existing bug.

**Comment by teohhanhui** [comment]
It is always `true` in Symfony 4, and the option has been deprecated in Symfony 4.1

I think we definitely should note this in the upgrade notes. It'll be a breaking change for those upgrading to Sylius 1.2 / Symfony 4.x

**Comment by teohhanhui** [comment]
In other words, this was one of those rare cases where Symfony does some weird BC break-ish deprecation because of its security implications.
