### ISSUE TITLE
the sixth level of the menu of taxon is flickering

### ISSUE THREAD

**Issue by tarakbz** [Sylius/Sylius#9331]
| Q                | A
| ---------------- | -----
| Bug report?      | yes

| RFC?             | no/yes
| Sylius version   | 1.1.2

hy , 
the sixth level of the menu of taxon is flickering , i update the semantic ui to the last version , but that does not solve the problem
any idea please ? 
thanks for help .

**Comment by Zales0123** [comment]
Hello @tarakbz! What do you mean by `flickering`? Is your question about menu in Admin panel or in shop? Taxons tree has indeed not the best UX, for sure it needs some work, someone with good UX/UI skills would be more than welcomed in our community 😄

**Comment by tarakbz** [comment]
![capture d ecran de 2018-04-13 10-05-09](https://user-images.githubusercontent.com/2982846/38726930-7d932160-3f03-11e8-8465-3f75877af55c.png)

hy , 
the third column with the text "test1à2" and "sdfsdf"  appears twice on each rollover of the "test" menu

**Comment by tarakbz** [comment]
any idea ?

**Comment by lchrusciel** [comment]
Slack and StackOverflow are our main support channels. Please ask there your question
