### ISSUE TITLE
RFC: PerformanceBundle

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#9336]
Today while trying to improve some speed I found out that `ActivePromotionsByChannelProvider::getPromotions` does a new database query every time you use it, even if in the same request / same channel. I have to apply promotions on some pages more than 100 times per request (don't ask why). I think it would be nice to have some decorators that handle this, similar to the `CachedPerRequestChannelContext` implementation. 

As it's pure for performance, I think it would be good to group them under a separate bundle e.g., as maybe not everyone wants to use it. 

WDYT?

**Comment by teohhanhui** [comment]
You could just have a CachedXXX implementation which uses a PSR-6 cache implementation, such as the Symfony Cache component.
