### ISSUE TITLE
Deleting taxons, hard to see where a relation still exists

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#9348]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Sylius version   | 1.0.x

As a shop manager, it's sometimes hard to delete taxons. It's easy to find out which products have that taxon as a main taxon set, but it's harder for the related taxons. Would be great to see this in the admin, to make shop managers life easier :-)

**Comment by CoderMaggie** [comment]
Closing as a duplicate of https://github.com/Sylius/Sylius/issues/9220
