### ISSUE TITLE
[Docs] Configuring tax rates needs call to setCategory

### ISSUE THREAD

**Issue by MichaelMackus** [Sylius/Sylius#9351]
http://docs.sylius.com/en/1.1/components_and_bundles/bundles/SyliusTaxationBundle/configuring_taxation.html#configuring-the-tax-rates

**Comment by MichaelMackus** [comment]
Looks like the documentation still hasn't been updated. Feel free to assign me to the issue & I can look at this when I find some time. If the issue gets closed, I'll likely forget...

Just trying to help newcomers to Sylius, since the linked documentation never sets up the relationship between the tax & tax category.

**Comment by lchrusciel** [comment]
@MichaelMackus if you only have time to open a PR @Sylius/core-team would love to review and merge it :)

**Comment by pamil** [comment]
#9763 should fix this issue.

**Comment by pamil** [comment]
Fixed! 🎉
