### ISSUE TITLE
Multichannel Bug

### ISSUE THREAD

**Issue by wpexpertsio** [Sylius/Sylius#9363]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 0.18

Create Multichannel in backend the frontend page and backend settings page give error 
An exception has been thrown during the rendering of a template ("Channel could not be found!")." at /opt/lampp/htdocs/test/vendor/sylius/sylius/src/Sylius/Bundle/WebBundle/Resources/views/Frontend/layout.html.twig line 55 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the rendering of a template (\"Channel could not be found!\"). at /opt/lampp/htdocs/test/vendor/sylius/sylius/src/Sylius/Bundle/WebBundle/Resources/views/Frontend/layout.html.twig:55, Sylius\\Component\\Channel\\Context\\ChannelNotFoundException(code: 0): Channel could not be found! at /opt/lampp/htdocs/test/vendor/sylius/sylius/src/Sylius/Component/Channel/Context/CompositeChannelContext.php:54)"

**Comment by wpexpertsio** [comment]
Yes i configure hostname for each channel  https://drive.google.com/file/d/1rhv42ZksT4XNvowCWcQVdT0EJJmv5Am6/view?usp=sharing

**Comment by Zales0123** [comment]
Maybe it's not explained explicitly, but each channel must work on a different hostname :) Btw, I know it's not always possible, but I highly recommend to switch to a stable version of Sylius. On such an old version as 0.18 you could encounter many errors that won't be fixed from our side, as it's not supported anymore.

At the end, I also recommend to register on our Slack to have more instant help from the community :)

**Comment by pamil** [comment]
v0.18 is not supported anymore, as @Zales0123 mentioned above.
