### ISSUE TITLE
How to turn off oauth authentication on some interfaces?

### ISSUE THREAD

**Issue by weiwenhao** [Sylius/Sylius#9367]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.x.y

How to turn off oauth authentication on some interfaces?
Does rest api only apply to admin?

**Comment by Zales0123** [comment]
Hello @weiwenhao and welcome to the community! **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our Slack or [Forum](forum.sylius.com) (preffered) or [stackoverflow](https://stackoverflow.com/questions/tagged/sylius) ;) Good luck :)
