### ISSUE TITLE
some subtree split repositories aren't being updated

### ISSUE THREAD

**Issue by jrobeson** [Sylius/Sylius#9375]
| Q                | A
| ---------------- | -----
| Bug report?      | yes?

For example: https://github.com/Sylius/SyliusResourceBundle hasn't been updated since March 15th.

**Comment by jrobeson** [comment]
It seems that others are in fact being upda

**Comment by martiis** [comment]
+1 component also

**Comment by pamil** [comment]
I've just managed to switch to [splitsh/lite](https://github.com/splitsh/lite) and subtree splits are now done in literally seconds. Branches have been just synchronised and all the past tags are processed right now. The next steps is to connect that with GitHub webhooks and make it a seamless process.

**Comment by martiis** [comment]
Thanks :ok_hand:
