### ISSUE TITLE
Key sylius.ui.bulk_actions is missing in Spanish translation, looking for options

### ISSUE THREAD

**Issue by migmolrod** [Sylius/Sylius#9376]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.1.5

I was going to make a pull request adding that key but I found myself very doubtful about how to translate it.
'In bulk' means 'a granel' but to me that sounds like when someone buys from a wholesaler. Not very suitable for what I think 'bulk actions' should mean.

So, blilingual people, what about 'Acciones múltiples'? Maybe 'Acciones en lote'? Any other suggestion?

**Comment by lchrusciel** [comment]
Please join [Sylius project on Crowdin](https://crowdin.com/project/sylius) and suggest translation there. Sylius is just synchronised with those translations.
