### ISSUE TITLE
Select Type for product Attributes throws Array to string convertion error

### ISSUE THREAD

**Issue by mamazu** [Sylius/Sylius#9387]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.2.0

Steps to reproduce:
* Create a second locale
* Create a product attribute with type select
* Add two possible values for the configuration (and translate them in every locale)
* Set min entries = 0 and max entries = 1
* Add a name for the attribute in both languages
* Save

Result:
![image](https://user-images.githubusercontent.com/14860264/39527719-736ddeae-4e22-11e8-82b3-1622acb3be13.png)

**Comment by Zales0123** [comment]
I've just checked it and it seems to work fine (probably after https://github.com/Sylius/Sylius/pull/10077) :)

<img width="1191" alt="zrzut ekranu 2019-01-11 o 15 36 13" src="https://user-images.githubusercontent.com/6212718/51040051-c67fb480-15b6-11e9-92b2-d0ec7bc44a65.png">


Feel free to open this issue if something is still wrong :)
