### ISSUE TITLE
Product option impact instead of multiple variants

### ISSUE THREAD

**Issue by Toumm** [Sylius/Sylius#9395]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes
| Sylius version   | 1.x.y

Hi there,
I have product with a lot of option, and the server cannot handle the generation of all the variants by the 504 response time SLA. Eventhough, even if it would be able to generate them, it will take like 3 days to configure them.
Are you thinking about creating a new kind of option that alter the price of the master variant instead of creating variants? 
Product 1 20$
--> Option 1:
      ---> choice 1: +0$
      ---> choice 2: +10$
      ---> choice 1: +20$
Maybe this could be sort of an adjustment? Just thinking out loud...

I saw a few tickets about this topic, but no real improvement in these :(

**Comment by alexsegura** [comment]
You will need to implement this by yourself. 
I did this using adjustments, like you are suggesting. 

I extended [`ProductOption`](https://github.com/coopcycle/coopcycle-web/blob/f5b02c8eb2382aeae6a371c0d21ab2b6ec66b012/src/AppBundle/Sylius/Product/ProductOptionInterface.php) and [`ProductOptionValue`](https://github.com/coopcycle/coopcycle-web/blob/f5b02c8eb2382aeae6a371c0d21ab2b6ec66b012/src/AppBundle/Sylius/Product/ProductOptionValueInterface.php) to store the additional amount. 
In your case, you will most probably only need to extend `ProductOptionValue`

```php
interface ProductOptionInterface extends BaseProductOptionInterface
{
    const STRATEGY_FREE = 'free';
    const STRATEGY_OPTION = 'option';
    const STRATEGY_OPTION_VALUE = 'option_value';

    public function getStrategy(): string;
    public function setStrategy(string $strategy): void;

    public function getPrice(): ?int;
    public function setPrice(?int $price): void;
}
```

```php
interface ProductOptionValueInterface extends BaseProductOptionValueInterface
{
    public function getPrice(): ?int;
    public function setPrice(?int $price): void;
}
```

Then, I added an [`OrderProcessor`](https://github.com/coopcycle/coopcycle-web/blob/f5b02c8eb2382aeae6a371c0d21ab2b6ec66b012/src/AppBundle/Sylius/OrderProcessing/OrderOptionsProcessor.php) that adds adjustments based on the option values.

**Comment by nfacciolo** [comment]
Is that solution worked ?
