### ISSUE TITLE
[RFC] Consider replacing DB DC2TYPE:array with json_array app wide

### ISSUE THREAD

**Issue by diimpp** [Sylius/Sylius#9399]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | not sure
| RFC?             | yes
| Sylius version   | 1.x.y

Hi,

Problem is that `array` field type is not query-able, but `json_array` can be accessed via native functions and extensions like https://github.com/SyslogicNL/DoctrineJsonFunctions

So as far as I know, DB field type `array` can be switched to `json_array` without any BC in codebase (Don't really know).

My use case is where I need to pull promotion with specific rule configuration from DB, with `json_array` it can be done in more civil manner, than regexping `configuration` field.

> +----+--------------+--------------------------------------------+------------------------------------------------+
> | id | promotion_id | type                                       | configuration                                  |
> +----+--------------+--------------------------------------------+------------------------------------------------+
> |  1 |            1 | cart_quantity                              | a:1:{s:5:"count";i:100;}                       |

Are there downfalls beside BC for existing DB? I'm not sure.

Cheers.

**Comment by pamil** [comment]
I'm for it if we can provide migrations (and in the best case scenario - tests for these migrations).

**Comment by teohhanhui** [comment]
The correct type should be `json` as `json_array` type has been deprecated since Doctrine DBAL 2.6

**Comment by lchrusciel** [comment]
This change will block us from using MariaDB, and therefore platform.sh which has only MariaDB as MySQL instance :(

**Comment by teohhanhui** [comment]
Why would it block from using MariaDB? I don't understand. Doctrine DBAL supports MariaDB.

**Comment by lchrusciel** [comment]
Ok, my bad. They have [json type as a long text](https://mariadb.com/kb/en/library/json-data-type/)... It will work then, but not as expected

**Comment by teohhanhui** [comment]
Not stale.
