### ISSUE TITLE
Sylius Upgrading

### ISSUE THREAD

**Issue by wpexpertsio** [Sylius/Sylius#9406]
| Q                | A
| ---------------- | -----
|Sylius version   | 0.18

I want to upgrade sylius from 0.18 to 1.0.0
I follow this steps http://docs.sylius.com/en/1.1/book/installation/upgrading.html .. and remove all dependent bundle from composer.json 
When i run composer update sylius/sylius command i take long time and finally i get this error
- Conclusion: don't install symfony/symfony v3.2.0-RC2|install symfony/console v2.8.33|install symfony/console v2.8.34|install symfony/console v2.8.35|install symfony/console v2.8.36|install symfony/console v2.8.37|install symfony/console v2.8.38|install symfony/console v2.8.39
- Installation request for sensio/generator-bundle (locked at v2.5.3) -> satisfiable by sensio/generator-bundle[v2.5.3].

**Comment by blankcheck** [comment]
Install fresh new sylius, migrate data - that is what we have done.

We tried upgrade route from 0.19 - not pleasant, migration was simple enough.

I guess future upgrades (from 1 up) are much simpler.

**Comment by antonioperic** [comment]
Just go with fresh Sylius, you will save a lot of time.
