### ISSUE TITLE
[RFC] Use PHP-CS-Fixer directly and remove sylius-labs/coding-standard

### ISSUE THREAD

**Issue by teohhanhui** [Sylius/Sylius#9409]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | no
| BC Break report? | no
| RFC?             | yes
| Sylius version   | 1.x

EasyCodingStandard strips us of the ability to properly configure PHP-CS-Fixer. For example, there is no way to override a rule. I see it as just another unnecessary layer. And I'd argue strongly that the CS rules should be configured in a project, not as a vendor package.

**Comment by pamil** [comment]
If ECS is limiting the configuration options, we can indeed replace it with PHP-CS-Fixer (if it won't cause any other issues).

As for an external package with the configuration, it is meant to provide a common CS configuration across Sylius, projects based on Sylius and Sylius plugins.

**Comment by stefandoorn** [comment]
I use the config e.g. in my own project as dependency.

**Comment by teohhanhui** [comment]
> As for an external package with the configuration, it is meant to provide a common CS configuration across Sylius, projects based on Sylius and Sylius plugins.

Yeah, I get the intention, something like https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb. But the problem is neither ECS nor PHP-CS-Fixer provides an actual "presets" style of inheriting configuration.

**Comment by teohhanhui** [comment]
For example, this is the `.php_cs.dist` I use for our Sylius project: https://gist.github.com/teohhanhui/3558a4b9198089a28bb78e988f508261

`sylius-labs/coding-standard` (or why not in `sylius/sylius`?) could provide a `Config` class, yes... So the basic usage in the project `.php_cs.dist` would be:

```php
$finder = PhpCsFixer\Finder::create()
    ->exclude([
        'var',
    ])
    ->in(__DIR__)
;

return SyliusLabs\CodingStandard\PhpCsFixer\Config::create()
    ->setFinder($finder)
;
```

**Comment by TomasVotruba** [comment]
> For example, there is no way to override a rule.

There is. What do you mean by that?

**Comment by teohhanhui** [comment]
See my example above.

**Comment by TomasVotruba** [comment]
I know what it means, just why do you think ECS doesn't allow it?

**Comment by teohhanhui** [comment]
The old version did not allow it. I think it should be fine now.

**Comment by TomasVotruba** [comment]
Well, it's supported from the first version. Without it it would be kinda of useless.
So I wonder where did you find the bug, so it could be fixed (if there is any).

**Comment by TomasVotruba** [comment]
If you find any bug or got issue, just feel free to create or ask a questoin: https://github.com/Symplify/Symplify/issues/new

I'm here to help :)
