### ISSUE TITLE
Related products call to /admin/ajax/products/ takes too much memory

### ISSUE THREAD

**Issue by stefandoorn** [Sylius/Sylius#9411]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0.x

Not sure about the internals, but it looks like that calls to the `sylius_admin_ajax_product_index` route (on adding relations at product level via the admin) returns all data when a too broad search term has been used, therefore using lots of memory on the serialization and thus giving issues on certain hosts. 

```
ErrorException: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4198400 bytes)
  File "vendor/jms/serializer/src/JMS/Serializer/JsonSerializationVisitor.php", line 238, in handleFatalError
    $result = @json_encode($this->getRoot(), $this->options);
```

Wouldn't it be better there to use `sylius_admin_ajax_product_by_name_phrase` as it's a name search, doesn't need to know about grid, is autocomplete, etc.? Also, it can have a limit..

Usage here: `app/vendor/sylius/sylius/src/Sylius/Bundle/AdminBundle/Resources/views/Product/Tab/_associations.html.twig`

**Comment by Takeno** [comment]
It should be a duplicate of #9364

**Comment by stefandoorn** [comment]
Duplicate of #9364 indeed :)
