### ISSUE TITLE
Attributes in ProductVariant

### ISSUE THREAD

**Issue by alanpoulain** [Sylius/Sylius#9443]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.2.0

For the project I am working on, we had to introduce attributes in ProductVariant.
This can be useful if you need to add information specific to a variant and not to the related product.
For example, you may need to inform the customer that the red T-shirt is a collector one.
WDYT of having this feature directly in Sylius?

**Comment by Zales0123** [comment]
Hello Alan! The idea is nice and could be useful for some shops, but I think it's more case for a plugin thank for Sylius itself (at least for now). What do you think about such an approach? Check out our [Sylius Plugin development guide](https://docs.sylius.com/en/1.1/plugins/creating-plugin.html) for more info, you can also take a look at [existing plugins](https://sylius.com/plugins/).

**Comment by alanpoulain** [comment]
Hello Mateusz!
I understand your point of view. It depends of how you see Sylius: is it a core e-commerce platform without much features but highly customizable? Or is it a ready-to-use solution?
IMO there are some drawbacks of having a separate plugin:
- the user needs to know there is a plugin corresponding to its need (and it could have a bad impression when it uses Sylius for the first time: "Where is this feature I need?"),
- having a separate repository often means it will be less maintained (see for example the SyliusShopApiPlugin).
A plugin is really useful when you want to add a feature related to a third-party service (MailChimp, Akeneo, ...). But for a feature related directly to Sylius, I think having a plugin is less useful.
WDYT of my reasoning?

**Comment by Zales0123** [comment]
All things you've mentioned are totally true, it all depends on how Sylius should be seen. In my opinion (and I think also people from @Sylius/core-team) we should deeply focus on providing the best e-commerce functionalities and build the ecosystem around for customization and extensions (integrations and plugins).

Pros of having a plugin:
- easier from maintain point of view (don't have to be maintained by Sylius team)
- could be developed faster, not being limited by Sylius release cycle and BC promise
- plugin can be merged in the future to Sylius core, if we'll see that such a functionality is crucial for Sylius itself

Maintaining plugins is another story. You've mentioned SyliusShopApiPlugin, but even though it's not aggressively developed right now, it's already used in plenty of Sylius projects :) The same with the visibility of plugins - they surely should be more exposed and we will work on that for sure.

Nevertheless, I summon @pamil and @pjedrzejewski, I would like to see your opinion 😄

**Comment by stefandoorn** [comment]
As a Sylius user, I agree with @Zales0123. I prefer a stable well-maintained core with not too much functionality in it (obviously there needs to be a good base) with high-quality plugin infrastructure (which still needs work - e.g. 2 plugins extending same entity seems hard now) that is easily discovered.

**Comment by alanpoulain** [comment]
Your arguments are good too.
However since attributes are already used for `Product`, it seems to me it's a better idea to add them for `ProductVariant` too. It will force you to maintain a reusable code for attributes (and force some refactoring beforehand).
If a plugin is done, either it will duplicate the current code for attributes, or it will need some refactoring in the core and will contain only a few lines of code.
And to be honest, I don't have the courage to maintain a separate plugin. I think it's the case for a lot of developers, so it means you will receive less contributions from external developers.

**Comment by lchrusciel** [comment]
First of all, Sylius is meant to be highly customizable tailored to your needs solution rather than out of a box one. 
Secondly, Plugins architecture allows us to change the implementation or abandon bad or miscoded plugins, where the core stays same and is easy to upgrade. Once the plugin is battle tested it can be integrated into the core without too much work.
What is more, SyliusShopApiPlugin is an example why we need plugins instead of core development. We do not have enough power to support every possible feature, and plugins allow us to change the focus and let some parts to grow up at their own pace. New features are not delivered there, but bug fixes were merged, and it is up to date with master AFAIR.
We should be able to create a plugin effortless and check how useful it will be. Attribute bundle is pretty generic. Attributes concept itself on variant seems to be useful for me.

**Comment by stefandoorn** [comment]
Btw, I'm totally PRO to including some community/Sylius-core-team plugins by default in the default installer + instructions how to disable them if wanted.

**Comment by alanpoulain** [comment]
The SyliusShopApiPlugin is not necessarily the best example. It seems master is OK, but I was more talking about the releases (last one is 9 months ago).
There is no other example for what I'm talking (no third-party service but core functionalities) other than the SyliusShopApiPlugin.
Another solution I have not talked about is to remove the concept of attributes in the Sylius core and have a separate plugin for adding them in Product *and* in ProductVariant too. I think it's the best course of action if I follow your explanations.

**Comment by gabiudrescu** [comment]
@alanpoulain why don't you use Product Options to assign some product (variant) attributes?

**Comment by alanpoulain** [comment]
You mean using an option with only one value?
Why not but I think it's twisting the purpose of the option which is to add variation to a product.
In my case, it's not really to add variation but more to add details about a variant.

**Comment by Neirda24** [comment]
Hey @alanpoulain : In the end was a plugin developped ? We may have the same use case and other people landing on this issue could find useful to have a link to this plugin if it exists.
