### ISSUE TITLE
[Documentation] Docs refer to deprecated Sylius-Docs repository

### ISSUE THREAD

**Issue by pmikolajek** [Sylius/Sylius#9445]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.0

Current version of [Submitting a Patch](https://github.com/Sylius/Sylius/blob/482f7787202095e7459273c86022337550a299fd/docs/contributing/code/patches.rst) documentation page makes mention of having to "send a pull request to the [documentation repository](https://github.com/Sylius/Sylius-Docs) to update the documentation when appropriate". [Sylius-Docs](https://github.com/Sylius/Sylius-Docs), however, has been deprecated and is read-only. Should the paragraph be reworded to point to [Contributing to the Documentation](https://github.com/Sylius/Sylius/blob/482f7787202095e7459273c86022337550a299fd/docs/contributing/documentation/overview.rst) instead?

**Comment by Zales0123** [comment]
Definitely it's misleading, thank you for reporting that bug 👍
