### ISSUE TITLE
Links are broken on release change logs

### ISSUE THREAD

**Issue by loic425** [Sylius/Sylius#9449]
| Q                | A
| ---------------- | -----
| Bug report?      | kind of
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 

https://github.com/Sylius/Sylius/releases
Here, links to pull requests are broken release change logs, but they're ok on change log files.

**Comment by pamil** [comment]
Fixed 🎉

**Comment by loic425** [comment]
@pamil yes, thank you
