### ISSUE TITLE
server can't find public path (SF4)

### ISSUE THREAD

**Issue by hiousi** [Sylius/Sylius#9455]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.2 BETA

If you try to run PHP embeded web server with `bin/console server:start 0.0.0.0:80` it will fail with 
"The document root directory "/public" does not exist.

Symfony 4.0 suggest  /public where Sylius use /web.

**Comment by pamil** [comment]
You can change `public` to `web` by adding `--docroot=web` to that command.

**Comment by hiousi** [comment]
@pamil thank you for the workaround, that what I have done.

the doc does not indicate --docroot in its command.
should the sylius doc be changed? (http://docs.sylius.com/en/latest/book/installation/installation.html)

closed?

**Comment by pamil** [comment]
Yeah indeed, Sylius docs should be changed, could you send a PR to a `1.2` branch about it?
