### ISSUE TITLE
Problem promotionCoupon

### ISSUE THREAD

**Issue by alexandrelam** [Sylius/Sylius#9471]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.1.5

Hi,
When I apply a simple promotionCoupon

I have : Caused by:

ConstraintViolation {#6265 ▼
  root: Form {#4458 …}
  path: "data.promotionCoupon"
  value: null
}

Any ideas ? thank you

**Comment by Zales0123** [comment]
Hello @alexandrelam and welcome to the community! **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our [Slack](http://sylius.org/slack) (preferred), [forum](https://forum.sylius.com/) or [stackoverflow](https://stackoverflow.com/questions/tagged/sylius) ;) Good luck!
