### ISSUE TITLE
symfony 4 upgrade

### ISSUE THREAD

**Issue by mitalcoi** [Sylius/Sylius#9478]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.2.0

I just create fresh symfony 4.1 app and try to install last sylius, but got an error:
<img width="976" alt="2018-06-11 12 58 14" src="https://user-images.githubusercontent.com/3224226/41225322-31d98b5e-6d77-11e8-8dc4-057e563d66a2.png">

**Comment by pamil** [comment]
Could you try installing Sylius as recommended in http://docs.sylius.com/en/latest/book/installation/installation.html?

`composer create-project -s rc sylius/sylius-standard project`
