### ISSUE TITLE
Wrong flag icon of Czech republic in administration

### ISSUE THREAD

**Issue by hladpe** [Sylius/Sylius#9479]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.1.6

Czech language (cs_CZ) has displayed wrong Serbian flag (css class "cs") instead of correct one (css class "cz"). This bug is in administration for example specifically during creating or editing taxon, product,...

![sylius-sylius-czech-flag](https://user-images.githubusercontent.com/23253970/41240171-31d68422-6d9a-11e8-802d-fe3a97aeece0.png)

**Comment by lchrusciel** [comment]
The problem probably has its roots in Symfony Intl component.

**Comment by pamil** [comment]
Fixed by #10553.
