### ISSUE TITLE
Administrator creating Orders

### ISSUE THREAD

**Issue by CoderMaggie** [Sylius/Sylius#9501]
⚠️ 🛣 **This issue is a part of the** [Sylius Public Roadmap](https://github.com/orgs/Sylius/projects/2) 🛣 ⚠️ 

**Proposed solution**

Administrator from the Orders page in the admin panel should be able to create an Order and:

- choose or create a new Customer (with autocomplete),
- provide addresses of the Customer,
- choose items and their quantities (with autocomplete),
- choose payment and shipping methods,
- modify prices of items,
- modify total price of the Order (and have that modification distributed on items as adjustments)
- have preview of the created Order, before they place it
- after placing the Order send confirmation email with a link to payment to the Customer

_Edited:_
There is a work being done in https://github.com/Sylius/AdminOrderCreationPlugin repository. 🎉

**Comment by pamil** [comment]
There is a work being currently done in https://github.com/Sylius/AdminOrderCreationPlugin repository.

**Comment by CoderMaggie** [comment]
Closing, for further issues please post on the plugin repository https://github.com/Sylius/AdminOrderCreationPlugin :)
