### ISSUE TITLE
Customer Reorder

### ISSUE THREAD

**Issue by CoderMaggie** [Sylius/Sylius#9502]
⚠️ 🛣 **This issue is a part of the** [Sylius Public Roadmap](https://github.com/orgs/Sylius/projects/2) 🛣 ⚠️ 

**Proposed solution**

The main idea is to copy all the items of a chosen Order to a new Cart.
If something (items prices, order total, expired promotion, items stock availability) has changed between the old Order and the new Cart -> inform the Customer about that in a flash message.

_Edited:_
There is a work being done in https://github.com/Sylius/CustomerReorderPlugin repository. 🎉

**Comment by pamil** [comment]
There is a work being done in https://github.com/Sylius/CustomerReorderPlugin repository. 🎉

**Comment by CoderMaggie** [comment]
Closing, for further improvements please open new issues on the Plugin https://github.com/Sylius/CustomerReorderPlugin.
