### ISSUE TITLE
Administrator Reorder

### ISSUE THREAD

**Issue by CoderMaggie** [Sylius/Sylius#9503]
⚠️ 🛣 **This issue is a part of the** [Sylius Public Roadmap](https://github.com/orgs/Sylius/projects/2) 🛣 ⚠️ 

**Proposed solution**

This is basically the same as in Customer Reorder but from the Admin perspective. It is also similar to the Admin order creation, but with Customer and items already chosen.

_Edited:_
There is a work being done in https://github.com/Sylius/AdminOrderCreationPlugin repository. 🎉

**Comment by pamil** [comment]
There is a work being done in https://github.com/Sylius/AdminOrderCreationPlugin repository. 🎉

**Comment by pamil** [comment]
The official plugin for that feature is available in this repository: https://github.com/Sylius/AdminOrderCreationPlugin

**Comment by Zales0123** [comment]
I think that issues assigned to `Roadmap` should not be stalled... wdyt @pamil @CoderMaggie?

**Comment by CoderMaggie** [comment]
Closing, for further issues please post on the plugin repository https://github.com/Sylius/AdminOrderCreationPlugin :)
