### ISSUE TITLE
Invoicing

### ISSUE THREAD

**Issue by CoderMaggie** [Sylius/Sylius#9504]
⚠️ 🛣 **This issue is a part of the** [Sylius Public Roadmap](https://github.com/orgs/Sylius/projects/2) 🛣 ⚠️ 

Invoices are a complex, highly custom problem for each shop. As an eCommerce _framework_ we are willing to solve the most generic approach for it.

**Proposed solution**

In order to provide simple Invoicing for Sylius we will try to cover such scenarios:

- As an Administrator, when an Order is placed I want to have an Invoice automatically generated
- As an Administrator, I can view the Order's Invoices (as a list, and show of each Invoice)
- As an Administrator, I can download the Order's Invoices as pdf files
- As an Administrator, I want to browse all Invoices in the system (this will be a new item on the left menu in admin panel, under Orders)
- As a Customer, I want to download my Orders' Invoices as pdf files
- As a Customer, when my Order's Payment is paid, I want to receive an email with a downloadable Invoice
- As an Administrator, I want to resend to a Customer a chosen Invoice of their Order

_Edited:_
There is a work being done in https://github.com/Sylius/InvoicingPlugin repository (very early stage though). 🎉 

Apart from the scenarios listed above, the outcome we'd like to achieve is an immutable Invoice model (continuing efforts made in #9005), so that we won't get any glitches when the tax rate is changed etc.

**Comment by pamil** [comment]
There is a work being done in https://github.com/Sylius/InvoicingPlugin repository. 🎉 

Apart from the scenarios listed above, the outcome we'd like to achieve is an immutable Invoice model (continuing efforts made in #9005), so that we won't get any glitches when the tax rate is changed etc.

**Comment by Roshyo** [comment]
To fit our own needs, we developped a plugin meeting nearly all requirements listed above.
https://github.com/BeHappyCommunication/SyliusInvoicePlugin

It only lacks the email part.
We would be very glad to propose this plugin as official. Imo the only thing missing is the "features" part on wich we would be happy yo have some help.

**Comment by bruno-ds** [comment]
I had to develop an invoice system, one tricky part is the handle of the refunds.
Because a refund invoice has to be generated and a lot of possible case exists (total refund, partial refund of one/multiple articles,...)

In my case we chooses to be tightly coupled with stripe and filling a refund form in sylus' admin trigger a refund in stripe + the invoice

**Comment by Sripathi69** [comment]
As a customer I would like to track invoices through SMS on my mobile phone

**Comment by Roshyo** [comment]
Hi, I'm pretty sure that's a very specific use case that might need either custom development, either plugin. But I believe SyliusCore will find this use case too specific to be integrated in core.

**Comment by Zales0123** [comment]
I totally agree with @Roshyo 👍 This is a very specific use-case but should be quite easy to customize (either by custom code or by another plugin) 🖖

**Comment by CoderMaggie** [comment]
Closing, for further issues please post on the plugin repository https://github.com/Sylius/InvoicingPlugin :)
