### ISSUE TITLE
Customer registration in Checkout

### ISSUE THREAD

**Issue by CoderMaggie** [Sylius/Sylius#9505]
✅ **DONE**: #9656 ✅ 

⚠️ 🛣 **This issue is a part of the** [Sylius Public Roadmap](https://github.com/orgs/Sylius/projects/2) 🛣 ⚠️ 

**Proposed solution**

In the guest checkout, on the thank you page display e-mail and add a checkbox "☑️ I want to register in the shop", that will show two more fields below: password + password confirmation.

By having this we will be able to register the guest, while checking out. After leaving checkout they will need to of course confirm their account via the verification link they'll get on email. Then they will be able to see their order in the my account.

**Comment by stefandoorn** [comment]
Alternative: let the user make an account from the order thank you page instead of doing it inside the checkout (distracts).

**Comment by CoderMaggie** [comment]
@stefandoorn that's a good suggestion!
