### ISSUE TITLE
Returns

### ISSUE THREAD

**Issue by CoderMaggie** [Sylius/Sylius#9507]
⚠️ 🛣 **This issue is a part of the** [Sylius Public Roadmap](https://github.com/orgs/Sylius/projects/2) 🛣 ⚠️

There are many possible scenarios for Order returns, but as an eCommerce _framework_ we are willing to give the most generic approach for it (initially).

**Proposed solution**

Glossary:
- `Return Merchandise Authorisation = RMA` is a document that is generated upon the Customer request, after it is authorised by the Administrator (Customer Service)
- `RMA Request` happens when a Customer wants to inform the Shop that they would like to return items of their Order, where they provide a reason including description and pictures.

Whole(all items and cost) Order returns:
a Customer wants to return all items of a chosen Order; 
Customer opens a RMA Request providing a return reason; 
Admin accepts or declines the RMA Request (providing a message); 

If Admin accepts the RMA request, the RMA is created marking the RMA as `new`;
the Customer gets a RMA confirmation email with shipping instructions;
after the Shop receives a package to the Customer's RMA they mark the RMA as `authorized` or `rejected` (when something was wrong with the package);
after the Shop resolves the Return (manually) they mark the RMA as `resolved`;

**Comment by pjedrzejewski** [comment]
Implemented in the Sylius Plus version.

**Comment by dbalabka** [comment]
@pjedrzejewski is it possible that the Open Source version will have the `returned` order status w/o any advanced RMA support?
