### ISSUE TITLE
[RFC] Revive RBAC, possibly as plugin

### ISSUE THREAD

**Issue by diimpp** [Sylius/Sylius#9508]
⚠️ 🛣 **This issue is a part of the** [Sylius Public Roadmap](https://github.com/orgs/Sylius/projects/2) 🛣 ⚠️

With increasing Sylius popularity, including multi-channel and multi-tenant use cases, you can see rise to self-made access control solutions like
https://github.com/BeHappyCommunication/SyliusRightsManagementPlugin
https://bitbag.shop/products/sylius-access-control-layer

Personally I consider RBAC as most brilliant component, solving so complex topic in so simple and understandable manner and I was very sad seeing it go from the core.

In my experience all projects, that I've recently worked on, were lacking in roles separation and were ignoring this case as too pricey to tackle by themself or implementing rudimentary roles separation.

I think it's important to present official solution to as important and complex topic as security. Keep community undivided and present a stronger case for who considering to start using Sylius.

What do you think?

**Comment by alexrowesoap** [comment]
Getting RBAC back would be fantastic. We baked our own solution to compensate, but it's nowhere near as powerful as RBAC was

**Comment by pierre-H** [comment]
Why not using Symfony voters and ACL ?

**Comment by CoderMaggie** [comment]
Morning guys!
Christmas came early this year 🤶 😄 
Our RbacPlugin (MVP version) is now public: https://github.com/Sylius/RBACPlugin

**Comment by CoderMaggie** [comment]
Closing, for further issues please post on the plugin repository https://github.com/Sylius/RBACPlugin :)
