### ISSUE TITLE
Lacking debug:winzou

### ISSUE THREAD

**Issue by gustawdaniel** [Sylius/Sylius#9510]
**Sylius version affected**: v1.2.0

**Description**  

I docs

> http://docs.sylius.com/en/latest/cookbook/shop/checkout.html

There is presented command:

    php bin/console debug:winzou:state-machine

but applying this give error

```                     
  There are no commands defined in the "debug:winzou" namespace.  
                                                                  
  Did you mean one of these?                                      
      debug                                                       
      debug:payum 
```

**Steps to reproduce**  

Install Sylius in Ubuntu using composer

> https://sylius.com/download/

Use command

    php bin/console debug:winzou:state-machine

> https://sylius.com/download/

**Possible Solution**  

Update docs or dependencies.

**Comment by gustawdaniel** [comment]
I had discussion on slack 

> https://sylius-devs.slack.com

with @shql about this command. To make this command working I installed older version of Sylius by command:

    composer create-project sylius/sylius-standard=1.1.5 project_name

In newest version it seems to be broken.

**Comment by shql** [comment]
Hey, I reproduced this with a bare Symfony 4.1 install and just installing the winzou-bundle. The commands did not show up as available. Adding a custom command via console worked as expected. That's why I think it's an issue with the winzou state machine in connection with Symonfy 4.

**Comment by mikemix** [comment]
Same here guys :(

**Comment by pamil** [comment]
This is not a Sylius issue, could you open one for WinzouStateMachine (or open a PR there fixing it, there's one related here: https://github.com/winzou/StateMachineBundle/pull/43)?
