### ISSUE TITLE
Add --docroot=web in documentation of install with composer

### ISSUE THREAD

**Issue by gustawdaniel** [Sylius/Sylius#9514]
**Sylius docs version**: 1.2.0 / latest

**Description**

On the page 

> https://sylius.com/download/

There is presented command:

    php bin/console server:run

But it gives error
                                                                   
     [ERROR] The document root directory "/path_to_project/public"   
         does not exist.                                                        

Option 1:

Please replace this command by:                       

    php bin/console server:run --docroot=web

Because of in SF4 web is replaced by public.

Option 2:

Change directory structure in your project to be consistent with new symfony directories structure.

**Comment by hiousi** [comment]
should we move web to public?

**Comment by gustawdaniel** [comment]
Symfony 3 use web. Symfony 4 public.

**Comment by pamil** [comment]
Solved after v1.3.0 release! 🎉
