### ISSUE TITLE
Allow to add address during registration process

### ISSUE THREAD

**Issue by Stefun** [Sylius/Sylius#9523]
It is a common process to ask user address during registration. With existing registration form field, we can add fields related to address( address1, city/state, country ) and add this address as a default address.

**Comment by vvasiloi** [comment]
It can be easely customized, why put it in core?

**Comment by Stefun** [comment]
I agree. we can customize. But usually, 80% of websites have an address related fields in their registration form and since most of the fields are common and won't vary much we can consider this for Core. @vvasiloi: What do you think?

**Comment by vvasiloi** [comment]
@Stefun Sorry, but I cannot agree with that.

**Comment by Stefun** [comment]
You can take others opinions also on this and might be poll will help :)

**Comment by CoderMaggie** [comment]
Hi there! I'm Maggie, the Product Owner of Sylius.

We have the address book feature in Sylius, which in my opinion is enough to cover that scenario. 
See more here: http://docs.sylius.com/en/1.2/book/customers/addresses/address_book.html

Please reopen if you have any alternative thoughts on that. Best regards! 👋
