### ISSUE TITLE
Improve documentation about extending templates

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#9526]
http://docs.sylius.com/en/1.2/customization/template.html says:

> Copy the contents of the original template to make your work easier. And then modify it to your needs.

However there's [hidden Symfony&Twig](https://github.com/symfony/symfony/pull/24264) feature that can make the process a lot easier so one can override only a single block of a template. For instance to add a javascript asset to the `@SyliusShop/Account/profileUpdate.html.twig` template one can create a template as follows:

```
{% extends '@!SyliusShop/Account/profileUpdate.html.twig' %}

{% block javascripts %}
    <script src="..."></script>
{% endblock %}
```

Notice the `!` exclamation after the `@` in the `extends` tag. This will prevent the `circular reference detected error`. It strongly believe this is worth mentioning.

**Comment by Zales0123** [comment]
It seems nice 😄 we're right now in the phase of updating documentation for Sylius 1.3 release, but for sure we'll check out this possibility, it really makes overriding a lot easier 🐃
