### ISSUE TITLE
logout event

### ISSUE THREAD

**Issue by tautelis** [Sylius/Sylius#9528]
There are situation where our plugin needs to do some actions on user logout. There is not way to define multiple success_handlers and `ShopUserLogoutHandler` is a final class.

I think it would be useful to have something like `sylius.security.logout` event triggered in the `ShopUserLogoutHandler`. Optionally, passing the ShopUser object to the event (not sure if the customer context still have it at the moment the process enters success_handler).

**Comment by lchrusciel** [comment]
You can always decorate this service, can't you? 

Anyway, event may be a good idea

**Comment by tautelis** [comment]
Well, decoration is an option. Will use that for the moment, though event seems to be a cleaner way IHMO.

**Comment by mikemix** [comment]
Why don't you use a handler? `ShopUserLogoutHandler` sucks anyway. It extends Symfony success handler, but should be a handler anyway imvho. The success handler's job is to return a redirect response and is not intented to carry any additional domain logic like it does now.
