### ISSUE TITLE
Twig exception while rendering a form element when creating new select product attribute

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#9529]
**Sylius version affected**: 1.2.0

**Description**  
Twig exception while rendering a form element when creating new `select` product attribute.

**Steps to reproduce**  
This only happens when creating new product attribute, not editing. Add a new product attribute of type `select`. Leave `not multiple`, set `min entries` to 1 and `max entries` to 1. Add any value. See the error.

**Possible Solution**  
Validation missing? This only happens when creating new product attribute. When editing I get nice validation error.

**Comment by CoderMaggie** [comment]
Hey there!

I've tried to reproduce and to me the behaviour while creating the select rpoduct attribute seems okay. See screenshot below:

![image](https://user-images.githubusercontent.com/13198869/42080484-1defee48-7b83-11e8-9c05-d5b9c6216406.png)


Could you describe more, what seems wrong for you?

**Comment by mikemix** [comment]
You're missing a value.

**Comment by CoderMaggie** [comment]
Okay I got it!
![image](https://user-images.githubusercontent.com/13198869/42108757-b6a443e8-7bdb-11e8-9081-73309f88ac14.png)

Marking it as a bug then :)

**Comment by Zales0123** [comment]
I've just checked it and it seems to work fine (probably after https://github.com/Sylius/Sylius/pull/10077) :)

<img width="1166" alt="zrzut ekranu 2019-01-11 o 15 31 31" src="https://user-images.githubusercontent.com/6212718/51039838-6db01c00-15b6-11e9-8c8e-277c5aea15d0.png">

Feel free to open this issue if something is still wrong :)
