### ISSUE TITLE
Cannot delete product option values

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#9530]
**Sylius version affected**: 1.2.0

**Description**  
Cannot delete product option value when creating or editing a product option.

**Steps to reproduce**  
Go to `Product options` page and try to remove a product option value after it was added.

![zaznaczenie_040](https://user-images.githubusercontent.com/2399452/41962852-62cd983c-79f6-11e8-8470-b6ef4c2cbd20.png)

**Possible Solution**  
Missing crud buttons!

**Comment by Roshyo** [comment]
Any update on this ?

**Comment by Roshyo** [comment]
Here we are, don't know if tests are to be written though.

**Comment by Roshyo** [comment]
@CoderMaggie Maybe close this for the same reasons as the linked PR ?

**Comment by lchrusciel** [comment]
Hey folks! 

I can agree that this functionality may be useful, however, due to variant resolution we cannot simply allow for deletion of option values. We should allow for it only, when there is no usage of this particular value. If this case will be covered, I'm happy to merge this PR.
