### ISSUE TITLE
typo in the custom css and javascript page

### ISSUE THREAD

**Issue by muldos** [Sylius/Sylius#9535]
**Sylius docs version**: 1.2 / latest

**Description**
On this page 
http://docs.sylius.com/en/1.2/cookbook/frontend/admin-js-and-css.html?highlight=custom%20css

```{% include 'SyliusUiBundle::stylesheets.html.twig' with {'path': 'assets/admin/css/custom.css'} %}```
should be
```{% include 'SyliusUiBundle::_stylesheets.html.twig' with {'path': 'assets/admin/css/custom.css'} %}```

Best regards,

David

**Comment by bhargavmehta** [comment]
@Zales0123 
Please close this ticket.

**Comment by Zales0123** [comment]
Fixed by https://github.com/Sylius/Sylius/pull/9691, thank you @bhargavmehta and @muldos
