### ISSUE TITLE
"View your store" admin button's invalid url

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#9536]
**Sylius version affected**: 1.2.0

**Description**  
The "View your store" button redirects to an invalid URL if the store is ran on any other port than 80 and/or in a dev mode. My current URL: `http://localhost:8080/app_dev.php/admin`. Button redirects to: `http://localhost`, but should redirect to `http://localhost:8080/app_dev.php`.

**Steps to reproduce**  
Run Sylius on port any other than 80 and see the link in the admin's header.

**Possible Solution**  
Get site's url from the routing and let Symfony generate it properly.

**Comment by CoderMaggie** [comment]
Hi @mikemix 👋! 

Sylius takes the hostname from channel config, which you can adjust in the admin panel, and that's the desired behaviour. So generally you can go to channels config and set your hostname to `http://localhost:8080` and this redirect will work perfectly.

Please reopen if that's something else you've meant.
