### ISSUE TITLE
Improve admin UI on smaller screens

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#9538]
Current state of the customer grid in the admin, on 1366x768 screen:

![zaznaczenie_017](https://user-images.githubusercontent.com/2399452/42090552-2d50a2c8-7ba2-11e8-82b3-735fa3b401b4.png)

**Describe the proposed solution**
1. Add `whitespace: no-wrap` for the boolean labels (vide `Enabled` label on the attached screen).
2. Collapse action buttons on smaller screens

**Describe alternatives you've considered**
Override the template, I'm not keen on doing that.

**Additional context**
None.

**Comment by Roshyo** [comment]
Up, I think it is necessary to support a decently small screen (let's say 1400px wide ?) And the actual BO just lacks a button collapse to be ok.
Maybe also a smaller left menu with submenus being displayed on hover ?

**Comment by Zales0123** [comment]
Still relevant :( cc @kulczy, maybe you would be interested in implementing these improvements? 😄

**Comment by kulczy** [comment]
I will try to come up with some good solution 🤖

**Comment by pamil** [comment]
Fixed by #10215 in 1.3 🎉
