### ISSUE TITLE
Checkout & cart lost when trying to login while checking out

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#9542]
**Sylius version affected**: 1.2.0

**Description**  
Checkout & cart lost when trying to log in while checking out.

**Steps to reproduce**  

1. Add something to the cart and press `Check out`
2. Fill first field: a valid e-mail, password field pops out with the Login button
3. Type your valid password and press the button log in.
4. Poof, you are redirected to your dashboard and everything is lost. This is totally unacceptable.

**Possible Solution**  
Don't redirect to the dashboard? I'm going to disallow unauthenticated people to make orders.

**Comment by CoderMaggie** [comment]
related to: https://github.com/Sylius/Sylius/issues/8370

**Comment by Zales0123** [comment]
Hello Mike, I've just checked it out on our demo and on the newest `1.3` and it seems to work... Can you, please, check it out is it still an issue? Thanks!
