### ISSUE TITLE
It should not listen to loadClassMetaData events during a "doctrine:mapping:import" command

### ISSUE THREAD

**Issue by docteurklein** [Sylius/Sylius#955]
Currently, the loadClassMetadataSubscriber class listens on a **disconnected** schema, which makes the process fail.

**Comment by djaed** [comment]
just discovered this myself today ... 

when "doctrine:mapping:import"

was getting [Symfony\Component\Debug\Exception\ContextErrorException]                              
  Warning: class_parents(): Class XXXX does not exist and could not be loaded

so as quick fix simply commented out:

    /**
     * @return array
     */
    public function getSubscribedEvents()
    {
        //return array(
        //    'loadClassMetadata',
        //);
    }

then ran command again without problems ... after successful mapping:import and generate:entities I uncommented the above subscribed event again and all done ....

hope this helps someone solve the issue quicker

**Comment by msumme** [comment]
Also running into this issue.  It might be sufficient to just check to see if the class_exists before attempting to loop over its parents.  I tested the following, and it fixed the issue for me, though I don't know if there are any possible side-effects from that?
```php
 private function setAssociationMappings(ClassMetadataInfo $metadata, $configuration)
    {
        $class = $metadata->getName();
       // class will not exist during doctrine:mapping:import - skip process in this case.
        if(!class_exists($class)) {
            return;
        }
        foreach (class_parents($class) as $parent) {
            $parentMetadata = new ClassMetadata(
                $parent,
                $configuration->getNamingStrategy()
            );
            if (in_array($parent, $configuration->getMetadataDriverImpl()->getAllClassNames())) {
                $configuration->getMetadataDriverImpl()->loadMetadataForClass($parent, $parentMetadata);
                if ($parentMetadata->isMappedSuperclass) {
                    foreach ($parentMetadata->getAssociationMappings() as $key => $value) {
                        if ($this->hasRelation($value['type'])) {
                            $metadata->associationMappings[$key] = $value;
                        }
                    }
                }
            }
        }
    }

```

**Comment by patkar** [comment]
/ping @docteurklein 

Any update on this? Would be the fix of @msumme enough or does this break some behavior?

**Comment by harry-flipkod** [comment]
Also encountered this issue. Still no fix?
