### ISSUE TITLE
Make a possibility to opt-out from version notifications more visible

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#9554]
**Sylius docs version**: 1.1

Related to the discussion in #9547.

**Comment by venyii** [comment]
I think this is still very important to point out to people, I was surprised myself as well when I **discovered** it. Might tag it as a hacktoberfest issue

**Comment by DaniloBenevides** [comment]
Hello , can I work on this ? :D

**Comment by pamil** [comment]
Fixed by #9839.
