### ISSUE TITLE
XSRF: Missing form token in Admin-Panel

### ISSUE THREAD

**Issue by pawelwaniek** [Sylius/Sylius#9564]
**Sylius version affected**: 1.2.0

**Description**: 
_EDIT: Hidden until the issue is solved. (@pamil)_

**Comment by pamil** [comment]
Thank you a lot, the fix will be released in the morning (for future security issues, please report them privately at security@sylius.com, as [stated in the docs](http://docs.sylius.com/en/latest/contributing/code/security.html#reporting-a-security-issue).
