### ISSUE TITLE
As an admin I want to reduce the number of clicks required when creating a product

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#9565]
**Describe the proposed solution**
When we create a variant product in the admin, after the product was created, we should be redirected to the `/admin/products/X/variants/generate` url as this is an another required step in order to create a fully functional product. While this isn't an issue when creating a simple product, if creating a variant we have to 1) go back to the products list 2) find the product which can be troublesome when having hundreds or thousands of products 3) click on the `Manage variants` button 4) click on the `Generate variants` button. It's a pain in the *** if you ask me.

**Describe alternatives you've considered**
None. Personally I alter the url by hand by myself albeit I cannot ask my clients to do the same.

**Additional context**
None.

**Comment by Zales0123** [comment]
Redirecting to variants generation page is not the best option IMO - some stores have a very little number of variants or does not want to base them on product options. We must remember, that in **Sylius** itself we should provide as simple and reusable solution as it can be.
My suggestion is to add "Generate variants" button somewhere on the product edit page. As we're redirected to edit page by default, it would reduce the number of required clicks to 1. We could also do the same with promotion edit page (for generating coupons).

**Comment by mikemix** [comment]
Sure, that extra button would be great.
