### ISSUE TITLE
Stale asset cache in the browser between Sylius upgrades

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#9572]
**Describe the proposed solution**
If you update Sylius version, new assets are built, but client browser cache does not refresh that easily and still uses previous assets (css files etc.). Do you have any easy solution for this?

**Describe alternatives you've considered**
Override template, generate [manifest](https://symfony.com/blog/new-in-symfony-3-3-manifest-based-asset-versioning) file for assets, include assets by myself.

**Additional context**
None.

**Comment by pamil** [comment]
As @teohhanhui mentioned on Sylius' Slack:

> we need to use one of `version`, `version_strategy` or `json_manifest_path`
> https://symfony.com/doc/current/reference/configuration/framework.html#version

**Comment by teohhanhui** [comment]
This is one of the things that having only 1 `gulpfile` would definitely help with...

**Comment by mikemix** [comment]
Please don't block me from using the `json_manifest_path`. I have my own assets to manage.

**Comment by teohhanhui** [comment]
@mikemix You could always use `packages`: https://symfony.com/doc/current/reference/configuration/framework.html#packages

**Comment by teohhanhui** [comment]
If you ask me, all Sylius assets should be under a `sylius` asset package.

**Comment by mikemix** [comment]
Agreed.

**Comment by pamil** [comment]
I'd like to help, but my versioning / Gulp / frontend knowledge is not enough here :)

I think we can add `sylius` asset package without any BC breaks in v1.3.0, wdyt?

**Comment by mikemix** [comment]
Maybe we could drop yarn too, npm has lock file support too now.

**Comment by mikemix** [comment]
Please do not stale :/

**Comment by NoResponseMate** [comment]
Webpack has become the default tool for asset building since 1.12 and AFAIK it also includes cache busting with content hashing and manifests.
Let me know if something is still amiss, but for now, I'm closing this issue as resolved.
