### ISSUE TITLE
Variant generation throws exception when option has no values

### ISSUE THREAD

**Issue by bart1337** [Sylius/Sylius#9576]
**Sylius version affected**: 1.2.2

**Exception Message**  

> The set builder requires a single array of one or more array sets.

**Steps to reproduce**  

1. Create an option (DO NOT ADD ANY VALUES).
2. Create configurable product (select option created in previous step). 
3. Press Manage variants -> generate on created product.
4. Boom exception.

**Possible Solution**  
Require at least one value when creating options.

**Comment by pamil** [comment]
If someone would like to solve this bug:
 - target `1.1` branch
 - write a Behat scenario reproducing this issue (see `features/product/managing_product_variants/generating_product_variant.feature` and `features/product/managing_product_variants/generating_product_variant_validation.feature`):
    - you would need to create a new step `And this product has option "Taste" without any values` based on `And this product has option "Taste" with values "Orange" and "Melon"` (implementation can be found in `src/Sylius/Behat/Context/Setup/ProductContext.php:556`)

In case of any questions ask me here or on Slack (same handle, @pamil).

**Comment by Zales0123** [comment]
Fixed by #10242, thank you for reporting, @bart1337! 🖖
