### ISSUE TITLE
[Core] [BC-Break] Not nullable customer on order

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#9577]
**Sylius version affected**: 1.1.8

**Description**  
BC-Break introduced in https://github.com/Sylius/Sylius/pull/9552/commits/261c614f0e38d0660693cca4c30751376194434c#diff-fb2a1dbd12848847780522681726f61dR129. We should still allow for null value here.

**Comment by pamil** [comment]
Solved by #9578.
