### ISSUE TITLE
Cannot verify shop user account when account was created in the backend

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#9582]
**Sylius version affected**: <= 1.2.2

**Description**  

**My use case is not to allow unverified shop users to authenticate.** (I have a `UserChecker` that verifies that)

As an admin I created a shop user. I checked that user is enabled, can login to the shop and assigned a password. However this shop user's account is not verified (`verified_at` is null). I "recovered the password" successfully, clicked on the link to recover the password, set a new one, but still the account isn't verified. Is it possible to verify the account then under any circumstance?

**Steps to reproduce**  
Simple as is.

**Possible Solution**  
1. Add `verified` checkbox to the user profile form in the admin's backend, so the admin can mark the account as verified by himself.
2. Verify the account if any e-mail link is clicked (like a reset password link)

**Comment by lchrusciel** [comment]
I can confirm, that bug still exists. However we have already needed functionality in the shop part. The `verify` button should be copied from shop to the admin section (however we need to be careful to not couple admin with shop). Another possibility is to just add `verified` toggle on the customer edit page. The end goal would be to have them both in Sylius Core.
