### ISSUE TITLE
All grids empty after fresh install

### ISSUE THREAD

**Issue by Toumm** [Sylius/Sylius#9584]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no
| Sylius version   | 1.2.0

After a fresh install of Sylius, all grids are empty in the admin and show a message saying there is no result to display. I have created products and options, they are in the DB and editable entering manually the URL but the grids are all empty (Products grids, Option grids...)

**Comment by pamil** [comment]
Could you provide us exact steps you made? I can't reproduce it myself.

**Comment by SiCoUK** [comment]
I have found this happens if you change the default locale in the config. If you reinstall from the command line it works with the default locale you set and shows all the products.
