### ISSUE TITLE
Custom shipping calculators-Not appear in Admin dashboard

### ISSUE THREAD

**Issue by ChafikHadjAbdouRazack** [Sylius/Sylius#9588]
I use doc to make custom shipping calculator but the new method not appear in admin dashbord
I use sylius 1.1.10
My code:

<?php 

namespace AppBundle\Shipping;

use Sylius\Component\Shipping\Calculator\CalculatorInterface;
use Sylius\Component\Shipping\Model\ShipmentInterface;

final class FastCalculator implements CalculatorInterface
{
    
    private $fastService;

    public function __construct(FASTService $fastService)
    {
        $this->fastService = $fastService;
    }

    public function calculate(ShipmentInterface $subject, array $configuration):int
    {
        return $this->fastService->getShippingCostForDistance($subject->getOrder()->getShippingAddress()->getPostCode());
    }

    public function getType():string
    {
        return 'fast';
    }
}

service.yml:
services:
    app.shipping_calculator.fast:
        class: AppBundle\Shipping\FastCalculator
        arguments: ['@app.fast_service']
        tags:
            - { name: sylius.shipping_calculator, calculator: fast, label: "FAST" }

Need help. Thanks.

**Comment by Zales0123** [comment]
Hello @ChafikHadjAbdouRazack! **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our Slack (preferred) or [forum](https://forum.sylius.com/) ;) We have a very active, developed community, I'm sure someone will be able to help you with your problem. Good luck :)
