### ISSUE TITLE
Orders without product reference

### ISSUE THREAD

**Issue by amadi-delvis** [Sylius/Sylius#9589]
Hello.  
In the current implementation, I need to have an existing product items to create an order (FOREIGN KEY sylius_order_item.variant_id REFERENCES sylius_product_variant.id).  
If I do not want to keep a regular list of products or/and would like to get product items from alternative sources (external API's, etc), then is it possible to somehow use the current orders architecture for this task?

**Comment by Zales0123** [comment]
Hello @amadi-delvis 
For sure it is possible, but it would also require lots of customization from your site. We would definitely not support such a feature in the nearest future.
Take a look at our [customization guide](https://docs.sylius.com/en/1.2/customization/index.html), there are plenty of examples how you could adjust Sylius functionality to your needs. You can also check out [a basic Sylius-Akeneo integation](https://github.com/Sylake/AkeneoProducerBundle) which was developed by part of our team some time ago, regarding getting Sylius products from a different source.

Good luck! :)
