### ISSUE TITLE
Complicated error prone previewUploadedImage plugin

### ISSUE THREAD

**Issue by nenadalm** [Sylius/Sylius#9595]
Hi. I was adding images to one of my entities and found this: https://github.com/Sylius/Sylius/blob/281d33c1c7b3b83e9ac420e7be917e4632cb2593/src/Sylius/Bundle/AdminBundle/Resources/private/js/sylius-product-images-preview.js#L32

```js
$.fn.extend({
  previewUploadedImage(root) {
    $(`${root} input[type="file"]`).each((idx, el) => {
      $(el).change((event) => {
        displayUploadedImage(event.currentTarget);
      });
    });

    $(`${root} [data-form-collection="add"]`).on('click', (evt) => {
      const self = $(evt.currentTarget);

      setTimeout(() => {
        self.parent().find('.column:last-child input[type="file"]').on('change', (event) => {
          displayUploadedImage(event.currentTarget);
        });
      }, 500);
    });
  },
});
```

So as I understand it, if somebody adds new form part via add button, function is fired after 500ms that adds change handler on the file input.

What if there will be 2 inputs in 500ms? (last input will have 2 handlers and input before that none).
What if user removes that input in 500ms? (last input will have 2 handlers).

Why not write it just like:
```js
$.fn.extend({
  previewUploadedImage(root) {
    $(root).on('change', 'input[type="file"]', function() {
      displayUploadedImage(this);
    });
  },
});
```

? It seems to be simpler and less error prone.

**Comment by Zales0123** [comment]
If it works (I'm not a front-end expert 😄) and it's simpler than a current solution I'm totally 👍for that. Will you be willing to open a PR with such an improvement?

**Comment by nenadalm** [comment]
sure.
