### ISSUE TITLE
Username forced to e-mail only

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#9597]
**Sylius version affected**: 1.1.0

**Description**  
Why the `DefaultUsernameORMListener` forces shop user username to be e-mail only? How to create a customer & user with a non e-mail username like `mike` or `brangelina`?

**Steps to reproduce**  
Create a customer and user programatically, set non-email username to the shop user. Persist and flush.

**Possible Solution**  
Drop the listener and let people decide what username should account have? Or prevent listener from working if the username is not empty.

**Comment by mamazu** [comment]
True, in our shop this also is somewhat of a problem but this ties into the fact that email addresses in Sylius are unique across channel.

**Comment by mikemix** [comment]
Thanks. This helps.

**Comment by mikemix** [comment]
Thanks. This was helpful.

**Comment by mamazu** [comment]
I am also for implementing this so that the shop-user and the Symfony user that is used for authentication are used like they should be. (Currently the username of the Symfony is the user's email and the Symfony's user email is null for all users)

**Comment by decemvre** [comment]
Have there been any updates on this? I am integrating a forum as a sylius shop subdomain and I kind of need the username...

**Comment by vvasiloi** [comment]
@decemvre no updates, although it should be a fairly simple task. Maybe you could pick it up... 🙂

**Comment by decemvre** [comment]
@vvasiloi Nice try ( : but after giving it some thought im just going to connect the two by storing the forum db user id inside the sylius user table which is better anyway since usernames might change overtime.
