### ISSUE TITLE
Unable to make SyliusMailerBundle work under Symfony 4.1

### ISSUE THREAD

**Issue by lfjeff** [Sylius/Sylius#9598]
**Sylius version affected**: 1.x.y

**Description**  

After installing with no errors, I am unable to make SyliusMailerBundler work under Symfony 4.1

I am trying to use this as a standalone bundle, I am not using the full Sylius system.

**Steps to reproduce**  

When I try to use autowiring to inject the Sylius sender:
`__construct(Sender $syliusSender)`

I get the following error:
(1/1) RuntimeException
Cannot autowire service "App\EventSubscriber\BookingSubscriber": argument "$syliusSender" of method "__construct()" references class "Sylius\Component\Mailer\Sender\Sender" but no such service exists. You should maybe alias this class to the existing "sylius.email_sender" service.

**Possible Solution**  

The documentation appears to be old and does not give information on how to make things work with Symfony 4+:
http://docs.sylius.com/en/latest/components_and_bundles/bundles/SyliusMailerBundle/installation.html 

I have tried to create a new services yaml file to link the class, but nothing seems to work.

**Comment by pamil** [comment]
You can:
 a) either directly reference `sylius.email_sender` service instead of using autowiring
 b) or correcting the typehint to `Sylius\Component\Mailer\Sender\SenderInterface` and alias `sylius.email_sender` to `Sylius\Component\Mailer\Sender\SenderInterface`

**Comment by lfjeff** [comment]
Thanks for the reply.
 
I'm not inside a controller, so using
 sylius.email_sender is not practical. 
 Also, it's bad practice and I prefer to use
 dependency injection.
 
I changed the typehint to __construct(SenderInterface
 $syliusSender), but I can't figure out how
 to set an alias in the config.  I'm
 not up-to-speed on all the finer points of
 Symfony config files and the documentation
 I've been able to find on aliases does not
 seem to apply to my problem.
 
Would you mind giving me a bit more
 information about how to configure the
 alias you described?  I can't find any
 examples of how to do it in the config/services.yaml
 file.
 
Thanks
 
>>   b)
 or correcting the typehint to >>
   Sylius\Component\Mailer\Sender\SenderInterface
 and alias >>   sylius.email_sender
 to Sylius\Component\Mailer\Sender\SenderInterface
 

----------------------- Original
 Message -----------------------

**Comment by pamil** [comment]
Take a look at https://symfony.com/doc/current/service_container/alias_private.html#aliasing, it explains how services aliases work in Symfony.

**Comment by lfjeff** [comment]
I figured out the problem and added this PR to fix it:
https://github.com/Sylius/SyliusMailerBundle/pull/3/commits/b20880d581b22cb048109997c6ee7dfd102e5fab

**Comment by pamil** [comment]
Should be solved by #9607.
