### ISSUE TITLE
Using classes to select elements in Behat tests

### ISSUE THREAD

**Issue by nenadalm** [Sylius/Sylius#9609]
**Sylius version affected**: master

**Description**  
Hi. Maybe it would be better to use data attributes instead? I think it would be better for cases when somebody is heavily customizing templates? All attributes used for testing purposes could have some common prefix (like `b` for Behat).

Example of such data attribute could be `data-b-logout-btn` for logout button (instead of currently used class `.sylius-logout-button`).

That way it would be clear what markup is used for testing purposes (and nothing else) and should not be touched.

**Comment by Zales0123** [comment]
The idea is worth to be rethought, but as I understand it would be required then to add HTML data attributes **only** for testing? If yes, then it's a massive amount of work to do, for, correct me if I'm wrong, quite low value. In the end, even if something is changing in twig templates, it can be quite easily changed in Behat too... I'm not sure what to think about it 😄 #valuableOpinion cc @Sylius/core-team

**Comment by Roshyo** [comment]
I'm not personnaly a big fan of this. Such a method would indeed need a lot of work, and furthermore, someone heavily customizing Sylius might even change buttons from one page to another, and also, it adds a lot of octet to download for real users. It's not a comment in code that is not sent.

If you customize a lot the shop you can let classes, assuming they are useful for more than CSS (sadly...) and override the CSS itself, or even remove semantic UI CSS and apply yours.
