### ISSUE TITLE
[Cookbook][Entities] Reference to deprecated SensioGeneratorBundle

### ISSUE THREAD

**Issue by Gounlaf** [Sylius/Sylius#9614]
**Sylius docs version**: 1.x / latest

**Description**

Hi,

Documentation section "Cookbook -> Entities" refers to `SensioGeneratorBundle`; it's deprecated;
`symfony/maker-bundle` must be use instead
I might do a PR to fix it.

Regards

**Comment by Zales0123** [comment]
I think it has been already fixed, thank you, Levis, for this report :)
https://github.com/Sylius/Sylius/pull/9830
