### ISSUE TITLE
[docs] Taxon models not up to date

### ISSUE THREAD

**Issue by loic425** [Sylius/Sylius#9619]
**Sylius docs version**: 1.0 and up

**Description**
<!-- Describe what is missing or where exactly is the bug/typo/issue located. Links highly appreciated. --!>
Taxon models documentation is not up to date. 

There is no permalink anymore (both taxon and its translations), no createdAt and updatedAt on taxon (added on core) and there is position which is missing on taxon.

**Comment by pamil** [comment]
#9620 merged! :)
