### ISSUE TITLE
items_total in sylius_order table column causes 500 internal error

### ISSUE THREAD

**Issue by hatemBBN** [Sylius/Sylius#9639]
**Sylius version affected**: 1.1

**Description**  

the items_total field has limited size int(11) , thus cause 500 internal error with high values
**Steps to reproduce**  

add 70 unit of some item to cart  with unit price 15000000 through sylius resftul api

**Possible Solution**  

items_total field type or value should be changed or if you have restrictions, there should be validation rather than internal error.

**Comment by pamil** [comment]
The easiest solution would be to switch all fields dealing with prices (`Order::total`, `Order::itemsTotal`, `Order::adjustmentsTotal`, `OrderItem::total`, `OrderItem::itemsTotal`, etc.) from `integer` to `bigint` type and generate migrations for that by `bin/console doctrine:migrations:diff`. It should be targeted at `master` branch.

**Comment by lchrusciel** [comment]
Partially related to #3163

**Comment by TheMilek** [comment]
Hi @hatemBBN!

Thank you for submitting your issue 🥇 
After some discussion with the team, I must admit that this feature is not currently our main focus. 
Additionally, implementing such a thing could potentially cause some inappropriate behavior.

Thank you for your understanding and please let us know if you have any other concerns 🍻
