### ISSUE TITLE
Remove meta keywords for products

### ISSUE THREAD

**Issue by loevgaard** [Sylius/Sylius#9648]
**Describe the proposed solution**
On products you have the option to add meta keywords. Meta keywords hasn't been used for ages by anyone. Sylius is the platform of the future, so remove this.

Here's a few references:
https://webmasters.googleblog.com/2009/09/google-does-not-use-keywords-meta-tag.html
https://yoast.com/meta-keywords/

**Comment by loevgaard** [comment]
Don't close

**Comment by loevgaard** [comment]
Do not stale

**Comment by TheMilek** [comment]
Hi @loevgaard! 🚀 

Thank you for bringing this issue to our attention 🍻 
I wanted to kindly let you know that we have already addressed a similar issue in https://github.com/Sylius/Sylius/issues/12204 and the entire discussion is already documented there.

Therefore, I will be closing this issue as a duplicate. 
Please feel free to review the discussion in the linked issue if you have any further questions or concerns 😄
