### ISSUE TITLE
Missing method isEnabled in Sylius/Component/Grid/Definition/ActionGroup

### ISSUE THREAD

**Issue by piron4o** [Sylius/Sylius#9657]
**Sylius version affected**: 1.x.y

**Description**  

In `getEnabledActionGroups `  is called  `getEnabledItems ` but in `Sylius/Component/Grid/Definition/ActionGroup` `isEnabled ` is missing.
 
https://github.com/Sylius/Sylius/blob/059d85819da4c4efb2a9dfe2856f10a2d4d40093/src/Sylius/Component/Grid/Definition/Grid.php#L233

**Comment by pamil** [comment]
#9762 should fix this issue.

**Comment by Zales0123** [comment]
It's fixed now, thank you @piron4o :) 🎉
