### ISSUE TITLE
ResourceAutocompleteChoiceType: allow for closures in options

### ISSUE THREAD

**Issue by pamil** [Sylius/Sylius#9669]
**Describe the proposed solution**
`ResourceAutocompleteChoiceType` is copying the options from Symfony's `ChoiceType`. It does not include support for closures in options like `choice_value`, `choice_name` or `choice_label` which exists in `ChoiceType`. The idea is to add support for that type of parameters.

**Comment by coldic3** [comment]
I moved the issue to the resource bundle repo 👉️ https://github.com/Sylius/SyliusResourceBundle/issues/584
