### ISSUE TITLE
Taxon Translation slug generation

### ISSUE THREAD

**Issue by NVasse** [Sylius/Sylius#9670]
**Sylius version affected**: 1.2.*, demo version

**Description**  
The slug is not generated on the Taxon Translations other than the main locale and since the field is in readonly state you cannot set the slug field manually.
![capture d ecran 2018-08-23 a 17 51 32](https://user-images.githubusercontent.com/13745196/44536985-f27cc500-a6fd-11e8-8faa-dd585ec09cea.png)

**Steps to reproduce**  
Enable more than one locale, edit/add a Taxon and fill the name for any other locale than the main, the slug is not generated.

**Possible Solution**  
The problem does not exist on Product and the field is not in readonly state so maybe that's the problem.

**Comment by vvasiloi** [comment]
You can press the lock icon and edit the slug, but it would be nice to have it generated tho.

**Comment by NVasse** [comment]
.. I didn't even notice I could do that.. Thanks for the info.

**Comment by vvasiloi** [comment]
@NVasse It's not obvious... I guess the issue can be closed now.

**Comment by NVasse** [comment]
It's still a bug, the slug is generated on the main locale but no on the others.

**Comment by vvasiloi** [comment]
It's generated for all locales, based on the title in each locale, when creating a taxon.
It's also generated when editing a taxon if you unlock the slug field and edit the title for a given locale.

**Comment by NVasse** [comment]
Ok so it's actually only if you edit a Taxon and its slug for the other locales is not already filled, then the slug won't be generated, and it's really not a field you want to manually enter.

Btw, if you empty the slug field when you are creating a Taxon, the spinner won't stop.

**Comment by vvasiloi** [comment]
Unlike title, the slug isn't something someone will want to change often, that's why it's locked.
I tested on my local setup (v1.2.5) and http://demo.sylius.org/ and the slug is always generated, except the case when the slug field is locked on editing, so you have to unlock it first.
Also, no issues with the spinner.

**Comment by NVasse** [comment]
Can't reproduce the spinner bug I had.
Ok so you have to unlock it first to have it generated, didn't understand that, thanks.
