### ISSUE TITLE
.env files?

### ISSUE THREAD

**Issue by Bonobomagno** [Sylius/Sylius#9680]
**Sylius docs version**: 1.x / latest
(used sylius-standard latest)
**Description**
<!-- Describe what is missing or where exactly is the bug/typo/issue located. Links highly appreciated. --!>

i have an .env file, but no way to make sylius read it.
maybe some special config? idk

**Comment by pierre-H** [comment]
Maybe you should wait for `1.3.0` version which will be release at the end of september ([source](https://github.com/Sylius/Sylius-Standard/issues/250#issuecomment-416882102)).

**Comment by Roshyo** [comment]
Just in case you manually want to do it, it's quite easy. Just add these in app.php and app_dev.php (after the vendor/autoload.php

```php
$dotenv = new Dotenv();
$dotenv->load(__DIR__.'/../.env');
```

And the .env file will be loaded.
