### ISSUE TITLE
add product in promotion action

### ISSUE THREAD

**Issue by souidev** [Sylius/Sylius#9689]
**Sylius version affected**: 1.2.x

**Description**  
https://sylius-older.readthedocs.io/en/latest/book/promotions.html
In this page of doc it says that possible promotion action are : 
........
add product (for example: gives a free bonus sticker)
........

i can't figure out how i can do gift product in sylius

**Comment by souidev** [comment]
someone?

**Comment by souidev** [comment]
thk @mikemix could it be implemented i think it is necessary to have this feature

**Comment by mikemix** [comment]
Well it's not my responsibility to decide on that. Everybody has necessary features too ;)

**Comment by Zales0123** [comment]
Hello @souidev and sorry for the late response. First of all, you're using the old version of the documentation, but this action is indeed there in the newest version too 😄 https://sylius.readthedocs.io/en/1.2/book/orders/promotions.html#promotion-actions

It should be for sure deleted from docs. As we've right now entered the feature freeze phase of development (we're heading forward to `1.3` release), we should not add it in the code.

Thank you for reporting! :)

**Comment by souidev** [comment]
thk @Zales0123 could this feature be added as a custom action , apparently it is been active in older versionof sylius am i right ?

**Comment by Zales0123** [comment]
What do you mean by "custom action"? You mean in your custom application? :) That's for sure

**Comment by souidev** [comment]
Yes Thank 
if anyone have idea how to proceed or already implement this he's welcom to share with us :)
really gays i relly need this and i don't have enough time  
cordialement

**Comment by pamil** [comment]
https://docs.sylius.com/en/1.3/cookbook/promotions/custom-promotion-action.html should help you. Also, we recommend you our official support channels: https://docs.sylius.com/en/1.3/support/index.html

**Comment by bitbager** [comment]
Hi guys! It’s still in the docs though. Any updates on this feature?

**Comment by gabiudrescu** [comment]
this should be reopened to fix the documentation by removing the mention of obsolete rules that no longer exists.

the feature must either be introduced in Core (though I think it shouldn't) or implemented as a Plugin.

**Comment by gabiudrescu** [comment]
note to future self that arrives here from Google SERPS: the implementation in pre v1.x it is available here: https://github.com/Sylius/Sylius/blob/v0.19.0/src/Sylius/Component/Core/Promotion/Action/AddProductAction.php

in case someone wants to port this to the newer versions of Sylius :)
