### ISSUE TITLE
SyliusThemeBundle requires symfony/symfony

### ISSUE THREAD

**Issue by zghosts** [Sylius/Sylius#9693]
**Sylius version affected**: 1.2

**Description**  
Is there any particular reason why the SyliusThemeBundle requires "symfony/symfony": "^3.4|^4.1.1", instead of specifying the symfony components required by the bundle, this currently prevents me from adding the core bundle to an existing project.

**Possible Solution**  
Only require the symfony components actually required by the bundle

**Comment by pamil** [comment]
#9761 should fix this issue.

**Comment by Zales0123** [comment]
It's now fixed, thank you, @zghosts for the report :)
