### ISSUE TITLE
Product pagination bug

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#9699]
**Sylius version affected**: every

**Description**  
https://demo.sylius.com/en_US/taxons/t-shirts So we request 9 products per page, but only 6 are visible, the others are on the second page. My guess is this should not happen.

**Steps to reproduce**  
Visit https://demo.sylius.com/en_US/taxons/t-shirts

**Possible Solution**  
Dunno.

**Comment by mikemix** [comment]
This is a major issue in my opinion.

**Comment by vvasiloi** [comment]
It's happening again: https://demo.sylius.com/en_US/taxons/t-shirts?limit=9
![image](https://user-images.githubusercontent.com/7114562/55943376-2be35000-5c4f-11e9-9f1f-38e144522b31.png)

**Comment by smashou** [comment]
I think it comes from the `->addSelect('productTaxon')`. I suppose it is there to decrease the number of SQL requests, but it also generate duplicate results if a product is linked to many Taxons.
