### ISSUE TITLE
Unable to change product "enabled" field for simple product

### ISSUE THREAD

**Issue by jcgdjob** [Sylius/Sylius#9703]
**Sylius version affected**: 1.1.6

**Description**  
I have added a event listener on ProductVariantType so that on Admin site when updating products,  after form submitted, will check a custom field on ProductVariant and decided whether should update product "enabled" field to 1 or 0.

For variant product, it works fine. But for simple product, it does not work.

**Comment by CoderMaggie** [comment]
Hi there! I'd suggest to ask this question on our Slack, maybe there someone will be able to help you quicker :)

**Comment by pamil** [comment]
You can also use our other support channels: https://docs.sylius.com/en/1.3/support/index.html.
