### ISSUE TITLE
Adding a boolean to a translation Form forces to fill all languages

### ISSUE THREAD

**Issue by NVasse** [Sylius/Sylius#9704]
**Sylius version affected**: 1.2.*

**Description**  
If you add a boolean to a translation model then when you'll submit the corresponding form it will force you to fill all the required fields for all the available languages. I tried to set the boolean to null by default but it changed nothing.

**Steps to reproduce**  
1. Enable at least 2 languages
2. Add a boolean to ProductTranslation model
3. Add the checkboxType to the ProductTranslationType
4. Fill the required fields in the main language and leave the other languages fields empty
5. Submit
6. You will get a notice that the required fields for all the languages are not filled

**Possible Solution**  
ResourcesTranslationsType should check if all the fields of each submitted translation are null, if so, unset this translation.

**Comment by NVasse** [comment]
Any news about this ? It's soon going to be critical for me as we're soon going to prod the project..

**Comment by Zales0123** [comment]
Hello @NVasse, sorry for the long response time. Could you please explain a little bit more what is your use-case? As far as I understand, you are adding a boolean field on `Product` but checkbox field on `ProductTranslationType`... or is it a typo? If not, it for sure should be added in `ProductType` instead :)

**Comment by NVasse** [comment]
Hello, it's a typo, I fixed it. Everything is on the Product translation.

**Comment by NVasse** [comment]
Bump ? That's still a big problem.
