### ISSUE TITLE
Tutorial for adding a custom model uses incompatibel bundle

### ISSUE THREAD

**Issue by kappaj** [Sylius/Sylius#9710]
**Sylius docs version**: 1.2.x / latest

**Description**
The tutorial [How to add a custom model?](https://github.com/Sylius/Sylius/blob/1.2/docs/cookbook/entities/custom-model.rst) is based on the SensioGeneratorBundle. But this bundle does not support symfony 4.

The docs have to be changed. I think the best would be in using the new Symfony MakerBundle.
https://symfony.com/doc/current/bundles/SymfonyMakerBundle/index.html

**Comment by Zales0123** [comment]
Hello @kappaj and sorry for the long response time. For sure it should be changed, we're working hard to make Sylius documentation up-to-date for `1.3` release as quickly as possible :)

**Comment by Bonobomagno** [comment]
on new 1.3 you can use maker (with annotation) as flex recipe, so just 
`composer req annotation maker`

**Comment by NoResponseMate** [comment]
It took a while, but the doc in question has been updated with SymfonyMakerBundle in 1.9

Cheers :beers:
