### ISSUE TITLE
Bootstrap template

### ISSUE THREAD

**Issue by Dr-Ash** [Sylius/Sylius#9713]
Is there any bootstrap theme to be used instead of semantic ui. I think it will be a good idea to provide both semantic and bootstrap themes.

Otherwise i think i have to create a new theme if i wanna integrate a bootstrap based HTML template. (or maybe change directly in shop views as i have only one channel?)

**Comment by CoderMaggie** [comment]
If you have just one channel (and you're sure there will be no need for another one in the future), then you should override these Sylius original templates and integrate your own :) 
For the Sylius 1.2 -> https://docs.sylius.com/en/1.2/customization/template.html#methods-of-templates-customizing
