### ISSUE TITLE
Non existing urls returns 500

### ISSUE THREAD

**Issue by nenadalm** [Sylius/Sylius#9715]
example: https://demo.sylius.com/en_US/not-found

I don't know if that's the same case as in our highly customized eshop, but we had this problem: https://stackoverflow.com/questions/11869921/symfony2-is-grantedis-authenticated-fully-during-404-error-page-display-cau

(happened because cart was rendered on the page - it is rendered in base layout, which is extended by 404 page)

**Comment by pamil** [comment]
The same URL in the development mode correctly returns 404, I guess it's a bug somewhere in production exception handling.

**Comment by VGrade-pro** [comment]
Anybody fixes this issue ? I don't want to deploy a Sylius in production with a dev mode or worst, with no 404 pages at all.

**Comment by lchrusciel** [comment]
The problem currently exists on our demo :( 
E.g. https://www.demo.sylius.com/en_US/adsasd
Same will happen if we miss locale: https://www.demo.sylius.com/adsasd

**Comment by VinGrade** [comment]
Thx for responding to me, I see the problem too, but a fix is planning to future releases ? and in the meantime ,what can I do to enable the prod mode with 404 pages ?

**Comment by lchrusciel** [comment]
The problem does not exist anymore
