### ISSUE TITLE
[RFC] ChannelBasedEmailProvider

### ISSUE THREAD

**Issue by mamazu** [Sylius/Sylius#9737]
⚠️ 🛣 **This issue is a part of the** [Sylius Public Roadmap](https://github.com/orgs/Sylius/projects/2) 🛣 ⚠️

If Sylius sends an email then this email is the same for all channels. What this `ChannelBasedEmailProvider` would implement is config to look for if you want to send a channelized email eg. if the default config for the email would be `shop_api_register_user` as config key then the channel mailer would try to look for a channeled version first like `shop_api_register_user.channel1` and if no channelized email config was found, it sends the normal email. Those emails and configs have to be defined in the system using the plugin (e.g. sylius/core)

About the implementation: It would also implement the `EmailProviderInterface` and would get the channel either by using a `ChannelProvider` in the constructor via DI or has a setter for the channel. That would also make them interchangeable with the "old" non chanalized version of the `ChannelBasedEmailProvider`.

What do you think?

**Comment by CoderMaggie** [comment]
The current solution for this has been described here:
https://docs.sylius.com/en/latest/cookbook/emails/custom-email-template-per-channel.html

Please reopen if we need more here :)
