### ISSUE TITLE
Form collection nested, wrong prototype replace on add button

### ISSUE THREAD

**Issue by wadjeroudi** [Sylius/Sylius#9738]
**Sylius version affected**: 1.*

**Description**  
If you have an admin form that embed two nested collection form, the add button from the 2nd collection form will have his prototype replaced, but the two \_\_name\_\_ occurrences will be replaced by the count of the first collection form.
It will prevent the user from adding multiple items after clicking on the first collection form add button.
Because the inputs form from the 2nd collection have the same names.

It should replace only the first \_\_name\_\_.
https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-form-collection.js#L48

**Possible Solution**  
Here how sonata fixed the problem:
https://github.com/sonata-project/SonataAdminBundle/commit/0d3c6ea55623e059e71a4838c43017da1daaf3ae

**Comment by wadjeroudi** [comment]
@pamil if the sonata solution is OK for you, I can do the PR.

**Comment by vic-blt** [comment]
I'm currently using Sylius 1.7 and I have the same issue.

### Here's how I fixed the issue :

- Set the option `prototype_name` for your CollectionType element in your `buildForm` method.
- Create a .twig file which inherits theme.twig and overrides `collection_widget` block :
https://github.com/Sylius/Sylius/blob/b9b91ccb17696f840b5b3e224eb24069d104fb34/src/Sylius/Bundle/UiBundle/Resources/views/Form/theme.html.twig#L79-L112
```diff
87c87,88
<                 data-prototype='{{ self.collection_item(prototype, allow_delete, button_delete_label, '__name__')|e }}'
---
>                 data-prototype='{{ self.collection_item(prototype, allow_delete, button_delete_label, prototype.vars.name|default('__name__'))|e }}'
>                 data-prototype-name='{{ prototype.vars.name|default('__name__') }}'
94c95
<                     <input type="hidden" data-form-prototype="{{ key }}" value="{{ self.collection_item(subPrototype, allow_delete, button_delete_label, '__name__')|e }}" />
---
>                     <input type="hidden" data-form-prototype="{{ key }}" value="{{ self.collection_item(subPrototype, allow_delete, button_delete_label, subPrototype.vars.name|default('__name__'))|e }}" />
```
- Use the new twig theme with `form_theme`
- Create a copy of sylius-form-collection.js and change `addItem` method :
https://github.com/Sylius/Sylius/blob/b9b91ccb17696f840b5b3e224eb24069d104fb34/src/Sylius/Bundle/UiBundle/Resources/private/js/sylius-form-collection.js#L43-L54
```diff
46a47
>     let prototypeName = new RegExp(this.$element.data('prototype-name'), 'g');
48c49
<     prototype = prototype.replace(/__name__/g, this.count);
---
>     prototype = prototype.replace(prototypeName, this.count);
```
- Import the new js file in admin-entry.js and compile webpack

So I think `__name__` should not be hardcoded but instead use the `prototype_name` value.
