### ISSUE TITLE
Add a collection form after page is initialized

### ISSUE THREAD

**Issue by hmonglee** [Sylius/Sylius#9749]
**Sylius version affected**: 1.2.6

**Description**  
For example, you have many calculator for shipping charges. Each calculator have collection form type, so when you switch between calculator, the "Add" button won't work because he appears after the "$(document).ready". Only the first displays will work because he is initialized.
I take an example with shipping charges but it will affect all collection form.

**Steps to reproduce**  
 - Create a calculator with collection form type (allow_add => true)
 - Add a shipping method
 - Switch to the new calculator
 - Click in "Add"
 - Nothing will appear

**Possible Solution**  
https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver ?

**Comment by Tomsgu** [comment]
This is still a problem in sylius 1.8.7.
