### ISSUE TITLE
Broken "edit" link

### ISSUE THREAD

**Issue by dunglas** [Sylius/Sylius#9753]
The current edit link on the website is broken and points to a 404 error.

**Comment by CoderMaggie** [comment]
@dunglas any screenshots? Which website? Which page exactly?

**Comment by dunglas** [comment]
@CoderMaggie https://docs.sylius.com/en/1.2/api/introduction.html

Then click on:
<img width="163" alt="capture d ecran 2018-10-02 a 10 51 36" src="https://user-images.githubusercontent.com/57224/46338711-30400800-c631-11e8-863b-00000ea52827.png">

**Comment by lchrusciel** [comment]
seems to work right now

**Comment by pamil** [comment]
Indeed it works!
