### ISSUE TITLE
Improvement proposal for shipments

### ISSUE THREAD

**Issue by prigal** [Sylius/Sylius#9773]
_This proposal come from real experience. We are actually migrating a quite big ecommerce store to Sylius. We will probably do all this work on our side before anything will be decided or done in core, but I think this can be a common problem so I share our thoughts to give and get some feedback to improve Sylius_ 

**Describe the problem**
Actually, we have N shipments per order (shipment.order_id) and we know in the end which unit is attached to which shipment through order_item_unit.shipment_id. This doesn't allow us to have units from order A and units from order B in same shipment.

On a small ecommerce website it's not really a problem, but when you have hundreds/thousands orders a day and you want to reduce your shipment cost, you're going to group your delivery not per order but per shipping address. 

**Describe the proposed solution**
We should remove the direct link to order in shipments and keep only link between units and shipments. This way we can have a shipment that hold items from several orders.

Then we should directly attach delivery address to each shipment (not to order). 

Having delivery address attached to shipment will also enable a feature for shop users : delivering items in same order to different addresses. It's a common pattern in B2B stores. 

**Additional context**
About grouping orders.
We need to keep duplicated address in address book for each shipment even if they are the same because we can edit them per shipment later if customer contact us before shipping. 

To enable grouping when it's time to print the label, we will use a address book hash. This way, in the factory, grouping is done thanks to the hash (get all shipment with same address book hash) not thanks to shipment foreign keys to address book entry. _(hash will be a field updated on each address book update that will hash all fields used for the label)_

When the grouping has been decided we update all units.shipment_id of order A and B (and C...) so they are all linked to same shipment.

_NB: the hash thing is maybe something more particular to our needs and does not really have its place in core._

**To go further**
Carriers don't really track shipments but packages. They bill us shipments (based on destination, delay, weight and number of package) but they really track packages. 

If we want to model this, we should have a shipment_package entity linked to shipments (N packages for 1 shipment). The tracking number will be on shipment_package and not on shipment.

We should also add a state machine to shipment_package, because a shipment is really complete when all packages are really delivered.

If we introduce the shipment_package, we should in the end link units to packages, so when a package is lost, shop owner know which set of units has been lost and won't be forced to ship the whole order again.

**Comment by Zales0123** [comment]
Hello @prigal and sorry for the long response time.

Your proposal is great and seems like a very useful feature for some shops. However, we should still think about Sylius as an e-commerce framework rather than the out-of-the-box solution for everything. Therefore, I think it would be great to have such a big bunch of features as a Sylius plugin. We will just not be able to provide something like this in the nearest future to Sylius Core :) 

Thank you for contributing to the community! 🖖
