### ISSUE TITLE
[RFC] Promotion usage count locking mechanism

### ISSUE THREAD

**Issue by bburnichon** [Sylius/Sylius#979]
In project I'm in charge of, I need to ensure proper promotion usage count.

My problem, there are many orders placed at the same time on server. So, there is a chance the following situation happens:
- promotion1 is persisted in database with usage equals to 0.

First php request:
- promotion1 get used by order1. Doctrine loads promotion1 from database and increment usage. So usage yields now 1.

Second php request, with a different process:
- promotion1 get also used by order2. Doctrine loads same promotion1 (with usage still at 0). Its usage also yields 1.

At the end of the 2 requests, promotion usage is persisted at 1 instead of 2.

How would you tackle this issue? I did not see anything related to locking in whole project.

I think this locking issue could appear at many places, not only with promotion usage

**Comment by patrick-mcdougle** [comment]
#2776 has more info about this.
