### ISSUE TITLE
Overriding templates from Sylius bundles does not work

### ISSUE THREAD

**Issue by bitbager** [Sylius/Sylius#9802]
**Sylius version affected**: 1.3.0

**Description**  
Overriding templates from Sylius bundles does not work. 

**Steps to reproduce**  
After I create a file under `templates/bundles/SyliusShopBundle/Homepage/index.html.twig` path and I change the content to blank, I still get the Sylius vendor's homepage index template rendered. The weird thing is that overriding templates from Twig bundle (exceptions) works fine.

**Possible Solution**  
I think this might have something to do with the old templates structure, custom namespaces or theme loader for Sylius bundles.

**Tip**
If I remove the core template from vendor, then the custom template from `templates/bundles/Homepage/index.html.twig` is loaded. It seems like the vendor has a higher priority than the app. 
Might seem obvious, but the bug was detected on Sylius-Standard and replicated in the PluginSkeleton.

**Comment by pamil** [comment]
Related to #9719 and #8929.

**Comment by bitbager** [comment]
Guys, I really need it. Do you have any clue how to fix it? I can provide a PR 😄

**Comment by pamil** [comment]
I'm on it, it's broken by ThemeBundle logic. If you don't use ThemeBundle, there's a hotfix how to disable it for templates: https://github.com/Sylius/Sylius/issues/7491#issuecomment-379301391

**Comment by bitbager** [comment]
Thanks Kamil. I just debugged it quickly and it seems that the `$file = $this->templateLocator->locate($template)` in `ThemeFilesystemLoader` (line 120) points to a wrong location. This means that TemplateFileLocator's locate method should be updated. I hope that helps somehow.

**Comment by pamil** [comment]
#9804 should fix this one.
