### ISSUE TITLE
Deleting zones which are already used should not be possible

### ISSUE THREAD

**Issue by mmenozzi** [Sylius/Sylius#9808]
**Sylius version affected**: 1.3.0

**Description**  
Currently is possible to delete zone even if them are already used by shipping methods or tax rates. It shouldn't be allowed.

**Steps to reproduce**  
1. Create a zone
2. Create a shipping method for that zone
3. Delete the zone
4. I'd expect to be notified that I couldn't delete that zone but instead the zone is deleted.
5. Go to the shipping methods list and notice the error `Error: Method Proxies\__CG__\Sylius\Component\Addressing\Model\Zone::__toString() must not throw an exception, caught Doctrine\ORM\EntityNotFoundException: Entity of type 'Sylius\Component\Addressing\Model\Zone' for IDs id(37) was not found` (in dev/test env)

**Possible Solution**  
We can check if the zone is already in use before deleting it. What do you think?

**Comment by stefandoorn** [comment]
Isn't there a foreign key preventing this?

**Comment by mmenozzi** [comment]
I don’t think so because if there was you wouldn’t have that behavior.

**Comment by tom10271** [comment]
Is this fixed? I saw there is a foreign key constraint in sylius_shipping_method table in 1.5.2
