### ISSUE TITLE
Can't delete product option value

### ISSUE THREAD

**Issue by ChafikHadjAbdouRazack** [Sylius/Sylius#9820]
**Sylius version affected**: 1.1.10

**Description**  
Can't delete product option value

**Comment by CoderMaggie** [comment]
@ChafikHadjAbdouRazack How to reproduce this issue? 
Please provide any more details and then reopen if still valid.

**Comment by CoderMaggie** [comment]
@ChafikHadjAbdouRazack How to reproduce this issue? 
Please provide any more details and then reopen if still valid.
