### ISSUE TITLE
web hosting how install it?

### ISSUE THREAD

**Issue by langziyang** [Sylius/Sylius#9831]
**Sylius docs version**: 1.x / latest

**Description**
<!-- Describe what is missing or where exactly is the bug/typo/issue located. Links highly appreciated. --!>

i see the install doc,must use composer or other cli,so web hosting how install it?

**Comment by Zales0123** [comment]
Hello @langziyang and welcome to the community! **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our Slack (preferred) or [forum](https://forum.sylius.com/) ;) We have a very active, developed community, I'm sure someone will be able to help you with your problem. Good luck :)
