### ISSUE TITLE
How customization association?

### ISSUE THREAD

**Issue by LusenkoSasha** [Sylius/Sylius#9835]
How customization ProductsToProductAssociationsTransformer ?

**Comment by Zales0123** [comment]
Hello Sasha and welcome to the community! **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our Slack (preferred) or [forum](https://forum.sylius.com/) ;) We have a very active, developed community, I'm sure someone will be able to help you with your problem. Good luck :)
