### ISSUE TITLE
Admin Api Adjustment create not working

### ISSUE THREAD

**Issue by Keloo** [Sylius/Sylius#9846]
**Sylius version affected**: 1.1

**Description**  
When I try to do a post request to: `/api/v{version}/orders/{orderId}/adjustments/`
 I get: 
`{
    "code": 500, 
    "message": "Class \"form\" is not configured for resource \"sylius.adjustment\"."
}
`

**Steps to reproduce**  
Just get an access token and try to: `http -f post api/v<version>/orders/<order_id>/adjustments/ 'Authorization: Bearer <acces_token>`

**Comment by pamil** [comment]
Does this issue occur in a supported Sylius version (1.2+)?
