### ISSUE TITLE
sylius:theme:assets:install is using old structure 

### ISSUE THREAD

**Issue by alekseyp** [Sylius/Sylius#9848]
**Sylius version affected**: 1.3.1

**Description**  
`sylius:theme:assets:install` copies all assets to web folder instead of public folder

**Steps to reproduce**  
Create new theme
run `bin/console sylius:theme:assets:install` 
check for newly created `web` folder and no new files in `public` folder.

**Possible Solution**  
Current workaround is to specify `public` when running assets:install command as `bin/console sylius:theme:assets:install public`

**Comment by pamil** [comment]
Duplicate of #9849.
