### ISSUE TITLE
sylius:theme:assets:install using old structure

### ISSUE THREAD

**Issue by alekseyp** [Sylius/Sylius#9849]
**Sylius version affected**: 1.3.1

**Description**  
`bin/console sylius:theme:assets:install` copies asset to web folder instead of new public folder.

**Steps to reproduce**  
Create new theme
run `bin/console sylius:theme:assets:install`
Check for newly created `web` folder with all the assets
Check that no assets were added to `public` folder.

**Possible Solution**  
As workaround, even if It's not mentioned in the docs - you can add `public` parameter to copy assets to the right place. Running `bin/console sylius:theme:assets:install public` will copy everything to `public` folder.

I'm pretty sure that's not a desired behaviour, and it should work by simply running `bin/console sylius:theme:assets:install`

**Comment by pamil** [comment]
This is an expected behaviour, since changing that would be a BC break for anyone using the old structure. All we can do is to keep the docs updated with the new version.

**Comment by alekseyp** [comment]
Sorry for two issues.

Ok, so you suggesting to only update docs and show both options for now?

**Comment by wadjeroudi** [comment]
@pamil couldn't it be auto detected ?

**Comment by alekseyp** [comment]
Or shouldn't it just use `sylius_core.public_dir`?

**Comment by pamil** [comment]
Could you open https://github.com/Sylius/SyliusThemeBundle/pull/3 to Sylius/Sylius repository? SyliusThemeBundle is read-only. ThemeBundle is at `src/Sylius/Bundle/ThemeBundle`.

**Comment by alekseyp** [comment]
@pamil done.
