### ISSUE TITLE
Documentation on Shipping component refers to non-existent Rule class

### ISSUE THREAD

**Issue by tybw** [Sylius/Sylius#9855]
**Sylius docs version**: 1.x / latest

**Description**

Documentation for Shipping component states that there is a Rule class, but the class could not be found in the stated location.

The concerned documentation pages:
1. https://docs.sylius.com/en/latest/components_and_bundles/components/Shipping/models.html
2. https://docs.sylius.com/en/latest/components_and_bundles/components/Shipping/basic_usage.html

**Comment by devdrops** [comment]
@tybw @CoderMaggie working on it :wink:

**Comment by devdrops** [comment]
BTW, any plans on changing the http://api.sylius.com/Sylius/Component/Shipping/Model/Rule.html reference?
