### ISSUE TITLE
Admin Product image widget variant selector does not get any result

### ISSUE THREAD

**Issue by lccimat** [Sylius/Sylius#9867]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | ?
| RFC?             | no
| Sylius version   | 1.3.1

Hi,
I'm new here on sylius github and enjoy sylius for almost 1 year now (and love it).

I face an issue with image variant selector in product edit page.
My user has fr_FR language selected and the locale returned by sylius.context.locale::getLocaleCode() is "fr".
Translations are saved with fr_FR code.

The problem I face is in ProductVariantRepository::findByPhraseAndProductCode().
the innerJoin is done by "=" condition but "translation.locale" contains "fr_FR".

I tested following code in ProductVariantRepository::findByPhraseAndProductCode() and this solved my problem : will both join translation on "fr" and "fr_FR".
```
->innerJoin('o.translations', 'translation', 'WITH', 'translation.locale LIKE :locale')
...
->setParameter('locale', $locale.'%')
```

But I don't think the issue comes from here.
This function is only used by image widget variant selector.  

As I want to reference a variant on an image, why should I get results only based on my current locale and not all locales of the variant name ?

Thank you for answering.
Regards

**Comment by pamil** [comment]
Could you make sure that your administrator has `fr_FR` locale selected?

**Comment by matthiez** [comment]
This just happened to me too.
For a variant to show up it must be translated in the admin users locale.
I don't think it's supposed to be like that.
