### ISSUE TITLE
Be able to manipulate resources in ResourceController with event

### ISSUE THREAD

**Issue by maximehuran** [Sylius/Sylius#9869]
## Context

I want to change the categories on the horizontal menu.
The controller `sylius_shop_partial_taxon_index_by_code` is called and use `ResourceController::indexAction` method.
I can listen the event but cannot modify the returned taxons.

## Solution 

`Sylius\Bundle\ResourceBundle\Controller\ResourceController` on line 222
```php
$this->eventDispatcher->dispatchMultiple(ResourceActions::INDEX, $configuration, $resources);
```

We can retrieve the object and set the resource from the event subject : 
```php
$event = $this->eventDispatcher->dispatchMultiple(ResourceActions::INDEX, $configuration, $resources);
if ($event->hasArgument('subject')) {
    $resources = $event->getArgument('subject');
}
```

The `subject` string must be in constant for sure.

With this change, I can do some stuff in my custom event (listening `sylius.taxon.index`) : 
```php
$subject = $event->getSubject();
// Your custom logic
$event->setArgument('subject', $subject); // Use the constant instead of 'subject' string
```

## Question

It's sure we cannot do this change without check what are the impacts on the solution.
Maybe I think bad and my idea is not relevant.
But the question is simple, and may be asked for all events we can have : 
- Have we got to be able to manipulate event subject, to customize the logic without do some rewrites ?

I'm free to discuss about this idea and it could be interesting to think about that together.

**Comment by pjedrzejewski** [comment]
I would lean towards a solution with a custom repository method and defining your own routing for this partial action, inspired by the one included in the default shop. These controller events are more suitable for redirecting or modifying the response contents.

**Comment by maximehuran** [comment]
Yes this is how I did in order to manage my problem. 
I totally understand the goals of these controller events ^^
Thank you for the reply
