### ISSUE TITLE
[ Promotion ] Shipping discount

### ISSUE THREAD

**Issue by jvahldick** [Sylius/Sylius#988]
Hello,

The shipping discount is not being applied. 
The listener is being called at the address, I think it should be called on choice of shipping method , however this way there will probably be conflicts with the coupons.

When call listener at address, the total of shipping returns 0 because the shipping method was not selected yet..

**Comment by michalmarcinkowski** [comment]
That is already fixed see feature files, e.g. [percentage discount on shipping](https://github.com/Sylius/Sylius/blob/master/features/promotion/receiving_percentage_discount_on_shipping.feature).
