### ISSUE TITLE
Platfrom.sh deployment doesn't work with Symfony 4

### ISSUE THREAD

**Issue by lchrusciel** [Sylius/Sylius#9881]
Ref: https://github.com/Sylius/Sylius/issues/9861#issuecomment-433538103

**Comment by pamil** [comment]
I have fixed it in https://github.com/Sylius/SyliusDemo/pull/59/files#diff-a01ecef7a6e131049fbe7c316a819f8a on our demo, it triggers some errors but it works in the end. Let's keep the discussion there if there's any other, better solution.
