### ISSUE TITLE
Unused FriendsOfBehat Page Object Extension 

### ISSUE THREAD

**Issue by loic425** [Sylius/Sylius#9886]
**Sylius version affected**: at least 1.3.2 

**Description**  

This extension is on dev dependencies but it's not used. Page, PageInterface and UnexpectedPageExtension still be on sylius and same objects from the behat extension are not used yet.

**Steps to reproduce**  

**Possible Solution**  

Remove duplicated objects on sylius and use this behat extension objects :)

Moreover, on sylius, there's more "phpdoc" on these objects, I think it has to be improved on the extension objects.

**Comment by Zales0123** [comment]
Totally agreed, we should use the extension, it was one of the reasons to extract it 👍

**Comment by loic425** [comment]
I've made a pull request on behat extension to extract phpdoc from sylius duplicated objects
https://github.com/FriendsOfBehat/PageObjectExtension/pull/6

**Comment by Zales0123** [comment]
It's solved since merging #9887, thank you, Loïc, one more time 🎉
