### ISSUE TITLE
[ShopBundle] Can't submit an order as customer with promotions

### ISSUE THREAD

**Issue by Roshyo** [Sylius/Sylius#9904]
**Sylius version affected**: 1.3.2 ans 1.3.3 for sure

**Description**  
In a cart, I have a promotion applied with the rule "20% for all the order". When I try to submit my order as a customer, I have this error thrown : `sylius.order.total_integrity`
After digging into the ShopBundle, I've found that in `Sylius\Bundle\ShopBundle\EventListener\OrderPromotionIntegrityChecker` When the promotions are checked for eligibility, the total order amount is not equal to the one before.

**Steps to reproduce**  
I'd say : 
Create an order
Apply promotion with "order_percentage_discount" action
Try to validate your order (with cash on delivery for example)

**Possible Solution**  
I have no idea, actually I've just disabled the check to allow customers to put their orders. The amount in the end is the right one.

**Comment by pamil** [comment]
Could you open a new issue if the issue occurs to be caused by Sylius?

**Comment by Roshyo** [comment]
Yeah, couldn't find the time to debug it yet. If the issue is caused by Sylius I'll do so.
