### ISSUE TITLE
Extened support for autowire of Doctrine Repository

### ISSUE THREAD

**Issue by Bonobomagno** [Sylius/Sylius#9905]
**Describe the proposed solution**
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository instead of Doctrine\ORM\EntityRepository
in (i suppose) Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
**Additional context**
Of course this would ask some other change in code.

This is further step on a modern framework support (symfony 3 e 4).
Useful feature for who started using symfony from 3 or even flex. In fact actual symfony doc are in major part unusable on sylius.

**Comment by pamil** [comment]
Could you shed some more light on how you are using the ResourceBundle? Have you registered a resource or using only the ResourceBundle's `EntityRepository`?

**Comment by Bonobomagno** [comment]
The problem is on the controller.
First, you need to disable autowire for resource controller istances, 
Second, no way to use controller annotation. So you need to switch to AbstractController.

But now you don't have access to sylius container service anymore, so DI is needed. The problem is that if you try to use autowire, the Entity will give you error

`Cannot autowire service "App\Repository\XXX": argument "$class" of method "Doctrine\ORM\EntityRepository::__construct()" references class "Doctrine\ORM\Mapping\ClassMetadata" but no such service exists.`

 because it extend EntityRepository instead of autowire compatible one: ServiceEntityRepository.

Ofc you can try wire all by hand, but where is the advantage of  using symfony 4??
