### ISSUE TITLE
Promotion priority description

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#9907]
**Sylius docs version**: 1.x / latest

**Description**
The [Promotions](https://docs.sylius.com/en/1.3/book/orders/promotions.html#promotions) documentation should describe how the priority works. Is larger number a greater priority?

**Comment by pamil** [comment]
Promotions with higher priority get resolved first. Larger number = higher priority. Would you be willing to create a PR with a fix to the 1.2 branch?
