### ISSUE TITLE
Too much dependencies for sylius/taxation-bundle

### ISSUE THREAD

**Issue by soullivaneuh** [Sylius/Sylius#9911]
I would like to try an integration of Sylius for an existing project. We don't need a full ecommerce project but we would like to delegate the billing system to your components.

So I started with `sylius/taxation-bundle` which require `sylius/resource-bundle`.

Why not, it look like a core to me.

But now I have some fancy new bundle like `JMSSerializerBundle`, `BazingaHateoasBundle` and `WhiteOctoberPagerfantaBundle`. Problem: I don't use any of them for my goal of my initial require: Calculating taxes. Plus, it looks like they are not mentioned on the taxation-bundle documentation.

There is certainly no issue when you install Sylius full stack, but it's proposed as separated component/bundle, some dependencies relation should be reviewed.

What do you think?

**Comment by vvasiloi** [comment]
Use only the taxation component then: https://github.com/Sylius/Taxation.

**Comment by Soullivaneuh** [comment]
@vvasiloi If I do this, I will lose part of the Symfony bridge, starting by the services.

Still, it requires the `sylius/resource` package and with it some packages I don't need like `pagerfanta/pagerfanta`.

**Comment by Roshyo** [comment]
ResourceBundle is definitely needed for TaxationBundle since TaxCategories/Rates are Resources.

And since ResourceBundle is aimed to produce an API and HTML lists, JMS, Hateoas and Pagerfanta are needed.

So I don't think t's a good idea to remove those from dependencies, or else ResourceBundle will simply become an empty shell.

**Comment by Soullivaneuh** [comment]
Right, I didn't say to just remove resource bundle.

But maybe ResourceBundle can be split onto lighter parts.

**Comment by Soullivaneuh** [comment]
Because cleary, I just did an integration following the doc. It works well, and I didn't use any of the three installed packages quoted at the beginning of the issue.

**Comment by pamil** [comment]
I'm afraid that splitting ResourceBundle would result in a lot of work and possible BC breaks and we don't have enough time for that now. We're aware of such an issue and we'll keep it in mind while making plans for 2.0.

**Comment by Soullivaneuh** [comment]
Thanks @pamil,

Any 2.0 roadmap I can found on github? Any branch to start contributing? I see master is right now for 1.4.

**Comment by soullivaneuh** [comment]
IMHO this issue is still accurate.
