### ISSUE TITLE
[taxation-bundle] Configuring taxation do not rely all mandatory field

### ISSUE THREAD

**Issue by Soullivaneuh** [Sylius/Sylius#9913]
On this page: https://docs.sylius.com/en/1.3/components_and_bundles/bundles/SyliusTaxationBundle/configuring_taxation.html#configuring-the-tax-rates

The `code` and `calculator` fields are not present on the code sample.

But it can't works like this, the fields are required by Doctrine.

And by the way, we can't know what `calculator` field means at this state.

**Comment by pamil** [comment]
Could you open a PR with a fix? We're currently working on documentation rework, but it'd take some time so it would be great to have these docs up-to-date.
