### ISSUE TITLE
Order processor documentation incomplete

### ISSUE THREAD

**Issue by mikemix** [Sylius/Sylius#9924]
**Sylius docs version**: *

**Description**
The [documentation about order processors](https://docs.sylius.com/en/1.3/components_and_bundles/components/Order/processors.html) is incomplete. Given example ends up with the 500 sql exception:

> An exception occurred while executing 'INSERT INTO sylius_adjustment (type, label, amount, is_neutral, is_locked, origin_code, created_at, updated_at, order_id, order_item_id, order_item_unit_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [null, null, 0, 0, 0, null, "2018-11-13 18:52:08", "2018-11-13 18:52:08", 16, null, null]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'type' cannot be null

**Comment by Zales0123** [comment]
Indeed, `type` is also required 👍 It would be also nice to set some `label` in the example. Could you, please, open a PR with the documentation change? It would be great :)

**Comment by Zales0123** [comment]
Documentation is marked as outdated, but it still would be good to have it fixed 😄
