### ISSUE TITLE
Parameters.locale conflicts with channels without the specified locale

### ISSUE THREAD

**Issue by Peteck** [Sylius/Sylius#9925]
**Sylius version affected**: < 1.3

**Description**
So I was creating some channels that won't use the locale specified in `parameters.locale` and stuff started breaking.

So far I've found that the web debug toolbar breaks.

**Steps to reproduce**  
- Set `parameters.locale` to some locale
- Use a channel without the specified `parameters.locale`

**Possible Solution**  
Make a `parameters.locale` follow the locale context. This was the behavior of 1.2.

**Comment by pamil** [comment]
Could you send us some screenshots or the error messages that you get? Also, the specific setup you are using would be helpful.

**Comment by Peteck** [comment]
![v1_3_locale_problem](https://user-images.githubusercontent.com/1520592/48557183-55898c80-e8e6-11e8-8e62-82f37f3a54e2.jpg)
This is the response of the web debug toolbar when `parameters.locale` is set to `en_US` and I'm on a channel without `en_US` as a locale.

**Comment by Peteck** [comment]
Updated description because I seem to not having problems with `path()` anymore. I don't know what might have went wrong there. I'll report back if I'll experience the issue again.

**Comment by Zales0123** [comment]
<img width="1440" alt="zrzut ekranu 2018-11-15 o 15 49 37" src="https://user-images.githubusercontent.com/6212718/48560439-16f7d000-e8ee-11e8-9cfe-890be3e6cd8c.png">

Just checked it on `1.2` and it indeed seems to be an issue.

**Comment by Peteck** [comment]
This issue was fixed with pull request #9975
