### ISSUE TITLE
Infinite loop in Payum afterCaptureAction

### ISSUE THREAD

**Issue by tautelis** [Sylius/Sylius#9928]
**Sylius version affected**: 1.x

**Description**  
We had server down due to memory leak when requesting after-pay website. After debugging I found that it was caused by this particular extension getting into infinite loop:

https://github.com/tautelis/Sylius/blob/8f4542a2744aada6d66d93e259a09370d2b67829/src/Sylius/Bundle/PayumBundle/Extension/UpdatePaymentStateExtension.php#L93

The problem is that if `updatePaymentState` method throws an exception `onPostExecute` method is called once again.

**Steps to reproduce**  
1. Screw u you state machine.
2. Go to `sylius_shop_order_after_pay` page

**Possible Solution**  
Catch if context has an exception.

**Comment by Zales0123** [comment]
Nope https://github.com/Sylius/Sylius/pull/9931#issuecomment-465909593
