### ISSUE TITLE
MailerBundle should use configuration so multi-language support is easy to implement

### ISSUE THREAD

**Issue by leroy0211** [Sylius/Sylius#9930]
**Describe the proposed solution**

MailerBundle comes with some configuration options which don't work or have less implementation than expected. The configuration option `sylius_mailer.emails.[code].subject` doesn't work when using Twig files. The Twig file needs a `subject` block which overrules all. However, when the `subject` configuration is not applied a warning will be logged. 

The option that has less implementation than expected is the `sylius_mailer.emails.[code].template`. First of all Twig Globals are merged which can cause other Twig globals from Symfony itself (which have the same name) to be overwritten. For example `app` is such a global. 

**Describe alternatives you've considered**
Fully implemented the subject and template (or content) configuration option so these options can either be altered or otherwise translated the way we want. I think, looking at the code and [documentation](https://docs.sylius.com/en/latest/components_and_bundles/bundles/SyliusMailerBundle/your_first_email.html), the `subject` key was meant to be a configurable and translatable option, but didn't made it.

What I expect from the `sylius_mailer.emails.[code].subject` key is that this is just a translatable label, which can be translated through translation files. 
What I expect from the `sylius_mailer.emails.[code].template` key is that this is a path to the template you wish to send to the user, which doesn't expect to have a `subject` and `body` block ( since that is configured already) but extend/implement just a normal mail template.

**Additional context**
What I think of is someone wanted to set the subject of an email in a template, but came up with the idea to configure it in the configuration but forgot to remove it from the templates.

If that has been created, the next step to load emails from the database isn't such a hard thing to do because the Email Component already knows about content as a string, and handles this differently than a template.

**Comment by mamazu** [comment]
Sounds like a good suggestion. However where does the locale come from when you are using a translatable configuration. Do you have to pass it into the Email Provider or does it take the default locale of the current channel?

**Comment by leroy0211** [comment]
I would suggest to take the locale of the current channel. 

May an idea is to create a `UserMailInterface`, and when implemented on the User object the user can specify in which language he/she want's to be contacted. If that interface is not implemented on the User object, just fallback to the locale of the current channel. 

This way e-mails can also be sent with a different delivery system. So a worker can spool the mails in the correct language.

**Comment by mamazu** [comment]
Sounds like a great idea. This might be a problem when sending newsletters as they too have to be translated into many different languages. But it would be good to have the possibility to customize the language for default emails for example.
