### ISSUE TITLE
Show payment status in order history

### ISSUE THREAD

**Issue by jdeveloper** [Sylius/Sylius#9933]
When a user broweses order history and views the details of the order, there is no way to see the payment status. Consider you fullfilled an order and payed but then the payment was refunded. There is no way to see that the payment is refunded.

Here is a screenshot of an order that has a refunded payment and in red where I suggest to put the state label of the payment.

![order-status](https://user-images.githubusercontent.com/8874/48705528-a73d5a00-ebf9-11e8-8aee-0503467a2288.png)

**Comment by Chrysweel** [comment]
Great idea !

Many customers to see your history do not know if you have made the return
