### ISSUE TITLE
Method to get products with discount

### ISSUE THREAD

**Issue by jdeveloper** [Sylius/Sylius#9936]
It would be very nice to have a method in ProductRepository to get all products in offer (pricing < originalPricing). This way it could be easy to make a page with only products in offer.

**Comment by mamazu** [comment]
Sounds easy to implement and useful for a category "on sale".

**Comment by CoderMaggie** [comment]
Hi there!
We are planning to add this feature one day, when implementing the Catalog Promotions (as a Plugin).
I suppose the catalog promotions would be a much better place to solve your scenario. But hence it is not in development yet, I can suggest you to do a customization inside your app instead.

Feel free to reopen if you need sth more. 👋
