### ISSUE TITLE
sylius:theme:assets:install fails since 1.3.4

### ISSUE THREAD

**Issue by leonboot** [Sylius/Sylius#9939]
**Sylius version affected**: 1.3.4

**Description**

Running the `sylius:theme:assets:install` command fails:

> In AssetsInstallCommand.php line 83:
>
>   Type error: Return value of Sylius\Bundle\ThemeBundle\Command\AssetsInstallCommand::getTargetDir() must be of the type string, null returned 

**Steps to reproduce**

Run `bin/console sylius:theme:assets:install` without the target argument in a Sylius 1.3.4 installation.

**Possible Solution**  

I've made a comment on the commit that introduced the issue: https://github.com/Sylius/Sylius/commit/1a1e312eb4a757e655fc261c6798b5fca08e54bc#r31364077

**Comment by lchrusciel** [comment]
I guess we can finally close it! 🎉 Thanks @alekseyp and Leon! 🐋

**Comment by leonboot** [comment]
Finally? I wish I'd see this turnaround on other projects 😄 Nice going, @alekseyp! 💪
