### ISSUE TITLE
[Payment] Invalid Process Transition

### ISSUE THREAD

**Issue by frederic9583** [Sylius/Sylius#9941]
**Sylius version affected**: latest

Hey guys,

https://github.com/Sylius/Sylius/blob/3b9837b6636ef56ed9e885d04cace9df96c36ba1/src/Sylius/Bundle/CoreBundle/Resources/config/app/state_machine/sylius_payment.yml#L20-L22

As you can see here the `process` transition in `sylius_payment` only allows a transition from `new` to `processing`. There is no way to change it after a payment has changed from `new` to `authorized` or to any other state, see my two examples below:

## I. Process on Checkout
If i'm going to set the payment state to `process` in a checkout process (StatusAction), the customer will always fall back to the payment selection, as you can see it here:

https://github.com/Sylius/Sylius/blob/3b9837b6636ef56ed9e885d04cace9df96c36ba1/src/Sylius/Bundle/PayumBundle/Action/ResolveNextRouteAction.php#L32-L44
 
-> No use-case here.

## II. Change Payment State
Changing a payment with `markSuspended` or `markPending` later on (NotifyAction for example) is also impossible (see first snippet above).

-> No use-case here.

Am i missing something here? Thanks!

**Comment by Zales0123** [comment]
Hello @frederic9583, could you please share some more info about your use-case? Is there anything you cannot achieve with a state machine configuration customization? Of course, payum-related customizations can be hard to proceed, but we need more light to be able to help you :)
