### ISSUE TITLE
Suggestions drop down for Search Bar

### ISSUE THREAD

**Issue by Vinit-Koshti** [Sylius/Sylius#9944]
**Describe the proposed solution**
See the image to understand better:
[https://cdn.baymard.com/research/media_files/attachments/17029/original/research-media-file-b8ea5f7b83a419d6b987ce0d4400096e.jpg](url)

**Simple Search Suggestions as per the products in the database**

**Comment by CoderMaggie** [comment]
This can be solved by the integration of ElasticSearch - see the plugin: https://github.com/BitBagCommerce/SyliusElasticsearchPlugin

**Comment by Vinit-Koshti** [comment]
https://github.com/BitBagCommerce/SyliusElasticsearchPlugin installation instruction is not updated, though installed SyliusElasticsearchPlugin successfully but sylius still using default doctrine/orm based search

**Comment by CoderMaggie** [comment]
Then please open an issue on the plugin's repo or ask for help on our Slack :)
