### ISSUE TITLE
Removing an unused config option

### ISSUE THREAD

**Issue by mamazu** [Sylius/Sylius#9946]
Currently the mailer bundle has a configuration that is not needed `sylius.mailer.templates`

**Describe the proposed solution**
Deprecate and remove it.

**Describe alternatives you've considered**
I don't know what this is intended to do.

**Comment by Zales0123** [comment]
Indeed, this is the offspring of an old code refactoring, done billion years ago - https://github.com/Sylius/Sylius/pull/6708 :) 
Unfortunately, we cannot remove it as somebody can rely on this configuration - it should be deprecated and removed, as you've proposed. Are you willing to open a PR with such a change? Thanks :)

**Comment by mamazu** [comment]
Sure thing. However, I though about rewriting the whole module to add channel support.

**Comment by Zales0123** [comment]
It would for sure be nice, however, we need to think about BC promise 😕 Thank you for the PR 👍

**Comment by mamazu** [comment]
Well if you are intending to release 2.0 anyways then a BC break would be justifiable.
