### ISSUE TITLE
Erreur after registration

### ISSUE THREAD

**Issue by Ezar101** [Sylius/Sylius#9947]
After registration, I get redirect to the road _"/account/dashboard?id=42"_ and it sends back an error because the user is not activated or connected.
Can we change the redirection route after registration?
![capture d ecran 116](https://user-images.githubusercontent.com/29166550/48848717-b406ad00-edb5-11e8-805a-c044ac5b9901.png)

**Comment by CoderMaggie** [comment]
Hello @Ezar101 ;) 
**Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, like this support rquest, please, use our [Slack channel](http://sylius.org/slack) or [stackoverflow](https://stackoverflow.com/questions/tagged/sylius) ;)
