### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Channel could not be found! Tip: You can use the Web Debug Toolbar to switch between channels in development.").

### ISSUE THREAD

**Issue by christiankasse** [Sylius/Sylius#9948]
after my installation I just wrote this problem to me prevents me from working and am really blocking, please help

**Comment by mamazu** [comment]
You have to configure the URL for the default channel in the backend or manually set it in the debug toolbar because the current `ChannelResolver` could not determine the channel to use.

**Comment by mamazu** [comment]
Go to the admin pannel (usually under `/admin`) and click on channels and then edit the only channel you have and set the host to `localhost` or whatever URL you are using.

**Comment by christiankasse** [comment]
they said **No route found for "GET /en_US/admin"**

**Comment by christiankasse** [comment]
![screenshot from 2018-11-21 22-42-27](https://user-images.githubusercontent.com/26385000/48869814-d2cd6980-edde-11e8-9dbf-ac36f9bebea4.png)
![screenshot from 2018-11-21 22-42-32](https://user-images.githubusercontent.com/26385000/48869816-d2cd6980-edde-11e8-90f3-f82940d958f0.png)

**Comment by mamazu** [comment]
It's just `localhost:8081/admin`.

**Comment by christiankasse** [comment]
the second pincture present my first time when i was open my server to acced to the url

**Comment by christiankasse** [comment]
> It's just `localhost:8081/admin`.

Yes but no route it's link for this

**Comment by mamazu** [comment]
So this route does not exist?

**Comment by mamazu** [comment]
Then try to set it manually in the debug toolbar. (The bar at the bottom). There is a red field with two arrows that cross each other and after that it says "Undefined". Hover over it and then a menu will pop up with one other channel. Click on the "change" link next to the name.

**Comment by christiankasse** [comment]
but before that I first have to do the migrations after loading the fixtures but I can not and it cuts on the way saying saying   **Root image path not resolvable "/var/www/html/tinda/public/media/image"**

**Comment by mamazu** [comment]
The usual workflow is migrations first then the data fixtures.

**Comment by christiankasse** [comment]
it's said **No migrations to execute.**

**Comment by christiankasse** [comment]
![screenshot from 2018-11-21 23-00-21](https://user-images.githubusercontent.com/26385000/48870454-3d7fa480-ede1-11e8-90c8-9402a9d5dc8a.png)

**Comment by christiankasse** [comment]
I do not know if you understand me, after I download the project with the explanation of the documentation I'm blocking because even if I just hope to do **php bin / console** I do not buy all the commands with this error message that is displayed to me; my first project sylius I downloaded it two months ago and it worked well but it has been 3 days that I do absolutely nothing
![screenshot from 2018-11-21 23-05-00](https://user-images.githubusercontent.com/26385000/48870643-e4fcd700-ede1-11e8-94d0-a6c9be2ea95e.png)

**Comment by mamazu** [comment]
Try to create the folder and then try again. I am going to bed now, but I'll have a look at it later. Good luck for now.

**Comment by christiankasse** [comment]
thank you I'm still trying

**Comment by CoderMaggie** [comment]
Hello @christiankasse ! 

**Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our [Slack channel](http://sylius.org/slack) or [stackoverflow](https://stackoverflow.com/questions/tagged/sylius) ;)

**Comment by christiankasse** [comment]
How can i résolvez that?
