### ISSUE TITLE
Remove `AppBundle` from docs.

### ISSUE THREAD

**Issue by Konafets** [Sylius/Sylius#9951]
**Sylius docs version**: 1.3 / latest

**Description**
The namespace `AppBundle` is still used in 1.3 docs. Even Symfony 4.x changed it to `App`. Remove or change it.

List of pages (not complete):

- https://docs.sylius.com/en/1.3/components_and_bundles/bundles/SyliusMailerBundle/your_first_email.html

**Comment by Zales0123** [comment]
Agreed 👍 Are you willing to open a PR about this improvement? :)
