### ISSUE TITLE
Adding form_help to theme UiBundle 

### ISSUE THREAD

**Issue by rachdi** [Sylius/Sylius#9953]
**Sylius version affected**: 1.3

**Description** 

Symfony was adding  form_help To form field

**Steps to reproduce**  

I can't define a help message for the form field, which by default is rendered below the field from symfony 4

https://symfony.com/doc/current/reference/forms/types/text.html#help

**Possible Solution**  
 Adding form_help to theme UiBundle  

{% block form_row -%}
    <div class="{% if required %}required {% endif %}field{% if (not compound or force_error|default(false)) and not valid %} error{% endif %}">
        {{- form_label(form) -}}
        {{- form_widget(form) -}}
        {{- form_errors(form) -}}
        {{- form_help(form) -}}
    </div>
{%- endblock form_row %}

**Comment by lchrusciel** [comment]
We would have to bump minimal Symfony version because this feature was added in Symfony 4, while we are supporting both Symfony 3.4 and Symfony 4.1.

What is more, affected should be master, as it is IMHO a new feature ;)
