### ISSUE TITLE
I cant login like an admin

### ISSUE THREAD

**Issue by christiankasse** [Sylius/Sylius#9954]
can I have the default login after installation to access the admin?

when i try to go to _`localhost:8000/admin`_ I am redirected to` / login` where I pass **sylius** whith password, I am denied access saying **ERROR Bad credentials.**

**Comment by CoderMaggie** [comment]
I'm sorry Christian, but Sylius issues should be used to report bugs, propose new features, discuss new functionalities. Please, use our [Slack channel](http://sylius.org/slack) there you will get help you're looking for much faster 😄 

You are probably using wrong credentials, during installation you are asked to provide your own credentials, therefore I cannot guess what you have provided.

**Comment by christiankasse** [comment]
I understand you but my installation was rough because nowhere have I been asked for something as long as after he has finished he has executed the cache and then it's finished

**Comment by CoderMaggie** [comment]
@christiankasse were you following this guide? https://docs.sylius.com/en/latest/book/installation/installation.html#initiating-a-new-sylius-project

**Comment by christiankasse** [comment]
I uses this guide

**Comment by christiankasse** [comment]
It's for 4 Time that i install my project

**Comment by CoderMaggie** [comment]
It happens during `$php bin/console sylius:install` command, the 3rd step:

![image](https://user-images.githubusercontent.com/13198869/48934354-f807c800-ef03-11e8-9b78-261dc1285317.png)

**Comment by christiankasse** [comment]
thank you very much for your help, by the way, I just noticed my problem was the timezone which block me at the first and I never go to the 3rd where I should do the configuration. Thank you very much
