### ISSUE TITLE
Product options not appearing in admin

### ISSUE THREAD

**Issue by magdkudama** [Sylius/Sylius#9960]
**Sylius version affected**: 1.3.4

**Description**  

When adding a product option, it doesn't appear on the list.

This is (probably) also causing my product list to be empty, even though I've added many.

**Steps to reproduce**  

Go to admin, create a new product option, and go back to the list of product options.

If I hardcode the URL for my product option, I can edit it without problems:

<img width="1163" alt="screenshot 2018-11-25 at 16 22 12" src="https://user-images.githubusercontent.com/1323130/48980842-74e69d80-f0ce-11e8-8a49-c298b50373bf.png">

When I'm in the product options list though:

<img width="1165" alt="screenshot 2018-11-25 at 16 22 18" src="https://user-images.githubusercontent.com/1323130/48980848-7f089c00-f0ce-11e8-9e2e-266f15c9d395.png">

**Possible Solution**  

I deleted the default US locale, and changed it with English (UK) and German, not sure if maybe US is required for the application to work?

**Comment by magdkudama** [comment]
Indeed, when I add en_US, it all works fine!

Is there a way to delete that language?

**Comment by magdkudama** [comment]
Oh, do you mean if I change that I could actually remove en_US from the DB if I changed the default locale?

Thanks!

**Comment by Zales0123** [comment]
Even though I don't recommend deleting anything from your database manually, this is more or less as you say. Feel free to reopen this issue if you have any more questions, or, and it's the best choice, join our [Slack](http://sylius.com/slack) and you'll find help there, for sure :)
