### ISSUE TITLE
Deleting shop user in admin might result in "Cannot remove currently logged in user."

### ISSUE THREAD

**Issue by AndreasA** [Sylius/Sylius#9969]
**Sylius version affected**: 1.3.4

**Description**  
If your admin user has the same ID as the shop user and you want to delete the shop user, you get the error "Cannot remove currently logged in user."

**Steps to reproduce**  
1. In the backend login with the default admin (ID: 1) and create one customer (ID: 1) and enable that customer for shop login (setting password, ...)
1. On the customer use "Show" and then "Delete"

This results in: "Cannot remove currently logged in user."

**Possible Solution**  
The issue seems to be that the `\Sylius\Bundle\UserBundle\EventListener\UserDeleteListener` only checks for the same ID but not if they are of the same type, so e.g. the listener is called and compared with the admin object.

**Comment by laurent35240** [comment]
I opened PR #9988 to fix this issue
