### ISSUE TITLE
[Roadmap] [Feature] App stores integration

### ISSUE THREAD

**Issue by jdeveloper** [Sylius/Sylius#9974]
I think it would be a great benefit for sylius to support app sotres integratios for payments. Google Play, Apple store, Amazon etc. 

Ideally is that we can be able to associate channels to the payment gateways for app stores support. I the moment the mobile app calls for paymente, it should automaticly create order, set it as completed and mark it as payed.

It also would be interesting to support renewals aka subscriptions. I know there once was a subscription bundle but old and maybe there is another one.

**Comment by jdeveloper** [comment]
a suggested library could be https://github.com/aporat/store-receipt-validator to validate recepts

**Comment by pamil** [comment]
I think the app stores integration should be resolved in a dedicated plugin (for each app store).

**Comment by Zales0123** [comment]
👍 for the plugins for now. We already have lot's of integrations with various payment providers (Adyen, Mollie, PayU etc.) and it can be done the same way. We should focus on a clear, e-commerce stuff in the main Sylius repo. Of course, such plugins would be a huge value for all community, so we would probably think of making them as visible as possible :)
