### ISSUE TITLE
Simulate payment of zero euros

### ISSUE THREAD

**Issue by Chrysweel** [Sylius/Sylius#9977]
We find that it is often useful to simulate a payment for zero euros.

Example:

You want to give something to a user, but you want the user to be able to see it in their shopping history.

Maybe a user who has had a problem with an order and you have to rebuild it at zero cost. Maybe a user who won a raffle and you want to give him a product ... maybe a user who has received a product late and you want to give him another ...

As administrator I want to be able to simulate a payment to a user for a value of zero euros.

Now there are two options:

Option A)
Create a promotion based on coupons. That only works for that particular product.
Create a coupon for that promotion.
Impersonate the user and make the purchase with that coupon. Or send him the coupon and let him do it.

Problem: I created a "useless" and very personalized promotion ...

Option B)

Simulate a payment by bank transfer or cash on delivery. Enter the administration and mark it as paid.

Problem: When you post the orders and euros of the ecommerce, that order will be counted. When I really have not entered any money.

The ideal is also to be able to put comments on the orders from the administration so that I can leave for future managers that purchase I have made for the reason X.

It is understood ?

**Comment by Chrysweel** [comment]
@CoderMaggie I see this issue in column "Feedback needed" https://github.com/orgs/Sylius/projects/2#card-15290333

Is any information missing or is it necessary to describe the problem in more detail?

**Comment by CoderMaggie** [comment]
@Chrysweel the feedback needed column is for issues that are awaiting votes from the community :)

**Comment by Chrysweel** [comment]
Ok @CoderMaggie ! Thanks for to reply! :)

**Comment by Chrysweel** [comment]
This issue is in voting to roadmap. 
https://github.com/orgs/Sylius/projects/2
