### ISSUE TITLE
[feature]media for payments and shipping

### ISSUE THREAD

**Issue by ibasaw** [Sylius/Sylius#9980]
hi,

On the demo online and in the admin didn't see an option to add a media (logo, icon) to shippings and payments item.

This will be use to the front to reassure customer with brands they know and use to see on others websites.

Will be cool to have it in the core.

In fact every items of content, or options of the core may have a media

++

**Comment by mamazu** [comment]
This is not hard to implement, just override those entities in your own app and add the attributes to it. Or what you could also do is in the frontend template have a mapping `shippingMethodCode => image-url` and then render the image next to the option with the given code.

**Comment by ibasaw** [comment]
i know, already do it in one of my project but want it in the core

**Comment by alekseyp** [comment]
@ibasaw do i hear PR is ready?

**Comment by mamazu** [comment]
What you could also do is provide a plugin for the shop that does that. This way only who want those pictures need to install it.
