### ISSUE TITLE
yarn install flatmap-stream error 

### ISSUE THREAD

**Issue by yingjung** [Sylius/Sylius#9982]
yarn version : v1.12.3
and yarn install error:

error https://registry.yarnpkg.com/flatmap-stream/-/flatmap-stream-0.1.1.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by kulczy** [comment]
Hi @yingjung try to update the gulp-livereload package to the newest version `yarn upgrade gulp-livereload@^4.0.1`

**Comment by Konafets** [comment]
Update Sylius to latest version via `composer update` and then do a `yarn upgrade`.

**Comment by Zales0123** [comment]
Hello @yingjung, did this answers helped you? :) If yes, please close this issue. Thanks!

**Comment by yingjung** [comment]
yes， thank you very much!
