### ISSUE TITLE
[Roadmap] Filter promotions by state

### ISSUE THREAD

**Issue by ping86** [Sylius/Sylius#9989]
When you have a large list of promotions its very difficult search the active promotions. Would be great, filter promotions by activated/unactivated.

In our ecommerce we have more than 100 old promotions and we have a problem in determine the promotions actived. 

Thanks.

**Comment by mamazu** [comment]
Active promotions are defined by not having a specific start and end date or an end date in the past?

**Comment by ping86** [comment]
Yes but Sylius dont have filters with this specification. Only filter by promotion name and code.

**Comment by mamazu** [comment]
I just looked into it and it seems easy. You need to define a Filter type and then register it in the `sylius.form_registry.grid_filter` service and then use it in the promition grid.

**Comment by ping86** [comment]
Thank You for your advice. I think this filter should be in the default admin backend to improve admin's experience. 

I think actual filters in promotion page is not useful, and this feature can improve this page. For this reason I suggest this feature to roadmap.

Thanks :)

**Comment by mamazu** [comment]
If you need help with it just ask I have already done it in my sylius.

**Comment by mamazu** [comment]
True but it is not hard to implement.
