### ISSUE TITLE
European shop rules

### ISSUE THREAD

**Issue by Prometee** [Sylius/Sylius#9991]
Maybe other people will face the fact we have to handle EU rules in our shop. We could build a Sylius Plugin to get all the generic things like VAT rate rules, VAT rates, VAT number check (syntax+EU WebService).

We can use this ticket to list all those rules.

I put here the rules I have to build into Sylius to sell **softwares** from France to the world :
⚠️ I'm not 100% sure about those rules, correct me if I'm wrong.

**From French seller to a French customer :**
- you have to apply the standard taxe rate (eg: 20%)
- if he has a valid VAT number, he have to pay the VAT.

**From French seller to an EU customer (but not French)**
- you have to apply the standard taxe rate (eg: 20%)
- if he has a valid VAT number, taxe could be set to 0%

**From French seller to a *non* EU customer**
- you have to apply the zero taxe rate (eg: 0%)
- he can't have a VAT number outside EU.

Found an old related issue : #8047

**Comment by mamazu** [comment]
Sounds like a great idea. I think building this plugin will be a hard job because every country has their own crazy rules about taxes. I looks interesting and curious on how you would implement it (as a dynamic thing or as a whole bunch of fixtures)

**Comment by Prometee** [comment]
Rules are mainly about product types, so some configurations have to be made by the administrators. But I was thinking about global rules with only inputs like order country address and tax rates. Then we can provide some generic yaml fixtures to handle specific cases country by country and product type by product type.

**Comment by mamazu** [comment]
That would be awesome. Good luck with that.

**Comment by cefuroX** [comment]
It's actually not that problematic. There is an VAT Check from the EU commision:
http://ec.europa.eu/taxation_customs/vies/
And an SOAP API for that. What you have todo is to extend the OrderItemsTaxesApplicator :) I already did that but can't publish the code yet :P

**Comment by Prometee** [comment]
I already make it :
 - the webservice consumer : https://github.com/Prometee/VIESClient
 - the validator : https://github.com/Prometee/VIESClientBundle

**Comment by prigal** [comment]
> I already make it :
> 
> * the webservice consumer : https://github.com/Prometee/VIESClient
> * the validator : https://github.com/Prometee/VIESClientBundle

Thx, we will probably use it soon.

About main discussion, maybe plugin should only be about VATChecking in checkout and force VAT to 0% as long as all other use cases are "only" some zone/tax/productCategories configurations. That can be tricky, but it's doable, and I agree with @mamazu, all countries have their own crazy rules.

NB : You also have this kind of rule to handle : use french tax when delivering to belgium if you deliver less than 30K€ a year, use belgium tax if it's above. _(countries and limits may be wrong, but this kind of rule exist)_

**Comment by coderiekelt** [comment]
> NB : You also have this kind of rule to handle : use french tax when delivering to belgium if you deliver less than 30K€ a year, use belgium tax if it's above. (countries and limits may be wrong, but this kind of rule exist)

This is not actually all that hard to implement, I faced this problem myself and added a field "borderAmount" to the TaxRate entity and basically calculate that and open-sourced-ish it albeit a bit hacky, in Dutch this tax is called ICP hence the name IcpCalculator: https://gist.github.com/coderiekelt/0e941352a2a72aabb4dbaffd9da6027b

It is indeed true that within Europe you are allowed to sell goods and services for your local VAT rates until a certain amount e.g. in Germany 100k EUR, after that you calculate local VAT rates for your customer.

It would be very nice to see something like this intergrated in Sylius.

**Comment by Prometee** [comment]
I just release the first version SyliusVIESClientBundle it allow us to add VAT Number field to the address during the checkout and to see it across all Sylius interfaces.

[https://github.com/Prometee/SyliusVIESClientPlugin](https://github.com/Prometee/SyliusVIESClientPlugin)

It not finished yet, but I use it for staging project right now. It maybe need some more detailed documentation (especially if you already have `Channel` or `Address` entities in your `src/Entity` folder) and some Behat tests... But it works on latest Sylius release with sf4.2.

**Comment by Prometee** [comment]
There is a list of all European thresholds by country : https://www.simplyvat.com/wp-content/uploads/2013/12/VAT-Registration-Thresholds_January-2016.pdf

But maybe some values has been updated since 1st January 2016...

**Comment by stefandoorn** [comment]
As far as I understand it's not only the year in which you exceed the threshold, but automatically also the next year. If you stay under the threshold again that year, it will be stopped the year after.

**Comment by Prometee** [comment]
There will be also a computation cost for medium/large e-commerce stores doing this threshold checking on every checkout.
Also you are not required to only pay when you are above the threshold. I don't see any rules avoiding to pay those countries VAT before reaching the limits (but maybe I'm wrong).

So if we have to build it we have to make an `Entity` storing those threshold by country. And make a `SUM()` on every `OrderInterface::STATE_FULFILLED` orders to update this `Entity`. Also we can let the admins edit threshold(`@Gedmo\Versioned()`) and sum by country, to be able to reset it or just manually edit it.
