### ISSUE TITLE
how to send email in an hour or two hours?

### ISSUE THREAD

**Issue by LusenkoSasha** [Sylius/Sylius#9992]
How send emails with delay?

**Comment by Roshyo** [comment]
This question would rather be in slack, but anyway.
I'd say : create a spool in database (new entity ans so on), with a send date, and then make a cron job that will send every email that has to be sent.

**Comment by jacquesbh** [comment]
You can also use a RabbitMQ instance with a delay on the messages.
But the cronjob is probably easier.

**Comment by Zales0123** [comment]
Hello Sasha, as @Roshyo said, **Sylius** issues should be used to report bugs, propose new features, discuss new functionalities. For everything else, please, use our Slack or [stackoverflow](https://stackoverflow.com/questions/tagged/sylius) ;)
