### ISSUE TITLE
Product autocomplete in product associations is loading forever

### ISSUE THREAD

**Issue by andychan94** [Sylius/Sylius#9996]
**Sylius version affected**: 1.3.2

**Description**  
When adding a product, ajax product search fails.

**Steps to reproduce**  
I have around 40 products. I also have 2 association types. I have been using these associations on every product, When I am adding a new product now, and want to add associations to it, the ajax keeps failing or if I am lucky it takes 20-25 minutes to load the list of products. When I check the ajax link, I can see that each product is serialized, product object loads with its associated products which load with their associated products, which load with their associated products etc.

I saw another issue related to this, but I do not think it was resolved. Is there anything I can do to fix this?

**Comment by mamazu** [comment]
You could override the product controller and change the JSON rendering or look at or have a look at the FOSViewHandler for a quick fix.

**Comment by Soonz** [comment]
Not fixed yet, I have the same issue.

**Comment by vvasiloi** [comment]
WDYT about a dedicated endpoint for product autocomplete which will only return the relevant data: code and name?
This should solve the issue and also lower the response time.

**Comment by andychan94** [comment]
@Soonz I actually fixed it by following this:
https://github.com/Sylius/Sylius/issues/9364#issuecomment-455113939
